In [ ]:
%pip install -U \
  "autogluon.timeseries==1.5.0" \
  "torch>=2.6.0" \
  "torchvision>=0.21.0" \
  "torchaudio>=2.6.0" \
  "transformers>=4.48.0" \
  "tokenizers>=0.21.0" \
  "numpy==1.26.4"

Requirement already satisfied: autogluon.timeseries==1.5.0 in /usr/local/lib/python3.12/dist-packages (1.5.0)
Collecting torch>=2.6.0
  Downloading torch-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting torchvision>=0.21.0
  Downloading torchvision-0.26.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting torchaudio>=2.6.0
  Downloading torchaudio-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Requirement already satisfied: transformers>=4.48.0 in /usr/local/lib/python3.12/dist-packages (4.57.6)
Collecting transformers>=4.48.0
  Downloading transformers-5.8.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: tokenizers>=0.21.0 in /usr/local/lib/python3.12/dist-packages (0.22.2)
Collecting tokenizers>=0.21.0
  Downloading tokenizers-0.23.1-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.8 kB)
Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (1.5.3)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (1.16.3)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (2.2.2)
Collecting torch>=2.6.0
  Using cached torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: lightning<2.6,>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (2.5.6)
Requirement already satisfied: accelerate<2.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (1.13.0)
Requirement already satisfied: gluonts<0.17,>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (0.16.2)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (3.6.1)
Requirement already satisfied: statsforecast<2.0.2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (2.0.1)
Requirement already satisfied: mlforecast<0.15.0,>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (0.14.0)
Requirement already satisfied: utilsforecast<0.2.12,>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (0.2.11)
Requirement already satisfied: coreforecast<0.0.17,>=0.0.12 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (0.0.16)
Requirement already satisfied: fugue>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (0.9.7)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (4.67.3)
Requirement already satisfied: orjson~=3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (3.11.8)
Requirement already satisfied: einops<1,>=0.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (0.8.2)
Requirement already satisfied: chronos-forecasting<2.4,>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (2.2.2)
Requirement already satisfied: peft<0.18,>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (0.17.1)
Requirement already satisfied: tensorboard<3,>=2.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (2.20.0)
Requirement already satisfied: autogluon.core==1.5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (1.5.0)
Requirement already satisfied: autogluon.common==1.5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (1.5.0)
Requirement already satisfied: autogluon.features==1.5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0) (1.5.0)
Requirement already satisfied: autogluon.tabular==1.5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (1.5.0)
Requirement already satisfied: pyarrow<21.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (18.1.0)
Requirement already satisfied: boto3<2,>=1.10 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (1.43.6)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (5.9.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (2.32.4)
Requirement already satisfied: pyyaml>=5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (6.0.3)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (1.6.1)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (3.10.0)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (4.6.0)
Requirement already satisfied: catboost<1.3,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (1.2.10)
Requirement already satisfied: xgboost<3.2,>=2.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (3.1.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (2025.3.0)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch>=2.6.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch>=2.6.0)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch>=2.6.0)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch>=2.6.0)
  Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch>=2.6.0)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch>=2.6.0)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch>=2.6.0)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch>=2.6.0)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch>=2.6.0)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (0.7.1)
Collecting nvidia-nccl-cu12==2.27.5 (from torch>=2.6.0)
  Downloading nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (3.3.20)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch>=2.6.0)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.6.0) (3.5.1)
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchvision>=0.21.0
  Downloading torchvision-0.25.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision>=0.21.0) (11.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.36.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (26.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (2025.11.3)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.7.0)
Requirement already satisfied: triad>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from fugue>=0.9.0->autogluon.timeseries==1.5.0) (1.0.2)
Requirement already satisfied: adagio>=0.2.6 in /usr/local/lib/python3.12/dist-packages (from fugue>=0.9.0->autogluon.timeseries==1.5.0) (0.2.6)
Requirement already satisfied: pydantic<3,>=1.7 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0) (2.12.3)
Requirement already satisfied: toolz~=0.10 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0) (0.12.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers>=4.48.0) (1.4.3)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (0.15.3)
Requirement already satisfied: torchmetrics<3.0,>0.7.0 in /usr/local/lib/python3.12/dist-packages (from lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (1.9.0)
Requirement already satisfied: pytorch-lightning in /usr/local/lib/python3.12/dist-packages (from lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (2.6.1)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (3.1.2)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (0.60.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (4.8.0)
Requirement already satisfied: window-ops in /usr/local/lib/python3.12/dist-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (0.0.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.timeseries==1.5.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.timeseries==1.5.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.timeseries==1.5.0) (2026.1)
Requirement already satisfied: statsmodels>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from statsforecast<2.0.2,>=1.7.0->autogluon.timeseries==1.5.0) (0.14.6)
Requirement already satisfied: threadpoolctl>=3 in /usr/local/lib/python3.12/dist-packages (from statsforecast<2.0.2,>=1.7.0->autogluon.timeseries==1.5.0) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.6.0) (1.3.0)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.12/dist-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.12/dist-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (3.10.2)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.12/dist-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (5.29.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (3.1.8)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]<4.58,>=4.51.0->autogluon.timeseries==1.5.0) (0.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.6.0) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (2026.4.22)
Requirement already satisfied: botocore<1.44.0,>=1.43.6 in /usr/local/lib/python3.12/dist-packages (from boto3<2,>=1.10->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (1.43.6)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3<2,>=1.10->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (1.1.0)
Requirement already satisfied: s3transfer<0.18.0,>=0.17.0 in /usr/local/lib/python3.12/dist-packages (from boto3<2,>=1.10->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (0.17.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (1.17.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<2027.0,>=2022.5.0->lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (3.13.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (3.3.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (0.43.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.7->gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.7->gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.7->gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0) (0.4.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.2->statsforecast<2.0.2,>=1.7.0->autogluon.timeseries==1.5.0) (1.0.2)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (2.0.49)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2027.0,>=2022.5.0->lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2027.0,>=2022.5.0->lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2027.0,>=2022.5.0->lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2027.0,>=2022.5.0->lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2027.0,>=2022.5.0->lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2027.0,>=2022.5.0->lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (0.4.1)

In [3]:
import torch
import pandas as pd
import numpy as np
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
from sklearn.metrics import r2_score,mean_squared_error

In [4]:
df = pd.read_csv("../data/training/bitola_final_data.csv")
df.head()

,timestamp,sensorId,city,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,...,neighbor2_wind_speed,neighbor3_wind_speed,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
0,2023-12-01 00:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,58.333333,28.333333,13.666667,943.0,12.00,8.3,63.645833,...,8.3,6.98,0.000000,1.000000,-0.5,0.866025,-0.433884,-0.900969,0,1
1,2023-12-01 01:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.250000,13.750000,5.000000,943.0,12.00,9.3,64.750000,...,9.3,7.50,0.258819,0.965926,-0.5,0.866025,-0.433884,-0.900969,0,1
2,2023-12-01 02:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,60.000000,10.000000,4.500000,942.5,12.25,8.3,65.312500,...,8.3,6.74,0.500000,0.866025,-0.5,0.866025,-0.433884,-0.900969,0,1
3,2023-12-01 03:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.250000,9.750000,4.500000,942.0,13.00,9.4,64.854167,...,9.4,7.84,0.707107,0.707107,-0.5,0.866025,-0.433884,-0.900969,0,1
4,2023-12-01 04:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.500000,5.000000,2.000000,942.0,13.00,9.0,65.062500,...,9.0,8.32,0.866025,0.500000,-0.5,0.866025,-0.433884,-0.900969,0,1

In [5]:
df.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor1_pressure,...,neighbor2_wind_speed,neighbor3_wind_speed,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
count,192984.000000,149772.000000,149781.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,...,192984.000000,192984.000000,1.929840e+05,1.929840e+05,192984.000000,1.929840e+05,192984.000000,192984.000000,192984.000000,192984.000000
mean,52.712150,26.860537,14.470625,939.805608,16.794952,6.075046,52.241040,53.628155,51.232897,943.015291,...,6.173400,6.157256,-1.845999e-17,-5.550655e-17,-0.002785,-3.554140e-03,-0.002997,-0.000684,0.287278,0.414501
std,15.722700,49.673873,26.783313,12.797334,9.158462,3.743378,15.767958,16.392558,15.040098,6.651617,...,3.865857,3.848838,7.071086e-01,7.071086e-01,0.706861,7.073415e-01,0.707344,0.706866,0.452493,0.492637
min,9.500000,0.000000,0.000000,869.000000,-12.000000,0.000000,9.500000,9.500000,9.500000,911.000000,...,0.000000,0.000000,-1.000000e+00,-1.000000e+00,-1.000000,-1.000000e+00,-0.974928,-0.900969,0.000000,0.000000
25%,40.759259,5.333333,2.333333,937.000000,9.694444,3.500000,40.466667,41.333333,39.750000,939.000000,...,3.500000,3.500000,-7.071068e-01,-7.071068e-01,-0.500000,-8.660254e-01,-0.781831,-0.900969,0.000000,0.000000
50%,53.604167,11.000000,5.750000,942.000000,16.000000,5.300000,53.000000,54.495833,52.250000,943.000000,...,5.400000,5.400000,6.123234e-17,-6.123234e-17,0.000000,-1.836970e-16,0.000000,-0.222521,0.000000,0.000000
75%,64.850000,27.000000,14.500000,946.000000,23.750000,7.740000,64.250000,66.000000,63.000000,947.000000,...,7.900000,7.900000,7.071068e-01,7.071068e-01,0.866025,5.000000e-01,0.781831,0.623490,1.000000,1.000000
max,99.000000,1995.000000,639.250000,971.750000,47.500000,32.800000,99.000000,99.000000,86.750000,971.750000,...,32.800000,32.800000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,0.974928,1.000000,1.000000,1.000000

In [6]:
len(df)

192984

In [7]:
df['sensorId'].value_counts()

sensorId
16836a55-7140-43e2-9a63-56fac5cba714    17544
2002                                    17544
23b735ef-a996-4a7f-9998-2aa7e78827b0    17544
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    17544
40f081a6-4095-43f7-bffb-64e2af8c026e    17544
7b316592-8036-41e2-b8dc-b06b6a9afd54    17544
874ff9c6-786d-45fc-a90e-48c7ffe03417    17544
87f82783-853b-417d-8964-b5cf11e44873    17544
d241a044-0a06-40c2-9d90-c91fd0a95060    17544
d7060523-b163-4cc3-bc94-970dac72a38a    17544
fec52a19-9148-4350-a1b4-ae0da05ee199    17544
Name: count, dtype: int64

In [8]:
df = df.drop(columns=['city'],axis=1)

In [9]:
TARGET = 'pm10'
ID_COL = 'sensorId'
TIME_COL = 'timestamp'
PREDICTION_LENGTH = 512

In [10]:
df[TIME_COL] = pd.to_datetime(df[TIME_COL])

In [11]:
df[TIME_COL] = df[TIME_COL].dt.tz_convert(None)

In [12]:
print(df["timestamp"].dtype)

datetime64[ns]

In [13]:
def clean_outliers_spatiotemporal(df, target_col='pm10', window_size=4, threshold=2.5):

    df = df.sort_values('timestamp')

    rolling_stats = df.set_index('timestamp')[target_col].rolling(window=f'{window_size}h')

    global_rolling_mean = rolling_stats.mean().reset_index(drop=True)
    global_rolling_std = rolling_stats.std().reset_index(drop=True)


    z_scores = (df[target_col] - global_rolling_mean) / (global_rolling_std + 1e-6)

    df[target_col] = df[target_col].mask(z_scores.abs() > threshold, global_rolling_mean)

    return df

In [14]:
df = clean_outliers_spatiotemporal(df)

In [15]:
df.describe()

,timestamp,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,...,neighbor2_wind_speed,neighbor3_wind_speed,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
count,192984,192984.000000,149772.000000,149781.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,...,192984.000000,192984.000000,1.929840e+05,1.929840e+05,192984.000000,1.929840e+05,192984.000000,192984.000000,192984.000000,192984.000000
mean,2024-11-30 11:30:00,52.712150,15.646266,14.470625,939.805608,16.794952,6.075046,52.241040,53.628155,51.232897,...,6.173400,6.157256,-1.892483e-17,-5.550425e-17,-0.002785,-3.554140e-03,-0.002997,-0.000684,0.287278,0.414501
min,2023-12-01 00:00:00,9.500000,0.000000,0.000000,869.000000,-12.000000,0.000000,9.500000,9.500000,9.500000,...,0.000000,0.000000,-1.000000e+00,-1.000000e+00,-1.000000,-1.000000e+00,-0.974928,-0.900969,0.000000,0.000000
25%,2024-05-31 17:45:00,40.759259,5.250000,2.333333,937.000000,9.694444,3.500000,40.466667,41.333333,39.750000,...,3.500000,3.500000,-7.071068e-01,-7.071068e-01,-0.500000,-8.660254e-01,-0.781831,-0.900969,0.000000,0.000000
50%,2024-11-30 11:30:00,53.604167,9.584007,5.750000,942.000000,16.000000,5.300000,53.000000,54.495833,52.250000,...,5.400000,5.400000,6.123234e-17,-6.123234e-17,0.000000,-1.836970e-16,0.000000,-0.222521,0.000000,0.000000
75%,2025-06-01 05:15:00,64.850000,19.000000,14.500000,946.000000,23.750000,7.740000,64.250000,66.000000,63.000000,...,7.900000,7.900000,7.071068e-01,7.071068e-01,0.866025,5.000000e-01,0.781831,0.623490,1.000000,1.000000
max,2025-11-30 23:00:00,99.000000,507.500000,639.250000,971.750000,47.500000,32.800000,99.000000,99.000000,86.750000,...,32.800000,32.800000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,0.974928,1.000000,1.000000,1.000000
std,NaN,15.722700,19.536842,26.783313,12.797334,9.158462,3.743378,15.767958,16.392558,15.040098,...,3.865857,3.848838,7.071086e-01,7.071086e-01,0.706861,7.073415e-01,0.707344,0.706866,0.452493,0.492637

In [16]:
data = TimeSeriesDataFrame.from_data_frame(
    df,
    id_column=ID_COL,
    timestamp_column=TIME_COL
)

In [17]:
data.columns

Index(['humidity', 'pm10', 'pm25', 'pressure', 'temperature', 'wind_speed',
       'neighbor1_humidity', 'neighbor2_humidity', 'neighbor3_humidity',
       'neighbor1_pressure', 'neighbor2_pressure', 'neighbor3_pressure',
       'neighbor1_temperature', 'neighbor2_temperature',
       'neighbor3_temperature', 'neighbor1_wind_speed', 'neighbor2_wind_speed',
       'neighbor3_wind_speed', 'hour_sin', 'hour_cos', 'month_sin',
       'month_cos', 'day_sin', 'day_cos', 'is_weekend', 'is_heating_season'],
      dtype='object')

In [18]:
train_data, test_data = data.train_test_split(prediction_length=PREDICTION_LENGTH)

Sorting the dataframe index before generating the train/test split.

In [19]:
predictor = TimeSeriesPredictor(
    target= TARGET,
    prediction_length=PREDICTION_LENGTH,
    eval_metric="MASE",
)

In [ ]:
predictor.fit(
    train_data,
    presets="chronos2",   # or "chronos2_small" for faster training
    time_limit=300
    verbosity=2
)

Beginning AutoGluon training... Time limit = 300s
AutoGluon will save models to '/mnt/c/Users/RazorVision/Desktop/project-vrnmp/offline-Phase/AutogluonModels/ag-20260516_180221'
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025
CPU Count:          16
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 12.00/12.00 GB
Total GPU Memory:   Free: 12.00 GB, Allocated: 0.00 GB, Total: 12.00 GB
GPU Count:          1
Memory Avail:       10.35 GB / 15.58 GB (66.4%)
Disk Space Avail:   72.70 GB / 464.89 GB (15.6%)
===================================================
Setting presets to: chronos2

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': MASE,
 'hyperparameters': {'Chronos2': {'model_path': 'autogluon/chronos-2'}},
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 512,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': True,
 'target': 'pm10',
 'time_limit': 300,
 'verbosity': 2}

Inferred time series frequency: 'h'
Provided train_data has 187352 rows (NaN fraction=23.0%), 11 time series. Median time series length is 17032 (min=17032, max=17032).

Provided data contains following columns:
	target: 'pm10'
	past_covariates:
		categorical:        []
		continuous (float): ['humidity', 'pm25', 'pressure', 'temperature', 'wind_speed', 'neighbor1_humidity', ...]

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'MASE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-05-16 20:02:24
Models that will be trained: ['Chronos2']
Training timeseries model Chronos2. Training for up to 299.4s of the 299.4s of remaining time.

KeyboardInterrupt:

In [19]:
predictions = predictor.predict(train_data)

Model not specified in predict, will default to the model with the best validation score: Chronos2

In [20]:
print(predictions.head())

                                                               mean  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  34.817322
                                     2025-11-09 17:00:00  37.246620
                                     2025-11-09 18:00:00  33.631908
                                     2025-11-09 19:00:00  30.262213
                                     2025-11-09 20:00:00  28.418341

                                                                0.1  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  24.643730
                                     2025-11-09 17:00:00  24.688066
                                     2025-11-09 18:00:00  21.267815
                                     2025-11-09 19:00:00  18.245241
                                     2025-11-09 20:00:00  16.805607

                                                                0.2  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  28.304302
                                     2025-11-09 17:00:00  29.124779
                                     2025-11-09 18:00:00  25.714237
                                     2025-11-09 19:00:00  22.383482
                                     2025-11-09 20:00:00  20.843494

                                                                0.3  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  30.755257
                                     2025-11-09 17:00:00  32.212463
                                     2025-11-09 18:00:00  28.829346
                                     2025-11-09 19:00:00  25.418211
                                     2025-11-09 20:00:00  23.668449

                                                                0.4  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  32.833778
                                     2025-11-09 17:00:00  34.800514
                                     2025-11-09 18:00:00  31.345150
                                     2025-11-09 19:00:00  27.942680
                                     2025-11-09 20:00:00  26.072624

                                                                0.5  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  34.817322
                                     2025-11-09 17:00:00  37.246620
                                     2025-11-09 18:00:00  33.631908
                                     2025-11-09 19:00:00  30.262213
                                     2025-11-09 20:00:00  28.418341

                                                                0.6  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  36.837559
                                     2025-11-09 17:00:00  39.689880
                                     2025-11-09 18:00:00  36.036194
                                     2025-11-09 19:00:00  32.560177
                                     2025-11-09 20:00:00  30.810600

                                                                0.7  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  38.924889
                                     2025-11-09 17:00:00  42.182610
                                     2025-11-09 18:00:00  38.692726
                                     2025-11-09 19:00:00  35.009804
                                     2025-11-09 20:00:00  33.332882

                                                                0.8        0.9
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  41.498207  45.576256
                                     2025-11-09 17:00:00  45.446686  50.341003
                                     2025-11-09 18:00:00  42.261742  47.601219
                                     2025-11-09 19:00:00  38.256641  43.492355
                                     2025-11-09 20:00:00  36.665897  42.076488

In [21]:
performance = predictor.evaluate(test_data)

print(performance)

Model not specified in predict, will default to the model with the best validation score: Chronos2

{'MASE': -1.0510433854216212}

In [22]:
test_df = test_data.to_data_frame()
pred_df = predictions.to_data_frame()

In [23]:
merged = test_df.merge(
    pred_df[["mean"]],
    on=["item_id", "timestamp"],
    how="inner"
)

In [24]:
merged.columns

Index(['humidity', 'pm10', 'pm25', 'pressure', 'temperature', 'wind_speed',
       'neighbor1_humidity', 'neighbor2_humidity', 'neighbor3_humidity',
       'neighbor1_pressure', 'neighbor2_pressure', 'neighbor3_pressure',
       'neighbor1_temperature', 'neighbor2_temperature',
       'neighbor3_temperature', 'neighbor1_wind_speed', 'neighbor2_wind_speed',
       'neighbor3_wind_speed', 'hour_sin', 'hour_cos', 'month_sin',
       'month_cos', 'day_sin', 'day_cos', 'is_weekend', 'is_heating_season',
       'mean'],
      dtype='object')

In [25]:
merged = merged.rename(columns={"mean": "predicted"})

In [26]:
merged

                                                          humidity       pm10  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00     71.25  44.500000
                                     2025-11-09 17:00:00     72.00  32.333333
                                     2025-11-09 18:00:00     73.00  26.750000
                                     2025-11-09 19:00:00     73.75  10.500000
                                     2025-11-09 20:00:00     73.25   9.500000
...                                                            ...        ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00     61.75  11.250000
                                     2025-11-30 20:00:00     63.25   9.000000
                                     2025-11-30 21:00:00     63.50  12.000000
                                     2025-11-30 22:00:00     63.75   3.250000
                                     2025-11-30 23:00:00     63.75   1.750000

                                                               pm25  pressure  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  29.750000    944.00
                                     2025-11-09 17:00:00  20.666667    944.00
                                     2025-11-09 18:00:00  16.750000    944.25
                                     2025-11-09 19:00:00   6.250000    945.00
                                     2025-11-09 20:00:00   6.250000    945.00
...                                                             ...       ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00   6.000000    942.00
                                     2025-11-30 20:00:00   5.666667    942.00
                                     2025-11-30 21:00:00   6.000000    942.50
                                     2025-11-30 22:00:00   2.500000    943.00
                                     2025-11-30 23:00:00   0.750000    943.00

                                                          temperature  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00        16.00
                                     2025-11-09 17:00:00        16.00
                                     2025-11-09 18:00:00        15.75
                                     2025-11-09 19:00:00        15.00
                                     2025-11-09 20:00:00        15.00
...                                                               ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00         9.00
                                     2025-11-30 20:00:00         9.00
                                     2025-11-30 21:00:00         8.25
                                     2025-11-30 22:00:00         7.75
                                     2025-11-30 23:00:00         7.00

                                                          wind_speed  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00         5.1
                                     2025-11-09 17:00:00         5.6
                                     2025-11-09 18:00:00         1.5
                                     2025-11-09 19:00:00         4.5
                                     2025-11-09 20:00:00         4.0
...                                                              ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00         5.9
                                     2025-11-30 20:00:00         5.7
                                     2025-11-30 21:00:00         5.8
                                     2025-11-30 22:00:00         5.6
                                     2025-11-30 23:00:00         6.2

                                                          neighbor1_humidity  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00           68.250000
                                     2025-11-09 17:00:00           70.250000
                                     2025-11-09 18:00:00           70.500000
                                     2025-11-09 19:00:00           71.000000
                                     2025-11-09 20:00:00           71.666667
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00           63.500000
                                     2025-11-30 20:00:00           63.750000
                                     2025-11-30 21:00:00           63.333333
                                     2025-11-30 22:00:00           63.750000
                                     2025-11-30 23:00:00           64.000000

                                                          neighbor2_humidity  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00           74.116667
                                     2025-11-09 17:00:00           75.301667
                                     2025-11-09 18:00:00           76.353333
                                     2025-11-09 19:00:00           76.920476
                                     2025-11-09 20:00:00           74.636243
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00           86.500000
                                     2025-11-30 20:00:00           90.500000
                                     2025-11-30 21:00:00           94.333333
                                     2025-11-30 22:00:00           98.000000
                                     2025-11-30 23:00:00           98.000000

                                                          neighbor3_humidity  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00           69.500000
                                     2025-11-09 17:00:00           72.000000
                                     2025-11-09 18:00:00           73.750000
                                     2025-11-09 19:00:00           75.000000
                                     2025-11-09 20:00:00           75.500000
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00           68.583333
                                     2025-11-30 20:00:00           69.333333
                                     2025-11-30 21:00:00           70.425926
                                     2025-11-30 22:00:00           70.888889
                                     2025-11-30 23:00:00           71.472222

                                                          neighbor1_pressure  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00              944.00
                                     2025-11-09 17:00:00              944.00
                                     2025-11-09 18:00:00              944.00
                                     2025-11-09 19:00:00              944.00
                                     2025-11-09 20:00:00              944.00
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00              942.25
                                     2025-11-30 20:00:00              943.00
                                     2025-11-30 21:00:00              943.00
                                     2025-11-30 22:00:00              943.00
                                     2025-11-30 23:00:00              943.25

                                                          ...  \
item_id                              timestamp            ...
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  ...
                                     2025-11-09 17:00:00  ...
                                     2025-11-09 18:00:00  ...
                                     2025-11-09 19:00:00  ...
                                     2025-11-09 20:00:00  ...
...                                                       ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00  ...
                                     2025-11-30 20:00:00  ...
                                     2025-11-30 21:00:00  ...
                                     2025-11-30 22:00:00  ...
                                     2025-11-30 23:00:00  ...

                                                          neighbor3_wind_speed  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00                   5.1
                                     2025-11-09 17:00:00                   5.6
                                     2025-11-09 18:00:00                   1.5
                                     2025-11-09 19:00:00                   4.5
                                     2025-11-09 20:00:00                   4.0
...                                                                        ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00                   5.3
                                     2025-11-30 20:00:00                   5.4
                                     2025-11-30 21:00:00                   5.4
                                     2025-11-30 22:00:00                   5.0
                                     2025-11-30 23:00:00                   4.9

                                                          hour_sin  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00 -0.866025
                                     2025-11-09 17:00:00 -0.965926
                                     2025-11-09 18:00:00 -1.000000
                                     2025-11-09 19:00:00 -0.965926
                                     2025-11-09 20:00:00 -0.866025
...                                                            ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00 -0.965926
                                     2025-11-30 20:00:00 -0.866025
                                     2025-11-30 21:00:00 -0.707107
                                     2025-11-30 22:00:00 -0.500000
                                     2025-11-30 23:00:00 -0.258819

                                                              hour_cos  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00 -5.000000e-01
                                     2025-11-09 17:00:00 -2.588190e-01
                                     2025-11-09 18:00:00 -1.836970e-16
                                     2025-11-09 19:00:00  2.588190e-01
                                     2025-11-09 20:00:00  5.000000e-01
...                                                                ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00  2.588190e-01
                                     2025-11-30 20:00:00  5.000000e-01
                                     2025-11-30 21:00:00  7.071068e-01
                                     2025-11-30 22:00:00  8.660254e-01
                                     2025-11-30 23:00:00  9.659258e-01

                                                          month_sin  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  -0.866025
                                     2025-11-09 17:00:00  -0.866025
                                     2025-11-09 18:00:00  -0.866025
                                     2025-11-09 19:00:00  -0.866025
                                     2025-11-09 20:00:00  -0.866025
...                                                             ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00  -0.866025
                                     2025-11-30 20:00:00  -0.866025
                                     2025-11-30 21:00:00  -0.866025
                                     2025-11-30 22:00:00  -0.866025
                                     2025-11-30 23:00:00  -0.866025

                                                          month_cos   day_sin  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00        0.5 -0.781831
                                     2025-11-09 17:00:00        0.5 -0.781831
                                     2025-11-09 18:00:00        0.5 -0.781831
                                     2025-11-09 19:00:00        0.5 -0.781831
                                     2025-11-09 20:00:00        0.5 -0.781831
...                                                             ...       ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00        0.5 -0.781831
                                     2025-11-30 20:00:00        0.5 -0.781831
                                     2025-11-30 21:00:00        0.5 -0.781831
                                     2025-11-30 22:00:00        0.5 -0.781831
                                     2025-11-30 23:00:00        0.5 -0.781831

                                                          day_cos  is_weekend  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  0.62349           1
                                     2025-11-09 17:00:00  0.62349           1
                                     2025-11-09 18:00:00  0.62349           1
                                     2025-11-09 19:00:00  0.62349           1
                                     2025-11-09 20:00:00  0.62349           1
...                                                           ...         ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00  0.62349           1
                                     2025-11-30 20:00:00  0.62349           1
                                     2025-11-30 21:00:00  0.62349           1
                                     2025-11-30 22:00:00  0.62349           1
                                     2025-11-30 23:00:00  0.62349           1

                                                          is_heating_season  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00                  1
                                     2025-11-09 17:00:00                  1
                                     2025-11-09 18:00:00                  1
                                     2025-11-09 19:00:00                  1
                                     2025-11-09 20:00:00                  1
...                                                                     ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00                  1
                                     2025-11-30 20:00:00                  1
                                     2025-11-30 21:00:00                  1
                                     2025-11-30 22:00:00                  1
                                     2025-11-30 23:00:00                  1

                                                          predicted
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  34.817322
                                     2025-11-09 17:00:00  37.246620
                                     2025-11-09 18:00:00  33.631908
                                     2025-11-09 19:00:00  30.262213
                                     2025-11-09 20:00:00  28.418341
...                                                             ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00   9.002959
                                     2025-11-30 20:00:00   7.725951
                                     2025-11-30 21:00:00   6.447699
                                     2025-11-30 22:00:00   5.375382
                                     2025-11-30 23:00:00   4.694675

[5632 rows x 27 columns]

In [27]:
merged.dropna(inplace=True)

In [28]:
y_true = merged["pm10"]
y_pred = merged["predicted"]

r2_global = r2_score(y_true, y_pred)
rmse_global = np.sqrt(mean_squared_error(y_true, y_pred))

print("Global R2:", r2_global)
print("Global RMSE:", rmse_global)

Global R2: 0.3080617372218424
Global RMSE: 14.770893507764018

In [29]:
per_sensor = merged.groupby("item_id").apply(
    lambda df: pd.Series({
        "r2": r2_score(df["pm10"], df["predicted"]),
        "rmse": np.sqrt(mean_squared_error(df["pm10"], df["predicted"]))
    })
)

print(per_sensor)

                                            r2       rmse
item_id
16836a55-7140-43e2-9a63-56fac5cba714  0.060030  19.696621
2002                                  0.040868  11.334386
23b735ef-a996-4a7f-9998-2aa7e78827b0 -0.002161   6.526225
2819ecbb-5de3-4092-aa1d-4ba3a8c40add  0.110113   6.960545
40f081a6-4095-43f7-bffb-64e2af8c026e  0.077893  13.782003
7b316592-8036-41e2-b8dc-b06b6a9afd54  0.196434  36.167436
874ff9c6-786d-45fc-a90e-48c7ffe03417  0.131498   9.232803
87f82783-853b-417d-8964-b5cf11e44873 -0.199955   9.288192
d241a044-0a06-40c2-9d90-c91fd0a95060  0.019788   3.705899
d7060523-b163-4cc3-bc94-970dac72a38a  0.041156   8.097631
fec52a19-9148-4350-a1b4-ae0da05ee199  0.113621   5.482459

In [30]:
predictor.path

'/Users/jovan/Documents/Kodovi/RNMP/Project/Offline-Phase/AutogluonModels/ag-20260509_182303'

In [31]:
import shutil

shutil.copytree(
    predictor.path,
    "chronos2_model_pm10_bitola"
)

'chronos2_model_pm10_bitola'