## Data Preprocessing of the Bitola Air Pollution Dataset

In [77]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/training/bitola_features.csv",low_memory=False)

In [3]:
df.head(30)

,sensorId,timestamp,city,co,humidity,no2,o3,pm10,pm25,pressure,...,wind_speed,neighbor_1_pm10,neighbor_1_pm25,neighbor_1_wind_speed,neighbor_2_pm10,neighbor_2_pm25,neighbor_2_wind_speed,neighbor_3_pm10,neighbor_3_pm25,neighbor_3_wind_speed
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T01:13:38+01:00,bitola,NaN,58.0,NaN,NaN,16.0,7.0,943.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T01:29:10+01:00,bitola,NaN,58.0,NaN,NaN,34.0,16.0,943.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T01:44:41+01:00,bitola,NaN,59.0,NaN,NaN,35.0,18.0,943.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T02:00:13+01:00,bitola,NaN,59.0,NaN,NaN,26.0,10.0,943.0,...,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T02:15:45+01:00,bitola,NaN,59.0,NaN,NaN,15.0,7.0,943.0,...,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T02:31:16+01:00,bitola,NaN,60.0,NaN,NaN,5.0,2.0,943.0,...,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T02:46:48+01:00,bitola,NaN,59.0,NaN,NaN,9.0,1.0,943.0,...,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T03:02:20+01:00,bitola,NaN,60.0,NaN,NaN,11.0,6.0,943.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T03:17:52+01:00,bitola,NaN,60.0,NaN,NaN,9.0,3.0,943.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T03:33:23+01:00,bitola,NaN,60.0,NaN,NaN,10.0,5.0,942.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T03:48:55+01:00,bitola,NaN,60.0,NaN,NaN,10.0,4.0,942.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T04:04:27+01:00,bitola,NaN,59.0,NaN,NaN,8.0,4.0,942.0,...,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T04:19:58+01:00,bitola,NaN,59.0,NaN,NaN,13.0,6.0,942.0,...,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T04:35:30+01:00,bitola,NaN,59.0,NaN,NaN,13.0,6.0,942.0,...,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T04:51:01+01:00,bitola,NaN,60.0,NaN,NaN,5.0,2.0,942.0,...,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T05:06:33+01:00,bitola,NaN,60.0,NaN,NaN,5.0,2.0,942.0,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T05:22:05+01:00,bitola,NaN,59.0,NaN,NaN,4.0,1.0,942.0,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T05:37:36+01:00,bitola,NaN,59.0,NaN,NaN,3.0,1.0,942.0,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T05:53:08+01:00,bitola,NaN,60.0,NaN,NaN,8.0,4.0,942.0,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T06:08:40+01:00,bitola,NaN,60.0,NaN,NaN,4.0,2.0,942.0,...,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T06:24:12+01:00,bitola,NaN,60.0,NaN,NaN,16.0,7.0,942.0,...,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T06:39:44+01:00,bitola,NaN,60.0,NaN,NaN,9.0,4.0,942.0,...,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T06:55:16+01:00,bitola,NaN,61.0,NaN,NaN,7.0,3.0,942.0,...,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T07:10:48+01:00,bitola,NaN,60.0,NaN,NaN,3.0,1.0,942.0,...,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T07:26:21+01:00,bitola,NaN,59.0,NaN,NaN,3.0,1.0,942.0,...,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T07:41:52+01:00,bitola,NaN,59.0,NaN,NaN,5.0,3.0,942.0,...,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T07:57:25+01:00,bitola,NaN,58.0,NaN,NaN,21.0,10.0,942.0,...,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T08:12:57+01:00,bitola,NaN,58.0,NaN,NaN,30.0,15.0,943.0,...,12.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T08:28:28+01:00,bitola,NaN,57.0,NaN,NaN,15.0,8.0,943.0,...,12.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T08:44:00+01:00,bitola,NaN,56.0,NaN,NaN,11.0,3.0,943.0,...,12.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.tail(10)

,sensorId,timestamp,city,co,humidity,no2,o3,pm10,pm25,pressure,...,wind_speed,neighbor_1_pm10,neighbor_1_pm25,neighbor_1_wind_speed,neighbor_2_pm10,neighbor_2_pm25,neighbor_2_wind_speed,neighbor_3_pm10,neighbor_3_pm25,neighbor_3_wind_speed
1103349,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:22:38+01:00,bitola,NaN,64.0,NaN,NaN,3.0,2.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103350,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:24:44+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103351,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:38:10+01:00,bitola,NaN,64.0,NaN,NaN,4.0,4.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103352,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:40:16+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103353,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:53:41+01:00,bitola,NaN,64.0,NaN,NaN,3.0,2.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103354,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:55:47+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103355,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-12-01T00:09:13+01:00,bitola,NaN,63.0,NaN,NaN,3.0,1.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103356,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-12-01T00:24:44+01:00,bitola,NaN,64.0,NaN,NaN,0.0,0.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103357,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-12-01T00:40:16+01:00,bitola,NaN,64.0,NaN,NaN,3.0,1.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103358,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-12-01T00:55:47+01:00,bitola,NaN,64.0,NaN,NaN,1.0,1.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.describe()

,co,humidity,no2,o3,pm10,pm25,pressure,temperature,wind_speed,neighbor_1_pm10,neighbor_1_pm25,neighbor_1_wind_speed,neighbor_2_pm10,neighbor_2_pm25,neighbor_2_wind_speed,neighbor_3_pm10,neighbor_3_pm25,neighbor_3_wind_speed
count,24900.000000,508847.000000,25540.000000,21108.000000,526502.000000,538495.000000,510019.000000,510019.000000,562249.000000,213.000000,213.000000,217.000000,183.000000,183.000000,203.000000,297.000000,303.000000,306.000000
mean,0.238514,52.511991,12.215623,39.399754,26.018306,13.641850,939.442499,16.849076,5.973859,32.399061,17.201878,7.502304,29.349727,12.857923,5.952217,23.326599,11.557756,6.343137
std,0.603232,16.208122,12.427257,28.810507,55.757197,28.540954,14.724173,9.174995,3.812610,78.899180,42.788440,4.416860,117.788776,29.968876,3.442575,52.510402,26.146349,3.713277
min,0.000000,8.000000,0.000000,0.000000,0.000000,0.000000,869.000000,-12.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.400000,0.000000,0.000000,0.400000
25%,0.000000,40.000000,3.000000,13.000000,5.000000,2.000000,937.000000,10.000000,3.300000,5.000000,2.000000,4.200000,4.000000,2.000000,3.300000,5.000000,2.500000,4.400000
50%,0.000000,53.000000,8.000000,35.000000,10.000000,5.000000,942.000000,16.000000,5.200000,8.000000,4.000000,6.600000,7.000000,4.000000,5.400000,9.000000,4.000000,5.750000
75%,0.000000,65.000000,17.000000,61.000000,23.000000,12.000000,947.000000,24.000000,7.700000,17.000000,10.000000,10.600000,20.000000,10.500000,8.400000,17.000000,10.000000,7.975000
max,8.000000,99.000000,124.000000,145.000000,1995.000000,998.000000,975.000000,49.000000,32.800000,632.000000,324.000000,23.400000,1519.000000,287.000000,18.300000,457.000000,238.000000,19.800000

In [6]:
len(df)

1103359

In [7]:
percent_missing = (df.isnull().sum() * 100) / len(df)
print(percent_missing)

sensorId                  0.000000
timestamp                 0.000000
city                      0.000000
co                       97.743255
humidity                 53.882009
no2                      97.685250
o3                       98.086933
pm10                     52.281896
pm25                     51.194942
pressure                 53.775788
temperature              53.775788
wind_speed               49.042062
neighbor_1_pm10          99.980695
neighbor_1_pm25          99.980695
neighbor_1_wind_speed    99.980333
neighbor_2_pm10          99.983414
neighbor_2_pm25          99.983414
neighbor_2_wind_speed    99.981602
neighbor_3_pm10          99.973082
neighbor_3_pm25          99.972538
neighbor_3_wind_speed    99.972267
dtype: float64

Since no2,co and o3 along with other features that have missing value percent above 90% will be dropped

In [10]:
df= df.drop(columns=['neighbor_1_pm10','neighbor_2_pm10','neighbor_3_pm10','neighbor_1_pm25','neighbor_2_pm25','neighbor_3_pm25','neighbor_1_wind_speed','neighbor_2_wind_speed','neighbor_3_wind_speed','no2','o3','co'],axis=1)

In [11]:
df.columns

Index(['sensorId', 'timestamp', 'city', 'humidity', 'pm10', 'pm25', 'pressure',
       'temperature', 'wind_speed'],
      dtype='object')

In [12]:
df['sensorId'].value_counts()

sensorId
40f081a6-4095-43f7-bffb-64e2af8c026e    128007
87f82783-853b-417d-8964-b5cf11e44873    127413
874ff9c6-786d-45fc-a90e-48c7ffe03417    125548
7b316592-8036-41e2-b8dc-b06b6a9afd54    122295
16836a55-7140-43e2-9a63-56fac5cba714    108369
2819ecbb-5de3-4092-aa1d-4ba3a8c40add     92896
d7060523-b163-4cc3-bc94-970dac72a38a     83655
23b735ef-a996-4a7f-9998-2aa7e78827b0     73235
d241a044-0a06-40c2-9d90-c91fd0a95060     70704
fec52a19-9148-4350-a1b4-ae0da05ee199     70546
2002                                     30192
2001                                     29574
d851c0b9-990e-41db-9c53-529f88524cf9     16562
e20e9778-a020-4b86-932a-b7ab6a713a00     16017
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d      8342
87f82783-853b-417d-8964-b5cf11e44872         2
a9a2083f-f086-4fae-bdae-355b391f436b         1
d851c0b9-990e-41db-9c53-529f88524cf8         1
Name: count, dtype: int64

In [13]:
print(df['timestamp'].min())
print(df['timestamp'].max())

2023-12-01T01:00:13+01:00
2025-12-01T00:59:34+01:00

In [14]:
df['sensorId'].nunique()

18

Since we want hourly prediction the first thing we do is convert the timestamp into hourly timestamp

In [15]:
df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)


df["timestamp"] = df["timestamp"].dt.floor("h")

In [16]:
df.head(30)

,sensorId,timestamp,city,humidity,pm10,pm25,pressure,temperature,wind_speed
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.0,16.0,7.0,943.0,12.0,8.3
1,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.0,34.0,16.0,943.0,12.0,8.3
2,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,59.0,35.0,18.0,943.0,12.0,8.3
3,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.0,26.0,10.0,943.0,12.0,9.3
4,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.0,15.0,7.0,943.0,12.0,9.3
5,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,60.0,5.0,2.0,943.0,12.0,9.3
6,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.0,9.0,1.0,943.0,12.0,9.3
7,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.0,11.0,6.0,943.0,12.0,8.3
8,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.0,9.0,3.0,943.0,12.0,8.3
9,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.0,10.0,5.0,942.0,12.0,8.3
10,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.0,10.0,4.0,942.0,13.0,8.3
11,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.0,8.0,4.0,942.0,13.0,9.4
12,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.0,13.0,6.0,942.0,13.0,9.4
13,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.0,13.0,6.0,942.0,13.0,9.4
14,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,60.0,5.0,2.0,942.0,13.0,9.4
15,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,60.0,5.0,2.0,942.0,13.0,9.0
16,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,59.0,4.0,1.0,942.0,13.0,9.0
17,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,59.0,3.0,1.0,942.0,13.0,9.0
18,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,60.0,8.0,4.0,942.0,13.0,9.0
19,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,60.0,4.0,2.0,942.0,13.0,7.6
20,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,60.0,16.0,7.0,942.0,13.0,7.6
21,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,60.0,9.0,4.0,942.0,13.0,7.6
22,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,61.0,7.0,3.0,942.0,13.0,7.6
23,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,60.0,3.0,1.0,942.0,13.0,6.8
24,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,59.0,3.0,1.0,942.0,14.0,6.8
25,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,59.0,5.0,3.0,942.0,14.0,6.8
26,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,58.0,21.0,10.0,942.0,14.0,6.8
27,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 07:00:00+00:00,bitola,58.0,30.0,15.0,943.0,15.0,12.4
28,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 07:00:00+00:00,bitola,57.0,15.0,8.0,943.0,15.0,12.4
29,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 07:00:00+00:00,bitola,56.0,11.0,3.0,943.0,16.0,12.4

Since the timestamp above is hourly now we try to aggregate all values that belong to the same timestamp and sensorId

In [17]:
df_hourly = (
    df.groupby(["sensorId", "timestamp"])
      .agg({
          "city":"first",
          "humidity":"mean",
          "pm10":"mean",
          "pm25":"mean",
          "pressure":"mean",
          "temperature":"mean",
          "wind_speed":"mean"
      })
      .reset_index()
)

In [18]:
df_hourly = df_hourly.sort_values(by=["timestamp", "sensorId"]).reset_index(drop=True)

In [19]:
df_hourly.head(20)

,sensorId,timestamp,city,humidity,pm10,pm25,pressure,temperature,wind_speed
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.333333,28.333333,13.666667,943.0,12.00,8.3
1,2001,2023-12-01 00:00:00+00:00,bitola,NaN,NaN,9.000000,NaN,NaN,8.3
2,2002,2023-12-01 00:00:00+00:00,bitola,NaN,NaN,27.000000,NaN,NaN,8.3
3,40f081a6-4095-43f7-bffb-64e2af8c026e,2023-12-01 00:00:00+00:00,bitola,61.000000,5.500000,3.000000,942.0,12.00,5.0
4,874ff9c6-786d-45fc-a90e-48c7ffe03417,2023-12-01 00:00:00+00:00,bitola,68.250000,10.750000,3.500000,940.0,10.75,5.0
5,87f82783-853b-417d-8964-b5cf11e44873,2023-12-01 00:00:00+00:00,bitola,67.000000,52.000000,25.500000,943.0,11.00,8.3
6,d851c0b9-990e-41db-9c53-529f88524cf8,2023-12-01 00:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,5.0
7,d851c0b9-990e-41db-9c53-529f88524cf9,2023-12-01 00:00:00+00:00,bitola,61.000000,11.000000,6.000000,935.0,10.00,NaN
8,e20e9778-a020-4b86-932a-b7ab6a713a00,2023-12-01 00:00:00+00:00,bitola,47.000000,28.750000,16.000000,944.0,16.00,8.3
9,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.250000,13.750000,5.000000,943.0,12.00,9.3
10,2001,2023-12-01 01:00:00+00:00,bitola,NaN,NaN,10.000000,NaN,NaN,9.3
11,2002,2023-12-01 01:00:00+00:00,bitola,NaN,27.000000,23.000000,NaN,NaN,9.3
12,40f081a6-4095-43f7-bffb-64e2af8c026e,2023-12-01 01:00:00+00:00,bitola,62.500000,7.250000,3.250000,942.0,12.00,4.8
13,874ff9c6-786d-45fc-a90e-48c7ffe03417,2023-12-01 01:00:00+00:00,bitola,69.500000,9.250000,2.250000,940.0,11.00,4.8
14,87f82783-853b-417d-8964-b5cf11e44873,2023-12-01 01:00:00+00:00,bitola,67.750000,69.750000,29.500000,943.0,11.00,9.3
15,d851c0b9-990e-41db-9c53-529f88524cf9,2023-12-01 01:00:00+00:00,bitola,62.500000,7.000000,2.500000,935.0,10.00,4.8
16,e20e9778-a020-4b86-932a-b7ab6a713a00,2023-12-01 01:00:00+00:00,bitola,48.666667,23.666667,12.333333,944.0,16.00,9.3
17,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.000000,10.000000,4.500000,942.5,12.25,8.3
18,2001,2023-12-01 02:00:00+00:00,bitola,NaN,NaN,8.000000,NaN,NaN,8.3
19,2002,2023-12-01 02:00:00+00:00,bitola,NaN,19.000000,16.000000,NaN,NaN,8.3

In [20]:
df_hourly['sensorId'].value_counts()

sensorId
40f081a6-4095-43f7-bffb-64e2af8c026e    17338
87f82783-853b-417d-8964-b5cf11e44873    17087
874ff9c6-786d-45fc-a90e-48c7ffe03417    16834
7b316592-8036-41e2-b8dc-b06b6a9afd54    16232
2002                                    15516
2001                                    15173
16836a55-7140-43e2-9a63-56fac5cba714    15021
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    12040
d7060523-b163-4cc3-bc94-970dac72a38a    10931
23b735ef-a996-4a7f-9998-2aa7e78827b0     9538
d241a044-0a06-40c2-9d90-c91fd0a95060     9309
fec52a19-9148-4350-a1b4-ae0da05ee199     9238
e20e9778-a020-4b86-932a-b7ab6a713a00     2526
d851c0b9-990e-41db-9c53-529f88524cf9     2360
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d     1167
87f82783-853b-417d-8964-b5cf11e44872        2
d851c0b9-990e-41db-9c53-529f88524cf8        1
a9a2083f-f086-4fae-bdae-355b391f436b        1
Name: count, dtype: int64

In [21]:
percent_missing = (df_hourly.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

sensorId        0.000000
timestamp       0.000000
city            0.000000
humidity       21.429242
pm10           11.738319
pm25            4.716582
pressure       21.323555
temperature    21.323555
wind_speed      0.002349
dtype: float64

In [22]:
len(df_hourly)

170314

In [23]:
sensor_stats = df_hourly.groupby('sensorId')[['humidity', 'pressure', 'pm10','pm25','temperature']].apply(lambda x: x.isnull().mean())

In [24]:
print(sensor_stats[sensor_stats['humidity'] > 0.9])

                                      humidity  pressure      pm10      pm25  \
sensorId
2001                                       1.0       1.0  0.874448  0.113425
2002                                       1.0       1.0  0.157515  0.131026
87f82783-853b-417d-8964-b5cf11e44872       1.0       1.0  1.000000  1.000000
d851c0b9-990e-41db-9c53-529f88524cf8       1.0       1.0  1.000000  1.000000

                                      temperature
sensorId
2001                                          1.0
2002                                          1.0
87f82783-853b-417d-8964-b5cf11e44872          1.0
d851c0b9-990e-41db-9c53-529f88524cf8          1.0

Now we want to check which sensors have a lot of missing values and those that have over 100% missing data will be removed

In [26]:
sensor_stats = df_hourly.groupby('sensorId')[['pm10', 'pm25']].count()
valid_sensors = sensor_stats[sensor_stats.sum(axis=1) > 0].index

df_hourly = df_hourly[df_hourly['sensorId'].isin(valid_sensors)]

In [27]:
len(df_hourly)

170311

In [28]:
df_hourly['sensorId'].value_counts()

sensorId
40f081a6-4095-43f7-bffb-64e2af8c026e    17338
87f82783-853b-417d-8964-b5cf11e44873    17087
874ff9c6-786d-45fc-a90e-48c7ffe03417    16834
7b316592-8036-41e2-b8dc-b06b6a9afd54    16232
2002                                    15516
2001                                    15173
16836a55-7140-43e2-9a63-56fac5cba714    15021
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    12040
d7060523-b163-4cc3-bc94-970dac72a38a    10931
23b735ef-a996-4a7f-9998-2aa7e78827b0     9538
d241a044-0a06-40c2-9d90-c91fd0a95060     9309
fec52a19-9148-4350-a1b4-ae0da05ee199     9238
e20e9778-a020-4b86-932a-b7ab6a713a00     2526
d851c0b9-990e-41db-9c53-529f88524cf9     2360
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d     1167
a9a2083f-f086-4fae-bdae-355b391f436b        1
Name: count, dtype: int64

In [29]:
percent_missing = (df_hourly.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

sensorId        0.000000
timestamp       0.000000
city            0.000000
humidity       21.427858
pm10           11.736764
pm25            4.714904
pressure       21.322169
temperature    21.322169
wind_speed      0.002349
dtype: float64

Since there is still missing values across the dataset, now we try to interpolate the values of the humidity, temperature,pressure,wind_speed, pm10 and pm25 in order to reduce the missing value percentage based on the sensor id

In [30]:
df_hourly = df_hourly.sort_values(['sensorId', 'timestamp'])

cols_to_fix = ['pm10', 'pm25', 'temperature', 'humidity', 'pressure', 'wind_speed']

for col in cols_to_fix:

    df_hourly[col] = df_hourly.groupby('sensorId')[col].transform(
        lambda x: x.interpolate(method='linear', limit=3)
    )

In [31]:
percent_missing = (df_hourly.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

sensorId        0.000000
timestamp       0.000000
city            0.000000
humidity       21.339784
pm10           10.212494
pm25            2.592904
pressure       21.292224
temperature    21.292224
wind_speed      0.001174
dtype: float64

In [32]:
df_hourly.head(20)

,sensorId,timestamp,city,humidity,pm10,pm25,pressure,temperature,wind_speed
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.333333,28.333333,13.666667,943.00,12.000000,8.3
9,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.250000,13.750000,5.000000,943.00,12.000000,9.3
17,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.000000,10.000000,4.500000,942.50,12.250000,8.3
25,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.250000,9.750000,4.500000,942.00,13.000000,9.4
33,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,59.500000,5.000000,2.000000,942.00,13.000000,9.0
41,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,60.250000,9.000000,4.000000,942.00,13.000000,7.6
49,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,59.000000,8.000000,3.750000,942.00,13.750000,6.8
57,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 07:00:00+00:00,bitola,56.500000,15.500000,7.000000,943.00,15.500000,12.4
65,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 08:00:00+00:00,bitola,53.666667,7.333333,2.333333,943.00,16.666667,15.6
73,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 09:00:00+00:00,bitola,51.500000,6.500000,1.750000,943.00,17.250000,18.6
87,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 11:00:00+00:00,bitola,42.000000,4.000000,1.000000,942.00,19.000000,18.2
94,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 12:00:00+00:00,bitola,41.750000,7.000000,1.250000,941.75,19.500000,18.3
102,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 13:00:00+00:00,bitola,42.500000,13.500000,1.250000,941.00,19.750000,17.6
110,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 14:00:00+00:00,bitola,44.333333,6.000000,1.333333,941.00,19.000000,15.0
118,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 15:00:00+00:00,bitola,46.250000,7.000000,1.500000,941.00,18.500000,12.6
126,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 16:00:00+00:00,bitola,48.250000,10.250000,1.500000,941.00,18.000000,12.6
134,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 17:00:00+00:00,bitola,49.500000,16.250000,2.250000,941.00,17.500000,10.4
142,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 18:00:00+00:00,bitola,49.250000,11.666667,1.666667,941.00,17.000000,9.7
150,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 19:00:00+00:00,bitola,52.750000,12.000000,2.500000,941.00,16.500000,9.4
158,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 20:00:00+00:00,bitola,54.500000,14.500000,3.000000,941.00,15.250000,8.6

In [34]:
df_hourly = df_hourly.dropna(subset=['pm10', 'pm25'])

print(f"Remaining rows after dropping missing targets: {len(df_hourly)}")

Remaining rows after dropping missing targets: 152848

In [35]:
percent_missing = (df_hourly.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

sensorId        0.000000
timestamp       0.000000
city            0.000000
humidity       14.910892
pm10            0.000000
pm25            0.000000
pressure       14.857898
temperature    14.857898
wind_speed      0.001308
dtype: float64

Fill missing weather with the average of all other sensors in Bitola for that specific hour

In [36]:
weather_cols = ['humidity', 'pressure', 'temperature', 'wind_speed']


df_hourly[weather_cols] = df_hourly[weather_cols].fillna(
    df_hourly.groupby('timestamp')[weather_cols].transform('mean')
)

In [37]:
percent_missing = (df_hourly.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

sensorId       0.000000
timestamp      0.000000
city           0.000000
humidity       0.035983
pm10           0.000000
pm25           0.000000
pressure       0.035983
temperature    0.035983
wind_speed     0.000000
dtype: float64

Since we have small percent of the missing values we use for example the ffil method

In [38]:
df_hourly[weather_cols] = df_hourly[weather_cols].fillna(method='ffill')

# Verify one last time - everything should be 0.0
print(df_hourly.isnull().sum())

sensorId       0
timestamp      0
city           0
humidity       0
pm10           0
pm25           0
pressure       0
temperature    0
wind_speed     0
dtype: int64

C:\Users\Jovan\AppData\Local\Temp\ipykernel_12256\2034505720.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_hourly[weather_cols] = df_hourly[weather_cols].fillna(method='ffill')

In [39]:
df_hourly.head(20)

,sensorId,timestamp,city,humidity,pm10,pm25,pressure,temperature,wind_speed
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.333333,28.333333,13.666667,943.00,12.000000,8.3
9,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.250000,13.750000,5.000000,943.00,12.000000,9.3
17,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.000000,10.000000,4.500000,942.50,12.250000,8.3
25,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.250000,9.750000,4.500000,942.00,13.000000,9.4
33,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,59.500000,5.000000,2.000000,942.00,13.000000,9.0
41,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,60.250000,9.000000,4.000000,942.00,13.000000,7.6
49,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,59.000000,8.000000,3.750000,942.00,13.750000,6.8
57,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 07:00:00+00:00,bitola,56.500000,15.500000,7.000000,943.00,15.500000,12.4
65,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 08:00:00+00:00,bitola,53.666667,7.333333,2.333333,943.00,16.666667,15.6
73,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 09:00:00+00:00,bitola,51.500000,6.500000,1.750000,943.00,17.250000,18.6
87,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 11:00:00+00:00,bitola,42.000000,4.000000,1.000000,942.00,19.000000,18.2
94,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 12:00:00+00:00,bitola,41.750000,7.000000,1.250000,941.75,19.500000,18.3
102,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 13:00:00+00:00,bitola,42.500000,13.500000,1.250000,941.00,19.750000,17.6
110,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 14:00:00+00:00,bitola,44.333333,6.000000,1.333333,941.00,19.000000,15.0
118,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 15:00:00+00:00,bitola,46.250000,7.000000,1.500000,941.00,18.500000,12.6
126,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 16:00:00+00:00,bitola,48.250000,10.250000,1.500000,941.00,18.000000,12.6
134,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 17:00:00+00:00,bitola,49.500000,16.250000,2.250000,941.00,17.500000,10.4
142,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 18:00:00+00:00,bitola,49.250000,11.666667,1.666667,941.00,17.000000,9.7
150,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 19:00:00+00:00,bitola,52.750000,12.000000,2.500000,941.00,16.500000,9.4
158,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 20:00:00+00:00,bitola,54.500000,14.500000,3.000000,941.00,15.250000,8.6

In [40]:
df_hourly.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed
count,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000
mean,52.811261,27.148423,14.729742,939.616547,16.522121,6.041053
std,15.968654,49.878253,26.885154,13.951810,9.077592,3.864758
min,8.750000,0.000000,0.000000,869.000000,-12.000000,0.000000
25%,40.750000,5.500000,2.500000,937.250000,9.414773,3.300000
50%,53.750000,11.250000,6.000000,942.000000,15.750000,5.200000
75%,65.000000,27.000000,14.750000,946.750000,23.250000,7.800000
max,99.000000,1995.000000,639.250000,971.750000,47.500000,32.800000

In [41]:
len(df_hourly)

152848

In [42]:
df_hourly['sensorId'].value_counts()

sensorId
874ff9c6-786d-45fc-a90e-48c7ffe03417    16834
87f82783-853b-417d-8964-b5cf11e44873    16688
40f081a6-4095-43f7-bffb-64e2af8c026e    16563
7b316592-8036-41e2-b8dc-b06b6a9afd54    16232
2002                                    15300
16836a55-7140-43e2-9a63-56fac5cba714    15021
d7060523-b163-4cc3-bc94-970dac72a38a    10931
23b735ef-a996-4a7f-9998-2aa7e78827b0     9538
d241a044-0a06-40c2-9d90-c91fd0a95060     9308
fec52a19-9148-4350-a1b4-ae0da05ee199     9238
2819ecbb-5de3-4092-aa1d-4ba3a8c40add     9070
e20e9778-a020-4b86-932a-b7ab6a713a00     2526
d851c0b9-990e-41db-9c53-529f88524cf9     2252
2001                                     2179
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d     1167
a9a2083f-f086-4fae-bdae-355b391f436b        1
Name: count, dtype: int64

In [43]:
neighbourhood_matrix = pd.read_csv("data/neighbors_data/bitola_sensor_distances.csv")
neighbourhood_matrix

,sensor_id,neighbor_id,distance_km
0,d241a044-0a06-40c2-9d90-c91fd0a95060,fec52a19-9148-4350-a1b4-ae0da05ee199,7.082000
1,fec52a19-9148-4350-a1b4-ae0da05ee199,d241a044-0a06-40c2-9d90-c91fd0a95060,7.082000
2,d241a044-0a06-40c2-9d90-c91fd0a95060,be427cee-4c3a-4aa2-a1ce-9795a74533be,8.838588
3,be427cee-4c3a-4aa2-a1ce-9795a74533be,d241a044-0a06-40c2-9d90-c91fd0a95060,8.838588
4,d241a044-0a06-40c2-9d90-c91fd0a95060,c3f3da9b-9fd3-4037-94d3-598d655e6be9,10.004966
...,...,...,...
457,7b316592-8036-41e2-b8dc-b06b6a9afd54,40f081a6-4095-43f7-bffb-64e2af8c026e,1.049671
458,40f081a6-4095-43f7-bffb-64e2af8c026e,692c454c-a1ad-41fa-b3ca-aa1cb7d55d30,3.044465
459,692c454c-a1ad-41fa-b3ca-aa1cb7d55d30,40f081a6-4095-43f7-bffb-64e2af8c026e,3.044465
460,7b316592-8036-41e2-b8dc-b06b6a9afd54,692c454c-a1ad-41fa-b3ca-aa1cb7d55d30,2.083640
461,692c454c-a1ad-41fa-b3ca-aa1cb7d55d30,7b316592-8036-41e2-b8dc-b06b6a9afd54,2.083640

In [49]:
valid_sensors

Index(['16836a55-7140-43e2-9a63-56fac5cba714', '2001', '2002',
       '23b735ef-a996-4a7f-9998-2aa7e78827b0',
       '2819ecbb-5de3-4092-aa1d-4ba3a8c40add',
       '30dab8a6-ff63-43ce-9a3b-99f1f3f7054d',
       '40f081a6-4095-43f7-bffb-64e2af8c026e',
       '7b316592-8036-41e2-b8dc-b06b6a9afd54',
       '874ff9c6-786d-45fc-a90e-48c7ffe03417',
       '87f82783-853b-417d-8964-b5cf11e44873',
       'a9a2083f-f086-4fae-bdae-355b391f436b',
       'd241a044-0a06-40c2-9d90-c91fd0a95060',
       'd7060523-b163-4cc3-bc94-970dac72a38a',
       'd851c0b9-990e-41db-9c53-529f88524cf9',
       'e20e9778-a020-4b86-932a-b7ab6a713a00',
       'fec52a19-9148-4350-a1b4-ae0da05ee199'],
      dtype='object', name='sensorId')

In [50]:
neighbors_df_clean = neighbourhood_matrix[
    (neighbourhood_matrix['sensor_id'].isin(valid_sensors)) &
    (neighbourhood_matrix['neighbor_id'].isin(valid_sensors))
].copy()

Function for appending neighborhood features

In [51]:
def append_neighbors(df_hourly, neighbors_df, weather_cols, k_search=20, k_keep=3):
    # 1. Standardize the neighbor list
    # Ensure we only take the top K based on distance
    neighbors_topk = (
        neighbors_df.sort_values(["sensor_id", "distance_km"])
        .groupby("sensor_id")
        .head(k_search)
        .copy()
    )

    # Track original distance rank
    neighbors_topk['dist_rank'] = neighbors_topk.groupby("sensor_id").cumcount() + 1

    # 2. Merge with main data
    # We use 'neighbor_id' from the matrix to match 'sensorId' in the hourly data
    neighbor_values = neighbors_topk.merge(
        df_hourly[['sensorId', 'timestamp'] + weather_cols],
        left_on='neighbor_id',
        right_on='sensorId',
        how='inner'
    )

    # 3. Filter for availability
    # The 'sensor_id' here is the ORIGINAL sensor we are finding neighbors for
    available_topk = (
        neighbor_values.sort_values(['sensor_id', 'timestamp', 'dist_rank'])
        .groupby(['sensor_id', 'timestamp'])
        .head(k_keep)
        .copy()
    )

    # Create the 1, 2, 3 rank for the wide-format columns
    available_topk['final_rank'] = available_topk.groupby(['sensor_id', 'timestamp']).cumcount() + 1

    # 4. Pivot to wide format
    pivot_df = available_topk.pivot(
        index=['sensor_id', 'timestamp'],
        columns='final_rank',
        values=weather_cols
    )

    # Clean up column names: neighbor1_temp, neighbor2_temp, etc.
    if isinstance(pivot_df.columns, pd.MultiIndex):
        pivot_df.columns = [f"neighbor{rank}_{col}" for col, rank in pivot_df.columns]
    else:
        # Handle case with only one weather column
        pivot_df.columns = [f"neighbor{i}_{weather_cols[0]}" for i in pivot_df.columns]

    pivot_df = pivot_df.reset_index()

    # 5. Final Join back to original data
    df_result = df_hourly.merge(
        pivot_df,
        left_on=['sensorId', 'timestamp'],
        right_on=['sensor_id', 'timestamp'],
        how='left'
    ).drop(columns=['sensor_id'])

    return df_result

In [52]:
weather_cols

['humidity', 'pressure', 'temperature', 'wind_speed']

In [54]:
df_final = append_neighbors(df_hourly,neighbors_df_clean, weather_cols)

In [55]:
df_final

,sensorId,timestamp,city,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,...,neighbor3_humidity,neighbor1_pressure,neighbor2_pressure,neighbor3_pressure,neighbor1_temperature,neighbor2_temperature,neighbor3_temperature,neighbor1_wind_speed,neighbor2_wind_speed,neighbor3_wind_speed
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.333333,28.333333,13.666667,943.0,12.00,8.3,47.000000,...,61.000000,944.000000,943.0,935.000000,16.000000,11.000000,10.000000,8.3,8.3,6.98
1,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.250000,13.750000,5.000000,943.0,12.00,9.3,61.694444,...,67.750000,941.166667,944.0,943.000000,12.000000,16.000000,11.000000,9.3,9.3,9.30
2,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.000000,10.000000,4.500000,942.5,12.25,8.3,62.222222,...,68.750000,940.930556,944.0,943.000000,12.138889,16.000000,11.000000,8.3,8.3,8.30
3,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.250000,9.750000,4.500000,942.0,13.00,9.4,61.986111,...,69.333333,940.444444,944.0,942.333333,12.611111,16.000000,11.000000,9.4,9.4,9.40
4,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,59.500000,5.000000,2.000000,942.0,13.00,9.0,62.208333,...,69.500000,940.416667,944.0,942.000000,12.833333,16.750000,11.250000,9.0,9.0,9.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152843,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30 19:00:00+00:00,bitola,61.750000,11.250000,6.000000,942.0,9.00,5.9,63.500000,...,68.583333,942.250000,940.0,934.444444,9.000000,6.500000,8.277778,5.3,5.9,5.30
152844,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30 20:00:00+00:00,bitola,63.250000,9.000000,5.666667,942.0,9.00,5.7,63.750000,...,69.333333,943.000000,940.0,934.833333,9.000000,6.000000,7.777778,5.4,5.7,5.40
152845,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30 21:00:00+00:00,bitola,63.500000,12.000000,6.000000,942.5,8.25,5.8,63.333333,...,70.425926,943.000000,940.0,935.000000,9.000000,6.666667,7.685185,5.4,5.8,5.40
152846,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30 22:00:00+00:00,bitola,63.750000,3.250000,2.500000,943.0,7.75,5.6,63.750000,...,70.888889,943.000000,941.0,935.333333,8.250000,6.250000,7.222222,5.0,5.6,5.00
152847,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30 23:00:00+00:00,bitola,63.750000,1.750000,0.750000,943.0,7.00,6.2,64.000000,...,71.472222,943.250000,941.0,935.472222,8.000000,6.000000,6.750000,4.9,6.2,4.90

In [56]:
percent_missing = (df_final.isnull().sum() * 100) / len(df_final)
print(percent_missing)

sensorId                 0.000000
timestamp                0.000000
city                     0.000000
humidity                 0.000000
pm10                     0.000000
pm25                     0.000000
pressure                 0.000000
temperature              0.000000
wind_speed               0.000000
neighbor1_humidity       0.007197
neighbor2_humidity       0.035983
neighbor3_humidity       0.055611
neighbor1_pressure       0.007197
neighbor2_pressure       0.035983
neighbor3_pressure       0.055611
neighbor1_temperature    0.007197
neighbor2_temperature    0.035983
neighbor3_temperature    0.055611
neighbor1_wind_speed     0.007197
neighbor2_wind_speed     0.035983
neighbor3_wind_speed     0.055611
dtype: float64

In [69]:
features = ['temperature', 'humidity', 'pressure', 'wind_speed']

for feat in features:
    # 1. Fill Neighbor 3 with Neighbor 2 if 3 is missing
    n3_col = f'neighbor3_{feat}'
    n2_col = f'neighbor2_{feat}'
    n1_col = f'neighbor1_{feat}'

    df_final[n3_col] = df_final[n3_col].fillna(df_final[n2_col])

    # 2. Fill Neighbor 2 with Neighbor 1 if 2 is still missing
    df_final[n2_col] = df_final[n2_col].fillna(df_final[n1_col])

    # 3. Final safety check: if Neighbor 1 is missing (very rare),
    # fill with the sensor's own current value for that feature.
    df_final[n1_col] = df_final[n1_col].fillna(df_final[feat])

In [70]:
df_final

,sensorId,timestamp,city,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,...,neighbor3_humidity,neighbor1_pressure,neighbor2_pressure,neighbor3_pressure,neighbor1_temperature,neighbor2_temperature,neighbor3_temperature,neighbor1_wind_speed,neighbor2_wind_speed,neighbor3_wind_speed
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.333333,28.333333,13.666667,943.0,12.00,8.3,47.000000,...,61.000000,944.000000,943.0,935.000000,16.000000,11.000000,10.000000,8.3,8.3,6.98
1,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.250000,13.750000,5.000000,943.0,12.00,9.3,61.694444,...,67.750000,941.166667,944.0,943.000000,12.000000,16.000000,11.000000,9.3,9.3,9.30
2,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.000000,10.000000,4.500000,942.5,12.25,8.3,62.222222,...,68.750000,940.930556,944.0,943.000000,12.138889,16.000000,11.000000,8.3,8.3,8.30
3,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.250000,9.750000,4.500000,942.0,13.00,9.4,61.986111,...,69.333333,940.444444,944.0,942.333333,12.611111,16.000000,11.000000,9.4,9.4,9.40
4,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,59.500000,5.000000,2.000000,942.0,13.00,9.0,62.208333,...,69.500000,940.416667,944.0,942.000000,12.833333,16.750000,11.250000,9.0,9.0,9.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152843,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30 19:00:00+00:00,bitola,61.750000,11.250000,6.000000,942.0,9.00,5.9,63.500000,...,68.583333,942.250000,940.0,934.444444,9.000000,6.500000,8.277778,5.3,5.9,5.30
152844,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30 20:00:00+00:00,bitola,63.250000,9.000000,5.666667,942.0,9.00,5.7,63.750000,...,69.333333,943.000000,940.0,934.833333,9.000000,6.000000,7.777778,5.4,5.7,5.40
152845,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30 21:00:00+00:00,bitola,63.500000,12.000000,6.000000,942.5,8.25,5.8,63.333333,...,70.425926,943.000000,940.0,935.000000,9.000000,6.666667,7.685185,5.4,5.8,5.40
152846,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30 22:00:00+00:00,bitola,63.750000,3.250000,2.500000,943.0,7.75,5.6,63.750000,...,70.888889,943.000000,941.0,935.333333,8.250000,6.250000,7.222222,5.0,5.6,5.00
152847,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30 23:00:00+00:00,bitola,63.750000,1.750000,0.750000,943.0,7.00,6.2,64.000000,...,71.472222,943.250000,941.0,935.472222,8.000000,6.000000,6.750000,4.9,6.2,4.90

In [71]:
len(df_final)

152848

In [72]:
df_final['sensorId'].value_counts()

sensorId
874ff9c6-786d-45fc-a90e-48c7ffe03417    16834
87f82783-853b-417d-8964-b5cf11e44873    16688
40f081a6-4095-43f7-bffb-64e2af8c026e    16563
7b316592-8036-41e2-b8dc-b06b6a9afd54    16232
2002                                    15300
16836a55-7140-43e2-9a63-56fac5cba714    15021
d7060523-b163-4cc3-bc94-970dac72a38a    10931
23b735ef-a996-4a7f-9998-2aa7e78827b0     9538
d241a044-0a06-40c2-9d90-c91fd0a95060     9308
fec52a19-9148-4350-a1b4-ae0da05ee199     9238
2819ecbb-5de3-4092-aa1d-4ba3a8c40add     9070
e20e9778-a020-4b86-932a-b7ab6a713a00     2526
d851c0b9-990e-41db-9c53-529f88524cf9     2252
2001                                     2179
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d     1167
a9a2083f-f086-4fae-bdae-355b391f436b        1
Name: count, dtype: int64

In [73]:
df_final.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor1_pressure,neighbor2_pressure,neighbor3_pressure,neighbor1_temperature,neighbor2_temperature,neighbor3_temperature,neighbor1_wind_speed,neighbor2_wind_speed,neighbor3_wind_speed
count,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000,152848.000000
mean,52.811261,27.148423,14.729742,939.616547,16.522121,6.041053,52.123349,52.395307,51.546619,943.443694,942.744278,942.555363,16.777282,16.891293,17.032540,6.209273,6.170212,6.104457
std,15.968654,49.878253,26.885154,13.951810,9.077592,3.864758,16.010200,16.348770,14.835675,6.667281,6.812137,6.482998,9.041707,9.113808,8.992816,4.018830,3.983603,3.928952
min,8.750000,0.000000,0.000000,869.000000,-12.000000,0.000000,8.750000,9.333333,9.333333,911.000000,911.000000,917.000000,-12.000000,-12.000000,-12.000000,0.000000,0.000000,0.000000
25%,40.750000,5.500000,2.500000,937.250000,9.414773,3.300000,40.250000,40.000000,40.250000,939.680556,938.562500,938.250000,9.750000,9.787879,10.000000,3.300000,3.300000,3.300000
50%,53.750000,11.250000,6.000000,942.000000,15.750000,5.200000,52.750000,52.879630,52.604167,943.500000,943.000000,942.000000,16.000000,16.000000,16.000000,5.400000,5.400000,5.200000
75%,65.000000,27.000000,14.750000,946.750000,23.250000,7.800000,64.166667,64.750000,63.000000,947.000000,947.000000,946.625000,23.500000,23.750000,23.800000,8.000000,8.000000,7.900000
max,99.000000,1995.000000,639.250000,971.750000,47.500000,32.800000,99.000000,99.000000,96.500000,971.750000,971.750000,971.750000,47.500000,47.500000,46.750000,32.800000,32.800000,32.800000

In [74]:
percent_missing = (df_final.isnull().sum() * 100) / len(df_final)
print(percent_missing)

sensorId                 0.0
timestamp                0.0
city                     0.0
humidity                 0.0
pm10                     0.0
pm25                     0.0
pressure                 0.0
temperature              0.0
wind_speed               0.0
neighbor1_humidity       0.0
neighbor2_humidity       0.0
neighbor3_humidity       0.0
neighbor1_pressure       0.0
neighbor2_pressure       0.0
neighbor3_pressure       0.0
neighbor1_temperature    0.0
neighbor2_temperature    0.0
neighbor3_temperature    0.0
neighbor1_wind_speed     0.0
neighbor2_wind_speed     0.0
neighbor3_wind_speed     0.0
dtype: float64

In [75]:
len(df_final)

152848

In [76]:
df_final.columns

Index(['sensorId', 'timestamp', 'city', 'humidity', 'pm10', 'pm25', 'pressure',
       'temperature', 'wind_speed', 'neighbor1_humidity', 'neighbor2_humidity',
       'neighbor3_humidity', 'neighbor1_pressure', 'neighbor2_pressure',
       'neighbor3_pressure', 'neighbor1_temperature', 'neighbor2_temperature',
       'neighbor3_temperature', 'neighbor1_wind_speed', 'neighbor2_wind_speed',
       'neighbor3_wind_speed'],
      dtype='object')

Function for extracting some important details about the timestamp

In [78]:
def extract_time_features(df, timestamp_col='timestamp'):


    # 1. Cyclic Hour (24-hour cycle) //
    df['hour_sin'] = np.sin(2 * np.pi * df[timestamp_col].dt.hour / 24)
    df['hour_cos'] = np.cos(2 * np.pi * df[timestamp_col].dt.hour / 24)

    # 2. Cyclic Month (12-month cycle)//
    df['month_sin'] = np.sin(2 * np.pi * (df[timestamp_col].dt.month - 1) / 12)
    df['month_cos'] = np.cos(2 * np.pi * (df[timestamp_col].dt.month - 1) / 12)

    # 3. Weekend Flag
    # Monday=0, Sunday=6. Weekends are 5 and 6.
    df['is_weekend'] = df[timestamp_col].dt.dayofweek.isin([5, 6]).astype(int)

    # 4. Heating Season Flag (Specific for Bitola/Macedonia)
    # Most wood burning occurs from November (11) to March (3)
    df['is_heating_season'] = df[timestamp_col].dt.month.isin([11, 12, 1, 2, 3]).astype(int)

    return df

In [79]:
df_final = extract_time_features(df_final)

In [80]:
df_final.head(20)

,sensorId,timestamp,city,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,...,neighbor3_temperature,neighbor1_wind_speed,neighbor2_wind_speed,neighbor3_wind_speed,hour_sin,hour_cos,month_sin,month_cos,is_weekend,is_heating_season
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.333333,28.333333,13.666667,943.00,12.000000,8.3,47.000000,...,10.000000,8.3,8.3,6.98,0.000000e+00,1.000000e+00,-0.5,0.866025,0,1
1,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.250000,13.750000,5.000000,943.00,12.000000,9.3,61.694444,...,11.000000,9.3,9.3,9.30,2.588190e-01,9.659258e-01,-0.5,0.866025,0,1
2,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.000000,10.000000,4.500000,942.50,12.250000,8.3,62.222222,...,11.000000,8.3,8.3,8.30,5.000000e-01,8.660254e-01,-0.5,0.866025,0,1
3,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.250000,9.750000,4.500000,942.00,13.000000,9.4,61.986111,...,11.000000,9.4,9.4,9.40,7.071068e-01,7.071068e-01,-0.5,0.866025,0,1
4,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,59.500000,5.000000,2.000000,942.00,13.000000,9.0,62.208333,...,11.250000,9.0,9.0,9.00,8.660254e-01,5.000000e-01,-0.5,0.866025,0,1
5,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,60.250000,9.000000,4.000000,942.00,13.000000,7.6,63.416667,...,11.750000,7.6,7.6,7.60,9.659258e-01,2.588190e-01,-0.5,0.866025,0,1
6,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,59.000000,8.000000,3.750000,942.00,13.750000,6.8,63.291667,...,11.750000,6.8,6.8,6.80,1.000000e+00,6.123234e-17,-0.5,0.866025,0,1
7,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 07:00:00+00:00,bitola,56.500000,15.500000,7.000000,943.00,15.500000,12.4,60.583333,...,13.250000,12.4,12.4,12.40,9.659258e-01,-2.588190e-01,-0.5,0.866025,0,1
8,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 08:00:00+00:00,bitola,53.666667,7.333333,2.333333,943.00,16.666667,15.6,57.597222,...,15.000000,15.6,15.6,15.60,8.660254e-01,-5.000000e-01,-0.5,0.866025,0,1
9,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 09:00:00+00:00,bitola,51.500000,6.500000,1.750000,943.00,17.250000,18.6,53.000000,...,16.750000,18.6,18.6,18.60,7.071068e-01,-7.071068e-01,-0.5,0.866025,0,1
10,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 11:00:00+00:00,bitola,42.000000,4.000000,1.000000,942.00,19.000000,18.2,42.150000,...,21.000000,18.2,18.2,18.20,2.588190e-01,-9.659258e-01,-0.5,0.866025,0,1
11,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 12:00:00+00:00,bitola,41.750000,7.000000,1.250000,941.75,19.500000,18.3,42.486111,...,21.000000,18.3,18.3,18.30,1.224647e-16,-1.000000e+00,-0.5,0.866025,0,1
12,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 13:00:00+00:00,bitola,42.500000,13.500000,1.250000,941.00,19.750000,17.6,43.763889,...,20.750000,17.6,17.6,17.60,-2.588190e-01,-9.659258e-01,-0.5,0.866025,0,1
13,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 14:00:00+00:00,bitola,44.333333,6.000000,1.333333,941.00,19.000000,15.0,35.500000,...,15.000000,15.0,15.0,5.70,-5.000000e-01,-8.660254e-01,-0.5,0.866025,0,1
14,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 15:00:00+00:00,bitola,46.250000,7.000000,1.500000,941.00,18.500000,12.6,46.791667,...,19.000000,12.6,12.6,12.60,-7.071068e-01,-7.071068e-01,-0.5,0.866025,0,1
15,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 16:00:00+00:00,bitola,48.250000,10.250000,1.500000,941.00,18.000000,12.6,49.250000,...,18.000000,12.6,12.6,12.60,-8.660254e-01,-5.000000e-01,-0.5,0.866025,0,1
16,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 17:00:00+00:00,bitola,49.500000,16.250000,2.250000,941.00,17.500000,10.4,51.791667,...,17.500000,10.4,10.4,10.40,-9.659258e-01,-2.588190e-01,-0.5,0.866025,0,1
17,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 18:00:00+00:00,bitola,49.250000,11.666667,1.666667,941.00,17.000000,9.7,52.972222,...,16.666667,9.7,9.7,9.70,-1.000000e+00,-1.836970e-16,-0.5,0.866025,0,1
18,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 19:00:00+00:00,bitola,52.750000,12.000000,2.500000,941.00,16.500000,9.4,54.333333,...,16.000000,9.4,9.4,9.40,-9.659258e-01,2.588190e-01,-0.5,0.866025,0,1
19,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 20:00:00+00:00,bitola,54.500000,14.500000,3.000000,941.00,15.250000,8.6,55.569444,...,15.500000,8.6,8.6,8.60,-8.660254e-01,5.000000e-01,-0.5,0.866025,0,1

In [81]:
df_final.isnull().sum()

sensorId                 0
timestamp                0
city                     0
humidity                 0
pm10                     0
pm25                     0
pressure                 0
temperature              0
wind_speed               0
neighbor1_humidity       0
neighbor2_humidity       0
neighbor3_humidity       0
neighbor1_pressure       0
neighbor2_pressure       0
neighbor3_pressure       0
neighbor1_temperature    0
neighbor2_temperature    0
neighbor3_temperature    0
neighbor1_wind_speed     0
neighbor2_wind_speed     0
neighbor3_wind_speed     0
hour_sin                 0
hour_cos                 0
month_sin                0
month_cos                0
is_weekend               0
is_heating_season        0
dtype: int64

In [82]:
df_final.columns

Index(['sensorId', 'timestamp', 'city', 'humidity', 'pm10', 'pm25', 'pressure',
       'temperature', 'wind_speed', 'neighbor1_humidity', 'neighbor2_humidity',
       'neighbor3_humidity', 'neighbor1_pressure', 'neighbor2_pressure',
       'neighbor3_pressure', 'neighbor1_temperature', 'neighbor2_temperature',
       'neighbor3_temperature', 'neighbor1_wind_speed', 'neighbor2_wind_speed',
       'neighbor3_wind_speed', 'hour_sin', 'hour_cos', 'month_sin',
       'month_cos', 'is_weekend', 'is_heating_season'],
      dtype='object')

In [83]:
df_final['sensorId'].value_counts()

sensorId
874ff9c6-786d-45fc-a90e-48c7ffe03417    16834
87f82783-853b-417d-8964-b5cf11e44873    16688
40f081a6-4095-43f7-bffb-64e2af8c026e    16563
7b316592-8036-41e2-b8dc-b06b6a9afd54    16232
2002                                    15300
16836a55-7140-43e2-9a63-56fac5cba714    15021
d7060523-b163-4cc3-bc94-970dac72a38a    10931
23b735ef-a996-4a7f-9998-2aa7e78827b0     9538
d241a044-0a06-40c2-9d90-c91fd0a95060     9308
fec52a19-9148-4350-a1b4-ae0da05ee199     9238
2819ecbb-5de3-4092-aa1d-4ba3a8c40add     9070
e20e9778-a020-4b86-932a-b7ab6a713a00     2526
d851c0b9-990e-41db-9c53-529f88524cf9     2252
2001                                     2179
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d     1167
a9a2083f-f086-4fae-bdae-355b391f436b        1
Name: count, dtype: int64

In [84]:
df_final.to_csv("data/training/bitola_final_data.csv", index=False)