## Data Preprocessing of Bitola Dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/training/bitola_features.csv",low_memory=False)

In [3]:
df.head(30)

,sensorId,timestamp,city,co,humidity,no2,o3,pm10,pm25,pressure,...,wind_speed,neighbor_1_pm10,neighbor_1_pm25,neighbor_1_wind_speed,neighbor_2_pm10,neighbor_2_pm25,neighbor_2_wind_speed,neighbor_3_pm10,neighbor_3_pm25,neighbor_3_wind_speed
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T01:13:38+01:00,bitola,NaN,58.0,NaN,NaN,16.0,7.0,943.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T01:29:10+01:00,bitola,NaN,58.0,NaN,NaN,34.0,16.0,943.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T01:44:41+01:00,bitola,NaN,59.0,NaN,NaN,35.0,18.0,943.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T02:00:13+01:00,bitola,NaN,59.0,NaN,NaN,26.0,10.0,943.0,...,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T02:15:45+01:00,bitola,NaN,59.0,NaN,NaN,15.0,7.0,943.0,...,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T02:31:16+01:00,bitola,NaN,60.0,NaN,NaN,5.0,2.0,943.0,...,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T02:46:48+01:00,bitola,NaN,59.0,NaN,NaN,9.0,1.0,943.0,...,9.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T03:02:20+01:00,bitola,NaN,60.0,NaN,NaN,11.0,6.0,943.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T03:17:52+01:00,bitola,NaN,60.0,NaN,NaN,9.0,3.0,943.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T03:33:23+01:00,bitola,NaN,60.0,NaN,NaN,10.0,5.0,942.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T03:48:55+01:00,bitola,NaN,60.0,NaN,NaN,10.0,4.0,942.0,...,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T04:04:27+01:00,bitola,NaN,59.0,NaN,NaN,8.0,4.0,942.0,...,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T04:19:58+01:00,bitola,NaN,59.0,NaN,NaN,13.0,6.0,942.0,...,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T04:35:30+01:00,bitola,NaN,59.0,NaN,NaN,13.0,6.0,942.0,...,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T04:51:01+01:00,bitola,NaN,60.0,NaN,NaN,5.0,2.0,942.0,...,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T05:06:33+01:00,bitola,NaN,60.0,NaN,NaN,5.0,2.0,942.0,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T05:22:05+01:00,bitola,NaN,59.0,NaN,NaN,4.0,1.0,942.0,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T05:37:36+01:00,bitola,NaN,59.0,NaN,NaN,3.0,1.0,942.0,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T05:53:08+01:00,bitola,NaN,60.0,NaN,NaN,8.0,4.0,942.0,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T06:08:40+01:00,bitola,NaN,60.0,NaN,NaN,4.0,2.0,942.0,...,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T06:24:12+01:00,bitola,NaN,60.0,NaN,NaN,16.0,7.0,942.0,...,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T06:39:44+01:00,bitola,NaN,60.0,NaN,NaN,9.0,4.0,942.0,...,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T06:55:16+01:00,bitola,NaN,61.0,NaN,NaN,7.0,3.0,942.0,...,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T07:10:48+01:00,bitola,NaN,60.0,NaN,NaN,3.0,1.0,942.0,...,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T07:26:21+01:00,bitola,NaN,59.0,NaN,NaN,3.0,1.0,942.0,...,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T07:41:52+01:00,bitola,NaN,59.0,NaN,NaN,5.0,3.0,942.0,...,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T07:57:25+01:00,bitola,NaN,58.0,NaN,NaN,21.0,10.0,942.0,...,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T08:12:57+01:00,bitola,NaN,58.0,NaN,NaN,30.0,15.0,943.0,...,12.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T08:28:28+01:00,bitola,NaN,57.0,NaN,NaN,15.0,8.0,943.0,...,12.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01T08:44:00+01:00,bitola,NaN,56.0,NaN,NaN,11.0,3.0,943.0,...,12.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.tail(10)

,sensorId,timestamp,city,co,humidity,no2,o3,pm10,pm25,pressure,...,wind_speed,neighbor_1_pm10,neighbor_1_pm25,neighbor_1_wind_speed,neighbor_2_pm10,neighbor_2_pm25,neighbor_2_wind_speed,neighbor_3_pm10,neighbor_3_pm25,neighbor_3_wind_speed
1103349,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:22:38+01:00,bitola,NaN,64.0,NaN,NaN,3.0,2.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103350,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:24:44+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103351,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:38:10+01:00,bitola,NaN,64.0,NaN,NaN,4.0,4.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103352,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:40:16+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103353,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:53:41+01:00,bitola,NaN,64.0,NaN,NaN,3.0,2.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103354,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-11-30T23:55:47+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103355,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-12-01T00:09:13+01:00,bitola,NaN,63.0,NaN,NaN,3.0,1.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103356,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-12-01T00:24:44+01:00,bitola,NaN,64.0,NaN,NaN,0.0,0.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103357,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-12-01T00:40:16+01:00,bitola,NaN,64.0,NaN,NaN,3.0,1.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103358,fec52a19-9148-4350-a1b4-ae0da05ee199,2025-12-01T00:55:47+01:00,bitola,NaN,64.0,NaN,NaN,1.0,1.0,943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.describe()

,co,humidity,no2,o3,pm10,pm25,pressure,temperature,wind_speed,neighbor_1_pm10,neighbor_1_pm25,neighbor_1_wind_speed,neighbor_2_pm10,neighbor_2_pm25,neighbor_2_wind_speed,neighbor_3_pm10,neighbor_3_pm25,neighbor_3_wind_speed
count,24900.000000,508847.000000,25540.000000,21108.000000,526502.000000,538495.000000,510019.000000,510019.000000,562249.000000,213.000000,213.000000,217.000000,183.000000,183.000000,203.000000,297.000000,303.000000,306.000000
mean,0.238514,52.511991,12.215623,39.399754,26.018306,13.641850,939.442499,16.849076,5.973859,32.399061,17.201878,7.502304,29.349727,12.857923,5.952217,23.326599,11.557756,6.343137
std,0.603232,16.208122,12.427257,28.810507,55.757197,28.540954,14.724173,9.174995,3.812610,78.899180,42.788440,4.416860,117.788776,29.968876,3.442575,52.510402,26.146349,3.713277
min,0.000000,8.000000,0.000000,0.000000,0.000000,0.000000,869.000000,-12.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.400000,0.000000,0.000000,0.400000
25%,0.000000,40.000000,3.000000,13.000000,5.000000,2.000000,937.000000,10.000000,3.300000,5.000000,2.000000,4.200000,4.000000,2.000000,3.300000,5.000000,2.500000,4.400000
50%,0.000000,53.000000,8.000000,35.000000,10.000000,5.000000,942.000000,16.000000,5.200000,8.000000,4.000000,6.600000,7.000000,4.000000,5.400000,9.000000,4.000000,5.750000
75%,0.000000,65.000000,17.000000,61.000000,23.000000,12.000000,947.000000,24.000000,7.700000,17.000000,10.000000,10.600000,20.000000,10.500000,8.400000,17.000000,10.000000,7.975000
max,8.000000,99.000000,124.000000,145.000000,1995.000000,998.000000,975.000000,49.000000,32.800000,632.000000,324.000000,23.400000,1519.000000,287.000000,18.300000,457.000000,238.000000,19.800000

In [6]:
len(df)

1103359

In [7]:
percent_missing = (df.isnull().sum() * 100) / len(df)
print(percent_missing)

sensorId                  0.000000
timestamp                 0.000000
city                      0.000000
co                       97.743255
humidity                 53.882009
no2                      97.685250
o3                       98.086933
pm10                     52.281896
pm25                     51.194942
pressure                 53.775788
temperature              53.775788
wind_speed               49.042062
neighbor_1_pm10          99.980695
neighbor_1_pm25          99.980695
neighbor_1_wind_speed    99.980333
neighbor_2_pm10          99.983414
neighbor_2_pm25          99.983414
neighbor_2_wind_speed    99.981602
neighbor_3_pm10          99.973082
neighbor_3_pm25          99.972538
neighbor_3_wind_speed    99.972267
dtype: float64

### Drop the insignificant columns that has missing value percentage above 90%

In [8]:
df= df.drop(columns=['neighbor_1_pm10','neighbor_2_pm10','neighbor_3_pm10','neighbor_1_pm25','neighbor_2_pm25','neighbor_3_pm25','neighbor_1_wind_speed','neighbor_2_wind_speed','neighbor_3_wind_speed','no2','o3','co'],axis=1)

In [9]:
df.columns

Index(['sensorId', 'timestamp', 'city', 'humidity', 'pm10', 'pm25', 'pressure',
       'temperature', 'wind_speed'],
      dtype='object')

In [10]:
df['sensorId'].value_counts()

sensorId
40f081a6-4095-43f7-bffb-64e2af8c026e    128007
87f82783-853b-417d-8964-b5cf11e44873    127413
874ff9c6-786d-45fc-a90e-48c7ffe03417    125548
7b316592-8036-41e2-b8dc-b06b6a9afd54    122295
16836a55-7140-43e2-9a63-56fac5cba714    108369
2819ecbb-5de3-4092-aa1d-4ba3a8c40add     92896
d7060523-b163-4cc3-bc94-970dac72a38a     83655
23b735ef-a996-4a7f-9998-2aa7e78827b0     73235
d241a044-0a06-40c2-9d90-c91fd0a95060     70704
fec52a19-9148-4350-a1b4-ae0da05ee199     70546
2002                                     30192
2001                                     29574
d851c0b9-990e-41db-9c53-529f88524cf9     16562
e20e9778-a020-4b86-932a-b7ab6a713a00     16017
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d      8342
87f82783-853b-417d-8964-b5cf11e44872         2
a9a2083f-f086-4fae-bdae-355b391f436b         1
d851c0b9-990e-41db-9c53-529f88524cf8         1
Name: count, dtype: int64

In [11]:
print(df['timestamp'].min())
print(df['timestamp'].max())

2023-12-01T01:00:13+01:00
2025-12-01T00:59:34+01:00

In [12]:
df['sensorId'].nunique()

18

### Convert the original timestamp into hourly timestamp

In [13]:
df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)


df["timestamp"] = df["timestamp"].dt.floor("h")

In [14]:
df.head(30)

,sensorId,timestamp,city,humidity,pm10,pm25,pressure,temperature,wind_speed
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.0,16.0,7.0,943.0,12.0,8.3
1,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.0,34.0,16.0,943.0,12.0,8.3
2,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,59.0,35.0,18.0,943.0,12.0,8.3
3,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.0,26.0,10.0,943.0,12.0,9.3
4,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.0,15.0,7.0,943.0,12.0,9.3
5,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,60.0,5.0,2.0,943.0,12.0,9.3
6,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.0,9.0,1.0,943.0,12.0,9.3
7,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.0,11.0,6.0,943.0,12.0,8.3
8,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.0,9.0,3.0,943.0,12.0,8.3
9,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.0,10.0,5.0,942.0,12.0,8.3
10,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.0,10.0,4.0,942.0,13.0,8.3
11,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.0,8.0,4.0,942.0,13.0,9.4
12,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.0,13.0,6.0,942.0,13.0,9.4
13,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,59.0,13.0,6.0,942.0,13.0,9.4
14,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 03:00:00+00:00,bitola,60.0,5.0,2.0,942.0,13.0,9.4
15,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,60.0,5.0,2.0,942.0,13.0,9.0
16,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,59.0,4.0,1.0,942.0,13.0,9.0
17,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,59.0,3.0,1.0,942.0,13.0,9.0
18,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 04:00:00+00:00,bitola,60.0,8.0,4.0,942.0,13.0,9.0
19,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,60.0,4.0,2.0,942.0,13.0,7.6
20,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,60.0,16.0,7.0,942.0,13.0,7.6
21,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,60.0,9.0,4.0,942.0,13.0,7.6
22,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 05:00:00+00:00,bitola,61.0,7.0,3.0,942.0,13.0,7.6
23,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,60.0,3.0,1.0,942.0,13.0,6.8
24,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,59.0,3.0,1.0,942.0,14.0,6.8
25,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,59.0,5.0,3.0,942.0,14.0,6.8
26,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 06:00:00+00:00,bitola,58.0,21.0,10.0,942.0,14.0,6.8
27,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 07:00:00+00:00,bitola,58.0,30.0,15.0,943.0,15.0,12.4
28,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 07:00:00+00:00,bitola,57.0,15.0,8.0,943.0,15.0,12.4
29,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 07:00:00+00:00,bitola,56.0,11.0,3.0,943.0,16.0,12.4

### Hourly aggregation grouped by sensorId and timestamp

In [15]:
df_hourly = (
    df.groupby(["sensorId", "timestamp"])
      .agg({
          "city":"first",
          "humidity":"mean",
          "pm10":"mean",
          "pm25":"mean",
          "pressure":"mean",
          "temperature":"mean",
          "wind_speed":"mean"
      })
      .reset_index()
)

In [16]:
df_hourly = df_hourly.sort_values(by=["timestamp", "sensorId"]).reset_index(drop=True)

In [17]:
df_hourly.head(20)

,sensorId,timestamp,city,humidity,pm10,pm25,pressure,temperature,wind_speed
0,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 00:00:00+00:00,bitola,58.333333,28.333333,13.666667,943.0,12.00,8.3
1,2001,2023-12-01 00:00:00+00:00,bitola,NaN,NaN,9.000000,NaN,NaN,8.3
2,2002,2023-12-01 00:00:00+00:00,bitola,NaN,NaN,27.000000,NaN,NaN,8.3
3,40f081a6-4095-43f7-bffb-64e2af8c026e,2023-12-01 00:00:00+00:00,bitola,61.000000,5.500000,3.000000,942.0,12.00,5.0
4,874ff9c6-786d-45fc-a90e-48c7ffe03417,2023-12-01 00:00:00+00:00,bitola,68.250000,10.750000,3.500000,940.0,10.75,5.0
5,87f82783-853b-417d-8964-b5cf11e44873,2023-12-01 00:00:00+00:00,bitola,67.000000,52.000000,25.500000,943.0,11.00,8.3
6,d851c0b9-990e-41db-9c53-529f88524cf8,2023-12-01 00:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,5.0
7,d851c0b9-990e-41db-9c53-529f88524cf9,2023-12-01 00:00:00+00:00,bitola,61.000000,11.000000,6.000000,935.0,10.00,NaN
8,e20e9778-a020-4b86-932a-b7ab6a713a00,2023-12-01 00:00:00+00:00,bitola,47.000000,28.750000,16.000000,944.0,16.00,8.3
9,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 01:00:00+00:00,bitola,59.250000,13.750000,5.000000,943.0,12.00,9.3
10,2001,2023-12-01 01:00:00+00:00,bitola,NaN,NaN,10.000000,NaN,NaN,9.3
11,2002,2023-12-01 01:00:00+00:00,bitola,NaN,27.000000,23.000000,NaN,NaN,9.3
12,40f081a6-4095-43f7-bffb-64e2af8c026e,2023-12-01 01:00:00+00:00,bitola,62.500000,7.250000,3.250000,942.0,12.00,4.8
13,874ff9c6-786d-45fc-a90e-48c7ffe03417,2023-12-01 01:00:00+00:00,bitola,69.500000,9.250000,2.250000,940.0,11.00,4.8
14,87f82783-853b-417d-8964-b5cf11e44873,2023-12-01 01:00:00+00:00,bitola,67.750000,69.750000,29.500000,943.0,11.00,9.3
15,d851c0b9-990e-41db-9c53-529f88524cf9,2023-12-01 01:00:00+00:00,bitola,62.500000,7.000000,2.500000,935.0,10.00,4.8
16,e20e9778-a020-4b86-932a-b7ab6a713a00,2023-12-01 01:00:00+00:00,bitola,48.666667,23.666667,12.333333,944.0,16.00,9.3
17,16836a55-7140-43e2-9a63-56fac5cba714,2023-12-01 02:00:00+00:00,bitola,60.000000,10.000000,4.500000,942.5,12.25,8.3
18,2001,2023-12-01 02:00:00+00:00,bitola,NaN,NaN,8.000000,NaN,NaN,8.3
19,2002,2023-12-01 02:00:00+00:00,bitola,NaN,19.000000,16.000000,NaN,NaN,8.3

In [18]:
df_hourly['sensorId'].value_counts()

sensorId
40f081a6-4095-43f7-bffb-64e2af8c026e    17338
87f82783-853b-417d-8964-b5cf11e44873    17087
874ff9c6-786d-45fc-a90e-48c7ffe03417    16834
7b316592-8036-41e2-b8dc-b06b6a9afd54    16232
2002                                    15516
2001                                    15173
16836a55-7140-43e2-9a63-56fac5cba714    15021
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    12040
d7060523-b163-4cc3-bc94-970dac72a38a    10931
23b735ef-a996-4a7f-9998-2aa7e78827b0     9538
d241a044-0a06-40c2-9d90-c91fd0a95060     9309
fec52a19-9148-4350-a1b4-ae0da05ee199     9238
e20e9778-a020-4b86-932a-b7ab6a713a00     2526
d851c0b9-990e-41db-9c53-529f88524cf9     2360
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d     1167
87f82783-853b-417d-8964-b5cf11e44872        2
d851c0b9-990e-41db-9c53-529f88524cf8        1
a9a2083f-f086-4fae-bdae-355b391f436b        1
Name: count, dtype: int64

In [19]:
percent_missing = (df_hourly.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

sensorId        0.000000
timestamp       0.000000
city            0.000000
humidity       21.429242
pm10           11.738319
pm25            4.716582
pressure       21.323555
temperature    21.323555
wind_speed      0.002349
dtype: float64

In [20]:
len(df_hourly)

170314

In [21]:
sensor_stats = df_hourly.groupby('sensorId')[['humidity', 'pressure', 'pm10','pm25','temperature']].apply(lambda x: x.isnull().mean())

In [22]:
print(sensor_stats[sensor_stats['humidity'] > 0.9])

                                      humidity  pressure      pm10      pm25  \
sensorId
2001                                       1.0       1.0  0.874448  0.113425
2002                                       1.0       1.0  0.157515  0.131026
87f82783-853b-417d-8964-b5cf11e44872       1.0       1.0  1.000000  1.000000
d851c0b9-990e-41db-9c53-529f88524cf8       1.0       1.0  1.000000  1.000000

                                      temperature
sensorId
2001                                          1.0
2002                                          1.0
87f82783-853b-417d-8964-b5cf11e44872          1.0
d851c0b9-990e-41db-9c53-529f88524cf8          1.0

### Remove the sensors that have 100% missing values for pm10 and pm25

In [23]:
sensor_stats = df_hourly.groupby('sensorId')[['pm10', 'pm25']].count()
valid_sensors = sensor_stats[sensor_stats.sum(axis=1) > 0].index

df_hourly = df_hourly[df_hourly['sensorId'].isin(valid_sensors)]

In [24]:
len(df_hourly)

170311

In [25]:
df_hourly['sensorId'].value_counts()

sensorId
40f081a6-4095-43f7-bffb-64e2af8c026e    17338
87f82783-853b-417d-8964-b5cf11e44873    17087
874ff9c6-786d-45fc-a90e-48c7ffe03417    16834
7b316592-8036-41e2-b8dc-b06b6a9afd54    16232
2002                                    15516
2001                                    15173
16836a55-7140-43e2-9a63-56fac5cba714    15021
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    12040
d7060523-b163-4cc3-bc94-970dac72a38a    10931
23b735ef-a996-4a7f-9998-2aa7e78827b0     9538
d241a044-0a06-40c2-9d90-c91fd0a95060     9309
fec52a19-9148-4350-a1b4-ae0da05ee199     9238
e20e9778-a020-4b86-932a-b7ab6a713a00     2526
d851c0b9-990e-41db-9c53-529f88524cf9     2360
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d     1167
a9a2083f-f086-4fae-bdae-355b391f436b        1
Name: count, dtype: int64

### Remove the sparse sensor

In [26]:
df_hourly = df_hourly[df_hourly['sensorId']!="a9a2083f-f086-4fae-bdae-355b391f436b"]

In [27]:
percent_missing = (df_hourly.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

sensorId        0.000000
timestamp       0.000000
city            0.000000
humidity       21.427984
pm10           11.736833
pm25            4.714932
pressure       21.322295
temperature    21.322295
wind_speed      0.001761
dtype: float64

In [28]:
df_hourly['sensorId'].value_counts()

sensorId
40f081a6-4095-43f7-bffb-64e2af8c026e    17338
87f82783-853b-417d-8964-b5cf11e44873    17087
874ff9c6-786d-45fc-a90e-48c7ffe03417    16834
7b316592-8036-41e2-b8dc-b06b6a9afd54    16232
2002                                    15516
2001                                    15173
16836a55-7140-43e2-9a63-56fac5cba714    15021
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    12040
d7060523-b163-4cc3-bc94-970dac72a38a    10931
23b735ef-a996-4a7f-9998-2aa7e78827b0     9538
d241a044-0a06-40c2-9d90-c91fd0a95060     9309
fec52a19-9148-4350-a1b4-ae0da05ee199     9238
e20e9778-a020-4b86-932a-b7ab6a713a00     2526
d851c0b9-990e-41db-9c53-529f88524cf9     2360
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d     1167
Name: count, dtype: int64

In [29]:
start = df_hourly['timestamp'].min()
end = df_hourly['timestamp'].max()
print(f"Start: {start}")
print(f"End: {end}")

Start: 2023-12-01 00:00:00+00:00
End: 2025-11-30 23:00:00+00:00

### Add the full timeframe for each sensor

In [30]:
processed_dfs = []
for sensor_id, group in df_hourly.groupby('sensorId'):
    group = group.sort_values('timestamp').set_index('timestamp')
    group = group.resample('h').asfreq().reindex(pd.date_range(start, end, freq='h'))
    group['sensorId'] = sensor_id
    processed_dfs.append(group.reset_index())

df_hourly_full = pd.concat(processed_dfs)

In [32]:
df_hourly_full = df_hourly_full.rename(columns={'index': 'timestamp'})

In [33]:
df_hourly_full.columns

Index(['timestamp', 'sensorId', 'city', 'humidity', 'pm10', 'pm25', 'pressure',
       'temperature', 'wind_speed'],
      dtype='object')

In [34]:
df_hourly_full['sensorId'].value_counts()

sensorId
16836a55-7140-43e2-9a63-56fac5cba714    17544
2001                                    17544
2002                                    17544
23b735ef-a996-4a7f-9998-2aa7e78827b0    17544
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    17544
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d    17544
40f081a6-4095-43f7-bffb-64e2af8c026e    17544
7b316592-8036-41e2-b8dc-b06b6a9afd54    17544
874ff9c6-786d-45fc-a90e-48c7ffe03417    17544
87f82783-853b-417d-8964-b5cf11e44873    17544
d241a044-0a06-40c2-9d90-c91fd0a95060    17544
d7060523-b163-4cc3-bc94-970dac72a38a    17544
d851c0b9-990e-41db-9c53-529f88524cf9    17544
e20e9778-a020-4b86-932a-b7ab6a713a00    17544
fec52a19-9148-4350-a1b4-ae0da05ee199    17544
Name: count, dtype: int64

In [35]:
percent_missing = (df_hourly_full.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

timestamp       0.000000
sensorId        0.000000
city           54.518231
humidity       75.946216
pm10           66.255064
pm25           59.233163
pressure       75.840526
temperature    75.840526
wind_speed     54.519993
dtype: float64

### Linear Interpolation process for filling small gaps

In [36]:
df_hourly_full = df_hourly_full.sort_values(['sensorId', 'timestamp'])

cols_to_fix = ['pm10', 'pm25', 'temperature', 'humidity', 'pressure', 'wind_speed']

for col in cols_to_fix:

    df_hourly_full[col] = df_hourly_full.groupby('sensorId')[col].transform(
        lambda x: x.interpolate(method='linear', limit=3)
    )

In [37]:
df_hourly_full['city'] = df_hourly_full['city'].fillna('bitola')

In [38]:
percent_missing = (df_hourly_full.isnull().sum() * 100) / len(df_hourly_full)
print(percent_missing)

timestamp       0.000000
sensorId        0.000000
city            0.000000
humidity       48.582611
pm10           40.917313
pm25           35.528196
pressure       48.548792
temperature    48.548792
wind_speed     33.636571
dtype: float64

In [39]:
len(df_hourly_full)

263160

In [40]:
sensor_stats = df_hourly_full.groupby('sensorId')[['humidity', 'pressure', 'pm10','pm25','temperature']].apply(lambda x: x.isnull().mean())
print(sensor_stats[sensor_stats['humidity'] > 0.5])

                                      humidity  pressure      pm10      pm25  \
sensorId
2001                                  1.000000  1.000000  0.866165  0.062642
2002                                  1.000000  1.000000  0.064295  0.059451
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d  0.929264  0.929264  0.929435  0.929435
d851c0b9-990e-41db-9c53-529f88524cf9  0.865481  0.864626  0.870782  0.870782
e20e9778-a020-4b86-932a-b7ab6a713a00  0.883493  0.883493  0.853739  0.853739

                                      temperature
sensorId
2001                                     1.000000
2002                                     1.000000
30dab8a6-ff63-43ce-9a3b-99f1f3f7054d     0.929264
d851c0b9-990e-41db-9c53-529f88524cf9     0.864626
e20e9778-a020-4b86-932a-b7ab6a713a00     0.883493

### Remove again the sensors that have high percentage of missing values for pm10 and pm25

In [41]:
sensors_to_keep = sensor_stats[(sensor_stats['pm10'] <= 0.8) & (sensor_stats['pm25'] <= 0.8)].index

df_hourly_full = df_hourly_full[df_hourly_full['sensorId'].isin(sensors_to_keep)]

In [42]:
df_hourly_full['sensorId'].value_counts()

sensorId
16836a55-7140-43e2-9a63-56fac5cba714    17544
2002                                    17544
23b735ef-a996-4a7f-9998-2aa7e78827b0    17544
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    17544
40f081a6-4095-43f7-bffb-64e2af8c026e    17544
7b316592-8036-41e2-b8dc-b06b6a9afd54    17544
874ff9c6-786d-45fc-a90e-48c7ffe03417    17544
87f82783-853b-417d-8964-b5cf11e44873    17544
d241a044-0a06-40c2-9d90-c91fd0a95060    17544
d7060523-b163-4cc3-bc94-970dac72a38a    17544
fec52a19-9148-4350-a1b4-ae0da05ee199    17544
Name: count, dtype: int64

In [43]:
percent_missing = (df_hourly_full.isnull().sum() * 100) / len(df_hourly_full)
print(percent_missing)

timestamp       0.000000
sensorId        0.000000
city            0.000000
humidity       32.810492
pm10           23.795237
pm25           23.751192
pressure       32.772147
temperature    32.772147
wind_speed     21.399183
dtype: float64

### Linear interpolation in both directions for filling small gaps again

In [44]:
df_hourly_full = df_hourly_full.sort_values(['sensorId', 'timestamp']).reset_index(drop=True)
df_hourly_full[['pm10','pm25']] = df_hourly_full.groupby('sensorId')[['pm10','pm25']].transform(
    lambda x: x.interpolate(method='linear', limit_direction='both', limit=3)
)

In [45]:
percent_missing = (df_hourly_full.isnull().sum() * 100) / len(df_hourly_full)
print(percent_missing)

timestamp       0.000000
sensorId        0.000000
city            0.000000
humidity       32.810492
pm10           22.866663
pm25           22.857854
pressure       32.772147
temperature    32.772147
wind_speed     21.399183
dtype: float64

### Fill missing weather with the average of all other sensors in Bitola for that specific hour

In [46]:
weather_cols = ['humidity', 'pressure', 'temperature', 'wind_speed']

df_hourly_full[weather_cols] = df_hourly_full[weather_cols].fillna(
    df_hourly_full.groupby('timestamp')[weather_cols].transform('mean')
)

In [47]:
percent_missing = (df_hourly_full.isnull().sum() * 100) / len(df_hourly_full)
print(percent_missing)

timestamp       0.000000
sensorId        0.000000
city            0.000000
humidity        0.233698
pm10           22.866663
pm25           22.857854
pressure        0.233698
temperature     0.233698
wind_speed      0.039900
dtype: float64

### Fill the missing weather values with bfill() and ffill() methods

In [48]:
df_hourly_full[weather_cols] = df_hourly_full.groupby('sensorId')[weather_cols].ffill().bfill()
print(df_hourly_full.isnull().sum())

timestamp          0
sensorId           0
city               0
humidity           0
pm10           44129
pm25           44112
pressure           0
temperature        0
wind_speed         0
dtype: int64

### Linear interpolation for again filling the small gaps

In [49]:
df_hourly_full = df_hourly_full.sort_values(['sensorId', 'timestamp']).reset_index(drop=True)
df_hourly_full[['pm10','pm25']] = df_hourly_full.groupby('sensorId')[['pm10','pm25']].transform(
    lambda x: x.interpolate(method='linear', limit_direction='both', limit=3)
)

In [52]:
df_hourly_full.head(20)

,timestamp,sensorId,city,humidity,pm10,pm25,pressure,temperature,wind_speed
0,2023-12-01 00:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,58.333333,28.333333,13.666667,943.00,12.000000,8.3
1,2023-12-01 01:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.250000,13.750000,5.000000,943.00,12.000000,9.3
2,2023-12-01 02:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,60.000000,10.000000,4.500000,942.50,12.250000,8.3
3,2023-12-01 03:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.250000,9.750000,4.500000,942.00,13.000000,9.4
4,2023-12-01 04:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.500000,5.000000,2.000000,942.00,13.000000,9.0
5,2023-12-01 05:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,60.250000,9.000000,4.000000,942.00,13.000000,7.6
6,2023-12-01 06:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.000000,8.000000,3.750000,942.00,13.750000,6.8
7,2023-12-01 07:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,56.500000,15.500000,7.000000,943.00,15.500000,12.4
8,2023-12-01 08:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,53.666667,7.333333,2.333333,943.00,16.666667,15.6
9,2023-12-01 09:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,51.500000,6.500000,1.750000,943.00,17.250000,18.6
10,2023-12-01 10:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,46.750000,5.250000,1.375000,942.50,18.125000,18.4
11,2023-12-01 11:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,42.000000,4.000000,1.000000,942.00,19.000000,18.2
12,2023-12-01 12:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,41.750000,7.000000,1.250000,941.75,19.500000,18.3
13,2023-12-01 13:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,42.500000,13.500000,1.250000,941.00,19.750000,17.6
14,2023-12-01 14:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,44.333333,6.000000,1.333333,941.00,19.000000,15.0
15,2023-12-01 15:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,46.250000,7.000000,1.500000,941.00,18.500000,12.6
16,2023-12-01 16:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,48.250000,10.250000,1.500000,941.00,18.000000,12.6
17,2023-12-01 17:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,49.500000,16.250000,2.250000,941.00,17.500000,10.4
18,2023-12-01 18:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,49.250000,11.666667,1.666667,941.00,17.000000,9.7
19,2023-12-01 19:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,52.750000,12.000000,2.500000,941.00,16.500000,9.4

In [53]:
df_hourly_full.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed
count,192984.000000,149772.000000,149781.000000,192984.000000,192984.000000,192984.000000
mean,52.712150,26.860537,14.470625,939.805608,16.794952,6.075046
std,15.722700,49.673873,26.783313,12.797334,9.158462,3.743378
min,9.500000,0.000000,0.000000,869.000000,-12.000000,0.000000
25%,40.759259,5.333333,2.333333,937.000000,9.694444,3.500000
50%,53.604167,11.000000,5.750000,942.000000,16.000000,5.300000
75%,64.850000,27.000000,14.500000,946.000000,23.750000,7.740000
max,99.000000,1995.000000,639.250000,971.750000,47.500000,32.800000

In [54]:
len(df_hourly_full)

192984

In [55]:
df_hourly_full['sensorId'].value_counts()

sensorId
16836a55-7140-43e2-9a63-56fac5cba714    17544
2002                                    17544
23b735ef-a996-4a7f-9998-2aa7e78827b0    17544
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    17544
40f081a6-4095-43f7-bffb-64e2af8c026e    17544
7b316592-8036-41e2-b8dc-b06b6a9afd54    17544
874ff9c6-786d-45fc-a90e-48c7ffe03417    17544
87f82783-853b-417d-8964-b5cf11e44873    17544
d241a044-0a06-40c2-9d90-c91fd0a95060    17544
d7060523-b163-4cc3-bc94-970dac72a38a    17544
fec52a19-9148-4350-a1b4-ae0da05ee199    17544
Name: count, dtype: int64

### Load the neighborhood matrix of distances

In [56]:
neighbourhood_matrix = pd.read_csv("data/neighbors_data/bitola_sensor_distances.csv")
neighbourhood_matrix

,sensor_id,neighbor_id,distance_km
0,d241a044-0a06-40c2-9d90-c91fd0a95060,fec52a19-9148-4350-a1b4-ae0da05ee199,7.082000
1,fec52a19-9148-4350-a1b4-ae0da05ee199,d241a044-0a06-40c2-9d90-c91fd0a95060,7.082000
2,d241a044-0a06-40c2-9d90-c91fd0a95060,be427cee-4c3a-4aa2-a1ce-9795a74533be,8.838588
3,be427cee-4c3a-4aa2-a1ce-9795a74533be,d241a044-0a06-40c2-9d90-c91fd0a95060,8.838588
4,d241a044-0a06-40c2-9d90-c91fd0a95060,c3f3da9b-9fd3-4037-94d3-598d655e6be9,10.004966
...,...,...,...
457,7b316592-8036-41e2-b8dc-b06b6a9afd54,40f081a6-4095-43f7-bffb-64e2af8c026e,1.049671
458,40f081a6-4095-43f7-bffb-64e2af8c026e,692c454c-a1ad-41fa-b3ca-aa1cb7d55d30,3.044465
459,692c454c-a1ad-41fa-b3ca-aa1cb7d55d30,40f081a6-4095-43f7-bffb-64e2af8c026e,3.044465
460,7b316592-8036-41e2-b8dc-b06b6a9afd54,692c454c-a1ad-41fa-b3ca-aa1cb7d55d30,2.083640
461,692c454c-a1ad-41fa-b3ca-aa1cb7d55d30,7b316592-8036-41e2-b8dc-b06b6a9afd54,2.083640

In [59]:
valid_sensors = df_hourly_full['sensorId'].unique()

In [60]:
neighbors_df_clean = neighbourhood_matrix[
    (neighbourhood_matrix['sensor_id'].isin(valid_sensors)) &
    (neighbourhood_matrix['neighbor_id'].isin(valid_sensors))
].copy()

### Function for appending neighborhood features in each sensor

In [61]:
def append_neighbors(df_hourly, neighbors_df, weather_cols, k_search=20, k_keep=3):
    # 1. Standardize the neighbor list
    # Ensure we only take the top K based on distance
    neighbors_topk = (
        neighbors_df.sort_values(["sensor_id", "distance_km"])
        .groupby("sensor_id")
        .head(k_search)
        .copy()
    )

    # Track original distance rank
    neighbors_topk['dist_rank'] = neighbors_topk.groupby("sensor_id").cumcount() + 1

    # 2. Merge with main data
    # We use 'neighbor_id' from the matrix to match 'sensorId' in the hourly data
    neighbor_values = neighbors_topk.merge(
        df_hourly[['sensorId', 'timestamp'] + weather_cols],
        left_on='neighbor_id',
        right_on='sensorId',
        how='inner'
    )

    # 3. Filter for availability
    # The 'sensor_id' here is the ORIGINAL sensor we are finding neighbors for
    available_topk = (
        neighbor_values.sort_values(['sensor_id', 'timestamp', 'dist_rank'])
        .groupby(['sensor_id', 'timestamp'])
        .head(k_keep)
        .copy()
    )

    # Create the 1, 2, 3 rank for the wide-format columns
    available_topk['final_rank'] = available_topk.groupby(['sensor_id', 'timestamp']).cumcount() + 1

    # 4. Pivot to wide format
    pivot_df = available_topk.pivot(
        index=['sensor_id', 'timestamp'],
        columns='final_rank',
        values=weather_cols
    )

    # Clean up column names: neighbor1_temp, neighbor2_temp, etc.
    if isinstance(pivot_df.columns, pd.MultiIndex):
        pivot_df.columns = [f"neighbor{rank}_{col}" for col, rank in pivot_df.columns]
    else:
        # Handle case with only one weather column
        pivot_df.columns = [f"neighbor{i}_{weather_cols[0]}" for i in pivot_df.columns]

    pivot_df = pivot_df.reset_index()

    # 5. Final Join back to original data
    df_result = df_hourly.merge(
        pivot_df,
        left_on=['sensorId', 'timestamp'],
        right_on=['sensor_id', 'timestamp'],
        how='left'
    ).drop(columns=['sensor_id'])

    return df_result

In [62]:
weather_cols

['humidity', 'pressure', 'temperature', 'wind_speed']

In [63]:
df_final = append_neighbors(df_hourly_full,neighbors_df_clean, weather_cols)

In [64]:
df_final

,timestamp,sensorId,city,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,...,neighbor3_humidity,neighbor1_pressure,neighbor2_pressure,neighbor3_pressure,neighbor1_temperature,neighbor2_temperature,neighbor3_temperature,neighbor1_wind_speed,neighbor2_wind_speed,neighbor3_wind_speed
0,2023-12-01 00:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,58.333333,28.333333,13.666667,943.0,12.00,8.3,63.645833,...,63.645833,942.000000,942.000000,942.000000,11.437500,11.437500,11.437500,6.98,8.3,6.98
1,2023-12-01 01:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.250000,13.750000,5.000000,943.0,12.00,9.3,64.750000,...,64.750000,942.000000,942.000000,942.000000,11.500000,11.500000,11.500000,7.50,9.3,7.50
2,2023-12-01 02:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,60.000000,10.000000,4.500000,942.5,12.25,8.3,65.312500,...,65.312500,941.812500,941.812500,941.812500,11.625000,11.625000,11.625000,6.74,8.3,6.74
3,2023-12-01 03:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.250000,9.750000,4.500000,942.0,13.00,9.4,64.854167,...,64.854167,941.166667,941.166667,941.166667,12.166667,12.166667,12.166667,7.84,9.4,7.84
4,2023-12-01 04:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.500000,5.000000,2.000000,942.0,13.00,9.0,65.062500,...,65.062500,941.125000,941.125000,941.125000,12.312500,12.312500,12.312500,8.32,9.0,8.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192979,2025-11-30 19:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,bitola,61.750000,11.250000,6.000000,942.0,9.00,5.9,63.500000,...,68.583333,942.250000,940.000000,934.444444,9.000000,6.500000,8.277778,5.30,5.9,5.30
192980,2025-11-30 20:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,bitola,63.250000,9.000000,5.666667,942.0,9.00,5.7,63.750000,...,69.333333,943.000000,940.000000,934.833333,9.000000,6.000000,7.777778,5.40,5.7,5.40
192981,2025-11-30 21:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,bitola,63.500000,12.000000,6.000000,942.5,8.25,5.8,63.333333,...,70.425926,943.000000,940.000000,935.000000,9.000000,6.666667,7.685185,5.40,5.8,5.40
192982,2025-11-30 22:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,bitola,63.750000,3.250000,2.500000,943.0,7.75,5.6,63.750000,...,70.888889,943.000000,941.000000,935.333333,8.250000,6.250000,7.222222,5.00,5.6,5.00
192983,2025-11-30 23:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,bitola,63.750000,1.750000,0.750000,943.0,7.00,6.2,64.000000,...,71.472222,943.250000,941.000000,935.472222,8.000000,6.000000,6.750000,4.90,6.2,4.90

In [65]:
percent_missing = (df_final.isnull().sum() * 100) / len(df_final)
print(percent_missing)

timestamp                 0.000000
sensorId                  0.000000
city                      0.000000
humidity                  0.000000
pm10                     22.391494
pm25                     22.386830
pressure                  0.000000
temperature               0.000000
wind_speed                0.000000
neighbor1_humidity        0.000000
neighbor2_humidity        0.000000
neighbor3_humidity        0.000000
neighbor1_pressure        0.000000
neighbor2_pressure        0.000000
neighbor3_pressure        0.000000
neighbor1_temperature     0.000000
neighbor2_temperature     0.000000
neighbor3_temperature     0.000000
neighbor1_wind_speed      0.000000
neighbor2_wind_speed      0.000000
neighbor3_wind_speed      0.000000
dtype: float64

In [66]:
len(df_final)

192984

In [67]:
df_final['sensorId'].value_counts()

sensorId
16836a55-7140-43e2-9a63-56fac5cba714    17544
2002                                    17544
23b735ef-a996-4a7f-9998-2aa7e78827b0    17544
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    17544
40f081a6-4095-43f7-bffb-64e2af8c026e    17544
7b316592-8036-41e2-b8dc-b06b6a9afd54    17544
874ff9c6-786d-45fc-a90e-48c7ffe03417    17544
87f82783-853b-417d-8964-b5cf11e44873    17544
d241a044-0a06-40c2-9d90-c91fd0a95060    17544
d7060523-b163-4cc3-bc94-970dac72a38a    17544
fec52a19-9148-4350-a1b4-ae0da05ee199    17544
Name: count, dtype: int64

In [68]:
df_final.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor1_pressure,neighbor2_pressure,neighbor3_pressure,neighbor1_temperature,neighbor2_temperature,neighbor3_temperature,neighbor1_wind_speed,neighbor2_wind_speed,neighbor3_wind_speed
count,192984.000000,149772.000000,149781.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000,192984.000000
mean,52.712150,26.860537,14.470625,939.805608,16.794952,6.075046,52.241040,53.628155,51.232897,943.015291,942.100966,942.391155,16.943933,16.704184,17.258902,6.189260,6.173400,6.157256
std,15.722700,49.673873,26.783313,12.797334,9.158462,3.743378,15.767958,16.392558,15.040098,6.651617,6.727275,6.425791,9.132758,9.139144,9.219385,3.863181,3.865857,3.848838
min,9.500000,0.000000,0.000000,869.000000,-12.000000,0.000000,9.500000,9.500000,9.500000,911.000000,911.000000,916.400000,-12.000000,-12.000000,-12.000000,0.000000,0.000000,0.000000
25%,40.759259,5.333333,2.333333,937.000000,9.694444,3.500000,40.466667,41.333333,39.750000,939.000000,938.000000,938.200000,9.937500,9.583333,10.000000,3.500000,3.500000,3.500000
50%,53.604167,11.000000,5.750000,942.000000,16.000000,5.300000,53.000000,54.495833,52.250000,943.000000,942.000000,942.000000,16.000000,16.000000,16.370370,5.400000,5.400000,5.400000
75%,64.850000,27.000000,14.500000,946.000000,23.750000,7.740000,64.250000,66.000000,63.000000,947.000000,946.000000,946.000000,24.000000,23.500000,24.083333,7.900000,7.900000,7.900000
max,99.000000,1995.000000,639.250000,971.750000,47.500000,32.800000,99.000000,99.000000,86.750000,971.750000,971.750000,971.750000,47.500000,45.500000,47.500000,32.800000,32.800000,32.800000

### Function for extracting time features

In [69]:
def extract_time_features(df, timestamp_col='timestamp'):


    # 1. Cyclic Hour (24-hour cycle) //
    df['hour_sin'] = np.sin(2 * np.pi * df[timestamp_col].dt.hour / 24)
    df['hour_cos'] = np.cos(2 * np.pi * df[timestamp_col].dt.hour / 24)

    # 2. Cyclic Month (12-month cycle)//
    df['month_sin'] = np.sin(2 * np.pi * (df[timestamp_col].dt.month - 1) / 12)
    df['month_cos'] = np.cos(2 * np.pi * (df[timestamp_col].dt.month - 1) / 12)

    # 3. Weekend Flag
    # Monday=0, Sunday=6. Weekends are 5 and 6.
    df['is_weekend'] = df[timestamp_col].dt.dayofweek.isin([5, 6]).astype(int)

    # 4. Heating Season Flag (Specific for Bitola/Macedonia)
    # Most wood burning occurs from November (11) to March (3)
    df['is_heating_season'] = df[timestamp_col].dt.month.isin([11, 12, 1, 2, 3]).astype(int)

    return df

In [70]:
df_final = extract_time_features(df_final)

In [71]:
df_final.head(20)

,timestamp,sensorId,city,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,...,neighbor3_temperature,neighbor1_wind_speed,neighbor2_wind_speed,neighbor3_wind_speed,hour_sin,hour_cos,month_sin,month_cos,is_weekend,is_heating_season
0,2023-12-01 00:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,58.333333,28.333333,13.666667,943.00,12.000000,8.3,63.645833,...,11.437500,6.98,8.3,6.98,0.000000e+00,1.000000e+00,-0.5,0.866025,0,1
1,2023-12-01 01:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.250000,13.750000,5.000000,943.00,12.000000,9.3,64.750000,...,11.500000,7.50,9.3,7.50,2.588190e-01,9.659258e-01,-0.5,0.866025,0,1
2,2023-12-01 02:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,60.000000,10.000000,4.500000,942.50,12.250000,8.3,65.312500,...,11.625000,6.74,8.3,6.74,5.000000e-01,8.660254e-01,-0.5,0.866025,0,1
3,2023-12-01 03:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.250000,9.750000,4.500000,942.00,13.000000,9.4,64.854167,...,12.166667,7.84,9.4,7.84,7.071068e-01,7.071068e-01,-0.5,0.866025,0,1
4,2023-12-01 04:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.500000,5.000000,2.000000,942.00,13.000000,9.0,65.062500,...,12.312500,8.32,9.0,8.32,8.660254e-01,5.000000e-01,-0.5,0.866025,0,1
5,2023-12-01 05:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,60.250000,9.000000,4.000000,942.00,13.000000,7.6,66.500000,...,12.437500,6.28,7.6,6.28,9.659258e-01,2.588190e-01,-0.5,0.866025,0,1
6,2023-12-01 06:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,59.000000,8.000000,3.750000,942.00,13.750000,6.8,66.187500,...,12.625000,5.16,6.8,5.16,1.000000e+00,6.123234e-17,-0.5,0.866025,0,1
7,2023-12-01 07:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,56.500000,15.500000,7.000000,943.00,15.500000,12.4,63.250000,...,14.375000,8.72,12.4,8.72,9.659258e-01,-2.588190e-01,-0.5,0.866025,0,1
8,2023-12-01 08:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,53.666667,7.333333,2.333333,943.00,16.666667,15.6,59.708333,...,15.750000,11.40,15.6,11.40,8.660254e-01,-5.000000e-01,-0.5,0.866025,0,1
9,2023-12-01 09:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,51.500000,6.500000,1.750000,943.00,17.250000,18.6,55.062500,...,16.875000,14.72,18.6,14.72,7.071068e-01,-7.071068e-01,-0.5,0.866025,0,1
10,2023-12-01 10:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,46.750000,5.250000,1.375000,942.50,18.125000,18.4,44.979167,...,19.197917,15.36,19.2,15.36,5.000000e-01,-8.660254e-01,-0.5,0.866025,0,1
11,2023-12-01 11:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,42.000000,4.000000,1.000000,942.00,19.000000,18.2,44.562500,...,19.812500,14.80,18.2,14.80,2.588190e-01,-9.659258e-01,-0.5,0.866025,0,1
12,2023-12-01 12:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,41.750000,7.000000,1.250000,941.75,19.500000,18.3,43.062500,...,19.875000,14.90,18.3,14.90,1.224647e-16,-1.000000e+00,-0.5,0.866025,0,1
13,2023-12-01 13:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,42.500000,13.500000,1.250000,941.00,19.750000,17.6,44.312500,...,19.687500,13.84,17.6,13.84,-2.588190e-01,-9.659258e-01,-0.5,0.866025,0,1
14,2023-12-01 14:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,44.333333,6.000000,1.333333,941.00,19.000000,15.0,46.458333,...,18.875000,11.28,15.0,11.28,-5.000000e-01,-8.660254e-01,-0.5,0.866025,0,1
15,2023-12-01 15:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,46.250000,7.000000,1.500000,941.00,18.500000,12.6,48.187500,...,18.187500,10.36,12.6,10.36,-7.071068e-01,-7.071068e-01,-0.5,0.866025,0,1
16,2023-12-01 16:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,48.250000,10.250000,1.500000,941.00,18.000000,12.6,50.875000,...,17.625000,10.44,12.6,10.44,-8.660254e-01,-5.000000e-01,-0.5,0.866025,0,1
17,2023-12-01 17:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,49.500000,16.250000,2.250000,941.00,17.500000,10.4,54.000000,...,16.875000,8.84,10.4,8.84,-9.659258e-01,-2.588190e-01,-0.5,0.866025,0,1
18,2023-12-01 18:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,49.250000,11.666667,1.666667,941.00,17.000000,9.7,55.770833,...,16.166667,8.30,9.7,8.30,-1.000000e+00,-1.836970e-16,-0.5,0.866025,0,1
19,2023-12-01 19:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,bitola,52.750000,12.000000,2.500000,941.00,16.500000,9.4,57.062500,...,15.750000,8.28,9.4,8.28,-9.659258e-01,2.588190e-01,-0.5,0.866025,0,1

In [73]:
df_final.isnull().sum()

timestamp                    0
sensorId                     0
city                         0
humidity                     0
pm10                     43212
pm25                     43203
pressure                     0
temperature                  0
wind_speed                   0
neighbor1_humidity           0
neighbor2_humidity           0
neighbor3_humidity           0
neighbor1_pressure           0
neighbor2_pressure           0
neighbor3_pressure           0
neighbor1_temperature        0
neighbor2_temperature        0
neighbor3_temperature        0
neighbor1_wind_speed         0
neighbor2_wind_speed         0
neighbor3_wind_speed         0
hour_sin                     0
hour_cos                     0
month_sin                    0
month_cos                    0
is_weekend                   0
is_heating_season            0
dtype: int64

In [74]:
df_final.to_csv("data/training/bitola_final_data.csv", index=False)