In [1]:
%pip install -U \
  "autogluon.timeseries==1.5.0" \
  "torch>=2.6.0" \
  "torchvision>=0.21.0" \
  "torchaudio>=2.6.0" \
  "transformers>=4.48.0" \
  "tokenizers>=0.21.0" \
  "numpy==1.26.4"

Requirement already satisfied: autogluon.timeseries==1.5.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (1.5.0)
Requirement already satisfied: torch>=2.6.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (2.9.1)
Collecting torch>=2.6.0
  Downloading torch-2.12.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (31 kB)
Requirement already satisfied: torchvision>=0.21.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (0.24.1)
Collecting torchvision>=0.21.0
  Downloading torchvision-0.27.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (5.5 kB)
Requirement already satisfied: torchaudio>=2.6.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (2.11.0)
Requirement already satisfied: transformers>=4.48.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (4.57.6)
Collecting transformers>=4.48.0
  Downloading transformers-5.13.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: tokenizers>=0.21.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (0.22.2)
Collecting tokenizers>=0.21.0
  Using cached tokenizers-0.23.1-cp310-abi3-macosx_11_0_arm64.whl.metadata (9.8 kB)
Requirement already satisfied: numpy==1.26.4 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (1.26.4)
Requirement already satisfied: joblib<1.7,>=1.2 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (1.5.3)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (1.16.3)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (2.3.3)
Requirement already satisfied: lightning<2.6,>=2.5.1 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (2.5.6)
Requirement already satisfied: accelerate<2.0,>=0.34.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (1.13.0)
Requirement already satisfied: gluonts<0.17,>=0.15.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (0.16.2)
Requirement already satisfied: networkx<4,>=3.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (3.6.1)
Requirement already satisfied: statsforecast<2.0.2,>=1.7.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (2.0.1)
Requirement already satisfied: mlforecast<0.15.0,>=0.14.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (0.14.0)
Requirement already satisfied: utilsforecast<0.2.12,>=0.2.3 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (0.2.11)
Requirement already satisfied: coreforecast<0.0.17,>=0.0.12 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (0.0.16)
Requirement already satisfied: fugue>=0.9.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (0.9.7)
Requirement already satisfied: tqdm<5,>=4.38 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (4.67.3)
Requirement already satisfied: orjson~=3.9 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (3.11.9)
Requirement already satisfied: einops<1,>=0.7 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (0.8.2)
Requirement already satisfied: chronos-forecasting<2.4,>=2.2.2 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (2.2.2)
Requirement already satisfied: peft<0.18,>=0.13.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (0.17.1)
Requirement already satisfied: tensorboard<3,>=2.9 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (2.20.0)
Requirement already satisfied: autogluon.core==1.5.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (1.5.0)
Requirement already satisfied: autogluon.common==1.5.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (1.5.0)
Requirement already satisfied: autogluon.features==1.5.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.timeseries==1.5.0) (1.5.0)
Requirement already satisfied: autogluon.tabular==1.5.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (1.5.0)
Requirement already satisfied: pyarrow<21.0.0,>=7.0.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (20.0.0)
Requirement already satisfied: boto3<2,>=1.10 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (1.43.6)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (7.1.3)
Requirement already satisfied: requests in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (2.33.1)
Requirement already satisfied: pyyaml>=5.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (6.0.3)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (1.7.2)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (3.10.9)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (4.6.0)
Requirement already satisfied: catboost<1.3,>=1.2 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (1.2.10)
Requirement already satisfied: xgboost<3.2,>=2.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (3.1.3)
Requirement already satisfied: filelock in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from torch>=2.6.0) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from torch>=2.6.0) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from torch>=2.6.0) (1.14.0)
Requirement already satisfied: jinja2 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from torch>=2.6.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from torch>=2.6.0) (2026.4.0)
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchvision>=0.21.0
  Downloading torchvision-0.27.0-cp311-cp311-macosx_14_0_arm64.whl.metadata (5.5 kB)
  Using cached torchvision-0.26.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.5 kB)
  Using cached torchvision-0.25.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.4 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from torchvision>=0.21.0) (12.2.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from transformers>=4.48.0) (0.36.2)
Requirement already satisfied: packaging>=20.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from transformers>=4.48.0) (26.2)
Requirement already satisfied: regex!=2019.12.17 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from transformers>=4.48.0) (2026.4.4)
Requirement already satisfied: safetensors>=0.4.3 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from transformers>=4.48.0) (0.7.0)
Requirement already satisfied: triad>=1.0.1 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from fugue>=0.9.0->autogluon.timeseries==1.5.0) (1.0.2)
Requirement already satisfied: adagio>=0.2.6 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from fugue>=0.9.0->autogluon.timeseries==1.5.0) (0.2.6)
Requirement already satisfied: pydantic<3,>=1.7 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0) (2.13.4)
Requirement already satisfied: toolz~=0.10 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0) (0.12.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers>=4.48.0) (1.5.0)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (0.15.3)
Requirement already satisfied: torchmetrics<3.0,>0.7.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (1.9.0)
Requirement already satisfied: pytorch-lightning in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (2.6.1)
Requirement already satisfied: cloudpickle in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (3.1.2)
Requirement already satisfied: numba in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (0.65.1)
Requirement already satisfied: optuna in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (4.8.0)
Requirement already satisfied: window-ops in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (0.0.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from pandas<2.4.0,>=2.0.0->autogluon.timeseries==1.5.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from pandas<2.4.0,>=2.0.0->autogluon.timeseries==1.5.0) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from pandas<2.4.0,>=2.0.0->autogluon.timeseries==1.5.0) (2026.2)
Requirement already satisfied: statsmodels>=0.13.2 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from statsforecast<2.0.2,>=1.7.0->autogluon.timeseries==1.5.0) (0.14.6)
Requirement already satisfied: threadpoolctl>=3 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from statsforecast<2.0.2,>=1.7.0->autogluon.timeseries==1.5.0) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from sympy>=1.13.3->torch>=2.6.0) (1.3.0)
Requirement already satisfied: absl-py>=0.4 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (3.10.2)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (7.34.1)
Requirement already satisfied: setuptools>=41.0.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (65.5.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from tensorboard<3,>=2.9->autogluon.timeseries==1.5.0) (3.1.8)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from transformers[sentencepiece]<4.58,>=4.51.0->autogluon.timeseries==1.5.0) (0.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from jinja2->torch>=2.6.0) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from requests->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from requests->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from requests->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from requests->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (2026.4.22)
Requirement already satisfied: botocore<1.44.0,>=1.43.6 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from boto3<2,>=1.10->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (1.43.6)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from boto3<2,>=1.10->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (1.1.0)
Requirement already satisfied: s3transfer<0.18.0,>=0.17.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from boto3<2,>=1.10->autogluon.common==1.5.0->autogluon.timeseries==1.5.0) (0.17.0)
Requirement already satisfied: graphviz in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from catboost<1.3,>=1.2->autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (0.21)
Requirement already satisfied: plotly in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from catboost<1.3,>=1.2->autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (6.7.0)
Requirement already satisfied: six in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from catboost<1.3,>=1.2->autogluon.tabular[catboost,lightgbm,xgboost]==1.5.0->autogluon.timeseries==1.5.0) (1.17.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from fsspec[http]<2027.0,>=2022.5.0->lightning<2.6,>=2.5.1->autogluon.timeseries==1.5.0) (3.13.5)
Requirement already satisfied: contourpy>=1.0.1 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (1.5.0)
Requirement already satisfied: pyparsing>=3 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.timeseries==1.5.0) (3.3.2)
Requirement already satisfied: llvmlite<0.48,>=0.47.0dev0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from numba->mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (0.47.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from pydantic<3,>=1.7->gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from pydantic<3,>=1.7->gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from pydantic<3,>=1.7->gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0) (0.4.2)
Requirement already satisfied: patsy>=0.5.6 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from statsmodels>=0.13.2->statsforecast<2.0.2,>=1.7.0->autogluon.timeseries==1.5.0) (1.0.2)
Requirement already satisfied: alembic>=1.5.0 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from optuna->mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (1.18.4)
Requirement already satisfied: colorlog in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from optuna->mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /Users/jovan/Documents/Kodovi/RNMP/Project/venv/lib/python3.11/site-packages (from optuna->mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0) (2.0.49)

In [2]:
import pandas as pd
import numpy as np
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
from sklearn.metrics import r2_score,mean_squared_error

In [3]:
df = pd.read_csv("../data/training/bitola_final_data.csv")
df.head()

,timestamp,sensorId,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,...,neighbor3_wind_speed,season,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
0,2023-12-01 00:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,58.333333,28.333333,13.666667,943.0,12.00,8.3,63.645833,63.645833,...,6.98,winter,0.000000,1.000000,-0.5,0.866025,-0.433884,-0.900969,0,1
1,2023-12-01 01:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,59.250000,13.750000,5.000000,943.0,12.00,9.3,64.750000,64.750000,...,7.50,winter,0.258819,0.965926,-0.5,0.866025,-0.433884,-0.900969,0,1
2,2023-12-01 02:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,60.000000,10.000000,4.500000,942.5,12.25,8.3,65.312500,65.312500,...,6.74,winter,0.500000,0.866025,-0.5,0.866025,-0.433884,-0.900969,0,1
3,2023-12-01 03:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,59.250000,9.750000,4.500000,942.0,13.00,9.4,64.854167,64.854167,...,7.84,winter,0.707107,0.707107,-0.5,0.866025,-0.433884,-0.900969,0,1
4,2023-12-01 04:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,59.500000,5.000000,2.000000,942.0,13.00,9.0,65.062500,65.062500,...,8.32,winter,0.866025,0.500000,-0.5,0.866025,-0.433884,-0.900969,0,1

In [4]:
df.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor1_pressure,...,neighbor2_wind_speed,neighbor3_wind_speed,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
count,192533.000000,142475.00000,142887.000000,192533.000000,192533.000000,192907.000000,192533.000000,192533.000000,192533.000000,192533.000000,...,192907.000000,192907.000000,1.929840e+05,1.929840e+05,192984.000000,1.929840e+05,192984.000000,192984.000000,192984.000000,192984.000000
mean,52.706427,26.40624,14.096921,939.802395,16.796424,6.075865,52.234773,53.623165,51.226443,943.013828,...,6.174232,6.158097,-1.845999e-17,-5.550655e-17,-0.002785,-3.554140e-03,-0.002997,-0.000684,0.287278,0.414501
std,15.739595,49.61000,26.306709,12.804769,9.168444,3.743897,15.784644,16.410186,15.056326,6.656861,...,3.866399,3.849372,7.071086e-01,7.071086e-01,0.706861,7.073415e-01,0.707344,0.706866,0.452493,0.492637
min,9.500000,0.00000,0.000000,869.000000,-12.000000,0.000000,9.500000,9.500000,9.500000,911.000000,...,0.000000,0.000000,-1.000000e+00,-1.000000e+00,-1.000000,-1.000000e+00,-0.974928,-0.900969,0.000000,0.000000
25%,40.750000,5.25000,2.250000,937.000000,9.666667,3.500000,40.354167,41.314815,39.750000,939.000000,...,3.500000,3.500000,-7.071068e-01,-7.071068e-01,-0.500000,-8.660254e-01,-0.781831,-0.900969,0.000000,0.000000
50%,53.562500,10.75000,5.500000,942.000000,16.000000,5.300000,53.000000,54.468750,52.250000,943.000000,...,5.400000,5.400000,6.123234e-17,-6.123234e-17,0.000000,-1.836970e-16,0.000000,-0.222521,0.000000,0.000000
75%,64.937500,26.00000,14.000000,946.000000,23.750000,7.744444,64.250000,66.000000,63.000000,947.000000,...,7.900000,7.900000,7.071068e-01,7.071068e-01,0.866025,5.000000e-01,0.781831,0.623490,1.000000,1.000000
max,99.000000,1995.00000,639.250000,971.750000,47.500000,32.800000,99.000000,99.000000,86.750000,971.750000,...,32.800000,32.800000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,0.974928,1.000000,1.000000,1.000000

In [5]:
len(df)

192984

In [6]:
df['sensorId'].value_counts()

sensorId
16836a55-7140-43e2-9a63-56fac5cba714    17544
2002                                    17544
23b735ef-a996-4a7f-9998-2aa7e78827b0    17544
2819ecbb-5de3-4092-aa1d-4ba3a8c40add    17544
40f081a6-4095-43f7-bffb-64e2af8c026e    17544
7b316592-8036-41e2-b8dc-b06b6a9afd54    17544
874ff9c6-786d-45fc-a90e-48c7ffe03417    17544
87f82783-853b-417d-8964-b5cf11e44873    17544
d241a044-0a06-40c2-9d90-c91fd0a95060    17544
d7060523-b163-4cc3-bc94-970dac72a38a    17544
fec52a19-9148-4350-a1b4-ae0da05ee199    17544
Name: count, dtype: int64

In [7]:
TARGET = 'pm10'
ID_COL = 'sensorId'
TIME_COL = 'timestamp'
PREDICTION_LENGTH = 512

In [8]:
df[TIME_COL] = pd.to_datetime(df[TIME_COL])

In [9]:
df[TIME_COL] = df[TIME_COL].dt.tz_convert(None)

In [10]:
print(df["timestamp"].dtype)

datetime64[ns]

In [11]:
data = TimeSeriesDataFrame.from_data_frame(
    df,
    id_column=ID_COL,
    timestamp_column=TIME_COL
)

In [12]:
data.columns

Index(['humidity', 'pm10', 'pm25', 'pressure', 'temperature', 'wind_speed',
       'neighbor1_humidity', 'neighbor2_humidity', 'neighbor3_humidity',
       'neighbor1_pressure', 'neighbor2_pressure', 'neighbor3_pressure',
       'neighbor1_temperature', 'neighbor2_temperature',
       'neighbor3_temperature', 'neighbor1_wind_speed', 'neighbor2_wind_speed',
       'neighbor3_wind_speed', 'season', 'hour_sin', 'hour_cos', 'month_sin',
       'month_cos', 'day_sin', 'day_cos', 'is_weekend', 'is_heating_season'],
      dtype='object')

In [13]:
train_data, test_data = data.train_test_split(prediction_length=PREDICTION_LENGTH)

In [14]:
forecast_columns  = [ elem for elem in data.columns if elem not in ['pm10','pm25']]
forecast_columns

['humidity',
 'pressure',
 'temperature',
 'wind_speed',
 'neighbor1_humidity',
 'neighbor2_humidity',
 'neighbor3_humidity',
 'neighbor1_pressure',
 'neighbor2_pressure',
 'neighbor3_pressure',
 'neighbor1_temperature',
 'neighbor2_temperature',
 'neighbor3_temperature',
 'neighbor1_wind_speed',
 'neighbor2_wind_speed',
 'neighbor3_wind_speed',
 'season',
 'hour_sin',
 'hour_cos',
 'month_sin',
 'month_cos',
 'day_sin',
 'day_cos',
 'is_weekend',
 'is_heating_season']

In [15]:
predictor = TimeSeriesPredictor(
    target= TARGET,
    prediction_length=PREDICTION_LENGTH,
    eval_metric="MASE",
    known_covariates_names=forecast_columns
)

In [16]:
predictor.fit(
    train_data,
    presets="chronos2",   # or "chronos2_small" for faster training
    time_limit=300,
    verbosity=2
)

Beginning AutoGluon training... Time limit = 300s
AutoGluon will save models to '/mnt/c/Users/RazorVision/Desktop/project-vrnmp/offline-Phase/AutogluonModels/ag-20260715_114407'
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025
CPU Count:          16
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 12.00/12.00 GB
Total GPU Memory:   Free: 12.00 GB, Allocated: 0.00 GB, Total: 12.00 GB
GPU Count:          1
Memory Avail:       9.57 GB / 15.58 GB (61.4%)
Disk Space Avail:   49.21 GB / 464.89 GB (10.6%)
===================================================
Setting presets to: chronos2

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': MASE,
 'hyperparameters': {'Chronos2': {'model_path': 'autogluon/chronos-2'}},
 'known_covariates_names': ['humidity',
                            'pressure',
                            'temperature',
                            'wind_speed',
                            'neighbor1_humidity',
                            'neighbor2_humidity',
                            'neighbor3_humidity',
                            'neighbor1_pressure',
                            'neighbor2_pressure',
                            'neighbor3_pressure',
                            'neighbor1_temperature',
                            'neighbor2_temperature',
                            'neighbor3_temperature',
                            'neighbor1_wind_speed',
                            'neighbor2_wind_speed',
                            'neighbor3_wind_speed',
                            'season',
                            'hour_sin',
                            'hour_cos',
                            'month_sin',
                            'month_cos',
                            'day_sin',
                            'day_cos',
                            'is_weekend',
                            'is_heating_season'],
 'num_val_windows': 1,
 'prediction_length': 512,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': True,
 'target': 'pm10',
 'time_limit': 300,
 'verbosity': 2}

Inferred time series frequency: 'h'
Provided train_data has 187352 rows (NaN fraction=26.8%), 11 time series. Median time series length is 17032 (min=17032, max=17032).

Provided data contains following columns:
	target: 'pm10'
	known_covariates:
		categorical:        ['season']
		continuous (float): ['humidity', 'pressure', 'temperature', 'wind_speed', 'neighbor1_humidity', 'neighbor2_humidity', ...]
	past_covariates:
		categorical:        []
		continuous (float): ['pm25']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'MASE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-07-15 13:44:31
Models that will be trained: ['Chronos2']
Training timeseries model Chronos2. Training for up to 277.2s of the 277.2s of remaining time.
	44.34   s     = Training runtime
Training complete. Models trained: ['Chronos2']
Total runtime: 44.55 s
Best model: Chronos2

In [17]:
forecast_df = pd.read_csv('../data/raw/bitola_forecast_weather.csv')
forecast_df

,timestamp,sensorId,humidity,pressure,temperature,wind_speed
0,2025-11-09 16:00:00,16836a55-7140-43e2-9a63-56fac5cba714,88,944.7,12.5,7.1
1,2025-11-09 17:00:00,16836a55-7140-43e2-9a63-56fac5cba714,90,944.7,12.1,7.1
2,2025-11-09 18:00:00,16836a55-7140-43e2-9a63-56fac5cba714,91,944.5,12.0,6.2
3,2025-11-09 19:00:00,16836a55-7140-43e2-9a63-56fac5cba714,91,944.9,12.0,5.8
4,2025-11-09 20:00:00,16836a55-7140-43e2-9a63-56fac5cba714,93,944.8,11.8,5.8
...,...,...,...,...,...,...
59285,2026-03-01 18:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,51,950.9,7.6,7.4
59286,2026-03-01 19:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,56,950.7,6.5,6.2
59287,2026-03-01 20:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,56,951.1,5.8,6.8
59288,2026-03-01 21:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,58,951.2,5.2,6.9
59289,2026-03-01 22:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,58,950.8,4.7,7.0

In [18]:
neighbourhood_matrix = pd.read_csv('../data/neighbors_data/bitola_sensor_distances.csv')

In [19]:
valid_sensors = df['sensorId'].unique()

In [20]:
neighbors_df_clean = neighbourhood_matrix[
    (neighbourhood_matrix['sensor_id'].isin(valid_sensors)) &
    (neighbourhood_matrix['neighbor_id'].isin(valid_sensors))
].copy()

In [21]:
def append_neighbors(df_hourly, neighbors_df, weather_cols, k_search=20, k_keep=3):
    # 1. Standardize the neighbor list
    # Ensure we only take the top K based on distance
    neighbors_topk = (
        neighbors_df.sort_values(["sensor_id", "distance_km"])
        .groupby("sensor_id")
        .head(k_search)
        .copy()
    )

    # Track original distance rank
    neighbors_topk['dist_rank'] = neighbors_topk.groupby("sensor_id").cumcount() + 1

    # 2. Merge with main data
    # We use 'neighbor_id' from the matrix to match 'sensorId' in the hourly data
    neighbor_values = neighbors_topk.merge(
        df_hourly[['sensorId', 'timestamp'] + weather_cols],
        left_on='neighbor_id',
        right_on='sensorId',
        how='inner'
    )

    # 3. Filter for availability
    # The 'sensor_id' here is the ORIGINAL sensor we are finding neighbors for
    available_topk = (
        neighbor_values.sort_values(['sensor_id', 'timestamp', 'dist_rank'])
        .groupby(['sensor_id', 'timestamp'])
        .head(k_keep)
        .copy()
    )

    # Create the 1, 2, 3 rank for the wide-format columns
    available_topk['final_rank'] = available_topk.groupby(['sensor_id', 'timestamp']).cumcount() + 1

    # 4. Pivot to wide format
    pivot_df = available_topk.pivot(
        index=['sensor_id', 'timestamp'],
        columns='final_rank',
        values=weather_cols
    )

    # Clean up column names: neighbor1_temp, neighbor2_temp, etc.
    if isinstance(pivot_df.columns, pd.MultiIndex):
        pivot_df.columns = [f"neighbor{rank}_{col}" for col, rank in pivot_df.columns]
    else:
        # Handle case with only one weather column
        pivot_df.columns = [f"neighbor{i}_{weather_cols[0]}" for i in pivot_df.columns]

    pivot_df = pivot_df.reset_index()

    # 5. Final Join back to original data
    df_result = df_hourly.merge(
        pivot_df,
        left_on=['sensorId', 'timestamp'],
        right_on=['sensor_id', 'timestamp'],
        how='left'
    ).drop(columns=['sensor_id'])

    return df_result

In [22]:
weather_cols = ['humidity', 'pressure', 'temperature', 'wind_speed']

In [23]:
forecast_df = append_neighbors(forecast_df,neighbors_df_clean, weather_cols)
forecast_df

,timestamp,sensorId,humidity,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor1_pressure,neighbor2_pressure,neighbor3_pressure,neighbor1_temperature,neighbor2_temperature,neighbor3_temperature,neighbor1_wind_speed,neighbor2_wind_speed,neighbor3_wind_speed
0,2025-11-09 16:00:00,16836a55-7140-43e2-9a63-56fac5cba714,88,944.7,12.5,7.1,92.0,88.0,92.0,942.4,944.9,945.4,11.9,12.5,12.1,4.0,7.1,4.0
1,2025-11-09 17:00:00,16836a55-7140-43e2-9a63-56fac5cba714,90,944.7,12.1,7.1,87.0,90.0,87.0,942.4,945.0,945.4,11.8,12.1,12.0,2.8,7.1,2.8
2,2025-11-09 18:00:00,16836a55-7140-43e2-9a63-56fac5cba714,91,944.5,12.0,6.2,93.0,91.0,93.0,942.2,944.8,945.2,11.4,12.0,11.6,3.9,6.2,3.9
3,2025-11-09 19:00:00,16836a55-7140-43e2-9a63-56fac5cba714,91,944.9,12.0,5.8,95.0,91.0,95.0,942.6,945.1,945.5,11.3,12.0,11.5,2.9,5.8,2.9
4,2025-11-09 20:00:00,16836a55-7140-43e2-9a63-56fac5cba714,93,944.8,11.8,5.8,98.0,93.0,98.0,942.5,945.0,945.5,11.1,11.8,11.3,3.8,5.8,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59285,2026-03-01 18:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,51,950.9,7.6,7.4,44.0,51.0,44.0,953.1,949.3,953.3,7.9,7.5,7.9,5.9,7.4,5.9
59286,2026-03-01 19:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,56,950.7,6.5,6.2,52.0,56.0,52.0,953.0,949.1,953.2,7.1,6.4,7.1,4.5,6.2,4.5
59287,2026-03-01 20:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,56,951.1,5.8,6.8,56.0,56.0,56.0,953.4,949.4,953.6,6.2,5.7,6.2,4.9,6.8,4.9
59288,2026-03-01 21:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,58,951.2,5.2,6.9,59.0,58.0,59.0,953.6,949.6,953.8,5.4,5.1,5.4,4.6,6.9,4.6
59289,2026-03-01 22:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,58,950.8,4.7,7.0,60.0,58.0,60.0,953.1,949.2,953.3,4.6,4.6,4.6,4.4,7.0,4.4

In [24]:
def extract_time_features(df, timestamp_col='timestamp'):
    
    month = df[timestamp_col].dt.month

    df['season'] = np.select(
        [
            month.isin([12, 1, 2]),
            month.isin([3, 4, 5]),
            month.isin([6, 7, 8]),
            month.isin([9, 10, 11])
        ],
        [
            'winter',
            'spring',
            'summer',
            'autumn'
        ]
    )

    df['hour_sin'] = np.sin(2 * np.pi * df[timestamp_col].dt.hour / 24)
    df['hour_cos'] = np.cos(2 * np.pi * df[timestamp_col].dt.hour / 24)


    df['month_sin'] = np.sin(2 * np.pi * (df[timestamp_col].dt.month - 1) / 12)
    df['month_cos'] = np.cos(2 * np.pi * (df[timestamp_col].dt.month - 1) / 12)
    
    df['day_sin'] = np.sin(2 * np.pi * df[timestamp_col].dt.dayofweek / 7)
    df['day_cos'] = np.cos(2 * np.pi * df[timestamp_col].dt.dayofweek / 7)


    df['is_weekend'] = df[timestamp_col].dt.dayofweek.isin([5, 6]).astype(int)

    df['is_heating_season'] = df[timestamp_col].dt.month.isin([11, 12, 1, 2, 3]).astype(int)

    return df

In [25]:
forecast_df['timestamp'] = pd.to_datetime(forecast_df['timestamp'])
forecast_df = extract_time_features(forecast_df)
forecast_df

,timestamp,sensorId,humidity,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor1_pressure,...,neighbor3_wind_speed,season,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
0,2025-11-09 16:00:00,16836a55-7140-43e2-9a63-56fac5cba714,88,944.7,12.5,7.1,92.0,88.0,92.0,942.4,...,4.0,autumn,-0.866025,-5.000000e-01,-0.866025,0.5,-0.781831,0.62349,1,1
1,2025-11-09 17:00:00,16836a55-7140-43e2-9a63-56fac5cba714,90,944.7,12.1,7.1,87.0,90.0,87.0,942.4,...,2.8,autumn,-0.965926,-2.588190e-01,-0.866025,0.5,-0.781831,0.62349,1,1
2,2025-11-09 18:00:00,16836a55-7140-43e2-9a63-56fac5cba714,91,944.5,12.0,6.2,93.0,91.0,93.0,942.2,...,3.9,autumn,-1.000000,-1.836970e-16,-0.866025,0.5,-0.781831,0.62349,1,1
3,2025-11-09 19:00:00,16836a55-7140-43e2-9a63-56fac5cba714,91,944.9,12.0,5.8,95.0,91.0,95.0,942.6,...,2.9,autumn,-0.965926,2.588190e-01,-0.866025,0.5,-0.781831,0.62349,1,1
4,2025-11-09 20:00:00,16836a55-7140-43e2-9a63-56fac5cba714,93,944.8,11.8,5.8,98.0,93.0,98.0,942.5,...,3.8,autumn,-0.866025,5.000000e-01,-0.866025,0.5,-0.781831,0.62349,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59285,2026-03-01 18:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,51,950.9,7.6,7.4,44.0,51.0,44.0,953.1,...,5.9,spring,-1.000000,-1.836970e-16,0.866025,0.5,-0.781831,0.62349,1,1
59286,2026-03-01 19:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,56,950.7,6.5,6.2,52.0,56.0,52.0,953.0,...,4.5,spring,-0.965926,2.588190e-01,0.866025,0.5,-0.781831,0.62349,1,1
59287,2026-03-01 20:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,56,951.1,5.8,6.8,56.0,56.0,56.0,953.4,...,4.9,spring,-0.866025,5.000000e-01,0.866025,0.5,-0.781831,0.62349,1,1
59288,2026-03-01 21:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,58,951.2,5.2,6.9,59.0,58.0,59.0,953.6,...,4.6,spring,-0.707107,7.071068e-01,0.866025,0.5,-0.781831,0.62349,1,1
59289,2026-03-01 22:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,58,950.8,4.7,7.0,60.0,58.0,60.0,953.1,...,4.4,spring,-0.500000,8.660254e-01,0.866025,0.5,-0.781831,0.62349,1,1

In [26]:
start = pd.Timestamp("2025-11-09 16:00:00")
end = pd.Timestamp("2025-12-01 00:00:00")

filtered_df = forecast_df[
    (forecast_df["timestamp"] >= start) &
    (forecast_df["timestamp"] < end)
]

In [27]:
filtered_df

,timestamp,sensorId,humidity,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor1_pressure,...,neighbor3_wind_speed,season,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
0,2025-11-09 16:00:00,16836a55-7140-43e2-9a63-56fac5cba714,88,944.7,12.5,7.1,92.0,88.0,92.0,942.4,...,4.0,autumn,-0.866025,-5.000000e-01,-0.866025,0.5,-0.781831,0.62349,1,1
1,2025-11-09 17:00:00,16836a55-7140-43e2-9a63-56fac5cba714,90,944.7,12.1,7.1,87.0,90.0,87.0,942.4,...,2.8,autumn,-0.965926,-2.588190e-01,-0.866025,0.5,-0.781831,0.62349,1,1
2,2025-11-09 18:00:00,16836a55-7140-43e2-9a63-56fac5cba714,91,944.5,12.0,6.2,93.0,91.0,93.0,942.2,...,3.9,autumn,-1.000000,-1.836970e-16,-0.866025,0.5,-0.781831,0.62349,1,1
3,2025-11-09 19:00:00,16836a55-7140-43e2-9a63-56fac5cba714,91,944.9,12.0,5.8,95.0,91.0,95.0,942.6,...,2.9,autumn,-0.965926,2.588190e-01,-0.866025,0.5,-0.781831,0.62349,1,1
4,2025-11-09 20:00:00,16836a55-7140-43e2-9a63-56fac5cba714,93,944.8,11.8,5.8,98.0,93.0,98.0,942.5,...,3.8,autumn,-0.866025,5.000000e-01,-0.866025,0.5,-0.781831,0.62349,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57102,2025-11-30 19:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,88,940.4,4.3,5.3,92.0,88.0,92.0,942.9,...,0.8,autumn,-0.965926,2.588190e-01,-0.866025,0.5,-0.781831,0.62349,1,1
57103,2025-11-30 20:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,85,940.9,4.1,5.0,91.0,85.0,91.0,943.4,...,2.1,autumn,-0.866025,5.000000e-01,-0.866025,0.5,-0.781831,0.62349,1,1
57104,2025-11-30 21:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,84,941.2,3.9,5.0,92.0,84.0,92.0,943.9,...,0.5,autumn,-0.707107,7.071068e-01,-0.866025,0.5,-0.781831,0.62349,1,1
57105,2025-11-30 22:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,86,941.2,3.5,3.8,93.0,86.0,93.0,943.9,...,0.4,autumn,-0.500000,8.660254e-01,-0.866025,0.5,-0.781831,0.62349,1,1
57106,2025-11-30 23:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,85,941.7,3.2,4.2,90.0,85.0,90.0,944.3,...,2.6,autumn,-0.258819,9.659258e-01,-0.866025,0.5,-0.781831,0.62349,1,1

In [28]:
future_df = TimeSeriesDataFrame.from_data_frame(
    filtered_df,
    id_column=ID_COL,
    timestamp_column=TIME_COL
)

In [29]:
predictions = predictor.predict(data=train_data,known_covariates=future_df)

Model not specified in predict, will default to the model with the best validation score: Chronos2

In [30]:
print(predictions.head())

                                                               mean  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  38.731834
                                     2025-11-09 17:00:00  40.098709
                                     2025-11-09 18:00:00  37.771862
                                     2025-11-09 19:00:00  35.190342
                                     2025-11-09 20:00:00  32.144737

                                                                0.1  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  26.752377
                                     2025-11-09 17:00:00  24.982611
                                     2025-11-09 18:00:00  22.674049
                                     2025-11-09 19:00:00  20.068165
                                     2025-11-09 20:00:00  17.734859

                                                                0.2  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  30.525673
                                     2025-11-09 17:00:00  29.690630
                                     2025-11-09 18:00:00  27.422220
                                     2025-11-09 19:00:00  24.674028
                                     2025-11-09 20:00:00  22.126646

                                                                0.3  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  33.188240
                                     2025-11-09 17:00:00  33.135475
                                     2025-11-09 18:00:00  30.951103
                                     2025-11-09 19:00:00  28.261452
                                     2025-11-09 20:00:00  25.385874

                                                                0.4  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  35.862820
                                     2025-11-09 17:00:00  36.547256
                                     2025-11-09 18:00:00  34.265144
                                     2025-11-09 19:00:00  31.641588
                                     2025-11-09 20:00:00  28.617918

                                                                0.5  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  38.731834
                                     2025-11-09 17:00:00  40.098709
                                     2025-11-09 18:00:00  37.771862
                                     2025-11-09 19:00:00  35.190342
                                     2025-11-09 20:00:00  32.144737

                                                                0.6  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  41.521259
                                     2025-11-09 17:00:00  43.476784
                                     2025-11-09 18:00:00  41.192528
                                     2025-11-09 19:00:00  38.469124
                                     2025-11-09 20:00:00  35.505985

                                                                0.7  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  44.787560
                                     2025-11-09 17:00:00  47.417397
                                     2025-11-09 18:00:00  45.491760
                                     2025-11-09 19:00:00  42.489449
                                     2025-11-09 20:00:00  39.562019

                                                                0.8        0.9
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  49.044544  56.100880
                                     2025-11-09 17:00:00  52.592667  60.979126
                                     2025-11-09 18:00:00  51.381462  60.579712
                                     2025-11-09 19:00:00  48.042488  56.949272
                                     2025-11-09 20:00:00  45.318291  54.666122

In [31]:
performance = predictor.evaluate(test_data)

print(performance)

Model not specified in predict, will default to the model with the best validation score: Chronos2

{'MASE': -0.9024280952131684}

In [32]:
test_df = test_data.to_data_frame()
pred_df = predictions.to_data_frame()

In [33]:
merged = test_df.merge(
    pred_df[["mean"]],
    on=["item_id", "timestamp"],
    how="inner"
)

In [34]:
merged.columns

Index(['humidity', 'pm10', 'pm25', 'pressure', 'temperature', 'wind_speed',
       'neighbor1_humidity', 'neighbor2_humidity', 'neighbor3_humidity',
       'neighbor1_pressure', 'neighbor2_pressure', 'neighbor3_pressure',
       'neighbor1_temperature', 'neighbor2_temperature',
       'neighbor3_temperature', 'neighbor1_wind_speed', 'neighbor2_wind_speed',
       'neighbor3_wind_speed', 'season', 'hour_sin', 'hour_cos', 'month_sin',
       'month_cos', 'day_sin', 'day_cos', 'is_weekend', 'is_heating_season',
       'mean'],
      dtype='object')

In [35]:
merged = merged.rename(columns={"mean": "predicted"})

In [36]:
merged

                                                          humidity       pm10  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00     71.25  44.500000
                                     2025-11-09 17:00:00     72.00  32.333333
                                     2025-11-09 18:00:00     73.00  26.750000
                                     2025-11-09 19:00:00     73.75  10.500000
                                     2025-11-09 20:00:00     73.25   9.500000
...                                                            ...        ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00     61.75  11.250000
                                     2025-11-30 20:00:00     63.25   9.000000
                                     2025-11-30 21:00:00     63.50  12.000000
                                     2025-11-30 22:00:00     63.75   3.250000
                                     2025-11-30 23:00:00     63.75   1.750000

                                                               pm25  pressure  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  29.750000    944.00
                                     2025-11-09 17:00:00  20.666667    944.00
                                     2025-11-09 18:00:00  16.750000    944.25
                                     2025-11-09 19:00:00   6.250000    945.00
                                     2025-11-09 20:00:00   6.250000    945.00
...                                                             ...       ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00   6.000000    942.00
                                     2025-11-30 20:00:00   5.666667    942.00
                                     2025-11-30 21:00:00   6.000000    942.50
                                     2025-11-30 22:00:00   2.500000    943.00
                                     2025-11-30 23:00:00   0.750000    943.00

                                                          temperature  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00        16.00
                                     2025-11-09 17:00:00        16.00
                                     2025-11-09 18:00:00        15.75
                                     2025-11-09 19:00:00        15.00
                                     2025-11-09 20:00:00        15.00
...                                                               ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00         9.00
                                     2025-11-30 20:00:00         9.00
                                     2025-11-30 21:00:00         8.25
                                     2025-11-30 22:00:00         7.75
                                     2025-11-30 23:00:00         7.00

                                                          wind_speed  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00         5.1
                                     2025-11-09 17:00:00         5.6
                                     2025-11-09 18:00:00         1.5
                                     2025-11-09 19:00:00         4.5
                                     2025-11-09 20:00:00         4.0
...                                                              ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00         5.9
                                     2025-11-30 20:00:00         5.7
                                     2025-11-30 21:00:00         5.8
                                     2025-11-30 22:00:00         5.6
                                     2025-11-30 23:00:00         6.2

                                                          neighbor1_humidity  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00           68.250000
                                     2025-11-09 17:00:00           70.250000
                                     2025-11-09 18:00:00           70.500000
                                     2025-11-09 19:00:00           71.000000
                                     2025-11-09 20:00:00           71.666667
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00           63.500000
                                     2025-11-30 20:00:00           63.750000
                                     2025-11-30 21:00:00           63.333333
                                     2025-11-30 22:00:00           63.750000
                                     2025-11-30 23:00:00           64.000000

                                                          neighbor2_humidity  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00           74.116667
                                     2025-11-09 17:00:00           75.301667
                                     2025-11-09 18:00:00           76.353333
                                     2025-11-09 19:00:00           76.920476
                                     2025-11-09 20:00:00           74.636243
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00           86.500000
                                     2025-11-30 20:00:00           90.500000
                                     2025-11-30 21:00:00           94.333333
                                     2025-11-30 22:00:00           98.000000
                                     2025-11-30 23:00:00           98.000000

                                                          neighbor3_humidity  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00           69.500000
                                     2025-11-09 17:00:00           72.000000
                                     2025-11-09 18:00:00           73.750000
                                     2025-11-09 19:00:00           75.000000
                                     2025-11-09 20:00:00           75.500000
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00           68.583333
                                     2025-11-30 20:00:00           69.333333
                                     2025-11-30 21:00:00           70.425926
                                     2025-11-30 22:00:00           70.888889
                                     2025-11-30 23:00:00           71.472222

                                                          neighbor1_pressure  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00              944.00
                                     2025-11-09 17:00:00              944.00
                                     2025-11-09 18:00:00              944.00
                                     2025-11-09 19:00:00              944.00
                                     2025-11-09 20:00:00              944.00
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00              942.25
                                     2025-11-30 20:00:00              943.00
                                     2025-11-30 21:00:00              943.00
                                     2025-11-30 22:00:00              943.00
                                     2025-11-30 23:00:00              943.25

                                                          ...  season  \
item_id                              timestamp            ...
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  ...  autumn
                                     2025-11-09 17:00:00  ...  autumn
                                     2025-11-09 18:00:00  ...  autumn
                                     2025-11-09 19:00:00  ...  autumn
                                     2025-11-09 20:00:00  ...  autumn
...                                                       ...     ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00  ...  autumn
                                     2025-11-30 20:00:00  ...  autumn
                                     2025-11-30 21:00:00  ...  autumn
                                     2025-11-30 22:00:00  ...  autumn
                                     2025-11-30 23:00:00  ...  autumn

                                                          hour_sin  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00 -0.866025
                                     2025-11-09 17:00:00 -0.965926
                                     2025-11-09 18:00:00 -1.000000
                                     2025-11-09 19:00:00 -0.965926
                                     2025-11-09 20:00:00 -0.866025
...                                                            ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00 -0.965926
                                     2025-11-30 20:00:00 -0.866025
                                     2025-11-30 21:00:00 -0.707107
                                     2025-11-30 22:00:00 -0.500000
                                     2025-11-30 23:00:00 -0.258819

                                                              hour_cos  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00 -5.000000e-01
                                     2025-11-09 17:00:00 -2.588190e-01
                                     2025-11-09 18:00:00 -1.836970e-16
                                     2025-11-09 19:00:00  2.588190e-01
                                     2025-11-09 20:00:00  5.000000e-01
...                                                                ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00  2.588190e-01
                                     2025-11-30 20:00:00  5.000000e-01
                                     2025-11-30 21:00:00  7.071068e-01
                                     2025-11-30 22:00:00  8.660254e-01
                                     2025-11-30 23:00:00  9.659258e-01

                                                          month_sin  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  -0.866025
                                     2025-11-09 17:00:00  -0.866025
                                     2025-11-09 18:00:00  -0.866025
                                     2025-11-09 19:00:00  -0.866025
                                     2025-11-09 20:00:00  -0.866025
...                                                             ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00  -0.866025
                                     2025-11-30 20:00:00  -0.866025
                                     2025-11-30 21:00:00  -0.866025
                                     2025-11-30 22:00:00  -0.866025
                                     2025-11-30 23:00:00  -0.866025

                                                          month_cos   day_sin  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00        0.5 -0.781831
                                     2025-11-09 17:00:00        0.5 -0.781831
                                     2025-11-09 18:00:00        0.5 -0.781831
                                     2025-11-09 19:00:00        0.5 -0.781831
                                     2025-11-09 20:00:00        0.5 -0.781831
...                                                             ...       ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00        0.5 -0.781831
                                     2025-11-30 20:00:00        0.5 -0.781831
                                     2025-11-30 21:00:00        0.5 -0.781831
                                     2025-11-30 22:00:00        0.5 -0.781831
                                     2025-11-30 23:00:00        0.5 -0.781831

                                                          day_cos  is_weekend  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  0.62349           1
                                     2025-11-09 17:00:00  0.62349           1
                                     2025-11-09 18:00:00  0.62349           1
                                     2025-11-09 19:00:00  0.62349           1
                                     2025-11-09 20:00:00  0.62349           1
...                                                           ...         ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00  0.62349           1
                                     2025-11-30 20:00:00  0.62349           1
                                     2025-11-30 21:00:00  0.62349           1
                                     2025-11-30 22:00:00  0.62349           1
                                     2025-11-30 23:00:00  0.62349           1

                                                         is_heating_season  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00                 1
                                     2025-11-09 17:00:00                 1
                                     2025-11-09 18:00:00                 1
                                     2025-11-09 19:00:00                 1
                                     2025-11-09 20:00:00                 1
...                                                                    ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00                 1
                                     2025-11-30 20:00:00                 1
                                     2025-11-30 21:00:00                 1
                                     2025-11-30 22:00:00                 1
                                     2025-11-30 23:00:00                 1

                                                          predicted
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2025-11-09 16:00:00  38.731834
                                     2025-11-09 17:00:00  40.098709
                                     2025-11-09 18:00:00  37.771862
                                     2025-11-09 19:00:00  35.190342
                                     2025-11-09 20:00:00  32.144737
...                                                             ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-30 19:00:00   4.344679
                                     2025-11-30 20:00:00   3.128310
                                     2025-11-30 21:00:00   2.379110
                                     2025-11-30 22:00:00   1.613239
                                     2025-11-30 23:00:00   1.177910

[5632 rows x 28 columns]

In [37]:
train_data

                                                           humidity  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00  58.333333
                                     2023-12-01 01:00:00  59.250000
                                     2023-12-01 02:00:00  60.000000
                                     2023-12-01 03:00:00  59.250000
                                     2023-12-01 04:00:00  59.500000
...                                                             ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00  57.000000
                                     2025-11-09 12:00:00  59.750000
                                     2025-11-09 13:00:00  64.666667
                                     2025-11-09 14:00:00  66.000000
                                     2025-11-09 15:00:00  67.500000

                                                               pm10  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00  28.333333
                                     2023-12-01 01:00:00  13.750000
                                     2023-12-01 02:00:00  10.000000
                                     2023-12-01 03:00:00   9.750000
                                     2023-12-01 04:00:00   5.000000
...                                                             ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00   4.750000
                                     2025-11-09 12:00:00   5.500000
                                     2025-11-09 13:00:00   8.333333
                                     2025-11-09 14:00:00  25.000000
                                     2025-11-09 15:00:00  18.750000

                                                               pm25  pressure  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00  13.666667     943.0
                                     2023-12-01 01:00:00   5.000000     943.0
                                     2023-12-01 02:00:00   4.500000     942.5
                                     2023-12-01 03:00:00   4.500000     942.0
                                     2023-12-01 04:00:00   2.000000     942.0
...                                                             ...       ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00   1.000000     944.0
                                     2025-11-09 12:00:00   2.750000     944.0
                                     2025-11-09 13:00:00   3.333333     944.0
                                     2025-11-09 14:00:00  10.250000     944.0
                                     2025-11-09 15:00:00   8.250000     944.0

                                                          temperature  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00        12.00
                                     2023-12-01 01:00:00        12.00
                                     2023-12-01 02:00:00        12.25
                                     2023-12-01 03:00:00        13.00
                                     2023-12-01 04:00:00        13.00
...                                                               ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00        18.50
                                     2025-11-09 12:00:00        18.00
                                     2025-11-09 13:00:00        17.00
                                     2025-11-09 14:00:00        17.00
                                     2025-11-09 15:00:00        16.50

                                                          wind_speed  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00         8.3
                                     2023-12-01 01:00:00         9.3
                                     2023-12-01 02:00:00         8.3
                                     2023-12-01 03:00:00         9.4
                                     2023-12-01 04:00:00         9.0
...                                                              ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00        11.0
                                     2025-11-09 12:00:00         9.9
                                     2025-11-09 13:00:00         9.2
                                     2025-11-09 14:00:00         5.7
                                     2025-11-09 15:00:00         4.2

                                                          neighbor1_humidity  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00           63.645833
                                     2023-12-01 01:00:00           64.750000
                                     2023-12-01 02:00:00           65.312500
                                     2023-12-01 03:00:00           64.854167
                                     2023-12-01 04:00:00           65.062500
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00           60.750000
                                     2025-11-09 12:00:00           61.500000
                                     2025-11-09 13:00:00           66.500000
                                     2025-11-09 14:00:00           68.666667
                                     2025-11-09 15:00:00           69.750000

                                                          neighbor2_humidity  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00           63.645833
                                     2023-12-01 01:00:00           64.750000
                                     2023-12-01 02:00:00           65.312500
                                     2023-12-01 03:00:00           64.854167
                                     2023-12-01 04:00:00           65.062500
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00           80.500000
                                     2025-11-09 12:00:00           82.750000
                                     2025-11-09 13:00:00           93.000000
                                     2025-11-09 14:00:00           90.750000
                                     2025-11-09 15:00:00           96.500000

                                                          neighbor3_humidity  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00           63.645833
                                     2023-12-01 01:00:00           64.750000
                                     2023-12-01 02:00:00           65.312500
                                     2023-12-01 03:00:00           64.854167
                                     2023-12-01 04:00:00           65.062500
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00           62.491667
                                     2025-11-09 12:00:00           64.675000
                                     2025-11-09 13:00:00           70.666667
                                     2025-11-09 14:00:00           71.908333
                                     2025-11-09 15:00:00           73.008333

                                                          neighbor1_pressure  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00          942.000000
                                     2023-12-01 01:00:00          942.000000
                                     2023-12-01 02:00:00          941.812500
                                     2023-12-01 03:00:00          941.166667
                                     2023-12-01 04:00:00          941.125000
...                                                                      ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00          945.000000
                                     2025-11-09 12:00:00          945.000000
                                     2025-11-09 13:00:00          945.000000
                                     2025-11-09 14:00:00          944.000000
                                     2025-11-09 15:00:00          944.000000

                                                          ...  \
item_id                              timestamp            ...
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00  ...
                                     2023-12-01 01:00:00  ...
                                     2023-12-01 02:00:00  ...
                                     2023-12-01 03:00:00  ...
                                     2023-12-01 04:00:00  ...
...                                                       ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00  ...
                                     2025-11-09 12:00:00  ...
                                     2025-11-09 13:00:00  ...
                                     2025-11-09 14:00:00  ...
                                     2025-11-09 15:00:00  ...

                                                          neighbor3_wind_speed  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00                  6.98
                                     2023-12-01 01:00:00                  7.50
                                     2023-12-01 02:00:00                  6.74
                                     2023-12-01 03:00:00                  7.84
                                     2023-12-01 04:00:00                  8.32
...                                                                        ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00                 15.60
                                     2025-11-09 12:00:00                 14.10
                                     2025-11-09 13:00:00                 11.30
                                     2025-11-09 14:00:00                  8.40
                                     2025-11-09 15:00:00                  4.80

                                                          season  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00  winter
                                     2023-12-01 01:00:00  winter
                                     2023-12-01 02:00:00  winter
                                     2023-12-01 03:00:00  winter
                                     2023-12-01 04:00:00  winter
...                                                          ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00  autumn
                                     2025-11-09 12:00:00  autumn
                                     2025-11-09 13:00:00  autumn
                                     2025-11-09 14:00:00  autumn
                                     2025-11-09 15:00:00  autumn

                                                              hour_sin  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00  0.000000e+00
                                     2023-12-01 01:00:00  2.588190e-01
                                     2023-12-01 02:00:00  5.000000e-01
                                     2023-12-01 03:00:00  7.071068e-01
                                     2023-12-01 04:00:00  8.660254e-01
...                                                                ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00  2.588190e-01
                                     2025-11-09 12:00:00  1.224647e-16
                                     2025-11-09 13:00:00 -2.588190e-01
                                     2025-11-09 14:00:00 -5.000000e-01
                                     2025-11-09 15:00:00 -7.071068e-01

                                                          hour_cos  month_sin  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00  1.000000  -0.500000
                                     2023-12-01 01:00:00  0.965926  -0.500000
                                     2023-12-01 02:00:00  0.866025  -0.500000
                                     2023-12-01 03:00:00  0.707107  -0.500000
                                     2023-12-01 04:00:00  0.500000  -0.500000
...                                                            ...        ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00 -0.965926  -0.866025
                                     2025-11-09 12:00:00 -1.000000  -0.866025
                                     2025-11-09 13:00:00 -0.965926  -0.866025
                                     2025-11-09 14:00:00 -0.866025  -0.866025
                                     2025-11-09 15:00:00 -0.707107  -0.866025

                                                          month_cos   day_sin  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00   0.866025 -0.433884
                                     2023-12-01 01:00:00   0.866025 -0.433884
                                     2023-12-01 02:00:00   0.866025 -0.433884
                                     2023-12-01 03:00:00   0.866025 -0.433884
                                     2023-12-01 04:00:00   0.866025 -0.433884
...                                                             ...       ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00   0.500000 -0.781831
                                     2025-11-09 12:00:00   0.500000 -0.781831
                                     2025-11-09 13:00:00   0.500000 -0.781831
                                     2025-11-09 14:00:00   0.500000 -0.781831
                                     2025-11-09 15:00:00   0.500000 -0.781831

                                                           day_cos is_weekend  \
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00 -0.900969          0
                                     2023-12-01 01:00:00 -0.900969          0
                                     2023-12-01 02:00:00 -0.900969          0
                                     2023-12-01 03:00:00 -0.900969          0
                                     2023-12-01 04:00:00 -0.900969          0
...                                                            ...        ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00  0.623490          1
                                     2025-11-09 12:00:00  0.623490          1
                                     2025-11-09 13:00:00  0.623490          1
                                     2025-11-09 14:00:00  0.623490          1
                                     2025-11-09 15:00:00  0.623490          1

                                                          is_heating_season
item_id                              timestamp
16836a55-7140-43e2-9a63-56fac5cba714 2023-12-01 00:00:00                  1
                                     2023-12-01 01:00:00                  1
                                     2023-12-01 02:00:00                  1
                                     2023-12-01 03:00:00                  1
                                     2023-12-01 04:00:00                  1
...                                                                     ...
fec52a19-9148-4350-a1b4-ae0da05ee199 2025-11-09 11:00:00                  1
                                     2025-11-09 12:00:00                  1
                                     2025-11-09 13:00:00                  1
                                     2025-11-09 14:00:00                  1
                                     2025-11-09 15:00:00                  1

[187352 rows x 27 columns]

In [38]:

from pathlib import Path
import sqlite3

DB_PATH = Path("../data/bitola.db")
if not DB_PATH.exists():
    DB_PATH = Path("data/bitola.db")

if not DB_PATH.exists():
    raise FileNotFoundError("Could not find data/bitola.db. Run the notebook from offline-Phase or the project root.")

CITY = "Bitola"
MODEL_VERSION = f"chronos2_{TARGET}_bitola_offline_test_{PREDICTION_LENGTH}h"
MODEL_TYPE = 'fine_tuned'
train_df = (
    train_data.reset_index().rename(
        columns={
            "item_id": "sensor_id",
            TARGET: "actual_value"
        }
    )
)
train_df['predicted_value'] = np.nan
test_df = (
    merged.reset_index()
    .rename(columns={
        "item_id": "sensor_id",
        TARGET: "actual_value",
        "predicted": "predicted_value",
    })
)
offline_results = pd.concat([train_df,test_df],ignore_index=True).sort_values(["sensor_id", "timestamp"])
offline_results = offline_results[["sensor_id", "timestamp", "actual_value", "predicted_value"]].copy()
offline_results["city"] = CITY
offline_results["pollutant"] = TARGET
offline_results["model_version"] = MODEL_VERSION
offline_results["model_type"] = MODEL_TYPE
offline_results["timestamp"] = pd.to_datetime(offline_results["timestamp"]).dt.strftime("%Y-%m-%d %H:%M:%S")
offline_results = offline_results[["city", "sensor_id", "timestamp", "pollutant", "actual_value", "predicted_value", "model_version","model_type"]]

records = list(offline_results.itertuples(index=False, name=None))

with sqlite3.connect(DB_PATH) as conn:
    conn.execute("""
        CREATE TABLE IF NOT EXISTS offline_test_results (
            city TEXT NOT NULL,
            sensor_id TEXT NOT NULL,
            timestamp TEXT NOT NULL,
            pollutant TEXT NOT NULL,
            actual_value REAL,
            predicted_value REAL,
            model_version TEXT NOT NULL,
            model_type TEXT NOT NULL,
            PRIMARY KEY (city, sensor_id, timestamp, pollutant, model_version)
        )
    """)
    conn.executemany("""
        INSERT OR REPLACE INTO offline_test_results (
            city, sensor_id, timestamp, pollutant, actual_value, predicted_value, model_version,model_type
        ) VALUES (?, ?, ?, ?, ?, ?, ?,?)
    """, records)

print(f"Saved {len(records)} {CITY} {TARGET} offline test rows to {DB_PATH}")

/tmp/ipykernel_347962/3114147318.py:31: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  offline_results = pd.concat([train_df,test_df],ignore_index=True).sort_values(["sensor_id", "timestamp"])

Saved 192984 Bitola pm10 offline test rows to ../data/bitola.db

In [39]:
merged.dropna(inplace=True)

In [40]:
y_true = merged["pm10"]
y_pred = merged["predicted"]

r2_global = r2_score(y_true, y_pred)
rmse_global = np.sqrt(mean_squared_error(y_true, y_pred))

print("Global R2:", r2_global)
print("Global RMSE:", rmse_global)

Global R2: 0.2548877297292158
Global RMSE: 27.785316206336375

In [41]:
per_sensor = merged.groupby("item_id").apply(
    lambda df: pd.Series({
        "r2": r2_score(df["pm10"], df["predicted"]),
        "rmse": np.sqrt(mean_squared_error(df["pm10"], df["predicted"]))
    })
)

print(per_sensor)

                                            r2       rmse
item_id
16836a55-7140-43e2-9a63-56fac5cba714  0.120774  12.987241
2002                                  0.145305  23.901433
23b735ef-a996-4a7f-9998-2aa7e78827b0  0.090245  28.649348
2819ecbb-5de3-4092-aa1d-4ba3a8c40add  0.086338  10.687351
40f081a6-4095-43f7-bffb-64e2af8c026e -0.024724  22.187034
7b316592-8036-41e2-b8dc-b06b6a9afd54  0.249347  43.955149
874ff9c6-786d-45fc-a90e-48c7ffe03417  0.044830  31.797033
87f82783-853b-417d-8964-b5cf11e44873  0.169928  47.388756
d241a044-0a06-40c2-9d90-c91fd0a95060 -0.022858  11.010461
d7060523-b163-4cc3-bc94-970dac72a38a  0.062755  29.843329
fec52a19-9148-4350-a1b4-ae0da05ee199  0.176700   7.989832

In [42]:
predictor.path

'/mnt/c/Users/RazorVision/Desktop/project-vrnmp/offline-Phase/AutogluonModels/ag-20260715_114407'

In [43]:
import shutil

shutil.copytree(
    predictor.path,
    "chronos2_model_pm10_bitola"
)

'chronos2_model_pm10_bitola'