## Get historical data

In [2]:
import pandas as pd
import requests
from time import sleep
from tqdm import tqdm

In [3]:
data = pd.read_csv("../data/streaming/bitola_sensor_weather_features_online.csv")

In [4]:
data

,timestamp,sensorId,lat,lon,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,surface_pressure,pm10,pm25
0,2025-12-01 00:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127,1.9505,92.41695,4.293669,303.02386,943.69060,34.750000,17.500000
1,2025-12-01 01:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127,2.0005,92.41994,3.818376,315.00010,944.07420,18.250000,10.000000
2,2025-12-01 02:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127,1.6505,93.06822,3.893995,326.30990,944.16860,15.000000,8.750000
3,2025-12-01 03:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127,1.4005,93.72927,4.104631,322.12494,944.47410,14.750000,7.250000
4,2025-12-01 04:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127,1.3005,94.06355,3.563818,315.00010,944.81850,19.000000,8.750000
...,...,...,...,...,...,...,...,...,...,...,...
48021,2026-03-01 18:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767,6.9890,69.99575,1.659518,229.39879,949.81270,12.250000,4.000000
48022,2026-03-01 19:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767,6.4890,71.15741,1.049571,210.96368,950.14496,5.666667,2.666667
48023,2026-03-01 20:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767,5.6390,72.80048,1.527351,224.99990,950.19970,6.000000,3.000000
48024,2026-03-01 21:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767,5.1390,72.96915,1.152562,231.34016,950.34550,3.750000,2.250000
48025,2026-03-01 22:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767,4.4390,73.63402,1.152562,231.34016,949.97534,5.333333,1.000000

In [5]:
df = data[['timestamp','sensorId','lat','lon']]
df

,timestamp,sensorId,lat,lon
0,2025-12-01 00:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127
1,2025-12-01 01:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127
2,2025-12-01 02:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127
3,2025-12-01 03:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127
4,2025-12-01 04:00:00+00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127
...,...,...,...,...
48021,2026-03-01 18:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767
48022,2026-03-01 19:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767
48023,2026-03-01 20:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767
48024,2026-03-01 21:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767
48025,2026-03-01 22:00:00+00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767

In [6]:
df["timestamp"] = pd.to_datetime(df["timestamp"],utc=True)
df["date"] = df["timestamp"].dt.date
df["hour"] = df["timestamp"].dt.hour

/tmp/ipykernel_35822/2002426275.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["timestamp"] = pd.to_datetime(df["timestamp"],utc=True)
/tmp/ipykernel_35822/2002426275.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date"] = df["timestamp"].dt.date
/tmp/ipykernel_35822/2002426275.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["hour"] = df["timestamp"].dt.hour

In [7]:
def get_data_for_day(lat, lon, date):
    url = "https://historical-forecast-api.open-meteo.com/v1/forecast"
    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": str(date),
        "end_date": str(date),
        "hourly": ["temperature_2m", "relative_humidity_2m", "surface_pressure", "wind_speed_10m"],
        "timezone": "UTC"
    }

    r = requests.get(url, params=params, timeout=30)
    r.raise_for_status()
    return r.json()

In [8]:
weather_cache = {}

In [9]:
max(df['timestamp'])

Timestamp('2026-03-01 22:00:00+0000', tz='UTC')

In [10]:
df = df[['sensorId', 'lat', 'lon']].drop_duplicates()

# Create hourly timestamps
timestamps = pd.date_range(
    start='2025-11-09 16:00:00',
    end='2026-03-01 22:00:00',
    freq='h'
)

# Cartesian product between sensors and timestamps
new_df = (
    df.assign(key=1)
    .merge(
        pd.DataFrame({'timestamp': timestamps, 'key': 1}),
        on='key'
    )
    .drop(columns='key')
)

# Arrange columns
new_df = new_df[['timestamp', 'sensorId', 'lat', 'lon']]

# Combine with your existing dataframe
df = pd.concat([new_df, df], ignore_index=True)

# Sort
df = df.sort_values(['sensorId', 'timestamp']).reset_index(drop=True)

In [11]:
df

,timestamp,sensorId,lat,lon
0,2025-11-09 16:00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127
1,2025-11-09 17:00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127
2,2025-11-09 18:00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127
3,2025-11-09 19:00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127
4,2025-11-09 20:00:00,16836a55-7140-43e2-9a63-56fac5cba714,41.023537,21.330127
...,...,...,...,...
59307,2026-03-01 19:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767
59308,2026-03-01 20:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767
59309,2026-03-01 21:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767
59310,2026-03-01 22:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767
59311,NaT,fec52a19-9148-4350-a1b4-ae0da05ee199,41.024649,21.320767

In [12]:
df = df[df["timestamp"].notna()]

In [13]:
df["date"] = df["timestamp"].dt.date
df["hour"] = df["timestamp"].dt.hour

/tmp/ipykernel_35822/1979510837.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date"] = df["timestamp"].dt.date
/tmp/ipykernel_35822/1979510837.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["hour"] = df["timestamp"].dt.hour

In [14]:
wind_values = []
humidity_values = []
pressure_values = []
temperature_values = []

print("\nFetching data from Open-Meteo...\n")

for i, row in tqdm(df.iterrows(), total=len(df)):
    key = (row.lat, row.lon, row.date)

    print(f"Iteration: {i}/{len(df)}")
    if key not in weather_cache:
        success = False
        for _ in range(3):
            try:
                weather_cache[key] = get_data_for_day(row.lat, row.lon, row.date)
                success = True
                sleep(0.2)
                break
            except Exception as e:
                sleep(2)

        if not success:
            weather_cache[key] = None

    data = weather_cache[key]

    if data is None:
        wind_values.append(None)
        humidity_values.append(None)
        pressure_values.append(None)
        temperature_values.append(None)
        continue

    try:
        times = data["hourly"]["time"]
        winds = data["hourly"]["wind_speed_10m"]
        temperatures = data['hourly']['temperature_2m']
        humidity = data['hourly']['relative_humidity_2m']
        pressure = data['hourly']['surface_pressure']

        # Match exact timestamp hour
        ts_str = row.timestamp.strftime("%Y-%m-%dT%H:00")

        if ts_str in times:
            idx = times.index(ts_str)
            wind_values.append(winds[idx])
            humidity_values.append(humidity[idx])
            pressure_values.append(pressure[idx])
            temperature_values.append(temperatures[idx])
        else:
            wind_values.append(None)
            humidity_values.append(None)
            pressure_values.append(None)
            temperature_values.append(None)

    except:
        wind_values.append(None)
        humidity_values.append(None)
        pressure_values.append(None)
        temperature_values.append(None)

Fetching data from Open-Meteo...

  0%|          | 0/59290 [00:00<?, ?it/s]

Iteration: 0/59290

  0%|          | 1/59290 [00:00<7:24:28,  2.22it/s]

Iteration: 1/59290
Iteration: 2/59290
Iteration: 3/59290
Iteration: 4/59290
Iteration: 5/59290
Iteration: 6/59290
Iteration: 7/59290
Iteration: 8/59290

  0%|          | 9/59290 [00:00<1:19:28, 12.43it/s]

Iteration: 9/59290
Iteration: 10/59290
Iteration: 11/59290
Iteration: 12/59290
Iteration: 13/59290
Iteration: 14/59290
Iteration: 15/59290
Iteration: 16/59290
Iteration: 17/59290
Iteration: 18/59290
Iteration: 19/59290
Iteration: 20/59290
Iteration: 21/59290
Iteration: 22/59290
Iteration: 23/59290
Iteration: 24/59290
Iteration: 25/59290
Iteration: 26/59290
Iteration: 27/59290
Iteration: 28/59290
Iteration: 29/59290
Iteration: 30/59290
Iteration: 31/59290
Iteration: 32/59290

  0%|          | 33/59290 [00:01<28:30, 34.65it/s]

Iteration: 33/59290
Iteration: 34/59290
Iteration: 35/59290
Iteration: 36/59290
Iteration: 37/59290
Iteration: 38/59290
Iteration: 39/59290
Iteration: 40/59290
Iteration: 41/59290
Iteration: 42/59290
Iteration: 43/59290
Iteration: 44/59290
Iteration: 45/59290
Iteration: 46/59290
Iteration: 47/59290
Iteration: 48/59290
Iteration: 49/59290
Iteration: 50/59290
Iteration: 51/59290
Iteration: 52/59290
Iteration: 53/59290
Iteration: 54/59290
Iteration: 55/59290
Iteration: 56/59290

  0%|          | 57/59290 [00:01<21:24, 46.10it/s]

Iteration: 57/59290
Iteration: 58/59290
Iteration: 59/59290
Iteration: 60/59290
Iteration: 61/59290
Iteration: 62/59290
Iteration: 63/59290
Iteration: 64/59290
Iteration: 65/59290
Iteration: 66/59290
Iteration: 67/59290
Iteration: 68/59290
Iteration: 69/59290
Iteration: 70/59290
Iteration: 71/59290
Iteration: 72/59290
Iteration: 73/59290
Iteration: 74/59290
Iteration: 75/59290
Iteration: 76/59290
Iteration: 77/59290
Iteration: 78/59290
Iteration: 79/59290
Iteration: 80/59290

  0%|          | 81/59290 [00:02<35:32, 27.76it/s]

Iteration: 81/59290
Iteration: 82/59290
Iteration: 83/59290
Iteration: 84/59290
Iteration: 85/59290
Iteration: 86/59290
Iteration: 87/59290
Iteration: 88/59290
Iteration: 89/59290
Iteration: 90/59290
Iteration: 91/59290
Iteration: 92/59290
Iteration: 93/59290
Iteration: 94/59290
Iteration: 95/59290
Iteration: 96/59290
Iteration: 97/59290
Iteration: 98/59290
Iteration: 99/59290
Iteration: 100/59290
Iteration: 101/59290
Iteration: 102/59290
Iteration: 103/59290
Iteration: 104/59290

  0%|          | 105/59290 [00:05<55:03, 17.91it/s]

Iteration: 105/59290
Iteration: 106/59290
Iteration: 107/59290
Iteration: 108/59290
Iteration: 109/59290
Iteration: 110/59290
Iteration: 111/59290
Iteration: 112/59290
Iteration: 113/59290
Iteration: 114/59290
Iteration: 115/59290
Iteration: 116/59290
Iteration: 117/59290
Iteration: 118/59290
Iteration: 119/59290
Iteration: 120/59290
Iteration: 121/59290
Iteration: 122/59290
Iteration: 123/59290
Iteration: 124/59290
Iteration: 125/59290
Iteration: 126/59290
Iteration: 127/59290
Iteration: 128/59290

  0%|          | 129/59290 [00:05<42:56, 22.96it/s]

Iteration: 129/59290
Iteration: 130/59290
Iteration: 131/59290
Iteration: 132/59290
Iteration: 133/59290
Iteration: 134/59290
Iteration: 135/59290
Iteration: 136/59290
Iteration: 137/59290
Iteration: 138/59290
Iteration: 139/59290
Iteration: 140/59290
Iteration: 141/59290
Iteration: 142/59290
Iteration: 143/59290
Iteration: 144/59290
Iteration: 145/59290
Iteration: 146/59290
Iteration: 147/59290
Iteration: 148/59290
Iteration: 149/59290
Iteration: 150/59290
Iteration: 151/59290
Iteration: 152/59290

  0%|          | 153/59290 [00:05<33:40, 29.27it/s]

Iteration: 153/59290
Iteration: 154/59290
Iteration: 155/59290
Iteration: 156/59290
Iteration: 157/59290
Iteration: 158/59290
Iteration: 159/59290
Iteration: 160/59290
Iteration: 161/59290
Iteration: 162/59290
Iteration: 163/59290
Iteration: 164/59290
Iteration: 165/59290
Iteration: 166/59290
Iteration: 167/59290
Iteration: 168/59290
Iteration: 169/59290
Iteration: 170/59290
Iteration: 171/59290
Iteration: 172/59290
Iteration: 173/59290
Iteration: 174/59290
Iteration: 175/59290
Iteration: 176/59290

  0%|          | 177/59290 [00:06<27:48, 35.43it/s]

Iteration: 177/59290
Iteration: 178/59290
Iteration: 179/59290
Iteration: 180/59290
Iteration: 181/59290
Iteration: 182/59290
Iteration: 183/59290
Iteration: 184/59290
Iteration: 185/59290
Iteration: 186/59290
Iteration: 187/59290
Iteration: 188/59290
Iteration: 189/59290
Iteration: 190/59290
Iteration: 191/59290
Iteration: 192/59290
Iteration: 193/59290
Iteration: 194/59290
Iteration: 195/59290
Iteration: 196/59290
Iteration: 197/59290
Iteration: 198/59290
Iteration: 199/59290
Iteration: 200/59290

  0%|          | 201/59290 [00:06<23:50, 41.31it/s]

Iteration: 201/59290
Iteration: 202/59290
Iteration: 203/59290
Iteration: 204/59290
Iteration: 205/59290
Iteration: 206/59290
Iteration: 207/59290
Iteration: 208/59290
Iteration: 209/59290
Iteration: 210/59290
Iteration: 211/59290
Iteration: 212/59290
Iteration: 213/59290
Iteration: 214/59290
Iteration: 215/59290
Iteration: 216/59290
Iteration: 217/59290
Iteration: 218/59290
Iteration: 219/59290
Iteration: 220/59290
Iteration: 221/59290
Iteration: 222/59290
Iteration: 223/59290
Iteration: 224/59290

  0%|          | 225/59290 [00:07<21:12, 46.42it/s]

Iteration: 225/59290
Iteration: 226/59290
Iteration: 227/59290
Iteration: 228/59290
Iteration: 229/59290
Iteration: 230/59290
Iteration: 231/59290
Iteration: 232/59290
Iteration: 233/59290
Iteration: 234/59290
Iteration: 235/59290
Iteration: 236/59290
Iteration: 237/59290
Iteration: 238/59290
Iteration: 239/59290
Iteration: 240/59290
Iteration: 241/59290
Iteration: 242/59290
Iteration: 243/59290
Iteration: 244/59290
Iteration: 245/59290
Iteration: 246/59290
Iteration: 247/59290
Iteration: 248/59290

  0%|          | 249/59290 [00:07<19:21, 50.81it/s]

Iteration: 249/59290
Iteration: 250/59290
Iteration: 251/59290
Iteration: 252/59290
Iteration: 253/59290
Iteration: 254/59290
Iteration: 255/59290
Iteration: 256/59290
Iteration: 257/59290
Iteration: 258/59290
Iteration: 259/59290
Iteration: 260/59290
Iteration: 261/59290
Iteration: 262/59290
Iteration: 263/59290
Iteration: 264/59290
Iteration: 265/59290
Iteration: 266/59290
Iteration: 267/59290
Iteration: 268/59290
Iteration: 269/59290
Iteration: 270/59290
Iteration: 271/59290
Iteration: 272/59290

  0%|          | 273/59290 [00:42<7:27:20,  2.20it/s]

Iteration: 273/59290
Iteration: 274/59290
Iteration: 275/59290
Iteration: 276/59290
Iteration: 277/59290
Iteration: 278/59290
Iteration: 279/59290
Iteration: 280/59290
Iteration: 281/59290
Iteration: 282/59290
Iteration: 283/59290
Iteration: 284/59290
Iteration: 285/59290
Iteration: 286/59290
Iteration: 287/59290
Iteration: 288/59290
Iteration: 289/59290
Iteration: 290/59290
Iteration: 291/59290
Iteration: 292/59290
Iteration: 293/59290
Iteration: 294/59290
Iteration: 295/59290
Iteration: 296/59290

  1%|          | 297/59290 [00:42<5:15:59,  3.11it/s]

Iteration: 297/59290
Iteration: 298/59290
Iteration: 299/59290
Iteration: 300/59290
Iteration: 301/59290
Iteration: 302/59290
Iteration: 303/59290
Iteration: 304/59290
Iteration: 305/59290
Iteration: 306/59290
Iteration: 307/59290
Iteration: 308/59290
Iteration: 309/59290
Iteration: 310/59290
Iteration: 311/59290
Iteration: 312/59290
Iteration: 313/59290
Iteration: 314/59290
Iteration: 315/59290
Iteration: 316/59290
Iteration: 317/59290
Iteration: 318/59290
Iteration: 319/59290
Iteration: 320/59290

  1%|          | 321/59290 [00:42<3:44:53,  4.37it/s]

Iteration: 321/59290
Iteration: 322/59290
Iteration: 323/59290
Iteration: 324/59290
Iteration: 325/59290
Iteration: 326/59290
Iteration: 327/59290
Iteration: 328/59290
Iteration: 329/59290
Iteration: 330/59290
Iteration: 331/59290
Iteration: 332/59290
Iteration: 333/59290
Iteration: 334/59290
Iteration: 335/59290
Iteration: 336/59290
Iteration: 337/59290
Iteration: 338/59290
Iteration: 339/59290
Iteration: 340/59290
Iteration: 341/59290
Iteration: 342/59290
Iteration: 343/59290
Iteration: 344/59290

  1%|          | 345/59290 [00:43<2:41:35,  6.08it/s]

Iteration: 345/59290
Iteration: 346/59290
Iteration: 347/59290
Iteration: 348/59290
Iteration: 349/59290
Iteration: 350/59290
Iteration: 351/59290
Iteration: 352/59290
Iteration: 353/59290
Iteration: 354/59290
Iteration: 355/59290
Iteration: 356/59290
Iteration: 357/59290
Iteration: 358/59290
Iteration: 359/59290
Iteration: 360/59290
Iteration: 361/59290
Iteration: 362/59290
Iteration: 363/59290
Iteration: 364/59290
Iteration: 365/59290
Iteration: 366/59290
Iteration: 367/59290
Iteration: 368/59290

  1%|          | 369/59290 [01:15<8:33:57,  1.91it/s]

Iteration: 369/59290
Iteration: 370/59290
Iteration: 371/59290
Iteration: 372/59290
Iteration: 373/59290
Iteration: 374/59290
Iteration: 375/59290
Iteration: 376/59290
Iteration: 377/59290
Iteration: 378/59290
Iteration: 379/59290
Iteration: 380/59290
Iteration: 381/59290
Iteration: 382/59290
Iteration: 383/59290
Iteration: 384/59290
Iteration: 385/59290
Iteration: 386/59290
Iteration: 387/59290
Iteration: 388/59290
Iteration: 389/59290
Iteration: 390/59290
Iteration: 391/59290
Iteration: 392/59290

  1%|          | 393/59290 [01:16<6:03:51,  2.70it/s]

Iteration: 393/59290
Iteration: 394/59290
Iteration: 395/59290
Iteration: 396/59290
Iteration: 397/59290
Iteration: 398/59290
Iteration: 399/59290
Iteration: 400/59290
Iteration: 401/59290
Iteration: 402/59290
Iteration: 403/59290
Iteration: 404/59290
Iteration: 405/59290
Iteration: 406/59290
Iteration: 407/59290
Iteration: 408/59290
Iteration: 409/59290
Iteration: 410/59290
Iteration: 411/59290
Iteration: 412/59290
Iteration: 413/59290
Iteration: 414/59290
Iteration: 415/59290
Iteration: 416/59290

  1%|          | 417/59290 [01:16<4:19:01,  3.79it/s]

Iteration: 417/59290
Iteration: 418/59290
Iteration: 419/59290
Iteration: 420/59290
Iteration: 421/59290
Iteration: 422/59290
Iteration: 423/59290
Iteration: 424/59290
Iteration: 425/59290
Iteration: 426/59290
Iteration: 427/59290
Iteration: 428/59290
Iteration: 429/59290
Iteration: 430/59290
Iteration: 431/59290
Iteration: 432/59290
Iteration: 433/59290
Iteration: 434/59290
Iteration: 435/59290
Iteration: 436/59290
Iteration: 437/59290
Iteration: 438/59290
Iteration: 439/59290
Iteration: 440/59290

  1%|          | 441/59290 [01:16<3:05:47,  5.28it/s]

Iteration: 441/59290
Iteration: 442/59290
Iteration: 443/59290
Iteration: 444/59290
Iteration: 445/59290
Iteration: 446/59290
Iteration: 447/59290
Iteration: 448/59290
Iteration: 449/59290
Iteration: 450/59290
Iteration: 451/59290
Iteration: 452/59290
Iteration: 453/59290
Iteration: 454/59290
Iteration: 455/59290
Iteration: 456/59290
Iteration: 457/59290
Iteration: 458/59290
Iteration: 459/59290
Iteration: 460/59290
Iteration: 461/59290
Iteration: 462/59290
Iteration: 463/59290
Iteration: 464/59290

  1%|          | 465/59290 [01:17<2:14:30,  7.29it/s]

Iteration: 465/59290
Iteration: 466/59290
Iteration: 467/59290
Iteration: 468/59290
Iteration: 469/59290
Iteration: 470/59290
Iteration: 471/59290
Iteration: 472/59290
Iteration: 473/59290
Iteration: 474/59290
Iteration: 475/59290
Iteration: 476/59290
Iteration: 477/59290
Iteration: 478/59290
Iteration: 479/59290
Iteration: 480/59290
Iteration: 481/59290
Iteration: 482/59290
Iteration: 483/59290
Iteration: 484/59290
Iteration: 485/59290
Iteration: 486/59290
Iteration: 487/59290
Iteration: 488/59290

  1%|          | 489/59290 [01:17<1:38:48,  9.92it/s]

Iteration: 489/59290
Iteration: 490/59290
Iteration: 491/59290
Iteration: 492/59290
Iteration: 493/59290
Iteration: 494/59290
Iteration: 495/59290
Iteration: 496/59290
Iteration: 497/59290
Iteration: 498/59290
Iteration: 499/59290
Iteration: 500/59290
Iteration: 501/59290
Iteration: 502/59290
Iteration: 503/59290
Iteration: 504/59290
Iteration: 505/59290
Iteration: 506/59290
Iteration: 507/59290
Iteration: 508/59290
Iteration: 509/59290
Iteration: 510/59290
Iteration: 511/59290
Iteration: 512/59290

  1%|          | 513/59290 [01:17<1:13:44, 13.28it/s]

Iteration: 513/59290
Iteration: 514/59290
Iteration: 515/59290
Iteration: 516/59290
Iteration: 517/59290
Iteration: 518/59290
Iteration: 519/59290
Iteration: 520/59290
Iteration: 521/59290
Iteration: 522/59290
Iteration: 523/59290
Iteration: 524/59290
Iteration: 525/59290
Iteration: 526/59290
Iteration: 527/59290
Iteration: 528/59290
Iteration: 529/59290
Iteration: 530/59290
Iteration: 531/59290
Iteration: 532/59290
Iteration: 533/59290
Iteration: 534/59290
Iteration: 535/59290
Iteration: 536/59290

  1%|          | 537/59290 [01:18<56:08, 17.44it/s]

Iteration: 537/59290
Iteration: 538/59290
Iteration: 539/59290
Iteration: 540/59290
Iteration: 541/59290
Iteration: 542/59290
Iteration: 543/59290
Iteration: 544/59290
Iteration: 545/59290
Iteration: 546/59290
Iteration: 547/59290
Iteration: 548/59290
Iteration: 549/59290
Iteration: 550/59290
Iteration: 551/59290
Iteration: 552/59290
Iteration: 553/59290
Iteration: 554/59290
Iteration: 555/59290
Iteration: 556/59290
Iteration: 557/59290
Iteration: 558/59290
Iteration: 559/59290
Iteration: 560/59290

  1%|          | 561/59290 [01:18<44:04, 22.21it/s]

Iteration: 561/59290
Iteration: 562/59290
Iteration: 563/59290
Iteration: 564/59290
Iteration: 565/59290
Iteration: 566/59290
Iteration: 567/59290
Iteration: 568/59290
Iteration: 569/59290
Iteration: 570/59290
Iteration: 571/59290
Iteration: 572/59290
Iteration: 573/59290
Iteration: 574/59290
Iteration: 575/59290
Iteration: 576/59290
Iteration: 577/59290
Iteration: 578/59290
Iteration: 579/59290
Iteration: 580/59290
Iteration: 581/59290
Iteration: 582/59290
Iteration: 583/59290
Iteration: 584/59290

  1%|          | 585/59290 [01:20<50:21, 19.43it/s]

Iteration: 585/59290
Iteration: 586/59290
Iteration: 587/59290
Iteration: 588/59290
Iteration: 589/59290
Iteration: 590/59290
Iteration: 591/59290
Iteration: 592/59290
Iteration: 593/59290
Iteration: 594/59290
Iteration: 595/59290
Iteration: 596/59290
Iteration: 597/59290
Iteration: 598/59290
Iteration: 599/59290
Iteration: 600/59290
Iteration: 601/59290
Iteration: 602/59290
Iteration: 603/59290
Iteration: 604/59290
Iteration: 605/59290
Iteration: 606/59290
Iteration: 607/59290
Iteration: 608/59290

  1%|          | 609/59290 [01:22<59:51, 16.34it/s]

Iteration: 609/59290
Iteration: 610/59290
Iteration: 611/59290
Iteration: 612/59290
Iteration: 613/59290
Iteration: 614/59290
Iteration: 615/59290
Iteration: 616/59290
Iteration: 617/59290
Iteration: 618/59290
Iteration: 619/59290
Iteration: 620/59290
Iteration: 621/59290
Iteration: 622/59290
Iteration: 623/59290
Iteration: 624/59290
Iteration: 625/59290
Iteration: 626/59290
Iteration: 627/59290
Iteration: 628/59290
Iteration: 629/59290
Iteration: 630/59290
Iteration: 631/59290
Iteration: 632/59290

  1%|          | 633/59290 [01:22<48:22, 20.21it/s]

Iteration: 633/59290
Iteration: 634/59290
Iteration: 635/59290
Iteration: 636/59290
Iteration: 637/59290
Iteration: 638/59290
Iteration: 639/59290
Iteration: 640/59290
Iteration: 641/59290
Iteration: 642/59290
Iteration: 643/59290
Iteration: 644/59290
Iteration: 645/59290
Iteration: 646/59290
Iteration: 647/59290
Iteration: 648/59290
Iteration: 649/59290
Iteration: 650/59290
Iteration: 651/59290
Iteration: 652/59290
Iteration: 653/59290
Iteration: 654/59290
Iteration: 655/59290
Iteration: 656/59290

  1%|          | 657/59290 [01:23<38:29, 25.38it/s]

Iteration: 657/59290
Iteration: 658/59290
Iteration: 659/59290
Iteration: 660/59290
Iteration: 661/59290
Iteration: 662/59290
Iteration: 663/59290
Iteration: 664/59290
Iteration: 665/59290
Iteration: 666/59290
Iteration: 667/59290
Iteration: 668/59290
Iteration: 669/59290
Iteration: 670/59290
Iteration: 671/59290
Iteration: 672/59290
Iteration: 673/59290
Iteration: 674/59290
Iteration: 675/59290
Iteration: 676/59290
Iteration: 677/59290
Iteration: 678/59290
Iteration: 679/59290
Iteration: 680/59290

  1%|          | 681/59290 [01:23<31:33, 30.94it/s]

Iteration: 681/59290
Iteration: 682/59290
Iteration: 683/59290
Iteration: 684/59290
Iteration: 685/59290
Iteration: 686/59290
Iteration: 687/59290
Iteration: 688/59290
Iteration: 689/59290
Iteration: 690/59290
Iteration: 691/59290
Iteration: 692/59290
Iteration: 693/59290
Iteration: 694/59290
Iteration: 695/59290
Iteration: 696/59290
Iteration: 697/59290
Iteration: 698/59290
Iteration: 699/59290
Iteration: 700/59290
Iteration: 701/59290
Iteration: 702/59290
Iteration: 703/59290
Iteration: 704/59290

  1%|          | 705/59290 [01:24<26:46, 36.46it/s]

Iteration: 705/59290
Iteration: 706/59290
Iteration: 707/59290
Iteration: 708/59290
Iteration: 709/59290
Iteration: 710/59290
Iteration: 711/59290
Iteration: 712/59290
Iteration: 713/59290
Iteration: 714/59290
Iteration: 715/59290
Iteration: 716/59290
Iteration: 717/59290
Iteration: 718/59290
Iteration: 719/59290
Iteration: 720/59290
Iteration: 721/59290
Iteration: 722/59290
Iteration: 723/59290
Iteration: 724/59290
Iteration: 725/59290
Iteration: 726/59290
Iteration: 727/59290
Iteration: 728/59290

  1%|          | 729/59290 [01:25<37:13, 26.22it/s]

Iteration: 729/59290
Iteration: 730/59290
Iteration: 731/59290
Iteration: 732/59290
Iteration: 733/59290
Iteration: 734/59290
Iteration: 735/59290
Iteration: 736/59290
Iteration: 737/59290
Iteration: 738/59290
Iteration: 739/59290
Iteration: 740/59290
Iteration: 741/59290
Iteration: 742/59290
Iteration: 743/59290
Iteration: 744/59290
Iteration: 745/59290
Iteration: 746/59290
Iteration: 747/59290
Iteration: 748/59290
Iteration: 749/59290
Iteration: 750/59290
Iteration: 751/59290
Iteration: 752/59290

  1%|▏         | 753/59290 [01:27<49:37, 19.66it/s]

Iteration: 753/59290
Iteration: 754/59290
Iteration: 755/59290
Iteration: 756/59290
Iteration: 757/59290
Iteration: 758/59290
Iteration: 759/59290
Iteration: 760/59290
Iteration: 761/59290
Iteration: 762/59290
Iteration: 763/59290
Iteration: 764/59290
Iteration: 765/59290
Iteration: 766/59290
Iteration: 767/59290
Iteration: 768/59290
Iteration: 769/59290
Iteration: 770/59290
Iteration: 771/59290
Iteration: 772/59290
Iteration: 773/59290
Iteration: 774/59290
Iteration: 775/59290
Iteration: 776/59290

  1%|▏         | 777/59290 [01:28<41:59, 23.22it/s]

Iteration: 777/59290
Iteration: 778/59290
Iteration: 779/59290
Iteration: 780/59290
Iteration: 781/59290
Iteration: 782/59290
Iteration: 783/59290
Iteration: 784/59290
Iteration: 785/59290
Iteration: 786/59290
Iteration: 787/59290
Iteration: 788/59290
Iteration: 789/59290
Iteration: 790/59290
Iteration: 791/59290
Iteration: 792/59290
Iteration: 793/59290
Iteration: 794/59290
Iteration: 795/59290
Iteration: 796/59290
Iteration: 797/59290
Iteration: 798/59290
Iteration: 799/59290
Iteration: 800/59290

  1%|▏         | 801/59290 [01:28<34:00, 28.66it/s]

Iteration: 801/59290
Iteration: 802/59290
Iteration: 803/59290
Iteration: 804/59290
Iteration: 805/59290
Iteration: 806/59290
Iteration: 807/59290
Iteration: 808/59290
Iteration: 809/59290
Iteration: 810/59290
Iteration: 811/59290
Iteration: 812/59290
Iteration: 813/59290
Iteration: 814/59290
Iteration: 815/59290
Iteration: 816/59290
Iteration: 817/59290
Iteration: 818/59290
Iteration: 819/59290
Iteration: 820/59290
Iteration: 821/59290
Iteration: 822/59290
Iteration: 823/59290
Iteration: 824/59290

  1%|▏         | 825/59290 [01:28<28:30, 34.19it/s]

Iteration: 825/59290
Iteration: 826/59290
Iteration: 827/59290
Iteration: 828/59290
Iteration: 829/59290
Iteration: 830/59290
Iteration: 831/59290
Iteration: 832/59290
Iteration: 833/59290
Iteration: 834/59290
Iteration: 835/59290
Iteration: 836/59290
Iteration: 837/59290
Iteration: 838/59290
Iteration: 839/59290
Iteration: 840/59290
Iteration: 841/59290
Iteration: 842/59290
Iteration: 843/59290
Iteration: 844/59290
Iteration: 845/59290
Iteration: 846/59290
Iteration: 847/59290
Iteration: 848/59290

  1%|▏         | 849/59290 [01:29<24:30, 39.74it/s]

Iteration: 849/59290
Iteration: 850/59290
Iteration: 851/59290
Iteration: 852/59290
Iteration: 853/59290
Iteration: 854/59290
Iteration: 855/59290
Iteration: 856/59290
Iteration: 857/59290
Iteration: 858/59290
Iteration: 859/59290
Iteration: 860/59290
Iteration: 861/59290
Iteration: 862/59290
Iteration: 863/59290
Iteration: 864/59290
Iteration: 865/59290
Iteration: 866/59290
Iteration: 867/59290
Iteration: 868/59290
Iteration: 869/59290
Iteration: 870/59290
Iteration: 871/59290
Iteration: 872/59290

  1%|▏         | 873/59290 [01:29<21:45, 44.74it/s]

Iteration: 873/59290
Iteration: 874/59290
Iteration: 875/59290
Iteration: 876/59290
Iteration: 877/59290
Iteration: 878/59290
Iteration: 879/59290
Iteration: 880/59290
Iteration: 881/59290
Iteration: 882/59290
Iteration: 883/59290
Iteration: 884/59290
Iteration: 885/59290
Iteration: 886/59290
Iteration: 887/59290
Iteration: 888/59290
Iteration: 889/59290
Iteration: 890/59290
Iteration: 891/59290
Iteration: 892/59290
Iteration: 893/59290
Iteration: 894/59290
Iteration: 895/59290
Iteration: 896/59290

  2%|▏         | 897/59290 [01:29<19:51, 49.02it/s]

Iteration: 897/59290
Iteration: 898/59290
Iteration: 899/59290
Iteration: 900/59290
Iteration: 901/59290
Iteration: 902/59290
Iteration: 903/59290
Iteration: 904/59290
Iteration: 905/59290
Iteration: 906/59290
Iteration: 907/59290
Iteration: 908/59290
Iteration: 909/59290
Iteration: 910/59290
Iteration: 911/59290
Iteration: 912/59290
Iteration: 913/59290
Iteration: 914/59290
Iteration: 915/59290
Iteration: 916/59290
Iteration: 917/59290
Iteration: 918/59290
Iteration: 919/59290
Iteration: 920/59290

  2%|▏         | 921/59290 [01:30<18:29, 52.60it/s]

Iteration: 921/59290
Iteration: 922/59290
Iteration: 923/59290
Iteration: 924/59290
Iteration: 925/59290
Iteration: 926/59290
Iteration: 927/59290
Iteration: 928/59290
Iteration: 929/59290
Iteration: 930/59290
Iteration: 931/59290
Iteration: 932/59290
Iteration: 933/59290
Iteration: 934/59290
Iteration: 935/59290
Iteration: 936/59290
Iteration: 937/59290
Iteration: 938/59290
Iteration: 939/59290
Iteration: 940/59290
Iteration: 941/59290
Iteration: 942/59290
Iteration: 943/59290
Iteration: 944/59290

  2%|▏         | 945/59290 [01:30<17:45, 54.78it/s]

Iteration: 945/59290
Iteration: 946/59290
Iteration: 947/59290
Iteration: 948/59290
Iteration: 949/59290
Iteration: 950/59290
Iteration: 951/59290
Iteration: 952/59290
Iteration: 953/59290
Iteration: 954/59290
Iteration: 955/59290
Iteration: 956/59290
Iteration: 957/59290
Iteration: 958/59290
Iteration: 959/59290
Iteration: 960/59290
Iteration: 961/59290
Iteration: 962/59290
Iteration: 963/59290
Iteration: 964/59290
Iteration: 965/59290
Iteration: 966/59290
Iteration: 967/59290
Iteration: 968/59290

  2%|▏         | 969/59290 [01:31<17:02, 57.01it/s]

Iteration: 969/59290
Iteration: 970/59290
Iteration: 971/59290
Iteration: 972/59290
Iteration: 973/59290
Iteration: 974/59290
Iteration: 975/59290
Iteration: 976/59290
Iteration: 977/59290
Iteration: 978/59290
Iteration: 979/59290
Iteration: 980/59290
Iteration: 981/59290
Iteration: 982/59290
Iteration: 983/59290
Iteration: 984/59290
Iteration: 985/59290
Iteration: 986/59290
Iteration: 987/59290
Iteration: 988/59290
Iteration: 989/59290
Iteration: 990/59290
Iteration: 991/59290
Iteration: 992/59290

  2%|▏         | 993/59290 [01:32<27:20, 35.54it/s]

Iteration: 993/59290
Iteration: 994/59290
Iteration: 995/59290
Iteration: 996/59290
Iteration: 997/59290
Iteration: 998/59290
Iteration: 999/59290
Iteration: 1000/59290
Iteration: 1001/59290
Iteration: 1002/59290
Iteration: 1003/59290
Iteration: 1004/59290
Iteration: 1005/59290
Iteration: 1006/59290
Iteration: 1007/59290
Iteration: 1008/59290
Iteration: 1009/59290
Iteration: 1010/59290
Iteration: 1011/59290
Iteration: 1012/59290
Iteration: 1013/59290
Iteration: 1014/59290
Iteration: 1015/59290
Iteration: 1016/59290

  2%|▏         | 1017/59290 [01:34<43:33, 22.30it/s]

Iteration: 1017/59290
Iteration: 1018/59290
Iteration: 1019/59290
Iteration: 1020/59290
Iteration: 1021/59290
Iteration: 1022/59290
Iteration: 1023/59290
Iteration: 1024/59290
Iteration: 1025/59290
Iteration: 1026/59290
Iteration: 1027/59290
Iteration: 1028/59290
Iteration: 1029/59290
Iteration: 1030/59290
Iteration: 1031/59290
Iteration: 1032/59290
Iteration: 1033/59290
Iteration: 1034/59290
Iteration: 1035/59290
Iteration: 1036/59290
Iteration: 1037/59290
Iteration: 1038/59290
Iteration: 1039/59290
Iteration: 1040/59290

  2%|▏         | 1041/59290 [01:34<37:16, 26.04it/s]

Iteration: 1041/59290
Iteration: 1042/59290
Iteration: 1043/59290
Iteration: 1044/59290
Iteration: 1045/59290
Iteration: 1046/59290
Iteration: 1047/59290
Iteration: 1048/59290
Iteration: 1049/59290
Iteration: 1050/59290
Iteration: 1051/59290
Iteration: 1052/59290
Iteration: 1053/59290
Iteration: 1054/59290
Iteration: 1055/59290
Iteration: 1056/59290
Iteration: 1057/59290
Iteration: 1058/59290
Iteration: 1059/59290
Iteration: 1060/59290
Iteration: 1061/59290
Iteration: 1062/59290
Iteration: 1063/59290
Iteration: 1064/59290

  2%|▏         | 1065/59290 [01:35<30:36, 31.71it/s]

Iteration: 1065/59290
Iteration: 1066/59290
Iteration: 1067/59290
Iteration: 1068/59290
Iteration: 1069/59290
Iteration: 1070/59290
Iteration: 1071/59290
Iteration: 1072/59290
Iteration: 1073/59290
Iteration: 1074/59290
Iteration: 1075/59290
Iteration: 1076/59290
Iteration: 1077/59290
Iteration: 1078/59290
Iteration: 1079/59290
Iteration: 1080/59290
Iteration: 1081/59290
Iteration: 1082/59290
Iteration: 1083/59290
Iteration: 1084/59290
Iteration: 1085/59290
Iteration: 1086/59290
Iteration: 1087/59290
Iteration: 1088/59290

  2%|▏         | 1089/59290 [01:35<26:07, 37.12it/s]

Iteration: 1089/59290
Iteration: 1090/59290
Iteration: 1091/59290
Iteration: 1092/59290
Iteration: 1093/59290
Iteration: 1094/59290
Iteration: 1095/59290
Iteration: 1096/59290
Iteration: 1097/59290
Iteration: 1098/59290
Iteration: 1099/59290
Iteration: 1100/59290
Iteration: 1101/59290
Iteration: 1102/59290
Iteration: 1103/59290
Iteration: 1104/59290
Iteration: 1105/59290
Iteration: 1106/59290
Iteration: 1107/59290
Iteration: 1108/59290
Iteration: 1109/59290
Iteration: 1110/59290
Iteration: 1111/59290
Iteration: 1112/59290

  2%|▏         | 1113/59290 [01:37<37:36, 25.78it/s]

Iteration: 1113/59290
Iteration: 1114/59290
Iteration: 1115/59290
Iteration: 1116/59290
Iteration: 1117/59290
Iteration: 1118/59290
Iteration: 1119/59290
Iteration: 1120/59290
Iteration: 1121/59290
Iteration: 1122/59290
Iteration: 1123/59290
Iteration: 1124/59290
Iteration: 1125/59290
Iteration: 1126/59290
Iteration: 1127/59290
Iteration: 1128/59290
Iteration: 1129/59290
Iteration: 1130/59290
Iteration: 1131/59290
Iteration: 1132/59290
Iteration: 1133/59290
Iteration: 1134/59290
Iteration: 1135/59290
Iteration: 1136/59290

  2%|▏         | 1137/59290 [01:39<55:44, 17.39it/s]

Iteration: 1137/59290
Iteration: 1138/59290
Iteration: 1139/59290
Iteration: 1140/59290
Iteration: 1141/59290
Iteration: 1142/59290
Iteration: 1143/59290
Iteration: 1144/59290
Iteration: 1145/59290
Iteration: 1146/59290
Iteration: 1147/59290
Iteration: 1148/59290
Iteration: 1149/59290
Iteration: 1150/59290
Iteration: 1151/59290
Iteration: 1152/59290
Iteration: 1153/59290
Iteration: 1154/59290
Iteration: 1155/59290
Iteration: 1156/59290
Iteration: 1157/59290
Iteration: 1158/59290
Iteration: 1159/59290
Iteration: 1160/59290

  2%|▏         | 1161/59290 [01:40<43:33, 22.25it/s]

Iteration: 1161/59290
Iteration: 1162/59290
Iteration: 1163/59290
Iteration: 1164/59290
Iteration: 1165/59290
Iteration: 1166/59290
Iteration: 1167/59290
Iteration: 1168/59290
Iteration: 1169/59290
Iteration: 1170/59290
Iteration: 1171/59290
Iteration: 1172/59290
Iteration: 1173/59290
Iteration: 1174/59290
Iteration: 1175/59290
Iteration: 1176/59290
Iteration: 1177/59290
Iteration: 1178/59290
Iteration: 1179/59290
Iteration: 1180/59290
Iteration: 1181/59290
Iteration: 1182/59290
Iteration: 1183/59290
Iteration: 1184/59290

  2%|▏         | 1185/59290 [01:40<35:10, 27.54it/s]

Iteration: 1185/59290
Iteration: 1186/59290
Iteration: 1187/59290
Iteration: 1188/59290
Iteration: 1189/59290
Iteration: 1190/59290
Iteration: 1191/59290
Iteration: 1192/59290
Iteration: 1193/59290
Iteration: 1194/59290
Iteration: 1195/59290
Iteration: 1196/59290
Iteration: 1197/59290
Iteration: 1198/59290
Iteration: 1199/59290
Iteration: 1200/59290
Iteration: 1201/59290
Iteration: 1202/59290
Iteration: 1203/59290
Iteration: 1204/59290
Iteration: 1205/59290
Iteration: 1206/59290
Iteration: 1207/59290
Iteration: 1208/59290

  2%|▏         | 1209/59290 [01:40<29:12, 33.14it/s]

Iteration: 1209/59290
Iteration: 1210/59290
Iteration: 1211/59290
Iteration: 1212/59290
Iteration: 1213/59290
Iteration: 1214/59290
Iteration: 1215/59290
Iteration: 1216/59290
Iteration: 1217/59290
Iteration: 1218/59290
Iteration: 1219/59290
Iteration: 1220/59290
Iteration: 1221/59290
Iteration: 1222/59290
Iteration: 1223/59290
Iteration: 1224/59290
Iteration: 1225/59290
Iteration: 1226/59290
Iteration: 1227/59290
Iteration: 1228/59290
Iteration: 1229/59290
Iteration: 1230/59290
Iteration: 1231/59290
Iteration: 1232/59290

  2%|▏         | 1233/59290 [01:41<25:04, 38.59it/s]

Iteration: 1233/59290
Iteration: 1234/59290
Iteration: 1235/59290
Iteration: 1236/59290
Iteration: 1237/59290
Iteration: 1238/59290
Iteration: 1239/59290
Iteration: 1240/59290
Iteration: 1241/59290
Iteration: 1242/59290
Iteration: 1243/59290
Iteration: 1244/59290
Iteration: 1245/59290
Iteration: 1246/59290
Iteration: 1247/59290
Iteration: 1248/59290
Iteration: 1249/59290
Iteration: 1250/59290
Iteration: 1251/59290
Iteration: 1252/59290
Iteration: 1253/59290
Iteration: 1254/59290
Iteration: 1255/59290
Iteration: 1256/59290

  2%|▏         | 1257/59290 [01:41<22:04, 43.80it/s]

Iteration: 1257/59290
Iteration: 1258/59290
Iteration: 1259/59290
Iteration: 1260/59290
Iteration: 1261/59290
Iteration: 1262/59290
Iteration: 1263/59290
Iteration: 1264/59290
Iteration: 1265/59290
Iteration: 1266/59290
Iteration: 1267/59290
Iteration: 1268/59290
Iteration: 1269/59290
Iteration: 1270/59290
Iteration: 1271/59290
Iteration: 1272/59290
Iteration: 1273/59290
Iteration: 1274/59290
Iteration: 1275/59290
Iteration: 1276/59290
Iteration: 1277/59290
Iteration: 1278/59290
Iteration: 1279/59290
Iteration: 1280/59290

  2%|▏         | 1281/59290 [01:42<20:01, 48.29it/s]

Iteration: 1281/59290
Iteration: 1282/59290
Iteration: 1283/59290
Iteration: 1284/59290
Iteration: 1285/59290
Iteration: 1286/59290
Iteration: 1287/59290
Iteration: 1288/59290
Iteration: 1289/59290
Iteration: 1290/59290
Iteration: 1291/59290
Iteration: 1292/59290
Iteration: 1293/59290
Iteration: 1294/59290
Iteration: 1295/59290
Iteration: 1296/59290
Iteration: 1297/59290
Iteration: 1298/59290
Iteration: 1299/59290
Iteration: 1300/59290
Iteration: 1301/59290
Iteration: 1302/59290
Iteration: 1303/59290
Iteration: 1304/59290

  2%|▏         | 1305/59290 [01:43<32:52, 29.39it/s]

Iteration: 1305/59290
Iteration: 1306/59290
Iteration: 1307/59290
Iteration: 1308/59290
Iteration: 1309/59290
Iteration: 1310/59290
Iteration: 1311/59290
Iteration: 1312/59290
Iteration: 1313/59290
Iteration: 1314/59290
Iteration: 1315/59290
Iteration: 1316/59290
Iteration: 1317/59290
Iteration: 1318/59290
Iteration: 1319/59290
Iteration: 1320/59290
Iteration: 1321/59290
Iteration: 1322/59290
Iteration: 1323/59290
Iteration: 1324/59290
Iteration: 1325/59290
Iteration: 1326/59290
Iteration: 1327/59290
Iteration: 1328/59290

  2%|▏         | 1329/59290 [01:45<50:28, 19.14it/s]

Iteration: 1329/59290
Iteration: 1330/59290
Iteration: 1331/59290
Iteration: 1332/59290
Iteration: 1333/59290
Iteration: 1334/59290
Iteration: 1335/59290
Iteration: 1336/59290
Iteration: 1337/59290
Iteration: 1338/59290
Iteration: 1339/59290
Iteration: 1340/59290
Iteration: 1341/59290
Iteration: 1342/59290
Iteration: 1343/59290
Iteration: 1344/59290
Iteration: 1345/59290
Iteration: 1346/59290
Iteration: 1347/59290
Iteration: 1348/59290
Iteration: 1349/59290
Iteration: 1350/59290
Iteration: 1351/59290
Iteration: 1352/59290

  2%|▏         | 1353/59290 [01:46<40:09, 24.04it/s]

Iteration: 1353/59290
Iteration: 1354/59290
Iteration: 1355/59290
Iteration: 1356/59290
Iteration: 1357/59290
Iteration: 1358/59290
Iteration: 1359/59290
Iteration: 1360/59290
Iteration: 1361/59290
Iteration: 1362/59290
Iteration: 1363/59290
Iteration: 1364/59290
Iteration: 1365/59290
Iteration: 1366/59290
Iteration: 1367/59290
Iteration: 1368/59290
Iteration: 1369/59290
Iteration: 1370/59290
Iteration: 1371/59290
Iteration: 1372/59290
Iteration: 1373/59290
Iteration: 1374/59290
Iteration: 1375/59290
Iteration: 1376/59290

  2%|▏         | 1377/59290 [01:46<32:36, 29.60it/s]

Iteration: 1377/59290
Iteration: 1378/59290
Iteration: 1379/59290
Iteration: 1380/59290
Iteration: 1381/59290
Iteration: 1382/59290
Iteration: 1383/59290
Iteration: 1384/59290
Iteration: 1385/59290
Iteration: 1386/59290
Iteration: 1387/59290
Iteration: 1388/59290
Iteration: 1389/59290
Iteration: 1390/59290
Iteration: 1391/59290
Iteration: 1392/59290
Iteration: 1393/59290
Iteration: 1394/59290
Iteration: 1395/59290
Iteration: 1396/59290
Iteration: 1397/59290
Iteration: 1398/59290
Iteration: 1399/59290
Iteration: 1400/59290

  2%|▏         | 1401/59290 [01:47<27:21, 35.27it/s]

Iteration: 1401/59290
Iteration: 1402/59290
Iteration: 1403/59290
Iteration: 1404/59290
Iteration: 1405/59290
Iteration: 1406/59290
Iteration: 1407/59290
Iteration: 1408/59290
Iteration: 1409/59290
Iteration: 1410/59290
Iteration: 1411/59290
Iteration: 1412/59290
Iteration: 1413/59290
Iteration: 1414/59290
Iteration: 1415/59290
Iteration: 1416/59290
Iteration: 1417/59290
Iteration: 1418/59290
Iteration: 1419/59290
Iteration: 1420/59290
Iteration: 1421/59290
Iteration: 1422/59290
Iteration: 1423/59290
Iteration: 1424/59290

  2%|▏         | 1425/59290 [01:47<23:42, 40.69it/s]

Iteration: 1425/59290
Iteration: 1426/59290
Iteration: 1427/59290
Iteration: 1428/59290
Iteration: 1429/59290
Iteration: 1430/59290
Iteration: 1431/59290
Iteration: 1432/59290
Iteration: 1433/59290
Iteration: 1434/59290
Iteration: 1435/59290
Iteration: 1436/59290
Iteration: 1437/59290
Iteration: 1438/59290
Iteration: 1439/59290
Iteration: 1440/59290
Iteration: 1441/59290
Iteration: 1442/59290
Iteration: 1443/59290
Iteration: 1444/59290
Iteration: 1445/59290
Iteration: 1446/59290
Iteration: 1447/59290
Iteration: 1448/59290

  2%|▏         | 1449/59290 [01:47<21:11, 45.49it/s]

Iteration: 1449/59290
Iteration: 1450/59290
Iteration: 1451/59290
Iteration: 1452/59290
Iteration: 1453/59290
Iteration: 1454/59290
Iteration: 1455/59290
Iteration: 1456/59290
Iteration: 1457/59290
Iteration: 1458/59290
Iteration: 1459/59290
Iteration: 1460/59290
Iteration: 1461/59290
Iteration: 1462/59290
Iteration: 1463/59290
Iteration: 1464/59290
Iteration: 1465/59290
Iteration: 1466/59290
Iteration: 1467/59290
Iteration: 1468/59290
Iteration: 1469/59290
Iteration: 1470/59290
Iteration: 1471/59290
Iteration: 1472/59290

  2%|▏         | 1473/59290 [01:48<19:21, 49.77it/s]

Iteration: 1473/59290
Iteration: 1474/59290
Iteration: 1475/59290
Iteration: 1476/59290
Iteration: 1477/59290
Iteration: 1478/59290
Iteration: 1479/59290
Iteration: 1480/59290
Iteration: 1481/59290
Iteration: 1482/59290
Iteration: 1483/59290
Iteration: 1484/59290
Iteration: 1485/59290
Iteration: 1486/59290
Iteration: 1487/59290
Iteration: 1488/59290
Iteration: 1489/59290
Iteration: 1490/59290
Iteration: 1491/59290
Iteration: 1492/59290
Iteration: 1493/59290
Iteration: 1494/59290
Iteration: 1495/59290
Iteration: 1496/59290

  3%|▎         | 1497/59290 [01:48<18:08, 53.07it/s]

Iteration: 1497/59290
Iteration: 1498/59290
Iteration: 1499/59290
Iteration: 1500/59290
Iteration: 1501/59290
Iteration: 1502/59290
Iteration: 1503/59290
Iteration: 1504/59290
Iteration: 1505/59290
Iteration: 1506/59290
Iteration: 1507/59290
Iteration: 1508/59290
Iteration: 1509/59290
Iteration: 1510/59290
Iteration: 1511/59290
Iteration: 1512/59290
Iteration: 1513/59290
Iteration: 1514/59290
Iteration: 1515/59290
Iteration: 1516/59290
Iteration: 1517/59290
Iteration: 1518/59290
Iteration: 1519/59290
Iteration: 1520/59290

  3%|▎         | 1521/59290 [01:48<17:29, 55.07it/s]

Iteration: 1521/59290
Iteration: 1522/59290
Iteration: 1523/59290
Iteration: 1524/59290
Iteration: 1525/59290
Iteration: 1526/59290
Iteration: 1527/59290
Iteration: 1528/59290
Iteration: 1529/59290
Iteration: 1530/59290
Iteration: 1531/59290
Iteration: 1532/59290
Iteration: 1533/59290
Iteration: 1534/59290
Iteration: 1535/59290
Iteration: 1536/59290
Iteration: 1537/59290
Iteration: 1538/59290
Iteration: 1539/59290
Iteration: 1540/59290
Iteration: 1541/59290
Iteration: 1542/59290
Iteration: 1543/59290
Iteration: 1544/59290

  3%|▎         | 1545/59290 [01:49<17:02, 56.46it/s]

Iteration: 1545/59290
Iteration: 1546/59290
Iteration: 1547/59290
Iteration: 1548/59290
Iteration: 1549/59290
Iteration: 1550/59290
Iteration: 1551/59290
Iteration: 1552/59290
Iteration: 1553/59290
Iteration: 1554/59290
Iteration: 1555/59290
Iteration: 1556/59290
Iteration: 1557/59290
Iteration: 1558/59290
Iteration: 1559/59290
Iteration: 1560/59290
Iteration: 1561/59290
Iteration: 1562/59290
Iteration: 1563/59290
Iteration: 1564/59290
Iteration: 1565/59290
Iteration: 1566/59290
Iteration: 1567/59290
Iteration: 1568/59290

  3%|▎         | 1569/59290 [01:49<16:25, 58.56it/s]

Iteration: 1569/59290
Iteration: 1570/59290
Iteration: 1571/59290
Iteration: 1572/59290
Iteration: 1573/59290
Iteration: 1574/59290
Iteration: 1575/59290
Iteration: 1576/59290
Iteration: 1577/59290
Iteration: 1578/59290
Iteration: 1579/59290
Iteration: 1580/59290
Iteration: 1581/59290
Iteration: 1582/59290
Iteration: 1583/59290
Iteration: 1584/59290
Iteration: 1585/59290
Iteration: 1586/59290
Iteration: 1587/59290
Iteration: 1588/59290
Iteration: 1589/59290
Iteration: 1590/59290
Iteration: 1591/59290
Iteration: 1592/59290

  3%|▎         | 1593/59290 [01:51<27:48, 34.59it/s]

Iteration: 1593/59290
Iteration: 1594/59290
Iteration: 1595/59290
Iteration: 1596/59290
Iteration: 1597/59290
Iteration: 1598/59290
Iteration: 1599/59290
Iteration: 1600/59290
Iteration: 1601/59290
Iteration: 1602/59290
Iteration: 1603/59290
Iteration: 1604/59290
Iteration: 1605/59290
Iteration: 1606/59290
Iteration: 1607/59290
Iteration: 1608/59290
Iteration: 1609/59290
Iteration: 1610/59290
Iteration: 1611/59290
Iteration: 1612/59290
Iteration: 1613/59290
Iteration: 1614/59290
Iteration: 1615/59290
Iteration: 1616/59290

  3%|▎         | 1617/59290 [01:53<43:24, 22.14it/s]

Iteration: 1617/59290
Iteration: 1618/59290
Iteration: 1619/59290
Iteration: 1620/59290
Iteration: 1621/59290
Iteration: 1622/59290
Iteration: 1623/59290
Iteration: 1624/59290
Iteration: 1625/59290
Iteration: 1626/59290
Iteration: 1627/59290
Iteration: 1628/59290
Iteration: 1629/59290
Iteration: 1630/59290
Iteration: 1631/59290
Iteration: 1632/59290
Iteration: 1633/59290
Iteration: 1634/59290
Iteration: 1635/59290
Iteration: 1636/59290
Iteration: 1637/59290
Iteration: 1638/59290
Iteration: 1639/59290
Iteration: 1640/59290

  3%|▎         | 1641/59290 [01:53<36:36, 26.24it/s]

Iteration: 1641/59290
Iteration: 1642/59290
Iteration: 1643/59290
Iteration: 1644/59290
Iteration: 1645/59290
Iteration: 1646/59290
Iteration: 1647/59290
Iteration: 1648/59290
Iteration: 1649/59290
Iteration: 1650/59290
Iteration: 1651/59290
Iteration: 1652/59290
Iteration: 1653/59290
Iteration: 1654/59290
Iteration: 1655/59290
Iteration: 1656/59290
Iteration: 1657/59290
Iteration: 1658/59290
Iteration: 1659/59290
Iteration: 1660/59290
Iteration: 1661/59290
Iteration: 1662/59290
Iteration: 1663/59290
Iteration: 1664/59290

  3%|▎         | 1665/59290 [01:53<30:07, 31.88it/s]

Iteration: 1665/59290
Iteration: 1666/59290
Iteration: 1667/59290
Iteration: 1668/59290
Iteration: 1669/59290
Iteration: 1670/59290
Iteration: 1671/59290
Iteration: 1672/59290
Iteration: 1673/59290
Iteration: 1674/59290
Iteration: 1675/59290
Iteration: 1676/59290
Iteration: 1677/59290
Iteration: 1678/59290
Iteration: 1679/59290
Iteration: 1680/59290
Iteration: 1681/59290
Iteration: 1682/59290
Iteration: 1683/59290
Iteration: 1684/59290
Iteration: 1685/59290
Iteration: 1686/59290
Iteration: 1687/59290
Iteration: 1688/59290

  3%|▎         | 1689/59290 [01:54<25:34, 37.54it/s]

Iteration: 1689/59290
Iteration: 1690/59290
Iteration: 1691/59290
Iteration: 1692/59290
Iteration: 1693/59290
Iteration: 1694/59290
Iteration: 1695/59290
Iteration: 1696/59290
Iteration: 1697/59290
Iteration: 1698/59290
Iteration: 1699/59290
Iteration: 1700/59290
Iteration: 1701/59290
Iteration: 1702/59290
Iteration: 1703/59290
Iteration: 1704/59290
Iteration: 1705/59290
Iteration: 1706/59290
Iteration: 1707/59290
Iteration: 1708/59290
Iteration: 1709/59290
Iteration: 1710/59290
Iteration: 1711/59290
Iteration: 1712/59290

  3%|▎         | 1713/59290 [01:54<22:26, 42.76it/s]

Iteration: 1713/59290
Iteration: 1714/59290
Iteration: 1715/59290
Iteration: 1716/59290
Iteration: 1717/59290
Iteration: 1718/59290
Iteration: 1719/59290
Iteration: 1720/59290
Iteration: 1721/59290
Iteration: 1722/59290
Iteration: 1723/59290
Iteration: 1724/59290
Iteration: 1725/59290
Iteration: 1726/59290
Iteration: 1727/59290
Iteration: 1728/59290
Iteration: 1729/59290
Iteration: 1730/59290
Iteration: 1731/59290
Iteration: 1732/59290
Iteration: 1733/59290
Iteration: 1734/59290
Iteration: 1735/59290
Iteration: 1736/59290

  3%|▎         | 1737/59290 [01:56<32:23, 29.61it/s]

Iteration: 1737/59290
Iteration: 1738/59290
Iteration: 1739/59290
Iteration: 1740/59290
Iteration: 1741/59290
Iteration: 1742/59290
Iteration: 1743/59290
Iteration: 1744/59290
Iteration: 1745/59290
Iteration: 1746/59290
Iteration: 1747/59290
Iteration: 1748/59290
Iteration: 1749/59290
Iteration: 1750/59290
Iteration: 1751/59290
Iteration: 1752/59290
Iteration: 1753/59290
Iteration: 1754/59290
Iteration: 1755/59290
Iteration: 1756/59290
Iteration: 1757/59290
Iteration: 1758/59290
Iteration: 1759/59290
Iteration: 1760/59290

  3%|▎         | 1761/59290 [01:58<50:45, 18.89it/s]

Iteration: 1761/59290
Iteration: 1762/59290
Iteration: 1763/59290
Iteration: 1764/59290
Iteration: 1765/59290
Iteration: 1766/59290
Iteration: 1767/59290
Iteration: 1768/59290
Iteration: 1769/59290
Iteration: 1770/59290
Iteration: 1771/59290
Iteration: 1772/59290
Iteration: 1773/59290
Iteration: 1774/59290
Iteration: 1775/59290
Iteration: 1776/59290
Iteration: 1777/59290
Iteration: 1778/59290
Iteration: 1779/59290
Iteration: 1780/59290
Iteration: 1781/59290
Iteration: 1782/59290
Iteration: 1783/59290
Iteration: 1784/59290

  3%|▎         | 1785/59290 [01:58<40:00, 23.96it/s]

Iteration: 1785/59290
Iteration: 1786/59290
Iteration: 1787/59290
Iteration: 1788/59290
Iteration: 1789/59290
Iteration: 1790/59290
Iteration: 1791/59290
Iteration: 1792/59290
Iteration: 1793/59290
Iteration: 1794/59290
Iteration: 1795/59290
Iteration: 1796/59290
Iteration: 1797/59290
Iteration: 1798/59290
Iteration: 1799/59290
Iteration: 1800/59290
Iteration: 1801/59290
Iteration: 1802/59290
Iteration: 1803/59290
Iteration: 1804/59290
Iteration: 1805/59290
Iteration: 1806/59290
Iteration: 1807/59290
Iteration: 1808/59290

  3%|▎         | 1809/59290 [01:59<32:26, 29.53it/s]

Iteration: 1809/59290
Iteration: 1810/59290
Iteration: 1811/59290
Iteration: 1812/59290
Iteration: 1813/59290
Iteration: 1814/59290
Iteration: 1815/59290
Iteration: 1816/59290
Iteration: 1817/59290
Iteration: 1818/59290
Iteration: 1819/59290
Iteration: 1820/59290
Iteration: 1821/59290
Iteration: 1822/59290
Iteration: 1823/59290
Iteration: 1824/59290
Iteration: 1825/59290
Iteration: 1826/59290
Iteration: 1827/59290
Iteration: 1828/59290
Iteration: 1829/59290
Iteration: 1830/59290
Iteration: 1831/59290
Iteration: 1832/59290

  3%|▎         | 1833/59290 [01:59<27:17, 35.09it/s]

Iteration: 1833/59290
Iteration: 1834/59290
Iteration: 1835/59290
Iteration: 1836/59290
Iteration: 1837/59290
Iteration: 1838/59290
Iteration: 1839/59290
Iteration: 1840/59290
Iteration: 1841/59290
Iteration: 1842/59290
Iteration: 1843/59290
Iteration: 1844/59290
Iteration: 1845/59290
Iteration: 1846/59290
Iteration: 1847/59290
Iteration: 1848/59290
Iteration: 1849/59290
Iteration: 1850/59290
Iteration: 1851/59290
Iteration: 1852/59290
Iteration: 1853/59290
Iteration: 1854/59290
Iteration: 1855/59290
Iteration: 1856/59290

  3%|▎         | 1857/59290 [01:59<23:36, 40.55it/s]

Iteration: 1857/59290
Iteration: 1858/59290
Iteration: 1859/59290
Iteration: 1860/59290
Iteration: 1861/59290
Iteration: 1862/59290
Iteration: 1863/59290
Iteration: 1864/59290
Iteration: 1865/59290
Iteration: 1866/59290
Iteration: 1867/59290
Iteration: 1868/59290
Iteration: 1869/59290
Iteration: 1870/59290
Iteration: 1871/59290
Iteration: 1872/59290
Iteration: 1873/59290
Iteration: 1874/59290
Iteration: 1875/59290
Iteration: 1876/59290
Iteration: 1877/59290
Iteration: 1878/59290
Iteration: 1879/59290
Iteration: 1880/59290

  3%|▎         | 1881/59290 [02:01<35:37, 26.86it/s]

Iteration: 1881/59290
Iteration: 1882/59290
Iteration: 1883/59290
Iteration: 1884/59290
Iteration: 1885/59290
Iteration: 1886/59290
Iteration: 1887/59290
Iteration: 1888/59290
Iteration: 1889/59290
Iteration: 1890/59290
Iteration: 1891/59290
Iteration: 1892/59290
Iteration: 1893/59290
Iteration: 1894/59290
Iteration: 1895/59290
Iteration: 1896/59290
Iteration: 1897/59290
Iteration: 1898/59290
Iteration: 1899/59290
Iteration: 1900/59290
Iteration: 1901/59290
Iteration: 1902/59290
Iteration: 1903/59290
Iteration: 1904/59290

  3%|▎         | 1905/59290 [02:03<48:13, 19.83it/s]

Iteration: 1905/59290
Iteration: 1906/59290
Iteration: 1907/59290
Iteration: 1908/59290
Iteration: 1909/59290
Iteration: 1910/59290
Iteration: 1911/59290
Iteration: 1912/59290
Iteration: 1913/59290
Iteration: 1914/59290
Iteration: 1915/59290
Iteration: 1916/59290
Iteration: 1917/59290
Iteration: 1918/59290
Iteration: 1919/59290
Iteration: 1920/59290
Iteration: 1921/59290
Iteration: 1922/59290
Iteration: 1923/59290
Iteration: 1924/59290
Iteration: 1925/59290
Iteration: 1926/59290
Iteration: 1927/59290
Iteration: 1928/59290

  3%|▎         | 1929/59290 [02:04<41:31, 23.02it/s]

Iteration: 1929/59290
Iteration: 1930/59290
Iteration: 1931/59290
Iteration: 1932/59290
Iteration: 1933/59290
Iteration: 1934/59290
Iteration: 1935/59290
Iteration: 1936/59290
Iteration: 1937/59290
Iteration: 1938/59290
Iteration: 1939/59290
Iteration: 1940/59290
Iteration: 1941/59290
Iteration: 1942/59290
Iteration: 1943/59290
Iteration: 1944/59290
Iteration: 1945/59290
Iteration: 1946/59290
Iteration: 1947/59290
Iteration: 1948/59290
Iteration: 1949/59290
Iteration: 1950/59290
Iteration: 1951/59290
Iteration: 1952/59290

  3%|▎         | 1953/59290 [02:04<33:41, 28.36it/s]

Iteration: 1953/59290
Iteration: 1954/59290
Iteration: 1955/59290
Iteration: 1956/59290
Iteration: 1957/59290
Iteration: 1958/59290
Iteration: 1959/59290
Iteration: 1960/59290
Iteration: 1961/59290
Iteration: 1962/59290
Iteration: 1963/59290
Iteration: 1964/59290
Iteration: 1965/59290
Iteration: 1966/59290
Iteration: 1967/59290
Iteration: 1968/59290
Iteration: 1969/59290
Iteration: 1970/59290
Iteration: 1971/59290
Iteration: 1972/59290
Iteration: 1973/59290
Iteration: 1974/59290
Iteration: 1975/59290
Iteration: 1976/59290

  3%|▎         | 1977/59290 [02:04<28:01, 34.08it/s]

Iteration: 1977/59290
Iteration: 1978/59290
Iteration: 1979/59290
Iteration: 1980/59290
Iteration: 1981/59290
Iteration: 1982/59290
Iteration: 1983/59290
Iteration: 1984/59290
Iteration: 1985/59290
Iteration: 1986/59290
Iteration: 1987/59290
Iteration: 1988/59290
Iteration: 1989/59290
Iteration: 1990/59290
Iteration: 1991/59290
Iteration: 1992/59290
Iteration: 1993/59290
Iteration: 1994/59290
Iteration: 1995/59290
Iteration: 1996/59290
Iteration: 1997/59290
Iteration: 1998/59290
Iteration: 1999/59290
Iteration: 2000/59290

  3%|▎         | 2001/59290 [02:05<24:04, 39.66it/s]

Iteration: 2001/59290
Iteration: 2002/59290
Iteration: 2003/59290
Iteration: 2004/59290
Iteration: 2005/59290
Iteration: 2006/59290
Iteration: 2007/59290
Iteration: 2008/59290
Iteration: 2009/59290
Iteration: 2010/59290
Iteration: 2011/59290
Iteration: 2012/59290
Iteration: 2013/59290
Iteration: 2014/59290
Iteration: 2015/59290
Iteration: 2016/59290
Iteration: 2017/59290
Iteration: 2018/59290
Iteration: 2019/59290
Iteration: 2020/59290
Iteration: 2021/59290
Iteration: 2022/59290
Iteration: 2023/59290
Iteration: 2024/59290

  3%|▎         | 2025/59290 [02:05<21:19, 44.76it/s]

Iteration: 2025/59290
Iteration: 2026/59290
Iteration: 2027/59290
Iteration: 2028/59290
Iteration: 2029/59290
Iteration: 2030/59290
Iteration: 2031/59290
Iteration: 2032/59290
Iteration: 2033/59290
Iteration: 2034/59290
Iteration: 2035/59290
Iteration: 2036/59290
Iteration: 2037/59290
Iteration: 2038/59290
Iteration: 2039/59290
Iteration: 2040/59290
Iteration: 2041/59290
Iteration: 2042/59290
Iteration: 2043/59290
Iteration: 2044/59290
Iteration: 2045/59290
Iteration: 2046/59290
Iteration: 2047/59290
Iteration: 2048/59290

  3%|▎         | 2049/59290 [02:07<32:01, 29.80it/s]

Iteration: 2049/59290
Iteration: 2050/59290
Iteration: 2051/59290
Iteration: 2052/59290
Iteration: 2053/59290
Iteration: 2054/59290
Iteration: 2055/59290
Iteration: 2056/59290
Iteration: 2057/59290
Iteration: 2058/59290
Iteration: 2059/59290
Iteration: 2060/59290
Iteration: 2061/59290
Iteration: 2062/59290
Iteration: 2063/59290
Iteration: 2064/59290
Iteration: 2065/59290
Iteration: 2066/59290
Iteration: 2067/59290
Iteration: 2068/59290
Iteration: 2069/59290
Iteration: 2070/59290
Iteration: 2071/59290
Iteration: 2072/59290

  3%|▎         | 2073/59290 [02:09<50:53, 18.74it/s]

Iteration: 2073/59290
Iteration: 2074/59290
Iteration: 2075/59290
Iteration: 2076/59290
Iteration: 2077/59290
Iteration: 2078/59290
Iteration: 2079/59290
Iteration: 2080/59290
Iteration: 2081/59290
Iteration: 2082/59290
Iteration: 2083/59290
Iteration: 2084/59290
Iteration: 2085/59290
Iteration: 2086/59290
Iteration: 2087/59290
Iteration: 2088/59290
Iteration: 2089/59290
Iteration: 2090/59290
Iteration: 2091/59290
Iteration: 2092/59290
Iteration: 2093/59290
Iteration: 2094/59290
Iteration: 2095/59290
Iteration: 2096/59290

  4%|▎         | 2097/59290 [02:09<40:24, 23.59it/s]

Iteration: 2097/59290
Iteration: 2098/59290
Iteration: 2099/59290
Iteration: 2100/59290
Iteration: 2101/59290
Iteration: 2102/59290
Iteration: 2103/59290
Iteration: 2104/59290
Iteration: 2105/59290
Iteration: 2106/59290
Iteration: 2107/59290
Iteration: 2108/59290
Iteration: 2109/59290
Iteration: 2110/59290
Iteration: 2111/59290
Iteration: 2112/59290
Iteration: 2113/59290
Iteration: 2114/59290
Iteration: 2115/59290
Iteration: 2116/59290
Iteration: 2117/59290
Iteration: 2118/59290
Iteration: 2119/59290
Iteration: 2120/59290

  4%|▎         | 2121/59290 [02:10<32:55, 28.93it/s]

Iteration: 2121/59290
Iteration: 2122/59290
Iteration: 2123/59290
Iteration: 2124/59290
Iteration: 2125/59290
Iteration: 2126/59290
Iteration: 2127/59290
Iteration: 2128/59290
Iteration: 2129/59290
Iteration: 2130/59290
Iteration: 2131/59290
Iteration: 2132/59290
Iteration: 2133/59290
Iteration: 2134/59290
Iteration: 2135/59290
Iteration: 2136/59290
Iteration: 2137/59290
Iteration: 2138/59290
Iteration: 2139/59290
Iteration: 2140/59290
Iteration: 2141/59290
Iteration: 2142/59290
Iteration: 2143/59290
Iteration: 2144/59290

  4%|▎         | 2145/59290 [02:10<27:38, 34.45it/s]

Iteration: 2145/59290
Iteration: 2146/59290
Iteration: 2147/59290
Iteration: 2148/59290
Iteration: 2149/59290
Iteration: 2150/59290
Iteration: 2151/59290
Iteration: 2152/59290
Iteration: 2153/59290
Iteration: 2154/59290
Iteration: 2155/59290
Iteration: 2156/59290
Iteration: 2157/59290
Iteration: 2158/59290
Iteration: 2159/59290
Iteration: 2160/59290
Iteration: 2161/59290
Iteration: 2162/59290
Iteration: 2163/59290
Iteration: 2164/59290
Iteration: 2165/59290
Iteration: 2166/59290
Iteration: 2167/59290
Iteration: 2168/59290

  4%|▎         | 2169/59290 [02:11<23:51, 39.89it/s]

Iteration: 2169/59290
Iteration: 2170/59290
Iteration: 2171/59290
Iteration: 2172/59290
Iteration: 2173/59290
Iteration: 2174/59290
Iteration: 2175/59290
Iteration: 2176/59290
Iteration: 2177/59290
Iteration: 2178/59290
Iteration: 2179/59290
Iteration: 2180/59290
Iteration: 2181/59290
Iteration: 2182/59290
Iteration: 2183/59290
Iteration: 2184/59290
Iteration: 2185/59290
Iteration: 2186/59290
Iteration: 2187/59290
Iteration: 2188/59290
Iteration: 2189/59290
Iteration: 2190/59290
Iteration: 2191/59290
Iteration: 2192/59290

  4%|▎         | 2193/59290 [02:11<21:09, 44.96it/s]

Iteration: 2193/59290
Iteration: 2194/59290
Iteration: 2195/59290
Iteration: 2196/59290
Iteration: 2197/59290
Iteration: 2198/59290
Iteration: 2199/59290
Iteration: 2200/59290
Iteration: 2201/59290
Iteration: 2202/59290
Iteration: 2203/59290
Iteration: 2204/59290
Iteration: 2205/59290
Iteration: 2206/59290
Iteration: 2207/59290
Iteration: 2208/59290
Iteration: 2209/59290
Iteration: 2210/59290
Iteration: 2211/59290
Iteration: 2212/59290
Iteration: 2213/59290
Iteration: 2214/59290
Iteration: 2215/59290
Iteration: 2216/59290

  4%|▎         | 2217/59290 [02:11<19:50, 47.95it/s]

Iteration: 2217/59290
Iteration: 2218/59290
Iteration: 2219/59290
Iteration: 2220/59290
Iteration: 2221/59290
Iteration: 2222/59290
Iteration: 2223/59290
Iteration: 2224/59290
Iteration: 2225/59290
Iteration: 2226/59290
Iteration: 2227/59290
Iteration: 2228/59290
Iteration: 2229/59290
Iteration: 2230/59290
Iteration: 2231/59290
Iteration: 2232/59290
Iteration: 2233/59290
Iteration: 2234/59290
Iteration: 2235/59290
Iteration: 2236/59290
Iteration: 2237/59290
Iteration: 2238/59290
Iteration: 2239/59290
Iteration: 2240/59290

  4%|▍         | 2241/59290 [02:13<28:30, 33.35it/s]

Iteration: 2241/59290
Iteration: 2242/59290
Iteration: 2243/59290
Iteration: 2244/59290
Iteration: 2245/59290
Iteration: 2246/59290
Iteration: 2247/59290
Iteration: 2248/59290
Iteration: 2249/59290
Iteration: 2250/59290
Iteration: 2251/59290
Iteration: 2252/59290
Iteration: 2253/59290
Iteration: 2254/59290
Iteration: 2255/59290
Iteration: 2256/59290
Iteration: 2257/59290
Iteration: 2258/59290
Iteration: 2259/59290
Iteration: 2260/59290
Iteration: 2261/59290
Iteration: 2262/59290
Iteration: 2263/59290
Iteration: 2264/59290

  4%|▍         | 2265/59290 [02:15<42:53, 22.16it/s]

Iteration: 2265/59290
Iteration: 2266/59290
Iteration: 2267/59290
Iteration: 2268/59290
Iteration: 2269/59290
Iteration: 2270/59290
Iteration: 2271/59290
Iteration: 2272/59290
Iteration: 2273/59290
Iteration: 2274/59290
Iteration: 2275/59290
Iteration: 2276/59290
Iteration: 2277/59290
Iteration: 2278/59290
Iteration: 2279/59290
Iteration: 2280/59290
Iteration: 2281/59290
Iteration: 2282/59290
Iteration: 2283/59290
Iteration: 2284/59290
Iteration: 2285/59290
Iteration: 2286/59290
Iteration: 2287/59290
Iteration: 2288/59290

  4%|▍         | 2289/59290 [02:15<36:36, 25.95it/s]

Iteration: 2289/59290
Iteration: 2290/59290
Iteration: 2291/59290
Iteration: 2292/59290
Iteration: 2293/59290
Iteration: 2294/59290
Iteration: 2295/59290
Iteration: 2296/59290
Iteration: 2297/59290
Iteration: 2298/59290
Iteration: 2299/59290
Iteration: 2300/59290
Iteration: 2301/59290
Iteration: 2302/59290
Iteration: 2303/59290
Iteration: 2304/59290
Iteration: 2305/59290
Iteration: 2306/59290
Iteration: 2307/59290
Iteration: 2308/59290
Iteration: 2309/59290
Iteration: 2310/59290
Iteration: 2311/59290
Iteration: 2312/59290

  4%|▍         | 2313/59290 [02:15<30:17, 31.35it/s]

Iteration: 2313/59290
Iteration: 2314/59290
Iteration: 2315/59290
Iteration: 2316/59290
Iteration: 2317/59290
Iteration: 2318/59290
Iteration: 2319/59290
Iteration: 2320/59290
Iteration: 2321/59290
Iteration: 2322/59290
Iteration: 2323/59290
Iteration: 2324/59290
Iteration: 2325/59290
Iteration: 2326/59290
Iteration: 2327/59290
Iteration: 2328/59290
Iteration: 2329/59290
Iteration: 2330/59290
Iteration: 2331/59290
Iteration: 2332/59290
Iteration: 2333/59290
Iteration: 2334/59290
Iteration: 2335/59290
Iteration: 2336/59290

  4%|▍         | 2337/59290 [02:16<25:52, 36.68it/s]

Iteration: 2337/59290
Iteration: 2338/59290
Iteration: 2339/59290
Iteration: 2340/59290
Iteration: 2341/59290
Iteration: 2342/59290
Iteration: 2343/59290
Iteration: 2344/59290
Iteration: 2345/59290
Iteration: 2346/59290
Iteration: 2347/59290
Iteration: 2348/59290
Iteration: 2349/59290
Iteration: 2350/59290
Iteration: 2351/59290
Iteration: 2352/59290
Iteration: 2353/59290
Iteration: 2354/59290
Iteration: 2355/59290
Iteration: 2356/59290
Iteration: 2357/59290
Iteration: 2358/59290
Iteration: 2359/59290
Iteration: 2360/59290

  4%|▍         | 2361/59290 [02:16<22:55, 41.39it/s]

Iteration: 2361/59290
Iteration: 2362/59290
Iteration: 2363/59290
Iteration: 2364/59290
Iteration: 2365/59290
Iteration: 2366/59290
Iteration: 2367/59290
Iteration: 2368/59290
Iteration: 2369/59290
Iteration: 2370/59290
Iteration: 2371/59290
Iteration: 2372/59290
Iteration: 2373/59290
Iteration: 2374/59290
Iteration: 2375/59290
Iteration: 2376/59290
Iteration: 2377/59290
Iteration: 2378/59290
Iteration: 2379/59290
Iteration: 2380/59290
Iteration: 2381/59290
Iteration: 2382/59290
Iteration: 2383/59290
Iteration: 2384/59290

  4%|▍         | 2385/59290 [02:17<20:25, 46.42it/s]

Iteration: 2385/59290
Iteration: 2386/59290
Iteration: 2387/59290
Iteration: 2388/59290
Iteration: 2389/59290
Iteration: 2390/59290
Iteration: 2391/59290
Iteration: 2392/59290
Iteration: 2393/59290
Iteration: 2394/59290
Iteration: 2395/59290
Iteration: 2396/59290
Iteration: 2397/59290
Iteration: 2398/59290
Iteration: 2399/59290
Iteration: 2400/59290
Iteration: 2401/59290
Iteration: 2402/59290
Iteration: 2403/59290
Iteration: 2404/59290
Iteration: 2405/59290
Iteration: 2406/59290
Iteration: 2407/59290
Iteration: 2408/59290

  4%|▍         | 2409/59290 [02:17<18:54, 50.15it/s]

Iteration: 2409/59290
Iteration: 2410/59290
Iteration: 2411/59290
Iteration: 2412/59290
Iteration: 2413/59290
Iteration: 2414/59290
Iteration: 2415/59290
Iteration: 2416/59290
Iteration: 2417/59290
Iteration: 2418/59290
Iteration: 2419/59290
Iteration: 2420/59290
Iteration: 2421/59290
Iteration: 2422/59290
Iteration: 2423/59290
Iteration: 2424/59290
Iteration: 2425/59290
Iteration: 2426/59290
Iteration: 2427/59290
Iteration: 2428/59290
Iteration: 2429/59290
Iteration: 2430/59290
Iteration: 2431/59290
Iteration: 2432/59290

  4%|▍         | 2433/59290 [02:17<17:45, 53.37it/s]

Iteration: 2433/59290
Iteration: 2434/59290
Iteration: 2435/59290
Iteration: 2436/59290
Iteration: 2437/59290
Iteration: 2438/59290
Iteration: 2439/59290
Iteration: 2440/59290
Iteration: 2441/59290
Iteration: 2442/59290
Iteration: 2443/59290
Iteration: 2444/59290
Iteration: 2445/59290
Iteration: 2446/59290
Iteration: 2447/59290
Iteration: 2448/59290
Iteration: 2449/59290
Iteration: 2450/59290
Iteration: 2451/59290
Iteration: 2452/59290
Iteration: 2453/59290
Iteration: 2454/59290
Iteration: 2455/59290
Iteration: 2456/59290

  4%|▍         | 2457/59290 [02:18<16:57, 55.87it/s]

Iteration: 2457/59290
Iteration: 2458/59290
Iteration: 2459/59290
Iteration: 2460/59290
Iteration: 2461/59290
Iteration: 2462/59290
Iteration: 2463/59290
Iteration: 2464/59290
Iteration: 2465/59290
Iteration: 2466/59290
Iteration: 2467/59290
Iteration: 2468/59290
Iteration: 2469/59290
Iteration: 2470/59290
Iteration: 2471/59290
Iteration: 2472/59290
Iteration: 2473/59290
Iteration: 2474/59290
Iteration: 2475/59290
Iteration: 2476/59290
Iteration: 2477/59290
Iteration: 2478/59290
Iteration: 2479/59290
Iteration: 2480/59290

  4%|▍         | 2481/59290 [02:18<16:40, 56.78it/s]

Iteration: 2481/59290
Iteration: 2482/59290
Iteration: 2483/59290
Iteration: 2484/59290
Iteration: 2485/59290
Iteration: 2486/59290
Iteration: 2487/59290
Iteration: 2488/59290
Iteration: 2489/59290
Iteration: 2490/59290
Iteration: 2491/59290
Iteration: 2492/59290
Iteration: 2493/59290
Iteration: 2494/59290
Iteration: 2495/59290
Iteration: 2496/59290
Iteration: 2497/59290
Iteration: 2498/59290
Iteration: 2499/59290
Iteration: 2500/59290
Iteration: 2501/59290
Iteration: 2502/59290
Iteration: 2503/59290
Iteration: 2504/59290

  4%|▍         | 2505/59290 [02:19<16:14, 58.28it/s]

Iteration: 2505/59290
Iteration: 2506/59290
Iteration: 2507/59290
Iteration: 2508/59290
Iteration: 2509/59290
Iteration: 2510/59290
Iteration: 2511/59290
Iteration: 2512/59290
Iteration: 2513/59290
Iteration: 2514/59290
Iteration: 2515/59290
Iteration: 2516/59290
Iteration: 2517/59290
Iteration: 2518/59290
Iteration: 2519/59290
Iteration: 2520/59290
Iteration: 2521/59290
Iteration: 2522/59290
Iteration: 2523/59290
Iteration: 2524/59290
Iteration: 2525/59290
Iteration: 2526/59290
Iteration: 2527/59290
Iteration: 2528/59290

  4%|▍         | 2529/59290 [02:19<15:46, 59.97it/s]

Iteration: 2529/59290
Iteration: 2530/59290
Iteration: 2531/59290
Iteration: 2532/59290
Iteration: 2533/59290
Iteration: 2534/59290
Iteration: 2535/59290
Iteration: 2536/59290
Iteration: 2537/59290
Iteration: 2538/59290
Iteration: 2539/59290
Iteration: 2540/59290
Iteration: 2541/59290
Iteration: 2542/59290
Iteration: 2543/59290
Iteration: 2544/59290
Iteration: 2545/59290
Iteration: 2546/59290
Iteration: 2547/59290
Iteration: 2548/59290
Iteration: 2549/59290
Iteration: 2550/59290
Iteration: 2551/59290
Iteration: 2552/59290

  4%|▍         | 2553/59290 [02:19<15:47, 59.88it/s]

Iteration: 2553/59290
Iteration: 2554/59290
Iteration: 2555/59290
Iteration: 2556/59290
Iteration: 2557/59290
Iteration: 2558/59290
Iteration: 2559/59290
Iteration: 2560/59290
Iteration: 2561/59290
Iteration: 2562/59290
Iteration: 2563/59290
Iteration: 2564/59290
Iteration: 2565/59290
Iteration: 2566/59290
Iteration: 2567/59290
Iteration: 2568/59290
Iteration: 2569/59290
Iteration: 2570/59290
Iteration: 2571/59290
Iteration: 2572/59290
Iteration: 2573/59290
Iteration: 2574/59290
Iteration: 2575/59290
Iteration: 2576/59290

  4%|▍         | 2577/59290 [02:20<15:42, 60.15it/s]

Iteration: 2577/59290
Iteration: 2578/59290
Iteration: 2579/59290
Iteration: 2580/59290
Iteration: 2581/59290
Iteration: 2582/59290
Iteration: 2583/59290
Iteration: 2584/59290
Iteration: 2585/59290
Iteration: 2586/59290
Iteration: 2587/59290
Iteration: 2588/59290
Iteration: 2589/59290
Iteration: 2590/59290
Iteration: 2591/59290
Iteration: 2592/59290
Iteration: 2593/59290
Iteration: 2594/59290
Iteration: 2595/59290
Iteration: 2596/59290
Iteration: 2597/59290
Iteration: 2598/59290
Iteration: 2599/59290
Iteration: 2600/59290

  4%|▍         | 2601/59290 [02:21<24:49, 38.06it/s]

Iteration: 2601/59290
Iteration: 2602/59290
Iteration: 2603/59290
Iteration: 2604/59290
Iteration: 2605/59290
Iteration: 2606/59290
Iteration: 2607/59290
Iteration: 2608/59290
Iteration: 2609/59290
Iteration: 2610/59290
Iteration: 2611/59290
Iteration: 2612/59290
Iteration: 2613/59290
Iteration: 2614/59290
Iteration: 2615/59290
Iteration: 2616/59290
Iteration: 2617/59290
Iteration: 2618/59290
Iteration: 2619/59290
Iteration: 2620/59290
Iteration: 2621/59290
Iteration: 2622/59290
Iteration: 2623/59290
Iteration: 2624/59290

  4%|▍         | 2625/59290 [02:23<40:22, 23.39it/s]

Iteration: 2625/59290
Iteration: 2626/59290
Iteration: 2627/59290
Iteration: 2628/59290
Iteration: 2629/59290
Iteration: 2630/59290
Iteration: 2631/59290
Iteration: 2632/59290
Iteration: 2633/59290
Iteration: 2634/59290
Iteration: 2635/59290
Iteration: 2636/59290
Iteration: 2637/59290
Iteration: 2638/59290
Iteration: 2639/59290
Iteration: 2640/59290
Iteration: 2641/59290
Iteration: 2642/59290
Iteration: 2643/59290
Iteration: 2644/59290
Iteration: 2645/59290
Iteration: 2646/59290
Iteration: 2647/59290
Iteration: 2648/59290

  4%|▍         | 2649/59290 [02:23<32:43, 28.85it/s]

Iteration: 2649/59290
Iteration: 2650/59290
Iteration: 2651/59290
Iteration: 2652/59290
Iteration: 2653/59290
Iteration: 2654/59290
Iteration: 2655/59290
Iteration: 2656/59290
Iteration: 2657/59290
Iteration: 2658/59290
Iteration: 2659/59290
Iteration: 2660/59290
Iteration: 2661/59290
Iteration: 2662/59290
Iteration: 2663/59290
Iteration: 2664/59290
Iteration: 2665/59290
Iteration: 2666/59290
Iteration: 2667/59290
Iteration: 2668/59290
Iteration: 2669/59290
Iteration: 2670/59290
Iteration: 2671/59290
Iteration: 2672/59290

  5%|▍         | 2673/59290 [02:24<29:58, 31.48it/s]

Iteration: 2673/59290
Iteration: 2674/59290
Iteration: 2675/59290
Iteration: 2676/59290
Iteration: 2677/59290
Iteration: 2678/59290
Iteration: 2679/59290
Iteration: 2680/59290
Iteration: 2681/59290
Iteration: 2682/59290
Iteration: 2683/59290
Iteration: 2684/59290
Iteration: 2685/59290
Iteration: 2686/59290
Iteration: 2687/59290
Iteration: 2688/59290
Iteration: 2689/59290
Iteration: 2690/59290
Iteration: 2691/59290
Iteration: 2692/59290
Iteration: 2693/59290
Iteration: 2694/59290
Iteration: 2696/59290

  5%|▍         | 2696/59290 [02:24<26:18, 35.84it/s]

Iteration: 2697/59290
Iteration: 2698/59290
Iteration: 2699/59290
Iteration: 2700/59290
Iteration: 2701/59290
Iteration: 2702/59290
Iteration: 2703/59290
Iteration: 2704/59290

  5%|▍         | 2704/59290 [02:25<28:40, 32.89it/s]

Iteration: 2705/59290
Iteration: 2706/59290
Iteration: 2707/59290
Iteration: 2708/59290
Iteration: 2709/59290
Iteration: 2710/59290
Iteration: 2711/59290
Iteration: 2712/59290
Iteration: 2713/59290
Iteration: 2714/59290
Iteration: 2715/59290
Iteration: 2716/59290
Iteration: 2717/59290
Iteration: 2718/59290
Iteration: 2719/59290
Iteration: 2720/59290
Iteration: 2721/59290
Iteration: 2722/59290
Iteration: 2723/59290
Iteration: 2724/59290
Iteration: 2725/59290
Iteration: 2726/59290
Iteration: 2727/59290
Iteration: 2728/59290

  5%|▍         | 2728/59290 [02:25<23:51, 39.51it/s]

Iteration: 2729/59290
Iteration: 2730/59290
Iteration: 2731/59290
Iteration: 2732/59290
Iteration: 2733/59290
Iteration: 2734/59290
Iteration: 2735/59290
Iteration: 2736/59290
Iteration: 2737/59290
Iteration: 2738/59290
Iteration: 2739/59290
Iteration: 2740/59290
Iteration: 2741/59290
Iteration: 2742/59290
Iteration: 2743/59290
Iteration: 2744/59290
Iteration: 2745/59290
Iteration: 2746/59290
Iteration: 2747/59290
Iteration: 2748/59290
Iteration: 2749/59290
Iteration: 2750/59290
Iteration: 2751/59290
Iteration: 2752/59290

  5%|▍         | 2752/59290 [02:26<34:23, 27.40it/s]

Iteration: 2753/59290
Iteration: 2754/59290
Iteration: 2755/59290
Iteration: 2756/59290
Iteration: 2757/59290
Iteration: 2758/59290
Iteration: 2759/59290
Iteration: 2760/59290
Iteration: 2761/59290
Iteration: 2762/59290
Iteration: 2763/59290
Iteration: 2764/59290
Iteration: 2765/59290
Iteration: 2766/59290
Iteration: 2767/59290
Iteration: 2768/59290
Iteration: 2769/59290
Iteration: 2770/59290
Iteration: 2771/59290
Iteration: 2772/59290
Iteration: 2773/59290
Iteration: 2774/59290
Iteration: 2775/59290
Iteration: 2776/59290

  5%|▍         | 2776/59290 [02:28<47:29, 19.83it/s]

Iteration: 2777/59290
Iteration: 2778/59290
Iteration: 2779/59290
Iteration: 2780/59290
Iteration: 2781/59290
Iteration: 2782/59290
Iteration: 2783/59290
Iteration: 2784/59290
Iteration: 2785/59290
Iteration: 2786/59290
Iteration: 2787/59290
Iteration: 2788/59290
Iteration: 2789/59290
Iteration: 2790/59290
Iteration: 2791/59290
Iteration: 2792/59290
Iteration: 2793/59290
Iteration: 2794/59290
Iteration: 2795/59290
Iteration: 2796/59290
Iteration: 2797/59290
Iteration: 2798/59290
Iteration: 2799/59290
Iteration: 2800/59290

  5%|▍         | 2800/59290 [03:01<7:15:30,  2.16it/s]

Iteration: 2801/59290
Iteration: 2802/59290
Iteration: 2803/59290
Iteration: 2804/59290
Iteration: 2805/59290
Iteration: 2806/59290
Iteration: 2807/59290
Iteration: 2808/59290
Iteration: 2809/59290
Iteration: 2810/59290
Iteration: 2811/59290
Iteration: 2812/59290
Iteration: 2813/59290
Iteration: 2814/59290
Iteration: 2815/59290
Iteration: 2816/59290
Iteration: 2817/59290
Iteration: 2818/59290
Iteration: 2819/59290
Iteration: 2820/59290
Iteration: 2821/59290
Iteration: 2822/59290
Iteration: 2823/59290
Iteration: 2824/59290

  5%|▍         | 2824/59290 [03:01<5:04:35,  3.09it/s]

Iteration: 2825/59290
Iteration: 2826/59290
Iteration: 2827/59290
Iteration: 2828/59290
Iteration: 2829/59290
Iteration: 2830/59290
Iteration: 2831/59290
Iteration: 2832/59290
Iteration: 2833/59290
Iteration: 2834/59290
Iteration: 2835/59290
Iteration: 2836/59290
Iteration: 2837/59290
Iteration: 2838/59290
Iteration: 2839/59290
Iteration: 2840/59290
Iteration: 2841/59290
Iteration: 2842/59290
Iteration: 2843/59290
Iteration: 2844/59290
Iteration: 2845/59290
Iteration: 2846/59290
Iteration: 2847/59290
Iteration: 2848/59290

  5%|▍         | 2848/59290 [03:02<3:35:18,  4.37it/s]

Iteration: 2849/59290
Iteration: 2850/59290
Iteration: 2851/59290
Iteration: 2852/59290
Iteration: 2853/59290
Iteration: 2854/59290
Iteration: 2855/59290
Iteration: 2856/59290
Iteration: 2857/59290
Iteration: 2858/59290
Iteration: 2859/59290
Iteration: 2860/59290
Iteration: 2861/59290
Iteration: 2862/59290
Iteration: 2863/59290
Iteration: 2864/59290
Iteration: 2865/59290
Iteration: 2866/59290
Iteration: 2867/59290
Iteration: 2868/59290
Iteration: 2869/59290
Iteration: 2870/59290
Iteration: 2871/59290
Iteration: 2872/59290

  5%|▍         | 2872/59290 [03:03<2:48:20,  5.59it/s]

Iteration: 2873/59290
Iteration: 2874/59290
Iteration: 2875/59290
Iteration: 2876/59290
Iteration: 2877/59290
Iteration: 2878/59290
Iteration: 2879/59290
Iteration: 2880/59290
Iteration: 2881/59290
Iteration: 2882/59290
Iteration: 2883/59290
Iteration: 2884/59290
Iteration: 2885/59290
Iteration: 2886/59290
Iteration: 2887/59290
Iteration: 2888/59290
Iteration: 2889/59290
Iteration: 2890/59290
Iteration: 2891/59290
Iteration: 2892/59290
Iteration: 2893/59290
Iteration: 2894/59290
Iteration: 2895/59290
Iteration: 2896/59290

  5%|▍         | 2896/59290 [03:05<2:20:01,  6.71it/s]

Iteration: 2897/59290
Iteration: 2898/59290
Iteration: 2899/59290
Iteration: 2900/59290
Iteration: 2901/59290
Iteration: 2902/59290
Iteration: 2903/59290
Iteration: 2904/59290
Iteration: 2905/59290
Iteration: 2906/59290
Iteration: 2907/59290
Iteration: 2908/59290
Iteration: 2909/59290
Iteration: 2910/59290
Iteration: 2911/59290
Iteration: 2912/59290
Iteration: 2913/59290
Iteration: 2914/59290
Iteration: 2915/59290
Iteration: 2916/59290
Iteration: 2917/59290
Iteration: 2918/59290
Iteration: 2919/59290
Iteration: 2920/59290

  5%|▍         | 2920/59290 [03:06<1:42:58,  9.12it/s]

Iteration: 2921/59290
Iteration: 2922/59290
Iteration: 2923/59290
Iteration: 2924/59290
Iteration: 2925/59290
Iteration: 2926/59290
Iteration: 2927/59290
Iteration: 2928/59290
Iteration: 2929/59290
Iteration: 2930/59290
Iteration: 2931/59290
Iteration: 2932/59290
Iteration: 2933/59290
Iteration: 2934/59290
Iteration: 2935/59290
Iteration: 2936/59290
Iteration: 2937/59290
Iteration: 2938/59290
Iteration: 2939/59290
Iteration: 2940/59290
Iteration: 2941/59290
Iteration: 2942/59290
Iteration: 2943/59290
Iteration: 2944/59290

  5%|▍         | 2944/59290 [03:06<1:16:27, 12.28it/s]

Iteration: 2945/59290
Iteration: 2946/59290
Iteration: 2947/59290
Iteration: 2948/59290
Iteration: 2949/59290
Iteration: 2950/59290
Iteration: 2951/59290
Iteration: 2952/59290
Iteration: 2953/59290
Iteration: 2954/59290
Iteration: 2955/59290
Iteration: 2956/59290
Iteration: 2957/59290
Iteration: 2958/59290
Iteration: 2959/59290
Iteration: 2960/59290
Iteration: 2961/59290
Iteration: 2962/59290
Iteration: 2963/59290
Iteration: 2964/59290
Iteration: 2965/59290
Iteration: 2966/59290
Iteration: 2967/59290
Iteration: 2968/59290

  5%|▌         | 2968/59290 [03:06<57:48, 16.24it/s]

Iteration: 2969/59290
Iteration: 2970/59290
Iteration: 2971/59290
Iteration: 2972/59290
Iteration: 2973/59290
Iteration: 2974/59290
Iteration: 2975/59290
Iteration: 2976/59290
Iteration: 2977/59290
Iteration: 2978/59290
Iteration: 2979/59290
Iteration: 2980/59290
Iteration: 2981/59290
Iteration: 2982/59290
Iteration: 2983/59290
Iteration: 2984/59290
Iteration: 2985/59290
Iteration: 2986/59290
Iteration: 2987/59290
Iteration: 2988/59290
Iteration: 2989/59290
Iteration: 2990/59290
Iteration: 2991/59290
Iteration: 2992/59290

  5%|▌         | 2992/59290 [03:08<59:38, 15.73it/s]

Iteration: 2993/59290
Iteration: 2994/59290
Iteration: 2995/59290
Iteration: 2996/59290
Iteration: 2997/59290
Iteration: 2998/59290
Iteration: 2999/59290
Iteration: 3000/59290
Iteration: 3001/59290
Iteration: 3002/59290
Iteration: 3003/59290
Iteration: 3004/59290
Iteration: 3005/59290
Iteration: 3006/59290
Iteration: 3007/59290
Iteration: 3008/59290
Iteration: 3009/59290
Iteration: 3010/59290
Iteration: 3011/59290
Iteration: 3012/59290
Iteration: 3013/59290
Iteration: 3014/59290
Iteration: 3015/59290
Iteration: 3016/59290

  5%|▌         | 3016/59290 [03:10<1:03:32, 14.76it/s]

Iteration: 3017/59290
Iteration: 3018/59290
Iteration: 3019/59290
Iteration: 3020/59290
Iteration: 3021/59290
Iteration: 3022/59290
Iteration: 3023/59290
Iteration: 3024/59290
Iteration: 3025/59290
Iteration: 3026/59290
Iteration: 3027/59290
Iteration: 3028/59290
Iteration: 3029/59290
Iteration: 3030/59290
Iteration: 3031/59290
Iteration: 3032/59290
Iteration: 3033/59290
Iteration: 3034/59290
Iteration: 3035/59290
Iteration: 3036/59290
Iteration: 3037/59290
Iteration: 3038/59290
Iteration: 3039/59290
Iteration: 3040/59290

  5%|▌         | 3040/59290 [03:10<50:33, 18.54it/s]

Iteration: 3041/59290
Iteration: 3042/59290
Iteration: 3043/59290
Iteration: 3044/59290
Iteration: 3045/59290
Iteration: 3046/59290
Iteration: 3047/59290
Iteration: 3048/59290
Iteration: 3049/59290
Iteration: 3050/59290
Iteration: 3051/59290
Iteration: 3052/59290
Iteration: 3053/59290
Iteration: 3054/59290
Iteration: 3055/59290
Iteration: 3056/59290
Iteration: 3057/59290
Iteration: 3058/59290
Iteration: 3059/59290
Iteration: 3060/59290
Iteration: 3061/59290
Iteration: 3062/59290
Iteration: 3063/59290
Iteration: 3064/59290

  5%|▌         | 3064/59290 [03:11<39:50, 23.52it/s]

Iteration: 3065/59290
Iteration: 3066/59290
Iteration: 3067/59290
Iteration: 3068/59290
Iteration: 3069/59290
Iteration: 3070/59290
Iteration: 3071/59290
Iteration: 3072/59290
Iteration: 3073/59290
Iteration: 3074/59290
Iteration: 3075/59290
Iteration: 3076/59290
Iteration: 3077/59290
Iteration: 3078/59290
Iteration: 3079/59290
Iteration: 3080/59290
Iteration: 3081/59290
Iteration: 3082/59290
Iteration: 3083/59290
Iteration: 3084/59290
Iteration: 3085/59290
Iteration: 3086/59290
Iteration: 3087/59290
Iteration: 3088/59290

  5%|▌         | 3088/59290 [03:11<32:16, 29.03it/s]

Iteration: 3089/59290
Iteration: 3090/59290
Iteration: 3091/59290
Iteration: 3092/59290
Iteration: 3093/59290
Iteration: 3094/59290
Iteration: 3095/59290
Iteration: 3096/59290
Iteration: 3097/59290
Iteration: 3098/59290
Iteration: 3099/59290
Iteration: 3100/59290
Iteration: 3101/59290
Iteration: 3102/59290
Iteration: 3103/59290
Iteration: 3104/59290
Iteration: 3105/59290
Iteration: 3106/59290
Iteration: 3107/59290
Iteration: 3108/59290
Iteration: 3109/59290
Iteration: 3110/59290
Iteration: 3111/59290
Iteration: 3112/59290

  5%|▌         | 3112/59290 [03:12<27:06, 34.53it/s]

Iteration: 3113/59290
Iteration: 3114/59290
Iteration: 3115/59290
Iteration: 3116/59290
Iteration: 3117/59290
Iteration: 3118/59290
Iteration: 3119/59290
Iteration: 3120/59290
Iteration: 3121/59290
Iteration: 3122/59290
Iteration: 3123/59290
Iteration: 3124/59290
Iteration: 3125/59290
Iteration: 3126/59290
Iteration: 3127/59290
Iteration: 3128/59290
Iteration: 3129/59290
Iteration: 3130/59290
Iteration: 3131/59290
Iteration: 3132/59290
Iteration: 3133/59290
Iteration: 3134/59290
Iteration: 3135/59290
Iteration: 3136/59290

  5%|▌         | 3136/59290 [03:12<23:20, 40.11it/s]

Iteration: 3137/59290
Iteration: 3138/59290
Iteration: 3139/59290
Iteration: 3140/59290
Iteration: 3141/59290
Iteration: 3142/59290
Iteration: 3143/59290
Iteration: 3144/59290
Iteration: 3145/59290
Iteration: 3146/59290
Iteration: 3147/59290
Iteration: 3148/59290
Iteration: 3149/59290
Iteration: 3150/59290
Iteration: 3151/59290
Iteration: 3152/59290
Iteration: 3153/59290
Iteration: 3154/59290
Iteration: 3155/59290
Iteration: 3156/59290
Iteration: 3157/59290
Iteration: 3158/59290
Iteration: 3159/59290
Iteration: 3160/59290

  5%|▌         | 3160/59290 [03:12<20:50, 44.89it/s]

Iteration: 3161/59290
Iteration: 3162/59290
Iteration: 3163/59290
Iteration: 3164/59290
Iteration: 3165/59290
Iteration: 3166/59290
Iteration: 3167/59290
Iteration: 3168/59290
Iteration: 3169/59290
Iteration: 3170/59290
Iteration: 3171/59290
Iteration: 3172/59290
Iteration: 3173/59290
Iteration: 3174/59290
Iteration: 3175/59290
Iteration: 3176/59290
Iteration: 3177/59290
Iteration: 3178/59290
Iteration: 3179/59290
Iteration: 3180/59290
Iteration: 3181/59290
Iteration: 3182/59290
Iteration: 3183/59290
Iteration: 3184/59290

  5%|▌         | 3184/59290 [03:14<29:40, 31.51it/s]

Iteration: 3185/59290
Iteration: 3186/59290
Iteration: 3187/59290
Iteration: 3188/59290
Iteration: 3189/59290
Iteration: 3190/59290
Iteration: 3191/59290
Iteration: 3192/59290
Iteration: 3193/59290
Iteration: 3194/59290
Iteration: 3195/59290
Iteration: 3196/59290
Iteration: 3197/59290
Iteration: 3198/59290
Iteration: 3199/59290
Iteration: 3200/59290
Iteration: 3201/59290
Iteration: 3202/59290
Iteration: 3203/59290
Iteration: 3204/59290
Iteration: 3205/59290
Iteration: 3206/59290
Iteration: 3207/59290
Iteration: 3208/59290

  5%|▌         | 3208/59290 [03:16<43:23, 21.54it/s]

Iteration: 3209/59290
Iteration: 3210/59290
Iteration: 3211/59290
Iteration: 3212/59290
Iteration: 3213/59290
Iteration: 3214/59290
Iteration: 3215/59290
Iteration: 3216/59290
Iteration: 3217/59290
Iteration: 3218/59290
Iteration: 3219/59290
Iteration: 3220/59290
Iteration: 3221/59290
Iteration: 3222/59290
Iteration: 3223/59290
Iteration: 3224/59290
Iteration: 3225/59290
Iteration: 3226/59290
Iteration: 3227/59290
Iteration: 3228/59290
Iteration: 3229/59290
Iteration: 3230/59290
Iteration: 3231/59290
Iteration: 3232/59290

  5%|▌         | 3232/59290 [03:16<34:45, 26.88it/s]

Iteration: 3233/59290
Iteration: 3234/59290
Iteration: 3235/59290
Iteration: 3236/59290
Iteration: 3237/59290
Iteration: 3238/59290
Iteration: 3239/59290
Iteration: 3240/59290
Iteration: 3241/59290
Iteration: 3242/59290
Iteration: 3243/59290
Iteration: 3244/59290
Iteration: 3245/59290
Iteration: 3246/59290
Iteration: 3247/59290
Iteration: 3248/59290
Iteration: 3249/59290
Iteration: 3250/59290
Iteration: 3251/59290
Iteration: 3252/59290
Iteration: 3253/59290
Iteration: 3254/59290
Iteration: 3255/59290
Iteration: 3256/59290

  5%|▌         | 3256/59290 [03:16<30:14, 30.89it/s]

Iteration: 3257/59290
Iteration: 3258/59290
Iteration: 3259/59290
Iteration: 3260/59290
Iteration: 3261/59290
Iteration: 3262/59290
Iteration: 3263/59290
Iteration: 3264/59290
Iteration: 3265/59290
Iteration: 3266/59290
Iteration: 3267/59290
Iteration: 3268/59290
Iteration: 3269/59290
Iteration: 3270/59290
Iteration: 3271/59290
Iteration: 3272/59290
Iteration: 3273/59290
Iteration: 3274/59290
Iteration: 3275/59290
Iteration: 3276/59290
Iteration: 3277/59290
Iteration: 3278/59290
Iteration: 3279/59290
Iteration: 3280/59290

  6%|▌         | 3280/59290 [03:17<25:31, 36.57it/s]

Iteration: 3281/59290
Iteration: 3282/59290
Iteration: 3283/59290
Iteration: 3284/59290
Iteration: 3285/59290
Iteration: 3286/59290
Iteration: 3287/59290
Iteration: 3288/59290
Iteration: 3289/59290
Iteration: 3290/59290
Iteration: 3291/59290
Iteration: 3292/59290
Iteration: 3293/59290
Iteration: 3294/59290
Iteration: 3295/59290
Iteration: 3296/59290
Iteration: 3297/59290
Iteration: 3298/59290
Iteration: 3299/59290
Iteration: 3300/59290
Iteration: 3301/59290
Iteration: 3302/59290
Iteration: 3303/59290
Iteration: 3304/59290

  6%|▌         | 3304/59290 [03:17<22:15, 41.91it/s]

Iteration: 3305/59290
Iteration: 3306/59290
Iteration: 3307/59290
Iteration: 3308/59290
Iteration: 3309/59290
Iteration: 3310/59290
Iteration: 3311/59290
Iteration: 3312/59290
Iteration: 3313/59290
Iteration: 3314/59290
Iteration: 3315/59290
Iteration: 3316/59290
Iteration: 3317/59290
Iteration: 3318/59290
Iteration: 3319/59290
Iteration: 3320/59290
Iteration: 3321/59290
Iteration: 3322/59290
Iteration: 3323/59290
Iteration: 3324/59290
Iteration: 3325/59290
Iteration: 3326/59290
Iteration: 3327/59290
Iteration: 3328/59290

  6%|▌         | 3328/59290 [03:18<19:56, 46.79it/s]

Iteration: 3329/59290
Iteration: 3330/59290
Iteration: 3331/59290
Iteration: 3332/59290
Iteration: 3333/59290
Iteration: 3334/59290
Iteration: 3335/59290
Iteration: 3336/59290
Iteration: 3337/59290
Iteration: 3338/59290
Iteration: 3339/59290
Iteration: 3340/59290
Iteration: 3341/59290
Iteration: 3342/59290
Iteration: 3343/59290
Iteration: 3344/59290
Iteration: 3345/59290
Iteration: 3346/59290
Iteration: 3347/59290
Iteration: 3348/59290
Iteration: 3349/59290
Iteration: 3350/59290
Iteration: 3351/59290
Iteration: 3352/59290

  6%|▌         | 3352/59290 [03:18<18:21, 50.78it/s]

Iteration: 3353/59290
Iteration: 3354/59290
Iteration: 3355/59290
Iteration: 3356/59290
Iteration: 3357/59290
Iteration: 3358/59290
Iteration: 3359/59290
Iteration: 3360/59290
Iteration: 3361/59290
Iteration: 3362/59290
Iteration: 3363/59290
Iteration: 3364/59290
Iteration: 3365/59290
Iteration: 3366/59290
Iteration: 3367/59290
Iteration: 3368/59290
Iteration: 3369/59290
Iteration: 3370/59290
Iteration: 3371/59290
Iteration: 3372/59290
Iteration: 3373/59290
Iteration: 3374/59290
Iteration: 3375/59290
Iteration: 3376/59290

  6%|▌         | 3376/59290 [03:18<17:13, 54.12it/s]

Iteration: 3377/59290
Iteration: 3378/59290
Iteration: 3379/59290
Iteration: 3380/59290
Iteration: 3381/59290
Iteration: 3382/59290
Iteration: 3383/59290
Iteration: 3384/59290
Iteration: 3385/59290
Iteration: 3386/59290
Iteration: 3387/59290
Iteration: 3388/59290
Iteration: 3389/59290
Iteration: 3390/59290
Iteration: 3391/59290
Iteration: 3392/59290
Iteration: 3393/59290
Iteration: 3394/59290
Iteration: 3395/59290
Iteration: 3396/59290
Iteration: 3397/59290
Iteration: 3398/59290
Iteration: 3399/59290
Iteration: 3400/59290

  6%|▌         | 3400/59290 [03:19<16:22, 56.88it/s]

Iteration: 3401/59290
Iteration: 3402/59290
Iteration: 3403/59290
Iteration: 3404/59290
Iteration: 3405/59290
Iteration: 3406/59290
Iteration: 3407/59290
Iteration: 3408/59290
Iteration: 3409/59290
Iteration: 3410/59290
Iteration: 3411/59290
Iteration: 3412/59290
Iteration: 3413/59290
Iteration: 3414/59290
Iteration: 3415/59290
Iteration: 3416/59290
Iteration: 3417/59290
Iteration: 3418/59290
Iteration: 3419/59290
Iteration: 3420/59290
Iteration: 3421/59290
Iteration: 3422/59290
Iteration: 3423/59290
Iteration: 3424/59290

  6%|▌         | 3424/59290 [03:19<15:52, 58.65it/s]

Iteration: 3425/59290
Iteration: 3426/59290
Iteration: 3427/59290
Iteration: 3428/59290
Iteration: 3429/59290
Iteration: 3430/59290
Iteration: 3431/59290
Iteration: 3432/59290
Iteration: 3433/59290
Iteration: 3434/59290
Iteration: 3435/59290
Iteration: 3436/59290
Iteration: 3437/59290
Iteration: 3438/59290
Iteration: 3439/59290
Iteration: 3440/59290
Iteration: 3441/59290
Iteration: 3442/59290
Iteration: 3443/59290
Iteration: 3444/59290
Iteration: 3445/59290
Iteration: 3446/59290
Iteration: 3447/59290
Iteration: 3448/59290

  6%|▌         | 3448/59290 [03:19<15:38, 59.53it/s]

Iteration: 3449/59290
Iteration: 3450/59290
Iteration: 3451/59290
Iteration: 3452/59290
Iteration: 3453/59290
Iteration: 3454/59290
Iteration: 3455/59290
Iteration: 3456/59290
Iteration: 3457/59290
Iteration: 3458/59290
Iteration: 3459/59290
Iteration: 3460/59290
Iteration: 3461/59290
Iteration: 3462/59290
Iteration: 3463/59290
Iteration: 3464/59290
Iteration: 3465/59290
Iteration: 3466/59290
Iteration: 3467/59290
Iteration: 3468/59290
Iteration: 3469/59290
Iteration: 3470/59290
Iteration: 3471/59290
Iteration: 3472/59290

  6%|▌         | 3472/59290 [03:21<27:12, 34.19it/s]

Iteration: 3473/59290
Iteration: 3474/59290
Iteration: 3475/59290
Iteration: 3476/59290
Iteration: 3477/59290
Iteration: 3478/59290
Iteration: 3479/59290
Iteration: 3480/59290
Iteration: 3481/59290
Iteration: 3482/59290
Iteration: 3483/59290
Iteration: 3484/59290
Iteration: 3485/59290
Iteration: 3486/59290
Iteration: 3487/59290
Iteration: 3488/59290
Iteration: 3489/59290
Iteration: 3490/59290
Iteration: 3491/59290
Iteration: 3492/59290
Iteration: 3493/59290
Iteration: 3494/59290
Iteration: 3495/59290
Iteration: 3496/59290

  6%|▌         | 3496/59290 [03:23<40:23, 23.02it/s]

Iteration: 3497/59290
Iteration: 3498/59290
Iteration: 3499/59290
Iteration: 3500/59290
Iteration: 3501/59290
Iteration: 3502/59290
Iteration: 3503/59290
Iteration: 3504/59290
Iteration: 3505/59290
Iteration: 3506/59290
Iteration: 3507/59290
Iteration: 3508/59290
Iteration: 3509/59290
Iteration: 3510/59290
Iteration: 3511/59290
Iteration: 3512/59290
Iteration: 3513/59290
Iteration: 3514/59290
Iteration: 3515/59290
Iteration: 3516/59290
Iteration: 3517/59290
Iteration: 3518/59290
Iteration: 3519/59290
Iteration: 3520/59290

  6%|▌         | 3520/59290 [03:23<33:51, 27.45it/s]

Iteration: 3521/59290
Iteration: 3522/59290
Iteration: 3523/59290
Iteration: 3524/59290
Iteration: 3525/59290
Iteration: 3526/59290
Iteration: 3527/59290
Iteration: 3528/59290
Iteration: 3529/59290
Iteration: 3530/59290
Iteration: 3531/59290
Iteration: 3532/59290
Iteration: 3533/59290
Iteration: 3534/59290
Iteration: 3535/59290
Iteration: 3536/59290
Iteration: 3537/59290
Iteration: 3538/59290
Iteration: 3539/59290
Iteration: 3540/59290
Iteration: 3541/59290
Iteration: 3542/59290
Iteration: 3543/59290
Iteration: 3544/59290

  6%|▌         | 3544/59290 [03:24<28:06, 33.05it/s]

Iteration: 3545/59290
Iteration: 3546/59290
Iteration: 3547/59290
Iteration: 3548/59290
Iteration: 3549/59290
Iteration: 3550/59290
Iteration: 3551/59290
Iteration: 3552/59290
Iteration: 3553/59290
Iteration: 3554/59290
Iteration: 3555/59290
Iteration: 3556/59290
Iteration: 3557/59290
Iteration: 3558/59290
Iteration: 3559/59290
Iteration: 3560/59290
Iteration: 3561/59290
Iteration: 3562/59290
Iteration: 3563/59290
Iteration: 3564/59290
Iteration: 3565/59290
Iteration: 3566/59290
Iteration: 3567/59290
Iteration: 3568/59290

  6%|▌         | 3568/59290 [03:24<24:01, 38.66it/s]

Iteration: 3569/59290
Iteration: 3570/59290
Iteration: 3571/59290
Iteration: 3572/59290
Iteration: 3573/59290
Iteration: 3574/59290
Iteration: 3575/59290
Iteration: 3576/59290
Iteration: 3577/59290
Iteration: 3578/59290
Iteration: 3579/59290
Iteration: 3580/59290
Iteration: 3581/59290
Iteration: 3582/59290
Iteration: 3583/59290
Iteration: 3584/59290
Iteration: 3585/59290
Iteration: 3586/59290
Iteration: 3587/59290
Iteration: 3588/59290
Iteration: 3589/59290
Iteration: 3590/59290
Iteration: 3591/59290
Iteration: 3592/59290

  6%|▌         | 3592/59290 [03:24<21:20, 43.50it/s]

Iteration: 3593/59290
Iteration: 3594/59290
Iteration: 3595/59290
Iteration: 3596/59290
Iteration: 3597/59290
Iteration: 3598/59290
Iteration: 3599/59290
Iteration: 3600/59290
Iteration: 3601/59290
Iteration: 3602/59290
Iteration: 3603/59290
Iteration: 3604/59290
Iteration: 3605/59290
Iteration: 3606/59290
Iteration: 3607/59290
Iteration: 3608/59290
Iteration: 3609/59290
Iteration: 3610/59290
Iteration: 3611/59290
Iteration: 3612/59290
Iteration: 3613/59290
Iteration: 3614/59290
Iteration: 3615/59290
Iteration: 3616/59290

  6%|▌         | 3616/59290 [03:26<31:18, 29.64it/s]

Iteration: 3617/59290
Iteration: 3618/59290
Iteration: 3619/59290
Iteration: 3620/59290
Iteration: 3621/59290
Iteration: 3622/59290
Iteration: 3623/59290
Iteration: 3624/59290
Iteration: 3625/59290
Iteration: 3626/59290
Iteration: 3627/59290
Iteration: 3628/59290
Iteration: 3629/59290
Iteration: 3630/59290
Iteration: 3631/59290
Iteration: 3632/59290
Iteration: 3633/59290
Iteration: 3634/59290
Iteration: 3635/59290
Iteration: 3636/59290
Iteration: 3637/59290
Iteration: 3638/59290
Iteration: 3639/59290
Iteration: 3640/59290

  6%|▌         | 3640/59290 [03:28<44:45, 20.72it/s]

Iteration: 3641/59290
Iteration: 3642/59290
Iteration: 3643/59290
Iteration: 3644/59290
Iteration: 3645/59290
Iteration: 3646/59290
Iteration: 3647/59290
Iteration: 3648/59290
Iteration: 3649/59290
Iteration: 3650/59290
Iteration: 3651/59290
Iteration: 3652/59290
Iteration: 3653/59290
Iteration: 3654/59290
Iteration: 3655/59290
Iteration: 3656/59290
Iteration: 3657/59290
Iteration: 3658/59290
Iteration: 3659/59290
Iteration: 3660/59290
Iteration: 3661/59290
Iteration: 3662/59290
Iteration: 3663/59290
Iteration: 3664/59290

  6%|▌         | 3664/59290 [03:28<35:46, 25.92it/s]

Iteration: 3665/59290
Iteration: 3666/59290
Iteration: 3667/59290
Iteration: 3668/59290
Iteration: 3669/59290
Iteration: 3670/59290
Iteration: 3671/59290
Iteration: 3672/59290
Iteration: 3673/59290
Iteration: 3674/59290
Iteration: 3675/59290
Iteration: 3676/59290
Iteration: 3677/59290
Iteration: 3678/59290
Iteration: 3679/59290
Iteration: 3680/59290
Iteration: 3681/59290
Iteration: 3682/59290
Iteration: 3683/59290
Iteration: 3684/59290
Iteration: 3685/59290
Iteration: 3686/59290
Iteration: 3687/59290
Iteration: 3688/59290

  6%|▌         | 3688/59290 [03:28<30:21, 30.52it/s]

Iteration: 3689/59290
Iteration: 3690/59290
Iteration: 3691/59290
Iteration: 3692/59290
Iteration: 3693/59290
Iteration: 3694/59290
Iteration: 3695/59290
Iteration: 3696/59290
Iteration: 3697/59290
Iteration: 3698/59290
Iteration: 3699/59290
Iteration: 3700/59290
Iteration: 3701/59290
Iteration: 3702/59290
Iteration: 3703/59290
Iteration: 3704/59290
Iteration: 3705/59290
Iteration: 3706/59290
Iteration: 3707/59290
Iteration: 3708/59290
Iteration: 3709/59290
Iteration: 3710/59290
Iteration: 3711/59290
Iteration: 3712/59290

  6%|▋         | 3712/59290 [03:29<25:43, 36.01it/s]

Iteration: 3713/59290
Iteration: 3714/59290
Iteration: 3715/59290
Iteration: 3716/59290
Iteration: 3717/59290
Iteration: 3718/59290
Iteration: 3719/59290
Iteration: 3720/59290
Iteration: 3721/59290
Iteration: 3722/59290
Iteration: 3723/59290
Iteration: 3724/59290
Iteration: 3725/59290
Iteration: 3726/59290
Iteration: 3727/59290
Iteration: 3728/59290
Iteration: 3729/59290
Iteration: 3730/59290
Iteration: 3731/59290
Iteration: 3732/59290
Iteration: 3733/59290
Iteration: 3734/59290
Iteration: 3735/59290
Iteration: 3736/59290

  6%|▋         | 3736/59290 [03:29<22:21, 41.41it/s]

Iteration: 3737/59290
Iteration: 3738/59290
Iteration: 3739/59290
Iteration: 3740/59290
Iteration: 3741/59290
Iteration: 3742/59290
Iteration: 3743/59290
Iteration: 3744/59290
Iteration: 3745/59290
Iteration: 3746/59290
Iteration: 3747/59290
Iteration: 3748/59290
Iteration: 3749/59290
Iteration: 3750/59290
Iteration: 3751/59290
Iteration: 3752/59290
Iteration: 3753/59290
Iteration: 3754/59290
Iteration: 3755/59290
Iteration: 3756/59290
Iteration: 3757/59290
Iteration: 3758/59290
Iteration: 3759/59290
Iteration: 3760/59290

  6%|▋         | 3760/59290 [03:30<20:04, 46.10it/s]

Iteration: 3761/59290
Iteration: 3762/59290
Iteration: 3763/59290
Iteration: 3764/59290
Iteration: 3765/59290
Iteration: 3766/59290
Iteration: 3767/59290
Iteration: 3768/59290
Iteration: 3769/59290
Iteration: 3770/59290
Iteration: 3771/59290
Iteration: 3772/59290
Iteration: 3773/59290
Iteration: 3774/59290
Iteration: 3775/59290
Iteration: 3776/59290
Iteration: 3777/59290
Iteration: 3778/59290
Iteration: 3779/59290
Iteration: 3780/59290
Iteration: 3781/59290
Iteration: 3782/59290
Iteration: 3783/59290
Iteration: 3784/59290

  6%|▋         | 3784/59290 [03:30<18:25, 50.23it/s]

Iteration: 3785/59290
Iteration: 3786/59290
Iteration: 3787/59290
Iteration: 3788/59290
Iteration: 3789/59290
Iteration: 3790/59290
Iteration: 3791/59290
Iteration: 3792/59290
Iteration: 3793/59290
Iteration: 3794/59290
Iteration: 3795/59290
Iteration: 3796/59290
Iteration: 3797/59290
Iteration: 3798/59290
Iteration: 3799/59290
Iteration: 3800/59290
Iteration: 3801/59290
Iteration: 3802/59290
Iteration: 3803/59290
Iteration: 3804/59290
Iteration: 3805/59290
Iteration: 3806/59290
Iteration: 3807/59290
Iteration: 3808/59290

  6%|▋         | 3808/59290 [03:30<17:12, 53.71it/s]

Iteration: 3809/59290
Iteration: 3810/59290
Iteration: 3811/59290
Iteration: 3812/59290
Iteration: 3813/59290
Iteration: 3814/59290
Iteration: 3815/59290
Iteration: 3816/59290
Iteration: 3817/59290
Iteration: 3818/59290
Iteration: 3819/59290
Iteration: 3820/59290
Iteration: 3821/59290
Iteration: 3822/59290
Iteration: 3823/59290
Iteration: 3824/59290
Iteration: 3825/59290
Iteration: 3826/59290
Iteration: 3827/59290
Iteration: 3828/59290
Iteration: 3829/59290
Iteration: 3830/59290
Iteration: 3831/59290
Iteration: 3832/59290

  6%|▋         | 3832/59290 [03:34<48:05, 19.22it/s]

Iteration: 3833/59290
Iteration: 3834/59290
Iteration: 3835/59290
Iteration: 3836/59290
Iteration: 3837/59290
Iteration: 3838/59290
Iteration: 3839/59290
Iteration: 3840/59290
Iteration: 3841/59290
Iteration: 3842/59290
Iteration: 3843/59290
Iteration: 3844/59290
Iteration: 3845/59290
Iteration: 3846/59290
Iteration: 3847/59290
Iteration: 3848/59290
Iteration: 3849/59290
Iteration: 3850/59290
Iteration: 3851/59290
Iteration: 3852/59290
Iteration: 3853/59290
Iteration: 3854/59290
Iteration: 3855/59290
Iteration: 3856/59290

  7%|▋         | 3856/59290 [03:34<38:41, 23.88it/s]

Iteration: 3857/59290
Iteration: 3858/59290
Iteration: 3859/59290
Iteration: 3860/59290
Iteration: 3861/59290
Iteration: 3862/59290
Iteration: 3863/59290
Iteration: 3864/59290
Iteration: 3865/59290
Iteration: 3866/59290
Iteration: 3867/59290
Iteration: 3868/59290
Iteration: 3869/59290
Iteration: 3870/59290
Iteration: 3871/59290
Iteration: 3872/59290
Iteration: 3873/59290
Iteration: 3874/59290
Iteration: 3875/59290
Iteration: 3876/59290
Iteration: 3877/59290
Iteration: 3878/59290
Iteration: 3879/59290
Iteration: 3880/59290

  7%|▋         | 3880/59290 [04:06<6:42:43,  2.29it/s]

Iteration: 3881/59290
Iteration: 3882/59290
Iteration: 3883/59290
Iteration: 3884/59290
Iteration: 3885/59290
Iteration: 3886/59290
Iteration: 3887/59290
Iteration: 3888/59290
Iteration: 3889/59290
Iteration: 3890/59290
Iteration: 3891/59290
Iteration: 3892/59290
Iteration: 3893/59290
Iteration: 3894/59290
Iteration: 3895/59290
Iteration: 3896/59290
Iteration: 3897/59290
Iteration: 3898/59290
Iteration: 3899/59290
Iteration: 3900/59290
Iteration: 3901/59290
Iteration: 3902/59290
Iteration: 3903/59290
Iteration: 3904/59290

  7%|▋         | 3904/59290 [04:07<4:46:38,  3.22it/s]

Iteration: 3905/59290
Iteration: 3906/59290
Iteration: 3907/59290
Iteration: 3908/59290
Iteration: 3909/59290
Iteration: 3910/59290
Iteration: 3911/59290
Iteration: 3912/59290
Iteration: 3913/59290
Iteration: 3914/59290
Iteration: 3915/59290
Iteration: 3916/59290
Iteration: 3917/59290
Iteration: 3918/59290
Iteration: 3919/59290
Iteration: 3920/59290
Iteration: 3921/59290
Iteration: 3922/59290
Iteration: 3923/59290
Iteration: 3924/59290
Iteration: 3925/59290
Iteration: 3926/59290
Iteration: 3927/59290
Iteration: 3928/59290

  7%|▋         | 3928/59290 [04:07<3:24:54,  4.50it/s]

Iteration: 3929/59290
Iteration: 3930/59290
Iteration: 3931/59290
Iteration: 3932/59290
Iteration: 3933/59290
Iteration: 3934/59290
Iteration: 3935/59290
Iteration: 3936/59290
Iteration: 3937/59290
Iteration: 3938/59290
Iteration: 3939/59290
Iteration: 3940/59290
Iteration: 3941/59290
Iteration: 3942/59290
Iteration: 3943/59290
Iteration: 3944/59290
Iteration: 3945/59290
Iteration: 3946/59290
Iteration: 3947/59290
Iteration: 3948/59290
Iteration: 3949/59290
Iteration: 3950/59290
Iteration: 3951/59290
Iteration: 3952/59290

  7%|▋         | 3952/59290 [04:08<2:27:46,  6.24it/s]

Iteration: 3953/59290
Iteration: 3954/59290
Iteration: 3955/59290
Iteration: 3956/59290
Iteration: 3957/59290
Iteration: 3958/59290
Iteration: 3959/59290
Iteration: 3960/59290
Iteration: 3961/59290
Iteration: 3962/59290
Iteration: 3963/59290
Iteration: 3964/59290
Iteration: 3965/59290
Iteration: 3966/59290
Iteration: 3967/59290
Iteration: 3968/59290
Iteration: 3969/59290
Iteration: 3970/59290
Iteration: 3971/59290
Iteration: 3972/59290
Iteration: 3973/59290
Iteration: 3974/59290
Iteration: 3975/59290
Iteration: 3976/59290

  7%|▋         | 3976/59290 [04:08<1:47:56,  8.54it/s]

Iteration: 3977/59290
Iteration: 3978/59290
Iteration: 3979/59290
Iteration: 3980/59290
Iteration: 3981/59290
Iteration: 3982/59290
Iteration: 3983/59290
Iteration: 3984/59290
Iteration: 3985/59290
Iteration: 3986/59290
Iteration: 3987/59290
Iteration: 3988/59290
Iteration: 3989/59290
Iteration: 3990/59290
Iteration: 3991/59290
Iteration: 3992/59290
Iteration: 3993/59290
Iteration: 3994/59290
Iteration: 3995/59290
Iteration: 3996/59290
Iteration: 3997/59290
Iteration: 3998/59290
Iteration: 3999/59290
Iteration: 4000/59290

  7%|▋         | 4000/59290 [04:09<1:30:02, 10.23it/s]

Iteration: 4001/59290
Iteration: 4002/59290
Iteration: 4003/59290
Iteration: 4004/59290
Iteration: 4005/59290
Iteration: 4006/59290
Iteration: 4007/59290
Iteration: 4008/59290
Iteration: 4009/59290
Iteration: 4010/59290
Iteration: 4011/59290
Iteration: 4012/59290
Iteration: 4013/59290
Iteration: 4014/59290
Iteration: 4015/59290
Iteration: 4016/59290
Iteration: 4017/59290
Iteration: 4018/59290
Iteration: 4019/59290
Iteration: 4020/59290
Iteration: 4021/59290
Iteration: 4022/59290
Iteration: 4023/59290
Iteration: 4024/59290

  7%|▋         | 4024/59290 [04:11<1:24:04, 10.96it/s]

Iteration: 4025/59290
Iteration: 4026/59290
Iteration: 4027/59290
Iteration: 4028/59290
Iteration: 4029/59290
Iteration: 4030/59290
Iteration: 4031/59290
Iteration: 4032/59290
Iteration: 4033/59290
Iteration: 4034/59290
Iteration: 4035/59290
Iteration: 4036/59290
Iteration: 4037/59290
Iteration: 4038/59290
Iteration: 4039/59290
Iteration: 4040/59290
Iteration: 4041/59290
Iteration: 4042/59290
Iteration: 4043/59290
Iteration: 4044/59290
Iteration: 4045/59290
Iteration: 4046/59290
Iteration: 4047/59290
Iteration: 4048/59290

  7%|▋         | 4048/59290 [04:12<1:05:39, 14.02it/s]

Iteration: 4049/59290
Iteration: 4050/59290
Iteration: 4051/59290
Iteration: 4052/59290
Iteration: 4053/59290
Iteration: 4054/59290
Iteration: 4055/59290
Iteration: 4056/59290
Iteration: 4057/59290
Iteration: 4058/59290
Iteration: 4059/59290
Iteration: 4060/59290
Iteration: 4061/59290
Iteration: 4062/59290
Iteration: 4063/59290
Iteration: 4064/59290
Iteration: 4065/59290
Iteration: 4066/59290
Iteration: 4067/59290
Iteration: 4068/59290
Iteration: 4069/59290
Iteration: 4070/59290
Iteration: 4071/59290
Iteration: 4072/59290

  7%|▋         | 4072/59290 [04:12<50:24, 18.26it/s]

Iteration: 4073/59290
Iteration: 4074/59290
Iteration: 4075/59290
Iteration: 4076/59290
Iteration: 4077/59290
Iteration: 4078/59290
Iteration: 4079/59290
Iteration: 4080/59290
Iteration: 4081/59290
Iteration: 4082/59290
Iteration: 4083/59290
Iteration: 4084/59290
Iteration: 4085/59290
Iteration: 4086/59290
Iteration: 4087/59290
Iteration: 4088/59290
Iteration: 4089/59290
Iteration: 4090/59290
Iteration: 4091/59290
Iteration: 4092/59290
Iteration: 4093/59290
Iteration: 4094/59290
Iteration: 4095/59290
Iteration: 4096/59290

  7%|▋         | 4096/59290 [04:13<39:57, 23.02it/s]

Iteration: 4097/59290
Iteration: 4098/59290
Iteration: 4099/59290
Iteration: 4100/59290
Iteration: 4101/59290
Iteration: 4102/59290
Iteration: 4103/59290
Iteration: 4104/59290
Iteration: 4105/59290
Iteration: 4106/59290
Iteration: 4107/59290
Iteration: 4108/59290
Iteration: 4109/59290
Iteration: 4110/59290
Iteration: 4111/59290
Iteration: 4112/59290
Iteration: 4113/59290
Iteration: 4114/59290
Iteration: 4115/59290
Iteration: 4116/59290
Iteration: 4117/59290
Iteration: 4118/59290
Iteration: 4119/59290
Iteration: 4120/59290

  7%|▋         | 4120/59290 [04:13<32:22, 28.41it/s]

Iteration: 4121/59290
Iteration: 4122/59290
Iteration: 4123/59290
Iteration: 4124/59290
Iteration: 4125/59290
Iteration: 4126/59290
Iteration: 4127/59290
Iteration: 4128/59290
Iteration: 4129/59290
Iteration: 4130/59290
Iteration: 4131/59290
Iteration: 4132/59290
Iteration: 4133/59290
Iteration: 4134/59290
Iteration: 4135/59290
Iteration: 4136/59290
Iteration: 4137/59290
Iteration: 4138/59290
Iteration: 4139/59290
Iteration: 4140/59290
Iteration: 4141/59290
Iteration: 4142/59290
Iteration: 4143/59290
Iteration: 4144/59290

  7%|▋         | 4144/59290 [04:13<27:03, 33.96it/s]

Iteration: 4145/59290
Iteration: 4146/59290
Iteration: 4147/59290
Iteration: 4148/59290
Iteration: 4149/59290
Iteration: 4150/59290
Iteration: 4151/59290
Iteration: 4152/59290
Iteration: 4153/59290
Iteration: 4154/59290
Iteration: 4155/59290
Iteration: 4156/59290
Iteration: 4157/59290
Iteration: 4158/59290
Iteration: 4159/59290
Iteration: 4160/59290
Iteration: 4161/59290
Iteration: 4162/59290
Iteration: 4163/59290
Iteration: 4164/59290
Iteration: 4165/59290
Iteration: 4166/59290
Iteration: 4167/59290
Iteration: 4168/59290

  7%|▋         | 4168/59290 [04:14<23:15, 39.50it/s]

Iteration: 4169/59290
Iteration: 4170/59290
Iteration: 4171/59290
Iteration: 4172/59290
Iteration: 4173/59290
Iteration: 4174/59290
Iteration: 4175/59290
Iteration: 4176/59290
Iteration: 4177/59290
Iteration: 4178/59290
Iteration: 4179/59290
Iteration: 4180/59290
Iteration: 4181/59290
Iteration: 4182/59290
Iteration: 4183/59290
Iteration: 4184/59290
Iteration: 4185/59290
Iteration: 4186/59290
Iteration: 4187/59290
Iteration: 4188/59290
Iteration: 4189/59290
Iteration: 4190/59290
Iteration: 4191/59290
Iteration: 4192/59290

  7%|▋         | 4192/59290 [04:14<20:34, 44.63it/s]

Iteration: 4193/59290
Iteration: 4194/59290
Iteration: 4195/59290
Iteration: 4196/59290
Iteration: 4197/59290
Iteration: 4198/59290
Iteration: 4199/59290
Iteration: 4200/59290
Iteration: 4201/59290
Iteration: 4202/59290
Iteration: 4203/59290
Iteration: 4204/59290
Iteration: 4205/59290
Iteration: 4206/59290
Iteration: 4207/59290
Iteration: 4208/59290
Iteration: 4209/59290
Iteration: 4210/59290
Iteration: 4211/59290
Iteration: 4212/59290
Iteration: 4213/59290
Iteration: 4214/59290
Iteration: 4215/59290
Iteration: 4216/59290

  7%|▋         | 4216/59290 [04:14<18:50, 48.70it/s]

Iteration: 4217/59290
Iteration: 4218/59290
Iteration: 4219/59290
Iteration: 4220/59290
Iteration: 4221/59290
Iteration: 4222/59290
Iteration: 4223/59290
Iteration: 4224/59290
Iteration: 4225/59290
Iteration: 4226/59290
Iteration: 4227/59290
Iteration: 4228/59290
Iteration: 4229/59290
Iteration: 4230/59290
Iteration: 4231/59290
Iteration: 4232/59290
Iteration: 4233/59290
Iteration: 4234/59290
Iteration: 4235/59290
Iteration: 4236/59290
Iteration: 4237/59290
Iteration: 4238/59290
Iteration: 4239/59290
Iteration: 4240/59290

  7%|▋         | 4240/59290 [04:15<17:45, 51.64it/s]

Iteration: 4241/59290
Iteration: 4242/59290
Iteration: 4243/59290
Iteration: 4244/59290
Iteration: 4245/59290
Iteration: 4246/59290
Iteration: 4247/59290
Iteration: 4248/59290
Iteration: 4249/59290
Iteration: 4250/59290
Iteration: 4251/59290
Iteration: 4252/59290
Iteration: 4253/59290
Iteration: 4254/59290
Iteration: 4255/59290
Iteration: 4256/59290
Iteration: 4257/59290
Iteration: 4258/59290
Iteration: 4259/59290
Iteration: 4260/59290
Iteration: 4261/59290
Iteration: 4262/59290
Iteration: 4263/59290
Iteration: 4264/59290

  7%|▋         | 4264/59290 [04:15<16:57, 54.08it/s]

Iteration: 4265/59290
Iteration: 4266/59290
Iteration: 4267/59290
Iteration: 4268/59290
Iteration: 4269/59290
Iteration: 4270/59290
Iteration: 4271/59290
Iteration: 4272/59290
Iteration: 4273/59290
Iteration: 4274/59290
Iteration: 4275/59290
Iteration: 4276/59290
Iteration: 4277/59290
Iteration: 4278/59290
Iteration: 4279/59290
Iteration: 4280/59290
Iteration: 4281/59290
Iteration: 4282/59290
Iteration: 4283/59290
Iteration: 4284/59290
Iteration: 4285/59290
Iteration: 4286/59290
Iteration: 4287/59290
Iteration: 4288/59290

  7%|▋         | 4288/59290 [04:16<25:13, 36.35it/s]

Iteration: 4289/59290
Iteration: 4290/59290
Iteration: 4291/59290
Iteration: 4292/59290
Iteration: 4293/59290
Iteration: 4294/59290
Iteration: 4295/59290
Iteration: 4296/59290
Iteration: 4297/59290
Iteration: 4298/59290
Iteration: 4299/59290
Iteration: 4300/59290
Iteration: 4301/59290
Iteration: 4302/59290
Iteration: 4303/59290
Iteration: 4304/59290
Iteration: 4305/59290
Iteration: 4306/59290
Iteration: 4307/59290
Iteration: 4308/59290
Iteration: 4309/59290
Iteration: 4310/59290
Iteration: 4311/59290
Iteration: 4312/59290

  7%|▋         | 4312/59290 [04:18<38:32, 23.77it/s]

Iteration: 4313/59290
Iteration: 4314/59290
Iteration: 4315/59290
Iteration: 4316/59290
Iteration: 4317/59290
Iteration: 4318/59290
Iteration: 4319/59290
Iteration: 4320/59290
Iteration: 4321/59290
Iteration: 4322/59290
Iteration: 4323/59290
Iteration: 4324/59290
Iteration: 4325/59290
Iteration: 4326/59290
Iteration: 4327/59290
Iteration: 4328/59290
Iteration: 4329/59290
Iteration: 4330/59290
Iteration: 4331/59290
Iteration: 4332/59290
Iteration: 4333/59290
Iteration: 4334/59290
Iteration: 4335/59290
Iteration: 4336/59290

  7%|▋         | 4336/59290 [04:19<33:51, 27.05it/s]

Iteration: 4337/59290
Iteration: 4338/59290
Iteration: 4339/59290
Iteration: 4340/59290
Iteration: 4341/59290
Iteration: 4342/59290
Iteration: 4343/59290
Iteration: 4344/59290
Iteration: 4345/59290
Iteration: 4346/59290
Iteration: 4347/59290
Iteration: 4348/59290
Iteration: 4349/59290
Iteration: 4350/59290
Iteration: 4351/59290
Iteration: 4352/59290
Iteration: 4353/59290
Iteration: 4354/59290
Iteration: 4355/59290
Iteration: 4356/59290
Iteration: 4357/59290
Iteration: 4358/59290
Iteration: 4359/59290
Iteration: 4360/59290

  7%|▋         | 4360/59290 [04:19<28:00, 32.69it/s]

Iteration: 4361/59290
Iteration: 4362/59290
Iteration: 4363/59290
Iteration: 4364/59290
Iteration: 4365/59290
Iteration: 4366/59290
Iteration: 4367/59290
Iteration: 4368/59290
Iteration: 4369/59290
Iteration: 4370/59290
Iteration: 4371/59290
Iteration: 4372/59290
Iteration: 4373/59290
Iteration: 4374/59290
Iteration: 4375/59290
Iteration: 4376/59290
Iteration: 4377/59290
Iteration: 4378/59290
Iteration: 4379/59290
Iteration: 4380/59290
Iteration: 4381/59290
Iteration: 4382/59290
Iteration: 4383/59290
Iteration: 4384/59290

  7%|▋         | 4384/59290 [04:20<24:02, 38.07it/s]

Iteration: 4385/59290
Iteration: 4386/59290
Iteration: 4387/59290
Iteration: 4388/59290
Iteration: 4389/59290
Iteration: 4390/59290
Iteration: 4391/59290
Iteration: 4392/59290
Iteration: 4393/59290
Iteration: 4394/59290
Iteration: 4395/59290
Iteration: 4396/59290
Iteration: 4397/59290
Iteration: 4398/59290
Iteration: 4399/59290
Iteration: 4400/59290
Iteration: 4401/59290
Iteration: 4402/59290
Iteration: 4403/59290
Iteration: 4404/59290
Iteration: 4405/59290
Iteration: 4406/59290
Iteration: 4407/59290
Iteration: 4408/59290

  7%|▋         | 4408/59290 [04:20<21:06, 43.35it/s]

Iteration: 4409/59290
Iteration: 4410/59290
Iteration: 4411/59290
Iteration: 4412/59290
Iteration: 4413/59290
Iteration: 4414/59290
Iteration: 4415/59290
Iteration: 4416/59290
Iteration: 4417/59290
Iteration: 4418/59290
Iteration: 4419/59290
Iteration: 4420/59290
Iteration: 4421/59290
Iteration: 4422/59290
Iteration: 4423/59290
Iteration: 4424/59290
Iteration: 4425/59290
Iteration: 4426/59290
Iteration: 4427/59290
Iteration: 4428/59290
Iteration: 4429/59290
Iteration: 4430/59290
Iteration: 4431/59290
Iteration: 4432/59290

  7%|▋         | 4432/59290 [04:23<51:42, 17.68it/s]

Iteration: 4433/59290
Iteration: 4434/59290
Iteration: 4435/59290
Iteration: 4436/59290
Iteration: 4437/59290
Iteration: 4438/59290
Iteration: 4439/59290
Iteration: 4440/59290
Iteration: 4441/59290
Iteration: 4442/59290
Iteration: 4443/59290
Iteration: 4444/59290
Iteration: 4445/59290
Iteration: 4446/59290
Iteration: 4447/59290
Iteration: 4448/59290
Iteration: 4449/59290
Iteration: 4450/59290
Iteration: 4451/59290
Iteration: 4452/59290
Iteration: 4453/59290
Iteration: 4454/59290
Iteration: 4455/59290
Iteration: 4456/59290

  8%|▊         | 4456/59290 [04:24<41:33, 21.99it/s]

Iteration: 4457/59290
Iteration: 4458/59290
Iteration: 4459/59290
Iteration: 4460/59290
Iteration: 4461/59290
Iteration: 4462/59290
Iteration: 4463/59290
Iteration: 4464/59290
Iteration: 4465/59290
Iteration: 4466/59290
Iteration: 4467/59290
Iteration: 4468/59290
Iteration: 4469/59290
Iteration: 4470/59290
Iteration: 4471/59290
Iteration: 4472/59290
Iteration: 4473/59290
Iteration: 4474/59290
Iteration: 4475/59290
Iteration: 4476/59290
Iteration: 4477/59290
Iteration: 4478/59290
Iteration: 4479/59290
Iteration: 4480/59290

  8%|▊         | 4480/59290 [04:24<33:21, 27.39it/s]

Iteration: 4481/59290
Iteration: 4482/59290
Iteration: 4483/59290
Iteration: 4484/59290
Iteration: 4485/59290
Iteration: 4486/59290
Iteration: 4487/59290
Iteration: 4488/59290
Iteration: 4489/59290
Iteration: 4490/59290
Iteration: 4491/59290
Iteration: 4492/59290
Iteration: 4493/59290
Iteration: 4494/59290
Iteration: 4495/59290
Iteration: 4496/59290
Iteration: 4497/59290
Iteration: 4498/59290
Iteration: 4499/59290
Iteration: 4500/59290
Iteration: 4501/59290
Iteration: 4502/59290
Iteration: 4503/59290
Iteration: 4504/59290

  8%|▊         | 4504/59290 [04:24<27:38, 33.04it/s]

Iteration: 4505/59290
Iteration: 4506/59290
Iteration: 4507/59290
Iteration: 4508/59290
Iteration: 4509/59290
Iteration: 4510/59290
Iteration: 4511/59290
Iteration: 4512/59290
Iteration: 4513/59290
Iteration: 4514/59290
Iteration: 4515/59290
Iteration: 4516/59290
Iteration: 4517/59290
Iteration: 4518/59290
Iteration: 4519/59290
Iteration: 4520/59290
Iteration: 4521/59290
Iteration: 4522/59290
Iteration: 4523/59290
Iteration: 4524/59290
Iteration: 4525/59290
Iteration: 4526/59290
Iteration: 4527/59290
Iteration: 4528/59290

  8%|▊         | 4528/59290 [04:25<23:38, 38.61it/s]

Iteration: 4529/59290
Iteration: 4530/59290
Iteration: 4531/59290
Iteration: 4532/59290
Iteration: 4533/59290
Iteration: 4534/59290
Iteration: 4535/59290
Iteration: 4536/59290
Iteration: 4537/59290
Iteration: 4538/59290
Iteration: 4539/59290
Iteration: 4540/59290
Iteration: 4541/59290
Iteration: 4542/59290
Iteration: 4543/59290
Iteration: 4544/59290
Iteration: 4545/59290
Iteration: 4546/59290
Iteration: 4547/59290
Iteration: 4548/59290
Iteration: 4549/59290
Iteration: 4550/59290
Iteration: 4551/59290
Iteration: 4552/59290

  8%|▊         | 4552/59290 [04:25<20:44, 43.97it/s]

Iteration: 4553/59290
Iteration: 4554/59290
Iteration: 4555/59290
Iteration: 4556/59290
Iteration: 4557/59290
Iteration: 4558/59290
Iteration: 4559/59290
Iteration: 4560/59290
Iteration: 4561/59290
Iteration: 4562/59290
Iteration: 4563/59290
Iteration: 4564/59290
Iteration: 4565/59290
Iteration: 4566/59290
Iteration: 4567/59290
Iteration: 4568/59290
Iteration: 4569/59290
Iteration: 4570/59290
Iteration: 4571/59290
Iteration: 4572/59290
Iteration: 4573/59290
Iteration: 4574/59290
Iteration: 4575/59290
Iteration: 4576/59290

  8%|▊         | 4576/59290 [04:26<18:52, 48.32it/s]

Iteration: 4577/59290
Iteration: 4578/59290
Iteration: 4579/59290
Iteration: 4580/59290
Iteration: 4581/59290
Iteration: 4582/59290
Iteration: 4583/59290
Iteration: 4584/59290
Iteration: 4585/59290
Iteration: 4586/59290
Iteration: 4587/59290
Iteration: 4588/59290
Iteration: 4589/59290
Iteration: 4590/59290
Iteration: 4591/59290
Iteration: 4592/59290
Iteration: 4593/59290
Iteration: 4594/59290
Iteration: 4595/59290
Iteration: 4596/59290
Iteration: 4597/59290
Iteration: 4598/59290
Iteration: 4599/59290
Iteration: 4600/59290

  8%|▊         | 4600/59290 [04:26<17:28, 52.17it/s]

Iteration: 4601/59290
Iteration: 4602/59290
Iteration: 4603/59290
Iteration: 4604/59290
Iteration: 4605/59290
Iteration: 4606/59290
Iteration: 4607/59290
Iteration: 4608/59290
Iteration: 4609/59290
Iteration: 4610/59290
Iteration: 4611/59290
Iteration: 4612/59290
Iteration: 4613/59290
Iteration: 4614/59290
Iteration: 4615/59290
Iteration: 4616/59290
Iteration: 4617/59290
Iteration: 4618/59290
Iteration: 4619/59290
Iteration: 4620/59290
Iteration: 4621/59290
Iteration: 4622/59290
Iteration: 4623/59290
Iteration: 4624/59290

  8%|▊         | 4624/59290 [04:26<16:50, 54.10it/s]

Iteration: 4625/59290
Iteration: 4626/59290
Iteration: 4627/59290
Iteration: 4628/59290
Iteration: 4629/59290
Iteration: 4630/59290
Iteration: 4631/59290
Iteration: 4632/59290
Iteration: 4633/59290
Iteration: 4634/59290
Iteration: 4635/59290
Iteration: 4636/59290
Iteration: 4637/59290
Iteration: 4638/59290
Iteration: 4639/59290
Iteration: 4640/59290
Iteration: 4641/59290
Iteration: 4642/59290
Iteration: 4643/59290
Iteration: 4644/59290
Iteration: 4645/59290
Iteration: 4646/59290
Iteration: 4647/59290
Iteration: 4648/59290

  8%|▊         | 4648/59290 [04:27<15:59, 56.94it/s]

Iteration: 4649/59290
Iteration: 4650/59290
Iteration: 4651/59290
Iteration: 4652/59290
Iteration: 4653/59290
Iteration: 4654/59290
Iteration: 4655/59290
Iteration: 4656/59290
Iteration: 4657/59290
Iteration: 4658/59290
Iteration: 4659/59290
Iteration: 4660/59290
Iteration: 4661/59290
Iteration: 4662/59290
Iteration: 4663/59290
Iteration: 4664/59290
Iteration: 4665/59290
Iteration: 4666/59290
Iteration: 4667/59290
Iteration: 4668/59290
Iteration: 4669/59290
Iteration: 4670/59290
Iteration: 4671/59290
Iteration: 4672/59290

  8%|▊         | 4672/59290 [04:28<27:42, 32.86it/s]

Iteration: 4673/59290
Iteration: 4674/59290
Iteration: 4675/59290
Iteration: 4676/59290
Iteration: 4677/59290
Iteration: 4678/59290
Iteration: 4679/59290
Iteration: 4680/59290
Iteration: 4681/59290
Iteration: 4682/59290
Iteration: 4683/59290
Iteration: 4684/59290
Iteration: 4685/59290
Iteration: 4686/59290
Iteration: 4687/59290
Iteration: 4688/59290
Iteration: 4689/59290
Iteration: 4690/59290
Iteration: 4691/59290
Iteration: 4692/59290
Iteration: 4693/59290
Iteration: 4694/59290
Iteration: 4695/59290
Iteration: 4696/59290

  8%|▊         | 4696/59290 [04:30<41:09, 22.11it/s]

Iteration: 4697/59290
Iteration: 4698/59290
Iteration: 4699/59290
Iteration: 4700/59290
Iteration: 4701/59290
Iteration: 4702/59290
Iteration: 4703/59290
Iteration: 4704/59290
Iteration: 4705/59290
Iteration: 4706/59290
Iteration: 4707/59290
Iteration: 4708/59290
Iteration: 4709/59290
Iteration: 4710/59290
Iteration: 4711/59290
Iteration: 4712/59290
Iteration: 4713/59290
Iteration: 4714/59290
Iteration: 4715/59290
Iteration: 4716/59290
Iteration: 4717/59290
Iteration: 4718/59290
Iteration: 4719/59290
Iteration: 4720/59290

  8%|▊         | 4720/59290 [04:30<33:05, 27.49it/s]

Iteration: 4721/59290
Iteration: 4722/59290
Iteration: 4723/59290
Iteration: 4724/59290
Iteration: 4725/59290
Iteration: 4726/59290
Iteration: 4727/59290
Iteration: 4728/59290
Iteration: 4729/59290
Iteration: 4730/59290
Iteration: 4731/59290
Iteration: 4732/59290
Iteration: 4733/59290
Iteration: 4734/59290
Iteration: 4735/59290
Iteration: 4736/59290
Iteration: 4737/59290
Iteration: 4738/59290
Iteration: 4739/59290
Iteration: 4740/59290
Iteration: 4741/59290
Iteration: 4742/59290
Iteration: 4743/59290
Iteration: 4744/59290

  8%|▊         | 4744/59290 [04:31<29:10, 31.15it/s]

Iteration: 4745/59290
Iteration: 4746/59290
Iteration: 4747/59290
Iteration: 4748/59290
Iteration: 4749/59290
Iteration: 4750/59290
Iteration: 4751/59290
Iteration: 4752/59290
Iteration: 4753/59290
Iteration: 4754/59290
Iteration: 4755/59290
Iteration: 4756/59290
Iteration: 4757/59290
Iteration: 4758/59290
Iteration: 4759/59290
Iteration: 4760/59290
Iteration: 4761/59290
Iteration: 4762/59290
Iteration: 4763/59290
Iteration: 4764/59290
Iteration: 4765/59290
Iteration: 4766/59290
Iteration: 4767/59290
Iteration: 4768/59290

  8%|▊         | 4768/59290 [04:31<24:39, 36.84it/s]

Iteration: 4769/59290
Iteration: 4770/59290
Iteration: 4771/59290
Iteration: 4772/59290
Iteration: 4773/59290
Iteration: 4774/59290
Iteration: 4775/59290
Iteration: 4776/59290
Iteration: 4777/59290
Iteration: 4778/59290
Iteration: 4779/59290
Iteration: 4780/59290
Iteration: 4781/59290
Iteration: 4782/59290
Iteration: 4783/59290
Iteration: 4784/59290
Iteration: 4785/59290
Iteration: 4786/59290
Iteration: 4787/59290
Iteration: 4788/59290
Iteration: 4789/59290
Iteration: 4790/59290
Iteration: 4791/59290
Iteration: 4792/59290

  8%|▊         | 4792/59290 [04:32<21:26, 42.36it/s]

Iteration: 4793/59290
Iteration: 4794/59290
Iteration: 4795/59290
Iteration: 4796/59290
Iteration: 4797/59290
Iteration: 4798/59290
Iteration: 4799/59290
Iteration: 4800/59290
Iteration: 4801/59290
Iteration: 4802/59290
Iteration: 4803/59290
Iteration: 4804/59290
Iteration: 4805/59290
Iteration: 4806/59290
Iteration: 4807/59290
Iteration: 4808/59290
Iteration: 4809/59290
Iteration: 4810/59290
Iteration: 4811/59290
Iteration: 4812/59290
Iteration: 4813/59290
Iteration: 4814/59290
Iteration: 4815/59290
Iteration: 4816/59290

  8%|▊         | 4816/59290 [04:32<19:31, 46.49it/s]

Iteration: 4817/59290
Iteration: 4818/59290
Iteration: 4819/59290
Iteration: 4820/59290
Iteration: 4821/59290
Iteration: 4822/59290
Iteration: 4823/59290
Iteration: 4824/59290
Iteration: 4825/59290
Iteration: 4826/59290
Iteration: 4827/59290
Iteration: 4828/59290
Iteration: 4829/59290
Iteration: 4830/59290
Iteration: 4831/59290
Iteration: 4832/59290
Iteration: 4833/59290
Iteration: 4834/59290
Iteration: 4835/59290
Iteration: 4836/59290
Iteration: 4837/59290
Iteration: 4838/59290
Iteration: 4839/59290
Iteration: 4840/59290

  8%|▊         | 4840/59290 [04:33<28:08, 32.26it/s]

Iteration: 4841/59290
Iteration: 4842/59290
Iteration: 4843/59290
Iteration: 4844/59290
Iteration: 4845/59290
Iteration: 4846/59290
Iteration: 4847/59290
Iteration: 4848/59290
Iteration: 4849/59290
Iteration: 4850/59290
Iteration: 4851/59290
Iteration: 4852/59290
Iteration: 4853/59290
Iteration: 4854/59290
Iteration: 4855/59290
Iteration: 4856/59290
Iteration: 4857/59290
Iteration: 4858/59290
Iteration: 4859/59290
Iteration: 4860/59290
Iteration: 4861/59290
Iteration: 4862/59290
Iteration: 4863/59290
Iteration: 4864/59290

  8%|▊         | 4864/59290 [04:35<41:06, 22.07it/s]

Iteration: 4865/59290
Iteration: 4866/59290
Iteration: 4867/59290
Iteration: 4868/59290
Iteration: 4869/59290
Iteration: 4870/59290
Iteration: 4871/59290
Iteration: 4872/59290
Iteration: 4873/59290
Iteration: 4874/59290
Iteration: 4875/59290
Iteration: 4876/59290
Iteration: 4877/59290
Iteration: 4878/59290
Iteration: 4879/59290
Iteration: 4880/59290
Iteration: 4881/59290
Iteration: 4882/59290
Iteration: 4883/59290
Iteration: 4884/59290
Iteration: 4885/59290
Iteration: 4886/59290
Iteration: 4887/59290
Iteration: 4888/59290

  8%|▊         | 4888/59290 [04:36<36:53, 24.57it/s]

Iteration: 4889/59290
Iteration: 4890/59290
Iteration: 4891/59290
Iteration: 4892/59290
Iteration: 4893/59290
Iteration: 4894/59290
Iteration: 4895/59290
Iteration: 4896/59290
Iteration: 4897/59290
Iteration: 4898/59290
Iteration: 4899/59290
Iteration: 4900/59290
Iteration: 4901/59290
Iteration: 4902/59290
Iteration: 4903/59290
Iteration: 4904/59290
Iteration: 4905/59290
Iteration: 4906/59290
Iteration: 4907/59290
Iteration: 4908/59290
Iteration: 4909/59290
Iteration: 4910/59290
Iteration: 4911/59290
Iteration: 4912/59290

  8%|▊         | 4912/59290 [04:36<30:12, 30.00it/s]

Iteration: 4913/59290
Iteration: 4914/59290
Iteration: 4915/59290
Iteration: 4916/59290
Iteration: 4917/59290
Iteration: 4918/59290
Iteration: 4919/59290
Iteration: 4920/59290
Iteration: 4921/59290
Iteration: 4922/59290
Iteration: 4923/59290
Iteration: 4924/59290
Iteration: 4925/59290
Iteration: 4926/59290
Iteration: 4927/59290
Iteration: 4928/59290
Iteration: 4929/59290
Iteration: 4930/59290
Iteration: 4931/59290
Iteration: 4932/59290
Iteration: 4933/59290
Iteration: 4934/59290
Iteration: 4935/59290
Iteration: 4936/59290

  8%|▊         | 4936/59290 [04:37<25:25, 35.64it/s]

Iteration: 4937/59290
Iteration: 4938/59290
Iteration: 4939/59290
Iteration: 4940/59290
Iteration: 4941/59290
Iteration: 4942/59290
Iteration: 4943/59290
Iteration: 4944/59290
Iteration: 4945/59290
Iteration: 4946/59290
Iteration: 4947/59290
Iteration: 4948/59290
Iteration: 4949/59290
Iteration: 4950/59290
Iteration: 4951/59290
Iteration: 4952/59290
Iteration: 4953/59290
Iteration: 4954/59290
Iteration: 4955/59290
Iteration: 4956/59290
Iteration: 4957/59290
Iteration: 4958/59290
Iteration: 4959/59290
Iteration: 4960/59290

  8%|▊         | 4960/59290 [04:37<22:01, 41.10it/s]

Iteration: 4961/59290
Iteration: 4962/59290
Iteration: 4963/59290
Iteration: 4964/59290
Iteration: 4965/59290
Iteration: 4966/59290
Iteration: 4967/59290
Iteration: 4968/59290
Iteration: 4969/59290
Iteration: 4970/59290
Iteration: 4971/59290
Iteration: 4972/59290
Iteration: 4973/59290
Iteration: 4974/59290
Iteration: 4975/59290
Iteration: 4976/59290
Iteration: 4977/59290
Iteration: 4978/59290
Iteration: 4979/59290
Iteration: 4980/59290
Iteration: 4981/59290
Iteration: 4982/59290
Iteration: 4983/59290
Iteration: 4984/59290

  8%|▊         | 4984/59290 [04:38<19:51, 45.57it/s]

Iteration: 4985/59290
Iteration: 4986/59290
Iteration: 4987/59290
Iteration: 4988/59290
Iteration: 4989/59290
Iteration: 4990/59290
Iteration: 4991/59290
Iteration: 4992/59290
Iteration: 4993/59290
Iteration: 4994/59290
Iteration: 4995/59290
Iteration: 4996/59290
Iteration: 4997/59290
Iteration: 4998/59290
Iteration: 4999/59290
Iteration: 5000/59290
Iteration: 5001/59290
Iteration: 5002/59290
Iteration: 5003/59290
Iteration: 5004/59290
Iteration: 5005/59290
Iteration: 5006/59290
Iteration: 5007/59290
Iteration: 5008/59290

  8%|▊         | 5008/59290 [04:38<18:16, 49.50it/s]

Iteration: 5009/59290
Iteration: 5010/59290
Iteration: 5011/59290
Iteration: 5012/59290
Iteration: 5013/59290
Iteration: 5014/59290
Iteration: 5015/59290
Iteration: 5016/59290
Iteration: 5017/59290
Iteration: 5018/59290
Iteration: 5019/59290
Iteration: 5020/59290
Iteration: 5021/59290
Iteration: 5022/59290
Iteration: 5023/59290
Iteration: 5024/59290
Iteration: 5025/59290
Iteration: 5026/59290
Iteration: 5027/59290
Iteration: 5028/59290
Iteration: 5029/59290
Iteration: 5030/59290
Iteration: 5031/59290
Iteration: 5032/59290

  8%|▊         | 5032/59290 [04:38<16:59, 53.23it/s]

Iteration: 5033/59290
Iteration: 5034/59290
Iteration: 5035/59290
Iteration: 5036/59290
Iteration: 5037/59290
Iteration: 5038/59290
Iteration: 5039/59290
Iteration: 5040/59290
Iteration: 5041/59290
Iteration: 5042/59290
Iteration: 5043/59290
Iteration: 5044/59290
Iteration: 5045/59290
Iteration: 5046/59290
Iteration: 5047/59290
Iteration: 5048/59290
Iteration: 5049/59290
Iteration: 5050/59290
Iteration: 5051/59290
Iteration: 5052/59290
Iteration: 5053/59290
Iteration: 5054/59290
Iteration: 5055/59290
Iteration: 5056/59290

  9%|▊         | 5056/59290 [04:39<16:28, 54.85it/s]

Iteration: 5057/59290
Iteration: 5058/59290
Iteration: 5059/59290
Iteration: 5060/59290
Iteration: 5061/59290
Iteration: 5062/59290
Iteration: 5063/59290
Iteration: 5064/59290
Iteration: 5065/59290
Iteration: 5066/59290
Iteration: 5067/59290
Iteration: 5068/59290
Iteration: 5069/59290
Iteration: 5070/59290
Iteration: 5071/59290
Iteration: 5072/59290
Iteration: 5073/59290
Iteration: 5074/59290
Iteration: 5075/59290
Iteration: 5076/59290
Iteration: 5077/59290
Iteration: 5078/59290
Iteration: 5079/59290
Iteration: 5080/59290

  9%|▊         | 5080/59290 [04:40<25:48, 35.01it/s]

Iteration: 5081/59290
Iteration: 5082/59290
Iteration: 5083/59290
Iteration: 5084/59290
Iteration: 5085/59290
Iteration: 5086/59290
Iteration: 5087/59290
Iteration: 5088/59290
Iteration: 5089/59290
Iteration: 5090/59290
Iteration: 5091/59290
Iteration: 5092/59290
Iteration: 5093/59290
Iteration: 5094/59290
Iteration: 5095/59290
Iteration: 5096/59290
Iteration: 5097/59290
Iteration: 5098/59290
Iteration: 5099/59290
Iteration: 5100/59290
Iteration: 5101/59290
Iteration: 5102/59290
Iteration: 5103/59290
Iteration: 5104/59290

  9%|▊         | 5104/59290 [04:42<44:35, 20.25it/s]

Iteration: 5105/59290
Iteration: 5106/59290
Iteration: 5107/59290
Iteration: 5108/59290
Iteration: 5109/59290
Iteration: 5110/59290
Iteration: 5111/59290
Iteration: 5112/59290
Iteration: 5113/59290
Iteration: 5114/59290
Iteration: 5115/59290
Iteration: 5116/59290
Iteration: 5117/59290
Iteration: 5118/59290
Iteration: 5119/59290
Iteration: 5120/59290
Iteration: 5121/59290
Iteration: 5122/59290
Iteration: 5123/59290
Iteration: 5124/59290
Iteration: 5125/59290
Iteration: 5126/59290
Iteration: 5127/59290
Iteration: 5128/59290

  9%|▊         | 5128/59290 [04:43<35:40, 25.30it/s]

Iteration: 5129/59290
Iteration: 5130/59290
Iteration: 5131/59290
Iteration: 5132/59290
Iteration: 5133/59290
Iteration: 5134/59290
Iteration: 5135/59290
Iteration: 5136/59290
Iteration: 5137/59290
Iteration: 5138/59290
Iteration: 5139/59290
Iteration: 5140/59290
Iteration: 5141/59290
Iteration: 5142/59290
Iteration: 5143/59290
Iteration: 5144/59290
Iteration: 5145/59290
Iteration: 5146/59290
Iteration: 5147/59290
Iteration: 5148/59290
Iteration: 5149/59290
Iteration: 5150/59290
Iteration: 5151/59290
Iteration: 5152/59290

  9%|▊         | 5152/59290 [04:43<29:14, 30.86it/s]

Iteration: 5153/59290
Iteration: 5154/59290
Iteration: 5155/59290
Iteration: 5156/59290
Iteration: 5157/59290
Iteration: 5158/59290
Iteration: 5159/59290
Iteration: 5160/59290
Iteration: 5161/59290
Iteration: 5162/59290
Iteration: 5163/59290
Iteration: 5164/59290
Iteration: 5165/59290
Iteration: 5166/59290
Iteration: 5167/59290
Iteration: 5168/59290
Iteration: 5169/59290
Iteration: 5170/59290
Iteration: 5171/59290
Iteration: 5172/59290
Iteration: 5173/59290
Iteration: 5174/59290
Iteration: 5175/59290
Iteration: 5176/59290

  9%|▊         | 5176/59290 [04:43<24:36, 36.64it/s]

Iteration: 5177/59290
Iteration: 5178/59290
Iteration: 5179/59290
Iteration: 5180/59290
Iteration: 5181/59290
Iteration: 5182/59290
Iteration: 5183/59290
Iteration: 5184/59290
Iteration: 5185/59290
Iteration: 5186/59290
Iteration: 5187/59290
Iteration: 5188/59290
Iteration: 5189/59290
Iteration: 5190/59290
Iteration: 5191/59290
Iteration: 5192/59290
Iteration: 5193/59290
Iteration: 5194/59290
Iteration: 5195/59290
Iteration: 5196/59290
Iteration: 5197/59290
Iteration: 5198/59290
Iteration: 5199/59290
Iteration: 5200/59290

  9%|▉         | 5200/59290 [04:44<21:34, 41.77it/s]

Iteration: 5201/59290
Iteration: 5202/59290
Iteration: 5203/59290
Iteration: 5204/59290
Iteration: 5205/59290
Iteration: 5206/59290
Iteration: 5207/59290
Iteration: 5208/59290
Iteration: 5209/59290
Iteration: 5210/59290
Iteration: 5211/59290
Iteration: 5212/59290
Iteration: 5213/59290
Iteration: 5214/59290
Iteration: 5215/59290
Iteration: 5216/59290
Iteration: 5217/59290
Iteration: 5218/59290
Iteration: 5219/59290
Iteration: 5220/59290
Iteration: 5221/59290
Iteration: 5222/59290
Iteration: 5223/59290
Iteration: 5224/59290

  9%|▉         | 5224/59290 [04:44<19:32, 46.13it/s]

Iteration: 5225/59290
Iteration: 5226/59290
Iteration: 5227/59290
Iteration: 5228/59290
Iteration: 5229/59290
Iteration: 5230/59290
Iteration: 5231/59290
Iteration: 5232/59290
Iteration: 5233/59290
Iteration: 5234/59290
Iteration: 5235/59290
Iteration: 5236/59290
Iteration: 5237/59290
Iteration: 5238/59290
Iteration: 5239/59290
Iteration: 5240/59290
Iteration: 5241/59290
Iteration: 5242/59290
Iteration: 5243/59290
Iteration: 5244/59290
Iteration: 5245/59290
Iteration: 5246/59290
Iteration: 5247/59290
Iteration: 5248/59290

  9%|▉         | 5248/59290 [04:45<18:14, 49.35it/s]

Iteration: 5249/59290
Iteration: 5250/59290
Iteration: 5251/59290
Iteration: 5252/59290
Iteration: 5253/59290
Iteration: 5254/59290
Iteration: 5255/59290
Iteration: 5256/59290
Iteration: 5257/59290
Iteration: 5258/59290
Iteration: 5259/59290
Iteration: 5260/59290
Iteration: 5261/59290
Iteration: 5262/59290
Iteration: 5263/59290
Iteration: 5264/59290
Iteration: 5265/59290
Iteration: 5266/59290
Iteration: 5267/59290
Iteration: 5268/59290
Iteration: 5269/59290
Iteration: 5270/59290
Iteration: 5271/59290
Iteration: 5272/59290

  9%|▉         | 5272/59290 [04:45<17:01, 52.90it/s]

Iteration: 5273/59290
Iteration: 5274/59290
Iteration: 5275/59290
Iteration: 5276/59290
Iteration: 5277/59290
Iteration: 5278/59290
Iteration: 5279/59290
Iteration: 5280/59290
Iteration: 5281/59290
Iteration: 5282/59290
Iteration: 5283/59290
Iteration: 5284/59290
Iteration: 5285/59290
Iteration: 5286/59290
Iteration: 5287/59290
Iteration: 5288/59290
Iteration: 5289/59290
Iteration: 5290/59290
Iteration: 5291/59290
Iteration: 5292/59290
Iteration: 5293/59290
Iteration: 5294/59290
Iteration: 5295/59290
Iteration: 5296/59290

  9%|▉         | 5296/59290 [04:45<16:03, 56.04it/s]

Iteration: 5297/59290
Iteration: 5298/59290
Iteration: 5299/59290
Iteration: 5300/59290
Iteration: 5301/59290
Iteration: 5302/59290
Iteration: 5303/59290
Iteration: 5304/59290
Iteration: 5305/59290
Iteration: 5306/59290
Iteration: 5307/59290
Iteration: 5308/59290
Iteration: 5309/59290
Iteration: 5310/59290
Iteration: 5311/59290
Iteration: 5312/59290
Iteration: 5313/59290
Iteration: 5314/59290
Iteration: 5315/59290
Iteration: 5316/59290
Iteration: 5317/59290
Iteration: 5318/59290
Iteration: 5319/59290
Iteration: 5320/59290

  9%|▉         | 5320/59290 [04:46<15:31, 57.94it/s]

Iteration: 5321/59290
Iteration: 5322/59290
Iteration: 5323/59290
Iteration: 5324/59290
Iteration: 5325/59290
Iteration: 5326/59290
Iteration: 5327/59290
Iteration: 5328/59290
Iteration: 5329/59290
Iteration: 5330/59290
Iteration: 5331/59290
Iteration: 5332/59290
Iteration: 5333/59290
Iteration: 5334/59290
Iteration: 5335/59290
Iteration: 5336/59290
Iteration: 5337/59290
Iteration: 5338/59290
Iteration: 5339/59290
Iteration: 5340/59290
Iteration: 5341/59290
Iteration: 5342/59290
Iteration: 5343/59290
Iteration: 5344/59290

  9%|▉         | 5344/59290 [04:46<15:05, 59.56it/s]

Iteration: 5345/59290
Iteration: 5346/59290
Iteration: 5347/59290
Iteration: 5348/59290
Iteration: 5349/59290
Iteration: 5350/59290
Iteration: 5351/59290
Iteration: 5352/59290
Iteration: 5353/59290
Iteration: 5354/59290
Iteration: 5355/59290
Iteration: 5356/59290
Iteration: 5357/59290
Iteration: 5358/59290
Iteration: 5359/59290
Iteration: 5360/59290
Iteration: 5361/59290
Iteration: 5362/59290
Iteration: 5363/59290
Iteration: 5364/59290
Iteration: 5365/59290
Iteration: 5366/59290
Iteration: 5367/59290
Iteration: 5368/59290

  9%|▉         | 5368/59290 [04:48<26:27, 33.96it/s]

Iteration: 5369/59290
Iteration: 5370/59290
Iteration: 5371/59290
Iteration: 5372/59290
Iteration: 5373/59290
Iteration: 5374/59290
Iteration: 5375/59290
Iteration: 5376/59290
Iteration: 5377/59290
Iteration: 5378/59290
Iteration: 5379/59290
Iteration: 5380/59290
Iteration: 5381/59290
Iteration: 5382/59290
Iteration: 5383/59290
Iteration: 5384/59290
Iteration: 5385/59290
Iteration: 5386/59290
Iteration: 5387/59290
Iteration: 5388/59290
Iteration: 5389/59290
Iteration: 5390/59290
Iteration: 5392/59290

  9%|▉         | 5391/59290 [04:50<40:56, 21.94it/s]

Iteration: 5393/59290
Iteration: 5394/59290
Iteration: 5395/59290
Iteration: 5396/59290
Iteration: 5397/59290
Iteration: 5398/59290
Iteration: 5399/59290
Iteration: 5400/59290

  9%|▉         | 5399/59290 [04:50<43:16, 20.76it/s]

Iteration: 5401/59290
Iteration: 5402/59290
Iteration: 5403/59290
Iteration: 5404/59290
Iteration: 5405/59290
Iteration: 5406/59290
Iteration: 5407/59290
Iteration: 5408/59290
Iteration: 5409/59290
Iteration: 5410/59290
Iteration: 5411/59290
Iteration: 5412/59290
Iteration: 5413/59290
Iteration: 5414/59290
Iteration: 5415/59290
Iteration: 5416/59290
Iteration: 5417/59290
Iteration: 5418/59290
Iteration: 5419/59290
Iteration: 5420/59290
Iteration: 5421/59290
Iteration: 5422/59290
Iteration: 5423/59290
Iteration: 5424/59290

  9%|▉         | 5423/59290 [04:50<33:09, 27.07it/s]

Iteration: 5425/59290
Iteration: 5426/59290
Iteration: 5427/59290
Iteration: 5428/59290
Iteration: 5429/59290
Iteration: 5430/59290
Iteration: 5431/59290
Iteration: 5432/59290
Iteration: 5433/59290
Iteration: 5434/59290
Iteration: 5435/59290
Iteration: 5436/59290
Iteration: 5437/59290
Iteration: 5438/59290
Iteration: 5439/59290
Iteration: 5440/59290
Iteration: 5441/59290
Iteration: 5442/59290
Iteration: 5443/59290
Iteration: 5444/59290
Iteration: 5445/59290
Iteration: 5446/59290
Iteration: 5447/59290
Iteration: 5448/59290

  9%|▉         | 5447/59290 [04:51<26:48, 33.47it/s]

Iteration: 5449/59290
Iteration: 5450/59290
Iteration: 5451/59290
Iteration: 5452/59290
Iteration: 5453/59290
Iteration: 5454/59290
Iteration: 5455/59290
Iteration: 5456/59290
Iteration: 5457/59290
Iteration: 5458/59290
Iteration: 5459/59290
Iteration: 5460/59290
Iteration: 5461/59290
Iteration: 5462/59290
Iteration: 5463/59290
Iteration: 5464/59290
Iteration: 5465/59290
Iteration: 5466/59290
Iteration: 5467/59290
Iteration: 5468/59290
Iteration: 5469/59290
Iteration: 5470/59290
Iteration: 5471/59290
Iteration: 5472/59290

  9%|▉         | 5471/59290 [04:51<22:48, 39.32it/s]

Iteration: 5473/59290
Iteration: 5474/59290
Iteration: 5475/59290
Iteration: 5476/59290
Iteration: 5477/59290
Iteration: 5478/59290
Iteration: 5479/59290
Iteration: 5480/59290
Iteration: 5481/59290
Iteration: 5482/59290
Iteration: 5483/59290
Iteration: 5484/59290
Iteration: 5485/59290
Iteration: 5486/59290
Iteration: 5487/59290
Iteration: 5488/59290
Iteration: 5489/59290
Iteration: 5490/59290
Iteration: 5491/59290
Iteration: 5492/59290
Iteration: 5493/59290
Iteration: 5494/59290
Iteration: 5495/59290
Iteration: 5496/59290

  9%|▉         | 5495/59290 [04:52<20:28, 43.78it/s]

Iteration: 5497/59290
Iteration: 5498/59290
Iteration: 5499/59290
Iteration: 5500/59290
Iteration: 5501/59290
Iteration: 5502/59290
Iteration: 5503/59290
Iteration: 5504/59290
Iteration: 5505/59290
Iteration: 5506/59290
Iteration: 5507/59290
Iteration: 5508/59290
Iteration: 5509/59290
Iteration: 5510/59290
Iteration: 5511/59290
Iteration: 5512/59290
Iteration: 5513/59290
Iteration: 5514/59290
Iteration: 5515/59290
Iteration: 5516/59290
Iteration: 5517/59290
Iteration: 5518/59290
Iteration: 5519/59290
Iteration: 5520/59290

  9%|▉         | 5519/59290 [04:53<27:31, 32.55it/s]

Iteration: 5521/59290
Iteration: 5522/59290
Iteration: 5523/59290
Iteration: 5524/59290
Iteration: 5525/59290
Iteration: 5526/59290
Iteration: 5527/59290
Iteration: 5528/59290
Iteration: 5529/59290
Iteration: 5530/59290
Iteration: 5531/59290
Iteration: 5532/59290
Iteration: 5533/59290
Iteration: 5534/59290
Iteration: 5535/59290
Iteration: 5536/59290
Iteration: 5537/59290
Iteration: 5538/59290
Iteration: 5539/59290
Iteration: 5540/59290
Iteration: 5541/59290
Iteration: 5542/59290
Iteration: 5543/59290
Iteration: 5544/59290

  9%|▉         | 5543/59290 [04:55<39:40, 22.58it/s]

Iteration: 5545/59290
Iteration: 5546/59290
Iteration: 5547/59290
Iteration: 5548/59290
Iteration: 5549/59290
Iteration: 5550/59290
Iteration: 5551/59290
Iteration: 5552/59290
Iteration: 5553/59290
Iteration: 5554/59290
Iteration: 5555/59290
Iteration: 5556/59290
Iteration: 5557/59290
Iteration: 5558/59290
Iteration: 5559/59290
Iteration: 5560/59290
Iteration: 5561/59290
Iteration: 5562/59290
Iteration: 5563/59290
Iteration: 5564/59290
Iteration: 5565/59290
Iteration: 5566/59290
Iteration: 5567/59290
Iteration: 5568/59290

  9%|▉         | 5567/59290 [04:55<33:41, 26.57it/s]

Iteration: 5569/59290
Iteration: 5570/59290
Iteration: 5571/59290
Iteration: 5572/59290
Iteration: 5573/59290
Iteration: 5574/59290
Iteration: 5575/59290
Iteration: 5576/59290
Iteration: 5577/59290
Iteration: 5578/59290
Iteration: 5579/59290
Iteration: 5580/59290
Iteration: 5581/59290
Iteration: 5582/59290
Iteration: 5583/59290
Iteration: 5584/59290
Iteration: 5585/59290
Iteration: 5586/59290
Iteration: 5587/59290
Iteration: 5588/59290
Iteration: 5589/59290
Iteration: 5590/59290
Iteration: 5591/59290
Iteration: 5592/59290

  9%|▉         | 5591/59290 [04:55<27:39, 32.37it/s]

Iteration: 5593/59290
Iteration: 5594/59290
Iteration: 5595/59290
Iteration: 5596/59290
Iteration: 5597/59290
Iteration: 5598/59290
Iteration: 5599/59290
Iteration: 5600/59290
Iteration: 5601/59290
Iteration: 5602/59290
Iteration: 5603/59290
Iteration: 5604/59290
Iteration: 5605/59290
Iteration: 5606/59290
Iteration: 5607/59290
Iteration: 5608/59290
Iteration: 5609/59290
Iteration: 5610/59290
Iteration: 5611/59290
Iteration: 5612/59290
Iteration: 5613/59290
Iteration: 5614/59290
Iteration: 5615/59290
Iteration: 5616/59290

  9%|▉         | 5615/59290 [04:56<23:32, 38.00it/s]

Iteration: 5617/59290
Iteration: 5618/59290
Iteration: 5619/59290
Iteration: 5620/59290
Iteration: 5621/59290
Iteration: 5622/59290
Iteration: 5623/59290
Iteration: 5624/59290
Iteration: 5625/59290
Iteration: 5626/59290
Iteration: 5627/59290
Iteration: 5628/59290
Iteration: 5629/59290
Iteration: 5630/59290
Iteration: 5631/59290
Iteration: 5632/59290
Iteration: 5633/59290
Iteration: 5634/59290
Iteration: 5635/59290
Iteration: 5636/59290
Iteration: 5637/59290
Iteration: 5638/59290
Iteration: 5639/59290
Iteration: 5640/59290

 10%|▉         | 5639/59290 [04:56<20:47, 43.00it/s]

Iteration: 5641/59290
Iteration: 5642/59290
Iteration: 5643/59290
Iteration: 5644/59290
Iteration: 5645/59290
Iteration: 5646/59290
Iteration: 5647/59290
Iteration: 5648/59290
Iteration: 5649/59290
Iteration: 5650/59290
Iteration: 5651/59290
Iteration: 5652/59290
Iteration: 5653/59290
Iteration: 5654/59290
Iteration: 5655/59290
Iteration: 5656/59290
Iteration: 5657/59290
Iteration: 5658/59290
Iteration: 5659/59290
Iteration: 5660/59290
Iteration: 5661/59290
Iteration: 5662/59290
Iteration: 5663/59290
Iteration: 5664/59290

 10%|▉         | 5663/59290 [04:57<18:51, 47.42it/s]

Iteration: 5665/59290
Iteration: 5666/59290
Iteration: 5667/59290
Iteration: 5668/59290
Iteration: 5669/59290
Iteration: 5670/59290
Iteration: 5671/59290
Iteration: 5672/59290
Iteration: 5673/59290
Iteration: 5674/59290
Iteration: 5675/59290
Iteration: 5676/59290
Iteration: 5677/59290
Iteration: 5678/59290
Iteration: 5679/59290
Iteration: 5680/59290
Iteration: 5681/59290
Iteration: 5682/59290
Iteration: 5683/59290
Iteration: 5684/59290
Iteration: 5685/59290
Iteration: 5686/59290
Iteration: 5687/59290
Iteration: 5688/59290

 10%|▉         | 5687/59290 [04:57<17:24, 51.32it/s]

Iteration: 5689/59290
Iteration: 5690/59290
Iteration: 5691/59290
Iteration: 5692/59290
Iteration: 5693/59290
Iteration: 5694/59290
Iteration: 5695/59290
Iteration: 5696/59290
Iteration: 5697/59290
Iteration: 5698/59290
Iteration: 5699/59290
Iteration: 5700/59290
Iteration: 5701/59290
Iteration: 5702/59290
Iteration: 5703/59290
Iteration: 5704/59290
Iteration: 5705/59290
Iteration: 5706/59290
Iteration: 5707/59290
Iteration: 5708/59290
Iteration: 5709/59290
Iteration: 5710/59290
Iteration: 5711/59290
Iteration: 5712/59290

 10%|▉         | 5711/59290 [04:57<16:21, 54.57it/s]

Iteration: 5713/59290
Iteration: 5714/59290
Iteration: 5715/59290
Iteration: 5716/59290
Iteration: 5717/59290
Iteration: 5718/59290
Iteration: 5719/59290
Iteration: 5720/59290
Iteration: 5721/59290
Iteration: 5722/59290
Iteration: 5723/59290
Iteration: 5724/59290
Iteration: 5725/59290
Iteration: 5726/59290
Iteration: 5727/59290
Iteration: 5728/59290
Iteration: 5729/59290
Iteration: 5730/59290
Iteration: 5731/59290
Iteration: 5732/59290
Iteration: 5733/59290
Iteration: 5734/59290
Iteration: 5735/59290
Iteration: 5736/59290

 10%|▉         | 5735/59290 [04:59<28:25, 31.39it/s]

Iteration: 5737/59290
Iteration: 5738/59290
Iteration: 5739/59290
Iteration: 5740/59290
Iteration: 5741/59290
Iteration: 5742/59290
Iteration: 5743/59290
Iteration: 5744/59290
Iteration: 5745/59290
Iteration: 5746/59290
Iteration: 5747/59290
Iteration: 5748/59290
Iteration: 5749/59290
Iteration: 5750/59290
Iteration: 5751/59290
Iteration: 5752/59290
Iteration: 5753/59290
Iteration: 5754/59290
Iteration: 5755/59290
Iteration: 5756/59290
Iteration: 5757/59290
Iteration: 5758/59290
Iteration: 5759/59290
Iteration: 5760/59290

 10%|▉         | 5759/59290 [05:01<41:43, 21.38it/s]

Iteration: 5761/59290
Iteration: 5762/59290
Iteration: 5763/59290
Iteration: 5764/59290
Iteration: 5765/59290
Iteration: 5766/59290
Iteration: 5767/59290
Iteration: 5768/59290
Iteration: 5769/59290
Iteration: 5770/59290
Iteration: 5771/59290
Iteration: 5772/59290
Iteration: 5773/59290
Iteration: 5774/59290
Iteration: 5775/59290
Iteration: 5776/59290
Iteration: 5777/59290
Iteration: 5778/59290
Iteration: 5779/59290
Iteration: 5780/59290
Iteration: 5781/59290
Iteration: 5782/59290
Iteration: 5783/59290
Iteration: 5784/59290

 10%|▉         | 5783/59290 [05:02<37:06, 24.03it/s]

Iteration: 5785/59290
Iteration: 5786/59290
Iteration: 5787/59290
Iteration: 5788/59290
Iteration: 5789/59290
Iteration: 5790/59290
Iteration: 5791/59290
Iteration: 5792/59290
Iteration: 5793/59290
Iteration: 5794/59290
Iteration: 5795/59290
Iteration: 5796/59290
Iteration: 5797/59290
Iteration: 5798/59290
Iteration: 5799/59290
Iteration: 5800/59290
Iteration: 5801/59290
Iteration: 5802/59290
Iteration: 5803/59290
Iteration: 5804/59290
Iteration: 5805/59290
Iteration: 5806/59290
Iteration: 5807/59290
Iteration: 5808/59290

 10%|▉         | 5807/59290 [05:02<30:16, 29.45it/s]

Iteration: 5809/59290
Iteration: 5810/59290
Iteration: 5811/59290
Iteration: 5812/59290
Iteration: 5813/59290
Iteration: 5814/59290
Iteration: 5815/59290
Iteration: 5816/59290
Iteration: 5817/59290
Iteration: 5818/59290
Iteration: 5819/59290
Iteration: 5820/59290
Iteration: 5821/59290
Iteration: 5822/59290
Iteration: 5823/59290
Iteration: 5824/59290
Iteration: 5825/59290
Iteration: 5826/59290
Iteration: 5827/59290
Iteration: 5828/59290
Iteration: 5829/59290
Iteration: 5830/59290
Iteration: 5831/59290
Iteration: 5832/59290

 10%|▉         | 5831/59290 [05:02<25:19, 35.17it/s]

Iteration: 5833/59290
Iteration: 5834/59290
Iteration: 5835/59290
Iteration: 5836/59290
Iteration: 5837/59290
Iteration: 5838/59290
Iteration: 5839/59290
Iteration: 5840/59290
Iteration: 5841/59290
Iteration: 5842/59290
Iteration: 5843/59290
Iteration: 5844/59290
Iteration: 5845/59290
Iteration: 5846/59290
Iteration: 5847/59290
Iteration: 5848/59290
Iteration: 5849/59290
Iteration: 5850/59290
Iteration: 5851/59290
Iteration: 5852/59290
Iteration: 5853/59290
Iteration: 5854/59290
Iteration: 5855/59290
Iteration: 5856/59290

 10%|▉         | 5855/59290 [05:03<21:54, 40.65it/s]

Iteration: 5857/59290
Iteration: 5858/59290
Iteration: 5859/59290
Iteration: 5860/59290
Iteration: 5861/59290
Iteration: 5862/59290
Iteration: 5863/59290
Iteration: 5864/59290
Iteration: 5865/59290
Iteration: 5866/59290
Iteration: 5867/59290
Iteration: 5868/59290
Iteration: 5869/59290
Iteration: 5870/59290
Iteration: 5871/59290
Iteration: 5872/59290
Iteration: 5873/59290
Iteration: 5874/59290
Iteration: 5875/59290
Iteration: 5876/59290
Iteration: 5877/59290
Iteration: 5878/59290
Iteration: 5879/59290
Iteration: 5880/59290

 10%|▉         | 5879/59290 [05:36<6:23:51,  2.32it/s]

Iteration: 5881/59290
Iteration: 5882/59290
Iteration: 5883/59290
Iteration: 5884/59290
Iteration: 5885/59290
Iteration: 5886/59290
Iteration: 5887/59290
Iteration: 5888/59290
Iteration: 5889/59290
Iteration: 5890/59290
Iteration: 5891/59290
Iteration: 5892/59290
Iteration: 5893/59290
Iteration: 5894/59290
Iteration: 5895/59290
Iteration: 5896/59290
Iteration: 5897/59290
Iteration: 5898/59290
Iteration: 5899/59290
Iteration: 5900/59290
Iteration: 5901/59290
Iteration: 5902/59290
Iteration: 5903/59290
Iteration: 5904/59290

 10%|▉         | 5903/59290 [05:36<4:34:03,  3.25it/s]

Iteration: 5905/59290
Iteration: 5906/59290
Iteration: 5907/59290
Iteration: 5908/59290
Iteration: 5909/59290
Iteration: 5910/59290
Iteration: 5911/59290
Iteration: 5912/59290
Iteration: 5913/59290
Iteration: 5914/59290
Iteration: 5915/59290
Iteration: 5916/59290
Iteration: 5917/59290
Iteration: 5918/59290
Iteration: 5919/59290
Iteration: 5920/59290
Iteration: 5921/59290
Iteration: 5922/59290
Iteration: 5923/59290
Iteration: 5924/59290
Iteration: 5925/59290
Iteration: 5926/59290
Iteration: 5927/59290
Iteration: 5928/59290

 10%|▉         | 5927/59290 [05:37<3:15:58,  4.54it/s]

Iteration: 5929/59290
Iteration: 5930/59290
Iteration: 5931/59290
Iteration: 5932/59290
Iteration: 5933/59290
Iteration: 5934/59290
Iteration: 5935/59290
Iteration: 5936/59290
Iteration: 5937/59290
Iteration: 5938/59290
Iteration: 5939/59290
Iteration: 5940/59290
Iteration: 5941/59290
Iteration: 5942/59290
Iteration: 5943/59290
Iteration: 5944/59290
Iteration: 5945/59290
Iteration: 5946/59290
Iteration: 5947/59290
Iteration: 5948/59290
Iteration: 5949/59290
Iteration: 5950/59290
Iteration: 5951/59290
Iteration: 5952/59290

 10%|█         | 5951/59290 [05:37<2:21:38,  6.28it/s]

Iteration: 5953/59290
Iteration: 5954/59290
Iteration: 5955/59290
Iteration: 5956/59290
Iteration: 5957/59290
Iteration: 5958/59290
Iteration: 5959/59290
Iteration: 5960/59290
Iteration: 5961/59290
Iteration: 5962/59290
Iteration: 5963/59290
Iteration: 5964/59290
Iteration: 5965/59290
Iteration: 5966/59290
Iteration: 5967/59290
Iteration: 5968/59290
Iteration: 5969/59290
Iteration: 5970/59290
Iteration: 5971/59290
Iteration: 5972/59290
Iteration: 5973/59290
Iteration: 5974/59290
Iteration: 5975/59290
Iteration: 5976/59290

 10%|█         | 5975/59290 [05:37<1:43:12,  8.61it/s]

Iteration: 5977/59290
Iteration: 5978/59290
Iteration: 5979/59290
Iteration: 5980/59290
Iteration: 5981/59290
Iteration: 5982/59290
Iteration: 5983/59290
Iteration: 5984/59290
Iteration: 5985/59290
Iteration: 5986/59290
Iteration: 5987/59290
Iteration: 5988/59290
Iteration: 5989/59290
Iteration: 5990/59290
Iteration: 5991/59290
Iteration: 5992/59290
Iteration: 5993/59290
Iteration: 5994/59290
Iteration: 5995/59290
Iteration: 5996/59290
Iteration: 5997/59290
Iteration: 5998/59290
Iteration: 5999/59290
Iteration: 6000/59290

 10%|█         | 5999/59290 [05:38<1:16:21, 11.63it/s]

Iteration: 6001/59290
Iteration: 6002/59290
Iteration: 6003/59290
Iteration: 6004/59290
Iteration: 6005/59290
Iteration: 6006/59290
Iteration: 6007/59290
Iteration: 6008/59290
Iteration: 6009/59290
Iteration: 6010/59290
Iteration: 6011/59290
Iteration: 6012/59290
Iteration: 6013/59290
Iteration: 6014/59290
Iteration: 6015/59290
Iteration: 6016/59290
Iteration: 6017/59290
Iteration: 6018/59290
Iteration: 6019/59290
Iteration: 6020/59290
Iteration: 6021/59290
Iteration: 6022/59290
Iteration: 6023/59290
Iteration: 6024/59290

 10%|█         | 6023/59290 [05:38<57:35, 15.42it/s]

Iteration: 6025/59290
Iteration: 6026/59290
Iteration: 6027/59290
Iteration: 6028/59290
Iteration: 6029/59290
Iteration: 6030/59290
Iteration: 6031/59290
Iteration: 6032/59290
Iteration: 6033/59290
Iteration: 6034/59290
Iteration: 6035/59290
Iteration: 6036/59290
Iteration: 6037/59290
Iteration: 6038/59290
Iteration: 6039/59290
Iteration: 6040/59290
Iteration: 6041/59290
Iteration: 6042/59290
Iteration: 6043/59290
Iteration: 6044/59290
Iteration: 6045/59290
Iteration: 6046/59290
Iteration: 6047/59290
Iteration: 6048/59290

 10%|█         | 6047/59290 [05:39<44:29, 19.95it/s]

Iteration: 6049/59290
Iteration: 6050/59290
Iteration: 6051/59290
Iteration: 6052/59290
Iteration: 6053/59290
Iteration: 6054/59290
Iteration: 6055/59290
Iteration: 6056/59290
Iteration: 6057/59290
Iteration: 6058/59290
Iteration: 6059/59290
Iteration: 6060/59290
Iteration: 6061/59290
Iteration: 6062/59290
Iteration: 6063/59290
Iteration: 6064/59290
Iteration: 6065/59290
Iteration: 6066/59290
Iteration: 6067/59290
Iteration: 6068/59290
Iteration: 6069/59290
Iteration: 6070/59290
Iteration: 6071/59290
Iteration: 6072/59290

 10%|█         | 6071/59290 [05:40<45:45, 19.38it/s]

Iteration: 6073/59290
Iteration: 6074/59290
Iteration: 6075/59290
Iteration: 6076/59290
Iteration: 6077/59290
Iteration: 6078/59290
Iteration: 6079/59290
Iteration: 6080/59290
Iteration: 6081/59290
Iteration: 6082/59290
Iteration: 6083/59290
Iteration: 6084/59290
Iteration: 6085/59290
Iteration: 6086/59290
Iteration: 6087/59290
Iteration: 6088/59290
Iteration: 6089/59290
Iteration: 6090/59290
Iteration: 6091/59290
Iteration: 6092/59290
Iteration: 6093/59290
Iteration: 6094/59290
Iteration: 6095/59290
Iteration: 6096/59290

 10%|█         | 6095/59290 [05:42<53:09, 16.68it/s]

Iteration: 6097/59290
Iteration: 6098/59290
Iteration: 6099/59290
Iteration: 6100/59290
Iteration: 6101/59290
Iteration: 6102/59290
Iteration: 6103/59290
Iteration: 6104/59290
Iteration: 6105/59290
Iteration: 6106/59290
Iteration: 6107/59290
Iteration: 6108/59290
Iteration: 6109/59290
Iteration: 6110/59290
Iteration: 6111/59290
Iteration: 6112/59290
Iteration: 6113/59290
Iteration: 6114/59290
Iteration: 6115/59290
Iteration: 6116/59290
Iteration: 6117/59290
Iteration: 6118/59290
Iteration: 6119/59290
Iteration: 6120/59290

 10%|█         | 6119/59290 [05:43<46:10, 19.19it/s]

Iteration: 6121/59290
Iteration: 6122/59290
Iteration: 6123/59290
Iteration: 6124/59290
Iteration: 6125/59290
Iteration: 6126/59290
Iteration: 6127/59290
Iteration: 6128/59290
Iteration: 6129/59290
Iteration: 6130/59290
Iteration: 6131/59290
Iteration: 6132/59290
Iteration: 6133/59290
Iteration: 6134/59290
Iteration: 6135/59290
Iteration: 6136/59290
Iteration: 6137/59290
Iteration: 6138/59290
Iteration: 6139/59290
Iteration: 6140/59290
Iteration: 6141/59290
Iteration: 6142/59290
Iteration: 6143/59290
Iteration: 6144/59290

 10%|█         | 6143/59290 [05:43<36:39, 24.17it/s]

Iteration: 6145/59290
Iteration: 6146/59290
Iteration: 6147/59290
Iteration: 6148/59290
Iteration: 6149/59290
Iteration: 6150/59290
Iteration: 6151/59290
Iteration: 6152/59290
Iteration: 6153/59290
Iteration: 6154/59290
Iteration: 6155/59290
Iteration: 6156/59290
Iteration: 6157/59290
Iteration: 6158/59290
Iteration: 6159/59290
Iteration: 6160/59290
Iteration: 6161/59290
Iteration: 6162/59290
Iteration: 6163/59290
Iteration: 6164/59290
Iteration: 6165/59290
Iteration: 6166/59290
Iteration: 6167/59290
Iteration: 6168/59290

 10%|█         | 6167/59290 [05:43<30:04, 29.43it/s]

Iteration: 6169/59290
Iteration: 6170/59290
Iteration: 6171/59290
Iteration: 6172/59290
Iteration: 6173/59290
Iteration: 6174/59290
Iteration: 6175/59290
Iteration: 6176/59290
Iteration: 6177/59290
Iteration: 6178/59290
Iteration: 6179/59290
Iteration: 6180/59290
Iteration: 6181/59290
Iteration: 6182/59290
Iteration: 6183/59290
Iteration: 6184/59290
Iteration: 6185/59290
Iteration: 6186/59290
Iteration: 6187/59290
Iteration: 6188/59290
Iteration: 6189/59290
Iteration: 6190/59290
Iteration: 6191/59290
Iteration: 6192/59290

 10%|█         | 6191/59290 [05:44<25:13, 35.08it/s]

Iteration: 6193/59290
Iteration: 6194/59290
Iteration: 6195/59290
Iteration: 6196/59290
Iteration: 6197/59290
Iteration: 6198/59290
Iteration: 6199/59290
Iteration: 6200/59290
Iteration: 6201/59290
Iteration: 6202/59290
Iteration: 6203/59290
Iteration: 6204/59290
Iteration: 6205/59290
Iteration: 6206/59290
Iteration: 6207/59290
Iteration: 6208/59290
Iteration: 6209/59290
Iteration: 6210/59290
Iteration: 6211/59290
Iteration: 6212/59290
Iteration: 6213/59290
Iteration: 6214/59290
Iteration: 6215/59290
Iteration: 6216/59290

 10%|█         | 6215/59290 [05:44<21:46, 40.63it/s]

Iteration: 6217/59290
Iteration: 6218/59290
Iteration: 6219/59290
Iteration: 6220/59290
Iteration: 6221/59290
Iteration: 6222/59290
Iteration: 6223/59290
Iteration: 6224/59290
Iteration: 6225/59290
Iteration: 6226/59290
Iteration: 6227/59290
Iteration: 6228/59290
Iteration: 6229/59290
Iteration: 6230/59290
Iteration: 6231/59290
Iteration: 6232/59290
Iteration: 6233/59290
Iteration: 6234/59290
Iteration: 6235/59290
Iteration: 6236/59290
Iteration: 6237/59290
Iteration: 6238/59290
Iteration: 6239/59290
Iteration: 6240/59290

 11%|█         | 6239/59290 [05:45<19:20, 45.73it/s]

Iteration: 6241/59290
Iteration: 6242/59290
Iteration: 6243/59290
Iteration: 6244/59290
Iteration: 6245/59290
Iteration: 6246/59290
Iteration: 6247/59290
Iteration: 6248/59290
Iteration: 6249/59290
Iteration: 6250/59290
Iteration: 6251/59290
Iteration: 6252/59290
Iteration: 6253/59290
Iteration: 6254/59290
Iteration: 6255/59290
Iteration: 6256/59290
Iteration: 6257/59290
Iteration: 6258/59290
Iteration: 6259/59290
Iteration: 6260/59290
Iteration: 6261/59290
Iteration: 6262/59290
Iteration: 6263/59290
Iteration: 6264/59290

 11%|█         | 6263/59290 [05:45<17:39, 50.03it/s]

Iteration: 6265/59290
Iteration: 6266/59290
Iteration: 6267/59290
Iteration: 6268/59290
Iteration: 6269/59290
Iteration: 6270/59290
Iteration: 6271/59290
Iteration: 6272/59290
Iteration: 6273/59290
Iteration: 6274/59290
Iteration: 6275/59290
Iteration: 6276/59290
Iteration: 6277/59290
Iteration: 6278/59290
Iteration: 6279/59290
Iteration: 6280/59290
Iteration: 6281/59290
Iteration: 6282/59290
Iteration: 6283/59290
Iteration: 6284/59290
Iteration: 6285/59290
Iteration: 6286/59290
Iteration: 6287/59290
Iteration: 6288/59290

 11%|█         | 6287/59290 [05:45<16:25, 53.76it/s]

Iteration: 6289/59290
Iteration: 6290/59290
Iteration: 6291/59290
Iteration: 6292/59290
Iteration: 6293/59290
Iteration: 6294/59290
Iteration: 6295/59290
Iteration: 6296/59290
Iteration: 6297/59290
Iteration: 6298/59290
Iteration: 6299/59290
Iteration: 6300/59290
Iteration: 6301/59290
Iteration: 6302/59290
Iteration: 6303/59290
Iteration: 6304/59290
Iteration: 6305/59290
Iteration: 6306/59290
Iteration: 6307/59290
Iteration: 6308/59290
Iteration: 6309/59290
Iteration: 6310/59290
Iteration: 6311/59290
Iteration: 6312/59290

 11%|█         | 6311/59290 [05:46<15:44, 56.10it/s]

Iteration: 6313/59290
Iteration: 6314/59290
Iteration: 6315/59290
Iteration: 6316/59290
Iteration: 6317/59290
Iteration: 6318/59290
Iteration: 6319/59290
Iteration: 6320/59290
Iteration: 6321/59290
Iteration: 6322/59290
Iteration: 6323/59290
Iteration: 6324/59290
Iteration: 6325/59290
Iteration: 6326/59290
Iteration: 6327/59290
Iteration: 6328/59290
Iteration: 6329/59290
Iteration: 6330/59290
Iteration: 6331/59290
Iteration: 6332/59290
Iteration: 6333/59290
Iteration: 6334/59290
Iteration: 6335/59290
Iteration: 6336/59290

 11%|█         | 6335/59290 [05:46<15:57, 55.33it/s]

Iteration: 6337/59290
Iteration: 6338/59290
Iteration: 6339/59290
Iteration: 6340/59290
Iteration: 6341/59290
Iteration: 6342/59290
Iteration: 6343/59290
Iteration: 6344/59290
Iteration: 6345/59290
Iteration: 6346/59290
Iteration: 6347/59290
Iteration: 6348/59290
Iteration: 6349/59290
Iteration: 6350/59290
Iteration: 6351/59290
Iteration: 6352/59290
Iteration: 6353/59290
Iteration: 6354/59290
Iteration: 6355/59290
Iteration: 6356/59290
Iteration: 6357/59290
Iteration: 6358/59290
Iteration: 6359/59290
Iteration: 6360/59290

 11%|█         | 6359/59290 [05:47<25:22, 34.76it/s]

Iteration: 6361/59290
Iteration: 6362/59290
Iteration: 6363/59290
Iteration: 6364/59290
Iteration: 6365/59290
Iteration: 6366/59290
Iteration: 6367/59290
Iteration: 6368/59290
Iteration: 6369/59290
Iteration: 6370/59290
Iteration: 6371/59290
Iteration: 6372/59290
Iteration: 6373/59290
Iteration: 6374/59290
Iteration: 6375/59290
Iteration: 6376/59290
Iteration: 6377/59290
Iteration: 6378/59290
Iteration: 6379/59290
Iteration: 6380/59290
Iteration: 6381/59290
Iteration: 6382/59290
Iteration: 6383/59290
Iteration: 6384/59290

 11%|█         | 6383/59290 [05:49<39:36, 22.26it/s]

Iteration: 6385/59290
Iteration: 6386/59290
Iteration: 6387/59290
Iteration: 6388/59290
Iteration: 6389/59290
Iteration: 6390/59290
Iteration: 6391/59290
Iteration: 6392/59290
Iteration: 6393/59290
Iteration: 6394/59290
Iteration: 6395/59290
Iteration: 6396/59290
Iteration: 6397/59290
Iteration: 6398/59290
Iteration: 6399/59290
Iteration: 6400/59290
Iteration: 6401/59290
Iteration: 6402/59290
Iteration: 6403/59290
Iteration: 6404/59290
Iteration: 6405/59290
Iteration: 6406/59290
Iteration: 6407/59290
Iteration: 6408/59290

 11%|█         | 6407/59290 [05:50<34:13, 25.75it/s]

Iteration: 6409/59290
Iteration: 6410/59290
Iteration: 6411/59290
Iteration: 6412/59290
Iteration: 6413/59290
Iteration: 6414/59290
Iteration: 6415/59290
Iteration: 6416/59290
Iteration: 6417/59290
Iteration: 6418/59290
Iteration: 6419/59290
Iteration: 6420/59290
Iteration: 6421/59290
Iteration: 6422/59290
Iteration: 6423/59290
Iteration: 6424/59290
Iteration: 6425/59290
Iteration: 6426/59290
Iteration: 6427/59290
Iteration: 6428/59290
Iteration: 6429/59290
Iteration: 6430/59290
Iteration: 6431/59290
Iteration: 6432/59290

 11%|█         | 6431/59290 [05:50<27:58, 31.48it/s]

Iteration: 6433/59290
Iteration: 6434/59290
Iteration: 6435/59290
Iteration: 6436/59290
Iteration: 6437/59290
Iteration: 6438/59290
Iteration: 6439/59290
Iteration: 6440/59290
Iteration: 6441/59290
Iteration: 6442/59290
Iteration: 6443/59290
Iteration: 6444/59290
Iteration: 6445/59290
Iteration: 6446/59290
Iteration: 6447/59290
Iteration: 6448/59290
Iteration: 6449/59290
Iteration: 6450/59290
Iteration: 6451/59290
Iteration: 6452/59290
Iteration: 6453/59290
Iteration: 6454/59290
Iteration: 6455/59290
Iteration: 6456/59290

 11%|█         | 6455/59290 [05:51<23:43, 37.11it/s]

Iteration: 6457/59290
Iteration: 6458/59290
Iteration: 6459/59290
Iteration: 6460/59290
Iteration: 6461/59290
Iteration: 6462/59290
Iteration: 6463/59290
Iteration: 6464/59290
Iteration: 6465/59290
Iteration: 6466/59290
Iteration: 6467/59290
Iteration: 6468/59290
Iteration: 6469/59290
Iteration: 6470/59290
Iteration: 6471/59290
Iteration: 6472/59290
Iteration: 6473/59290
Iteration: 6474/59290
Iteration: 6475/59290
Iteration: 6476/59290
Iteration: 6477/59290
Iteration: 6478/59290
Iteration: 6479/59290
Iteration: 6480/59290

 11%|█         | 6479/59290 [05:51<20:44, 42.43it/s]

Iteration: 6481/59290
Iteration: 6482/59290
Iteration: 6483/59290
Iteration: 6484/59290
Iteration: 6485/59290
Iteration: 6486/59290
Iteration: 6487/59290
Iteration: 6488/59290
Iteration: 6489/59290
Iteration: 6490/59290
Iteration: 6491/59290
Iteration: 6492/59290
Iteration: 6493/59290
Iteration: 6494/59290
Iteration: 6495/59290
Iteration: 6496/59290
Iteration: 6497/59290
Iteration: 6498/59290
Iteration: 6499/59290
Iteration: 6500/59290
Iteration: 6501/59290
Iteration: 6502/59290
Iteration: 6503/59290
Iteration: 6504/59290

 11%|█         | 6503/59290 [05:51<18:34, 47.36it/s]

Iteration: 6505/59290
Iteration: 6506/59290
Iteration: 6507/59290
Iteration: 6508/59290
Iteration: 6509/59290
Iteration: 6510/59290
Iteration: 6511/59290
Iteration: 6512/59290
Iteration: 6513/59290
Iteration: 6514/59290
Iteration: 6515/59290
Iteration: 6516/59290
Iteration: 6517/59290
Iteration: 6518/59290
Iteration: 6519/59290
Iteration: 6520/59290
Iteration: 6521/59290
Iteration: 6522/59290
Iteration: 6523/59290
Iteration: 6524/59290
Iteration: 6525/59290
Iteration: 6526/59290
Iteration: 6527/59290
Iteration: 6528/59290

 11%|█         | 6527/59290 [05:52<17:27, 50.35it/s]

Iteration: 6529/59290
Iteration: 6530/59290
Iteration: 6531/59290
Iteration: 6532/59290
Iteration: 6533/59290
Iteration: 6534/59290
Iteration: 6535/59290
Iteration: 6536/59290
Iteration: 6537/59290
Iteration: 6538/59290
Iteration: 6539/59290
Iteration: 6540/59290
Iteration: 6541/59290
Iteration: 6542/59290
Iteration: 6543/59290
Iteration: 6544/59290
Iteration: 6545/59290
Iteration: 6546/59290
Iteration: 6547/59290
Iteration: 6548/59290
Iteration: 6549/59290
Iteration: 6550/59290
Iteration: 6551/59290
Iteration: 6552/59290

 11%|█         | 6551/59290 [05:53<29:02, 30.27it/s]

Iteration: 6553/59290
Iteration: 6554/59290
Iteration: 6555/59290
Iteration: 6556/59290
Iteration: 6557/59290
Iteration: 6558/59290
Iteration: 6559/59290
Iteration: 6560/59290
Iteration: 6561/59290
Iteration: 6562/59290
Iteration: 6563/59290
Iteration: 6564/59290
Iteration: 6565/59290
Iteration: 6566/59290
Iteration: 6567/59290
Iteration: 6568/59290
Iteration: 6569/59290
Iteration: 6570/59290
Iteration: 6571/59290
Iteration: 6572/59290
Iteration: 6573/59290
Iteration: 6574/59290
Iteration: 6575/59290
Iteration: 6576/59290

 11%|█         | 6575/59290 [05:56<46:01, 19.09it/s]

Iteration: 6577/59290
Iteration: 6578/59290
Iteration: 6579/59290
Iteration: 6580/59290
Iteration: 6581/59290
Iteration: 6582/59290
Iteration: 6583/59290
Iteration: 6584/59290
Iteration: 6585/59290
Iteration: 6586/59290
Iteration: 6587/59290
Iteration: 6588/59290
Iteration: 6589/59290
Iteration: 6590/59290
Iteration: 6591/59290
Iteration: 6592/59290
Iteration: 6593/59290
Iteration: 6594/59290
Iteration: 6595/59290
Iteration: 6596/59290
Iteration: 6597/59290
Iteration: 6598/59290
Iteration: 6599/59290
Iteration: 6600/59290

 11%|█         | 6599/59290 [05:56<36:15, 24.21it/s]

Iteration: 6601/59290
Iteration: 6602/59290
Iteration: 6603/59290
Iteration: 6604/59290
Iteration: 6605/59290
Iteration: 6606/59290
Iteration: 6607/59290
Iteration: 6608/59290
Iteration: 6609/59290
Iteration: 6610/59290
Iteration: 6611/59290
Iteration: 6612/59290
Iteration: 6613/59290
Iteration: 6614/59290
Iteration: 6615/59290
Iteration: 6616/59290
Iteration: 6617/59290
Iteration: 6618/59290
Iteration: 6619/59290
Iteration: 6620/59290
Iteration: 6621/59290
Iteration: 6622/59290
Iteration: 6623/59290
Iteration: 6624/59290

 11%|█         | 6623/59290 [05:57<29:29, 29.77it/s]

Iteration: 6625/59290
Iteration: 6626/59290
Iteration: 6627/59290
Iteration: 6628/59290
Iteration: 6629/59290
Iteration: 6630/59290
Iteration: 6631/59290
Iteration: 6632/59290
Iteration: 6633/59290
Iteration: 6634/59290
Iteration: 6635/59290
Iteration: 6636/59290
Iteration: 6637/59290
Iteration: 6638/59290
Iteration: 6639/59290
Iteration: 6640/59290
Iteration: 6641/59290
Iteration: 6642/59290
Iteration: 6643/59290
Iteration: 6644/59290
Iteration: 6645/59290
Iteration: 6646/59290
Iteration: 6647/59290
Iteration: 6648/59290

 11%|█         | 6647/59290 [05:57<24:49, 35.34it/s]

Iteration: 6649/59290
Iteration: 6650/59290
Iteration: 6651/59290
Iteration: 6652/59290
Iteration: 6653/59290
Iteration: 6654/59290
Iteration: 6655/59290
Iteration: 6656/59290
Iteration: 6657/59290
Iteration: 6658/59290
Iteration: 6659/59290
Iteration: 6660/59290
Iteration: 6661/59290
Iteration: 6662/59290
Iteration: 6663/59290
Iteration: 6664/59290
Iteration: 6665/59290
Iteration: 6666/59290
Iteration: 6667/59290
Iteration: 6668/59290
Iteration: 6669/59290
Iteration: 6670/59290
Iteration: 6671/59290
Iteration: 6672/59290

 11%|█▏        | 6671/59290 [05:57<21:36, 40.57it/s]

Iteration: 6673/59290
Iteration: 6674/59290
Iteration: 6675/59290
Iteration: 6676/59290
Iteration: 6677/59290
Iteration: 6678/59290
Iteration: 6679/59290
Iteration: 6680/59290
Iteration: 6681/59290
Iteration: 6682/59290
Iteration: 6683/59290
Iteration: 6684/59290
Iteration: 6685/59290
Iteration: 6686/59290
Iteration: 6687/59290
Iteration: 6688/59290
Iteration: 6689/59290
Iteration: 6690/59290
Iteration: 6691/59290
Iteration: 6692/59290
Iteration: 6693/59290
Iteration: 6694/59290
Iteration: 6695/59290
Iteration: 6696/59290

 11%|█▏        | 6695/59290 [05:58<19:44, 44.40it/s]

Iteration: 6697/59290
Iteration: 6698/59290
Iteration: 6699/59290
Iteration: 6700/59290
Iteration: 6701/59290
Iteration: 6702/59290
Iteration: 6703/59290
Iteration: 6704/59290
Iteration: 6705/59290
Iteration: 6706/59290
Iteration: 6707/59290
Iteration: 6708/59290
Iteration: 6709/59290
Iteration: 6710/59290
Iteration: 6711/59290
Iteration: 6712/59290
Iteration: 6713/59290
Iteration: 6714/59290
Iteration: 6715/59290
Iteration: 6716/59290
Iteration: 6717/59290
Iteration: 6718/59290
Iteration: 6719/59290
Iteration: 6720/59290

 11%|█▏        | 6719/59290 [05:58<17:57, 48.78it/s]

Iteration: 6721/59290
Iteration: 6722/59290
Iteration: 6723/59290
Iteration: 6724/59290
Iteration: 6725/59290
Iteration: 6726/59290
Iteration: 6727/59290
Iteration: 6728/59290
Iteration: 6729/59290
Iteration: 6730/59290
Iteration: 6731/59290
Iteration: 6732/59290
Iteration: 6733/59290
Iteration: 6734/59290
Iteration: 6735/59290
Iteration: 6736/59290
Iteration: 6737/59290
Iteration: 6738/59290
Iteration: 6739/59290
Iteration: 6740/59290
Iteration: 6741/59290
Iteration: 6742/59290
Iteration: 6743/59290
Iteration: 6744/59290

 11%|█▏        | 6743/59290 [06:00<29:33, 29.62it/s]

Iteration: 6745/59290
Iteration: 6746/59290
Iteration: 6747/59290
Iteration: 6748/59290
Iteration: 6749/59290
Iteration: 6750/59290
Iteration: 6751/59290
Iteration: 6752/59290
Iteration: 6753/59290
Iteration: 6754/59290
Iteration: 6755/59290
Iteration: 6756/59290
Iteration: 6757/59290
Iteration: 6758/59290
Iteration: 6759/59290
Iteration: 6760/59290
Iteration: 6761/59290
Iteration: 6762/59290
Iteration: 6763/59290
Iteration: 6764/59290
Iteration: 6765/59290
Iteration: 6766/59290
Iteration: 6767/59290
Iteration: 6768/59290

 11%|█▏        | 6767/59290 [06:02<46:33, 18.80it/s]

Iteration: 6769/59290
Iteration: 6770/59290
Iteration: 6771/59290
Iteration: 6772/59290
Iteration: 6773/59290
Iteration: 6774/59290
Iteration: 6775/59290
Iteration: 6776/59290
Iteration: 6777/59290
Iteration: 6778/59290
Iteration: 6779/59290
Iteration: 6780/59290
Iteration: 6781/59290
Iteration: 6782/59290
Iteration: 6783/59290
Iteration: 6784/59290
Iteration: 6785/59290
Iteration: 6786/59290
Iteration: 6787/59290
Iteration: 6788/59290
Iteration: 6789/59290
Iteration: 6790/59290
Iteration: 6791/59290
Iteration: 6792/59290

 11%|█▏        | 6791/59290 [06:02<36:47, 23.78it/s]

Iteration: 6793/59290
Iteration: 6794/59290
Iteration: 6795/59290
Iteration: 6796/59290
Iteration: 6797/59290
Iteration: 6798/59290
Iteration: 6799/59290
Iteration: 6800/59290
Iteration: 6801/59290
Iteration: 6802/59290
Iteration: 6803/59290
Iteration: 6804/59290
Iteration: 6805/59290
Iteration: 6806/59290
Iteration: 6807/59290
Iteration: 6808/59290
Iteration: 6809/59290
Iteration: 6810/59290
Iteration: 6811/59290
Iteration: 6812/59290
Iteration: 6813/59290
Iteration: 6814/59290
Iteration: 6815/59290
Iteration: 6816/59290

 11%|█▏        | 6815/59290 [06:03<30:03, 29.10it/s]

Iteration: 6817/59290
Iteration: 6818/59290
Iteration: 6819/59290
Iteration: 6820/59290
Iteration: 6821/59290
Iteration: 6822/59290
Iteration: 6823/59290
Iteration: 6824/59290
Iteration: 6825/59290
Iteration: 6826/59290
Iteration: 6827/59290
Iteration: 6828/59290
Iteration: 6829/59290
Iteration: 6830/59290
Iteration: 6831/59290
Iteration: 6832/59290
Iteration: 6833/59290
Iteration: 6834/59290
Iteration: 6835/59290
Iteration: 6836/59290
Iteration: 6837/59290
Iteration: 6838/59290
Iteration: 6839/59290
Iteration: 6840/59290

 12%|█▏        | 6839/59290 [06:03<25:13, 34.65it/s]

Iteration: 6841/59290
Iteration: 6842/59290
Iteration: 6843/59290
Iteration: 6844/59290
Iteration: 6845/59290
Iteration: 6846/59290
Iteration: 6847/59290
Iteration: 6848/59290
Iteration: 6849/59290
Iteration: 6850/59290
Iteration: 6851/59290
Iteration: 6852/59290
Iteration: 6853/59290
Iteration: 6854/59290
Iteration: 6855/59290
Iteration: 6856/59290
Iteration: 6857/59290
Iteration: 6858/59290
Iteration: 6859/59290
Iteration: 6860/59290
Iteration: 6861/59290
Iteration: 6862/59290
Iteration: 6863/59290
Iteration: 6864/59290

 12%|█▏        | 6863/59290 [06:05<32:27, 26.91it/s]

Iteration: 6865/59290
Iteration: 6866/59290
Iteration: 6867/59290
Iteration: 6868/59290
Iteration: 6869/59290
Iteration: 6870/59290
Iteration: 6871/59290
Iteration: 6872/59290
Iteration: 6873/59290
Iteration: 6874/59290
Iteration: 6875/59290
Iteration: 6876/59290
Iteration: 6877/59290
Iteration: 6878/59290
Iteration: 6879/59290
Iteration: 6880/59290
Iteration: 6881/59290
Iteration: 6882/59290
Iteration: 6883/59290
Iteration: 6884/59290
Iteration: 6885/59290
Iteration: 6886/59290
Iteration: 6887/59290
Iteration: 6888/59290

 12%|█▏        | 6887/59290 [06:06<43:19, 20.16it/s]

Iteration: 6889/59290
Iteration: 6890/59290
Iteration: 6891/59290
Iteration: 6892/59290
Iteration: 6893/59290
Iteration: 6894/59290
Iteration: 6895/59290
Iteration: 6896/59290
Iteration: 6897/59290
Iteration: 6898/59290
Iteration: 6899/59290
Iteration: 6900/59290
Iteration: 6901/59290
Iteration: 6902/59290
Iteration: 6903/59290
Iteration: 6904/59290
Iteration: 6905/59290
Iteration: 6906/59290
Iteration: 6907/59290
Iteration: 6908/59290
Iteration: 6909/59290
Iteration: 6910/59290
Iteration: 6911/59290
Iteration: 6912/59290

 12%|█▏        | 6911/59290 [06:07<35:29, 24.60it/s]

Iteration: 6913/59290
Iteration: 6914/59290
Iteration: 6915/59290
Iteration: 6916/59290
Iteration: 6917/59290
Iteration: 6918/59290
Iteration: 6919/59290
Iteration: 6920/59290
Iteration: 6921/59290
Iteration: 6922/59290
Iteration: 6923/59290
Iteration: 6924/59290
Iteration: 6925/59290
Iteration: 6926/59290
Iteration: 6927/59290
Iteration: 6928/59290
Iteration: 6929/59290
Iteration: 6930/59290
Iteration: 6931/59290
Iteration: 6932/59290
Iteration: 6933/59290
Iteration: 6934/59290
Iteration: 6935/59290
Iteration: 6936/59290

 12%|█▏        | 6935/59290 [06:07<29:19, 29.76it/s]

Iteration: 6937/59290
Iteration: 6938/59290
Iteration: 6939/59290
Iteration: 6940/59290
Iteration: 6941/59290
Iteration: 6942/59290
Iteration: 6943/59290
Iteration: 6944/59290
Iteration: 6945/59290
Iteration: 6946/59290
Iteration: 6947/59290
Iteration: 6948/59290
Iteration: 6949/59290
Iteration: 6950/59290
Iteration: 6951/59290
Iteration: 6952/59290
Iteration: 6953/59290
Iteration: 6954/59290
Iteration: 6955/59290
Iteration: 6956/59290
Iteration: 6957/59290
Iteration: 6958/59290
Iteration: 6959/59290
Iteration: 6960/59290

 12%|█▏        | 6959/59290 [06:08<24:57, 34.95it/s]

Iteration: 6961/59290
Iteration: 6962/59290
Iteration: 6963/59290
Iteration: 6964/59290
Iteration: 6965/59290
Iteration: 6966/59290
Iteration: 6967/59290
Iteration: 6968/59290
Iteration: 6969/59290
Iteration: 6970/59290
Iteration: 6971/59290
Iteration: 6972/59290
Iteration: 6973/59290
Iteration: 6974/59290
Iteration: 6975/59290
Iteration: 6976/59290
Iteration: 6977/59290
Iteration: 6978/59290
Iteration: 6979/59290
Iteration: 6980/59290
Iteration: 6981/59290
Iteration: 6982/59290
Iteration: 6983/59290
Iteration: 6984/59290

 12%|█▏        | 6983/59290 [06:08<21:35, 40.37it/s]

Iteration: 6985/59290
Iteration: 6986/59290
Iteration: 6987/59290
Iteration: 6988/59290
Iteration: 6989/59290
Iteration: 6990/59290
Iteration: 6991/59290
Iteration: 6992/59290
Iteration: 6993/59290
Iteration: 6994/59290
Iteration: 6995/59290
Iteration: 6996/59290
Iteration: 6997/59290
Iteration: 6998/59290
Iteration: 6999/59290
Iteration: 7000/59290
Iteration: 7001/59290
Iteration: 7002/59290
Iteration: 7003/59290
Iteration: 7004/59290
Iteration: 7005/59290
Iteration: 7006/59290
Iteration: 7007/59290
Iteration: 7008/59290

 12%|█▏        | 7007/59290 [06:08<19:13, 45.33it/s]

Iteration: 7009/59290
Iteration: 7010/59290
Iteration: 7011/59290
Iteration: 7012/59290
Iteration: 7013/59290
Iteration: 7014/59290
Iteration: 7015/59290
Iteration: 7016/59290
Iteration: 7017/59290
Iteration: 7018/59290
Iteration: 7019/59290
Iteration: 7020/59290
Iteration: 7021/59290
Iteration: 7022/59290
Iteration: 7023/59290
Iteration: 7024/59290
Iteration: 7025/59290
Iteration: 7026/59290
Iteration: 7027/59290
Iteration: 7028/59290
Iteration: 7029/59290
Iteration: 7030/59290
Iteration: 7031/59290
Iteration: 7032/59290

 12%|█▏        | 7031/59290 [06:09<17:30, 49.73it/s]

Iteration: 7033/59290
Iteration: 7034/59290
Iteration: 7035/59290
Iteration: 7036/59290
Iteration: 7037/59290
Iteration: 7038/59290
Iteration: 7039/59290
Iteration: 7040/59290
Iteration: 7041/59290
Iteration: 7042/59290
Iteration: 7043/59290
Iteration: 7044/59290
Iteration: 7045/59290
Iteration: 7046/59290
Iteration: 7047/59290
Iteration: 7048/59290
Iteration: 7049/59290
Iteration: 7050/59290
Iteration: 7051/59290
Iteration: 7052/59290
Iteration: 7053/59290
Iteration: 7054/59290
Iteration: 7055/59290
Iteration: 7056/59290

 12%|█▏        | 7055/59290 [06:10<26:47, 32.50it/s]

Iteration: 7057/59290
Iteration: 7058/59290
Iteration: 7059/59290
Iteration: 7060/59290
Iteration: 7061/59290
Iteration: 7062/59290
Iteration: 7063/59290
Iteration: 7064/59290
Iteration: 7065/59290
Iteration: 7066/59290
Iteration: 7067/59290
Iteration: 7068/59290
Iteration: 7069/59290
Iteration: 7070/59290
Iteration: 7071/59290
Iteration: 7072/59290
Iteration: 7073/59290
Iteration: 7074/59290
Iteration: 7075/59290
Iteration: 7076/59290
Iteration: 7077/59290
Iteration: 7078/59290
Iteration: 7079/59290
Iteration: 7080/59290

 12%|█▏        | 7079/59290 [06:12<40:10, 21.66it/s]

Iteration: 7081/59290
Iteration: 7082/59290
Iteration: 7083/59290
Iteration: 7084/59290
Iteration: 7085/59290
Iteration: 7086/59290
Iteration: 7087/59290
Iteration: 7088/59290
Iteration: 7089/59290
Iteration: 7090/59290
Iteration: 7091/59290
Iteration: 7092/59290
Iteration: 7093/59290
Iteration: 7094/59290
Iteration: 7095/59290
Iteration: 7096/59290
Iteration: 7097/59290
Iteration: 7098/59290
Iteration: 7099/59290
Iteration: 7100/59290
Iteration: 7101/59290
Iteration: 7102/59290
Iteration: 7103/59290
Iteration: 7104/59290

 12%|█▏        | 7103/59290 [06:13<36:12, 24.02it/s]

Iteration: 7105/59290
Iteration: 7106/59290
Iteration: 7107/59290
Iteration: 7108/59290
Iteration: 7109/59290
Iteration: 7110/59290
Iteration: 7111/59290
Iteration: 7112/59290
Iteration: 7113/59290
Iteration: 7114/59290
Iteration: 7115/59290
Iteration: 7116/59290
Iteration: 7117/59290
Iteration: 7118/59290
Iteration: 7119/59290
Iteration: 7120/59290
Iteration: 7121/59290
Iteration: 7122/59290
Iteration: 7123/59290
Iteration: 7124/59290
Iteration: 7125/59290
Iteration: 7126/59290
Iteration: 7127/59290
Iteration: 7128/59290

 12%|█▏        | 7127/59290 [06:13<29:37, 29.34it/s]

Iteration: 7129/59290
Iteration: 7130/59290
Iteration: 7131/59290
Iteration: 7132/59290
Iteration: 7133/59290
Iteration: 7134/59290
Iteration: 7135/59290
Iteration: 7136/59290
Iteration: 7137/59290
Iteration: 7138/59290
Iteration: 7139/59290
Iteration: 7140/59290
Iteration: 7141/59290
Iteration: 7142/59290
Iteration: 7143/59290
Iteration: 7144/59290
Iteration: 7145/59290
Iteration: 7146/59290
Iteration: 7147/59290
Iteration: 7148/59290
Iteration: 7149/59290
Iteration: 7150/59290
Iteration: 7151/59290
Iteration: 7152/59290

 12%|█▏        | 7151/59290 [06:14<24:52, 34.93it/s]

Iteration: 7153/59290
Iteration: 7154/59290
Iteration: 7155/59290
Iteration: 7156/59290
Iteration: 7157/59290
Iteration: 7158/59290
Iteration: 7159/59290
Iteration: 7160/59290
Iteration: 7161/59290
Iteration: 7162/59290
Iteration: 7163/59290
Iteration: 7164/59290
Iteration: 7165/59290
Iteration: 7166/59290
Iteration: 7167/59290
Iteration: 7168/59290
Iteration: 7169/59290
Iteration: 7170/59290
Iteration: 7171/59290
Iteration: 7172/59290
Iteration: 7173/59290
Iteration: 7174/59290
Iteration: 7175/59290
Iteration: 7176/59290

 12%|█▏        | 7175/59290 [06:14<21:50, 39.78it/s]

Iteration: 7177/59290
Iteration: 7178/59290
Iteration: 7179/59290
Iteration: 7180/59290
Iteration: 7181/59290
Iteration: 7182/59290
Iteration: 7183/59290
Iteration: 7184/59290
Iteration: 7185/59290
Iteration: 7186/59290
Iteration: 7187/59290
Iteration: 7188/59290
Iteration: 7189/59290
Iteration: 7190/59290
Iteration: 7191/59290
Iteration: 7192/59290
Iteration: 7193/59290
Iteration: 7194/59290
Iteration: 7195/59290
Iteration: 7196/59290
Iteration: 7197/59290
Iteration: 7198/59290
Iteration: 7199/59290
Iteration: 7200/59290

 12%|█▏        | 7199/59290 [06:14<19:21, 44.84it/s]

Iteration: 7201/59290
Iteration: 7202/59290
Iteration: 7203/59290
Iteration: 7204/59290
Iteration: 7205/59290
Iteration: 7206/59290
Iteration: 7207/59290
Iteration: 7208/59290
Iteration: 7209/59290
Iteration: 7210/59290
Iteration: 7211/59290
Iteration: 7212/59290
Iteration: 7213/59290
Iteration: 7214/59290
Iteration: 7215/59290
Iteration: 7216/59290
Iteration: 7217/59290
Iteration: 7218/59290
Iteration: 7219/59290
Iteration: 7220/59290
Iteration: 7221/59290
Iteration: 7222/59290
Iteration: 7223/59290
Iteration: 7224/59290

 12%|█▏        | 7223/59290 [06:15<17:40, 49.10it/s]

Iteration: 7225/59290
Iteration: 7226/59290
Iteration: 7227/59290
Iteration: 7228/59290
Iteration: 7229/59290
Iteration: 7230/59290
Iteration: 7231/59290
Iteration: 7232/59290
Iteration: 7233/59290
Iteration: 7234/59290
Iteration: 7235/59290
Iteration: 7236/59290
Iteration: 7237/59290
Iteration: 7238/59290
Iteration: 7239/59290
Iteration: 7240/59290
Iteration: 7241/59290
Iteration: 7242/59290
Iteration: 7243/59290
Iteration: 7244/59290
Iteration: 7245/59290
Iteration: 7246/59290
Iteration: 7247/59290
Iteration: 7248/59290

 12%|█▏        | 7247/59290 [06:15<16:37, 52.16it/s]

Iteration: 7249/59290
Iteration: 7250/59290
Iteration: 7251/59290
Iteration: 7252/59290
Iteration: 7253/59290
Iteration: 7254/59290
Iteration: 7255/59290
Iteration: 7256/59290
Iteration: 7257/59290
Iteration: 7258/59290
Iteration: 7259/59290
Iteration: 7260/59290
Iteration: 7261/59290
Iteration: 7262/59290
Iteration: 7263/59290
Iteration: 7264/59290
Iteration: 7265/59290
Iteration: 7266/59290
Iteration: 7267/59290
Iteration: 7268/59290
Iteration: 7269/59290
Iteration: 7270/59290
Iteration: 7271/59290
Iteration: 7272/59290

 12%|█▏        | 7271/59290 [06:16<15:45, 55.04it/s]

Iteration: 7273/59290
Iteration: 7274/59290
Iteration: 7275/59290
Iteration: 7276/59290
Iteration: 7277/59290
Iteration: 7278/59290
Iteration: 7279/59290
Iteration: 7280/59290
Iteration: 7281/59290
Iteration: 7282/59290
Iteration: 7283/59290
Iteration: 7284/59290
Iteration: 7285/59290
Iteration: 7286/59290
Iteration: 7287/59290
Iteration: 7288/59290
Iteration: 7289/59290
Iteration: 7290/59290
Iteration: 7291/59290
Iteration: 7292/59290
Iteration: 7293/59290
Iteration: 7294/59290
Iteration: 7295/59290
Iteration: 7296/59290

 12%|█▏        | 7295/59290 [06:16<15:15, 56.79it/s]

Iteration: 7297/59290
Iteration: 7298/59290
Iteration: 7299/59290
Iteration: 7300/59290
Iteration: 7301/59290
Iteration: 7302/59290
Iteration: 7303/59290
Iteration: 7304/59290
Iteration: 7305/59290
Iteration: 7306/59290
Iteration: 7307/59290
Iteration: 7308/59290
Iteration: 7309/59290
Iteration: 7310/59290
Iteration: 7311/59290
Iteration: 7312/59290
Iteration: 7313/59290
Iteration: 7314/59290
Iteration: 7315/59290
Iteration: 7316/59290
Iteration: 7317/59290
Iteration: 7318/59290
Iteration: 7319/59290
Iteration: 7320/59290

 12%|█▏        | 7319/59290 [06:16<15:18, 56.60it/s]

Iteration: 7321/59290
Iteration: 7322/59290
Iteration: 7323/59290
Iteration: 7324/59290
Iteration: 7325/59290
Iteration: 7326/59290
Iteration: 7327/59290
Iteration: 7328/59290
Iteration: 7329/59290
Iteration: 7330/59290
Iteration: 7331/59290
Iteration: 7332/59290
Iteration: 7333/59290
Iteration: 7334/59290
Iteration: 7335/59290
Iteration: 7336/59290
Iteration: 7337/59290
Iteration: 7338/59290
Iteration: 7339/59290
Iteration: 7340/59290
Iteration: 7341/59290
Iteration: 7342/59290
Iteration: 7343/59290
Iteration: 7344/59290

 12%|█▏        | 7343/59290 [06:17<15:01, 57.59it/s]

Iteration: 7345/59290
Iteration: 7346/59290
Iteration: 7347/59290
Iteration: 7348/59290
Iteration: 7349/59290
Iteration: 7350/59290
Iteration: 7351/59290
Iteration: 7352/59290
Iteration: 7353/59290
Iteration: 7354/59290
Iteration: 7355/59290
Iteration: 7356/59290
Iteration: 7357/59290
Iteration: 7358/59290
Iteration: 7359/59290
Iteration: 7360/59290
Iteration: 7361/59290
Iteration: 7362/59290
Iteration: 7363/59290
Iteration: 7364/59290
Iteration: 7365/59290
Iteration: 7366/59290
Iteration: 7367/59290
Iteration: 7368/59290

 12%|█▏        | 7367/59290 [06:18<23:55, 36.16it/s]

Iteration: 7369/59290
Iteration: 7370/59290
Iteration: 7371/59290
Iteration: 7372/59290
Iteration: 7373/59290
Iteration: 7374/59290
Iteration: 7375/59290
Iteration: 7376/59290
Iteration: 7377/59290
Iteration: 7378/59290
Iteration: 7379/59290
Iteration: 7380/59290
Iteration: 7381/59290
Iteration: 7382/59290
Iteration: 7383/59290
Iteration: 7384/59290
Iteration: 7385/59290
Iteration: 7386/59290
Iteration: 7387/59290
Iteration: 7388/59290
Iteration: 7389/59290
Iteration: 7390/59290
Iteration: 7391/59290
Iteration: 7392/59290

 12%|█▏        | 7391/59290 [06:20<39:22, 21.97it/s]

Iteration: 7393/59290
Iteration: 7394/59290
Iteration: 7395/59290
Iteration: 7396/59290
Iteration: 7397/59290
Iteration: 7398/59290
Iteration: 7399/59290
Iteration: 7400/59290
Iteration: 7401/59290
Iteration: 7402/59290
Iteration: 7403/59290
Iteration: 7404/59290
Iteration: 7405/59290
Iteration: 7406/59290
Iteration: 7407/59290
Iteration: 7408/59290
Iteration: 7409/59290
Iteration: 7410/59290
Iteration: 7411/59290
Iteration: 7412/59290
Iteration: 7413/59290
Iteration: 7414/59290
Iteration: 7415/59290
Iteration: 7416/59290

 13%|█▎        | 7415/59290 [06:21<35:14, 24.54it/s]

Iteration: 7417/59290
Iteration: 7418/59290
Iteration: 7419/59290
Iteration: 7420/59290
Iteration: 7421/59290
Iteration: 7422/59290
Iteration: 7423/59290
Iteration: 7424/59290
Iteration: 7425/59290
Iteration: 7426/59290
Iteration: 7427/59290
Iteration: 7428/59290
Iteration: 7429/59290
Iteration: 7430/59290
Iteration: 7431/59290
Iteration: 7432/59290
Iteration: 7433/59290
Iteration: 7434/59290
Iteration: 7435/59290
Iteration: 7436/59290
Iteration: 7437/59290
Iteration: 7438/59290
Iteration: 7439/59290
Iteration: 7440/59290

 13%|█▎        | 7439/59290 [06:21<28:44, 30.07it/s]

Iteration: 7441/59290
Iteration: 7442/59290
Iteration: 7443/59290
Iteration: 7444/59290
Iteration: 7445/59290
Iteration: 7446/59290
Iteration: 7447/59290
Iteration: 7448/59290
Iteration: 7449/59290
Iteration: 7450/59290
Iteration: 7451/59290
Iteration: 7452/59290
Iteration: 7453/59290
Iteration: 7454/59290
Iteration: 7455/59290
Iteration: 7456/59290
Iteration: 7457/59290
Iteration: 7458/59290
Iteration: 7459/59290
Iteration: 7460/59290
Iteration: 7461/59290
Iteration: 7462/59290
Iteration: 7463/59290
Iteration: 7464/59290

 13%|█▎        | 7463/59290 [06:22<24:15, 35.62it/s]

Iteration: 7465/59290
Iteration: 7466/59290
Iteration: 7467/59290
Iteration: 7468/59290
Iteration: 7469/59290
Iteration: 7470/59290
Iteration: 7471/59290
Iteration: 7472/59290
Iteration: 7473/59290
Iteration: 7474/59290
Iteration: 7475/59290
Iteration: 7476/59290
Iteration: 7477/59290
Iteration: 7478/59290
Iteration: 7479/59290
Iteration: 7480/59290
Iteration: 7481/59290
Iteration: 7482/59290
Iteration: 7483/59290
Iteration: 7484/59290
Iteration: 7485/59290
Iteration: 7486/59290
Iteration: 7487/59290
Iteration: 7488/59290

 13%|█▎        | 7487/59290 [06:22<21:02, 41.02it/s]

Iteration: 7489/59290
Iteration: 7490/59290
Iteration: 7491/59290
Iteration: 7492/59290
Iteration: 7493/59290
Iteration: 7494/59290
Iteration: 7495/59290
Iteration: 7496/59290
Iteration: 7497/59290
Iteration: 7498/59290
Iteration: 7499/59290
Iteration: 7500/59290
Iteration: 7501/59290
Iteration: 7502/59290
Iteration: 7503/59290
Iteration: 7504/59290
Iteration: 7505/59290
Iteration: 7506/59290
Iteration: 7507/59290
Iteration: 7508/59290
Iteration: 7509/59290
Iteration: 7510/59290
Iteration: 7511/59290
Iteration: 7512/59290

 13%|█▎        | 7511/59290 [06:22<18:52, 45.72it/s]

Iteration: 7513/59290
Iteration: 7514/59290
Iteration: 7515/59290
Iteration: 7516/59290
Iteration: 7517/59290
Iteration: 7518/59290
Iteration: 7519/59290
Iteration: 7520/59290
Iteration: 7521/59290
Iteration: 7522/59290
Iteration: 7523/59290
Iteration: 7524/59290
Iteration: 7525/59290
Iteration: 7526/59290
Iteration: 7527/59290
Iteration: 7528/59290
Iteration: 7529/59290
Iteration: 7530/59290
Iteration: 7531/59290
Iteration: 7532/59290
Iteration: 7533/59290
Iteration: 7534/59290
Iteration: 7535/59290
Iteration: 7536/59290

 13%|█▎        | 7535/59290 [06:23<17:40, 48.82it/s]

Iteration: 7537/59290
Iteration: 7538/59290
Iteration: 7539/59290
Iteration: 7540/59290
Iteration: 7541/59290
Iteration: 7542/59290
Iteration: 7543/59290
Iteration: 7544/59290
Iteration: 7545/59290
Iteration: 7546/59290
Iteration: 7547/59290
Iteration: 7548/59290
Iteration: 7549/59290
Iteration: 7550/59290
Iteration: 7551/59290
Iteration: 7552/59290
Iteration: 7553/59290
Iteration: 7554/59290
Iteration: 7555/59290
Iteration: 7556/59290
Iteration: 7557/59290
Iteration: 7558/59290
Iteration: 7559/59290
Iteration: 7560/59290

 13%|█▎        | 7559/59290 [06:24<26:24, 32.66it/s]

Iteration: 7561/59290
Iteration: 7562/59290
Iteration: 7563/59290
Iteration: 7564/59290
Iteration: 7565/59290
Iteration: 7566/59290
Iteration: 7567/59290
Iteration: 7568/59290
Iteration: 7569/59290
Iteration: 7570/59290
Iteration: 7571/59290
Iteration: 7572/59290
Iteration: 7573/59290
Iteration: 7574/59290
Iteration: 7575/59290
Iteration: 7576/59290
Iteration: 7577/59290
Iteration: 7578/59290
Iteration: 7579/59290
Iteration: 7580/59290
Iteration: 7581/59290
Iteration: 7582/59290
Iteration: 7583/59290
Iteration: 7584/59290

 13%|█▎        | 7583/59290 [06:26<40:07, 21.47it/s]

Iteration: 7585/59290
Iteration: 7586/59290
Iteration: 7587/59290
Iteration: 7588/59290
Iteration: 7589/59290
Iteration: 7590/59290
Iteration: 7591/59290
Iteration: 7592/59290
Iteration: 7593/59290
Iteration: 7594/59290
Iteration: 7595/59290
Iteration: 7596/59290
Iteration: 7597/59290
Iteration: 7598/59290
Iteration: 7599/59290
Iteration: 7600/59290
Iteration: 7601/59290
Iteration: 7602/59290
Iteration: 7603/59290
Iteration: 7604/59290
Iteration: 7605/59290
Iteration: 7606/59290
Iteration: 7607/59290
Iteration: 7608/59290

 13%|█▎        | 7607/59290 [06:27<33:13, 25.92it/s]

Iteration: 7609/59290
Iteration: 7610/59290
Iteration: 7611/59290
Iteration: 7612/59290
Iteration: 7613/59290
Iteration: 7614/59290
Iteration: 7615/59290
Iteration: 7616/59290
Iteration: 7617/59290
Iteration: 7618/59290
Iteration: 7619/59290
Iteration: 7620/59290
Iteration: 7621/59290
Iteration: 7622/59290
Iteration: 7623/59290
Iteration: 7624/59290
Iteration: 7625/59290
Iteration: 7626/59290
Iteration: 7627/59290
Iteration: 7628/59290
Iteration: 7629/59290
Iteration: 7630/59290
Iteration: 7631/59290
Iteration: 7632/59290

 13%|█▎        | 7631/59290 [06:27<27:18, 31.53it/s]

Iteration: 7633/59290
Iteration: 7634/59290
Iteration: 7635/59290
Iteration: 7636/59290
Iteration: 7637/59290
Iteration: 7638/59290
Iteration: 7639/59290
Iteration: 7640/59290
Iteration: 7641/59290
Iteration: 7642/59290
Iteration: 7643/59290
Iteration: 7644/59290
Iteration: 7645/59290
Iteration: 7646/59290
Iteration: 7647/59290
Iteration: 7648/59290
Iteration: 7649/59290
Iteration: 7650/59290
Iteration: 7651/59290
Iteration: 7652/59290
Iteration: 7653/59290
Iteration: 7654/59290
Iteration: 7655/59290
Iteration: 7656/59290

 13%|█▎        | 7655/59290 [06:27<23:12, 37.09it/s]

Iteration: 7657/59290
Iteration: 7658/59290
Iteration: 7659/59290
Iteration: 7660/59290
Iteration: 7661/59290
Iteration: 7662/59290
Iteration: 7663/59290
Iteration: 7664/59290
Iteration: 7665/59290
Iteration: 7666/59290
Iteration: 7667/59290
Iteration: 7668/59290
Iteration: 7669/59290
Iteration: 7670/59290
Iteration: 7671/59290
Iteration: 7672/59290
Iteration: 7673/59290
Iteration: 7674/59290
Iteration: 7675/59290
Iteration: 7676/59290
Iteration: 7677/59290
Iteration: 7678/59290
Iteration: 7679/59290
Iteration: 7680/59290

 13%|█▎        | 7679/59290 [06:28<20:17, 42.39it/s]

Iteration: 7681/59290
Iteration: 7682/59290
Iteration: 7683/59290
Iteration: 7684/59290
Iteration: 7685/59290
Iteration: 7686/59290
Iteration: 7687/59290
Iteration: 7688/59290
Iteration: 7689/59290
Iteration: 7690/59290
Iteration: 7691/59290
Iteration: 7692/59290
Iteration: 7693/59290
Iteration: 7694/59290
Iteration: 7695/59290
Iteration: 7696/59290
Iteration: 7697/59290
Iteration: 7698/59290
Iteration: 7699/59290
Iteration: 7700/59290
Iteration: 7701/59290
Iteration: 7702/59290
Iteration: 7703/59290
Iteration: 7704/59290

 13%|█▎        | 7703/59290 [06:28<18:55, 45.45it/s]

Iteration: 7705/59290
Iteration: 7706/59290
Iteration: 7707/59290
Iteration: 7708/59290
Iteration: 7709/59290
Iteration: 7710/59290
Iteration: 7711/59290
Iteration: 7712/59290
Iteration: 7713/59290
Iteration: 7714/59290
Iteration: 7715/59290
Iteration: 7716/59290
Iteration: 7717/59290
Iteration: 7718/59290
Iteration: 7719/59290
Iteration: 7720/59290
Iteration: 7721/59290
Iteration: 7722/59290
Iteration: 7723/59290
Iteration: 7724/59290
Iteration: 7725/59290
Iteration: 7726/59290
Iteration: 7727/59290
Iteration: 7728/59290

 13%|█▎        | 7727/59290 [06:29<17:16, 49.76it/s]

Iteration: 7729/59290
Iteration: 7730/59290
Iteration: 7731/59290
Iteration: 7732/59290
Iteration: 7733/59290
Iteration: 7734/59290
Iteration: 7735/59290
Iteration: 7736/59290
Iteration: 7737/59290
Iteration: 7738/59290
Iteration: 7739/59290
Iteration: 7740/59290
Iteration: 7741/59290
Iteration: 7742/59290
Iteration: 7743/59290
Iteration: 7744/59290
Iteration: 7745/59290
Iteration: 7746/59290
Iteration: 7747/59290
Iteration: 7748/59290
Iteration: 7749/59290
Iteration: 7750/59290
Iteration: 7751/59290
Iteration: 7752/59290

 13%|█▎        | 7751/59290 [06:29<16:13, 52.93it/s]

Iteration: 7753/59290
Iteration: 7754/59290
Iteration: 7755/59290
Iteration: 7756/59290
Iteration: 7757/59290
Iteration: 7758/59290
Iteration: 7759/59290
Iteration: 7760/59290
Iteration: 7761/59290
Iteration: 7762/59290
Iteration: 7763/59290
Iteration: 7764/59290
Iteration: 7765/59290
Iteration: 7766/59290
Iteration: 7767/59290
Iteration: 7768/59290
Iteration: 7769/59290
Iteration: 7770/59290
Iteration: 7771/59290
Iteration: 7772/59290
Iteration: 7773/59290
Iteration: 7774/59290
Iteration: 7775/59290
Iteration: 7776/59290

 13%|█▎        | 7775/59290 [06:30<25:53, 33.16it/s]

Iteration: 7777/59290
Iteration: 7778/59290
Iteration: 7779/59290
Iteration: 7780/59290
Iteration: 7781/59290
Iteration: 7782/59290
Iteration: 7783/59290
Iteration: 7784/59290
Iteration: 7785/59290
Iteration: 7786/59290
Iteration: 7787/59290
Iteration: 7788/59290
Iteration: 7789/59290
Iteration: 7790/59290
Iteration: 7791/59290
Iteration: 7792/59290
Iteration: 7793/59290
Iteration: 7794/59290
Iteration: 7795/59290
Iteration: 7796/59290
Iteration: 7797/59290
Iteration: 7798/59290
Iteration: 7799/59290
Iteration: 7800/59290

 13%|█▎        | 7799/59290 [06:32<40:49, 21.02it/s]

Iteration: 7801/59290
Iteration: 7802/59290
Iteration: 7803/59290
Iteration: 7804/59290
Iteration: 7805/59290
Iteration: 7806/59290
Iteration: 7807/59290
Iteration: 7808/59290
Iteration: 7809/59290
Iteration: 7810/59290
Iteration: 7811/59290
Iteration: 7812/59290
Iteration: 7813/59290
Iteration: 7814/59290
Iteration: 7815/59290
Iteration: 7816/59290
Iteration: 7817/59290
Iteration: 7818/59290
Iteration: 7819/59290
Iteration: 7820/59290
Iteration: 7821/59290
Iteration: 7822/59290
Iteration: 7823/59290
Iteration: 7824/59290

 13%|█▎        | 7823/59290 [06:33<34:31, 24.84it/s]

Iteration: 7825/59290
Iteration: 7826/59290
Iteration: 7827/59290
Iteration: 7828/59290
Iteration: 7829/59290
Iteration: 7830/59290
Iteration: 7831/59290
Iteration: 7832/59290
Iteration: 7833/59290
Iteration: 7834/59290
Iteration: 7835/59290
Iteration: 7836/59290
Iteration: 7837/59290
Iteration: 7838/59290
Iteration: 7839/59290
Iteration: 7840/59290
Iteration: 7841/59290
Iteration: 7842/59290
Iteration: 7843/59290
Iteration: 7844/59290
Iteration: 7845/59290
Iteration: 7846/59290
Iteration: 7847/59290
Iteration: 7848/59290

 13%|█▎        | 7847/59290 [06:33<28:13, 30.38it/s]

Iteration: 7849/59290
Iteration: 7850/59290
Iteration: 7851/59290
Iteration: 7852/59290
Iteration: 7853/59290
Iteration: 7854/59290
Iteration: 7855/59290
Iteration: 7856/59290
Iteration: 7857/59290
Iteration: 7858/59290
Iteration: 7859/59290
Iteration: 7860/59290
Iteration: 7861/59290
Iteration: 7862/59290
Iteration: 7863/59290
Iteration: 7864/59290
Iteration: 7865/59290
Iteration: 7866/59290
Iteration: 7867/59290
Iteration: 7868/59290
Iteration: 7869/59290
Iteration: 7870/59290
Iteration: 7871/59290
Iteration: 7872/59290

 13%|█▎        | 7871/59290 [06:34<23:47, 36.03it/s]

Iteration: 7873/59290
Iteration: 7874/59290
Iteration: 7875/59290
Iteration: 7876/59290
Iteration: 7877/59290
Iteration: 7878/59290
Iteration: 7879/59290
Iteration: 7880/59290
Iteration: 7881/59290
Iteration: 7882/59290
Iteration: 7883/59290
Iteration: 7884/59290
Iteration: 7885/59290
Iteration: 7886/59290
Iteration: 7887/59290
Iteration: 7888/59290
Iteration: 7889/59290
Iteration: 7890/59290
Iteration: 7891/59290
Iteration: 7892/59290
Iteration: 7893/59290
Iteration: 7894/59290
Iteration: 7895/59290
Iteration: 7896/59290

 13%|█▎        | 7895/59290 [06:34<21:07, 40.54it/s]

Iteration: 7897/59290
Iteration: 7898/59290
Iteration: 7899/59290
Iteration: 7900/59290
Iteration: 7901/59290
Iteration: 7902/59290
Iteration: 7903/59290
Iteration: 7904/59290
Iteration: 7905/59290
Iteration: 7906/59290
Iteration: 7907/59290
Iteration: 7908/59290
Iteration: 7909/59290
Iteration: 7910/59290
Iteration: 7911/59290
Iteration: 7912/59290
Iteration: 7913/59290
Iteration: 7914/59290
Iteration: 7915/59290
Iteration: 7916/59290
Iteration: 7917/59290
Iteration: 7918/59290
Iteration: 7919/59290
Iteration: 7920/59290

 13%|█▎        | 7919/59290 [06:35<28:57, 29.57it/s]

Iteration: 7921/59290
Iteration: 7922/59290
Iteration: 7923/59290
Iteration: 7924/59290
Iteration: 7925/59290
Iteration: 7926/59290
Iteration: 7927/59290
Iteration: 7928/59290
Iteration: 7929/59290
Iteration: 7930/59290
Iteration: 7931/59290
Iteration: 7932/59290
Iteration: 7933/59290
Iteration: 7934/59290
Iteration: 7935/59290
Iteration: 7936/59290
Iteration: 7937/59290
Iteration: 7938/59290
Iteration: 7939/59290
Iteration: 7940/59290
Iteration: 7941/59290
Iteration: 7942/59290
Iteration: 7943/59290
Iteration: 7944/59290

 13%|█▎        | 7943/59290 [06:38<42:28, 20.15it/s]

Iteration: 7945/59290
Iteration: 7946/59290
Iteration: 7947/59290
Iteration: 7948/59290
Iteration: 7949/59290
Iteration: 7950/59290
Iteration: 7951/59290
Iteration: 7952/59290
Iteration: 7953/59290
Iteration: 7954/59290
Iteration: 7955/59290
Iteration: 7956/59290
Iteration: 7957/59290
Iteration: 7958/59290
Iteration: 7959/59290
Iteration: 7960/59290
Iteration: 7961/59290
Iteration: 7962/59290
Iteration: 7963/59290
Iteration: 7964/59290
Iteration: 7965/59290
Iteration: 7966/59290
Iteration: 7967/59290
Iteration: 7968/59290

 13%|█▎        | 7967/59290 [06:38<34:53, 24.52it/s]

Iteration: 7969/59290
Iteration: 7970/59290
Iteration: 7971/59290
Iteration: 7972/59290
Iteration: 7973/59290
Iteration: 7974/59290
Iteration: 7975/59290
Iteration: 7976/59290
Iteration: 7977/59290
Iteration: 7978/59290
Iteration: 7979/59290
Iteration: 7980/59290
Iteration: 7981/59290
Iteration: 7982/59290
Iteration: 7983/59290
Iteration: 7984/59290
Iteration: 7985/59290
Iteration: 7986/59290
Iteration: 7987/59290
Iteration: 7988/59290
Iteration: 7989/59290
Iteration: 7990/59290
Iteration: 7991/59290
Iteration: 7992/59290

 13%|█▎        | 7991/59290 [06:38<28:31, 29.97it/s]

Iteration: 7993/59290
Iteration: 7994/59290
Iteration: 7995/59290
Iteration: 7996/59290
Iteration: 7997/59290
Iteration: 7998/59290
Iteration: 7999/59290
Iteration: 8000/59290
Iteration: 8001/59290
Iteration: 8002/59290
Iteration: 8003/59290
Iteration: 8004/59290
Iteration: 8005/59290
Iteration: 8006/59290
Iteration: 8007/59290
Iteration: 8008/59290
Iteration: 8009/59290
Iteration: 8010/59290
Iteration: 8011/59290
Iteration: 8012/59290
Iteration: 8013/59290
Iteration: 8014/59290
Iteration: 8015/59290
Iteration: 8016/59290

 14%|█▎        | 8015/59290 [06:39<23:57, 35.68it/s]

Iteration: 8017/59290
Iteration: 8018/59290
Iteration: 8019/59290
Iteration: 8020/59290
Iteration: 8021/59290
Iteration: 8022/59290
Iteration: 8023/59290
Iteration: 8024/59290
Iteration: 8025/59290
Iteration: 8026/59290
Iteration: 8027/59290
Iteration: 8028/59290
Iteration: 8029/59290
Iteration: 8030/59290
Iteration: 8031/59290
Iteration: 8032/59290
Iteration: 8033/59290
Iteration: 8034/59290
Iteration: 8035/59290
Iteration: 8036/59290
Iteration: 8037/59290
Iteration: 8038/59290
Iteration: 8039/59290
Iteration: 8040/59290

 14%|█▎        | 8039/59290 [06:39<21:32, 39.66it/s]

Iteration: 8041/59290
Iteration: 8042/59290
Iteration: 8043/59290
Iteration: 8044/59290
Iteration: 8045/59290
Iteration: 8046/59290
Iteration: 8047/59290
Iteration: 8048/59290
Iteration: 8049/59290
Iteration: 8050/59290
Iteration: 8051/59290
Iteration: 8052/59290
Iteration: 8053/59290
Iteration: 8054/59290
Iteration: 8055/59290
Iteration: 8056/59290
Iteration: 8057/59290
Iteration: 8058/59290
Iteration: 8059/59290
Iteration: 8060/59290
Iteration: 8061/59290
Iteration: 8062/59290
Iteration: 8063/59290
Iteration: 8064/59290

 14%|█▎        | 8063/59290 [06:40<19:06, 44.68it/s]

Iteration: 8065/59290
Iteration: 8066/59290
Iteration: 8067/59290
Iteration: 8068/59290
Iteration: 8069/59290
Iteration: 8070/59290
Iteration: 8071/59290
Iteration: 8072/59290
Iteration: 8073/59290
Iteration: 8074/59290
Iteration: 8075/59290
Iteration: 8076/59290
Iteration: 8077/59290
Iteration: 8078/59290
Iteration: 8079/59290
Iteration: 8080/59290
Iteration: 8081/59290
Iteration: 8082/59290
Iteration: 8083/59290
Iteration: 8084/59290
Iteration: 8085/59290
Iteration: 8086/59290
Iteration: 8088/59290

 14%|█▎        | 8086/59290 [06:41<31:42, 26.91it/s]

Iteration: 8089/59290
Iteration: 8090/59290
Iteration: 8091/59290
Iteration: 8092/59290
Iteration: 8093/59290
Iteration: 8094/59290
Iteration: 8095/59290
Iteration: 8096/59290

 14%|█▎        | 8094/59290 [06:44<1:01:05, 13.97it/s]

Iteration: 8097/59290
Iteration: 8098/59290
Iteration: 8099/59290
Iteration: 8100/59290
Iteration: 8101/59290
Iteration: 8102/59290
Iteration: 8103/59290
Iteration: 8104/59290
Iteration: 8105/59290
Iteration: 8106/59290
Iteration: 8107/59290
Iteration: 8108/59290
Iteration: 8109/59290
Iteration: 8110/59290
Iteration: 8111/59290
Iteration: 8112/59290
Iteration: 8113/59290
Iteration: 8114/59290
Iteration: 8115/59290
Iteration: 8116/59290
Iteration: 8117/59290
Iteration: 8118/59290
Iteration: 8119/59290
Iteration: 8120/59290

 14%|█▎        | 8118/59290 [06:44<44:15, 19.27it/s]

Iteration: 8121/59290
Iteration: 8122/59290
Iteration: 8123/59290
Iteration: 8124/59290
Iteration: 8125/59290
Iteration: 8126/59290
Iteration: 8127/59290
Iteration: 8128/59290
Iteration: 8129/59290
Iteration: 8130/59290
Iteration: 8131/59290
Iteration: 8132/59290
Iteration: 8133/59290
Iteration: 8134/59290
Iteration: 8135/59290
Iteration: 8136/59290
Iteration: 8137/59290
Iteration: 8138/59290
Iteration: 8139/59290
Iteration: 8140/59290
Iteration: 8141/59290
Iteration: 8142/59290
Iteration: 8143/59290
Iteration: 8144/59290

 14%|█▎        | 8142/59290 [06:45<34:05, 25.01it/s]

Iteration: 8145/59290
Iteration: 8146/59290
Iteration: 8147/59290
Iteration: 8148/59290
Iteration: 8149/59290
Iteration: 8150/59290
Iteration: 8151/59290
Iteration: 8152/59290
Iteration: 8153/59290
Iteration: 8154/59290
Iteration: 8155/59290
Iteration: 8156/59290
Iteration: 8157/59290
Iteration: 8158/59290
Iteration: 8159/59290
Iteration: 8160/59290
Iteration: 8161/59290
Iteration: 8162/59290
Iteration: 8163/59290
Iteration: 8164/59290
Iteration: 8165/59290
Iteration: 8166/59290
Iteration: 8167/59290
Iteration: 8168/59290

 14%|█▍        | 8166/59290 [06:45<27:32, 30.94it/s]

Iteration: 8169/59290
Iteration: 8170/59290
Iteration: 8171/59290
Iteration: 8172/59290
Iteration: 8173/59290
Iteration: 8174/59290
Iteration: 8175/59290
Iteration: 8176/59290
Iteration: 8177/59290
Iteration: 8178/59290
Iteration: 8179/59290
Iteration: 8180/59290
Iteration: 8181/59290
Iteration: 8182/59290
Iteration: 8183/59290
Iteration: 8184/59290
Iteration: 8185/59290
Iteration: 8186/59290
Iteration: 8187/59290
Iteration: 8188/59290
Iteration: 8189/59290
Iteration: 8190/59290
Iteration: 8191/59290
Iteration: 8192/59290

 14%|█▍        | 8190/59290 [06:45<23:06, 36.85it/s]

Iteration: 8193/59290
Iteration: 8194/59290
Iteration: 8195/59290
Iteration: 8196/59290
Iteration: 8197/59290
Iteration: 8198/59290
Iteration: 8199/59290
Iteration: 8200/59290
Iteration: 8201/59290
Iteration: 8202/59290
Iteration: 8203/59290
Iteration: 8204/59290
Iteration: 8205/59290
Iteration: 8206/59290
Iteration: 8207/59290
Iteration: 8208/59290
Iteration: 8209/59290
Iteration: 8210/59290
Iteration: 8211/59290
Iteration: 8212/59290
Iteration: 8213/59290
Iteration: 8214/59290
Iteration: 8215/59290
Iteration: 8216/59290

 14%|█▍        | 8214/59290 [06:46<20:04, 42.39it/s]

Iteration: 8217/59290
Iteration: 8218/59290
Iteration: 8219/59290
Iteration: 8220/59290
Iteration: 8221/59290
Iteration: 8222/59290
Iteration: 8223/59290
Iteration: 8224/59290
Iteration: 8225/59290
Iteration: 8226/59290
Iteration: 8227/59290
Iteration: 8228/59290
Iteration: 8229/59290
Iteration: 8230/59290
Iteration: 8231/59290
Iteration: 8232/59290
Iteration: 8233/59290
Iteration: 8234/59290
Iteration: 8235/59290
Iteration: 8236/59290
Iteration: 8237/59290
Iteration: 8238/59290
Iteration: 8239/59290
Iteration: 8240/59290

 14%|█▍        | 8238/59290 [06:46<17:56, 47.42it/s]

Iteration: 8241/59290
Iteration: 8242/59290
Iteration: 8243/59290
Iteration: 8244/59290
Iteration: 8245/59290
Iteration: 8246/59290
Iteration: 8247/59290
Iteration: 8248/59290
Iteration: 8249/59290
Iteration: 8250/59290
Iteration: 8251/59290
Iteration: 8252/59290
Iteration: 8253/59290
Iteration: 8254/59290
Iteration: 8255/59290
Iteration: 8256/59290
Iteration: 8257/59290
Iteration: 8258/59290
Iteration: 8259/59290
Iteration: 8260/59290
Iteration: 8261/59290
Iteration: 8262/59290
Iteration: 8263/59290
Iteration: 8264/59290

 14%|█▍        | 8262/59290 [06:46<16:51, 50.45it/s]

Iteration: 8265/59290
Iteration: 8266/59290
Iteration: 8267/59290
Iteration: 8268/59290
Iteration: 8269/59290
Iteration: 8270/59290
Iteration: 8271/59290
Iteration: 8272/59290
Iteration: 8273/59290
Iteration: 8274/59290
Iteration: 8275/59290
Iteration: 8276/59290
Iteration: 8277/59290
Iteration: 8278/59290
Iteration: 8279/59290
Iteration: 8280/59290
Iteration: 8281/59290
Iteration: 8282/59290
Iteration: 8283/59290
Iteration: 8284/59290
Iteration: 8285/59290
Iteration: 8286/59290
Iteration: 8287/59290
Iteration: 8288/59290

 14%|█▍        | 8286/59290 [06:47<15:46, 53.87it/s]

Iteration: 8289/59290
Iteration: 8290/59290
Iteration: 8291/59290
Iteration: 8292/59290
Iteration: 8293/59290
Iteration: 8294/59290
Iteration: 8295/59290
Iteration: 8296/59290
Iteration: 8297/59290
Iteration: 8298/59290
Iteration: 8299/59290
Iteration: 8300/59290
Iteration: 8301/59290
Iteration: 8302/59290
Iteration: 8303/59290
Iteration: 8304/59290
Iteration: 8305/59290
Iteration: 8306/59290
Iteration: 8307/59290
Iteration: 8308/59290
Iteration: 8309/59290
Iteration: 8310/59290
Iteration: 8311/59290
Iteration: 8312/59290

 14%|█▍        | 8310/59290 [06:47<14:57, 56.78it/s]

Iteration: 8313/59290
Iteration: 8314/59290
Iteration: 8315/59290
Iteration: 8316/59290
Iteration: 8317/59290
Iteration: 8318/59290
Iteration: 8319/59290
Iteration: 8320/59290
Iteration: 8321/59290
Iteration: 8322/59290
Iteration: 8323/59290
Iteration: 8324/59290
Iteration: 8325/59290
Iteration: 8326/59290
Iteration: 8327/59290
Iteration: 8328/59290
Iteration: 8329/59290
Iteration: 8330/59290
Iteration: 8331/59290
Iteration: 8332/59290
Iteration: 8333/59290
Iteration: 8334/59290
Iteration: 8335/59290
Iteration: 8336/59290

 14%|█▍        | 8334/59290 [06:48<14:25, 58.87it/s]

Iteration: 8337/59290
Iteration: 8338/59290
Iteration: 8339/59290
Iteration: 8340/59290
Iteration: 8341/59290
Iteration: 8342/59290
Iteration: 8343/59290
Iteration: 8344/59290
Iteration: 8345/59290
Iteration: 8346/59290
Iteration: 8347/59290
Iteration: 8348/59290
Iteration: 8349/59290
Iteration: 8350/59290
Iteration: 8351/59290
Iteration: 8352/59290
Iteration: 8353/59290
Iteration: 8354/59290
Iteration: 8355/59290
Iteration: 8356/59290
Iteration: 8357/59290
Iteration: 8358/59290
Iteration: 8359/59290
Iteration: 8360/59290

 14%|█▍        | 8358/59290 [06:49<23:26, 36.21it/s]

Iteration: 8361/59290
Iteration: 8362/59290
Iteration: 8363/59290
Iteration: 8364/59290
Iteration: 8365/59290
Iteration: 8366/59290
Iteration: 8367/59290
Iteration: 8368/59290
Iteration: 8369/59290
Iteration: 8370/59290
Iteration: 8371/59290
Iteration: 8372/59290
Iteration: 8373/59290
Iteration: 8374/59290
Iteration: 8375/59290
Iteration: 8376/59290
Iteration: 8377/59290
Iteration: 8378/59290
Iteration: 8379/59290
Iteration: 8380/59290
Iteration: 8381/59290
Iteration: 8382/59290
Iteration: 8383/59290
Iteration: 8384/59290

 14%|█▍        | 8382/59290 [06:51<37:36, 22.56it/s]

Iteration: 8385/59290
Iteration: 8386/59290
Iteration: 8387/59290
Iteration: 8388/59290
Iteration: 8389/59290
Iteration: 8390/59290
Iteration: 8391/59290
Iteration: 8392/59290
Iteration: 8393/59290
Iteration: 8394/59290
Iteration: 8395/59290
Iteration: 8396/59290
Iteration: 8397/59290
Iteration: 8398/59290
Iteration: 8399/59290
Iteration: 8400/59290
Iteration: 8401/59290
Iteration: 8402/59290
Iteration: 8403/59290
Iteration: 8404/59290
Iteration: 8405/59290
Iteration: 8406/59290
Iteration: 8407/59290
Iteration: 8408/59290

 14%|█▍        | 8406/59290 [06:51<32:29, 26.10it/s]

Iteration: 8409/59290
Iteration: 8410/59290
Iteration: 8411/59290
Iteration: 8412/59290
Iteration: 8413/59290
Iteration: 8414/59290
Iteration: 8415/59290
Iteration: 8416/59290
Iteration: 8417/59290
Iteration: 8418/59290
Iteration: 8419/59290
Iteration: 8420/59290
Iteration: 8421/59290
Iteration: 8422/59290
Iteration: 8423/59290
Iteration: 8424/59290
Iteration: 8425/59290
Iteration: 8426/59290
Iteration: 8427/59290
Iteration: 8428/59290
Iteration: 8429/59290
Iteration: 8430/59290
Iteration: 8431/59290
Iteration: 8432/59290

 14%|█▍        | 8430/59290 [06:52<26:41, 31.76it/s]

Iteration: 8433/59290
Iteration: 8434/59290
Iteration: 8435/59290
Iteration: 8436/59290
Iteration: 8437/59290
Iteration: 8438/59290
Iteration: 8439/59290
Iteration: 8440/59290
Iteration: 8441/59290
Iteration: 8442/59290
Iteration: 8443/59290
Iteration: 8444/59290
Iteration: 8445/59290
Iteration: 8446/59290
Iteration: 8447/59290
Iteration: 8448/59290
Iteration: 8449/59290
Iteration: 8450/59290
Iteration: 8451/59290
Iteration: 8452/59290
Iteration: 8453/59290
Iteration: 8454/59290
Iteration: 8455/59290
Iteration: 8456/59290

 14%|█▍        | 8454/59290 [06:52<22:50, 37.10it/s]

Iteration: 8457/59290
Iteration: 8458/59290
Iteration: 8459/59290
Iteration: 8460/59290
Iteration: 8461/59290
Iteration: 8462/59290
Iteration: 8463/59290
Iteration: 8464/59290
Iteration: 8465/59290
Iteration: 8466/59290
Iteration: 8467/59290
Iteration: 8468/59290
Iteration: 8469/59290
Iteration: 8470/59290
Iteration: 8471/59290
Iteration: 8472/59290
Iteration: 8473/59290
Iteration: 8474/59290
Iteration: 8475/59290
Iteration: 8476/59290
Iteration: 8477/59290
Iteration: 8478/59290
Iteration: 8479/59290
Iteration: 8480/59290

 14%|█▍        | 8478/59290 [06:53<19:58, 42.40it/s]

Iteration: 8481/59290
Iteration: 8482/59290
Iteration: 8483/59290
Iteration: 8484/59290
Iteration: 8485/59290
Iteration: 8486/59290
Iteration: 8487/59290
Iteration: 8488/59290
Iteration: 8489/59290
Iteration: 8490/59290
Iteration: 8491/59290
Iteration: 8492/59290
Iteration: 8493/59290
Iteration: 8494/59290
Iteration: 8495/59290
Iteration: 8496/59290
Iteration: 8497/59290
Iteration: 8498/59290
Iteration: 8499/59290
Iteration: 8500/59290
Iteration: 8501/59290
Iteration: 8502/59290
Iteration: 8503/59290
Iteration: 8504/59290

 14%|█▍        | 8502/59290 [06:53<17:59, 47.04it/s]

Iteration: 8505/59290
Iteration: 8506/59290
Iteration: 8507/59290
Iteration: 8508/59290
Iteration: 8509/59290
Iteration: 8510/59290
Iteration: 8511/59290
Iteration: 8512/59290
Iteration: 8513/59290
Iteration: 8514/59290
Iteration: 8515/59290
Iteration: 8516/59290
Iteration: 8517/59290
Iteration: 8518/59290
Iteration: 8519/59290
Iteration: 8520/59290
Iteration: 8521/59290
Iteration: 8522/59290
Iteration: 8523/59290
Iteration: 8524/59290
Iteration: 8525/59290
Iteration: 8526/59290
Iteration: 8527/59290
Iteration: 8528/59290

 14%|█▍        | 8526/59290 [06:54<26:46, 31.61it/s]

Iteration: 8529/59290
Iteration: 8530/59290
Iteration: 8531/59290
Iteration: 8532/59290
Iteration: 8533/59290
Iteration: 8534/59290
Iteration: 8535/59290
Iteration: 8536/59290
Iteration: 8537/59290
Iteration: 8538/59290
Iteration: 8539/59290
Iteration: 8540/59290
Iteration: 8541/59290
Iteration: 8542/59290
Iteration: 8543/59290
Iteration: 8544/59290
Iteration: 8545/59290
Iteration: 8546/59290
Iteration: 8547/59290
Iteration: 8548/59290
Iteration: 8549/59290
Iteration: 8550/59290
Iteration: 8551/59290
Iteration: 8552/59290

 14%|█▍        | 8550/59290 [06:56<40:56, 20.65it/s]

Iteration: 8553/59290
Iteration: 8554/59290
Iteration: 8555/59290
Iteration: 8556/59290
Iteration: 8557/59290
Iteration: 8558/59290
Iteration: 8559/59290
Iteration: 8560/59290
Iteration: 8561/59290
Iteration: 8562/59290
Iteration: 8563/59290
Iteration: 8564/59290
Iteration: 8565/59290
Iteration: 8566/59290
Iteration: 8567/59290
Iteration: 8568/59290
Iteration: 8569/59290
Iteration: 8570/59290
Iteration: 8571/59290
Iteration: 8572/59290
Iteration: 8573/59290
Iteration: 8574/59290
Iteration: 8575/59290
Iteration: 8576/59290

 14%|█▍        | 8574/59290 [06:57<34:20, 24.62it/s]

Iteration: 8577/59290
Iteration: 8578/59290
Iteration: 8579/59290
Iteration: 8580/59290
Iteration: 8581/59290
Iteration: 8582/59290
Iteration: 8583/59290
Iteration: 8584/59290
Iteration: 8585/59290
Iteration: 8586/59290
Iteration: 8587/59290
Iteration: 8588/59290
Iteration: 8589/59290
Iteration: 8590/59290
Iteration: 8591/59290
Iteration: 8592/59290
Iteration: 8593/59290
Iteration: 8594/59290
Iteration: 8595/59290
Iteration: 8596/59290
Iteration: 8597/59290
Iteration: 8598/59290
Iteration: 8599/59290
Iteration: 8600/59290

 15%|█▍        | 8598/59290 [06:57<27:58, 30.20it/s]

Iteration: 8601/59290
Iteration: 8602/59290
Iteration: 8603/59290
Iteration: 8604/59290
Iteration: 8605/59290
Iteration: 8606/59290
Iteration: 8607/59290
Iteration: 8608/59290
Iteration: 8609/59290
Iteration: 8610/59290
Iteration: 8611/59290
Iteration: 8612/59290
Iteration: 8613/59290
Iteration: 8614/59290
Iteration: 8615/59290
Iteration: 8616/59290
Iteration: 8617/59290
Iteration: 8618/59290
Iteration: 8619/59290
Iteration: 8620/59290
Iteration: 8621/59290
Iteration: 8622/59290
Iteration: 8623/59290
Iteration: 8624/59290

 15%|█▍        | 8622/59290 [06:58<23:36, 35.76it/s]

Iteration: 8625/59290
Iteration: 8626/59290
Iteration: 8627/59290
Iteration: 8628/59290
Iteration: 8629/59290
Iteration: 8630/59290
Iteration: 8631/59290
Iteration: 8632/59290
Iteration: 8633/59290
Iteration: 8634/59290
Iteration: 8635/59290
Iteration: 8636/59290
Iteration: 8637/59290
Iteration: 8638/59290
Iteration: 8639/59290
Iteration: 8640/59290
Iteration: 8641/59290
Iteration: 8642/59290
Iteration: 8643/59290
Iteration: 8644/59290
Iteration: 8645/59290
Iteration: 8646/59290
Iteration: 8647/59290
Iteration: 8648/59290

 15%|█▍        | 8646/59290 [06:58<20:36, 40.95it/s]

Iteration: 8649/59290
Iteration: 8650/59290
Iteration: 8651/59290
Iteration: 8652/59290
Iteration: 8653/59290
Iteration: 8654/59290
Iteration: 8655/59290
Iteration: 8656/59290
Iteration: 8657/59290
Iteration: 8658/59290
Iteration: 8659/59290
Iteration: 8660/59290
Iteration: 8661/59290
Iteration: 8662/59290
Iteration: 8663/59290
Iteration: 8664/59290
Iteration: 8665/59290
Iteration: 8666/59290
Iteration: 8667/59290
Iteration: 8668/59290
Iteration: 8669/59290
Iteration: 8670/59290
Iteration: 8671/59290
Iteration: 8672/59290

 15%|█▍        | 8670/59290 [06:58<18:25, 45.79it/s]

Iteration: 8673/59290
Iteration: 8674/59290
Iteration: 8675/59290
Iteration: 8676/59290
Iteration: 8677/59290
Iteration: 8678/59290
Iteration: 8679/59290
Iteration: 8680/59290
Iteration: 8681/59290
Iteration: 8682/59290
Iteration: 8683/59290
Iteration: 8684/59290
Iteration: 8685/59290
Iteration: 8686/59290
Iteration: 8687/59290
Iteration: 8688/59290
Iteration: 8689/59290
Iteration: 8690/59290
Iteration: 8691/59290
Iteration: 8692/59290
Iteration: 8693/59290
Iteration: 8694/59290
Iteration: 8695/59290
Iteration: 8696/59290

 15%|█▍        | 8694/59290 [06:59<16:48, 50.17it/s]

Iteration: 8697/59290
Iteration: 8698/59290
Iteration: 8699/59290
Iteration: 8700/59290
Iteration: 8701/59290
Iteration: 8702/59290
Iteration: 8703/59290
Iteration: 8704/59290
Iteration: 8705/59290
Iteration: 8706/59290
Iteration: 8707/59290
Iteration: 8708/59290
Iteration: 8709/59290
Iteration: 8710/59290
Iteration: 8711/59290
Iteration: 8712/59290
Iteration: 8713/59290
Iteration: 8714/59290
Iteration: 8715/59290
Iteration: 8716/59290
Iteration: 8717/59290
Iteration: 8718/59290
Iteration: 8719/59290
Iteration: 8720/59290

 15%|█▍        | 8718/59290 [06:59<15:54, 53.00it/s]

Iteration: 8721/59290
Iteration: 8722/59290
Iteration: 8723/59290
Iteration: 8724/59290
Iteration: 8725/59290
Iteration: 8726/59290
Iteration: 8727/59290
Iteration: 8728/59290
Iteration: 8729/59290
Iteration: 8730/59290
Iteration: 8731/59290
Iteration: 8732/59290
Iteration: 8733/59290
Iteration: 8734/59290
Iteration: 8735/59290
Iteration: 8736/59290
Iteration: 8737/59290
Iteration: 8738/59290
Iteration: 8739/59290
Iteration: 8740/59290
Iteration: 8741/59290
Iteration: 8742/59290
Iteration: 8743/59290
Iteration: 8744/59290

 15%|█▍        | 8742/59290 [07:00<15:02, 56.04it/s]

Iteration: 8745/59290
Iteration: 8746/59290
Iteration: 8747/59290
Iteration: 8748/59290
Iteration: 8749/59290
Iteration: 8750/59290
Iteration: 8751/59290
Iteration: 8752/59290
Iteration: 8753/59290
Iteration: 8754/59290
Iteration: 8755/59290
Iteration: 8756/59290
Iteration: 8757/59290
Iteration: 8758/59290
Iteration: 8759/59290
Iteration: 8760/59290
Iteration: 8761/59290
Iteration: 8762/59290
Iteration: 8763/59290
Iteration: 8764/59290
Iteration: 8765/59290
Iteration: 8766/59290
Iteration: 8767/59290
Iteration: 8768/59290

 15%|█▍        | 8766/59290 [07:00<14:34, 57.78it/s]

Iteration: 8769/59290
Iteration: 8770/59290
Iteration: 8771/59290
Iteration: 8772/59290
Iteration: 8773/59290
Iteration: 8774/59290
Iteration: 8775/59290
Iteration: 8776/59290
Iteration: 8777/59290
Iteration: 8778/59290
Iteration: 8779/59290
Iteration: 8780/59290
Iteration: 8781/59290
Iteration: 8782/59290
Iteration: 8783/59290
Iteration: 8784/59290
Iteration: 8785/59290
Iteration: 8786/59290
Iteration: 8787/59290
Iteration: 8788/59290
Iteration: 8789/59290
Iteration: 8790/59290
Iteration: 8791/59290
Iteration: 8792/59290

 15%|█▍        | 8790/59290 [07:01<24:02, 35.00it/s]

Iteration: 8793/59290
Iteration: 8794/59290
Iteration: 8795/59290
Iteration: 8796/59290
Iteration: 8797/59290
Iteration: 8798/59290
Iteration: 8799/59290
Iteration: 8800/59290
Iteration: 8801/59290
Iteration: 8802/59290
Iteration: 8803/59290
Iteration: 8804/59290
Iteration: 8805/59290
Iteration: 8806/59290
Iteration: 8807/59290
Iteration: 8808/59290
Iteration: 8809/59290
Iteration: 8810/59290
Iteration: 8811/59290
Iteration: 8812/59290
Iteration: 8813/59290
Iteration: 8814/59290
Iteration: 8815/59290
Iteration: 8816/59290

 15%|█▍        | 8814/59290 [07:04<42:53, 19.62it/s]

Iteration: 8817/59290
Iteration: 8818/59290
Iteration: 8819/59290
Iteration: 8820/59290
Iteration: 8821/59290
Iteration: 8822/59290
Iteration: 8823/59290
Iteration: 8824/59290
Iteration: 8825/59290
Iteration: 8826/59290
Iteration: 8827/59290
Iteration: 8828/59290
Iteration: 8829/59290
Iteration: 8830/59290
Iteration: 8831/59290
Iteration: 8832/59290
Iteration: 8833/59290
Iteration: 8834/59290
Iteration: 8835/59290
Iteration: 8836/59290
Iteration: 8837/59290
Iteration: 8838/59290
Iteration: 8839/59290
Iteration: 8840/59290

 15%|█▍        | 8838/59290 [07:04<34:05, 24.67it/s]

Iteration: 8841/59290
Iteration: 8842/59290
Iteration: 8843/59290
Iteration: 8844/59290
Iteration: 8845/59290
Iteration: 8846/59290
Iteration: 8847/59290
Iteration: 8848/59290
Iteration: 8849/59290
Iteration: 8850/59290
Iteration: 8851/59290
Iteration: 8852/59290
Iteration: 8853/59290
Iteration: 8854/59290
Iteration: 8855/59290
Iteration: 8856/59290
Iteration: 8857/59290
Iteration: 8858/59290
Iteration: 8859/59290
Iteration: 8860/59290
Iteration: 8861/59290
Iteration: 8862/59290
Iteration: 8863/59290
Iteration: 8864/59290

 15%|█▍        | 8862/59290 [07:05<27:52, 30.16it/s]

Iteration: 8865/59290
Iteration: 8866/59290
Iteration: 8867/59290
Iteration: 8868/59290
Iteration: 8869/59290
Iteration: 8870/59290
Iteration: 8871/59290
Iteration: 8872/59290
Iteration: 8873/59290
Iteration: 8874/59290
Iteration: 8875/59290
Iteration: 8876/59290
Iteration: 8877/59290
Iteration: 8878/59290
Iteration: 8879/59290
Iteration: 8880/59290
Iteration: 8881/59290
Iteration: 8882/59290
Iteration: 8883/59290
Iteration: 8884/59290
Iteration: 8885/59290
Iteration: 8886/59290
Iteration: 8887/59290
Iteration: 8888/59290

 15%|█▍        | 8886/59290 [07:05<23:28, 35.79it/s]

Iteration: 8889/59290
Iteration: 8890/59290
Iteration: 8891/59290
Iteration: 8892/59290
Iteration: 8893/59290
Iteration: 8894/59290
Iteration: 8895/59290
Iteration: 8896/59290
Iteration: 8897/59290
Iteration: 8898/59290
Iteration: 8899/59290
Iteration: 8900/59290
Iteration: 8901/59290
Iteration: 8902/59290
Iteration: 8903/59290
Iteration: 8904/59290
Iteration: 8905/59290
Iteration: 8906/59290
Iteration: 8907/59290
Iteration: 8908/59290
Iteration: 8909/59290
Iteration: 8910/59290
Iteration: 8911/59290
Iteration: 8912/59290

 15%|█▌        | 8910/59290 [07:05<20:22, 41.20it/s]

Iteration: 8913/59290
Iteration: 8914/59290
Iteration: 8915/59290
Iteration: 8916/59290
Iteration: 8917/59290
Iteration: 8918/59290
Iteration: 8919/59290
Iteration: 8920/59290
Iteration: 8921/59290
Iteration: 8922/59290
Iteration: 8923/59290
Iteration: 8924/59290
Iteration: 8925/59290
Iteration: 8926/59290
Iteration: 8927/59290
Iteration: 8928/59290
Iteration: 8929/59290
Iteration: 8930/59290
Iteration: 8931/59290
Iteration: 8932/59290
Iteration: 8933/59290
Iteration: 8934/59290
Iteration: 8935/59290
Iteration: 8936/59290

 15%|█▌        | 8934/59290 [07:07<27:54, 30.07it/s]

Iteration: 8937/59290
Iteration: 8938/59290
Iteration: 8939/59290
Iteration: 8940/59290
Iteration: 8941/59290
Iteration: 8942/59290
Iteration: 8943/59290
Iteration: 8944/59290
Iteration: 8945/59290
Iteration: 8946/59290
Iteration: 8947/59290
Iteration: 8948/59290
Iteration: 8949/59290
Iteration: 8950/59290
Iteration: 8951/59290
Iteration: 8952/59290
Iteration: 8953/59290
Iteration: 8954/59290
Iteration: 8955/59290
Iteration: 8956/59290
Iteration: 8957/59290
Iteration: 8958/59290
Iteration: 8959/59290
Iteration: 8960/59290

 15%|█▌        | 8958/59290 [07:09<42:11, 19.88it/s]

Iteration: 8961/59290
Iteration: 8962/59290
Iteration: 8963/59290
Iteration: 8964/59290
Iteration: 8965/59290
Iteration: 8966/59290
Iteration: 8967/59290
Iteration: 8968/59290
Iteration: 8969/59290
Iteration: 8970/59290
Iteration: 8971/59290
Iteration: 8972/59290
Iteration: 8973/59290
Iteration: 8974/59290
Iteration: 8975/59290
Iteration: 8976/59290
Iteration: 8977/59290
Iteration: 8978/59290
Iteration: 8979/59290
Iteration: 8980/59290
Iteration: 8981/59290
Iteration: 8982/59290
Iteration: 8983/59290
Iteration: 8984/59290

 15%|█▌        | 8982/59290 [07:09<35:57, 23.32it/s]

Iteration: 8985/59290
Iteration: 8986/59290
Iteration: 8987/59290
Iteration: 8988/59290
Iteration: 8989/59290
Iteration: 8990/59290
Iteration: 8991/59290
Iteration: 8992/59290
Iteration: 8993/59290
Iteration: 8994/59290
Iteration: 8995/59290
Iteration: 8996/59290
Iteration: 8997/59290
Iteration: 8998/59290
Iteration: 8999/59290
Iteration: 9000/59290
Iteration: 9001/59290
Iteration: 9002/59290
Iteration: 9003/59290
Iteration: 9004/59290
Iteration: 9005/59290
Iteration: 9006/59290
Iteration: 9007/59290
Iteration: 9008/59290

 15%|█▌        | 9006/59290 [07:10<29:07, 28.78it/s]

Iteration: 9009/59290
Iteration: 9010/59290
Iteration: 9011/59290
Iteration: 9012/59290
Iteration: 9013/59290
Iteration: 9014/59290
Iteration: 9015/59290
Iteration: 9016/59290
Iteration: 9017/59290
Iteration: 9018/59290
Iteration: 9019/59290
Iteration: 9020/59290
Iteration: 9021/59290
Iteration: 9022/59290
Iteration: 9023/59290
Iteration: 9024/59290
Iteration: 9025/59290
Iteration: 9026/59290
Iteration: 9027/59290
Iteration: 9028/59290
Iteration: 9029/59290
Iteration: 9030/59290
Iteration: 9031/59290
Iteration: 9032/59290

 15%|█▌        | 9030/59290 [07:10<24:28, 34.22it/s]

Iteration: 9033/59290
Iteration: 9034/59290
Iteration: 9035/59290
Iteration: 9036/59290
Iteration: 9037/59290
Iteration: 9038/59290
Iteration: 9039/59290
Iteration: 9040/59290
Iteration: 9041/59290
Iteration: 9042/59290
Iteration: 9043/59290
Iteration: 9044/59290
Iteration: 9045/59290
Iteration: 9046/59290
Iteration: 9047/59290
Iteration: 9048/59290
Iteration: 9049/59290
Iteration: 9050/59290
Iteration: 9051/59290
Iteration: 9052/59290
Iteration: 9053/59290
Iteration: 9054/59290
Iteration: 9055/59290
Iteration: 9056/59290

 15%|█▌        | 9054/59290 [07:10<21:05, 39.69it/s]

Iteration: 9057/59290
Iteration: 9058/59290
Iteration: 9059/59290
Iteration: 9060/59290
Iteration: 9061/59290
Iteration: 9062/59290
Iteration: 9063/59290
Iteration: 9064/59290
Iteration: 9065/59290
Iteration: 9066/59290
Iteration: 9067/59290
Iteration: 9068/59290
Iteration: 9069/59290
Iteration: 9070/59290
Iteration: 9071/59290
Iteration: 9072/59290
Iteration: 9073/59290
Iteration: 9074/59290
Iteration: 9075/59290
Iteration: 9076/59290
Iteration: 9077/59290
Iteration: 9078/59290
Iteration: 9079/59290
Iteration: 9080/59290

 15%|█▌        | 9078/59290 [07:11<18:39, 44.87it/s]

Iteration: 9081/59290
Iteration: 9082/59290
Iteration: 9083/59290
Iteration: 9084/59290
Iteration: 9085/59290
Iteration: 9086/59290
Iteration: 9087/59290
Iteration: 9088/59290
Iteration: 9089/59290
Iteration: 9090/59290
Iteration: 9091/59290
Iteration: 9092/59290
Iteration: 9093/59290
Iteration: 9094/59290
Iteration: 9095/59290
Iteration: 9096/59290
Iteration: 9097/59290
Iteration: 9098/59290
Iteration: 9099/59290
Iteration: 9100/59290
Iteration: 9101/59290
Iteration: 9102/59290
Iteration: 9103/59290
Iteration: 9104/59290

 15%|█▌        | 9102/59290 [07:11<16:55, 49.41it/s]

Iteration: 9105/59290
Iteration: 9106/59290
Iteration: 9107/59290
Iteration: 9108/59290
Iteration: 9109/59290
Iteration: 9110/59290
Iteration: 9111/59290
Iteration: 9112/59290
Iteration: 9113/59290
Iteration: 9114/59290
Iteration: 9115/59290
Iteration: 9116/59290
Iteration: 9117/59290
Iteration: 9118/59290
Iteration: 9119/59290
Iteration: 9120/59290
Iteration: 9121/59290
Iteration: 9122/59290
Iteration: 9123/59290
Iteration: 9124/59290
Iteration: 9125/59290
Iteration: 9126/59290
Iteration: 9127/59290
Iteration: 9128/59290

 15%|█▌        | 9126/59290 [07:12<15:44, 53.13it/s]

Iteration: 9129/59290
Iteration: 9130/59290
Iteration: 9131/59290
Iteration: 9132/59290
Iteration: 9133/59290
Iteration: 9134/59290
Iteration: 9135/59290
Iteration: 9136/59290
Iteration: 9137/59290
Iteration: 9138/59290
Iteration: 9139/59290
Iteration: 9140/59290
Iteration: 9141/59290
Iteration: 9142/59290
Iteration: 9143/59290
Iteration: 9144/59290
Iteration: 9145/59290
Iteration: 9146/59290
Iteration: 9147/59290
Iteration: 9148/59290
Iteration: 9149/59290
Iteration: 9150/59290
Iteration: 9151/59290
Iteration: 9152/59290

 15%|█▌        | 9150/59290 [07:13<24:48, 33.69it/s]

Iteration: 9153/59290
Iteration: 9154/59290
Iteration: 9155/59290
Iteration: 9156/59290
Iteration: 9157/59290
Iteration: 9158/59290
Iteration: 9159/59290
Iteration: 9160/59290
Iteration: 9161/59290
Iteration: 9162/59290
Iteration: 9163/59290
Iteration: 9164/59290
Iteration: 9165/59290
Iteration: 9166/59290
Iteration: 9167/59290
Iteration: 9168/59290
Iteration: 9169/59290
Iteration: 9170/59290
Iteration: 9171/59290
Iteration: 9172/59290
Iteration: 9173/59290
Iteration: 9174/59290
Iteration: 9175/59290
Iteration: 9176/59290

 15%|█▌        | 9174/59290 [07:15<38:36, 21.64it/s]

Iteration: 9177/59290
Iteration: 9178/59290
Iteration: 9179/59290
Iteration: 9180/59290
Iteration: 9181/59290
Iteration: 9182/59290
Iteration: 9183/59290
Iteration: 9184/59290
Iteration: 9185/59290
Iteration: 9186/59290
Iteration: 9187/59290
Iteration: 9188/59290
Iteration: 9189/59290
Iteration: 9190/59290
Iteration: 9191/59290
Iteration: 9192/59290
Iteration: 9193/59290
Iteration: 9194/59290
Iteration: 9195/59290
Iteration: 9196/59290
Iteration: 9197/59290
Iteration: 9198/59290
Iteration: 9199/59290
Iteration: 9200/59290

 16%|█▌        | 9198/59290 [07:15<30:53, 27.03it/s]

Iteration: 9201/59290
Iteration: 9202/59290
Iteration: 9203/59290
Iteration: 9204/59290
Iteration: 9205/59290
Iteration: 9206/59290
Iteration: 9207/59290
Iteration: 9208/59290
Iteration: 9209/59290
Iteration: 9210/59290
Iteration: 9211/59290
Iteration: 9212/59290
Iteration: 9213/59290
Iteration: 9214/59290
Iteration: 9215/59290
Iteration: 9216/59290
Iteration: 9217/59290
Iteration: 9218/59290
Iteration: 9219/59290
Iteration: 9220/59290
Iteration: 9221/59290
Iteration: 9222/59290
Iteration: 9223/59290
Iteration: 9224/59290

 16%|█▌        | 9222/59290 [07:16<27:35, 30.25it/s]

Iteration: 9225/59290
Iteration: 9226/59290
Iteration: 9227/59290
Iteration: 9228/59290
Iteration: 9229/59290
Iteration: 9230/59290
Iteration: 9231/59290
Iteration: 9232/59290
Iteration: 9233/59290
Iteration: 9234/59290
Iteration: 9235/59290
Iteration: 9236/59290
Iteration: 9237/59290
Iteration: 9238/59290
Iteration: 9239/59290
Iteration: 9240/59290
Iteration: 9241/59290
Iteration: 9242/59290
Iteration: 9243/59290
Iteration: 9244/59290
Iteration: 9245/59290
Iteration: 9246/59290
Iteration: 9247/59290
Iteration: 9248/59290

 16%|█▌        | 9246/59290 [07:16<23:10, 35.98it/s]

Iteration: 9249/59290
Iteration: 9250/59290
Iteration: 9251/59290
Iteration: 9252/59290
Iteration: 9253/59290
Iteration: 9254/59290
Iteration: 9255/59290
Iteration: 9256/59290
Iteration: 9257/59290
Iteration: 9258/59290
Iteration: 9259/59290
Iteration: 9260/59290
Iteration: 9261/59290
Iteration: 9262/59290
Iteration: 9263/59290
Iteration: 9264/59290
Iteration: 9265/59290
Iteration: 9266/59290
Iteration: 9267/59290
Iteration: 9268/59290
Iteration: 9269/59290
Iteration: 9270/59290
Iteration: 9271/59290
Iteration: 9272/59290

 16%|█▌        | 9270/59290 [07:17<20:08, 41.39it/s]

Iteration: 9273/59290
Iteration: 9274/59290
Iteration: 9275/59290
Iteration: 9276/59290
Iteration: 9277/59290
Iteration: 9278/59290
Iteration: 9279/59290
Iteration: 9280/59290
Iteration: 9281/59290
Iteration: 9282/59290
Iteration: 9283/59290
Iteration: 9284/59290
Iteration: 9285/59290
Iteration: 9286/59290
Iteration: 9287/59290
Iteration: 9288/59290
Iteration: 9289/59290
Iteration: 9290/59290
Iteration: 9291/59290
Iteration: 9292/59290
Iteration: 9293/59290
Iteration: 9294/59290
Iteration: 9295/59290
Iteration: 9296/59290

 16%|█▌        | 9294/59290 [07:17<18:00, 46.28it/s]

Iteration: 9297/59290
Iteration: 9298/59290
Iteration: 9299/59290
Iteration: 9300/59290
Iteration: 9301/59290
Iteration: 9302/59290
Iteration: 9303/59290
Iteration: 9304/59290
Iteration: 9305/59290
Iteration: 9306/59290
Iteration: 9307/59290
Iteration: 9308/59290
Iteration: 9309/59290
Iteration: 9310/59290
Iteration: 9311/59290
Iteration: 9312/59290
Iteration: 9313/59290
Iteration: 9314/59290
Iteration: 9315/59290
Iteration: 9316/59290
Iteration: 9317/59290
Iteration: 9318/59290
Iteration: 9319/59290
Iteration: 9320/59290

 16%|█▌        | 9318/59290 [07:17<16:37, 50.11it/s]

Iteration: 9321/59290
Iteration: 9322/59290
Iteration: 9323/59290
Iteration: 9324/59290
Iteration: 9325/59290
Iteration: 9326/59290
Iteration: 9327/59290
Iteration: 9328/59290
Iteration: 9329/59290
Iteration: 9330/59290
Iteration: 9331/59290
Iteration: 9332/59290
Iteration: 9333/59290
Iteration: 9334/59290
Iteration: 9335/59290
Iteration: 9336/59290
Iteration: 9337/59290
Iteration: 9338/59290
Iteration: 9339/59290
Iteration: 9340/59290
Iteration: 9341/59290
Iteration: 9342/59290
Iteration: 9343/59290
Iteration: 9344/59290

 16%|█▌        | 9342/59290 [07:18<15:35, 53.37it/s]

Iteration: 9345/59290
Iteration: 9346/59290
Iteration: 9347/59290
Iteration: 9348/59290
Iteration: 9349/59290
Iteration: 9350/59290
Iteration: 9351/59290
Iteration: 9352/59290
Iteration: 9353/59290
Iteration: 9354/59290
Iteration: 9355/59290
Iteration: 9356/59290
Iteration: 9357/59290
Iteration: 9358/59290
Iteration: 9359/59290
Iteration: 9360/59290
Iteration: 9361/59290
Iteration: 9362/59290
Iteration: 9363/59290
Iteration: 9364/59290
Iteration: 9365/59290
Iteration: 9366/59290
Iteration: 9367/59290
Iteration: 9368/59290

 16%|█▌        | 9366/59290 [07:18<14:47, 56.22it/s]

Iteration: 9369/59290
Iteration: 9370/59290
Iteration: 9371/59290
Iteration: 9372/59290
Iteration: 9373/59290
Iteration: 9374/59290
Iteration: 9375/59290
Iteration: 9376/59290
Iteration: 9377/59290
Iteration: 9378/59290
Iteration: 9379/59290
Iteration: 9380/59290
Iteration: 9381/59290
Iteration: 9382/59290
Iteration: 9383/59290
Iteration: 9384/59290
Iteration: 9385/59290
Iteration: 9386/59290
Iteration: 9387/59290
Iteration: 9388/59290
Iteration: 9389/59290
Iteration: 9390/59290
Iteration: 9391/59290
Iteration: 9392/59290

 16%|█▌        | 9390/59290 [07:19<14:32, 57.17it/s]

Iteration: 9393/59290
Iteration: 9394/59290
Iteration: 9395/59290
Iteration: 9396/59290
Iteration: 9397/59290
Iteration: 9398/59290
Iteration: 9399/59290
Iteration: 9400/59290
Iteration: 9401/59290
Iteration: 9402/59290
Iteration: 9403/59290
Iteration: 9404/59290
Iteration: 9405/59290
Iteration: 9406/59290
Iteration: 9407/59290
Iteration: 9408/59290
Iteration: 9409/59290
Iteration: 9410/59290
Iteration: 9411/59290
Iteration: 9412/59290
Iteration: 9413/59290
Iteration: 9414/59290
Iteration: 9415/59290
Iteration: 9416/59290

 16%|█▌        | 9414/59290 [07:19<14:24, 57.68it/s]

Iteration: 9417/59290
Iteration: 9418/59290
Iteration: 9419/59290
Iteration: 9420/59290
Iteration: 9421/59290
Iteration: 9422/59290
Iteration: 9423/59290
Iteration: 9424/59290
Iteration: 9425/59290
Iteration: 9426/59290
Iteration: 9427/59290
Iteration: 9428/59290
Iteration: 9429/59290
Iteration: 9430/59290
Iteration: 9431/59290
Iteration: 9432/59290
Iteration: 9433/59290
Iteration: 9434/59290
Iteration: 9435/59290
Iteration: 9436/59290
Iteration: 9437/59290
Iteration: 9438/59290
Iteration: 9439/59290
Iteration: 9440/59290

 16%|█▌        | 9438/59290 [07:19<14:05, 58.97it/s]

Iteration: 9441/59290
Iteration: 9442/59290
Iteration: 9443/59290
Iteration: 9444/59290
Iteration: 9445/59290
Iteration: 9446/59290
Iteration: 9447/59290
Iteration: 9448/59290
Iteration: 9449/59290
Iteration: 9450/59290
Iteration: 9451/59290
Iteration: 9452/59290
Iteration: 9453/59290
Iteration: 9454/59290
Iteration: 9455/59290
Iteration: 9456/59290
Iteration: 9457/59290
Iteration: 9458/59290
Iteration: 9459/59290
Iteration: 9460/59290
Iteration: 9461/59290
Iteration: 9462/59290
Iteration: 9463/59290
Iteration: 9464/59290

 16%|█▌        | 9462/59290 [07:20<13:44, 60.44it/s]

Iteration: 9465/59290
Iteration: 9466/59290
Iteration: 9467/59290
Iteration: 9468/59290
Iteration: 9469/59290
Iteration: 9470/59290
Iteration: 9471/59290
Iteration: 9472/59290
Iteration: 9473/59290
Iteration: 9474/59290
Iteration: 9475/59290
Iteration: 9476/59290
Iteration: 9477/59290
Iteration: 9478/59290
Iteration: 9479/59290
Iteration: 9480/59290
Iteration: 9481/59290
Iteration: 9482/59290
Iteration: 9483/59290
Iteration: 9484/59290
Iteration: 9485/59290
Iteration: 9486/59290
Iteration: 9487/59290
Iteration: 9488/59290

 16%|█▌        | 9486/59290 [07:20<13:42, 60.57it/s]

Iteration: 9489/59290
Iteration: 9490/59290
Iteration: 9491/59290
Iteration: 9492/59290
Iteration: 9493/59290
Iteration: 9494/59290
Iteration: 9495/59290
Iteration: 9496/59290
Iteration: 9497/59290
Iteration: 9498/59290
Iteration: 9499/59290
Iteration: 9500/59290
Iteration: 9501/59290
Iteration: 9502/59290
Iteration: 9503/59290
Iteration: 9504/59290
Iteration: 9505/59290
Iteration: 9506/59290
Iteration: 9507/59290
Iteration: 9508/59290
Iteration: 9509/59290
Iteration: 9510/59290
Iteration: 9511/59290
Iteration: 9512/59290

 16%|█▌        | 9510/59290 [07:22<25:11, 32.93it/s]

Iteration: 9513/59290
Iteration: 9514/59290
Iteration: 9515/59290
Iteration: 9516/59290
Iteration: 9517/59290
Iteration: 9518/59290
Iteration: 9519/59290
Iteration: 9520/59290
Iteration: 9521/59290
Iteration: 9522/59290
Iteration: 9523/59290
Iteration: 9524/59290
Iteration: 9525/59290
Iteration: 9526/59290
Iteration: 9527/59290
Iteration: 9528/59290
Iteration: 9529/59290
Iteration: 9530/59290
Iteration: 9531/59290
Iteration: 9532/59290
Iteration: 9533/59290
Iteration: 9534/59290
Iteration: 9535/59290
Iteration: 9536/59290

 16%|█▌        | 9534/59290 [07:24<39:38, 20.92it/s]

Iteration: 9537/59290
Iteration: 9538/59290
Iteration: 9539/59290
Iteration: 9540/59290
Iteration: 9541/59290
Iteration: 9542/59290
Iteration: 9543/59290
Iteration: 9544/59290
Iteration: 9545/59290
Iteration: 9546/59290
Iteration: 9547/59290
Iteration: 9548/59290
Iteration: 9549/59290
Iteration: 9550/59290
Iteration: 9551/59290
Iteration: 9552/59290
Iteration: 9553/59290
Iteration: 9554/59290
Iteration: 9555/59290
Iteration: 9556/59290
Iteration: 9557/59290
Iteration: 9558/59290
Iteration: 9559/59290
Iteration: 9560/59290

 16%|█▌        | 9558/59290 [07:24<31:45, 26.10it/s]

Iteration: 9561/59290
Iteration: 9562/59290
Iteration: 9563/59290
Iteration: 9564/59290
Iteration: 9565/59290
Iteration: 9566/59290
Iteration: 9567/59290
Iteration: 9568/59290
Iteration: 9569/59290
Iteration: 9570/59290
Iteration: 9571/59290
Iteration: 9572/59290
Iteration: 9573/59290
Iteration: 9574/59290
Iteration: 9575/59290
Iteration: 9576/59290
Iteration: 9577/59290
Iteration: 9578/59290
Iteration: 9579/59290
Iteration: 9580/59290
Iteration: 9581/59290
Iteration: 9582/59290
Iteration: 9583/59290
Iteration: 9584/59290

 16%|█▌        | 9582/59290 [07:25<26:55, 30.77it/s]

Iteration: 9585/59290
Iteration: 9586/59290
Iteration: 9587/59290
Iteration: 9588/59290
Iteration: 9589/59290
Iteration: 9590/59290
Iteration: 9591/59290
Iteration: 9592/59290
Iteration: 9593/59290
Iteration: 9594/59290
Iteration: 9595/59290
Iteration: 9596/59290
Iteration: 9597/59290
Iteration: 9598/59290
Iteration: 9599/59290
Iteration: 9600/59290
Iteration: 9601/59290
Iteration: 9602/59290
Iteration: 9603/59290
Iteration: 9604/59290
Iteration: 9605/59290
Iteration: 9606/59290
Iteration: 9607/59290
Iteration: 9608/59290

 16%|█▌        | 9606/59290 [07:25<22:47, 36.33it/s]

Iteration: 9609/59290
Iteration: 9610/59290
Iteration: 9611/59290
Iteration: 9612/59290
Iteration: 9613/59290
Iteration: 9614/59290
Iteration: 9615/59290
Iteration: 9616/59290
Iteration: 9617/59290
Iteration: 9618/59290
Iteration: 9619/59290
Iteration: 9620/59290
Iteration: 9621/59290
Iteration: 9622/59290
Iteration: 9623/59290
Iteration: 9624/59290
Iteration: 9625/59290
Iteration: 9626/59290
Iteration: 9627/59290
Iteration: 9628/59290
Iteration: 9629/59290
Iteration: 9630/59290
Iteration: 9631/59290
Iteration: 9632/59290

 16%|█▌        | 9630/59290 [07:25<20:06, 41.15it/s]

Iteration: 9633/59290
Iteration: 9634/59290
Iteration: 9635/59290
Iteration: 9636/59290
Iteration: 9637/59290
Iteration: 9638/59290
Iteration: 9639/59290
Iteration: 9640/59290
Iteration: 9641/59290
Iteration: 9642/59290
Iteration: 9643/59290
Iteration: 9644/59290
Iteration: 9645/59290
Iteration: 9646/59290
Iteration: 9647/59290
Iteration: 9648/59290
Iteration: 9649/59290
Iteration: 9650/59290
Iteration: 9651/59290
Iteration: 9652/59290
Iteration: 9653/59290
Iteration: 9654/59290
Iteration: 9655/59290
Iteration: 9656/59290

 16%|█▋        | 9654/59290 [07:26<18:03, 45.81it/s]

Iteration: 9657/59290
Iteration: 9658/59290
Iteration: 9659/59290
Iteration: 9660/59290
Iteration: 9661/59290
Iteration: 9662/59290
Iteration: 9663/59290
Iteration: 9664/59290
Iteration: 9665/59290
Iteration: 9666/59290
Iteration: 9667/59290
Iteration: 9668/59290
Iteration: 9669/59290
Iteration: 9670/59290
Iteration: 9671/59290
Iteration: 9672/59290
Iteration: 9673/59290
Iteration: 9674/59290
Iteration: 9675/59290
Iteration: 9676/59290
Iteration: 9677/59290
Iteration: 9678/59290
Iteration: 9679/59290
Iteration: 9680/59290

 16%|█▋        | 9678/59290 [07:26<16:39, 49.62it/s]

Iteration: 9681/59290
Iteration: 9682/59290
Iteration: 9683/59290
Iteration: 9684/59290
Iteration: 9685/59290
Iteration: 9686/59290
Iteration: 9687/59290
Iteration: 9688/59290
Iteration: 9689/59290
Iteration: 9690/59290
Iteration: 9691/59290
Iteration: 9692/59290
Iteration: 9693/59290
Iteration: 9694/59290
Iteration: 9695/59290
Iteration: 9696/59290
Iteration: 9697/59290
Iteration: 9698/59290
Iteration: 9699/59290
Iteration: 9700/59290
Iteration: 9701/59290
Iteration: 9702/59290
Iteration: 9703/59290
Iteration: 9704/59290

 16%|█▋        | 9702/59290 [07:27<15:31, 53.23it/s]

Iteration: 9705/59290
Iteration: 9706/59290
Iteration: 9707/59290
Iteration: 9708/59290
Iteration: 9709/59290
Iteration: 9710/59290
Iteration: 9711/59290
Iteration: 9712/59290
Iteration: 9713/59290
Iteration: 9714/59290
Iteration: 9715/59290
Iteration: 9716/59290
Iteration: 9717/59290
Iteration: 9718/59290
Iteration: 9719/59290
Iteration: 9720/59290
Iteration: 9721/59290
Iteration: 9722/59290
Iteration: 9723/59290
Iteration: 9724/59290
Iteration: 9725/59290
Iteration: 9726/59290
Iteration: 9727/59290
Iteration: 9728/59290

 16%|█▋        | 9726/59290 [07:27<14:46, 55.88it/s]

Iteration: 9729/59290
Iteration: 9730/59290
Iteration: 9731/59290
Iteration: 9732/59290
Iteration: 9733/59290
Iteration: 9734/59290
Iteration: 9735/59290
Iteration: 9736/59290
Iteration: 9737/59290
Iteration: 9738/59290
Iteration: 9739/59290
Iteration: 9740/59290
Iteration: 9741/59290
Iteration: 9742/59290
Iteration: 9743/59290
Iteration: 9744/59290
Iteration: 9745/59290
Iteration: 9746/59290
Iteration: 9747/59290
Iteration: 9748/59290
Iteration: 9749/59290
Iteration: 9750/59290
Iteration: 9751/59290
Iteration: 9752/59290

 16%|█▋        | 9750/59290 [07:27<14:19, 57.61it/s]

Iteration: 9753/59290
Iteration: 9754/59290
Iteration: 9755/59290
Iteration: 9756/59290
Iteration: 9757/59290
Iteration: 9758/59290
Iteration: 9759/59290
Iteration: 9760/59290
Iteration: 9761/59290
Iteration: 9762/59290
Iteration: 9763/59290
Iteration: 9764/59290
Iteration: 9765/59290
Iteration: 9766/59290
Iteration: 9767/59290
Iteration: 9768/59290
Iteration: 9769/59290
Iteration: 9770/59290
Iteration: 9771/59290
Iteration: 9772/59290
Iteration: 9773/59290
Iteration: 9774/59290
Iteration: 9775/59290
Iteration: 9776/59290

 16%|█▋        | 9774/59290 [07:29<23:57, 34.46it/s]

Iteration: 9777/59290
Iteration: 9778/59290
Iteration: 9779/59290
Iteration: 9780/59290
Iteration: 9781/59290
Iteration: 9782/59290
Iteration: 9783/59290
Iteration: 9784/59290
Iteration: 9785/59290
Iteration: 9786/59290
Iteration: 9787/59290
Iteration: 9788/59290
Iteration: 9789/59290
Iteration: 9790/59290
Iteration: 9791/59290
Iteration: 9792/59290
Iteration: 9793/59290
Iteration: 9794/59290
Iteration: 9795/59290
Iteration: 9796/59290
Iteration: 9797/59290
Iteration: 9798/59290
Iteration: 9799/59290
Iteration: 9800/59290

 17%|█▋        | 9798/59290 [07:31<37:50, 21.80it/s]

Iteration: 9801/59290
Iteration: 9802/59290
Iteration: 9803/59290
Iteration: 9804/59290
Iteration: 9805/59290
Iteration: 9806/59290
Iteration: 9807/59290
Iteration: 9808/59290
Iteration: 9809/59290
Iteration: 9810/59290
Iteration: 9811/59290
Iteration: 9812/59290
Iteration: 9813/59290
Iteration: 9814/59290
Iteration: 9815/59290
Iteration: 9816/59290
Iteration: 9817/59290
Iteration: 9818/59290
Iteration: 9819/59290
Iteration: 9820/59290
Iteration: 9821/59290
Iteration: 9822/59290
Iteration: 9823/59290
Iteration: 9824/59290

 17%|█▋        | 9822/59290 [07:31<30:46, 26.79it/s]

Iteration: 9825/59290
Iteration: 9826/59290
Iteration: 9827/59290
Iteration: 9828/59290
Iteration: 9829/59290
Iteration: 9830/59290
Iteration: 9831/59290
Iteration: 9832/59290
Iteration: 9833/59290
Iteration: 9834/59290
Iteration: 9835/59290
Iteration: 9836/59290
Iteration: 9837/59290
Iteration: 9838/59290
Iteration: 9839/59290
Iteration: 9840/59290
Iteration: 9841/59290
Iteration: 9842/59290
Iteration: 9843/59290
Iteration: 9844/59290
Iteration: 9845/59290
Iteration: 9846/59290
Iteration: 9847/59290
Iteration: 9848/59290

 17%|█▋        | 9846/59290 [07:32<26:35, 30.98it/s]

Iteration: 9849/59290
Iteration: 9850/59290
Iteration: 9851/59290
Iteration: 9852/59290
Iteration: 9853/59290
Iteration: 9854/59290
Iteration: 9855/59290
Iteration: 9856/59290
Iteration: 9857/59290
Iteration: 9858/59290
Iteration: 9859/59290
Iteration: 9860/59290
Iteration: 9861/59290
Iteration: 9862/59290
Iteration: 9863/59290
Iteration: 9864/59290
Iteration: 9865/59290
Iteration: 9866/59290
Iteration: 9867/59290
Iteration: 9868/59290
Iteration: 9869/59290
Iteration: 9870/59290
Iteration: 9871/59290
Iteration: 9872/59290

 17%|█▋        | 9870/59290 [07:32<22:42, 36.26it/s]

Iteration: 9873/59290
Iteration: 9874/59290
Iteration: 9875/59290
Iteration: 9876/59290
Iteration: 9877/59290
Iteration: 9878/59290
Iteration: 9879/59290
Iteration: 9880/59290
Iteration: 9881/59290
Iteration: 9882/59290
Iteration: 9883/59290
Iteration: 9884/59290
Iteration: 9885/59290
Iteration: 9886/59290
Iteration: 9887/59290
Iteration: 9888/59290
Iteration: 9889/59290
Iteration: 9890/59290
Iteration: 9891/59290
Iteration: 9892/59290
Iteration: 9893/59290
Iteration: 9894/59290
Iteration: 9895/59290
Iteration: 9896/59290

 17%|█▋        | 9894/59290 [07:32<19:49, 41.52it/s]

Iteration: 9897/59290
Iteration: 9898/59290
Iteration: 9899/59290
Iteration: 9900/59290
Iteration: 9901/59290
Iteration: 9902/59290
Iteration: 9903/59290
Iteration: 9904/59290
Iteration: 9905/59290
Iteration: 9906/59290
Iteration: 9907/59290
Iteration: 9908/59290
Iteration: 9909/59290
Iteration: 9910/59290
Iteration: 9911/59290
Iteration: 9912/59290
Iteration: 9913/59290
Iteration: 9914/59290
Iteration: 9915/59290
Iteration: 9916/59290
Iteration: 9917/59290
Iteration: 9918/59290
Iteration: 9919/59290
Iteration: 9920/59290

 17%|█▋        | 9918/59290 [07:33<17:48, 46.22it/s]

Iteration: 9921/59290
Iteration: 9922/59290
Iteration: 9923/59290
Iteration: 9924/59290
Iteration: 9925/59290
Iteration: 9926/59290
Iteration: 9927/59290
Iteration: 9928/59290
Iteration: 9929/59290
Iteration: 9930/59290
Iteration: 9931/59290
Iteration: 9932/59290
Iteration: 9933/59290
Iteration: 9934/59290
Iteration: 9935/59290
Iteration: 9936/59290
Iteration: 9937/59290
Iteration: 9938/59290
Iteration: 9939/59290
Iteration: 9940/59290
Iteration: 9941/59290
Iteration: 9942/59290
Iteration: 9943/59290
Iteration: 9944/59290

 17%|█▋        | 9942/59290 [07:33<16:27, 49.97it/s]

Iteration: 9945/59290
Iteration: 9946/59290
Iteration: 9947/59290
Iteration: 9948/59290
Iteration: 9949/59290
Iteration: 9950/59290
Iteration: 9951/59290
Iteration: 9952/59290
Iteration: 9953/59290
Iteration: 9954/59290
Iteration: 9955/59290
Iteration: 9956/59290
Iteration: 9957/59290
Iteration: 9958/59290
Iteration: 9959/59290
Iteration: 9960/59290
Iteration: 9961/59290
Iteration: 9962/59290
Iteration: 9963/59290
Iteration: 9964/59290
Iteration: 9965/59290
Iteration: 9966/59290
Iteration: 9967/59290
Iteration: 9968/59290

 17%|█▋        | 9966/59290 [07:35<27:03, 30.39it/s]

Iteration: 9969/59290
Iteration: 9970/59290
Iteration: 9971/59290
Iteration: 9972/59290
Iteration: 9973/59290
Iteration: 9974/59290
Iteration: 9975/59290
Iteration: 9976/59290
Iteration: 9977/59290
Iteration: 9978/59290
Iteration: 9979/59290
Iteration: 9980/59290
Iteration: 9981/59290
Iteration: 9982/59290
Iteration: 9983/59290
Iteration: 9984/59290
Iteration: 9985/59290
Iteration: 9986/59290
Iteration: 9987/59290
Iteration: 9988/59290
Iteration: 9989/59290
Iteration: 9990/59290
Iteration: 9991/59290
Iteration: 9992/59290

 17%|█▋        | 9990/59290 [07:37<39:57, 20.56it/s]

Iteration: 9993/59290
Iteration: 9994/59290
Iteration: 9995/59290
Iteration: 9996/59290
Iteration: 9997/59290
Iteration: 9998/59290
Iteration: 9999/59290
Iteration: 10000/59290
Iteration: 10001/59290
Iteration: 10002/59290
Iteration: 10003/59290
Iteration: 10004/59290
Iteration: 10005/59290
Iteration: 10006/59290
Iteration: 10007/59290
Iteration: 10008/59290
Iteration: 10009/59290
Iteration: 10010/59290
Iteration: 10011/59290
Iteration: 10012/59290
Iteration: 10013/59290
Iteration: 10014/59290
Iteration: 10015/59290
Iteration: 10016/59290

 17%|█▋        | 10014/59290 [07:37<35:29, 23.14it/s]

Iteration: 10017/59290
Iteration: 10018/59290
Iteration: 10019/59290
Iteration: 10020/59290
Iteration: 10021/59290
Iteration: 10022/59290
Iteration: 10023/59290
Iteration: 10024/59290
Iteration: 10025/59290
Iteration: 10026/59290
Iteration: 10027/59290
Iteration: 10028/59290
Iteration: 10029/59290
Iteration: 10030/59290
Iteration: 10031/59290
Iteration: 10032/59290
Iteration: 10033/59290
Iteration: 10034/59290
Iteration: 10035/59290
Iteration: 10036/59290
Iteration: 10037/59290
Iteration: 10038/59290
Iteration: 10039/59290
Iteration: 10040/59290

 17%|█▋        | 10038/59290 [07:38<28:44, 28.56it/s]

Iteration: 10041/59290
Iteration: 10042/59290
Iteration: 10043/59290
Iteration: 10044/59290
Iteration: 10045/59290
Iteration: 10046/59290
Iteration: 10047/59290
Iteration: 10048/59290
Iteration: 10049/59290
Iteration: 10050/59290
Iteration: 10051/59290
Iteration: 10052/59290
Iteration: 10053/59290
Iteration: 10054/59290
Iteration: 10055/59290
Iteration: 10056/59290
Iteration: 10057/59290
Iteration: 10058/59290
Iteration: 10059/59290
Iteration: 10060/59290
Iteration: 10061/59290
Iteration: 10062/59290
Iteration: 10063/59290
Iteration: 10064/59290

 17%|█▋        | 10062/59290 [07:38<24:04, 34.09it/s]

Iteration: 10065/59290
Iteration: 10066/59290
Iteration: 10067/59290
Iteration: 10068/59290
Iteration: 10069/59290
Iteration: 10070/59290
Iteration: 10071/59290
Iteration: 10072/59290
Iteration: 10073/59290
Iteration: 10074/59290
Iteration: 10075/59290
Iteration: 10076/59290
Iteration: 10077/59290
Iteration: 10078/59290
Iteration: 10079/59290
Iteration: 10080/59290
Iteration: 10081/59290
Iteration: 10082/59290
Iteration: 10083/59290
Iteration: 10084/59290
Iteration: 10085/59290
Iteration: 10086/59290
Iteration: 10087/59290
Iteration: 10088/59290

 17%|█▋        | 10086/59290 [07:39<20:44, 39.53it/s]

Iteration: 10089/59290
Iteration: 10090/59290
Iteration: 10091/59290
Iteration: 10092/59290
Iteration: 10093/59290
Iteration: 10094/59290
Iteration: 10095/59290
Iteration: 10096/59290
Iteration: 10097/59290
Iteration: 10098/59290
Iteration: 10099/59290
Iteration: 10100/59290
Iteration: 10101/59290
Iteration: 10102/59290
Iteration: 10103/59290
Iteration: 10104/59290
Iteration: 10105/59290
Iteration: 10106/59290
Iteration: 10107/59290
Iteration: 10108/59290
Iteration: 10109/59290
Iteration: 10110/59290
Iteration: 10111/59290
Iteration: 10112/59290

 17%|█▋        | 10110/59290 [07:39<18:22, 44.60it/s]

Iteration: 10113/59290
Iteration: 10114/59290
Iteration: 10115/59290
Iteration: 10116/59290
Iteration: 10117/59290
Iteration: 10118/59290
Iteration: 10119/59290
Iteration: 10120/59290
Iteration: 10121/59290
Iteration: 10122/59290
Iteration: 10123/59290
Iteration: 10124/59290
Iteration: 10125/59290
Iteration: 10126/59290
Iteration: 10127/59290
Iteration: 10128/59290
Iteration: 10129/59290
Iteration: 10130/59290
Iteration: 10131/59290
Iteration: 10132/59290
Iteration: 10133/59290
Iteration: 10134/59290
Iteration: 10135/59290
Iteration: 10136/59290

 17%|█▋        | 10134/59290 [07:39<16:44, 48.95it/s]

Iteration: 10137/59290
Iteration: 10138/59290
Iteration: 10139/59290
Iteration: 10140/59290
Iteration: 10141/59290
Iteration: 10142/59290
Iteration: 10143/59290
Iteration: 10144/59290
Iteration: 10145/59290
Iteration: 10146/59290
Iteration: 10147/59290
Iteration: 10148/59290
Iteration: 10149/59290
Iteration: 10150/59290
Iteration: 10151/59290
Iteration: 10152/59290
Iteration: 10153/59290
Iteration: 10154/59290
Iteration: 10155/59290
Iteration: 10156/59290
Iteration: 10157/59290
Iteration: 10158/59290
Iteration: 10159/59290
Iteration: 10160/59290

 17%|█▋        | 10158/59290 [07:40<15:59, 51.19it/s]

Iteration: 10161/59290
Iteration: 10162/59290
Iteration: 10163/59290
Iteration: 10164/59290
Iteration: 10165/59290
Iteration: 10166/59290
Iteration: 10167/59290
Iteration: 10168/59290
Iteration: 10169/59290
Iteration: 10170/59290
Iteration: 10171/59290
Iteration: 10172/59290
Iteration: 10173/59290
Iteration: 10174/59290
Iteration: 10175/59290
Iteration: 10176/59290
Iteration: 10177/59290
Iteration: 10178/59290
Iteration: 10179/59290
Iteration: 10180/59290
Iteration: 10181/59290
Iteration: 10182/59290
Iteration: 10183/59290
Iteration: 10184/59290

 17%|█▋        | 10182/59290 [07:41<25:05, 32.63it/s]

Iteration: 10185/59290
Iteration: 10186/59290
Iteration: 10187/59290
Iteration: 10188/59290
Iteration: 10189/59290
Iteration: 10190/59290
Iteration: 10191/59290
Iteration: 10192/59290
Iteration: 10193/59290
Iteration: 10194/59290
Iteration: 10195/59290
Iteration: 10196/59290
Iteration: 10197/59290
Iteration: 10198/59290
Iteration: 10199/59290
Iteration: 10200/59290
Iteration: 10201/59290
Iteration: 10202/59290
Iteration: 10203/59290
Iteration: 10204/59290
Iteration: 10205/59290
Iteration: 10206/59290
Iteration: 10207/59290
Iteration: 10208/59290

 17%|█▋        | 10206/59290 [07:44<44:03, 18.57it/s]

Iteration: 10209/59290
Iteration: 10210/59290
Iteration: 10211/59290
Iteration: 10212/59290
Iteration: 10213/59290
Iteration: 10214/59290
Iteration: 10215/59290
Iteration: 10216/59290
Iteration: 10217/59290
Iteration: 10218/59290
Iteration: 10219/59290
Iteration: 10220/59290
Iteration: 10221/59290
Iteration: 10222/59290
Iteration: 10223/59290
Iteration: 10224/59290
Iteration: 10225/59290
Iteration: 10226/59290
Iteration: 10227/59290
Iteration: 10228/59290
Iteration: 10229/59290
Iteration: 10230/59290
Iteration: 10231/59290
Iteration: 10232/59290

 17%|█▋        | 10230/59290 [07:44<34:41, 23.57it/s]

Iteration: 10233/59290
Iteration: 10234/59290
Iteration: 10235/59290
Iteration: 10236/59290
Iteration: 10237/59290
Iteration: 10238/59290
Iteration: 10239/59290
Iteration: 10240/59290
Iteration: 10241/59290
Iteration: 10242/59290
Iteration: 10243/59290
Iteration: 10244/59290
Iteration: 10245/59290
Iteration: 10246/59290
Iteration: 10247/59290
Iteration: 10248/59290
Iteration: 10249/59290
Iteration: 10250/59290
Iteration: 10251/59290
Iteration: 10252/59290
Iteration: 10253/59290
Iteration: 10254/59290
Iteration: 10255/59290
Iteration: 10256/59290

 17%|█▋        | 10254/59290 [07:44<28:07, 29.06it/s]

Iteration: 10257/59290
Iteration: 10258/59290
Iteration: 10259/59290
Iteration: 10260/59290
Iteration: 10261/59290
Iteration: 10262/59290
Iteration: 10263/59290
Iteration: 10264/59290
Iteration: 10265/59290
Iteration: 10266/59290
Iteration: 10267/59290
Iteration: 10268/59290
Iteration: 10269/59290
Iteration: 10270/59290
Iteration: 10271/59290
Iteration: 10272/59290
Iteration: 10273/59290
Iteration: 10274/59290
Iteration: 10275/59290
Iteration: 10276/59290
Iteration: 10277/59290
Iteration: 10278/59290
Iteration: 10279/59290
Iteration: 10280/59290

 17%|█▋        | 10278/59290 [07:45<23:36, 34.60it/s]

Iteration: 10281/59290
Iteration: 10282/59290
Iteration: 10283/59290
Iteration: 10284/59290
Iteration: 10285/59290
Iteration: 10286/59290
Iteration: 10287/59290
Iteration: 10288/59290
Iteration: 10289/59290
Iteration: 10290/59290
Iteration: 10291/59290
Iteration: 10292/59290
Iteration: 10293/59290
Iteration: 10294/59290
Iteration: 10295/59290
Iteration: 10296/59290
Iteration: 10297/59290
Iteration: 10298/59290
Iteration: 10299/59290
Iteration: 10300/59290
Iteration: 10301/59290
Iteration: 10302/59290
Iteration: 10303/59290
Iteration: 10304/59290

 17%|█▋        | 10302/59290 [07:45<20:19, 40.16it/s]

Iteration: 10305/59290
Iteration: 10306/59290
Iteration: 10307/59290
Iteration: 10308/59290
Iteration: 10309/59290
Iteration: 10310/59290
Iteration: 10311/59290
Iteration: 10312/59290
Iteration: 10313/59290
Iteration: 10314/59290
Iteration: 10315/59290
Iteration: 10316/59290
Iteration: 10317/59290
Iteration: 10318/59290
Iteration: 10319/59290
Iteration: 10320/59290
Iteration: 10321/59290
Iteration: 10322/59290
Iteration: 10323/59290
Iteration: 10324/59290
Iteration: 10325/59290
Iteration: 10326/59290
Iteration: 10327/59290
Iteration: 10328/59290

 17%|█▋        | 10326/59290 [07:46<18:08, 45.00it/s]

Iteration: 10329/59290
Iteration: 10330/59290
Iteration: 10331/59290
Iteration: 10332/59290
Iteration: 10333/59290
Iteration: 10334/59290
Iteration: 10335/59290
Iteration: 10336/59290
Iteration: 10337/59290
Iteration: 10338/59290
Iteration: 10339/59290
Iteration: 10340/59290
Iteration: 10341/59290
Iteration: 10342/59290
Iteration: 10343/59290
Iteration: 10344/59290
Iteration: 10345/59290
Iteration: 10346/59290
Iteration: 10347/59290
Iteration: 10348/59290
Iteration: 10349/59290
Iteration: 10350/59290
Iteration: 10351/59290
Iteration: 10352/59290

 17%|█▋        | 10350/59290 [07:46<16:27, 49.57it/s]

Iteration: 10353/59290
Iteration: 10354/59290
Iteration: 10355/59290
Iteration: 10356/59290
Iteration: 10357/59290
Iteration: 10358/59290
Iteration: 10359/59290
Iteration: 10360/59290
Iteration: 10361/59290
Iteration: 10362/59290
Iteration: 10363/59290
Iteration: 10364/59290
Iteration: 10365/59290
Iteration: 10366/59290
Iteration: 10367/59290
Iteration: 10368/59290
Iteration: 10369/59290
Iteration: 10370/59290
Iteration: 10371/59290
Iteration: 10372/59290
Iteration: 10373/59290
Iteration: 10374/59290
Iteration: 10375/59290
Iteration: 10376/59290

 17%|█▋        | 10374/59290 [07:46<15:21, 53.11it/s]

Iteration: 10377/59290
Iteration: 10378/59290
Iteration: 10379/59290
Iteration: 10380/59290
Iteration: 10381/59290
Iteration: 10382/59290
Iteration: 10383/59290
Iteration: 10384/59290
Iteration: 10385/59290
Iteration: 10386/59290
Iteration: 10387/59290
Iteration: 10388/59290
Iteration: 10389/59290
Iteration: 10390/59290
Iteration: 10391/59290
Iteration: 10392/59290
Iteration: 10393/59290
Iteration: 10394/59290
Iteration: 10395/59290
Iteration: 10396/59290
Iteration: 10397/59290
Iteration: 10398/59290
Iteration: 10399/59290
Iteration: 10400/59290

 18%|█▊        | 10398/59290 [07:47<14:42, 55.40it/s]

Iteration: 10401/59290
Iteration: 10402/59290
Iteration: 10403/59290
Iteration: 10404/59290
Iteration: 10405/59290
Iteration: 10406/59290
Iteration: 10407/59290
Iteration: 10408/59290
Iteration: 10409/59290
Iteration: 10410/59290
Iteration: 10411/59290
Iteration: 10412/59290
Iteration: 10413/59290
Iteration: 10414/59290
Iteration: 10415/59290
Iteration: 10416/59290
Iteration: 10417/59290
Iteration: 10418/59290
Iteration: 10419/59290
Iteration: 10420/59290
Iteration: 10421/59290
Iteration: 10422/59290
Iteration: 10423/59290
Iteration: 10424/59290

 18%|█▊        | 10422/59290 [07:47<14:11, 57.40it/s]

Iteration: 10425/59290
Iteration: 10426/59290
Iteration: 10427/59290
Iteration: 10428/59290
Iteration: 10429/59290
Iteration: 10430/59290
Iteration: 10431/59290
Iteration: 10432/59290
Iteration: 10433/59290
Iteration: 10434/59290
Iteration: 10435/59290
Iteration: 10436/59290
Iteration: 10437/59290
Iteration: 10438/59290
Iteration: 10439/59290
Iteration: 10440/59290
Iteration: 10441/59290
Iteration: 10442/59290
Iteration: 10443/59290
Iteration: 10444/59290
Iteration: 10445/59290
Iteration: 10446/59290
Iteration: 10447/59290
Iteration: 10448/59290

 18%|█▊        | 10446/59290 [07:48<13:50, 58.83it/s]

Iteration: 10449/59290
Iteration: 10450/59290
Iteration: 10451/59290
Iteration: 10452/59290
Iteration: 10453/59290
Iteration: 10454/59290
Iteration: 10455/59290
Iteration: 10456/59290
Iteration: 10457/59290
Iteration: 10458/59290
Iteration: 10459/59290
Iteration: 10460/59290
Iteration: 10461/59290
Iteration: 10462/59290
Iteration: 10463/59290
Iteration: 10464/59290
Iteration: 10465/59290
Iteration: 10466/59290
Iteration: 10467/59290
Iteration: 10468/59290
Iteration: 10469/59290
Iteration: 10470/59290
Iteration: 10471/59290
Iteration: 10472/59290

 18%|█▊        | 10470/59290 [07:48<13:28, 60.36it/s]

Iteration: 10473/59290
Iteration: 10474/59290
Iteration: 10475/59290
Iteration: 10476/59290
Iteration: 10477/59290
Iteration: 10478/59290
Iteration: 10479/59290
Iteration: 10480/59290
Iteration: 10481/59290
Iteration: 10482/59290
Iteration: 10483/59290
Iteration: 10484/59290
Iteration: 10485/59290
Iteration: 10486/59290
Iteration: 10487/59290
Iteration: 10488/59290
Iteration: 10489/59290
Iteration: 10490/59290
Iteration: 10491/59290
Iteration: 10492/59290
Iteration: 10493/59290
Iteration: 10494/59290
Iteration: 10495/59290
Iteration: 10496/59290

 18%|█▊        | 10494/59290 [07:48<13:20, 60.96it/s]

Iteration: 10497/59290
Iteration: 10498/59290
Iteration: 10499/59290
Iteration: 10500/59290
Iteration: 10501/59290
Iteration: 10502/59290
Iteration: 10503/59290
Iteration: 10504/59290
Iteration: 10505/59290
Iteration: 10506/59290
Iteration: 10507/59290
Iteration: 10508/59290
Iteration: 10509/59290
Iteration: 10510/59290
Iteration: 10511/59290
Iteration: 10512/59290
Iteration: 10513/59290
Iteration: 10514/59290
Iteration: 10515/59290
Iteration: 10516/59290
Iteration: 10517/59290
Iteration: 10518/59290
Iteration: 10519/59290
Iteration: 10520/59290

 18%|█▊        | 10518/59290 [07:50<25:31, 31.85it/s]

Iteration: 10521/59290
Iteration: 10522/59290
Iteration: 10523/59290
Iteration: 10524/59290
Iteration: 10525/59290
Iteration: 10526/59290
Iteration: 10527/59290
Iteration: 10528/59290
Iteration: 10529/59290
Iteration: 10530/59290
Iteration: 10531/59290
Iteration: 10532/59290
Iteration: 10533/59290
Iteration: 10534/59290
Iteration: 10535/59290
Iteration: 10536/59290
Iteration: 10537/59290
Iteration: 10538/59290
Iteration: 10539/59290
Iteration: 10540/59290
Iteration: 10541/59290
Iteration: 10542/59290
Iteration: 10543/59290
Iteration: 10544/59290

 18%|█▊        | 10542/59290 [07:52<39:01, 20.81it/s]

Iteration: 10545/59290
Iteration: 10546/59290
Iteration: 10547/59290
Iteration: 10548/59290
Iteration: 10549/59290
Iteration: 10550/59290
Iteration: 10551/59290
Iteration: 10552/59290
Iteration: 10553/59290
Iteration: 10554/59290
Iteration: 10555/59290
Iteration: 10556/59290
Iteration: 10557/59290
Iteration: 10558/59290
Iteration: 10559/59290
Iteration: 10560/59290
Iteration: 10561/59290
Iteration: 10562/59290
Iteration: 10563/59290
Iteration: 10564/59290
Iteration: 10565/59290
Iteration: 10566/59290
Iteration: 10567/59290
Iteration: 10568/59290

 18%|█▊        | 10566/59290 [07:52<31:09, 26.06it/s]

Iteration: 10569/59290
Iteration: 10570/59290
Iteration: 10571/59290
Iteration: 10572/59290
Iteration: 10573/59290
Iteration: 10574/59290
Iteration: 10575/59290
Iteration: 10576/59290
Iteration: 10577/59290
Iteration: 10578/59290
Iteration: 10579/59290
Iteration: 10580/59290
Iteration: 10581/59290
Iteration: 10582/59290
Iteration: 10583/59290
Iteration: 10584/59290
Iteration: 10585/59290
Iteration: 10586/59290
Iteration: 10587/59290
Iteration: 10588/59290
Iteration: 10589/59290
Iteration: 10590/59290
Iteration: 10591/59290
Iteration: 10592/59290

 18%|█▊        | 10590/59290 [07:53<28:48, 28.18it/s]

Iteration: 10593/59290
Iteration: 10594/59290
Iteration: 10595/59290
Iteration: 10596/59290
Iteration: 10597/59290
Iteration: 10598/59290
Iteration: 10599/59290
Iteration: 10600/59290
Iteration: 10601/59290
Iteration: 10602/59290
Iteration: 10603/59290
Iteration: 10604/59290
Iteration: 10605/59290
Iteration: 10606/59290
Iteration: 10607/59290
Iteration: 10608/59290
Iteration: 10609/59290
Iteration: 10610/59290
Iteration: 10611/59290
Iteration: 10612/59290
Iteration: 10613/59290
Iteration: 10614/59290
Iteration: 10615/59290
Iteration: 10616/59290

 18%|█▊        | 10614/59290 [07:53<23:58, 33.83it/s]

Iteration: 10617/59290
Iteration: 10618/59290
Iteration: 10619/59290
Iteration: 10620/59290
Iteration: 10621/59290
Iteration: 10622/59290
Iteration: 10623/59290
Iteration: 10624/59290
Iteration: 10625/59290
Iteration: 10626/59290
Iteration: 10627/59290
Iteration: 10628/59290
Iteration: 10629/59290
Iteration: 10630/59290
Iteration: 10631/59290
Iteration: 10632/59290
Iteration: 10633/59290
Iteration: 10634/59290
Iteration: 10635/59290
Iteration: 10636/59290
Iteration: 10637/59290
Iteration: 10638/59290
Iteration: 10639/59290
Iteration: 10640/59290

 18%|█▊        | 10638/59290 [07:54<20:39, 39.26it/s]

Iteration: 10641/59290
Iteration: 10642/59290
Iteration: 10643/59290
Iteration: 10644/59290
Iteration: 10645/59290
Iteration: 10646/59290
Iteration: 10647/59290
Iteration: 10648/59290
Iteration: 10649/59290
Iteration: 10650/59290
Iteration: 10651/59290
Iteration: 10652/59290
Iteration: 10653/59290
Iteration: 10654/59290
Iteration: 10655/59290
Iteration: 10656/59290
Iteration: 10657/59290
Iteration: 10658/59290
Iteration: 10659/59290
Iteration: 10660/59290
Iteration: 10661/59290
Iteration: 10662/59290
Iteration: 10663/59290
Iteration: 10664/59290

 18%|█▊        | 10662/59290 [07:54<18:14, 44.41it/s]

Iteration: 10665/59290
Iteration: 10666/59290
Iteration: 10667/59290
Iteration: 10668/59290
Iteration: 10669/59290
Iteration: 10670/59290
Iteration: 10671/59290
Iteration: 10672/59290
Iteration: 10673/59290
Iteration: 10674/59290
Iteration: 10675/59290
Iteration: 10676/59290
Iteration: 10677/59290
Iteration: 10678/59290
Iteration: 10679/59290
Iteration: 10680/59290
Iteration: 10681/59290
Iteration: 10682/59290
Iteration: 10683/59290
Iteration: 10684/59290
Iteration: 10685/59290
Iteration: 10686/59290
Iteration: 10687/59290
Iteration: 10688/59290

 18%|█▊        | 10686/59290 [07:55<16:40, 48.60it/s]

Iteration: 10689/59290
Iteration: 10690/59290
Iteration: 10691/59290
Iteration: 10692/59290
Iteration: 10693/59290
Iteration: 10694/59290
Iteration: 10695/59290
Iteration: 10696/59290
Iteration: 10697/59290
Iteration: 10698/59290
Iteration: 10699/59290
Iteration: 10700/59290
Iteration: 10701/59290
Iteration: 10702/59290
Iteration: 10703/59290
Iteration: 10704/59290
Iteration: 10705/59290
Iteration: 10706/59290
Iteration: 10707/59290
Iteration: 10708/59290
Iteration: 10709/59290
Iteration: 10710/59290
Iteration: 10711/59290
Iteration: 10712/59290

 18%|█▊        | 10710/59290 [07:55<15:27, 52.38it/s]

Iteration: 10713/59290
Iteration: 10714/59290
Iteration: 10715/59290
Iteration: 10716/59290
Iteration: 10717/59290
Iteration: 10718/59290
Iteration: 10719/59290
Iteration: 10720/59290
Iteration: 10721/59290
Iteration: 10722/59290
Iteration: 10723/59290
Iteration: 10724/59290
Iteration: 10725/59290
Iteration: 10726/59290
Iteration: 10727/59290
Iteration: 10728/59290
Iteration: 10729/59290
Iteration: 10730/59290
Iteration: 10731/59290
Iteration: 10732/59290
Iteration: 10733/59290
Iteration: 10734/59290
Iteration: 10735/59290
Iteration: 10736/59290

 18%|█▊        | 10734/59290 [07:55<14:36, 55.42it/s]

Iteration: 10737/59290
Iteration: 10738/59290
Iteration: 10739/59290
Iteration: 10740/59290
Iteration: 10741/59290
Iteration: 10742/59290
Iteration: 10743/59290
Iteration: 10744/59290
Iteration: 10745/59290
Iteration: 10746/59290
Iteration: 10747/59290
Iteration: 10748/59290
Iteration: 10749/59290
Iteration: 10750/59290
Iteration: 10751/59290
Iteration: 10752/59290
Iteration: 10753/59290
Iteration: 10754/59290
Iteration: 10755/59290
Iteration: 10756/59290
Iteration: 10757/59290
Iteration: 10758/59290
Iteration: 10759/59290
Iteration: 10760/59290

 18%|█▊        | 10758/59290 [07:56<14:04, 57.44it/s]

Iteration: 10761/59290
Iteration: 10762/59290
Iteration: 10763/59290
Iteration: 10764/59290
Iteration: 10765/59290
Iteration: 10766/59290
Iteration: 10767/59290
Iteration: 10768/59290
Iteration: 10769/59290
Iteration: 10770/59290
Iteration: 10771/59290
Iteration: 10772/59290
Iteration: 10773/59290
Iteration: 10774/59290
Iteration: 10775/59290
Iteration: 10776/59290
Iteration: 10777/59290
Iteration: 10778/59290
Iteration: 10779/59290
Iteration: 10780/59290
Iteration: 10781/59290
Iteration: 10782/59290
Iteration: 10784/59290

 18%|█▊        | 10781/59290 [07:56<14:10, 57.06it/s]

Iteration: 10785/59290
Iteration: 10786/59290
Iteration: 10787/59290
Iteration: 10788/59290
Iteration: 10789/59290
Iteration: 10790/59290
Iteration: 10791/59290
Iteration: 10792/59290

 18%|█▊        | 10789/59290 [07:58<30:34, 26.44it/s]

Iteration: 10793/59290
Iteration: 10794/59290
Iteration: 10795/59290
Iteration: 10796/59290
Iteration: 10797/59290
Iteration: 10798/59290
Iteration: 10799/59290
Iteration: 10800/59290
Iteration: 10801/59290
Iteration: 10802/59290
Iteration: 10803/59290
Iteration: 10804/59290
Iteration: 10805/59290
Iteration: 10806/59290
Iteration: 10807/59290
Iteration: 10808/59290
Iteration: 10809/59290
Iteration: 10810/59290
Iteration: 10811/59290
Iteration: 10812/59290
Iteration: 10813/59290
Iteration: 10814/59290
Iteration: 10815/59290
Iteration: 10816/59290

 18%|█▊        | 10813/59290 [08:00<45:32, 17.74it/s]

Iteration: 10817/59290
Iteration: 10818/59290
Iteration: 10819/59290
Iteration: 10820/59290
Iteration: 10821/59290
Iteration: 10822/59290
Iteration: 10823/59290
Iteration: 10824/59290
Iteration: 10825/59290
Iteration: 10826/59290
Iteration: 10827/59290
Iteration: 10828/59290
Iteration: 10829/59290
Iteration: 10830/59290
Iteration: 10831/59290
Iteration: 10832/59290
Iteration: 10833/59290
Iteration: 10834/59290
Iteration: 10835/59290
Iteration: 10836/59290
Iteration: 10837/59290
Iteration: 10838/59290
Iteration: 10839/59290
Iteration: 10840/59290

 18%|█▊        | 10837/59290 [08:00<37:21, 21.62it/s]

Iteration: 10841/59290
Iteration: 10842/59290
Iteration: 10843/59290
Iteration: 10844/59290
Iteration: 10845/59290
Iteration: 10846/59290
Iteration: 10847/59290
Iteration: 10848/59290
Iteration: 10849/59290
Iteration: 10850/59290
Iteration: 10851/59290
Iteration: 10852/59290
Iteration: 10853/59290
Iteration: 10854/59290
Iteration: 10855/59290
Iteration: 10856/59290
Iteration: 10857/59290
Iteration: 10858/59290
Iteration: 10859/59290
Iteration: 10860/59290
Iteration: 10861/59290
Iteration: 10862/59290
Iteration: 10863/59290
Iteration: 10864/59290

 18%|█▊        | 10861/59290 [08:01<29:29, 27.37it/s]

Iteration: 10865/59290
Iteration: 10866/59290
Iteration: 10867/59290
Iteration: 10868/59290
Iteration: 10869/59290
Iteration: 10870/59290
Iteration: 10871/59290
Iteration: 10872/59290
Iteration: 10873/59290
Iteration: 10874/59290
Iteration: 10875/59290
Iteration: 10876/59290
Iteration: 10877/59290
Iteration: 10878/59290
Iteration: 10879/59290
Iteration: 10880/59290
Iteration: 10881/59290
Iteration: 10882/59290
Iteration: 10883/59290
Iteration: 10884/59290
Iteration: 10885/59290
Iteration: 10886/59290
Iteration: 10887/59290
Iteration: 10888/59290

 18%|█▊        | 10885/59290 [08:01<24:08, 33.41it/s]

Iteration: 10889/59290
Iteration: 10890/59290
Iteration: 10891/59290
Iteration: 10892/59290
Iteration: 10893/59290
Iteration: 10894/59290
Iteration: 10895/59290
Iteration: 10896/59290
Iteration: 10897/59290
Iteration: 10898/59290
Iteration: 10899/59290
Iteration: 10900/59290
Iteration: 10901/59290
Iteration: 10902/59290
Iteration: 10903/59290
Iteration: 10904/59290
Iteration: 10905/59290
Iteration: 10906/59290
Iteration: 10907/59290
Iteration: 10908/59290
Iteration: 10909/59290
Iteration: 10910/59290
Iteration: 10911/59290
Iteration: 10912/59290

 18%|█▊        | 10909/59290 [08:01<20:33, 39.24it/s]

Iteration: 10913/59290
Iteration: 10914/59290
Iteration: 10915/59290
Iteration: 10916/59290
Iteration: 10917/59290
Iteration: 10918/59290
Iteration: 10919/59290
Iteration: 10920/59290
Iteration: 10921/59290
Iteration: 10922/59290
Iteration: 10923/59290
Iteration: 10924/59290
Iteration: 10925/59290
Iteration: 10926/59290
Iteration: 10927/59290
Iteration: 10928/59290
Iteration: 10929/59290
Iteration: 10930/59290
Iteration: 10931/59290
Iteration: 10932/59290
Iteration: 10933/59290
Iteration: 10934/59290
Iteration: 10935/59290
Iteration: 10936/59290

 18%|█▊        | 10933/59290 [08:03<29:27, 27.37it/s]

Iteration: 10937/59290
Iteration: 10938/59290
Iteration: 10939/59290
Iteration: 10940/59290
Iteration: 10941/59290
Iteration: 10942/59290
Iteration: 10943/59290
Iteration: 10944/59290
Iteration: 10945/59290
Iteration: 10946/59290
Iteration: 10947/59290
Iteration: 10948/59290
Iteration: 10949/59290
Iteration: 10950/59290
Iteration: 10951/59290
Iteration: 10952/59290
Iteration: 10953/59290
Iteration: 10954/59290
Iteration: 10955/59290
Iteration: 10956/59290
Iteration: 10957/59290
Iteration: 10958/59290
Iteration: 10959/59290
Iteration: 10960/59290

 18%|█▊        | 10957/59290 [08:05<42:47, 18.83it/s]

Iteration: 10961/59290
Iteration: 10962/59290
Iteration: 10963/59290
Iteration: 10964/59290
Iteration: 10965/59290
Iteration: 10966/59290
Iteration: 10967/59290
Iteration: 10968/59290
Iteration: 10969/59290
Iteration: 10970/59290
Iteration: 10971/59290
Iteration: 10972/59290
Iteration: 10973/59290
Iteration: 10974/59290
Iteration: 10975/59290
Iteration: 10976/59290
Iteration: 10977/59290
Iteration: 10978/59290
Iteration: 10979/59290
Iteration: 10980/59290
Iteration: 10981/59290
Iteration: 10982/59290
Iteration: 10983/59290
Iteration: 10984/59290

 19%|█▊        | 10981/59290 [08:06<35:36, 22.61it/s]

Iteration: 10985/59290
Iteration: 10986/59290
Iteration: 10987/59290
Iteration: 10988/59290
Iteration: 10989/59290
Iteration: 10990/59290
Iteration: 10991/59290
Iteration: 10992/59290
Iteration: 10993/59290
Iteration: 10994/59290
Iteration: 10995/59290
Iteration: 10996/59290
Iteration: 10997/59290
Iteration: 10998/59290
Iteration: 10999/59290
Iteration: 11000/59290
Iteration: 11001/59290
Iteration: 11002/59290
Iteration: 11003/59290
Iteration: 11004/59290
Iteration: 11005/59290
Iteration: 11006/59290
Iteration: 11007/59290
Iteration: 11008/59290

 19%|█▊        | 11005/59290 [08:06<28:35, 28.15it/s]

Iteration: 11009/59290
Iteration: 11010/59290
Iteration: 11011/59290
Iteration: 11012/59290
Iteration: 11013/59290
Iteration: 11014/59290
Iteration: 11015/59290
Iteration: 11016/59290
Iteration: 11017/59290
Iteration: 11018/59290
Iteration: 11019/59290
Iteration: 11020/59290
Iteration: 11021/59290
Iteration: 11022/59290
Iteration: 11023/59290
Iteration: 11024/59290
Iteration: 11025/59290
Iteration: 11026/59290
Iteration: 11027/59290
Iteration: 11028/59290
Iteration: 11029/59290
Iteration: 11030/59290
Iteration: 11031/59290
Iteration: 11032/59290

 19%|█▊        | 11029/59290 [08:06<23:46, 33.83it/s]

Iteration: 11033/59290
Iteration: 11034/59290
Iteration: 11035/59290
Iteration: 11036/59290
Iteration: 11037/59290
Iteration: 11038/59290
Iteration: 11039/59290
Iteration: 11040/59290
Iteration: 11041/59290
Iteration: 11042/59290
Iteration: 11043/59290
Iteration: 11044/59290
Iteration: 11045/59290
Iteration: 11046/59290
Iteration: 11047/59290
Iteration: 11048/59290
Iteration: 11049/59290
Iteration: 11050/59290
Iteration: 11051/59290
Iteration: 11052/59290
Iteration: 11053/59290
Iteration: 11054/59290
Iteration: 11055/59290
Iteration: 11056/59290

 19%|█▊        | 11053/59290 [08:07<20:25, 39.37it/s]

Iteration: 11057/59290
Iteration: 11058/59290
Iteration: 11059/59290
Iteration: 11060/59290
Iteration: 11061/59290
Iteration: 11062/59290
Iteration: 11063/59290
Iteration: 11064/59290
Iteration: 11065/59290
Iteration: 11066/59290
Iteration: 11067/59290
Iteration: 11068/59290
Iteration: 11069/59290
Iteration: 11070/59290
Iteration: 11071/59290
Iteration: 11072/59290
Iteration: 11073/59290
Iteration: 11074/59290
Iteration: 11075/59290
Iteration: 11076/59290
Iteration: 11077/59290
Iteration: 11078/59290
Iteration: 11079/59290
Iteration: 11080/59290

 19%|█▊        | 11077/59290 [08:07<18:10, 44.22it/s]

Iteration: 11081/59290
Iteration: 11082/59290
Iteration: 11083/59290
Iteration: 11084/59290
Iteration: 11085/59290
Iteration: 11086/59290
Iteration: 11087/59290
Iteration: 11088/59290
Iteration: 11089/59290
Iteration: 11090/59290
Iteration: 11091/59290
Iteration: 11092/59290
Iteration: 11093/59290
Iteration: 11094/59290
Iteration: 11095/59290
Iteration: 11096/59290
Iteration: 11097/59290
Iteration: 11098/59290
Iteration: 11099/59290
Iteration: 11100/59290
Iteration: 11101/59290
Iteration: 11102/59290
Iteration: 11103/59290
Iteration: 11104/59290

 19%|█▊        | 11101/59290 [08:08<16:25, 48.88it/s]

Iteration: 11105/59290
Iteration: 11106/59290
Iteration: 11107/59290
Iteration: 11108/59290
Iteration: 11109/59290
Iteration: 11110/59290
Iteration: 11111/59290
Iteration: 11112/59290
Iteration: 11113/59290
Iteration: 11114/59290
Iteration: 11115/59290
Iteration: 11116/59290
Iteration: 11117/59290
Iteration: 11118/59290
Iteration: 11119/59290
Iteration: 11120/59290
Iteration: 11121/59290
Iteration: 11122/59290
Iteration: 11123/59290
Iteration: 11124/59290
Iteration: 11125/59290
Iteration: 11126/59290
Iteration: 11127/59290
Iteration: 11128/59290

 19%|█▉        | 11125/59290 [08:09<26:55, 29.82it/s]

Iteration: 11129/59290
Iteration: 11130/59290
Iteration: 11131/59290
Iteration: 11132/59290
Iteration: 11133/59290
Iteration: 11134/59290
Iteration: 11135/59290
Iteration: 11136/59290
Iteration: 11137/59290
Iteration: 11138/59290
Iteration: 11139/59290
Iteration: 11140/59290
Iteration: 11141/59290
Iteration: 11142/59290
Iteration: 11143/59290
Iteration: 11144/59290
Iteration: 11145/59290
Iteration: 11146/59290
Iteration: 11147/59290
Iteration: 11148/59290
Iteration: 11149/59290
Iteration: 11150/59290
Iteration: 11151/59290
Iteration: 11152/59290

 19%|█▉        | 11149/59290 [08:12<44:26, 18.05it/s]

Iteration: 11153/59290
Iteration: 11154/59290
Iteration: 11155/59290
Iteration: 11156/59290
Iteration: 11157/59290
Iteration: 11158/59290
Iteration: 11159/59290
Iteration: 11160/59290
Iteration: 11161/59290
Iteration: 11162/59290
Iteration: 11163/59290
Iteration: 11164/59290
Iteration: 11165/59290
Iteration: 11166/59290
Iteration: 11167/59290
Iteration: 11168/59290
Iteration: 11169/59290
Iteration: 11170/59290
Iteration: 11171/59290
Iteration: 11172/59290
Iteration: 11173/59290
Iteration: 11174/59290
Iteration: 11175/59290
Iteration: 11176/59290

 19%|█▉        | 11173/59290 [08:12<35:13, 22.76it/s]

Iteration: 11177/59290
Iteration: 11178/59290
Iteration: 11179/59290
Iteration: 11180/59290
Iteration: 11181/59290
Iteration: 11182/59290
Iteration: 11183/59290
Iteration: 11184/59290
Iteration: 11185/59290
Iteration: 11186/59290
Iteration: 11187/59290
Iteration: 11188/59290
Iteration: 11189/59290
Iteration: 11190/59290
Iteration: 11191/59290
Iteration: 11192/59290
Iteration: 11193/59290
Iteration: 11194/59290
Iteration: 11195/59290
Iteration: 11196/59290
Iteration: 11197/59290
Iteration: 11198/59290
Iteration: 11199/59290
Iteration: 11200/59290

 19%|█▉        | 11197/59290 [08:12<28:28, 28.16it/s]

Iteration: 11201/59290
Iteration: 11202/59290
Iteration: 11203/59290
Iteration: 11204/59290
Iteration: 11205/59290
Iteration: 11206/59290
Iteration: 11207/59290
Iteration: 11208/59290
Iteration: 11209/59290
Iteration: 11210/59290
Iteration: 11211/59290
Iteration: 11212/59290
Iteration: 11213/59290
Iteration: 11214/59290
Iteration: 11215/59290
Iteration: 11216/59290
Iteration: 11217/59290
Iteration: 11218/59290
Iteration: 11219/59290
Iteration: 11220/59290
Iteration: 11221/59290
Iteration: 11222/59290
Iteration: 11223/59290
Iteration: 11224/59290

 19%|█▉        | 11221/59290 [08:13<23:40, 33.83it/s]

Iteration: 11225/59290
Iteration: 11226/59290
Iteration: 11227/59290
Iteration: 11228/59290
Iteration: 11229/59290
Iteration: 11230/59290
Iteration: 11231/59290
Iteration: 11232/59290
Iteration: 11233/59290
Iteration: 11234/59290
Iteration: 11235/59290
Iteration: 11236/59290
Iteration: 11237/59290
Iteration: 11238/59290
Iteration: 11239/59290
Iteration: 11240/59290
Iteration: 11241/59290
Iteration: 11242/59290
Iteration: 11243/59290
Iteration: 11244/59290
Iteration: 11245/59290
Iteration: 11246/59290
Iteration: 11247/59290
Iteration: 11248/59290

 19%|█▉        | 11245/59290 [08:13<20:25, 39.21it/s]

Iteration: 11249/59290
Iteration: 11250/59290
Iteration: 11251/59290
Iteration: 11252/59290
Iteration: 11253/59290
Iteration: 11254/59290
Iteration: 11255/59290
Iteration: 11256/59290
Iteration: 11257/59290
Iteration: 11258/59290
Iteration: 11259/59290
Iteration: 11260/59290
Iteration: 11261/59290
Iteration: 11262/59290
Iteration: 11263/59290
Iteration: 11264/59290
Iteration: 11265/59290
Iteration: 11266/59290
Iteration: 11267/59290
Iteration: 11268/59290
Iteration: 11269/59290
Iteration: 11270/59290
Iteration: 11271/59290
Iteration: 11272/59290

 19%|█▉        | 11269/59290 [08:14<18:15, 43.83it/s]

Iteration: 11273/59290
Iteration: 11274/59290
Iteration: 11275/59290
Iteration: 11276/59290
Iteration: 11277/59290
Iteration: 11278/59290
Iteration: 11279/59290
Iteration: 11280/59290
Iteration: 11281/59290
Iteration: 11282/59290
Iteration: 11283/59290
Iteration: 11284/59290
Iteration: 11285/59290
Iteration: 11286/59290
Iteration: 11287/59290
Iteration: 11288/59290
Iteration: 11289/59290
Iteration: 11290/59290
Iteration: 11291/59290
Iteration: 11292/59290
Iteration: 11293/59290
Iteration: 11294/59290
Iteration: 11295/59290
Iteration: 11296/59290

 19%|█▉        | 11293/59290 [08:14<16:30, 48.47it/s]

Iteration: 11297/59290
Iteration: 11298/59290
Iteration: 11299/59290
Iteration: 11300/59290
Iteration: 11301/59290
Iteration: 11302/59290
Iteration: 11303/59290
Iteration: 11304/59290
Iteration: 11305/59290
Iteration: 11306/59290
Iteration: 11307/59290
Iteration: 11308/59290
Iteration: 11309/59290
Iteration: 11310/59290
Iteration: 11311/59290
Iteration: 11312/59290
Iteration: 11313/59290
Iteration: 11314/59290
Iteration: 11315/59290
Iteration: 11316/59290
Iteration: 11317/59290
Iteration: 11318/59290
Iteration: 11319/59290
Iteration: 11320/59290

 19%|█▉        | 11317/59290 [08:14<15:32, 51.46it/s]

Iteration: 11321/59290
Iteration: 11322/59290
Iteration: 11323/59290
Iteration: 11324/59290
Iteration: 11325/59290
Iteration: 11326/59290
Iteration: 11327/59290
Iteration: 11328/59290
Iteration: 11329/59290
Iteration: 11330/59290
Iteration: 11331/59290
Iteration: 11332/59290
Iteration: 11333/59290
Iteration: 11334/59290
Iteration: 11335/59290
Iteration: 11336/59290
Iteration: 11337/59290
Iteration: 11338/59290
Iteration: 11339/59290
Iteration: 11340/59290
Iteration: 11341/59290
Iteration: 11342/59290
Iteration: 11343/59290
Iteration: 11344/59290

 19%|█▉        | 11341/59290 [08:15<14:46, 54.06it/s]

Iteration: 11345/59290
Iteration: 11346/59290
Iteration: 11347/59290
Iteration: 11348/59290
Iteration: 11349/59290
Iteration: 11350/59290
Iteration: 11351/59290
Iteration: 11352/59290
Iteration: 11353/59290
Iteration: 11354/59290
Iteration: 11355/59290
Iteration: 11356/59290
Iteration: 11357/59290
Iteration: 11358/59290
Iteration: 11359/59290
Iteration: 11360/59290
Iteration: 11361/59290
Iteration: 11362/59290
Iteration: 11363/59290
Iteration: 11364/59290
Iteration: 11365/59290
Iteration: 11366/59290
Iteration: 11367/59290
Iteration: 11368/59290

 19%|█▉        | 11365/59290 [08:15<14:12, 56.24it/s]

Iteration: 11369/59290
Iteration: 11370/59290
Iteration: 11371/59290
Iteration: 11372/59290
Iteration: 11373/59290
Iteration: 11374/59290
Iteration: 11375/59290
Iteration: 11376/59290
Iteration: 11377/59290
Iteration: 11378/59290
Iteration: 11379/59290
Iteration: 11380/59290
Iteration: 11381/59290
Iteration: 11382/59290
Iteration: 11383/59290
Iteration: 11384/59290
Iteration: 11385/59290
Iteration: 11386/59290
Iteration: 11387/59290
Iteration: 11388/59290
Iteration: 11389/59290
Iteration: 11390/59290
Iteration: 11391/59290
Iteration: 11392/59290

 19%|█▉        | 11389/59290 [08:16<13:52, 57.55it/s]

Iteration: 11393/59290
Iteration: 11394/59290
Iteration: 11395/59290
Iteration: 11396/59290
Iteration: 11397/59290
Iteration: 11398/59290
Iteration: 11399/59290
Iteration: 11400/59290
Iteration: 11401/59290
Iteration: 11402/59290
Iteration: 11403/59290
Iteration: 11404/59290
Iteration: 11405/59290
Iteration: 11406/59290
Iteration: 11407/59290
Iteration: 11408/59290
Iteration: 11409/59290
Iteration: 11410/59290
Iteration: 11411/59290
Iteration: 11412/59290
Iteration: 11413/59290
Iteration: 11414/59290
Iteration: 11415/59290
Iteration: 11416/59290

 19%|█▉        | 11413/59290 [08:16<13:25, 59.42it/s]

Iteration: 11417/59290
Iteration: 11418/59290
Iteration: 11419/59290
Iteration: 11420/59290
Iteration: 11421/59290
Iteration: 11422/59290
Iteration: 11423/59290
Iteration: 11424/59290
Iteration: 11425/59290
Iteration: 11426/59290
Iteration: 11427/59290
Iteration: 11428/59290
Iteration: 11429/59290
Iteration: 11430/59290
Iteration: 11431/59290
Iteration: 11432/59290
Iteration: 11433/59290
Iteration: 11434/59290
Iteration: 11435/59290
Iteration: 11436/59290
Iteration: 11437/59290
Iteration: 11438/59290
Iteration: 11439/59290
Iteration: 11440/59290

 19%|█▉        | 11437/59290 [08:16<13:22, 59.66it/s]

Iteration: 11441/59290
Iteration: 11442/59290
Iteration: 11443/59290
Iteration: 11444/59290
Iteration: 11445/59290
Iteration: 11446/59290
Iteration: 11447/59290
Iteration: 11448/59290
Iteration: 11449/59290
Iteration: 11450/59290
Iteration: 11451/59290
Iteration: 11452/59290
Iteration: 11453/59290
Iteration: 11454/59290
Iteration: 11455/59290
Iteration: 11456/59290
Iteration: 11457/59290
Iteration: 11458/59290
Iteration: 11459/59290
Iteration: 11460/59290
Iteration: 11461/59290
Iteration: 11462/59290
Iteration: 11463/59290
Iteration: 11464/59290

 19%|█▉        | 11461/59290 [08:17<13:12, 60.35it/s]

Iteration: 11465/59290
Iteration: 11466/59290
Iteration: 11467/59290
Iteration: 11468/59290
Iteration: 11469/59290
Iteration: 11470/59290
Iteration: 11471/59290
Iteration: 11472/59290
Iteration: 11473/59290
Iteration: 11474/59290
Iteration: 11475/59290
Iteration: 11476/59290
Iteration: 11477/59290
Iteration: 11478/59290
Iteration: 11479/59290
Iteration: 11480/59290
Iteration: 11481/59290
Iteration: 11482/59290
Iteration: 11483/59290
Iteration: 11484/59290
Iteration: 11485/59290
Iteration: 11486/59290
Iteration: 11487/59290
Iteration: 11488/59290

 19%|█▉        | 11485/59290 [08:18<23:31, 33.86it/s]

Iteration: 11489/59290
Iteration: 11490/59290
Iteration: 11491/59290
Iteration: 11492/59290
Iteration: 11493/59290
Iteration: 11494/59290
Iteration: 11495/59290
Iteration: 11496/59290
Iteration: 11497/59290
Iteration: 11498/59290
Iteration: 11499/59290
Iteration: 11500/59290
Iteration: 11501/59290
Iteration: 11502/59290
Iteration: 11503/59290
Iteration: 11504/59290
Iteration: 11505/59290
Iteration: 11506/59290
Iteration: 11507/59290
Iteration: 11508/59290
Iteration: 11509/59290
Iteration: 11510/59290
Iteration: 11511/59290
Iteration: 11512/59290

 19%|█▉        | 11509/59290 [08:20<38:00, 20.96it/s]

Iteration: 11513/59290
Iteration: 11514/59290
Iteration: 11515/59290
Iteration: 11516/59290
Iteration: 11517/59290
Iteration: 11518/59290
Iteration: 11519/59290
Iteration: 11520/59290
Iteration: 11521/59290
Iteration: 11522/59290
Iteration: 11523/59290
Iteration: 11524/59290
Iteration: 11525/59290
Iteration: 11526/59290
Iteration: 11527/59290
Iteration: 11528/59290
Iteration: 11529/59290
Iteration: 11530/59290
Iteration: 11531/59290
Iteration: 11532/59290
Iteration: 11533/59290
Iteration: 11534/59290
Iteration: 11535/59290
Iteration: 11536/59290

 19%|█▉        | 11533/59290 [08:21<33:39, 23.65it/s]

Iteration: 11537/59290
Iteration: 11538/59290
Iteration: 11539/59290
Iteration: 11540/59290
Iteration: 11541/59290
Iteration: 11542/59290
Iteration: 11543/59290
Iteration: 11544/59290
Iteration: 11545/59290
Iteration: 11546/59290
Iteration: 11547/59290
Iteration: 11548/59290
Iteration: 11549/59290
Iteration: 11550/59290
Iteration: 11551/59290
Iteration: 11552/59290
Iteration: 11553/59290
Iteration: 11554/59290
Iteration: 11555/59290
Iteration: 11556/59290
Iteration: 11557/59290
Iteration: 11558/59290
Iteration: 11559/59290
Iteration: 11560/59290

 19%|█▉        | 11557/59290 [08:21<27:23, 29.04it/s]

Iteration: 11561/59290
Iteration: 11562/59290
Iteration: 11563/59290
Iteration: 11564/59290
Iteration: 11565/59290
Iteration: 11566/59290
Iteration: 11567/59290
Iteration: 11568/59290
Iteration: 11569/59290
Iteration: 11570/59290
Iteration: 11571/59290
Iteration: 11572/59290
Iteration: 11573/59290
Iteration: 11574/59290
Iteration: 11575/59290
Iteration: 11576/59290
Iteration: 11577/59290
Iteration: 11578/59290
Iteration: 11579/59290
Iteration: 11580/59290
Iteration: 11581/59290
Iteration: 11582/59290
Iteration: 11583/59290
Iteration: 11584/59290

 20%|█▉        | 11581/59290 [08:22<22:58, 34.60it/s]

Iteration: 11585/59290
Iteration: 11586/59290
Iteration: 11587/59290
Iteration: 11588/59290
Iteration: 11589/59290
Iteration: 11590/59290
Iteration: 11591/59290
Iteration: 11592/59290
Iteration: 11593/59290
Iteration: 11594/59290
Iteration: 11595/59290
Iteration: 11596/59290
Iteration: 11597/59290
Iteration: 11598/59290
Iteration: 11599/59290
Iteration: 11600/59290
Iteration: 11601/59290
Iteration: 11602/59290
Iteration: 11603/59290
Iteration: 11604/59290
Iteration: 11605/59290
Iteration: 11606/59290
Iteration: 11607/59290
Iteration: 11608/59290

 20%|█▉        | 11605/59290 [08:22<19:46, 40.19it/s]

Iteration: 11609/59290
Iteration: 11610/59290
Iteration: 11611/59290
Iteration: 11612/59290
Iteration: 11613/59290
Iteration: 11614/59290
Iteration: 11615/59290
Iteration: 11616/59290
Iteration: 11617/59290
Iteration: 11618/59290
Iteration: 11619/59290
Iteration: 11620/59290
Iteration: 11621/59290
Iteration: 11622/59290
Iteration: 11623/59290
Iteration: 11624/59290
Iteration: 11625/59290
Iteration: 11626/59290
Iteration: 11627/59290
Iteration: 11628/59290
Iteration: 11629/59290
Iteration: 11630/59290
Iteration: 11631/59290
Iteration: 11632/59290

 20%|█▉        | 11629/59290 [08:23<17:43, 44.80it/s]

Iteration: 11633/59290
Iteration: 11634/59290
Iteration: 11635/59290
Iteration: 11636/59290
Iteration: 11637/59290
Iteration: 11638/59290
Iteration: 11639/59290
Iteration: 11640/59290
Iteration: 11641/59290
Iteration: 11642/59290
Iteration: 11643/59290
Iteration: 11644/59290
Iteration: 11645/59290
Iteration: 11646/59290
Iteration: 11647/59290
Iteration: 11648/59290
Iteration: 11649/59290
Iteration: 11650/59290
Iteration: 11651/59290
Iteration: 11652/59290
Iteration: 11653/59290
Iteration: 11654/59290
Iteration: 11655/59290
Iteration: 11656/59290

 20%|█▉        | 11653/59290 [08:23<16:12, 48.97it/s]

Iteration: 11657/59290
Iteration: 11658/59290
Iteration: 11659/59290
Iteration: 11660/59290
Iteration: 11661/59290
Iteration: 11662/59290
Iteration: 11663/59290
Iteration: 11664/59290
Iteration: 11665/59290
Iteration: 11666/59290
Iteration: 11667/59290
Iteration: 11668/59290
Iteration: 11669/59290
Iteration: 11670/59290
Iteration: 11671/59290
Iteration: 11672/59290
Iteration: 11673/59290
Iteration: 11674/59290
Iteration: 11675/59290
Iteration: 11676/59290
Iteration: 11677/59290
Iteration: 11678/59290
Iteration: 11679/59290
Iteration: 11680/59290

 20%|█▉        | 11677/59290 [08:23<15:01, 52.84it/s]

Iteration: 11681/59290
Iteration: 11682/59290
Iteration: 11683/59290
Iteration: 11684/59290
Iteration: 11685/59290
Iteration: 11686/59290
Iteration: 11687/59290
Iteration: 11688/59290
Iteration: 11689/59290
Iteration: 11690/59290
Iteration: 11691/59290
Iteration: 11692/59290
Iteration: 11693/59290
Iteration: 11694/59290
Iteration: 11695/59290
Iteration: 11696/59290
Iteration: 11697/59290
Iteration: 11698/59290
Iteration: 11699/59290
Iteration: 11700/59290
Iteration: 11701/59290
Iteration: 11702/59290
Iteration: 11703/59290
Iteration: 11704/59290

 20%|█▉        | 11701/59290 [08:24<14:16, 55.58it/s]

Iteration: 11705/59290
Iteration: 11706/59290
Iteration: 11707/59290
Iteration: 11708/59290
Iteration: 11709/59290
Iteration: 11710/59290
Iteration: 11711/59290
Iteration: 11712/59290
Iteration: 11713/59290
Iteration: 11714/59290
Iteration: 11715/59290
Iteration: 11716/59290
Iteration: 11717/59290
Iteration: 11718/59290
Iteration: 11719/59290
Iteration: 11720/59290
Iteration: 11721/59290
Iteration: 11722/59290
Iteration: 11723/59290
Iteration: 11724/59290
Iteration: 11725/59290
Iteration: 11726/59290
Iteration: 11727/59290
Iteration: 11728/59290

 20%|█▉        | 11725/59290 [08:24<14:02, 56.43it/s]

Iteration: 11729/59290
Iteration: 11730/59290
Iteration: 11731/59290
Iteration: 11732/59290
Iteration: 11733/59290
Iteration: 11734/59290
Iteration: 11735/59290
Iteration: 11736/59290
Iteration: 11737/59290
Iteration: 11738/59290
Iteration: 11739/59290
Iteration: 11740/59290
Iteration: 11741/59290
Iteration: 11742/59290
Iteration: 11743/59290
Iteration: 11744/59290
Iteration: 11745/59290
Iteration: 11746/59290
Iteration: 11747/59290
Iteration: 11748/59290
Iteration: 11749/59290
Iteration: 11750/59290
Iteration: 11751/59290
Iteration: 11752/59290

 20%|█▉        | 11749/59290 [08:25<13:39, 58.02it/s]

Iteration: 11753/59290
Iteration: 11754/59290
Iteration: 11755/59290
Iteration: 11756/59290
Iteration: 11757/59290
Iteration: 11758/59290
Iteration: 11759/59290
Iteration: 11760/59290
Iteration: 11761/59290
Iteration: 11762/59290
Iteration: 11763/59290
Iteration: 11764/59290
Iteration: 11765/59290
Iteration: 11766/59290
Iteration: 11767/59290
Iteration: 11768/59290
Iteration: 11769/59290
Iteration: 11770/59290
Iteration: 11771/59290
Iteration: 11772/59290
Iteration: 11773/59290
Iteration: 11774/59290
Iteration: 11775/59290
Iteration: 11776/59290

 20%|█▉        | 11773/59290 [08:26<23:49, 33.24it/s]

Iteration: 11777/59290
Iteration: 11778/59290
Iteration: 11779/59290
Iteration: 11780/59290
Iteration: 11781/59290
Iteration: 11782/59290
Iteration: 11783/59290
Iteration: 11784/59290
Iteration: 11785/59290
Iteration: 11786/59290
Iteration: 11787/59290
Iteration: 11788/59290
Iteration: 11789/59290
Iteration: 11790/59290
Iteration: 11791/59290
Iteration: 11792/59290
Iteration: 11793/59290
Iteration: 11794/59290
Iteration: 11795/59290
Iteration: 11796/59290
Iteration: 11797/59290
Iteration: 11798/59290
Iteration: 11799/59290
Iteration: 11800/59290

 20%|█▉        | 11797/59290 [08:28<38:03, 20.79it/s]

Iteration: 11801/59290
Iteration: 11802/59290
Iteration: 11803/59290
Iteration: 11804/59290
Iteration: 11805/59290
Iteration: 11806/59290
Iteration: 11807/59290
Iteration: 11808/59290
Iteration: 11809/59290
Iteration: 11810/59290
Iteration: 11811/59290
Iteration: 11812/59290
Iteration: 11813/59290
Iteration: 11814/59290
Iteration: 11815/59290
Iteration: 11816/59290
Iteration: 11817/59290
Iteration: 11818/59290
Iteration: 11819/59290
Iteration: 11820/59290
Iteration: 11821/59290
Iteration: 11822/59290
Iteration: 11823/59290
Iteration: 11824/59290

 20%|█▉        | 11821/59290 [08:28<30:21, 26.06it/s]

Iteration: 11825/59290
Iteration: 11826/59290
Iteration: 11827/59290
Iteration: 11828/59290
Iteration: 11829/59290
Iteration: 11830/59290
Iteration: 11831/59290
Iteration: 11832/59290
Iteration: 11833/59290
Iteration: 11834/59290
Iteration: 11835/59290
Iteration: 11836/59290
Iteration: 11837/59290
Iteration: 11838/59290
Iteration: 11839/59290
Iteration: 11840/59290
Iteration: 11841/59290
Iteration: 11842/59290
Iteration: 11843/59290
Iteration: 11844/59290
Iteration: 11845/59290
Iteration: 11846/59290
Iteration: 11847/59290
Iteration: 11848/59290

 20%|█▉        | 11845/59290 [08:29<26:14, 30.13it/s]

Iteration: 11849/59290
Iteration: 11850/59290
Iteration: 11851/59290
Iteration: 11852/59290
Iteration: 11853/59290
Iteration: 11854/59290
Iteration: 11855/59290
Iteration: 11856/59290
Iteration: 11857/59290
Iteration: 11858/59290
Iteration: 11859/59290
Iteration: 11860/59290
Iteration: 11861/59290
Iteration: 11862/59290
Iteration: 11863/59290
Iteration: 11864/59290
Iteration: 11865/59290
Iteration: 11866/59290
Iteration: 11867/59290
Iteration: 11868/59290
Iteration: 11869/59290
Iteration: 11870/59290
Iteration: 11871/59290
Iteration: 11872/59290

 20%|██        | 11869/59290 [08:29<22:14, 35.54it/s]

Iteration: 11873/59290
Iteration: 11874/59290
Iteration: 11875/59290
Iteration: 11876/59290
Iteration: 11877/59290
Iteration: 11878/59290
Iteration: 11879/59290
Iteration: 11880/59290
Iteration: 11881/59290
Iteration: 11882/59290
Iteration: 11883/59290
Iteration: 11884/59290
Iteration: 11885/59290
Iteration: 11886/59290
Iteration: 11887/59290
Iteration: 11888/59290
Iteration: 11889/59290
Iteration: 11890/59290
Iteration: 11891/59290
Iteration: 11892/59290
Iteration: 11893/59290
Iteration: 11894/59290
Iteration: 11895/59290
Iteration: 11896/59290

 20%|██        | 11893/59290 [08:30<19:29, 40.53it/s]

Iteration: 11897/59290
Iteration: 11898/59290
Iteration: 11899/59290
Iteration: 11900/59290
Iteration: 11901/59290
Iteration: 11902/59290
Iteration: 11903/59290
Iteration: 11904/59290
Iteration: 11905/59290
Iteration: 11906/59290
Iteration: 11907/59290
Iteration: 11908/59290
Iteration: 11909/59290
Iteration: 11910/59290
Iteration: 11911/59290
Iteration: 11912/59290
Iteration: 11913/59290
Iteration: 11914/59290
Iteration: 11915/59290
Iteration: 11916/59290
Iteration: 11917/59290
Iteration: 11918/59290
Iteration: 11919/59290
Iteration: 11920/59290

 20%|██        | 11917/59290 [08:30<17:26, 45.26it/s]

Iteration: 11921/59290
Iteration: 11922/59290
Iteration: 11923/59290
Iteration: 11924/59290
Iteration: 11925/59290
Iteration: 11926/59290
Iteration: 11927/59290
Iteration: 11928/59290
Iteration: 11929/59290
Iteration: 11930/59290
Iteration: 11931/59290
Iteration: 11932/59290
Iteration: 11933/59290
Iteration: 11934/59290
Iteration: 11935/59290
Iteration: 11936/59290
Iteration: 11937/59290
Iteration: 11938/59290
Iteration: 11939/59290
Iteration: 11940/59290
Iteration: 11941/59290
Iteration: 11942/59290
Iteration: 11943/59290
Iteration: 11944/59290

 20%|██        | 11941/59290 [08:32<27:23, 28.81it/s]

Iteration: 11945/59290
Iteration: 11946/59290
Iteration: 11947/59290
Iteration: 11948/59290
Iteration: 11949/59290
Iteration: 11950/59290
Iteration: 11951/59290
Iteration: 11952/59290
Iteration: 11953/59290
Iteration: 11954/59290
Iteration: 11955/59290
Iteration: 11956/59290
Iteration: 11957/59290
Iteration: 11958/59290
Iteration: 11959/59290
Iteration: 11960/59290
Iteration: 11961/59290
Iteration: 11962/59290
Iteration: 11963/59290
Iteration: 11964/59290
Iteration: 11965/59290
Iteration: 11966/59290
Iteration: 11967/59290
Iteration: 11968/59290

 20%|██        | 11965/59290 [08:34<40:17, 19.58it/s]

Iteration: 11969/59290
Iteration: 11970/59290
Iteration: 11971/59290
Iteration: 11972/59290
Iteration: 11973/59290
Iteration: 11974/59290
Iteration: 11975/59290
Iteration: 11976/59290
Iteration: 11977/59290
Iteration: 11978/59290
Iteration: 11979/59290
Iteration: 11980/59290
Iteration: 11981/59290
Iteration: 11982/59290
Iteration: 11983/59290
Iteration: 11984/59290
Iteration: 11985/59290
Iteration: 11986/59290
Iteration: 11987/59290
Iteration: 11988/59290
Iteration: 11989/59290
Iteration: 11990/59290
Iteration: 11991/59290
Iteration: 11992/59290

 20%|██        | 11989/59290 [08:35<36:17, 21.72it/s]

Iteration: 11993/59290
Iteration: 11994/59290
Iteration: 11995/59290
Iteration: 11996/59290
Iteration: 11997/59290
Iteration: 11998/59290
Iteration: 11999/59290
Iteration: 12000/59290
Iteration: 12001/59290
Iteration: 12002/59290
Iteration: 12003/59290
Iteration: 12004/59290
Iteration: 12005/59290
Iteration: 12006/59290
Iteration: 12007/59290
Iteration: 12008/59290
Iteration: 12009/59290
Iteration: 12010/59290
Iteration: 12011/59290
Iteration: 12012/59290
Iteration: 12013/59290
Iteration: 12014/59290
Iteration: 12015/59290
Iteration: 12016/59290

 20%|██        | 12013/59290 [08:35<29:23, 26.81it/s]

Iteration: 12017/59290
Iteration: 12018/59290
Iteration: 12019/59290
Iteration: 12020/59290
Iteration: 12021/59290
Iteration: 12022/59290
Iteration: 12023/59290
Iteration: 12024/59290
Iteration: 12025/59290
Iteration: 12026/59290
Iteration: 12027/59290
Iteration: 12028/59290
Iteration: 12029/59290
Iteration: 12030/59290
Iteration: 12031/59290
Iteration: 12032/59290
Iteration: 12033/59290
Iteration: 12034/59290
Iteration: 12035/59290
Iteration: 12036/59290
Iteration: 12037/59290
Iteration: 12038/59290
Iteration: 12039/59290
Iteration: 12040/59290

 20%|██        | 12037/59290 [08:35<24:15, 32.47it/s]

Iteration: 12041/59290
Iteration: 12042/59290
Iteration: 12043/59290
Iteration: 12044/59290
Iteration: 12045/59290
Iteration: 12046/59290
Iteration: 12047/59290
Iteration: 12048/59290
Iteration: 12049/59290
Iteration: 12050/59290
Iteration: 12051/59290
Iteration: 12052/59290
Iteration: 12053/59290
Iteration: 12054/59290
Iteration: 12055/59290
Iteration: 12056/59290
Iteration: 12057/59290
Iteration: 12058/59290
Iteration: 12059/59290
Iteration: 12060/59290
Iteration: 12061/59290
Iteration: 12062/59290
Iteration: 12063/59290
Iteration: 12064/59290

 20%|██        | 12061/59290 [08:36<20:43, 37.98it/s]

Iteration: 12065/59290
Iteration: 12066/59290
Iteration: 12067/59290
Iteration: 12068/59290
Iteration: 12069/59290
Iteration: 12070/59290
Iteration: 12071/59290
Iteration: 12072/59290
Iteration: 12073/59290
Iteration: 12074/59290
Iteration: 12075/59290
Iteration: 12076/59290
Iteration: 12077/59290
Iteration: 12078/59290
Iteration: 12079/59290
Iteration: 12080/59290
Iteration: 12081/59290
Iteration: 12082/59290
Iteration: 12083/59290
Iteration: 12084/59290
Iteration: 12085/59290
Iteration: 12086/59290
Iteration: 12087/59290
Iteration: 12088/59290

 20%|██        | 12085/59290 [08:36<18:24, 42.74it/s]

Iteration: 12089/59290
Iteration: 12090/59290
Iteration: 12091/59290
Iteration: 12092/59290
Iteration: 12093/59290
Iteration: 12094/59290
Iteration: 12095/59290
Iteration: 12096/59290
Iteration: 12097/59290
Iteration: 12098/59290
Iteration: 12099/59290
Iteration: 12100/59290
Iteration: 12101/59290
Iteration: 12102/59290
Iteration: 12103/59290
Iteration: 12104/59290
Iteration: 12105/59290
Iteration: 12106/59290
Iteration: 12107/59290
Iteration: 12108/59290
Iteration: 12109/59290
Iteration: 12110/59290
Iteration: 12111/59290
Iteration: 12112/59290

 20%|██        | 12109/59290 [08:37<16:36, 47.33it/s]

Iteration: 12113/59290
Iteration: 12114/59290
Iteration: 12115/59290
Iteration: 12116/59290
Iteration: 12117/59290
Iteration: 12118/59290
Iteration: 12119/59290
Iteration: 12120/59290
Iteration: 12121/59290
Iteration: 12122/59290
Iteration: 12123/59290
Iteration: 12124/59290
Iteration: 12125/59290
Iteration: 12126/59290
Iteration: 12127/59290
Iteration: 12128/59290
Iteration: 12129/59290
Iteration: 12130/59290
Iteration: 12131/59290
Iteration: 12132/59290
Iteration: 12133/59290
Iteration: 12134/59290
Iteration: 12135/59290
Iteration: 12136/59290

 20%|██        | 12133/59290 [08:37<15:31, 50.62it/s]

Iteration: 12137/59290
Iteration: 12138/59290
Iteration: 12139/59290
Iteration: 12140/59290
Iteration: 12141/59290
Iteration: 12142/59290
Iteration: 12143/59290
Iteration: 12144/59290
Iteration: 12145/59290
Iteration: 12146/59290
Iteration: 12147/59290
Iteration: 12148/59290
Iteration: 12149/59290
Iteration: 12150/59290
Iteration: 12151/59290
Iteration: 12152/59290
Iteration: 12153/59290
Iteration: 12154/59290
Iteration: 12155/59290
Iteration: 12156/59290
Iteration: 12157/59290
Iteration: 12158/59290
Iteration: 12159/59290
Iteration: 12160/59290

 21%|██        | 12157/59290 [08:38<24:46, 31.71it/s]

Iteration: 12161/59290
Iteration: 12162/59290
Iteration: 12163/59290
Iteration: 12164/59290
Iteration: 12165/59290
Iteration: 12166/59290
Iteration: 12167/59290
Iteration: 12168/59290
Iteration: 12169/59290
Iteration: 12170/59290
Iteration: 12171/59290
Iteration: 12172/59290
Iteration: 12173/59290
Iteration: 12174/59290
Iteration: 12175/59290
Iteration: 12176/59290
Iteration: 12177/59290
Iteration: 12178/59290
Iteration: 12179/59290
Iteration: 12180/59290
Iteration: 12181/59290
Iteration: 12182/59290
Iteration: 12183/59290
Iteration: 12184/59290

 21%|██        | 12181/59290 [08:41<38:05, 20.61it/s]

Iteration: 12185/59290
Iteration: 12186/59290
Iteration: 12187/59290
Iteration: 12188/59290
Iteration: 12189/59290
Iteration: 12190/59290
Iteration: 12191/59290
Iteration: 12192/59290
Iteration: 12193/59290
Iteration: 12194/59290
Iteration: 12195/59290
Iteration: 12196/59290
Iteration: 12197/59290
Iteration: 12198/59290
Iteration: 12199/59290
Iteration: 12200/59290
Iteration: 12201/59290
Iteration: 12202/59290
Iteration: 12203/59290
Iteration: 12204/59290
Iteration: 12205/59290
Iteration: 12206/59290
Iteration: 12207/59290
Iteration: 12208/59290

 21%|██        | 12205/59290 [08:41<33:20, 23.54it/s]

Iteration: 12209/59290
Iteration: 12210/59290
Iteration: 12211/59290
Iteration: 12212/59290
Iteration: 12213/59290
Iteration: 12214/59290
Iteration: 12215/59290
Iteration: 12216/59290
Iteration: 12217/59290
Iteration: 12218/59290
Iteration: 12219/59290
Iteration: 12220/59290
Iteration: 12221/59290
Iteration: 12222/59290
Iteration: 12223/59290
Iteration: 12224/59290
Iteration: 12225/59290
Iteration: 12226/59290
Iteration: 12227/59290
Iteration: 12228/59290
Iteration: 12229/59290
Iteration: 12230/59290
Iteration: 12231/59290
Iteration: 12232/59290

 21%|██        | 12229/59290 [08:42<27:27, 28.57it/s]

Iteration: 12233/59290
Iteration: 12234/59290
Iteration: 12235/59290
Iteration: 12236/59290
Iteration: 12237/59290
Iteration: 12238/59290
Iteration: 12239/59290
Iteration: 12240/59290
Iteration: 12241/59290
Iteration: 12242/59290
Iteration: 12243/59290
Iteration: 12244/59290
Iteration: 12245/59290
Iteration: 12246/59290
Iteration: 12247/59290
Iteration: 12248/59290
Iteration: 12249/59290
Iteration: 12250/59290
Iteration: 12251/59290
Iteration: 12252/59290
Iteration: 12253/59290
Iteration: 12254/59290
Iteration: 12255/59290
Iteration: 12256/59290

 21%|██        | 12253/59290 [08:42<22:58, 34.12it/s]

Iteration: 12257/59290
Iteration: 12258/59290
Iteration: 12259/59290
Iteration: 12260/59290
Iteration: 12261/59290
Iteration: 12262/59290
Iteration: 12263/59290
Iteration: 12264/59290
Iteration: 12265/59290
Iteration: 12266/59290
Iteration: 12267/59290
Iteration: 12268/59290
Iteration: 12269/59290
Iteration: 12270/59290
Iteration: 12271/59290
Iteration: 12272/59290
Iteration: 12273/59290
Iteration: 12274/59290
Iteration: 12275/59290
Iteration: 12276/59290
Iteration: 12277/59290
Iteration: 12278/59290
Iteration: 12279/59290
Iteration: 12280/59290

 21%|██        | 12277/59290 [08:42<19:49, 39.53it/s]

Iteration: 12281/59290
Iteration: 12282/59290
Iteration: 12283/59290
Iteration: 12284/59290
Iteration: 12285/59290
Iteration: 12286/59290
Iteration: 12287/59290
Iteration: 12288/59290
Iteration: 12289/59290
Iteration: 12290/59290
Iteration: 12291/59290
Iteration: 12292/59290
Iteration: 12293/59290
Iteration: 12294/59290
Iteration: 12295/59290
Iteration: 12296/59290
Iteration: 12297/59290
Iteration: 12298/59290
Iteration: 12299/59290
Iteration: 12300/59290
Iteration: 12301/59290
Iteration: 12302/59290
Iteration: 12303/59290
Iteration: 12304/59290

 21%|██        | 12301/59290 [08:43<17:46, 44.08it/s]

Iteration: 12305/59290
Iteration: 12306/59290
Iteration: 12307/59290
Iteration: 12308/59290
Iteration: 12309/59290
Iteration: 12310/59290
Iteration: 12311/59290
Iteration: 12312/59290
Iteration: 12313/59290
Iteration: 12314/59290
Iteration: 12315/59290
Iteration: 12316/59290
Iteration: 12317/59290
Iteration: 12318/59290
Iteration: 12319/59290
Iteration: 12320/59290
Iteration: 12321/59290
Iteration: 12322/59290
Iteration: 12323/59290
Iteration: 12324/59290
Iteration: 12325/59290
Iteration: 12326/59290
Iteration: 12327/59290
Iteration: 12328/59290

 21%|██        | 12325/59290 [08:43<16:11, 48.35it/s]

Iteration: 12329/59290
Iteration: 12330/59290
Iteration: 12331/59290
Iteration: 12332/59290
Iteration: 12333/59290
Iteration: 12334/59290
Iteration: 12335/59290
Iteration: 12336/59290
Iteration: 12337/59290
Iteration: 12338/59290
Iteration: 12339/59290
Iteration: 12340/59290
Iteration: 12341/59290
Iteration: 12342/59290
Iteration: 12343/59290
Iteration: 12344/59290
Iteration: 12345/59290
Iteration: 12346/59290
Iteration: 12347/59290
Iteration: 12348/59290
Iteration: 12349/59290
Iteration: 12350/59290
Iteration: 12351/59290
Iteration: 12352/59290

 21%|██        | 12349/59290 [08:44<15:06, 51.81it/s]

Iteration: 12353/59290
Iteration: 12354/59290
Iteration: 12355/59290
Iteration: 12356/59290
Iteration: 12357/59290
Iteration: 12358/59290
Iteration: 12359/59290
Iteration: 12360/59290
Iteration: 12361/59290
Iteration: 12362/59290
Iteration: 12363/59290
Iteration: 12364/59290
Iteration: 12365/59290
Iteration: 12366/59290
Iteration: 12367/59290
Iteration: 12368/59290
Iteration: 12369/59290
Iteration: 12370/59290
Iteration: 12371/59290
Iteration: 12372/59290
Iteration: 12373/59290
Iteration: 12374/59290
Iteration: 12375/59290
Iteration: 12376/59290

 21%|██        | 12373/59290 [09:16<5:28:29,  2.38it/s]

Iteration: 12377/59290
Iteration: 12378/59290
Iteration: 12379/59290
Iteration: 12380/59290
Iteration: 12381/59290
Iteration: 12382/59290
Iteration: 12383/59290
Iteration: 12384/59290
Iteration: 12385/59290
Iteration: 12386/59290
Iteration: 12387/59290
Iteration: 12388/59290
Iteration: 12389/59290
Iteration: 12390/59290
Iteration: 12391/59290
Iteration: 12392/59290
Iteration: 12393/59290
Iteration: 12394/59290
Iteration: 12395/59290
Iteration: 12396/59290
Iteration: 12397/59290
Iteration: 12398/59290
Iteration: 12399/59290
Iteration: 12400/59290

 21%|██        | 12397/59290 [09:16<3:53:36,  3.35it/s]

Iteration: 12401/59290
Iteration: 12402/59290
Iteration: 12403/59290
Iteration: 12404/59290
Iteration: 12405/59290
Iteration: 12406/59290
Iteration: 12407/59290
Iteration: 12408/59290
Iteration: 12409/59290
Iteration: 12410/59290
Iteration: 12411/59290
Iteration: 12412/59290
Iteration: 12413/59290
Iteration: 12414/59290
Iteration: 12415/59290
Iteration: 12416/59290
Iteration: 12417/59290
Iteration: 12418/59290
Iteration: 12419/59290
Iteration: 12420/59290
Iteration: 12421/59290
Iteration: 12422/59290
Iteration: 12423/59290
Iteration: 12424/59290

 21%|██        | 12421/59290 [09:17<2:47:05,  4.67it/s]

Iteration: 12425/59290
Iteration: 12426/59290
Iteration: 12427/59290
Iteration: 12428/59290
Iteration: 12429/59290
Iteration: 12430/59290
Iteration: 12431/59290
Iteration: 12432/59290
Iteration: 12433/59290
Iteration: 12434/59290
Iteration: 12435/59290
Iteration: 12436/59290
Iteration: 12437/59290
Iteration: 12438/59290
Iteration: 12439/59290
Iteration: 12440/59290
Iteration: 12441/59290
Iteration: 12442/59290
Iteration: 12443/59290
Iteration: 12444/59290
Iteration: 12445/59290
Iteration: 12446/59290
Iteration: 12447/59290
Iteration: 12448/59290

 21%|██        | 12445/59290 [09:17<2:00:38,  6.47it/s]

Iteration: 12449/59290
Iteration: 12450/59290
Iteration: 12451/59290
Iteration: 12452/59290
Iteration: 12453/59290
Iteration: 12454/59290
Iteration: 12455/59290
Iteration: 12456/59290
Iteration: 12457/59290
Iteration: 12458/59290
Iteration: 12459/59290
Iteration: 12460/59290
Iteration: 12461/59290
Iteration: 12462/59290
Iteration: 12463/59290
Iteration: 12464/59290
Iteration: 12465/59290
Iteration: 12466/59290
Iteration: 12467/59290
Iteration: 12468/59290
Iteration: 12469/59290
Iteration: 12470/59290
Iteration: 12471/59290
Iteration: 12472/59290

 21%|██        | 12469/59290 [09:18<1:28:08,  8.85it/s]

Iteration: 12473/59290
Iteration: 12474/59290
Iteration: 12475/59290
Iteration: 12476/59290
Iteration: 12477/59290
Iteration: 12478/59290
Iteration: 12479/59290
Iteration: 12480/59290
Iteration: 12481/59290
Iteration: 12482/59290
Iteration: 12483/59290
Iteration: 12484/59290
Iteration: 12485/59290
Iteration: 12486/59290
Iteration: 12487/59290
Iteration: 12488/59290
Iteration: 12489/59290
Iteration: 12490/59290
Iteration: 12491/59290
Iteration: 12492/59290
Iteration: 12493/59290
Iteration: 12494/59290
Iteration: 12495/59290
Iteration: 12496/59290

 21%|██        | 12493/59290 [09:18<1:05:23, 11.93it/s]

Iteration: 12497/59290
Iteration: 12498/59290
Iteration: 12499/59290
Iteration: 12500/59290
Iteration: 12501/59290
Iteration: 12502/59290
Iteration: 12503/59290
Iteration: 12504/59290
Iteration: 12505/59290
Iteration: 12506/59290
Iteration: 12507/59290
Iteration: 12508/59290
Iteration: 12509/59290
Iteration: 12510/59290
Iteration: 12511/59290
Iteration: 12512/59290
Iteration: 12513/59290
Iteration: 12514/59290
Iteration: 12515/59290
Iteration: 12516/59290
Iteration: 12517/59290
Iteration: 12518/59290
Iteration: 12519/59290
Iteration: 12520/59290

 21%|██        | 12517/59290 [09:18<49:41, 15.69it/s]

Iteration: 12521/59290
Iteration: 12522/59290
Iteration: 12523/59290
Iteration: 12524/59290
Iteration: 12525/59290
Iteration: 12526/59290
Iteration: 12527/59290
Iteration: 12528/59290
Iteration: 12529/59290
Iteration: 12530/59290
Iteration: 12531/59290
Iteration: 12532/59290
Iteration: 12533/59290
Iteration: 12534/59290
Iteration: 12535/59290
Iteration: 12536/59290
Iteration: 12537/59290
Iteration: 12538/59290
Iteration: 12539/59290
Iteration: 12540/59290
Iteration: 12541/59290
Iteration: 12542/59290
Iteration: 12543/59290
Iteration: 12544/59290

 21%|██        | 12541/59290 [09:19<38:25, 20.28it/s]

Iteration: 12545/59290
Iteration: 12546/59290
Iteration: 12547/59290
Iteration: 12548/59290
Iteration: 12549/59290
Iteration: 12550/59290
Iteration: 12551/59290
Iteration: 12552/59290
Iteration: 12553/59290
Iteration: 12554/59290
Iteration: 12555/59290
Iteration: 12556/59290
Iteration: 12557/59290
Iteration: 12558/59290
Iteration: 12559/59290
Iteration: 12560/59290
Iteration: 12561/59290
Iteration: 12562/59290
Iteration: 12563/59290
Iteration: 12564/59290
Iteration: 12565/59290
Iteration: 12566/59290
Iteration: 12567/59290
Iteration: 12568/59290

 21%|██        | 12565/59290 [09:20<42:56, 18.13it/s]

Iteration: 12569/59290
Iteration: 12570/59290
Iteration: 12571/59290
Iteration: 12572/59290
Iteration: 12573/59290
Iteration: 12574/59290
Iteration: 12575/59290
Iteration: 12576/59290
Iteration: 12577/59290
Iteration: 12578/59290
Iteration: 12579/59290
Iteration: 12580/59290
Iteration: 12581/59290
Iteration: 12582/59290
Iteration: 12583/59290
Iteration: 12584/59290
Iteration: 12585/59290
Iteration: 12586/59290
Iteration: 12587/59290
Iteration: 12588/59290
Iteration: 12589/59290
Iteration: 12590/59290
Iteration: 12591/59290
Iteration: 12592/59290

 21%|██        | 12589/59290 [09:23<52:33, 14.81it/s]

Iteration: 12593/59290
Iteration: 12594/59290
Iteration: 12595/59290
Iteration: 12596/59290
Iteration: 12597/59290
Iteration: 12598/59290
Iteration: 12599/59290
Iteration: 12600/59290
Iteration: 12601/59290
Iteration: 12602/59290
Iteration: 12603/59290
Iteration: 12604/59290
Iteration: 12605/59290
Iteration: 12606/59290
Iteration: 12607/59290
Iteration: 12608/59290
Iteration: 12609/59290
Iteration: 12610/59290
Iteration: 12611/59290
Iteration: 12612/59290
Iteration: 12613/59290
Iteration: 12614/59290
Iteration: 12615/59290
Iteration: 12616/59290

 21%|██▏       | 12613/59290 [09:24<45:12, 17.21it/s]

Iteration: 12617/59290
Iteration: 12618/59290
Iteration: 12619/59290
Iteration: 12620/59290
Iteration: 12621/59290
Iteration: 12622/59290
Iteration: 12623/59290
Iteration: 12624/59290
Iteration: 12625/59290
Iteration: 12626/59290
Iteration: 12627/59290
Iteration: 12628/59290
Iteration: 12629/59290
Iteration: 12630/59290
Iteration: 12631/59290
Iteration: 12632/59290
Iteration: 12633/59290
Iteration: 12634/59290
Iteration: 12635/59290
Iteration: 12636/59290
Iteration: 12637/59290
Iteration: 12638/59290
Iteration: 12639/59290
Iteration: 12640/59290

 21%|██▏       | 12637/59290 [09:24<36:13, 21.47it/s]

Iteration: 12641/59290
Iteration: 12642/59290
Iteration: 12643/59290
Iteration: 12644/59290
Iteration: 12645/59290
Iteration: 12646/59290
Iteration: 12647/59290
Iteration: 12648/59290
Iteration: 12649/59290
Iteration: 12650/59290
Iteration: 12651/59290
Iteration: 12652/59290
Iteration: 12653/59290
Iteration: 12654/59290
Iteration: 12655/59290
Iteration: 12656/59290
Iteration: 12657/59290
Iteration: 12658/59290
Iteration: 12659/59290
Iteration: 12660/59290
Iteration: 12661/59290
Iteration: 12662/59290
Iteration: 12663/59290
Iteration: 12664/59290

 21%|██▏       | 12661/59290 [09:25<29:17, 26.53it/s]

Iteration: 12665/59290
Iteration: 12666/59290
Iteration: 12667/59290
Iteration: 12668/59290
Iteration: 12669/59290
Iteration: 12670/59290
Iteration: 12671/59290
Iteration: 12672/59290
Iteration: 12673/59290
Iteration: 12674/59290
Iteration: 12675/59290
Iteration: 12676/59290
Iteration: 12677/59290
Iteration: 12678/59290
Iteration: 12679/59290
Iteration: 12680/59290
Iteration: 12681/59290
Iteration: 12682/59290
Iteration: 12683/59290
Iteration: 12684/59290
Iteration: 12685/59290
Iteration: 12686/59290
Iteration: 12687/59290
Iteration: 12688/59290

 21%|██▏       | 12685/59290 [09:25<24:41, 31.46it/s]

Iteration: 12689/59290
Iteration: 12690/59290
Iteration: 12691/59290
Iteration: 12692/59290
Iteration: 12693/59290
Iteration: 12694/59290
Iteration: 12695/59290
Iteration: 12696/59290
Iteration: 12697/59290
Iteration: 12698/59290
Iteration: 12699/59290
Iteration: 12700/59290
Iteration: 12701/59290
Iteration: 12702/59290
Iteration: 12703/59290
Iteration: 12704/59290
Iteration: 12705/59290
Iteration: 12706/59290
Iteration: 12707/59290
Iteration: 12708/59290
Iteration: 12709/59290
Iteration: 12710/59290
Iteration: 12711/59290
Iteration: 12712/59290

 21%|██▏       | 12709/59290 [09:29<54:51, 14.15it/s]

Iteration: 12713/59290
Iteration: 12714/59290
Iteration: 12715/59290
Iteration: 12716/59290
Iteration: 12717/59290
Iteration: 12718/59290
Iteration: 12719/59290
Iteration: 12720/59290
Iteration: 12721/59290
Iteration: 12722/59290
Iteration: 12723/59290
Iteration: 12724/59290
Iteration: 12725/59290
Iteration: 12726/59290
Iteration: 12727/59290
Iteration: 12728/59290
Iteration: 12729/59290
Iteration: 12730/59290
Iteration: 12731/59290
Iteration: 12732/59290
Iteration: 12733/59290
Iteration: 12734/59290
Iteration: 12735/59290
Iteration: 12736/59290

 21%|██▏       | 12733/59290 [09:30<45:30, 17.05it/s]

Iteration: 12737/59290
Iteration: 12738/59290
Iteration: 12739/59290
Iteration: 12740/59290
Iteration: 12741/59290
Iteration: 12742/59290
Iteration: 12743/59290
Iteration: 12744/59290
Iteration: 12745/59290
Iteration: 12746/59290
Iteration: 12747/59290
Iteration: 12748/59290
Iteration: 12749/59290
Iteration: 12750/59290
Iteration: 12751/59290
Iteration: 12752/59290
Iteration: 12753/59290
Iteration: 12754/59290
Iteration: 12755/59290
Iteration: 12756/59290
Iteration: 12757/59290
Iteration: 12758/59290
Iteration: 12759/59290
Iteration: 12760/59290

 22%|██▏       | 12757/59290 [09:30<37:24, 20.73it/s]

Iteration: 12761/59290
Iteration: 12762/59290
Iteration: 12763/59290
Iteration: 12764/59290
Iteration: 12765/59290
Iteration: 12766/59290
Iteration: 12767/59290
Iteration: 12768/59290
Iteration: 12769/59290
Iteration: 12770/59290
Iteration: 12771/59290
Iteration: 12772/59290
Iteration: 12773/59290
Iteration: 12774/59290
Iteration: 12775/59290
Iteration: 12776/59290
Iteration: 12777/59290
Iteration: 12778/59290
Iteration: 12779/59290
Iteration: 12780/59290
Iteration: 12781/59290
Iteration: 12782/59290
Iteration: 12783/59290
Iteration: 12784/59290

 22%|██▏       | 12781/59290 [09:31<31:32, 24.57it/s]

Iteration: 12785/59290
Iteration: 12786/59290
Iteration: 12787/59290
Iteration: 12788/59290
Iteration: 12789/59290
Iteration: 12790/59290
Iteration: 12791/59290
Iteration: 12792/59290
Iteration: 12793/59290
Iteration: 12794/59290
Iteration: 12795/59290
Iteration: 12796/59290
Iteration: 12797/59290
Iteration: 12798/59290
Iteration: 12799/59290
Iteration: 12800/59290
Iteration: 12801/59290
Iteration: 12802/59290
Iteration: 12803/59290
Iteration: 12804/59290
Iteration: 12805/59290
Iteration: 12806/59290
Iteration: 12807/59290
Iteration: 12808/59290

 22%|██▏       | 12805/59290 [09:31<26:09, 29.61it/s]

Iteration: 12809/59290
Iteration: 12810/59290
Iteration: 12811/59290
Iteration: 12812/59290
Iteration: 12813/59290
Iteration: 12814/59290
Iteration: 12815/59290
Iteration: 12816/59290
Iteration: 12817/59290
Iteration: 12818/59290
Iteration: 12819/59290
Iteration: 12820/59290
Iteration: 12821/59290
Iteration: 12822/59290
Iteration: 12823/59290
Iteration: 12824/59290
Iteration: 12825/59290
Iteration: 12826/59290
Iteration: 12827/59290
Iteration: 12828/59290
Iteration: 12829/59290
Iteration: 12830/59290
Iteration: 12831/59290
Iteration: 12832/59290

 22%|██▏       | 12829/59290 [09:31<22:01, 35.15it/s]

Iteration: 12833/59290
Iteration: 12834/59290
Iteration: 12835/59290
Iteration: 12836/59290
Iteration: 12837/59290
Iteration: 12838/59290
Iteration: 12839/59290
Iteration: 12840/59290
Iteration: 12841/59290
Iteration: 12842/59290
Iteration: 12843/59290
Iteration: 12844/59290
Iteration: 12845/59290
Iteration: 12846/59290
Iteration: 12847/59290
Iteration: 12848/59290
Iteration: 12849/59290
Iteration: 12850/59290
Iteration: 12851/59290
Iteration: 12852/59290
Iteration: 12853/59290
Iteration: 12854/59290
Iteration: 12855/59290
Iteration: 12856/59290

 22%|██▏       | 12853/59290 [09:32<20:15, 38.22it/s]

Iteration: 12857/59290
Iteration: 12858/59290
Iteration: 12859/59290
Iteration: 12860/59290
Iteration: 12861/59290
Iteration: 12862/59290
Iteration: 12863/59290
Iteration: 12864/59290
Iteration: 12865/59290
Iteration: 12866/59290
Iteration: 12867/59290
Iteration: 12868/59290
Iteration: 12869/59290
Iteration: 12870/59290
Iteration: 12871/59290
Iteration: 12872/59290
Iteration: 12873/59290
Iteration: 12874/59290
Iteration: 12875/59290
Iteration: 12876/59290
Iteration: 12877/59290
Iteration: 12878/59290
Iteration: 12879/59290
Iteration: 12880/59290

 22%|██▏       | 12877/59290 [09:32<18:54, 40.90it/s]

Iteration: 12881/59290
Iteration: 12882/59290
Iteration: 12883/59290
Iteration: 12884/59290
Iteration: 12885/59290
Iteration: 12886/59290
Iteration: 12887/59290
Iteration: 12888/59290
Iteration: 12889/59290
Iteration: 12890/59290
Iteration: 12891/59290
Iteration: 12892/59290
Iteration: 12893/59290
Iteration: 12894/59290
Iteration: 12895/59290
Iteration: 12896/59290
Iteration: 12897/59290
Iteration: 12898/59290
Iteration: 12899/59290
Iteration: 12900/59290
Iteration: 12901/59290
Iteration: 12902/59290
Iteration: 12903/59290
Iteration: 12904/59290

 22%|██▏       | 12901/59290 [09:33<18:34, 41.62it/s]

Iteration: 12905/59290
Iteration: 12906/59290
Iteration: 12907/59290
Iteration: 12908/59290
Iteration: 12909/59290
Iteration: 12910/59290
Iteration: 12911/59290
Iteration: 12912/59290
Iteration: 12913/59290
Iteration: 12914/59290
Iteration: 12915/59290
Iteration: 12916/59290
Iteration: 12917/59290
Iteration: 12918/59290
Iteration: 12919/59290
Iteration: 12920/59290
Iteration: 12921/59290
Iteration: 12922/59290
Iteration: 12923/59290
Iteration: 12924/59290
Iteration: 12925/59290
Iteration: 12926/59290
Iteration: 12927/59290
Iteration: 12928/59290

 22%|██▏       | 12925/59290 [09:33<17:02, 45.36it/s]

Iteration: 12929/59290
Iteration: 12930/59290
Iteration: 12931/59290
Iteration: 12932/59290
Iteration: 12933/59290
Iteration: 12934/59290
Iteration: 12935/59290
Iteration: 12936/59290
Iteration: 12937/59290
Iteration: 12938/59290
Iteration: 12939/59290
Iteration: 12940/59290
Iteration: 12941/59290
Iteration: 12942/59290
Iteration: 12943/59290
Iteration: 12944/59290
Iteration: 12945/59290
Iteration: 12946/59290
Iteration: 12947/59290
Iteration: 12948/59290
Iteration: 12949/59290
Iteration: 12950/59290
Iteration: 12951/59290
Iteration: 12952/59290

 22%|██▏       | 12949/59290 [09:34<15:56, 48.45it/s]

Iteration: 12953/59290
Iteration: 12954/59290
Iteration: 12955/59290
Iteration: 12956/59290
Iteration: 12957/59290
Iteration: 12958/59290
Iteration: 12959/59290
Iteration: 12960/59290
Iteration: 12961/59290
Iteration: 12962/59290
Iteration: 12963/59290
Iteration: 12964/59290
Iteration: 12965/59290
Iteration: 12966/59290
Iteration: 12967/59290
Iteration: 12968/59290
Iteration: 12969/59290
Iteration: 12970/59290
Iteration: 12971/59290
Iteration: 12972/59290
Iteration: 12973/59290
Iteration: 12974/59290
Iteration: 12975/59290
Iteration: 12976/59290

 22%|██▏       | 12973/59290 [09:34<14:59, 51.50it/s]

Iteration: 12977/59290
Iteration: 12978/59290
Iteration: 12979/59290
Iteration: 12980/59290
Iteration: 12981/59290
Iteration: 12982/59290
Iteration: 12983/59290
Iteration: 12984/59290
Iteration: 12985/59290
Iteration: 12986/59290
Iteration: 12987/59290
Iteration: 12988/59290
Iteration: 12989/59290
Iteration: 12990/59290
Iteration: 12991/59290
Iteration: 12992/59290
Iteration: 12993/59290
Iteration: 12994/59290
Iteration: 12995/59290
Iteration: 12996/59290
Iteration: 12997/59290
Iteration: 12998/59290
Iteration: 12999/59290
Iteration: 13000/59290

 22%|██▏       | 12997/59290 [09:36<24:18, 31.75it/s]

Iteration: 13001/59290
Iteration: 13002/59290
Iteration: 13003/59290
Iteration: 13004/59290
Iteration: 13005/59290
Iteration: 13006/59290
Iteration: 13007/59290
Iteration: 13008/59290
Iteration: 13009/59290
Iteration: 13010/59290
Iteration: 13011/59290
Iteration: 13012/59290
Iteration: 13013/59290
Iteration: 13014/59290
Iteration: 13015/59290
Iteration: 13016/59290
Iteration: 13017/59290
Iteration: 13018/59290
Iteration: 13019/59290
Iteration: 13020/59290
Iteration: 13021/59290
Iteration: 13022/59290
Iteration: 13023/59290
Iteration: 13024/59290

 22%|██▏       | 13021/59290 [09:38<38:37, 19.97it/s]

Iteration: 13025/59290
Iteration: 13026/59290
Iteration: 13027/59290
Iteration: 13028/59290
Iteration: 13029/59290
Iteration: 13030/59290
Iteration: 13031/59290
Iteration: 13032/59290
Iteration: 13033/59290
Iteration: 13034/59290
Iteration: 13035/59290
Iteration: 13036/59290
Iteration: 13037/59290
Iteration: 13038/59290
Iteration: 13039/59290
Iteration: 13040/59290
Iteration: 13041/59290
Iteration: 13042/59290
Iteration: 13043/59290
Iteration: 13044/59290
Iteration: 13045/59290
Iteration: 13046/59290
Iteration: 13047/59290
Iteration: 13048/59290

 22%|██▏       | 13045/59290 [09:38<31:14, 24.67it/s]

Iteration: 13049/59290
Iteration: 13050/59290
Iteration: 13051/59290
Iteration: 13052/59290
Iteration: 13053/59290
Iteration: 13054/59290
Iteration: 13055/59290
Iteration: 13056/59290
Iteration: 13057/59290
Iteration: 13058/59290
Iteration: 13059/59290
Iteration: 13060/59290
Iteration: 13061/59290
Iteration: 13062/59290
Iteration: 13063/59290
Iteration: 13064/59290
Iteration: 13065/59290
Iteration: 13066/59290
Iteration: 13067/59290
Iteration: 13068/59290
Iteration: 13069/59290
Iteration: 13070/59290
Iteration: 13071/59290
Iteration: 13072/59290

 22%|██▏       | 13069/59290 [09:39<26:12, 29.39it/s]

Iteration: 13073/59290
Iteration: 13074/59290
Iteration: 13075/59290
Iteration: 13076/59290
Iteration: 13077/59290
Iteration: 13078/59290
Iteration: 13079/59290
Iteration: 13080/59290
Iteration: 13081/59290
Iteration: 13082/59290
Iteration: 13083/59290
Iteration: 13084/59290
Iteration: 13085/59290
Iteration: 13086/59290
Iteration: 13087/59290
Iteration: 13088/59290
Iteration: 13089/59290
Iteration: 13090/59290
Iteration: 13091/59290
Iteration: 13092/59290
Iteration: 13093/59290
Iteration: 13094/59290
Iteration: 13095/59290
Iteration: 13096/59290

 22%|██▏       | 13093/59290 [09:39<22:22, 34.42it/s]

Iteration: 13097/59290
Iteration: 13098/59290
Iteration: 13099/59290
Iteration: 13100/59290
Iteration: 13101/59290
Iteration: 13102/59290
Iteration: 13103/59290
Iteration: 13104/59290
Iteration: 13105/59290
Iteration: 13106/59290
Iteration: 13107/59290
Iteration: 13108/59290
Iteration: 13109/59290
Iteration: 13110/59290
Iteration: 13111/59290
Iteration: 13112/59290
Iteration: 13113/59290
Iteration: 13114/59290
Iteration: 13115/59290
Iteration: 13116/59290
Iteration: 13117/59290
Iteration: 13118/59290
Iteration: 13119/59290
Iteration: 13120/59290

 22%|██▏       | 13117/59290 [09:40<19:13, 40.04it/s]

Iteration: 13121/59290
Iteration: 13122/59290
Iteration: 13123/59290
Iteration: 13124/59290
Iteration: 13125/59290
Iteration: 13126/59290
Iteration: 13127/59290
Iteration: 13128/59290
Iteration: 13129/59290
Iteration: 13130/59290
Iteration: 13131/59290
Iteration: 13132/59290
Iteration: 13133/59290
Iteration: 13134/59290
Iteration: 13135/59290
Iteration: 13136/59290
Iteration: 13137/59290
Iteration: 13138/59290
Iteration: 13139/59290
Iteration: 13140/59290
Iteration: 13141/59290
Iteration: 13142/59290
Iteration: 13143/59290
Iteration: 13144/59290

 22%|██▏       | 13141/59290 [09:40<17:08, 44.85it/s]

Iteration: 13145/59290
Iteration: 13146/59290
Iteration: 13147/59290
Iteration: 13148/59290
Iteration: 13149/59290
Iteration: 13150/59290
Iteration: 13151/59290
Iteration: 13152/59290
Iteration: 13153/59290
Iteration: 13154/59290
Iteration: 13155/59290
Iteration: 13156/59290
Iteration: 13157/59290
Iteration: 13158/59290
Iteration: 13159/59290
Iteration: 13160/59290
Iteration: 13161/59290
Iteration: 13162/59290
Iteration: 13163/59290
Iteration: 13164/59290
Iteration: 13165/59290
Iteration: 13166/59290
Iteration: 13167/59290
Iteration: 13168/59290

 22%|██▏       | 13165/59290 [09:41<18:39, 41.20it/s]

Iteration: 13169/59290
Iteration: 13170/59290
Iteration: 13171/59290
Iteration: 13172/59290
Iteration: 13173/59290
Iteration: 13174/59290
Iteration: 13175/59290
Iteration: 13176/59290
Iteration: 13177/59290
Iteration: 13178/59290
Iteration: 13179/59290
Iteration: 13180/59290
Iteration: 13181/59290
Iteration: 13182/59290
Iteration: 13183/59290
Iteration: 13184/59290
Iteration: 13185/59290
Iteration: 13186/59290
Iteration: 13187/59290
Iteration: 13188/59290
Iteration: 13189/59290
Iteration: 13190/59290
Iteration: 13191/59290
Iteration: 13192/59290

 22%|██▏       | 13189/59290 [09:41<17:01, 45.12it/s]

Iteration: 13193/59290
Iteration: 13194/59290
Iteration: 13195/59290
Iteration: 13196/59290
Iteration: 13197/59290
Iteration: 13198/59290
Iteration: 13199/59290
Iteration: 13200/59290
Iteration: 13201/59290
Iteration: 13202/59290
Iteration: 13203/59290
Iteration: 13204/59290
Iteration: 13205/59290
Iteration: 13206/59290
Iteration: 13207/59290
Iteration: 13208/59290
Iteration: 13209/59290
Iteration: 13210/59290
Iteration: 13211/59290
Iteration: 13212/59290
Iteration: 13213/59290
Iteration: 13214/59290
Iteration: 13215/59290
Iteration: 13216/59290

 22%|██▏       | 13213/59290 [09:42<16:05, 47.75it/s]

Iteration: 13217/59290
Iteration: 13218/59290
Iteration: 13219/59290
Iteration: 13220/59290
Iteration: 13221/59290
Iteration: 13222/59290
Iteration: 13223/59290
Iteration: 13224/59290
Iteration: 13225/59290
Iteration: 13226/59290
Iteration: 13227/59290
Iteration: 13228/59290
Iteration: 13229/59290
Iteration: 13230/59290
Iteration: 13231/59290
Iteration: 13232/59290
Iteration: 13233/59290
Iteration: 13234/59290
Iteration: 13235/59290
Iteration: 13236/59290
Iteration: 13237/59290
Iteration: 13238/59290
Iteration: 13239/59290
Iteration: 13240/59290

 22%|██▏       | 13237/59290 [09:42<14:50, 51.70it/s]

Iteration: 13241/59290
Iteration: 13242/59290
Iteration: 13243/59290
Iteration: 13244/59290
Iteration: 13245/59290
Iteration: 13246/59290
Iteration: 13247/59290
Iteration: 13248/59290
Iteration: 13249/59290
Iteration: 13250/59290
Iteration: 13251/59290
Iteration: 13252/59290
Iteration: 13253/59290
Iteration: 13254/59290
Iteration: 13255/59290
Iteration: 13256/59290
Iteration: 13257/59290
Iteration: 13258/59290
Iteration: 13259/59290
Iteration: 13260/59290
Iteration: 13261/59290
Iteration: 13262/59290
Iteration: 13263/59290
Iteration: 13264/59290

 22%|██▏       | 13261/59290 [09:42<14:07, 54.28it/s]

Iteration: 13265/59290
Iteration: 13266/59290
Iteration: 13267/59290
Iteration: 13268/59290
Iteration: 13269/59290
Iteration: 13270/59290
Iteration: 13271/59290
Iteration: 13272/59290
Iteration: 13273/59290
Iteration: 13274/59290
Iteration: 13275/59290
Iteration: 13276/59290
Iteration: 13277/59290
Iteration: 13278/59290
Iteration: 13279/59290
Iteration: 13280/59290
Iteration: 13281/59290
Iteration: 13282/59290
Iteration: 13283/59290
Iteration: 13284/59290
Iteration: 13285/59290
Iteration: 13286/59290
Iteration: 13287/59290
Iteration: 13288/59290

 22%|██▏       | 13285/59290 [09:43<13:47, 55.61it/s]

Iteration: 13289/59290
Iteration: 13290/59290
Iteration: 13291/59290
Iteration: 13292/59290
Iteration: 13293/59290
Iteration: 13294/59290
Iteration: 13295/59290
Iteration: 13296/59290
Iteration: 13297/59290
Iteration: 13298/59290
Iteration: 13299/59290
Iteration: 13300/59290
Iteration: 13301/59290
Iteration: 13302/59290
Iteration: 13303/59290
Iteration: 13304/59290
Iteration: 13305/59290
Iteration: 13306/59290
Iteration: 13307/59290
Iteration: 13308/59290
Iteration: 13309/59290
Iteration: 13310/59290
Iteration: 13311/59290
Iteration: 13312/59290

 22%|██▏       | 13309/59290 [09:43<13:30, 56.73it/s]

Iteration: 13313/59290
Iteration: 13314/59290
Iteration: 13315/59290
Iteration: 13316/59290
Iteration: 13317/59290
Iteration: 13318/59290
Iteration: 13319/59290
Iteration: 13320/59290
Iteration: 13321/59290
Iteration: 13322/59290
Iteration: 13323/59290
Iteration: 13324/59290
Iteration: 13325/59290
Iteration: 13326/59290
Iteration: 13327/59290
Iteration: 13328/59290
Iteration: 13329/59290
Iteration: 13330/59290
Iteration: 13331/59290
Iteration: 13332/59290
Iteration: 13333/59290
Iteration: 13334/59290
Iteration: 13335/59290
Iteration: 13336/59290

 22%|██▏       | 13333/59290 [09:44<13:13, 57.88it/s]

Iteration: 13337/59290
Iteration: 13338/59290
Iteration: 13339/59290
Iteration: 13340/59290
Iteration: 13341/59290
Iteration: 13342/59290
Iteration: 13343/59290
Iteration: 13344/59290
Iteration: 13345/59290
Iteration: 13346/59290
Iteration: 13347/59290
Iteration: 13348/59290
Iteration: 13349/59290
Iteration: 13350/59290
Iteration: 13351/59290
Iteration: 13352/59290
Iteration: 13353/59290
Iteration: 13354/59290
Iteration: 13355/59290
Iteration: 13356/59290
Iteration: 13357/59290
Iteration: 13358/59290
Iteration: 13359/59290
Iteration: 13360/59290

 23%|██▎       | 13357/59290 [09:44<12:54, 59.31it/s]

Iteration: 13361/59290
Iteration: 13362/59290
Iteration: 13363/59290
Iteration: 13364/59290
Iteration: 13365/59290
Iteration: 13366/59290
Iteration: 13367/59290
Iteration: 13368/59290
Iteration: 13369/59290
Iteration: 13370/59290
Iteration: 13371/59290
Iteration: 13372/59290
Iteration: 13373/59290
Iteration: 13374/59290
Iteration: 13375/59290
Iteration: 13376/59290
Iteration: 13377/59290
Iteration: 13378/59290
Iteration: 13379/59290
Iteration: 13380/59290
Iteration: 13381/59290
Iteration: 13382/59290
Iteration: 13383/59290
Iteration: 13384/59290

 23%|██▎       | 13381/59290 [09:44<12:48, 59.76it/s]

Iteration: 13385/59290
Iteration: 13386/59290
Iteration: 13387/59290
Iteration: 13388/59290
Iteration: 13389/59290
Iteration: 13390/59290
Iteration: 13391/59290
Iteration: 13392/59290
Iteration: 13393/59290
Iteration: 13394/59290
Iteration: 13395/59290
Iteration: 13396/59290
Iteration: 13397/59290
Iteration: 13398/59290
Iteration: 13399/59290
Iteration: 13400/59290
Iteration: 13401/59290
Iteration: 13402/59290
Iteration: 13403/59290
Iteration: 13404/59290
Iteration: 13405/59290
Iteration: 13406/59290
Iteration: 13407/59290
Iteration: 13408/59290

 23%|██▎       | 13405/59290 [09:45<12:36, 60.62it/s]

Iteration: 13409/59290
Iteration: 13410/59290
Iteration: 13411/59290
Iteration: 13412/59290
Iteration: 13413/59290
Iteration: 13414/59290
Iteration: 13415/59290
Iteration: 13416/59290
Iteration: 13417/59290
Iteration: 13418/59290
Iteration: 13419/59290
Iteration: 13420/59290
Iteration: 13421/59290
Iteration: 13422/59290
Iteration: 13423/59290
Iteration: 13424/59290
Iteration: 13425/59290
Iteration: 13426/59290
Iteration: 13427/59290
Iteration: 13428/59290
Iteration: 13429/59290
Iteration: 13430/59290
Iteration: 13431/59290
Iteration: 13432/59290

 23%|██▎       | 13429/59290 [09:45<12:28, 61.31it/s]

Iteration: 13433/59290
Iteration: 13434/59290
Iteration: 13435/59290
Iteration: 13436/59290
Iteration: 13437/59290
Iteration: 13438/59290
Iteration: 13439/59290
Iteration: 13440/59290
Iteration: 13441/59290
Iteration: 13442/59290
Iteration: 13443/59290
Iteration: 13444/59290
Iteration: 13445/59290
Iteration: 13446/59290
Iteration: 13447/59290
Iteration: 13448/59290
Iteration: 13449/59290
Iteration: 13450/59290
Iteration: 13451/59290
Iteration: 13452/59290
Iteration: 13453/59290
Iteration: 13454/59290
Iteration: 13455/59290
Iteration: 13456/59290

 23%|██▎       | 13453/59290 [09:45<12:18, 62.06it/s]

Iteration: 13457/59290
Iteration: 13458/59290
Iteration: 13459/59290
Iteration: 13460/59290
Iteration: 13461/59290
Iteration: 13462/59290
Iteration: 13463/59290
Iteration: 13464/59290
Iteration: 13465/59290
Iteration: 13466/59290
Iteration: 13467/59290
Iteration: 13468/59290
Iteration: 13469/59290
Iteration: 13470/59290
Iteration: 13471/59290
Iteration: 13472/59290
Iteration: 13473/59290
Iteration: 13474/59290
Iteration: 13475/59290
Iteration: 13476/59290
Iteration: 13477/59290
Iteration: 13478/59290
Iteration: 13480/59290

 23%|██▎       | 13476/59290 [09:46<12:55, 59.08it/s]

Iteration: 13481/59290
Iteration: 13482/59290
Iteration: 13483/59290
Iteration: 13484/59290
Iteration: 13485/59290
Iteration: 13486/59290
Iteration: 13487/59290
Iteration: 13488/59290

 23%|██▎       | 13484/59290 [09:46<15:55, 47.93it/s]

Iteration: 13489/59290
Iteration: 13490/59290
Iteration: 13491/59290
Iteration: 13492/59290
Iteration: 13493/59290
Iteration: 13494/59290
Iteration: 13495/59290
Iteration: 13496/59290
Iteration: 13497/59290
Iteration: 13498/59290
Iteration: 13499/59290
Iteration: 13500/59290
Iteration: 13501/59290
Iteration: 13502/59290
Iteration: 13503/59290
Iteration: 13504/59290
Iteration: 13505/59290
Iteration: 13506/59290
Iteration: 13507/59290
Iteration: 13508/59290
Iteration: 13509/59290
Iteration: 13510/59290
Iteration: 13511/59290
Iteration: 13512/59290

 23%|██▎       | 13508/59290 [09:47<14:36, 52.23it/s]

Iteration: 13513/59290
Iteration: 13514/59290
Iteration: 13515/59290
Iteration: 13516/59290
Iteration: 13517/59290
Iteration: 13518/59290
Iteration: 13519/59290
Iteration: 13520/59290
Iteration: 13521/59290
Iteration: 13522/59290
Iteration: 13523/59290
Iteration: 13524/59290
Iteration: 13525/59290
Iteration: 13526/59290
Iteration: 13527/59290
Iteration: 13528/59290
Iteration: 13529/59290
Iteration: 13530/59290
Iteration: 13531/59290
Iteration: 13532/59290
Iteration: 13533/59290
Iteration: 13534/59290
Iteration: 13535/59290
Iteration: 13536/59290

 23%|██▎       | 13532/59290 [09:47<13:46, 55.36it/s]

Iteration: 13537/59290
Iteration: 13538/59290
Iteration: 13539/59290
Iteration: 13540/59290
Iteration: 13541/59290
Iteration: 13542/59290
Iteration: 13543/59290
Iteration: 13544/59290
Iteration: 13545/59290
Iteration: 13546/59290
Iteration: 13547/59290
Iteration: 13548/59290
Iteration: 13549/59290
Iteration: 13550/59290
Iteration: 13551/59290
Iteration: 13552/59290
Iteration: 13553/59290
Iteration: 13554/59290
Iteration: 13555/59290
Iteration: 13556/59290
Iteration: 13557/59290
Iteration: 13558/59290
Iteration: 13559/59290
Iteration: 13560/59290

 23%|██▎       | 13556/59290 [09:47<13:11, 57.79it/s]

Iteration: 13561/59290
Iteration: 13562/59290
Iteration: 13563/59290
Iteration: 13564/59290
Iteration: 13565/59290
Iteration: 13566/59290
Iteration: 13567/59290
Iteration: 13568/59290
Iteration: 13569/59290
Iteration: 13570/59290
Iteration: 13571/59290
Iteration: 13572/59290
Iteration: 13573/59290
Iteration: 13574/59290
Iteration: 13575/59290
Iteration: 13576/59290
Iteration: 13577/59290
Iteration: 13578/59290
Iteration: 13579/59290
Iteration: 13580/59290
Iteration: 13581/59290
Iteration: 13582/59290
Iteration: 13583/59290
Iteration: 13584/59290

 23%|██▎       | 13580/59290 [09:48<12:52, 59.18it/s]

Iteration: 13585/59290
Iteration: 13586/59290
Iteration: 13587/59290
Iteration: 13588/59290
Iteration: 13589/59290
Iteration: 13590/59290
Iteration: 13591/59290
Iteration: 13592/59290
Iteration: 13593/59290
Iteration: 13594/59290
Iteration: 13595/59290
Iteration: 13596/59290
Iteration: 13597/59290
Iteration: 13598/59290
Iteration: 13599/59290
Iteration: 13600/59290
Iteration: 13601/59290
Iteration: 13602/59290
Iteration: 13603/59290
Iteration: 13604/59290
Iteration: 13605/59290
Iteration: 13606/59290
Iteration: 13607/59290
Iteration: 13608/59290

 23%|██▎       | 13604/59290 [09:48<12:40, 60.04it/s]

Iteration: 13609/59290
Iteration: 13610/59290
Iteration: 13611/59290
Iteration: 13612/59290
Iteration: 13613/59290
Iteration: 13614/59290
Iteration: 13615/59290
Iteration: 13616/59290
Iteration: 13617/59290
Iteration: 13618/59290
Iteration: 13619/59290
Iteration: 13620/59290
Iteration: 13621/59290
Iteration: 13622/59290
Iteration: 13623/59290
Iteration: 13624/59290
Iteration: 13625/59290
Iteration: 13626/59290
Iteration: 13627/59290
Iteration: 13628/59290
Iteration: 13629/59290
Iteration: 13630/59290
Iteration: 13631/59290
Iteration: 13632/59290

 23%|██▎       | 13628/59290 [09:49<12:36, 60.35it/s]

Iteration: 13633/59290
Iteration: 13634/59290
Iteration: 13635/59290
Iteration: 13636/59290
Iteration: 13637/59290
Iteration: 13638/59290
Iteration: 13639/59290
Iteration: 13640/59290
Iteration: 13641/59290
Iteration: 13642/59290
Iteration: 13643/59290
Iteration: 13644/59290
Iteration: 13645/59290
Iteration: 13646/59290
Iteration: 13647/59290
Iteration: 13648/59290
Iteration: 13649/59290
Iteration: 13650/59290
Iteration: 13651/59290
Iteration: 13652/59290
Iteration: 13653/59290
Iteration: 13654/59290
Iteration: 13655/59290
Iteration: 13656/59290

 23%|██▎       | 13652/59290 [09:49<12:32, 60.66it/s]

Iteration: 13657/59290
Iteration: 13658/59290
Iteration: 13659/59290
Iteration: 13660/59290
Iteration: 13661/59290
Iteration: 13662/59290
Iteration: 13663/59290
Iteration: 13664/59290
Iteration: 13665/59290
Iteration: 13666/59290
Iteration: 13667/59290
Iteration: 13668/59290
Iteration: 13669/59290
Iteration: 13670/59290
Iteration: 13671/59290
Iteration: 13672/59290
Iteration: 13673/59290
Iteration: 13674/59290
Iteration: 13675/59290
Iteration: 13676/59290
Iteration: 13677/59290
Iteration: 13678/59290
Iteration: 13679/59290
Iteration: 13680/59290

 23%|██▎       | 13676/59290 [09:49<12:20, 61.58it/s]

Iteration: 13681/59290
Iteration: 13682/59290
Iteration: 13683/59290
Iteration: 13684/59290
Iteration: 13685/59290
Iteration: 13686/59290
Iteration: 13687/59290
Iteration: 13688/59290
Iteration: 13689/59290
Iteration: 13690/59290
Iteration: 13691/59290
Iteration: 13692/59290
Iteration: 13693/59290
Iteration: 13694/59290
Iteration: 13695/59290
Iteration: 13696/59290
Iteration: 13697/59290
Iteration: 13698/59290
Iteration: 13699/59290
Iteration: 13700/59290
Iteration: 13701/59290
Iteration: 13702/59290
Iteration: 13703/59290
Iteration: 13704/59290

 23%|██▎       | 13700/59290 [09:51<23:55, 31.77it/s]

Iteration: 13705/59290
Iteration: 13706/59290
Iteration: 13707/59290
Iteration: 13708/59290
Iteration: 13709/59290
Iteration: 13710/59290
Iteration: 13711/59290
Iteration: 13712/59290
Iteration: 13713/59290
Iteration: 13714/59290
Iteration: 13715/59290
Iteration: 13716/59290
Iteration: 13717/59290
Iteration: 13718/59290
Iteration: 13719/59290
Iteration: 13720/59290
Iteration: 13721/59290
Iteration: 13722/59290
Iteration: 13723/59290
Iteration: 13724/59290
Iteration: 13725/59290
Iteration: 13726/59290
Iteration: 13727/59290
Iteration: 13728/59290

 23%|██▎       | 13724/59290 [09:53<38:24, 19.77it/s]

Iteration: 13729/59290
Iteration: 13730/59290
Iteration: 13731/59290
Iteration: 13732/59290
Iteration: 13733/59290
Iteration: 13734/59290
Iteration: 13735/59290
Iteration: 13736/59290
Iteration: 13737/59290
Iteration: 13738/59290
Iteration: 13739/59290
Iteration: 13740/59290
Iteration: 13741/59290
Iteration: 13742/59290
Iteration: 13743/59290
Iteration: 13744/59290
Iteration: 13745/59290
Iteration: 13746/59290
Iteration: 13747/59290
Iteration: 13748/59290
Iteration: 13749/59290
Iteration: 13750/59290
Iteration: 13751/59290
Iteration: 13752/59290

 23%|██▎       | 13748/59290 [09:54<30:51, 24.59it/s]

Iteration: 13753/59290
Iteration: 13754/59290
Iteration: 13755/59290
Iteration: 13756/59290
Iteration: 13757/59290
Iteration: 13758/59290
Iteration: 13759/59290
Iteration: 13760/59290
Iteration: 13761/59290
Iteration: 13762/59290
Iteration: 13763/59290
Iteration: 13764/59290
Iteration: 13765/59290
Iteration: 13766/59290
Iteration: 13767/59290
Iteration: 13768/59290
Iteration: 13769/59290
Iteration: 13770/59290
Iteration: 13771/59290
Iteration: 13772/59290
Iteration: 13773/59290
Iteration: 13774/59290
Iteration: 13775/59290
Iteration: 13776/59290

 23%|██▎       | 13772/59290 [09:54<25:14, 30.05it/s]

Iteration: 13777/59290
Iteration: 13778/59290
Iteration: 13779/59290
Iteration: 13780/59290
Iteration: 13781/59290
Iteration: 13782/59290
Iteration: 13783/59290
Iteration: 13784/59290
Iteration: 13785/59290
Iteration: 13786/59290
Iteration: 13787/59290
Iteration: 13788/59290
Iteration: 13789/59290
Iteration: 13790/59290
Iteration: 13791/59290
Iteration: 13792/59290
Iteration: 13793/59290
Iteration: 13794/59290
Iteration: 13795/59290
Iteration: 13796/59290
Iteration: 13797/59290
Iteration: 13798/59290
Iteration: 13799/59290
Iteration: 13800/59290

 23%|██▎       | 13796/59290 [09:54<21:17, 35.61it/s]

Iteration: 13801/59290
Iteration: 13802/59290
Iteration: 13803/59290
Iteration: 13804/59290
Iteration: 13805/59290
Iteration: 13806/59290
Iteration: 13807/59290
Iteration: 13808/59290
Iteration: 13809/59290
Iteration: 13810/59290
Iteration: 13811/59290
Iteration: 13812/59290
Iteration: 13813/59290
Iteration: 13814/59290
Iteration: 13815/59290
Iteration: 13816/59290
Iteration: 13817/59290
Iteration: 13818/59290
Iteration: 13819/59290
Iteration: 13820/59290
Iteration: 13821/59290
Iteration: 13822/59290
Iteration: 13823/59290
Iteration: 13824/59290

 23%|██▎       | 13820/59290 [09:55<18:29, 40.99it/s]

Iteration: 13825/59290
Iteration: 13826/59290
Iteration: 13827/59290
Iteration: 13828/59290
Iteration: 13829/59290
Iteration: 13830/59290
Iteration: 13831/59290
Iteration: 13832/59290
Iteration: 13833/59290
Iteration: 13834/59290
Iteration: 13835/59290
Iteration: 13836/59290
Iteration: 13837/59290
Iteration: 13838/59290
Iteration: 13839/59290
Iteration: 13840/59290
Iteration: 13841/59290
Iteration: 13842/59290
Iteration: 13843/59290
Iteration: 13844/59290
Iteration: 13845/59290
Iteration: 13846/59290
Iteration: 13847/59290
Iteration: 13848/59290

 23%|██▎       | 13844/59290 [09:55<16:38, 45.52it/s]

Iteration: 13849/59290
Iteration: 13850/59290
Iteration: 13851/59290
Iteration: 13852/59290
Iteration: 13853/59290
Iteration: 13854/59290
Iteration: 13855/59290
Iteration: 13856/59290
Iteration: 13857/59290
Iteration: 13858/59290
Iteration: 13859/59290
Iteration: 13860/59290
Iteration: 13861/59290
Iteration: 13862/59290
Iteration: 13863/59290
Iteration: 13864/59290
Iteration: 13865/59290
Iteration: 13866/59290
Iteration: 13867/59290
Iteration: 13868/59290
Iteration: 13869/59290
Iteration: 13870/59290
Iteration: 13871/59290
Iteration: 13872/59290

 23%|██▎       | 13868/59290 [09:56<15:25, 49.07it/s]

Iteration: 13873/59290
Iteration: 13874/59290
Iteration: 13875/59290
Iteration: 13876/59290
Iteration: 13877/59290
Iteration: 13878/59290
Iteration: 13879/59290
Iteration: 13880/59290
Iteration: 13881/59290
Iteration: 13882/59290
Iteration: 13883/59290
Iteration: 13884/59290
Iteration: 13885/59290
Iteration: 13886/59290
Iteration: 13887/59290
Iteration: 13888/59290
Iteration: 13889/59290
Iteration: 13890/59290
Iteration: 13891/59290
Iteration: 13892/59290
Iteration: 13893/59290
Iteration: 13894/59290
Iteration: 13895/59290
Iteration: 13896/59290

 23%|██▎       | 13892/59290 [09:56<14:25, 52.48it/s]

Iteration: 13897/59290
Iteration: 13898/59290
Iteration: 13899/59290
Iteration: 13900/59290
Iteration: 13901/59290
Iteration: 13902/59290
Iteration: 13903/59290
Iteration: 13904/59290
Iteration: 13905/59290
Iteration: 13906/59290
Iteration: 13907/59290
Iteration: 13908/59290
Iteration: 13909/59290
Iteration: 13910/59290
Iteration: 13911/59290
Iteration: 13912/59290
Iteration: 13913/59290
Iteration: 13914/59290
Iteration: 13915/59290
Iteration: 13916/59290
Iteration: 13917/59290
Iteration: 13918/59290
Iteration: 13919/59290
Iteration: 13920/59290

 23%|██▎       | 13916/59290 [09:56<13:38, 55.44it/s]

Iteration: 13921/59290
Iteration: 13922/59290
Iteration: 13923/59290
Iteration: 13924/59290
Iteration: 13925/59290
Iteration: 13926/59290
Iteration: 13927/59290
Iteration: 13928/59290
Iteration: 13929/59290
Iteration: 13930/59290
Iteration: 13931/59290
Iteration: 13932/59290
Iteration: 13933/59290
Iteration: 13934/59290
Iteration: 13935/59290
Iteration: 13936/59290
Iteration: 13937/59290
Iteration: 13938/59290
Iteration: 13939/59290
Iteration: 13940/59290
Iteration: 13941/59290
Iteration: 13942/59290
Iteration: 13943/59290
Iteration: 13944/59290

 24%|██▎       | 13940/59290 [09:57<14:52, 50.84it/s]

Iteration: 13945/59290
Iteration: 13946/59290
Iteration: 13947/59290
Iteration: 13948/59290
Iteration: 13949/59290
Iteration: 13950/59290
Iteration: 13951/59290
Iteration: 13952/59290
Iteration: 13953/59290
Iteration: 13954/59290
Iteration: 13955/59290
Iteration: 13956/59290
Iteration: 13957/59290
Iteration: 13958/59290
Iteration: 13959/59290
Iteration: 13960/59290
Iteration: 13961/59290
Iteration: 13962/59290
Iteration: 13963/59290
Iteration: 13964/59290
Iteration: 13965/59290
Iteration: 13966/59290
Iteration: 13967/59290
Iteration: 13968/59290

 24%|██▎       | 13964/59290 [09:57<14:11, 53.26it/s]

Iteration: 13969/59290
Iteration: 13970/59290
Iteration: 13971/59290
Iteration: 13972/59290
Iteration: 13973/59290
Iteration: 13974/59290
Iteration: 13975/59290
Iteration: 13976/59290
Iteration: 13977/59290
Iteration: 13978/59290
Iteration: 13979/59290
Iteration: 13980/59290
Iteration: 13981/59290
Iteration: 13982/59290
Iteration: 13983/59290
Iteration: 13984/59290
Iteration: 13985/59290
Iteration: 13986/59290
Iteration: 13987/59290
Iteration: 13988/59290
Iteration: 13989/59290
Iteration: 13990/59290
Iteration: 13991/59290
Iteration: 13992/59290

 24%|██▎       | 13988/59290 [09:58<13:33, 55.67it/s]

Iteration: 13993/59290
Iteration: 13994/59290
Iteration: 13995/59290
Iteration: 13996/59290
Iteration: 13997/59290
Iteration: 13998/59290
Iteration: 13999/59290
Iteration: 14000/59290
Iteration: 14001/59290
Iteration: 14002/59290
Iteration: 14003/59290
Iteration: 14004/59290
Iteration: 14005/59290
Iteration: 14006/59290
Iteration: 14007/59290
Iteration: 14008/59290
Iteration: 14009/59290
Iteration: 14010/59290
Iteration: 14011/59290
Iteration: 14012/59290
Iteration: 14013/59290
Iteration: 14014/59290
Iteration: 14015/59290
Iteration: 14016/59290

 24%|██▎       | 14012/59290 [09:58<13:01, 57.93it/s]

Iteration: 14017/59290
Iteration: 14018/59290
Iteration: 14019/59290
Iteration: 14020/59290
Iteration: 14021/59290
Iteration: 14022/59290
Iteration: 14023/59290
Iteration: 14024/59290
Iteration: 14025/59290
Iteration: 14026/59290
Iteration: 14027/59290
Iteration: 14028/59290
Iteration: 14029/59290
Iteration: 14030/59290
Iteration: 14031/59290
Iteration: 14032/59290
Iteration: 14033/59290
Iteration: 14034/59290
Iteration: 14035/59290
Iteration: 14036/59290
Iteration: 14037/59290
Iteration: 14038/59290
Iteration: 14039/59290
Iteration: 14040/59290

 24%|██▎       | 14036/59290 [09:58<12:46, 59.07it/s]

Iteration: 14041/59290
Iteration: 14042/59290
Iteration: 14043/59290
Iteration: 14044/59290
Iteration: 14045/59290
Iteration: 14046/59290
Iteration: 14047/59290
Iteration: 14048/59290
Iteration: 14049/59290
Iteration: 14050/59290
Iteration: 14051/59290
Iteration: 14052/59290
Iteration: 14053/59290
Iteration: 14054/59290
Iteration: 14055/59290
Iteration: 14056/59290
Iteration: 14057/59290
Iteration: 14058/59290
Iteration: 14059/59290
Iteration: 14060/59290
Iteration: 14061/59290
Iteration: 14062/59290
Iteration: 14063/59290
Iteration: 14064/59290

 24%|██▎       | 14060/59290 [09:59<12:29, 60.31it/s]

Iteration: 14065/59290
Iteration: 14066/59290
Iteration: 14067/59290
Iteration: 14068/59290
Iteration: 14069/59290
Iteration: 14070/59290
Iteration: 14071/59290
Iteration: 14072/59290
Iteration: 14073/59290
Iteration: 14074/59290
Iteration: 14075/59290
Iteration: 14076/59290
Iteration: 14077/59290
Iteration: 14078/59290
Iteration: 14079/59290
Iteration: 14080/59290
Iteration: 14081/59290
Iteration: 14082/59290
Iteration: 14083/59290
Iteration: 14084/59290
Iteration: 14085/59290
Iteration: 14086/59290
Iteration: 14087/59290
Iteration: 14088/59290

 24%|██▍       | 14084/59290 [09:59<12:22, 60.86it/s]

Iteration: 14089/59290
Iteration: 14090/59290
Iteration: 14091/59290
Iteration: 14092/59290
Iteration: 14093/59290
Iteration: 14094/59290
Iteration: 14095/59290
Iteration: 14096/59290
Iteration: 14097/59290
Iteration: 14098/59290
Iteration: 14099/59290
Iteration: 14100/59290
Iteration: 14101/59290
Iteration: 14102/59290
Iteration: 14103/59290
Iteration: 14104/59290
Iteration: 14105/59290
Iteration: 14106/59290
Iteration: 14107/59290
Iteration: 14108/59290
Iteration: 14109/59290
Iteration: 14110/59290
Iteration: 14111/59290
Iteration: 14112/59290

 24%|██▍       | 14108/59290 [10:00<12:22, 60.81it/s]

Iteration: 14113/59290
Iteration: 14114/59290
Iteration: 14115/59290
Iteration: 14116/59290
Iteration: 14117/59290
Iteration: 14118/59290
Iteration: 14119/59290
Iteration: 14120/59290
Iteration: 14121/59290
Iteration: 14122/59290
Iteration: 14123/59290
Iteration: 14124/59290
Iteration: 14125/59290
Iteration: 14126/59290
Iteration: 14127/59290
Iteration: 14128/59290
Iteration: 14129/59290
Iteration: 14130/59290
Iteration: 14131/59290
Iteration: 14132/59290
Iteration: 14133/59290
Iteration: 14134/59290
Iteration: 14135/59290
Iteration: 14136/59290

 24%|██▍       | 14132/59290 [10:00<12:16, 61.35it/s]

Iteration: 14137/59290
Iteration: 14138/59290
Iteration: 14139/59290
Iteration: 14140/59290
Iteration: 14141/59290
Iteration: 14142/59290
Iteration: 14143/59290
Iteration: 14144/59290
Iteration: 14145/59290
Iteration: 14146/59290
Iteration: 14147/59290
Iteration: 14148/59290
Iteration: 14149/59290
Iteration: 14150/59290
Iteration: 14151/59290
Iteration: 14152/59290
Iteration: 14153/59290
Iteration: 14154/59290
Iteration: 14155/59290
Iteration: 14156/59290
Iteration: 14157/59290
Iteration: 14158/59290
Iteration: 14159/59290
Iteration: 14160/59290

 24%|██▍       | 14156/59290 [10:00<12:07, 62.02it/s]

Iteration: 14161/59290
Iteration: 14162/59290
Iteration: 14163/59290
Iteration: 14164/59290
Iteration: 14165/59290
Iteration: 14166/59290
Iteration: 14167/59290
Iteration: 14168/59290
Iteration: 14169/59290
Iteration: 14170/59290
Iteration: 14171/59290
Iteration: 14172/59290
Iteration: 14173/59290
Iteration: 14174/59290
Iteration: 14175/59290
Iteration: 14176/59290
Iteration: 14177/59290
Iteration: 14178/59290
Iteration: 14179/59290
Iteration: 14180/59290
Iteration: 14181/59290
Iteration: 14182/59290
Iteration: 14183/59290
Iteration: 14184/59290

 24%|██▍       | 14180/59290 [10:01<12:09, 61.86it/s]

Iteration: 14185/59290
Iteration: 14186/59290
Iteration: 14187/59290
Iteration: 14188/59290
Iteration: 14189/59290
Iteration: 14190/59290
Iteration: 14191/59290
Iteration: 14192/59290
Iteration: 14193/59290
Iteration: 14194/59290
Iteration: 14195/59290
Iteration: 14196/59290
Iteration: 14197/59290
Iteration: 14198/59290
Iteration: 14199/59290
Iteration: 14200/59290
Iteration: 14201/59290
Iteration: 14202/59290
Iteration: 14203/59290
Iteration: 14204/59290
Iteration: 14205/59290
Iteration: 14206/59290
Iteration: 14207/59290
Iteration: 14208/59290

 24%|██▍       | 14204/59290 [10:01<12:15, 61.27it/s]

Iteration: 14209/59290
Iteration: 14210/59290
Iteration: 14211/59290
Iteration: 14212/59290
Iteration: 14213/59290
Iteration: 14214/59290
Iteration: 14215/59290
Iteration: 14216/59290
Iteration: 14217/59290
Iteration: 14218/59290
Iteration: 14219/59290
Iteration: 14220/59290
Iteration: 14221/59290
Iteration: 14222/59290
Iteration: 14223/59290
Iteration: 14224/59290
Iteration: 14225/59290
Iteration: 14226/59290
Iteration: 14227/59290
Iteration: 14228/59290
Iteration: 14229/59290
Iteration: 14230/59290
Iteration: 14231/59290
Iteration: 14232/59290

 24%|██▍       | 14228/59290 [10:35<5:25:28,  2.31it/s]

Iteration: 14233/59290
Iteration: 14234/59290
Iteration: 14235/59290
Iteration: 14236/59290
Iteration: 14237/59290
Iteration: 14238/59290
Iteration: 14239/59290
Iteration: 14240/59290
Iteration: 14241/59290
Iteration: 14242/59290
Iteration: 14243/59290
Iteration: 14244/59290
Iteration: 14245/59290
Iteration: 14246/59290
Iteration: 14247/59290
Iteration: 14248/59290
Iteration: 14249/59290
Iteration: 14250/59290
Iteration: 14251/59290
Iteration: 14252/59290
Iteration: 14253/59290
Iteration: 14254/59290
Iteration: 14255/59290
Iteration: 14256/59290

 24%|██▍       | 14252/59290 [10:35<3:51:21,  3.24it/s]

Iteration: 14257/59290
Iteration: 14258/59290
Iteration: 14259/59290
Iteration: 14260/59290
Iteration: 14261/59290
Iteration: 14262/59290
Iteration: 14263/59290
Iteration: 14264/59290
Iteration: 14265/59290
Iteration: 14266/59290
Iteration: 14267/59290
Iteration: 14268/59290
Iteration: 14269/59290
Iteration: 14270/59290
Iteration: 14271/59290
Iteration: 14272/59290
Iteration: 14273/59290
Iteration: 14274/59290
Iteration: 14275/59290
Iteration: 14276/59290
Iteration: 14277/59290
Iteration: 14278/59290
Iteration: 14279/59290
Iteration: 14280/59290

 24%|██▍       | 14276/59290 [10:36<2:49:33,  4.42it/s]

Iteration: 14281/59290
Iteration: 14282/59290
Iteration: 14283/59290
Iteration: 14284/59290
Iteration: 14285/59290
Iteration: 14286/59290
Iteration: 14287/59290
Iteration: 14288/59290
Iteration: 14289/59290
Iteration: 14290/59290
Iteration: 14291/59290
Iteration: 14292/59290
Iteration: 14293/59290
Iteration: 14294/59290
Iteration: 14295/59290
Iteration: 14296/59290
Iteration: 14297/59290
Iteration: 14298/59290
Iteration: 14299/59290
Iteration: 14300/59290
Iteration: 14301/59290
Iteration: 14302/59290
Iteration: 14303/59290
Iteration: 14304/59290

 24%|██▍       | 14300/59290 [10:36<2:02:12,  6.14it/s]

Iteration: 14305/59290
Iteration: 14306/59290
Iteration: 14307/59290
Iteration: 14308/59290
Iteration: 14309/59290
Iteration: 14310/59290
Iteration: 14311/59290
Iteration: 14312/59290
Iteration: 14313/59290
Iteration: 14314/59290
Iteration: 14315/59290
Iteration: 14316/59290
Iteration: 14317/59290
Iteration: 14318/59290
Iteration: 14319/59290
Iteration: 14320/59290
Iteration: 14321/59290
Iteration: 14322/59290
Iteration: 14323/59290
Iteration: 14324/59290
Iteration: 14325/59290
Iteration: 14326/59290
Iteration: 14327/59290
Iteration: 14328/59290

 24%|██▍       | 14324/59290 [10:37<1:29:01,  8.42it/s]

Iteration: 14329/59290
Iteration: 14330/59290
Iteration: 14331/59290
Iteration: 14332/59290
Iteration: 14333/59290
Iteration: 14334/59290
Iteration: 14335/59290
Iteration: 14336/59290
Iteration: 14337/59290
Iteration: 14338/59290
Iteration: 14339/59290
Iteration: 14340/59290
Iteration: 14341/59290
Iteration: 14342/59290
Iteration: 14343/59290
Iteration: 14344/59290
Iteration: 14345/59290
Iteration: 14346/59290
Iteration: 14347/59290
Iteration: 14348/59290
Iteration: 14349/59290
Iteration: 14350/59290
Iteration: 14351/59290
Iteration: 14352/59290

 24%|██▍       | 14348/59290 [10:37<1:05:47, 11.39it/s]

Iteration: 14353/59290
Iteration: 14354/59290
Iteration: 14355/59290
Iteration: 14356/59290
Iteration: 14357/59290
Iteration: 14358/59290
Iteration: 14359/59290
Iteration: 14360/59290
Iteration: 14361/59290
Iteration: 14362/59290
Iteration: 14363/59290
Iteration: 14364/59290
Iteration: 14365/59290
Iteration: 14366/59290
Iteration: 14367/59290
Iteration: 14368/59290
Iteration: 14369/59290
Iteration: 14370/59290
Iteration: 14371/59290
Iteration: 14372/59290
Iteration: 14373/59290
Iteration: 14374/59290
Iteration: 14375/59290
Iteration: 14376/59290

 24%|██▍       | 14372/59290 [10:38<49:44, 15.05it/s]

Iteration: 14377/59290
Iteration: 14378/59290
Iteration: 14379/59290
Iteration: 14380/59290
Iteration: 14381/59290
Iteration: 14382/59290
Iteration: 14383/59290
Iteration: 14384/59290
Iteration: 14385/59290
Iteration: 14386/59290
Iteration: 14387/59290
Iteration: 14388/59290
Iteration: 14389/59290
Iteration: 14390/59290
Iteration: 14391/59290
Iteration: 14392/59290
Iteration: 14393/59290
Iteration: 14394/59290
Iteration: 14395/59290
Iteration: 14396/59290
Iteration: 14397/59290
Iteration: 14398/59290
Iteration: 14399/59290
Iteration: 14400/59290

 24%|██▍       | 14396/59290 [10:38<38:18, 19.53it/s]

Iteration: 14401/59290
Iteration: 14402/59290
Iteration: 14403/59290
Iteration: 14404/59290
Iteration: 14405/59290
Iteration: 14406/59290
Iteration: 14407/59290
Iteration: 14408/59290
Iteration: 14409/59290
Iteration: 14410/59290
Iteration: 14411/59290
Iteration: 14412/59290
Iteration: 14413/59290
Iteration: 14414/59290
Iteration: 14415/59290
Iteration: 14416/59290
Iteration: 14417/59290
Iteration: 14418/59290
Iteration: 14419/59290
Iteration: 14420/59290
Iteration: 14421/59290
Iteration: 14422/59290
Iteration: 14423/59290
Iteration: 14424/59290

 24%|██▍       | 14420/59290 [10:38<30:28, 24.53it/s]

Iteration: 14425/59290
Iteration: 14426/59290
Iteration: 14427/59290
Iteration: 14428/59290
Iteration: 14429/59290
Iteration: 14430/59290
Iteration: 14431/59290
Iteration: 14432/59290
Iteration: 14433/59290
Iteration: 14434/59290
Iteration: 14435/59290
Iteration: 14436/59290
Iteration: 14437/59290
Iteration: 14438/59290
Iteration: 14439/59290
Iteration: 14440/59290
Iteration: 14441/59290
Iteration: 14442/59290
Iteration: 14443/59290
Iteration: 14444/59290
Iteration: 14445/59290
Iteration: 14446/59290
Iteration: 14447/59290
Iteration: 14448/59290

 24%|██▍       | 14444/59290 [10:39<24:54, 30.00it/s]

Iteration: 14449/59290
Iteration: 14450/59290
Iteration: 14451/59290
Iteration: 14452/59290
Iteration: 14453/59290
Iteration: 14454/59290
Iteration: 14455/59290
Iteration: 14456/59290
Iteration: 14457/59290
Iteration: 14458/59290
Iteration: 14459/59290
Iteration: 14460/59290
Iteration: 14461/59290
Iteration: 14462/59290
Iteration: 14463/59290
Iteration: 14464/59290
Iteration: 14465/59290
Iteration: 14466/59290
Iteration: 14467/59290
Iteration: 14468/59290
Iteration: 14469/59290
Iteration: 14470/59290
Iteration: 14471/59290
Iteration: 14472/59290

 24%|██▍       | 14468/59290 [10:39<21:09, 35.31it/s]

Iteration: 14473/59290
Iteration: 14474/59290
Iteration: 14475/59290
Iteration: 14476/59290
Iteration: 14477/59290
Iteration: 14478/59290
Iteration: 14479/59290
Iteration: 14480/59290
Iteration: 14481/59290
Iteration: 14482/59290
Iteration: 14483/59290
Iteration: 14484/59290
Iteration: 14485/59290
Iteration: 14486/59290
Iteration: 14487/59290
Iteration: 14488/59290
Iteration: 14489/59290
Iteration: 14490/59290
Iteration: 14491/59290
Iteration: 14492/59290
Iteration: 14493/59290
Iteration: 14494/59290
Iteration: 14495/59290
Iteration: 14496/59290

 24%|██▍       | 14492/59290 [10:40<18:20, 40.72it/s]

Iteration: 14497/59290
Iteration: 14498/59290
Iteration: 14499/59290
Iteration: 14500/59290
Iteration: 14501/59290
Iteration: 14502/59290
Iteration: 14503/59290
Iteration: 14504/59290
Iteration: 14505/59290
Iteration: 14506/59290
Iteration: 14507/59290
Iteration: 14508/59290
Iteration: 14509/59290
Iteration: 14510/59290
Iteration: 14511/59290
Iteration: 14512/59290
Iteration: 14513/59290
Iteration: 14514/59290
Iteration: 14515/59290
Iteration: 14516/59290
Iteration: 14517/59290
Iteration: 14518/59290
Iteration: 14519/59290
Iteration: 14520/59290

 24%|██▍       | 14516/59290 [10:40<16:20, 45.65it/s]

Iteration: 14521/59290
Iteration: 14522/59290
Iteration: 14523/59290
Iteration: 14524/59290
Iteration: 14525/59290
Iteration: 14526/59290
Iteration: 14527/59290
Iteration: 14528/59290
Iteration: 14529/59290
Iteration: 14530/59290
Iteration: 14531/59290
Iteration: 14532/59290
Iteration: 14533/59290
Iteration: 14534/59290
Iteration: 14535/59290
Iteration: 14536/59290
Iteration: 14537/59290
Iteration: 14538/59290
Iteration: 14539/59290
Iteration: 14540/59290
Iteration: 14541/59290
Iteration: 14542/59290
Iteration: 14543/59290
Iteration: 14544/59290

 25%|██▍       | 14540/59290 [10:40<14:59, 49.72it/s]

Iteration: 14545/59290
Iteration: 14546/59290
Iteration: 14547/59290
Iteration: 14548/59290
Iteration: 14549/59290
Iteration: 14550/59290
Iteration: 14551/59290
Iteration: 14552/59290
Iteration: 14553/59290
Iteration: 14554/59290
Iteration: 14555/59290
Iteration: 14556/59290
Iteration: 14557/59290
Iteration: 14558/59290
Iteration: 14559/59290
Iteration: 14560/59290
Iteration: 14561/59290
Iteration: 14562/59290
Iteration: 14563/59290
Iteration: 14564/59290
Iteration: 14565/59290
Iteration: 14566/59290
Iteration: 14567/59290
Iteration: 14568/59290

 25%|██▍       | 14564/59290 [10:41<13:57, 53.41it/s]

Iteration: 14569/59290
Iteration: 14570/59290
Iteration: 14571/59290
Iteration: 14572/59290
Iteration: 14573/59290
Iteration: 14574/59290
Iteration: 14575/59290
Iteration: 14576/59290
Iteration: 14577/59290
Iteration: 14578/59290
Iteration: 14579/59290
Iteration: 14580/59290
Iteration: 14581/59290
Iteration: 14582/59290
Iteration: 14583/59290
Iteration: 14584/59290
Iteration: 14585/59290
Iteration: 14586/59290
Iteration: 14587/59290
Iteration: 14588/59290
Iteration: 14589/59290
Iteration: 14590/59290
Iteration: 14591/59290
Iteration: 14592/59290

 25%|██▍       | 14588/59290 [10:41<13:19, 55.90it/s]

Iteration: 14593/59290
Iteration: 14594/59290
Iteration: 14595/59290
Iteration: 14596/59290
Iteration: 14597/59290
Iteration: 14598/59290
Iteration: 14599/59290
Iteration: 14600/59290
Iteration: 14601/59290
Iteration: 14602/59290
Iteration: 14603/59290
Iteration: 14604/59290
Iteration: 14605/59290
Iteration: 14606/59290
Iteration: 14607/59290
Iteration: 14608/59290
Iteration: 14609/59290
Iteration: 14610/59290
Iteration: 14611/59290
Iteration: 14612/59290
Iteration: 14613/59290
Iteration: 14614/59290
Iteration: 14615/59290
Iteration: 14616/59290

 25%|██▍       | 14612/59290 [10:43<22:44, 32.74it/s]

Iteration: 14617/59290
Iteration: 14618/59290
Iteration: 14619/59290
Iteration: 14620/59290
Iteration: 14621/59290
Iteration: 14622/59290
Iteration: 14623/59290
Iteration: 14624/59290
Iteration: 14625/59290
Iteration: 14626/59290
Iteration: 14627/59290
Iteration: 14628/59290
Iteration: 14629/59290
Iteration: 14630/59290
Iteration: 14631/59290
Iteration: 14632/59290
Iteration: 14633/59290
Iteration: 14634/59290
Iteration: 14635/59290
Iteration: 14636/59290
Iteration: 14637/59290
Iteration: 14638/59290
Iteration: 14639/59290
Iteration: 14640/59290

 25%|██▍       | 14636/59290 [10:45<35:33, 20.93it/s]

Iteration: 14641/59290
Iteration: 14642/59290
Iteration: 14643/59290
Iteration: 14644/59290
Iteration: 14645/59290
Iteration: 14646/59290
Iteration: 14647/59290
Iteration: 14648/59290
Iteration: 14649/59290
Iteration: 14650/59290
Iteration: 14651/59290
Iteration: 14652/59290
Iteration: 14653/59290
Iteration: 14654/59290
Iteration: 14655/59290
Iteration: 14656/59290
Iteration: 14657/59290
Iteration: 14658/59290
Iteration: 14659/59290
Iteration: 14660/59290
Iteration: 14661/59290
Iteration: 14662/59290
Iteration: 14663/59290
Iteration: 14664/59290

 25%|██▍       | 14660/59290 [10:45<28:34, 26.03it/s]

Iteration: 14665/59290
Iteration: 14666/59290
Iteration: 14667/59290
Iteration: 14668/59290
Iteration: 14669/59290
Iteration: 14670/59290
Iteration: 14671/59290
Iteration: 14672/59290
Iteration: 14673/59290
Iteration: 14674/59290
Iteration: 14675/59290
Iteration: 14676/59290
Iteration: 14677/59290
Iteration: 14678/59290
Iteration: 14679/59290
Iteration: 14680/59290
Iteration: 14681/59290
Iteration: 14682/59290
Iteration: 14683/59290
Iteration: 14684/59290
Iteration: 14685/59290
Iteration: 14686/59290
Iteration: 14687/59290
Iteration: 14688/59290

 25%|██▍       | 14684/59290 [10:46<25:04, 29.64it/s]

Iteration: 14689/59290
Iteration: 14690/59290
Iteration: 14691/59290
Iteration: 14692/59290
Iteration: 14693/59290
Iteration: 14694/59290
Iteration: 14695/59290
Iteration: 14696/59290
Iteration: 14697/59290
Iteration: 14698/59290
Iteration: 14699/59290
Iteration: 14700/59290
Iteration: 14701/59290
Iteration: 14702/59290
Iteration: 14703/59290
Iteration: 14704/59290
Iteration: 14705/59290
Iteration: 14706/59290
Iteration: 14707/59290
Iteration: 14708/59290
Iteration: 14709/59290
Iteration: 14710/59290
Iteration: 14711/59290
Iteration: 14712/59290

 25%|██▍       | 14708/59290 [10:46<21:06, 35.19it/s]

Iteration: 14713/59290
Iteration: 14714/59290
Iteration: 14715/59290
Iteration: 14716/59290
Iteration: 14717/59290
Iteration: 14718/59290
Iteration: 14719/59290
Iteration: 14720/59290
Iteration: 14721/59290
Iteration: 14722/59290
Iteration: 14723/59290
Iteration: 14724/59290
Iteration: 14725/59290
Iteration: 14726/59290
Iteration: 14727/59290
Iteration: 14728/59290
Iteration: 14729/59290
Iteration: 14730/59290
Iteration: 14731/59290
Iteration: 14732/59290
Iteration: 14733/59290
Iteration: 14734/59290
Iteration: 14735/59290
Iteration: 14736/59290

 25%|██▍       | 14732/59290 [10:46<18:30, 40.14it/s]

Iteration: 14737/59290
Iteration: 14738/59290
Iteration: 14739/59290
Iteration: 14740/59290
Iteration: 14741/59290
Iteration: 14742/59290
Iteration: 14743/59290
Iteration: 14744/59290
Iteration: 14745/59290
Iteration: 14746/59290
Iteration: 14747/59290
Iteration: 14748/59290
Iteration: 14749/59290
Iteration: 14750/59290
Iteration: 14751/59290
Iteration: 14752/59290
Iteration: 14753/59290
Iteration: 14754/59290
Iteration: 14755/59290
Iteration: 14756/59290
Iteration: 14757/59290
Iteration: 14758/59290
Iteration: 14759/59290
Iteration: 14760/59290

 25%|██▍       | 14756/59290 [10:47<16:34, 44.76it/s]

Iteration: 14761/59290
Iteration: 14762/59290
Iteration: 14763/59290
Iteration: 14764/59290
Iteration: 14765/59290
Iteration: 14766/59290
Iteration: 14767/59290
Iteration: 14768/59290
Iteration: 14769/59290
Iteration: 14770/59290
Iteration: 14771/59290
Iteration: 14772/59290
Iteration: 14773/59290
Iteration: 14774/59290
Iteration: 14775/59290
Iteration: 14776/59290
Iteration: 14777/59290
Iteration: 14778/59290
Iteration: 14779/59290
Iteration: 14780/59290
Iteration: 14781/59290
Iteration: 14782/59290
Iteration: 14783/59290
Iteration: 14784/59290

 25%|██▍       | 14780/59290 [10:47<15:13, 48.72it/s]

Iteration: 14785/59290
Iteration: 14786/59290
Iteration: 14787/59290
Iteration: 14788/59290
Iteration: 14789/59290
Iteration: 14790/59290
Iteration: 14791/59290
Iteration: 14792/59290
Iteration: 14793/59290
Iteration: 14794/59290
Iteration: 14795/59290
Iteration: 14796/59290
Iteration: 14797/59290
Iteration: 14798/59290
Iteration: 14799/59290
Iteration: 14800/59290
Iteration: 14801/59290
Iteration: 14802/59290
Iteration: 14803/59290
Iteration: 14804/59290
Iteration: 14805/59290
Iteration: 14806/59290
Iteration: 14807/59290
Iteration: 14808/59290

 25%|██▍       | 14804/59290 [10:49<24:30, 30.25it/s]

Iteration: 14809/59290
Iteration: 14810/59290
Iteration: 14811/59290
Iteration: 14812/59290
Iteration: 14813/59290
Iteration: 14814/59290
Iteration: 14815/59290
Iteration: 14816/59290
Iteration: 14817/59290
Iteration: 14818/59290
Iteration: 14819/59290
Iteration: 14820/59290
Iteration: 14821/59290
Iteration: 14822/59290
Iteration: 14823/59290
Iteration: 14824/59290
Iteration: 14825/59290
Iteration: 14826/59290
Iteration: 14827/59290
Iteration: 14828/59290
Iteration: 14829/59290
Iteration: 14830/59290
Iteration: 14831/59290
Iteration: 14832/59290

 25%|██▌       | 14828/59290 [10:51<41:54, 17.68it/s]

Iteration: 14833/59290
Iteration: 14834/59290
Iteration: 14835/59290
Iteration: 14836/59290
Iteration: 14837/59290
Iteration: 14838/59290
Iteration: 14839/59290
Iteration: 14840/59290
Iteration: 14841/59290
Iteration: 14842/59290
Iteration: 14843/59290
Iteration: 14844/59290
Iteration: 14845/59290
Iteration: 14846/59290
Iteration: 14847/59290
Iteration: 14848/59290
Iteration: 14849/59290
Iteration: 14850/59290
Iteration: 14851/59290
Iteration: 14852/59290
Iteration: 14853/59290
Iteration: 14854/59290
Iteration: 14855/59290
Iteration: 14856/59290

 25%|██▌       | 14852/59290 [10:52<33:12, 22.30it/s]

Iteration: 14857/59290
Iteration: 14858/59290
Iteration: 14859/59290
Iteration: 14860/59290
Iteration: 14861/59290
Iteration: 14862/59290
Iteration: 14863/59290
Iteration: 14864/59290
Iteration: 14865/59290
Iteration: 14866/59290
Iteration: 14867/59290
Iteration: 14868/59290
Iteration: 14869/59290
Iteration: 14870/59290
Iteration: 14871/59290
Iteration: 14872/59290
Iteration: 14873/59290
Iteration: 14874/59290
Iteration: 14875/59290
Iteration: 14876/59290
Iteration: 14877/59290
Iteration: 14878/59290
Iteration: 14879/59290
Iteration: 14880/59290

 25%|██▌       | 14876/59290 [10:52<26:45, 27.67it/s]

Iteration: 14881/59290
Iteration: 14882/59290
Iteration: 14883/59290
Iteration: 14884/59290
Iteration: 14885/59290
Iteration: 14886/59290
Iteration: 14887/59290
Iteration: 14888/59290
Iteration: 14889/59290
Iteration: 14890/59290
Iteration: 14891/59290
Iteration: 14892/59290
Iteration: 14893/59290
Iteration: 14894/59290
Iteration: 14895/59290
Iteration: 14896/59290
Iteration: 14897/59290
Iteration: 14898/59290
Iteration: 14899/59290
Iteration: 14900/59290
Iteration: 14901/59290
Iteration: 14902/59290
Iteration: 14903/59290
Iteration: 14904/59290

 25%|██▌       | 14900/59290 [10:53<22:28, 32.91it/s]

Iteration: 14905/59290
Iteration: 14906/59290
Iteration: 14907/59290
Iteration: 14908/59290
Iteration: 14909/59290
Iteration: 14910/59290
Iteration: 14911/59290
Iteration: 14912/59290
Iteration: 14913/59290
Iteration: 14914/59290
Iteration: 14915/59290
Iteration: 14916/59290
Iteration: 14917/59290
Iteration: 14918/59290
Iteration: 14919/59290
Iteration: 14920/59290
Iteration: 14921/59290
Iteration: 14922/59290
Iteration: 14923/59290
Iteration: 14924/59290
Iteration: 14925/59290
Iteration: 14926/59290
Iteration: 14927/59290
Iteration: 14928/59290

 25%|██▌       | 14924/59290 [10:53<19:17, 38.33it/s]

Iteration: 14929/59290
Iteration: 14930/59290
Iteration: 14931/59290
Iteration: 14932/59290
Iteration: 14933/59290
Iteration: 14934/59290
Iteration: 14935/59290
Iteration: 14936/59290
Iteration: 14937/59290
Iteration: 14938/59290
Iteration: 14939/59290
Iteration: 14940/59290
Iteration: 14941/59290
Iteration: 14942/59290
Iteration: 14943/59290
Iteration: 14944/59290
Iteration: 14945/59290
Iteration: 14946/59290
Iteration: 14947/59290
Iteration: 14948/59290
Iteration: 14949/59290
Iteration: 14950/59290
Iteration: 14951/59290
Iteration: 14952/59290

 25%|██▌       | 14948/59290 [10:54<27:49, 26.56it/s]

Iteration: 14953/59290
Iteration: 14954/59290
Iteration: 14955/59290
Iteration: 14956/59290
Iteration: 14957/59290
Iteration: 14958/59290
Iteration: 14959/59290
Iteration: 14960/59290
Iteration: 14961/59290
Iteration: 14962/59290
Iteration: 14963/59290
Iteration: 14964/59290
Iteration: 14965/59290
Iteration: 14966/59290
Iteration: 14967/59290
Iteration: 14968/59290
Iteration: 14969/59290
Iteration: 14970/59290
Iteration: 14971/59290
Iteration: 14972/59290
Iteration: 14973/59290
Iteration: 14974/59290
Iteration: 14975/59290
Iteration: 14976/59290

 25%|██▌       | 14972/59290 [10:57<39:01, 18.92it/s]

Iteration: 14977/59290
Iteration: 14978/59290
Iteration: 14979/59290
Iteration: 14980/59290
Iteration: 14981/59290
Iteration: 14982/59290
Iteration: 14983/59290
Iteration: 14984/59290
Iteration: 14985/59290
Iteration: 14986/59290
Iteration: 14987/59290
Iteration: 14988/59290
Iteration: 14989/59290
Iteration: 14990/59290
Iteration: 14991/59290
Iteration: 14992/59290
Iteration: 14993/59290
Iteration: 14994/59290
Iteration: 14995/59290
Iteration: 14996/59290
Iteration: 14997/59290
Iteration: 14998/59290
Iteration: 14999/59290
Iteration: 15000/59290

 25%|██▌       | 14996/59290 [10:57<30:49, 23.94it/s]

Iteration: 15001/59290
Iteration: 15002/59290
Iteration: 15003/59290
Iteration: 15004/59290
Iteration: 15005/59290
Iteration: 15006/59290
Iteration: 15007/59290
Iteration: 15008/59290
Iteration: 15009/59290
Iteration: 15010/59290
Iteration: 15011/59290
Iteration: 15012/59290
Iteration: 15013/59290
Iteration: 15014/59290
Iteration: 15015/59290
Iteration: 15016/59290
Iteration: 15017/59290
Iteration: 15018/59290
Iteration: 15019/59290
Iteration: 15020/59290
Iteration: 15021/59290
Iteration: 15022/59290
Iteration: 15023/59290
Iteration: 15024/59290

 25%|██▌       | 15020/59290 [10:58<29:19, 25.16it/s]

Iteration: 15025/59290
Iteration: 15026/59290
Iteration: 15027/59290
Iteration: 15028/59290
Iteration: 15029/59290
Iteration: 15030/59290
Iteration: 15031/59290
Iteration: 15032/59290
Iteration: 15033/59290
Iteration: 15034/59290
Iteration: 15035/59290
Iteration: 15036/59290
Iteration: 15037/59290
Iteration: 15038/59290
Iteration: 15039/59290
Iteration: 15040/59290
Iteration: 15041/59290
Iteration: 15042/59290
Iteration: 15043/59290
Iteration: 15044/59290
Iteration: 15045/59290
Iteration: 15046/59290
Iteration: 15047/59290
Iteration: 15048/59290

 25%|██▌       | 15044/59290 [10:58<24:03, 30.64it/s]

Iteration: 15049/59290
Iteration: 15050/59290
Iteration: 15051/59290
Iteration: 15052/59290
Iteration: 15053/59290
Iteration: 15054/59290
Iteration: 15055/59290
Iteration: 15056/59290
Iteration: 15057/59290
Iteration: 15058/59290
Iteration: 15059/59290
Iteration: 15060/59290
Iteration: 15061/59290
Iteration: 15062/59290
Iteration: 15063/59290
Iteration: 15064/59290
Iteration: 15065/59290
Iteration: 15066/59290
Iteration: 15067/59290
Iteration: 15068/59290
Iteration: 15069/59290
Iteration: 15070/59290
Iteration: 15071/59290
Iteration: 15072/59290

 25%|██▌       | 15068/59290 [10:59<20:30, 35.93it/s]

Iteration: 15073/59290
Iteration: 15074/59290
Iteration: 15075/59290
Iteration: 15076/59290
Iteration: 15077/59290
Iteration: 15078/59290
Iteration: 15079/59290
Iteration: 15080/59290
Iteration: 15081/59290
Iteration: 15082/59290
Iteration: 15083/59290
Iteration: 15084/59290
Iteration: 15085/59290
Iteration: 15086/59290
Iteration: 15087/59290
Iteration: 15088/59290
Iteration: 15089/59290
Iteration: 15090/59290
Iteration: 15091/59290
Iteration: 15092/59290
Iteration: 15093/59290
Iteration: 15094/59290
Iteration: 15095/59290
Iteration: 15096/59290

 25%|██▌       | 15092/59290 [10:59<17:51, 41.25it/s]

Iteration: 15097/59290
Iteration: 15098/59290
Iteration: 15099/59290
Iteration: 15100/59290
Iteration: 15101/59290
Iteration: 15102/59290
Iteration: 15103/59290
Iteration: 15104/59290
Iteration: 15105/59290
Iteration: 15106/59290
Iteration: 15107/59290
Iteration: 15108/59290
Iteration: 15109/59290
Iteration: 15110/59290
Iteration: 15111/59290
Iteration: 15112/59290
Iteration: 15113/59290
Iteration: 15114/59290
Iteration: 15115/59290
Iteration: 15116/59290
Iteration: 15117/59290
Iteration: 15118/59290
Iteration: 15119/59290
Iteration: 15120/59290

 25%|██▌       | 15116/59290 [10:59<15:57, 46.14it/s]

Iteration: 15121/59290
Iteration: 15122/59290
Iteration: 15123/59290
Iteration: 15124/59290
Iteration: 15125/59290
Iteration: 15126/59290
Iteration: 15127/59290
Iteration: 15128/59290
Iteration: 15129/59290
Iteration: 15130/59290
Iteration: 15131/59290
Iteration: 15132/59290
Iteration: 15133/59290
Iteration: 15134/59290
Iteration: 15135/59290
Iteration: 15136/59290
Iteration: 15137/59290
Iteration: 15138/59290
Iteration: 15139/59290
Iteration: 15140/59290
Iteration: 15141/59290
Iteration: 15142/59290
Iteration: 15143/59290
Iteration: 15144/59290

 26%|██▌       | 15140/59290 [11:00<14:48, 49.70it/s]

Iteration: 15145/59290
Iteration: 15146/59290
Iteration: 15147/59290
Iteration: 15148/59290
Iteration: 15149/59290
Iteration: 15150/59290
Iteration: 15151/59290
Iteration: 15152/59290
Iteration: 15153/59290
Iteration: 15154/59290
Iteration: 15155/59290
Iteration: 15156/59290
Iteration: 15157/59290
Iteration: 15158/59290
Iteration: 15159/59290
Iteration: 15160/59290
Iteration: 15161/59290
Iteration: 15162/59290
Iteration: 15163/59290
Iteration: 15164/59290
Iteration: 15165/59290
Iteration: 15166/59290
Iteration: 15167/59290
Iteration: 15168/59290

 26%|██▌       | 15164/59290 [11:00<13:51, 53.08it/s]

Iteration: 15169/59290
Iteration: 15170/59290
Iteration: 15171/59290
Iteration: 15172/59290
Iteration: 15173/59290
Iteration: 15174/59290
Iteration: 15175/59290
Iteration: 15176/59290
Iteration: 15177/59290
Iteration: 15178/59290
Iteration: 15179/59290
Iteration: 15180/59290
Iteration: 15181/59290
Iteration: 15182/59290
Iteration: 15183/59290
Iteration: 15184/59290
Iteration: 15185/59290
Iteration: 15186/59290
Iteration: 15187/59290
Iteration: 15188/59290
Iteration: 15189/59290
Iteration: 15190/59290
Iteration: 15191/59290
Iteration: 15192/59290

 26%|██▌       | 15188/59290 [11:01<13:20, 55.12it/s]

Iteration: 15193/59290
Iteration: 15194/59290
Iteration: 15195/59290
Iteration: 15196/59290
Iteration: 15197/59290
Iteration: 15198/59290
Iteration: 15199/59290
Iteration: 15200/59290
Iteration: 15201/59290
Iteration: 15202/59290
Iteration: 15203/59290
Iteration: 15204/59290
Iteration: 15205/59290
Iteration: 15206/59290
Iteration: 15207/59290
Iteration: 15208/59290
Iteration: 15209/59290
Iteration: 15210/59290
Iteration: 15211/59290
Iteration: 15212/59290
Iteration: 15213/59290
Iteration: 15214/59290
Iteration: 15215/59290
Iteration: 15216/59290

 26%|██▌       | 15212/59290 [11:01<13:06, 56.02it/s]

Iteration: 15217/59290
Iteration: 15218/59290
Iteration: 15219/59290
Iteration: 15220/59290
Iteration: 15221/59290
Iteration: 15222/59290
Iteration: 15223/59290
Iteration: 15224/59290
Iteration: 15225/59290
Iteration: 15226/59290
Iteration: 15227/59290
Iteration: 15228/59290
Iteration: 15229/59290
Iteration: 15230/59290
Iteration: 15231/59290
Iteration: 15232/59290
Iteration: 15233/59290
Iteration: 15234/59290
Iteration: 15235/59290
Iteration: 15236/59290
Iteration: 15237/59290
Iteration: 15238/59290
Iteration: 15239/59290
Iteration: 15240/59290

 26%|██▌       | 15236/59290 [11:01<12:51, 57.11it/s]

Iteration: 15241/59290
Iteration: 15242/59290
Iteration: 15243/59290
Iteration: 15244/59290
Iteration: 15245/59290
Iteration: 15246/59290
Iteration: 15247/59290
Iteration: 15248/59290
Iteration: 15249/59290
Iteration: 15250/59290
Iteration: 15251/59290
Iteration: 15252/59290
Iteration: 15253/59290
Iteration: 15254/59290
Iteration: 15255/59290
Iteration: 15256/59290
Iteration: 15257/59290
Iteration: 15258/59290
Iteration: 15259/59290
Iteration: 15260/59290
Iteration: 15261/59290
Iteration: 15262/59290
Iteration: 15263/59290
Iteration: 15264/59290

 26%|██▌       | 15260/59290 [11:02<12:37, 58.13it/s]

Iteration: 15265/59290
Iteration: 15266/59290
Iteration: 15267/59290
Iteration: 15268/59290
Iteration: 15269/59290
Iteration: 15270/59290
Iteration: 15271/59290
Iteration: 15272/59290
Iteration: 15273/59290
Iteration: 15274/59290
Iteration: 15275/59290
Iteration: 15276/59290
Iteration: 15277/59290
Iteration: 15278/59290
Iteration: 15279/59290
Iteration: 15280/59290
Iteration: 15281/59290
Iteration: 15282/59290
Iteration: 15283/59290
Iteration: 15284/59290
Iteration: 15285/59290
Iteration: 15286/59290
Iteration: 15287/59290
Iteration: 15288/59290

 26%|██▌       | 15284/59290 [11:02<12:16, 59.76it/s]

Iteration: 15289/59290
Iteration: 15290/59290
Iteration: 15291/59290
Iteration: 15292/59290
Iteration: 15293/59290
Iteration: 15294/59290
Iteration: 15295/59290
Iteration: 15296/59290
Iteration: 15297/59290
Iteration: 15298/59290
Iteration: 15299/59290
Iteration: 15300/59290
Iteration: 15301/59290
Iteration: 15302/59290
Iteration: 15303/59290
Iteration: 15304/59290
Iteration: 15305/59290
Iteration: 15306/59290
Iteration: 15307/59290
Iteration: 15308/59290
Iteration: 15309/59290
Iteration: 15310/59290
Iteration: 15311/59290
Iteration: 15312/59290

 26%|██▌       | 15308/59290 [11:02<12:03, 60.78it/s]

Iteration: 15313/59290
Iteration: 15314/59290
Iteration: 15315/59290
Iteration: 15316/59290
Iteration: 15317/59290
Iteration: 15318/59290
Iteration: 15319/59290
Iteration: 15320/59290
Iteration: 15321/59290
Iteration: 15322/59290
Iteration: 15323/59290
Iteration: 15324/59290
Iteration: 15325/59290
Iteration: 15326/59290
Iteration: 15327/59290
Iteration: 15328/59290
Iteration: 15329/59290
Iteration: 15330/59290
Iteration: 15331/59290
Iteration: 15332/59290
Iteration: 15333/59290
Iteration: 15334/59290
Iteration: 15335/59290
Iteration: 15336/59290

 26%|██▌       | 15332/59290 [11:03<11:50, 61.86it/s]

Iteration: 15337/59290
Iteration: 15338/59290
Iteration: 15339/59290
Iteration: 15340/59290
Iteration: 15341/59290
Iteration: 15342/59290
Iteration: 15343/59290
Iteration: 15344/59290
Iteration: 15345/59290
Iteration: 15346/59290
Iteration: 15347/59290
Iteration: 15348/59290
Iteration: 15349/59290
Iteration: 15350/59290
Iteration: 15351/59290
Iteration: 15352/59290
Iteration: 15353/59290
Iteration: 15354/59290
Iteration: 15355/59290
Iteration: 15356/59290
Iteration: 15357/59290
Iteration: 15358/59290
Iteration: 15359/59290
Iteration: 15360/59290

 26%|██▌       | 15356/59290 [11:04<20:29, 35.74it/s]

Iteration: 15361/59290
Iteration: 15362/59290
Iteration: 15363/59290
Iteration: 15364/59290
Iteration: 15365/59290
Iteration: 15366/59290
Iteration: 15367/59290
Iteration: 15368/59290
Iteration: 15369/59290
Iteration: 15370/59290
Iteration: 15371/59290
Iteration: 15372/59290
Iteration: 15373/59290
Iteration: 15374/59290
Iteration: 15375/59290
Iteration: 15376/59290
Iteration: 15377/59290
Iteration: 15378/59290
Iteration: 15379/59290
Iteration: 15380/59290
Iteration: 15381/59290
Iteration: 15382/59290
Iteration: 15383/59290
Iteration: 15384/59290

 26%|██▌       | 15380/59290 [11:06<33:56, 21.56it/s]

Iteration: 15385/59290
Iteration: 15386/59290
Iteration: 15387/59290
Iteration: 15388/59290
Iteration: 15389/59290
Iteration: 15390/59290
Iteration: 15391/59290
Iteration: 15392/59290
Iteration: 15393/59290
Iteration: 15394/59290
Iteration: 15395/59290
Iteration: 15396/59290
Iteration: 15397/59290
Iteration: 15398/59290
Iteration: 15399/59290
Iteration: 15400/59290
Iteration: 15401/59290
Iteration: 15402/59290
Iteration: 15403/59290
Iteration: 15404/59290
Iteration: 15405/59290
Iteration: 15406/59290
Iteration: 15407/59290
Iteration: 15408/59290

 26%|██▌       | 15404/59290 [11:07<31:49, 22.98it/s]

Iteration: 15409/59290
Iteration: 15410/59290
Iteration: 15411/59290
Iteration: 15412/59290
Iteration: 15413/59290
Iteration: 15414/59290
Iteration: 15415/59290
Iteration: 15416/59290
Iteration: 15417/59290
Iteration: 15418/59290
Iteration: 15419/59290
Iteration: 15420/59290
Iteration: 15421/59290
Iteration: 15422/59290
Iteration: 15423/59290
Iteration: 15424/59290
Iteration: 15425/59290
Iteration: 15426/59290
Iteration: 15427/59290
Iteration: 15428/59290
Iteration: 15429/59290
Iteration: 15430/59290
Iteration: 15431/59290
Iteration: 15432/59290

 26%|██▌       | 15428/59290 [11:08<25:41, 28.45it/s]

Iteration: 15433/59290
Iteration: 15434/59290
Iteration: 15435/59290
Iteration: 15436/59290
Iteration: 15437/59290
Iteration: 15438/59290
Iteration: 15439/59290
Iteration: 15440/59290
Iteration: 15441/59290
Iteration: 15442/59290
Iteration: 15443/59290
Iteration: 15444/59290
Iteration: 15445/59290
Iteration: 15446/59290
Iteration: 15447/59290
Iteration: 15448/59290
Iteration: 15449/59290
Iteration: 15450/59290
Iteration: 15451/59290
Iteration: 15452/59290
Iteration: 15453/59290
Iteration: 15454/59290
Iteration: 15455/59290
Iteration: 15456/59290

 26%|██▌       | 15452/59290 [11:08<21:24, 34.12it/s]

Iteration: 15457/59290
Iteration: 15458/59290
Iteration: 15459/59290
Iteration: 15460/59290
Iteration: 15461/59290
Iteration: 15462/59290
Iteration: 15463/59290
Iteration: 15464/59290
Iteration: 15465/59290
Iteration: 15466/59290
Iteration: 15467/59290
Iteration: 15468/59290
Iteration: 15469/59290
Iteration: 15470/59290
Iteration: 15471/59290
Iteration: 15472/59290
Iteration: 15473/59290
Iteration: 15474/59290
Iteration: 15475/59290
Iteration: 15476/59290
Iteration: 15477/59290
Iteration: 15478/59290
Iteration: 15479/59290
Iteration: 15480/59290

 26%|██▌       | 15476/59290 [11:08<18:27, 39.56it/s]

Iteration: 15481/59290
Iteration: 15482/59290
Iteration: 15483/59290
Iteration: 15484/59290
Iteration: 15485/59290
Iteration: 15486/59290
Iteration: 15487/59290
Iteration: 15488/59290
Iteration: 15489/59290
Iteration: 15490/59290
Iteration: 15491/59290
Iteration: 15492/59290
Iteration: 15493/59290
Iteration: 15494/59290
Iteration: 15495/59290
Iteration: 15496/59290
Iteration: 15497/59290
Iteration: 15498/59290
Iteration: 15499/59290
Iteration: 15500/59290
Iteration: 15501/59290
Iteration: 15502/59290
Iteration: 15503/59290
Iteration: 15504/59290

 26%|██▌       | 15500/59290 [11:09<16:22, 44.58it/s]

Iteration: 15505/59290
Iteration: 15506/59290
Iteration: 15507/59290
Iteration: 15508/59290
Iteration: 15509/59290
Iteration: 15510/59290
Iteration: 15511/59290
Iteration: 15512/59290
Iteration: 15513/59290
Iteration: 15514/59290
Iteration: 15515/59290
Iteration: 15516/59290
Iteration: 15517/59290
Iteration: 15518/59290
Iteration: 15519/59290
Iteration: 15520/59290
Iteration: 15521/59290
Iteration: 15522/59290
Iteration: 15523/59290
Iteration: 15524/59290
Iteration: 15525/59290
Iteration: 15526/59290
Iteration: 15527/59290
Iteration: 15528/59290

 26%|██▌       | 15524/59290 [11:09<14:56, 48.84it/s]

Iteration: 15529/59290
Iteration: 15530/59290
Iteration: 15531/59290
Iteration: 15532/59290
Iteration: 15533/59290
Iteration: 15534/59290
Iteration: 15535/59290
Iteration: 15536/59290
Iteration: 15537/59290
Iteration: 15538/59290
Iteration: 15539/59290
Iteration: 15540/59290
Iteration: 15541/59290
Iteration: 15542/59290
Iteration: 15543/59290
Iteration: 15544/59290
Iteration: 15545/59290
Iteration: 15546/59290
Iteration: 15547/59290
Iteration: 15548/59290
Iteration: 15549/59290
Iteration: 15550/59290
Iteration: 15551/59290
Iteration: 15552/59290

 26%|██▌       | 15548/59290 [11:09<13:49, 52.71it/s]

Iteration: 15553/59290
Iteration: 15554/59290
Iteration: 15555/59290
Iteration: 15556/59290
Iteration: 15557/59290
Iteration: 15558/59290
Iteration: 15559/59290
Iteration: 15560/59290
Iteration: 15561/59290
Iteration: 15562/59290
Iteration: 15563/59290
Iteration: 15564/59290
Iteration: 15565/59290
Iteration: 15566/59290
Iteration: 15567/59290
Iteration: 15568/59290
Iteration: 15569/59290
Iteration: 15570/59290
Iteration: 15571/59290
Iteration: 15572/59290
Iteration: 15573/59290
Iteration: 15574/59290
Iteration: 15575/59290
Iteration: 15576/59290

 26%|██▋       | 15572/59290 [11:10<13:06, 55.62it/s]

Iteration: 15577/59290
Iteration: 15578/59290
Iteration: 15579/59290
Iteration: 15580/59290
Iteration: 15581/59290
Iteration: 15582/59290
Iteration: 15583/59290
Iteration: 15584/59290
Iteration: 15585/59290
Iteration: 15586/59290
Iteration: 15587/59290
Iteration: 15588/59290
Iteration: 15589/59290
Iteration: 15590/59290
Iteration: 15591/59290
Iteration: 15592/59290
Iteration: 15593/59290
Iteration: 15594/59290
Iteration: 15595/59290
Iteration: 15596/59290
Iteration: 15597/59290
Iteration: 15598/59290
Iteration: 15599/59290
Iteration: 15600/59290

 26%|██▋       | 15596/59290 [11:10<12:51, 56.60it/s]

Iteration: 15601/59290
Iteration: 15602/59290
Iteration: 15603/59290
Iteration: 15604/59290
Iteration: 15605/59290
Iteration: 15606/59290
Iteration: 15607/59290
Iteration: 15608/59290
Iteration: 15609/59290
Iteration: 15610/59290
Iteration: 15611/59290
Iteration: 15612/59290
Iteration: 15613/59290
Iteration: 15614/59290
Iteration: 15615/59290
Iteration: 15616/59290
Iteration: 15617/59290
Iteration: 15618/59290
Iteration: 15619/59290
Iteration: 15620/59290
Iteration: 15621/59290
Iteration: 15622/59290
Iteration: 15623/59290
Iteration: 15624/59290

 26%|██▋       | 15620/59290 [11:11<12:23, 58.73it/s]

Iteration: 15625/59290
Iteration: 15626/59290
Iteration: 15627/59290
Iteration: 15628/59290
Iteration: 15629/59290
Iteration: 15630/59290
Iteration: 15631/59290
Iteration: 15632/59290
Iteration: 15633/59290
Iteration: 15634/59290
Iteration: 15635/59290
Iteration: 15636/59290
Iteration: 15637/59290
Iteration: 15638/59290
Iteration: 15639/59290
Iteration: 15640/59290
Iteration: 15641/59290
Iteration: 15642/59290
Iteration: 15643/59290
Iteration: 15644/59290
Iteration: 15645/59290
Iteration: 15646/59290
Iteration: 15647/59290
Iteration: 15648/59290

 26%|██▋       | 15644/59290 [11:11<12:14, 59.39it/s]

Iteration: 15649/59290
Iteration: 15650/59290
Iteration: 15651/59290
Iteration: 15652/59290
Iteration: 15653/59290
Iteration: 15654/59290
Iteration: 15655/59290
Iteration: 15656/59290
Iteration: 15657/59290
Iteration: 15658/59290
Iteration: 15659/59290
Iteration: 15660/59290
Iteration: 15661/59290
Iteration: 15662/59290
Iteration: 15663/59290
Iteration: 15664/59290
Iteration: 15665/59290
Iteration: 15666/59290
Iteration: 15667/59290
Iteration: 15668/59290
Iteration: 15669/59290
Iteration: 15670/59290
Iteration: 15671/59290
Iteration: 15672/59290

 26%|██▋       | 15668/59290 [11:11<12:11, 59.61it/s]

Iteration: 15673/59290
Iteration: 15674/59290
Iteration: 15675/59290
Iteration: 15676/59290
Iteration: 15677/59290
Iteration: 15678/59290
Iteration: 15679/59290
Iteration: 15680/59290
Iteration: 15681/59290
Iteration: 15682/59290
Iteration: 15683/59290
Iteration: 15684/59290
Iteration: 15685/59290
Iteration: 15686/59290
Iteration: 15687/59290
Iteration: 15688/59290
Iteration: 15689/59290
Iteration: 15690/59290
Iteration: 15691/59290
Iteration: 15692/59290
Iteration: 15693/59290
Iteration: 15694/59290
Iteration: 15695/59290
Iteration: 15696/59290

 26%|██▋       | 15692/59290 [11:12<12:01, 60.45it/s]

Iteration: 15697/59290
Iteration: 15698/59290
Iteration: 15699/59290
Iteration: 15700/59290
Iteration: 15701/59290
Iteration: 15702/59290
Iteration: 15703/59290
Iteration: 15704/59290
Iteration: 15705/59290
Iteration: 15706/59290
Iteration: 15707/59290
Iteration: 15708/59290
Iteration: 15709/59290
Iteration: 15710/59290
Iteration: 15711/59290
Iteration: 15712/59290
Iteration: 15713/59290
Iteration: 15714/59290
Iteration: 15715/59290
Iteration: 15716/59290
Iteration: 15717/59290
Iteration: 15718/59290
Iteration: 15719/59290
Iteration: 15720/59290

 27%|██▋       | 15716/59290 [11:12<11:53, 61.08it/s]

Iteration: 15721/59290
Iteration: 15722/59290
Iteration: 15723/59290
Iteration: 15724/59290
Iteration: 15725/59290
Iteration: 15726/59290
Iteration: 15727/59290
Iteration: 15728/59290
Iteration: 15729/59290
Iteration: 15730/59290
Iteration: 15731/59290
Iteration: 15732/59290
Iteration: 15733/59290
Iteration: 15734/59290
Iteration: 15735/59290
Iteration: 15736/59290
Iteration: 15737/59290
Iteration: 15738/59290
Iteration: 15739/59290
Iteration: 15740/59290
Iteration: 15741/59290
Iteration: 15742/59290
Iteration: 15743/59290
Iteration: 15744/59290

 27%|██▋       | 15740/59290 [11:13<11:55, 60.87it/s]

Iteration: 15745/59290
Iteration: 15746/59290
Iteration: 15747/59290
Iteration: 15748/59290
Iteration: 15749/59290
Iteration: 15750/59290
Iteration: 15751/59290
Iteration: 15752/59290
Iteration: 15753/59290
Iteration: 15754/59290
Iteration: 15755/59290
Iteration: 15756/59290
Iteration: 15757/59290
Iteration: 15758/59290
Iteration: 15759/59290
Iteration: 15760/59290
Iteration: 15761/59290
Iteration: 15762/59290
Iteration: 15763/59290
Iteration: 15764/59290
Iteration: 15765/59290
Iteration: 15766/59290
Iteration: 15767/59290
Iteration: 15768/59290

 27%|██▋       | 15764/59290 [11:13<12:02, 60.25it/s]

Iteration: 15769/59290
Iteration: 15770/59290
Iteration: 15771/59290
Iteration: 15772/59290
Iteration: 15773/59290
Iteration: 15774/59290
Iteration: 15775/59290
Iteration: 15776/59290
Iteration: 15777/59290
Iteration: 15778/59290
Iteration: 15779/59290
Iteration: 15780/59290
Iteration: 15781/59290
Iteration: 15782/59290
Iteration: 15783/59290
Iteration: 15784/59290
Iteration: 15785/59290
Iteration: 15786/59290
Iteration: 15787/59290
Iteration: 15788/59290
Iteration: 15789/59290
Iteration: 15790/59290
Iteration: 15791/59290
Iteration: 15792/59290

 27%|██▋       | 15788/59290 [11:13<11:58, 60.55it/s]

Iteration: 15793/59290
Iteration: 15794/59290
Iteration: 15795/59290
Iteration: 15796/59290
Iteration: 15797/59290
Iteration: 15798/59290
Iteration: 15799/59290
Iteration: 15800/59290
Iteration: 15801/59290
Iteration: 15802/59290
Iteration: 15803/59290
Iteration: 15804/59290
Iteration: 15805/59290
Iteration: 15806/59290
Iteration: 15807/59290
Iteration: 15808/59290
Iteration: 15809/59290
Iteration: 15810/59290
Iteration: 15811/59290
Iteration: 15812/59290
Iteration: 15813/59290
Iteration: 15814/59290
Iteration: 15815/59290
Iteration: 15816/59290

 27%|██▋       | 15812/59290 [11:14<11:48, 61.34it/s]

Iteration: 15817/59290
Iteration: 15818/59290
Iteration: 15819/59290
Iteration: 15820/59290
Iteration: 15821/59290
Iteration: 15822/59290
Iteration: 15823/59290
Iteration: 15824/59290
Iteration: 15825/59290
Iteration: 15826/59290
Iteration: 15827/59290
Iteration: 15828/59290
Iteration: 15829/59290
Iteration: 15830/59290
Iteration: 15831/59290
Iteration: 15832/59290
Iteration: 15833/59290
Iteration: 15834/59290
Iteration: 15835/59290
Iteration: 15836/59290
Iteration: 15837/59290
Iteration: 15838/59290
Iteration: 15839/59290
Iteration: 15840/59290

 27%|██▋       | 15836/59290 [11:14<11:41, 61.98it/s]

Iteration: 15841/59290
Iteration: 15842/59290
Iteration: 15843/59290
Iteration: 15844/59290
Iteration: 15845/59290
Iteration: 15846/59290
Iteration: 15847/59290
Iteration: 15848/59290
Iteration: 15849/59290
Iteration: 15850/59290
Iteration: 15851/59290
Iteration: 15852/59290
Iteration: 15853/59290
Iteration: 15854/59290
Iteration: 15855/59290
Iteration: 15856/59290
Iteration: 15857/59290
Iteration: 15858/59290
Iteration: 15859/59290
Iteration: 15860/59290
Iteration: 15861/59290
Iteration: 15862/59290
Iteration: 15863/59290
Iteration: 15864/59290

 27%|██▋       | 15860/59290 [11:16<23:29, 30.81it/s]

Iteration: 15865/59290
Iteration: 15866/59290
Iteration: 15867/59290
Iteration: 15868/59290
Iteration: 15869/59290
Iteration: 15870/59290
Iteration: 15871/59290
Iteration: 15872/59290
Iteration: 15873/59290
Iteration: 15874/59290
Iteration: 15875/59290
Iteration: 15876/59290
Iteration: 15877/59290
Iteration: 15878/59290
Iteration: 15879/59290
Iteration: 15880/59290
Iteration: 15881/59290
Iteration: 15882/59290
Iteration: 15883/59290
Iteration: 15884/59290
Iteration: 15885/59290
Iteration: 15886/59290
Iteration: 15887/59290
Iteration: 15888/59290

 27%|██▋       | 15884/59290 [11:51<5:32:45,  2.17it/s]

Iteration: 15889/59290
Iteration: 15890/59290
Iteration: 15891/59290
Iteration: 15892/59290
Iteration: 15893/59290
Iteration: 15894/59290
Iteration: 15895/59290
Iteration: 15896/59290
Iteration: 15897/59290
Iteration: 15898/59290
Iteration: 15899/59290
Iteration: 15900/59290
Iteration: 15901/59290
Iteration: 15902/59290
Iteration: 15903/59290
Iteration: 15904/59290
Iteration: 15905/59290
Iteration: 15906/59290
Iteration: 15907/59290
Iteration: 15908/59290
Iteration: 15909/59290
Iteration: 15910/59290
Iteration: 15911/59290
Iteration: 15912/59290

 27%|██▋       | 15908/59290 [11:51<3:57:07,  3.05it/s]

Iteration: 15913/59290
Iteration: 15914/59290
Iteration: 15915/59290
Iteration: 15916/59290
Iteration: 15917/59290
Iteration: 15918/59290
Iteration: 15919/59290
Iteration: 15920/59290
Iteration: 15921/59290
Iteration: 15922/59290
Iteration: 15923/59290
Iteration: 15924/59290
Iteration: 15925/59290
Iteration: 15926/59290
Iteration: 15927/59290
Iteration: 15928/59290
Iteration: 15929/59290
Iteration: 15930/59290
Iteration: 15931/59290
Iteration: 15932/59290
Iteration: 15933/59290
Iteration: 15934/59290
Iteration: 15935/59290
Iteration: 15936/59290

 27%|██▋       | 15932/59290 [11:52<2:49:27,  4.26it/s]

Iteration: 15937/59290
Iteration: 15938/59290
Iteration: 15939/59290
Iteration: 15940/59290
Iteration: 15941/59290
Iteration: 15942/59290
Iteration: 15943/59290
Iteration: 15944/59290
Iteration: 15945/59290
Iteration: 15946/59290
Iteration: 15947/59290
Iteration: 15948/59290
Iteration: 15949/59290
Iteration: 15950/59290
Iteration: 15951/59290
Iteration: 15952/59290
Iteration: 15953/59290
Iteration: 15954/59290
Iteration: 15955/59290
Iteration: 15956/59290
Iteration: 15957/59290
Iteration: 15958/59290
Iteration: 15959/59290
Iteration: 15960/59290

 27%|██▋       | 15956/59290 [11:52<2:01:56,  5.92it/s]

Iteration: 15961/59290
Iteration: 15962/59290
Iteration: 15963/59290
Iteration: 15964/59290
Iteration: 15965/59290
Iteration: 15966/59290
Iteration: 15967/59290
Iteration: 15968/59290
Iteration: 15969/59290
Iteration: 15970/59290
Iteration: 15971/59290
Iteration: 15972/59290
Iteration: 15973/59290
Iteration: 15974/59290
Iteration: 15975/59290
Iteration: 15976/59290
Iteration: 15977/59290
Iteration: 15978/59290
Iteration: 15979/59290
Iteration: 15980/59290
Iteration: 15981/59290
Iteration: 15982/59290
Iteration: 15983/59290
Iteration: 15984/59290

 27%|██▋       | 15980/59290 [11:52<1:28:56,  8.12it/s]

Iteration: 15985/59290
Iteration: 15986/59290
Iteration: 15987/59290
Iteration: 15988/59290
Iteration: 15989/59290
Iteration: 15990/59290
Iteration: 15991/59290
Iteration: 15992/59290
Iteration: 15993/59290
Iteration: 15994/59290
Iteration: 15995/59290
Iteration: 15996/59290
Iteration: 15997/59290
Iteration: 15998/59290
Iteration: 15999/59290
Iteration: 16000/59290
Iteration: 16001/59290
Iteration: 16002/59290
Iteration: 16003/59290
Iteration: 16004/59290
Iteration: 16005/59290
Iteration: 16006/59290
Iteration: 16007/59290
Iteration: 16008/59290

 27%|██▋       | 16004/59290 [11:54<1:15:08,  9.60it/s]

Iteration: 16009/59290
Iteration: 16010/59290
Iteration: 16011/59290
Iteration: 16012/59290
Iteration: 16013/59290
Iteration: 16014/59290
Iteration: 16015/59290
Iteration: 16016/59290
Iteration: 16017/59290
Iteration: 16018/59290
Iteration: 16019/59290
Iteration: 16020/59290
Iteration: 16021/59290
Iteration: 16022/59290
Iteration: 16023/59290
Iteration: 16024/59290
Iteration: 16025/59290
Iteration: 16026/59290
Iteration: 16027/59290
Iteration: 16028/59290
Iteration: 16029/59290
Iteration: 16030/59290
Iteration: 16031/59290
Iteration: 16032/59290

 27%|██▋       | 16028/59290 [11:56<1:10:49, 10.18it/s]

Iteration: 16033/59290
Iteration: 16034/59290
Iteration: 16035/59290
Iteration: 16036/59290
Iteration: 16037/59290
Iteration: 16038/59290
Iteration: 16039/59290
Iteration: 16040/59290
Iteration: 16041/59290
Iteration: 16042/59290
Iteration: 16043/59290
Iteration: 16044/59290
Iteration: 16045/59290
Iteration: 16046/59290
Iteration: 16047/59290
Iteration: 16048/59290
Iteration: 16049/59290
Iteration: 16050/59290
Iteration: 16051/59290
Iteration: 16052/59290
Iteration: 16053/59290
Iteration: 16054/59290
Iteration: 16055/59290
Iteration: 16056/59290

 27%|██▋       | 16052/59290 [11:57<55:42, 12.94it/s]

Iteration: 16057/59290
Iteration: 16058/59290
Iteration: 16059/59290
Iteration: 16060/59290
Iteration: 16061/59290
Iteration: 16062/59290
Iteration: 16063/59290
Iteration: 16064/59290
Iteration: 16065/59290
Iteration: 16066/59290
Iteration: 16067/59290
Iteration: 16068/59290
Iteration: 16069/59290
Iteration: 16070/59290
Iteration: 16071/59290
Iteration: 16072/59290
Iteration: 16073/59290
Iteration: 16074/59290
Iteration: 16075/59290
Iteration: 16076/59290
Iteration: 16077/59290
Iteration: 16078/59290
Iteration: 16079/59290
Iteration: 16080/59290

 27%|██▋       | 16076/59290 [11:57<42:21, 17.01it/s]

Iteration: 16081/59290
Iteration: 16082/59290
Iteration: 16083/59290
Iteration: 16084/59290
Iteration: 16085/59290
Iteration: 16086/59290
Iteration: 16087/59290
Iteration: 16088/59290
Iteration: 16089/59290
Iteration: 16090/59290
Iteration: 16091/59290
Iteration: 16092/59290
Iteration: 16093/59290
Iteration: 16094/59290
Iteration: 16095/59290
Iteration: 16096/59290
Iteration: 16097/59290
Iteration: 16098/59290
Iteration: 16099/59290
Iteration: 16100/59290
Iteration: 16101/59290
Iteration: 16102/59290
Iteration: 16103/59290
Iteration: 16104/59290

 27%|██▋       | 16100/59290 [11:57<32:59, 21.82it/s]

Iteration: 16105/59290
Iteration: 16106/59290
Iteration: 16107/59290
Iteration: 16108/59290
Iteration: 16109/59290
Iteration: 16110/59290
Iteration: 16111/59290
Iteration: 16112/59290
Iteration: 16113/59290
Iteration: 16114/59290
Iteration: 16115/59290
Iteration: 16116/59290
Iteration: 16117/59290
Iteration: 16118/59290
Iteration: 16119/59290
Iteration: 16120/59290
Iteration: 16121/59290
Iteration: 16122/59290
Iteration: 16123/59290
Iteration: 16124/59290
Iteration: 16125/59290
Iteration: 16126/59290
Iteration: 16127/59290
Iteration: 16128/59290

 27%|██▋       | 16124/59290 [11:58<26:42, 26.93it/s]

Iteration: 16129/59290
Iteration: 16130/59290
Iteration: 16131/59290
Iteration: 16132/59290
Iteration: 16133/59290
Iteration: 16134/59290
Iteration: 16135/59290
Iteration: 16136/59290
Iteration: 16137/59290
Iteration: 16138/59290
Iteration: 16139/59290
Iteration: 16140/59290
Iteration: 16141/59290
Iteration: 16142/59290
Iteration: 16143/59290
Iteration: 16144/59290
Iteration: 16145/59290
Iteration: 16146/59290
Iteration: 16147/59290
Iteration: 16148/59290
Iteration: 16149/59290
Iteration: 16150/59290
Iteration: 16151/59290
Iteration: 16152/59290

 27%|██▋       | 16148/59290 [11:58<22:03, 32.59it/s]

Iteration: 16153/59290
Iteration: 16154/59290
Iteration: 16155/59290
Iteration: 16156/59290
Iteration: 16157/59290
Iteration: 16158/59290
Iteration: 16159/59290
Iteration: 16160/59290
Iteration: 16161/59290
Iteration: 16162/59290
Iteration: 16163/59290
Iteration: 16164/59290
Iteration: 16165/59290
Iteration: 16166/59290
Iteration: 16167/59290
Iteration: 16168/59290
Iteration: 16169/59290
Iteration: 16170/59290
Iteration: 16171/59290
Iteration: 16172/59290
Iteration: 16173/59290
Iteration: 16174/59290
Iteration: 16176/59290

 27%|██▋       | 16171/59290 [11:59<19:21, 37.12it/s]

Iteration: 16177/59290
Iteration: 16178/59290
Iteration: 16179/59290
Iteration: 16180/59290
Iteration: 16181/59290
Iteration: 16182/59290
Iteration: 16183/59290
Iteration: 16184/59290

 27%|██▋       | 16179/59290 [11:59<21:22, 33.61it/s]

Iteration: 16185/59290
Iteration: 16186/59290
Iteration: 16187/59290
Iteration: 16188/59290
Iteration: 16189/59290
Iteration: 16190/59290
Iteration: 16191/59290
Iteration: 16192/59290
Iteration: 16193/59290
Iteration: 16194/59290
Iteration: 16195/59290
Iteration: 16196/59290
Iteration: 16197/59290
Iteration: 16198/59290
Iteration: 16199/59290
Iteration: 16200/59290
Iteration: 16201/59290
Iteration: 16202/59290
Iteration: 16203/59290
Iteration: 16204/59290
Iteration: 16205/59290
Iteration: 16206/59290
Iteration: 16207/59290
Iteration: 16208/59290

 27%|██▋       | 16203/59290 [11:59<17:52, 40.16it/s]

Iteration: 16209/59290
Iteration: 16210/59290
Iteration: 16211/59290
Iteration: 16212/59290
Iteration: 16213/59290
Iteration: 16214/59290
Iteration: 16215/59290
Iteration: 16216/59290
Iteration: 16217/59290
Iteration: 16218/59290
Iteration: 16219/59290
Iteration: 16220/59290
Iteration: 16221/59290
Iteration: 16222/59290
Iteration: 16223/59290
Iteration: 16224/59290
Iteration: 16225/59290
Iteration: 16226/59290
Iteration: 16227/59290
Iteration: 16228/59290
Iteration: 16229/59290
Iteration: 16230/59290
Iteration: 16231/59290
Iteration: 16232/59290

 27%|██▋       | 16227/59290 [12:00<15:43, 45.66it/s]

Iteration: 16233/59290
Iteration: 16234/59290
Iteration: 16235/59290
Iteration: 16236/59290
Iteration: 16237/59290
Iteration: 16238/59290
Iteration: 16239/59290
Iteration: 16240/59290
Iteration: 16241/59290
Iteration: 16242/59290
Iteration: 16243/59290
Iteration: 16244/59290
Iteration: 16245/59290
Iteration: 16246/59290
Iteration: 16247/59290
Iteration: 16248/59290
Iteration: 16249/59290
Iteration: 16250/59290
Iteration: 16251/59290
Iteration: 16252/59290
Iteration: 16253/59290
Iteration: 16254/59290
Iteration: 16255/59290
Iteration: 16256/59290

 27%|██▋       | 16251/59290 [12:00<14:14, 50.38it/s]

Iteration: 16257/59290
Iteration: 16258/59290
Iteration: 16259/59290
Iteration: 16260/59290
Iteration: 16261/59290
Iteration: 16262/59290
Iteration: 16263/59290
Iteration: 16264/59290
Iteration: 16265/59290
Iteration: 16266/59290
Iteration: 16267/59290
Iteration: 16268/59290
Iteration: 16269/59290
Iteration: 16270/59290
Iteration: 16271/59290
Iteration: 16272/59290
Iteration: 16273/59290
Iteration: 16274/59290
Iteration: 16275/59290
Iteration: 16276/59290
Iteration: 16277/59290
Iteration: 16278/59290
Iteration: 16279/59290
Iteration: 16280/59290

 27%|██▋       | 16275/59290 [12:02<23:34, 30.41it/s]

Iteration: 16281/59290
Iteration: 16282/59290
Iteration: 16283/59290
Iteration: 16284/59290
Iteration: 16285/59290
Iteration: 16286/59290
Iteration: 16287/59290
Iteration: 16288/59290
Iteration: 16289/59290
Iteration: 16290/59290
Iteration: 16291/59290
Iteration: 16292/59290
Iteration: 16293/59290
Iteration: 16294/59290
Iteration: 16295/59290
Iteration: 16296/59290
Iteration: 16297/59290
Iteration: 16298/59290
Iteration: 16299/59290
Iteration: 16300/59290
Iteration: 16301/59290
Iteration: 16302/59290
Iteration: 16303/59290
Iteration: 16304/59290

 27%|██▋       | 16299/59290 [12:04<39:14, 18.26it/s]

Iteration: 16305/59290
Iteration: 16306/59290
Iteration: 16307/59290
Iteration: 16308/59290
Iteration: 16309/59290
Iteration: 16310/59290
Iteration: 16311/59290
Iteration: 16312/59290
Iteration: 16313/59290
Iteration: 16314/59290
Iteration: 16315/59290
Iteration: 16316/59290
Iteration: 16317/59290
Iteration: 16318/59290
Iteration: 16319/59290
Iteration: 16320/59290
Iteration: 16321/59290
Iteration: 16322/59290
Iteration: 16323/59290
Iteration: 16324/59290
Iteration: 16325/59290
Iteration: 16326/59290
Iteration: 16327/59290
Iteration: 16328/59290

 28%|██▊       | 16323/59290 [12:04<30:38, 23.37it/s]

Iteration: 16329/59290
Iteration: 16330/59290
Iteration: 16331/59290
Iteration: 16332/59290
Iteration: 16333/59290
Iteration: 16334/59290
Iteration: 16335/59290
Iteration: 16336/59290
Iteration: 16337/59290
Iteration: 16338/59290
Iteration: 16339/59290
Iteration: 16340/59290
Iteration: 16341/59290
Iteration: 16342/59290
Iteration: 16343/59290
Iteration: 16344/59290
Iteration: 16345/59290
Iteration: 16346/59290
Iteration: 16347/59290
Iteration: 16348/59290
Iteration: 16349/59290
Iteration: 16350/59290
Iteration: 16351/59290
Iteration: 16352/59290

 28%|██▊       | 16347/59290 [12:05<24:56, 28.69it/s]

Iteration: 16353/59290
Iteration: 16354/59290
Iteration: 16355/59290
Iteration: 16356/59290
Iteration: 16357/59290
Iteration: 16358/59290
Iteration: 16359/59290
Iteration: 16360/59290
Iteration: 16361/59290
Iteration: 16362/59290
Iteration: 16363/59290
Iteration: 16364/59290
Iteration: 16365/59290
Iteration: 16366/59290
Iteration: 16367/59290
Iteration: 16368/59290
Iteration: 16369/59290
Iteration: 16370/59290
Iteration: 16371/59290
Iteration: 16372/59290
Iteration: 16373/59290
Iteration: 16374/59290
Iteration: 16375/59290
Iteration: 16376/59290

 28%|██▊       | 16371/59290 [12:05<20:48, 34.38it/s]

Iteration: 16377/59290
Iteration: 16378/59290
Iteration: 16379/59290
Iteration: 16380/59290
Iteration: 16381/59290
Iteration: 16382/59290
Iteration: 16383/59290
Iteration: 16384/59290
Iteration: 16385/59290
Iteration: 16386/59290
Iteration: 16387/59290
Iteration: 16388/59290
Iteration: 16389/59290
Iteration: 16390/59290
Iteration: 16391/59290
Iteration: 16392/59290
Iteration: 16393/59290
Iteration: 16394/59290
Iteration: 16395/59290
Iteration: 16396/59290
Iteration: 16397/59290
Iteration: 16398/59290
Iteration: 16399/59290
Iteration: 16400/59290

 28%|██▊       | 16395/59290 [12:07<26:50, 26.64it/s]

Iteration: 16401/59290
Iteration: 16402/59290
Iteration: 16403/59290
Iteration: 16404/59290
Iteration: 16405/59290
Iteration: 16406/59290
Iteration: 16407/59290
Iteration: 16408/59290
Iteration: 16409/59290
Iteration: 16410/59290
Iteration: 16411/59290
Iteration: 16412/59290
Iteration: 16413/59290
Iteration: 16414/59290
Iteration: 16415/59290
Iteration: 16416/59290
Iteration: 16417/59290
Iteration: 16418/59290
Iteration: 16419/59290
Iteration: 16420/59290
Iteration: 16421/59290
Iteration: 16422/59290
Iteration: 16423/59290
Iteration: 16424/59290

 28%|██▊       | 16419/59290 [12:09<38:03, 18.77it/s]

Iteration: 16425/59290
Iteration: 16426/59290
Iteration: 16427/59290
Iteration: 16428/59290
Iteration: 16429/59290
Iteration: 16430/59290
Iteration: 16431/59290
Iteration: 16432/59290
Iteration: 16433/59290
Iteration: 16434/59290
Iteration: 16435/59290
Iteration: 16436/59290
Iteration: 16437/59290
Iteration: 16438/59290
Iteration: 16439/59290
Iteration: 16440/59290
Iteration: 16441/59290
Iteration: 16442/59290
Iteration: 16443/59290
Iteration: 16444/59290
Iteration: 16445/59290
Iteration: 16446/59290
Iteration: 16447/59290
Iteration: 16448/59290

 28%|██▊       | 16443/59290 [12:09<31:18, 22.81it/s]

Iteration: 16449/59290
Iteration: 16450/59290
Iteration: 16451/59290
Iteration: 16452/59290
Iteration: 16453/59290
Iteration: 16454/59290
Iteration: 16455/59290
Iteration: 16456/59290
Iteration: 16457/59290
Iteration: 16458/59290
Iteration: 16459/59290
Iteration: 16460/59290
Iteration: 16461/59290
Iteration: 16462/59290
Iteration: 16463/59290
Iteration: 16464/59290
Iteration: 16465/59290
Iteration: 16466/59290
Iteration: 16467/59290
Iteration: 16468/59290
Iteration: 16469/59290
Iteration: 16470/59290
Iteration: 16471/59290
Iteration: 16472/59290

 28%|██▊       | 16467/59290 [12:10<25:14, 28.28it/s]

Iteration: 16473/59290
Iteration: 16474/59290
Iteration: 16475/59290
Iteration: 16476/59290
Iteration: 16477/59290
Iteration: 16478/59290
Iteration: 16479/59290
Iteration: 16480/59290
Iteration: 16481/59290
Iteration: 16482/59290
Iteration: 16483/59290
Iteration: 16484/59290
Iteration: 16485/59290
Iteration: 16486/59290
Iteration: 16487/59290
Iteration: 16488/59290
Iteration: 16489/59290
Iteration: 16490/59290
Iteration: 16491/59290
Iteration: 16492/59290
Iteration: 16493/59290
Iteration: 16494/59290
Iteration: 16495/59290
Iteration: 16496/59290

 28%|██▊       | 16491/59290 [12:10<20:57, 34.03it/s]

Iteration: 16497/59290
Iteration: 16498/59290
Iteration: 16499/59290
Iteration: 16500/59290
Iteration: 16501/59290
Iteration: 16502/59290
Iteration: 16503/59290
Iteration: 16504/59290
Iteration: 16505/59290
Iteration: 16506/59290
Iteration: 16507/59290
Iteration: 16508/59290
Iteration: 16509/59290
Iteration: 16510/59290
Iteration: 16511/59290
Iteration: 16512/59290
Iteration: 16513/59290
Iteration: 16514/59290
Iteration: 16515/59290
Iteration: 16516/59290
Iteration: 16517/59290
Iteration: 16518/59290
Iteration: 16519/59290
Iteration: 16520/59290

 28%|██▊       | 16515/59290 [12:10<17:58, 39.65it/s]

Iteration: 16521/59290
Iteration: 16522/59290
Iteration: 16523/59290
Iteration: 16524/59290
Iteration: 16525/59290
Iteration: 16526/59290
Iteration: 16527/59290
Iteration: 16528/59290
Iteration: 16529/59290
Iteration: 16530/59290
Iteration: 16531/59290
Iteration: 16532/59290
Iteration: 16533/59290
Iteration: 16534/59290
Iteration: 16535/59290
Iteration: 16536/59290
Iteration: 16537/59290
Iteration: 16538/59290
Iteration: 16539/59290
Iteration: 16540/59290
Iteration: 16541/59290
Iteration: 16542/59290
Iteration: 16543/59290
Iteration: 16544/59290

 28%|██▊       | 16539/59290 [12:11<16:03, 44.36it/s]

Iteration: 16545/59290
Iteration: 16546/59290
Iteration: 16547/59290
Iteration: 16548/59290
Iteration: 16549/59290
Iteration: 16550/59290
Iteration: 16551/59290
Iteration: 16552/59290
Iteration: 16553/59290
Iteration: 16554/59290
Iteration: 16555/59290
Iteration: 16556/59290
Iteration: 16557/59290
Iteration: 16558/59290
Iteration: 16559/59290
Iteration: 16560/59290
Iteration: 16561/59290
Iteration: 16562/59290
Iteration: 16563/59290
Iteration: 16564/59290
Iteration: 16565/59290
Iteration: 16566/59290
Iteration: 16567/59290
Iteration: 16568/59290

 28%|██▊       | 16563/59290 [12:11<14:44, 48.29it/s]

Iteration: 16569/59290
Iteration: 16570/59290
Iteration: 16571/59290
Iteration: 16572/59290
Iteration: 16573/59290
Iteration: 16574/59290
Iteration: 16575/59290
Iteration: 16576/59290
Iteration: 16577/59290
Iteration: 16578/59290
Iteration: 16579/59290
Iteration: 16580/59290
Iteration: 16581/59290
Iteration: 16582/59290
Iteration: 16583/59290
Iteration: 16584/59290
Iteration: 16585/59290
Iteration: 16586/59290
Iteration: 16587/59290
Iteration: 16588/59290
Iteration: 16589/59290
Iteration: 16590/59290
Iteration: 16591/59290
Iteration: 16592/59290

 28%|██▊       | 16587/59290 [12:12<13:38, 52.14it/s]

Iteration: 16593/59290
Iteration: 16594/59290
Iteration: 16595/59290
Iteration: 16596/59290
Iteration: 16597/59290
Iteration: 16598/59290
Iteration: 16599/59290
Iteration: 16600/59290
Iteration: 16601/59290
Iteration: 16602/59290
Iteration: 16603/59290
Iteration: 16604/59290
Iteration: 16605/59290
Iteration: 16606/59290
Iteration: 16607/59290
Iteration: 16608/59290
Iteration: 16609/59290
Iteration: 16610/59290
Iteration: 16611/59290
Iteration: 16612/59290
Iteration: 16613/59290
Iteration: 16614/59290
Iteration: 16615/59290
Iteration: 16616/59290

 28%|██▊       | 16611/59290 [12:12<12:55, 55.03it/s]

Iteration: 16617/59290
Iteration: 16618/59290
Iteration: 16619/59290
Iteration: 16620/59290
Iteration: 16621/59290
Iteration: 16622/59290
Iteration: 16623/59290
Iteration: 16624/59290
Iteration: 16625/59290
Iteration: 16626/59290
Iteration: 16627/59290
Iteration: 16628/59290
Iteration: 16629/59290
Iteration: 16630/59290
Iteration: 16631/59290
Iteration: 16632/59290
Iteration: 16633/59290
Iteration: 16634/59290
Iteration: 16635/59290
Iteration: 16636/59290
Iteration: 16637/59290
Iteration: 16638/59290
Iteration: 16639/59290
Iteration: 16640/59290

 28%|██▊       | 16635/59290 [12:12<12:25, 57.25it/s]

Iteration: 16641/59290
Iteration: 16642/59290
Iteration: 16643/59290
Iteration: 16644/59290
Iteration: 16645/59290
Iteration: 16646/59290
Iteration: 16647/59290
Iteration: 16648/59290
Iteration: 16649/59290
Iteration: 16650/59290
Iteration: 16651/59290
Iteration: 16652/59290
Iteration: 16653/59290
Iteration: 16654/59290
Iteration: 16655/59290
Iteration: 16656/59290
Iteration: 16657/59290
Iteration: 16658/59290
Iteration: 16659/59290
Iteration: 16660/59290
Iteration: 16661/59290
Iteration: 16662/59290
Iteration: 16663/59290
Iteration: 16664/59290

 28%|██▊       | 16659/59290 [12:13<12:09, 58.44it/s]

Iteration: 16665/59290
Iteration: 16666/59290
Iteration: 16667/59290
Iteration: 16668/59290
Iteration: 16669/59290
Iteration: 16670/59290
Iteration: 16671/59290
Iteration: 16672/59290
Iteration: 16673/59290
Iteration: 16674/59290
Iteration: 16675/59290
Iteration: 16676/59290
Iteration: 16677/59290
Iteration: 16678/59290
Iteration: 16679/59290
Iteration: 16680/59290
Iteration: 16681/59290
Iteration: 16682/59290
Iteration: 16683/59290
Iteration: 16684/59290
Iteration: 16685/59290
Iteration: 16686/59290
Iteration: 16687/59290
Iteration: 16688/59290

 28%|██▊       | 16683/59290 [12:13<11:56, 59.50it/s]

Iteration: 16689/59290
Iteration: 16690/59290
Iteration: 16691/59290
Iteration: 16692/59290
Iteration: 16693/59290
Iteration: 16694/59290
Iteration: 16695/59290
Iteration: 16696/59290
Iteration: 16697/59290
Iteration: 16698/59290
Iteration: 16699/59290
Iteration: 16700/59290
Iteration: 16701/59290
Iteration: 16702/59290
Iteration: 16703/59290
Iteration: 16704/59290
Iteration: 16705/59290
Iteration: 16706/59290
Iteration: 16707/59290
Iteration: 16708/59290
Iteration: 16709/59290
Iteration: 16710/59290
Iteration: 16711/59290
Iteration: 16712/59290

 28%|██▊       | 16707/59290 [12:13<11:41, 60.70it/s]

Iteration: 16713/59290
Iteration: 16714/59290
Iteration: 16715/59290
Iteration: 16716/59290
Iteration: 16717/59290
Iteration: 16718/59290
Iteration: 16719/59290
Iteration: 16720/59290
Iteration: 16721/59290
Iteration: 16722/59290
Iteration: 16723/59290
Iteration: 16724/59290
Iteration: 16725/59290
Iteration: 16726/59290
Iteration: 16727/59290
Iteration: 16728/59290
Iteration: 16729/59290
Iteration: 16730/59290
Iteration: 16731/59290
Iteration: 16732/59290
Iteration: 16733/59290
Iteration: 16734/59290
Iteration: 16735/59290
Iteration: 16736/59290

 28%|██▊       | 16731/59290 [12:14<11:35, 61.21it/s]

Iteration: 16737/59290
Iteration: 16738/59290
Iteration: 16739/59290
Iteration: 16740/59290
Iteration: 16741/59290
Iteration: 16742/59290
Iteration: 16743/59290
Iteration: 16744/59290
Iteration: 16745/59290
Iteration: 16746/59290
Iteration: 16747/59290
Iteration: 16748/59290
Iteration: 16749/59290
Iteration: 16750/59290
Iteration: 16751/59290
Iteration: 16752/59290
Iteration: 16753/59290
Iteration: 16754/59290
Iteration: 16755/59290
Iteration: 16756/59290
Iteration: 16757/59290
Iteration: 16758/59290
Iteration: 16759/59290
Iteration: 16760/59290

 28%|██▊       | 16755/59290 [12:14<11:29, 61.72it/s]

Iteration: 16761/59290
Iteration: 16762/59290
Iteration: 16763/59290
Iteration: 16764/59290
Iteration: 16765/59290
Iteration: 16766/59290
Iteration: 16767/59290
Iteration: 16768/59290
Iteration: 16769/59290
Iteration: 16770/59290
Iteration: 16771/59290
Iteration: 16772/59290
Iteration: 16773/59290
Iteration: 16774/59290
Iteration: 16775/59290
Iteration: 16776/59290
Iteration: 16777/59290
Iteration: 16778/59290
Iteration: 16779/59290
Iteration: 16780/59290
Iteration: 16781/59290
Iteration: 16782/59290
Iteration: 16783/59290
Iteration: 16784/59290

 28%|██▊       | 16779/59290 [12:15<11:25, 61.99it/s]

Iteration: 16785/59290
Iteration: 16786/59290
Iteration: 16787/59290
Iteration: 16788/59290
Iteration: 16789/59290
Iteration: 16790/59290
Iteration: 16791/59290
Iteration: 16792/59290
Iteration: 16793/59290
Iteration: 16794/59290
Iteration: 16795/59290
Iteration: 16796/59290
Iteration: 16797/59290
Iteration: 16798/59290
Iteration: 16799/59290
Iteration: 16800/59290
Iteration: 16801/59290
Iteration: 16802/59290
Iteration: 16803/59290
Iteration: 16804/59290
Iteration: 16805/59290
Iteration: 16806/59290
Iteration: 16807/59290
Iteration: 16808/59290

 28%|██▊       | 16803/59290 [12:15<11:20, 62.40it/s]

Iteration: 16809/59290
Iteration: 16810/59290
Iteration: 16811/59290
Iteration: 16812/59290
Iteration: 16813/59290
Iteration: 16814/59290
Iteration: 16815/59290
Iteration: 16816/59290
Iteration: 16817/59290
Iteration: 16818/59290
Iteration: 16819/59290
Iteration: 16820/59290
Iteration: 16821/59290
Iteration: 16822/59290
Iteration: 16823/59290
Iteration: 16824/59290
Iteration: 16825/59290
Iteration: 16826/59290
Iteration: 16827/59290
Iteration: 16828/59290
Iteration: 16829/59290
Iteration: 16830/59290
Iteration: 16831/59290
Iteration: 16832/59290

 28%|██▊       | 16827/59290 [12:15<11:33, 61.21it/s]

Iteration: 16833/59290
Iteration: 16834/59290
Iteration: 16835/59290
Iteration: 16836/59290
Iteration: 16837/59290
Iteration: 16838/59290
Iteration: 16839/59290
Iteration: 16840/59290
Iteration: 16841/59290
Iteration: 16842/59290
Iteration: 16843/59290
Iteration: 16844/59290
Iteration: 16845/59290
Iteration: 16846/59290
Iteration: 16847/59290
Iteration: 16848/59290
Iteration: 16849/59290
Iteration: 16850/59290
Iteration: 16851/59290
Iteration: 16852/59290
Iteration: 16853/59290
Iteration: 16854/59290
Iteration: 16855/59290
Iteration: 16856/59290

 28%|██▊       | 16851/59290 [12:17<19:43, 35.87it/s]

Iteration: 16857/59290
Iteration: 16858/59290
Iteration: 16859/59290
Iteration: 16860/59290
Iteration: 16861/59290
Iteration: 16862/59290
Iteration: 16863/59290
Iteration: 16864/59290
Iteration: 16865/59290
Iteration: 16866/59290
Iteration: 16867/59290
Iteration: 16868/59290
Iteration: 16869/59290
Iteration: 16870/59290
Iteration: 16871/59290
Iteration: 16872/59290
Iteration: 16873/59290
Iteration: 16874/59290
Iteration: 16875/59290
Iteration: 16876/59290
Iteration: 16877/59290
Iteration: 16878/59290
Iteration: 16879/59290
Iteration: 16880/59290

 28%|██▊       | 16875/59290 [12:19<32:36, 21.68it/s]

Iteration: 16881/59290
Iteration: 16882/59290
Iteration: 16883/59290
Iteration: 16884/59290
Iteration: 16885/59290
Iteration: 16886/59290
Iteration: 16887/59290
Iteration: 16888/59290
Iteration: 16889/59290
Iteration: 16890/59290
Iteration: 16891/59290
Iteration: 16892/59290
Iteration: 16893/59290
Iteration: 16894/59290
Iteration: 16895/59290
Iteration: 16896/59290
Iteration: 16897/59290
Iteration: 16898/59290
Iteration: 16899/59290
Iteration: 16900/59290
Iteration: 16901/59290
Iteration: 16902/59290
Iteration: 16903/59290
Iteration: 16904/59290

 29%|██▊       | 16899/59290 [12:20<29:41, 23.80it/s]

Iteration: 16905/59290
Iteration: 16906/59290
Iteration: 16907/59290
Iteration: 16908/59290
Iteration: 16909/59290
Iteration: 16910/59290
Iteration: 16911/59290
Iteration: 16912/59290
Iteration: 16913/59290
Iteration: 16914/59290
Iteration: 16915/59290
Iteration: 16916/59290
Iteration: 16917/59290
Iteration: 16918/59290
Iteration: 16919/59290
Iteration: 16920/59290
Iteration: 16921/59290
Iteration: 16922/59290
Iteration: 16923/59290
Iteration: 16924/59290
Iteration: 16925/59290
Iteration: 16926/59290
Iteration: 16927/59290
Iteration: 16928/59290

 29%|██▊       | 16923/59290 [12:20<24:24, 28.94it/s]

Iteration: 16929/59290
Iteration: 16930/59290
Iteration: 16931/59290
Iteration: 16932/59290
Iteration: 16933/59290
Iteration: 16934/59290
Iteration: 16935/59290
Iteration: 16936/59290
Iteration: 16937/59290
Iteration: 16938/59290
Iteration: 16939/59290
Iteration: 16940/59290
Iteration: 16941/59290
Iteration: 16942/59290
Iteration: 16943/59290
Iteration: 16944/59290
Iteration: 16945/59290
Iteration: 16946/59290
Iteration: 16947/59290
Iteration: 16948/59290
Iteration: 16949/59290
Iteration: 16950/59290
Iteration: 16951/59290
Iteration: 16952/59290

 29%|██▊       | 16947/59290 [12:20<20:20, 34.69it/s]

Iteration: 16953/59290
Iteration: 16954/59290
Iteration: 16955/59290
Iteration: 16956/59290
Iteration: 16957/59290
Iteration: 16958/59290
Iteration: 16959/59290
Iteration: 16960/59290
Iteration: 16961/59290
Iteration: 16962/59290
Iteration: 16963/59290
Iteration: 16964/59290
Iteration: 16965/59290
Iteration: 16966/59290
Iteration: 16967/59290
Iteration: 16968/59290
Iteration: 16969/59290
Iteration: 16970/59290
Iteration: 16971/59290
Iteration: 16972/59290
Iteration: 16973/59290
Iteration: 16974/59290
Iteration: 16975/59290
Iteration: 16976/59290

 29%|██▊       | 16971/59290 [12:21<17:45, 39.70it/s]

Iteration: 16977/59290
Iteration: 16978/59290
Iteration: 16979/59290
Iteration: 16980/59290
Iteration: 16981/59290
Iteration: 16982/59290
Iteration: 16983/59290
Iteration: 16984/59290
Iteration: 16985/59290
Iteration: 16986/59290
Iteration: 16987/59290
Iteration: 16988/59290
Iteration: 16989/59290
Iteration: 16990/59290
Iteration: 16991/59290
Iteration: 16992/59290
Iteration: 16993/59290
Iteration: 16994/59290
Iteration: 16995/59290
Iteration: 16996/59290
Iteration: 16997/59290
Iteration: 16998/59290
Iteration: 16999/59290
Iteration: 17000/59290

 29%|██▊       | 16995/59290 [12:21<15:43, 44.84it/s]

Iteration: 17001/59290
Iteration: 17002/59290
Iteration: 17003/59290
Iteration: 17004/59290
Iteration: 17005/59290
Iteration: 17006/59290
Iteration: 17007/59290
Iteration: 17008/59290
Iteration: 17009/59290
Iteration: 17010/59290
Iteration: 17011/59290
Iteration: 17012/59290
Iteration: 17013/59290
Iteration: 17014/59290
Iteration: 17015/59290
Iteration: 17016/59290
Iteration: 17017/59290
Iteration: 17018/59290
Iteration: 17019/59290
Iteration: 17020/59290
Iteration: 17021/59290
Iteration: 17022/59290
Iteration: 17023/59290
Iteration: 17024/59290

 29%|██▊       | 17019/59290 [12:23<23:40, 29.76it/s]

Iteration: 17025/59290
Iteration: 17026/59290
Iteration: 17027/59290
Iteration: 17028/59290
Iteration: 17029/59290
Iteration: 17030/59290
Iteration: 17031/59290
Iteration: 17032/59290
Iteration: 17033/59290
Iteration: 17034/59290
Iteration: 17035/59290
Iteration: 17036/59290
Iteration: 17037/59290
Iteration: 17038/59290
Iteration: 17039/59290
Iteration: 17040/59290
Iteration: 17041/59290
Iteration: 17042/59290
Iteration: 17043/59290
Iteration: 17044/59290
Iteration: 17045/59290
Iteration: 17046/59290
Iteration: 17047/59290
Iteration: 17048/59290

 29%|██▊       | 17043/59290 [12:25<35:28, 19.85it/s]

Iteration: 17049/59290
Iteration: 17050/59290
Iteration: 17051/59290
Iteration: 17052/59290
Iteration: 17053/59290
Iteration: 17054/59290
Iteration: 17055/59290
Iteration: 17056/59290
Iteration: 17057/59290
Iteration: 17058/59290
Iteration: 17059/59290
Iteration: 17060/59290
Iteration: 17061/59290
Iteration: 17062/59290
Iteration: 17063/59290
Iteration: 17064/59290
Iteration: 17065/59290
Iteration: 17066/59290
Iteration: 17067/59290
Iteration: 17068/59290
Iteration: 17069/59290
Iteration: 17070/59290
Iteration: 17071/59290
Iteration: 17072/59290

 29%|██▉       | 17067/59290 [12:25<31:09, 22.59it/s]

Iteration: 17073/59290
Iteration: 17074/59290
Iteration: 17075/59290
Iteration: 17076/59290
Iteration: 17077/59290
Iteration: 17078/59290
Iteration: 17079/59290
Iteration: 17080/59290
Iteration: 17081/59290
Iteration: 17082/59290
Iteration: 17083/59290
Iteration: 17084/59290
Iteration: 17085/59290
Iteration: 17086/59290
Iteration: 17087/59290
Iteration: 17088/59290
Iteration: 17089/59290
Iteration: 17090/59290
Iteration: 17091/59290
Iteration: 17092/59290
Iteration: 17093/59290
Iteration: 17094/59290
Iteration: 17095/59290
Iteration: 17096/59290

 29%|██▉       | 17091/59290 [12:26<25:21, 27.74it/s]

Iteration: 17097/59290
Iteration: 17098/59290
Iteration: 17099/59290
Iteration: 17100/59290
Iteration: 17101/59290
Iteration: 17102/59290
Iteration: 17103/59290
Iteration: 17104/59290
Iteration: 17105/59290
Iteration: 17106/59290
Iteration: 17107/59290
Iteration: 17108/59290
Iteration: 17109/59290
Iteration: 17110/59290
Iteration: 17111/59290
Iteration: 17112/59290
Iteration: 17113/59290
Iteration: 17114/59290
Iteration: 17115/59290
Iteration: 17116/59290
Iteration: 17117/59290
Iteration: 17118/59290
Iteration: 17119/59290
Iteration: 17120/59290

 29%|██▉       | 17115/59290 [12:26<21:16, 33.04it/s]

Iteration: 17121/59290
Iteration: 17122/59290
Iteration: 17123/59290
Iteration: 17124/59290
Iteration: 17125/59290
Iteration: 17126/59290
Iteration: 17127/59290
Iteration: 17128/59290
Iteration: 17129/59290
Iteration: 17130/59290
Iteration: 17131/59290
Iteration: 17132/59290
Iteration: 17133/59290
Iteration: 17134/59290
Iteration: 17135/59290
Iteration: 17136/59290
Iteration: 17137/59290
Iteration: 17138/59290
Iteration: 17139/59290
Iteration: 17140/59290
Iteration: 17141/59290
Iteration: 17142/59290
Iteration: 17143/59290
Iteration: 17144/59290

 29%|██▉       | 17139/59290 [12:27<18:13, 38.53it/s]

Iteration: 17145/59290
Iteration: 17146/59290
Iteration: 17147/59290
Iteration: 17148/59290
Iteration: 17149/59290
Iteration: 17150/59290
Iteration: 17151/59290
Iteration: 17152/59290
Iteration: 17153/59290
Iteration: 17154/59290
Iteration: 17155/59290
Iteration: 17156/59290
Iteration: 17157/59290
Iteration: 17158/59290
Iteration: 17159/59290
Iteration: 17160/59290
Iteration: 17161/59290
Iteration: 17162/59290
Iteration: 17163/59290
Iteration: 17164/59290
Iteration: 17165/59290
Iteration: 17166/59290
Iteration: 17167/59290
Iteration: 17168/59290

 29%|██▉       | 17163/59290 [12:27<16:13, 43.29it/s]

Iteration: 17169/59290
Iteration: 17170/59290
Iteration: 17171/59290
Iteration: 17172/59290
Iteration: 17173/59290
Iteration: 17174/59290
Iteration: 17175/59290
Iteration: 17176/59290
Iteration: 17177/59290
Iteration: 17178/59290
Iteration: 17179/59290
Iteration: 17180/59290
Iteration: 17181/59290
Iteration: 17182/59290
Iteration: 17183/59290
Iteration: 17184/59290
Iteration: 17185/59290
Iteration: 17186/59290
Iteration: 17187/59290
Iteration: 17188/59290
Iteration: 17189/59290
Iteration: 17190/59290
Iteration: 17191/59290
Iteration: 17192/59290

 29%|██▉       | 17187/59290 [12:27<14:39, 47.84it/s]

Iteration: 17193/59290
Iteration: 17194/59290
Iteration: 17195/59290
Iteration: 17196/59290
Iteration: 17197/59290
Iteration: 17198/59290
Iteration: 17199/59290
Iteration: 17200/59290
Iteration: 17201/59290
Iteration: 17202/59290
Iteration: 17203/59290
Iteration: 17204/59290
Iteration: 17205/59290
Iteration: 17206/59290
Iteration: 17207/59290
Iteration: 17208/59290
Iteration: 17209/59290
Iteration: 17210/59290
Iteration: 17211/59290
Iteration: 17212/59290
Iteration: 17213/59290
Iteration: 17214/59290
Iteration: 17215/59290
Iteration: 17216/59290

 29%|██▉       | 17211/59290 [12:28<13:32, 51.80it/s]

Iteration: 17217/59290
Iteration: 17218/59290
Iteration: 17219/59290
Iteration: 17220/59290
Iteration: 17221/59290
Iteration: 17222/59290
Iteration: 17223/59290
Iteration: 17224/59290
Iteration: 17225/59290
Iteration: 17226/59290
Iteration: 17227/59290
Iteration: 17228/59290
Iteration: 17229/59290
Iteration: 17230/59290
Iteration: 17231/59290
Iteration: 17232/59290
Iteration: 17233/59290
Iteration: 17234/59290
Iteration: 17235/59290
Iteration: 17236/59290
Iteration: 17237/59290
Iteration: 17238/59290
Iteration: 17239/59290
Iteration: 17240/59290

 29%|██▉       | 17235/59290 [12:28<12:43, 55.09it/s]

Iteration: 17241/59290
Iteration: 17242/59290
Iteration: 17243/59290
Iteration: 17244/59290
Iteration: 17245/59290
Iteration: 17246/59290
Iteration: 17247/59290
Iteration: 17248/59290
Iteration: 17249/59290
Iteration: 17250/59290
Iteration: 17251/59290
Iteration: 17252/59290
Iteration: 17253/59290
Iteration: 17254/59290
Iteration: 17255/59290
Iteration: 17256/59290
Iteration: 17257/59290
Iteration: 17258/59290
Iteration: 17259/59290
Iteration: 17260/59290
Iteration: 17261/59290
Iteration: 17262/59290
Iteration: 17263/59290
Iteration: 17264/59290

 29%|██▉       | 17259/59290 [12:29<12:10, 57.51it/s]

Iteration: 17265/59290
Iteration: 17266/59290
Iteration: 17267/59290
Iteration: 17268/59290
Iteration: 17269/59290
Iteration: 17270/59290
Iteration: 17271/59290
Iteration: 17272/59290
Iteration: 17273/59290
Iteration: 17274/59290
Iteration: 17275/59290
Iteration: 17276/59290
Iteration: 17277/59290
Iteration: 17278/59290
Iteration: 17279/59290
Iteration: 17280/59290
Iteration: 17281/59290
Iteration: 17282/59290
Iteration: 17283/59290
Iteration: 17284/59290
Iteration: 17285/59290
Iteration: 17286/59290
Iteration: 17287/59290
Iteration: 17288/59290

 29%|██▉       | 17283/59290 [12:29<11:45, 59.50it/s]

Iteration: 17289/59290
Iteration: 17290/59290
Iteration: 17291/59290
Iteration: 17292/59290
Iteration: 17293/59290
Iteration: 17294/59290
Iteration: 17295/59290
Iteration: 17296/59290
Iteration: 17297/59290
Iteration: 17298/59290
Iteration: 17299/59290
Iteration: 17300/59290
Iteration: 17301/59290
Iteration: 17302/59290
Iteration: 17303/59290
Iteration: 17304/59290
Iteration: 17305/59290
Iteration: 17306/59290
Iteration: 17307/59290
Iteration: 17308/59290
Iteration: 17309/59290
Iteration: 17310/59290
Iteration: 17311/59290
Iteration: 17312/59290

 29%|██▉       | 17307/59290 [12:33<41:11, 16.99it/s]

Iteration: 17313/59290
Iteration: 17314/59290
Iteration: 17315/59290
Iteration: 17316/59290
Iteration: 17317/59290
Iteration: 17318/59290
Iteration: 17319/59290
Iteration: 17320/59290
Iteration: 17321/59290
Iteration: 17322/59290
Iteration: 17323/59290
Iteration: 17324/59290
Iteration: 17325/59290
Iteration: 17326/59290
Iteration: 17327/59290
Iteration: 17328/59290
Iteration: 17329/59290
Iteration: 17330/59290
Iteration: 17331/59290
Iteration: 17332/59290
Iteration: 17333/59290
Iteration: 17334/59290
Iteration: 17335/59290
Iteration: 17336/59290

 29%|██▉       | 17331/59290 [12:33<35:10, 19.88it/s]

Iteration: 17337/59290
Iteration: 17338/59290
Iteration: 17339/59290
Iteration: 17340/59290
Iteration: 17341/59290
Iteration: 17342/59290
Iteration: 17343/59290
Iteration: 17344/59290
Iteration: 17345/59290
Iteration: 17346/59290
Iteration: 17347/59290
Iteration: 17348/59290
Iteration: 17349/59290
Iteration: 17350/59290
Iteration: 17351/59290
Iteration: 17352/59290
Iteration: 17353/59290
Iteration: 17354/59290
Iteration: 17355/59290
Iteration: 17356/59290
Iteration: 17357/59290
Iteration: 17358/59290
Iteration: 17359/59290
Iteration: 17360/59290

 29%|██▉       | 17355/59290 [12:34<28:09, 24.82it/s]

Iteration: 17361/59290
Iteration: 17362/59290
Iteration: 17363/59290
Iteration: 17364/59290
Iteration: 17365/59290
Iteration: 17366/59290
Iteration: 17367/59290
Iteration: 17368/59290
Iteration: 17369/59290
Iteration: 17370/59290
Iteration: 17371/59290
Iteration: 17372/59290
Iteration: 17373/59290
Iteration: 17374/59290
Iteration: 17375/59290
Iteration: 17376/59290
Iteration: 17377/59290
Iteration: 17378/59290
Iteration: 17379/59290
Iteration: 17380/59290
Iteration: 17381/59290
Iteration: 17382/59290
Iteration: 17383/59290
Iteration: 17384/59290

 29%|██▉       | 17379/59290 [12:34<22:59, 30.39it/s]

Iteration: 17385/59290
Iteration: 17386/59290
Iteration: 17387/59290
Iteration: 17388/59290
Iteration: 17389/59290
Iteration: 17390/59290
Iteration: 17391/59290
Iteration: 17392/59290
Iteration: 17393/59290
Iteration: 17394/59290
Iteration: 17395/59290
Iteration: 17396/59290
Iteration: 17397/59290
Iteration: 17398/59290
Iteration: 17399/59290
Iteration: 17400/59290
Iteration: 17401/59290
Iteration: 17402/59290
Iteration: 17403/59290
Iteration: 17404/59290
Iteration: 17405/59290
Iteration: 17406/59290
Iteration: 17407/59290
Iteration: 17408/59290

 29%|██▉       | 17403/59290 [12:35<19:25, 35.95it/s]

Iteration: 17409/59290
Iteration: 17410/59290
Iteration: 17411/59290
Iteration: 17412/59290
Iteration: 17413/59290
Iteration: 17414/59290
Iteration: 17415/59290
Iteration: 17416/59290
Iteration: 17417/59290
Iteration: 17418/59290
Iteration: 17419/59290
Iteration: 17420/59290
Iteration: 17421/59290
Iteration: 17422/59290
Iteration: 17423/59290
Iteration: 17424/59290
Iteration: 17425/59290
Iteration: 17426/59290
Iteration: 17427/59290
Iteration: 17428/59290
Iteration: 17429/59290
Iteration: 17430/59290
Iteration: 17431/59290
Iteration: 17432/59290

 29%|██▉       | 17427/59290 [12:36<27:05, 25.75it/s]

Iteration: 17433/59290
Iteration: 17434/59290
Iteration: 17435/59290
Iteration: 17436/59290
Iteration: 17437/59290
Iteration: 17438/59290
Iteration: 17439/59290
Iteration: 17440/59290
Iteration: 17441/59290
Iteration: 17442/59290
Iteration: 17443/59290
Iteration: 17444/59290
Iteration: 17445/59290
Iteration: 17446/59290
Iteration: 17447/59290
Iteration: 17448/59290
Iteration: 17449/59290
Iteration: 17450/59290
Iteration: 17451/59290
Iteration: 17452/59290
Iteration: 17453/59290
Iteration: 17454/59290
Iteration: 17455/59290
Iteration: 17456/59290

 29%|██▉       | 17451/59290 [12:38<37:04, 18.81it/s]

Iteration: 17457/59290
Iteration: 17458/59290
Iteration: 17459/59290
Iteration: 17460/59290
Iteration: 17461/59290
Iteration: 17462/59290
Iteration: 17463/59290
Iteration: 17464/59290
Iteration: 17465/59290
Iteration: 17466/59290
Iteration: 17467/59290
Iteration: 17468/59290
Iteration: 17469/59290
Iteration: 17470/59290
Iteration: 17471/59290
Iteration: 17472/59290
Iteration: 17473/59290
Iteration: 17474/59290
Iteration: 17475/59290
Iteration: 17476/59290
Iteration: 17477/59290
Iteration: 17478/59290
Iteration: 17479/59290
Iteration: 17480/59290

 29%|██▉       | 17475/59290 [12:39<31:51, 21.88it/s]

Iteration: 17481/59290
Iteration: 17482/59290
Iteration: 17483/59290
Iteration: 17484/59290
Iteration: 17485/59290
Iteration: 17486/59290
Iteration: 17487/59290
Iteration: 17488/59290
Iteration: 17489/59290
Iteration: 17490/59290
Iteration: 17491/59290
Iteration: 17492/59290
Iteration: 17493/59290
Iteration: 17494/59290
Iteration: 17495/59290
Iteration: 17496/59290
Iteration: 17497/59290
Iteration: 17498/59290
Iteration: 17499/59290
Iteration: 17500/59290
Iteration: 17501/59290
Iteration: 17502/59290
Iteration: 17503/59290
Iteration: 17504/59290

 30%|██▉       | 17499/59290 [12:39<25:31, 27.28it/s]

Iteration: 17505/59290
Iteration: 17506/59290
Iteration: 17507/59290
Iteration: 17508/59290
Iteration: 17509/59290
Iteration: 17510/59290
Iteration: 17511/59290
Iteration: 17512/59290
Iteration: 17513/59290
Iteration: 17514/59290
Iteration: 17515/59290
Iteration: 17516/59290
Iteration: 17517/59290
Iteration: 17518/59290
Iteration: 17519/59290
Iteration: 17520/59290
Iteration: 17521/59290
Iteration: 17522/59290
Iteration: 17523/59290
Iteration: 17524/59290
Iteration: 17525/59290
Iteration: 17526/59290
Iteration: 17527/59290
Iteration: 17528/59290

 30%|██▉       | 17523/59290 [12:40<21:24, 32.52it/s]

Iteration: 17529/59290
Iteration: 17530/59290
Iteration: 17531/59290
Iteration: 17532/59290
Iteration: 17533/59290
Iteration: 17534/59290
Iteration: 17535/59290
Iteration: 17536/59290
Iteration: 17537/59290
Iteration: 17538/59290
Iteration: 17539/59290
Iteration: 17540/59290
Iteration: 17541/59290
Iteration: 17542/59290
Iteration: 17543/59290
Iteration: 17544/59290
Iteration: 17545/59290
Iteration: 17546/59290
Iteration: 17547/59290
Iteration: 17548/59290
Iteration: 17549/59290
Iteration: 17550/59290
Iteration: 17551/59290
Iteration: 17552/59290

 30%|██▉       | 17547/59290 [12:40<18:13, 38.18it/s]

Iteration: 17553/59290
Iteration: 17554/59290
Iteration: 17555/59290
Iteration: 17556/59290
Iteration: 17557/59290
Iteration: 17558/59290
Iteration: 17559/59290
Iteration: 17560/59290
Iteration: 17561/59290
Iteration: 17562/59290
Iteration: 17563/59290
Iteration: 17564/59290
Iteration: 17565/59290
Iteration: 17566/59290
Iteration: 17567/59290
Iteration: 17568/59290
Iteration: 17569/59290
Iteration: 17570/59290
Iteration: 17571/59290
Iteration: 17572/59290
Iteration: 17573/59290
Iteration: 17574/59290
Iteration: 17575/59290
Iteration: 17576/59290

 30%|██▉       | 17571/59290 [12:40<16:02, 43.32it/s]

Iteration: 17577/59290
Iteration: 17578/59290
Iteration: 17579/59290
Iteration: 17580/59290
Iteration: 17581/59290
Iteration: 17582/59290
Iteration: 17583/59290
Iteration: 17584/59290
Iteration: 17585/59290
Iteration: 17586/59290
Iteration: 17587/59290
Iteration: 17588/59290
Iteration: 17589/59290
Iteration: 17590/59290
Iteration: 17591/59290
Iteration: 17592/59290
Iteration: 17593/59290
Iteration: 17594/59290
Iteration: 17595/59290
Iteration: 17596/59290
Iteration: 17597/59290
Iteration: 17598/59290
Iteration: 17599/59290
Iteration: 17600/59290

 30%|██▉       | 17595/59290 [12:41<14:29, 47.98it/s]

Iteration: 17601/59290
Iteration: 17602/59290
Iteration: 17603/59290
Iteration: 17604/59290
Iteration: 17605/59290
Iteration: 17606/59290
Iteration: 17607/59290
Iteration: 17608/59290
Iteration: 17609/59290
Iteration: 17610/59290
Iteration: 17611/59290
Iteration: 17612/59290
Iteration: 17613/59290
Iteration: 17614/59290
Iteration: 17615/59290
Iteration: 17616/59290
Iteration: 17617/59290
Iteration: 17618/59290
Iteration: 17619/59290
Iteration: 17620/59290
Iteration: 17621/59290
Iteration: 17622/59290
Iteration: 17623/59290
Iteration: 17624/59290

 30%|██▉       | 17619/59290 [12:41<13:26, 51.67it/s]

Iteration: 17625/59290
Iteration: 17626/59290
Iteration: 17627/59290
Iteration: 17628/59290
Iteration: 17629/59290
Iteration: 17630/59290
Iteration: 17631/59290
Iteration: 17632/59290
Iteration: 17633/59290
Iteration: 17634/59290
Iteration: 17635/59290
Iteration: 17636/59290
Iteration: 17637/59290
Iteration: 17638/59290
Iteration: 17639/59290
Iteration: 17640/59290
Iteration: 17641/59290
Iteration: 17642/59290
Iteration: 17643/59290
Iteration: 17644/59290
Iteration: 17645/59290
Iteration: 17646/59290
Iteration: 17647/59290
Iteration: 17648/59290

 30%|██▉       | 17643/59290 [12:42<12:41, 54.68it/s]

Iteration: 17649/59290
Iteration: 17650/59290
Iteration: 17651/59290
Iteration: 17652/59290
Iteration: 17653/59290
Iteration: 17654/59290
Iteration: 17655/59290
Iteration: 17656/59290
Iteration: 17657/59290
Iteration: 17658/59290
Iteration: 17659/59290
Iteration: 17660/59290
Iteration: 17661/59290
Iteration: 17662/59290
Iteration: 17663/59290
Iteration: 17664/59290
Iteration: 17665/59290
Iteration: 17666/59290
Iteration: 17667/59290
Iteration: 17668/59290
Iteration: 17669/59290
Iteration: 17670/59290
Iteration: 17671/59290
Iteration: 17672/59290

 30%|██▉       | 17667/59290 [12:42<12:09, 57.04it/s]

Iteration: 17673/59290
Iteration: 17674/59290
Iteration: 17675/59290
Iteration: 17676/59290
Iteration: 17677/59290
Iteration: 17678/59290
Iteration: 17679/59290
Iteration: 17680/59290
Iteration: 17681/59290
Iteration: 17682/59290
Iteration: 17683/59290
Iteration: 17684/59290
Iteration: 17685/59290
Iteration: 17686/59290
Iteration: 17687/59290
Iteration: 17688/59290
Iteration: 17689/59290
Iteration: 17690/59290
Iteration: 17691/59290
Iteration: 17692/59290
Iteration: 17693/59290
Iteration: 17694/59290
Iteration: 17695/59290
Iteration: 17696/59290

 30%|██▉       | 17691/59290 [12:42<11:57, 57.95it/s]

Iteration: 17697/59290
Iteration: 17698/59290
Iteration: 17699/59290
Iteration: 17700/59290
Iteration: 17701/59290
Iteration: 17702/59290
Iteration: 17703/59290
Iteration: 17704/59290
Iteration: 17705/59290
Iteration: 17706/59290
Iteration: 17707/59290
Iteration: 17708/59290
Iteration: 17709/59290
Iteration: 17710/59290
Iteration: 17711/59290
Iteration: 17712/59290
Iteration: 17713/59290
Iteration: 17714/59290
Iteration: 17715/59290
Iteration: 17716/59290
Iteration: 17717/59290
Iteration: 17718/59290
Iteration: 17719/59290
Iteration: 17720/59290

 30%|██▉       | 17715/59290 [12:43<11:49, 58.57it/s]

Iteration: 17721/59290
Iteration: 17722/59290
Iteration: 17723/59290
Iteration: 17724/59290
Iteration: 17725/59290
Iteration: 17726/59290
Iteration: 17727/59290
Iteration: 17728/59290
Iteration: 17729/59290
Iteration: 17730/59290
Iteration: 17731/59290
Iteration: 17732/59290
Iteration: 17733/59290
Iteration: 17734/59290
Iteration: 17735/59290
Iteration: 17736/59290
Iteration: 17737/59290
Iteration: 17738/59290
Iteration: 17739/59290
Iteration: 17740/59290
Iteration: 17741/59290
Iteration: 17742/59290
Iteration: 17743/59290
Iteration: 17744/59290

 30%|██▉       | 17739/59290 [12:43<11:33, 59.91it/s]

Iteration: 17745/59290
Iteration: 17746/59290
Iteration: 17747/59290
Iteration: 17748/59290
Iteration: 17749/59290
Iteration: 17750/59290
Iteration: 17751/59290
Iteration: 17752/59290
Iteration: 17753/59290
Iteration: 17754/59290
Iteration: 17755/59290
Iteration: 17756/59290
Iteration: 17757/59290
Iteration: 17758/59290
Iteration: 17759/59290
Iteration: 17760/59290
Iteration: 17761/59290
Iteration: 17762/59290
Iteration: 17763/59290
Iteration: 17764/59290
Iteration: 17765/59290
Iteration: 17766/59290
Iteration: 17767/59290
Iteration: 17768/59290

 30%|██▉       | 17763/59290 [12:43<11:21, 60.97it/s]

Iteration: 17769/59290
Iteration: 17770/59290
Iteration: 17771/59290
Iteration: 17772/59290
Iteration: 17773/59290
Iteration: 17774/59290
Iteration: 17775/59290
Iteration: 17776/59290
Iteration: 17777/59290
Iteration: 17778/59290
Iteration: 17779/59290
Iteration: 17780/59290
Iteration: 17781/59290
Iteration: 17782/59290
Iteration: 17783/59290
Iteration: 17784/59290
Iteration: 17785/59290
Iteration: 17786/59290
Iteration: 17787/59290
Iteration: 17788/59290
Iteration: 17789/59290
Iteration: 17790/59290
Iteration: 17791/59290
Iteration: 17792/59290

 30%|███       | 17787/59290 [12:44<11:13, 61.60it/s]

Iteration: 17793/59290
Iteration: 17794/59290
Iteration: 17795/59290
Iteration: 17796/59290
Iteration: 17797/59290
Iteration: 17798/59290
Iteration: 17799/59290
Iteration: 17800/59290
Iteration: 17801/59290
Iteration: 17802/59290
Iteration: 17803/59290
Iteration: 17804/59290
Iteration: 17805/59290
Iteration: 17806/59290
Iteration: 17807/59290
Iteration: 17808/59290
Iteration: 17809/59290
Iteration: 17810/59290
Iteration: 17811/59290
Iteration: 17812/59290
Iteration: 17813/59290
Iteration: 17814/59290
Iteration: 17815/59290
Iteration: 17816/59290

 30%|███       | 17811/59290 [12:44<11:20, 60.95it/s]

Iteration: 17817/59290
Iteration: 17818/59290
Iteration: 17819/59290
Iteration: 17820/59290
Iteration: 17821/59290
Iteration: 17822/59290
Iteration: 17823/59290
Iteration: 17824/59290
Iteration: 17825/59290
Iteration: 17826/59290
Iteration: 17827/59290
Iteration: 17828/59290
Iteration: 17829/59290
Iteration: 17830/59290
Iteration: 17831/59290
Iteration: 17832/59290
Iteration: 17833/59290
Iteration: 17834/59290
Iteration: 17835/59290
Iteration: 17836/59290
Iteration: 17837/59290
Iteration: 17838/59290
Iteration: 17839/59290
Iteration: 17840/59290

 30%|███       | 17835/59290 [12:45<11:15, 61.40it/s]

Iteration: 17841/59290
Iteration: 17842/59290
Iteration: 17843/59290
Iteration: 17844/59290
Iteration: 17845/59290
Iteration: 17846/59290
Iteration: 17847/59290
Iteration: 17848/59290
Iteration: 17849/59290
Iteration: 17850/59290
Iteration: 17851/59290
Iteration: 17852/59290
Iteration: 17853/59290
Iteration: 17854/59290
Iteration: 17855/59290
Iteration: 17856/59290
Iteration: 17857/59290
Iteration: 17858/59290
Iteration: 17859/59290
Iteration: 17860/59290
Iteration: 17861/59290
Iteration: 17862/59290
Iteration: 17863/59290
Iteration: 17864/59290

 30%|███       | 17859/59290 [12:45<11:14, 61.47it/s]

Iteration: 17865/59290
Iteration: 17866/59290
Iteration: 17867/59290
Iteration: 17868/59290
Iteration: 17869/59290
Iteration: 17870/59290
Iteration: 17871/59290
Iteration: 17872/59290
Iteration: 17873/59290
Iteration: 17874/59290
Iteration: 17875/59290
Iteration: 17876/59290
Iteration: 17877/59290
Iteration: 17878/59290
Iteration: 17879/59290
Iteration: 17880/59290
Iteration: 17881/59290
Iteration: 17882/59290
Iteration: 17883/59290
Iteration: 17884/59290
Iteration: 17885/59290
Iteration: 17886/59290
Iteration: 17887/59290
Iteration: 17888/59290

 30%|███       | 17883/59290 [12:45<11:06, 62.10it/s]

Iteration: 17889/59290
Iteration: 17890/59290
Iteration: 17891/59290
Iteration: 17892/59290
Iteration: 17893/59290
Iteration: 17894/59290
Iteration: 17895/59290
Iteration: 17896/59290
Iteration: 17897/59290
Iteration: 17898/59290
Iteration: 17899/59290
Iteration: 17900/59290
Iteration: 17901/59290
Iteration: 17902/59290
Iteration: 17903/59290
Iteration: 17904/59290
Iteration: 17905/59290
Iteration: 17906/59290
Iteration: 17907/59290
Iteration: 17908/59290
Iteration: 17909/59290
Iteration: 17910/59290
Iteration: 17911/59290
Iteration: 17912/59290

 30%|███       | 17907/59290 [12:46<11:14, 61.34it/s]

Iteration: 17913/59290
Iteration: 17914/59290
Iteration: 17915/59290
Iteration: 17916/59290
Iteration: 17917/59290
Iteration: 17918/59290
Iteration: 17919/59290
Iteration: 17920/59290
Iteration: 17921/59290
Iteration: 17922/59290
Iteration: 17923/59290
Iteration: 17924/59290
Iteration: 17925/59290
Iteration: 17926/59290
Iteration: 17927/59290
Iteration: 17928/59290
Iteration: 17929/59290
Iteration: 17930/59290
Iteration: 17931/59290
Iteration: 17932/59290
Iteration: 17933/59290
Iteration: 17934/59290
Iteration: 17935/59290
Iteration: 17936/59290

 30%|███       | 17931/59290 [12:46<11:06, 62.07it/s]

Iteration: 17937/59290
Iteration: 17938/59290
Iteration: 17939/59290
Iteration: 17940/59290
Iteration: 17941/59290
Iteration: 17942/59290
Iteration: 17943/59290
Iteration: 17944/59290
Iteration: 17945/59290
Iteration: 17946/59290
Iteration: 17947/59290
Iteration: 17948/59290
Iteration: 17949/59290
Iteration: 17950/59290
Iteration: 17951/59290
Iteration: 17952/59290
Iteration: 17953/59290
Iteration: 17954/59290
Iteration: 17955/59290
Iteration: 17956/59290
Iteration: 17957/59290
Iteration: 17958/59290
Iteration: 17959/59290
Iteration: 17960/59290

 30%|███       | 17955/59290 [13:19<4:47:53,  2.39it/s]

Iteration: 17961/59290
Iteration: 17962/59290
Iteration: 17963/59290
Iteration: 17964/59290
Iteration: 17965/59290
Iteration: 17966/59290
Iteration: 17967/59290
Iteration: 17968/59290
Iteration: 17969/59290
Iteration: 17970/59290
Iteration: 17971/59290
Iteration: 17972/59290
Iteration: 17973/59290
Iteration: 17974/59290
Iteration: 17975/59290
Iteration: 17976/59290
Iteration: 17977/59290
Iteration: 17978/59290
Iteration: 17979/59290
Iteration: 17980/59290
Iteration: 17981/59290
Iteration: 17982/59290
Iteration: 17983/59290
Iteration: 17984/59290

 30%|███       | 17979/59290 [13:19<3:24:41,  3.36it/s]

Iteration: 17985/59290
Iteration: 17986/59290
Iteration: 17987/59290
Iteration: 17988/59290
Iteration: 17989/59290
Iteration: 17990/59290
Iteration: 17991/59290
Iteration: 17992/59290
Iteration: 17993/59290
Iteration: 17994/59290
Iteration: 17995/59290
Iteration: 17996/59290
Iteration: 17997/59290
Iteration: 17998/59290
Iteration: 17999/59290
Iteration: 18000/59290
Iteration: 18001/59290
Iteration: 18002/59290
Iteration: 18003/59290
Iteration: 18004/59290
Iteration: 18005/59290
Iteration: 18006/59290
Iteration: 18007/59290
Iteration: 18008/59290

 30%|███       | 18003/59290 [13:19<2:26:25,  4.70it/s]

Iteration: 18009/59290
Iteration: 18010/59290
Iteration: 18011/59290
Iteration: 18012/59290
Iteration: 18013/59290
Iteration: 18014/59290
Iteration: 18015/59290
Iteration: 18016/59290
Iteration: 18017/59290
Iteration: 18018/59290
Iteration: 18019/59290
Iteration: 18020/59290
Iteration: 18021/59290
Iteration: 18022/59290
Iteration: 18023/59290
Iteration: 18024/59290
Iteration: 18025/59290
Iteration: 18026/59290
Iteration: 18027/59290
Iteration: 18028/59290
Iteration: 18029/59290
Iteration: 18030/59290
Iteration: 18031/59290
Iteration: 18032/59290

 30%|███       | 18027/59290 [13:20<1:45:41,  6.51it/s]

Iteration: 18033/59290
Iteration: 18034/59290
Iteration: 18035/59290
Iteration: 18036/59290
Iteration: 18037/59290
Iteration: 18038/59290
Iteration: 18039/59290
Iteration: 18040/59290
Iteration: 18041/59290
Iteration: 18042/59290
Iteration: 18043/59290
Iteration: 18044/59290
Iteration: 18045/59290
Iteration: 18046/59290
Iteration: 18047/59290
Iteration: 18048/59290
Iteration: 18049/59290
Iteration: 18050/59290
Iteration: 18051/59290
Iteration: 18052/59290
Iteration: 18053/59290
Iteration: 18054/59290
Iteration: 18055/59290
Iteration: 18056/59290

 30%|███       | 18051/59290 [13:20<1:17:13,  8.90it/s]

Iteration: 18057/59290
Iteration: 18058/59290
Iteration: 18059/59290
Iteration: 18060/59290
Iteration: 18061/59290
Iteration: 18062/59290
Iteration: 18063/59290
Iteration: 18064/59290
Iteration: 18065/59290
Iteration: 18066/59290
Iteration: 18067/59290
Iteration: 18068/59290
Iteration: 18069/59290
Iteration: 18070/59290
Iteration: 18071/59290
Iteration: 18072/59290
Iteration: 18073/59290
Iteration: 18074/59290
Iteration: 18075/59290
Iteration: 18076/59290
Iteration: 18077/59290
Iteration: 18078/59290
Iteration: 18079/59290
Iteration: 18080/59290

 30%|███       | 18075/59290 [13:22<1:08:48,  9.98it/s]

Iteration: 18081/59290
Iteration: 18082/59290
Iteration: 18083/59290
Iteration: 18084/59290
Iteration: 18085/59290
Iteration: 18086/59290
Iteration: 18087/59290
Iteration: 18088/59290
Iteration: 18089/59290
Iteration: 18090/59290
Iteration: 18091/59290
Iteration: 18092/59290
Iteration: 18093/59290
Iteration: 18094/59290
Iteration: 18095/59290
Iteration: 18096/59290
Iteration: 18097/59290
Iteration: 18098/59290
Iteration: 18099/59290
Iteration: 18100/59290
Iteration: 18101/59290
Iteration: 18102/59290
Iteration: 18103/59290
Iteration: 18104/59290

 31%|███       | 18099/59290 [13:25<1:12:18,  9.49it/s]

Iteration: 18105/59290
Iteration: 18106/59290
Iteration: 18107/59290
Iteration: 18108/59290
Iteration: 18109/59290
Iteration: 18110/59290
Iteration: 18111/59290
Iteration: 18112/59290
Iteration: 18113/59290
Iteration: 18114/59290
Iteration: 18115/59290
Iteration: 18116/59290
Iteration: 18117/59290
Iteration: 18118/59290
Iteration: 18119/59290
Iteration: 18120/59290
Iteration: 18121/59290
Iteration: 18122/59290
Iteration: 18123/59290
Iteration: 18124/59290
Iteration: 18125/59290
Iteration: 18126/59290
Iteration: 18127/59290
Iteration: 18128/59290

 31%|███       | 18123/59290 [13:25<54:12, 12.66it/s]

Iteration: 18129/59290
Iteration: 18130/59290
Iteration: 18131/59290
Iteration: 18132/59290
Iteration: 18133/59290
Iteration: 18134/59290
Iteration: 18135/59290
Iteration: 18136/59290
Iteration: 18137/59290
Iteration: 18138/59290
Iteration: 18139/59290
Iteration: 18140/59290
Iteration: 18141/59290
Iteration: 18142/59290
Iteration: 18143/59290
Iteration: 18144/59290
Iteration: 18145/59290
Iteration: 18146/59290
Iteration: 18147/59290
Iteration: 18148/59290
Iteration: 18149/59290
Iteration: 18150/59290
Iteration: 18151/59290
Iteration: 18152/59290

 31%|███       | 18147/59290 [13:26<41:09, 16.66it/s]

Iteration: 18153/59290
Iteration: 18154/59290
Iteration: 18155/59290
Iteration: 18156/59290
Iteration: 18157/59290
Iteration: 18158/59290
Iteration: 18159/59290
Iteration: 18160/59290
Iteration: 18161/59290
Iteration: 18162/59290
Iteration: 18163/59290
Iteration: 18164/59290
Iteration: 18165/59290
Iteration: 18166/59290
Iteration: 18167/59290
Iteration: 18168/59290
Iteration: 18169/59290
Iteration: 18170/59290
Iteration: 18171/59290
Iteration: 18172/59290
Iteration: 18173/59290
Iteration: 18174/59290
Iteration: 18175/59290
Iteration: 18176/59290

 31%|███       | 18171/59290 [13:26<32:01, 21.40it/s]

Iteration: 18177/59290
Iteration: 18178/59290
Iteration: 18179/59290
Iteration: 18180/59290
Iteration: 18181/59290
Iteration: 18182/59290
Iteration: 18183/59290
Iteration: 18184/59290
Iteration: 18185/59290
Iteration: 18186/59290
Iteration: 18187/59290
Iteration: 18188/59290
Iteration: 18189/59290
Iteration: 18190/59290
Iteration: 18191/59290
Iteration: 18192/59290
Iteration: 18193/59290
Iteration: 18194/59290
Iteration: 18195/59290
Iteration: 18196/59290
Iteration: 18197/59290
Iteration: 18198/59290
Iteration: 18199/59290
Iteration: 18200/59290

 31%|███       | 18195/59290 [13:26<25:42, 26.63it/s]

Iteration: 18201/59290
Iteration: 18202/59290
Iteration: 18203/59290
Iteration: 18204/59290
Iteration: 18205/59290
Iteration: 18206/59290
Iteration: 18207/59290
Iteration: 18208/59290
Iteration: 18209/59290
Iteration: 18210/59290
Iteration: 18211/59290
Iteration: 18212/59290
Iteration: 18213/59290
Iteration: 18214/59290
Iteration: 18215/59290
Iteration: 18216/59290
Iteration: 18217/59290
Iteration: 18218/59290
Iteration: 18219/59290
Iteration: 18220/59290
Iteration: 18221/59290
Iteration: 18222/59290
Iteration: 18223/59290
Iteration: 18224/59290

 31%|███       | 18219/59290 [13:27<21:13, 32.26it/s]

Iteration: 18225/59290
Iteration: 18226/59290
Iteration: 18227/59290
Iteration: 18228/59290
Iteration: 18229/59290
Iteration: 18230/59290
Iteration: 18231/59290
Iteration: 18232/59290
Iteration: 18233/59290
Iteration: 18234/59290
Iteration: 18235/59290
Iteration: 18236/59290
Iteration: 18237/59290
Iteration: 18238/59290
Iteration: 18239/59290
Iteration: 18240/59290
Iteration: 18241/59290
Iteration: 18242/59290
Iteration: 18243/59290
Iteration: 18244/59290
Iteration: 18245/59290
Iteration: 18246/59290
Iteration: 18247/59290
Iteration: 18248/59290

 31%|███       | 18243/59290 [13:27<18:05, 37.82it/s]

Iteration: 18249/59290
Iteration: 18250/59290
Iteration: 18251/59290
Iteration: 18252/59290
Iteration: 18253/59290
Iteration: 18254/59290
Iteration: 18255/59290
Iteration: 18256/59290
Iteration: 18257/59290
Iteration: 18258/59290
Iteration: 18259/59290
Iteration: 18260/59290
Iteration: 18261/59290
Iteration: 18262/59290
Iteration: 18263/59290
Iteration: 18264/59290
Iteration: 18265/59290
Iteration: 18266/59290
Iteration: 18267/59290
Iteration: 18268/59290
Iteration: 18269/59290
Iteration: 18270/59290
Iteration: 18271/59290
Iteration: 18272/59290

 31%|███       | 18267/59290 [13:27<15:56, 42.87it/s]

Iteration: 18273/59290
Iteration: 18274/59290
Iteration: 18275/59290
Iteration: 18276/59290
Iteration: 18277/59290
Iteration: 18278/59290
Iteration: 18279/59290
Iteration: 18280/59290
Iteration: 18281/59290
Iteration: 18282/59290
Iteration: 18283/59290
Iteration: 18284/59290
Iteration: 18285/59290
Iteration: 18286/59290
Iteration: 18287/59290
Iteration: 18288/59290
Iteration: 18289/59290
Iteration: 18290/59290
Iteration: 18291/59290
Iteration: 18292/59290
Iteration: 18293/59290
Iteration: 18294/59290
Iteration: 18295/59290
Iteration: 18296/59290

 31%|███       | 18291/59290 [13:28<14:31, 47.07it/s]

Iteration: 18297/59290
Iteration: 18298/59290
Iteration: 18299/59290
Iteration: 18300/59290
Iteration: 18301/59290
Iteration: 18302/59290
Iteration: 18303/59290
Iteration: 18304/59290
Iteration: 18305/59290
Iteration: 18306/59290
Iteration: 18307/59290
Iteration: 18308/59290
Iteration: 18309/59290
Iteration: 18310/59290
Iteration: 18311/59290
Iteration: 18312/59290
Iteration: 18313/59290
Iteration: 18314/59290
Iteration: 18315/59290
Iteration: 18316/59290
Iteration: 18317/59290
Iteration: 18318/59290
Iteration: 18319/59290
Iteration: 18320/59290

 31%|███       | 18315/59290 [13:28<13:21, 51.10it/s]

Iteration: 18321/59290
Iteration: 18322/59290
Iteration: 18323/59290
Iteration: 18324/59290
Iteration: 18325/59290
Iteration: 18326/59290
Iteration: 18327/59290
Iteration: 18328/59290
Iteration: 18329/59290
Iteration: 18330/59290
Iteration: 18331/59290
Iteration: 18332/59290
Iteration: 18333/59290
Iteration: 18334/59290
Iteration: 18335/59290
Iteration: 18336/59290
Iteration: 18337/59290
Iteration: 18338/59290
Iteration: 18339/59290
Iteration: 18340/59290
Iteration: 18341/59290
Iteration: 18342/59290
Iteration: 18343/59290
Iteration: 18344/59290

 31%|███       | 18339/59290 [13:29<12:36, 54.12it/s]

Iteration: 18345/59290
Iteration: 18346/59290
Iteration: 18347/59290
Iteration: 18348/59290
Iteration: 18349/59290
Iteration: 18350/59290
Iteration: 18351/59290
Iteration: 18352/59290
Iteration: 18353/59290
Iteration: 18354/59290
Iteration: 18355/59290
Iteration: 18356/59290
Iteration: 18357/59290
Iteration: 18358/59290
Iteration: 18359/59290
Iteration: 18360/59290
Iteration: 18361/59290
Iteration: 18362/59290
Iteration: 18363/59290
Iteration: 18364/59290
Iteration: 18365/59290
Iteration: 18366/59290
Iteration: 18367/59290
Iteration: 18368/59290

 31%|███       | 18363/59290 [13:29<12:03, 56.57it/s]

Iteration: 18369/59290
Iteration: 18370/59290
Iteration: 18371/59290
Iteration: 18372/59290
Iteration: 18373/59290
Iteration: 18374/59290
Iteration: 18375/59290
Iteration: 18376/59290
Iteration: 18377/59290
Iteration: 18378/59290
Iteration: 18379/59290
Iteration: 18380/59290
Iteration: 18381/59290
Iteration: 18382/59290
Iteration: 18383/59290
Iteration: 18384/59290
Iteration: 18385/59290
Iteration: 18386/59290
Iteration: 18387/59290
Iteration: 18388/59290
Iteration: 18389/59290
Iteration: 18390/59290
Iteration: 18391/59290
Iteration: 18392/59290

 31%|███       | 18387/59290 [13:31<21:55, 31.08it/s]

Iteration: 18393/59290
Iteration: 18394/59290
Iteration: 18395/59290
Iteration: 18396/59290
Iteration: 18397/59290
Iteration: 18398/59290
Iteration: 18399/59290
Iteration: 18400/59290
Iteration: 18401/59290
Iteration: 18402/59290
Iteration: 18403/59290
Iteration: 18404/59290
Iteration: 18405/59290
Iteration: 18406/59290
Iteration: 18407/59290
Iteration: 18408/59290
Iteration: 18409/59290
Iteration: 18410/59290
Iteration: 18411/59290
Iteration: 18412/59290
Iteration: 18413/59290
Iteration: 18414/59290
Iteration: 18415/59290
Iteration: 18416/59290

 31%|███       | 18411/59290 [13:33<34:55, 19.50it/s]

Iteration: 18417/59290
Iteration: 18418/59290
Iteration: 18419/59290
Iteration: 18420/59290
Iteration: 18421/59290
Iteration: 18422/59290
Iteration: 18423/59290
Iteration: 18424/59290
Iteration: 18425/59290
Iteration: 18426/59290
Iteration: 18427/59290
Iteration: 18428/59290
Iteration: 18429/59290
Iteration: 18430/59290
Iteration: 18431/59290
Iteration: 18432/59290
Iteration: 18433/59290
Iteration: 18434/59290
Iteration: 18435/59290
Iteration: 18436/59290
Iteration: 18437/59290
Iteration: 18438/59290
Iteration: 18439/59290
Iteration: 18440/59290

 31%|███       | 18435/59290 [13:33<29:22, 23.19it/s]

Iteration: 18441/59290
Iteration: 18442/59290
Iteration: 18443/59290
Iteration: 18444/59290
Iteration: 18445/59290
Iteration: 18446/59290
Iteration: 18447/59290
Iteration: 18448/59290
Iteration: 18449/59290
Iteration: 18450/59290
Iteration: 18451/59290
Iteration: 18452/59290
Iteration: 18453/59290
Iteration: 18454/59290
Iteration: 18455/59290
Iteration: 18456/59290
Iteration: 18457/59290
Iteration: 18458/59290
Iteration: 18459/59290
Iteration: 18460/59290
Iteration: 18461/59290
Iteration: 18462/59290
Iteration: 18463/59290
Iteration: 18464/59290

 31%|███       | 18459/59290 [13:34<23:56, 28.43it/s]

Iteration: 18465/59290
Iteration: 18466/59290
Iteration: 18467/59290
Iteration: 18468/59290
Iteration: 18469/59290
Iteration: 18470/59290
Iteration: 18471/59290
Iteration: 18472/59290
Iteration: 18473/59290
Iteration: 18474/59290
Iteration: 18475/59290
Iteration: 18476/59290
Iteration: 18477/59290
Iteration: 18478/59290
Iteration: 18479/59290
Iteration: 18480/59290
Iteration: 18481/59290
Iteration: 18482/59290
Iteration: 18483/59290
Iteration: 18484/59290
Iteration: 18485/59290
Iteration: 18486/59290
Iteration: 18487/59290
Iteration: 18488/59290

 31%|███       | 18483/59290 [13:34<20:08, 33.77it/s]

Iteration: 18489/59290
Iteration: 18490/59290
Iteration: 18491/59290
Iteration: 18492/59290
Iteration: 18493/59290
Iteration: 18494/59290
Iteration: 18495/59290
Iteration: 18496/59290
Iteration: 18497/59290
Iteration: 18498/59290
Iteration: 18499/59290
Iteration: 18500/59290
Iteration: 18501/59290
Iteration: 18502/59290
Iteration: 18503/59290
Iteration: 18504/59290
Iteration: 18505/59290
Iteration: 18506/59290
Iteration: 18507/59290
Iteration: 18508/59290
Iteration: 18509/59290
Iteration: 18510/59290
Iteration: 18511/59290
Iteration: 18512/59290

 31%|███       | 18507/59290 [13:35<17:21, 39.14it/s]

Iteration: 18513/59290
Iteration: 18514/59290
Iteration: 18515/59290
Iteration: 18516/59290
Iteration: 18517/59290
Iteration: 18518/59290
Iteration: 18519/59290
Iteration: 18520/59290
Iteration: 18521/59290
Iteration: 18522/59290
Iteration: 18523/59290
Iteration: 18524/59290
Iteration: 18525/59290
Iteration: 18526/59290
Iteration: 18527/59290
Iteration: 18528/59290
Iteration: 18529/59290
Iteration: 18530/59290
Iteration: 18531/59290
Iteration: 18532/59290
Iteration: 18533/59290
Iteration: 18534/59290
Iteration: 18535/59290
Iteration: 18536/59290

 31%|███▏      | 18531/59290 [13:36<26:26, 25.69it/s]

Iteration: 18537/59290
Iteration: 18538/59290
Iteration: 18539/59290
Iteration: 18540/59290
Iteration: 18541/59290
Iteration: 18542/59290
Iteration: 18543/59290
Iteration: 18544/59290
Iteration: 18545/59290
Iteration: 18546/59290
Iteration: 18547/59290
Iteration: 18548/59290
Iteration: 18549/59290
Iteration: 18550/59290
Iteration: 18551/59290
Iteration: 18552/59290
Iteration: 18553/59290
Iteration: 18554/59290
Iteration: 18555/59290
Iteration: 18556/59290
Iteration: 18557/59290
Iteration: 18558/59290
Iteration: 18559/59290
Iteration: 18560/59290

 31%|███▏      | 18555/59290 [13:38<36:43, 18.49it/s]

Iteration: 18561/59290
Iteration: 18562/59290
Iteration: 18563/59290
Iteration: 18564/59290
Iteration: 18565/59290
Iteration: 18566/59290
Iteration: 18567/59290
Iteration: 18568/59290
Iteration: 18569/59290
Iteration: 18570/59290
Iteration: 18571/59290
Iteration: 18572/59290
Iteration: 18573/59290
Iteration: 18574/59290
Iteration: 18575/59290
Iteration: 18576/59290
Iteration: 18577/59290
Iteration: 18578/59290
Iteration: 18579/59290
Iteration: 18580/59290
Iteration: 18581/59290
Iteration: 18582/59290
Iteration: 18583/59290
Iteration: 18584/59290

 31%|███▏      | 18579/59290 [13:39<31:25, 21.59it/s]

Iteration: 18585/59290
Iteration: 18586/59290
Iteration: 18587/59290
Iteration: 18588/59290
Iteration: 18589/59290
Iteration: 18590/59290
Iteration: 18591/59290
Iteration: 18592/59290
Iteration: 18593/59290
Iteration: 18594/59290
Iteration: 18595/59290
Iteration: 18596/59290
Iteration: 18597/59290
Iteration: 18598/59290
Iteration: 18599/59290
Iteration: 18600/59290
Iteration: 18601/59290
Iteration: 18602/59290
Iteration: 18603/59290
Iteration: 18604/59290
Iteration: 18605/59290
Iteration: 18606/59290
Iteration: 18607/59290
Iteration: 18608/59290

 31%|███▏      | 18603/59290 [13:40<25:24, 26.69it/s]

Iteration: 18609/59290
Iteration: 18610/59290
Iteration: 18611/59290
Iteration: 18612/59290
Iteration: 18613/59290
Iteration: 18614/59290
Iteration: 18615/59290
Iteration: 18616/59290
Iteration: 18617/59290
Iteration: 18618/59290
Iteration: 18619/59290
Iteration: 18620/59290
Iteration: 18621/59290
Iteration: 18622/59290
Iteration: 18623/59290
Iteration: 18624/59290
Iteration: 18625/59290
Iteration: 18626/59290
Iteration: 18627/59290
Iteration: 18628/59290
Iteration: 18629/59290
Iteration: 18630/59290
Iteration: 18631/59290
Iteration: 18632/59290

 31%|███▏      | 18627/59290 [13:40<21:25, 31.62it/s]

Iteration: 18633/59290
Iteration: 18634/59290
Iteration: 18635/59290
Iteration: 18636/59290
Iteration: 18637/59290
Iteration: 18638/59290
Iteration: 18639/59290
Iteration: 18640/59290
Iteration: 18641/59290
Iteration: 18642/59290
Iteration: 18643/59290
Iteration: 18644/59290
Iteration: 18645/59290
Iteration: 18646/59290
Iteration: 18647/59290
Iteration: 18648/59290
Iteration: 18649/59290
Iteration: 18650/59290
Iteration: 18651/59290
Iteration: 18652/59290
Iteration: 18653/59290
Iteration: 18654/59290
Iteration: 18655/59290
Iteration: 18656/59290

 31%|███▏      | 18651/59290 [13:40<18:18, 37.00it/s]

Iteration: 18657/59290
Iteration: 18658/59290
Iteration: 18659/59290
Iteration: 18660/59290
Iteration: 18661/59290
Iteration: 18662/59290
Iteration: 18663/59290
Iteration: 18664/59290
Iteration: 18665/59290
Iteration: 18666/59290
Iteration: 18667/59290
Iteration: 18668/59290
Iteration: 18669/59290
Iteration: 18670/59290
Iteration: 18671/59290
Iteration: 18672/59290
Iteration: 18673/59290
Iteration: 18674/59290
Iteration: 18675/59290
Iteration: 18676/59290
Iteration: 18677/59290
Iteration: 18678/59290
Iteration: 18679/59290
Iteration: 18680/59290

 31%|███▏      | 18675/59290 [13:41<16:22, 41.32it/s]

Iteration: 18681/59290
Iteration: 18682/59290
Iteration: 18683/59290
Iteration: 18684/59290
Iteration: 18685/59290
Iteration: 18686/59290
Iteration: 18687/59290
Iteration: 18688/59290
Iteration: 18689/59290
Iteration: 18690/59290
Iteration: 18691/59290
Iteration: 18692/59290
Iteration: 18693/59290
Iteration: 18694/59290
Iteration: 18695/59290
Iteration: 18696/59290
Iteration: 18697/59290
Iteration: 18698/59290
Iteration: 18699/59290
Iteration: 18700/59290
Iteration: 18701/59290
Iteration: 18702/59290
Iteration: 18703/59290
Iteration: 18704/59290

 32%|███▏      | 18699/59290 [13:41<14:38, 46.19it/s]

Iteration: 18705/59290
Iteration: 18706/59290
Iteration: 18707/59290
Iteration: 18708/59290
Iteration: 18709/59290
Iteration: 18710/59290
Iteration: 18711/59290
Iteration: 18712/59290
Iteration: 18713/59290
Iteration: 18714/59290
Iteration: 18715/59290
Iteration: 18716/59290
Iteration: 18717/59290
Iteration: 18718/59290
Iteration: 18719/59290
Iteration: 18720/59290
Iteration: 18721/59290
Iteration: 18722/59290
Iteration: 18723/59290
Iteration: 18724/59290
Iteration: 18725/59290
Iteration: 18726/59290
Iteration: 18727/59290
Iteration: 18728/59290

 32%|███▏      | 18723/59290 [13:42<13:25, 50.39it/s]

Iteration: 18729/59290
Iteration: 18730/59290
Iteration: 18731/59290
Iteration: 18732/59290
Iteration: 18733/59290
Iteration: 18734/59290
Iteration: 18735/59290
Iteration: 18736/59290
Iteration: 18737/59290
Iteration: 18738/59290
Iteration: 18739/59290
Iteration: 18740/59290
Iteration: 18741/59290
Iteration: 18742/59290
Iteration: 18743/59290
Iteration: 18744/59290
Iteration: 18745/59290
Iteration: 18746/59290
Iteration: 18747/59290
Iteration: 18748/59290
Iteration: 18749/59290
Iteration: 18750/59290
Iteration: 18751/59290
Iteration: 18752/59290

 32%|███▏      | 18747/59290 [13:42<12:35, 53.67it/s]

Iteration: 18753/59290
Iteration: 18754/59290
Iteration: 18755/59290
Iteration: 18756/59290
Iteration: 18757/59290
Iteration: 18758/59290
Iteration: 18759/59290
Iteration: 18760/59290
Iteration: 18761/59290
Iteration: 18762/59290
Iteration: 18763/59290
Iteration: 18764/59290
Iteration: 18765/59290
Iteration: 18766/59290
Iteration: 18767/59290
Iteration: 18768/59290
Iteration: 18769/59290
Iteration: 18770/59290
Iteration: 18771/59290
Iteration: 18772/59290
Iteration: 18773/59290
Iteration: 18774/59290
Iteration: 18775/59290
Iteration: 18776/59290

 32%|███▏      | 18771/59290 [13:42<12:00, 56.25it/s]

Iteration: 18777/59290
Iteration: 18778/59290
Iteration: 18779/59290
Iteration: 18780/59290
Iteration: 18781/59290
Iteration: 18782/59290
Iteration: 18783/59290
Iteration: 18784/59290
Iteration: 18785/59290
Iteration: 18786/59290
Iteration: 18787/59290
Iteration: 18788/59290
Iteration: 18789/59290
Iteration: 18790/59290
Iteration: 18791/59290
Iteration: 18792/59290
Iteration: 18793/59290
Iteration: 18794/59290
Iteration: 18795/59290
Iteration: 18796/59290
Iteration: 18797/59290
Iteration: 18798/59290
Iteration: 18799/59290
Iteration: 18800/59290

 32%|███▏      | 18795/59290 [13:43<11:36, 58.12it/s]

Iteration: 18801/59290
Iteration: 18802/59290
Iteration: 18803/59290
Iteration: 18804/59290
Iteration: 18805/59290
Iteration: 18806/59290
Iteration: 18807/59290
Iteration: 18808/59290
Iteration: 18809/59290
Iteration: 18810/59290
Iteration: 18811/59290
Iteration: 18812/59290
Iteration: 18813/59290
Iteration: 18814/59290
Iteration: 18815/59290
Iteration: 18816/59290
Iteration: 18817/59290
Iteration: 18818/59290
Iteration: 18819/59290
Iteration: 18820/59290
Iteration: 18821/59290
Iteration: 18822/59290
Iteration: 18823/59290
Iteration: 18824/59290

 32%|███▏      | 18819/59290 [13:43<11:19, 59.58it/s]

Iteration: 18825/59290
Iteration: 18826/59290
Iteration: 18827/59290
Iteration: 18828/59290
Iteration: 18829/59290
Iteration: 18830/59290
Iteration: 18831/59290
Iteration: 18832/59290
Iteration: 18833/59290
Iteration: 18834/59290
Iteration: 18835/59290
Iteration: 18836/59290
Iteration: 18837/59290
Iteration: 18838/59290
Iteration: 18839/59290
Iteration: 18840/59290
Iteration: 18841/59290
Iteration: 18842/59290
Iteration: 18843/59290
Iteration: 18844/59290
Iteration: 18845/59290
Iteration: 18846/59290
Iteration: 18847/59290
Iteration: 18848/59290

 32%|███▏      | 18843/59290 [13:43<11:15, 59.86it/s]

Iteration: 18849/59290
Iteration: 18850/59290
Iteration: 18851/59290
Iteration: 18852/59290
Iteration: 18853/59290
Iteration: 18854/59290
Iteration: 18855/59290
Iteration: 18856/59290
Iteration: 18857/59290
Iteration: 18858/59290
Iteration: 18859/59290
Iteration: 18860/59290
Iteration: 18861/59290
Iteration: 18862/59290
Iteration: 18863/59290
Iteration: 18864/59290
Iteration: 18865/59290
Iteration: 18866/59290
Iteration: 18867/59290
Iteration: 18868/59290
Iteration: 18869/59290
Iteration: 18870/59290
Iteration: 18872/59290

 32%|███▏      | 18866/59290 [13:44<11:33, 58.28it/s]

Iteration: 18873/59290
Iteration: 18874/59290
Iteration: 18875/59290
Iteration: 18876/59290
Iteration: 18877/59290
Iteration: 18878/59290
Iteration: 18879/59290
Iteration: 18880/59290

 32%|███▏      | 18874/59290 [13:46<29:09, 23.10it/s]

Iteration: 18881/59290
Iteration: 18882/59290
Iteration: 18883/59290
Iteration: 18884/59290
Iteration: 18885/59290
Iteration: 18886/59290
Iteration: 18887/59290
Iteration: 18888/59290
Iteration: 18889/59290
Iteration: 18890/59290
Iteration: 18891/59290
Iteration: 18892/59290
Iteration: 18893/59290
Iteration: 18894/59290
Iteration: 18895/59290
Iteration: 18896/59290
Iteration: 18897/59290
Iteration: 18898/59290
Iteration: 18899/59290
Iteration: 18900/59290
Iteration: 18901/59290
Iteration: 18902/59290
Iteration: 18903/59290
Iteration: 18904/59290

 32%|███▏      | 18898/59290 [13:48<39:48, 16.91it/s]

Iteration: 18905/59290
Iteration: 18906/59290
Iteration: 18907/59290
Iteration: 18908/59290
Iteration: 18909/59290
Iteration: 18910/59290
Iteration: 18911/59290
Iteration: 18912/59290
Iteration: 18913/59290
Iteration: 18914/59290
Iteration: 18915/59290
Iteration: 18916/59290
Iteration: 18917/59290
Iteration: 18918/59290
Iteration: 18919/59290
Iteration: 18920/59290
Iteration: 18921/59290
Iteration: 18922/59290
Iteration: 18923/59290
Iteration: 18924/59290
Iteration: 18925/59290
Iteration: 18926/59290
Iteration: 18927/59290
Iteration: 18928/59290

 32%|███▏      | 18922/59290 [13:48<30:08, 22.32it/s]

Iteration: 18929/59290
Iteration: 18930/59290
Iteration: 18931/59290
Iteration: 18932/59290
Iteration: 18933/59290
Iteration: 18934/59290
Iteration: 18935/59290
Iteration: 18936/59290
Iteration: 18937/59290
Iteration: 18938/59290
Iteration: 18939/59290
Iteration: 18940/59290
Iteration: 18941/59290
Iteration: 18942/59290
Iteration: 18943/59290
Iteration: 18944/59290
Iteration: 18945/59290
Iteration: 18946/59290
Iteration: 18947/59290
Iteration: 18948/59290
Iteration: 18949/59290
Iteration: 18950/59290
Iteration: 18951/59290
Iteration: 18952/59290

 32%|███▏      | 18946/59290 [13:49<23:47, 28.26it/s]

Iteration: 18953/59290
Iteration: 18954/59290
Iteration: 18955/59290
Iteration: 18956/59290
Iteration: 18957/59290
Iteration: 18958/59290
Iteration: 18959/59290
Iteration: 18960/59290
Iteration: 18961/59290
Iteration: 18962/59290
Iteration: 18963/59290
Iteration: 18964/59290
Iteration: 18965/59290
Iteration: 18966/59290
Iteration: 18967/59290
Iteration: 18968/59290
Iteration: 18969/59290
Iteration: 18970/59290
Iteration: 18971/59290
Iteration: 18972/59290
Iteration: 18973/59290
Iteration: 18974/59290
Iteration: 18975/59290
Iteration: 18976/59290

 32%|███▏      | 18970/59290 [13:49<22:03, 30.46it/s]

Iteration: 18977/59290
Iteration: 18978/59290
Iteration: 18979/59290
Iteration: 18980/59290
Iteration: 18981/59290
Iteration: 18982/59290
Iteration: 18983/59290
Iteration: 18984/59290
Iteration: 18985/59290
Iteration: 18986/59290
Iteration: 18987/59290
Iteration: 18988/59290
Iteration: 18989/59290
Iteration: 18990/59290
Iteration: 18991/59290
Iteration: 18992/59290
Iteration: 18993/59290
Iteration: 18994/59290
Iteration: 18995/59290
Iteration: 18996/59290
Iteration: 18997/59290
Iteration: 18998/59290
Iteration: 18999/59290
Iteration: 19000/59290

 32%|███▏      | 18994/59290 [13:50<18:38, 36.01it/s]

Iteration: 19001/59290
Iteration: 19002/59290
Iteration: 19003/59290
Iteration: 19004/59290
Iteration: 19005/59290
Iteration: 19006/59290
Iteration: 19007/59290
Iteration: 19008/59290
Iteration: 19009/59290
Iteration: 19010/59290
Iteration: 19011/59290
Iteration: 19012/59290
Iteration: 19013/59290
Iteration: 19014/59290
Iteration: 19015/59290
Iteration: 19016/59290
Iteration: 19017/59290
Iteration: 19018/59290
Iteration: 19019/59290
Iteration: 19020/59290
Iteration: 19021/59290
Iteration: 19022/59290
Iteration: 19023/59290
Iteration: 19024/59290

 32%|███▏      | 19018/59290 [13:50<16:13, 41.38it/s]

Iteration: 19025/59290
Iteration: 19026/59290
Iteration: 19027/59290
Iteration: 19028/59290
Iteration: 19029/59290
Iteration: 19030/59290
Iteration: 19031/59290
Iteration: 19032/59290
Iteration: 19033/59290
Iteration: 19034/59290
Iteration: 19035/59290
Iteration: 19036/59290
Iteration: 19037/59290
Iteration: 19038/59290
Iteration: 19039/59290
Iteration: 19040/59290
Iteration: 19041/59290
Iteration: 19042/59290
Iteration: 19043/59290
Iteration: 19044/59290
Iteration: 19045/59290
Iteration: 19046/59290
Iteration: 19047/59290
Iteration: 19048/59290

 32%|███▏      | 19042/59290 [13:50<14:46, 45.39it/s]

Iteration: 19049/59290
Iteration: 19050/59290
Iteration: 19051/59290
Iteration: 19052/59290
Iteration: 19053/59290
Iteration: 19054/59290
Iteration: 19055/59290
Iteration: 19056/59290
Iteration: 19057/59290
Iteration: 19058/59290
Iteration: 19059/59290
Iteration: 19060/59290
Iteration: 19061/59290
Iteration: 19062/59290
Iteration: 19063/59290
Iteration: 19064/59290
Iteration: 19065/59290
Iteration: 19066/59290
Iteration: 19067/59290
Iteration: 19068/59290
Iteration: 19069/59290
Iteration: 19070/59290
Iteration: 19071/59290
Iteration: 19072/59290

 32%|███▏      | 19066/59290 [13:51<13:34, 49.37it/s]

Iteration: 19073/59290
Iteration: 19074/59290
Iteration: 19075/59290
Iteration: 19076/59290
Iteration: 19077/59290
Iteration: 19078/59290
Iteration: 19079/59290
Iteration: 19080/59290
Iteration: 19081/59290
Iteration: 19082/59290
Iteration: 19083/59290
Iteration: 19084/59290
Iteration: 19085/59290
Iteration: 19086/59290
Iteration: 19087/59290
Iteration: 19088/59290
Iteration: 19089/59290
Iteration: 19090/59290
Iteration: 19091/59290
Iteration: 19092/59290
Iteration: 19093/59290
Iteration: 19094/59290
Iteration: 19095/59290
Iteration: 19096/59290

 32%|███▏      | 19090/59290 [13:51<12:42, 52.73it/s]

Iteration: 19097/59290
Iteration: 19098/59290
Iteration: 19099/59290
Iteration: 19100/59290
Iteration: 19101/59290
Iteration: 19102/59290
Iteration: 19103/59290
Iteration: 19104/59290
Iteration: 19105/59290
Iteration: 19106/59290
Iteration: 19107/59290
Iteration: 19108/59290
Iteration: 19109/59290
Iteration: 19110/59290
Iteration: 19111/59290
Iteration: 19112/59290
Iteration: 19113/59290
Iteration: 19114/59290
Iteration: 19115/59290
Iteration: 19116/59290
Iteration: 19117/59290
Iteration: 19118/59290
Iteration: 19119/59290
Iteration: 19120/59290

 32%|███▏      | 19114/59290 [13:53<20:39, 32.41it/s]

Iteration: 19121/59290
Iteration: 19122/59290
Iteration: 19123/59290
Iteration: 19124/59290
Iteration: 19125/59290
Iteration: 19126/59290
Iteration: 19127/59290
Iteration: 19128/59290
Iteration: 19129/59290
Iteration: 19130/59290
Iteration: 19131/59290
Iteration: 19132/59290
Iteration: 19133/59290
Iteration: 19134/59290
Iteration: 19135/59290
Iteration: 19136/59290
Iteration: 19137/59290
Iteration: 19138/59290
Iteration: 19139/59290
Iteration: 19140/59290
Iteration: 19141/59290
Iteration: 19142/59290
Iteration: 19143/59290
Iteration: 19144/59290

 32%|███▏      | 19138/59290 [13:55<32:18, 20.72it/s]

Iteration: 19145/59290
Iteration: 19146/59290
Iteration: 19147/59290
Iteration: 19148/59290
Iteration: 19149/59290
Iteration: 19150/59290
Iteration: 19151/59290
Iteration: 19152/59290
Iteration: 19153/59290
Iteration: 19154/59290
Iteration: 19155/59290
Iteration: 19156/59290
Iteration: 19157/59290
Iteration: 19158/59290
Iteration: 19159/59290
Iteration: 19160/59290
Iteration: 19161/59290
Iteration: 19162/59290
Iteration: 19163/59290
Iteration: 19164/59290
Iteration: 19165/59290
Iteration: 19166/59290
Iteration: 19167/59290
Iteration: 19168/59290

 32%|███▏      | 19162/59290 [13:55<25:46, 25.95it/s]

Iteration: 19169/59290
Iteration: 19170/59290
Iteration: 19171/59290
Iteration: 19172/59290
Iteration: 19173/59290
Iteration: 19174/59290
Iteration: 19175/59290
Iteration: 19176/59290
Iteration: 19177/59290
Iteration: 19178/59290
Iteration: 19179/59290
Iteration: 19180/59290
Iteration: 19181/59290
Iteration: 19182/59290
Iteration: 19183/59290
Iteration: 19184/59290
Iteration: 19185/59290
Iteration: 19186/59290
Iteration: 19187/59290
Iteration: 19188/59290
Iteration: 19189/59290
Iteration: 19190/59290
Iteration: 19191/59290
Iteration: 19192/59290

 32%|███▏      | 19186/59290 [13:56<23:23, 28.57it/s]

Iteration: 19193/59290
Iteration: 19194/59290
Iteration: 19195/59290
Iteration: 19196/59290
Iteration: 19197/59290
Iteration: 19198/59290
Iteration: 19199/59290
Iteration: 19200/59290
Iteration: 19201/59290
Iteration: 19202/59290
Iteration: 19203/59290
Iteration: 19204/59290
Iteration: 19205/59290
Iteration: 19206/59290
Iteration: 19207/59290
Iteration: 19208/59290
Iteration: 19209/59290
Iteration: 19210/59290
Iteration: 19211/59290
Iteration: 19212/59290
Iteration: 19213/59290
Iteration: 19214/59290
Iteration: 19215/59290
Iteration: 19216/59290

 32%|███▏      | 19210/59290 [13:56<19:36, 34.06it/s]

Iteration: 19217/59290
Iteration: 19218/59290
Iteration: 19219/59290
Iteration: 19220/59290
Iteration: 19221/59290
Iteration: 19222/59290
Iteration: 19223/59290
Iteration: 19224/59290
Iteration: 19225/59290
Iteration: 19226/59290
Iteration: 19227/59290
Iteration: 19228/59290
Iteration: 19229/59290
Iteration: 19230/59290
Iteration: 19231/59290
Iteration: 19232/59290
Iteration: 19233/59290
Iteration: 19234/59290
Iteration: 19235/59290
Iteration: 19236/59290
Iteration: 19237/59290
Iteration: 19238/59290
Iteration: 19239/59290
Iteration: 19240/59290

 32%|███▏      | 19234/59290 [13:57<17:05, 39.08it/s]

Iteration: 19241/59290
Iteration: 19242/59290
Iteration: 19243/59290
Iteration: 19244/59290
Iteration: 19245/59290
Iteration: 19246/59290
Iteration: 19247/59290
Iteration: 19248/59290
Iteration: 19249/59290
Iteration: 19250/59290
Iteration: 19251/59290
Iteration: 19252/59290
Iteration: 19253/59290
Iteration: 19254/59290
Iteration: 19255/59290
Iteration: 19256/59290
Iteration: 19257/59290
Iteration: 19258/59290
Iteration: 19259/59290
Iteration: 19260/59290
Iteration: 19261/59290
Iteration: 19262/59290
Iteration: 19263/59290
Iteration: 19264/59290

 32%|███▏      | 19258/59290 [13:57<15:14, 43.78it/s]

Iteration: 19265/59290
Iteration: 19266/59290
Iteration: 19267/59290
Iteration: 19268/59290
Iteration: 19269/59290
Iteration: 19270/59290
Iteration: 19271/59290
Iteration: 19272/59290
Iteration: 19273/59290
Iteration: 19274/59290
Iteration: 19275/59290
Iteration: 19276/59290
Iteration: 19277/59290
Iteration: 19278/59290
Iteration: 19279/59290
Iteration: 19280/59290
Iteration: 19281/59290
Iteration: 19282/59290
Iteration: 19283/59290
Iteration: 19284/59290
Iteration: 19285/59290
Iteration: 19286/59290
Iteration: 19287/59290
Iteration: 19288/59290

 33%|███▎      | 19282/59290 [13:57<13:46, 48.39it/s]

Iteration: 19289/59290
Iteration: 19290/59290
Iteration: 19291/59290
Iteration: 19292/59290
Iteration: 19293/59290
Iteration: 19294/59290
Iteration: 19295/59290
Iteration: 19296/59290
Iteration: 19297/59290
Iteration: 19298/59290
Iteration: 19299/59290
Iteration: 19300/59290
Iteration: 19301/59290
Iteration: 19302/59290
Iteration: 19303/59290
Iteration: 19304/59290
Iteration: 19305/59290
Iteration: 19306/59290
Iteration: 19307/59290
Iteration: 19308/59290
Iteration: 19309/59290
Iteration: 19310/59290
Iteration: 19311/59290
Iteration: 19312/59290

 33%|███▎      | 19306/59290 [13:58<12:51, 51.82it/s]

Iteration: 19313/59290
Iteration: 19314/59290
Iteration: 19315/59290
Iteration: 19316/59290
Iteration: 19317/59290
Iteration: 19318/59290
Iteration: 19319/59290
Iteration: 19320/59290
Iteration: 19321/59290
Iteration: 19322/59290
Iteration: 19323/59290
Iteration: 19324/59290
Iteration: 19325/59290
Iteration: 19326/59290
Iteration: 19327/59290
Iteration: 19328/59290
Iteration: 19329/59290
Iteration: 19330/59290
Iteration: 19331/59290
Iteration: 19332/59290
Iteration: 19333/59290
Iteration: 19334/59290
Iteration: 19335/59290
Iteration: 19336/59290

 33%|███▎      | 19330/59290 [13:58<12:10, 54.70it/s]

Iteration: 19337/59290
Iteration: 19338/59290
Iteration: 19339/59290
Iteration: 19340/59290
Iteration: 19341/59290
Iteration: 19342/59290
Iteration: 19343/59290
Iteration: 19344/59290
Iteration: 19345/59290
Iteration: 19346/59290
Iteration: 19347/59290
Iteration: 19348/59290
Iteration: 19349/59290
Iteration: 19350/59290
Iteration: 19351/59290
Iteration: 19352/59290
Iteration: 19353/59290
Iteration: 19354/59290
Iteration: 19355/59290
Iteration: 19356/59290
Iteration: 19357/59290
Iteration: 19358/59290
Iteration: 19359/59290
Iteration: 19360/59290

 33%|███▎      | 19354/59290 [13:58<11:37, 57.24it/s]

Iteration: 19361/59290
Iteration: 19362/59290
Iteration: 19363/59290
Iteration: 19364/59290
Iteration: 19365/59290
Iteration: 19366/59290
Iteration: 19367/59290
Iteration: 19368/59290
Iteration: 19369/59290
Iteration: 19370/59290
Iteration: 19371/59290
Iteration: 19372/59290
Iteration: 19373/59290
Iteration: 19374/59290
Iteration: 19375/59290
Iteration: 19376/59290
Iteration: 19377/59290
Iteration: 19378/59290
Iteration: 19379/59290
Iteration: 19380/59290
Iteration: 19381/59290
Iteration: 19382/59290
Iteration: 19383/59290
Iteration: 19384/59290

 33%|███▎      | 19378/59290 [13:59<11:20, 58.62it/s]

Iteration: 19385/59290
Iteration: 19386/59290
Iteration: 19387/59290
Iteration: 19388/59290
Iteration: 19389/59290
Iteration: 19390/59290
Iteration: 19391/59290
Iteration: 19392/59290
Iteration: 19393/59290
Iteration: 19394/59290
Iteration: 19395/59290
Iteration: 19396/59290
Iteration: 19397/59290
Iteration: 19398/59290
Iteration: 19399/59290
Iteration: 19400/59290
Iteration: 19401/59290
Iteration: 19402/59290
Iteration: 19403/59290
Iteration: 19404/59290
Iteration: 19405/59290
Iteration: 19406/59290
Iteration: 19407/59290
Iteration: 19408/59290

 33%|███▎      | 19402/59290 [13:59<11:24, 58.27it/s]

Iteration: 19409/59290
Iteration: 19410/59290
Iteration: 19411/59290
Iteration: 19412/59290
Iteration: 19413/59290
Iteration: 19414/59290
Iteration: 19415/59290
Iteration: 19416/59290
Iteration: 19417/59290
Iteration: 19418/59290
Iteration: 19419/59290
Iteration: 19420/59290
Iteration: 19421/59290
Iteration: 19422/59290
Iteration: 19423/59290
Iteration: 19424/59290
Iteration: 19425/59290
Iteration: 19426/59290
Iteration: 19427/59290
Iteration: 19428/59290
Iteration: 19429/59290
Iteration: 19430/59290
Iteration: 19431/59290
Iteration: 19432/59290

 33%|███▎      | 19426/59290 [14:01<20:07, 33.02it/s]

Iteration: 19433/59290
Iteration: 19434/59290
Iteration: 19435/59290
Iteration: 19436/59290
Iteration: 19437/59290
Iteration: 19438/59290
Iteration: 19439/59290
Iteration: 19440/59290
Iteration: 19441/59290
Iteration: 19442/59290
Iteration: 19443/59290
Iteration: 19444/59290
Iteration: 19445/59290
Iteration: 19446/59290
Iteration: 19447/59290
Iteration: 19448/59290
Iteration: 19449/59290
Iteration: 19450/59290
Iteration: 19451/59290
Iteration: 19452/59290
Iteration: 19453/59290
Iteration: 19454/59290
Iteration: 19455/59290
Iteration: 19456/59290

 33%|███▎      | 19450/59290 [14:03<31:58, 20.76it/s]

Iteration: 19457/59290
Iteration: 19458/59290
Iteration: 19459/59290
Iteration: 19460/59290
Iteration: 19461/59290
Iteration: 19462/59290
Iteration: 19463/59290
Iteration: 19464/59290
Iteration: 19465/59290
Iteration: 19466/59290
Iteration: 19467/59290
Iteration: 19468/59290
Iteration: 19469/59290
Iteration: 19470/59290
Iteration: 19471/59290
Iteration: 19472/59290
Iteration: 19473/59290
Iteration: 19474/59290
Iteration: 19475/59290
Iteration: 19476/59290
Iteration: 19477/59290
Iteration: 19478/59290
Iteration: 19479/59290
Iteration: 19480/59290

 33%|███▎      | 19474/59290 [14:04<27:40, 23.97it/s]

Iteration: 19481/59290
Iteration: 19482/59290
Iteration: 19483/59290
Iteration: 19484/59290
Iteration: 19485/59290
Iteration: 19486/59290
Iteration: 19487/59290
Iteration: 19488/59290
Iteration: 19489/59290
Iteration: 19490/59290
Iteration: 19491/59290
Iteration: 19492/59290
Iteration: 19493/59290
Iteration: 19494/59290
Iteration: 19495/59290
Iteration: 19496/59290
Iteration: 19497/59290
Iteration: 19498/59290
Iteration: 19499/59290
Iteration: 19500/59290
Iteration: 19501/59290
Iteration: 19502/59290
Iteration: 19503/59290
Iteration: 19504/59290

 33%|███▎      | 19498/59290 [14:04<22:31, 29.45it/s]

Iteration: 19505/59290
Iteration: 19506/59290
Iteration: 19507/59290
Iteration: 19508/59290
Iteration: 19509/59290
Iteration: 19510/59290
Iteration: 19511/59290
Iteration: 19512/59290
Iteration: 19513/59290
Iteration: 19514/59290
Iteration: 19515/59290
Iteration: 19516/59290
Iteration: 19517/59290
Iteration: 19518/59290
Iteration: 19519/59290
Iteration: 19520/59290
Iteration: 19521/59290
Iteration: 19522/59290
Iteration: 19523/59290
Iteration: 19524/59290
Iteration: 19525/59290
Iteration: 19526/59290
Iteration: 19527/59290
Iteration: 19528/59290

 33%|███▎      | 19522/59290 [14:04<18:53, 35.08it/s]

Iteration: 19529/59290
Iteration: 19530/59290
Iteration: 19531/59290
Iteration: 19532/59290
Iteration: 19533/59290
Iteration: 19534/59290
Iteration: 19535/59290
Iteration: 19536/59290
Iteration: 19537/59290
Iteration: 19538/59290
Iteration: 19539/59290
Iteration: 19540/59290
Iteration: 19541/59290
Iteration: 19542/59290
Iteration: 19543/59290
Iteration: 19544/59290
Iteration: 19545/59290
Iteration: 19546/59290
Iteration: 19547/59290
Iteration: 19548/59290
Iteration: 19549/59290
Iteration: 19550/59290
Iteration: 19551/59290
Iteration: 19552/59290

 33%|███▎      | 19546/59290 [14:05<16:33, 39.99it/s]

Iteration: 19553/59290
Iteration: 19554/59290
Iteration: 19555/59290
Iteration: 19556/59290
Iteration: 19557/59290
Iteration: 19558/59290
Iteration: 19559/59290
Iteration: 19560/59290
Iteration: 19561/59290
Iteration: 19562/59290
Iteration: 19563/59290
Iteration: 19564/59290
Iteration: 19565/59290
Iteration: 19566/59290
Iteration: 19567/59290
Iteration: 19568/59290
Iteration: 19569/59290
Iteration: 19570/59290
Iteration: 19571/59290
Iteration: 19572/59290
Iteration: 19573/59290
Iteration: 19574/59290
Iteration: 19575/59290
Iteration: 19576/59290

 33%|███▎      | 19570/59290 [14:06<24:26, 27.08it/s]

Iteration: 19577/59290
Iteration: 19578/59290
Iteration: 19579/59290
Iteration: 19580/59290
Iteration: 19581/59290
Iteration: 19582/59290
Iteration: 19583/59290
Iteration: 19584/59290
Iteration: 19585/59290
Iteration: 19586/59290
Iteration: 19587/59290
Iteration: 19588/59290
Iteration: 19589/59290
Iteration: 19590/59290
Iteration: 19591/59290
Iteration: 19592/59290
Iteration: 19593/59290
Iteration: 19594/59290
Iteration: 19595/59290
Iteration: 19596/59290
Iteration: 19597/59290
Iteration: 19598/59290
Iteration: 19599/59290
Iteration: 19600/59290

 33%|███▎      | 19594/59290 [14:08<35:20, 18.72it/s]

Iteration: 19601/59290
Iteration: 19602/59290
Iteration: 19603/59290
Iteration: 19604/59290
Iteration: 19605/59290
Iteration: 19606/59290
Iteration: 19607/59290
Iteration: 19608/59290
Iteration: 19609/59290
Iteration: 19610/59290
Iteration: 19611/59290
Iteration: 19612/59290
Iteration: 19613/59290
Iteration: 19614/59290
Iteration: 19615/59290
Iteration: 19616/59290
Iteration: 19617/59290
Iteration: 19618/59290
Iteration: 19619/59290
Iteration: 19620/59290
Iteration: 19621/59290
Iteration: 19622/59290
Iteration: 19623/59290
Iteration: 19624/59290

 33%|███▎      | 19618/59290 [14:09<31:27, 21.02it/s]

Iteration: 19625/59290
Iteration: 19626/59290
Iteration: 19627/59290
Iteration: 19628/59290
Iteration: 19629/59290
Iteration: 19630/59290
Iteration: 19631/59290
Iteration: 19632/59290
Iteration: 19633/59290
Iteration: 19634/59290
Iteration: 19635/59290
Iteration: 19636/59290
Iteration: 19637/59290
Iteration: 19638/59290
Iteration: 19639/59290
Iteration: 19640/59290
Iteration: 19641/59290
Iteration: 19642/59290
Iteration: 19643/59290
Iteration: 19644/59290
Iteration: 19645/59290
Iteration: 19646/59290
Iteration: 19647/59290
Iteration: 19648/59290

 33%|███▎      | 19642/59290 [14:10<25:07, 26.30it/s]

Iteration: 19649/59290
Iteration: 19650/59290
Iteration: 19651/59290
Iteration: 19652/59290
Iteration: 19653/59290
Iteration: 19654/59290
Iteration: 19655/59290
Iteration: 19656/59290
Iteration: 19657/59290
Iteration: 19658/59290
Iteration: 19659/59290
Iteration: 19660/59290
Iteration: 19661/59290
Iteration: 19662/59290
Iteration: 19663/59290
Iteration: 19664/59290
Iteration: 19665/59290
Iteration: 19666/59290
Iteration: 19667/59290
Iteration: 19668/59290
Iteration: 19669/59290
Iteration: 19670/59290
Iteration: 19671/59290
Iteration: 19672/59290

 33%|███▎      | 19666/59290 [14:10<20:42, 31.89it/s]

Iteration: 19673/59290
Iteration: 19674/59290
Iteration: 19675/59290
Iteration: 19676/59290
Iteration: 19677/59290
Iteration: 19678/59290
Iteration: 19679/59290
Iteration: 19680/59290
Iteration: 19681/59290
Iteration: 19682/59290
Iteration: 19683/59290
Iteration: 19684/59290
Iteration: 19685/59290
Iteration: 19686/59290
Iteration: 19687/59290
Iteration: 19688/59290
Iteration: 19689/59290
Iteration: 19690/59290
Iteration: 19691/59290
Iteration: 19692/59290
Iteration: 19693/59290
Iteration: 19694/59290
Iteration: 19695/59290
Iteration: 19696/59290

 33%|███▎      | 19690/59290 [14:10<17:32, 37.62it/s]

Iteration: 19697/59290
Iteration: 19698/59290
Iteration: 19699/59290
Iteration: 19700/59290
Iteration: 19701/59290
Iteration: 19702/59290
Iteration: 19703/59290
Iteration: 19704/59290
Iteration: 19705/59290
Iteration: 19706/59290
Iteration: 19707/59290
Iteration: 19708/59290
Iteration: 19709/59290
Iteration: 19710/59290
Iteration: 19711/59290
Iteration: 19712/59290
Iteration: 19713/59290
Iteration: 19714/59290
Iteration: 19715/59290
Iteration: 19716/59290
Iteration: 19717/59290
Iteration: 19718/59290
Iteration: 19719/59290
Iteration: 19720/59290

 33%|███▎      | 19714/59290 [14:11<15:22, 42.89it/s]

Iteration: 19721/59290
Iteration: 19722/59290
Iteration: 19723/59290
Iteration: 19724/59290
Iteration: 19725/59290
Iteration: 19726/59290
Iteration: 19727/59290
Iteration: 19728/59290
Iteration: 19729/59290
Iteration: 19730/59290
Iteration: 19731/59290
Iteration: 19732/59290
Iteration: 19733/59290
Iteration: 19734/59290
Iteration: 19735/59290
Iteration: 19736/59290
Iteration: 19737/59290
Iteration: 19738/59290
Iteration: 19739/59290
Iteration: 19740/59290
Iteration: 19741/59290
Iteration: 19742/59290
Iteration: 19743/59290
Iteration: 19744/59290

 33%|███▎      | 19738/59290 [14:11<13:50, 47.62it/s]

Iteration: 19745/59290
Iteration: 19746/59290
Iteration: 19747/59290
Iteration: 19748/59290
Iteration: 19749/59290
Iteration: 19750/59290
Iteration: 19751/59290
Iteration: 19752/59290
Iteration: 19753/59290
Iteration: 19754/59290
Iteration: 19755/59290
Iteration: 19756/59290
Iteration: 19757/59290
Iteration: 19758/59290
Iteration: 19759/59290
Iteration: 19760/59290
Iteration: 19761/59290
Iteration: 19762/59290
Iteration: 19763/59290
Iteration: 19764/59290
Iteration: 19765/59290
Iteration: 19766/59290
Iteration: 19767/59290
Iteration: 19768/59290

 33%|███▎      | 19762/59290 [14:12<12:53, 51.11it/s]

Iteration: 19769/59290
Iteration: 19770/59290
Iteration: 19771/59290
Iteration: 19772/59290
Iteration: 19773/59290
Iteration: 19774/59290
Iteration: 19775/59290
Iteration: 19776/59290
Iteration: 19777/59290
Iteration: 19778/59290
Iteration: 19779/59290
Iteration: 19780/59290
Iteration: 19781/59290
Iteration: 19782/59290
Iteration: 19783/59290
Iteration: 19784/59290
Iteration: 19785/59290
Iteration: 19786/59290
Iteration: 19787/59290
Iteration: 19788/59290
Iteration: 19789/59290
Iteration: 19790/59290
Iteration: 19791/59290
Iteration: 19792/59290

 33%|███▎      | 19786/59290 [14:12<12:11, 53.99it/s]

Iteration: 19793/59290
Iteration: 19794/59290
Iteration: 19795/59290
Iteration: 19796/59290
Iteration: 19797/59290
Iteration: 19798/59290
Iteration: 19799/59290
Iteration: 19800/59290
Iteration: 19801/59290
Iteration: 19802/59290
Iteration: 19803/59290
Iteration: 19804/59290
Iteration: 19805/59290
Iteration: 19806/59290
Iteration: 19807/59290
Iteration: 19808/59290
Iteration: 19809/59290
Iteration: 19810/59290
Iteration: 19811/59290
Iteration: 19812/59290
Iteration: 19813/59290
Iteration: 19814/59290
Iteration: 19815/59290
Iteration: 19816/59290

 33%|███▎      | 19810/59290 [14:12<11:50, 55.54it/s]

Iteration: 19817/59290
Iteration: 19818/59290
Iteration: 19819/59290
Iteration: 19820/59290
Iteration: 19821/59290
Iteration: 19822/59290
Iteration: 19823/59290
Iteration: 19824/59290
Iteration: 19825/59290
Iteration: 19826/59290
Iteration: 19827/59290
Iteration: 19828/59290
Iteration: 19829/59290
Iteration: 19830/59290
Iteration: 19831/59290
Iteration: 19832/59290
Iteration: 19833/59290
Iteration: 19834/59290
Iteration: 19835/59290
Iteration: 19836/59290
Iteration: 19837/59290
Iteration: 19838/59290
Iteration: 19839/59290
Iteration: 19840/59290

 33%|███▎      | 19834/59290 [14:13<11:33, 56.93it/s]

Iteration: 19841/59290
Iteration: 19842/59290
Iteration: 19843/59290
Iteration: 19844/59290
Iteration: 19845/59290
Iteration: 19846/59290
Iteration: 19847/59290
Iteration: 19848/59290
Iteration: 19849/59290
Iteration: 19850/59290
Iteration: 19851/59290
Iteration: 19852/59290
Iteration: 19853/59290
Iteration: 19854/59290
Iteration: 19855/59290
Iteration: 19856/59290
Iteration: 19857/59290
Iteration: 19858/59290
Iteration: 19859/59290
Iteration: 19860/59290
Iteration: 19861/59290
Iteration: 19862/59290
Iteration: 19863/59290
Iteration: 19864/59290

 33%|███▎      | 19858/59290 [14:13<11:12, 58.65it/s]

Iteration: 19865/59290
Iteration: 19866/59290
Iteration: 19867/59290
Iteration: 19868/59290
Iteration: 19869/59290
Iteration: 19870/59290
Iteration: 19871/59290
Iteration: 19872/59290
Iteration: 19873/59290
Iteration: 19874/59290
Iteration: 19875/59290
Iteration: 19876/59290
Iteration: 19877/59290
Iteration: 19878/59290
Iteration: 19879/59290
Iteration: 19880/59290
Iteration: 19881/59290
Iteration: 19882/59290
Iteration: 19883/59290
Iteration: 19884/59290
Iteration: 19885/59290
Iteration: 19886/59290
Iteration: 19887/59290
Iteration: 19888/59290

 34%|███▎      | 19882/59290 [14:13<11:02, 59.52it/s]

Iteration: 19889/59290
Iteration: 19890/59290
Iteration: 19891/59290
Iteration: 19892/59290
Iteration: 19893/59290
Iteration: 19894/59290
Iteration: 19895/59290
Iteration: 19896/59290
Iteration: 19897/59290
Iteration: 19898/59290
Iteration: 19899/59290
Iteration: 19900/59290
Iteration: 19901/59290
Iteration: 19902/59290
Iteration: 19903/59290
Iteration: 19904/59290
Iteration: 19905/59290
Iteration: 19906/59290
Iteration: 19907/59290
Iteration: 19908/59290
Iteration: 19909/59290
Iteration: 19910/59290
Iteration: 19911/59290
Iteration: 19912/59290

 34%|███▎      | 19906/59290 [14:14<10:55, 60.06it/s]

Iteration: 19913/59290
Iteration: 19914/59290
Iteration: 19915/59290
Iteration: 19916/59290
Iteration: 19917/59290
Iteration: 19918/59290
Iteration: 19919/59290
Iteration: 19920/59290
Iteration: 19921/59290
Iteration: 19922/59290
Iteration: 19923/59290
Iteration: 19924/59290
Iteration: 19925/59290
Iteration: 19926/59290
Iteration: 19927/59290
Iteration: 19928/59290
Iteration: 19929/59290
Iteration: 19930/59290
Iteration: 19931/59290
Iteration: 19932/59290
Iteration: 19933/59290
Iteration: 19934/59290
Iteration: 19935/59290
Iteration: 19936/59290

 34%|███▎      | 19930/59290 [14:14<10:49, 60.58it/s]

Iteration: 19937/59290
Iteration: 19938/59290
Iteration: 19939/59290
Iteration: 19940/59290
Iteration: 19941/59290
Iteration: 19942/59290
Iteration: 19943/59290
Iteration: 19944/59290
Iteration: 19945/59290
Iteration: 19946/59290
Iteration: 19947/59290
Iteration: 19948/59290
Iteration: 19949/59290
Iteration: 19950/59290
Iteration: 19951/59290
Iteration: 19952/59290
Iteration: 19953/59290
Iteration: 19954/59290
Iteration: 19955/59290
Iteration: 19956/59290
Iteration: 19957/59290
Iteration: 19958/59290
Iteration: 19959/59290
Iteration: 19960/59290

 34%|███▎      | 19954/59290 [14:15<10:42, 61.21it/s]

Iteration: 19961/59290
Iteration: 19962/59290
Iteration: 19963/59290
Iteration: 19964/59290
Iteration: 19965/59290
Iteration: 19966/59290
Iteration: 19967/59290
Iteration: 19968/59290
Iteration: 19969/59290
Iteration: 19970/59290
Iteration: 19971/59290
Iteration: 19972/59290
Iteration: 19973/59290
Iteration: 19974/59290
Iteration: 19975/59290
Iteration: 19976/59290
Iteration: 19977/59290
Iteration: 19978/59290
Iteration: 19979/59290
Iteration: 19980/59290
Iteration: 19981/59290
Iteration: 19982/59290
Iteration: 19983/59290
Iteration: 19984/59290

 34%|███▎      | 19978/59290 [14:15<10:35, 61.85it/s]

Iteration: 19985/59290
Iteration: 19986/59290
Iteration: 19987/59290
Iteration: 19988/59290
Iteration: 19989/59290
Iteration: 19990/59290
Iteration: 19991/59290
Iteration: 19992/59290
Iteration: 19993/59290
Iteration: 19994/59290
Iteration: 19995/59290
Iteration: 19996/59290
Iteration: 19997/59290
Iteration: 19998/59290
Iteration: 19999/59290
Iteration: 20000/59290
Iteration: 20001/59290
Iteration: 20002/59290
Iteration: 20003/59290
Iteration: 20004/59290
Iteration: 20005/59290
Iteration: 20006/59290
Iteration: 20007/59290
Iteration: 20008/59290

 34%|███▎      | 20002/59290 [14:15<10:37, 61.61it/s]

Iteration: 20009/59290
Iteration: 20010/59290
Iteration: 20011/59290
Iteration: 20012/59290
Iteration: 20013/59290
Iteration: 20014/59290
Iteration: 20015/59290
Iteration: 20016/59290
Iteration: 20017/59290
Iteration: 20018/59290
Iteration: 20019/59290
Iteration: 20020/59290
Iteration: 20021/59290
Iteration: 20022/59290
Iteration: 20023/59290
Iteration: 20024/59290
Iteration: 20025/59290
Iteration: 20026/59290
Iteration: 20027/59290
Iteration: 20028/59290
Iteration: 20029/59290
Iteration: 20030/59290
Iteration: 20031/59290
Iteration: 20032/59290

 34%|███▍      | 20026/59290 [14:16<10:32, 62.09it/s]

Iteration: 20033/59290
Iteration: 20034/59290
Iteration: 20035/59290
Iteration: 20036/59290
Iteration: 20037/59290
Iteration: 20038/59290
Iteration: 20039/59290
Iteration: 20040/59290
Iteration: 20041/59290
Iteration: 20042/59290
Iteration: 20043/59290
Iteration: 20044/59290
Iteration: 20045/59290
Iteration: 20046/59290
Iteration: 20047/59290
Iteration: 20048/59290
Iteration: 20049/59290
Iteration: 20050/59290
Iteration: 20051/59290
Iteration: 20052/59290
Iteration: 20053/59290
Iteration: 20054/59290
Iteration: 20055/59290
Iteration: 20056/59290

 34%|███▍      | 20050/59290 [14:16<10:38, 61.50it/s]

Iteration: 20057/59290
Iteration: 20058/59290
Iteration: 20059/59290
Iteration: 20060/59290
Iteration: 20061/59290
Iteration: 20062/59290
Iteration: 20063/59290
Iteration: 20064/59290
Iteration: 20065/59290
Iteration: 20066/59290
Iteration: 20067/59290
Iteration: 20068/59290
Iteration: 20069/59290
Iteration: 20070/59290
Iteration: 20071/59290
Iteration: 20072/59290
Iteration: 20073/59290
Iteration: 20074/59290
Iteration: 20075/59290
Iteration: 20076/59290
Iteration: 20077/59290
Iteration: 20078/59290
Iteration: 20079/59290
Iteration: 20080/59290

 34%|███▍      | 20074/59290 [14:17<10:30, 62.22it/s]

Iteration: 20081/59290
Iteration: 20082/59290
Iteration: 20083/59290
Iteration: 20084/59290
Iteration: 20085/59290
Iteration: 20086/59290
Iteration: 20087/59290
Iteration: 20088/59290
Iteration: 20089/59290
Iteration: 20090/59290
Iteration: 20091/59290
Iteration: 20092/59290
Iteration: 20093/59290
Iteration: 20094/59290
Iteration: 20095/59290
Iteration: 20096/59290
Iteration: 20097/59290
Iteration: 20098/59290
Iteration: 20099/59290
Iteration: 20100/59290
Iteration: 20101/59290
Iteration: 20102/59290
Iteration: 20103/59290
Iteration: 20104/59290

 34%|███▍      | 20098/59290 [14:17<10:31, 62.08it/s]

Iteration: 20105/59290
Iteration: 20106/59290
Iteration: 20107/59290
Iteration: 20108/59290
Iteration: 20109/59290
Iteration: 20110/59290
Iteration: 20111/59290
Iteration: 20112/59290
Iteration: 20113/59290
Iteration: 20114/59290
Iteration: 20115/59290
Iteration: 20116/59290
Iteration: 20117/59290
Iteration: 20118/59290
Iteration: 20119/59290
Iteration: 20120/59290
Iteration: 20121/59290
Iteration: 20122/59290
Iteration: 20123/59290
Iteration: 20124/59290
Iteration: 20125/59290
Iteration: 20126/59290
Iteration: 20127/59290
Iteration: 20128/59290

 34%|███▍      | 20122/59290 [14:17<10:32, 61.93it/s]

Iteration: 20129/59290
Iteration: 20130/59290
Iteration: 20131/59290
Iteration: 20132/59290
Iteration: 20133/59290
Iteration: 20134/59290
Iteration: 20135/59290
Iteration: 20136/59290
Iteration: 20137/59290
Iteration: 20138/59290
Iteration: 20139/59290
Iteration: 20140/59290
Iteration: 20141/59290
Iteration: 20142/59290
Iteration: 20143/59290
Iteration: 20144/59290
Iteration: 20145/59290
Iteration: 20146/59290
Iteration: 20147/59290
Iteration: 20148/59290
Iteration: 20149/59290
Iteration: 20150/59290
Iteration: 20151/59290
Iteration: 20152/59290

 34%|███▍      | 20146/59290 [14:18<10:28, 62.25it/s]

Iteration: 20153/59290
Iteration: 20154/59290
Iteration: 20155/59290
Iteration: 20156/59290
Iteration: 20157/59290
Iteration: 20158/59290
Iteration: 20159/59290
Iteration: 20160/59290
Iteration: 20161/59290
Iteration: 20162/59290
Iteration: 20163/59290
Iteration: 20164/59290
Iteration: 20165/59290
Iteration: 20166/59290
Iteration: 20167/59290
Iteration: 20168/59290
Iteration: 20169/59290
Iteration: 20170/59290
Iteration: 20171/59290
Iteration: 20172/59290
Iteration: 20173/59290
Iteration: 20174/59290
Iteration: 20175/59290
Iteration: 20176/59290

 34%|███▍      | 20170/59290 [14:18<10:27, 62.31it/s]

Iteration: 20177/59290
Iteration: 20178/59290
Iteration: 20179/59290
Iteration: 20180/59290
Iteration: 20181/59290
Iteration: 20182/59290
Iteration: 20183/59290
Iteration: 20184/59290
Iteration: 20185/59290
Iteration: 20186/59290
Iteration: 20187/59290
Iteration: 20188/59290
Iteration: 20189/59290
Iteration: 20190/59290
Iteration: 20191/59290
Iteration: 20192/59290
Iteration: 20193/59290
Iteration: 20194/59290
Iteration: 20195/59290
Iteration: 20196/59290
Iteration: 20197/59290
Iteration: 20198/59290
Iteration: 20199/59290
Iteration: 20200/59290

 34%|███▍      | 20194/59290 [14:18<10:24, 62.61it/s]

Iteration: 20201/59290
Iteration: 20202/59290
Iteration: 20203/59290
Iteration: 20204/59290
Iteration: 20205/59290
Iteration: 20206/59290
Iteration: 20207/59290
Iteration: 20208/59290
Iteration: 20209/59290
Iteration: 20210/59290
Iteration: 20211/59290
Iteration: 20212/59290
Iteration: 20213/59290
Iteration: 20214/59290
Iteration: 20215/59290
Iteration: 20216/59290
Iteration: 20217/59290
Iteration: 20218/59290
Iteration: 20219/59290
Iteration: 20220/59290
Iteration: 20221/59290
Iteration: 20222/59290
Iteration: 20223/59290
Iteration: 20224/59290

 34%|███▍      | 20218/59290 [14:19<10:24, 62.56it/s]

Iteration: 20225/59290
Iteration: 20226/59290
Iteration: 20227/59290
Iteration: 20228/59290
Iteration: 20229/59290
Iteration: 20230/59290
Iteration: 20231/59290
Iteration: 20232/59290
Iteration: 20233/59290
Iteration: 20234/59290
Iteration: 20235/59290
Iteration: 20236/59290
Iteration: 20237/59290
Iteration: 20238/59290
Iteration: 20239/59290
Iteration: 20240/59290
Iteration: 20241/59290
Iteration: 20242/59290
Iteration: 20243/59290
Iteration: 20244/59290
Iteration: 20245/59290
Iteration: 20246/59290
Iteration: 20247/59290
Iteration: 20248/59290

 34%|███▍      | 20242/59290 [14:19<10:26, 62.34it/s]

Iteration: 20249/59290
Iteration: 20250/59290
Iteration: 20251/59290
Iteration: 20252/59290
Iteration: 20253/59290
Iteration: 20254/59290
Iteration: 20255/59290
Iteration: 20256/59290
Iteration: 20257/59290
Iteration: 20258/59290
Iteration: 20259/59290
Iteration: 20260/59290
Iteration: 20261/59290
Iteration: 20262/59290
Iteration: 20263/59290
Iteration: 20264/59290
Iteration: 20265/59290
Iteration: 20266/59290
Iteration: 20267/59290
Iteration: 20268/59290
Iteration: 20269/59290
Iteration: 20270/59290
Iteration: 20271/59290
Iteration: 20272/59290

 34%|███▍      | 20266/59290 [14:20<10:24, 62.47it/s]

Iteration: 20273/59290
Iteration: 20274/59290
Iteration: 20275/59290
Iteration: 20276/59290
Iteration: 20277/59290
Iteration: 20278/59290
Iteration: 20279/59290
Iteration: 20280/59290
Iteration: 20281/59290
Iteration: 20282/59290
Iteration: 20283/59290
Iteration: 20284/59290
Iteration: 20285/59290
Iteration: 20286/59290
Iteration: 20287/59290
Iteration: 20288/59290
Iteration: 20289/59290
Iteration: 20290/59290
Iteration: 20291/59290
Iteration: 20292/59290
Iteration: 20293/59290
Iteration: 20294/59290
Iteration: 20295/59290
Iteration: 20296/59290

 34%|███▍      | 20290/59290 [14:20<10:21, 62.70it/s]

Iteration: 20297/59290
Iteration: 20298/59290
Iteration: 20299/59290
Iteration: 20300/59290
Iteration: 20301/59290
Iteration: 20302/59290
Iteration: 20303/59290
Iteration: 20304/59290
Iteration: 20305/59290
Iteration: 20306/59290
Iteration: 20307/59290
Iteration: 20308/59290
Iteration: 20309/59290
Iteration: 20310/59290
Iteration: 20311/59290
Iteration: 20312/59290
Iteration: 20313/59290
Iteration: 20314/59290
Iteration: 20315/59290
Iteration: 20316/59290
Iteration: 20317/59290
Iteration: 20318/59290
Iteration: 20319/59290
Iteration: 20320/59290

 34%|███▍      | 20314/59290 [14:20<10:26, 62.18it/s]

Iteration: 20321/59290
Iteration: 20322/59290
Iteration: 20323/59290
Iteration: 20324/59290
Iteration: 20325/59290
Iteration: 20326/59290
Iteration: 20327/59290
Iteration: 20328/59290
Iteration: 20329/59290
Iteration: 20330/59290
Iteration: 20331/59290
Iteration: 20332/59290
Iteration: 20333/59290
Iteration: 20334/59290
Iteration: 20335/59290
Iteration: 20336/59290
Iteration: 20337/59290
Iteration: 20338/59290
Iteration: 20339/59290
Iteration: 20340/59290
Iteration: 20341/59290
Iteration: 20342/59290
Iteration: 20343/59290
Iteration: 20344/59290

 34%|███▍      | 20338/59290 [14:21<10:23, 62.46it/s]

Iteration: 20345/59290
Iteration: 20346/59290
Iteration: 20347/59290
Iteration: 20348/59290
Iteration: 20349/59290
Iteration: 20350/59290
Iteration: 20351/59290
Iteration: 20352/59290
Iteration: 20353/59290
Iteration: 20354/59290
Iteration: 20355/59290
Iteration: 20356/59290
Iteration: 20357/59290
Iteration: 20358/59290
Iteration: 20359/59290
Iteration: 20360/59290
Iteration: 20361/59290
Iteration: 20362/59290
Iteration: 20363/59290
Iteration: 20364/59290
Iteration: 20365/59290
Iteration: 20366/59290
Iteration: 20367/59290
Iteration: 20368/59290

 34%|███▍      | 20362/59290 [14:21<10:21, 62.63it/s]

Iteration: 20369/59290
Iteration: 20370/59290
Iteration: 20371/59290
Iteration: 20372/59290
Iteration: 20373/59290
Iteration: 20374/59290
Iteration: 20375/59290
Iteration: 20376/59290
Iteration: 20377/59290
Iteration: 20378/59290
Iteration: 20379/59290
Iteration: 20380/59290
Iteration: 20381/59290
Iteration: 20382/59290
Iteration: 20383/59290
Iteration: 20384/59290
Iteration: 20385/59290
Iteration: 20386/59290
Iteration: 20387/59290
Iteration: 20388/59290
Iteration: 20389/59290
Iteration: 20390/59290
Iteration: 20391/59290
Iteration: 20392/59290

 34%|███▍      | 20386/59290 [14:22<10:15, 63.19it/s]

Iteration: 20393/59290
Iteration: 20394/59290
Iteration: 20395/59290
Iteration: 20396/59290
Iteration: 20397/59290
Iteration: 20398/59290
Iteration: 20399/59290
Iteration: 20400/59290
Iteration: 20401/59290
Iteration: 20402/59290
Iteration: 20403/59290
Iteration: 20404/59290
Iteration: 20405/59290
Iteration: 20406/59290
Iteration: 20407/59290
Iteration: 20408/59290
Iteration: 20409/59290
Iteration: 20410/59290
Iteration: 20411/59290
Iteration: 20412/59290
Iteration: 20413/59290
Iteration: 20414/59290
Iteration: 20415/59290
Iteration: 20416/59290

 34%|███▍      | 20410/59290 [14:22<10:31, 61.60it/s]

Iteration: 20417/59290
Iteration: 20418/59290
Iteration: 20419/59290
Iteration: 20420/59290
Iteration: 20421/59290
Iteration: 20422/59290
Iteration: 20423/59290
Iteration: 20424/59290
Iteration: 20425/59290
Iteration: 20426/59290
Iteration: 20427/59290
Iteration: 20428/59290
Iteration: 20429/59290
Iteration: 20430/59290
Iteration: 20431/59290
Iteration: 20432/59290
Iteration: 20433/59290
Iteration: 20434/59290
Iteration: 20435/59290
Iteration: 20436/59290
Iteration: 20437/59290
Iteration: 20438/59290
Iteration: 20439/59290
Iteration: 20440/59290

 34%|███▍      | 20434/59290 [14:22<10:31, 61.54it/s]

Iteration: 20441/59290
Iteration: 20442/59290
Iteration: 20443/59290
Iteration: 20444/59290
Iteration: 20445/59290
Iteration: 20446/59290
Iteration: 20447/59290
Iteration: 20448/59290
Iteration: 20449/59290
Iteration: 20450/59290
Iteration: 20451/59290
Iteration: 20452/59290
Iteration: 20453/59290
Iteration: 20454/59290
Iteration: 20455/59290
Iteration: 20456/59290
Iteration: 20457/59290
Iteration: 20458/59290
Iteration: 20459/59290
Iteration: 20460/59290
Iteration: 20461/59290
Iteration: 20462/59290
Iteration: 20463/59290
Iteration: 20464/59290

 35%|███▍      | 20458/59290 [14:23<10:32, 61.37it/s]

Iteration: 20465/59290
Iteration: 20466/59290
Iteration: 20467/59290
Iteration: 20468/59290
Iteration: 20469/59290
Iteration: 20470/59290
Iteration: 20471/59290
Iteration: 20472/59290
Iteration: 20473/59290
Iteration: 20474/59290
Iteration: 20475/59290
Iteration: 20476/59290
Iteration: 20477/59290
Iteration: 20478/59290
Iteration: 20479/59290
Iteration: 20480/59290
Iteration: 20481/59290
Iteration: 20482/59290
Iteration: 20483/59290
Iteration: 20484/59290
Iteration: 20485/59290
Iteration: 20486/59290
Iteration: 20487/59290
Iteration: 20488/59290

 35%|███▍      | 20482/59290 [14:23<10:30, 61.55it/s]

Iteration: 20489/59290
Iteration: 20490/59290
Iteration: 20491/59290
Iteration: 20492/59290
Iteration: 20493/59290
Iteration: 20494/59290
Iteration: 20495/59290
Iteration: 20496/59290
Iteration: 20497/59290
Iteration: 20498/59290
Iteration: 20499/59290
Iteration: 20500/59290
Iteration: 20501/59290
Iteration: 20502/59290
Iteration: 20503/59290
Iteration: 20504/59290
Iteration: 20505/59290
Iteration: 20506/59290
Iteration: 20507/59290
Iteration: 20508/59290
Iteration: 20509/59290
Iteration: 20510/59290
Iteration: 20511/59290
Iteration: 20512/59290

 35%|███▍      | 20506/59290 [14:24<10:24, 62.07it/s]

Iteration: 20513/59290
Iteration: 20514/59290
Iteration: 20515/59290
Iteration: 20516/59290
Iteration: 20517/59290
Iteration: 20518/59290
Iteration: 20519/59290
Iteration: 20520/59290
Iteration: 20521/59290
Iteration: 20522/59290
Iteration: 20523/59290
Iteration: 20524/59290
Iteration: 20525/59290
Iteration: 20526/59290
Iteration: 20527/59290
Iteration: 20528/59290
Iteration: 20529/59290
Iteration: 20530/59290
Iteration: 20531/59290
Iteration: 20532/59290
Iteration: 20533/59290
Iteration: 20534/59290
Iteration: 20535/59290
Iteration: 20536/59290

 35%|███▍      | 20530/59290 [14:24<10:19, 62.54it/s]

Iteration: 20537/59290
Iteration: 20538/59290
Iteration: 20539/59290
Iteration: 20540/59290
Iteration: 20541/59290
Iteration: 20542/59290
Iteration: 20543/59290
Iteration: 20544/59290
Iteration: 20545/59290
Iteration: 20546/59290
Iteration: 20547/59290
Iteration: 20548/59290
Iteration: 20549/59290
Iteration: 20550/59290
Iteration: 20551/59290
Iteration: 20552/59290
Iteration: 20553/59290
Iteration: 20554/59290
Iteration: 20555/59290
Iteration: 20556/59290
Iteration: 20557/59290
Iteration: 20558/59290
Iteration: 20559/59290
Iteration: 20560/59290

 35%|███▍      | 20554/59290 [14:24<10:17, 62.78it/s]

Iteration: 20561/59290
Iteration: 20562/59290
Iteration: 20563/59290
Iteration: 20564/59290
Iteration: 20565/59290
Iteration: 20566/59290
Iteration: 20567/59290
Iteration: 20568/59290
Iteration: 20569/59290
Iteration: 20570/59290
Iteration: 20571/59290
Iteration: 20572/59290
Iteration: 20573/59290
Iteration: 20574/59290
Iteration: 20575/59290
Iteration: 20576/59290
Iteration: 20577/59290
Iteration: 20578/59290
Iteration: 20579/59290
Iteration: 20580/59290
Iteration: 20581/59290
Iteration: 20582/59290
Iteration: 20583/59290
Iteration: 20584/59290

 35%|███▍      | 20578/59290 [14:26<21:57, 29.39it/s]

Iteration: 20585/59290
Iteration: 20586/59290
Iteration: 20587/59290
Iteration: 20588/59290
Iteration: 20589/59290
Iteration: 20590/59290
Iteration: 20591/59290
Iteration: 20592/59290
Iteration: 20593/59290
Iteration: 20594/59290
Iteration: 20595/59290
Iteration: 20596/59290
Iteration: 20597/59290
Iteration: 20598/59290
Iteration: 20599/59290
Iteration: 20600/59290
Iteration: 20601/59290
Iteration: 20602/59290
Iteration: 20603/59290
Iteration: 20604/59290
Iteration: 20605/59290
Iteration: 20606/59290
Iteration: 20607/59290
Iteration: 20608/59290

 35%|███▍      | 20602/59290 [14:28<34:06, 18.90it/s]

Iteration: 20609/59290
Iteration: 20610/59290
Iteration: 20611/59290
Iteration: 20612/59290
Iteration: 20613/59290
Iteration: 20614/59290
Iteration: 20615/59290
Iteration: 20616/59290
Iteration: 20617/59290
Iteration: 20618/59290
Iteration: 20619/59290
Iteration: 20620/59290
Iteration: 20621/59290
Iteration: 20622/59290
Iteration: 20623/59290
Iteration: 20624/59290
Iteration: 20625/59290
Iteration: 20626/59290
Iteration: 20627/59290
Iteration: 20628/59290
Iteration: 20629/59290
Iteration: 20630/59290
Iteration: 20631/59290
Iteration: 20632/59290

 35%|███▍      | 20626/59290 [14:29<29:57, 21.51it/s]

Iteration: 20633/59290
Iteration: 20634/59290
Iteration: 20635/59290
Iteration: 20636/59290
Iteration: 20637/59290
Iteration: 20638/59290
Iteration: 20639/59290
Iteration: 20640/59290
Iteration: 20641/59290
Iteration: 20642/59290
Iteration: 20643/59290
Iteration: 20644/59290
Iteration: 20645/59290
Iteration: 20646/59290
Iteration: 20647/59290
Iteration: 20648/59290
Iteration: 20649/59290
Iteration: 20650/59290
Iteration: 20651/59290
Iteration: 20652/59290
Iteration: 20653/59290
Iteration: 20654/59290
Iteration: 20655/59290
Iteration: 20656/59290

 35%|███▍      | 20650/59290 [14:30<24:19, 26.48it/s]

Iteration: 20657/59290
Iteration: 20658/59290
Iteration: 20659/59290
Iteration: 20660/59290
Iteration: 20661/59290
Iteration: 20662/59290
Iteration: 20663/59290
Iteration: 20664/59290
Iteration: 20665/59290
Iteration: 20666/59290
Iteration: 20667/59290
Iteration: 20668/59290
Iteration: 20669/59290
Iteration: 20670/59290
Iteration: 20671/59290
Iteration: 20672/59290
Iteration: 20673/59290
Iteration: 20674/59290
Iteration: 20675/59290
Iteration: 20676/59290
Iteration: 20677/59290
Iteration: 20678/59290
Iteration: 20679/59290
Iteration: 20680/59290

 35%|███▍      | 20674/59290 [14:30<20:03, 32.08it/s]

Iteration: 20681/59290
Iteration: 20682/59290
Iteration: 20683/59290
Iteration: 20684/59290
Iteration: 20685/59290
Iteration: 20686/59290
Iteration: 20687/59290
Iteration: 20688/59290
Iteration: 20689/59290
Iteration: 20690/59290
Iteration: 20691/59290
Iteration: 20692/59290
Iteration: 20693/59290
Iteration: 20694/59290
Iteration: 20695/59290
Iteration: 20696/59290
Iteration: 20697/59290
Iteration: 20698/59290
Iteration: 20699/59290
Iteration: 20700/59290
Iteration: 20701/59290
Iteration: 20702/59290
Iteration: 20703/59290
Iteration: 20704/59290

 35%|███▍      | 20698/59290 [14:30<17:33, 36.65it/s]

Iteration: 20705/59290
Iteration: 20706/59290
Iteration: 20707/59290
Iteration: 20708/59290
Iteration: 20709/59290
Iteration: 20710/59290
Iteration: 20711/59290
Iteration: 20712/59290
Iteration: 20713/59290
Iteration: 20714/59290
Iteration: 20715/59290
Iteration: 20716/59290
Iteration: 20717/59290
Iteration: 20718/59290
Iteration: 20719/59290
Iteration: 20720/59290
Iteration: 20721/59290
Iteration: 20722/59290
Iteration: 20723/59290
Iteration: 20724/59290
Iteration: 20725/59290
Iteration: 20726/59290
Iteration: 20727/59290
Iteration: 20728/59290

 35%|███▍      | 20722/59290 [14:31<15:24, 41.72it/s]

Iteration: 20729/59290
Iteration: 20730/59290
Iteration: 20731/59290
Iteration: 20732/59290
Iteration: 20733/59290
Iteration: 20734/59290
Iteration: 20735/59290
Iteration: 20736/59290
Iteration: 20737/59290
Iteration: 20738/59290
Iteration: 20739/59290
Iteration: 20740/59290
Iteration: 20741/59290
Iteration: 20742/59290
Iteration: 20743/59290
Iteration: 20744/59290
Iteration: 20745/59290
Iteration: 20746/59290
Iteration: 20747/59290
Iteration: 20748/59290
Iteration: 20749/59290
Iteration: 20750/59290
Iteration: 20751/59290
Iteration: 20752/59290

 35%|███▍      | 20746/59290 [14:31<13:47, 46.56it/s]

Iteration: 20753/59290
Iteration: 20754/59290
Iteration: 20755/59290
Iteration: 20756/59290
Iteration: 20757/59290
Iteration: 20758/59290
Iteration: 20759/59290
Iteration: 20760/59290
Iteration: 20761/59290
Iteration: 20762/59290
Iteration: 20763/59290
Iteration: 20764/59290
Iteration: 20765/59290
Iteration: 20766/59290
Iteration: 20767/59290
Iteration: 20768/59290
Iteration: 20769/59290
Iteration: 20770/59290
Iteration: 20771/59290
Iteration: 20772/59290
Iteration: 20773/59290
Iteration: 20774/59290
Iteration: 20775/59290
Iteration: 20776/59290

 35%|███▌      | 20770/59290 [14:32<12:42, 50.50it/s]

Iteration: 20777/59290
Iteration: 20778/59290
Iteration: 20779/59290
Iteration: 20780/59290
Iteration: 20781/59290
Iteration: 20782/59290
Iteration: 20783/59290
Iteration: 20784/59290
Iteration: 20785/59290
Iteration: 20786/59290
Iteration: 20787/59290
Iteration: 20788/59290
Iteration: 20789/59290
Iteration: 20790/59290
Iteration: 20791/59290
Iteration: 20792/59290
Iteration: 20793/59290
Iteration: 20794/59290
Iteration: 20795/59290
Iteration: 20796/59290
Iteration: 20797/59290
Iteration: 20798/59290
Iteration: 20799/59290
Iteration: 20800/59290

 35%|███▌      | 20794/59290 [14:32<13:02, 49.23it/s]

Iteration: 20801/59290
Iteration: 20802/59290
Iteration: 20803/59290
Iteration: 20804/59290
Iteration: 20805/59290
Iteration: 20806/59290
Iteration: 20807/59290
Iteration: 20808/59290
Iteration: 20809/59290
Iteration: 20810/59290
Iteration: 20811/59290
Iteration: 20812/59290
Iteration: 20813/59290
Iteration: 20814/59290
Iteration: 20815/59290
Iteration: 20816/59290
Iteration: 20817/59290
Iteration: 20818/59290
Iteration: 20819/59290
Iteration: 20820/59290
Iteration: 20821/59290
Iteration: 20822/59290
Iteration: 20823/59290
Iteration: 20824/59290

 35%|███▌      | 20818/59290 [14:32<12:09, 52.76it/s]

Iteration: 20825/59290
Iteration: 20826/59290
Iteration: 20827/59290
Iteration: 20828/59290
Iteration: 20829/59290
Iteration: 20830/59290
Iteration: 20831/59290
Iteration: 20832/59290
Iteration: 20833/59290
Iteration: 20834/59290
Iteration: 20835/59290
Iteration: 20836/59290
Iteration: 20837/59290
Iteration: 20838/59290
Iteration: 20839/59290
Iteration: 20840/59290
Iteration: 20841/59290
Iteration: 20842/59290
Iteration: 20843/59290
Iteration: 20844/59290
Iteration: 20845/59290
Iteration: 20846/59290
Iteration: 20847/59290
Iteration: 20848/59290

 35%|███▌      | 20842/59290 [14:33<11:35, 55.30it/s]

Iteration: 20849/59290
Iteration: 20850/59290
Iteration: 20851/59290
Iteration: 20852/59290
Iteration: 20853/59290
Iteration: 20854/59290
Iteration: 20855/59290
Iteration: 20856/59290
Iteration: 20857/59290
Iteration: 20858/59290
Iteration: 20859/59290
Iteration: 20860/59290
Iteration: 20861/59290
Iteration: 20862/59290
Iteration: 20863/59290
Iteration: 20864/59290
Iteration: 20865/59290
Iteration: 20866/59290
Iteration: 20867/59290
Iteration: 20868/59290
Iteration: 20869/59290
Iteration: 20870/59290
Iteration: 20871/59290
Iteration: 20872/59290

 35%|███▌      | 20866/59290 [14:33<11:08, 57.45it/s]

Iteration: 20873/59290
Iteration: 20874/59290
Iteration: 20875/59290
Iteration: 20876/59290
Iteration: 20877/59290
Iteration: 20878/59290
Iteration: 20879/59290
Iteration: 20880/59290
Iteration: 20881/59290
Iteration: 20882/59290
Iteration: 20883/59290
Iteration: 20884/59290
Iteration: 20885/59290
Iteration: 20886/59290
Iteration: 20887/59290
Iteration: 20888/59290
Iteration: 20889/59290
Iteration: 20890/59290
Iteration: 20891/59290
Iteration: 20892/59290
Iteration: 20893/59290
Iteration: 20894/59290
Iteration: 20895/59290
Iteration: 20896/59290

 35%|███▌      | 20890/59290 [14:34<10:57, 58.38it/s]

Iteration: 20897/59290
Iteration: 20898/59290
Iteration: 20899/59290
Iteration: 20900/59290
Iteration: 20901/59290
Iteration: 20902/59290
Iteration: 20903/59290
Iteration: 20904/59290
Iteration: 20905/59290
Iteration: 20906/59290
Iteration: 20907/59290
Iteration: 20908/59290
Iteration: 20909/59290
Iteration: 20910/59290
Iteration: 20911/59290
Iteration: 20912/59290
Iteration: 20913/59290
Iteration: 20914/59290
Iteration: 20915/59290
Iteration: 20916/59290
Iteration: 20917/59290
Iteration: 20918/59290
Iteration: 20919/59290
Iteration: 20920/59290

 35%|███▌      | 20914/59290 [14:34<10:39, 60.00it/s]

Iteration: 20921/59290
Iteration: 20922/59290
Iteration: 20923/59290
Iteration: 20924/59290
Iteration: 20925/59290
Iteration: 20926/59290
Iteration: 20927/59290
Iteration: 20928/59290
Iteration: 20929/59290
Iteration: 20930/59290
Iteration: 20931/59290
Iteration: 20932/59290
Iteration: 20933/59290
Iteration: 20934/59290
Iteration: 20935/59290
Iteration: 20936/59290
Iteration: 20937/59290
Iteration: 20938/59290
Iteration: 20939/59290
Iteration: 20940/59290
Iteration: 20941/59290
Iteration: 20942/59290
Iteration: 20943/59290
Iteration: 20944/59290

 35%|███▌      | 20938/59290 [14:36<22:11, 28.80it/s]

Iteration: 20945/59290
Iteration: 20946/59290
Iteration: 20947/59290
Iteration: 20948/59290
Iteration: 20949/59290
Iteration: 20950/59290
Iteration: 20951/59290
Iteration: 20952/59290
Iteration: 20953/59290
Iteration: 20954/59290
Iteration: 20955/59290
Iteration: 20956/59290
Iteration: 20957/59290
Iteration: 20958/59290
Iteration: 20959/59290
Iteration: 20960/59290
Iteration: 20961/59290
Iteration: 20962/59290
Iteration: 20963/59290
Iteration: 20964/59290
Iteration: 20965/59290
Iteration: 20966/59290
Iteration: 20967/59290
Iteration: 20968/59290

 35%|███▌      | 20962/59290 [14:38<33:46, 18.91it/s]

Iteration: 20969/59290
Iteration: 20970/59290
Iteration: 20971/59290
Iteration: 20972/59290
Iteration: 20973/59290
Iteration: 20974/59290
Iteration: 20975/59290
Iteration: 20976/59290
Iteration: 20977/59290
Iteration: 20978/59290
Iteration: 20979/59290
Iteration: 20980/59290
Iteration: 20981/59290
Iteration: 20982/59290
Iteration: 20983/59290
Iteration: 20984/59290
Iteration: 20985/59290
Iteration: 20986/59290
Iteration: 20987/59290
Iteration: 20988/59290
Iteration: 20989/59290
Iteration: 20990/59290
Iteration: 20991/59290
Iteration: 20992/59290

 35%|███▌      | 20986/59290 [14:39<31:27, 20.29it/s]

Iteration: 20993/59290
Iteration: 20994/59290
Iteration: 20995/59290
Iteration: 20996/59290
Iteration: 20997/59290
Iteration: 20998/59290
Iteration: 20999/59290
Iteration: 21000/59290
Iteration: 21001/59290
Iteration: 21002/59290
Iteration: 21003/59290
Iteration: 21004/59290
Iteration: 21005/59290
Iteration: 21006/59290
Iteration: 21007/59290
Iteration: 21008/59290
Iteration: 21009/59290
Iteration: 21010/59290
Iteration: 21011/59290
Iteration: 21012/59290
Iteration: 21013/59290
Iteration: 21014/59290
Iteration: 21015/59290
Iteration: 21016/59290

 35%|███▌      | 21010/59290 [14:39<25:05, 25.43it/s]

Iteration: 21017/59290
Iteration: 21018/59290
Iteration: 21019/59290
Iteration: 21020/59290
Iteration: 21021/59290
Iteration: 21022/59290
Iteration: 21023/59290
Iteration: 21024/59290
Iteration: 21025/59290
Iteration: 21026/59290
Iteration: 21027/59290
Iteration: 21028/59290
Iteration: 21029/59290
Iteration: 21030/59290
Iteration: 21031/59290
Iteration: 21032/59290
Iteration: 21033/59290
Iteration: 21034/59290
Iteration: 21035/59290
Iteration: 21036/59290
Iteration: 21037/59290
Iteration: 21038/59290
Iteration: 21039/59290
Iteration: 21040/59290

 35%|███▌      | 21034/59290 [14:40<20:35, 30.97it/s]

Iteration: 21041/59290
Iteration: 21042/59290
Iteration: 21043/59290
Iteration: 21044/59290
Iteration: 21045/59290
Iteration: 21046/59290
Iteration: 21047/59290
Iteration: 21048/59290
Iteration: 21049/59290
Iteration: 21050/59290
Iteration: 21051/59290
Iteration: 21052/59290
Iteration: 21053/59290
Iteration: 21054/59290
Iteration: 21055/59290
Iteration: 21056/59290
Iteration: 21057/59290
Iteration: 21058/59290
Iteration: 21059/59290
Iteration: 21060/59290
Iteration: 21061/59290
Iteration: 21062/59290
Iteration: 21063/59290
Iteration: 21064/59290

 36%|███▌      | 21058/59290 [14:40<17:25, 36.57it/s]

Iteration: 21065/59290
Iteration: 21066/59290
Iteration: 21067/59290
Iteration: 21068/59290
Iteration: 21069/59290
Iteration: 21070/59290
Iteration: 21071/59290
Iteration: 21072/59290
Iteration: 21073/59290
Iteration: 21074/59290
Iteration: 21075/59290
Iteration: 21076/59290
Iteration: 21077/59290
Iteration: 21078/59290
Iteration: 21079/59290
Iteration: 21080/59290
Iteration: 21081/59290
Iteration: 21082/59290
Iteration: 21083/59290
Iteration: 21084/59290
Iteration: 21085/59290
Iteration: 21086/59290
Iteration: 21087/59290
Iteration: 21088/59290

 36%|███▌      | 21082/59290 [14:41<15:15, 41.74it/s]

Iteration: 21089/59290
Iteration: 21090/59290
Iteration: 21091/59290
Iteration: 21092/59290
Iteration: 21093/59290
Iteration: 21094/59290
Iteration: 21095/59290
Iteration: 21096/59290
Iteration: 21097/59290
Iteration: 21098/59290
Iteration: 21099/59290
Iteration: 21100/59290
Iteration: 21101/59290
Iteration: 21102/59290
Iteration: 21103/59290
Iteration: 21104/59290
Iteration: 21105/59290
Iteration: 21106/59290
Iteration: 21107/59290
Iteration: 21108/59290
Iteration: 21109/59290
Iteration: 21110/59290
Iteration: 21111/59290
Iteration: 21112/59290

 36%|███▌      | 21106/59290 [14:41<13:45, 46.26it/s]

Iteration: 21113/59290
Iteration: 21114/59290
Iteration: 21115/59290
Iteration: 21116/59290
Iteration: 21117/59290
Iteration: 21118/59290
Iteration: 21119/59290
Iteration: 21120/59290
Iteration: 21121/59290
Iteration: 21122/59290
Iteration: 21123/59290
Iteration: 21124/59290
Iteration: 21125/59290
Iteration: 21126/59290
Iteration: 21127/59290
Iteration: 21128/59290
Iteration: 21129/59290
Iteration: 21130/59290
Iteration: 21131/59290
Iteration: 21132/59290
Iteration: 21133/59290
Iteration: 21134/59290
Iteration: 21135/59290
Iteration: 21136/59290

 36%|███▌      | 21130/59290 [14:41<12:34, 50.57it/s]

Iteration: 21137/59290
Iteration: 21138/59290
Iteration: 21139/59290
Iteration: 21140/59290
Iteration: 21141/59290
Iteration: 21142/59290
Iteration: 21143/59290
Iteration: 21144/59290
Iteration: 21145/59290
Iteration: 21146/59290
Iteration: 21147/59290
Iteration: 21148/59290
Iteration: 21149/59290
Iteration: 21150/59290
Iteration: 21151/59290
Iteration: 21152/59290
Iteration: 21153/59290
Iteration: 21154/59290
Iteration: 21155/59290
Iteration: 21156/59290
Iteration: 21157/59290
Iteration: 21158/59290
Iteration: 21159/59290
Iteration: 21160/59290

 36%|███▌      | 21154/59290 [14:42<11:52, 53.56it/s]

Iteration: 21161/59290
Iteration: 21162/59290
Iteration: 21163/59290
Iteration: 21164/59290
Iteration: 21165/59290
Iteration: 21166/59290
Iteration: 21167/59290
Iteration: 21168/59290
Iteration: 21169/59290
Iteration: 21170/59290
Iteration: 21171/59290
Iteration: 21172/59290
Iteration: 21173/59290
Iteration: 21174/59290
Iteration: 21175/59290
Iteration: 21176/59290
Iteration: 21177/59290
Iteration: 21178/59290
Iteration: 21179/59290
Iteration: 21180/59290
Iteration: 21181/59290
Iteration: 21182/59290
Iteration: 21183/59290
Iteration: 21184/59290

 36%|███▌      | 21178/59290 [14:42<11:23, 55.79it/s]

Iteration: 21185/59290
Iteration: 21186/59290
Iteration: 21187/59290
Iteration: 21188/59290
Iteration: 21189/59290
Iteration: 21190/59290
Iteration: 21191/59290
Iteration: 21192/59290
Iteration: 21193/59290
Iteration: 21194/59290
Iteration: 21195/59290
Iteration: 21196/59290
Iteration: 21197/59290
Iteration: 21198/59290
Iteration: 21199/59290
Iteration: 21200/59290
Iteration: 21201/59290
Iteration: 21202/59290
Iteration: 21203/59290
Iteration: 21204/59290
Iteration: 21205/59290
Iteration: 21206/59290
Iteration: 21207/59290
Iteration: 21208/59290

 36%|███▌      | 21202/59290 [14:43<10:54, 58.15it/s]

Iteration: 21209/59290
Iteration: 21210/59290
Iteration: 21211/59290
Iteration: 21212/59290
Iteration: 21213/59290
Iteration: 21214/59290
Iteration: 21215/59290
Iteration: 21216/59290
Iteration: 21217/59290
Iteration: 21218/59290
Iteration: 21219/59290
Iteration: 21220/59290
Iteration: 21221/59290
Iteration: 21222/59290
Iteration: 21223/59290
Iteration: 21224/59290
Iteration: 21225/59290
Iteration: 21226/59290
Iteration: 21227/59290
Iteration: 21228/59290
Iteration: 21229/59290
Iteration: 21230/59290
Iteration: 21231/59290
Iteration: 21232/59290

 36%|███▌      | 21226/59290 [14:43<10:39, 59.49it/s]

Iteration: 21233/59290
Iteration: 21234/59290
Iteration: 21235/59290
Iteration: 21236/59290
Iteration: 21237/59290
Iteration: 21238/59290
Iteration: 21239/59290
Iteration: 21240/59290
Iteration: 21241/59290
Iteration: 21242/59290
Iteration: 21243/59290
Iteration: 21244/59290
Iteration: 21245/59290
Iteration: 21246/59290
Iteration: 21247/59290
Iteration: 21248/59290
Iteration: 21249/59290
Iteration: 21250/59290
Iteration: 21251/59290
Iteration: 21252/59290
Iteration: 21253/59290
Iteration: 21254/59290
Iteration: 21255/59290
Iteration: 21256/59290

 36%|███▌      | 21250/59290 [14:43<10:29, 60.45it/s]

Iteration: 21257/59290
Iteration: 21258/59290
Iteration: 21259/59290
Iteration: 21260/59290
Iteration: 21261/59290
Iteration: 21262/59290
Iteration: 21263/59290
Iteration: 21264/59290
Iteration: 21265/59290
Iteration: 21266/59290
Iteration: 21267/59290
Iteration: 21268/59290
Iteration: 21269/59290
Iteration: 21270/59290
Iteration: 21271/59290
Iteration: 21272/59290
Iteration: 21273/59290
Iteration: 21274/59290
Iteration: 21275/59290
Iteration: 21276/59290
Iteration: 21277/59290
Iteration: 21278/59290
Iteration: 21279/59290
Iteration: 21280/59290

 36%|███▌      | 21274/59290 [14:44<10:22, 61.03it/s]

Iteration: 21281/59290
Iteration: 21282/59290
Iteration: 21283/59290
Iteration: 21284/59290
Iteration: 21285/59290
Iteration: 21286/59290
Iteration: 21287/59290
Iteration: 21288/59290
Iteration: 21289/59290
Iteration: 21290/59290
Iteration: 21291/59290
Iteration: 21292/59290
Iteration: 21293/59290
Iteration: 21294/59290
Iteration: 21295/59290
Iteration: 21296/59290
Iteration: 21297/59290
Iteration: 21298/59290
Iteration: 21299/59290
Iteration: 21300/59290
Iteration: 21301/59290
Iteration: 21302/59290
Iteration: 21303/59290
Iteration: 21304/59290

 36%|███▌      | 21298/59290 [14:44<10:28, 60.41it/s]

Iteration: 21305/59290
Iteration: 21306/59290
Iteration: 21307/59290
Iteration: 21308/59290
Iteration: 21309/59290
Iteration: 21310/59290
Iteration: 21311/59290
Iteration: 21312/59290
Iteration: 21313/59290
Iteration: 21314/59290
Iteration: 21315/59290
Iteration: 21316/59290
Iteration: 21317/59290
Iteration: 21318/59290
Iteration: 21319/59290
Iteration: 21320/59290
Iteration: 21321/59290
Iteration: 21322/59290
Iteration: 21323/59290
Iteration: 21324/59290
Iteration: 21325/59290
Iteration: 21326/59290
Iteration: 21327/59290
Iteration: 21328/59290

 36%|███▌      | 21322/59290 [14:44<10:23, 60.89it/s]

Iteration: 21329/59290
Iteration: 21330/59290
Iteration: 21331/59290
Iteration: 21332/59290
Iteration: 21333/59290
Iteration: 21334/59290
Iteration: 21335/59290
Iteration: 21336/59290
Iteration: 21337/59290
Iteration: 21338/59290
Iteration: 21339/59290
Iteration: 21340/59290
Iteration: 21341/59290
Iteration: 21342/59290
Iteration: 21343/59290
Iteration: 21344/59290
Iteration: 21345/59290
Iteration: 21346/59290
Iteration: 21347/59290
Iteration: 21348/59290
Iteration: 21349/59290
Iteration: 21350/59290
Iteration: 21351/59290
Iteration: 21352/59290

 36%|███▌      | 21346/59290 [14:45<10:14, 61.72it/s]

Iteration: 21353/59290
Iteration: 21354/59290
Iteration: 21355/59290
Iteration: 21356/59290
Iteration: 21357/59290
Iteration: 21358/59290
Iteration: 21359/59290
Iteration: 21360/59290
Iteration: 21361/59290
Iteration: 21362/59290
Iteration: 21363/59290
Iteration: 21364/59290
Iteration: 21365/59290
Iteration: 21366/59290
Iteration: 21367/59290
Iteration: 21368/59290
Iteration: 21369/59290
Iteration: 21370/59290
Iteration: 21371/59290
Iteration: 21372/59290
Iteration: 21373/59290
Iteration: 21374/59290
Iteration: 21375/59290
Iteration: 21376/59290

 36%|███▌      | 21370/59290 [14:47<20:18, 31.11it/s]

Iteration: 21377/59290
Iteration: 21378/59290
Iteration: 21379/59290
Iteration: 21380/59290
Iteration: 21381/59290
Iteration: 21382/59290
Iteration: 21383/59290
Iteration: 21384/59290
Iteration: 21385/59290
Iteration: 21386/59290
Iteration: 21387/59290
Iteration: 21388/59290
Iteration: 21389/59290
Iteration: 21390/59290
Iteration: 21391/59290
Iteration: 21392/59290
Iteration: 21393/59290
Iteration: 21394/59290
Iteration: 21395/59290
Iteration: 21396/59290
Iteration: 21397/59290
Iteration: 21398/59290
Iteration: 21399/59290
Iteration: 21400/59290

 36%|███▌      | 21394/59290 [14:49<32:17, 19.56it/s]

Iteration: 21401/59290
Iteration: 21402/59290
Iteration: 21403/59290
Iteration: 21404/59290
Iteration: 21405/59290
Iteration: 21406/59290
Iteration: 21407/59290
Iteration: 21408/59290
Iteration: 21409/59290
Iteration: 21410/59290
Iteration: 21411/59290
Iteration: 21412/59290
Iteration: 21413/59290
Iteration: 21414/59290
Iteration: 21415/59290
Iteration: 21416/59290
Iteration: 21417/59290
Iteration: 21418/59290
Iteration: 21419/59290
Iteration: 21420/59290
Iteration: 21421/59290
Iteration: 21422/59290
Iteration: 21423/59290
Iteration: 21424/59290

 36%|███▌      | 21418/59290 [14:50<28:28, 22.17it/s]

Iteration: 21425/59290
Iteration: 21426/59290
Iteration: 21427/59290
Iteration: 21428/59290
Iteration: 21429/59290
Iteration: 21430/59290
Iteration: 21431/59290
Iteration: 21432/59290
Iteration: 21433/59290
Iteration: 21434/59290
Iteration: 21435/59290
Iteration: 21436/59290
Iteration: 21437/59290
Iteration: 21438/59290
Iteration: 21439/59290
Iteration: 21440/59290
Iteration: 21441/59290
Iteration: 21442/59290
Iteration: 21443/59290
Iteration: 21444/59290
Iteration: 21445/59290
Iteration: 21446/59290
Iteration: 21447/59290
Iteration: 21448/59290

 36%|███▌      | 21442/59290 [14:50<23:00, 27.41it/s]

Iteration: 21449/59290
Iteration: 21450/59290
Iteration: 21451/59290
Iteration: 21452/59290
Iteration: 21453/59290
Iteration: 21454/59290
Iteration: 21455/59290
Iteration: 21456/59290
Iteration: 21457/59290
Iteration: 21458/59290
Iteration: 21459/59290
Iteration: 21460/59290
Iteration: 21461/59290
Iteration: 21462/59290
Iteration: 21463/59290
Iteration: 21464/59290
Iteration: 21465/59290
Iteration: 21466/59290
Iteration: 21467/59290
Iteration: 21468/59290
Iteration: 21469/59290
Iteration: 21470/59290
Iteration: 21471/59290
Iteration: 21472/59290

 36%|███▌      | 21466/59290 [14:50<19:03, 33.07it/s]

Iteration: 21473/59290
Iteration: 21474/59290
Iteration: 21475/59290
Iteration: 21476/59290
Iteration: 21477/59290
Iteration: 21478/59290
Iteration: 21479/59290
Iteration: 21480/59290
Iteration: 21481/59290
Iteration: 21482/59290
Iteration: 21483/59290
Iteration: 21484/59290
Iteration: 21485/59290
Iteration: 21486/59290
Iteration: 21487/59290
Iteration: 21488/59290
Iteration: 21489/59290
Iteration: 21490/59290
Iteration: 21491/59290
Iteration: 21492/59290
Iteration: 21493/59290
Iteration: 21494/59290
Iteration: 21495/59290
Iteration: 21496/59290

 36%|███▌      | 21490/59290 [14:51<16:14, 38.78it/s]

Iteration: 21497/59290
Iteration: 21498/59290
Iteration: 21499/59290
Iteration: 21500/59290
Iteration: 21501/59290
Iteration: 21502/59290
Iteration: 21503/59290
Iteration: 21504/59290
Iteration: 21505/59290
Iteration: 21506/59290
Iteration: 21507/59290
Iteration: 21508/59290
Iteration: 21509/59290
Iteration: 21510/59290
Iteration: 21511/59290
Iteration: 21512/59290
Iteration: 21513/59290
Iteration: 21514/59290
Iteration: 21515/59290
Iteration: 21516/59290
Iteration: 21517/59290
Iteration: 21518/59290
Iteration: 21519/59290
Iteration: 21520/59290

 36%|███▋      | 21514/59290 [14:53<25:44, 24.46it/s]

Iteration: 21521/59290
Iteration: 21522/59290
Iteration: 21523/59290
Iteration: 21524/59290
Iteration: 21525/59290
Iteration: 21526/59290
Iteration: 21527/59290
Iteration: 21528/59290
Iteration: 21529/59290
Iteration: 21530/59290
Iteration: 21531/59290
Iteration: 21532/59290
Iteration: 21533/59290
Iteration: 21534/59290
Iteration: 21535/59290
Iteration: 21536/59290
Iteration: 21537/59290
Iteration: 21538/59290
Iteration: 21539/59290
Iteration: 21540/59290
Iteration: 21541/59290
Iteration: 21542/59290
Iteration: 21543/59290
Iteration: 21544/59290

 36%|███▋      | 21538/59290 [14:55<35:56, 17.50it/s]

Iteration: 21545/59290
Iteration: 21546/59290
Iteration: 21547/59290
Iteration: 21548/59290
Iteration: 21549/59290
Iteration: 21550/59290
Iteration: 21551/59290
Iteration: 21552/59290
Iteration: 21553/59290
Iteration: 21554/59290
Iteration: 21555/59290
Iteration: 21556/59290
Iteration: 21557/59290
Iteration: 21558/59290
Iteration: 21559/59290
Iteration: 21560/59290
Iteration: 21561/59290
Iteration: 21562/59290
Iteration: 21563/59290
Iteration: 21564/59290
Iteration: 21565/59290
Iteration: 21566/59290
Iteration: 21568/59290

 36%|███▋      | 21561/59290 [14:55<30:35, 20.55it/s]

Iteration: 21569/59290
Iteration: 21570/59290
Iteration: 21571/59290
Iteration: 21572/59290
Iteration: 21573/59290
Iteration: 21574/59290
Iteration: 21575/59290
Iteration: 21576/59290

 36%|███▋      | 21569/59290 [14:56<30:57, 20.31it/s]

Iteration: 21577/59290
Iteration: 21578/59290
Iteration: 21579/59290
Iteration: 21580/59290
Iteration: 21581/59290
Iteration: 21582/59290
Iteration: 21583/59290
Iteration: 21584/59290
Iteration: 21585/59290
Iteration: 21586/59290
Iteration: 21587/59290
Iteration: 21588/59290
Iteration: 21589/59290
Iteration: 21590/59290
Iteration: 21591/59290
Iteration: 21592/59290
Iteration: 21593/59290
Iteration: 21594/59290
Iteration: 21595/59290
Iteration: 21596/59290
Iteration: 21597/59290
Iteration: 21598/59290
Iteration: 21599/59290
Iteration: 21600/59290

 36%|███▋      | 21593/59290 [14:56<23:38, 26.57it/s]

Iteration: 21601/59290
Iteration: 21602/59290
Iteration: 21603/59290
Iteration: 21604/59290
Iteration: 21605/59290
Iteration: 21606/59290
Iteration: 21607/59290
Iteration: 21608/59290
Iteration: 21609/59290
Iteration: 21610/59290
Iteration: 21611/59290
Iteration: 21612/59290
Iteration: 21613/59290
Iteration: 21614/59290
Iteration: 21615/59290
Iteration: 21616/59290
Iteration: 21617/59290
Iteration: 21618/59290
Iteration: 21619/59290
Iteration: 21620/59290
Iteration: 21621/59290
Iteration: 21622/59290
Iteration: 21623/59290
Iteration: 21624/59290

 36%|███▋      | 21617/59290 [14:57<19:15, 32.60it/s]

Iteration: 21625/59290
Iteration: 21626/59290
Iteration: 21627/59290
Iteration: 21628/59290
Iteration: 21629/59290
Iteration: 21630/59290
Iteration: 21631/59290
Iteration: 21632/59290
Iteration: 21633/59290
Iteration: 21634/59290
Iteration: 21635/59290
Iteration: 21636/59290
Iteration: 21637/59290
Iteration: 21638/59290
Iteration: 21639/59290
Iteration: 21640/59290
Iteration: 21641/59290
Iteration: 21642/59290
Iteration: 21643/59290
Iteration: 21644/59290
Iteration: 21645/59290
Iteration: 21646/59290
Iteration: 21647/59290
Iteration: 21648/59290

 37%|███▋      | 21641/59290 [14:58<26:39, 23.53it/s]

Iteration: 21649/59290
Iteration: 21650/59290
Iteration: 21651/59290
Iteration: 21652/59290
Iteration: 21653/59290
Iteration: 21654/59290
Iteration: 21655/59290
Iteration: 21656/59290
Iteration: 21657/59290
Iteration: 21658/59290
Iteration: 21659/59290
Iteration: 21660/59290
Iteration: 21661/59290
Iteration: 21662/59290
Iteration: 21663/59290
Iteration: 21664/59290
Iteration: 21665/59290
Iteration: 21666/59290
Iteration: 21667/59290
Iteration: 21668/59290
Iteration: 21669/59290
Iteration: 21670/59290
Iteration: 21671/59290
Iteration: 21672/59290

 37%|███▋      | 21665/59290 [15:01<37:16, 16.83it/s]

Iteration: 21673/59290
Iteration: 21674/59290
Iteration: 21675/59290
Iteration: 21676/59290
Iteration: 21677/59290
Iteration: 21678/59290
Iteration: 21679/59290
Iteration: 21680/59290
Iteration: 21681/59290
Iteration: 21682/59290
Iteration: 21683/59290
Iteration: 21684/59290
Iteration: 21685/59290
Iteration: 21686/59290
Iteration: 21687/59290
Iteration: 21688/59290
Iteration: 21689/59290
Iteration: 21690/59290
Iteration: 21691/59290
Iteration: 21692/59290
Iteration: 21693/59290
Iteration: 21694/59290
Iteration: 21695/59290
Iteration: 21696/59290

 37%|███▋      | 21689/59290 [15:01<29:07, 21.51it/s]

Iteration: 21697/59290
Iteration: 21698/59290
Iteration: 21699/59290
Iteration: 21700/59290
Iteration: 21701/59290
Iteration: 21702/59290
Iteration: 21703/59290
Iteration: 21704/59290
Iteration: 21705/59290
Iteration: 21706/59290
Iteration: 21707/59290
Iteration: 21708/59290
Iteration: 21709/59290
Iteration: 21710/59290
Iteration: 21711/59290
Iteration: 21712/59290
Iteration: 21713/59290
Iteration: 21714/59290
Iteration: 21715/59290
Iteration: 21716/59290
Iteration: 21717/59290
Iteration: 21718/59290
Iteration: 21719/59290
Iteration: 21720/59290

 37%|███▋      | 21713/59290 [15:01<23:12, 26.98it/s]

Iteration: 21721/59290
Iteration: 21722/59290
Iteration: 21723/59290
Iteration: 21724/59290
Iteration: 21725/59290
Iteration: 21726/59290
Iteration: 21727/59290
Iteration: 21728/59290
Iteration: 21729/59290
Iteration: 21730/59290
Iteration: 21731/59290
Iteration: 21732/59290
Iteration: 21733/59290
Iteration: 21734/59290
Iteration: 21735/59290
Iteration: 21736/59290
Iteration: 21737/59290
Iteration: 21738/59290
Iteration: 21739/59290
Iteration: 21740/59290
Iteration: 21741/59290
Iteration: 21742/59290
Iteration: 21743/59290
Iteration: 21744/59290

 37%|███▋      | 21737/59290 [15:02<19:23, 32.29it/s]

Iteration: 21745/59290
Iteration: 21746/59290
Iteration: 21747/59290
Iteration: 21748/59290
Iteration: 21749/59290
Iteration: 21750/59290
Iteration: 21751/59290
Iteration: 21752/59290
Iteration: 21753/59290
Iteration: 21754/59290
Iteration: 21755/59290
Iteration: 21756/59290
Iteration: 21757/59290
Iteration: 21758/59290
Iteration: 21759/59290
Iteration: 21760/59290
Iteration: 21761/59290
Iteration: 21762/59290
Iteration: 21763/59290
Iteration: 21764/59290
Iteration: 21765/59290
Iteration: 21766/59290
Iteration: 21767/59290
Iteration: 21768/59290

 37%|███▋      | 21761/59290 [15:02<16:29, 37.94it/s]

Iteration: 21769/59290
Iteration: 21770/59290
Iteration: 21771/59290
Iteration: 21772/59290
Iteration: 21773/59290
Iteration: 21774/59290
Iteration: 21775/59290
Iteration: 21776/59290
Iteration: 21777/59290
Iteration: 21778/59290
Iteration: 21779/59290
Iteration: 21780/59290
Iteration: 21781/59290
Iteration: 21782/59290
Iteration: 21783/59290
Iteration: 21784/59290
Iteration: 21785/59290
Iteration: 21786/59290
Iteration: 21787/59290
Iteration: 21788/59290
Iteration: 21789/59290
Iteration: 21790/59290
Iteration: 21791/59290
Iteration: 21792/59290

 37%|███▋      | 21785/59290 [15:03<16:03, 38.93it/s]

Iteration: 21793/59290
Iteration: 21794/59290
Iteration: 21795/59290
Iteration: 21796/59290
Iteration: 21797/59290
Iteration: 21798/59290
Iteration: 21799/59290
Iteration: 21800/59290
Iteration: 21801/59290
Iteration: 21802/59290
Iteration: 21803/59290
Iteration: 21804/59290
Iteration: 21805/59290
Iteration: 21806/59290
Iteration: 21807/59290
Iteration: 21808/59290
Iteration: 21809/59290
Iteration: 21810/59290
Iteration: 21811/59290
Iteration: 21812/59290
Iteration: 21813/59290
Iteration: 21814/59290
Iteration: 21815/59290
Iteration: 21816/59290

 37%|███▋      | 21809/59290 [15:03<14:13, 43.93it/s]

Iteration: 21817/59290
Iteration: 21818/59290
Iteration: 21819/59290
Iteration: 21820/59290
Iteration: 21821/59290
Iteration: 21822/59290
Iteration: 21823/59290
Iteration: 21824/59290
Iteration: 21825/59290
Iteration: 21826/59290
Iteration: 21827/59290
Iteration: 21828/59290
Iteration: 21829/59290
Iteration: 21830/59290
Iteration: 21831/59290
Iteration: 21832/59290
Iteration: 21833/59290
Iteration: 21834/59290
Iteration: 21835/59290
Iteration: 21836/59290
Iteration: 21837/59290
Iteration: 21838/59290
Iteration: 21839/59290
Iteration: 21840/59290

 37%|███▋      | 21833/59290 [15:04<13:02, 47.86it/s]

Iteration: 21841/59290
Iteration: 21842/59290
Iteration: 21843/59290
Iteration: 21844/59290
Iteration: 21845/59290
Iteration: 21846/59290
Iteration: 21847/59290
Iteration: 21848/59290
Iteration: 21849/59290
Iteration: 21850/59290
Iteration: 21851/59290
Iteration: 21852/59290
Iteration: 21853/59290
Iteration: 21854/59290
Iteration: 21855/59290
Iteration: 21856/59290
Iteration: 21857/59290
Iteration: 21858/59290
Iteration: 21859/59290
Iteration: 21860/59290
Iteration: 21861/59290
Iteration: 21862/59290
Iteration: 21863/59290
Iteration: 21864/59290

 37%|███▋      | 21857/59290 [15:04<12:06, 51.51it/s]

Iteration: 21865/59290
Iteration: 21866/59290
Iteration: 21867/59290
Iteration: 21868/59290
Iteration: 21869/59290
Iteration: 21870/59290
Iteration: 21871/59290
Iteration: 21872/59290
Iteration: 21873/59290
Iteration: 21874/59290
Iteration: 21875/59290
Iteration: 21876/59290
Iteration: 21877/59290
Iteration: 21878/59290
Iteration: 21879/59290
Iteration: 21880/59290
Iteration: 21881/59290
Iteration: 21882/59290
Iteration: 21883/59290
Iteration: 21884/59290
Iteration: 21885/59290
Iteration: 21886/59290
Iteration: 21887/59290
Iteration: 21888/59290

 37%|███▋      | 21881/59290 [15:04<11:23, 54.69it/s]

Iteration: 21889/59290
Iteration: 21890/59290
Iteration: 21891/59290
Iteration: 21892/59290
Iteration: 21893/59290
Iteration: 21894/59290
Iteration: 21895/59290
Iteration: 21896/59290
Iteration: 21897/59290
Iteration: 21898/59290
Iteration: 21899/59290
Iteration: 21900/59290
Iteration: 21901/59290
Iteration: 21902/59290
Iteration: 21903/59290
Iteration: 21904/59290
Iteration: 21905/59290
Iteration: 21906/59290
Iteration: 21907/59290
Iteration: 21908/59290
Iteration: 21909/59290
Iteration: 21910/59290
Iteration: 21911/59290
Iteration: 21912/59290

 37%|███▋      | 21905/59290 [15:05<10:54, 57.12it/s]

Iteration: 21913/59290
Iteration: 21914/59290
Iteration: 21915/59290
Iteration: 21916/59290
Iteration: 21917/59290
Iteration: 21918/59290
Iteration: 21919/59290
Iteration: 21920/59290
Iteration: 21921/59290
Iteration: 21922/59290
Iteration: 21923/59290
Iteration: 21924/59290
Iteration: 21925/59290
Iteration: 21926/59290
Iteration: 21927/59290
Iteration: 21928/59290
Iteration: 21929/59290
Iteration: 21930/59290
Iteration: 21931/59290
Iteration: 21932/59290
Iteration: 21933/59290
Iteration: 21934/59290
Iteration: 21935/59290
Iteration: 21936/59290

 37%|███▋      | 21929/59290 [15:05<10:42, 58.16it/s]

Iteration: 21937/59290
Iteration: 21938/59290
Iteration: 21939/59290
Iteration: 21940/59290
Iteration: 21941/59290
Iteration: 21942/59290
Iteration: 21943/59290
Iteration: 21944/59290
Iteration: 21945/59290
Iteration: 21946/59290
Iteration: 21947/59290
Iteration: 21948/59290
Iteration: 21949/59290
Iteration: 21950/59290
Iteration: 21951/59290
Iteration: 21952/59290
Iteration: 21953/59290
Iteration: 21954/59290
Iteration: 21955/59290
Iteration: 21956/59290
Iteration: 21957/59290
Iteration: 21958/59290
Iteration: 21959/59290
Iteration: 21960/59290

 37%|███▋      | 21953/59290 [15:05<10:26, 59.58it/s]

Iteration: 21961/59290
Iteration: 21962/59290
Iteration: 21963/59290
Iteration: 21964/59290
Iteration: 21965/59290
Iteration: 21966/59290
Iteration: 21967/59290
Iteration: 21968/59290
Iteration: 21969/59290
Iteration: 21970/59290
Iteration: 21971/59290
Iteration: 21972/59290
Iteration: 21973/59290
Iteration: 21974/59290
Iteration: 21975/59290
Iteration: 21976/59290
Iteration: 21977/59290
Iteration: 21978/59290
Iteration: 21979/59290
Iteration: 21980/59290
Iteration: 21981/59290
Iteration: 21982/59290
Iteration: 21983/59290
Iteration: 21984/59290

 37%|███▋      | 21977/59290 [15:06<10:14, 60.69it/s]

Iteration: 21985/59290
Iteration: 21986/59290
Iteration: 21987/59290
Iteration: 21988/59290
Iteration: 21989/59290
Iteration: 21990/59290
Iteration: 21991/59290
Iteration: 21992/59290
Iteration: 21993/59290
Iteration: 21994/59290
Iteration: 21995/59290
Iteration: 21996/59290
Iteration: 21997/59290
Iteration: 21998/59290
Iteration: 21999/59290
Iteration: 22000/59290
Iteration: 22001/59290
Iteration: 22002/59290
Iteration: 22003/59290
Iteration: 22004/59290
Iteration: 22005/59290
Iteration: 22006/59290
Iteration: 22007/59290
Iteration: 22008/59290

 37%|███▋      | 22001/59290 [15:06<10:07, 61.40it/s]

Iteration: 22009/59290
Iteration: 22010/59290
Iteration: 22011/59290
Iteration: 22012/59290
Iteration: 22013/59290
Iteration: 22014/59290
Iteration: 22015/59290
Iteration: 22016/59290
Iteration: 22017/59290
Iteration: 22018/59290
Iteration: 22019/59290
Iteration: 22020/59290
Iteration: 22021/59290
Iteration: 22022/59290
Iteration: 22023/59290
Iteration: 22024/59290
Iteration: 22025/59290
Iteration: 22026/59290
Iteration: 22027/59290
Iteration: 22028/59290
Iteration: 22029/59290
Iteration: 22030/59290
Iteration: 22031/59290
Iteration: 22032/59290

 37%|███▋      | 22025/59290 [15:07<09:58, 62.24it/s]

Iteration: 22033/59290
Iteration: 22034/59290
Iteration: 22035/59290
Iteration: 22036/59290
Iteration: 22037/59290
Iteration: 22038/59290
Iteration: 22039/59290
Iteration: 22040/59290
Iteration: 22041/59290
Iteration: 22042/59290
Iteration: 22043/59290
Iteration: 22044/59290
Iteration: 22045/59290
Iteration: 22046/59290
Iteration: 22047/59290
Iteration: 22048/59290
Iteration: 22049/59290
Iteration: 22050/59290
Iteration: 22051/59290
Iteration: 22052/59290
Iteration: 22053/59290
Iteration: 22054/59290
Iteration: 22055/59290
Iteration: 22056/59290

 37%|███▋      | 22049/59290 [15:07<09:58, 62.21it/s]

Iteration: 22057/59290
Iteration: 22058/59290
Iteration: 22059/59290
Iteration: 22060/59290
Iteration: 22061/59290
Iteration: 22062/59290
Iteration: 22063/59290
Iteration: 22064/59290
Iteration: 22065/59290
Iteration: 22066/59290
Iteration: 22067/59290
Iteration: 22068/59290
Iteration: 22069/59290
Iteration: 22070/59290
Iteration: 22071/59290
Iteration: 22072/59290
Iteration: 22073/59290
Iteration: 22074/59290
Iteration: 22075/59290
Iteration: 22076/59290
Iteration: 22077/59290
Iteration: 22078/59290
Iteration: 22079/59290
Iteration: 22080/59290

 37%|███▋      | 22073/59290 [15:07<09:57, 62.24it/s]

Iteration: 22081/59290
Iteration: 22082/59290
Iteration: 22083/59290
Iteration: 22084/59290
Iteration: 22085/59290
Iteration: 22086/59290
Iteration: 22087/59290
Iteration: 22088/59290
Iteration: 22089/59290
Iteration: 22090/59290
Iteration: 22091/59290
Iteration: 22092/59290
Iteration: 22093/59290
Iteration: 22094/59290
Iteration: 22095/59290
Iteration: 22096/59290
Iteration: 22097/59290
Iteration: 22098/59290
Iteration: 22099/59290
Iteration: 22100/59290
Iteration: 22101/59290
Iteration: 22102/59290
Iteration: 22103/59290
Iteration: 22104/59290

 37%|███▋      | 22097/59290 [15:08<09:54, 62.58it/s]

Iteration: 22105/59290
Iteration: 22106/59290
Iteration: 22107/59290
Iteration: 22108/59290
Iteration: 22109/59290
Iteration: 22110/59290
Iteration: 22111/59290
Iteration: 22112/59290
Iteration: 22113/59290
Iteration: 22114/59290
Iteration: 22115/59290
Iteration: 22116/59290
Iteration: 22117/59290
Iteration: 22118/59290
Iteration: 22119/59290
Iteration: 22120/59290
Iteration: 22121/59290
Iteration: 22122/59290
Iteration: 22123/59290
Iteration: 22124/59290
Iteration: 22125/59290
Iteration: 22126/59290
Iteration: 22127/59290
Iteration: 22128/59290

 37%|███▋      | 22121/59290 [15:10<21:12, 29.20it/s]

Iteration: 22129/59290
Iteration: 22130/59290
Iteration: 22131/59290
Iteration: 22132/59290
Iteration: 22133/59290
Iteration: 22134/59290
Iteration: 22135/59290
Iteration: 22136/59290
Iteration: 22137/59290
Iteration: 22138/59290
Iteration: 22139/59290
Iteration: 22140/59290
Iteration: 22141/59290
Iteration: 22142/59290
Iteration: 22143/59290
Iteration: 22144/59290
Iteration: 22145/59290
Iteration: 22146/59290
Iteration: 22147/59290
Iteration: 22148/59290
Iteration: 22149/59290
Iteration: 22150/59290
Iteration: 22151/59290
Iteration: 22152/59290

 37%|███▋      | 22145/59290 [15:12<31:47, 19.48it/s]

Iteration: 22153/59290
Iteration: 22154/59290
Iteration: 22155/59290
Iteration: 22156/59290
Iteration: 22157/59290
Iteration: 22158/59290
Iteration: 22159/59290
Iteration: 22160/59290
Iteration: 22161/59290
Iteration: 22162/59290
Iteration: 22163/59290
Iteration: 22164/59290
Iteration: 22165/59290
Iteration: 22166/59290
Iteration: 22167/59290
Iteration: 22168/59290
Iteration: 22169/59290
Iteration: 22170/59290
Iteration: 22171/59290
Iteration: 22172/59290
Iteration: 22173/59290
Iteration: 22174/59290
Iteration: 22175/59290
Iteration: 22176/59290

 37%|███▋      | 22169/59290 [15:12<25:08, 24.61it/s]

Iteration: 22177/59290
Iteration: 22178/59290
Iteration: 22179/59290
Iteration: 22180/59290
Iteration: 22181/59290
Iteration: 22182/59290
Iteration: 22183/59290
Iteration: 22184/59290
Iteration: 22185/59290
Iteration: 22186/59290
Iteration: 22187/59290
Iteration: 22188/59290
Iteration: 22189/59290
Iteration: 22190/59290
Iteration: 22191/59290
Iteration: 22192/59290
Iteration: 22193/59290
Iteration: 22194/59290
Iteration: 22195/59290
Iteration: 22196/59290
Iteration: 22197/59290
Iteration: 22198/59290
Iteration: 22199/59290
Iteration: 22200/59290

 37%|███▋      | 22193/59290 [15:13<20:31, 30.12it/s]

Iteration: 22201/59290
Iteration: 22202/59290
Iteration: 22203/59290
Iteration: 22204/59290
Iteration: 22205/59290
Iteration: 22206/59290
Iteration: 22207/59290
Iteration: 22208/59290
Iteration: 22209/59290
Iteration: 22210/59290
Iteration: 22211/59290
Iteration: 22212/59290
Iteration: 22213/59290
Iteration: 22214/59290
Iteration: 22215/59290
Iteration: 22216/59290
Iteration: 22217/59290
Iteration: 22218/59290
Iteration: 22219/59290
Iteration: 22220/59290
Iteration: 22221/59290
Iteration: 22222/59290
Iteration: 22223/59290
Iteration: 22224/59290

 37%|███▋      | 22217/59290 [15:13<18:36, 33.21it/s]

Iteration: 22225/59290
Iteration: 22226/59290
Iteration: 22227/59290
Iteration: 22228/59290
Iteration: 22229/59290
Iteration: 22230/59290
Iteration: 22231/59290
Iteration: 22232/59290
Iteration: 22233/59290
Iteration: 22234/59290
Iteration: 22235/59290
Iteration: 22236/59290
Iteration: 22237/59290
Iteration: 22238/59290
Iteration: 22239/59290
Iteration: 22240/59290
Iteration: 22241/59290
Iteration: 22242/59290
Iteration: 22243/59290
Iteration: 22244/59290
Iteration: 22245/59290
Iteration: 22246/59290
Iteration: 22247/59290
Iteration: 22248/59290

 38%|███▊      | 22241/59290 [15:13<15:54, 38.81it/s]

Iteration: 22249/59290
Iteration: 22250/59290
Iteration: 22251/59290
Iteration: 22252/59290
Iteration: 22253/59290
Iteration: 22254/59290
Iteration: 22255/59290
Iteration: 22256/59290
Iteration: 22257/59290
Iteration: 22258/59290
Iteration: 22259/59290
Iteration: 22260/59290
Iteration: 22261/59290
Iteration: 22262/59290
Iteration: 22263/59290
Iteration: 22264/59290
Iteration: 22265/59290
Iteration: 22266/59290
Iteration: 22267/59290
Iteration: 22268/59290
Iteration: 22269/59290
Iteration: 22270/59290
Iteration: 22271/59290
Iteration: 22272/59290

 38%|███▊      | 22265/59290 [15:14<14:02, 43.92it/s]

Iteration: 22273/59290
Iteration: 22274/59290
Iteration: 22275/59290
Iteration: 22276/59290
Iteration: 22277/59290
Iteration: 22278/59290
Iteration: 22279/59290
Iteration: 22280/59290
Iteration: 22281/59290
Iteration: 22282/59290
Iteration: 22283/59290
Iteration: 22284/59290
Iteration: 22285/59290
Iteration: 22286/59290
Iteration: 22287/59290
Iteration: 22288/59290
Iteration: 22289/59290
Iteration: 22290/59290
Iteration: 22291/59290
Iteration: 22292/59290
Iteration: 22293/59290
Iteration: 22294/59290
Iteration: 22295/59290
Iteration: 22296/59290

 38%|███▊      | 22289/59290 [15:14<12:44, 48.42it/s]

Iteration: 22297/59290
Iteration: 22298/59290
Iteration: 22299/59290
Iteration: 22300/59290
Iteration: 22301/59290
Iteration: 22302/59290
Iteration: 22303/59290
Iteration: 22304/59290
Iteration: 22305/59290
Iteration: 22306/59290
Iteration: 22307/59290
Iteration: 22308/59290
Iteration: 22309/59290
Iteration: 22310/59290
Iteration: 22311/59290
Iteration: 22312/59290
Iteration: 22313/59290
Iteration: 22314/59290
Iteration: 22315/59290
Iteration: 22316/59290
Iteration: 22317/59290
Iteration: 22318/59290
Iteration: 22319/59290
Iteration: 22320/59290

 38%|███▊      | 22313/59290 [15:15<11:59, 51.42it/s]

Iteration: 22321/59290
Iteration: 22322/59290
Iteration: 22323/59290
Iteration: 22324/59290
Iteration: 22325/59290
Iteration: 22326/59290
Iteration: 22327/59290
Iteration: 22328/59290
Iteration: 22329/59290
Iteration: 22330/59290
Iteration: 22331/59290
Iteration: 22332/59290
Iteration: 22333/59290
Iteration: 22334/59290
Iteration: 22335/59290
Iteration: 22336/59290
Iteration: 22337/59290
Iteration: 22338/59290
Iteration: 22339/59290
Iteration: 22340/59290
Iteration: 22341/59290
Iteration: 22342/59290
Iteration: 22343/59290
Iteration: 22344/59290

 38%|███▊      | 22337/59290 [15:15<11:27, 53.77it/s]

Iteration: 22345/59290
Iteration: 22346/59290
Iteration: 22347/59290
Iteration: 22348/59290
Iteration: 22349/59290
Iteration: 22350/59290
Iteration: 22351/59290
Iteration: 22352/59290
Iteration: 22353/59290
Iteration: 22354/59290
Iteration: 22355/59290
Iteration: 22356/59290
Iteration: 22357/59290
Iteration: 22358/59290
Iteration: 22359/59290
Iteration: 22360/59290
Iteration: 22361/59290
Iteration: 22362/59290
Iteration: 22363/59290
Iteration: 22364/59290
Iteration: 22365/59290
Iteration: 22366/59290
Iteration: 22367/59290
Iteration: 22368/59290

 38%|███▊      | 22361/59290 [15:15<11:04, 55.60it/s]

Iteration: 22369/59290
Iteration: 22370/59290
Iteration: 22371/59290
Iteration: 22372/59290
Iteration: 22373/59290
Iteration: 22374/59290
Iteration: 22375/59290
Iteration: 22376/59290
Iteration: 22377/59290
Iteration: 22378/59290
Iteration: 22379/59290
Iteration: 22380/59290
Iteration: 22381/59290
Iteration: 22382/59290
Iteration: 22383/59290
Iteration: 22384/59290
Iteration: 22385/59290
Iteration: 22386/59290
Iteration: 22387/59290
Iteration: 22388/59290
Iteration: 22389/59290
Iteration: 22390/59290
Iteration: 22391/59290
Iteration: 22392/59290

 38%|███▊      | 22385/59290 [15:16<10:45, 57.16it/s]

Iteration: 22393/59290
Iteration: 22394/59290
Iteration: 22395/59290
Iteration: 22396/59290
Iteration: 22397/59290
Iteration: 22398/59290
Iteration: 22399/59290
Iteration: 22400/59290
Iteration: 22401/59290
Iteration: 22402/59290
Iteration: 22403/59290
Iteration: 22404/59290
Iteration: 22405/59290
Iteration: 22406/59290
Iteration: 22407/59290
Iteration: 22408/59290
Iteration: 22409/59290
Iteration: 22410/59290
Iteration: 22411/59290
Iteration: 22412/59290
Iteration: 22413/59290
Iteration: 22414/59290
Iteration: 22415/59290
Iteration: 22416/59290

 38%|███▊      | 22409/59290 [15:17<18:29, 33.23it/s]

Iteration: 22417/59290
Iteration: 22418/59290
Iteration: 22419/59290
Iteration: 22420/59290
Iteration: 22421/59290
Iteration: 22422/59290
Iteration: 22423/59290
Iteration: 22424/59290
Iteration: 22425/59290
Iteration: 22426/59290
Iteration: 22427/59290
Iteration: 22428/59290
Iteration: 22429/59290
Iteration: 22430/59290
Iteration: 22431/59290
Iteration: 22432/59290
Iteration: 22433/59290
Iteration: 22434/59290
Iteration: 22435/59290
Iteration: 22436/59290
Iteration: 22437/59290
Iteration: 22438/59290
Iteration: 22439/59290
Iteration: 22440/59290

 38%|███▊      | 22433/59290 [15:19<26:32, 23.15it/s]

Iteration: 22441/59290
Iteration: 22442/59290
Iteration: 22443/59290
Iteration: 22444/59290
Iteration: 22445/59290
Iteration: 22446/59290
Iteration: 22447/59290
Iteration: 22448/59290
Iteration: 22449/59290
Iteration: 22450/59290
Iteration: 22451/59290
Iteration: 22452/59290
Iteration: 22453/59290
Iteration: 22454/59290
Iteration: 22455/59290
Iteration: 22456/59290
Iteration: 22457/59290
Iteration: 22458/59290
Iteration: 22459/59290
Iteration: 22460/59290
Iteration: 22461/59290
Iteration: 22462/59290
Iteration: 22463/59290
Iteration: 22464/59290

 38%|███▊      | 22457/59290 [15:21<36:21, 16.89it/s]

Iteration: 22465/59290
Iteration: 22466/59290
Iteration: 22467/59290
Iteration: 22468/59290
Iteration: 22469/59290
Iteration: 22470/59290
Iteration: 22471/59290
Iteration: 22472/59290
Iteration: 22473/59290
Iteration: 22474/59290
Iteration: 22475/59290
Iteration: 22476/59290
Iteration: 22477/59290
Iteration: 22478/59290
Iteration: 22479/59290
Iteration: 22480/59290
Iteration: 22481/59290
Iteration: 22482/59290
Iteration: 22483/59290
Iteration: 22484/59290
Iteration: 22485/59290
Iteration: 22486/59290
Iteration: 22487/59290
Iteration: 22488/59290

 38%|███▊      | 22481/59290 [15:22<30:40, 20.00it/s]

Iteration: 22489/59290
Iteration: 22490/59290
Iteration: 22491/59290
Iteration: 22492/59290
Iteration: 22493/59290
Iteration: 22494/59290
Iteration: 22495/59290
Iteration: 22496/59290
Iteration: 22497/59290
Iteration: 22498/59290
Iteration: 22499/59290
Iteration: 22500/59290
Iteration: 22501/59290
Iteration: 22502/59290
Iteration: 22503/59290
Iteration: 22504/59290
Iteration: 22505/59290
Iteration: 22506/59290
Iteration: 22507/59290
Iteration: 22508/59290
Iteration: 22509/59290
Iteration: 22510/59290
Iteration: 22511/59290
Iteration: 22512/59290

 38%|███▊      | 22505/59290 [15:23<25:33, 23.98it/s]

Iteration: 22513/59290
Iteration: 22514/59290
Iteration: 22515/59290
Iteration: 22516/59290
Iteration: 22517/59290
Iteration: 22518/59290
Iteration: 22519/59290
Iteration: 22520/59290
Iteration: 22521/59290
Iteration: 22522/59290
Iteration: 22523/59290
Iteration: 22524/59290
Iteration: 22525/59290
Iteration: 22526/59290
Iteration: 22527/59290
Iteration: 22528/59290
Iteration: 22529/59290
Iteration: 22530/59290
Iteration: 22531/59290
Iteration: 22532/59290
Iteration: 22533/59290
Iteration: 22534/59290
Iteration: 22535/59290
Iteration: 22536/59290

 38%|███▊      | 22529/59290 [15:23<21:13, 28.87it/s]

Iteration: 22537/59290
Iteration: 22538/59290
Iteration: 22539/59290
Iteration: 22540/59290
Iteration: 22541/59290
Iteration: 22542/59290
Iteration: 22543/59290
Iteration: 22544/59290
Iteration: 22545/59290
Iteration: 22546/59290
Iteration: 22547/59290
Iteration: 22548/59290
Iteration: 22549/59290
Iteration: 22550/59290
Iteration: 22551/59290
Iteration: 22552/59290
Iteration: 22553/59290
Iteration: 22554/59290
Iteration: 22555/59290
Iteration: 22556/59290
Iteration: 22557/59290
Iteration: 22558/59290
Iteration: 22559/59290
Iteration: 22560/59290

 38%|███▊      | 22553/59290 [15:23<17:43, 34.54it/s]

Iteration: 22561/59290
Iteration: 22562/59290
Iteration: 22563/59290
Iteration: 22564/59290
Iteration: 22565/59290
Iteration: 22566/59290
Iteration: 22567/59290
Iteration: 22568/59290
Iteration: 22569/59290
Iteration: 22570/59290
Iteration: 22571/59290
Iteration: 22572/59290
Iteration: 22573/59290
Iteration: 22574/59290
Iteration: 22575/59290
Iteration: 22576/59290
Iteration: 22577/59290
Iteration: 22578/59290
Iteration: 22579/59290
Iteration: 22580/59290
Iteration: 22581/59290
Iteration: 22582/59290
Iteration: 22583/59290
Iteration: 22584/59290

 38%|███▊      | 22577/59290 [15:24<15:18, 39.97it/s]

Iteration: 22585/59290
Iteration: 22586/59290
Iteration: 22587/59290
Iteration: 22588/59290
Iteration: 22589/59290
Iteration: 22590/59290
Iteration: 22591/59290
Iteration: 22592/59290
Iteration: 22593/59290
Iteration: 22594/59290
Iteration: 22595/59290
Iteration: 22596/59290
Iteration: 22597/59290
Iteration: 22598/59290
Iteration: 22599/59290
Iteration: 22600/59290
Iteration: 22601/59290
Iteration: 22602/59290
Iteration: 22603/59290
Iteration: 22604/59290
Iteration: 22605/59290
Iteration: 22606/59290
Iteration: 22607/59290
Iteration: 22608/59290

 38%|███▊      | 22601/59290 [15:28<40:14, 15.19it/s]

Iteration: 22609/59290
Iteration: 22610/59290
Iteration: 22611/59290
Iteration: 22612/59290
Iteration: 22613/59290
Iteration: 22614/59290
Iteration: 22615/59290
Iteration: 22616/59290
Iteration: 22617/59290
Iteration: 22618/59290
Iteration: 22619/59290
Iteration: 22620/59290
Iteration: 22621/59290
Iteration: 22622/59290
Iteration: 22623/59290
Iteration: 22624/59290
Iteration: 22625/59290
Iteration: 22626/59290
Iteration: 22627/59290
Iteration: 22628/59290
Iteration: 22629/59290
Iteration: 22630/59290
Iteration: 22631/59290
Iteration: 22632/59290

 38%|███▊      | 22625/59290 [15:28<33:21, 18.32it/s]

Iteration: 22633/59290
Iteration: 22634/59290
Iteration: 22635/59290
Iteration: 22636/59290
Iteration: 22637/59290
Iteration: 22638/59290
Iteration: 22639/59290
Iteration: 22640/59290
Iteration: 22641/59290
Iteration: 22642/59290
Iteration: 22643/59290
Iteration: 22644/59290
Iteration: 22645/59290
Iteration: 22646/59290
Iteration: 22647/59290
Iteration: 22648/59290
Iteration: 22649/59290
Iteration: 22650/59290
Iteration: 22651/59290
Iteration: 22652/59290
Iteration: 22653/59290
Iteration: 22654/59290
Iteration: 22655/59290
Iteration: 22656/59290

 38%|███▊      | 22649/59290 [15:29<26:42, 22.87it/s]

Iteration: 22657/59290
Iteration: 22658/59290
Iteration: 22659/59290
Iteration: 22660/59290
Iteration: 22661/59290
Iteration: 22662/59290
Iteration: 22663/59290
Iteration: 22664/59290
Iteration: 22665/59290
Iteration: 22666/59290
Iteration: 22667/59290
Iteration: 22668/59290
Iteration: 22669/59290
Iteration: 22670/59290
Iteration: 22671/59290
Iteration: 22672/59290
Iteration: 22673/59290
Iteration: 22674/59290
Iteration: 22675/59290
Iteration: 22676/59290
Iteration: 22677/59290
Iteration: 22678/59290
Iteration: 22679/59290
Iteration: 22680/59290

 38%|███▊      | 22673/59290 [15:29<21:36, 28.25it/s]

Iteration: 22681/59290
Iteration: 22682/59290
Iteration: 22683/59290
Iteration: 22684/59290
Iteration: 22685/59290
Iteration: 22686/59290
Iteration: 22687/59290
Iteration: 22688/59290
Iteration: 22689/59290
Iteration: 22690/59290
Iteration: 22691/59290
Iteration: 22692/59290
Iteration: 22693/59290
Iteration: 22694/59290
Iteration: 22695/59290
Iteration: 22696/59290
Iteration: 22697/59290
Iteration: 22698/59290
Iteration: 22699/59290
Iteration: 22700/59290
Iteration: 22701/59290
Iteration: 22702/59290
Iteration: 22703/59290
Iteration: 22704/59290

 38%|███▊      | 22697/59290 [15:29<18:08, 33.61it/s]

Iteration: 22705/59290
Iteration: 22706/59290
Iteration: 22707/59290
Iteration: 22708/59290
Iteration: 22709/59290
Iteration: 22710/59290
Iteration: 22711/59290
Iteration: 22712/59290
Iteration: 22713/59290
Iteration: 22714/59290
Iteration: 22715/59290
Iteration: 22716/59290
Iteration: 22717/59290
Iteration: 22718/59290
Iteration: 22719/59290
Iteration: 22720/59290
Iteration: 22721/59290
Iteration: 22722/59290
Iteration: 22723/59290
Iteration: 22724/59290
Iteration: 22725/59290
Iteration: 22726/59290
Iteration: 22727/59290
Iteration: 22728/59290

 38%|███▊      | 22721/59290 [15:30<15:35, 39.10it/s]

Iteration: 22729/59290
Iteration: 22730/59290
Iteration: 22731/59290
Iteration: 22732/59290
Iteration: 22733/59290
Iteration: 22734/59290
Iteration: 22735/59290
Iteration: 22736/59290
Iteration: 22737/59290
Iteration: 22738/59290
Iteration: 22739/59290
Iteration: 22740/59290
Iteration: 22741/59290
Iteration: 22742/59290
Iteration: 22743/59290
Iteration: 22744/59290
Iteration: 22745/59290
Iteration: 22746/59290
Iteration: 22747/59290
Iteration: 22748/59290
Iteration: 22749/59290
Iteration: 22750/59290
Iteration: 22751/59290
Iteration: 22752/59290

 38%|███▊      | 22745/59290 [15:30<13:47, 44.18it/s]

Iteration: 22753/59290
Iteration: 22754/59290
Iteration: 22755/59290
Iteration: 22756/59290
Iteration: 22757/59290
Iteration: 22758/59290
Iteration: 22759/59290
Iteration: 22760/59290
Iteration: 22761/59290
Iteration: 22762/59290
Iteration: 22763/59290
Iteration: 22764/59290
Iteration: 22765/59290
Iteration: 22766/59290
Iteration: 22767/59290
Iteration: 22768/59290
Iteration: 22769/59290
Iteration: 22770/59290
Iteration: 22771/59290
Iteration: 22772/59290
Iteration: 22773/59290
Iteration: 22774/59290
Iteration: 22775/59290
Iteration: 22776/59290

 38%|███▊      | 22769/59290 [15:31<12:30, 48.64it/s]

Iteration: 22777/59290
Iteration: 22778/59290
Iteration: 22779/59290
Iteration: 22780/59290
Iteration: 22781/59290
Iteration: 22782/59290
Iteration: 22783/59290
Iteration: 22784/59290
Iteration: 22785/59290
Iteration: 22786/59290
Iteration: 22787/59290
Iteration: 22788/59290
Iteration: 22789/59290
Iteration: 22790/59290
Iteration: 22791/59290
Iteration: 22792/59290
Iteration: 22793/59290
Iteration: 22794/59290
Iteration: 22795/59290
Iteration: 22796/59290
Iteration: 22797/59290
Iteration: 22798/59290
Iteration: 22799/59290
Iteration: 22800/59290

 38%|███▊      | 22793/59290 [15:31<11:43, 51.86it/s]

Iteration: 22801/59290
Iteration: 22802/59290
Iteration: 22803/59290
Iteration: 22804/59290
Iteration: 22805/59290
Iteration: 22806/59290
Iteration: 22807/59290
Iteration: 22808/59290
Iteration: 22809/59290
Iteration: 22810/59290
Iteration: 22811/59290
Iteration: 22812/59290
Iteration: 22813/59290
Iteration: 22814/59290
Iteration: 22815/59290
Iteration: 22816/59290
Iteration: 22817/59290
Iteration: 22818/59290
Iteration: 22819/59290
Iteration: 22820/59290
Iteration: 22821/59290
Iteration: 22822/59290
Iteration: 22823/59290
Iteration: 22824/59290

 38%|███▊      | 22817/59290 [15:31<11:03, 55.01it/s]

Iteration: 22825/59290
Iteration: 22826/59290
Iteration: 22827/59290
Iteration: 22828/59290
Iteration: 22829/59290
Iteration: 22830/59290
Iteration: 22831/59290
Iteration: 22832/59290
Iteration: 22833/59290
Iteration: 22834/59290
Iteration: 22835/59290
Iteration: 22836/59290
Iteration: 22837/59290
Iteration: 22838/59290
Iteration: 22839/59290
Iteration: 22840/59290
Iteration: 22841/59290
Iteration: 22842/59290
Iteration: 22843/59290
Iteration: 22844/59290
Iteration: 22845/59290
Iteration: 22846/59290
Iteration: 22847/59290
Iteration: 22848/59290

 39%|███▊      | 22841/59290 [15:32<10:33, 57.53it/s]

Iteration: 22849/59290
Iteration: 22850/59290
Iteration: 22851/59290
Iteration: 22852/59290
Iteration: 22853/59290
Iteration: 22854/59290
Iteration: 22855/59290
Iteration: 22856/59290
Iteration: 22857/59290
Iteration: 22858/59290
Iteration: 22859/59290
Iteration: 22860/59290
Iteration: 22861/59290
Iteration: 22862/59290
Iteration: 22863/59290
Iteration: 22864/59290
Iteration: 22865/59290
Iteration: 22866/59290
Iteration: 22867/59290
Iteration: 22868/59290
Iteration: 22869/59290
Iteration: 22870/59290
Iteration: 22871/59290
Iteration: 22872/59290

 39%|███▊      | 22865/59290 [15:32<10:21, 58.57it/s]

Iteration: 22873/59290
Iteration: 22874/59290
Iteration: 22875/59290
Iteration: 22876/59290
Iteration: 22877/59290
Iteration: 22878/59290
Iteration: 22879/59290
Iteration: 22880/59290
Iteration: 22881/59290
Iteration: 22882/59290
Iteration: 22883/59290
Iteration: 22884/59290
Iteration: 22885/59290
Iteration: 22886/59290
Iteration: 22887/59290
Iteration: 22888/59290
Iteration: 22889/59290
Iteration: 22890/59290
Iteration: 22891/59290
Iteration: 22892/59290
Iteration: 22893/59290
Iteration: 22894/59290
Iteration: 22895/59290
Iteration: 22896/59290

 39%|███▊      | 22889/59290 [15:33<10:08, 59.80it/s]

Iteration: 22897/59290
Iteration: 22898/59290
Iteration: 22899/59290
Iteration: 22900/59290
Iteration: 22901/59290
Iteration: 22902/59290
Iteration: 22903/59290
Iteration: 22904/59290
Iteration: 22905/59290
Iteration: 22906/59290
Iteration: 22907/59290
Iteration: 22908/59290
Iteration: 22909/59290
Iteration: 22910/59290
Iteration: 22911/59290
Iteration: 22912/59290
Iteration: 22913/59290
Iteration: 22914/59290
Iteration: 22915/59290
Iteration: 22916/59290
Iteration: 22917/59290
Iteration: 22918/59290
Iteration: 22919/59290
Iteration: 22920/59290

 39%|███▊      | 22913/59290 [15:33<10:07, 59.85it/s]

Iteration: 22921/59290
Iteration: 22922/59290
Iteration: 22923/59290
Iteration: 22924/59290
Iteration: 22925/59290
Iteration: 22926/59290
Iteration: 22927/59290
Iteration: 22928/59290
Iteration: 22929/59290
Iteration: 22930/59290
Iteration: 22931/59290
Iteration: 22932/59290
Iteration: 22933/59290
Iteration: 22934/59290
Iteration: 22935/59290
Iteration: 22936/59290
Iteration: 22937/59290
Iteration: 22938/59290
Iteration: 22939/59290
Iteration: 22940/59290
Iteration: 22941/59290
Iteration: 22942/59290
Iteration: 22943/59290
Iteration: 22944/59290

 39%|███▊      | 22937/59290 [15:33<09:57, 60.84it/s]

Iteration: 22945/59290
Iteration: 22946/59290
Iteration: 22947/59290
Iteration: 22948/59290
Iteration: 22949/59290
Iteration: 22950/59290
Iteration: 22951/59290
Iteration: 22952/59290
Iteration: 22953/59290
Iteration: 22954/59290
Iteration: 22955/59290
Iteration: 22956/59290
Iteration: 22957/59290
Iteration: 22958/59290
Iteration: 22959/59290
Iteration: 22960/59290
Iteration: 22961/59290
Iteration: 22962/59290
Iteration: 22963/59290
Iteration: 22964/59290
Iteration: 22965/59290
Iteration: 22966/59290
Iteration: 22967/59290
Iteration: 22968/59290

 39%|███▊      | 22961/59290 [15:35<20:23, 29.68it/s]

Iteration: 22969/59290
Iteration: 22970/59290
Iteration: 22971/59290
Iteration: 22972/59290
Iteration: 22973/59290
Iteration: 22974/59290
Iteration: 22975/59290
Iteration: 22976/59290
Iteration: 22977/59290
Iteration: 22978/59290
Iteration: 22979/59290
Iteration: 22980/59290
Iteration: 22981/59290
Iteration: 22982/59290
Iteration: 22983/59290
Iteration: 22984/59290
Iteration: 22985/59290
Iteration: 22986/59290
Iteration: 22987/59290
Iteration: 22988/59290
Iteration: 22989/59290
Iteration: 22990/59290
Iteration: 22991/59290
Iteration: 22992/59290

 39%|███▉      | 22985/59290 [15:37<31:49, 19.01it/s]

Iteration: 22993/59290
Iteration: 22994/59290
Iteration: 22995/59290
Iteration: 22996/59290
Iteration: 22997/59290
Iteration: 22998/59290
Iteration: 22999/59290
Iteration: 23000/59290
Iteration: 23001/59290
Iteration: 23002/59290
Iteration: 23003/59290
Iteration: 23004/59290
Iteration: 23005/59290
Iteration: 23006/59290
Iteration: 23007/59290
Iteration: 23008/59290
Iteration: 23009/59290
Iteration: 23010/59290
Iteration: 23011/59290
Iteration: 23012/59290
Iteration: 23013/59290
Iteration: 23014/59290
Iteration: 23015/59290
Iteration: 23016/59290

 39%|███▉      | 23009/59290 [15:38<25:11, 24.01it/s]

Iteration: 23017/59290
Iteration: 23018/59290
Iteration: 23019/59290
Iteration: 23020/59290
Iteration: 23021/59290
Iteration: 23022/59290
Iteration: 23023/59290
Iteration: 23024/59290
Iteration: 23025/59290
Iteration: 23026/59290
Iteration: 23027/59290
Iteration: 23028/59290
Iteration: 23029/59290
Iteration: 23030/59290
Iteration: 23031/59290
Iteration: 23032/59290
Iteration: 23033/59290
Iteration: 23034/59290
Iteration: 23035/59290
Iteration: 23036/59290
Iteration: 23037/59290
Iteration: 23038/59290
Iteration: 23039/59290
Iteration: 23040/59290

 39%|███▉      | 23033/59290 [15:38<20:37, 29.30it/s]

Iteration: 23041/59290
Iteration: 23042/59290
Iteration: 23043/59290
Iteration: 23044/59290
Iteration: 23045/59290
Iteration: 23046/59290
Iteration: 23047/59290
Iteration: 23048/59290
Iteration: 23049/59290
Iteration: 23050/59290
Iteration: 23051/59290
Iteration: 23052/59290
Iteration: 23053/59290
Iteration: 23054/59290
Iteration: 23055/59290
Iteration: 23056/59290
Iteration: 23057/59290
Iteration: 23058/59290
Iteration: 23059/59290
Iteration: 23060/59290
Iteration: 23061/59290
Iteration: 23062/59290
Iteration: 23063/59290
Iteration: 23064/59290

 39%|███▉      | 23057/59290 [15:39<18:08, 33.30it/s]

Iteration: 23065/59290
Iteration: 23066/59290
Iteration: 23067/59290
Iteration: 23068/59290
Iteration: 23069/59290
Iteration: 23070/59290
Iteration: 23071/59290
Iteration: 23072/59290
Iteration: 23073/59290
Iteration: 23074/59290
Iteration: 23075/59290
Iteration: 23076/59290
Iteration: 23077/59290
Iteration: 23078/59290
Iteration: 23079/59290
Iteration: 23080/59290
Iteration: 23081/59290
Iteration: 23082/59290
Iteration: 23083/59290
Iteration: 23084/59290
Iteration: 23085/59290
Iteration: 23086/59290
Iteration: 23087/59290
Iteration: 23088/59290

 39%|███▉      | 23081/59290 [16:11<4:17:59,  2.34it/s]

Iteration: 23089/59290
Iteration: 23090/59290
Iteration: 23091/59290
Iteration: 23092/59290
Iteration: 23093/59290
Iteration: 23094/59290
Iteration: 23095/59290
Iteration: 23096/59290
Iteration: 23097/59290
Iteration: 23098/59290
Iteration: 23099/59290
Iteration: 23100/59290
Iteration: 23101/59290
Iteration: 23102/59290
Iteration: 23103/59290
Iteration: 23104/59290
Iteration: 23105/59290
Iteration: 23106/59290
Iteration: 23107/59290
Iteration: 23108/59290
Iteration: 23109/59290
Iteration: 23110/59290
Iteration: 23111/59290
Iteration: 23112/59290

 39%|███▉      | 23105/59290 [16:12<3:03:40,  3.28it/s]

Iteration: 23113/59290
Iteration: 23114/59290
Iteration: 23115/59290
Iteration: 23116/59290
Iteration: 23117/59290
Iteration: 23118/59290
Iteration: 23119/59290
Iteration: 23120/59290
Iteration: 23121/59290
Iteration: 23122/59290
Iteration: 23123/59290
Iteration: 23124/59290
Iteration: 23125/59290
Iteration: 23126/59290
Iteration: 23127/59290
Iteration: 23128/59290
Iteration: 23129/59290
Iteration: 23130/59290
Iteration: 23131/59290
Iteration: 23132/59290
Iteration: 23133/59290
Iteration: 23134/59290
Iteration: 23135/59290
Iteration: 23136/59290

 39%|███▉      | 23129/59290 [16:12<2:11:24,  4.59it/s]

Iteration: 23137/59290
Iteration: 23138/59290
Iteration: 23139/59290
Iteration: 23140/59290
Iteration: 23141/59290
Iteration: 23142/59290
Iteration: 23143/59290
Iteration: 23144/59290
Iteration: 23145/59290
Iteration: 23146/59290
Iteration: 23147/59290
Iteration: 23148/59290
Iteration: 23149/59290
Iteration: 23150/59290
Iteration: 23151/59290
Iteration: 23152/59290
Iteration: 23153/59290
Iteration: 23154/59290
Iteration: 23155/59290
Iteration: 23156/59290
Iteration: 23157/59290
Iteration: 23158/59290
Iteration: 23159/59290
Iteration: 23160/59290

 39%|███▉      | 23153/59290 [16:12<1:34:46,  6.36it/s]

Iteration: 23161/59290
Iteration: 23162/59290
Iteration: 23163/59290
Iteration: 23164/59290
Iteration: 23165/59290
Iteration: 23166/59290
Iteration: 23167/59290
Iteration: 23168/59290
Iteration: 23169/59290
Iteration: 23170/59290
Iteration: 23171/59290
Iteration: 23172/59290
Iteration: 23173/59290
Iteration: 23174/59290
Iteration: 23175/59290
Iteration: 23176/59290
Iteration: 23177/59290
Iteration: 23178/59290
Iteration: 23179/59290
Iteration: 23180/59290
Iteration: 23181/59290
Iteration: 23182/59290
Iteration: 23183/59290
Iteration: 23184/59290

 39%|███▉      | 23177/59290 [16:13<1:09:10,  8.70it/s]

Iteration: 23185/59290
Iteration: 23186/59290
Iteration: 23187/59290
Iteration: 23188/59290
Iteration: 23189/59290
Iteration: 23190/59290
Iteration: 23191/59290
Iteration: 23192/59290
Iteration: 23193/59290
Iteration: 23194/59290
Iteration: 23195/59290
Iteration: 23196/59290
Iteration: 23197/59290
Iteration: 23198/59290
Iteration: 23199/59290
Iteration: 23200/59290
Iteration: 23201/59290
Iteration: 23202/59290
Iteration: 23203/59290
Iteration: 23204/59290
Iteration: 23205/59290
Iteration: 23206/59290
Iteration: 23207/59290
Iteration: 23208/59290

 39%|███▉      | 23201/59290 [16:13<51:16, 11.73it/s]

Iteration: 23209/59290
Iteration: 23210/59290
Iteration: 23211/59290
Iteration: 23212/59290
Iteration: 23213/59290
Iteration: 23214/59290
Iteration: 23215/59290
Iteration: 23216/59290
Iteration: 23217/59290
Iteration: 23218/59290
Iteration: 23219/59290
Iteration: 23220/59290
Iteration: 23221/59290
Iteration: 23222/59290
Iteration: 23223/59290
Iteration: 23224/59290
Iteration: 23225/59290
Iteration: 23226/59290
Iteration: 23227/59290
Iteration: 23228/59290
Iteration: 23229/59290
Iteration: 23230/59290
Iteration: 23231/59290
Iteration: 23232/59290

 39%|███▉      | 23225/59290 [16:14<38:47, 15.50it/s]

Iteration: 23233/59290
Iteration: 23234/59290
Iteration: 23235/59290
Iteration: 23236/59290
Iteration: 23237/59290
Iteration: 23238/59290
Iteration: 23239/59290
Iteration: 23240/59290
Iteration: 23241/59290
Iteration: 23242/59290
Iteration: 23243/59290
Iteration: 23244/59290
Iteration: 23245/59290
Iteration: 23246/59290
Iteration: 23247/59290
Iteration: 23248/59290
Iteration: 23249/59290
Iteration: 23250/59290
Iteration: 23251/59290
Iteration: 23252/59290
Iteration: 23253/59290
Iteration: 23254/59290
Iteration: 23255/59290
Iteration: 23256/59290

 39%|███▉      | 23249/59290 [16:14<30:01, 20.01it/s]

Iteration: 23257/59290
Iteration: 23258/59290
Iteration: 23259/59290
Iteration: 23260/59290
Iteration: 23261/59290
Iteration: 23262/59290
Iteration: 23263/59290
Iteration: 23264/59290
Iteration: 23265/59290
Iteration: 23266/59290
Iteration: 23267/59290
Iteration: 23268/59290
Iteration: 23269/59290
Iteration: 23270/59290
Iteration: 23271/59290
Iteration: 23272/59290
Iteration: 23273/59290
Iteration: 23274/59290
Iteration: 23275/59290
Iteration: 23276/59290
Iteration: 23277/59290
Iteration: 23278/59290
Iteration: 23279/59290
Iteration: 23280/59290

 39%|███▉      | 23273/59290 [16:14<23:50, 25.17it/s]

Iteration: 23281/59290
Iteration: 23282/59290
Iteration: 23283/59290
Iteration: 23284/59290
Iteration: 23285/59290
Iteration: 23286/59290
Iteration: 23287/59290
Iteration: 23288/59290
Iteration: 23289/59290
Iteration: 23290/59290
Iteration: 23291/59290
Iteration: 23292/59290
Iteration: 23293/59290
Iteration: 23294/59290
Iteration: 23295/59290
Iteration: 23296/59290
Iteration: 23297/59290
Iteration: 23298/59290
Iteration: 23299/59290
Iteration: 23300/59290
Iteration: 23301/59290
Iteration: 23302/59290
Iteration: 23303/59290
Iteration: 23304/59290

 39%|███▉      | 23297/59290 [16:15<19:38, 30.53it/s]

Iteration: 23305/59290
Iteration: 23306/59290
Iteration: 23307/59290
Iteration: 23308/59290
Iteration: 23309/59290
Iteration: 23310/59290
Iteration: 23311/59290
Iteration: 23312/59290
Iteration: 23313/59290
Iteration: 23314/59290
Iteration: 23315/59290
Iteration: 23316/59290
Iteration: 23317/59290
Iteration: 23318/59290
Iteration: 23319/59290
Iteration: 23320/59290
Iteration: 23321/59290
Iteration: 23322/59290
Iteration: 23323/59290
Iteration: 23324/59290
Iteration: 23325/59290
Iteration: 23326/59290
Iteration: 23327/59290
Iteration: 23328/59290

 39%|███▉      | 23321/59290 [16:15<16:33, 36.20it/s]

Iteration: 23329/59290
Iteration: 23330/59290
Iteration: 23331/59290
Iteration: 23332/59290
Iteration: 23333/59290
Iteration: 23334/59290
Iteration: 23335/59290
Iteration: 23336/59290
Iteration: 23337/59290
Iteration: 23338/59290
Iteration: 23339/59290
Iteration: 23340/59290
Iteration: 23341/59290
Iteration: 23342/59290
Iteration: 23343/59290
Iteration: 23344/59290
Iteration: 23345/59290
Iteration: 23346/59290
Iteration: 23347/59290
Iteration: 23348/59290
Iteration: 23349/59290
Iteration: 23350/59290
Iteration: 23351/59290
Iteration: 23352/59290

 39%|███▉      | 23345/59290 [16:17<23:38, 25.33it/s]

Iteration: 23353/59290
Iteration: 23354/59290
Iteration: 23355/59290
Iteration: 23356/59290
Iteration: 23357/59290
Iteration: 23358/59290
Iteration: 23359/59290
Iteration: 23360/59290
Iteration: 23361/59290
Iteration: 23362/59290
Iteration: 23363/59290
Iteration: 23364/59290
Iteration: 23365/59290
Iteration: 23366/59290
Iteration: 23367/59290
Iteration: 23368/59290
Iteration: 23369/59290
Iteration: 23370/59290
Iteration: 23371/59290
Iteration: 23372/59290
Iteration: 23373/59290
Iteration: 23374/59290
Iteration: 23375/59290
Iteration: 23376/59290

 39%|███▉      | 23369/59290 [16:19<33:18, 17.97it/s]

Iteration: 23377/59290
Iteration: 23378/59290
Iteration: 23379/59290
Iteration: 23380/59290
Iteration: 23381/59290
Iteration: 23382/59290
Iteration: 23383/59290
Iteration: 23384/59290
Iteration: 23385/59290
Iteration: 23386/59290
Iteration: 23387/59290
Iteration: 23388/59290
Iteration: 23389/59290
Iteration: 23390/59290
Iteration: 23391/59290
Iteration: 23392/59290
Iteration: 23393/59290
Iteration: 23394/59290
Iteration: 23395/59290
Iteration: 23396/59290
Iteration: 23397/59290
Iteration: 23398/59290
Iteration: 23399/59290
Iteration: 23400/59290

 39%|███▉      | 23393/59290 [16:20<29:32, 20.25it/s]

Iteration: 23401/59290
Iteration: 23402/59290
Iteration: 23403/59290
Iteration: 23404/59290
Iteration: 23405/59290
Iteration: 23406/59290
Iteration: 23407/59290
Iteration: 23408/59290
Iteration: 23409/59290
Iteration: 23410/59290
Iteration: 23411/59290
Iteration: 23412/59290
Iteration: 23413/59290
Iteration: 23414/59290
Iteration: 23415/59290
Iteration: 23416/59290
Iteration: 23417/59290
Iteration: 23418/59290
Iteration: 23419/59290
Iteration: 23420/59290
Iteration: 23421/59290
Iteration: 23422/59290
Iteration: 23423/59290
Iteration: 23424/59290

 39%|███▉      | 23417/59290 [16:20<23:31, 25.42it/s]

Iteration: 23425/59290
Iteration: 23426/59290
Iteration: 23427/59290
Iteration: 23428/59290
Iteration: 23429/59290
Iteration: 23430/59290
Iteration: 23431/59290
Iteration: 23432/59290
Iteration: 23433/59290
Iteration: 23434/59290
Iteration: 23435/59290
Iteration: 23436/59290
Iteration: 23437/59290
Iteration: 23438/59290
Iteration: 23439/59290
Iteration: 23440/59290
Iteration: 23441/59290
Iteration: 23442/59290
Iteration: 23443/59290
Iteration: 23444/59290
Iteration: 23445/59290
Iteration: 23446/59290
Iteration: 23447/59290
Iteration: 23448/59290

 40%|███▉      | 23441/59290 [16:21<19:14, 31.05it/s]

Iteration: 23449/59290
Iteration: 23450/59290
Iteration: 23451/59290
Iteration: 23452/59290
Iteration: 23453/59290
Iteration: 23454/59290
Iteration: 23455/59290
Iteration: 23456/59290
Iteration: 23457/59290
Iteration: 23458/59290
Iteration: 23459/59290
Iteration: 23460/59290
Iteration: 23461/59290
Iteration: 23462/59290
Iteration: 23463/59290
Iteration: 23464/59290
Iteration: 23465/59290
Iteration: 23466/59290
Iteration: 23467/59290
Iteration: 23468/59290
Iteration: 23469/59290
Iteration: 23470/59290
Iteration: 23471/59290
Iteration: 23472/59290

 40%|███▉      | 23465/59290 [16:21<16:14, 36.76it/s]

Iteration: 23473/59290
Iteration: 23474/59290
Iteration: 23475/59290
Iteration: 23476/59290
Iteration: 23477/59290
Iteration: 23478/59290
Iteration: 23479/59290
Iteration: 23480/59290
Iteration: 23481/59290
Iteration: 23482/59290
Iteration: 23483/59290
Iteration: 23484/59290
Iteration: 23485/59290
Iteration: 23486/59290
Iteration: 23487/59290
Iteration: 23488/59290
Iteration: 23489/59290
Iteration: 23490/59290
Iteration: 23491/59290
Iteration: 23492/59290
Iteration: 23493/59290
Iteration: 23494/59290
Iteration: 23495/59290
Iteration: 23496/59290

 40%|███▉      | 23489/59290 [16:25<41:17, 14.45it/s]

Iteration: 23497/59290
Iteration: 23498/59290
Iteration: 23499/59290
Iteration: 23500/59290
Iteration: 23501/59290
Iteration: 23502/59290
Iteration: 23503/59290
Iteration: 23504/59290
Iteration: 23505/59290
Iteration: 23506/59290
Iteration: 23507/59290
Iteration: 23508/59290
Iteration: 23509/59290
Iteration: 23510/59290
Iteration: 23511/59290
Iteration: 23512/59290
Iteration: 23513/59290
Iteration: 23514/59290
Iteration: 23515/59290
Iteration: 23516/59290
Iteration: 23517/59290
Iteration: 23518/59290
Iteration: 23519/59290
Iteration: 23520/59290

 40%|███▉      | 23513/59290 [16:25<31:42, 18.81it/s]

Iteration: 23521/59290
Iteration: 23522/59290
Iteration: 23523/59290
Iteration: 23524/59290
Iteration: 23525/59290
Iteration: 23526/59290
Iteration: 23527/59290
Iteration: 23528/59290
Iteration: 23529/59290
Iteration: 23530/59290
Iteration: 23531/59290
Iteration: 23532/59290
Iteration: 23533/59290
Iteration: 23534/59290
Iteration: 23535/59290
Iteration: 23536/59290
Iteration: 23537/59290
Iteration: 23538/59290
Iteration: 23539/59290
Iteration: 23540/59290
Iteration: 23541/59290
Iteration: 23542/59290
Iteration: 23543/59290
Iteration: 23544/59290

 40%|███▉      | 23537/59290 [16:26<24:58, 23.86it/s]

Iteration: 23545/59290
Iteration: 23546/59290
Iteration: 23547/59290
Iteration: 23548/59290
Iteration: 23549/59290
Iteration: 23550/59290
Iteration: 23551/59290
Iteration: 23552/59290
Iteration: 23553/59290
Iteration: 23554/59290
Iteration: 23555/59290
Iteration: 23556/59290
Iteration: 23557/59290
Iteration: 23558/59290
Iteration: 23559/59290
Iteration: 23560/59290
Iteration: 23561/59290
Iteration: 23562/59290
Iteration: 23563/59290
Iteration: 23564/59290
Iteration: 23565/59290
Iteration: 23566/59290
Iteration: 23567/59290
Iteration: 23568/59290

 40%|███▉      | 23561/59290 [16:26<20:18, 29.33it/s]

Iteration: 23569/59290
Iteration: 23570/59290
Iteration: 23571/59290
Iteration: 23572/59290
Iteration: 23573/59290
Iteration: 23574/59290
Iteration: 23575/59290
Iteration: 23576/59290
Iteration: 23577/59290
Iteration: 23578/59290
Iteration: 23579/59290
Iteration: 23580/59290
Iteration: 23581/59290
Iteration: 23582/59290
Iteration: 23583/59290
Iteration: 23584/59290
Iteration: 23585/59290
Iteration: 23586/59290
Iteration: 23587/59290
Iteration: 23588/59290
Iteration: 23589/59290
Iteration: 23590/59290
Iteration: 23591/59290
Iteration: 23592/59290

 40%|███▉      | 23585/59290 [16:27<19:21, 30.73it/s]

Iteration: 23593/59290
Iteration: 23594/59290
Iteration: 23595/59290
Iteration: 23596/59290
Iteration: 23597/59290
Iteration: 23598/59290
Iteration: 23599/59290
Iteration: 23600/59290
Iteration: 23601/59290
Iteration: 23602/59290
Iteration: 23603/59290
Iteration: 23604/59290
Iteration: 23605/59290
Iteration: 23606/59290
Iteration: 23607/59290
Iteration: 23608/59290
Iteration: 23609/59290
Iteration: 23610/59290
Iteration: 23611/59290
Iteration: 23612/59290
Iteration: 23613/59290
Iteration: 23614/59290
Iteration: 23615/59290
Iteration: 23616/59290

 40%|███▉      | 23609/59290 [16:27<16:20, 36.38it/s]

Iteration: 23617/59290
Iteration: 23618/59290
Iteration: 23619/59290
Iteration: 23620/59290
Iteration: 23621/59290
Iteration: 23622/59290
Iteration: 23623/59290
Iteration: 23624/59290
Iteration: 23625/59290
Iteration: 23626/59290
Iteration: 23627/59290
Iteration: 23628/59290
Iteration: 23629/59290
Iteration: 23630/59290
Iteration: 23631/59290
Iteration: 23632/59290
Iteration: 23633/59290
Iteration: 23634/59290
Iteration: 23635/59290
Iteration: 23636/59290
Iteration: 23637/59290
Iteration: 23638/59290
Iteration: 23639/59290
Iteration: 23640/59290

 40%|███▉      | 23633/59290 [16:28<14:15, 41.70it/s]

Iteration: 23641/59290
Iteration: 23642/59290
Iteration: 23643/59290
Iteration: 23644/59290
Iteration: 23645/59290
Iteration: 23646/59290
Iteration: 23647/59290
Iteration: 23648/59290
Iteration: 23649/59290
Iteration: 23650/59290
Iteration: 23651/59290
Iteration: 23652/59290
Iteration: 23653/59290
Iteration: 23654/59290
Iteration: 23655/59290
Iteration: 23656/59290
Iteration: 23657/59290
Iteration: 23658/59290
Iteration: 23659/59290
Iteration: 23660/59290
Iteration: 23661/59290
Iteration: 23662/59290
Iteration: 23663/59290
Iteration: 23664/59290

 40%|███▉      | 23657/59290 [16:28<12:47, 46.41it/s]

Iteration: 23665/59290
Iteration: 23666/59290
Iteration: 23667/59290
Iteration: 23668/59290
Iteration: 23669/59290
Iteration: 23670/59290
Iteration: 23671/59290
Iteration: 23672/59290
Iteration: 23673/59290
Iteration: 23674/59290
Iteration: 23675/59290
Iteration: 23676/59290
Iteration: 23677/59290
Iteration: 23678/59290
Iteration: 23679/59290
Iteration: 23680/59290
Iteration: 23681/59290
Iteration: 23682/59290
Iteration: 23683/59290
Iteration: 23684/59290
Iteration: 23685/59290
Iteration: 23686/59290
Iteration: 23687/59290
Iteration: 23688/59290

 40%|███▉      | 23681/59290 [16:28<11:58, 49.55it/s]

Iteration: 23689/59290
Iteration: 23690/59290
Iteration: 23691/59290
Iteration: 23692/59290
Iteration: 23693/59290
Iteration: 23694/59290
Iteration: 23695/59290
Iteration: 23696/59290
Iteration: 23697/59290
Iteration: 23698/59290
Iteration: 23699/59290
Iteration: 23700/59290
Iteration: 23701/59290
Iteration: 23702/59290
Iteration: 23703/59290
Iteration: 23704/59290
Iteration: 23705/59290
Iteration: 23706/59290
Iteration: 23707/59290
Iteration: 23708/59290
Iteration: 23709/59290
Iteration: 23710/59290
Iteration: 23711/59290
Iteration: 23712/59290

 40%|███▉      | 23705/59290 [16:29<11:12, 52.94it/s]

Iteration: 23713/59290
Iteration: 23714/59290
Iteration: 23715/59290
Iteration: 23716/59290
Iteration: 23717/59290
Iteration: 23718/59290
Iteration: 23719/59290
Iteration: 23720/59290
Iteration: 23721/59290
Iteration: 23722/59290
Iteration: 23723/59290
Iteration: 23724/59290
Iteration: 23725/59290
Iteration: 23726/59290
Iteration: 23727/59290
Iteration: 23728/59290
Iteration: 23729/59290
Iteration: 23730/59290
Iteration: 23731/59290
Iteration: 23732/59290
Iteration: 23733/59290
Iteration: 23734/59290
Iteration: 23735/59290
Iteration: 23736/59290

 40%|████      | 23729/59290 [16:29<10:37, 55.81it/s]

Iteration: 23737/59290
Iteration: 23738/59290
Iteration: 23739/59290
Iteration: 23740/59290
Iteration: 23741/59290
Iteration: 23742/59290
Iteration: 23743/59290
Iteration: 23744/59290
Iteration: 23745/59290
Iteration: 23746/59290
Iteration: 23747/59290
Iteration: 23748/59290
Iteration: 23749/59290
Iteration: 23750/59290
Iteration: 23751/59290
Iteration: 23752/59290
Iteration: 23753/59290
Iteration: 23754/59290
Iteration: 23755/59290
Iteration: 23756/59290
Iteration: 23757/59290
Iteration: 23758/59290
Iteration: 23759/59290
Iteration: 23760/59290

 40%|████      | 23753/59290 [16:29<10:16, 57.68it/s]

Iteration: 23761/59290
Iteration: 23762/59290
Iteration: 23763/59290
Iteration: 23764/59290
Iteration: 23765/59290
Iteration: 23766/59290
Iteration: 23767/59290
Iteration: 23768/59290
Iteration: 23769/59290
Iteration: 23770/59290
Iteration: 23771/59290
Iteration: 23772/59290
Iteration: 23773/59290
Iteration: 23774/59290
Iteration: 23775/59290
Iteration: 23776/59290
Iteration: 23777/59290
Iteration: 23778/59290
Iteration: 23779/59290
Iteration: 23780/59290
Iteration: 23781/59290
Iteration: 23782/59290
Iteration: 23783/59290
Iteration: 23784/59290

 40%|████      | 23777/59290 [16:30<09:58, 59.38it/s]

Iteration: 23785/59290
Iteration: 23786/59290
Iteration: 23787/59290
Iteration: 23788/59290
Iteration: 23789/59290
Iteration: 23790/59290
Iteration: 23791/59290
Iteration: 23792/59290
Iteration: 23793/59290
Iteration: 23794/59290
Iteration: 23795/59290
Iteration: 23796/59290
Iteration: 23797/59290
Iteration: 23798/59290
Iteration: 23799/59290
Iteration: 23800/59290
Iteration: 23801/59290
Iteration: 23802/59290
Iteration: 23803/59290
Iteration: 23804/59290
Iteration: 23805/59290
Iteration: 23806/59290
Iteration: 23807/59290
Iteration: 23808/59290

 40%|████      | 23801/59290 [16:30<09:44, 60.75it/s]

Iteration: 23809/59290
Iteration: 23810/59290
Iteration: 23811/59290
Iteration: 23812/59290
Iteration: 23813/59290
Iteration: 23814/59290
Iteration: 23815/59290
Iteration: 23816/59290
Iteration: 23817/59290
Iteration: 23818/59290
Iteration: 23819/59290
Iteration: 23820/59290
Iteration: 23821/59290
Iteration: 23822/59290
Iteration: 23823/59290
Iteration: 23824/59290
Iteration: 23825/59290
Iteration: 23826/59290
Iteration: 23827/59290
Iteration: 23828/59290
Iteration: 23829/59290
Iteration: 23830/59290
Iteration: 23831/59290
Iteration: 23832/59290

 40%|████      | 23825/59290 [16:31<09:39, 61.16it/s]

Iteration: 23833/59290
Iteration: 23834/59290
Iteration: 23835/59290
Iteration: 23836/59290
Iteration: 23837/59290
Iteration: 23838/59290
Iteration: 23839/59290
Iteration: 23840/59290
Iteration: 23841/59290
Iteration: 23842/59290
Iteration: 23843/59290
Iteration: 23844/59290
Iteration: 23845/59290
Iteration: 23846/59290
Iteration: 23847/59290
Iteration: 23848/59290
Iteration: 23849/59290
Iteration: 23850/59290
Iteration: 23851/59290
Iteration: 23852/59290
Iteration: 23853/59290
Iteration: 23854/59290
Iteration: 23855/59290
Iteration: 23856/59290

 40%|████      | 23849/59290 [16:31<09:37, 61.39it/s]

Iteration: 23857/59290
Iteration: 23858/59290
Iteration: 23859/59290
Iteration: 23860/59290
Iteration: 23861/59290
Iteration: 23862/59290
Iteration: 23863/59290
Iteration: 23864/59290
Iteration: 23865/59290
Iteration: 23866/59290
Iteration: 23867/59290
Iteration: 23868/59290
Iteration: 23869/59290
Iteration: 23870/59290
Iteration: 23871/59290
Iteration: 23872/59290
Iteration: 23873/59290
Iteration: 23874/59290
Iteration: 23875/59290
Iteration: 23876/59290
Iteration: 23877/59290
Iteration: 23878/59290
Iteration: 23879/59290
Iteration: 23880/59290

 40%|████      | 23873/59290 [16:31<09:49, 60.06it/s]

Iteration: 23881/59290
Iteration: 23882/59290
Iteration: 23883/59290
Iteration: 23884/59290
Iteration: 23885/59290
Iteration: 23886/59290
Iteration: 23887/59290
Iteration: 23888/59290
Iteration: 23889/59290
Iteration: 23890/59290
Iteration: 23891/59290
Iteration: 23892/59290
Iteration: 23893/59290
Iteration: 23894/59290
Iteration: 23895/59290
Iteration: 23896/59290
Iteration: 23897/59290
Iteration: 23898/59290
Iteration: 23899/59290
Iteration: 23900/59290
Iteration: 23901/59290
Iteration: 23902/59290
Iteration: 23903/59290
Iteration: 23904/59290

 40%|████      | 23897/59290 [16:32<09:40, 60.98it/s]

Iteration: 23905/59290
Iteration: 23906/59290
Iteration: 23907/59290
Iteration: 23908/59290
Iteration: 23909/59290
Iteration: 23910/59290
Iteration: 23911/59290
Iteration: 23912/59290
Iteration: 23913/59290
Iteration: 23914/59290
Iteration: 23915/59290
Iteration: 23916/59290
Iteration: 23917/59290
Iteration: 23918/59290
Iteration: 23919/59290
Iteration: 23920/59290
Iteration: 23921/59290
Iteration: 23922/59290
Iteration: 23923/59290
Iteration: 23924/59290
Iteration: 23925/59290
Iteration: 23926/59290
Iteration: 23927/59290
Iteration: 23928/59290

 40%|████      | 23921/59290 [16:32<09:29, 62.07it/s]

Iteration: 23929/59290
Iteration: 23930/59290
Iteration: 23931/59290
Iteration: 23932/59290
Iteration: 23933/59290
Iteration: 23934/59290
Iteration: 23935/59290
Iteration: 23936/59290
Iteration: 23937/59290
Iteration: 23938/59290
Iteration: 23939/59290
Iteration: 23940/59290
Iteration: 23941/59290
Iteration: 23942/59290
Iteration: 23943/59290
Iteration: 23944/59290
Iteration: 23945/59290
Iteration: 23946/59290
Iteration: 23947/59290
Iteration: 23948/59290
Iteration: 23949/59290
Iteration: 23950/59290
Iteration: 23951/59290
Iteration: 23952/59290

 40%|████      | 23945/59290 [16:33<09:27, 62.25it/s]

Iteration: 23953/59290
Iteration: 23954/59290
Iteration: 23955/59290
Iteration: 23956/59290
Iteration: 23957/59290
Iteration: 23958/59290
Iteration: 23959/59290
Iteration: 23960/59290
Iteration: 23961/59290
Iteration: 23962/59290
Iteration: 23963/59290
Iteration: 23964/59290
Iteration: 23965/59290
Iteration: 23966/59290
Iteration: 23967/59290
Iteration: 23968/59290
Iteration: 23969/59290
Iteration: 23970/59290
Iteration: 23971/59290
Iteration: 23972/59290
Iteration: 23973/59290
Iteration: 23974/59290
Iteration: 23975/59290
Iteration: 23976/59290

 40%|████      | 23969/59290 [16:37<36:01, 16.34it/s]

Iteration: 23977/59290
Iteration: 23978/59290
Iteration: 23979/59290
Iteration: 23980/59290
Iteration: 23981/59290
Iteration: 23982/59290
Iteration: 23983/59290
Iteration: 23984/59290
Iteration: 23985/59290
Iteration: 23986/59290
Iteration: 23987/59290
Iteration: 23988/59290
Iteration: 23989/59290
Iteration: 23990/59290
Iteration: 23991/59290
Iteration: 23992/59290
Iteration: 23993/59290
Iteration: 23994/59290
Iteration: 23995/59290
Iteration: 23996/59290
Iteration: 23997/59290
Iteration: 23998/59290
Iteration: 23999/59290
Iteration: 24000/59290

 40%|████      | 23993/59290 [16:37<29:28, 19.96it/s]

Iteration: 24001/59290
Iteration: 24002/59290
Iteration: 24003/59290
Iteration: 24004/59290
Iteration: 24005/59290
Iteration: 24006/59290
Iteration: 24007/59290
Iteration: 24008/59290
Iteration: 24009/59290
Iteration: 24010/59290
Iteration: 24011/59290
Iteration: 24012/59290
Iteration: 24013/59290
Iteration: 24014/59290
Iteration: 24015/59290
Iteration: 24016/59290
Iteration: 24017/59290
Iteration: 24018/59290
Iteration: 24019/59290
Iteration: 24020/59290
Iteration: 24021/59290
Iteration: 24022/59290
Iteration: 24023/59290
Iteration: 24024/59290

 41%|████      | 24017/59290 [16:37<23:32, 24.97it/s]

Iteration: 24025/59290
Iteration: 24026/59290
Iteration: 24027/59290
Iteration: 24028/59290
Iteration: 24029/59290
Iteration: 24030/59290
Iteration: 24031/59290
Iteration: 24032/59290
Iteration: 24033/59290
Iteration: 24034/59290
Iteration: 24035/59290
Iteration: 24036/59290
Iteration: 24037/59290
Iteration: 24038/59290
Iteration: 24039/59290
Iteration: 24040/59290
Iteration: 24041/59290
Iteration: 24042/59290
Iteration: 24043/59290
Iteration: 24044/59290
Iteration: 24045/59290
Iteration: 24046/59290
Iteration: 24047/59290
Iteration: 24048/59290

 41%|████      | 24041/59290 [16:38<19:17, 30.44it/s]

Iteration: 24049/59290
Iteration: 24050/59290
Iteration: 24051/59290
Iteration: 24052/59290
Iteration: 24053/59290
Iteration: 24054/59290
Iteration: 24055/59290
Iteration: 24056/59290
Iteration: 24057/59290
Iteration: 24058/59290
Iteration: 24059/59290
Iteration: 24060/59290
Iteration: 24061/59290
Iteration: 24062/59290
Iteration: 24063/59290
Iteration: 24064/59290
Iteration: 24065/59290
Iteration: 24066/59290
Iteration: 24067/59290
Iteration: 24068/59290
Iteration: 24069/59290
Iteration: 24070/59290
Iteration: 24071/59290
Iteration: 24072/59290

 41%|████      | 24065/59290 [16:38<16:21, 35.90it/s]

Iteration: 24073/59290
Iteration: 24074/59290
Iteration: 24075/59290
Iteration: 24076/59290
Iteration: 24077/59290
Iteration: 24078/59290
Iteration: 24079/59290
Iteration: 24080/59290
Iteration: 24081/59290
Iteration: 24082/59290
Iteration: 24083/59290
Iteration: 24084/59290
Iteration: 24085/59290
Iteration: 24086/59290
Iteration: 24087/59290
Iteration: 24088/59290
Iteration: 24089/59290
Iteration: 24090/59290
Iteration: 24091/59290
Iteration: 24092/59290
Iteration: 24093/59290
Iteration: 24094/59290
Iteration: 24095/59290
Iteration: 24096/59290

 41%|████      | 24089/59290 [16:39<14:10, 41.38it/s]

Iteration: 24097/59290
Iteration: 24098/59290
Iteration: 24099/59290
Iteration: 24100/59290
Iteration: 24101/59290
Iteration: 24102/59290
Iteration: 24103/59290
Iteration: 24104/59290
Iteration: 24105/59290
Iteration: 24106/59290
Iteration: 24107/59290
Iteration: 24108/59290
Iteration: 24109/59290
Iteration: 24110/59290
Iteration: 24111/59290
Iteration: 24112/59290
Iteration: 24113/59290
Iteration: 24114/59290
Iteration: 24115/59290
Iteration: 24116/59290
Iteration: 24117/59290
Iteration: 24118/59290
Iteration: 24119/59290
Iteration: 24120/59290

 41%|████      | 24113/59290 [16:39<12:39, 46.30it/s]

Iteration: 24121/59290
Iteration: 24122/59290
Iteration: 24123/59290
Iteration: 24124/59290
Iteration: 24125/59290
Iteration: 24126/59290
Iteration: 24127/59290
Iteration: 24128/59290
Iteration: 24129/59290
Iteration: 24130/59290
Iteration: 24131/59290
Iteration: 24132/59290
Iteration: 24133/59290
Iteration: 24134/59290
Iteration: 24135/59290
Iteration: 24136/59290
Iteration: 24137/59290
Iteration: 24138/59290
Iteration: 24139/59290
Iteration: 24140/59290
Iteration: 24141/59290
Iteration: 24142/59290
Iteration: 24143/59290
Iteration: 24144/59290

 41%|████      | 24137/59290 [16:39<11:38, 50.31it/s]

Iteration: 24145/59290
Iteration: 24146/59290
Iteration: 24147/59290
Iteration: 24148/59290
Iteration: 24149/59290
Iteration: 24150/59290
Iteration: 24151/59290
Iteration: 24152/59290
Iteration: 24153/59290
Iteration: 24154/59290
Iteration: 24155/59290
Iteration: 24156/59290
Iteration: 24157/59290
Iteration: 24158/59290
Iteration: 24159/59290
Iteration: 24160/59290
Iteration: 24161/59290
Iteration: 24162/59290
Iteration: 24163/59290
Iteration: 24164/59290
Iteration: 24165/59290
Iteration: 24166/59290
Iteration: 24167/59290
Iteration: 24168/59290

 41%|████      | 24161/59290 [16:40<10:51, 53.93it/s]

Iteration: 24169/59290
Iteration: 24170/59290
Iteration: 24171/59290
Iteration: 24172/59290
Iteration: 24173/59290
Iteration: 24174/59290
Iteration: 24175/59290
Iteration: 24176/59290
Iteration: 24177/59290
Iteration: 24178/59290
Iteration: 24179/59290
Iteration: 24180/59290
Iteration: 24181/59290
Iteration: 24182/59290
Iteration: 24183/59290
Iteration: 24184/59290
Iteration: 24185/59290
Iteration: 24186/59290
Iteration: 24187/59290
Iteration: 24188/59290
Iteration: 24189/59290
Iteration: 24190/59290
Iteration: 24191/59290
Iteration: 24192/59290

 41%|████      | 24185/59290 [16:40<10:30, 55.70it/s]

Iteration: 24193/59290
Iteration: 24194/59290
Iteration: 24195/59290
Iteration: 24196/59290
Iteration: 24197/59290
Iteration: 24198/59290
Iteration: 24199/59290
Iteration: 24200/59290
Iteration: 24201/59290
Iteration: 24202/59290
Iteration: 24203/59290
Iteration: 24204/59290
Iteration: 24205/59290
Iteration: 24206/59290
Iteration: 24207/59290
Iteration: 24208/59290
Iteration: 24209/59290
Iteration: 24210/59290
Iteration: 24211/59290
Iteration: 24212/59290
Iteration: 24213/59290
Iteration: 24214/59290
Iteration: 24215/59290
Iteration: 24216/59290

 41%|████      | 24209/59290 [16:41<10:03, 58.11it/s]

Iteration: 24217/59290
Iteration: 24218/59290
Iteration: 24219/59290
Iteration: 24220/59290
Iteration: 24221/59290
Iteration: 24222/59290
Iteration: 24223/59290
Iteration: 24224/59290
Iteration: 24225/59290
Iteration: 24226/59290
Iteration: 24227/59290
Iteration: 24228/59290
Iteration: 24229/59290
Iteration: 24230/59290
Iteration: 24231/59290
Iteration: 24232/59290
Iteration: 24233/59290
Iteration: 24234/59290
Iteration: 24235/59290
Iteration: 24236/59290
Iteration: 24237/59290
Iteration: 24238/59290
Iteration: 24239/59290
Iteration: 24240/59290

 41%|████      | 24233/59290 [16:41<09:49, 59.46it/s]

Iteration: 24241/59290
Iteration: 24242/59290
Iteration: 24243/59290
Iteration: 24244/59290
Iteration: 24245/59290
Iteration: 24246/59290
Iteration: 24247/59290
Iteration: 24248/59290
Iteration: 24249/59290
Iteration: 24250/59290
Iteration: 24251/59290
Iteration: 24252/59290
Iteration: 24253/59290
Iteration: 24254/59290
Iteration: 24255/59290
Iteration: 24256/59290
Iteration: 24257/59290
Iteration: 24258/59290
Iteration: 24259/59290
Iteration: 24260/59290
Iteration: 24261/59290
Iteration: 24262/59290
Iteration: 24264/59290

 41%|████      | 24256/59290 [16:41<09:58, 58.56it/s]

Iteration: 24265/59290
Iteration: 24266/59290
Iteration: 24267/59290
Iteration: 24268/59290
Iteration: 24269/59290
Iteration: 24270/59290
Iteration: 24271/59290
Iteration: 24272/59290

 41%|████      | 24264/59290 [16:42<12:11, 47.90it/s]

Iteration: 24273/59290
Iteration: 24274/59290
Iteration: 24275/59290
Iteration: 24276/59290
Iteration: 24277/59290
Iteration: 24278/59290
Iteration: 24279/59290
Iteration: 24280/59290
Iteration: 24281/59290
Iteration: 24282/59290
Iteration: 24283/59290
Iteration: 24284/59290
Iteration: 24285/59290
Iteration: 24286/59290
Iteration: 24287/59290
Iteration: 24288/59290
Iteration: 24289/59290
Iteration: 24290/59290
Iteration: 24291/59290
Iteration: 24292/59290
Iteration: 24293/59290
Iteration: 24294/59290
Iteration: 24295/59290
Iteration: 24296/59290

 41%|████      | 24288/59290 [16:42<11:08, 52.35it/s]

Iteration: 24297/59290
Iteration: 24298/59290
Iteration: 24299/59290
Iteration: 24300/59290
Iteration: 24301/59290
Iteration: 24302/59290
Iteration: 24303/59290
Iteration: 24304/59290
Iteration: 24305/59290
Iteration: 24306/59290
Iteration: 24307/59290
Iteration: 24308/59290
Iteration: 24309/59290
Iteration: 24310/59290
Iteration: 24311/59290
Iteration: 24312/59290
Iteration: 24313/59290
Iteration: 24314/59290
Iteration: 24315/59290
Iteration: 24316/59290
Iteration: 24317/59290
Iteration: 24318/59290
Iteration: 24319/59290
Iteration: 24320/59290

 41%|████      | 24312/59290 [16:42<10:34, 55.09it/s]

Iteration: 24321/59290
Iteration: 24322/59290
Iteration: 24323/59290
Iteration: 24324/59290
Iteration: 24325/59290
Iteration: 24326/59290
Iteration: 24327/59290
Iteration: 24328/59290
Iteration: 24329/59290
Iteration: 24330/59290
Iteration: 24331/59290
Iteration: 24332/59290
Iteration: 24333/59290
Iteration: 24334/59290
Iteration: 24335/59290
Iteration: 24336/59290
Iteration: 24337/59290
Iteration: 24338/59290
Iteration: 24339/59290
Iteration: 24340/59290
Iteration: 24341/59290
Iteration: 24342/59290
Iteration: 24343/59290
Iteration: 24344/59290

 41%|████      | 24336/59290 [16:44<20:35, 28.29it/s]

Iteration: 24345/59290
Iteration: 24346/59290
Iteration: 24347/59290
Iteration: 24348/59290
Iteration: 24349/59290
Iteration: 24350/59290
Iteration: 24351/59290
Iteration: 24352/59290
Iteration: 24353/59290
Iteration: 24354/59290
Iteration: 24355/59290
Iteration: 24356/59290
Iteration: 24357/59290
Iteration: 24358/59290
Iteration: 24359/59290
Iteration: 24360/59290
Iteration: 24361/59290
Iteration: 24362/59290
Iteration: 24363/59290
Iteration: 24364/59290
Iteration: 24365/59290
Iteration: 24366/59290
Iteration: 24367/59290
Iteration: 24368/59290

 41%|████      | 24360/59290 [16:46<31:25, 18.52it/s]

Iteration: 24369/59290
Iteration: 24370/59290
Iteration: 24371/59290
Iteration: 24372/59290
Iteration: 24373/59290
Iteration: 24374/59290
Iteration: 24375/59290
Iteration: 24376/59290
Iteration: 24377/59290
Iteration: 24378/59290
Iteration: 24379/59290
Iteration: 24380/59290
Iteration: 24381/59290
Iteration: 24382/59290
Iteration: 24383/59290
Iteration: 24384/59290
Iteration: 24385/59290
Iteration: 24386/59290
Iteration: 24387/59290
Iteration: 24388/59290
Iteration: 24389/59290
Iteration: 24390/59290
Iteration: 24391/59290
Iteration: 24392/59290

 41%|████      | 24384/59290 [16:47<26:09, 22.23it/s]

Iteration: 24393/59290
Iteration: 24394/59290
Iteration: 24395/59290
Iteration: 24396/59290
Iteration: 24397/59290
Iteration: 24398/59290
Iteration: 24399/59290
Iteration: 24400/59290
Iteration: 24401/59290
Iteration: 24402/59290
Iteration: 24403/59290
Iteration: 24404/59290
Iteration: 24405/59290
Iteration: 24406/59290
Iteration: 24407/59290
Iteration: 24408/59290
Iteration: 24409/59290
Iteration: 24410/59290
Iteration: 24411/59290
Iteration: 24412/59290
Iteration: 24413/59290
Iteration: 24414/59290
Iteration: 24415/59290
Iteration: 24416/59290

 41%|████      | 24408/59290 [16:47<21:04, 27.59it/s]

Iteration: 24417/59290
Iteration: 24418/59290
Iteration: 24419/59290
Iteration: 24420/59290
Iteration: 24421/59290
Iteration: 24422/59290
Iteration: 24423/59290
Iteration: 24424/59290
Iteration: 24425/59290
Iteration: 24426/59290
Iteration: 24427/59290
Iteration: 24428/59290
Iteration: 24429/59290
Iteration: 24430/59290
Iteration: 24431/59290
Iteration: 24432/59290
Iteration: 24433/59290
Iteration: 24434/59290
Iteration: 24435/59290
Iteration: 24436/59290
Iteration: 24437/59290
Iteration: 24438/59290
Iteration: 24439/59290
Iteration: 24440/59290

 41%|████      | 24432/59290 [16:48<17:31, 33.16it/s]

Iteration: 24441/59290
Iteration: 24442/59290
Iteration: 24443/59290
Iteration: 24444/59290
Iteration: 24445/59290
Iteration: 24446/59290
Iteration: 24447/59290
Iteration: 24448/59290
Iteration: 24449/59290
Iteration: 24450/59290
Iteration: 24451/59290
Iteration: 24452/59290
Iteration: 24453/59290
Iteration: 24454/59290
Iteration: 24455/59290
Iteration: 24456/59290
Iteration: 24457/59290
Iteration: 24458/59290
Iteration: 24459/59290
Iteration: 24460/59290
Iteration: 24461/59290
Iteration: 24462/59290
Iteration: 24463/59290
Iteration: 24464/59290

 41%|████      | 24456/59290 [16:48<14:59, 38.71it/s]

Iteration: 24465/59290
Iteration: 24466/59290
Iteration: 24467/59290
Iteration: 24468/59290
Iteration: 24469/59290
Iteration: 24470/59290
Iteration: 24471/59290
Iteration: 24472/59290
Iteration: 24473/59290
Iteration: 24474/59290
Iteration: 24475/59290
Iteration: 24476/59290
Iteration: 24477/59290
Iteration: 24478/59290
Iteration: 24479/59290
Iteration: 24480/59290
Iteration: 24481/59290
Iteration: 24482/59290
Iteration: 24483/59290
Iteration: 24484/59290
Iteration: 24485/59290
Iteration: 24486/59290
Iteration: 24487/59290
Iteration: 24488/59290

 41%|████▏     | 24480/59290 [16:50<23:04, 25.15it/s]

Iteration: 24489/59290
Iteration: 24490/59290
Iteration: 24491/59290
Iteration: 24492/59290
Iteration: 24493/59290
Iteration: 24494/59290
Iteration: 24495/59290
Iteration: 24496/59290
Iteration: 24497/59290
Iteration: 24498/59290
Iteration: 24499/59290
Iteration: 24500/59290
Iteration: 24501/59290
Iteration: 24502/59290
Iteration: 24503/59290
Iteration: 24504/59290
Iteration: 24505/59290
Iteration: 24506/59290
Iteration: 24507/59290
Iteration: 24508/59290
Iteration: 24509/59290
Iteration: 24510/59290
Iteration: 24511/59290
Iteration: 24512/59290

 41%|████▏     | 24504/59290 [16:52<33:06, 17.51it/s]

Iteration: 24513/59290
Iteration: 24514/59290
Iteration: 24515/59290
Iteration: 24516/59290
Iteration: 24517/59290
Iteration: 24518/59290
Iteration: 24519/59290
Iteration: 24520/59290
Iteration: 24521/59290
Iteration: 24522/59290
Iteration: 24523/59290
Iteration: 24524/59290
Iteration: 24525/59290
Iteration: 24526/59290
Iteration: 24527/59290
Iteration: 24528/59290
Iteration: 24529/59290
Iteration: 24530/59290
Iteration: 24531/59290
Iteration: 24532/59290
Iteration: 24533/59290
Iteration: 24534/59290
Iteration: 24535/59290
Iteration: 24536/59290

 41%|████▏     | 24528/59290 [16:53<28:13, 20.53it/s]

Iteration: 24537/59290
Iteration: 24538/59290
Iteration: 24539/59290
Iteration: 24540/59290
Iteration: 24541/59290
Iteration: 24542/59290
Iteration: 24543/59290
Iteration: 24544/59290
Iteration: 24545/59290
Iteration: 24546/59290
Iteration: 24547/59290
Iteration: 24548/59290
Iteration: 24549/59290
Iteration: 24550/59290
Iteration: 24551/59290
Iteration: 24552/59290
Iteration: 24553/59290
Iteration: 24554/59290
Iteration: 24555/59290
Iteration: 24556/59290
Iteration: 24557/59290
Iteration: 24558/59290
Iteration: 24559/59290
Iteration: 24560/59290

 41%|████▏     | 24552/59290 [16:53<22:28, 25.77it/s]

Iteration: 24561/59290
Iteration: 24562/59290
Iteration: 24563/59290
Iteration: 24564/59290
Iteration: 24565/59290
Iteration: 24566/59290
Iteration: 24567/59290
Iteration: 24568/59290
Iteration: 24569/59290
Iteration: 24570/59290
Iteration: 24571/59290
Iteration: 24572/59290
Iteration: 24573/59290
Iteration: 24574/59290
Iteration: 24575/59290
Iteration: 24576/59290
Iteration: 24577/59290
Iteration: 24578/59290
Iteration: 24579/59290
Iteration: 24580/59290
Iteration: 24581/59290
Iteration: 24582/59290
Iteration: 24583/59290
Iteration: 24584/59290

 41%|████▏     | 24576/59290 [16:54<18:27, 31.33it/s]

Iteration: 24585/59290
Iteration: 24586/59290
Iteration: 24587/59290
Iteration: 24588/59290
Iteration: 24589/59290
Iteration: 24590/59290
Iteration: 24591/59290
Iteration: 24592/59290
Iteration: 24593/59290
Iteration: 24594/59290
Iteration: 24595/59290
Iteration: 24596/59290
Iteration: 24597/59290
Iteration: 24598/59290
Iteration: 24599/59290
Iteration: 24600/59290
Iteration: 24601/59290
Iteration: 24602/59290
Iteration: 24603/59290
Iteration: 24604/59290
Iteration: 24605/59290
Iteration: 24606/59290
Iteration: 24607/59290
Iteration: 24608/59290

 41%|████▏     | 24600/59290 [16:54<15:40, 36.89it/s]

Iteration: 24609/59290
Iteration: 24610/59290
Iteration: 24611/59290
Iteration: 24612/59290
Iteration: 24613/59290
Iteration: 24614/59290
Iteration: 24615/59290
Iteration: 24616/59290
Iteration: 24617/59290
Iteration: 24618/59290
Iteration: 24619/59290
Iteration: 24620/59290
Iteration: 24621/59290
Iteration: 24622/59290
Iteration: 24623/59290
Iteration: 24624/59290
Iteration: 24625/59290
Iteration: 24626/59290
Iteration: 24627/59290
Iteration: 24628/59290
Iteration: 24629/59290
Iteration: 24630/59290
Iteration: 24631/59290
Iteration: 24632/59290

 42%|████▏     | 24624/59290 [16:55<13:48, 41.86it/s]

Iteration: 24633/59290
Iteration: 24634/59290
Iteration: 24635/59290
Iteration: 24636/59290
Iteration: 24637/59290
Iteration: 24638/59290
Iteration: 24639/59290
Iteration: 24640/59290
Iteration: 24641/59290
Iteration: 24642/59290
Iteration: 24643/59290
Iteration: 24644/59290
Iteration: 24645/59290
Iteration: 24646/59290
Iteration: 24647/59290
Iteration: 24648/59290
Iteration: 24649/59290
Iteration: 24650/59290
Iteration: 24651/59290
Iteration: 24652/59290
Iteration: 24653/59290
Iteration: 24654/59290
Iteration: 24655/59290
Iteration: 24656/59290

 42%|████▏     | 24648/59290 [16:55<12:26, 46.42it/s]

Iteration: 24657/59290
Iteration: 24658/59290
Iteration: 24659/59290
Iteration: 24660/59290
Iteration: 24661/59290
Iteration: 24662/59290
Iteration: 24663/59290
Iteration: 24664/59290
Iteration: 24665/59290
Iteration: 24666/59290
Iteration: 24667/59290
Iteration: 24668/59290
Iteration: 24669/59290
Iteration: 24670/59290
Iteration: 24671/59290
Iteration: 24672/59290
Iteration: 24673/59290
Iteration: 24674/59290
Iteration: 24675/59290
Iteration: 24676/59290
Iteration: 24677/59290
Iteration: 24678/59290
Iteration: 24679/59290
Iteration: 24680/59290

 42%|████▏     | 24672/59290 [16:55<11:34, 49.83it/s]

Iteration: 24681/59290
Iteration: 24682/59290
Iteration: 24683/59290
Iteration: 24684/59290
Iteration: 24685/59290
Iteration: 24686/59290
Iteration: 24687/59290
Iteration: 24688/59290
Iteration: 24689/59290
Iteration: 24690/59290
Iteration: 24691/59290
Iteration: 24692/59290
Iteration: 24693/59290
Iteration: 24694/59290
Iteration: 24695/59290
Iteration: 24696/59290
Iteration: 24697/59290
Iteration: 24698/59290
Iteration: 24699/59290
Iteration: 24700/59290
Iteration: 24701/59290
Iteration: 24702/59290
Iteration: 24703/59290
Iteration: 24704/59290

 42%|████▏     | 24696/59290 [16:56<10:53, 52.96it/s]

Iteration: 24705/59290
Iteration: 24706/59290
Iteration: 24707/59290
Iteration: 24708/59290
Iteration: 24709/59290
Iteration: 24710/59290
Iteration: 24711/59290
Iteration: 24712/59290
Iteration: 24713/59290
Iteration: 24714/59290
Iteration: 24715/59290
Iteration: 24716/59290
Iteration: 24717/59290
Iteration: 24718/59290
Iteration: 24719/59290
Iteration: 24720/59290
Iteration: 24721/59290
Iteration: 24722/59290
Iteration: 24723/59290
Iteration: 24724/59290
Iteration: 24725/59290
Iteration: 24726/59290
Iteration: 24727/59290
Iteration: 24728/59290

 42%|████▏     | 24720/59290 [16:56<10:19, 55.79it/s]

Iteration: 24729/59290
Iteration: 24730/59290
Iteration: 24731/59290
Iteration: 24732/59290
Iteration: 24733/59290
Iteration: 24734/59290
Iteration: 24735/59290
Iteration: 24736/59290
Iteration: 24737/59290
Iteration: 24738/59290
Iteration: 24739/59290
Iteration: 24740/59290
Iteration: 24741/59290
Iteration: 24742/59290
Iteration: 24743/59290
Iteration: 24744/59290
Iteration: 24745/59290
Iteration: 24746/59290
Iteration: 24747/59290
Iteration: 24748/59290
Iteration: 24749/59290
Iteration: 24750/59290
Iteration: 24751/59290
Iteration: 24752/59290

 42%|████▏     | 24744/59290 [16:56<10:01, 57.44it/s]

Iteration: 24753/59290
Iteration: 24754/59290
Iteration: 24755/59290
Iteration: 24756/59290
Iteration: 24757/59290
Iteration: 24758/59290
Iteration: 24759/59290
Iteration: 24760/59290
Iteration: 24761/59290
Iteration: 24762/59290
Iteration: 24763/59290
Iteration: 24764/59290
Iteration: 24765/59290
Iteration: 24766/59290
Iteration: 24767/59290
Iteration: 24768/59290
Iteration: 24769/59290
Iteration: 24770/59290
Iteration: 24771/59290
Iteration: 24772/59290
Iteration: 24773/59290
Iteration: 24774/59290
Iteration: 24775/59290
Iteration: 24776/59290

 42%|████▏     | 24768/59290 [16:57<09:47, 58.80it/s]

Iteration: 24777/59290
Iteration: 24778/59290
Iteration: 24779/59290
Iteration: 24780/59290
Iteration: 24781/59290
Iteration: 24782/59290
Iteration: 24783/59290
Iteration: 24784/59290
Iteration: 24785/59290
Iteration: 24786/59290
Iteration: 24787/59290
Iteration: 24788/59290
Iteration: 24789/59290
Iteration: 24790/59290
Iteration: 24791/59290
Iteration: 24792/59290
Iteration: 24793/59290
Iteration: 24794/59290
Iteration: 24795/59290
Iteration: 24796/59290
Iteration: 24797/59290
Iteration: 24798/59290
Iteration: 24799/59290
Iteration: 24800/59290

 42%|████▏     | 24792/59290 [16:57<09:32, 60.31it/s]

Iteration: 24801/59290
Iteration: 24802/59290
Iteration: 24803/59290
Iteration: 24804/59290
Iteration: 24805/59290
Iteration: 24806/59290
Iteration: 24807/59290
Iteration: 24808/59290
Iteration: 24809/59290
Iteration: 24810/59290
Iteration: 24811/59290
Iteration: 24812/59290
Iteration: 24813/59290
Iteration: 24814/59290
Iteration: 24815/59290
Iteration: 24816/59290
Iteration: 24817/59290
Iteration: 24818/59290
Iteration: 24819/59290
Iteration: 24820/59290
Iteration: 24821/59290
Iteration: 24822/59290
Iteration: 24823/59290
Iteration: 24824/59290

 42%|████▏     | 24816/59290 [16:58<09:48, 58.61it/s]

Iteration: 24825/59290
Iteration: 24826/59290
Iteration: 24827/59290
Iteration: 24828/59290
Iteration: 24829/59290
Iteration: 24830/59290
Iteration: 24831/59290
Iteration: 24832/59290
Iteration: 24833/59290
Iteration: 24834/59290
Iteration: 24835/59290
Iteration: 24836/59290
Iteration: 24837/59290
Iteration: 24838/59290
Iteration: 24839/59290
Iteration: 24840/59290
Iteration: 24841/59290
Iteration: 24842/59290
Iteration: 24843/59290
Iteration: 24844/59290
Iteration: 24845/59290
Iteration: 24846/59290
Iteration: 24847/59290
Iteration: 24848/59290

 42%|████▏     | 24840/59290 [16:59<17:55, 32.02it/s]

Iteration: 24849/59290
Iteration: 24850/59290
Iteration: 24851/59290
Iteration: 24852/59290
Iteration: 24853/59290
Iteration: 24854/59290
Iteration: 24855/59290
Iteration: 24856/59290
Iteration: 24857/59290
Iteration: 24858/59290
Iteration: 24859/59290
Iteration: 24860/59290
Iteration: 24861/59290
Iteration: 24862/59290
Iteration: 24863/59290
Iteration: 24864/59290
Iteration: 24865/59290
Iteration: 24866/59290
Iteration: 24867/59290
Iteration: 24868/59290
Iteration: 24869/59290
Iteration: 24870/59290
Iteration: 24871/59290
Iteration: 24872/59290

 42%|████▏     | 24864/59290 [17:02<32:01, 17.92it/s]

Iteration: 24873/59290
Iteration: 24874/59290
Iteration: 24875/59290
Iteration: 24876/59290
Iteration: 24877/59290
Iteration: 24878/59290
Iteration: 24879/59290
Iteration: 24880/59290
Iteration: 24881/59290
Iteration: 24882/59290
Iteration: 24883/59290
Iteration: 24884/59290
Iteration: 24885/59290
Iteration: 24886/59290
Iteration: 24887/59290
Iteration: 24888/59290
Iteration: 24889/59290
Iteration: 24890/59290
Iteration: 24891/59290
Iteration: 24892/59290
Iteration: 24893/59290
Iteration: 24894/59290
Iteration: 24895/59290
Iteration: 24896/59290

 42%|████▏     | 24888/59290 [17:02<25:13, 22.73it/s]

Iteration: 24897/59290
Iteration: 24898/59290
Iteration: 24899/59290
Iteration: 24900/59290
Iteration: 24901/59290
Iteration: 24902/59290
Iteration: 24903/59290
Iteration: 24904/59290
Iteration: 24905/59290
Iteration: 24906/59290
Iteration: 24907/59290
Iteration: 24908/59290
Iteration: 24909/59290
Iteration: 24910/59290
Iteration: 24911/59290
Iteration: 24912/59290
Iteration: 24913/59290
Iteration: 24914/59290
Iteration: 24915/59290
Iteration: 24916/59290
Iteration: 24917/59290
Iteration: 24918/59290
Iteration: 24919/59290
Iteration: 24920/59290

 42%|████▏     | 24912/59290 [17:03<20:20, 28.17it/s]

Iteration: 24921/59290
Iteration: 24922/59290
Iteration: 24923/59290
Iteration: 24924/59290
Iteration: 24925/59290
Iteration: 24926/59290
Iteration: 24927/59290
Iteration: 24928/59290
Iteration: 24929/59290
Iteration: 24930/59290
Iteration: 24931/59290
Iteration: 24932/59290
Iteration: 24933/59290
Iteration: 24934/59290
Iteration: 24935/59290
Iteration: 24936/59290
Iteration: 24937/59290
Iteration: 24938/59290
Iteration: 24939/59290
Iteration: 24940/59290
Iteration: 24941/59290
Iteration: 24942/59290
Iteration: 24943/59290
Iteration: 24944/59290

 42%|████▏     | 24936/59290 [17:03<17:17, 33.11it/s]

Iteration: 24945/59290
Iteration: 24946/59290
Iteration: 24947/59290
Iteration: 24948/59290
Iteration: 24949/59290
Iteration: 24950/59290
Iteration: 24951/59290
Iteration: 24952/59290
Iteration: 24953/59290
Iteration: 24954/59290
Iteration: 24955/59290
Iteration: 24956/59290
Iteration: 24957/59290
Iteration: 24958/59290
Iteration: 24959/59290
Iteration: 24960/59290
Iteration: 24961/59290
Iteration: 24962/59290
Iteration: 24963/59290
Iteration: 24964/59290
Iteration: 24965/59290
Iteration: 24966/59290
Iteration: 24967/59290
Iteration: 24968/59290

 42%|████▏     | 24960/59290 [17:05<22:24, 25.54it/s]

Iteration: 24969/59290
Iteration: 24970/59290
Iteration: 24971/59290
Iteration: 24972/59290
Iteration: 24973/59290
Iteration: 24974/59290
Iteration: 24975/59290
Iteration: 24976/59290
Iteration: 24977/59290
Iteration: 24978/59290
Iteration: 24979/59290
Iteration: 24980/59290
Iteration: 24981/59290
Iteration: 24982/59290
Iteration: 24983/59290
Iteration: 24984/59290
Iteration: 24985/59290
Iteration: 24986/59290
Iteration: 24987/59290
Iteration: 24988/59290
Iteration: 24989/59290
Iteration: 24990/59290
Iteration: 24991/59290
Iteration: 24992/59290

 42%|████▏     | 24984/59290 [17:07<31:34, 18.10it/s]

Iteration: 24993/59290
Iteration: 24994/59290
Iteration: 24995/59290
Iteration: 24996/59290
Iteration: 24997/59290
Iteration: 24998/59290
Iteration: 24999/59290
Iteration: 25000/59290
Iteration: 25001/59290
Iteration: 25002/59290
Iteration: 25003/59290
Iteration: 25004/59290
Iteration: 25005/59290
Iteration: 25006/59290
Iteration: 25007/59290
Iteration: 25008/59290
Iteration: 25009/59290
Iteration: 25010/59290
Iteration: 25011/59290
Iteration: 25012/59290
Iteration: 25013/59290
Iteration: 25014/59290
Iteration: 25015/59290
Iteration: 25016/59290

 42%|████▏     | 25008/59290 [17:07<26:40, 21.42it/s]

Iteration: 25017/59290
Iteration: 25018/59290
Iteration: 25019/59290
Iteration: 25020/59290
Iteration: 25021/59290
Iteration: 25022/59290
Iteration: 25023/59290
Iteration: 25024/59290
Iteration: 25025/59290
Iteration: 25026/59290
Iteration: 25027/59290
Iteration: 25028/59290
Iteration: 25029/59290
Iteration: 25030/59290
Iteration: 25031/59290
Iteration: 25032/59290
Iteration: 25033/59290
Iteration: 25034/59290
Iteration: 25035/59290
Iteration: 25036/59290
Iteration: 25037/59290
Iteration: 25038/59290
Iteration: 25039/59290
Iteration: 25040/59290

 42%|████▏     | 25032/59290 [17:08<21:27, 26.60it/s]

Iteration: 25041/59290
Iteration: 25042/59290
Iteration: 25043/59290
Iteration: 25044/59290
Iteration: 25045/59290
Iteration: 25046/59290
Iteration: 25047/59290
Iteration: 25048/59290
Iteration: 25049/59290
Iteration: 25050/59290
Iteration: 25051/59290
Iteration: 25052/59290
Iteration: 25053/59290
Iteration: 25054/59290
Iteration: 25055/59290
Iteration: 25056/59290
Iteration: 25057/59290
Iteration: 25058/59290
Iteration: 25059/59290
Iteration: 25060/59290
Iteration: 25061/59290
Iteration: 25062/59290
Iteration: 25063/59290
Iteration: 25064/59290

 42%|████▏     | 25056/59290 [17:08<17:47, 32.07it/s]

Iteration: 25065/59290
Iteration: 25066/59290
Iteration: 25067/59290
Iteration: 25068/59290
Iteration: 25069/59290
Iteration: 25070/59290
Iteration: 25071/59290
Iteration: 25072/59290
Iteration: 25073/59290
Iteration: 25074/59290
Iteration: 25075/59290
Iteration: 25076/59290
Iteration: 25077/59290
Iteration: 25078/59290
Iteration: 25079/59290
Iteration: 25080/59290
Iteration: 25081/59290
Iteration: 25082/59290
Iteration: 25083/59290
Iteration: 25084/59290
Iteration: 25085/59290
Iteration: 25086/59290
Iteration: 25087/59290
Iteration: 25088/59290

 42%|████▏     | 25080/59290 [17:09<15:13, 37.43it/s]

Iteration: 25089/59290
Iteration: 25090/59290
Iteration: 25091/59290
Iteration: 25092/59290
Iteration: 25093/59290
Iteration: 25094/59290
Iteration: 25095/59290
Iteration: 25096/59290
Iteration: 25097/59290
Iteration: 25098/59290
Iteration: 25099/59290
Iteration: 25100/59290
Iteration: 25101/59290
Iteration: 25102/59290
Iteration: 25103/59290
Iteration: 25104/59290
Iteration: 25105/59290
Iteration: 25106/59290
Iteration: 25107/59290
Iteration: 25108/59290
Iteration: 25109/59290
Iteration: 25110/59290
Iteration: 25111/59290
Iteration: 25112/59290

 42%|████▏     | 25104/59290 [17:09<13:20, 42.72it/s]

Iteration: 25113/59290
Iteration: 25114/59290
Iteration: 25115/59290
Iteration: 25116/59290
Iteration: 25117/59290
Iteration: 25118/59290
Iteration: 25119/59290
Iteration: 25120/59290
Iteration: 25121/59290
Iteration: 25122/59290
Iteration: 25123/59290
Iteration: 25124/59290
Iteration: 25125/59290
Iteration: 25126/59290
Iteration: 25127/59290
Iteration: 25128/59290
Iteration: 25129/59290
Iteration: 25130/59290
Iteration: 25131/59290
Iteration: 25132/59290
Iteration: 25133/59290
Iteration: 25134/59290
Iteration: 25135/59290
Iteration: 25136/59290

 42%|████▏     | 25128/59290 [17:09<12:02, 47.30it/s]

Iteration: 25137/59290
Iteration: 25138/59290
Iteration: 25139/59290
Iteration: 25140/59290
Iteration: 25141/59290
Iteration: 25142/59290
Iteration: 25143/59290
Iteration: 25144/59290
Iteration: 25145/59290
Iteration: 25146/59290
Iteration: 25147/59290
Iteration: 25148/59290
Iteration: 25149/59290
Iteration: 25150/59290
Iteration: 25151/59290
Iteration: 25152/59290
Iteration: 25153/59290
Iteration: 25154/59290
Iteration: 25155/59290
Iteration: 25156/59290
Iteration: 25157/59290
Iteration: 25158/59290
Iteration: 25159/59290
Iteration: 25160/59290

 42%|████▏     | 25152/59290 [17:10<11:11, 50.80it/s]

Iteration: 25161/59290
Iteration: 25162/59290
Iteration: 25163/59290
Iteration: 25164/59290
Iteration: 25165/59290
Iteration: 25166/59290
Iteration: 25167/59290
Iteration: 25168/59290
Iteration: 25169/59290
Iteration: 25170/59290
Iteration: 25171/59290
Iteration: 25172/59290
Iteration: 25173/59290
Iteration: 25174/59290
Iteration: 25175/59290
Iteration: 25176/59290
Iteration: 25177/59290
Iteration: 25178/59290
Iteration: 25179/59290
Iteration: 25180/59290
Iteration: 25181/59290
Iteration: 25182/59290
Iteration: 25183/59290
Iteration: 25184/59290

 42%|████▏     | 25176/59290 [17:10<10:30, 54.14it/s]

Iteration: 25185/59290
Iteration: 25186/59290
Iteration: 25187/59290
Iteration: 25188/59290
Iteration: 25189/59290
Iteration: 25190/59290
Iteration: 25191/59290
Iteration: 25192/59290
Iteration: 25193/59290
Iteration: 25194/59290
Iteration: 25195/59290
Iteration: 25196/59290
Iteration: 25197/59290
Iteration: 25198/59290
Iteration: 25199/59290
Iteration: 25200/59290
Iteration: 25201/59290
Iteration: 25202/59290
Iteration: 25203/59290
Iteration: 25204/59290
Iteration: 25205/59290
Iteration: 25206/59290
Iteration: 25207/59290
Iteration: 25208/59290

 43%|████▎     | 25200/59290 [17:10<10:07, 56.16it/s]

Iteration: 25209/59290
Iteration: 25210/59290
Iteration: 25211/59290
Iteration: 25212/59290
Iteration: 25213/59290
Iteration: 25214/59290
Iteration: 25215/59290
Iteration: 25216/59290
Iteration: 25217/59290
Iteration: 25218/59290
Iteration: 25219/59290
Iteration: 25220/59290
Iteration: 25221/59290
Iteration: 25222/59290
Iteration: 25223/59290
Iteration: 25224/59290
Iteration: 25225/59290
Iteration: 25226/59290
Iteration: 25227/59290
Iteration: 25228/59290
Iteration: 25229/59290
Iteration: 25230/59290
Iteration: 25231/59290
Iteration: 25232/59290

 43%|████▎     | 25224/59290 [17:11<09:45, 58.15it/s]

Iteration: 25233/59290
Iteration: 25234/59290
Iteration: 25235/59290
Iteration: 25236/59290
Iteration: 25237/59290
Iteration: 25238/59290
Iteration: 25239/59290
Iteration: 25240/59290
Iteration: 25241/59290
Iteration: 25242/59290
Iteration: 25243/59290
Iteration: 25244/59290
Iteration: 25245/59290
Iteration: 25246/59290
Iteration: 25247/59290
Iteration: 25248/59290
Iteration: 25249/59290
Iteration: 25250/59290
Iteration: 25251/59290
Iteration: 25252/59290
Iteration: 25253/59290
Iteration: 25254/59290
Iteration: 25255/59290
Iteration: 25256/59290

 43%|████▎     | 25248/59290 [17:11<09:35, 59.13it/s]

Iteration: 25257/59290
Iteration: 25258/59290
Iteration: 25259/59290
Iteration: 25260/59290
Iteration: 25261/59290
Iteration: 25262/59290
Iteration: 25263/59290
Iteration: 25264/59290
Iteration: 25265/59290
Iteration: 25266/59290
Iteration: 25267/59290
Iteration: 25268/59290
Iteration: 25269/59290
Iteration: 25270/59290
Iteration: 25271/59290
Iteration: 25272/59290
Iteration: 25273/59290
Iteration: 25274/59290
Iteration: 25275/59290
Iteration: 25276/59290
Iteration: 25277/59290
Iteration: 25278/59290
Iteration: 25279/59290
Iteration: 25280/59290

 43%|████▎     | 25272/59290 [17:12<09:28, 59.80it/s]

Iteration: 25281/59290
Iteration: 25282/59290
Iteration: 25283/59290
Iteration: 25284/59290
Iteration: 25285/59290
Iteration: 25286/59290
Iteration: 25287/59290
Iteration: 25288/59290
Iteration: 25289/59290
Iteration: 25290/59290
Iteration: 25291/59290
Iteration: 25292/59290
Iteration: 25293/59290
Iteration: 25294/59290
Iteration: 25295/59290
Iteration: 25296/59290
Iteration: 25297/59290
Iteration: 25298/59290
Iteration: 25299/59290
Iteration: 25300/59290
Iteration: 25301/59290
Iteration: 25302/59290
Iteration: 25303/59290
Iteration: 25304/59290

 43%|████▎     | 25296/59290 [17:12<09:17, 61.03it/s]

Iteration: 25305/59290
Iteration: 25306/59290
Iteration: 25307/59290
Iteration: 25308/59290
Iteration: 25309/59290
Iteration: 25310/59290
Iteration: 25311/59290
Iteration: 25312/59290
Iteration: 25313/59290
Iteration: 25314/59290
Iteration: 25315/59290
Iteration: 25316/59290
Iteration: 25317/59290
Iteration: 25318/59290
Iteration: 25319/59290
Iteration: 25320/59290
Iteration: 25321/59290
Iteration: 25322/59290
Iteration: 25323/59290
Iteration: 25324/59290
Iteration: 25325/59290
Iteration: 25326/59290
Iteration: 25327/59290
Iteration: 25328/59290

 43%|████▎     | 25320/59290 [17:12<09:08, 61.98it/s]

Iteration: 25329/59290
Iteration: 25330/59290
Iteration: 25331/59290
Iteration: 25332/59290
Iteration: 25333/59290
Iteration: 25334/59290
Iteration: 25335/59290
Iteration: 25336/59290
Iteration: 25337/59290
Iteration: 25338/59290
Iteration: 25339/59290
Iteration: 25340/59290
Iteration: 25341/59290
Iteration: 25342/59290
Iteration: 25343/59290
Iteration: 25344/59290
Iteration: 25345/59290
Iteration: 25346/59290
Iteration: 25347/59290
Iteration: 25348/59290
Iteration: 25349/59290
Iteration: 25350/59290
Iteration: 25351/59290
Iteration: 25352/59290

 43%|████▎     | 25344/59290 [17:13<09:06, 62.14it/s]

Iteration: 25353/59290
Iteration: 25354/59290
Iteration: 25355/59290
Iteration: 25356/59290
Iteration: 25357/59290
Iteration: 25358/59290
Iteration: 25359/59290
Iteration: 25360/59290
Iteration: 25361/59290
Iteration: 25362/59290
Iteration: 25363/59290
Iteration: 25364/59290
Iteration: 25365/59290
Iteration: 25366/59290
Iteration: 25367/59290
Iteration: 25368/59290
Iteration: 25369/59290
Iteration: 25370/59290
Iteration: 25371/59290
Iteration: 25372/59290
Iteration: 25373/59290
Iteration: 25374/59290
Iteration: 25375/59290
Iteration: 25376/59290

 43%|████▎     | 25368/59290 [17:13<09:03, 62.44it/s]

Iteration: 25377/59290
Iteration: 25378/59290
Iteration: 25379/59290
Iteration: 25380/59290
Iteration: 25381/59290
Iteration: 25382/59290
Iteration: 25383/59290
Iteration: 25384/59290
Iteration: 25385/59290
Iteration: 25386/59290
Iteration: 25387/59290
Iteration: 25388/59290
Iteration: 25389/59290
Iteration: 25390/59290
Iteration: 25391/59290
Iteration: 25392/59290
Iteration: 25393/59290
Iteration: 25394/59290
Iteration: 25395/59290
Iteration: 25396/59290
Iteration: 25397/59290
Iteration: 25398/59290
Iteration: 25399/59290
Iteration: 25400/59290

 43%|████▎     | 25392/59290 [17:14<09:10, 61.61it/s]

Iteration: 25401/59290
Iteration: 25402/59290
Iteration: 25403/59290
Iteration: 25404/59290
Iteration: 25405/59290
Iteration: 25406/59290
Iteration: 25407/59290
Iteration: 25408/59290
Iteration: 25409/59290
Iteration: 25410/59290
Iteration: 25411/59290
Iteration: 25412/59290
Iteration: 25413/59290
Iteration: 25414/59290
Iteration: 25415/59290
Iteration: 25416/59290
Iteration: 25417/59290
Iteration: 25418/59290
Iteration: 25419/59290
Iteration: 25420/59290
Iteration: 25421/59290
Iteration: 25422/59290
Iteration: 25423/59290
Iteration: 25424/59290

 43%|████▎     | 25416/59290 [17:14<09:03, 62.27it/s]

Iteration: 25425/59290
Iteration: 25426/59290
Iteration: 25427/59290
Iteration: 25428/59290
Iteration: 25429/59290
Iteration: 25430/59290
Iteration: 25431/59290
Iteration: 25432/59290
Iteration: 25433/59290
Iteration: 25434/59290
Iteration: 25435/59290
Iteration: 25436/59290
Iteration: 25437/59290
Iteration: 25438/59290
Iteration: 25439/59290
Iteration: 25440/59290
Iteration: 25441/59290
Iteration: 25442/59290
Iteration: 25443/59290
Iteration: 25444/59290
Iteration: 25445/59290
Iteration: 25446/59290
Iteration: 25447/59290
Iteration: 25448/59290

 43%|████▎     | 25440/59290 [17:14<08:59, 62.70it/s]

Iteration: 25449/59290
Iteration: 25450/59290
Iteration: 25451/59290
Iteration: 25452/59290
Iteration: 25453/59290
Iteration: 25454/59290
Iteration: 25455/59290
Iteration: 25456/59290
Iteration: 25457/59290
Iteration: 25458/59290
Iteration: 25459/59290
Iteration: 25460/59290
Iteration: 25461/59290
Iteration: 25462/59290
Iteration: 25463/59290
Iteration: 25464/59290
Iteration: 25465/59290
Iteration: 25466/59290
Iteration: 25467/59290
Iteration: 25468/59290
Iteration: 25469/59290
Iteration: 25470/59290
Iteration: 25471/59290
Iteration: 25472/59290

 43%|████▎     | 25464/59290 [17:15<09:08, 61.62it/s]

Iteration: 25473/59290
Iteration: 25474/59290
Iteration: 25475/59290
Iteration: 25476/59290
Iteration: 25477/59290
Iteration: 25478/59290
Iteration: 25479/59290
Iteration: 25480/59290
Iteration: 25481/59290
Iteration: 25482/59290
Iteration: 25483/59290
Iteration: 25484/59290
Iteration: 25485/59290
Iteration: 25486/59290
Iteration: 25487/59290
Iteration: 25488/59290
Iteration: 25489/59290
Iteration: 25490/59290
Iteration: 25491/59290
Iteration: 25492/59290
Iteration: 25493/59290
Iteration: 25494/59290
Iteration: 25495/59290
Iteration: 25496/59290

 43%|████▎     | 25488/59290 [17:16<16:34, 33.99it/s]

Iteration: 25497/59290
Iteration: 25498/59290
Iteration: 25499/59290
Iteration: 25500/59290
Iteration: 25501/59290
Iteration: 25502/59290
Iteration: 25503/59290
Iteration: 25504/59290
Iteration: 25505/59290
Iteration: 25506/59290
Iteration: 25507/59290
Iteration: 25508/59290
Iteration: 25509/59290
Iteration: 25510/59290
Iteration: 25511/59290
Iteration: 25512/59290
Iteration: 25513/59290
Iteration: 25514/59290
Iteration: 25515/59290
Iteration: 25516/59290
Iteration: 25517/59290
Iteration: 25518/59290
Iteration: 25519/59290
Iteration: 25520/59290

 43%|████▎     | 25512/59290 [17:18<26:31, 21.23it/s]

Iteration: 25521/59290
Iteration: 25522/59290
Iteration: 25523/59290
Iteration: 25524/59290
Iteration: 25525/59290
Iteration: 25526/59290
Iteration: 25527/59290
Iteration: 25528/59290
Iteration: 25529/59290
Iteration: 25530/59290
Iteration: 25531/59290
Iteration: 25532/59290
Iteration: 25533/59290
Iteration: 25534/59290
Iteration: 25535/59290
Iteration: 25536/59290
Iteration: 25537/59290
Iteration: 25538/59290
Iteration: 25539/59290
Iteration: 25540/59290
Iteration: 25541/59290
Iteration: 25542/59290
Iteration: 25543/59290
Iteration: 25544/59290

 43%|████▎     | 25536/59290 [17:19<23:22, 24.07it/s]

Iteration: 25545/59290
Iteration: 25546/59290
Iteration: 25547/59290
Iteration: 25548/59290
Iteration: 25549/59290
Iteration: 25550/59290
Iteration: 25551/59290
Iteration: 25552/59290
Iteration: 25553/59290
Iteration: 25554/59290
Iteration: 25555/59290
Iteration: 25556/59290
Iteration: 25557/59290
Iteration: 25558/59290
Iteration: 25559/59290
Iteration: 25560/59290
Iteration: 25561/59290
Iteration: 25562/59290
Iteration: 25563/59290
Iteration: 25564/59290
Iteration: 25565/59290
Iteration: 25566/59290
Iteration: 25567/59290
Iteration: 25568/59290

 43%|████▎     | 25560/59290 [17:19<18:59, 29.60it/s]

Iteration: 25569/59290
Iteration: 25570/59290
Iteration: 25571/59290
Iteration: 25572/59290
Iteration: 25573/59290
Iteration: 25574/59290
Iteration: 25575/59290
Iteration: 25576/59290
Iteration: 25577/59290
Iteration: 25578/59290
Iteration: 25579/59290
Iteration: 25580/59290
Iteration: 25581/59290
Iteration: 25582/59290
Iteration: 25583/59290
Iteration: 25584/59290
Iteration: 25585/59290
Iteration: 25586/59290
Iteration: 25587/59290
Iteration: 25588/59290
Iteration: 25589/59290
Iteration: 25590/59290
Iteration: 25591/59290
Iteration: 25592/59290

 43%|████▎     | 25584/59290 [17:20<15:56, 35.25it/s]

Iteration: 25593/59290
Iteration: 25594/59290
Iteration: 25595/59290
Iteration: 25596/59290
Iteration: 25597/59290
Iteration: 25598/59290
Iteration: 25599/59290
Iteration: 25600/59290
Iteration: 25601/59290
Iteration: 25602/59290
Iteration: 25603/59290
Iteration: 25604/59290
Iteration: 25605/59290
Iteration: 25606/59290
Iteration: 25607/59290
Iteration: 25608/59290
Iteration: 25609/59290
Iteration: 25610/59290
Iteration: 25611/59290
Iteration: 25612/59290
Iteration: 25613/59290
Iteration: 25614/59290
Iteration: 25615/59290
Iteration: 25616/59290

 43%|████▎     | 25608/59290 [17:20<13:50, 40.56it/s]

Iteration: 25617/59290
Iteration: 25618/59290
Iteration: 25619/59290
Iteration: 25620/59290
Iteration: 25621/59290
Iteration: 25622/59290
Iteration: 25623/59290
Iteration: 25624/59290
Iteration: 25625/59290
Iteration: 25626/59290
Iteration: 25627/59290
Iteration: 25628/59290
Iteration: 25629/59290
Iteration: 25630/59290
Iteration: 25631/59290
Iteration: 25632/59290
Iteration: 25633/59290
Iteration: 25634/59290
Iteration: 25635/59290
Iteration: 25636/59290
Iteration: 25637/59290
Iteration: 25638/59290
Iteration: 25639/59290
Iteration: 25640/59290

 43%|████▎     | 25632/59290 [17:20<12:19, 45.52it/s]

Iteration: 25641/59290
Iteration: 25642/59290
Iteration: 25643/59290
Iteration: 25644/59290
Iteration: 25645/59290
Iteration: 25646/59290
Iteration: 25647/59290
Iteration: 25648/59290
Iteration: 25649/59290
Iteration: 25650/59290
Iteration: 25651/59290
Iteration: 25652/59290
Iteration: 25653/59290
Iteration: 25654/59290
Iteration: 25655/59290
Iteration: 25656/59290
Iteration: 25657/59290
Iteration: 25658/59290
Iteration: 25659/59290
Iteration: 25660/59290
Iteration: 25661/59290
Iteration: 25662/59290
Iteration: 25663/59290
Iteration: 25664/59290

 43%|████▎     | 25656/59290 [17:22<19:43, 28.41it/s]

Iteration: 25665/59290
Iteration: 25666/59290
Iteration: 25667/59290
Iteration: 25668/59290
Iteration: 25669/59290
Iteration: 25670/59290
Iteration: 25671/59290
Iteration: 25672/59290
Iteration: 25673/59290
Iteration: 25674/59290
Iteration: 25675/59290
Iteration: 25676/59290
Iteration: 25677/59290
Iteration: 25678/59290
Iteration: 25679/59290
Iteration: 25680/59290
Iteration: 25681/59290
Iteration: 25682/59290
Iteration: 25683/59290
Iteration: 25684/59290
Iteration: 25685/59290
Iteration: 25686/59290
Iteration: 25687/59290
Iteration: 25688/59290

 43%|████▎     | 25680/59290 [17:25<32:00, 17.50it/s]

Iteration: 25689/59290
Iteration: 25690/59290
Iteration: 25691/59290
Iteration: 25692/59290
Iteration: 25693/59290
Iteration: 25694/59290
Iteration: 25695/59290
Iteration: 25696/59290
Iteration: 25697/59290
Iteration: 25698/59290
Iteration: 25699/59290
Iteration: 25700/59290
Iteration: 25701/59290
Iteration: 25702/59290
Iteration: 25703/59290
Iteration: 25704/59290
Iteration: 25705/59290
Iteration: 25706/59290
Iteration: 25707/59290
Iteration: 25708/59290
Iteration: 25709/59290
Iteration: 25710/59290
Iteration: 25711/59290
Iteration: 25712/59290

 43%|████▎     | 25704/59290 [17:25<25:24, 22.03it/s]

Iteration: 25713/59290
Iteration: 25714/59290
Iteration: 25715/59290
Iteration: 25716/59290
Iteration: 25717/59290
Iteration: 25718/59290
Iteration: 25719/59290
Iteration: 25720/59290
Iteration: 25721/59290
Iteration: 25722/59290
Iteration: 25723/59290
Iteration: 25724/59290
Iteration: 25725/59290
Iteration: 25726/59290
Iteration: 25727/59290
Iteration: 25728/59290
Iteration: 25729/59290
Iteration: 25730/59290
Iteration: 25731/59290
Iteration: 25732/59290
Iteration: 25733/59290
Iteration: 25734/59290
Iteration: 25735/59290
Iteration: 25736/59290

 43%|████▎     | 25728/59290 [17:25<20:31, 27.26it/s]

Iteration: 25737/59290
Iteration: 25738/59290
Iteration: 25739/59290
Iteration: 25740/59290
Iteration: 25741/59290
Iteration: 25742/59290
Iteration: 25743/59290
Iteration: 25744/59290
Iteration: 25745/59290
Iteration: 25746/59290
Iteration: 25747/59290
Iteration: 25748/59290
Iteration: 25749/59290
Iteration: 25750/59290
Iteration: 25751/59290
Iteration: 25752/59290
Iteration: 25753/59290
Iteration: 25754/59290
Iteration: 25755/59290
Iteration: 25756/59290
Iteration: 25757/59290
Iteration: 25758/59290
Iteration: 25759/59290
Iteration: 25760/59290

 43%|████▎     | 25752/59290 [17:26<17:06, 32.66it/s]

Iteration: 25761/59290
Iteration: 25762/59290
Iteration: 25763/59290
Iteration: 25764/59290
Iteration: 25765/59290
Iteration: 25766/59290
Iteration: 25767/59290
Iteration: 25768/59290
Iteration: 25769/59290
Iteration: 25770/59290
Iteration: 25771/59290
Iteration: 25772/59290
Iteration: 25773/59290
Iteration: 25774/59290
Iteration: 25775/59290
Iteration: 25776/59290
Iteration: 25777/59290
Iteration: 25778/59290
Iteration: 25779/59290
Iteration: 25780/59290
Iteration: 25781/59290
Iteration: 25782/59290
Iteration: 25783/59290
Iteration: 25784/59290

 43%|████▎     | 25776/59290 [17:26<14:34, 38.32it/s]

Iteration: 25785/59290
Iteration: 25786/59290
Iteration: 25787/59290
Iteration: 25788/59290
Iteration: 25789/59290
Iteration: 25790/59290
Iteration: 25791/59290
Iteration: 25792/59290
Iteration: 25793/59290
Iteration: 25794/59290
Iteration: 25795/59290
Iteration: 25796/59290
Iteration: 25797/59290
Iteration: 25798/59290
Iteration: 25799/59290
Iteration: 25800/59290
Iteration: 25801/59290
Iteration: 25802/59290
Iteration: 25803/59290
Iteration: 25804/59290
Iteration: 25805/59290
Iteration: 25806/59290
Iteration: 25807/59290
Iteration: 25808/59290

 44%|████▎     | 25800/59290 [17:27<12:57, 43.09it/s]

Iteration: 25809/59290
Iteration: 25810/59290
Iteration: 25811/59290
Iteration: 25812/59290
Iteration: 25813/59290
Iteration: 25814/59290
Iteration: 25815/59290
Iteration: 25816/59290
Iteration: 25817/59290
Iteration: 25818/59290
Iteration: 25819/59290
Iteration: 25820/59290
Iteration: 25821/59290
Iteration: 25822/59290
Iteration: 25823/59290
Iteration: 25824/59290
Iteration: 25825/59290
Iteration: 25826/59290
Iteration: 25827/59290
Iteration: 25828/59290
Iteration: 25829/59290
Iteration: 25830/59290
Iteration: 25831/59290
Iteration: 25832/59290

 44%|████▎     | 25824/59290 [17:27<11:40, 47.80it/s]

Iteration: 25833/59290
Iteration: 25834/59290
Iteration: 25835/59290
Iteration: 25836/59290
Iteration: 25837/59290
Iteration: 25838/59290
Iteration: 25839/59290
Iteration: 25840/59290
Iteration: 25841/59290
Iteration: 25842/59290
Iteration: 25843/59290
Iteration: 25844/59290
Iteration: 25845/59290
Iteration: 25846/59290
Iteration: 25847/59290
Iteration: 25848/59290
Iteration: 25849/59290
Iteration: 25850/59290
Iteration: 25851/59290
Iteration: 25852/59290
Iteration: 25853/59290
Iteration: 25854/59290
Iteration: 25855/59290
Iteration: 25856/59290

 44%|████▎     | 25848/59290 [17:27<10:48, 51.58it/s]

Iteration: 25857/59290
Iteration: 25858/59290
Iteration: 25859/59290
Iteration: 25860/59290
Iteration: 25861/59290
Iteration: 25862/59290
Iteration: 25863/59290
Iteration: 25864/59290
Iteration: 25865/59290
Iteration: 25866/59290
Iteration: 25867/59290
Iteration: 25868/59290
Iteration: 25869/59290
Iteration: 25870/59290
Iteration: 25871/59290
Iteration: 25872/59290
Iteration: 25873/59290
Iteration: 25874/59290
Iteration: 25875/59290
Iteration: 25876/59290
Iteration: 25877/59290
Iteration: 25878/59290
Iteration: 25879/59290
Iteration: 25880/59290

 44%|████▎     | 25872/59290 [17:28<10:11, 54.65it/s]

Iteration: 25881/59290
Iteration: 25882/59290
Iteration: 25883/59290
Iteration: 25884/59290
Iteration: 25885/59290
Iteration: 25886/59290
Iteration: 25887/59290
Iteration: 25888/59290
Iteration: 25889/59290
Iteration: 25890/59290
Iteration: 25891/59290
Iteration: 25892/59290
Iteration: 25893/59290
Iteration: 25894/59290
Iteration: 25895/59290
Iteration: 25896/59290
Iteration: 25897/59290
Iteration: 25898/59290
Iteration: 25899/59290
Iteration: 25900/59290
Iteration: 25901/59290
Iteration: 25902/59290
Iteration: 25903/59290
Iteration: 25904/59290

 44%|████▎     | 25896/59290 [18:02<4:05:48,  2.26it/s]

Iteration: 25905/59290
Iteration: 25906/59290
Iteration: 25907/59290
Iteration: 25908/59290
Iteration: 25909/59290
Iteration: 25910/59290
Iteration: 25911/59290
Iteration: 25912/59290
Iteration: 25913/59290
Iteration: 25914/59290
Iteration: 25915/59290
Iteration: 25916/59290
Iteration: 25917/59290
Iteration: 25918/59290
Iteration: 25919/59290
Iteration: 25920/59290
Iteration: 25921/59290
Iteration: 25922/59290
Iteration: 25923/59290
Iteration: 25924/59290
Iteration: 25925/59290
Iteration: 25926/59290
Iteration: 25927/59290
Iteration: 25928/59290

 44%|████▎     | 25920/59290 [18:03<2:57:08,  3.14it/s]

Iteration: 25929/59290
Iteration: 25930/59290
Iteration: 25931/59290
Iteration: 25932/59290
Iteration: 25933/59290
Iteration: 25934/59290
Iteration: 25935/59290
Iteration: 25936/59290
Iteration: 25937/59290
Iteration: 25938/59290
Iteration: 25939/59290
Iteration: 25940/59290
Iteration: 25941/59290
Iteration: 25942/59290
Iteration: 25943/59290
Iteration: 25944/59290
Iteration: 25945/59290
Iteration: 25946/59290
Iteration: 25947/59290
Iteration: 25948/59290
Iteration: 25949/59290
Iteration: 25950/59290
Iteration: 25951/59290
Iteration: 25952/59290

 44%|████▍     | 25944/59290 [18:03<2:06:29,  4.39it/s]

Iteration: 25953/59290
Iteration: 25954/59290
Iteration: 25955/59290
Iteration: 25956/59290
Iteration: 25957/59290
Iteration: 25958/59290
Iteration: 25959/59290
Iteration: 25960/59290
Iteration: 25961/59290
Iteration: 25962/59290
Iteration: 25963/59290
Iteration: 25964/59290
Iteration: 25965/59290
Iteration: 25966/59290
Iteration: 25967/59290
Iteration: 25968/59290
Iteration: 25969/59290
Iteration: 25970/59290
Iteration: 25971/59290
Iteration: 25972/59290
Iteration: 25973/59290
Iteration: 25974/59290
Iteration: 25975/59290
Iteration: 25976/59290

 44%|████▍     | 25968/59290 [18:04<1:31:06,  6.10it/s]

Iteration: 25977/59290
Iteration: 25978/59290
Iteration: 25979/59290
Iteration: 25980/59290
Iteration: 25981/59290
Iteration: 25982/59290
Iteration: 25983/59290
Iteration: 25984/59290
Iteration: 25985/59290
Iteration: 25986/59290
Iteration: 25987/59290
Iteration: 25988/59290
Iteration: 25989/59290
Iteration: 25990/59290
Iteration: 25991/59290
Iteration: 25992/59290
Iteration: 25993/59290
Iteration: 25994/59290
Iteration: 25995/59290
Iteration: 25996/59290
Iteration: 25997/59290
Iteration: 25998/59290
Iteration: 25999/59290
Iteration: 26000/59290

 44%|████▍     | 25992/59290 [18:04<1:06:25,  8.35it/s]

Iteration: 26001/59290
Iteration: 26002/59290
Iteration: 26003/59290
Iteration: 26004/59290
Iteration: 26005/59290
Iteration: 26006/59290
Iteration: 26007/59290
Iteration: 26008/59290
Iteration: 26009/59290
Iteration: 26010/59290
Iteration: 26011/59290
Iteration: 26012/59290
Iteration: 26013/59290
Iteration: 26014/59290
Iteration: 26015/59290
Iteration: 26016/59290
Iteration: 26017/59290
Iteration: 26018/59290
Iteration: 26019/59290
Iteration: 26020/59290
Iteration: 26021/59290
Iteration: 26022/59290
Iteration: 26023/59290
Iteration: 26024/59290

 44%|████▍     | 26016/59290 [18:04<49:05, 11.30it/s]

Iteration: 26025/59290
Iteration: 26026/59290
Iteration: 26027/59290
Iteration: 26028/59290
Iteration: 26029/59290
Iteration: 26030/59290
Iteration: 26031/59290
Iteration: 26032/59290
Iteration: 26033/59290
Iteration: 26034/59290
Iteration: 26035/59290
Iteration: 26036/59290
Iteration: 26037/59290
Iteration: 26038/59290
Iteration: 26039/59290
Iteration: 26040/59290
Iteration: 26041/59290
Iteration: 26042/59290
Iteration: 26043/59290
Iteration: 26044/59290
Iteration: 26045/59290
Iteration: 26046/59290
Iteration: 26047/59290
Iteration: 26048/59290

 44%|████▍     | 26040/59290 [18:05<36:58, 14.99it/s]

Iteration: 26049/59290
Iteration: 26050/59290
Iteration: 26051/59290
Iteration: 26052/59290
Iteration: 26053/59290
Iteration: 26054/59290
Iteration: 26055/59290
Iteration: 26056/59290
Iteration: 26057/59290
Iteration: 26058/59290
Iteration: 26059/59290
Iteration: 26060/59290
Iteration: 26061/59290
Iteration: 26062/59290
Iteration: 26063/59290
Iteration: 26064/59290
Iteration: 26065/59290
Iteration: 26066/59290
Iteration: 26067/59290
Iteration: 26068/59290
Iteration: 26069/59290
Iteration: 26070/59290
Iteration: 26071/59290
Iteration: 26072/59290

 44%|████▍     | 26064/59290 [18:05<28:26, 19.46it/s]

Iteration: 26073/59290
Iteration: 26074/59290
Iteration: 26075/59290
Iteration: 26076/59290
Iteration: 26077/59290
Iteration: 26078/59290
Iteration: 26079/59290
Iteration: 26080/59290
Iteration: 26081/59290
Iteration: 26082/59290
Iteration: 26083/59290
Iteration: 26084/59290
Iteration: 26085/59290
Iteration: 26086/59290
Iteration: 26087/59290
Iteration: 26088/59290
Iteration: 26089/59290
Iteration: 26090/59290
Iteration: 26091/59290
Iteration: 26092/59290
Iteration: 26093/59290
Iteration: 26094/59290
Iteration: 26095/59290
Iteration: 26096/59290

 44%|████▍     | 26088/59290 [18:05<22:28, 24.62it/s]

Iteration: 26097/59290
Iteration: 26098/59290
Iteration: 26099/59290
Iteration: 26100/59290
Iteration: 26101/59290
Iteration: 26102/59290
Iteration: 26103/59290
Iteration: 26104/59290
Iteration: 26105/59290
Iteration: 26106/59290
Iteration: 26107/59290
Iteration: 26108/59290
Iteration: 26109/59290
Iteration: 26110/59290
Iteration: 26111/59290
Iteration: 26112/59290
Iteration: 26113/59290
Iteration: 26114/59290
Iteration: 26115/59290
Iteration: 26116/59290
Iteration: 26117/59290
Iteration: 26118/59290
Iteration: 26119/59290
Iteration: 26120/59290

 44%|████▍     | 26112/59290 [18:06<18:22, 30.10it/s]

Iteration: 26121/59290
Iteration: 26122/59290
Iteration: 26123/59290
Iteration: 26124/59290
Iteration: 26125/59290
Iteration: 26126/59290
Iteration: 26127/59290
Iteration: 26128/59290
Iteration: 26129/59290
Iteration: 26130/59290
Iteration: 26131/59290
Iteration: 26132/59290
Iteration: 26133/59290
Iteration: 26134/59290
Iteration: 26135/59290
Iteration: 26136/59290
Iteration: 26137/59290
Iteration: 26138/59290
Iteration: 26139/59290
Iteration: 26140/59290
Iteration: 26141/59290
Iteration: 26142/59290
Iteration: 26143/59290
Iteration: 26144/59290

 44%|████▍     | 26136/59290 [18:06<15:37, 35.37it/s]

Iteration: 26145/59290
Iteration: 26146/59290
Iteration: 26147/59290
Iteration: 26148/59290
Iteration: 26149/59290
Iteration: 26150/59290
Iteration: 26151/59290
Iteration: 26152/59290
Iteration: 26153/59290
Iteration: 26154/59290
Iteration: 26155/59290
Iteration: 26156/59290
Iteration: 26157/59290
Iteration: 26158/59290
Iteration: 26159/59290
Iteration: 26160/59290
Iteration: 26161/59290
Iteration: 26162/59290
Iteration: 26163/59290
Iteration: 26164/59290
Iteration: 26165/59290
Iteration: 26166/59290
Iteration: 26167/59290
Iteration: 26168/59290

 44%|████▍     | 26160/59290 [18:07<13:32, 40.77it/s]

Iteration: 26169/59290
Iteration: 26170/59290
Iteration: 26171/59290
Iteration: 26172/59290
Iteration: 26173/59290
Iteration: 26174/59290
Iteration: 26175/59290
Iteration: 26176/59290
Iteration: 26177/59290
Iteration: 26178/59290
Iteration: 26179/59290
Iteration: 26180/59290
Iteration: 26181/59290
Iteration: 26182/59290
Iteration: 26183/59290
Iteration: 26184/59290
Iteration: 26185/59290
Iteration: 26186/59290
Iteration: 26187/59290
Iteration: 26188/59290
Iteration: 26189/59290
Iteration: 26190/59290
Iteration: 26191/59290
Iteration: 26192/59290

 44%|████▍     | 26184/59290 [18:11<38:03, 14.50it/s]

Iteration: 26193/59290
Iteration: 26194/59290
Iteration: 26195/59290
Iteration: 26196/59290
Iteration: 26197/59290
Iteration: 26198/59290
Iteration: 26199/59290
Iteration: 26200/59290
Iteration: 26201/59290
Iteration: 26202/59290
Iteration: 26203/59290
Iteration: 26204/59290
Iteration: 26205/59290
Iteration: 26206/59290
Iteration: 26207/59290
Iteration: 26208/59290
Iteration: 26209/59290
Iteration: 26210/59290
Iteration: 26211/59290
Iteration: 26212/59290
Iteration: 26213/59290
Iteration: 26214/59290
Iteration: 26215/59290
Iteration: 26216/59290

 44%|████▍     | 26208/59290 [18:11<30:29, 18.08it/s]

Iteration: 26217/59290
Iteration: 26218/59290
Iteration: 26219/59290
Iteration: 26220/59290
Iteration: 26221/59290
Iteration: 26222/59290
Iteration: 26223/59290
Iteration: 26224/59290
Iteration: 26225/59290
Iteration: 26226/59290
Iteration: 26227/59290
Iteration: 26228/59290
Iteration: 26229/59290
Iteration: 26230/59290
Iteration: 26231/59290
Iteration: 26232/59290
Iteration: 26233/59290
Iteration: 26234/59290
Iteration: 26235/59290
Iteration: 26236/59290
Iteration: 26237/59290
Iteration: 26238/59290
Iteration: 26239/59290
Iteration: 26240/59290

 44%|████▍     | 26232/59290 [18:12<23:58, 22.98it/s]

Iteration: 26241/59290
Iteration: 26242/59290
Iteration: 26243/59290
Iteration: 26244/59290
Iteration: 26245/59290
Iteration: 26246/59290
Iteration: 26247/59290
Iteration: 26248/59290
Iteration: 26249/59290
Iteration: 26250/59290
Iteration: 26251/59290
Iteration: 26252/59290
Iteration: 26253/59290
Iteration: 26254/59290
Iteration: 26255/59290
Iteration: 26256/59290
Iteration: 26257/59290
Iteration: 26258/59290
Iteration: 26259/59290
Iteration: 26260/59290
Iteration: 26261/59290
Iteration: 26262/59290
Iteration: 26263/59290
Iteration: 26264/59290

 44%|████▍     | 26256/59290 [18:12<19:21, 28.43it/s]

Iteration: 26265/59290
Iteration: 26266/59290
Iteration: 26267/59290
Iteration: 26268/59290
Iteration: 26269/59290
Iteration: 26270/59290
Iteration: 26271/59290
Iteration: 26272/59290
Iteration: 26273/59290
Iteration: 26274/59290
Iteration: 26275/59290
Iteration: 26276/59290
Iteration: 26277/59290
Iteration: 26278/59290
Iteration: 26279/59290
Iteration: 26280/59290
Iteration: 26281/59290
Iteration: 26282/59290
Iteration: 26283/59290
Iteration: 26284/59290
Iteration: 26285/59290
Iteration: 26286/59290
Iteration: 26287/59290
Iteration: 26288/59290

 44%|████▍     | 26280/59290 [18:13<16:11, 33.96it/s]

Iteration: 26289/59290
Iteration: 26290/59290
Iteration: 26291/59290
Iteration: 26292/59290
Iteration: 26293/59290
Iteration: 26294/59290
Iteration: 26295/59290
Iteration: 26296/59290
Iteration: 26297/59290
Iteration: 26298/59290
Iteration: 26299/59290
Iteration: 26300/59290
Iteration: 26301/59290
Iteration: 26302/59290
Iteration: 26303/59290
Iteration: 26304/59290
Iteration: 26305/59290
Iteration: 26306/59290
Iteration: 26307/59290
Iteration: 26308/59290
Iteration: 26309/59290
Iteration: 26310/59290
Iteration: 26311/59290
Iteration: 26312/59290

 44%|████▍     | 26304/59290 [18:13<13:57, 39.40it/s]

Iteration: 26313/59290
Iteration: 26314/59290
Iteration: 26315/59290
Iteration: 26316/59290
Iteration: 26317/59290
Iteration: 26318/59290
Iteration: 26319/59290
Iteration: 26320/59290
Iteration: 26321/59290
Iteration: 26322/59290
Iteration: 26323/59290
Iteration: 26324/59290
Iteration: 26325/59290
Iteration: 26326/59290
Iteration: 26327/59290
Iteration: 26328/59290
Iteration: 26329/59290
Iteration: 26330/59290
Iteration: 26331/59290
Iteration: 26332/59290
Iteration: 26333/59290
Iteration: 26334/59290
Iteration: 26335/59290
Iteration: 26336/59290

 44%|████▍     | 26328/59290 [18:14<20:11, 27.21it/s]

Iteration: 26337/59290
Iteration: 26338/59290
Iteration: 26339/59290
Iteration: 26340/59290
Iteration: 26341/59290
Iteration: 26342/59290
Iteration: 26343/59290
Iteration: 26344/59290
Iteration: 26345/59290
Iteration: 26346/59290
Iteration: 26347/59290
Iteration: 26348/59290
Iteration: 26349/59290
Iteration: 26350/59290
Iteration: 26351/59290
Iteration: 26352/59290
Iteration: 26353/59290
Iteration: 26354/59290
Iteration: 26355/59290
Iteration: 26356/59290
Iteration: 26357/59290
Iteration: 26358/59290
Iteration: 26359/59290
Iteration: 26360/59290

 44%|████▍     | 26352/59290 [18:17<30:32, 17.98it/s]

Iteration: 26361/59290
Iteration: 26362/59290
Iteration: 26363/59290
Iteration: 26364/59290
Iteration: 26365/59290
Iteration: 26366/59290
Iteration: 26367/59290
Iteration: 26368/59290
Iteration: 26369/59290
Iteration: 26370/59290
Iteration: 26371/59290
Iteration: 26372/59290
Iteration: 26373/59290
Iteration: 26374/59290
Iteration: 26375/59290
Iteration: 26376/59290
Iteration: 26377/59290
Iteration: 26378/59290
Iteration: 26379/59290
Iteration: 26380/59290
Iteration: 26381/59290
Iteration: 26382/59290
Iteration: 26383/59290
Iteration: 26384/59290

 44%|████▍     | 26376/59290 [18:17<25:08, 21.82it/s]

Iteration: 26385/59290
Iteration: 26386/59290
Iteration: 26387/59290
Iteration: 26388/59290
Iteration: 26389/59290
Iteration: 26390/59290
Iteration: 26391/59290
Iteration: 26392/59290
Iteration: 26393/59290
Iteration: 26394/59290
Iteration: 26395/59290
Iteration: 26396/59290
Iteration: 26397/59290
Iteration: 26398/59290
Iteration: 26399/59290
Iteration: 26400/59290
Iteration: 26401/59290
Iteration: 26402/59290
Iteration: 26403/59290
Iteration: 26404/59290
Iteration: 26405/59290
Iteration: 26406/59290
Iteration: 26407/59290
Iteration: 26408/59290

 45%|████▍     | 26400/59290 [18:18<20:08, 27.22it/s]

Iteration: 26409/59290
Iteration: 26410/59290
Iteration: 26411/59290
Iteration: 26412/59290
Iteration: 26413/59290
Iteration: 26414/59290
Iteration: 26415/59290
Iteration: 26416/59290
Iteration: 26417/59290
Iteration: 26418/59290
Iteration: 26419/59290
Iteration: 26420/59290
Iteration: 26421/59290
Iteration: 26422/59290
Iteration: 26423/59290
Iteration: 26424/59290
Iteration: 26425/59290
Iteration: 26426/59290
Iteration: 26427/59290
Iteration: 26428/59290
Iteration: 26429/59290
Iteration: 26430/59290
Iteration: 26431/59290
Iteration: 26432/59290

 45%|████▍     | 26424/59290 [18:18<16:39, 32.88it/s]

Iteration: 26433/59290
Iteration: 26434/59290
Iteration: 26435/59290
Iteration: 26436/59290
Iteration: 26437/59290
Iteration: 26438/59290
Iteration: 26439/59290
Iteration: 26440/59290
Iteration: 26441/59290
Iteration: 26442/59290
Iteration: 26443/59290
Iteration: 26444/59290
Iteration: 26445/59290
Iteration: 26446/59290
Iteration: 26447/59290
Iteration: 26448/59290
Iteration: 26449/59290
Iteration: 26450/59290
Iteration: 26451/59290
Iteration: 26452/59290
Iteration: 26453/59290
Iteration: 26454/59290
Iteration: 26455/59290
Iteration: 26456/59290

 45%|████▍     | 26448/59290 [18:20<23:51, 22.95it/s]

Iteration: 26457/59290
Iteration: 26458/59290
Iteration: 26459/59290
Iteration: 26460/59290
Iteration: 26461/59290
Iteration: 26462/59290
Iteration: 26463/59290
Iteration: 26464/59290
Iteration: 26465/59290
Iteration: 26466/59290
Iteration: 26467/59290
Iteration: 26468/59290
Iteration: 26469/59290
Iteration: 26470/59290
Iteration: 26471/59290
Iteration: 26472/59290
Iteration: 26473/59290
Iteration: 26474/59290
Iteration: 26475/59290
Iteration: 26476/59290
Iteration: 26477/59290
Iteration: 26478/59290
Iteration: 26479/59290
Iteration: 26480/59290

 45%|████▍     | 26472/59290 [18:22<32:41, 16.73it/s]

Iteration: 26481/59290
Iteration: 26482/59290
Iteration: 26483/59290
Iteration: 26484/59290
Iteration: 26485/59290
Iteration: 26486/59290
Iteration: 26487/59290
Iteration: 26488/59290
Iteration: 26489/59290
Iteration: 26490/59290
Iteration: 26491/59290
Iteration: 26492/59290
Iteration: 26493/59290
Iteration: 26494/59290
Iteration: 26495/59290
Iteration: 26496/59290
Iteration: 26497/59290
Iteration: 26498/59290
Iteration: 26499/59290
Iteration: 26500/59290
Iteration: 26501/59290
Iteration: 26502/59290
Iteration: 26503/59290
Iteration: 26504/59290

 45%|████▍     | 26496/59290 [18:23<26:30, 20.61it/s]

Iteration: 26505/59290
Iteration: 26506/59290
Iteration: 26507/59290
Iteration: 26508/59290
Iteration: 26509/59290
Iteration: 26510/59290
Iteration: 26511/59290
Iteration: 26512/59290
Iteration: 26513/59290
Iteration: 26514/59290
Iteration: 26515/59290
Iteration: 26516/59290
Iteration: 26517/59290
Iteration: 26518/59290
Iteration: 26519/59290
Iteration: 26520/59290
Iteration: 26521/59290
Iteration: 26522/59290
Iteration: 26523/59290
Iteration: 26524/59290
Iteration: 26525/59290
Iteration: 26526/59290
Iteration: 26527/59290
Iteration: 26528/59290

 45%|████▍     | 26520/59290 [18:23<21:16, 25.68it/s]

Iteration: 26529/59290
Iteration: 26530/59290
Iteration: 26531/59290
Iteration: 26532/59290
Iteration: 26533/59290
Iteration: 26534/59290
Iteration: 26535/59290
Iteration: 26536/59290
Iteration: 26537/59290
Iteration: 26538/59290
Iteration: 26539/59290
Iteration: 26540/59290
Iteration: 26541/59290
Iteration: 26542/59290
Iteration: 26543/59290
Iteration: 26544/59290
Iteration: 26545/59290
Iteration: 26546/59290
Iteration: 26547/59290
Iteration: 26548/59290
Iteration: 26549/59290
Iteration: 26550/59290
Iteration: 26551/59290
Iteration: 26552/59290

 45%|████▍     | 26544/59290 [18:24<17:28, 31.24it/s]

Iteration: 26553/59290
Iteration: 26554/59290
Iteration: 26555/59290
Iteration: 26556/59290
Iteration: 26557/59290
Iteration: 26558/59290
Iteration: 26559/59290
Iteration: 26560/59290
Iteration: 26561/59290
Iteration: 26562/59290
Iteration: 26563/59290
Iteration: 26564/59290
Iteration: 26565/59290
Iteration: 26566/59290
Iteration: 26567/59290
Iteration: 26568/59290
Iteration: 26569/59290
Iteration: 26570/59290
Iteration: 26571/59290
Iteration: 26572/59290
Iteration: 26573/59290
Iteration: 26574/59290
Iteration: 26575/59290
Iteration: 26576/59290

 45%|████▍     | 26568/59290 [18:24<14:55, 36.53it/s]

Iteration: 26577/59290
Iteration: 26578/59290
Iteration: 26579/59290
Iteration: 26580/59290
Iteration: 26581/59290
Iteration: 26582/59290
Iteration: 26583/59290
Iteration: 26584/59290
Iteration: 26585/59290
Iteration: 26586/59290
Iteration: 26587/59290
Iteration: 26588/59290
Iteration: 26589/59290
Iteration: 26590/59290
Iteration: 26591/59290
Iteration: 26592/59290
Iteration: 26593/59290
Iteration: 26594/59290
Iteration: 26595/59290
Iteration: 26596/59290
Iteration: 26597/59290
Iteration: 26598/59290
Iteration: 26599/59290
Iteration: 26600/59290

 45%|████▍     | 26592/59290 [18:24<12:58, 42.00it/s]

Iteration: 26601/59290
Iteration: 26602/59290
Iteration: 26603/59290
Iteration: 26604/59290
Iteration: 26605/59290
Iteration: 26606/59290
Iteration: 26607/59290
Iteration: 26608/59290
Iteration: 26609/59290
Iteration: 26610/59290
Iteration: 26611/59290
Iteration: 26612/59290
Iteration: 26613/59290
Iteration: 26614/59290
Iteration: 26615/59290
Iteration: 26616/59290
Iteration: 26617/59290
Iteration: 26618/59290
Iteration: 26619/59290
Iteration: 26620/59290
Iteration: 26621/59290
Iteration: 26622/59290
Iteration: 26623/59290
Iteration: 26624/59290

 45%|████▍     | 26616/59290 [18:25<11:45, 46.30it/s]

Iteration: 26625/59290
Iteration: 26626/59290
Iteration: 26627/59290
Iteration: 26628/59290
Iteration: 26629/59290
Iteration: 26630/59290
Iteration: 26631/59290
Iteration: 26632/59290
Iteration: 26633/59290
Iteration: 26634/59290
Iteration: 26635/59290
Iteration: 26636/59290
Iteration: 26637/59290
Iteration: 26638/59290
Iteration: 26639/59290
Iteration: 26640/59290
Iteration: 26641/59290
Iteration: 26642/59290
Iteration: 26643/59290
Iteration: 26644/59290
Iteration: 26645/59290
Iteration: 26646/59290
Iteration: 26647/59290
Iteration: 26648/59290

 45%|████▍     | 26640/59290 [18:25<10:55, 49.83it/s]

Iteration: 26649/59290
Iteration: 26650/59290
Iteration: 26651/59290
Iteration: 26652/59290
Iteration: 26653/59290
Iteration: 26654/59290
Iteration: 26655/59290
Iteration: 26656/59290
Iteration: 26657/59290
Iteration: 26658/59290
Iteration: 26659/59290
Iteration: 26660/59290
Iteration: 26661/59290
Iteration: 26662/59290
Iteration: 26663/59290
Iteration: 26664/59290
Iteration: 26665/59290
Iteration: 26666/59290
Iteration: 26667/59290
Iteration: 26668/59290
Iteration: 26669/59290
Iteration: 26670/59290
Iteration: 26671/59290
Iteration: 26672/59290

 45%|████▍     | 26664/59290 [18:58<3:49:14,  2.37it/s]

Iteration: 26673/59290
Iteration: 26674/59290
Iteration: 26675/59290
Iteration: 26676/59290
Iteration: 26677/59290
Iteration: 26678/59290
Iteration: 26679/59290
Iteration: 26680/59290
Iteration: 26681/59290
Iteration: 26682/59290
Iteration: 26683/59290
Iteration: 26684/59290
Iteration: 26685/59290
Iteration: 26686/59290
Iteration: 26687/59290
Iteration: 26688/59290
Iteration: 26689/59290
Iteration: 26690/59290
Iteration: 26691/59290
Iteration: 26692/59290
Iteration: 26693/59290
Iteration: 26694/59290
Iteration: 26695/59290
Iteration: 26696/59290

 45%|████▌     | 26688/59290 [18:59<2:45:48,  3.28it/s]

Iteration: 26697/59290
Iteration: 26698/59290
Iteration: 26699/59290
Iteration: 26700/59290
Iteration: 26701/59290
Iteration: 26702/59290
Iteration: 26703/59290
Iteration: 26704/59290
Iteration: 26705/59290
Iteration: 26706/59290
Iteration: 26707/59290
Iteration: 26708/59290
Iteration: 26709/59290
Iteration: 26710/59290
Iteration: 26711/59290
Iteration: 26712/59290
Iteration: 26713/59290
Iteration: 26714/59290
Iteration: 26715/59290
Iteration: 26716/59290
Iteration: 26717/59290
Iteration: 26718/59290
Iteration: 26719/59290
Iteration: 26720/59290

 45%|████▌     | 26712/59290 [18:59<1:58:38,  4.58it/s]

Iteration: 26721/59290
Iteration: 26722/59290
Iteration: 26723/59290
Iteration: 26724/59290
Iteration: 26725/59290
Iteration: 26726/59290
Iteration: 26727/59290
Iteration: 26728/59290
Iteration: 26729/59290
Iteration: 26730/59290
Iteration: 26731/59290
Iteration: 26732/59290
Iteration: 26733/59290
Iteration: 26734/59290
Iteration: 26735/59290
Iteration: 26736/59290
Iteration: 26737/59290
Iteration: 26738/59290
Iteration: 26739/59290
Iteration: 26740/59290
Iteration: 26741/59290
Iteration: 26742/59290
Iteration: 26743/59290
Iteration: 26744/59290

 45%|████▌     | 26736/59290 [18:59<1:25:36,  6.34it/s]

Iteration: 26745/59290
Iteration: 26746/59290
Iteration: 26747/59290
Iteration: 26748/59290
Iteration: 26749/59290
Iteration: 26750/59290
Iteration: 26751/59290
Iteration: 26752/59290
Iteration: 26753/59290
Iteration: 26754/59290
Iteration: 26755/59290
Iteration: 26756/59290
Iteration: 26757/59290
Iteration: 26758/59290
Iteration: 26759/59290
Iteration: 26760/59290
Iteration: 26761/59290
Iteration: 26762/59290
Iteration: 26763/59290
Iteration: 26764/59290
Iteration: 26765/59290
Iteration: 26766/59290
Iteration: 26767/59290
Iteration: 26768/59290

 45%|████▌     | 26760/59290 [19:00<1:02:37,  8.66it/s]

Iteration: 26769/59290
Iteration: 26770/59290
Iteration: 26771/59290
Iteration: 26772/59290
Iteration: 26773/59290
Iteration: 26774/59290
Iteration: 26775/59290
Iteration: 26776/59290
Iteration: 26777/59290
Iteration: 26778/59290
Iteration: 26779/59290
Iteration: 26780/59290
Iteration: 26781/59290
Iteration: 26782/59290
Iteration: 26783/59290
Iteration: 26784/59290
Iteration: 26785/59290
Iteration: 26786/59290
Iteration: 26787/59290
Iteration: 26788/59290
Iteration: 26789/59290
Iteration: 26790/59290
Iteration: 26791/59290
Iteration: 26792/59290

 45%|████▌     | 26784/59290 [19:00<46:29, 11.65it/s]

Iteration: 26793/59290
Iteration: 26794/59290
Iteration: 26795/59290
Iteration: 26796/59290
Iteration: 26797/59290
Iteration: 26798/59290
Iteration: 26799/59290
Iteration: 26800/59290
Iteration: 26801/59290
Iteration: 26802/59290
Iteration: 26803/59290
Iteration: 26804/59290
Iteration: 26805/59290
Iteration: 26806/59290
Iteration: 26807/59290
Iteration: 26808/59290
Iteration: 26809/59290
Iteration: 26810/59290
Iteration: 26811/59290
Iteration: 26812/59290
Iteration: 26813/59290
Iteration: 26814/59290
Iteration: 26815/59290
Iteration: 26816/59290

 45%|████▌     | 26808/59290 [19:00<35:03, 15.44it/s]

Iteration: 26817/59290
Iteration: 26818/59290
Iteration: 26819/59290
Iteration: 26820/59290
Iteration: 26821/59290
Iteration: 26822/59290
Iteration: 26823/59290
Iteration: 26824/59290
Iteration: 26825/59290
Iteration: 26826/59290
Iteration: 26827/59290
Iteration: 26828/59290
Iteration: 26829/59290
Iteration: 26830/59290
Iteration: 26831/59290
Iteration: 26832/59290
Iteration: 26833/59290
Iteration: 26834/59290
Iteration: 26835/59290
Iteration: 26836/59290
Iteration: 26837/59290
Iteration: 26838/59290
Iteration: 26839/59290
Iteration: 26840/59290

 45%|████▌     | 26832/59290 [19:01<27:07, 19.94it/s]

Iteration: 26841/59290
Iteration: 26842/59290
Iteration: 26843/59290
Iteration: 26844/59290
Iteration: 26845/59290
Iteration: 26846/59290
Iteration: 26847/59290
Iteration: 26848/59290
Iteration: 26849/59290
Iteration: 26850/59290
Iteration: 26851/59290
Iteration: 26852/59290
Iteration: 26853/59290
Iteration: 26854/59290
Iteration: 26855/59290
Iteration: 26856/59290
Iteration: 26857/59290
Iteration: 26858/59290
Iteration: 26859/59290
Iteration: 26860/59290
Iteration: 26861/59290
Iteration: 26862/59290
Iteration: 26863/59290
Iteration: 26864/59290

 45%|████▌     | 26856/59290 [19:01<21:37, 25.01it/s]

Iteration: 26865/59290
Iteration: 26866/59290
Iteration: 26867/59290
Iteration: 26868/59290
Iteration: 26869/59290
Iteration: 26870/59290
Iteration: 26871/59290
Iteration: 26872/59290
Iteration: 26873/59290
Iteration: 26874/59290
Iteration: 26875/59290
Iteration: 26876/59290
Iteration: 26877/59290
Iteration: 26878/59290
Iteration: 26879/59290
Iteration: 26880/59290
Iteration: 26881/59290
Iteration: 26882/59290
Iteration: 26883/59290
Iteration: 26884/59290
Iteration: 26885/59290
Iteration: 26886/59290
Iteration: 26887/59290
Iteration: 26888/59290

 45%|████▌     | 26880/59290 [19:02<17:52, 30.22it/s]

Iteration: 26889/59290
Iteration: 26890/59290
Iteration: 26891/59290
Iteration: 26892/59290
Iteration: 26893/59290
Iteration: 26894/59290
Iteration: 26895/59290
Iteration: 26896/59290
Iteration: 26897/59290
Iteration: 26898/59290
Iteration: 26899/59290
Iteration: 26900/59290
Iteration: 26901/59290
Iteration: 26902/59290
Iteration: 26903/59290
Iteration: 26904/59290
Iteration: 26905/59290
Iteration: 26906/59290
Iteration: 26907/59290
Iteration: 26908/59290
Iteration: 26909/59290
Iteration: 26910/59290
Iteration: 26911/59290
Iteration: 26912/59290

 45%|████▌     | 26904/59290 [19:02<15:05, 35.78it/s]

Iteration: 26913/59290
Iteration: 26914/59290
Iteration: 26915/59290
Iteration: 26916/59290
Iteration: 26917/59290
Iteration: 26918/59290
Iteration: 26919/59290
Iteration: 26920/59290
Iteration: 26921/59290
Iteration: 26922/59290
Iteration: 26923/59290
Iteration: 26924/59290
Iteration: 26925/59290
Iteration: 26926/59290
Iteration: 26927/59290
Iteration: 26928/59290
Iteration: 26929/59290
Iteration: 26930/59290
Iteration: 26931/59290
Iteration: 26932/59290
Iteration: 26933/59290
Iteration: 26934/59290
Iteration: 26935/59290
Iteration: 26936/59290

 45%|████▌     | 26928/59290 [19:02<13:07, 41.09it/s]

Iteration: 26937/59290
Iteration: 26938/59290
Iteration: 26939/59290
Iteration: 26940/59290
Iteration: 26941/59290
Iteration: 26942/59290
Iteration: 26943/59290
Iteration: 26944/59290
Iteration: 26945/59290
Iteration: 26946/59290
Iteration: 26947/59290
Iteration: 26948/59290
Iteration: 26949/59290
Iteration: 26950/59290
Iteration: 26951/59290
Iteration: 26952/59290
Iteration: 26953/59290
Iteration: 26954/59290
Iteration: 26955/59290
Iteration: 26956/59290
Iteration: 26957/59290
Iteration: 26958/59290
Iteration: 26960/59290

 45%|████▌     | 26951/59290 [19:06<36:46, 14.65it/s]

Iteration: 26961/59290
Iteration: 26962/59290
Iteration: 26963/59290
Iteration: 26964/59290
Iteration: 26965/59290
Iteration: 26966/59290
Iteration: 26967/59290
Iteration: 26968/59290

 45%|████▌     | 26959/59290 [19:07<37:00, 14.56it/s]

Iteration: 26969/59290
Iteration: 26970/59290
Iteration: 26971/59290
Iteration: 26972/59290
Iteration: 26973/59290
Iteration: 26974/59290
Iteration: 26975/59290
Iteration: 26976/59290
Iteration: 26977/59290
Iteration: 26978/59290
Iteration: 26979/59290
Iteration: 26980/59290
Iteration: 26981/59290
Iteration: 26982/59290
Iteration: 26983/59290
Iteration: 26984/59290
Iteration: 26985/59290
Iteration: 26986/59290
Iteration: 26987/59290
Iteration: 26988/59290
Iteration: 26989/59290
Iteration: 26990/59290
Iteration: 26991/59290
Iteration: 26992/59290

 46%|████▌     | 26983/59290 [19:07<27:02, 19.91it/s]

Iteration: 26993/59290
Iteration: 26994/59290
Iteration: 26995/59290
Iteration: 26996/59290
Iteration: 26997/59290
Iteration: 26998/59290
Iteration: 26999/59290
Iteration: 27000/59290
Iteration: 27001/59290
Iteration: 27002/59290
Iteration: 27003/59290
Iteration: 27004/59290
Iteration: 27005/59290
Iteration: 27006/59290
Iteration: 27007/59290
Iteration: 27008/59290
Iteration: 27009/59290
Iteration: 27010/59290
Iteration: 27011/59290
Iteration: 27012/59290
Iteration: 27013/59290
Iteration: 27014/59290
Iteration: 27015/59290
Iteration: 27016/59290

 46%|████▌     | 27007/59290 [19:08<20:47, 25.87it/s]

Iteration: 27017/59290
Iteration: 27018/59290
Iteration: 27019/59290
Iteration: 27020/59290
Iteration: 27021/59290
Iteration: 27022/59290
Iteration: 27023/59290
Iteration: 27024/59290
Iteration: 27025/59290
Iteration: 27026/59290
Iteration: 27027/59290
Iteration: 27028/59290
Iteration: 27029/59290
Iteration: 27030/59290
Iteration: 27031/59290
Iteration: 27032/59290
Iteration: 27033/59290
Iteration: 27034/59290
Iteration: 27035/59290
Iteration: 27036/59290
Iteration: 27037/59290
Iteration: 27038/59290
Iteration: 27039/59290
Iteration: 27040/59290

 46%|████▌     | 27031/59290 [19:08<16:48, 32.00it/s]

Iteration: 27041/59290
Iteration: 27042/59290
Iteration: 27043/59290
Iteration: 27044/59290
Iteration: 27045/59290
Iteration: 27046/59290
Iteration: 27047/59290
Iteration: 27048/59290
Iteration: 27049/59290
Iteration: 27050/59290
Iteration: 27051/59290
Iteration: 27052/59290
Iteration: 27053/59290
Iteration: 27054/59290
Iteration: 27055/59290
Iteration: 27056/59290
Iteration: 27057/59290
Iteration: 27058/59290
Iteration: 27059/59290
Iteration: 27060/59290
Iteration: 27061/59290
Iteration: 27062/59290
Iteration: 27063/59290
Iteration: 27064/59290

 46%|████▌     | 27055/59290 [19:09<14:09, 37.94it/s]

Iteration: 27065/59290
Iteration: 27066/59290
Iteration: 27067/59290
Iteration: 27068/59290
Iteration: 27069/59290
Iteration: 27070/59290
Iteration: 27071/59290
Iteration: 27072/59290
Iteration: 27073/59290
Iteration: 27074/59290
Iteration: 27075/59290
Iteration: 27076/59290
Iteration: 27077/59290
Iteration: 27078/59290
Iteration: 27079/59290
Iteration: 27080/59290
Iteration: 27081/59290
Iteration: 27082/59290
Iteration: 27083/59290
Iteration: 27084/59290
Iteration: 27085/59290
Iteration: 27086/59290
Iteration: 27087/59290
Iteration: 27088/59290

 46%|████▌     | 27079/59290 [19:10<20:45, 25.85it/s]

Iteration: 27089/59290
Iteration: 27090/59290
Iteration: 27091/59290
Iteration: 27092/59290
Iteration: 27093/59290
Iteration: 27094/59290
Iteration: 27095/59290
Iteration: 27096/59290
Iteration: 27097/59290
Iteration: 27098/59290
Iteration: 27099/59290
Iteration: 27100/59290
Iteration: 27101/59290
Iteration: 27102/59290
Iteration: 27103/59290
Iteration: 27104/59290
Iteration: 27105/59290
Iteration: 27106/59290
Iteration: 27107/59290
Iteration: 27108/59290
Iteration: 27109/59290
Iteration: 27110/59290
Iteration: 27111/59290
Iteration: 27112/59290

 46%|████▌     | 27103/59290 [19:13<32:11, 16.66it/s]

Iteration: 27113/59290
Iteration: 27114/59290
Iteration: 27115/59290
Iteration: 27116/59290
Iteration: 27117/59290
Iteration: 27118/59290
Iteration: 27119/59290
Iteration: 27120/59290
Iteration: 27121/59290
Iteration: 27122/59290
Iteration: 27123/59290
Iteration: 27124/59290
Iteration: 27125/59290
Iteration: 27126/59290
Iteration: 27127/59290
Iteration: 27128/59290
Iteration: 27129/59290
Iteration: 27130/59290
Iteration: 27131/59290
Iteration: 27132/59290
Iteration: 27133/59290
Iteration: 27134/59290
Iteration: 27135/59290
Iteration: 27136/59290

 46%|████▌     | 27127/59290 [19:13<25:06, 21.35it/s]

Iteration: 27137/59290
Iteration: 27138/59290
Iteration: 27139/59290
Iteration: 27140/59290
Iteration: 27141/59290
Iteration: 27142/59290
Iteration: 27143/59290
Iteration: 27144/59290
Iteration: 27145/59290
Iteration: 27146/59290
Iteration: 27147/59290
Iteration: 27148/59290
Iteration: 27149/59290
Iteration: 27150/59290
Iteration: 27151/59290
Iteration: 27152/59290
Iteration: 27153/59290
Iteration: 27154/59290
Iteration: 27155/59290
Iteration: 27156/59290
Iteration: 27157/59290
Iteration: 27158/59290
Iteration: 27159/59290
Iteration: 27160/59290

 46%|████▌     | 27151/59290 [19:14<20:08, 26.58it/s]

Iteration: 27161/59290
Iteration: 27162/59290
Iteration: 27163/59290
Iteration: 27164/59290
Iteration: 27165/59290
Iteration: 27166/59290
Iteration: 27167/59290
Iteration: 27168/59290
Iteration: 27169/59290
Iteration: 27170/59290
Iteration: 27171/59290
Iteration: 27172/59290
Iteration: 27173/59290
Iteration: 27174/59290
Iteration: 27175/59290
Iteration: 27176/59290
Iteration: 27177/59290
Iteration: 27178/59290
Iteration: 27179/59290
Iteration: 27180/59290
Iteration: 27181/59290
Iteration: 27182/59290
Iteration: 27183/59290
Iteration: 27184/59290

 46%|████▌     | 27175/59290 [19:14<16:41, 32.06it/s]

Iteration: 27185/59290
Iteration: 27186/59290
Iteration: 27187/59290
Iteration: 27188/59290
Iteration: 27189/59290
Iteration: 27190/59290
Iteration: 27191/59290
Iteration: 27192/59290
Iteration: 27193/59290
Iteration: 27194/59290
Iteration: 27195/59290
Iteration: 27196/59290
Iteration: 27197/59290
Iteration: 27198/59290
Iteration: 27199/59290
Iteration: 27200/59290
Iteration: 27201/59290
Iteration: 27202/59290
Iteration: 27203/59290
Iteration: 27204/59290
Iteration: 27205/59290
Iteration: 27206/59290
Iteration: 27207/59290
Iteration: 27208/59290

 46%|████▌     | 27199/59290 [19:15<21:19, 25.07it/s]

Iteration: 27209/59290
Iteration: 27210/59290
Iteration: 27211/59290
Iteration: 27212/59290
Iteration: 27213/59290
Iteration: 27214/59290
Iteration: 27215/59290
Iteration: 27216/59290
Iteration: 27217/59290
Iteration: 27218/59290
Iteration: 27219/59290
Iteration: 27220/59290
Iteration: 27221/59290
Iteration: 27222/59290
Iteration: 27223/59290
Iteration: 27224/59290
Iteration: 27225/59290
Iteration: 27226/59290
Iteration: 27227/59290
Iteration: 27228/59290
Iteration: 27229/59290
Iteration: 27230/59290
Iteration: 27231/59290
Iteration: 27232/59290

 46%|████▌     | 27223/59290 [19:17<29:15, 18.27it/s]

Iteration: 27233/59290
Iteration: 27234/59290
Iteration: 27235/59290
Iteration: 27236/59290
Iteration: 27237/59290
Iteration: 27238/59290
Iteration: 27239/59290
Iteration: 27240/59290
Iteration: 27241/59290
Iteration: 27242/59290
Iteration: 27243/59290
Iteration: 27244/59290
Iteration: 27245/59290
Iteration: 27246/59290
Iteration: 27247/59290
Iteration: 27248/59290
Iteration: 27249/59290
Iteration: 27250/59290
Iteration: 27251/59290
Iteration: 27252/59290
Iteration: 27253/59290
Iteration: 27254/59290
Iteration: 27255/59290
Iteration: 27256/59290

 46%|████▌     | 27247/59290 [19:18<23:39, 22.58it/s]

Iteration: 27257/59290
Iteration: 27258/59290
Iteration: 27259/59290
Iteration: 27260/59290
Iteration: 27261/59290
Iteration: 27262/59290
Iteration: 27263/59290
Iteration: 27264/59290
Iteration: 27265/59290
Iteration: 27266/59290
Iteration: 27267/59290
Iteration: 27268/59290
Iteration: 27269/59290
Iteration: 27270/59290
Iteration: 27271/59290
Iteration: 27272/59290
Iteration: 27273/59290
Iteration: 27274/59290
Iteration: 27275/59290
Iteration: 27276/59290
Iteration: 27277/59290
Iteration: 27278/59290
Iteration: 27279/59290
Iteration: 27280/59290

 46%|████▌     | 27271/59290 [19:18<19:05, 27.95it/s]

Iteration: 27281/59290
Iteration: 27282/59290
Iteration: 27283/59290
Iteration: 27284/59290
Iteration: 27285/59290
Iteration: 27286/59290
Iteration: 27287/59290
Iteration: 27288/59290
Iteration: 27289/59290
Iteration: 27290/59290
Iteration: 27291/59290
Iteration: 27292/59290
Iteration: 27293/59290
Iteration: 27294/59290
Iteration: 27295/59290
Iteration: 27296/59290
Iteration: 27297/59290
Iteration: 27298/59290
Iteration: 27299/59290
Iteration: 27300/59290
Iteration: 27301/59290
Iteration: 27302/59290
Iteration: 27303/59290
Iteration: 27304/59290

 46%|████▌     | 27295/59290 [19:19<15:54, 33.51it/s]

Iteration: 27305/59290
Iteration: 27306/59290
Iteration: 27307/59290
Iteration: 27308/59290
Iteration: 27309/59290
Iteration: 27310/59290
Iteration: 27311/59290
Iteration: 27312/59290
Iteration: 27313/59290
Iteration: 27314/59290
Iteration: 27315/59290
Iteration: 27316/59290
Iteration: 27317/59290
Iteration: 27318/59290
Iteration: 27319/59290
Iteration: 27320/59290
Iteration: 27321/59290
Iteration: 27322/59290
Iteration: 27323/59290
Iteration: 27324/59290
Iteration: 27325/59290
Iteration: 27326/59290
Iteration: 27327/59290
Iteration: 27328/59290

 46%|████▌     | 27319/59290 [19:19<13:44, 38.78it/s]

Iteration: 27329/59290
Iteration: 27330/59290
Iteration: 27331/59290
Iteration: 27332/59290
Iteration: 27333/59290
Iteration: 27334/59290
Iteration: 27335/59290
Iteration: 27336/59290
Iteration: 27337/59290
Iteration: 27338/59290
Iteration: 27339/59290
Iteration: 27340/59290
Iteration: 27341/59290
Iteration: 27342/59290
Iteration: 27343/59290
Iteration: 27344/59290
Iteration: 27345/59290
Iteration: 27346/59290
Iteration: 27347/59290
Iteration: 27348/59290
Iteration: 27349/59290
Iteration: 27350/59290
Iteration: 27351/59290
Iteration: 27352/59290

 46%|████▌     | 27343/59290 [19:20<12:11, 43.69it/s]

Iteration: 27353/59290
Iteration: 27354/59290
Iteration: 27355/59290
Iteration: 27356/59290
Iteration: 27357/59290
Iteration: 27358/59290
Iteration: 27359/59290
Iteration: 27360/59290
Iteration: 27361/59290
Iteration: 27362/59290
Iteration: 27363/59290
Iteration: 27364/59290
Iteration: 27365/59290
Iteration: 27366/59290
Iteration: 27367/59290
Iteration: 27368/59290
Iteration: 27369/59290
Iteration: 27370/59290
Iteration: 27371/59290
Iteration: 27372/59290
Iteration: 27373/59290
Iteration: 27374/59290
Iteration: 27375/59290
Iteration: 27376/59290

 46%|████▌     | 27367/59290 [19:20<11:02, 48.16it/s]

Iteration: 27377/59290
Iteration: 27378/59290
Iteration: 27379/59290
Iteration: 27380/59290
Iteration: 27381/59290
Iteration: 27382/59290
Iteration: 27383/59290
Iteration: 27384/59290
Iteration: 27385/59290
Iteration: 27386/59290
Iteration: 27387/59290
Iteration: 27388/59290
Iteration: 27389/59290
Iteration: 27390/59290
Iteration: 27391/59290
Iteration: 27392/59290
Iteration: 27393/59290
Iteration: 27394/59290
Iteration: 27395/59290
Iteration: 27396/59290
Iteration: 27397/59290
Iteration: 27398/59290
Iteration: 27399/59290
Iteration: 27400/59290

 46%|████▌     | 27391/59290 [19:20<10:15, 51.83it/s]

Iteration: 27401/59290
Iteration: 27402/59290
Iteration: 27403/59290
Iteration: 27404/59290
Iteration: 27405/59290
Iteration: 27406/59290
Iteration: 27407/59290
Iteration: 27408/59290
Iteration: 27409/59290
Iteration: 27410/59290
Iteration: 27411/59290
Iteration: 27412/59290
Iteration: 27413/59290
Iteration: 27414/59290
Iteration: 27415/59290
Iteration: 27416/59290
Iteration: 27417/59290
Iteration: 27418/59290
Iteration: 27419/59290
Iteration: 27420/59290
Iteration: 27421/59290
Iteration: 27422/59290
Iteration: 27423/59290
Iteration: 27424/59290

 46%|████▌     | 27415/59290 [19:21<09:41, 54.85it/s]

Iteration: 27425/59290
Iteration: 27426/59290
Iteration: 27427/59290
Iteration: 27428/59290
Iteration: 27429/59290
Iteration: 27430/59290
Iteration: 27431/59290
Iteration: 27432/59290
Iteration: 27433/59290
Iteration: 27434/59290
Iteration: 27435/59290
Iteration: 27436/59290
Iteration: 27437/59290
Iteration: 27438/59290
Iteration: 27439/59290
Iteration: 27440/59290
Iteration: 27441/59290
Iteration: 27442/59290
Iteration: 27443/59290
Iteration: 27444/59290
Iteration: 27445/59290
Iteration: 27446/59290
Iteration: 27447/59290
Iteration: 27448/59290

 46%|████▋     | 27439/59290 [19:21<09:26, 56.27it/s]

Iteration: 27449/59290
Iteration: 27450/59290
Iteration: 27451/59290
Iteration: 27452/59290
Iteration: 27453/59290
Iteration: 27454/59290
Iteration: 27455/59290
Iteration: 27456/59290
Iteration: 27457/59290
Iteration: 27458/59290
Iteration: 27459/59290
Iteration: 27460/59290
Iteration: 27461/59290
Iteration: 27462/59290
Iteration: 27463/59290
Iteration: 27464/59290
Iteration: 27465/59290
Iteration: 27466/59290
Iteration: 27467/59290
Iteration: 27468/59290
Iteration: 27469/59290
Iteration: 27470/59290
Iteration: 27471/59290
Iteration: 27472/59290

 46%|████▋     | 27463/59290 [19:23<17:06, 31.01it/s]

Iteration: 27473/59290
Iteration: 27474/59290
Iteration: 27475/59290
Iteration: 27476/59290
Iteration: 27477/59290
Iteration: 27478/59290
Iteration: 27479/59290
Iteration: 27480/59290
Iteration: 27481/59290
Iteration: 27482/59290
Iteration: 27483/59290
Iteration: 27484/59290
Iteration: 27485/59290
Iteration: 27486/59290
Iteration: 27487/59290
Iteration: 27488/59290
Iteration: 27489/59290
Iteration: 27490/59290
Iteration: 27491/59290
Iteration: 27492/59290
Iteration: 27493/59290
Iteration: 27494/59290
Iteration: 27495/59290
Iteration: 27496/59290

 46%|████▋     | 27487/59290 [19:25<26:36, 19.92it/s]

Iteration: 27497/59290
Iteration: 27498/59290
Iteration: 27499/59290
Iteration: 27500/59290
Iteration: 27501/59290
Iteration: 27502/59290
Iteration: 27503/59290
Iteration: 27504/59290
Iteration: 27505/59290
Iteration: 27506/59290
Iteration: 27507/59290
Iteration: 27508/59290
Iteration: 27509/59290
Iteration: 27510/59290
Iteration: 27511/59290
Iteration: 27512/59290
Iteration: 27513/59290
Iteration: 27514/59290
Iteration: 27515/59290
Iteration: 27516/59290
Iteration: 27517/59290
Iteration: 27518/59290
Iteration: 27519/59290
Iteration: 27520/59290

 46%|████▋     | 27511/59290 [19:26<23:08, 22.89it/s]

Iteration: 27521/59290
Iteration: 27522/59290
Iteration: 27523/59290
Iteration: 27524/59290
Iteration: 27525/59290
Iteration: 27526/59290
Iteration: 27527/59290
Iteration: 27528/59290
Iteration: 27529/59290
Iteration: 27530/59290
Iteration: 27531/59290
Iteration: 27532/59290
Iteration: 27533/59290
Iteration: 27534/59290
Iteration: 27535/59290
Iteration: 27536/59290
Iteration: 27537/59290
Iteration: 27538/59290
Iteration: 27539/59290
Iteration: 27540/59290
Iteration: 27541/59290
Iteration: 27542/59290
Iteration: 27543/59290
Iteration: 27544/59290

 46%|████▋     | 27535/59290 [19:26<18:39, 28.36it/s]

Iteration: 27545/59290
Iteration: 27546/59290
Iteration: 27547/59290
Iteration: 27548/59290
Iteration: 27549/59290
Iteration: 27550/59290
Iteration: 27551/59290
Iteration: 27552/59290
Iteration: 27553/59290
Iteration: 27554/59290
Iteration: 27555/59290
Iteration: 27556/59290
Iteration: 27557/59290
Iteration: 27558/59290
Iteration: 27559/59290
Iteration: 27560/59290
Iteration: 27561/59290
Iteration: 27562/59290
Iteration: 27563/59290
Iteration: 27564/59290
Iteration: 27565/59290
Iteration: 27566/59290
Iteration: 27567/59290
Iteration: 27568/59290

 46%|████▋     | 27559/59290 [19:26<15:33, 34.00it/s]

Iteration: 27569/59290
Iteration: 27570/59290
Iteration: 27571/59290
Iteration: 27572/59290
Iteration: 27573/59290
Iteration: 27574/59290
Iteration: 27575/59290
Iteration: 27576/59290
Iteration: 27577/59290
Iteration: 27578/59290
Iteration: 27579/59290
Iteration: 27580/59290
Iteration: 27581/59290
Iteration: 27582/59290
Iteration: 27583/59290
Iteration: 27584/59290
Iteration: 27585/59290
Iteration: 27586/59290
Iteration: 27587/59290
Iteration: 27588/59290
Iteration: 27589/59290
Iteration: 27590/59290
Iteration: 27591/59290
Iteration: 27592/59290

 47%|████▋     | 27583/59290 [19:27<13:22, 39.51it/s]

Iteration: 27593/59290
Iteration: 27594/59290
Iteration: 27595/59290
Iteration: 27596/59290
Iteration: 27597/59290
Iteration: 27598/59290
Iteration: 27599/59290
Iteration: 27600/59290
Iteration: 27601/59290
Iteration: 27602/59290
Iteration: 27603/59290
Iteration: 27604/59290
Iteration: 27605/59290
Iteration: 27606/59290
Iteration: 27607/59290
Iteration: 27608/59290
Iteration: 27609/59290
Iteration: 27610/59290
Iteration: 27611/59290
Iteration: 27612/59290
Iteration: 27613/59290
Iteration: 27614/59290
Iteration: 27615/59290
Iteration: 27616/59290

 47%|████▋     | 27607/59290 [19:27<11:54, 44.34it/s]

Iteration: 27617/59290
Iteration: 27618/59290
Iteration: 27619/59290
Iteration: 27620/59290
Iteration: 27621/59290
Iteration: 27622/59290
Iteration: 27623/59290
Iteration: 27624/59290
Iteration: 27625/59290
Iteration: 27626/59290
Iteration: 27627/59290
Iteration: 27628/59290
Iteration: 27629/59290
Iteration: 27630/59290
Iteration: 27631/59290
Iteration: 27632/59290
Iteration: 27633/59290
Iteration: 27634/59290
Iteration: 27635/59290
Iteration: 27636/59290
Iteration: 27637/59290
Iteration: 27638/59290
Iteration: 27639/59290
Iteration: 27640/59290

 47%|████▋     | 27631/59290 [19:27<10:47, 48.92it/s]

Iteration: 27641/59290
Iteration: 27642/59290
Iteration: 27643/59290
Iteration: 27644/59290
Iteration: 27645/59290
Iteration: 27646/59290
Iteration: 27647/59290
Iteration: 27648/59290
Iteration: 27649/59290
Iteration: 27650/59290
Iteration: 27651/59290
Iteration: 27652/59290
Iteration: 27653/59290
Iteration: 27654/59290
Iteration: 27655/59290
Iteration: 27656/59290
Iteration: 27657/59290
Iteration: 27658/59290
Iteration: 27659/59290
Iteration: 27660/59290
Iteration: 27661/59290
Iteration: 27662/59290
Iteration: 27663/59290
Iteration: 27664/59290

 47%|████▋     | 27655/59290 [19:28<10:04, 52.37it/s]

Iteration: 27665/59290
Iteration: 27666/59290
Iteration: 27667/59290
Iteration: 27668/59290
Iteration: 27669/59290
Iteration: 27670/59290
Iteration: 27671/59290
Iteration: 27672/59290
Iteration: 27673/59290
Iteration: 27674/59290
Iteration: 27675/59290
Iteration: 27676/59290
Iteration: 27677/59290
Iteration: 27678/59290
Iteration: 27679/59290
Iteration: 27680/59290
Iteration: 27681/59290
Iteration: 27682/59290
Iteration: 27683/59290
Iteration: 27684/59290
Iteration: 27685/59290
Iteration: 27686/59290
Iteration: 27687/59290
Iteration: 27688/59290

 47%|████▋     | 27679/59290 [19:28<09:33, 55.17it/s]

Iteration: 27689/59290
Iteration: 27690/59290
Iteration: 27691/59290
Iteration: 27692/59290
Iteration: 27693/59290
Iteration: 27694/59290
Iteration: 27695/59290
Iteration: 27696/59290
Iteration: 27697/59290
Iteration: 27698/59290
Iteration: 27699/59290
Iteration: 27700/59290
Iteration: 27701/59290
Iteration: 27702/59290
Iteration: 27703/59290
Iteration: 27704/59290
Iteration: 27705/59290
Iteration: 27706/59290
Iteration: 27707/59290
Iteration: 27708/59290
Iteration: 27709/59290
Iteration: 27710/59290
Iteration: 27711/59290
Iteration: 27712/59290

 47%|████▋     | 27703/59290 [19:29<09:19, 56.48it/s]

Iteration: 27713/59290
Iteration: 27714/59290
Iteration: 27715/59290
Iteration: 27716/59290
Iteration: 27717/59290
Iteration: 27718/59290
Iteration: 27719/59290
Iteration: 27720/59290
Iteration: 27721/59290
Iteration: 27722/59290
Iteration: 27723/59290
Iteration: 27724/59290
Iteration: 27725/59290
Iteration: 27726/59290
Iteration: 27727/59290
Iteration: 27728/59290
Iteration: 27729/59290
Iteration: 27730/59290
Iteration: 27731/59290
Iteration: 27732/59290
Iteration: 27733/59290
Iteration: 27734/59290
Iteration: 27735/59290
Iteration: 27736/59290

 47%|████▋     | 27727/59290 [19:29<08:59, 58.50it/s]

Iteration: 27737/59290
Iteration: 27738/59290
Iteration: 27739/59290
Iteration: 27740/59290
Iteration: 27741/59290
Iteration: 27742/59290
Iteration: 27743/59290
Iteration: 27744/59290
Iteration: 27745/59290
Iteration: 27746/59290
Iteration: 27747/59290
Iteration: 27748/59290
Iteration: 27749/59290
Iteration: 27750/59290
Iteration: 27751/59290
Iteration: 27752/59290
Iteration: 27753/59290
Iteration: 27754/59290
Iteration: 27755/59290
Iteration: 27756/59290
Iteration: 27757/59290
Iteration: 27758/59290
Iteration: 27759/59290
Iteration: 27760/59290

 47%|████▋     | 27751/59290 [19:29<08:58, 58.57it/s]

Iteration: 27761/59290
Iteration: 27762/59290
Iteration: 27763/59290
Iteration: 27764/59290
Iteration: 27765/59290
Iteration: 27766/59290
Iteration: 27767/59290
Iteration: 27768/59290
Iteration: 27769/59290
Iteration: 27770/59290
Iteration: 27771/59290
Iteration: 27772/59290
Iteration: 27773/59290
Iteration: 27774/59290
Iteration: 27775/59290
Iteration: 27776/59290
Iteration: 27777/59290
Iteration: 27778/59290
Iteration: 27779/59290
Iteration: 27780/59290
Iteration: 27781/59290
Iteration: 27782/59290
Iteration: 27783/59290
Iteration: 27784/59290

 47%|████▋     | 27775/59290 [19:31<16:44, 31.39it/s]

Iteration: 27785/59290
Iteration: 27786/59290
Iteration: 27787/59290
Iteration: 27788/59290
Iteration: 27789/59290
Iteration: 27790/59290
Iteration: 27791/59290
Iteration: 27792/59290
Iteration: 27793/59290
Iteration: 27794/59290
Iteration: 27795/59290
Iteration: 27796/59290
Iteration: 27797/59290
Iteration: 27798/59290
Iteration: 27799/59290
Iteration: 27800/59290
Iteration: 27801/59290
Iteration: 27802/59290
Iteration: 27803/59290
Iteration: 27804/59290
Iteration: 27805/59290
Iteration: 27806/59290
Iteration: 27807/59290
Iteration: 27808/59290

 47%|████▋     | 27799/59290 [19:33<26:43, 19.64it/s]

Iteration: 27809/59290
Iteration: 27810/59290
Iteration: 27811/59290
Iteration: 27812/59290
Iteration: 27813/59290
Iteration: 27814/59290
Iteration: 27815/59290
Iteration: 27816/59290
Iteration: 27817/59290
Iteration: 27818/59290
Iteration: 27819/59290
Iteration: 27820/59290
Iteration: 27821/59290
Iteration: 27822/59290
Iteration: 27823/59290
Iteration: 27824/59290
Iteration: 27825/59290
Iteration: 27826/59290
Iteration: 27827/59290
Iteration: 27828/59290
Iteration: 27829/59290
Iteration: 27830/59290
Iteration: 27831/59290
Iteration: 27832/59290

 47%|████▋     | 27823/59290 [19:34<22:28, 23.34it/s]

Iteration: 27833/59290
Iteration: 27834/59290
Iteration: 27835/59290
Iteration: 27836/59290
Iteration: 27837/59290
Iteration: 27838/59290
Iteration: 27839/59290
Iteration: 27840/59290
Iteration: 27841/59290
Iteration: 27842/59290
Iteration: 27843/59290
Iteration: 27844/59290
Iteration: 27845/59290
Iteration: 27846/59290
Iteration: 27847/59290
Iteration: 27848/59290
Iteration: 27849/59290
Iteration: 27850/59290
Iteration: 27851/59290
Iteration: 27852/59290
Iteration: 27853/59290
Iteration: 27854/59290
Iteration: 27855/59290
Iteration: 27856/59290

 47%|████▋     | 27847/59290 [19:34<18:13, 28.76it/s]

Iteration: 27857/59290
Iteration: 27858/59290
Iteration: 27859/59290
Iteration: 27860/59290
Iteration: 27861/59290
Iteration: 27862/59290
Iteration: 27863/59290
Iteration: 27864/59290
Iteration: 27865/59290
Iteration: 27866/59290
Iteration: 27867/59290
Iteration: 27868/59290
Iteration: 27869/59290
Iteration: 27870/59290
Iteration: 27871/59290
Iteration: 27872/59290
Iteration: 27873/59290
Iteration: 27874/59290
Iteration: 27875/59290
Iteration: 27876/59290
Iteration: 27877/59290
Iteration: 27878/59290
Iteration: 27879/59290
Iteration: 27880/59290

 47%|████▋     | 27871/59290 [19:35<15:23, 34.02it/s]

Iteration: 27881/59290
Iteration: 27882/59290
Iteration: 27883/59290
Iteration: 27884/59290
Iteration: 27885/59290
Iteration: 27886/59290
Iteration: 27887/59290
Iteration: 27888/59290
Iteration: 27889/59290
Iteration: 27890/59290
Iteration: 27891/59290
Iteration: 27892/59290
Iteration: 27893/59290
Iteration: 27894/59290
Iteration: 27895/59290
Iteration: 27896/59290
Iteration: 27897/59290
Iteration: 27898/59290
Iteration: 27899/59290
Iteration: 27900/59290
Iteration: 27901/59290
Iteration: 27902/59290
Iteration: 27903/59290
Iteration: 27904/59290

 47%|████▋     | 27895/59290 [19:35<13:19, 39.29it/s]

Iteration: 27905/59290
Iteration: 27906/59290
Iteration: 27907/59290
Iteration: 27908/59290
Iteration: 27909/59290
Iteration: 27910/59290
Iteration: 27911/59290
Iteration: 27912/59290
Iteration: 27913/59290
Iteration: 27914/59290
Iteration: 27915/59290
Iteration: 27916/59290
Iteration: 27917/59290
Iteration: 27918/59290
Iteration: 27919/59290
Iteration: 27920/59290
Iteration: 27921/59290
Iteration: 27922/59290
Iteration: 27923/59290
Iteration: 27924/59290
Iteration: 27925/59290
Iteration: 27926/59290
Iteration: 27927/59290
Iteration: 27928/59290

 47%|████▋     | 27919/59290 [19:35<12:12, 42.83it/s]

Iteration: 27929/59290
Iteration: 27930/59290
Iteration: 27931/59290
Iteration: 27932/59290
Iteration: 27933/59290
Iteration: 27934/59290
Iteration: 27935/59290
Iteration: 27936/59290
Iteration: 27937/59290
Iteration: 27938/59290
Iteration: 27939/59290
Iteration: 27940/59290
Iteration: 27941/59290
Iteration: 27942/59290
Iteration: 27943/59290
Iteration: 27944/59290
Iteration: 27945/59290
Iteration: 27946/59290
Iteration: 27947/59290
Iteration: 27948/59290
Iteration: 27949/59290
Iteration: 27950/59290
Iteration: 27951/59290
Iteration: 27952/59290

 47%|████▋     | 27943/59290 [19:37<18:19, 28.52it/s]

Iteration: 27953/59290
Iteration: 27954/59290
Iteration: 27955/59290
Iteration: 27956/59290
Iteration: 27957/59290
Iteration: 27958/59290
Iteration: 27959/59290
Iteration: 27960/59290
Iteration: 27961/59290
Iteration: 27962/59290
Iteration: 27963/59290
Iteration: 27964/59290
Iteration: 27965/59290
Iteration: 27966/59290
Iteration: 27967/59290
Iteration: 27968/59290
Iteration: 27969/59290
Iteration: 27970/59290
Iteration: 27971/59290
Iteration: 27972/59290
Iteration: 27973/59290
Iteration: 27974/59290
Iteration: 27975/59290
Iteration: 27976/59290

 47%|████▋     | 27967/59290 [19:40<29:51, 17.49it/s]

Iteration: 27977/59290
Iteration: 27978/59290
Iteration: 27979/59290
Iteration: 27980/59290
Iteration: 27981/59290
Iteration: 27982/59290
Iteration: 27983/59290
Iteration: 27984/59290
Iteration: 27985/59290
Iteration: 27986/59290
Iteration: 27987/59290
Iteration: 27988/59290
Iteration: 27989/59290
Iteration: 27990/59290
Iteration: 27991/59290
Iteration: 27992/59290
Iteration: 27993/59290
Iteration: 27994/59290
Iteration: 27995/59290
Iteration: 27996/59290
Iteration: 27997/59290
Iteration: 27998/59290
Iteration: 27999/59290
Iteration: 28000/59290

 47%|████▋     | 27991/59290 [19:40<23:29, 22.21it/s]

Iteration: 28001/59290
Iteration: 28002/59290
Iteration: 28003/59290
Iteration: 28004/59290
Iteration: 28005/59290
Iteration: 28006/59290
Iteration: 28007/59290
Iteration: 28008/59290
Iteration: 28009/59290
Iteration: 28010/59290
Iteration: 28011/59290
Iteration: 28012/59290
Iteration: 28013/59290
Iteration: 28014/59290
Iteration: 28015/59290
Iteration: 28016/59290
Iteration: 28017/59290
Iteration: 28018/59290
Iteration: 28019/59290
Iteration: 28020/59290
Iteration: 28021/59290
Iteration: 28022/59290
Iteration: 28023/59290
Iteration: 28024/59290

 47%|████▋     | 28015/59290 [19:40<19:00, 27.43it/s]

Iteration: 28025/59290
Iteration: 28026/59290
Iteration: 28027/59290
Iteration: 28028/59290
Iteration: 28029/59290
Iteration: 28030/59290
Iteration: 28031/59290
Iteration: 28032/59290
Iteration: 28033/59290
Iteration: 28034/59290
Iteration: 28035/59290
Iteration: 28036/59290
Iteration: 28037/59290
Iteration: 28038/59290
Iteration: 28039/59290
Iteration: 28040/59290
Iteration: 28041/59290
Iteration: 28042/59290
Iteration: 28043/59290
Iteration: 28044/59290
Iteration: 28045/59290
Iteration: 28046/59290
Iteration: 28047/59290
Iteration: 28048/59290

 47%|████▋     | 28039/59290 [19:42<24:33, 21.21it/s]

Iteration: 28049/59290
Iteration: 28050/59290
Iteration: 28051/59290
Iteration: 28052/59290
Iteration: 28053/59290
Iteration: 28054/59290
Iteration: 28055/59290
Iteration: 28056/59290
Iteration: 28057/59290
Iteration: 28058/59290
Iteration: 28059/59290
Iteration: 28060/59290
Iteration: 28061/59290
Iteration: 28062/59290
Iteration: 28063/59290
Iteration: 28064/59290
Iteration: 28065/59290
Iteration: 28066/59290
Iteration: 28067/59290
Iteration: 28068/59290
Iteration: 28069/59290
Iteration: 28070/59290
Iteration: 28071/59290
Iteration: 28072/59290

 47%|████▋     | 28063/59290 [19:45<34:29, 15.09it/s]

Iteration: 28073/59290
Iteration: 28074/59290
Iteration: 28075/59290
Iteration: 28076/59290
Iteration: 28077/59290
Iteration: 28078/59290
Iteration: 28079/59290
Iteration: 28080/59290
Iteration: 28081/59290
Iteration: 28082/59290
Iteration: 28083/59290
Iteration: 28084/59290
Iteration: 28085/59290
Iteration: 28086/59290
Iteration: 28087/59290
Iteration: 28088/59290
Iteration: 28089/59290
Iteration: 28090/59290
Iteration: 28091/59290
Iteration: 28092/59290
Iteration: 28093/59290
Iteration: 28094/59290
Iteration: 28095/59290
Iteration: 28096/59290

 47%|████▋     | 28087/59290 [19:45<26:48, 19.40it/s]

Iteration: 28097/59290
Iteration: 28098/59290
Iteration: 28099/59290
Iteration: 28100/59290
Iteration: 28101/59290
Iteration: 28102/59290
Iteration: 28103/59290
Iteration: 28104/59290
Iteration: 28105/59290
Iteration: 28106/59290
Iteration: 28107/59290
Iteration: 28108/59290
Iteration: 28109/59290
Iteration: 28110/59290
Iteration: 28111/59290
Iteration: 28112/59290
Iteration: 28113/59290
Iteration: 28114/59290
Iteration: 28115/59290
Iteration: 28116/59290
Iteration: 28117/59290
Iteration: 28118/59290
Iteration: 28119/59290
Iteration: 28120/59290

 47%|████▋     | 28111/59290 [19:46<21:12, 24.50it/s]

Iteration: 28121/59290
Iteration: 28122/59290
Iteration: 28123/59290
Iteration: 28124/59290
Iteration: 28125/59290
Iteration: 28126/59290
Iteration: 28127/59290
Iteration: 28128/59290
Iteration: 28129/59290
Iteration: 28130/59290
Iteration: 28131/59290
Iteration: 28132/59290
Iteration: 28133/59290
Iteration: 28134/59290
Iteration: 28135/59290
Iteration: 28136/59290
Iteration: 28137/59290
Iteration: 28138/59290
Iteration: 28139/59290
Iteration: 28140/59290
Iteration: 28141/59290
Iteration: 28142/59290
Iteration: 28143/59290
Iteration: 28144/59290

 47%|████▋     | 28135/59290 [19:46<17:18, 30.00it/s]

Iteration: 28145/59290
Iteration: 28146/59290
Iteration: 28147/59290
Iteration: 28148/59290
Iteration: 28149/59290
Iteration: 28150/59290
Iteration: 28151/59290
Iteration: 28152/59290
Iteration: 28153/59290
Iteration: 28154/59290
Iteration: 28155/59290
Iteration: 28156/59290
Iteration: 28157/59290
Iteration: 28158/59290
Iteration: 28159/59290
Iteration: 28160/59290
Iteration: 28161/59290
Iteration: 28162/59290
Iteration: 28163/59290
Iteration: 28164/59290
Iteration: 28165/59290
Iteration: 28166/59290
Iteration: 28167/59290
Iteration: 28168/59290

 47%|████▋     | 28159/59290 [19:46<14:38, 35.43it/s]

Iteration: 28169/59290
Iteration: 28170/59290
Iteration: 28171/59290
Iteration: 28172/59290
Iteration: 28173/59290
Iteration: 28174/59290
Iteration: 28175/59290
Iteration: 28176/59290
Iteration: 28177/59290
Iteration: 28178/59290
Iteration: 28179/59290
Iteration: 28180/59290
Iteration: 28181/59290
Iteration: 28182/59290
Iteration: 28183/59290
Iteration: 28184/59290
Iteration: 28185/59290
Iteration: 28186/59290
Iteration: 28187/59290
Iteration: 28188/59290
Iteration: 28189/59290
Iteration: 28190/59290
Iteration: 28191/59290
Iteration: 28192/59290

 48%|████▊     | 28183/59290 [19:47<12:43, 40.77it/s]

Iteration: 28193/59290
Iteration: 28194/59290
Iteration: 28195/59290
Iteration: 28196/59290
Iteration: 28197/59290
Iteration: 28198/59290
Iteration: 28199/59290
Iteration: 28200/59290
Iteration: 28201/59290
Iteration: 28202/59290
Iteration: 28203/59290
Iteration: 28204/59290
Iteration: 28205/59290
Iteration: 28206/59290
Iteration: 28207/59290
Iteration: 28208/59290
Iteration: 28209/59290
Iteration: 28210/59290
Iteration: 28211/59290
Iteration: 28212/59290
Iteration: 28213/59290
Iteration: 28214/59290
Iteration: 28215/59290
Iteration: 28216/59290

 48%|████▊     | 28207/59290 [19:47<11:23, 45.49it/s]

Iteration: 28217/59290
Iteration: 28218/59290
Iteration: 28219/59290
Iteration: 28220/59290
Iteration: 28221/59290
Iteration: 28222/59290
Iteration: 28223/59290
Iteration: 28224/59290
Iteration: 28225/59290
Iteration: 28226/59290
Iteration: 28227/59290
Iteration: 28228/59290
Iteration: 28229/59290
Iteration: 28230/59290
Iteration: 28231/59290
Iteration: 28232/59290
Iteration: 28233/59290
Iteration: 28234/59290
Iteration: 28235/59290
Iteration: 28236/59290
Iteration: 28237/59290
Iteration: 28238/59290
Iteration: 28239/59290
Iteration: 28240/59290

 48%|████▊     | 28231/59290 [19:47<10:24, 49.72it/s]

Iteration: 28241/59290
Iteration: 28242/59290
Iteration: 28243/59290
Iteration: 28244/59290
Iteration: 28245/59290
Iteration: 28246/59290
Iteration: 28247/59290
Iteration: 28248/59290
Iteration: 28249/59290
Iteration: 28250/59290
Iteration: 28251/59290
Iteration: 28252/59290
Iteration: 28253/59290
Iteration: 28254/59290
Iteration: 28255/59290
Iteration: 28256/59290
Iteration: 28257/59290
Iteration: 28258/59290
Iteration: 28259/59290
Iteration: 28260/59290
Iteration: 28261/59290
Iteration: 28262/59290
Iteration: 28263/59290
Iteration: 28264/59290

 48%|████▊     | 28255/59290 [19:48<09:42, 53.30it/s]

Iteration: 28265/59290
Iteration: 28266/59290
Iteration: 28267/59290
Iteration: 28268/59290
Iteration: 28269/59290
Iteration: 28270/59290
Iteration: 28271/59290
Iteration: 28272/59290
Iteration: 28273/59290
Iteration: 28274/59290
Iteration: 28275/59290
Iteration: 28276/59290
Iteration: 28277/59290
Iteration: 28278/59290
Iteration: 28279/59290
Iteration: 28280/59290
Iteration: 28281/59290
Iteration: 28282/59290
Iteration: 28283/59290
Iteration: 28284/59290
Iteration: 28285/59290
Iteration: 28286/59290
Iteration: 28287/59290
Iteration: 28288/59290

 48%|████▊     | 28279/59290 [19:48<09:15, 55.86it/s]

Iteration: 28289/59290
Iteration: 28290/59290
Iteration: 28291/59290
Iteration: 28292/59290
Iteration: 28293/59290
Iteration: 28294/59290
Iteration: 28295/59290
Iteration: 28296/59290
Iteration: 28297/59290
Iteration: 28298/59290
Iteration: 28299/59290
Iteration: 28300/59290
Iteration: 28301/59290
Iteration: 28302/59290
Iteration: 28303/59290
Iteration: 28304/59290
Iteration: 28305/59290
Iteration: 28306/59290
Iteration: 28307/59290
Iteration: 28308/59290
Iteration: 28309/59290
Iteration: 28310/59290
Iteration: 28311/59290
Iteration: 28312/59290

 48%|████▊     | 28303/59290 [19:50<16:22, 31.54it/s]

Iteration: 28313/59290
Iteration: 28314/59290
Iteration: 28315/59290
Iteration: 28316/59290
Iteration: 28317/59290
Iteration: 28318/59290
Iteration: 28319/59290
Iteration: 28320/59290
Iteration: 28321/59290
Iteration: 28322/59290
Iteration: 28323/59290
Iteration: 28324/59290
Iteration: 28325/59290
Iteration: 28326/59290
Iteration: 28327/59290
Iteration: 28328/59290
Iteration: 28329/59290
Iteration: 28330/59290
Iteration: 28331/59290
Iteration: 28332/59290
Iteration: 28333/59290
Iteration: 28334/59290
Iteration: 28335/59290
Iteration: 28336/59290

 48%|████▊     | 28327/59290 [19:52<25:35, 20.17it/s]

Iteration: 28337/59290
Iteration: 28338/59290
Iteration: 28339/59290
Iteration: 28340/59290
Iteration: 28341/59290
Iteration: 28342/59290
Iteration: 28343/59290
Iteration: 28344/59290
Iteration: 28345/59290
Iteration: 28346/59290
Iteration: 28347/59290
Iteration: 28348/59290
Iteration: 28349/59290
Iteration: 28350/59290
Iteration: 28351/59290
Iteration: 28352/59290
Iteration: 28353/59290
Iteration: 28354/59290
Iteration: 28355/59290
Iteration: 28356/59290
Iteration: 28357/59290
Iteration: 28358/59290
Iteration: 28359/59290
Iteration: 28360/59290

 48%|████▊     | 28351/59290 [19:53<21:50, 23.62it/s]

Iteration: 28361/59290
Iteration: 28362/59290
Iteration: 28363/59290
Iteration: 28364/59290
Iteration: 28365/59290
Iteration: 28366/59290
Iteration: 28367/59290
Iteration: 28368/59290
Iteration: 28369/59290
Iteration: 28370/59290
Iteration: 28371/59290
Iteration: 28372/59290
Iteration: 28373/59290
Iteration: 28374/59290
Iteration: 28375/59290
Iteration: 28376/59290
Iteration: 28377/59290
Iteration: 28378/59290
Iteration: 28379/59290
Iteration: 28380/59290
Iteration: 28381/59290
Iteration: 28382/59290
Iteration: 28383/59290
Iteration: 28384/59290

 48%|████▊     | 28375/59290 [19:53<17:42, 29.09it/s]

Iteration: 28385/59290
Iteration: 28386/59290
Iteration: 28387/59290
Iteration: 28388/59290
Iteration: 28389/59290
Iteration: 28390/59290
Iteration: 28391/59290
Iteration: 28392/59290
Iteration: 28393/59290
Iteration: 28394/59290
Iteration: 28395/59290
Iteration: 28396/59290
Iteration: 28397/59290
Iteration: 28398/59290
Iteration: 28399/59290
Iteration: 28400/59290
Iteration: 28401/59290
Iteration: 28402/59290
Iteration: 28403/59290
Iteration: 28404/59290
Iteration: 28405/59290
Iteration: 28406/59290
Iteration: 28407/59290
Iteration: 28408/59290

 48%|████▊     | 28399/59290 [19:53<14:51, 34.65it/s]

Iteration: 28409/59290
Iteration: 28410/59290
Iteration: 28411/59290
Iteration: 28412/59290
Iteration: 28413/59290
Iteration: 28414/59290
Iteration: 28415/59290
Iteration: 28416/59290
Iteration: 28417/59290
Iteration: 28418/59290
Iteration: 28419/59290
Iteration: 28420/59290
Iteration: 28421/59290
Iteration: 28422/59290
Iteration: 28423/59290
Iteration: 28424/59290
Iteration: 28425/59290
Iteration: 28426/59290
Iteration: 28427/59290
Iteration: 28428/59290
Iteration: 28429/59290
Iteration: 28430/59290
Iteration: 28431/59290
Iteration: 28432/59290

 48%|████▊     | 28423/59290 [19:54<12:46, 40.26it/s]

Iteration: 28433/59290
Iteration: 28434/59290
Iteration: 28435/59290
Iteration: 28436/59290
Iteration: 28437/59290
Iteration: 28438/59290
Iteration: 28439/59290
Iteration: 28440/59290
Iteration: 28441/59290
Iteration: 28442/59290
Iteration: 28443/59290
Iteration: 28444/59290
Iteration: 28445/59290
Iteration: 28446/59290
Iteration: 28447/59290
Iteration: 28448/59290
Iteration: 28449/59290
Iteration: 28450/59290
Iteration: 28451/59290
Iteration: 28452/59290
Iteration: 28453/59290
Iteration: 28454/59290
Iteration: 28455/59290
Iteration: 28456/59290

 48%|████▊     | 28447/59290 [19:54<11:20, 45.34it/s]

Iteration: 28457/59290
Iteration: 28458/59290
Iteration: 28459/59290
Iteration: 28460/59290
Iteration: 28461/59290
Iteration: 28462/59290
Iteration: 28463/59290
Iteration: 28464/59290
Iteration: 28465/59290
Iteration: 28466/59290
Iteration: 28467/59290
Iteration: 28468/59290
Iteration: 28469/59290
Iteration: 28470/59290
Iteration: 28471/59290
Iteration: 28472/59290
Iteration: 28473/59290
Iteration: 28474/59290
Iteration: 28475/59290
Iteration: 28476/59290
Iteration: 28477/59290
Iteration: 28478/59290
Iteration: 28479/59290
Iteration: 28480/59290

 48%|████▊     | 28471/59290 [19:54<10:20, 49.71it/s]

Iteration: 28481/59290
Iteration: 28482/59290
Iteration: 28483/59290
Iteration: 28484/59290
Iteration: 28485/59290
Iteration: 28486/59290
Iteration: 28487/59290
Iteration: 28488/59290
Iteration: 28489/59290
Iteration: 28490/59290
Iteration: 28491/59290
Iteration: 28492/59290
Iteration: 28493/59290
Iteration: 28494/59290
Iteration: 28495/59290
Iteration: 28496/59290
Iteration: 28497/59290
Iteration: 28498/59290
Iteration: 28499/59290
Iteration: 28500/59290
Iteration: 28501/59290
Iteration: 28502/59290
Iteration: 28503/59290
Iteration: 28504/59290

 48%|████▊     | 28495/59290 [19:55<09:48, 52.29it/s]

Iteration: 28505/59290
Iteration: 28506/59290
Iteration: 28507/59290
Iteration: 28508/59290
Iteration: 28509/59290
Iteration: 28510/59290
Iteration: 28511/59290
Iteration: 28512/59290
Iteration: 28513/59290
Iteration: 28514/59290
Iteration: 28515/59290
Iteration: 28516/59290
Iteration: 28517/59290
Iteration: 28518/59290
Iteration: 28519/59290
Iteration: 28520/59290
Iteration: 28521/59290
Iteration: 28522/59290
Iteration: 28523/59290
Iteration: 28524/59290
Iteration: 28525/59290
Iteration: 28526/59290
Iteration: 28527/59290
Iteration: 28528/59290

 48%|████▊     | 28519/59290 [19:55<09:14, 55.47it/s]

Iteration: 28529/59290
Iteration: 28530/59290
Iteration: 28531/59290
Iteration: 28532/59290
Iteration: 28533/59290
Iteration: 28534/59290
Iteration: 28535/59290
Iteration: 28536/59290
Iteration: 28537/59290
Iteration: 28538/59290
Iteration: 28539/59290
Iteration: 28540/59290
Iteration: 28541/59290
Iteration: 28542/59290
Iteration: 28543/59290
Iteration: 28544/59290
Iteration: 28545/59290
Iteration: 28546/59290
Iteration: 28547/59290
Iteration: 28548/59290
Iteration: 28549/59290
Iteration: 28550/59290
Iteration: 28551/59290
Iteration: 28552/59290

 48%|████▊     | 28543/59290 [19:56<08:53, 57.68it/s]

Iteration: 28553/59290
Iteration: 28554/59290
Iteration: 28555/59290
Iteration: 28556/59290
Iteration: 28557/59290
Iteration: 28558/59290
Iteration: 28559/59290
Iteration: 28560/59290
Iteration: 28561/59290
Iteration: 28562/59290
Iteration: 28563/59290
Iteration: 28564/59290
Iteration: 28565/59290
Iteration: 28566/59290
Iteration: 28567/59290
Iteration: 28568/59290
Iteration: 28569/59290
Iteration: 28570/59290
Iteration: 28571/59290
Iteration: 28572/59290
Iteration: 28573/59290
Iteration: 28574/59290
Iteration: 28575/59290
Iteration: 28576/59290

 48%|████▊     | 28567/59290 [19:56<08:35, 59.61it/s]

Iteration: 28577/59290
Iteration: 28578/59290
Iteration: 28579/59290
Iteration: 28580/59290
Iteration: 28581/59290
Iteration: 28582/59290
Iteration: 28583/59290
Iteration: 28584/59290
Iteration: 28585/59290
Iteration: 28586/59290
Iteration: 28587/59290
Iteration: 28588/59290
Iteration: 28589/59290
Iteration: 28590/59290
Iteration: 28591/59290
Iteration: 28592/59290
Iteration: 28593/59290
Iteration: 28594/59290
Iteration: 28595/59290
Iteration: 28596/59290
Iteration: 28597/59290
Iteration: 28598/59290
Iteration: 28599/59290
Iteration: 28600/59290

 48%|████▊     | 28591/59290 [19:56<08:24, 60.87it/s]

Iteration: 28601/59290
Iteration: 28602/59290
Iteration: 28603/59290
Iteration: 28604/59290
Iteration: 28605/59290
Iteration: 28606/59290
Iteration: 28607/59290
Iteration: 28608/59290
Iteration: 28609/59290
Iteration: 28610/59290
Iteration: 28611/59290
Iteration: 28612/59290
Iteration: 28613/59290
Iteration: 28614/59290
Iteration: 28615/59290
Iteration: 28616/59290
Iteration: 28617/59290
Iteration: 28618/59290
Iteration: 28619/59290
Iteration: 28620/59290
Iteration: 28621/59290
Iteration: 28622/59290
Iteration: 28623/59290
Iteration: 28624/59290

 48%|████▊     | 28615/59290 [19:58<16:41, 30.62it/s]

Iteration: 28625/59290
Iteration: 28626/59290
Iteration: 28627/59290
Iteration: 28628/59290
Iteration: 28629/59290
Iteration: 28630/59290
Iteration: 28631/59290
Iteration: 28632/59290
Iteration: 28633/59290
Iteration: 28634/59290
Iteration: 28635/59290
Iteration: 28636/59290
Iteration: 28637/59290
Iteration: 28638/59290
Iteration: 28639/59290
Iteration: 28640/59290
Iteration: 28641/59290
Iteration: 28642/59290
Iteration: 28643/59290
Iteration: 28644/59290
Iteration: 28645/59290
Iteration: 28646/59290
Iteration: 28647/59290
Iteration: 28648/59290

 48%|████▊     | 28639/59290 [20:00<26:01, 19.63it/s]

Iteration: 28649/59290
Iteration: 28650/59290
Iteration: 28651/59290
Iteration: 28652/59290
Iteration: 28653/59290
Iteration: 28654/59290
Iteration: 28655/59290
Iteration: 28656/59290
Iteration: 28657/59290
Iteration: 28658/59290
Iteration: 28659/59290
Iteration: 28660/59290
Iteration: 28661/59290
Iteration: 28662/59290
Iteration: 28663/59290
Iteration: 28664/59290
Iteration: 28665/59290
Iteration: 28666/59290
Iteration: 28667/59290
Iteration: 28668/59290
Iteration: 28669/59290
Iteration: 28670/59290
Iteration: 28671/59290
Iteration: 28672/59290

 48%|████▊     | 28663/59290 [20:01<23:12, 22.00it/s]

Iteration: 28673/59290
Iteration: 28674/59290
Iteration: 28675/59290
Iteration: 28676/59290
Iteration: 28677/59290
Iteration: 28678/59290
Iteration: 28679/59290
Iteration: 28680/59290
Iteration: 28681/59290
Iteration: 28682/59290
Iteration: 28683/59290
Iteration: 28684/59290
Iteration: 28685/59290
Iteration: 28686/59290
Iteration: 28687/59290
Iteration: 28688/59290
Iteration: 28689/59290
Iteration: 28690/59290
Iteration: 28691/59290
Iteration: 28692/59290
Iteration: 28693/59290
Iteration: 28694/59290
Iteration: 28695/59290
Iteration: 28696/59290

 48%|████▊     | 28687/59290 [20:01<18:44, 27.21it/s]

Iteration: 28697/59290
Iteration: 28698/59290
Iteration: 28699/59290
Iteration: 28700/59290
Iteration: 28701/59290
Iteration: 28702/59290
Iteration: 28703/59290
Iteration: 28704/59290
Iteration: 28705/59290
Iteration: 28706/59290
Iteration: 28707/59290
Iteration: 28708/59290
Iteration: 28709/59290
Iteration: 28710/59290
Iteration: 28711/59290
Iteration: 28712/59290
Iteration: 28713/59290
Iteration: 28714/59290
Iteration: 28715/59290
Iteration: 28716/59290
Iteration: 28717/59290
Iteration: 28718/59290
Iteration: 28719/59290
Iteration: 28720/59290

 48%|████▊     | 28711/59290 [20:02<15:33, 32.74it/s]

Iteration: 28721/59290
Iteration: 28722/59290
Iteration: 28723/59290
Iteration: 28724/59290
Iteration: 28725/59290
Iteration: 28726/59290
Iteration: 28727/59290
Iteration: 28728/59290
Iteration: 28729/59290
Iteration: 28730/59290
Iteration: 28731/59290
Iteration: 28732/59290
Iteration: 28733/59290
Iteration: 28734/59290
Iteration: 28735/59290
Iteration: 28736/59290
Iteration: 28737/59290
Iteration: 28738/59290
Iteration: 28739/59290
Iteration: 28740/59290
Iteration: 28741/59290
Iteration: 28742/59290
Iteration: 28743/59290
Iteration: 28744/59290

 48%|████▊     | 28735/59290 [20:02<13:18, 38.27it/s]

Iteration: 28745/59290
Iteration: 28746/59290
Iteration: 28747/59290
Iteration: 28748/59290
Iteration: 28749/59290
Iteration: 28750/59290
Iteration: 28751/59290
Iteration: 28752/59290
Iteration: 28753/59290
Iteration: 28754/59290
Iteration: 28755/59290
Iteration: 28756/59290
Iteration: 28757/59290
Iteration: 28758/59290
Iteration: 28759/59290
Iteration: 28760/59290
Iteration: 28761/59290
Iteration: 28762/59290
Iteration: 28763/59290
Iteration: 28764/59290
Iteration: 28765/59290
Iteration: 28766/59290
Iteration: 28767/59290
Iteration: 28768/59290

 49%|████▊     | 28759/59290 [20:04<19:51, 25.62it/s]

Iteration: 28769/59290
Iteration: 28770/59290
Iteration: 28771/59290
Iteration: 28772/59290
Iteration: 28773/59290
Iteration: 28774/59290
Iteration: 28775/59290
Iteration: 28776/59290
Iteration: 28777/59290
Iteration: 28778/59290
Iteration: 28779/59290
Iteration: 28780/59290
Iteration: 28781/59290
Iteration: 28782/59290
Iteration: 28783/59290
Iteration: 28784/59290
Iteration: 28785/59290
Iteration: 28786/59290
Iteration: 28787/59290
Iteration: 28788/59290
Iteration: 28789/59290
Iteration: 28790/59290
Iteration: 28791/59290
Iteration: 28792/59290

 49%|████▊     | 28783/59290 [20:06<27:26, 18.52it/s]

Iteration: 28793/59290
Iteration: 28794/59290
Iteration: 28795/59290
Iteration: 28796/59290
Iteration: 28797/59290
Iteration: 28798/59290
Iteration: 28799/59290
Iteration: 28800/59290
Iteration: 28801/59290
Iteration: 28802/59290
Iteration: 28803/59290
Iteration: 28804/59290
Iteration: 28805/59290
Iteration: 28806/59290
Iteration: 28807/59290
Iteration: 28808/59290
Iteration: 28809/59290
Iteration: 28810/59290
Iteration: 28811/59290
Iteration: 28812/59290
Iteration: 28813/59290
Iteration: 28814/59290
Iteration: 28815/59290
Iteration: 28816/59290

 49%|████▊     | 28807/59290 [20:07<22:45, 22.32it/s]

Iteration: 28817/59290
Iteration: 28818/59290
Iteration: 28819/59290
Iteration: 28820/59290
Iteration: 28821/59290
Iteration: 28822/59290
Iteration: 28823/59290
Iteration: 28824/59290
Iteration: 28825/59290
Iteration: 28826/59290
Iteration: 28827/59290
Iteration: 28828/59290
Iteration: 28829/59290
Iteration: 28830/59290
Iteration: 28831/59290
Iteration: 28832/59290
Iteration: 28833/59290
Iteration: 28834/59290
Iteration: 28835/59290
Iteration: 28836/59290
Iteration: 28837/59290
Iteration: 28838/59290
Iteration: 28839/59290
Iteration: 28840/59290

 49%|████▊     | 28831/59290 [20:07<18:26, 27.54it/s]

Iteration: 28841/59290
Iteration: 28842/59290
Iteration: 28843/59290
Iteration: 28844/59290
Iteration: 28845/59290
Iteration: 28846/59290
Iteration: 28847/59290
Iteration: 28848/59290
Iteration: 28849/59290
Iteration: 28850/59290
Iteration: 28851/59290
Iteration: 28852/59290
Iteration: 28853/59290
Iteration: 28854/59290
Iteration: 28855/59290
Iteration: 28856/59290
Iteration: 28857/59290
Iteration: 28858/59290
Iteration: 28859/59290
Iteration: 28860/59290
Iteration: 28861/59290
Iteration: 28862/59290
Iteration: 28863/59290
Iteration: 28864/59290

 49%|████▊     | 28855/59290 [20:07<15:16, 33.21it/s]

Iteration: 28865/59290
Iteration: 28866/59290
Iteration: 28867/59290
Iteration: 28868/59290
Iteration: 28869/59290
Iteration: 28870/59290
Iteration: 28871/59290
Iteration: 28872/59290
Iteration: 28873/59290
Iteration: 28874/59290
Iteration: 28875/59290
Iteration: 28876/59290
Iteration: 28877/59290
Iteration: 28878/59290
Iteration: 28879/59290
Iteration: 28880/59290
Iteration: 28881/59290
Iteration: 28882/59290
Iteration: 28883/59290
Iteration: 28884/59290
Iteration: 28885/59290
Iteration: 28886/59290
Iteration: 28887/59290
Iteration: 28888/59290

 49%|████▊     | 28879/59290 [20:11<34:41, 14.61it/s]

Iteration: 28889/59290
Iteration: 28890/59290
Iteration: 28891/59290
Iteration: 28892/59290
Iteration: 28893/59290
Iteration: 28894/59290
Iteration: 28895/59290
Iteration: 28896/59290
Iteration: 28897/59290
Iteration: 28898/59290
Iteration: 28899/59290
Iteration: 28900/59290
Iteration: 28901/59290
Iteration: 28902/59290
Iteration: 28903/59290
Iteration: 28904/59290
Iteration: 28905/59290
Iteration: 28906/59290
Iteration: 28907/59290
Iteration: 28908/59290
Iteration: 28909/59290
Iteration: 28910/59290
Iteration: 28911/59290
Iteration: 28912/59290

 49%|████▊     | 28903/59290 [20:12<27:31, 18.40it/s]

Iteration: 28913/59290
Iteration: 28914/59290
Iteration: 28915/59290
Iteration: 28916/59290
Iteration: 28917/59290
Iteration: 28918/59290
Iteration: 28919/59290
Iteration: 28920/59290
Iteration: 28921/59290
Iteration: 28922/59290
Iteration: 28923/59290
Iteration: 28924/59290
Iteration: 28925/59290
Iteration: 28926/59290
Iteration: 28927/59290
Iteration: 28928/59290
Iteration: 28929/59290
Iteration: 28930/59290
Iteration: 28931/59290
Iteration: 28932/59290
Iteration: 28933/59290
Iteration: 28934/59290
Iteration: 28935/59290
Iteration: 28936/59290

 49%|████▉     | 28927/59290 [20:12<21:39, 23.37it/s]

Iteration: 28937/59290
Iteration: 28938/59290
Iteration: 28939/59290
Iteration: 28940/59290
Iteration: 28941/59290
Iteration: 28942/59290
Iteration: 28943/59290
Iteration: 28944/59290
Iteration: 28945/59290
Iteration: 28946/59290
Iteration: 28947/59290
Iteration: 28948/59290
Iteration: 28949/59290
Iteration: 28950/59290
Iteration: 28951/59290
Iteration: 28952/59290
Iteration: 28953/59290
Iteration: 28954/59290
Iteration: 28955/59290
Iteration: 28956/59290
Iteration: 28957/59290
Iteration: 28958/59290
Iteration: 28959/59290
Iteration: 28960/59290

 49%|████▉     | 28951/59290 [20:12<17:36, 28.73it/s]

Iteration: 28961/59290
Iteration: 28962/59290
Iteration: 28963/59290
Iteration: 28964/59290
Iteration: 28965/59290
Iteration: 28966/59290
Iteration: 28967/59290
Iteration: 28968/59290
Iteration: 28969/59290
Iteration: 28970/59290
Iteration: 28971/59290
Iteration: 28972/59290
Iteration: 28973/59290
Iteration: 28974/59290
Iteration: 28975/59290
Iteration: 28976/59290
Iteration: 28977/59290
Iteration: 28978/59290
Iteration: 28979/59290
Iteration: 28980/59290
Iteration: 28981/59290
Iteration: 28982/59290
Iteration: 28983/59290
Iteration: 28984/59290

 49%|████▉     | 28975/59290 [20:14<23:08, 21.83it/s]

Iteration: 28985/59290
Iteration: 28986/59290
Iteration: 28987/59290
Iteration: 28988/59290
Iteration: 28989/59290
Iteration: 28990/59290
Iteration: 28991/59290
Iteration: 28992/59290
Iteration: 28993/59290
Iteration: 28994/59290
Iteration: 28995/59290
Iteration: 28996/59290
Iteration: 28997/59290
Iteration: 28998/59290
Iteration: 28999/59290
Iteration: 29000/59290
Iteration: 29001/59290
Iteration: 29002/59290
Iteration: 29003/59290
Iteration: 29004/59290
Iteration: 29005/59290
Iteration: 29006/59290
Iteration: 29007/59290
Iteration: 29008/59290

 49%|████▉     | 28999/59290 [20:49<3:53:47,  2.16it/s]

Iteration: 29009/59290
Iteration: 29010/59290
Iteration: 29011/59290
Iteration: 29012/59290
Iteration: 29013/59290
Iteration: 29014/59290
Iteration: 29015/59290
Iteration: 29016/59290
Iteration: 29017/59290
Iteration: 29018/59290
Iteration: 29019/59290
Iteration: 29020/59290
Iteration: 29021/59290
Iteration: 29022/59290
Iteration: 29023/59290
Iteration: 29024/59290
Iteration: 29025/59290
Iteration: 29026/59290
Iteration: 29027/59290
Iteration: 29028/59290
Iteration: 29029/59290
Iteration: 29030/59290
Iteration: 29031/59290
Iteration: 29032/59290

 49%|████▉     | 29023/59290 [20:49<2:45:54,  3.04it/s]

Iteration: 29033/59290
Iteration: 29034/59290
Iteration: 29035/59290
Iteration: 29036/59290
Iteration: 29037/59290
Iteration: 29038/59290
Iteration: 29039/59290
Iteration: 29040/59290
Iteration: 29041/59290
Iteration: 29042/59290
Iteration: 29043/59290
Iteration: 29044/59290
Iteration: 29045/59290
Iteration: 29046/59290
Iteration: 29047/59290
Iteration: 29048/59290
Iteration: 29049/59290
Iteration: 29050/59290
Iteration: 29051/59290
Iteration: 29052/59290
Iteration: 29053/59290
Iteration: 29054/59290
Iteration: 29055/59290
Iteration: 29056/59290

 49%|████▉     | 29047/59290 [20:49<1:58:26,  4.26it/s]

Iteration: 29057/59290
Iteration: 29058/59290
Iteration: 29059/59290
Iteration: 29060/59290
Iteration: 29061/59290
Iteration: 29062/59290
Iteration: 29063/59290
Iteration: 29064/59290
Iteration: 29065/59290
Iteration: 29066/59290
Iteration: 29067/59290
Iteration: 29068/59290
Iteration: 29069/59290
Iteration: 29070/59290
Iteration: 29071/59290
Iteration: 29072/59290
Iteration: 29073/59290
Iteration: 29074/59290
Iteration: 29075/59290
Iteration: 29076/59290
Iteration: 29077/59290
Iteration: 29078/59290
Iteration: 29079/59290
Iteration: 29080/59290

 49%|████▉     | 29071/59290 [20:50<1:25:17,  5.90it/s]

Iteration: 29081/59290
Iteration: 29082/59290
Iteration: 29083/59290
Iteration: 29084/59290
Iteration: 29085/59290
Iteration: 29086/59290
Iteration: 29087/59290
Iteration: 29088/59290
Iteration: 29089/59290
Iteration: 29090/59290
Iteration: 29091/59290
Iteration: 29092/59290
Iteration: 29093/59290
Iteration: 29094/59290
Iteration: 29095/59290
Iteration: 29096/59290
Iteration: 29097/59290
Iteration: 29098/59290
Iteration: 29099/59290
Iteration: 29100/59290
Iteration: 29101/59290
Iteration: 29102/59290
Iteration: 29103/59290
Iteration: 29104/59290

 49%|████▉     | 29095/59290 [20:50<1:01:59,  8.12it/s]

Iteration: 29105/59290
Iteration: 29106/59290
Iteration: 29107/59290
Iteration: 29108/59290
Iteration: 29109/59290
Iteration: 29110/59290
Iteration: 29111/59290
Iteration: 29112/59290
Iteration: 29113/59290
Iteration: 29114/59290
Iteration: 29115/59290
Iteration: 29116/59290
Iteration: 29117/59290
Iteration: 29118/59290
Iteration: 29119/59290
Iteration: 29120/59290
Iteration: 29121/59290
Iteration: 29122/59290
Iteration: 29123/59290
Iteration: 29124/59290
Iteration: 29125/59290
Iteration: 29126/59290
Iteration: 29127/59290
Iteration: 29128/59290

 49%|████▉     | 29119/59290 [20:50<45:44, 10.99it/s]

Iteration: 29129/59290
Iteration: 29130/59290
Iteration: 29131/59290
Iteration: 29132/59290
Iteration: 29133/59290
Iteration: 29134/59290
Iteration: 29135/59290
Iteration: 29136/59290
Iteration: 29137/59290
Iteration: 29138/59290
Iteration: 29139/59290
Iteration: 29140/59290
Iteration: 29141/59290
Iteration: 29142/59290
Iteration: 29143/59290
Iteration: 29144/59290
Iteration: 29145/59290
Iteration: 29146/59290
Iteration: 29147/59290
Iteration: 29148/59290
Iteration: 29149/59290
Iteration: 29150/59290
Iteration: 29151/59290
Iteration: 29152/59290

 49%|████▉     | 29143/59290 [20:51<34:28, 14.58it/s]

Iteration: 29153/59290
Iteration: 29154/59290
Iteration: 29155/59290
Iteration: 29156/59290
Iteration: 29157/59290
Iteration: 29158/59290
Iteration: 29159/59290
Iteration: 29160/59290
Iteration: 29161/59290
Iteration: 29162/59290
Iteration: 29163/59290
Iteration: 29164/59290
Iteration: 29165/59290
Iteration: 29166/59290
Iteration: 29167/59290
Iteration: 29168/59290
Iteration: 29169/59290
Iteration: 29170/59290
Iteration: 29171/59290
Iteration: 29172/59290
Iteration: 29173/59290
Iteration: 29174/59290
Iteration: 29175/59290
Iteration: 29176/59290

 49%|████▉     | 29167/59290 [20:51<26:27, 18.97it/s]

Iteration: 29177/59290
Iteration: 29178/59290
Iteration: 29179/59290
Iteration: 29180/59290
Iteration: 29181/59290
Iteration: 29182/59290
Iteration: 29183/59290
Iteration: 29184/59290
Iteration: 29185/59290
Iteration: 29186/59290
Iteration: 29187/59290
Iteration: 29188/59290
Iteration: 29189/59290
Iteration: 29190/59290
Iteration: 29191/59290
Iteration: 29192/59290
Iteration: 29193/59290
Iteration: 29194/59290
Iteration: 29195/59290
Iteration: 29196/59290
Iteration: 29197/59290
Iteration: 29198/59290
Iteration: 29199/59290
Iteration: 29200/59290

 49%|████▉     | 29191/59290 [20:53<29:29, 17.01it/s]

Iteration: 29201/59290
Iteration: 29202/59290
Iteration: 29203/59290
Iteration: 29204/59290
Iteration: 29205/59290
Iteration: 29206/59290
Iteration: 29207/59290
Iteration: 29208/59290
Iteration: 29209/59290
Iteration: 29210/59290
Iteration: 29211/59290
Iteration: 29212/59290
Iteration: 29213/59290
Iteration: 29214/59290
Iteration: 29215/59290
Iteration: 29216/59290
Iteration: 29217/59290
Iteration: 29218/59290
Iteration: 29219/59290
Iteration: 29220/59290
Iteration: 29221/59290
Iteration: 29222/59290
Iteration: 29223/59290
Iteration: 29224/59290

 49%|████▉     | 29215/59290 [20:55<33:20, 15.03it/s]

Iteration: 29225/59290
Iteration: 29226/59290
Iteration: 29227/59290
Iteration: 29228/59290
Iteration: 29229/59290
Iteration: 29230/59290
Iteration: 29231/59290
Iteration: 29232/59290
Iteration: 29233/59290
Iteration: 29234/59290
Iteration: 29235/59290
Iteration: 29236/59290
Iteration: 29237/59290
Iteration: 29238/59290
Iteration: 29239/59290
Iteration: 29240/59290
Iteration: 29241/59290
Iteration: 29242/59290
Iteration: 29243/59290
Iteration: 29244/59290
Iteration: 29245/59290
Iteration: 29246/59290
Iteration: 29247/59290
Iteration: 29248/59290

 49%|████▉     | 29239/59290 [20:56<26:26, 18.94it/s]

Iteration: 29249/59290
Iteration: 29250/59290
Iteration: 29251/59290
Iteration: 29252/59290
Iteration: 29253/59290
Iteration: 29254/59290
Iteration: 29255/59290
Iteration: 29256/59290
Iteration: 29257/59290
Iteration: 29258/59290
Iteration: 29259/59290
Iteration: 29260/59290
Iteration: 29261/59290
Iteration: 29262/59290
Iteration: 29263/59290
Iteration: 29264/59290
Iteration: 29265/59290
Iteration: 29266/59290
Iteration: 29267/59290
Iteration: 29268/59290
Iteration: 29269/59290
Iteration: 29270/59290
Iteration: 29271/59290
Iteration: 29272/59290

 49%|████▉     | 29263/59290 [20:56<21:04, 23.75it/s]

Iteration: 29273/59290
Iteration: 29274/59290
Iteration: 29275/59290
Iteration: 29276/59290
Iteration: 29277/59290
Iteration: 29278/59290
Iteration: 29279/59290
Iteration: 29280/59290
Iteration: 29281/59290
Iteration: 29282/59290
Iteration: 29283/59290
Iteration: 29284/59290
Iteration: 29285/59290
Iteration: 29286/59290
Iteration: 29287/59290
Iteration: 29288/59290
Iteration: 29289/59290
Iteration: 29290/59290
Iteration: 29291/59290
Iteration: 29292/59290
Iteration: 29293/59290
Iteration: 29294/59290
Iteration: 29295/59290
Iteration: 29296/59290

 49%|████▉     | 29287/59290 [20:56<17:08, 29.17it/s]

Iteration: 29297/59290
Iteration: 29298/59290
Iteration: 29299/59290
Iteration: 29300/59290
Iteration: 29301/59290
Iteration: 29302/59290
Iteration: 29303/59290
Iteration: 29304/59290
Iteration: 29305/59290
Iteration: 29306/59290
Iteration: 29307/59290
Iteration: 29308/59290
Iteration: 29309/59290
Iteration: 29310/59290
Iteration: 29311/59290
Iteration: 29312/59290
Iteration: 29313/59290
Iteration: 29314/59290
Iteration: 29315/59290
Iteration: 29316/59290
Iteration: 29317/59290
Iteration: 29318/59290
Iteration: 29319/59290
Iteration: 29320/59290

 49%|████▉     | 29311/59290 [20:57<14:21, 34.80it/s]

Iteration: 29321/59290
Iteration: 29322/59290
Iteration: 29323/59290
Iteration: 29324/59290
Iteration: 29325/59290
Iteration: 29326/59290
Iteration: 29327/59290
Iteration: 29328/59290
Iteration: 29329/59290
Iteration: 29330/59290
Iteration: 29331/59290
Iteration: 29332/59290
Iteration: 29333/59290
Iteration: 29334/59290
Iteration: 29335/59290
Iteration: 29336/59290
Iteration: 29337/59290
Iteration: 29338/59290
Iteration: 29339/59290
Iteration: 29340/59290
Iteration: 29341/59290
Iteration: 29342/59290
Iteration: 29343/59290
Iteration: 29344/59290

 49%|████▉     | 29335/59290 [20:57<12:24, 40.23it/s]

Iteration: 29345/59290
Iteration: 29346/59290
Iteration: 29347/59290
Iteration: 29348/59290
Iteration: 29349/59290
Iteration: 29350/59290
Iteration: 29351/59290
Iteration: 29352/59290
Iteration: 29353/59290
Iteration: 29354/59290
Iteration: 29355/59290
Iteration: 29356/59290
Iteration: 29357/59290
Iteration: 29358/59290
Iteration: 29359/59290
Iteration: 29360/59290
Iteration: 29361/59290
Iteration: 29362/59290
Iteration: 29363/59290
Iteration: 29364/59290
Iteration: 29365/59290
Iteration: 29366/59290
Iteration: 29367/59290
Iteration: 29368/59290

 50%|████▉     | 29359/59290 [20:57<11:04, 45.01it/s]

Iteration: 29369/59290
Iteration: 29370/59290
Iteration: 29371/59290
Iteration: 29372/59290
Iteration: 29373/59290
Iteration: 29374/59290
Iteration: 29375/59290
Iteration: 29376/59290
Iteration: 29377/59290
Iteration: 29378/59290
Iteration: 29379/59290
Iteration: 29380/59290
Iteration: 29381/59290
Iteration: 29382/59290
Iteration: 29383/59290
Iteration: 29384/59290
Iteration: 29385/59290
Iteration: 29386/59290
Iteration: 29387/59290
Iteration: 29388/59290
Iteration: 29389/59290
Iteration: 29390/59290
Iteration: 29391/59290
Iteration: 29392/59290

 50%|████▉     | 29383/59290 [20:58<10:06, 49.27it/s]

Iteration: 29393/59290
Iteration: 29394/59290
Iteration: 29395/59290
Iteration: 29396/59290
Iteration: 29397/59290
Iteration: 29398/59290
Iteration: 29399/59290
Iteration: 29400/59290
Iteration: 29401/59290
Iteration: 29402/59290
Iteration: 29403/59290
Iteration: 29404/59290
Iteration: 29405/59290
Iteration: 29406/59290
Iteration: 29407/59290
Iteration: 29408/59290
Iteration: 29409/59290
Iteration: 29410/59290
Iteration: 29411/59290
Iteration: 29412/59290
Iteration: 29413/59290
Iteration: 29414/59290
Iteration: 29415/59290
Iteration: 29416/59290

 50%|████▉     | 29407/59290 [20:58<09:25, 52.87it/s]

Iteration: 29417/59290
Iteration: 29418/59290
Iteration: 29419/59290
Iteration: 29420/59290
Iteration: 29421/59290
Iteration: 29422/59290
Iteration: 29423/59290
Iteration: 29424/59290
Iteration: 29425/59290
Iteration: 29426/59290
Iteration: 29427/59290
Iteration: 29428/59290
Iteration: 29429/59290
Iteration: 29430/59290
Iteration: 29431/59290
Iteration: 29432/59290
Iteration: 29433/59290
Iteration: 29434/59290
Iteration: 29435/59290
Iteration: 29436/59290
Iteration: 29437/59290
Iteration: 29438/59290
Iteration: 29439/59290
Iteration: 29440/59290

 50%|████▉     | 29431/59290 [20:59<08:56, 55.62it/s]

Iteration: 29441/59290
Iteration: 29442/59290
Iteration: 29443/59290
Iteration: 29444/59290
Iteration: 29445/59290
Iteration: 29446/59290
Iteration: 29447/59290
Iteration: 29448/59290
Iteration: 29449/59290
Iteration: 29450/59290
Iteration: 29451/59290
Iteration: 29452/59290
Iteration: 29453/59290
Iteration: 29454/59290
Iteration: 29455/59290
Iteration: 29456/59290
Iteration: 29457/59290
Iteration: 29458/59290
Iteration: 29459/59290
Iteration: 29460/59290
Iteration: 29461/59290
Iteration: 29462/59290
Iteration: 29463/59290
Iteration: 29464/59290

 50%|████▉     | 29455/59290 [20:59<08:41, 57.21it/s]

Iteration: 29465/59290
Iteration: 29466/59290
Iteration: 29467/59290
Iteration: 29468/59290
Iteration: 29469/59290
Iteration: 29470/59290
Iteration: 29471/59290
Iteration: 29472/59290
Iteration: 29473/59290
Iteration: 29474/59290
Iteration: 29475/59290
Iteration: 29476/59290
Iteration: 29477/59290
Iteration: 29478/59290
Iteration: 29479/59290
Iteration: 29480/59290
Iteration: 29481/59290
Iteration: 29482/59290
Iteration: 29483/59290
Iteration: 29484/59290
Iteration: 29485/59290
Iteration: 29486/59290
Iteration: 29487/59290
Iteration: 29488/59290

 50%|████▉     | 29479/59290 [20:59<08:24, 59.11it/s]

Iteration: 29489/59290
Iteration: 29490/59290
Iteration: 29491/59290
Iteration: 29492/59290
Iteration: 29493/59290
Iteration: 29494/59290
Iteration: 29495/59290
Iteration: 29496/59290
Iteration: 29497/59290
Iteration: 29498/59290
Iteration: 29499/59290
Iteration: 29500/59290
Iteration: 29501/59290
Iteration: 29502/59290
Iteration: 29503/59290
Iteration: 29504/59290
Iteration: 29505/59290
Iteration: 29506/59290
Iteration: 29507/59290
Iteration: 29508/59290
Iteration: 29509/59290
Iteration: 29510/59290
Iteration: 29511/59290
Iteration: 29512/59290

 50%|████▉     | 29503/59290 [21:01<14:46, 33.61it/s]

Iteration: 29513/59290
Iteration: 29514/59290
Iteration: 29515/59290
Iteration: 29516/59290
Iteration: 29517/59290
Iteration: 29518/59290
Iteration: 29519/59290
Iteration: 29520/59290
Iteration: 29521/59290
Iteration: 29522/59290
Iteration: 29523/59290
Iteration: 29524/59290
Iteration: 29525/59290
Iteration: 29526/59290
Iteration: 29527/59290
Iteration: 29528/59290
Iteration: 29529/59290
Iteration: 29530/59290
Iteration: 29531/59290
Iteration: 29532/59290
Iteration: 29533/59290
Iteration: 29534/59290
Iteration: 29535/59290
Iteration: 29536/59290

 50%|████▉     | 29527/59290 [21:03<23:12, 21.37it/s]

Iteration: 29537/59290
Iteration: 29538/59290
Iteration: 29539/59290
Iteration: 29540/59290
Iteration: 29541/59290
Iteration: 29542/59290
Iteration: 29543/59290
Iteration: 29544/59290
Iteration: 29545/59290
Iteration: 29546/59290
Iteration: 29547/59290
Iteration: 29548/59290
Iteration: 29549/59290
Iteration: 29550/59290
Iteration: 29551/59290
Iteration: 29552/59290
Iteration: 29553/59290
Iteration: 29554/59290
Iteration: 29555/59290
Iteration: 29556/59290
Iteration: 29557/59290
Iteration: 29558/59290
Iteration: 29559/59290
Iteration: 29560/59290

 50%|████▉     | 29551/59290 [21:03<19:19, 25.65it/s]

Iteration: 29561/59290
Iteration: 29562/59290
Iteration: 29563/59290
Iteration: 29564/59290
Iteration: 29565/59290
Iteration: 29566/59290
Iteration: 29567/59290
Iteration: 29568/59290
Iteration: 29569/59290
Iteration: 29570/59290
Iteration: 29571/59290
Iteration: 29572/59290
Iteration: 29573/59290
Iteration: 29574/59290
Iteration: 29575/59290
Iteration: 29576/59290
Iteration: 29577/59290
Iteration: 29578/59290
Iteration: 29579/59290
Iteration: 29580/59290
Iteration: 29581/59290
Iteration: 29582/59290
Iteration: 29583/59290
Iteration: 29584/59290

 50%|████▉     | 29575/59290 [21:04<15:55, 31.08it/s]

Iteration: 29585/59290
Iteration: 29586/59290
Iteration: 29587/59290
Iteration: 29588/59290
Iteration: 29589/59290
Iteration: 29590/59290
Iteration: 29591/59290
Iteration: 29592/59290
Iteration: 29593/59290
Iteration: 29594/59290
Iteration: 29595/59290
Iteration: 29596/59290
Iteration: 29597/59290
Iteration: 29598/59290
Iteration: 29599/59290
Iteration: 29600/59290
Iteration: 29601/59290
Iteration: 29602/59290
Iteration: 29603/59290
Iteration: 29604/59290
Iteration: 29605/59290
Iteration: 29606/59290
Iteration: 29607/59290
Iteration: 29608/59290

 50%|████▉     | 29599/59290 [21:04<13:30, 36.64it/s]

Iteration: 29609/59290
Iteration: 29610/59290
Iteration: 29611/59290
Iteration: 29612/59290
Iteration: 29613/59290
Iteration: 29614/59290
Iteration: 29615/59290
Iteration: 29616/59290
Iteration: 29617/59290
Iteration: 29618/59290
Iteration: 29619/59290
Iteration: 29620/59290
Iteration: 29621/59290
Iteration: 29622/59290
Iteration: 29623/59290
Iteration: 29624/59290
Iteration: 29625/59290
Iteration: 29626/59290
Iteration: 29627/59290
Iteration: 29628/59290
Iteration: 29629/59290
Iteration: 29630/59290
Iteration: 29631/59290
Iteration: 29632/59290

 50%|████▉     | 29623/59290 [21:05<11:46, 42.01it/s]

Iteration: 29633/59290
Iteration: 29634/59290
Iteration: 29635/59290
Iteration: 29636/59290
Iteration: 29637/59290
Iteration: 29638/59290
Iteration: 29639/59290
Iteration: 29640/59290
Iteration: 29641/59290
Iteration: 29642/59290
Iteration: 29643/59290
Iteration: 29644/59290
Iteration: 29645/59290
Iteration: 29646/59290
Iteration: 29647/59290
Iteration: 29648/59290
Iteration: 29649/59290
Iteration: 29650/59290
Iteration: 29651/59290
Iteration: 29652/59290
Iteration: 29653/59290
Iteration: 29654/59290
Iteration: 29656/59290

 50%|█████     | 29646/59290 [21:08<32:12, 15.34it/s]

Iteration: 29657/59290
Iteration: 29658/59290
Iteration: 29659/59290
Iteration: 29660/59290
Iteration: 29661/59290
Iteration: 29662/59290
Iteration: 29663/59290
Iteration: 29664/59290

 50%|█████     | 29654/59290 [21:09<32:13, 15.33it/s]

Iteration: 29665/59290
Iteration: 29666/59290
Iteration: 29667/59290
Iteration: 29668/59290
Iteration: 29669/59290
Iteration: 29670/59290
Iteration: 29671/59290
Iteration: 29672/59290
Iteration: 29673/59290
Iteration: 29674/59290
Iteration: 29675/59290
Iteration: 29676/59290
Iteration: 29677/59290
Iteration: 29678/59290
Iteration: 29679/59290
Iteration: 29680/59290
Iteration: 29681/59290
Iteration: 29682/59290
Iteration: 29683/59290
Iteration: 29684/59290
Iteration: 29685/59290
Iteration: 29686/59290
Iteration: 29687/59290
Iteration: 29688/59290

 50%|█████     | 29678/59290 [21:09<23:53, 20.65it/s]

Iteration: 29689/59290
Iteration: 29690/59290
Iteration: 29691/59290
Iteration: 29692/59290
Iteration: 29693/59290
Iteration: 29694/59290
Iteration: 29695/59290
Iteration: 29696/59290
Iteration: 29697/59290
Iteration: 29698/59290
Iteration: 29699/59290
Iteration: 29700/59290
Iteration: 29701/59290
Iteration: 29702/59290
Iteration: 29703/59290
Iteration: 29704/59290
Iteration: 29705/59290
Iteration: 29706/59290
Iteration: 29707/59290
Iteration: 29708/59290
Iteration: 29709/59290
Iteration: 29710/59290
Iteration: 29711/59290
Iteration: 29712/59290

 50%|█████     | 29702/59290 [21:10<18:35, 26.52it/s]

Iteration: 29713/59290
Iteration: 29714/59290
Iteration: 29715/59290
Iteration: 29716/59290
Iteration: 29717/59290
Iteration: 29718/59290
Iteration: 29719/59290
Iteration: 29720/59290
Iteration: 29721/59290
Iteration: 29722/59290
Iteration: 29723/59290
Iteration: 29724/59290
Iteration: 29725/59290
Iteration: 29726/59290
Iteration: 29727/59290
Iteration: 29728/59290
Iteration: 29729/59290
Iteration: 29730/59290
Iteration: 29731/59290
Iteration: 29732/59290
Iteration: 29733/59290
Iteration: 29734/59290
Iteration: 29735/59290
Iteration: 29736/59290

 50%|█████     | 29726/59290 [21:11<23:29, 20.97it/s]

Iteration: 29737/59290
Iteration: 29738/59290
Iteration: 29739/59290
Iteration: 29740/59290
Iteration: 29741/59290
Iteration: 29742/59290
Iteration: 29743/59290
Iteration: 29744/59290
Iteration: 29745/59290
Iteration: 29746/59290
Iteration: 29747/59290
Iteration: 29748/59290
Iteration: 29749/59290
Iteration: 29750/59290
Iteration: 29751/59290
Iteration: 29752/59290
Iteration: 29753/59290
Iteration: 29754/59290
Iteration: 29755/59290
Iteration: 29756/59290
Iteration: 29757/59290
Iteration: 29758/59290
Iteration: 29759/59290
Iteration: 29760/59290

 50%|█████     | 29750/59290 [21:14<32:01, 15.38it/s]

Iteration: 29761/59290
Iteration: 29762/59290
Iteration: 29763/59290
Iteration: 29764/59290
Iteration: 29765/59290
Iteration: 29766/59290
Iteration: 29767/59290
Iteration: 29768/59290
Iteration: 29769/59290
Iteration: 29770/59290
Iteration: 29771/59290
Iteration: 29772/59290
Iteration: 29773/59290
Iteration: 29774/59290
Iteration: 29775/59290
Iteration: 29776/59290
Iteration: 29777/59290
Iteration: 29778/59290
Iteration: 29779/59290
Iteration: 29780/59290
Iteration: 29781/59290
Iteration: 29782/59290
Iteration: 29783/59290
Iteration: 29784/59290

 50%|█████     | 29774/59290 [21:14<24:28, 20.10it/s]

Iteration: 29785/59290
Iteration: 29786/59290
Iteration: 29787/59290
Iteration: 29788/59290
Iteration: 29789/59290
Iteration: 29790/59290
Iteration: 29791/59290
Iteration: 29792/59290
Iteration: 29793/59290
Iteration: 29794/59290
Iteration: 29795/59290
Iteration: 29796/59290
Iteration: 29797/59290
Iteration: 29798/59290
Iteration: 29799/59290
Iteration: 29800/59290
Iteration: 29801/59290
Iteration: 29802/59290
Iteration: 29803/59290
Iteration: 29804/59290
Iteration: 29805/59290
Iteration: 29806/59290
Iteration: 29807/59290
Iteration: 29808/59290

 50%|█████     | 29798/59290 [21:15<19:25, 25.31it/s]

Iteration: 29809/59290
Iteration: 29810/59290
Iteration: 29811/59290
Iteration: 29812/59290
Iteration: 29813/59290
Iteration: 29814/59290
Iteration: 29815/59290
Iteration: 29816/59290
Iteration: 29817/59290
Iteration: 29818/59290
Iteration: 29819/59290
Iteration: 29820/59290
Iteration: 29821/59290
Iteration: 29822/59290
Iteration: 29823/59290
Iteration: 29824/59290
Iteration: 29825/59290
Iteration: 29826/59290
Iteration: 29827/59290
Iteration: 29828/59290
Iteration: 29829/59290
Iteration: 29830/59290
Iteration: 29831/59290
Iteration: 29832/59290

 50%|█████     | 29822/59290 [21:15<16:06, 30.50it/s]

Iteration: 29833/59290
Iteration: 29834/59290
Iteration: 29835/59290
Iteration: 29836/59290
Iteration: 29837/59290
Iteration: 29838/59290
Iteration: 29839/59290
Iteration: 29840/59290
Iteration: 29841/59290
Iteration: 29842/59290
Iteration: 29843/59290
Iteration: 29844/59290
Iteration: 29845/59290
Iteration: 29846/59290
Iteration: 29847/59290
Iteration: 29848/59290
Iteration: 29849/59290
Iteration: 29850/59290
Iteration: 29851/59290
Iteration: 29852/59290
Iteration: 29853/59290
Iteration: 29854/59290
Iteration: 29855/59290
Iteration: 29856/59290

 50%|█████     | 29846/59290 [21:17<20:53, 23.50it/s]

Iteration: 29857/59290
Iteration: 29858/59290
Iteration: 29859/59290
Iteration: 29860/59290
Iteration: 29861/59290
Iteration: 29862/59290
Iteration: 29863/59290
Iteration: 29864/59290
Iteration: 29865/59290
Iteration: 29866/59290
Iteration: 29867/59290
Iteration: 29868/59290
Iteration: 29869/59290
Iteration: 29870/59290
Iteration: 29871/59290
Iteration: 29872/59290
Iteration: 29873/59290
Iteration: 29874/59290
Iteration: 29875/59290
Iteration: 29876/59290
Iteration: 29877/59290
Iteration: 29878/59290
Iteration: 29879/59290
Iteration: 29880/59290

 50%|█████     | 29870/59290 [21:19<30:05, 16.29it/s]

Iteration: 29881/59290
Iteration: 29882/59290
Iteration: 29883/59290
Iteration: 29884/59290
Iteration: 29885/59290
Iteration: 29886/59290
Iteration: 29887/59290
Iteration: 29888/59290
Iteration: 29889/59290
Iteration: 29890/59290
Iteration: 29891/59290
Iteration: 29892/59290
Iteration: 29893/59290
Iteration: 29894/59290
Iteration: 29895/59290
Iteration: 29896/59290
Iteration: 29897/59290
Iteration: 29898/59290
Iteration: 29899/59290
Iteration: 29900/59290
Iteration: 29901/59290
Iteration: 29902/59290
Iteration: 29903/59290
Iteration: 29904/59290

 50%|█████     | 29894/59290 [21:19<23:20, 20.98it/s]

Iteration: 29905/59290
Iteration: 29906/59290
Iteration: 29907/59290
Iteration: 29908/59290
Iteration: 29909/59290
Iteration: 29910/59290
Iteration: 29911/59290
Iteration: 29912/59290
Iteration: 29913/59290
Iteration: 29914/59290
Iteration: 29915/59290
Iteration: 29916/59290
Iteration: 29917/59290
Iteration: 29918/59290
Iteration: 29919/59290
Iteration: 29920/59290
Iteration: 29921/59290
Iteration: 29922/59290
Iteration: 29923/59290
Iteration: 29924/59290
Iteration: 29925/59290
Iteration: 29926/59290
Iteration: 29927/59290
Iteration: 29928/59290

 50%|█████     | 29918/59290 [21:20<18:42, 26.17it/s]

Iteration: 29929/59290
Iteration: 29930/59290
Iteration: 29931/59290
Iteration: 29932/59290
Iteration: 29933/59290
Iteration: 29934/59290
Iteration: 29935/59290
Iteration: 29936/59290
Iteration: 29937/59290
Iteration: 29938/59290
Iteration: 29939/59290
Iteration: 29940/59290
Iteration: 29941/59290
Iteration: 29942/59290
Iteration: 29943/59290
Iteration: 29944/59290
Iteration: 29945/59290
Iteration: 29946/59290
Iteration: 29947/59290
Iteration: 29948/59290
Iteration: 29949/59290
Iteration: 29950/59290
Iteration: 29951/59290
Iteration: 29952/59290

 51%|█████     | 29942/59290 [21:20<15:24, 31.74it/s]

Iteration: 29953/59290
Iteration: 29954/59290
Iteration: 29955/59290
Iteration: 29956/59290
Iteration: 29957/59290
Iteration: 29958/59290
Iteration: 29959/59290
Iteration: 29960/59290
Iteration: 29961/59290
Iteration: 29962/59290
Iteration: 29963/59290
Iteration: 29964/59290
Iteration: 29965/59290
Iteration: 29966/59290
Iteration: 29967/59290
Iteration: 29968/59290
Iteration: 29969/59290
Iteration: 29970/59290
Iteration: 29971/59290
Iteration: 29972/59290
Iteration: 29973/59290
Iteration: 29974/59290
Iteration: 29975/59290
Iteration: 29976/59290

 51%|█████     | 29966/59290 [21:21<13:03, 37.43it/s]

Iteration: 29977/59290
Iteration: 29978/59290
Iteration: 29979/59290
Iteration: 29980/59290
Iteration: 29981/59290
Iteration: 29982/59290
Iteration: 29983/59290
Iteration: 29984/59290
Iteration: 29985/59290
Iteration: 29986/59290
Iteration: 29987/59290
Iteration: 29988/59290
Iteration: 29989/59290
Iteration: 29990/59290
Iteration: 29991/59290
Iteration: 29992/59290
Iteration: 29993/59290
Iteration: 29994/59290
Iteration: 29995/59290
Iteration: 29996/59290
Iteration: 29997/59290
Iteration: 29998/59290
Iteration: 29999/59290
Iteration: 30000/59290

 51%|█████     | 29990/59290 [21:21<11:25, 42.72it/s]

Iteration: 30001/59290
Iteration: 30002/59290
Iteration: 30003/59290
Iteration: 30004/59290
Iteration: 30005/59290
Iteration: 30006/59290
Iteration: 30007/59290
Iteration: 30008/59290
Iteration: 30009/59290
Iteration: 30010/59290
Iteration: 30011/59290
Iteration: 30012/59290
Iteration: 30013/59290
Iteration: 30014/59290
Iteration: 30015/59290
Iteration: 30016/59290
Iteration: 30017/59290
Iteration: 30018/59290
Iteration: 30019/59290
Iteration: 30020/59290
Iteration: 30021/59290
Iteration: 30022/59290
Iteration: 30023/59290
Iteration: 30024/59290

 51%|█████     | 30014/59290 [21:21<10:23, 46.96it/s]

Iteration: 30025/59290
Iteration: 30026/59290
Iteration: 30027/59290
Iteration: 30028/59290
Iteration: 30029/59290
Iteration: 30030/59290
Iteration: 30031/59290
Iteration: 30032/59290
Iteration: 30033/59290
Iteration: 30034/59290
Iteration: 30035/59290
Iteration: 30036/59290
Iteration: 30037/59290
Iteration: 30038/59290
Iteration: 30039/59290
Iteration: 30040/59290
Iteration: 30041/59290
Iteration: 30042/59290
Iteration: 30043/59290
Iteration: 30044/59290
Iteration: 30045/59290
Iteration: 30046/59290
Iteration: 30047/59290
Iteration: 30048/59290

 51%|█████     | 30038/59290 [21:22<09:35, 50.83it/s]

Iteration: 30049/59290
Iteration: 30050/59290
Iteration: 30051/59290
Iteration: 30052/59290
Iteration: 30053/59290
Iteration: 30054/59290
Iteration: 30055/59290
Iteration: 30056/59290
Iteration: 30057/59290
Iteration: 30058/59290
Iteration: 30059/59290
Iteration: 30060/59290
Iteration: 30061/59290
Iteration: 30062/59290
Iteration: 30063/59290
Iteration: 30064/59290
Iteration: 30065/59290
Iteration: 30066/59290
Iteration: 30067/59290
Iteration: 30068/59290
Iteration: 30069/59290
Iteration: 30070/59290
Iteration: 30071/59290
Iteration: 30072/59290

 51%|█████     | 30062/59290 [21:22<09:04, 53.68it/s]

Iteration: 30073/59290
Iteration: 30074/59290
Iteration: 30075/59290
Iteration: 30076/59290
Iteration: 30077/59290
Iteration: 30078/59290
Iteration: 30079/59290
Iteration: 30080/59290
Iteration: 30081/59290
Iteration: 30082/59290
Iteration: 30083/59290
Iteration: 30084/59290
Iteration: 30085/59290
Iteration: 30086/59290
Iteration: 30087/59290
Iteration: 30088/59290
Iteration: 30089/59290
Iteration: 30090/59290
Iteration: 30091/59290
Iteration: 30092/59290
Iteration: 30093/59290
Iteration: 30094/59290
Iteration: 30095/59290
Iteration: 30096/59290

 51%|█████     | 30086/59290 [21:23<08:36, 56.50it/s]

Iteration: 30097/59290
Iteration: 30098/59290
Iteration: 30099/59290
Iteration: 30100/59290
Iteration: 30101/59290
Iteration: 30102/59290
Iteration: 30103/59290
Iteration: 30104/59290
Iteration: 30105/59290
Iteration: 30106/59290
Iteration: 30107/59290
Iteration: 30108/59290
Iteration: 30109/59290
Iteration: 30110/59290
Iteration: 30111/59290
Iteration: 30112/59290
Iteration: 30113/59290
Iteration: 30114/59290
Iteration: 30115/59290
Iteration: 30116/59290
Iteration: 30117/59290
Iteration: 30118/59290
Iteration: 30119/59290
Iteration: 30120/59290

 51%|█████     | 30110/59290 [21:24<15:27, 31.47it/s]

Iteration: 30121/59290
Iteration: 30122/59290
Iteration: 30123/59290
Iteration: 30124/59290
Iteration: 30125/59290
Iteration: 30126/59290
Iteration: 30127/59290
Iteration: 30128/59290
Iteration: 30129/59290
Iteration: 30130/59290
Iteration: 30131/59290
Iteration: 30132/59290
Iteration: 30133/59290
Iteration: 30134/59290
Iteration: 30135/59290
Iteration: 30136/59290
Iteration: 30137/59290
Iteration: 30138/59290
Iteration: 30139/59290
Iteration: 30140/59290
Iteration: 30141/59290
Iteration: 30142/59290
Iteration: 30143/59290
Iteration: 30144/59290

 51%|█████     | 30134/59290 [21:26<23:40, 20.52it/s]

Iteration: 30145/59290
Iteration: 30146/59290
Iteration: 30147/59290
Iteration: 30148/59290
Iteration: 30149/59290
Iteration: 30150/59290
Iteration: 30151/59290
Iteration: 30152/59290
Iteration: 30153/59290
Iteration: 30154/59290
Iteration: 30155/59290
Iteration: 30156/59290
Iteration: 30157/59290
Iteration: 30158/59290
Iteration: 30159/59290
Iteration: 30160/59290
Iteration: 30161/59290
Iteration: 30162/59290
Iteration: 30163/59290
Iteration: 30164/59290
Iteration: 30165/59290
Iteration: 30166/59290
Iteration: 30167/59290
Iteration: 30168/59290

 51%|█████     | 30158/59290 [21:27<20:59, 23.13it/s]

Iteration: 30169/59290
Iteration: 30170/59290
Iteration: 30171/59290
Iteration: 30172/59290
Iteration: 30173/59290
Iteration: 30174/59290
Iteration: 30175/59290
Iteration: 30176/59290
Iteration: 30177/59290
Iteration: 30178/59290
Iteration: 30179/59290
Iteration: 30180/59290
Iteration: 30181/59290
Iteration: 30182/59290
Iteration: 30183/59290
Iteration: 30184/59290
Iteration: 30185/59290
Iteration: 30186/59290
Iteration: 30187/59290
Iteration: 30188/59290
Iteration: 30189/59290
Iteration: 30190/59290
Iteration: 30191/59290
Iteration: 30192/59290

 51%|█████     | 30182/59290 [21:27<16:56, 28.64it/s]

Iteration: 30193/59290
Iteration: 30194/59290
Iteration: 30195/59290
Iteration: 30196/59290
Iteration: 30197/59290
Iteration: 30198/59290
Iteration: 30199/59290
Iteration: 30200/59290
Iteration: 30201/59290
Iteration: 30202/59290
Iteration: 30203/59290
Iteration: 30204/59290
Iteration: 30205/59290
Iteration: 30206/59290
Iteration: 30207/59290
Iteration: 30208/59290
Iteration: 30209/59290
Iteration: 30210/59290
Iteration: 30211/59290
Iteration: 30212/59290
Iteration: 30213/59290
Iteration: 30214/59290
Iteration: 30215/59290
Iteration: 30216/59290

 51%|█████     | 30206/59290 [21:28<14:14, 34.02it/s]

Iteration: 30217/59290
Iteration: 30218/59290
Iteration: 30219/59290
Iteration: 30220/59290
Iteration: 30221/59290
Iteration: 30222/59290
Iteration: 30223/59290
Iteration: 30224/59290
Iteration: 30225/59290
Iteration: 30226/59290
Iteration: 30227/59290
Iteration: 30228/59290
Iteration: 30229/59290
Iteration: 30230/59290
Iteration: 30231/59290
Iteration: 30232/59290
Iteration: 30233/59290
Iteration: 30234/59290
Iteration: 30235/59290
Iteration: 30236/59290
Iteration: 30237/59290
Iteration: 30238/59290
Iteration: 30239/59290
Iteration: 30240/59290

 51%|█████     | 30230/59290 [21:28<12:16, 39.46it/s]

Iteration: 30241/59290
Iteration: 30242/59290
Iteration: 30243/59290
Iteration: 30244/59290
Iteration: 30245/59290
Iteration: 30246/59290
Iteration: 30247/59290
Iteration: 30248/59290
Iteration: 30249/59290
Iteration: 30250/59290
Iteration: 30251/59290
Iteration: 30252/59290
Iteration: 30253/59290
Iteration: 30254/59290
Iteration: 30255/59290
Iteration: 30256/59290
Iteration: 30257/59290
Iteration: 30258/59290
Iteration: 30259/59290
Iteration: 30260/59290
Iteration: 30261/59290
Iteration: 30262/59290
Iteration: 30263/59290
Iteration: 30264/59290

 51%|█████     | 30254/59290 [21:28<10:50, 44.61it/s]

Iteration: 30265/59290
Iteration: 30266/59290
Iteration: 30267/59290
Iteration: 30268/59290
Iteration: 30269/59290
Iteration: 30270/59290
Iteration: 30271/59290
Iteration: 30272/59290
Iteration: 30273/59290
Iteration: 30274/59290
Iteration: 30275/59290
Iteration: 30276/59290
Iteration: 30277/59290
Iteration: 30278/59290
Iteration: 30279/59290
Iteration: 30280/59290
Iteration: 30281/59290
Iteration: 30282/59290
Iteration: 30283/59290
Iteration: 30284/59290
Iteration: 30285/59290
Iteration: 30286/59290
Iteration: 30287/59290
Iteration: 30288/59290

 51%|█████     | 30278/59290 [21:29<09:49, 49.20it/s]

Iteration: 30289/59290
Iteration: 30290/59290
Iteration: 30291/59290
Iteration: 30292/59290
Iteration: 30293/59290
Iteration: 30294/59290
Iteration: 30295/59290
Iteration: 30296/59290
Iteration: 30297/59290
Iteration: 30298/59290
Iteration: 30299/59290
Iteration: 30300/59290
Iteration: 30301/59290
Iteration: 30302/59290
Iteration: 30303/59290
Iteration: 30304/59290
Iteration: 30305/59290
Iteration: 30306/59290
Iteration: 30307/59290
Iteration: 30308/59290
Iteration: 30309/59290
Iteration: 30310/59290
Iteration: 30311/59290
Iteration: 30312/59290

 51%|█████     | 30302/59290 [21:29<09:07, 52.99it/s]

Iteration: 30313/59290
Iteration: 30314/59290
Iteration: 30315/59290
Iteration: 30316/59290
Iteration: 30317/59290
Iteration: 30318/59290
Iteration: 30319/59290
Iteration: 30320/59290
Iteration: 30321/59290
Iteration: 30322/59290
Iteration: 30323/59290
Iteration: 30324/59290
Iteration: 30325/59290
Iteration: 30326/59290
Iteration: 30327/59290
Iteration: 30328/59290
Iteration: 30329/59290
Iteration: 30330/59290
Iteration: 30331/59290
Iteration: 30332/59290
Iteration: 30333/59290
Iteration: 30334/59290
Iteration: 30335/59290
Iteration: 30336/59290

 51%|█████     | 30326/59290 [21:30<08:38, 55.88it/s]

Iteration: 30337/59290
Iteration: 30338/59290
Iteration: 30339/59290
Iteration: 30340/59290
Iteration: 30341/59290
Iteration: 30342/59290
Iteration: 30343/59290
Iteration: 30344/59290
Iteration: 30345/59290
Iteration: 30346/59290
Iteration: 30347/59290
Iteration: 30348/59290
Iteration: 30349/59290
Iteration: 30350/59290
Iteration: 30351/59290
Iteration: 30352/59290
Iteration: 30353/59290
Iteration: 30354/59290
Iteration: 30355/59290
Iteration: 30356/59290
Iteration: 30357/59290
Iteration: 30358/59290
Iteration: 30359/59290
Iteration: 30360/59290

 51%|█████     | 30350/59290 [21:30<08:20, 57.83it/s]

Iteration: 30361/59290
Iteration: 30362/59290
Iteration: 30363/59290
Iteration: 30364/59290
Iteration: 30365/59290
Iteration: 30366/59290
Iteration: 30367/59290
Iteration: 30368/59290
Iteration: 30369/59290
Iteration: 30370/59290
Iteration: 30371/59290
Iteration: 30372/59290
Iteration: 30373/59290
Iteration: 30374/59290
Iteration: 30375/59290
Iteration: 30376/59290
Iteration: 30377/59290
Iteration: 30378/59290
Iteration: 30379/59290
Iteration: 30380/59290
Iteration: 30381/59290
Iteration: 30382/59290
Iteration: 30383/59290
Iteration: 30384/59290

 51%|█████     | 30374/59290 [21:30<08:04, 59.65it/s]

Iteration: 30385/59290
Iteration: 30386/59290
Iteration: 30387/59290
Iteration: 30388/59290
Iteration: 30389/59290
Iteration: 30390/59290
Iteration: 30391/59290
Iteration: 30392/59290
Iteration: 30393/59290
Iteration: 30394/59290
Iteration: 30395/59290
Iteration: 30396/59290
Iteration: 30397/59290
Iteration: 30398/59290
Iteration: 30399/59290
Iteration: 30400/59290
Iteration: 30401/59290
Iteration: 30402/59290
Iteration: 30403/59290
Iteration: 30404/59290
Iteration: 30405/59290
Iteration: 30406/59290
Iteration: 30407/59290
Iteration: 30408/59290

 51%|█████▏    | 30398/59290 [21:31<07:57, 60.48it/s]

Iteration: 30409/59290
Iteration: 30410/59290
Iteration: 30411/59290
Iteration: 30412/59290
Iteration: 30413/59290
Iteration: 30414/59290
Iteration: 30415/59290
Iteration: 30416/59290
Iteration: 30417/59290
Iteration: 30418/59290
Iteration: 30419/59290
Iteration: 30420/59290
Iteration: 30421/59290
Iteration: 30422/59290
Iteration: 30423/59290
Iteration: 30424/59290
Iteration: 30425/59290
Iteration: 30426/59290
Iteration: 30427/59290
Iteration: 30428/59290
Iteration: 30429/59290
Iteration: 30430/59290
Iteration: 30431/59290
Iteration: 30432/59290

 51%|█████▏    | 30422/59290 [21:32<14:15, 33.74it/s]

Iteration: 30433/59290
Iteration: 30434/59290
Iteration: 30435/59290
Iteration: 30436/59290
Iteration: 30437/59290
Iteration: 30438/59290
Iteration: 30439/59290
Iteration: 30440/59290
Iteration: 30441/59290
Iteration: 30442/59290
Iteration: 30443/59290
Iteration: 30444/59290
Iteration: 30445/59290
Iteration: 30446/59290
Iteration: 30447/59290
Iteration: 30448/59290
Iteration: 30449/59290
Iteration: 30450/59290
Iteration: 30451/59290
Iteration: 30452/59290
Iteration: 30453/59290
Iteration: 30454/59290
Iteration: 30455/59290
Iteration: 30456/59290

 51%|█████▏    | 30446/59290 [21:35<24:44, 19.43it/s]

Iteration: 30457/59290
Iteration: 30458/59290
Iteration: 30459/59290
Iteration: 30460/59290
Iteration: 30461/59290
Iteration: 30462/59290
Iteration: 30463/59290
Iteration: 30464/59290
Iteration: 30465/59290
Iteration: 30466/59290
Iteration: 30467/59290
Iteration: 30468/59290
Iteration: 30469/59290
Iteration: 30470/59290
Iteration: 30471/59290
Iteration: 30472/59290
Iteration: 30473/59290
Iteration: 30474/59290
Iteration: 30475/59290
Iteration: 30476/59290
Iteration: 30477/59290
Iteration: 30478/59290
Iteration: 30479/59290
Iteration: 30480/59290

 51%|█████▏    | 30470/59290 [21:35<19:36, 24.51it/s]

Iteration: 30481/59290
Iteration: 30482/59290
Iteration: 30483/59290
Iteration: 30484/59290
Iteration: 30485/59290
Iteration: 30486/59290
Iteration: 30487/59290
Iteration: 30488/59290
Iteration: 30489/59290
Iteration: 30490/59290
Iteration: 30491/59290
Iteration: 30492/59290
Iteration: 30493/59290
Iteration: 30494/59290
Iteration: 30495/59290
Iteration: 30496/59290
Iteration: 30497/59290
Iteration: 30498/59290
Iteration: 30499/59290
Iteration: 30500/59290
Iteration: 30501/59290
Iteration: 30502/59290
Iteration: 30503/59290
Iteration: 30504/59290

 51%|█████▏    | 30494/59290 [21:35<15:59, 30.00it/s]

Iteration: 30505/59290
Iteration: 30506/59290
Iteration: 30507/59290
Iteration: 30508/59290
Iteration: 30509/59290
Iteration: 30510/59290
Iteration: 30511/59290
Iteration: 30512/59290
Iteration: 30513/59290
Iteration: 30514/59290
Iteration: 30515/59290
Iteration: 30516/59290
Iteration: 30517/59290
Iteration: 30518/59290
Iteration: 30519/59290
Iteration: 30520/59290
Iteration: 30521/59290
Iteration: 30522/59290
Iteration: 30523/59290
Iteration: 30524/59290
Iteration: 30525/59290
Iteration: 30526/59290
Iteration: 30527/59290
Iteration: 30528/59290

 51%|█████▏    | 30518/59290 [21:36<13:25, 35.72it/s]

Iteration: 30529/59290
Iteration: 30530/59290
Iteration: 30531/59290
Iteration: 30532/59290
Iteration: 30533/59290
Iteration: 30534/59290
Iteration: 30535/59290
Iteration: 30536/59290
Iteration: 30537/59290
Iteration: 30538/59290
Iteration: 30539/59290
Iteration: 30540/59290
Iteration: 30541/59290
Iteration: 30542/59290
Iteration: 30543/59290
Iteration: 30544/59290
Iteration: 30545/59290
Iteration: 30546/59290
Iteration: 30547/59290
Iteration: 30548/59290
Iteration: 30549/59290
Iteration: 30550/59290
Iteration: 30551/59290
Iteration: 30552/59290

 52%|█████▏    | 30542/59290 [21:36<11:36, 41.26it/s]

Iteration: 30553/59290
Iteration: 30554/59290
Iteration: 30555/59290
Iteration: 30556/59290
Iteration: 30557/59290
Iteration: 30558/59290
Iteration: 30559/59290
Iteration: 30560/59290
Iteration: 30561/59290
Iteration: 30562/59290
Iteration: 30563/59290
Iteration: 30564/59290
Iteration: 30565/59290
Iteration: 30566/59290
Iteration: 30567/59290
Iteration: 30568/59290
Iteration: 30569/59290
Iteration: 30570/59290
Iteration: 30571/59290
Iteration: 30572/59290
Iteration: 30573/59290
Iteration: 30574/59290
Iteration: 30575/59290
Iteration: 30576/59290

 52%|█████▏    | 30566/59290 [21:38<16:57, 28.22it/s]

Iteration: 30577/59290
Iteration: 30578/59290
Iteration: 30579/59290
Iteration: 30580/59290
Iteration: 30581/59290
Iteration: 30582/59290
Iteration: 30583/59290
Iteration: 30584/59290
Iteration: 30585/59290
Iteration: 30586/59290
Iteration: 30587/59290
Iteration: 30588/59290
Iteration: 30589/59290
Iteration: 30590/59290
Iteration: 30591/59290
Iteration: 30592/59290
Iteration: 30593/59290
Iteration: 30594/59290
Iteration: 30595/59290
Iteration: 30596/59290
Iteration: 30597/59290
Iteration: 30598/59290
Iteration: 30599/59290
Iteration: 30600/59290

 52%|█████▏    | 30590/59290 [21:40<26:18, 18.18it/s]

Iteration: 30601/59290
Iteration: 30602/59290
Iteration: 30603/59290
Iteration: 30604/59290
Iteration: 30605/59290
Iteration: 30606/59290
Iteration: 30607/59290
Iteration: 30608/59290
Iteration: 30609/59290
Iteration: 30610/59290
Iteration: 30611/59290
Iteration: 30612/59290
Iteration: 30613/59290
Iteration: 30614/59290
Iteration: 30615/59290
Iteration: 30616/59290
Iteration: 30617/59290
Iteration: 30618/59290
Iteration: 30619/59290
Iteration: 30620/59290
Iteration: 30621/59290
Iteration: 30622/59290
Iteration: 30623/59290
Iteration: 30624/59290

 52%|█████▏    | 30614/59290 [21:40<20:44, 23.04it/s]

Iteration: 30625/59290
Iteration: 30626/59290
Iteration: 30627/59290
Iteration: 30628/59290
Iteration: 30629/59290
Iteration: 30630/59290
Iteration: 30631/59290
Iteration: 30632/59290
Iteration: 30633/59290
Iteration: 30634/59290
Iteration: 30635/59290
Iteration: 30636/59290
Iteration: 30637/59290
Iteration: 30638/59290
Iteration: 30639/59290
Iteration: 30640/59290
Iteration: 30641/59290
Iteration: 30642/59290
Iteration: 30643/59290
Iteration: 30644/59290
Iteration: 30645/59290
Iteration: 30646/59290
Iteration: 30647/59290
Iteration: 30648/59290

 52%|█████▏    | 30638/59290 [21:41<16:44, 28.52it/s]

Iteration: 30649/59290
Iteration: 30650/59290
Iteration: 30651/59290
Iteration: 30652/59290
Iteration: 30653/59290
Iteration: 30654/59290
Iteration: 30655/59290
Iteration: 30656/59290
Iteration: 30657/59290
Iteration: 30658/59290
Iteration: 30659/59290
Iteration: 30660/59290
Iteration: 30661/59290
Iteration: 30662/59290
Iteration: 30663/59290
Iteration: 30664/59290
Iteration: 30665/59290
Iteration: 30666/59290
Iteration: 30667/59290
Iteration: 30668/59290
Iteration: 30669/59290
Iteration: 30670/59290
Iteration: 30671/59290
Iteration: 30672/59290

 52%|█████▏    | 30662/59290 [21:42<21:58, 21.72it/s]

Iteration: 30673/59290
Iteration: 30674/59290
Iteration: 30675/59290
Iteration: 30676/59290
Iteration: 30677/59290
Iteration: 30678/59290
Iteration: 30679/59290
Iteration: 30680/59290
Iteration: 30681/59290
Iteration: 30682/59290
Iteration: 30683/59290
Iteration: 30684/59290
Iteration: 30685/59290
Iteration: 30686/59290
Iteration: 30687/59290
Iteration: 30688/59290
Iteration: 30689/59290
Iteration: 30690/59290
Iteration: 30691/59290
Iteration: 30692/59290
Iteration: 30693/59290
Iteration: 30694/59290
Iteration: 30695/59290
Iteration: 30696/59290

 52%|█████▏    | 30686/59290 [21:45<29:25, 16.20it/s]

Iteration: 30697/59290
Iteration: 30698/59290
Iteration: 30699/59290
Iteration: 30700/59290
Iteration: 30701/59290
Iteration: 30702/59290
Iteration: 30703/59290
Iteration: 30704/59290
Iteration: 30705/59290
Iteration: 30706/59290
Iteration: 30707/59290
Iteration: 30708/59290
Iteration: 30709/59290
Iteration: 30710/59290
Iteration: 30711/59290
Iteration: 30712/59290
Iteration: 30713/59290
Iteration: 30714/59290
Iteration: 30715/59290
Iteration: 30716/59290
Iteration: 30717/59290
Iteration: 30718/59290
Iteration: 30719/59290
Iteration: 30720/59290

 52%|█████▏    | 30710/59290 [21:45<22:54, 20.79it/s]

Iteration: 30721/59290
Iteration: 30722/59290
Iteration: 30723/59290
Iteration: 30724/59290
Iteration: 30725/59290
Iteration: 30726/59290
Iteration: 30727/59290
Iteration: 30728/59290
Iteration: 30729/59290
Iteration: 30730/59290
Iteration: 30731/59290
Iteration: 30732/59290
Iteration: 30733/59290
Iteration: 30734/59290
Iteration: 30735/59290
Iteration: 30736/59290
Iteration: 30737/59290
Iteration: 30738/59290
Iteration: 30739/59290
Iteration: 30740/59290
Iteration: 30741/59290
Iteration: 30742/59290
Iteration: 30743/59290
Iteration: 30744/59290

 52%|█████▏    | 30734/59290 [21:46<18:15, 26.07it/s]

Iteration: 30745/59290
Iteration: 30746/59290
Iteration: 30747/59290
Iteration: 30748/59290
Iteration: 30749/59290
Iteration: 30750/59290
Iteration: 30751/59290
Iteration: 30752/59290
Iteration: 30753/59290
Iteration: 30754/59290
Iteration: 30755/59290
Iteration: 30756/59290
Iteration: 30757/59290
Iteration: 30758/59290
Iteration: 30759/59290
Iteration: 30760/59290
Iteration: 30761/59290
Iteration: 30762/59290
Iteration: 30763/59290
Iteration: 30764/59290
Iteration: 30765/59290
Iteration: 30766/59290
Iteration: 30767/59290
Iteration: 30768/59290

 52%|█████▏    | 30758/59290 [21:47<22:44, 20.91it/s]

Iteration: 30769/59290
Iteration: 30770/59290
Iteration: 30771/59290
Iteration: 30772/59290
Iteration: 30773/59290
Iteration: 30774/59290
Iteration: 30775/59290
Iteration: 30776/59290
Iteration: 30777/59290
Iteration: 30778/59290
Iteration: 30779/59290
Iteration: 30780/59290
Iteration: 30781/59290
Iteration: 30782/59290
Iteration: 30783/59290
Iteration: 30784/59290
Iteration: 30785/59290
Iteration: 30786/59290
Iteration: 30787/59290
Iteration: 30788/59290
Iteration: 30789/59290
Iteration: 30790/59290
Iteration: 30791/59290
Iteration: 30792/59290

 52%|█████▏    | 30782/59290 [21:49<27:38, 17.19it/s]

Iteration: 30793/59290
Iteration: 30794/59290
Iteration: 30795/59290
Iteration: 30796/59290
Iteration: 30797/59290
Iteration: 30798/59290
Iteration: 30799/59290
Iteration: 30800/59290
Iteration: 30801/59290
Iteration: 30802/59290
Iteration: 30803/59290
Iteration: 30804/59290
Iteration: 30805/59290
Iteration: 30806/59290
Iteration: 30807/59290
Iteration: 30808/59290
Iteration: 30809/59290
Iteration: 30810/59290
Iteration: 30811/59290
Iteration: 30812/59290
Iteration: 30813/59290
Iteration: 30814/59290
Iteration: 30815/59290
Iteration: 30816/59290

 52%|█████▏    | 30806/59290 [21:50<21:47, 21.78it/s]

Iteration: 30817/59290
Iteration: 30818/59290
Iteration: 30819/59290
Iteration: 30820/59290
Iteration: 30821/59290
Iteration: 30822/59290
Iteration: 30823/59290
Iteration: 30824/59290
Iteration: 30825/59290
Iteration: 30826/59290
Iteration: 30827/59290
Iteration: 30828/59290
Iteration: 30829/59290
Iteration: 30830/59290
Iteration: 30831/59290
Iteration: 30832/59290
Iteration: 30833/59290
Iteration: 30834/59290
Iteration: 30835/59290
Iteration: 30836/59290
Iteration: 30837/59290
Iteration: 30838/59290
Iteration: 30839/59290
Iteration: 30840/59290

 52%|█████▏    | 30830/59290 [21:50<17:28, 27.15it/s]

Iteration: 30841/59290
Iteration: 30842/59290
Iteration: 30843/59290
Iteration: 30844/59290
Iteration: 30845/59290
Iteration: 30846/59290
Iteration: 30847/59290
Iteration: 30848/59290
Iteration: 30849/59290
Iteration: 30850/59290
Iteration: 30851/59290
Iteration: 30852/59290
Iteration: 30853/59290
Iteration: 30854/59290
Iteration: 30855/59290
Iteration: 30856/59290
Iteration: 30857/59290
Iteration: 30858/59290
Iteration: 30859/59290
Iteration: 30860/59290
Iteration: 30861/59290
Iteration: 30862/59290
Iteration: 30863/59290
Iteration: 30864/59290

 52%|█████▏    | 30854/59290 [21:50<14:28, 32.74it/s]

Iteration: 30865/59290
Iteration: 30866/59290
Iteration: 30867/59290
Iteration: 30868/59290
Iteration: 30869/59290
Iteration: 30870/59290
Iteration: 30871/59290
Iteration: 30872/59290
Iteration: 30873/59290
Iteration: 30874/59290
Iteration: 30875/59290
Iteration: 30876/59290
Iteration: 30877/59290
Iteration: 30878/59290
Iteration: 30879/59290
Iteration: 30880/59290
Iteration: 30881/59290
Iteration: 30882/59290
Iteration: 30883/59290
Iteration: 30884/59290
Iteration: 30885/59290
Iteration: 30886/59290
Iteration: 30887/59290
Iteration: 30888/59290

 52%|█████▏    | 30878/59290 [21:51<12:23, 38.20it/s]

Iteration: 30889/59290
Iteration: 30890/59290
Iteration: 30891/59290
Iteration: 30892/59290
Iteration: 30893/59290
Iteration: 30894/59290
Iteration: 30895/59290
Iteration: 30896/59290
Iteration: 30897/59290
Iteration: 30898/59290
Iteration: 30899/59290
Iteration: 30900/59290
Iteration: 30901/59290
Iteration: 30902/59290
Iteration: 30903/59290
Iteration: 30904/59290
Iteration: 30905/59290
Iteration: 30906/59290
Iteration: 30907/59290
Iteration: 30908/59290
Iteration: 30909/59290
Iteration: 30910/59290
Iteration: 30911/59290
Iteration: 30912/59290

 52%|█████▏    | 30902/59290 [21:51<10:54, 43.36it/s]

Iteration: 30913/59290
Iteration: 30914/59290
Iteration: 30915/59290
Iteration: 30916/59290
Iteration: 30917/59290
Iteration: 30918/59290
Iteration: 30919/59290
Iteration: 30920/59290
Iteration: 30921/59290
Iteration: 30922/59290
Iteration: 30923/59290
Iteration: 30924/59290
Iteration: 30925/59290
Iteration: 30926/59290
Iteration: 30927/59290
Iteration: 30928/59290
Iteration: 30929/59290
Iteration: 30930/59290
Iteration: 30931/59290
Iteration: 30932/59290
Iteration: 30933/59290
Iteration: 30934/59290
Iteration: 30935/59290
Iteration: 30936/59290

 52%|█████▏    | 30926/59290 [21:52<09:49, 48.09it/s]

Iteration: 30937/59290
Iteration: 30938/59290
Iteration: 30939/59290
Iteration: 30940/59290
Iteration: 30941/59290
Iteration: 30942/59290
Iteration: 30943/59290
Iteration: 30944/59290
Iteration: 30945/59290
Iteration: 30946/59290
Iteration: 30947/59290
Iteration: 30948/59290
Iteration: 30949/59290
Iteration: 30950/59290
Iteration: 30951/59290
Iteration: 30952/59290
Iteration: 30953/59290
Iteration: 30954/59290
Iteration: 30955/59290
Iteration: 30956/59290
Iteration: 30957/59290
Iteration: 30958/59290
Iteration: 30959/59290
Iteration: 30960/59290

 52%|█████▏    | 30950/59290 [21:52<09:06, 51.84it/s]

Iteration: 30961/59290
Iteration: 30962/59290
Iteration: 30963/59290
Iteration: 30964/59290
Iteration: 30965/59290
Iteration: 30966/59290
Iteration: 30967/59290
Iteration: 30968/59290
Iteration: 30969/59290
Iteration: 30970/59290
Iteration: 30971/59290
Iteration: 30972/59290
Iteration: 30973/59290
Iteration: 30974/59290
Iteration: 30975/59290
Iteration: 30976/59290
Iteration: 30977/59290
Iteration: 30978/59290
Iteration: 30979/59290
Iteration: 30980/59290
Iteration: 30981/59290
Iteration: 30982/59290
Iteration: 30983/59290
Iteration: 30984/59290

 52%|█████▏    | 30974/59290 [21:52<08:35, 54.90it/s]

Iteration: 30985/59290
Iteration: 30986/59290
Iteration: 30987/59290
Iteration: 30988/59290
Iteration: 30989/59290
Iteration: 30990/59290
Iteration: 30991/59290
Iteration: 30992/59290
Iteration: 30993/59290
Iteration: 30994/59290
Iteration: 30995/59290
Iteration: 30996/59290
Iteration: 30997/59290
Iteration: 30998/59290
Iteration: 30999/59290
Iteration: 31000/59290
Iteration: 31001/59290
Iteration: 31002/59290
Iteration: 31003/59290
Iteration: 31004/59290
Iteration: 31005/59290
Iteration: 31006/59290
Iteration: 31007/59290
Iteration: 31008/59290

 52%|█████▏    | 30998/59290 [21:53<08:21, 56.38it/s]

Iteration: 31009/59290
Iteration: 31010/59290
Iteration: 31011/59290
Iteration: 31012/59290
Iteration: 31013/59290
Iteration: 31014/59290
Iteration: 31015/59290
Iteration: 31016/59290
Iteration: 31017/59290
Iteration: 31018/59290
Iteration: 31019/59290
Iteration: 31020/59290
Iteration: 31021/59290
Iteration: 31022/59290
Iteration: 31023/59290
Iteration: 31024/59290
Iteration: 31025/59290
Iteration: 31026/59290
Iteration: 31027/59290
Iteration: 31028/59290
Iteration: 31029/59290
Iteration: 31030/59290
Iteration: 31031/59290
Iteration: 31032/59290

 52%|█████▏    | 31022/59290 [21:54<14:15, 33.06it/s]

Iteration: 31033/59290
Iteration: 31034/59290
Iteration: 31035/59290
Iteration: 31036/59290
Iteration: 31037/59290
Iteration: 31038/59290
Iteration: 31039/59290
Iteration: 31040/59290
Iteration: 31041/59290
Iteration: 31042/59290
Iteration: 31043/59290
Iteration: 31044/59290
Iteration: 31045/59290
Iteration: 31046/59290
Iteration: 31047/59290
Iteration: 31048/59290
Iteration: 31049/59290
Iteration: 31050/59290
Iteration: 31051/59290
Iteration: 31052/59290
Iteration: 31053/59290
Iteration: 31054/59290
Iteration: 31055/59290
Iteration: 31056/59290

 52%|█████▏    | 31046/59290 [22:27<3:21:13,  2.34it/s]

Iteration: 31057/59290
Iteration: 31058/59290
Iteration: 31059/59290
Iteration: 31060/59290
Iteration: 31061/59290
Iteration: 31062/59290
Iteration: 31063/59290
Iteration: 31064/59290
Iteration: 31065/59290
Iteration: 31066/59290
Iteration: 31067/59290
Iteration: 31068/59290
Iteration: 31069/59290
Iteration: 31070/59290
Iteration: 31071/59290
Iteration: 31072/59290
Iteration: 31073/59290
Iteration: 31074/59290
Iteration: 31075/59290
Iteration: 31076/59290
Iteration: 31077/59290
Iteration: 31078/59290
Iteration: 31079/59290
Iteration: 31080/59290

 52%|█████▏    | 31070/59290 [22:27<2:22:55,  3.29it/s]

Iteration: 31081/59290
Iteration: 31082/59290
Iteration: 31083/59290
Iteration: 31084/59290
Iteration: 31085/59290
Iteration: 31086/59290
Iteration: 31087/59290
Iteration: 31088/59290
Iteration: 31089/59290
Iteration: 31090/59290
Iteration: 31091/59290
Iteration: 31092/59290
Iteration: 31093/59290
Iteration: 31094/59290
Iteration: 31095/59290
Iteration: 31096/59290
Iteration: 31097/59290
Iteration: 31098/59290
Iteration: 31099/59290
Iteration: 31100/59290
Iteration: 31101/59290
Iteration: 31102/59290
Iteration: 31103/59290
Iteration: 31104/59290

 52%|█████▏    | 31094/59290 [22:27<1:42:12,  4.60it/s]

Iteration: 31105/59290
Iteration: 31106/59290
Iteration: 31107/59290
Iteration: 31108/59290
Iteration: 31109/59290
Iteration: 31110/59290
Iteration: 31111/59290
Iteration: 31112/59290
Iteration: 31113/59290
Iteration: 31114/59290
Iteration: 31115/59290
Iteration: 31116/59290
Iteration: 31117/59290
Iteration: 31118/59290
Iteration: 31119/59290
Iteration: 31120/59290
Iteration: 31121/59290
Iteration: 31122/59290
Iteration: 31123/59290
Iteration: 31124/59290
Iteration: 31125/59290
Iteration: 31126/59290
Iteration: 31127/59290
Iteration: 31128/59290

 52%|█████▏    | 31118/59290 [22:28<1:13:45,  6.37it/s]

Iteration: 31129/59290
Iteration: 31130/59290
Iteration: 31131/59290
Iteration: 31132/59290
Iteration: 31133/59290
Iteration: 31134/59290
Iteration: 31135/59290
Iteration: 31136/59290
Iteration: 31137/59290
Iteration: 31138/59290
Iteration: 31139/59290
Iteration: 31140/59290
Iteration: 31141/59290
Iteration: 31142/59290
Iteration: 31143/59290
Iteration: 31144/59290
Iteration: 31145/59290
Iteration: 31146/59290
Iteration: 31147/59290
Iteration: 31148/59290
Iteration: 31149/59290
Iteration: 31150/59290
Iteration: 31151/59290
Iteration: 31152/59290

 53%|█████▎    | 31142/59290 [22:28<53:51,  8.71it/s]

Iteration: 31153/59290
Iteration: 31154/59290
Iteration: 31155/59290
Iteration: 31156/59290
Iteration: 31157/59290
Iteration: 31158/59290
Iteration: 31159/59290
Iteration: 31160/59290
Iteration: 31161/59290
Iteration: 31162/59290
Iteration: 31163/59290
Iteration: 31164/59290
Iteration: 31165/59290
Iteration: 31166/59290
Iteration: 31167/59290
Iteration: 31168/59290
Iteration: 31169/59290
Iteration: 31170/59290
Iteration: 31171/59290
Iteration: 31172/59290
Iteration: 31173/59290
Iteration: 31174/59290
Iteration: 31175/59290
Iteration: 31176/59290

 53%|█████▎    | 31166/59290 [22:29<39:52, 11.75it/s]

Iteration: 31177/59290
Iteration: 31178/59290
Iteration: 31179/59290
Iteration: 31180/59290
Iteration: 31181/59290
Iteration: 31182/59290
Iteration: 31183/59290
Iteration: 31184/59290
Iteration: 31185/59290
Iteration: 31186/59290
Iteration: 31187/59290
Iteration: 31188/59290
Iteration: 31189/59290
Iteration: 31190/59290
Iteration: 31191/59290
Iteration: 31192/59290
Iteration: 31193/59290
Iteration: 31194/59290
Iteration: 31195/59290
Iteration: 31196/59290
Iteration: 31197/59290
Iteration: 31198/59290
Iteration: 31199/59290
Iteration: 31200/59290

 53%|█████▎    | 31190/59290 [22:29<30:11, 15.51it/s]

Iteration: 31201/59290
Iteration: 31202/59290
Iteration: 31203/59290
Iteration: 31204/59290
Iteration: 31205/59290
Iteration: 31206/59290
Iteration: 31207/59290
Iteration: 31208/59290
Iteration: 31209/59290
Iteration: 31210/59290
Iteration: 31211/59290
Iteration: 31212/59290
Iteration: 31213/59290
Iteration: 31214/59290
Iteration: 31215/59290
Iteration: 31216/59290
Iteration: 31217/59290
Iteration: 31218/59290
Iteration: 31219/59290
Iteration: 31220/59290
Iteration: 31221/59290
Iteration: 31222/59290
Iteration: 31223/59290
Iteration: 31224/59290

 53%|█████▎    | 31214/59290 [22:29<23:16, 20.10it/s]

Iteration: 31225/59290
Iteration: 31226/59290
Iteration: 31227/59290
Iteration: 31228/59290
Iteration: 31229/59290
Iteration: 31230/59290
Iteration: 31231/59290
Iteration: 31232/59290
Iteration: 31233/59290
Iteration: 31234/59290
Iteration: 31235/59290
Iteration: 31236/59290
Iteration: 31237/59290
Iteration: 31238/59290
Iteration: 31239/59290
Iteration: 31240/59290
Iteration: 31241/59290
Iteration: 31242/59290
Iteration: 31243/59290
Iteration: 31244/59290
Iteration: 31245/59290
Iteration: 31246/59290
Iteration: 31247/59290
Iteration: 31248/59290

 53%|█████▎    | 31238/59290 [22:30<18:26, 25.36it/s]

Iteration: 31249/59290
Iteration: 31250/59290
Iteration: 31251/59290
Iteration: 31252/59290
Iteration: 31253/59290
Iteration: 31254/59290
Iteration: 31255/59290
Iteration: 31256/59290
Iteration: 31257/59290
Iteration: 31258/59290
Iteration: 31259/59290
Iteration: 31260/59290
Iteration: 31261/59290
Iteration: 31262/59290
Iteration: 31263/59290
Iteration: 31264/59290
Iteration: 31265/59290
Iteration: 31266/59290
Iteration: 31267/59290
Iteration: 31268/59290
Iteration: 31269/59290
Iteration: 31270/59290
Iteration: 31271/59290
Iteration: 31272/59290

 53%|█████▎    | 31262/59290 [22:30<15:13, 30.69it/s]

Iteration: 31273/59290
Iteration: 31274/59290
Iteration: 31275/59290
Iteration: 31276/59290
Iteration: 31277/59290
Iteration: 31278/59290
Iteration: 31279/59290
Iteration: 31280/59290
Iteration: 31281/59290
Iteration: 31282/59290
Iteration: 31283/59290
Iteration: 31284/59290
Iteration: 31285/59290
Iteration: 31286/59290
Iteration: 31287/59290
Iteration: 31288/59290
Iteration: 31289/59290
Iteration: 31290/59290
Iteration: 31291/59290
Iteration: 31292/59290
Iteration: 31293/59290
Iteration: 31294/59290
Iteration: 31295/59290
Iteration: 31296/59290

 53%|█████▎    | 31286/59290 [22:31<18:30, 25.21it/s]

Iteration: 31297/59290
Iteration: 31298/59290
Iteration: 31299/59290
Iteration: 31300/59290
Iteration: 31301/59290
Iteration: 31302/59290
Iteration: 31303/59290
Iteration: 31304/59290
Iteration: 31305/59290
Iteration: 31306/59290
Iteration: 31307/59290
Iteration: 31308/59290
Iteration: 31309/59290
Iteration: 31310/59290
Iteration: 31311/59290
Iteration: 31312/59290
Iteration: 31313/59290
Iteration: 31314/59290
Iteration: 31315/59290
Iteration: 31316/59290
Iteration: 31317/59290
Iteration: 31318/59290
Iteration: 31319/59290
Iteration: 31320/59290

 53%|█████▎    | 31310/59290 [22:34<26:32, 17.57it/s]

Iteration: 31321/59290
Iteration: 31322/59290
Iteration: 31323/59290
Iteration: 31324/59290
Iteration: 31325/59290
Iteration: 31326/59290
Iteration: 31327/59290
Iteration: 31328/59290
Iteration: 31329/59290
Iteration: 31330/59290
Iteration: 31331/59290
Iteration: 31332/59290
Iteration: 31333/59290
Iteration: 31334/59290
Iteration: 31335/59290
Iteration: 31336/59290
Iteration: 31337/59290
Iteration: 31338/59290
Iteration: 31339/59290
Iteration: 31340/59290
Iteration: 31341/59290
Iteration: 31342/59290
Iteration: 31343/59290
Iteration: 31344/59290

 53%|█████▎    | 31334/59290 [22:34<20:49, 22.37it/s]

Iteration: 31345/59290
Iteration: 31346/59290
Iteration: 31347/59290
Iteration: 31348/59290
Iteration: 31349/59290
Iteration: 31350/59290
Iteration: 31351/59290
Iteration: 31352/59290
Iteration: 31353/59290
Iteration: 31354/59290
Iteration: 31355/59290
Iteration: 31356/59290
Iteration: 31357/59290
Iteration: 31358/59290
Iteration: 31359/59290
Iteration: 31360/59290
Iteration: 31361/59290
Iteration: 31362/59290
Iteration: 31363/59290
Iteration: 31364/59290
Iteration: 31365/59290
Iteration: 31366/59290
Iteration: 31367/59290
Iteration: 31368/59290

 53%|█████▎    | 31358/59290 [22:35<16:43, 27.84it/s]

Iteration: 31369/59290
Iteration: 31370/59290
Iteration: 31371/59290
Iteration: 31372/59290
Iteration: 31373/59290
Iteration: 31374/59290
Iteration: 31375/59290
Iteration: 31376/59290
Iteration: 31377/59290
Iteration: 31378/59290
Iteration: 31379/59290
Iteration: 31380/59290
Iteration: 31381/59290
Iteration: 31382/59290
Iteration: 31383/59290
Iteration: 31384/59290
Iteration: 31385/59290
Iteration: 31386/59290
Iteration: 31387/59290
Iteration: 31388/59290
Iteration: 31389/59290
Iteration: 31390/59290
Iteration: 31391/59290
Iteration: 31392/59290

 53%|█████▎    | 31382/59290 [22:35<13:56, 33.35it/s]

Iteration: 31393/59290
Iteration: 31394/59290
Iteration: 31395/59290
Iteration: 31396/59290
Iteration: 31397/59290
Iteration: 31398/59290
Iteration: 31399/59290
Iteration: 31400/59290
Iteration: 31401/59290
Iteration: 31402/59290
Iteration: 31403/59290
Iteration: 31404/59290
Iteration: 31405/59290
Iteration: 31406/59290
Iteration: 31407/59290
Iteration: 31408/59290
Iteration: 31409/59290
Iteration: 31410/59290
Iteration: 31411/59290
Iteration: 31412/59290
Iteration: 31413/59290
Iteration: 31414/59290
Iteration: 31415/59290
Iteration: 31416/59290

 53%|█████▎    | 31406/59290 [22:35<11:57, 38.85it/s]

Iteration: 31417/59290
Iteration: 31418/59290
Iteration: 31419/59290
Iteration: 31420/59290
Iteration: 31421/59290
Iteration: 31422/59290
Iteration: 31423/59290
Iteration: 31424/59290
Iteration: 31425/59290
Iteration: 31426/59290
Iteration: 31427/59290
Iteration: 31428/59290
Iteration: 31429/59290
Iteration: 31430/59290
Iteration: 31431/59290
Iteration: 31432/59290
Iteration: 31433/59290
Iteration: 31434/59290
Iteration: 31435/59290
Iteration: 31436/59290
Iteration: 31437/59290
Iteration: 31438/59290
Iteration: 31439/59290
Iteration: 31440/59290

 53%|█████▎    | 31430/59290 [22:37<18:10, 25.54it/s]

Iteration: 31441/59290
Iteration: 31442/59290
Iteration: 31443/59290
Iteration: 31444/59290
Iteration: 31445/59290
Iteration: 31446/59290
Iteration: 31447/59290
Iteration: 31448/59290
Iteration: 31449/59290
Iteration: 31450/59290
Iteration: 31451/59290
Iteration: 31452/59290
Iteration: 31453/59290
Iteration: 31454/59290
Iteration: 31455/59290
Iteration: 31456/59290
Iteration: 31457/59290
Iteration: 31458/59290
Iteration: 31459/59290
Iteration: 31460/59290
Iteration: 31461/59290
Iteration: 31462/59290
Iteration: 31463/59290
Iteration: 31464/59290

 53%|█████▎    | 31454/59290 [22:39<26:05, 17.78it/s]

Iteration: 31465/59290
Iteration: 31466/59290
Iteration: 31467/59290
Iteration: 31468/59290
Iteration: 31469/59290
Iteration: 31470/59290
Iteration: 31471/59290
Iteration: 31472/59290
Iteration: 31473/59290
Iteration: 31474/59290
Iteration: 31475/59290
Iteration: 31476/59290
Iteration: 31477/59290
Iteration: 31478/59290
Iteration: 31479/59290
Iteration: 31480/59290
Iteration: 31481/59290
Iteration: 31482/59290
Iteration: 31483/59290
Iteration: 31484/59290
Iteration: 31485/59290
Iteration: 31486/59290
Iteration: 31487/59290
Iteration: 31488/59290

 53%|█████▎    | 31478/59290 [22:40<20:24, 22.71it/s]

Iteration: 31489/59290
Iteration: 31490/59290
Iteration: 31491/59290
Iteration: 31492/59290
Iteration: 31493/59290
Iteration: 31494/59290
Iteration: 31495/59290
Iteration: 31496/59290
Iteration: 31497/59290
Iteration: 31498/59290
Iteration: 31499/59290
Iteration: 31500/59290
Iteration: 31501/59290
Iteration: 31502/59290
Iteration: 31503/59290
Iteration: 31504/59290
Iteration: 31505/59290
Iteration: 31506/59290
Iteration: 31507/59290
Iteration: 31508/59290
Iteration: 31509/59290
Iteration: 31510/59290
Iteration: 31511/59290
Iteration: 31512/59290

 53%|█████▎    | 31502/59290 [22:40<16:29, 28.09it/s]

Iteration: 31513/59290
Iteration: 31514/59290
Iteration: 31515/59290
Iteration: 31516/59290
Iteration: 31517/59290
Iteration: 31518/59290
Iteration: 31519/59290
Iteration: 31520/59290
Iteration: 31521/59290
Iteration: 31522/59290
Iteration: 31523/59290
Iteration: 31524/59290
Iteration: 31525/59290
Iteration: 31526/59290
Iteration: 31527/59290
Iteration: 31528/59290
Iteration: 31529/59290
Iteration: 31530/59290
Iteration: 31531/59290
Iteration: 31532/59290
Iteration: 31533/59290
Iteration: 31534/59290
Iteration: 31535/59290
Iteration: 31536/59290

 53%|█████▎    | 31526/59290 [22:40<13:40, 33.82it/s]

Iteration: 31537/59290
Iteration: 31538/59290
Iteration: 31539/59290
Iteration: 31540/59290
Iteration: 31541/59290
Iteration: 31542/59290
Iteration: 31543/59290
Iteration: 31544/59290
Iteration: 31545/59290
Iteration: 31546/59290
Iteration: 31547/59290
Iteration: 31548/59290
Iteration: 31549/59290
Iteration: 31550/59290
Iteration: 31551/59290
Iteration: 31552/59290
Iteration: 31553/59290
Iteration: 31554/59290
Iteration: 31555/59290
Iteration: 31556/59290
Iteration: 31557/59290
Iteration: 31558/59290
Iteration: 31559/59290
Iteration: 31560/59290

 53%|█████▎    | 31550/59290 [22:42<18:12, 25.38it/s]

Iteration: 31561/59290
Iteration: 31562/59290
Iteration: 31563/59290
Iteration: 31564/59290
Iteration: 31565/59290
Iteration: 31566/59290
Iteration: 31567/59290
Iteration: 31568/59290
Iteration: 31569/59290
Iteration: 31570/59290
Iteration: 31571/59290
Iteration: 31572/59290
Iteration: 31573/59290
Iteration: 31574/59290
Iteration: 31575/59290
Iteration: 31576/59290
Iteration: 31577/59290
Iteration: 31578/59290
Iteration: 31579/59290
Iteration: 31580/59290
Iteration: 31581/59290
Iteration: 31582/59290
Iteration: 31583/59290
Iteration: 31584/59290

 53%|█████▎    | 31574/59290 [22:44<24:08, 19.13it/s]

Iteration: 31585/59290
Iteration: 31586/59290
Iteration: 31587/59290
Iteration: 31588/59290
Iteration: 31589/59290
Iteration: 31590/59290
Iteration: 31591/59290
Iteration: 31592/59290
Iteration: 31593/59290
Iteration: 31594/59290
Iteration: 31595/59290
Iteration: 31596/59290
Iteration: 31597/59290
Iteration: 31598/59290
Iteration: 31599/59290
Iteration: 31600/59290
Iteration: 31601/59290
Iteration: 31602/59290
Iteration: 31603/59290
Iteration: 31604/59290
Iteration: 31605/59290
Iteration: 31606/59290
Iteration: 31607/59290
Iteration: 31608/59290

 53%|█████▎    | 31598/59290 [22:44<19:51, 23.24it/s]

Iteration: 31609/59290
Iteration: 31610/59290
Iteration: 31611/59290
Iteration: 31612/59290
Iteration: 31613/59290
Iteration: 31614/59290
Iteration: 31615/59290
Iteration: 31616/59290
Iteration: 31617/59290
Iteration: 31618/59290
Iteration: 31619/59290
Iteration: 31620/59290
Iteration: 31621/59290
Iteration: 31622/59290
Iteration: 31623/59290
Iteration: 31624/59290
Iteration: 31625/59290
Iteration: 31626/59290
Iteration: 31627/59290
Iteration: 31628/59290
Iteration: 31629/59290
Iteration: 31630/59290
Iteration: 31631/59290
Iteration: 31632/59290

 53%|█████▎    | 31622/59290 [22:45<16:05, 28.65it/s]

Iteration: 31633/59290
Iteration: 31634/59290
Iteration: 31635/59290
Iteration: 31636/59290
Iteration: 31637/59290
Iteration: 31638/59290
Iteration: 31639/59290
Iteration: 31640/59290
Iteration: 31641/59290
Iteration: 31642/59290
Iteration: 31643/59290
Iteration: 31644/59290
Iteration: 31645/59290
Iteration: 31646/59290
Iteration: 31647/59290
Iteration: 31648/59290
Iteration: 31649/59290
Iteration: 31650/59290
Iteration: 31651/59290
Iteration: 31652/59290
Iteration: 31653/59290
Iteration: 31654/59290
Iteration: 31655/59290
Iteration: 31656/59290

 53%|█████▎    | 31646/59290 [22:45<13:23, 34.40it/s]

Iteration: 31657/59290
Iteration: 31658/59290
Iteration: 31659/59290
Iteration: 31660/59290
Iteration: 31661/59290
Iteration: 31662/59290
Iteration: 31663/59290
Iteration: 31664/59290
Iteration: 31665/59290
Iteration: 31666/59290
Iteration: 31667/59290
Iteration: 31668/59290
Iteration: 31669/59290
Iteration: 31670/59290
Iteration: 31671/59290
Iteration: 31672/59290
Iteration: 31673/59290
Iteration: 31674/59290
Iteration: 31675/59290
Iteration: 31676/59290
Iteration: 31677/59290
Iteration: 31678/59290
Iteration: 31679/59290
Iteration: 31680/59290

 53%|█████▎    | 31670/59290 [22:46<11:35, 39.72it/s]

Iteration: 31681/59290
Iteration: 31682/59290
Iteration: 31683/59290
Iteration: 31684/59290
Iteration: 31685/59290
Iteration: 31686/59290
Iteration: 31687/59290
Iteration: 31688/59290
Iteration: 31689/59290
Iteration: 31690/59290
Iteration: 31691/59290
Iteration: 31692/59290
Iteration: 31693/59290
Iteration: 31694/59290
Iteration: 31695/59290
Iteration: 31696/59290
Iteration: 31697/59290
Iteration: 31698/59290
Iteration: 31699/59290
Iteration: 31700/59290
Iteration: 31701/59290
Iteration: 31702/59290
Iteration: 31703/59290
Iteration: 31704/59290

 53%|█████▎    | 31694/59290 [22:47<15:58, 28.78it/s]

Iteration: 31705/59290
Iteration: 31706/59290
Iteration: 31707/59290
Iteration: 31708/59290
Iteration: 31709/59290
Iteration: 31710/59290
Iteration: 31711/59290
Iteration: 31712/59290
Iteration: 31713/59290
Iteration: 31714/59290
Iteration: 31715/59290
Iteration: 31716/59290
Iteration: 31717/59290
Iteration: 31718/59290
Iteration: 31719/59290
Iteration: 31720/59290
Iteration: 31721/59290
Iteration: 31722/59290
Iteration: 31723/59290
Iteration: 31724/59290
Iteration: 31725/59290
Iteration: 31726/59290
Iteration: 31727/59290
Iteration: 31728/59290

 53%|█████▎    | 31718/59290 [22:49<24:15, 18.95it/s]

Iteration: 31729/59290
Iteration: 31730/59290
Iteration: 31731/59290
Iteration: 31732/59290
Iteration: 31733/59290
Iteration: 31734/59290
Iteration: 31735/59290
Iteration: 31736/59290
Iteration: 31737/59290
Iteration: 31738/59290
Iteration: 31739/59290
Iteration: 31740/59290
Iteration: 31741/59290
Iteration: 31742/59290
Iteration: 31743/59290
Iteration: 31744/59290
Iteration: 31745/59290
Iteration: 31746/59290
Iteration: 31747/59290
Iteration: 31748/59290
Iteration: 31749/59290
Iteration: 31750/59290
Iteration: 31751/59290
Iteration: 31752/59290

 54%|█████▎    | 31742/59290 [22:50<19:10, 23.94it/s]

Iteration: 31753/59290
Iteration: 31754/59290
Iteration: 31755/59290
Iteration: 31756/59290
Iteration: 31757/59290
Iteration: 31758/59290
Iteration: 31759/59290
Iteration: 31760/59290
Iteration: 31761/59290
Iteration: 31762/59290
Iteration: 31763/59290
Iteration: 31764/59290
Iteration: 31765/59290
Iteration: 31766/59290
Iteration: 31767/59290
Iteration: 31768/59290
Iteration: 31769/59290
Iteration: 31770/59290
Iteration: 31771/59290
Iteration: 31772/59290
Iteration: 31773/59290
Iteration: 31774/59290
Iteration: 31775/59290
Iteration: 31776/59290

 54%|█████▎    | 31766/59290 [22:50<15:36, 29.40it/s]

Iteration: 31777/59290
Iteration: 31778/59290
Iteration: 31779/59290
Iteration: 31780/59290
Iteration: 31781/59290
Iteration: 31782/59290
Iteration: 31783/59290
Iteration: 31784/59290
Iteration: 31785/59290
Iteration: 31786/59290
Iteration: 31787/59290
Iteration: 31788/59290
Iteration: 31789/59290
Iteration: 31790/59290
Iteration: 31791/59290
Iteration: 31792/59290
Iteration: 31793/59290
Iteration: 31794/59290
Iteration: 31795/59290
Iteration: 31796/59290
Iteration: 31797/59290
Iteration: 31798/59290
Iteration: 31799/59290
Iteration: 31800/59290

 54%|█████▎    | 31790/59290 [22:50<13:03, 35.11it/s]

Iteration: 31801/59290
Iteration: 31802/59290
Iteration: 31803/59290
Iteration: 31804/59290
Iteration: 31805/59290
Iteration: 31806/59290
Iteration: 31807/59290
Iteration: 31808/59290
Iteration: 31809/59290
Iteration: 31810/59290
Iteration: 31811/59290
Iteration: 31812/59290
Iteration: 31813/59290
Iteration: 31814/59290
Iteration: 31815/59290
Iteration: 31816/59290
Iteration: 31817/59290
Iteration: 31818/59290
Iteration: 31819/59290
Iteration: 31820/59290
Iteration: 31821/59290
Iteration: 31822/59290
Iteration: 31823/59290
Iteration: 31824/59290

 54%|█████▎    | 31814/59290 [22:51<11:26, 40.04it/s]

Iteration: 31825/59290
Iteration: 31826/59290
Iteration: 31827/59290
Iteration: 31828/59290
Iteration: 31829/59290
Iteration: 31830/59290
Iteration: 31831/59290
Iteration: 31832/59290
Iteration: 31833/59290
Iteration: 31834/59290
Iteration: 31835/59290
Iteration: 31836/59290
Iteration: 31837/59290
Iteration: 31838/59290
Iteration: 31839/59290
Iteration: 31840/59290
Iteration: 31841/59290
Iteration: 31842/59290
Iteration: 31843/59290
Iteration: 31844/59290
Iteration: 31845/59290
Iteration: 31846/59290
Iteration: 31847/59290
Iteration: 31848/59290

 54%|█████▎    | 31838/59290 [22:51<10:09, 45.07it/s]

Iteration: 31849/59290
Iteration: 31850/59290
Iteration: 31851/59290
Iteration: 31852/59290
Iteration: 31853/59290
Iteration: 31854/59290
Iteration: 31855/59290
Iteration: 31856/59290
Iteration: 31857/59290
Iteration: 31858/59290
Iteration: 31859/59290
Iteration: 31860/59290
Iteration: 31861/59290
Iteration: 31862/59290
Iteration: 31863/59290
Iteration: 31864/59290
Iteration: 31865/59290
Iteration: 31866/59290
Iteration: 31867/59290
Iteration: 31868/59290
Iteration: 31869/59290
Iteration: 31870/59290
Iteration: 31871/59290
Iteration: 31872/59290

 54%|█████▎    | 31862/59290 [22:51<09:15, 49.36it/s]

Iteration: 31873/59290
Iteration: 31874/59290
Iteration: 31875/59290
Iteration: 31876/59290
Iteration: 31877/59290
Iteration: 31878/59290
Iteration: 31879/59290
Iteration: 31880/59290
Iteration: 31881/59290
Iteration: 31882/59290
Iteration: 31883/59290
Iteration: 31884/59290
Iteration: 31885/59290
Iteration: 31886/59290
Iteration: 31887/59290
Iteration: 31888/59290
Iteration: 31889/59290
Iteration: 31890/59290
Iteration: 31891/59290
Iteration: 31892/59290
Iteration: 31893/59290
Iteration: 31894/59290
Iteration: 31895/59290
Iteration: 31896/59290

 54%|█████▍    | 31886/59290 [22:52<08:38, 52.81it/s]

Iteration: 31897/59290
Iteration: 31898/59290
Iteration: 31899/59290
Iteration: 31900/59290
Iteration: 31901/59290
Iteration: 31902/59290
Iteration: 31903/59290
Iteration: 31904/59290
Iteration: 31905/59290
Iteration: 31906/59290
Iteration: 31907/59290
Iteration: 31908/59290
Iteration: 31909/59290
Iteration: 31910/59290
Iteration: 31911/59290
Iteration: 31912/59290
Iteration: 31913/59290
Iteration: 31914/59290
Iteration: 31915/59290
Iteration: 31916/59290
Iteration: 31917/59290
Iteration: 31918/59290
Iteration: 31919/59290
Iteration: 31920/59290

 54%|█████▍    | 31910/59290 [22:53<14:41, 31.06it/s]

Iteration: 31921/59290
Iteration: 31922/59290
Iteration: 31923/59290
Iteration: 31924/59290
Iteration: 31925/59290
Iteration: 31926/59290
Iteration: 31927/59290
Iteration: 31928/59290
Iteration: 31929/59290
Iteration: 31930/59290
Iteration: 31931/59290
Iteration: 31932/59290
Iteration: 31933/59290
Iteration: 31934/59290
Iteration: 31935/59290
Iteration: 31936/59290
Iteration: 31937/59290
Iteration: 31938/59290
Iteration: 31939/59290
Iteration: 31940/59290
Iteration: 31941/59290
Iteration: 31942/59290
Iteration: 31943/59290
Iteration: 31944/59290

 54%|█████▍    | 31934/59290 [22:55<21:49, 20.89it/s]

Iteration: 31945/59290
Iteration: 31946/59290
Iteration: 31947/59290
Iteration: 31948/59290
Iteration: 31949/59290
Iteration: 31950/59290
Iteration: 31951/59290
Iteration: 31952/59290
Iteration: 31953/59290
Iteration: 31954/59290
Iteration: 31955/59290
Iteration: 31956/59290
Iteration: 31957/59290
Iteration: 31958/59290
Iteration: 31959/59290
Iteration: 31960/59290
Iteration: 31961/59290
Iteration: 31962/59290
Iteration: 31963/59290
Iteration: 31964/59290
Iteration: 31965/59290
Iteration: 31966/59290
Iteration: 31967/59290
Iteration: 31968/59290

 54%|█████▍    | 31958/59290 [22:56<18:28, 24.65it/s]

Iteration: 31969/59290
Iteration: 31970/59290
Iteration: 31971/59290
Iteration: 31972/59290
Iteration: 31973/59290
Iteration: 31974/59290
Iteration: 31975/59290
Iteration: 31976/59290
Iteration: 31977/59290
Iteration: 31978/59290
Iteration: 31979/59290
Iteration: 31980/59290
Iteration: 31981/59290
Iteration: 31982/59290
Iteration: 31983/59290
Iteration: 31984/59290
Iteration: 31985/59290
Iteration: 31986/59290
Iteration: 31987/59290
Iteration: 31988/59290
Iteration: 31989/59290
Iteration: 31990/59290
Iteration: 31991/59290
Iteration: 31992/59290

 54%|█████▍    | 31982/59290 [22:56<15:05, 30.15it/s]

Iteration: 31993/59290
Iteration: 31994/59290
Iteration: 31995/59290
Iteration: 31996/59290
Iteration: 31997/59290
Iteration: 31998/59290
Iteration: 31999/59290
Iteration: 32000/59290
Iteration: 32001/59290
Iteration: 32002/59290
Iteration: 32003/59290
Iteration: 32004/59290
Iteration: 32005/59290
Iteration: 32006/59290
Iteration: 32007/59290
Iteration: 32008/59290
Iteration: 32009/59290
Iteration: 32010/59290
Iteration: 32011/59290
Iteration: 32012/59290
Iteration: 32013/59290
Iteration: 32014/59290
Iteration: 32015/59290
Iteration: 32016/59290

 54%|█████▍    | 32006/59290 [22:57<12:40, 35.86it/s]

Iteration: 32017/59290
Iteration: 32018/59290
Iteration: 32019/59290
Iteration: 32020/59290
Iteration: 32021/59290
Iteration: 32022/59290
Iteration: 32023/59290
Iteration: 32024/59290
Iteration: 32025/59290
Iteration: 32026/59290
Iteration: 32027/59290
Iteration: 32028/59290
Iteration: 32029/59290
Iteration: 32030/59290
Iteration: 32031/59290
Iteration: 32032/59290
Iteration: 32033/59290
Iteration: 32034/59290
Iteration: 32035/59290
Iteration: 32036/59290
Iteration: 32037/59290
Iteration: 32038/59290
Iteration: 32039/59290
Iteration: 32040/59290

 54%|█████▍    | 32030/59290 [22:57<11:01, 41.21it/s]

Iteration: 32041/59290
Iteration: 32042/59290
Iteration: 32043/59290
Iteration: 32044/59290
Iteration: 32045/59290
Iteration: 32046/59290
Iteration: 32047/59290
Iteration: 32048/59290
Iteration: 32049/59290
Iteration: 32050/59290
Iteration: 32051/59290
Iteration: 32052/59290
Iteration: 32053/59290
Iteration: 32054/59290
Iteration: 32055/59290
Iteration: 32056/59290
Iteration: 32057/59290
Iteration: 32058/59290
Iteration: 32059/59290
Iteration: 32060/59290
Iteration: 32061/59290
Iteration: 32062/59290
Iteration: 32063/59290
Iteration: 32064/59290

 54%|█████▍    | 32054/59290 [22:57<09:54, 45.81it/s]

Iteration: 32065/59290
Iteration: 32066/59290
Iteration: 32067/59290
Iteration: 32068/59290
Iteration: 32069/59290
Iteration: 32070/59290
Iteration: 32071/59290
Iteration: 32072/59290
Iteration: 32073/59290
Iteration: 32074/59290
Iteration: 32075/59290
Iteration: 32076/59290
Iteration: 32077/59290
Iteration: 32078/59290
Iteration: 32079/59290
Iteration: 32080/59290
Iteration: 32081/59290
Iteration: 32082/59290
Iteration: 32083/59290
Iteration: 32084/59290
Iteration: 32085/59290
Iteration: 32086/59290
Iteration: 32087/59290
Iteration: 32088/59290

 54%|█████▍    | 32078/59290 [22:58<09:02, 50.19it/s]

Iteration: 32089/59290
Iteration: 32090/59290
Iteration: 32091/59290
Iteration: 32092/59290
Iteration: 32093/59290
Iteration: 32094/59290
Iteration: 32095/59290
Iteration: 32096/59290
Iteration: 32097/59290
Iteration: 32098/59290
Iteration: 32099/59290
Iteration: 32100/59290
Iteration: 32101/59290
Iteration: 32102/59290
Iteration: 32103/59290
Iteration: 32104/59290
Iteration: 32105/59290
Iteration: 32106/59290
Iteration: 32107/59290
Iteration: 32108/59290
Iteration: 32109/59290
Iteration: 32110/59290
Iteration: 32111/59290
Iteration: 32112/59290

 54%|█████▍    | 32102/59290 [22:58<08:28, 53.52it/s]

Iteration: 32113/59290
Iteration: 32114/59290
Iteration: 32115/59290
Iteration: 32116/59290
Iteration: 32117/59290
Iteration: 32118/59290
Iteration: 32119/59290
Iteration: 32120/59290
Iteration: 32121/59290
Iteration: 32122/59290
Iteration: 32123/59290
Iteration: 32124/59290
Iteration: 32125/59290
Iteration: 32126/59290
Iteration: 32127/59290
Iteration: 32128/59290
Iteration: 32129/59290
Iteration: 32130/59290
Iteration: 32131/59290
Iteration: 32132/59290
Iteration: 32133/59290
Iteration: 32134/59290
Iteration: 32135/59290
Iteration: 32136/59290

 54%|█████▍    | 32126/59290 [22:59<08:03, 56.21it/s]

Iteration: 32137/59290
Iteration: 32138/59290
Iteration: 32139/59290
Iteration: 32140/59290
Iteration: 32141/59290
Iteration: 32142/59290
Iteration: 32143/59290
Iteration: 32144/59290
Iteration: 32145/59290
Iteration: 32146/59290
Iteration: 32147/59290
Iteration: 32148/59290
Iteration: 32149/59290
Iteration: 32150/59290
Iteration: 32151/59290
Iteration: 32152/59290
Iteration: 32153/59290
Iteration: 32154/59290
Iteration: 32155/59290
Iteration: 32156/59290
Iteration: 32157/59290
Iteration: 32158/59290
Iteration: 32159/59290
Iteration: 32160/59290

 54%|█████▍    | 32150/59290 [23:33<3:20:21,  2.26it/s]

Iteration: 32161/59290
Iteration: 32162/59290
Iteration: 32163/59290
Iteration: 32164/59290
Iteration: 32165/59290
Iteration: 32166/59290
Iteration: 32167/59290
Iteration: 32168/59290
Iteration: 32169/59290
Iteration: 32170/59290
Iteration: 32171/59290
Iteration: 32172/59290
Iteration: 32173/59290
Iteration: 32174/59290
Iteration: 32175/59290
Iteration: 32176/59290
Iteration: 32177/59290
Iteration: 32178/59290
Iteration: 32179/59290
Iteration: 32180/59290
Iteration: 32181/59290
Iteration: 32182/59290
Iteration: 32183/59290
Iteration: 32184/59290

 54%|█████▍    | 32174/59290 [23:33<2:22:17,  3.18it/s]

Iteration: 32185/59290
Iteration: 32186/59290
Iteration: 32187/59290
Iteration: 32188/59290
Iteration: 32189/59290
Iteration: 32190/59290
Iteration: 32191/59290
Iteration: 32192/59290
Iteration: 32193/59290
Iteration: 32194/59290
Iteration: 32195/59290
Iteration: 32196/59290
Iteration: 32197/59290
Iteration: 32198/59290
Iteration: 32199/59290
Iteration: 32200/59290
Iteration: 32201/59290
Iteration: 32202/59290
Iteration: 32203/59290
Iteration: 32204/59290
Iteration: 32205/59290
Iteration: 32206/59290
Iteration: 32207/59290
Iteration: 32208/59290

 54%|█████▍    | 32198/59290 [23:34<1:41:38,  4.44it/s]

Iteration: 32209/59290
Iteration: 32210/59290
Iteration: 32211/59290
Iteration: 32212/59290
Iteration: 32213/59290
Iteration: 32214/59290
Iteration: 32215/59290
Iteration: 32216/59290
Iteration: 32217/59290
Iteration: 32218/59290
Iteration: 32219/59290
Iteration: 32220/59290
Iteration: 32221/59290
Iteration: 32222/59290
Iteration: 32223/59290
Iteration: 32224/59290
Iteration: 32225/59290
Iteration: 32226/59290
Iteration: 32227/59290
Iteration: 32228/59290
Iteration: 32229/59290
Iteration: 32230/59290
Iteration: 32231/59290
Iteration: 32232/59290

 54%|█████▍    | 32222/59290 [23:34<1:13:18,  6.15it/s]

Iteration: 32233/59290
Iteration: 32234/59290
Iteration: 32235/59290
Iteration: 32236/59290
Iteration: 32237/59290
Iteration: 32238/59290
Iteration: 32239/59290
Iteration: 32240/59290
Iteration: 32241/59290
Iteration: 32242/59290
Iteration: 32243/59290
Iteration: 32244/59290
Iteration: 32245/59290
Iteration: 32246/59290
Iteration: 32247/59290
Iteration: 32248/59290
Iteration: 32249/59290
Iteration: 32250/59290
Iteration: 32251/59290
Iteration: 32252/59290
Iteration: 32253/59290
Iteration: 32254/59290
Iteration: 32255/59290
Iteration: 32256/59290

 54%|█████▍    | 32246/59290 [23:35<53:24,  8.44it/s]

Iteration: 32257/59290
Iteration: 32258/59290
Iteration: 32259/59290
Iteration: 32260/59290
Iteration: 32261/59290
Iteration: 32262/59290
Iteration: 32263/59290
Iteration: 32264/59290
Iteration: 32265/59290
Iteration: 32266/59290
Iteration: 32267/59290
Iteration: 32268/59290
Iteration: 32269/59290
Iteration: 32270/59290
Iteration: 32271/59290
Iteration: 32272/59290
Iteration: 32273/59290
Iteration: 32274/59290
Iteration: 32275/59290
Iteration: 32276/59290
Iteration: 32277/59290
Iteration: 32278/59290
Iteration: 32279/59290
Iteration: 32280/59290

 54%|█████▍    | 32270/59290 [23:36<45:09,  9.97it/s]

Iteration: 32281/59290
Iteration: 32282/59290
Iteration: 32283/59290
Iteration: 32284/59290
Iteration: 32285/59290
Iteration: 32286/59290
Iteration: 32287/59290
Iteration: 32288/59290
Iteration: 32289/59290
Iteration: 32290/59290
Iteration: 32291/59290
Iteration: 32292/59290
Iteration: 32293/59290
Iteration: 32294/59290
Iteration: 32295/59290
Iteration: 32296/59290
Iteration: 32297/59290
Iteration: 32298/59290
Iteration: 32299/59290
Iteration: 32300/59290
Iteration: 32301/59290
Iteration: 32302/59290
Iteration: 32303/59290
Iteration: 32304/59290

 54%|█████▍    | 32294/59290 [23:38<42:25, 10.60it/s]

Iteration: 32305/59290
Iteration: 32306/59290
Iteration: 32307/59290
Iteration: 32308/59290
Iteration: 32309/59290
Iteration: 32310/59290
Iteration: 32311/59290
Iteration: 32312/59290
Iteration: 32313/59290
Iteration: 32314/59290
Iteration: 32315/59290
Iteration: 32316/59290
Iteration: 32317/59290
Iteration: 32318/59290
Iteration: 32319/59290
Iteration: 32320/59290
Iteration: 32321/59290
Iteration: 32322/59290
Iteration: 32323/59290
Iteration: 32324/59290
Iteration: 32325/59290
Iteration: 32326/59290
Iteration: 32327/59290
Iteration: 32328/59290

 55%|█████▍    | 32318/59290 [23:38<32:02, 14.03it/s]

Iteration: 32329/59290
Iteration: 32330/59290
Iteration: 32331/59290
Iteration: 32332/59290
Iteration: 32333/59290
Iteration: 32334/59290
Iteration: 32335/59290
Iteration: 32336/59290
Iteration: 32337/59290
Iteration: 32338/59290
Iteration: 32339/59290
Iteration: 32340/59290
Iteration: 32341/59290
Iteration: 32342/59290
Iteration: 32343/59290
Iteration: 32344/59290
Iteration: 32345/59290
Iteration: 32346/59290
Iteration: 32347/59290
Iteration: 32348/59290
Iteration: 32349/59290
Iteration: 32350/59290
Iteration: 32352/59290

 55%|█████▍    | 32341/59290 [23:39<25:09, 17.85it/s]

Iteration: 32353/59290
Iteration: 32354/59290
Iteration: 32355/59290
Iteration: 32356/59290
Iteration: 32357/59290
Iteration: 32358/59290
Iteration: 32359/59290
Iteration: 32360/59290

 55%|█████▍    | 32349/59290 [23:39<24:45, 18.14it/s]

Iteration: 32361/59290
Iteration: 32362/59290
Iteration: 32363/59290
Iteration: 32364/59290
Iteration: 32365/59290
Iteration: 32366/59290
Iteration: 32367/59290
Iteration: 32368/59290
Iteration: 32369/59290
Iteration: 32370/59290
Iteration: 32371/59290
Iteration: 32372/59290
Iteration: 32373/59290
Iteration: 32374/59290
Iteration: 32375/59290
Iteration: 32376/59290
Iteration: 32377/59290
Iteration: 32378/59290
Iteration: 32379/59290
Iteration: 32380/59290
Iteration: 32381/59290
Iteration: 32382/59290
Iteration: 32383/59290
Iteration: 32384/59290

 55%|█████▍    | 32373/59290 [23:41<26:45, 16.76it/s]

Iteration: 32385/59290
Iteration: 32386/59290
Iteration: 32387/59290
Iteration: 32388/59290
Iteration: 32389/59290
Iteration: 32390/59290
Iteration: 32391/59290
Iteration: 32392/59290
Iteration: 32393/59290
Iteration: 32394/59290
Iteration: 32395/59290
Iteration: 32396/59290
Iteration: 32397/59290
Iteration: 32398/59290
Iteration: 32399/59290
Iteration: 32400/59290
Iteration: 32401/59290
Iteration: 32402/59290
Iteration: 32403/59290
Iteration: 32404/59290
Iteration: 32405/59290
Iteration: 32406/59290
Iteration: 32407/59290
Iteration: 32408/59290

 55%|█████▍    | 32397/59290 [23:43<30:15, 14.81it/s]

Iteration: 32409/59290
Iteration: 32410/59290
Iteration: 32411/59290
Iteration: 32412/59290
Iteration: 32413/59290
Iteration: 32414/59290
Iteration: 32415/59290
Iteration: 32416/59290
Iteration: 32417/59290
Iteration: 32418/59290
Iteration: 32419/59290
Iteration: 32420/59290
Iteration: 32421/59290
Iteration: 32422/59290
Iteration: 32423/59290
Iteration: 32424/59290
Iteration: 32425/59290
Iteration: 32426/59290
Iteration: 32427/59290
Iteration: 32428/59290
Iteration: 32429/59290
Iteration: 32430/59290
Iteration: 32431/59290
Iteration: 32432/59290

 55%|█████▍    | 32421/59290 [23:43<23:14, 19.26it/s]

Iteration: 32433/59290
Iteration: 32434/59290
Iteration: 32435/59290
Iteration: 32436/59290
Iteration: 32437/59290
Iteration: 32438/59290
Iteration: 32439/59290
Iteration: 32440/59290
Iteration: 32441/59290
Iteration: 32442/59290
Iteration: 32443/59290
Iteration: 32444/59290
Iteration: 32445/59290
Iteration: 32446/59290
Iteration: 32447/59290
Iteration: 32448/59290
Iteration: 32449/59290
Iteration: 32450/59290
Iteration: 32451/59290
Iteration: 32452/59290
Iteration: 32453/59290
Iteration: 32454/59290
Iteration: 32455/59290
Iteration: 32456/59290

 55%|█████▍    | 32445/59290 [23:44<18:07, 24.69it/s]

Iteration: 32457/59290
Iteration: 32458/59290
Iteration: 32459/59290
Iteration: 32460/59290
Iteration: 32461/59290
Iteration: 32462/59290
Iteration: 32463/59290
Iteration: 32464/59290
Iteration: 32465/59290
Iteration: 32466/59290
Iteration: 32467/59290
Iteration: 32468/59290
Iteration: 32469/59290
Iteration: 32470/59290
Iteration: 32471/59290
Iteration: 32472/59290
Iteration: 32473/59290
Iteration: 32474/59290
Iteration: 32475/59290
Iteration: 32476/59290
Iteration: 32477/59290
Iteration: 32478/59290
Iteration: 32479/59290
Iteration: 32480/59290

 55%|█████▍    | 32469/59290 [23:44<14:40, 30.48it/s]

Iteration: 32481/59290
Iteration: 32482/59290
Iteration: 32483/59290
Iteration: 32484/59290
Iteration: 32485/59290
Iteration: 32486/59290
Iteration: 32487/59290
Iteration: 32488/59290
Iteration: 32489/59290
Iteration: 32490/59290
Iteration: 32491/59290
Iteration: 32492/59290
Iteration: 32493/59290
Iteration: 32494/59290
Iteration: 32495/59290
Iteration: 32496/59290
Iteration: 32497/59290
Iteration: 32498/59290
Iteration: 32499/59290
Iteration: 32500/59290
Iteration: 32501/59290
Iteration: 32502/59290
Iteration: 32503/59290
Iteration: 32504/59290

 55%|█████▍    | 32493/59290 [23:44<12:19, 36.23it/s]

Iteration: 32505/59290
Iteration: 32506/59290
Iteration: 32507/59290
Iteration: 32508/59290
Iteration: 32509/59290
Iteration: 32510/59290
Iteration: 32511/59290
Iteration: 32512/59290
Iteration: 32513/59290
Iteration: 32514/59290
Iteration: 32515/59290
Iteration: 32516/59290
Iteration: 32517/59290
Iteration: 32518/59290
Iteration: 32519/59290
Iteration: 32520/59290
Iteration: 32521/59290
Iteration: 32522/59290
Iteration: 32523/59290
Iteration: 32524/59290
Iteration: 32525/59290
Iteration: 32526/59290
Iteration: 32527/59290
Iteration: 32528/59290

 55%|█████▍    | 32517/59290 [23:46<16:44, 26.65it/s]

Iteration: 32529/59290
Iteration: 32530/59290
Iteration: 32531/59290
Iteration: 32532/59290
Iteration: 32533/59290
Iteration: 32534/59290
Iteration: 32535/59290
Iteration: 32536/59290
Iteration: 32537/59290
Iteration: 32538/59290
Iteration: 32539/59290
Iteration: 32540/59290
Iteration: 32541/59290
Iteration: 32542/59290
Iteration: 32543/59290
Iteration: 32544/59290
Iteration: 32545/59290
Iteration: 32546/59290
Iteration: 32547/59290
Iteration: 32548/59290
Iteration: 32549/59290
Iteration: 32550/59290
Iteration: 32551/59290
Iteration: 32552/59290

 55%|█████▍    | 32541/59290 [23:48<24:16, 18.37it/s]

Iteration: 32553/59290
Iteration: 32554/59290
Iteration: 32555/59290
Iteration: 32556/59290
Iteration: 32557/59290
Iteration: 32558/59290
Iteration: 32559/59290
Iteration: 32560/59290
Iteration: 32561/59290
Iteration: 32562/59290
Iteration: 32563/59290
Iteration: 32564/59290
Iteration: 32565/59290
Iteration: 32566/59290
Iteration: 32567/59290
Iteration: 32568/59290
Iteration: 32569/59290
Iteration: 32570/59290
Iteration: 32571/59290
Iteration: 32572/59290
Iteration: 32573/59290
Iteration: 32574/59290
Iteration: 32575/59290
Iteration: 32576/59290

 55%|█████▍    | 32565/59290 [23:48<19:03, 23.38it/s]

Iteration: 32577/59290
Iteration: 32578/59290
Iteration: 32579/59290
Iteration: 32580/59290
Iteration: 32581/59290
Iteration: 32582/59290
Iteration: 32583/59290
Iteration: 32584/59290
Iteration: 32585/59290
Iteration: 32586/59290
Iteration: 32587/59290
Iteration: 32588/59290
Iteration: 32589/59290
Iteration: 32590/59290
Iteration: 32591/59290
Iteration: 32592/59290
Iteration: 32593/59290
Iteration: 32594/59290
Iteration: 32595/59290
Iteration: 32596/59290
Iteration: 32597/59290
Iteration: 32598/59290
Iteration: 32599/59290
Iteration: 32600/59290

 55%|█████▍    | 32589/59290 [23:49<15:29, 28.72it/s]

Iteration: 32601/59290
Iteration: 32602/59290
Iteration: 32603/59290
Iteration: 32604/59290
Iteration: 32605/59290
Iteration: 32606/59290
Iteration: 32607/59290
Iteration: 32608/59290
Iteration: 32609/59290
Iteration: 32610/59290
Iteration: 32611/59290
Iteration: 32612/59290
Iteration: 32613/59290
Iteration: 32614/59290
Iteration: 32615/59290
Iteration: 32616/59290
Iteration: 32617/59290
Iteration: 32618/59290
Iteration: 32619/59290
Iteration: 32620/59290
Iteration: 32621/59290
Iteration: 32622/59290
Iteration: 32623/59290
Iteration: 32624/59290

 55%|█████▌    | 32613/59290 [23:49<12:55, 34.42it/s]

Iteration: 32625/59290
Iteration: 32626/59290
Iteration: 32627/59290
Iteration: 32628/59290
Iteration: 32629/59290
Iteration: 32630/59290
Iteration: 32631/59290
Iteration: 32632/59290
Iteration: 32633/59290
Iteration: 32634/59290
Iteration: 32635/59290
Iteration: 32636/59290
Iteration: 32637/59290
Iteration: 32638/59290
Iteration: 32639/59290
Iteration: 32640/59290
Iteration: 32641/59290
Iteration: 32642/59290
Iteration: 32643/59290
Iteration: 32644/59290
Iteration: 32645/59290
Iteration: 32646/59290
Iteration: 32647/59290
Iteration: 32648/59290

 55%|█████▌    | 32637/59290 [23:50<11:08, 39.84it/s]

Iteration: 32649/59290
Iteration: 32650/59290
Iteration: 32651/59290
Iteration: 32652/59290
Iteration: 32653/59290
Iteration: 32654/59290
Iteration: 32655/59290
Iteration: 32656/59290
Iteration: 32657/59290
Iteration: 32658/59290
Iteration: 32659/59290
Iteration: 32660/59290
Iteration: 32661/59290
Iteration: 32662/59290
Iteration: 32663/59290
Iteration: 32664/59290
Iteration: 32665/59290
Iteration: 32666/59290
Iteration: 32667/59290
Iteration: 32668/59290
Iteration: 32669/59290
Iteration: 32670/59290
Iteration: 32671/59290
Iteration: 32672/59290

 55%|█████▌    | 32661/59290 [23:50<09:53, 44.90it/s]

Iteration: 32673/59290
Iteration: 32674/59290
Iteration: 32675/59290
Iteration: 32676/59290
Iteration: 32677/59290
Iteration: 32678/59290
Iteration: 32679/59290
Iteration: 32680/59290
Iteration: 32681/59290
Iteration: 32682/59290
Iteration: 32683/59290
Iteration: 32684/59290
Iteration: 32685/59290
Iteration: 32686/59290
Iteration: 32687/59290
Iteration: 32688/59290
Iteration: 32689/59290
Iteration: 32690/59290
Iteration: 32691/59290
Iteration: 32692/59290
Iteration: 32693/59290
Iteration: 32694/59290
Iteration: 32695/59290
Iteration: 32696/59290

 55%|█████▌    | 32685/59290 [23:50<09:00, 49.25it/s]

Iteration: 32697/59290
Iteration: 32698/59290
Iteration: 32699/59290
Iteration: 32700/59290
Iteration: 32701/59290
Iteration: 32702/59290
Iteration: 32703/59290
Iteration: 32704/59290
Iteration: 32705/59290
Iteration: 32706/59290
Iteration: 32707/59290
Iteration: 32708/59290
Iteration: 32709/59290
Iteration: 32710/59290
Iteration: 32711/59290
Iteration: 32712/59290
Iteration: 32713/59290
Iteration: 32714/59290
Iteration: 32715/59290
Iteration: 32716/59290
Iteration: 32717/59290
Iteration: 32718/59290
Iteration: 32719/59290
Iteration: 32720/59290

 55%|█████▌    | 32709/59290 [23:51<08:35, 51.54it/s]

Iteration: 32721/59290
Iteration: 32722/59290
Iteration: 32723/59290
Iteration: 32724/59290
Iteration: 32725/59290
Iteration: 32726/59290
Iteration: 32727/59290
Iteration: 32728/59290
Iteration: 32729/59290
Iteration: 32730/59290
Iteration: 32731/59290
Iteration: 32732/59290
Iteration: 32733/59290
Iteration: 32734/59290
Iteration: 32735/59290
Iteration: 32736/59290
Iteration: 32737/59290
Iteration: 32738/59290
Iteration: 32739/59290
Iteration: 32740/59290
Iteration: 32741/59290
Iteration: 32742/59290
Iteration: 32743/59290
Iteration: 32744/59290

 55%|█████▌    | 32733/59290 [23:52<15:10, 29.16it/s]

Iteration: 32745/59290
Iteration: 32746/59290
Iteration: 32747/59290
Iteration: 32748/59290
Iteration: 32749/59290
Iteration: 32750/59290
Iteration: 32751/59290
Iteration: 32752/59290
Iteration: 32753/59290
Iteration: 32754/59290
Iteration: 32755/59290
Iteration: 32756/59290
Iteration: 32757/59290
Iteration: 32758/59290
Iteration: 32759/59290
Iteration: 32760/59290
Iteration: 32761/59290
Iteration: 32762/59290
Iteration: 32763/59290
Iteration: 32764/59290
Iteration: 32765/59290
Iteration: 32766/59290
Iteration: 32767/59290
Iteration: 32768/59290

 55%|█████▌    | 32757/59290 [23:54<21:44, 20.33it/s]

Iteration: 32769/59290
Iteration: 32770/59290
Iteration: 32771/59290
Iteration: 32772/59290
Iteration: 32773/59290
Iteration: 32774/59290
Iteration: 32775/59290
Iteration: 32776/59290
Iteration: 32777/59290
Iteration: 32778/59290
Iteration: 32779/59290
Iteration: 32780/59290
Iteration: 32781/59290
Iteration: 32782/59290
Iteration: 32783/59290
Iteration: 32784/59290
Iteration: 32785/59290
Iteration: 32786/59290
Iteration: 32787/59290
Iteration: 32788/59290
Iteration: 32789/59290
Iteration: 32790/59290
Iteration: 32791/59290
Iteration: 32792/59290

 55%|█████▌    | 32781/59290 [23:55<18:08, 24.36it/s]

Iteration: 32793/59290
Iteration: 32794/59290
Iteration: 32795/59290
Iteration: 32796/59290
Iteration: 32797/59290
Iteration: 32798/59290
Iteration: 32799/59290
Iteration: 32800/59290
Iteration: 32801/59290
Iteration: 32802/59290
Iteration: 32803/59290
Iteration: 32804/59290
Iteration: 32805/59290
Iteration: 32806/59290
Iteration: 32807/59290
Iteration: 32808/59290
Iteration: 32809/59290
Iteration: 32810/59290
Iteration: 32811/59290
Iteration: 32812/59290
Iteration: 32813/59290
Iteration: 32814/59290
Iteration: 32815/59290
Iteration: 32816/59290

 55%|█████▌    | 32805/59290 [23:55<14:45, 29.92it/s]

Iteration: 32817/59290
Iteration: 32818/59290
Iteration: 32819/59290
Iteration: 32820/59290
Iteration: 32821/59290
Iteration: 32822/59290
Iteration: 32823/59290
Iteration: 32824/59290
Iteration: 32825/59290
Iteration: 32826/59290
Iteration: 32827/59290
Iteration: 32828/59290
Iteration: 32829/59290
Iteration: 32830/59290
Iteration: 32831/59290
Iteration: 32832/59290
Iteration: 32833/59290
Iteration: 32834/59290
Iteration: 32835/59290
Iteration: 32836/59290
Iteration: 32837/59290
Iteration: 32838/59290
Iteration: 32839/59290
Iteration: 32840/59290

 55%|█████▌    | 32829/59290 [23:56<12:26, 35.45it/s]

Iteration: 32841/59290
Iteration: 32842/59290
Iteration: 32843/59290
Iteration: 32844/59290
Iteration: 32845/59290
Iteration: 32846/59290
Iteration: 32847/59290
Iteration: 32848/59290
Iteration: 32849/59290
Iteration: 32850/59290
Iteration: 32851/59290
Iteration: 32852/59290
Iteration: 32853/59290
Iteration: 32854/59290
Iteration: 32855/59290
Iteration: 32856/59290
Iteration: 32857/59290
Iteration: 32858/59290
Iteration: 32859/59290
Iteration: 32860/59290
Iteration: 32861/59290
Iteration: 32862/59290
Iteration: 32863/59290
Iteration: 32864/59290

 55%|█████▌    | 32853/59290 [23:56<10:47, 40.85it/s]

Iteration: 32865/59290
Iteration: 32866/59290
Iteration: 32867/59290
Iteration: 32868/59290
Iteration: 32869/59290
Iteration: 32870/59290
Iteration: 32871/59290
Iteration: 32872/59290
Iteration: 32873/59290
Iteration: 32874/59290
Iteration: 32875/59290
Iteration: 32876/59290
Iteration: 32877/59290
Iteration: 32878/59290
Iteration: 32879/59290
Iteration: 32880/59290
Iteration: 32881/59290
Iteration: 32882/59290
Iteration: 32883/59290
Iteration: 32884/59290
Iteration: 32885/59290
Iteration: 32886/59290
Iteration: 32887/59290
Iteration: 32888/59290

 55%|█████▌    | 32877/59290 [23:56<09:39, 45.62it/s]

Iteration: 32889/59290
Iteration: 32890/59290
Iteration: 32891/59290
Iteration: 32892/59290
Iteration: 32893/59290
Iteration: 32894/59290
Iteration: 32895/59290
Iteration: 32896/59290
Iteration: 32897/59290
Iteration: 32898/59290
Iteration: 32899/59290
Iteration: 32900/59290
Iteration: 32901/59290
Iteration: 32902/59290
Iteration: 32903/59290
Iteration: 32904/59290
Iteration: 32905/59290
Iteration: 32906/59290
Iteration: 32907/59290
Iteration: 32908/59290
Iteration: 32909/59290
Iteration: 32910/59290
Iteration: 32911/59290
Iteration: 32912/59290

 55%|█████▌    | 32901/59290 [23:57<08:53, 49.45it/s]

Iteration: 32913/59290
Iteration: 32914/59290
Iteration: 32915/59290
Iteration: 32916/59290
Iteration: 32917/59290
Iteration: 32918/59290
Iteration: 32919/59290
Iteration: 32920/59290
Iteration: 32921/59290
Iteration: 32922/59290
Iteration: 32923/59290
Iteration: 32924/59290
Iteration: 32925/59290
Iteration: 32926/59290
Iteration: 32927/59290
Iteration: 32928/59290
Iteration: 32929/59290
Iteration: 32930/59290
Iteration: 32931/59290
Iteration: 32932/59290
Iteration: 32933/59290
Iteration: 32934/59290
Iteration: 32935/59290
Iteration: 32936/59290

 56%|█████▌    | 32925/59290 [23:57<08:20, 52.73it/s]

Iteration: 32937/59290
Iteration: 32938/59290
Iteration: 32939/59290
Iteration: 32940/59290
Iteration: 32941/59290
Iteration: 32942/59290
Iteration: 32943/59290
Iteration: 32944/59290
Iteration: 32945/59290
Iteration: 32946/59290
Iteration: 32947/59290
Iteration: 32948/59290
Iteration: 32949/59290
Iteration: 32950/59290
Iteration: 32951/59290
Iteration: 32952/59290
Iteration: 32953/59290
Iteration: 32954/59290
Iteration: 32955/59290
Iteration: 32956/59290
Iteration: 32957/59290
Iteration: 32958/59290
Iteration: 32959/59290
Iteration: 32960/59290

 56%|█████▌    | 32949/59290 [23:58<07:52, 55.75it/s]

Iteration: 32961/59290
Iteration: 32962/59290
Iteration: 32963/59290
Iteration: 32964/59290
Iteration: 32965/59290
Iteration: 32966/59290
Iteration: 32967/59290
Iteration: 32968/59290
Iteration: 32969/59290
Iteration: 32970/59290
Iteration: 32971/59290
Iteration: 32972/59290
Iteration: 32973/59290
Iteration: 32974/59290
Iteration: 32975/59290
Iteration: 32976/59290
Iteration: 32977/59290
Iteration: 32978/59290
Iteration: 32979/59290
Iteration: 32980/59290
Iteration: 32981/59290
Iteration: 32982/59290
Iteration: 32983/59290
Iteration: 32984/59290

 56%|█████▌    | 32973/59290 [23:58<07:33, 58.04it/s]

Iteration: 32985/59290
Iteration: 32986/59290
Iteration: 32987/59290
Iteration: 32988/59290
Iteration: 32989/59290
Iteration: 32990/59290
Iteration: 32991/59290
Iteration: 32992/59290
Iteration: 32993/59290
Iteration: 32994/59290
Iteration: 32995/59290
Iteration: 32996/59290
Iteration: 32997/59290
Iteration: 32998/59290
Iteration: 32999/59290
Iteration: 33000/59290
Iteration: 33001/59290
Iteration: 33002/59290
Iteration: 33003/59290
Iteration: 33004/59290
Iteration: 33005/59290
Iteration: 33006/59290
Iteration: 33007/59290
Iteration: 33008/59290

 56%|█████▌    | 32997/59290 [23:58<07:23, 59.29it/s]

Iteration: 33009/59290
Iteration: 33010/59290
Iteration: 33011/59290
Iteration: 33012/59290
Iteration: 33013/59290
Iteration: 33014/59290
Iteration: 33015/59290
Iteration: 33016/59290
Iteration: 33017/59290
Iteration: 33018/59290
Iteration: 33019/59290
Iteration: 33020/59290
Iteration: 33021/59290
Iteration: 33022/59290
Iteration: 33023/59290
Iteration: 33024/59290
Iteration: 33025/59290
Iteration: 33026/59290
Iteration: 33027/59290
Iteration: 33028/59290
Iteration: 33029/59290
Iteration: 33030/59290
Iteration: 33031/59290
Iteration: 33032/59290

 56%|█████▌    | 33021/59290 [24:00<14:46, 29.64it/s]

Iteration: 33033/59290
Iteration: 33034/59290
Iteration: 33035/59290
Iteration: 33036/59290
Iteration: 33037/59290
Iteration: 33038/59290
Iteration: 33039/59290
Iteration: 33040/59290
Iteration: 33041/59290
Iteration: 33042/59290
Iteration: 33043/59290
Iteration: 33044/59290
Iteration: 33045/59290
Iteration: 33046/59290
Iteration: 33047/59290
Iteration: 33048/59290
Iteration: 33049/59290
Iteration: 33050/59290
Iteration: 33051/59290
Iteration: 33052/59290
Iteration: 33053/59290
Iteration: 33054/59290
Iteration: 33055/59290
Iteration: 33056/59290

 56%|█████▌    | 33045/59290 [24:02<21:33, 20.29it/s]

Iteration: 33057/59290
Iteration: 33058/59290
Iteration: 33059/59290
Iteration: 33060/59290
Iteration: 33061/59290
Iteration: 33062/59290
Iteration: 33063/59290
Iteration: 33064/59290
Iteration: 33065/59290
Iteration: 33066/59290
Iteration: 33067/59290
Iteration: 33068/59290
Iteration: 33069/59290
Iteration: 33070/59290
Iteration: 33071/59290
Iteration: 33072/59290
Iteration: 33073/59290
Iteration: 33074/59290
Iteration: 33075/59290
Iteration: 33076/59290
Iteration: 33077/59290
Iteration: 33078/59290
Iteration: 33079/59290
Iteration: 33080/59290

 56%|█████▌    | 33069/59290 [24:03<17:39, 24.74it/s]

Iteration: 33081/59290
Iteration: 33082/59290
Iteration: 33083/59290
Iteration: 33084/59290
Iteration: 33085/59290
Iteration: 33086/59290
Iteration: 33087/59290
Iteration: 33088/59290
Iteration: 33089/59290
Iteration: 33090/59290
Iteration: 33091/59290
Iteration: 33092/59290
Iteration: 33093/59290
Iteration: 33094/59290
Iteration: 33095/59290
Iteration: 33096/59290
Iteration: 33097/59290
Iteration: 33098/59290
Iteration: 33099/59290
Iteration: 33100/59290
Iteration: 33101/59290
Iteration: 33102/59290
Iteration: 33103/59290
Iteration: 33104/59290

 56%|█████▌    | 33093/59290 [24:03<14:39, 29.80it/s]

Iteration: 33105/59290
Iteration: 33106/59290
Iteration: 33107/59290
Iteration: 33108/59290
Iteration: 33109/59290
Iteration: 33110/59290
Iteration: 33111/59290
Iteration: 33112/59290
Iteration: 33113/59290
Iteration: 33114/59290
Iteration: 33115/59290
Iteration: 33116/59290
Iteration: 33117/59290
Iteration: 33118/59290
Iteration: 33119/59290
Iteration: 33120/59290
Iteration: 33121/59290
Iteration: 33122/59290
Iteration: 33123/59290
Iteration: 33124/59290
Iteration: 33125/59290
Iteration: 33126/59290
Iteration: 33127/59290
Iteration: 33128/59290

 56%|█████▌    | 33117/59290 [24:03<12:20, 35.34it/s]

Iteration: 33129/59290
Iteration: 33130/59290
Iteration: 33131/59290
Iteration: 33132/59290
Iteration: 33133/59290
Iteration: 33134/59290
Iteration: 33135/59290
Iteration: 33136/59290
Iteration: 33137/59290
Iteration: 33138/59290
Iteration: 33139/59290
Iteration: 33140/59290
Iteration: 33141/59290
Iteration: 33142/59290
Iteration: 33143/59290
Iteration: 33144/59290
Iteration: 33145/59290
Iteration: 33146/59290
Iteration: 33147/59290
Iteration: 33148/59290
Iteration: 33149/59290
Iteration: 33150/59290
Iteration: 33151/59290
Iteration: 33152/59290

 56%|█████▌    | 33141/59290 [24:04<10:47, 40.41it/s]

Iteration: 33153/59290
Iteration: 33154/59290
Iteration: 33155/59290
Iteration: 33156/59290
Iteration: 33157/59290
Iteration: 33158/59290
Iteration: 33159/59290
Iteration: 33160/59290
Iteration: 33161/59290
Iteration: 33162/59290
Iteration: 33163/59290
Iteration: 33164/59290
Iteration: 33165/59290
Iteration: 33166/59290
Iteration: 33167/59290
Iteration: 33168/59290
Iteration: 33169/59290
Iteration: 33170/59290
Iteration: 33171/59290
Iteration: 33172/59290
Iteration: 33173/59290
Iteration: 33174/59290
Iteration: 33175/59290
Iteration: 33176/59290

 56%|█████▌    | 33165/59290 [24:06<16:34, 26.28it/s]

Iteration: 33177/59290
Iteration: 33178/59290
Iteration: 33179/59290
Iteration: 33180/59290
Iteration: 33181/59290
Iteration: 33182/59290
Iteration: 33183/59290
Iteration: 33184/59290
Iteration: 33185/59290
Iteration: 33186/59290
Iteration: 33187/59290
Iteration: 33188/59290
Iteration: 33189/59290
Iteration: 33190/59290
Iteration: 33191/59290
Iteration: 33192/59290
Iteration: 33193/59290
Iteration: 33194/59290
Iteration: 33195/59290
Iteration: 33196/59290
Iteration: 33197/59290
Iteration: 33198/59290
Iteration: 33199/59290
Iteration: 33200/59290

 56%|█████▌    | 33189/59290 [24:07<21:57, 19.82it/s]

Iteration: 33201/59290
Iteration: 33202/59290
Iteration: 33203/59290
Iteration: 33204/59290
Iteration: 33205/59290
Iteration: 33206/59290
Iteration: 33207/59290
Iteration: 33208/59290
Iteration: 33209/59290
Iteration: 33210/59290
Iteration: 33211/59290
Iteration: 33212/59290
Iteration: 33213/59290
Iteration: 33214/59290
Iteration: 33215/59290
Iteration: 33216/59290
Iteration: 33217/59290
Iteration: 33218/59290
Iteration: 33219/59290
Iteration: 33220/59290
Iteration: 33221/59290
Iteration: 33222/59290
Iteration: 33223/59290
Iteration: 33224/59290

 56%|█████▌    | 33213/59290 [24:08<17:45, 24.48it/s]

Iteration: 33225/59290
Iteration: 33226/59290
Iteration: 33227/59290
Iteration: 33228/59290
Iteration: 33229/59290
Iteration: 33230/59290
Iteration: 33231/59290
Iteration: 33232/59290
Iteration: 33233/59290
Iteration: 33234/59290
Iteration: 33235/59290
Iteration: 33236/59290
Iteration: 33237/59290
Iteration: 33238/59290
Iteration: 33239/59290
Iteration: 33240/59290
Iteration: 33241/59290
Iteration: 33242/59290
Iteration: 33243/59290
Iteration: 33244/59290
Iteration: 33245/59290
Iteration: 33246/59290
Iteration: 33247/59290
Iteration: 33248/59290

 56%|█████▌    | 33237/59290 [24:08<14:30, 29.92it/s]

Iteration: 33249/59290
Iteration: 33250/59290
Iteration: 33251/59290
Iteration: 33252/59290
Iteration: 33253/59290
Iteration: 33254/59290
Iteration: 33255/59290
Iteration: 33256/59290
Iteration: 33257/59290
Iteration: 33258/59290
Iteration: 33259/59290
Iteration: 33260/59290
Iteration: 33261/59290
Iteration: 33262/59290
Iteration: 33263/59290
Iteration: 33264/59290
Iteration: 33265/59290
Iteration: 33266/59290
Iteration: 33267/59290
Iteration: 33268/59290
Iteration: 33269/59290
Iteration: 33270/59290
Iteration: 33271/59290
Iteration: 33272/59290

 56%|█████▌    | 33261/59290 [24:09<12:12, 35.54it/s]

Iteration: 33273/59290
Iteration: 33274/59290
Iteration: 33275/59290
Iteration: 33276/59290
Iteration: 33277/59290
Iteration: 33278/59290
Iteration: 33279/59290
Iteration: 33280/59290
Iteration: 33281/59290
Iteration: 33282/59290
Iteration: 33283/59290
Iteration: 33284/59290
Iteration: 33285/59290
Iteration: 33286/59290
Iteration: 33287/59290
Iteration: 33288/59290
Iteration: 33289/59290
Iteration: 33290/59290
Iteration: 33291/59290
Iteration: 33292/59290
Iteration: 33293/59290
Iteration: 33294/59290
Iteration: 33295/59290
Iteration: 33296/59290

 56%|█████▌    | 33285/59290 [24:09<10:39, 40.69it/s]

Iteration: 33297/59290
Iteration: 33298/59290
Iteration: 33299/59290
Iteration: 33300/59290
Iteration: 33301/59290
Iteration: 33302/59290
Iteration: 33303/59290
Iteration: 33304/59290
Iteration: 33305/59290
Iteration: 33306/59290
Iteration: 33307/59290
Iteration: 33308/59290
Iteration: 33309/59290
Iteration: 33310/59290
Iteration: 33311/59290
Iteration: 33312/59290
Iteration: 33313/59290
Iteration: 33314/59290
Iteration: 33315/59290
Iteration: 33316/59290
Iteration: 33317/59290
Iteration: 33318/59290
Iteration: 33319/59290
Iteration: 33320/59290

 56%|█████▌    | 33309/59290 [24:11<15:38, 27.69it/s]

Iteration: 33321/59290
Iteration: 33322/59290
Iteration: 33323/59290
Iteration: 33324/59290
Iteration: 33325/59290
Iteration: 33326/59290
Iteration: 33327/59290
Iteration: 33328/59290
Iteration: 33329/59290
Iteration: 33330/59290
Iteration: 33331/59290
Iteration: 33332/59290
Iteration: 33333/59290
Iteration: 33334/59290
Iteration: 33335/59290
Iteration: 33336/59290
Iteration: 33337/59290
Iteration: 33338/59290
Iteration: 33339/59290
Iteration: 33340/59290
Iteration: 33341/59290
Iteration: 33342/59290
Iteration: 33343/59290
Iteration: 33344/59290

 56%|█████▌    | 33333/59290 [24:13<23:23, 18.49it/s]

Iteration: 33345/59290
Iteration: 33346/59290
Iteration: 33347/59290
Iteration: 33348/59290
Iteration: 33349/59290
Iteration: 33350/59290
Iteration: 33351/59290
Iteration: 33352/59290
Iteration: 33353/59290
Iteration: 33354/59290
Iteration: 33355/59290
Iteration: 33356/59290
Iteration: 33357/59290
Iteration: 33358/59290
Iteration: 33359/59290
Iteration: 33360/59290
Iteration: 33361/59290
Iteration: 33362/59290
Iteration: 33363/59290
Iteration: 33364/59290
Iteration: 33365/59290
Iteration: 33366/59290
Iteration: 33367/59290
Iteration: 33368/59290

 56%|█████▋    | 33357/59290 [24:13<18:25, 23.46it/s]

Iteration: 33369/59290
Iteration: 33370/59290
Iteration: 33371/59290
Iteration: 33372/59290
Iteration: 33373/59290
Iteration: 33374/59290
Iteration: 33375/59290
Iteration: 33376/59290
Iteration: 33377/59290
Iteration: 33378/59290
Iteration: 33379/59290
Iteration: 33380/59290
Iteration: 33381/59290
Iteration: 33382/59290
Iteration: 33383/59290
Iteration: 33384/59290
Iteration: 33385/59290
Iteration: 33386/59290
Iteration: 33387/59290
Iteration: 33388/59290
Iteration: 33389/59290
Iteration: 33390/59290
Iteration: 33391/59290
Iteration: 33392/59290

 56%|█████▋    | 33381/59290 [24:14<14:58, 28.85it/s]

Iteration: 33393/59290
Iteration: 33394/59290
Iteration: 33395/59290
Iteration: 33396/59290
Iteration: 33397/59290
Iteration: 33398/59290
Iteration: 33399/59290
Iteration: 33400/59290
Iteration: 33401/59290
Iteration: 33402/59290
Iteration: 33403/59290
Iteration: 33404/59290
Iteration: 33405/59290
Iteration: 33406/59290
Iteration: 33407/59290
Iteration: 33408/59290
Iteration: 33409/59290
Iteration: 33410/59290
Iteration: 33411/59290
Iteration: 33412/59290
Iteration: 33413/59290
Iteration: 33414/59290
Iteration: 33415/59290
Iteration: 33416/59290

 56%|█████▋    | 33405/59290 [24:14<12:31, 34.42it/s]

Iteration: 33417/59290
Iteration: 33418/59290
Iteration: 33419/59290
Iteration: 33420/59290
Iteration: 33421/59290
Iteration: 33422/59290
Iteration: 33423/59290
Iteration: 33424/59290
Iteration: 33425/59290
Iteration: 33426/59290
Iteration: 33427/59290
Iteration: 33428/59290
Iteration: 33429/59290
Iteration: 33430/59290
Iteration: 33431/59290
Iteration: 33432/59290
Iteration: 33433/59290
Iteration: 33434/59290
Iteration: 33435/59290
Iteration: 33436/59290
Iteration: 33437/59290
Iteration: 33438/59290
Iteration: 33439/59290
Iteration: 33440/59290

 56%|█████▋    | 33429/59290 [24:15<16:25, 26.25it/s]

Iteration: 33441/59290
Iteration: 33442/59290
Iteration: 33443/59290
Iteration: 33444/59290
Iteration: 33445/59290
Iteration: 33446/59290
Iteration: 33447/59290
Iteration: 33448/59290
Iteration: 33449/59290
Iteration: 33450/59290
Iteration: 33451/59290
Iteration: 33452/59290
Iteration: 33453/59290
Iteration: 33454/59290
Iteration: 33455/59290
Iteration: 33456/59290
Iteration: 33457/59290
Iteration: 33458/59290
Iteration: 33459/59290
Iteration: 33460/59290
Iteration: 33461/59290
Iteration: 33462/59290
Iteration: 33463/59290
Iteration: 33464/59290

 56%|█████▋    | 33453/59290 [24:18<23:55, 18.00it/s]

Iteration: 33465/59290
Iteration: 33466/59290
Iteration: 33467/59290
Iteration: 33468/59290
Iteration: 33469/59290
Iteration: 33470/59290
Iteration: 33471/59290
Iteration: 33472/59290
Iteration: 33473/59290
Iteration: 33474/59290
Iteration: 33475/59290
Iteration: 33476/59290
Iteration: 33477/59290
Iteration: 33478/59290
Iteration: 33479/59290
Iteration: 33480/59290
Iteration: 33481/59290
Iteration: 33482/59290
Iteration: 33483/59290
Iteration: 33484/59290
Iteration: 33485/59290
Iteration: 33486/59290
Iteration: 33487/59290
Iteration: 33488/59290

 56%|█████▋    | 33477/59290 [24:18<18:54, 22.76it/s]

Iteration: 33489/59290
Iteration: 33490/59290
Iteration: 33491/59290
Iteration: 33492/59290
Iteration: 33493/59290
Iteration: 33494/59290
Iteration: 33495/59290
Iteration: 33496/59290
Iteration: 33497/59290
Iteration: 33498/59290
Iteration: 33499/59290
Iteration: 33500/59290
Iteration: 33501/59290
Iteration: 33502/59290
Iteration: 33503/59290
Iteration: 33504/59290
Iteration: 33505/59290
Iteration: 33506/59290
Iteration: 33507/59290
Iteration: 33508/59290
Iteration: 33509/59290
Iteration: 33510/59290
Iteration: 33511/59290
Iteration: 33512/59290

 57%|█████▋    | 33501/59290 [24:19<15:21, 27.99it/s]

Iteration: 33513/59290
Iteration: 33514/59290
Iteration: 33515/59290
Iteration: 33516/59290
Iteration: 33517/59290
Iteration: 33518/59290
Iteration: 33519/59290
Iteration: 33520/59290
Iteration: 33521/59290
Iteration: 33522/59290
Iteration: 33523/59290
Iteration: 33524/59290
Iteration: 33525/59290
Iteration: 33526/59290
Iteration: 33527/59290
Iteration: 33528/59290
Iteration: 33529/59290
Iteration: 33530/59290
Iteration: 33531/59290
Iteration: 33532/59290
Iteration: 33533/59290
Iteration: 33534/59290
Iteration: 33535/59290
Iteration: 33536/59290

 57%|█████▋    | 33525/59290 [24:19<12:45, 33.65it/s]

Iteration: 33537/59290
Iteration: 33538/59290
Iteration: 33539/59290
Iteration: 33540/59290
Iteration: 33541/59290
Iteration: 33542/59290
Iteration: 33543/59290
Iteration: 33544/59290
Iteration: 33545/59290
Iteration: 33546/59290
Iteration: 33547/59290
Iteration: 33548/59290
Iteration: 33549/59290
Iteration: 33550/59290
Iteration: 33551/59290
Iteration: 33552/59290
Iteration: 33553/59290
Iteration: 33554/59290
Iteration: 33555/59290
Iteration: 33556/59290
Iteration: 33557/59290
Iteration: 33558/59290
Iteration: 33559/59290
Iteration: 33560/59290

 57%|█████▋    | 33549/59290 [24:19<10:57, 39.13it/s]

Iteration: 33561/59290
Iteration: 33562/59290
Iteration: 33563/59290
Iteration: 33564/59290
Iteration: 33565/59290
Iteration: 33566/59290
Iteration: 33567/59290
Iteration: 33568/59290
Iteration: 33569/59290
Iteration: 33570/59290
Iteration: 33571/59290
Iteration: 33572/59290
Iteration: 33573/59290
Iteration: 33574/59290
Iteration: 33575/59290
Iteration: 33576/59290
Iteration: 33577/59290
Iteration: 33578/59290
Iteration: 33579/59290
Iteration: 33580/59290
Iteration: 33581/59290
Iteration: 33582/59290
Iteration: 33583/59290
Iteration: 33584/59290

 57%|█████▋    | 33573/59290 [24:20<09:41, 44.22it/s]

Iteration: 33585/59290
Iteration: 33586/59290
Iteration: 33587/59290
Iteration: 33588/59290
Iteration: 33589/59290
Iteration: 33590/59290
Iteration: 33591/59290
Iteration: 33592/59290
Iteration: 33593/59290
Iteration: 33594/59290
Iteration: 33595/59290
Iteration: 33596/59290
Iteration: 33597/59290
Iteration: 33598/59290
Iteration: 33599/59290
Iteration: 33600/59290
Iteration: 33601/59290
Iteration: 33602/59290
Iteration: 33603/59290
Iteration: 33604/59290
Iteration: 33605/59290
Iteration: 33606/59290
Iteration: 33607/59290
Iteration: 33608/59290

 57%|█████▋    | 33597/59290 [24:20<08:46, 48.79it/s]

Iteration: 33609/59290
Iteration: 33610/59290
Iteration: 33611/59290
Iteration: 33612/59290
Iteration: 33613/59290
Iteration: 33614/59290
Iteration: 33615/59290
Iteration: 33616/59290
Iteration: 33617/59290
Iteration: 33618/59290
Iteration: 33619/59290
Iteration: 33620/59290
Iteration: 33621/59290
Iteration: 33622/59290
Iteration: 33623/59290
Iteration: 33624/59290
Iteration: 33625/59290
Iteration: 33626/59290
Iteration: 33627/59290
Iteration: 33628/59290
Iteration: 33629/59290
Iteration: 33630/59290
Iteration: 33631/59290
Iteration: 33632/59290

 57%|█████▋    | 33621/59290 [24:20<08:10, 52.38it/s]

Iteration: 33633/59290
Iteration: 33634/59290
Iteration: 33635/59290
Iteration: 33636/59290
Iteration: 33637/59290
Iteration: 33638/59290
Iteration: 33639/59290
Iteration: 33640/59290
Iteration: 33641/59290
Iteration: 33642/59290
Iteration: 33643/59290
Iteration: 33644/59290
Iteration: 33645/59290
Iteration: 33646/59290
Iteration: 33647/59290
Iteration: 33648/59290
Iteration: 33649/59290
Iteration: 33650/59290
Iteration: 33651/59290
Iteration: 33652/59290
Iteration: 33653/59290
Iteration: 33654/59290
Iteration: 33655/59290
Iteration: 33656/59290

 57%|█████▋    | 33645/59290 [24:22<14:00, 30.52it/s]

Iteration: 33657/59290
Iteration: 33658/59290
Iteration: 33659/59290
Iteration: 33660/59290
Iteration: 33661/59290
Iteration: 33662/59290
Iteration: 33663/59290
Iteration: 33664/59290
Iteration: 33665/59290
Iteration: 33666/59290
Iteration: 33667/59290
Iteration: 33668/59290
Iteration: 33669/59290
Iteration: 33670/59290
Iteration: 33671/59290
Iteration: 33672/59290
Iteration: 33673/59290
Iteration: 33674/59290
Iteration: 33675/59290
Iteration: 33676/59290
Iteration: 33677/59290
Iteration: 33678/59290
Iteration: 33679/59290
Iteration: 33680/59290

 57%|█████▋    | 33669/59290 [24:24<22:05, 19.33it/s]

Iteration: 33681/59290
Iteration: 33682/59290
Iteration: 33683/59290
Iteration: 33684/59290
Iteration: 33685/59290
Iteration: 33686/59290
Iteration: 33687/59290
Iteration: 33688/59290
Iteration: 33689/59290
Iteration: 33690/59290
Iteration: 33691/59290
Iteration: 33692/59290
Iteration: 33693/59290
Iteration: 33694/59290
Iteration: 33695/59290
Iteration: 33696/59290
Iteration: 33697/59290
Iteration: 33698/59290
Iteration: 33699/59290
Iteration: 33700/59290
Iteration: 33701/59290
Iteration: 33702/59290
Iteration: 33703/59290
Iteration: 33704/59290

 57%|█████▋    | 33693/59290 [24:25<17:35, 24.24it/s]

Iteration: 33705/59290
Iteration: 33706/59290
Iteration: 33707/59290
Iteration: 33708/59290
Iteration: 33709/59290
Iteration: 33710/59290
Iteration: 33711/59290
Iteration: 33712/59290
Iteration: 33713/59290
Iteration: 33714/59290
Iteration: 33715/59290
Iteration: 33716/59290
Iteration: 33717/59290
Iteration: 33718/59290
Iteration: 33719/59290
Iteration: 33720/59290
Iteration: 33721/59290
Iteration: 33722/59290
Iteration: 33723/59290
Iteration: 33724/59290
Iteration: 33725/59290
Iteration: 33726/59290
Iteration: 33727/59290
Iteration: 33728/59290

 57%|█████▋    | 33717/59290 [24:25<14:21, 29.69it/s]

Iteration: 33729/59290
Iteration: 33730/59290
Iteration: 33731/59290
Iteration: 33732/59290
Iteration: 33733/59290
Iteration: 33734/59290
Iteration: 33735/59290
Iteration: 33736/59290
Iteration: 33737/59290
Iteration: 33738/59290
Iteration: 33739/59290
Iteration: 33740/59290
Iteration: 33741/59290
Iteration: 33742/59290
Iteration: 33743/59290
Iteration: 33744/59290
Iteration: 33745/59290
Iteration: 33746/59290
Iteration: 33747/59290
Iteration: 33748/59290
Iteration: 33749/59290
Iteration: 33750/59290
Iteration: 33751/59290
Iteration: 33752/59290

 57%|█████▋    | 33741/59290 [24:25<12:05, 35.23it/s]

Iteration: 33753/59290
Iteration: 33754/59290
Iteration: 33755/59290
Iteration: 33756/59290
Iteration: 33757/59290
Iteration: 33758/59290
Iteration: 33759/59290
Iteration: 33760/59290
Iteration: 33761/59290
Iteration: 33762/59290
Iteration: 33763/59290
Iteration: 33764/59290
Iteration: 33765/59290
Iteration: 33766/59290
Iteration: 33767/59290
Iteration: 33768/59290
Iteration: 33769/59290
Iteration: 33770/59290
Iteration: 33771/59290
Iteration: 33772/59290
Iteration: 33773/59290
Iteration: 33774/59290
Iteration: 33775/59290
Iteration: 33776/59290

 57%|█████▋    | 33765/59290 [24:26<10:28, 40.59it/s]

Iteration: 33777/59290
Iteration: 33778/59290
Iteration: 33779/59290
Iteration: 33780/59290
Iteration: 33781/59290
Iteration: 33782/59290
Iteration: 33783/59290
Iteration: 33784/59290
Iteration: 33785/59290
Iteration: 33786/59290
Iteration: 33787/59290
Iteration: 33788/59290
Iteration: 33789/59290
Iteration: 33790/59290
Iteration: 33791/59290
Iteration: 33792/59290
Iteration: 33793/59290
Iteration: 33794/59290
Iteration: 33795/59290
Iteration: 33796/59290
Iteration: 33797/59290
Iteration: 33798/59290
Iteration: 33799/59290
Iteration: 33800/59290

 57%|█████▋    | 33789/59290 [24:26<09:20, 45.49it/s]

Iteration: 33801/59290
Iteration: 33802/59290
Iteration: 33803/59290
Iteration: 33804/59290
Iteration: 33805/59290
Iteration: 33806/59290
Iteration: 33807/59290
Iteration: 33808/59290
Iteration: 33809/59290
Iteration: 33810/59290
Iteration: 33811/59290
Iteration: 33812/59290
Iteration: 33813/59290
Iteration: 33814/59290
Iteration: 33815/59290
Iteration: 33816/59290
Iteration: 33817/59290
Iteration: 33818/59290
Iteration: 33819/59290
Iteration: 33820/59290
Iteration: 33821/59290
Iteration: 33822/59290
Iteration: 33823/59290
Iteration: 33824/59290

 57%|█████▋    | 33813/59290 [24:27<08:31, 49.77it/s]

Iteration: 33825/59290
Iteration: 33826/59290
Iteration: 33827/59290
Iteration: 33828/59290
Iteration: 33829/59290
Iteration: 33830/59290
Iteration: 33831/59290
Iteration: 33832/59290
Iteration: 33833/59290
Iteration: 33834/59290
Iteration: 33835/59290
Iteration: 33836/59290
Iteration: 33837/59290
Iteration: 33838/59290
Iteration: 33839/59290
Iteration: 33840/59290
Iteration: 33841/59290
Iteration: 33842/59290
Iteration: 33843/59290
Iteration: 33844/59290
Iteration: 33845/59290
Iteration: 33846/59290
Iteration: 33847/59290
Iteration: 33848/59290

 57%|█████▋    | 33837/59290 [24:27<07:57, 53.30it/s]

Iteration: 33849/59290
Iteration: 33850/59290
Iteration: 33851/59290
Iteration: 33852/59290
Iteration: 33853/59290
Iteration: 33854/59290
Iteration: 33855/59290
Iteration: 33856/59290
Iteration: 33857/59290
Iteration: 33858/59290
Iteration: 33859/59290
Iteration: 33860/59290
Iteration: 33861/59290
Iteration: 33862/59290
Iteration: 33863/59290
Iteration: 33864/59290
Iteration: 33865/59290
Iteration: 33866/59290
Iteration: 33867/59290
Iteration: 33868/59290
Iteration: 33869/59290
Iteration: 33870/59290
Iteration: 33871/59290
Iteration: 33872/59290

 57%|█████▋    | 33861/59290 [24:27<07:32, 56.17it/s]

Iteration: 33873/59290
Iteration: 33874/59290
Iteration: 33875/59290
Iteration: 33876/59290
Iteration: 33877/59290
Iteration: 33878/59290
Iteration: 33879/59290
Iteration: 33880/59290
Iteration: 33881/59290
Iteration: 33882/59290
Iteration: 33883/59290
Iteration: 33884/59290
Iteration: 33885/59290
Iteration: 33886/59290
Iteration: 33887/59290
Iteration: 33888/59290
Iteration: 33889/59290
Iteration: 33890/59290
Iteration: 33891/59290
Iteration: 33892/59290
Iteration: 33893/59290
Iteration: 33894/59290
Iteration: 33895/59290
Iteration: 33896/59290

 57%|█████▋    | 33885/59290 [24:28<07:22, 57.38it/s]

Iteration: 33897/59290
Iteration: 33898/59290
Iteration: 33899/59290
Iteration: 33900/59290
Iteration: 33901/59290
Iteration: 33902/59290
Iteration: 33903/59290
Iteration: 33904/59290
Iteration: 33905/59290
Iteration: 33906/59290
Iteration: 33907/59290
Iteration: 33908/59290
Iteration: 33909/59290
Iteration: 33910/59290
Iteration: 33911/59290
Iteration: 33912/59290
Iteration: 33913/59290
Iteration: 33914/59290
Iteration: 33915/59290
Iteration: 33916/59290
Iteration: 33917/59290
Iteration: 33918/59290
Iteration: 33919/59290
Iteration: 33920/59290

 57%|█████▋    | 33909/59290 [24:28<07:08, 59.24it/s]

Iteration: 33921/59290
Iteration: 33922/59290
Iteration: 33923/59290
Iteration: 33924/59290
Iteration: 33925/59290
Iteration: 33926/59290
Iteration: 33927/59290
Iteration: 33928/59290
Iteration: 33929/59290
Iteration: 33930/59290
Iteration: 33931/59290
Iteration: 33932/59290
Iteration: 33933/59290
Iteration: 33934/59290
Iteration: 33935/59290
Iteration: 33936/59290
Iteration: 33937/59290
Iteration: 33938/59290
Iteration: 33939/59290
Iteration: 33940/59290
Iteration: 33941/59290
Iteration: 33942/59290
Iteration: 33943/59290
Iteration: 33944/59290

 57%|█████▋    | 33933/59290 [24:28<06:58, 60.64it/s]

Iteration: 33945/59290
Iteration: 33946/59290
Iteration: 33947/59290
Iteration: 33948/59290
Iteration: 33949/59290
Iteration: 33950/59290
Iteration: 33951/59290
Iteration: 33952/59290
Iteration: 33953/59290
Iteration: 33954/59290
Iteration: 33955/59290
Iteration: 33956/59290
Iteration: 33957/59290
Iteration: 33958/59290
Iteration: 33959/59290
Iteration: 33960/59290
Iteration: 33961/59290
Iteration: 33962/59290
Iteration: 33963/59290
Iteration: 33964/59290
Iteration: 33965/59290
Iteration: 33966/59290
Iteration: 33967/59290
Iteration: 33968/59290

 57%|█████▋    | 33957/59290 [24:30<12:37, 33.44it/s]

Iteration: 33969/59290
Iteration: 33970/59290
Iteration: 33971/59290
Iteration: 33972/59290
Iteration: 33973/59290
Iteration: 33974/59290
Iteration: 33975/59290
Iteration: 33976/59290
Iteration: 33977/59290
Iteration: 33978/59290
Iteration: 33979/59290
Iteration: 33980/59290
Iteration: 33981/59290
Iteration: 33982/59290
Iteration: 33983/59290
Iteration: 33984/59290
Iteration: 33985/59290
Iteration: 33986/59290
Iteration: 33987/59290
Iteration: 33988/59290
Iteration: 33989/59290
Iteration: 33990/59290
Iteration: 33991/59290
Iteration: 33992/59290

 57%|█████▋    | 33981/59290 [24:32<20:58, 20.10it/s]

Iteration: 33993/59290
Iteration: 33994/59290
Iteration: 33995/59290
Iteration: 33996/59290
Iteration: 33997/59290
Iteration: 33998/59290
Iteration: 33999/59290
Iteration: 34000/59290
Iteration: 34001/59290
Iteration: 34002/59290
Iteration: 34003/59290
Iteration: 34004/59290
Iteration: 34005/59290
Iteration: 34006/59290
Iteration: 34007/59290
Iteration: 34008/59290
Iteration: 34009/59290
Iteration: 34010/59290
Iteration: 34011/59290
Iteration: 34012/59290
Iteration: 34013/59290
Iteration: 34014/59290
Iteration: 34015/59290
Iteration: 34016/59290

 57%|█████▋    | 34005/59290 [24:33<16:44, 25.17it/s]

Iteration: 34017/59290
Iteration: 34018/59290
Iteration: 34019/59290
Iteration: 34020/59290
Iteration: 34021/59290
Iteration: 34022/59290
Iteration: 34023/59290
Iteration: 34024/59290
Iteration: 34025/59290
Iteration: 34026/59290
Iteration: 34027/59290
Iteration: 34028/59290
Iteration: 34029/59290
Iteration: 34030/59290
Iteration: 34031/59290
Iteration: 34032/59290
Iteration: 34033/59290
Iteration: 34034/59290
Iteration: 34035/59290
Iteration: 34036/59290
Iteration: 34037/59290
Iteration: 34038/59290
Iteration: 34039/59290
Iteration: 34040/59290

 57%|█████▋    | 34029/59290 [24:33<13:44, 30.64it/s]

Iteration: 34041/59290
Iteration: 34042/59290
Iteration: 34043/59290
Iteration: 34044/59290
Iteration: 34045/59290
Iteration: 34046/59290
Iteration: 34047/59290
Iteration: 34048/59290
Iteration: 34049/59290
Iteration: 34050/59290
Iteration: 34051/59290
Iteration: 34052/59290
Iteration: 34053/59290
Iteration: 34054/59290
Iteration: 34055/59290
Iteration: 34056/59290
Iteration: 34057/59290
Iteration: 34058/59290
Iteration: 34059/59290
Iteration: 34060/59290
Iteration: 34061/59290
Iteration: 34062/59290
Iteration: 34063/59290
Iteration: 34064/59290

 57%|█████▋    | 34053/59290 [24:33<11:34, 36.32it/s]

Iteration: 34065/59290
Iteration: 34066/59290
Iteration: 34067/59290
Iteration: 34068/59290
Iteration: 34069/59290
Iteration: 34070/59290
Iteration: 34071/59290
Iteration: 34072/59290
Iteration: 34073/59290
Iteration: 34074/59290
Iteration: 34075/59290
Iteration: 34076/59290
Iteration: 34077/59290
Iteration: 34078/59290
Iteration: 34079/59290
Iteration: 34080/59290
Iteration: 34081/59290
Iteration: 34082/59290
Iteration: 34083/59290
Iteration: 34084/59290
Iteration: 34085/59290
Iteration: 34086/59290
Iteration: 34087/59290
Iteration: 34088/59290

 57%|█████▋    | 34077/59290 [24:34<10:08, 41.41it/s]

Iteration: 34089/59290
Iteration: 34090/59290
Iteration: 34091/59290
Iteration: 34092/59290
Iteration: 34093/59290
Iteration: 34094/59290
Iteration: 34095/59290
Iteration: 34096/59290
Iteration: 34097/59290
Iteration: 34098/59290
Iteration: 34099/59290
Iteration: 34100/59290
Iteration: 34101/59290
Iteration: 34102/59290
Iteration: 34103/59290
Iteration: 34104/59290
Iteration: 34105/59290
Iteration: 34106/59290
Iteration: 34107/59290
Iteration: 34108/59290
Iteration: 34109/59290
Iteration: 34110/59290
Iteration: 34111/59290
Iteration: 34112/59290

 58%|█████▊    | 34101/59290 [24:35<15:20, 27.36it/s]

Iteration: 34113/59290
Iteration: 34114/59290
Iteration: 34115/59290
Iteration: 34116/59290
Iteration: 34117/59290
Iteration: 34118/59290
Iteration: 34119/59290
Iteration: 34120/59290
Iteration: 34121/59290
Iteration: 34122/59290
Iteration: 34123/59290
Iteration: 34124/59290
Iteration: 34125/59290
Iteration: 34126/59290
Iteration: 34127/59290
Iteration: 34128/59290
Iteration: 34129/59290
Iteration: 34130/59290
Iteration: 34131/59290
Iteration: 34132/59290
Iteration: 34133/59290
Iteration: 34134/59290
Iteration: 34135/59290
Iteration: 34136/59290

 58%|█████▊    | 34125/59290 [24:37<21:04, 19.91it/s]

Iteration: 34137/59290
Iteration: 34138/59290
Iteration: 34139/59290
Iteration: 34140/59290
Iteration: 34141/59290
Iteration: 34142/59290
Iteration: 34143/59290
Iteration: 34144/59290
Iteration: 34145/59290
Iteration: 34146/59290
Iteration: 34147/59290
Iteration: 34148/59290
Iteration: 34149/59290
Iteration: 34150/59290
Iteration: 34151/59290
Iteration: 34152/59290
Iteration: 34153/59290
Iteration: 34154/59290
Iteration: 34155/59290
Iteration: 34156/59290
Iteration: 34157/59290
Iteration: 34158/59290
Iteration: 34159/59290
Iteration: 34160/59290

 58%|█████▊    | 34149/59290 [24:38<17:12, 24.35it/s]

Iteration: 34161/59290
Iteration: 34162/59290
Iteration: 34163/59290
Iteration: 34164/59290
Iteration: 34165/59290
Iteration: 34166/59290
Iteration: 34167/59290
Iteration: 34168/59290
Iteration: 34169/59290
Iteration: 34170/59290
Iteration: 34171/59290
Iteration: 34172/59290
Iteration: 34173/59290
Iteration: 34174/59290
Iteration: 34175/59290
Iteration: 34176/59290
Iteration: 34177/59290
Iteration: 34178/59290
Iteration: 34179/59290
Iteration: 34180/59290
Iteration: 34181/59290
Iteration: 34182/59290
Iteration: 34183/59290
Iteration: 34184/59290

 58%|█████▊    | 34173/59290 [24:38<14:07, 29.64it/s]

Iteration: 34185/59290
Iteration: 34186/59290
Iteration: 34187/59290
Iteration: 34188/59290
Iteration: 34189/59290
Iteration: 34190/59290
Iteration: 34191/59290
Iteration: 34192/59290
Iteration: 34193/59290
Iteration: 34194/59290
Iteration: 34195/59290
Iteration: 34196/59290
Iteration: 34197/59290
Iteration: 34198/59290
Iteration: 34199/59290
Iteration: 34200/59290
Iteration: 34201/59290
Iteration: 34202/59290
Iteration: 34203/59290
Iteration: 34204/59290
Iteration: 34205/59290
Iteration: 34206/59290
Iteration: 34207/59290
Iteration: 34208/59290

 58%|█████▊    | 34197/59290 [24:39<11:52, 35.20it/s]

Iteration: 34209/59290
Iteration: 34210/59290
Iteration: 34211/59290
Iteration: 34212/59290
Iteration: 34213/59290
Iteration: 34214/59290
Iteration: 34215/59290
Iteration: 34216/59290
Iteration: 34217/59290
Iteration: 34218/59290
Iteration: 34219/59290
Iteration: 34220/59290
Iteration: 34221/59290
Iteration: 34222/59290
Iteration: 34223/59290
Iteration: 34224/59290
Iteration: 34225/59290
Iteration: 34226/59290
Iteration: 34227/59290
Iteration: 34228/59290
Iteration: 34229/59290
Iteration: 34230/59290
Iteration: 34231/59290
Iteration: 34232/59290

 58%|█████▊    | 34221/59290 [24:40<17:17, 24.16it/s]

Iteration: 34233/59290
Iteration: 34234/59290
Iteration: 34235/59290
Iteration: 34236/59290
Iteration: 34237/59290
Iteration: 34238/59290
Iteration: 34239/59290
Iteration: 34240/59290
Iteration: 34241/59290
Iteration: 34242/59290
Iteration: 34243/59290
Iteration: 34244/59290
Iteration: 34245/59290
Iteration: 34246/59290
Iteration: 34247/59290
Iteration: 34248/59290
Iteration: 34249/59290
Iteration: 34250/59290
Iteration: 34251/59290
Iteration: 34252/59290
Iteration: 34253/59290
Iteration: 34254/59290
Iteration: 34255/59290
Iteration: 34256/59290

 58%|█████▊    | 34245/59290 [24:42<22:25, 18.61it/s]

Iteration: 34257/59290
Iteration: 34258/59290
Iteration: 34259/59290
Iteration: 34260/59290
Iteration: 34261/59290
Iteration: 34262/59290
Iteration: 34263/59290
Iteration: 34264/59290
Iteration: 34265/59290
Iteration: 34266/59290
Iteration: 34267/59290
Iteration: 34268/59290
Iteration: 34269/59290
Iteration: 34270/59290
Iteration: 34271/59290
Iteration: 34272/59290
Iteration: 34273/59290
Iteration: 34274/59290
Iteration: 34275/59290
Iteration: 34276/59290
Iteration: 34277/59290
Iteration: 34278/59290
Iteration: 34279/59290
Iteration: 34280/59290

 58%|█████▊    | 34269/59290 [24:43<18:13, 22.88it/s]

Iteration: 34281/59290
Iteration: 34282/59290
Iteration: 34283/59290
Iteration: 34284/59290
Iteration: 34285/59290
Iteration: 34286/59290
Iteration: 34287/59290
Iteration: 34288/59290
Iteration: 34289/59290
Iteration: 34290/59290
Iteration: 34291/59290
Iteration: 34292/59290
Iteration: 34293/59290
Iteration: 34294/59290
Iteration: 34295/59290
Iteration: 34296/59290
Iteration: 34297/59290
Iteration: 34298/59290
Iteration: 34299/59290
Iteration: 34300/59290
Iteration: 34301/59290
Iteration: 34302/59290
Iteration: 34303/59290
Iteration: 34304/59290

 58%|█████▊    | 34293/59290 [24:43<14:51, 28.05it/s]

Iteration: 34305/59290
Iteration: 34306/59290
Iteration: 34307/59290
Iteration: 34308/59290
Iteration: 34309/59290
Iteration: 34310/59290
Iteration: 34311/59290
Iteration: 34312/59290
Iteration: 34313/59290
Iteration: 34314/59290
Iteration: 34315/59290
Iteration: 34316/59290
Iteration: 34317/59290
Iteration: 34318/59290
Iteration: 34319/59290
Iteration: 34320/59290
Iteration: 34321/59290
Iteration: 34322/59290
Iteration: 34323/59290
Iteration: 34324/59290
Iteration: 34325/59290
Iteration: 34326/59290
Iteration: 34327/59290
Iteration: 34328/59290

 58%|█████▊    | 34317/59290 [24:44<12:22, 33.65it/s]

Iteration: 34329/59290
Iteration: 34330/59290
Iteration: 34331/59290
Iteration: 34332/59290
Iteration: 34333/59290
Iteration: 34334/59290
Iteration: 34335/59290
Iteration: 34336/59290
Iteration: 34337/59290
Iteration: 34338/59290
Iteration: 34339/59290
Iteration: 34340/59290
Iteration: 34341/59290
Iteration: 34342/59290
Iteration: 34343/59290
Iteration: 34344/59290
Iteration: 34345/59290
Iteration: 34346/59290
Iteration: 34347/59290
Iteration: 34348/59290
Iteration: 34349/59290
Iteration: 34350/59290
Iteration: 34351/59290
Iteration: 34352/59290

 58%|█████▊    | 34341/59290 [24:44<10:47, 38.51it/s]

Iteration: 34353/59290
Iteration: 34354/59290
Iteration: 34355/59290
Iteration: 34356/59290
Iteration: 34357/59290
Iteration: 34358/59290
Iteration: 34359/59290
Iteration: 34360/59290
Iteration: 34361/59290
Iteration: 34362/59290
Iteration: 34363/59290
Iteration: 34364/59290
Iteration: 34365/59290
Iteration: 34366/59290
Iteration: 34367/59290
Iteration: 34368/59290
Iteration: 34369/59290
Iteration: 34370/59290
Iteration: 34371/59290
Iteration: 34372/59290
Iteration: 34373/59290
Iteration: 34374/59290
Iteration: 34375/59290
Iteration: 34376/59290

 58%|█████▊    | 34365/59290 [24:45<14:20, 28.98it/s]

Iteration: 34377/59290
Iteration: 34378/59290
Iteration: 34379/59290
Iteration: 34380/59290
Iteration: 34381/59290
Iteration: 34382/59290
Iteration: 34383/59290
Iteration: 34384/59290
Iteration: 34385/59290
Iteration: 34386/59290
Iteration: 34387/59290
Iteration: 34388/59290
Iteration: 34389/59290
Iteration: 34390/59290
Iteration: 34391/59290
Iteration: 34392/59290
Iteration: 34393/59290
Iteration: 34394/59290
Iteration: 34395/59290
Iteration: 34396/59290
Iteration: 34397/59290
Iteration: 34398/59290
Iteration: 34399/59290
Iteration: 34400/59290

 58%|█████▊    | 34389/59290 [24:47<20:12, 20.54it/s]

Iteration: 34401/59290
Iteration: 34402/59290
Iteration: 34403/59290
Iteration: 34404/59290
Iteration: 34405/59290
Iteration: 34406/59290
Iteration: 34407/59290
Iteration: 34408/59290
Iteration: 34409/59290
Iteration: 34410/59290
Iteration: 34411/59290
Iteration: 34412/59290
Iteration: 34413/59290
Iteration: 34414/59290
Iteration: 34415/59290
Iteration: 34416/59290
Iteration: 34417/59290
Iteration: 34418/59290
Iteration: 34419/59290
Iteration: 34420/59290
Iteration: 34421/59290
Iteration: 34422/59290
Iteration: 34423/59290
Iteration: 34424/59290

 58%|█████▊    | 34413/59290 [24:48<16:22, 25.31it/s]

Iteration: 34425/59290
Iteration: 34426/59290
Iteration: 34427/59290
Iteration: 34428/59290
Iteration: 34429/59290
Iteration: 34430/59290
Iteration: 34431/59290
Iteration: 34432/59290
Iteration: 34433/59290
Iteration: 34434/59290
Iteration: 34435/59290
Iteration: 34436/59290
Iteration: 34437/59290
Iteration: 34438/59290
Iteration: 34439/59290
Iteration: 34440/59290
Iteration: 34441/59290
Iteration: 34442/59290
Iteration: 34443/59290
Iteration: 34444/59290
Iteration: 34445/59290
Iteration: 34446/59290
Iteration: 34447/59290
Iteration: 34448/59290

 58%|█████▊    | 34437/59290 [24:48<13:27, 30.78it/s]

Iteration: 34449/59290
Iteration: 34450/59290
Iteration: 34451/59290
Iteration: 34452/59290
Iteration: 34453/59290
Iteration: 34454/59290
Iteration: 34455/59290
Iteration: 34456/59290
Iteration: 34457/59290
Iteration: 34458/59290
Iteration: 34459/59290
Iteration: 34460/59290
Iteration: 34461/59290
Iteration: 34462/59290
Iteration: 34463/59290
Iteration: 34464/59290
Iteration: 34465/59290
Iteration: 34466/59290
Iteration: 34467/59290
Iteration: 34468/59290
Iteration: 34469/59290
Iteration: 34470/59290
Iteration: 34471/59290
Iteration: 34472/59290

 58%|█████▊    | 34461/59290 [24:48<11:28, 36.06it/s]

Iteration: 34473/59290
Iteration: 34474/59290
Iteration: 34475/59290
Iteration: 34476/59290
Iteration: 34477/59290
Iteration: 34478/59290
Iteration: 34479/59290
Iteration: 34480/59290
Iteration: 34481/59290
Iteration: 34482/59290
Iteration: 34483/59290
Iteration: 34484/59290
Iteration: 34485/59290
Iteration: 34486/59290
Iteration: 34487/59290
Iteration: 34488/59290
Iteration: 34489/59290
Iteration: 34490/59290
Iteration: 34491/59290
Iteration: 34492/59290
Iteration: 34493/59290
Iteration: 34494/59290
Iteration: 34495/59290
Iteration: 34496/59290

 58%|█████▊    | 34485/59290 [24:49<09:58, 41.46it/s]

Iteration: 34497/59290
Iteration: 34498/59290
Iteration: 34499/59290
Iteration: 34500/59290
Iteration: 34501/59290
Iteration: 34502/59290
Iteration: 34503/59290
Iteration: 34504/59290
Iteration: 34505/59290
Iteration: 34506/59290
Iteration: 34507/59290
Iteration: 34508/59290
Iteration: 34509/59290
Iteration: 34510/59290
Iteration: 34511/59290
Iteration: 34512/59290
Iteration: 34513/59290
Iteration: 34514/59290
Iteration: 34515/59290
Iteration: 34516/59290
Iteration: 34517/59290
Iteration: 34518/59290
Iteration: 34519/59290
Iteration: 34520/59290

 58%|█████▊    | 34509/59290 [24:49<08:54, 46.36it/s]

Iteration: 34521/59290
Iteration: 34522/59290
Iteration: 34523/59290
Iteration: 34524/59290
Iteration: 34525/59290
Iteration: 34526/59290
Iteration: 34527/59290
Iteration: 34528/59290
Iteration: 34529/59290
Iteration: 34530/59290
Iteration: 34531/59290
Iteration: 34532/59290
Iteration: 34533/59290
Iteration: 34534/59290
Iteration: 34535/59290
Iteration: 34536/59290
Iteration: 34537/59290
Iteration: 34538/59290
Iteration: 34539/59290
Iteration: 34540/59290
Iteration: 34541/59290
Iteration: 34542/59290
Iteration: 34543/59290
Iteration: 34544/59290

 58%|█████▊    | 34533/59290 [24:50<08:12, 50.28it/s]

Iteration: 34545/59290
Iteration: 34546/59290
Iteration: 34547/59290
Iteration: 34548/59290
Iteration: 34549/59290
Iteration: 34550/59290
Iteration: 34551/59290
Iteration: 34552/59290
Iteration: 34553/59290
Iteration: 34554/59290
Iteration: 34555/59290
Iteration: 34556/59290
Iteration: 34557/59290
Iteration: 34558/59290
Iteration: 34559/59290
Iteration: 34560/59290
Iteration: 34561/59290
Iteration: 34562/59290
Iteration: 34563/59290
Iteration: 34564/59290
Iteration: 34565/59290
Iteration: 34566/59290
Iteration: 34567/59290
Iteration: 34568/59290

 58%|█████▊    | 34557/59290 [24:50<07:44, 53.24it/s]

Iteration: 34569/59290
Iteration: 34570/59290
Iteration: 34571/59290
Iteration: 34572/59290
Iteration: 34573/59290
Iteration: 34574/59290
Iteration: 34575/59290
Iteration: 34576/59290
Iteration: 34577/59290
Iteration: 34578/59290
Iteration: 34579/59290
Iteration: 34580/59290
Iteration: 34581/59290
Iteration: 34582/59290
Iteration: 34583/59290
Iteration: 34584/59290
Iteration: 34585/59290
Iteration: 34586/59290
Iteration: 34587/59290
Iteration: 34588/59290
Iteration: 34589/59290
Iteration: 34590/59290
Iteration: 34591/59290
Iteration: 34592/59290

 58%|█████▊    | 34581/59290 [24:50<07:20, 56.05it/s]

Iteration: 34593/59290
Iteration: 34594/59290
Iteration: 34595/59290
Iteration: 34596/59290
Iteration: 34597/59290
Iteration: 34598/59290
Iteration: 34599/59290
Iteration: 34600/59290
Iteration: 34601/59290
Iteration: 34602/59290
Iteration: 34603/59290
Iteration: 34604/59290
Iteration: 34605/59290
Iteration: 34606/59290
Iteration: 34607/59290
Iteration: 34608/59290
Iteration: 34609/59290
Iteration: 34610/59290
Iteration: 34611/59290
Iteration: 34612/59290
Iteration: 34613/59290
Iteration: 34614/59290
Iteration: 34615/59290
Iteration: 34616/59290

 58%|█████▊    | 34605/59290 [24:52<13:43, 29.97it/s]

Iteration: 34617/59290
Iteration: 34618/59290
Iteration: 34619/59290
Iteration: 34620/59290
Iteration: 34621/59290
Iteration: 34622/59290
Iteration: 34623/59290
Iteration: 34624/59290
Iteration: 34625/59290
Iteration: 34626/59290
Iteration: 34627/59290
Iteration: 34628/59290
Iteration: 34629/59290
Iteration: 34630/59290
Iteration: 34631/59290
Iteration: 34632/59290
Iteration: 34633/59290
Iteration: 34634/59290
Iteration: 34635/59290
Iteration: 34636/59290
Iteration: 34637/59290
Iteration: 34638/59290
Iteration: 34639/59290
Iteration: 34640/59290

 58%|█████▊    | 34629/59290 [24:54<19:11, 21.42it/s]

Iteration: 34641/59290
Iteration: 34642/59290
Iteration: 34643/59290
Iteration: 34644/59290
Iteration: 34645/59290
Iteration: 34646/59290
Iteration: 34647/59290
Iteration: 34648/59290
Iteration: 34649/59290
Iteration: 34650/59290
Iteration: 34651/59290
Iteration: 34652/59290
Iteration: 34653/59290
Iteration: 34654/59290
Iteration: 34655/59290
Iteration: 34656/59290
Iteration: 34657/59290
Iteration: 34658/59290
Iteration: 34659/59290
Iteration: 34660/59290
Iteration: 34661/59290
Iteration: 34662/59290
Iteration: 34663/59290
Iteration: 34664/59290

 58%|█████▊    | 34653/59290 [24:54<15:30, 26.49it/s]

Iteration: 34665/59290
Iteration: 34666/59290
Iteration: 34667/59290
Iteration: 34668/59290
Iteration: 34669/59290
Iteration: 34670/59290
Iteration: 34671/59290
Iteration: 34672/59290
Iteration: 34673/59290
Iteration: 34674/59290
Iteration: 34675/59290
Iteration: 34676/59290
Iteration: 34677/59290
Iteration: 34678/59290
Iteration: 34679/59290
Iteration: 34680/59290
Iteration: 34681/59290
Iteration: 34682/59290
Iteration: 34683/59290
Iteration: 34684/59290
Iteration: 34685/59290
Iteration: 34686/59290
Iteration: 34687/59290
Iteration: 34688/59290

 58%|█████▊    | 34677/59290 [24:55<13:08, 31.21it/s]

Iteration: 34689/59290
Iteration: 34690/59290
Iteration: 34691/59290
Iteration: 34692/59290
Iteration: 34693/59290
Iteration: 34694/59290
Iteration: 34695/59290
Iteration: 34696/59290
Iteration: 34697/59290
Iteration: 34698/59290
Iteration: 34699/59290
Iteration: 34700/59290
Iteration: 34701/59290
Iteration: 34702/59290
Iteration: 34703/59290
Iteration: 34704/59290
Iteration: 34705/59290
Iteration: 34706/59290
Iteration: 34707/59290
Iteration: 34708/59290
Iteration: 34709/59290
Iteration: 34710/59290
Iteration: 34711/59290
Iteration: 34712/59290

 59%|█████▊    | 34701/59290 [24:55<11:12, 36.57it/s]

Iteration: 34713/59290
Iteration: 34714/59290
Iteration: 34715/59290
Iteration: 34716/59290
Iteration: 34717/59290
Iteration: 34718/59290
Iteration: 34719/59290
Iteration: 34720/59290
Iteration: 34721/59290
Iteration: 34722/59290
Iteration: 34723/59290
Iteration: 34724/59290
Iteration: 34725/59290
Iteration: 34726/59290
Iteration: 34727/59290
Iteration: 34728/59290
Iteration: 34729/59290
Iteration: 34730/59290
Iteration: 34731/59290
Iteration: 34732/59290
Iteration: 34733/59290
Iteration: 34734/59290
Iteration: 34735/59290
Iteration: 34736/59290

 59%|█████▊    | 34725/59290 [24:56<09:46, 41.87it/s]

Iteration: 34737/59290
Iteration: 34738/59290
Iteration: 34739/59290
Iteration: 34740/59290
Iteration: 34741/59290
Iteration: 34742/59290
Iteration: 34743/59290
Iteration: 34744/59290
Iteration: 34745/59290
Iteration: 34746/59290
Iteration: 34747/59290
Iteration: 34748/59290
Iteration: 34749/59290
Iteration: 34750/59290
Iteration: 34751/59290
Iteration: 34752/59290
Iteration: 34753/59290
Iteration: 34754/59290
Iteration: 34755/59290
Iteration: 34756/59290
Iteration: 34757/59290
Iteration: 34758/59290
Iteration: 34759/59290
Iteration: 34760/59290

 59%|█████▊    | 34749/59290 [24:56<08:52, 46.12it/s]

Iteration: 34761/59290
Iteration: 34762/59290
Iteration: 34763/59290
Iteration: 34764/59290
Iteration: 34765/59290
Iteration: 34766/59290
Iteration: 34767/59290
Iteration: 34768/59290
Iteration: 34769/59290
Iteration: 34770/59290
Iteration: 34771/59290
Iteration: 34772/59290
Iteration: 34773/59290
Iteration: 34774/59290
Iteration: 34775/59290
Iteration: 34776/59290
Iteration: 34777/59290
Iteration: 34778/59290
Iteration: 34779/59290
Iteration: 34780/59290
Iteration: 34781/59290
Iteration: 34782/59290
Iteration: 34783/59290
Iteration: 34784/59290

 59%|█████▊    | 34773/59290 [24:56<08:07, 50.29it/s]

Iteration: 34785/59290
Iteration: 34786/59290
Iteration: 34787/59290
Iteration: 34788/59290
Iteration: 34789/59290
Iteration: 34790/59290
Iteration: 34791/59290
Iteration: 34792/59290
Iteration: 34793/59290
Iteration: 34794/59290
Iteration: 34795/59290
Iteration: 34796/59290
Iteration: 34797/59290
Iteration: 34798/59290
Iteration: 34799/59290
Iteration: 34800/59290
Iteration: 34801/59290
Iteration: 34802/59290
Iteration: 34803/59290
Iteration: 34804/59290
Iteration: 34805/59290
Iteration: 34806/59290
Iteration: 34807/59290
Iteration: 34808/59290

 59%|█████▊    | 34797/59290 [24:57<07:36, 53.62it/s]

Iteration: 34809/59290
Iteration: 34810/59290
Iteration: 34811/59290
Iteration: 34812/59290
Iteration: 34813/59290
Iteration: 34814/59290
Iteration: 34815/59290
Iteration: 34816/59290
Iteration: 34817/59290
Iteration: 34818/59290
Iteration: 34819/59290
Iteration: 34820/59290
Iteration: 34821/59290
Iteration: 34822/59290
Iteration: 34823/59290
Iteration: 34824/59290
Iteration: 34825/59290
Iteration: 34826/59290
Iteration: 34827/59290
Iteration: 34828/59290
Iteration: 34829/59290
Iteration: 34830/59290
Iteration: 34831/59290
Iteration: 34832/59290

 59%|█████▊    | 34821/59290 [24:57<07:14, 56.28it/s]

Iteration: 34833/59290
Iteration: 34834/59290
Iteration: 34835/59290
Iteration: 34836/59290
Iteration: 34837/59290
Iteration: 34838/59290
Iteration: 34839/59290
Iteration: 34840/59290
Iteration: 34841/59290
Iteration: 34842/59290
Iteration: 34843/59290
Iteration: 34844/59290
Iteration: 34845/59290
Iteration: 34846/59290
Iteration: 34847/59290
Iteration: 34848/59290
Iteration: 34849/59290
Iteration: 34850/59290
Iteration: 34851/59290
Iteration: 34852/59290
Iteration: 34853/59290
Iteration: 34854/59290
Iteration: 34855/59290
Iteration: 34856/59290

 59%|█████▉    | 34845/59290 [24:57<07:05, 57.47it/s]

Iteration: 34857/59290
Iteration: 34858/59290
Iteration: 34859/59290
Iteration: 34860/59290
Iteration: 34861/59290
Iteration: 34862/59290
Iteration: 34863/59290
Iteration: 34864/59290
Iteration: 34865/59290
Iteration: 34866/59290
Iteration: 34867/59290
Iteration: 34868/59290
Iteration: 34869/59290
Iteration: 34870/59290
Iteration: 34871/59290
Iteration: 34872/59290
Iteration: 34873/59290
Iteration: 34874/59290
Iteration: 34875/59290
Iteration: 34876/59290
Iteration: 34877/59290
Iteration: 34878/59290
Iteration: 34879/59290
Iteration: 34880/59290

 59%|█████▉    | 34869/59290 [24:58<06:52, 59.15it/s]

Iteration: 34881/59290
Iteration: 34882/59290
Iteration: 34883/59290
Iteration: 34884/59290
Iteration: 34885/59290
Iteration: 34886/59290
Iteration: 34887/59290
Iteration: 34888/59290
Iteration: 34889/59290
Iteration: 34890/59290
Iteration: 34891/59290
Iteration: 34892/59290
Iteration: 34893/59290
Iteration: 34894/59290
Iteration: 34895/59290
Iteration: 34896/59290
Iteration: 34897/59290
Iteration: 34898/59290
Iteration: 34899/59290
Iteration: 34900/59290
Iteration: 34901/59290
Iteration: 34902/59290
Iteration: 34903/59290
Iteration: 34904/59290

 59%|█████▉    | 34893/59290 [24:58<06:44, 60.37it/s]

Iteration: 34905/59290
Iteration: 34906/59290
Iteration: 34907/59290
Iteration: 34908/59290
Iteration: 34909/59290
Iteration: 34910/59290
Iteration: 34911/59290
Iteration: 34912/59290
Iteration: 34913/59290
Iteration: 34914/59290
Iteration: 34915/59290
Iteration: 34916/59290
Iteration: 34917/59290
Iteration: 34918/59290
Iteration: 34919/59290
Iteration: 34920/59290
Iteration: 34921/59290
Iteration: 34922/59290
Iteration: 34923/59290
Iteration: 34924/59290
Iteration: 34925/59290
Iteration: 34926/59290
Iteration: 34927/59290
Iteration: 34928/59290

 59%|█████▉    | 34917/59290 [24:59<06:36, 61.44it/s]

Iteration: 34929/59290
Iteration: 34930/59290
Iteration: 34931/59290
Iteration: 34932/59290
Iteration: 34933/59290
Iteration: 34934/59290
Iteration: 34935/59290
Iteration: 34936/59290
Iteration: 34937/59290
Iteration: 34938/59290
Iteration: 34939/59290
Iteration: 34940/59290
Iteration: 34941/59290
Iteration: 34942/59290
Iteration: 34943/59290
Iteration: 34944/59290
Iteration: 34945/59290
Iteration: 34946/59290
Iteration: 34947/59290
Iteration: 34948/59290
Iteration: 34949/59290
Iteration: 34950/59290
Iteration: 34951/59290
Iteration: 34952/59290

 59%|█████▉    | 34941/59290 [25:00<11:41, 34.71it/s]

Iteration: 34953/59290
Iteration: 34954/59290
Iteration: 34955/59290
Iteration: 34956/59290
Iteration: 34957/59290
Iteration: 34958/59290
Iteration: 34959/59290
Iteration: 34960/59290
Iteration: 34961/59290
Iteration: 34962/59290
Iteration: 34963/59290
Iteration: 34964/59290
Iteration: 34965/59290
Iteration: 34966/59290
Iteration: 34967/59290
Iteration: 34968/59290
Iteration: 34969/59290
Iteration: 34970/59290
Iteration: 34971/59290
Iteration: 34972/59290
Iteration: 34973/59290
Iteration: 34974/59290
Iteration: 34975/59290
Iteration: 34976/59290

 59%|█████▉    | 34965/59290 [25:02<17:37, 23.00it/s]

Iteration: 34977/59290
Iteration: 34978/59290
Iteration: 34979/59290
Iteration: 34980/59290
Iteration: 34981/59290
Iteration: 34982/59290
Iteration: 34983/59290
Iteration: 34984/59290
Iteration: 34985/59290
Iteration: 34986/59290
Iteration: 34987/59290
Iteration: 34988/59290
Iteration: 34989/59290
Iteration: 34990/59290
Iteration: 34991/59290
Iteration: 34992/59290
Iteration: 34993/59290
Iteration: 34994/59290
Iteration: 34995/59290
Iteration: 34996/59290
Iteration: 34997/59290
Iteration: 34998/59290
Iteration: 34999/59290
Iteration: 35000/59290

 59%|█████▉    | 34989/59290 [25:02<14:41, 27.58it/s]

Iteration: 35001/59290
Iteration: 35002/59290
Iteration: 35003/59290
Iteration: 35004/59290
Iteration: 35005/59290
Iteration: 35006/59290
Iteration: 35007/59290
Iteration: 35008/59290
Iteration: 35009/59290
Iteration: 35010/59290
Iteration: 35011/59290
Iteration: 35012/59290
Iteration: 35013/59290
Iteration: 35014/59290
Iteration: 35015/59290
Iteration: 35016/59290
Iteration: 35017/59290
Iteration: 35018/59290
Iteration: 35019/59290
Iteration: 35020/59290
Iteration: 35021/59290
Iteration: 35022/59290
Iteration: 35023/59290
Iteration: 35024/59290

 59%|█████▉    | 35013/59290 [25:03<12:10, 33.25it/s]

Iteration: 35025/59290
Iteration: 35026/59290
Iteration: 35027/59290
Iteration: 35028/59290
Iteration: 35029/59290
Iteration: 35030/59290
Iteration: 35031/59290
Iteration: 35032/59290
Iteration: 35033/59290
Iteration: 35034/59290
Iteration: 35035/59290
Iteration: 35036/59290
Iteration: 35037/59290
Iteration: 35038/59290
Iteration: 35039/59290
Iteration: 35040/59290
Iteration: 35041/59290
Iteration: 35042/59290
Iteration: 35043/59290
Iteration: 35044/59290
Iteration: 35045/59290
Iteration: 35046/59290
Iteration: 35048/59290

 59%|█████▉    | 35036/59290 [25:03<10:48, 37.39it/s]

Iteration: 35049/59290
Iteration: 35050/59290
Iteration: 35051/59290
Iteration: 35052/59290
Iteration: 35053/59290
Iteration: 35054/59290
Iteration: 35055/59290
Iteration: 35056/59290

 59%|█████▉    | 35044/59290 [25:04<11:52, 34.03it/s]

Iteration: 35057/59290
Iteration: 35058/59290
Iteration: 35059/59290
Iteration: 35060/59290
Iteration: 35061/59290
Iteration: 35062/59290
Iteration: 35063/59290
Iteration: 35064/59290
Iteration: 35065/59290
Iteration: 35066/59290
Iteration: 35067/59290
Iteration: 35068/59290
Iteration: 35069/59290
Iteration: 35070/59290
Iteration: 35071/59290
Iteration: 35072/59290
Iteration: 35073/59290
Iteration: 35074/59290
Iteration: 35075/59290
Iteration: 35076/59290
Iteration: 35077/59290
Iteration: 35078/59290
Iteration: 35079/59290
Iteration: 35080/59290

 59%|█████▉    | 35068/59290 [25:04<09:58, 40.44it/s]

Iteration: 35081/59290
Iteration: 35082/59290
Iteration: 35083/59290
Iteration: 35084/59290
Iteration: 35085/59290
Iteration: 35086/59290
Iteration: 35087/59290
Iteration: 35088/59290
Iteration: 35089/59290
Iteration: 35090/59290
Iteration: 35091/59290
Iteration: 35092/59290
Iteration: 35093/59290
Iteration: 35094/59290
Iteration: 35095/59290
Iteration: 35096/59290
Iteration: 35097/59290
Iteration: 35098/59290
Iteration: 35099/59290
Iteration: 35100/59290
Iteration: 35101/59290
Iteration: 35102/59290
Iteration: 35103/59290
Iteration: 35104/59290

 59%|█████▉    | 35092/59290 [25:05<15:16, 26.39it/s]

Iteration: 35105/59290
Iteration: 35106/59290
Iteration: 35107/59290
Iteration: 35108/59290
Iteration: 35109/59290
Iteration: 35110/59290
Iteration: 35111/59290
Iteration: 35112/59290
Iteration: 35113/59290
Iteration: 35114/59290
Iteration: 35115/59290
Iteration: 35116/59290
Iteration: 35117/59290
Iteration: 35118/59290
Iteration: 35119/59290
Iteration: 35120/59290
Iteration: 35121/59290
Iteration: 35122/59290
Iteration: 35123/59290
Iteration: 35124/59290
Iteration: 35125/59290
Iteration: 35126/59290
Iteration: 35127/59290
Iteration: 35128/59290

 59%|█████▉    | 35116/59290 [25:07<20:49, 19.35it/s]

Iteration: 35129/59290
Iteration: 35130/59290
Iteration: 35131/59290
Iteration: 35132/59290
Iteration: 35133/59290
Iteration: 35134/59290
Iteration: 35135/59290
Iteration: 35136/59290
Iteration: 35137/59290
Iteration: 35138/59290
Iteration: 35139/59290
Iteration: 35140/59290
Iteration: 35141/59290
Iteration: 35142/59290
Iteration: 35143/59290
Iteration: 35144/59290
Iteration: 35145/59290
Iteration: 35146/59290
Iteration: 35147/59290
Iteration: 35148/59290
Iteration: 35149/59290
Iteration: 35150/59290
Iteration: 35151/59290
Iteration: 35152/59290

 59%|█████▉    | 35140/59290 [25:08<16:14, 24.79it/s]

Iteration: 35153/59290
Iteration: 35154/59290
Iteration: 35155/59290
Iteration: 35156/59290
Iteration: 35157/59290
Iteration: 35158/59290
Iteration: 35159/59290
Iteration: 35160/59290
Iteration: 35161/59290
Iteration: 35162/59290
Iteration: 35163/59290
Iteration: 35164/59290
Iteration: 35165/59290
Iteration: 35166/59290
Iteration: 35167/59290
Iteration: 35168/59290
Iteration: 35169/59290
Iteration: 35170/59290
Iteration: 35171/59290
Iteration: 35172/59290
Iteration: 35173/59290
Iteration: 35174/59290
Iteration: 35175/59290
Iteration: 35176/59290

 59%|█████▉    | 35164/59290 [25:08<13:27, 29.89it/s]

Iteration: 35177/59290
Iteration: 35178/59290
Iteration: 35179/59290
Iteration: 35180/59290
Iteration: 35181/59290
Iteration: 35182/59290
Iteration: 35183/59290
Iteration: 35184/59290
Iteration: 35185/59290
Iteration: 35186/59290
Iteration: 35187/59290
Iteration: 35188/59290
Iteration: 35189/59290
Iteration: 35190/59290
Iteration: 35191/59290
Iteration: 35192/59290
Iteration: 35193/59290
Iteration: 35194/59290
Iteration: 35195/59290
Iteration: 35196/59290
Iteration: 35197/59290
Iteration: 35198/59290
Iteration: 35199/59290
Iteration: 35200/59290

 59%|█████▉    | 35188/59290 [25:09<11:14, 35.71it/s]

Iteration: 35201/59290
Iteration: 35202/59290
Iteration: 35203/59290
Iteration: 35204/59290
Iteration: 35205/59290
Iteration: 35206/59290
Iteration: 35207/59290
Iteration: 35208/59290
Iteration: 35209/59290
Iteration: 35210/59290
Iteration: 35211/59290
Iteration: 35212/59290
Iteration: 35213/59290
Iteration: 35214/59290
Iteration: 35215/59290
Iteration: 35216/59290
Iteration: 35217/59290
Iteration: 35218/59290
Iteration: 35219/59290
Iteration: 35220/59290
Iteration: 35221/59290
Iteration: 35222/59290
Iteration: 35223/59290
Iteration: 35224/59290

 59%|█████▉    | 35212/59290 [25:09<09:48, 40.89it/s]

Iteration: 35225/59290
Iteration: 35226/59290
Iteration: 35227/59290
Iteration: 35228/59290
Iteration: 35229/59290
Iteration: 35230/59290
Iteration: 35231/59290
Iteration: 35232/59290
Iteration: 35233/59290
Iteration: 35234/59290
Iteration: 35235/59290
Iteration: 35236/59290
Iteration: 35237/59290
Iteration: 35238/59290
Iteration: 35239/59290
Iteration: 35240/59290
Iteration: 35241/59290
Iteration: 35242/59290
Iteration: 35243/59290
Iteration: 35244/59290
Iteration: 35245/59290
Iteration: 35246/59290
Iteration: 35247/59290
Iteration: 35248/59290

 59%|█████▉    | 35236/59290 [25:11<15:17, 26.23it/s]

Iteration: 35249/59290
Iteration: 35250/59290
Iteration: 35251/59290
Iteration: 35252/59290
Iteration: 35253/59290
Iteration: 35254/59290
Iteration: 35255/59290
Iteration: 35256/59290
Iteration: 35257/59290
Iteration: 35258/59290
Iteration: 35259/59290
Iteration: 35260/59290
Iteration: 35261/59290
Iteration: 35262/59290
Iteration: 35263/59290
Iteration: 35264/59290
Iteration: 35265/59290
Iteration: 35266/59290
Iteration: 35267/59290
Iteration: 35268/59290
Iteration: 35269/59290
Iteration: 35270/59290
Iteration: 35271/59290
Iteration: 35272/59290

 59%|█████▉    | 35260/59290 [25:12<20:06, 19.92it/s]

Iteration: 35273/59290
Iteration: 35274/59290
Iteration: 35275/59290
Iteration: 35276/59290
Iteration: 35277/59290
Iteration: 35278/59290
Iteration: 35279/59290
Iteration: 35280/59290
Iteration: 35281/59290
Iteration: 35282/59290
Iteration: 35283/59290
Iteration: 35284/59290
Iteration: 35285/59290
Iteration: 35286/59290
Iteration: 35287/59290
Iteration: 35288/59290
Iteration: 35289/59290
Iteration: 35290/59290
Iteration: 35291/59290
Iteration: 35292/59290
Iteration: 35293/59290
Iteration: 35294/59290
Iteration: 35295/59290
Iteration: 35296/59290

 60%|█████▉    | 35284/59290 [25:13<16:05, 24.85it/s]

Iteration: 35297/59290
Iteration: 35298/59290
Iteration: 35299/59290
Iteration: 35300/59290
Iteration: 35301/59290
Iteration: 35302/59290
Iteration: 35303/59290
Iteration: 35304/59290
Iteration: 35305/59290
Iteration: 35306/59290
Iteration: 35307/59290
Iteration: 35308/59290
Iteration: 35309/59290
Iteration: 35310/59290
Iteration: 35311/59290
Iteration: 35312/59290
Iteration: 35313/59290
Iteration: 35314/59290
Iteration: 35315/59290
Iteration: 35316/59290
Iteration: 35317/59290
Iteration: 35318/59290
Iteration: 35319/59290
Iteration: 35320/59290

 60%|█████▉    | 35308/59290 [25:13<13:09, 30.36it/s]

Iteration: 35321/59290
Iteration: 35322/59290
Iteration: 35323/59290
Iteration: 35324/59290
Iteration: 35325/59290
Iteration: 35326/59290
Iteration: 35327/59290
Iteration: 35328/59290
Iteration: 35329/59290
Iteration: 35330/59290
Iteration: 35331/59290
Iteration: 35332/59290
Iteration: 35333/59290
Iteration: 35334/59290
Iteration: 35335/59290
Iteration: 35336/59290
Iteration: 35337/59290
Iteration: 35338/59290
Iteration: 35339/59290
Iteration: 35340/59290
Iteration: 35341/59290
Iteration: 35342/59290
Iteration: 35343/59290
Iteration: 35344/59290

 60%|█████▉    | 35332/59290 [25:14<11:05, 36.00it/s]

Iteration: 35345/59290
Iteration: 35346/59290
Iteration: 35347/59290
Iteration: 35348/59290
Iteration: 35349/59290
Iteration: 35350/59290
Iteration: 35351/59290
Iteration: 35352/59290
Iteration: 35353/59290
Iteration: 35354/59290
Iteration: 35355/59290
Iteration: 35356/59290
Iteration: 35357/59290
Iteration: 35358/59290
Iteration: 35359/59290
Iteration: 35360/59290
Iteration: 35361/59290
Iteration: 35362/59290
Iteration: 35363/59290
Iteration: 35364/59290
Iteration: 35365/59290
Iteration: 35366/59290
Iteration: 35367/59290
Iteration: 35368/59290

 60%|█████▉    | 35356/59290 [25:14<09:39, 41.30it/s]

Iteration: 35369/59290
Iteration: 35370/59290
Iteration: 35371/59290
Iteration: 35372/59290
Iteration: 35373/59290
Iteration: 35374/59290
Iteration: 35375/59290
Iteration: 35376/59290
Iteration: 35377/59290
Iteration: 35378/59290
Iteration: 35379/59290
Iteration: 35380/59290
Iteration: 35381/59290
Iteration: 35382/59290
Iteration: 35383/59290
Iteration: 35384/59290
Iteration: 35385/59290
Iteration: 35386/59290
Iteration: 35387/59290
Iteration: 35388/59290
Iteration: 35389/59290
Iteration: 35390/59290
Iteration: 35391/59290
Iteration: 35392/59290

 60%|█████▉    | 35380/59290 [25:15<13:41, 29.12it/s]

Iteration: 35393/59290
Iteration: 35394/59290
Iteration: 35395/59290
Iteration: 35396/59290
Iteration: 35397/59290
Iteration: 35398/59290
Iteration: 35399/59290
Iteration: 35400/59290
Iteration: 35401/59290
Iteration: 35402/59290
Iteration: 35403/59290
Iteration: 35404/59290
Iteration: 35405/59290
Iteration: 35406/59290
Iteration: 35407/59290
Iteration: 35408/59290
Iteration: 35409/59290
Iteration: 35410/59290
Iteration: 35411/59290
Iteration: 35412/59290
Iteration: 35413/59290
Iteration: 35414/59290
Iteration: 35415/59290
Iteration: 35416/59290

 60%|█████▉    | 35404/59290 [25:17<19:23, 20.53it/s]

Iteration: 35417/59290
Iteration: 35418/59290
Iteration: 35419/59290
Iteration: 35420/59290
Iteration: 35421/59290
Iteration: 35422/59290
Iteration: 35423/59290
Iteration: 35424/59290
Iteration: 35425/59290
Iteration: 35426/59290
Iteration: 35427/59290
Iteration: 35428/59290
Iteration: 35429/59290
Iteration: 35430/59290
Iteration: 35431/59290
Iteration: 35432/59290
Iteration: 35433/59290
Iteration: 35434/59290
Iteration: 35435/59290
Iteration: 35436/59290
Iteration: 35437/59290
Iteration: 35438/59290
Iteration: 35439/59290
Iteration: 35440/59290

 60%|█████▉    | 35428/59290 [25:18<15:52, 25.05it/s]

Iteration: 35441/59290
Iteration: 35442/59290
Iteration: 35443/59290
Iteration: 35444/59290
Iteration: 35445/59290
Iteration: 35446/59290
Iteration: 35447/59290
Iteration: 35448/59290
Iteration: 35449/59290
Iteration: 35450/59290
Iteration: 35451/59290
Iteration: 35452/59290
Iteration: 35453/59290
Iteration: 35454/59290
Iteration: 35455/59290
Iteration: 35456/59290
Iteration: 35457/59290
Iteration: 35458/59290
Iteration: 35459/59290
Iteration: 35460/59290
Iteration: 35461/59290
Iteration: 35462/59290
Iteration: 35463/59290
Iteration: 35464/59290

 60%|█████▉    | 35452/59290 [25:18<12:59, 30.59it/s]

Iteration: 35465/59290
Iteration: 35466/59290
Iteration: 35467/59290
Iteration: 35468/59290
Iteration: 35469/59290
Iteration: 35470/59290
Iteration: 35471/59290
Iteration: 35472/59290
Iteration: 35473/59290
Iteration: 35474/59290
Iteration: 35475/59290
Iteration: 35476/59290
Iteration: 35477/59290
Iteration: 35478/59290
Iteration: 35479/59290
Iteration: 35480/59290
Iteration: 35481/59290
Iteration: 35482/59290
Iteration: 35483/59290
Iteration: 35484/59290
Iteration: 35485/59290
Iteration: 35486/59290
Iteration: 35487/59290
Iteration: 35488/59290

 60%|█████▉    | 35476/59290 [25:19<10:56, 36.30it/s]

Iteration: 35489/59290
Iteration: 35490/59290
Iteration: 35491/59290
Iteration: 35492/59290
Iteration: 35493/59290
Iteration: 35494/59290
Iteration: 35495/59290
Iteration: 35496/59290
Iteration: 35497/59290
Iteration: 35498/59290
Iteration: 35499/59290
Iteration: 35500/59290
Iteration: 35501/59290
Iteration: 35502/59290
Iteration: 35503/59290
Iteration: 35504/59290
Iteration: 35505/59290
Iteration: 35506/59290
Iteration: 35507/59290
Iteration: 35508/59290
Iteration: 35509/59290
Iteration: 35510/59290
Iteration: 35511/59290
Iteration: 35512/59290

 60%|█████▉    | 35500/59290 [25:19<09:33, 41.52it/s]

Iteration: 35513/59290
Iteration: 35514/59290
Iteration: 35515/59290
Iteration: 35516/59290
Iteration: 35517/59290
Iteration: 35518/59290
Iteration: 35519/59290
Iteration: 35520/59290
Iteration: 35521/59290
Iteration: 35522/59290
Iteration: 35523/59290
Iteration: 35524/59290
Iteration: 35525/59290
Iteration: 35526/59290
Iteration: 35527/59290
Iteration: 35528/59290
Iteration: 35529/59290
Iteration: 35530/59290
Iteration: 35531/59290
Iteration: 35532/59290
Iteration: 35533/59290
Iteration: 35534/59290
Iteration: 35535/59290
Iteration: 35536/59290

 60%|█████▉    | 35524/59290 [25:19<08:36, 46.00it/s]

Iteration: 35537/59290
Iteration: 35538/59290
Iteration: 35539/59290
Iteration: 35540/59290
Iteration: 35541/59290
Iteration: 35542/59290
Iteration: 35543/59290
Iteration: 35544/59290
Iteration: 35545/59290
Iteration: 35546/59290
Iteration: 35547/59290
Iteration: 35548/59290
Iteration: 35549/59290
Iteration: 35550/59290
Iteration: 35551/59290
Iteration: 35552/59290
Iteration: 35553/59290
Iteration: 35554/59290
Iteration: 35555/59290
Iteration: 35556/59290
Iteration: 35557/59290
Iteration: 35558/59290
Iteration: 35559/59290
Iteration: 35560/59290

 60%|█████▉    | 35548/59290 [25:20<07:54, 50.07it/s]

Iteration: 35561/59290
Iteration: 35562/59290
Iteration: 35563/59290
Iteration: 35564/59290
Iteration: 35565/59290
Iteration: 35566/59290
Iteration: 35567/59290
Iteration: 35568/59290
Iteration: 35569/59290
Iteration: 35570/59290
Iteration: 35571/59290
Iteration: 35572/59290
Iteration: 35573/59290
Iteration: 35574/59290
Iteration: 35575/59290
Iteration: 35576/59290
Iteration: 35577/59290
Iteration: 35578/59290
Iteration: 35579/59290
Iteration: 35580/59290
Iteration: 35581/59290
Iteration: 35582/59290
Iteration: 35583/59290
Iteration: 35584/59290

 60%|█████▉    | 35572/59290 [25:20<07:21, 53.68it/s]

Iteration: 35585/59290
Iteration: 35586/59290
Iteration: 35587/59290
Iteration: 35588/59290
Iteration: 35589/59290
Iteration: 35590/59290
Iteration: 35591/59290
Iteration: 35592/59290
Iteration: 35593/59290
Iteration: 35594/59290
Iteration: 35595/59290
Iteration: 35596/59290
Iteration: 35597/59290
Iteration: 35598/59290
Iteration: 35599/59290
Iteration: 35600/59290
Iteration: 35601/59290
Iteration: 35602/59290
Iteration: 35603/59290
Iteration: 35604/59290
Iteration: 35605/59290
Iteration: 35606/59290
Iteration: 35607/59290
Iteration: 35608/59290

 60%|██████    | 35596/59290 [25:21<07:04, 55.78it/s]

Iteration: 35609/59290
Iteration: 35610/59290
Iteration: 35611/59290
Iteration: 35612/59290
Iteration: 35613/59290
Iteration: 35614/59290
Iteration: 35615/59290
Iteration: 35616/59290
Iteration: 35617/59290
Iteration: 35618/59290
Iteration: 35619/59290
Iteration: 35620/59290
Iteration: 35621/59290
Iteration: 35622/59290
Iteration: 35623/59290
Iteration: 35624/59290
Iteration: 35625/59290
Iteration: 35626/59290
Iteration: 35627/59290
Iteration: 35628/59290
Iteration: 35629/59290
Iteration: 35630/59290
Iteration: 35631/59290
Iteration: 35632/59290

 60%|██████    | 35620/59290 [25:22<12:21, 31.91it/s]

Iteration: 35633/59290
Iteration: 35634/59290
Iteration: 35635/59290
Iteration: 35636/59290
Iteration: 35637/59290
Iteration: 35638/59290
Iteration: 35639/59290
Iteration: 35640/59290
Iteration: 35641/59290
Iteration: 35642/59290
Iteration: 35643/59290
Iteration: 35644/59290
Iteration: 35645/59290
Iteration: 35646/59290
Iteration: 35647/59290
Iteration: 35648/59290
Iteration: 35649/59290
Iteration: 35650/59290
Iteration: 35651/59290
Iteration: 35652/59290
Iteration: 35653/59290
Iteration: 35654/59290
Iteration: 35655/59290
Iteration: 35656/59290

 60%|██████    | 35644/59290 [25:24<18:31, 21.28it/s]

Iteration: 35657/59290
Iteration: 35658/59290
Iteration: 35659/59290
Iteration: 35660/59290
Iteration: 35661/59290
Iteration: 35662/59290
Iteration: 35663/59290
Iteration: 35664/59290
Iteration: 35665/59290
Iteration: 35666/59290
Iteration: 35667/59290
Iteration: 35668/59290
Iteration: 35669/59290
Iteration: 35670/59290
Iteration: 35671/59290
Iteration: 35672/59290
Iteration: 35673/59290
Iteration: 35674/59290
Iteration: 35675/59290
Iteration: 35676/59290
Iteration: 35677/59290
Iteration: 35678/59290
Iteration: 35679/59290
Iteration: 35680/59290

 60%|██████    | 35668/59290 [25:25<15:08, 26.00it/s]

Iteration: 35681/59290
Iteration: 35682/59290
Iteration: 35683/59290
Iteration: 35684/59290
Iteration: 35685/59290
Iteration: 35686/59290
Iteration: 35687/59290
Iteration: 35688/59290
Iteration: 35689/59290
Iteration: 35690/59290
Iteration: 35691/59290
Iteration: 35692/59290
Iteration: 35693/59290
Iteration: 35694/59290
Iteration: 35695/59290
Iteration: 35696/59290
Iteration: 35697/59290
Iteration: 35698/59290
Iteration: 35699/59290
Iteration: 35700/59290
Iteration: 35701/59290
Iteration: 35702/59290
Iteration: 35703/59290
Iteration: 35704/59290

 60%|██████    | 35692/59290 [25:25<12:25, 31.66it/s]

Iteration: 35705/59290
Iteration: 35706/59290
Iteration: 35707/59290
Iteration: 35708/59290
Iteration: 35709/59290
Iteration: 35710/59290
Iteration: 35711/59290
Iteration: 35712/59290
Iteration: 35713/59290
Iteration: 35714/59290
Iteration: 35715/59290
Iteration: 35716/59290
Iteration: 35717/59290
Iteration: 35718/59290
Iteration: 35719/59290
Iteration: 35720/59290
Iteration: 35721/59290
Iteration: 35722/59290
Iteration: 35723/59290
Iteration: 35724/59290
Iteration: 35725/59290
Iteration: 35726/59290
Iteration: 35727/59290
Iteration: 35728/59290

 60%|██████    | 35716/59290 [25:25<10:33, 37.24it/s]

Iteration: 35729/59290
Iteration: 35730/59290
Iteration: 35731/59290
Iteration: 35732/59290
Iteration: 35733/59290
Iteration: 35734/59290
Iteration: 35735/59290
Iteration: 35736/59290
Iteration: 35737/59290
Iteration: 35738/59290
Iteration: 35739/59290
Iteration: 35740/59290
Iteration: 35741/59290
Iteration: 35742/59290
Iteration: 35743/59290
Iteration: 35744/59290
Iteration: 35745/59290
Iteration: 35746/59290
Iteration: 35747/59290
Iteration: 35748/59290
Iteration: 35749/59290
Iteration: 35750/59290
Iteration: 35751/59290
Iteration: 35752/59290

 60%|██████    | 35740/59290 [25:26<09:18, 42.16it/s]

Iteration: 35753/59290
Iteration: 35754/59290
Iteration: 35755/59290
Iteration: 35756/59290
Iteration: 35757/59290
Iteration: 35758/59290
Iteration: 35759/59290
Iteration: 35760/59290
Iteration: 35761/59290
Iteration: 35762/59290
Iteration: 35763/59290
Iteration: 35764/59290
Iteration: 35765/59290
Iteration: 35766/59290
Iteration: 35767/59290
Iteration: 35768/59290
Iteration: 35769/59290
Iteration: 35770/59290
Iteration: 35771/59290
Iteration: 35772/59290
Iteration: 35773/59290
Iteration: 35774/59290
Iteration: 35775/59290
Iteration: 35776/59290

 60%|██████    | 35764/59290 [25:26<08:20, 47.02it/s]

Iteration: 35777/59290
Iteration: 35778/59290
Iteration: 35779/59290
Iteration: 35780/59290
Iteration: 35781/59290
Iteration: 35782/59290
Iteration: 35783/59290
Iteration: 35784/59290
Iteration: 35785/59290
Iteration: 35786/59290
Iteration: 35787/59290
Iteration: 35788/59290
Iteration: 35789/59290
Iteration: 35790/59290
Iteration: 35791/59290
Iteration: 35792/59290
Iteration: 35793/59290
Iteration: 35794/59290
Iteration: 35795/59290
Iteration: 35796/59290
Iteration: 35797/59290
Iteration: 35798/59290
Iteration: 35799/59290
Iteration: 35800/59290

 60%|██████    | 35788/59290 [25:26<07:42, 50.81it/s]

Iteration: 35801/59290
Iteration: 35802/59290
Iteration: 35803/59290
Iteration: 35804/59290
Iteration: 35805/59290
Iteration: 35806/59290
Iteration: 35807/59290
Iteration: 35808/59290
Iteration: 35809/59290
Iteration: 35810/59290
Iteration: 35811/59290
Iteration: 35812/59290
Iteration: 35813/59290
Iteration: 35814/59290
Iteration: 35815/59290
Iteration: 35816/59290
Iteration: 35817/59290
Iteration: 35818/59290
Iteration: 35819/59290
Iteration: 35820/59290
Iteration: 35821/59290
Iteration: 35822/59290
Iteration: 35823/59290
Iteration: 35824/59290

 60%|██████    | 35812/59290 [25:27<07:13, 54.18it/s]

Iteration: 35825/59290
Iteration: 35826/59290
Iteration: 35827/59290
Iteration: 35828/59290
Iteration: 35829/59290
Iteration: 35830/59290
Iteration: 35831/59290
Iteration: 35832/59290
Iteration: 35833/59290
Iteration: 35834/59290
Iteration: 35835/59290
Iteration: 35836/59290
Iteration: 35837/59290
Iteration: 35838/59290
Iteration: 35839/59290
Iteration: 35840/59290
Iteration: 35841/59290
Iteration: 35842/59290
Iteration: 35843/59290
Iteration: 35844/59290
Iteration: 35845/59290
Iteration: 35846/59290
Iteration: 35847/59290
Iteration: 35848/59290

 60%|██████    | 35836/59290 [25:27<06:53, 56.77it/s]

Iteration: 35849/59290
Iteration: 35850/59290
Iteration: 35851/59290
Iteration: 35852/59290
Iteration: 35853/59290
Iteration: 35854/59290
Iteration: 35855/59290
Iteration: 35856/59290
Iteration: 35857/59290
Iteration: 35858/59290
Iteration: 35859/59290
Iteration: 35860/59290
Iteration: 35861/59290
Iteration: 35862/59290
Iteration: 35863/59290
Iteration: 35864/59290
Iteration: 35865/59290
Iteration: 35866/59290
Iteration: 35867/59290
Iteration: 35868/59290
Iteration: 35869/59290
Iteration: 35870/59290
Iteration: 35871/59290
Iteration: 35872/59290

 60%|██████    | 35860/59290 [25:28<06:39, 58.66it/s]

Iteration: 35873/59290
Iteration: 35874/59290
Iteration: 35875/59290
Iteration: 35876/59290
Iteration: 35877/59290
Iteration: 35878/59290
Iteration: 35879/59290
Iteration: 35880/59290
Iteration: 35881/59290
Iteration: 35882/59290
Iteration: 35883/59290
Iteration: 35884/59290
Iteration: 35885/59290
Iteration: 35886/59290
Iteration: 35887/59290
Iteration: 35888/59290
Iteration: 35889/59290
Iteration: 35890/59290
Iteration: 35891/59290
Iteration: 35892/59290
Iteration: 35893/59290
Iteration: 35894/59290
Iteration: 35895/59290
Iteration: 35896/59290

 61%|██████    | 35884/59290 [25:28<06:30, 59.95it/s]

Iteration: 35897/59290
Iteration: 35898/59290
Iteration: 35899/59290
Iteration: 35900/59290
Iteration: 35901/59290
Iteration: 35902/59290
Iteration: 35903/59290
Iteration: 35904/59290
Iteration: 35905/59290
Iteration: 35906/59290
Iteration: 35907/59290
Iteration: 35908/59290
Iteration: 35909/59290
Iteration: 35910/59290
Iteration: 35911/59290
Iteration: 35912/59290
Iteration: 35913/59290
Iteration: 35914/59290
Iteration: 35915/59290
Iteration: 35916/59290
Iteration: 35917/59290
Iteration: 35918/59290
Iteration: 35919/59290
Iteration: 35920/59290

 61%|██████    | 35908/59290 [25:28<06:23, 60.95it/s]

Iteration: 35921/59290
Iteration: 35922/59290
Iteration: 35923/59290
Iteration: 35924/59290
Iteration: 35925/59290
Iteration: 35926/59290
Iteration: 35927/59290
Iteration: 35928/59290
Iteration: 35929/59290
Iteration: 35930/59290
Iteration: 35931/59290
Iteration: 35932/59290
Iteration: 35933/59290
Iteration: 35934/59290
Iteration: 35935/59290
Iteration: 35936/59290
Iteration: 35937/59290
Iteration: 35938/59290
Iteration: 35939/59290
Iteration: 35940/59290
Iteration: 35941/59290
Iteration: 35942/59290
Iteration: 35943/59290
Iteration: 35944/59290

 61%|██████    | 35932/59290 [25:29<06:17, 61.86it/s]

Iteration: 35945/59290
Iteration: 35946/59290
Iteration: 35947/59290
Iteration: 35948/59290
Iteration: 35949/59290
Iteration: 35950/59290
Iteration: 35951/59290
Iteration: 35952/59290
Iteration: 35953/59290
Iteration: 35954/59290
Iteration: 35955/59290
Iteration: 35956/59290
Iteration: 35957/59290
Iteration: 35958/59290
Iteration: 35959/59290
Iteration: 35960/59290
Iteration: 35961/59290
Iteration: 35962/59290
Iteration: 35963/59290
Iteration: 35964/59290
Iteration: 35965/59290
Iteration: 35966/59290
Iteration: 35967/59290
Iteration: 35968/59290

 61%|██████    | 35956/59290 [25:30<10:43, 36.25it/s]

Iteration: 35969/59290
Iteration: 35970/59290
Iteration: 35971/59290
Iteration: 35972/59290
Iteration: 35973/59290
Iteration: 35974/59290
Iteration: 35975/59290
Iteration: 35976/59290
Iteration: 35977/59290
Iteration: 35978/59290
Iteration: 35979/59290
Iteration: 35980/59290
Iteration: 35981/59290
Iteration: 35982/59290
Iteration: 35983/59290
Iteration: 35984/59290
Iteration: 35985/59290
Iteration: 35986/59290
Iteration: 35987/59290
Iteration: 35988/59290
Iteration: 35989/59290
Iteration: 35990/59290
Iteration: 35991/59290
Iteration: 35992/59290

 61%|██████    | 35980/59290 [25:32<16:38, 23.34it/s]

Iteration: 35993/59290
Iteration: 35994/59290
Iteration: 35995/59290
Iteration: 35996/59290
Iteration: 35997/59290
Iteration: 35998/59290
Iteration: 35999/59290
Iteration: 36000/59290
Iteration: 36001/59290
Iteration: 36002/59290
Iteration: 36003/59290
Iteration: 36004/59290
Iteration: 36005/59290
Iteration: 36006/59290
Iteration: 36007/59290
Iteration: 36008/59290
Iteration: 36009/59290
Iteration: 36010/59290
Iteration: 36011/59290
Iteration: 36012/59290
Iteration: 36013/59290
Iteration: 36014/59290
Iteration: 36015/59290
Iteration: 36016/59290

 61%|██████    | 36004/59290 [25:32<13:29, 28.76it/s]

Iteration: 36017/59290
Iteration: 36018/59290
Iteration: 36019/59290
Iteration: 36020/59290
Iteration: 36021/59290
Iteration: 36022/59290
Iteration: 36023/59290
Iteration: 36024/59290
Iteration: 36025/59290
Iteration: 36026/59290
Iteration: 36027/59290
Iteration: 36028/59290
Iteration: 36029/59290
Iteration: 36030/59290
Iteration: 36031/59290
Iteration: 36032/59290
Iteration: 36033/59290
Iteration: 36034/59290
Iteration: 36035/59290
Iteration: 36036/59290
Iteration: 36037/59290
Iteration: 36038/59290
Iteration: 36039/59290
Iteration: 36040/59290

 61%|██████    | 36028/59290 [25:33<11:46, 32.94it/s]

Iteration: 36041/59290
Iteration: 36042/59290
Iteration: 36043/59290
Iteration: 36044/59290
Iteration: 36045/59290
Iteration: 36046/59290
Iteration: 36047/59290
Iteration: 36048/59290
Iteration: 36049/59290
Iteration: 36050/59290
Iteration: 36051/59290
Iteration: 36052/59290
Iteration: 36053/59290
Iteration: 36054/59290
Iteration: 36055/59290
Iteration: 36056/59290
Iteration: 36057/59290
Iteration: 36058/59290
Iteration: 36059/59290
Iteration: 36060/59290
Iteration: 36061/59290
Iteration: 36062/59290
Iteration: 36063/59290
Iteration: 36064/59290

 61%|██████    | 36052/59290 [26:06<2:47:18,  2.31it/s]

Iteration: 36065/59290
Iteration: 36066/59290
Iteration: 36067/59290
Iteration: 36068/59290
Iteration: 36069/59290
Iteration: 36070/59290
Iteration: 36071/59290
Iteration: 36072/59290
Iteration: 36073/59290
Iteration: 36074/59290
Iteration: 36075/59290
Iteration: 36076/59290
Iteration: 36077/59290
Iteration: 36078/59290
Iteration: 36079/59290
Iteration: 36080/59290
Iteration: 36081/59290
Iteration: 36082/59290
Iteration: 36083/59290
Iteration: 36084/59290
Iteration: 36085/59290
Iteration: 36086/59290
Iteration: 36087/59290
Iteration: 36088/59290

 61%|██████    | 36076/59290 [26:08<2:06:19,  3.06it/s]

Iteration: 36089/59290
Iteration: 36090/59290
Iteration: 36091/59290
Iteration: 36092/59290
Iteration: 36093/59290
Iteration: 36094/59290
Iteration: 36095/59290
Iteration: 36096/59290
Iteration: 36097/59290
Iteration: 36098/59290
Iteration: 36099/59290
Iteration: 36100/59290
Iteration: 36101/59290
Iteration: 36102/59290
Iteration: 36103/59290
Iteration: 36104/59290
Iteration: 36105/59290
Iteration: 36106/59290
Iteration: 36107/59290
Iteration: 36108/59290
Iteration: 36109/59290
Iteration: 36110/59290
Iteration: 36111/59290
Iteration: 36112/59290

 61%|██████    | 36100/59290 [26:08<1:30:23,  4.28it/s]

Iteration: 36113/59290
Iteration: 36114/59290
Iteration: 36115/59290
Iteration: 36116/59290
Iteration: 36117/59290
Iteration: 36118/59290
Iteration: 36119/59290
Iteration: 36120/59290
Iteration: 36121/59290
Iteration: 36122/59290
Iteration: 36123/59290
Iteration: 36124/59290
Iteration: 36125/59290
Iteration: 36126/59290
Iteration: 36127/59290
Iteration: 36128/59290
Iteration: 36129/59290
Iteration: 36130/59290
Iteration: 36131/59290
Iteration: 36132/59290
Iteration: 36133/59290
Iteration: 36134/59290
Iteration: 36135/59290
Iteration: 36136/59290

 61%|██████    | 36124/59290 [26:08<1:05:01,  5.94it/s]

Iteration: 36137/59290
Iteration: 36138/59290
Iteration: 36139/59290
Iteration: 36140/59290
Iteration: 36141/59290
Iteration: 36142/59290
Iteration: 36143/59290
Iteration: 36144/59290
Iteration: 36145/59290
Iteration: 36146/59290
Iteration: 36147/59290
Iteration: 36148/59290
Iteration: 36149/59290
Iteration: 36150/59290
Iteration: 36151/59290
Iteration: 36152/59290
Iteration: 36153/59290
Iteration: 36154/59290
Iteration: 36155/59290
Iteration: 36156/59290
Iteration: 36157/59290
Iteration: 36158/59290
Iteration: 36159/59290
Iteration: 36160/59290

 61%|██████    | 36148/59290 [26:09<47:26,  8.13it/s]

Iteration: 36161/59290
Iteration: 36162/59290
Iteration: 36163/59290
Iteration: 36164/59290
Iteration: 36165/59290
Iteration: 36166/59290
Iteration: 36167/59290
Iteration: 36168/59290
Iteration: 36169/59290
Iteration: 36170/59290
Iteration: 36171/59290
Iteration: 36172/59290
Iteration: 36173/59290
Iteration: 36174/59290
Iteration: 36175/59290
Iteration: 36176/59290
Iteration: 36177/59290
Iteration: 36178/59290
Iteration: 36179/59290
Iteration: 36180/59290
Iteration: 36181/59290
Iteration: 36182/59290
Iteration: 36183/59290
Iteration: 36184/59290

 61%|██████    | 36172/59290 [26:10<41:24,  9.31it/s]

Iteration: 36185/59290
Iteration: 36186/59290
Iteration: 36187/59290
Iteration: 36188/59290
Iteration: 36189/59290
Iteration: 36190/59290
Iteration: 36191/59290
Iteration: 36192/59290
Iteration: 36193/59290
Iteration: 36194/59290
Iteration: 36195/59290
Iteration: 36196/59290
Iteration: 36197/59290
Iteration: 36198/59290
Iteration: 36199/59290
Iteration: 36200/59290
Iteration: 36201/59290
Iteration: 36202/59290
Iteration: 36203/59290
Iteration: 36204/59290
Iteration: 36205/59290
Iteration: 36206/59290
Iteration: 36207/59290
Iteration: 36208/59290

 61%|██████    | 36196/59290 [26:13<39:32,  9.74it/s]

Iteration: 36209/59290
Iteration: 36210/59290
Iteration: 36211/59290
Iteration: 36212/59290
Iteration: 36213/59290
Iteration: 36214/59290
Iteration: 36215/59290
Iteration: 36216/59290
Iteration: 36217/59290
Iteration: 36218/59290
Iteration: 36219/59290
Iteration: 36220/59290
Iteration: 36221/59290
Iteration: 36222/59290
Iteration: 36223/59290
Iteration: 36224/59290
Iteration: 36225/59290
Iteration: 36226/59290
Iteration: 36227/59290
Iteration: 36228/59290
Iteration: 36229/59290
Iteration: 36230/59290
Iteration: 36231/59290
Iteration: 36232/59290

 61%|██████    | 36220/59290 [26:13<29:29, 13.04it/s]

Iteration: 36233/59290
Iteration: 36234/59290
Iteration: 36235/59290
Iteration: 36236/59290
Iteration: 36237/59290
Iteration: 36238/59290
Iteration: 36239/59290
Iteration: 36240/59290
Iteration: 36241/59290
Iteration: 36242/59290
Iteration: 36243/59290
Iteration: 36244/59290
Iteration: 36245/59290
Iteration: 36246/59290
Iteration: 36247/59290
Iteration: 36248/59290
Iteration: 36249/59290
Iteration: 36250/59290
Iteration: 36251/59290
Iteration: 36252/59290
Iteration: 36253/59290
Iteration: 36254/59290
Iteration: 36255/59290
Iteration: 36256/59290

 61%|██████    | 36244/59290 [26:13<22:24, 17.14it/s]

Iteration: 36257/59290
Iteration: 36258/59290
Iteration: 36259/59290
Iteration: 36260/59290
Iteration: 36261/59290
Iteration: 36262/59290
Iteration: 36263/59290
Iteration: 36264/59290
Iteration: 36265/59290
Iteration: 36266/59290
Iteration: 36267/59290
Iteration: 36268/59290
Iteration: 36269/59290
Iteration: 36270/59290
Iteration: 36271/59290
Iteration: 36272/59290
Iteration: 36273/59290
Iteration: 36274/59290
Iteration: 36275/59290
Iteration: 36276/59290
Iteration: 36277/59290
Iteration: 36278/59290
Iteration: 36279/59290
Iteration: 36280/59290

 61%|██████    | 36268/59290 [26:14<17:28, 21.96it/s]

Iteration: 36281/59290
Iteration: 36282/59290
Iteration: 36283/59290
Iteration: 36284/59290
Iteration: 36285/59290
Iteration: 36286/59290
Iteration: 36287/59290
Iteration: 36288/59290
Iteration: 36289/59290
Iteration: 36290/59290
Iteration: 36291/59290
Iteration: 36292/59290
Iteration: 36293/59290
Iteration: 36294/59290
Iteration: 36295/59290
Iteration: 36296/59290
Iteration: 36297/59290
Iteration: 36298/59290
Iteration: 36299/59290
Iteration: 36300/59290
Iteration: 36301/59290
Iteration: 36302/59290
Iteration: 36303/59290
Iteration: 36304/59290

 61%|██████    | 36292/59290 [26:15<18:32, 20.68it/s]

Iteration: 36305/59290
Iteration: 36306/59290
Iteration: 36307/59290
Iteration: 36308/59290
Iteration: 36309/59290
Iteration: 36310/59290
Iteration: 36311/59290
Iteration: 36312/59290
Iteration: 36313/59290
Iteration: 36314/59290
Iteration: 36315/59290
Iteration: 36316/59290
Iteration: 36317/59290
Iteration: 36318/59290
Iteration: 36319/59290
Iteration: 36320/59290
Iteration: 36321/59290
Iteration: 36322/59290
Iteration: 36323/59290
Iteration: 36324/59290
Iteration: 36325/59290
Iteration: 36326/59290
Iteration: 36327/59290
Iteration: 36328/59290

 61%|██████▏   | 36316/59290 [26:17<21:47, 17.57it/s]

Iteration: 36329/59290
Iteration: 36330/59290
Iteration: 36331/59290
Iteration: 36332/59290
Iteration: 36333/59290
Iteration: 36334/59290
Iteration: 36335/59290
Iteration: 36336/59290
Iteration: 36337/59290
Iteration: 36338/59290
Iteration: 36339/59290
Iteration: 36340/59290
Iteration: 36341/59290
Iteration: 36342/59290
Iteration: 36343/59290
Iteration: 36344/59290
Iteration: 36345/59290
Iteration: 36346/59290
Iteration: 36347/59290
Iteration: 36348/59290
Iteration: 36349/59290
Iteration: 36350/59290
Iteration: 36351/59290
Iteration: 36352/59290

 61%|██████▏   | 36340/59290 [26:17<17:13, 22.20it/s]

Iteration: 36353/59290
Iteration: 36354/59290
Iteration: 36355/59290
Iteration: 36356/59290
Iteration: 36357/59290
Iteration: 36358/59290
Iteration: 36359/59290
Iteration: 36360/59290
Iteration: 36361/59290
Iteration: 36362/59290
Iteration: 36363/59290
Iteration: 36364/59290
Iteration: 36365/59290
Iteration: 36366/59290
Iteration: 36367/59290
Iteration: 36368/59290
Iteration: 36369/59290
Iteration: 36370/59290
Iteration: 36371/59290
Iteration: 36372/59290
Iteration: 36373/59290
Iteration: 36374/59290
Iteration: 36375/59290
Iteration: 36376/59290

 61%|██████▏   | 36364/59290 [26:18<13:59, 27.32it/s]

Iteration: 36377/59290
Iteration: 36378/59290
Iteration: 36379/59290
Iteration: 36380/59290
Iteration: 36381/59290
Iteration: 36382/59290
Iteration: 36383/59290
Iteration: 36384/59290
Iteration: 36385/59290
Iteration: 36386/59290
Iteration: 36387/59290
Iteration: 36388/59290
Iteration: 36389/59290
Iteration: 36390/59290
Iteration: 36391/59290
Iteration: 36392/59290
Iteration: 36393/59290
Iteration: 36394/59290
Iteration: 36395/59290
Iteration: 36396/59290
Iteration: 36397/59290
Iteration: 36398/59290
Iteration: 36399/59290
Iteration: 36400/59290

 61%|██████▏   | 36388/59290 [26:18<11:44, 32.51it/s]

Iteration: 36401/59290
Iteration: 36402/59290
Iteration: 36403/59290
Iteration: 36404/59290
Iteration: 36405/59290
Iteration: 36406/59290
Iteration: 36407/59290
Iteration: 36408/59290
Iteration: 36409/59290
Iteration: 36410/59290
Iteration: 36411/59290
Iteration: 36412/59290
Iteration: 36413/59290
Iteration: 36414/59290
Iteration: 36415/59290
Iteration: 36416/59290
Iteration: 36417/59290
Iteration: 36418/59290
Iteration: 36419/59290
Iteration: 36420/59290
Iteration: 36421/59290
Iteration: 36422/59290
Iteration: 36423/59290
Iteration: 36424/59290

 61%|██████▏   | 36412/59290 [26:19<10:07, 37.68it/s]

Iteration: 36425/59290
Iteration: 36426/59290
Iteration: 36427/59290
Iteration: 36428/59290
Iteration: 36429/59290
Iteration: 36430/59290
Iteration: 36431/59290
Iteration: 36432/59290
Iteration: 36433/59290
Iteration: 36434/59290
Iteration: 36435/59290
Iteration: 36436/59290
Iteration: 36437/59290
Iteration: 36438/59290
Iteration: 36439/59290
Iteration: 36440/59290
Iteration: 36441/59290
Iteration: 36442/59290
Iteration: 36443/59290
Iteration: 36444/59290
Iteration: 36445/59290
Iteration: 36446/59290
Iteration: 36447/59290
Iteration: 36448/59290

 61%|██████▏   | 36436/59290 [26:19<08:56, 42.57it/s]

Iteration: 36449/59290
Iteration: 36450/59290
Iteration: 36451/59290
Iteration: 36452/59290
Iteration: 36453/59290
Iteration: 36454/59290
Iteration: 36455/59290
Iteration: 36456/59290
Iteration: 36457/59290
Iteration: 36458/59290
Iteration: 36459/59290
Iteration: 36460/59290
Iteration: 36461/59290
Iteration: 36462/59290
Iteration: 36463/59290
Iteration: 36464/59290
Iteration: 36465/59290
Iteration: 36466/59290
Iteration: 36467/59290
Iteration: 36468/59290
Iteration: 36469/59290
Iteration: 36470/59290
Iteration: 36471/59290
Iteration: 36472/59290

 61%|██████▏   | 36460/59290 [26:19<08:11, 46.45it/s]

Iteration: 36473/59290
Iteration: 36474/59290
Iteration: 36475/59290
Iteration: 36476/59290
Iteration: 36477/59290
Iteration: 36478/59290
Iteration: 36479/59290
Iteration: 36480/59290
Iteration: 36481/59290
Iteration: 36482/59290
Iteration: 36483/59290
Iteration: 36484/59290
Iteration: 36485/59290
Iteration: 36486/59290
Iteration: 36487/59290
Iteration: 36488/59290
Iteration: 36489/59290
Iteration: 36490/59290
Iteration: 36491/59290
Iteration: 36492/59290
Iteration: 36493/59290
Iteration: 36494/59290
Iteration: 36495/59290
Iteration: 36496/59290

 62%|██████▏   | 36484/59290 [26:20<07:40, 49.55it/s]

Iteration: 36497/59290
Iteration: 36498/59290
Iteration: 36499/59290
Iteration: 36500/59290
Iteration: 36501/59290
Iteration: 36502/59290
Iteration: 36503/59290
Iteration: 36504/59290
Iteration: 36505/59290
Iteration: 36506/59290
Iteration: 36507/59290
Iteration: 36508/59290
Iteration: 36509/59290
Iteration: 36510/59290
Iteration: 36511/59290
Iteration: 36512/59290
Iteration: 36513/59290
Iteration: 36514/59290
Iteration: 36515/59290
Iteration: 36516/59290
Iteration: 36517/59290
Iteration: 36518/59290
Iteration: 36519/59290
Iteration: 36520/59290

 62%|██████▏   | 36508/59290 [26:21<10:52, 34.90it/s]

Iteration: 36521/59290
Iteration: 36522/59290
Iteration: 36523/59290
Iteration: 36524/59290
Iteration: 36525/59290
Iteration: 36526/59290
Iteration: 36527/59290
Iteration: 36528/59290
Iteration: 36529/59290
Iteration: 36530/59290
Iteration: 36531/59290
Iteration: 36532/59290
Iteration: 36533/59290
Iteration: 36534/59290
Iteration: 36535/59290
Iteration: 36536/59290
Iteration: 36537/59290
Iteration: 36538/59290
Iteration: 36539/59290
Iteration: 36540/59290
Iteration: 36541/59290
Iteration: 36542/59290
Iteration: 36543/59290
Iteration: 36544/59290

 62%|██████▏   | 36532/59290 [26:23<15:42, 24.16it/s]

Iteration: 36545/59290
Iteration: 36546/59290
Iteration: 36547/59290
Iteration: 36548/59290
Iteration: 36549/59290
Iteration: 36550/59290
Iteration: 36551/59290
Iteration: 36552/59290
Iteration: 36553/59290
Iteration: 36554/59290
Iteration: 36555/59290
Iteration: 36556/59290
Iteration: 36557/59290
Iteration: 36558/59290
Iteration: 36559/59290
Iteration: 36560/59290
Iteration: 36561/59290
Iteration: 36562/59290
Iteration: 36563/59290
Iteration: 36564/59290
Iteration: 36565/59290
Iteration: 36566/59290
Iteration: 36567/59290
Iteration: 36568/59290

 62%|██████▏   | 36556/59290 [26:23<13:02, 29.07it/s]

Iteration: 36569/59290
Iteration: 36570/59290
Iteration: 36571/59290
Iteration: 36572/59290
Iteration: 36573/59290
Iteration: 36574/59290
Iteration: 36575/59290
Iteration: 36576/59290
Iteration: 36577/59290
Iteration: 36578/59290
Iteration: 36579/59290
Iteration: 36580/59290
Iteration: 36581/59290
Iteration: 36582/59290
Iteration: 36583/59290
Iteration: 36584/59290
Iteration: 36585/59290
Iteration: 36586/59290
Iteration: 36587/59290
Iteration: 36588/59290
Iteration: 36589/59290
Iteration: 36590/59290
Iteration: 36591/59290
Iteration: 36592/59290

 62%|██████▏   | 36580/59290 [26:23<11:05, 34.14it/s]

Iteration: 36593/59290
Iteration: 36594/59290
Iteration: 36595/59290
Iteration: 36596/59290
Iteration: 36597/59290
Iteration: 36598/59290
Iteration: 36599/59290
Iteration: 36600/59290
Iteration: 36601/59290
Iteration: 36602/59290
Iteration: 36603/59290
Iteration: 36604/59290
Iteration: 36605/59290
Iteration: 36606/59290
Iteration: 36607/59290
Iteration: 36608/59290
Iteration: 36609/59290
Iteration: 36610/59290
Iteration: 36611/59290
Iteration: 36612/59290
Iteration: 36613/59290
Iteration: 36614/59290
Iteration: 36615/59290
Iteration: 36616/59290

 62%|██████▏   | 36604/59290 [26:24<09:40, 39.05it/s]

Iteration: 36617/59290
Iteration: 36618/59290
Iteration: 36619/59290
Iteration: 36620/59290
Iteration: 36621/59290
Iteration: 36622/59290
Iteration: 36623/59290
Iteration: 36624/59290
Iteration: 36625/59290
Iteration: 36626/59290
Iteration: 36627/59290
Iteration: 36628/59290
Iteration: 36629/59290
Iteration: 36630/59290
Iteration: 36631/59290
Iteration: 36632/59290
Iteration: 36633/59290
Iteration: 36634/59290
Iteration: 36635/59290
Iteration: 36636/59290
Iteration: 36637/59290
Iteration: 36638/59290
Iteration: 36639/59290
Iteration: 36640/59290

 62%|██████▏   | 36628/59290 [26:24<08:38, 43.72it/s]

Iteration: 36641/59290
Iteration: 36642/59290
Iteration: 36643/59290
Iteration: 36644/59290
Iteration: 36645/59290
Iteration: 36646/59290
Iteration: 36647/59290
Iteration: 36648/59290
Iteration: 36649/59290
Iteration: 36650/59290
Iteration: 36651/59290
Iteration: 36652/59290
Iteration: 36653/59290
Iteration: 36654/59290
Iteration: 36655/59290
Iteration: 36656/59290
Iteration: 36657/59290
Iteration: 36658/59290
Iteration: 36659/59290
Iteration: 36660/59290
Iteration: 36661/59290
Iteration: 36662/59290
Iteration: 36663/59290
Iteration: 36664/59290

 62%|██████▏   | 36652/59290 [26:25<07:57, 47.39it/s]

Iteration: 36665/59290
Iteration: 36666/59290
Iteration: 36667/59290
Iteration: 36668/59290
Iteration: 36669/59290
Iteration: 36670/59290
Iteration: 36671/59290
Iteration: 36672/59290
Iteration: 36673/59290
Iteration: 36674/59290
Iteration: 36675/59290
Iteration: 36676/59290
Iteration: 36677/59290
Iteration: 36678/59290
Iteration: 36679/59290
Iteration: 36680/59290
Iteration: 36681/59290
Iteration: 36682/59290
Iteration: 36683/59290
Iteration: 36684/59290
Iteration: 36685/59290
Iteration: 36686/59290
Iteration: 36687/59290
Iteration: 36688/59290

 62%|██████▏   | 36676/59290 [26:25<07:26, 50.66it/s]

Iteration: 36689/59290
Iteration: 36690/59290
Iteration: 36691/59290
Iteration: 36692/59290
Iteration: 36693/59290
Iteration: 36694/59290
Iteration: 36695/59290
Iteration: 36696/59290
Iteration: 36697/59290
Iteration: 36698/59290
Iteration: 36699/59290
Iteration: 36700/59290
Iteration: 36701/59290
Iteration: 36702/59290
Iteration: 36703/59290
Iteration: 36704/59290
Iteration: 36705/59290
Iteration: 36706/59290
Iteration: 36707/59290
Iteration: 36708/59290
Iteration: 36709/59290
Iteration: 36710/59290
Iteration: 36711/59290
Iteration: 36712/59290

 62%|██████▏   | 36700/59290 [26:25<06:58, 53.97it/s]

Iteration: 36713/59290
Iteration: 36714/59290
Iteration: 36715/59290
Iteration: 36716/59290
Iteration: 36717/59290
Iteration: 36718/59290
Iteration: 36719/59290
Iteration: 36720/59290
Iteration: 36721/59290
Iteration: 36722/59290
Iteration: 36723/59290
Iteration: 36724/59290
Iteration: 36725/59290
Iteration: 36726/59290
Iteration: 36727/59290
Iteration: 36728/59290
Iteration: 36729/59290
Iteration: 36730/59290
Iteration: 36731/59290
Iteration: 36732/59290
Iteration: 36733/59290
Iteration: 36734/59290
Iteration: 36735/59290
Iteration: 36736/59290

 62%|██████▏   | 36724/59290 [26:26<06:37, 56.77it/s]

Iteration: 36737/59290
Iteration: 36738/59290
Iteration: 36739/59290
Iteration: 36740/59290
Iteration: 36741/59290
Iteration: 36742/59290
Iteration: 36743/59290
Iteration: 36744/59290
Iteration: 36745/59290
Iteration: 36746/59290
Iteration: 36747/59290
Iteration: 36748/59290
Iteration: 36749/59290
Iteration: 36750/59290
Iteration: 36751/59290
Iteration: 36752/59290
Iteration: 36753/59290
Iteration: 36754/59290
Iteration: 36755/59290
Iteration: 36756/59290
Iteration: 36757/59290
Iteration: 36758/59290
Iteration: 36759/59290
Iteration: 36760/59290

 62%|██████▏   | 36748/59290 [26:26<06:23, 58.85it/s]

Iteration: 36761/59290
Iteration: 36762/59290
Iteration: 36763/59290
Iteration: 36764/59290
Iteration: 36765/59290
Iteration: 36766/59290
Iteration: 36767/59290
Iteration: 36768/59290
Iteration: 36769/59290
Iteration: 36770/59290
Iteration: 36771/59290
Iteration: 36772/59290
Iteration: 36773/59290
Iteration: 36774/59290
Iteration: 36775/59290
Iteration: 36776/59290
Iteration: 36777/59290
Iteration: 36778/59290
Iteration: 36779/59290
Iteration: 36780/59290
Iteration: 36781/59290
Iteration: 36782/59290
Iteration: 36783/59290
Iteration: 36784/59290

 62%|██████▏   | 36772/59290 [26:28<11:22, 32.99it/s]

Iteration: 36785/59290
Iteration: 36786/59290
Iteration: 36787/59290
Iteration: 36788/59290
Iteration: 36789/59290
Iteration: 36790/59290
Iteration: 36791/59290
Iteration: 36792/59290
Iteration: 36793/59290
Iteration: 36794/59290
Iteration: 36795/59290
Iteration: 36796/59290
Iteration: 36797/59290
Iteration: 36798/59290
Iteration: 36799/59290
Iteration: 36800/59290
Iteration: 36801/59290
Iteration: 36802/59290
Iteration: 36803/59290
Iteration: 36804/59290
Iteration: 36805/59290
Iteration: 36806/59290
Iteration: 36807/59290
Iteration: 36808/59290

 62%|██████▏   | 36796/59290 [26:29<15:56, 23.51it/s]

Iteration: 36809/59290
Iteration: 36810/59290
Iteration: 36811/59290
Iteration: 36812/59290
Iteration: 36813/59290
Iteration: 36814/59290
Iteration: 36815/59290
Iteration: 36816/59290
Iteration: 36817/59290
Iteration: 36818/59290
Iteration: 36819/59290
Iteration: 36820/59290
Iteration: 36821/59290
Iteration: 36822/59290
Iteration: 36823/59290
Iteration: 36824/59290
Iteration: 36825/59290
Iteration: 36826/59290
Iteration: 36827/59290
Iteration: 36828/59290
Iteration: 36829/59290
Iteration: 36830/59290
Iteration: 36831/59290
Iteration: 36832/59290

 62%|██████▏   | 36820/59290 [26:30<13:12, 28.36it/s]

Iteration: 36833/59290
Iteration: 36834/59290
Iteration: 36835/59290
Iteration: 36836/59290
Iteration: 36837/59290
Iteration: 36838/59290
Iteration: 36839/59290
Iteration: 36840/59290
Iteration: 36841/59290
Iteration: 36842/59290
Iteration: 36843/59290
Iteration: 36844/59290
Iteration: 36845/59290
Iteration: 36846/59290
Iteration: 36847/59290
Iteration: 36848/59290
Iteration: 36849/59290
Iteration: 36850/59290
Iteration: 36851/59290
Iteration: 36852/59290
Iteration: 36853/59290
Iteration: 36854/59290
Iteration: 36855/59290
Iteration: 36856/59290

 62%|██████▏   | 36844/59290 [26:30<10:58, 34.06it/s]

Iteration: 36857/59290
Iteration: 36858/59290
Iteration: 36859/59290
Iteration: 36860/59290
Iteration: 36861/59290
Iteration: 36862/59290
Iteration: 36863/59290
Iteration: 36864/59290
Iteration: 36865/59290
Iteration: 36866/59290
Iteration: 36867/59290
Iteration: 36868/59290
Iteration: 36869/59290
Iteration: 36870/59290
Iteration: 36871/59290
Iteration: 36872/59290
Iteration: 36873/59290
Iteration: 36874/59290
Iteration: 36875/59290
Iteration: 36876/59290
Iteration: 36877/59290
Iteration: 36878/59290
Iteration: 36879/59290
Iteration: 36880/59290

 62%|██████▏   | 36868/59290 [26:31<09:27, 39.49it/s]

Iteration: 36881/59290
Iteration: 36882/59290
Iteration: 36883/59290
Iteration: 36884/59290
Iteration: 36885/59290
Iteration: 36886/59290
Iteration: 36887/59290
Iteration: 36888/59290
Iteration: 36889/59290
Iteration: 36890/59290
Iteration: 36891/59290
Iteration: 36892/59290
Iteration: 36893/59290
Iteration: 36894/59290
Iteration: 36895/59290
Iteration: 36896/59290
Iteration: 36897/59290
Iteration: 36898/59290
Iteration: 36899/59290
Iteration: 36900/59290
Iteration: 36901/59290
Iteration: 36902/59290
Iteration: 36903/59290
Iteration: 36904/59290

 62%|██████▏   | 36892/59290 [26:31<08:22, 44.53it/s]

Iteration: 36905/59290
Iteration: 36906/59290
Iteration: 36907/59290
Iteration: 36908/59290
Iteration: 36909/59290
Iteration: 36910/59290
Iteration: 36911/59290
Iteration: 36912/59290
Iteration: 36913/59290
Iteration: 36914/59290
Iteration: 36915/59290
Iteration: 36916/59290
Iteration: 36917/59290
Iteration: 36918/59290
Iteration: 36919/59290
Iteration: 36920/59290
Iteration: 36921/59290
Iteration: 36922/59290
Iteration: 36923/59290
Iteration: 36924/59290
Iteration: 36925/59290
Iteration: 36926/59290
Iteration: 36927/59290
Iteration: 36928/59290

 62%|██████▏   | 36916/59290 [26:31<07:35, 49.09it/s]

Iteration: 36929/59290
Iteration: 36930/59290
Iteration: 36931/59290
Iteration: 36932/59290
Iteration: 36933/59290
Iteration: 36934/59290
Iteration: 36935/59290
Iteration: 36936/59290
Iteration: 36937/59290
Iteration: 36938/59290
Iteration: 36939/59290
Iteration: 36940/59290
Iteration: 36941/59290
Iteration: 36942/59290
Iteration: 36943/59290
Iteration: 36944/59290
Iteration: 36945/59290
Iteration: 36946/59290
Iteration: 36947/59290
Iteration: 36948/59290
Iteration: 36949/59290
Iteration: 36950/59290
Iteration: 36951/59290
Iteration: 36952/59290

 62%|██████▏   | 36940/59290 [26:33<11:14, 33.12it/s]

Iteration: 36953/59290
Iteration: 36954/59290
Iteration: 36955/59290
Iteration: 36956/59290
Iteration: 36957/59290
Iteration: 36958/59290
Iteration: 36959/59290
Iteration: 36960/59290
Iteration: 36961/59290
Iteration: 36962/59290
Iteration: 36963/59290
Iteration: 36964/59290
Iteration: 36965/59290
Iteration: 36966/59290
Iteration: 36967/59290
Iteration: 36968/59290
Iteration: 36969/59290
Iteration: 36970/59290
Iteration: 36971/59290
Iteration: 36972/59290
Iteration: 36973/59290
Iteration: 36974/59290
Iteration: 36975/59290
Iteration: 36976/59290

 62%|██████▏   | 36964/59290 [26:34<16:11, 22.99it/s]

Iteration: 36977/59290
Iteration: 36978/59290
Iteration: 36979/59290
Iteration: 36980/59290
Iteration: 36981/59290
Iteration: 36982/59290
Iteration: 36983/59290
Iteration: 36984/59290
Iteration: 36985/59290
Iteration: 36986/59290
Iteration: 36987/59290
Iteration: 36988/59290
Iteration: 36989/59290
Iteration: 36990/59290
Iteration: 36991/59290
Iteration: 36992/59290
Iteration: 36993/59290
Iteration: 36994/59290
Iteration: 36995/59290
Iteration: 36996/59290
Iteration: 36997/59290
Iteration: 36998/59290
Iteration: 36999/59290
Iteration: 37000/59290

 62%|██████▏   | 36988/59290 [26:35<13:15, 28.05it/s]

Iteration: 37001/59290
Iteration: 37002/59290
Iteration: 37003/59290
Iteration: 37004/59290
Iteration: 37005/59290
Iteration: 37006/59290
Iteration: 37007/59290
Iteration: 37008/59290
Iteration: 37009/59290
Iteration: 37010/59290
Iteration: 37011/59290
Iteration: 37012/59290
Iteration: 37013/59290
Iteration: 37014/59290
Iteration: 37015/59290
Iteration: 37016/59290
Iteration: 37017/59290
Iteration: 37018/59290
Iteration: 37019/59290
Iteration: 37020/59290
Iteration: 37021/59290
Iteration: 37022/59290
Iteration: 37023/59290
Iteration: 37024/59290

 62%|██████▏   | 37012/59290 [26:35<11:03, 33.57it/s]

Iteration: 37025/59290
Iteration: 37026/59290
Iteration: 37027/59290
Iteration: 37028/59290
Iteration: 37029/59290
Iteration: 37030/59290
Iteration: 37031/59290
Iteration: 37032/59290
Iteration: 37033/59290
Iteration: 37034/59290
Iteration: 37035/59290
Iteration: 37036/59290
Iteration: 37037/59290
Iteration: 37038/59290
Iteration: 37039/59290
Iteration: 37040/59290
Iteration: 37041/59290
Iteration: 37042/59290
Iteration: 37043/59290
Iteration: 37044/59290
Iteration: 37045/59290
Iteration: 37046/59290
Iteration: 37047/59290
Iteration: 37048/59290

 62%|██████▏   | 37036/59290 [26:36<09:31, 38.94it/s]

Iteration: 37049/59290
Iteration: 37050/59290
Iteration: 37051/59290
Iteration: 37052/59290
Iteration: 37053/59290
Iteration: 37054/59290
Iteration: 37055/59290
Iteration: 37056/59290
Iteration: 37057/59290
Iteration: 37058/59290
Iteration: 37059/59290
Iteration: 37060/59290
Iteration: 37061/59290
Iteration: 37062/59290
Iteration: 37063/59290
Iteration: 37064/59290
Iteration: 37065/59290
Iteration: 37066/59290
Iteration: 37067/59290
Iteration: 37068/59290
Iteration: 37069/59290
Iteration: 37070/59290
Iteration: 37071/59290
Iteration: 37072/59290

 63%|██████▎   | 37060/59290 [26:36<08:24, 44.10it/s]

Iteration: 37073/59290
Iteration: 37074/59290
Iteration: 37075/59290
Iteration: 37076/59290
Iteration: 37077/59290
Iteration: 37078/59290
Iteration: 37079/59290
Iteration: 37080/59290
Iteration: 37081/59290
Iteration: 37082/59290
Iteration: 37083/59290
Iteration: 37084/59290
Iteration: 37085/59290
Iteration: 37086/59290
Iteration: 37087/59290
Iteration: 37088/59290
Iteration: 37089/59290
Iteration: 37090/59290
Iteration: 37091/59290
Iteration: 37092/59290
Iteration: 37093/59290
Iteration: 37094/59290
Iteration: 37095/59290
Iteration: 37096/59290

 63%|██████▎   | 37084/59290 [26:37<11:46, 31.42it/s]

Iteration: 37097/59290
Iteration: 37098/59290
Iteration: 37099/59290
Iteration: 37100/59290
Iteration: 37101/59290
Iteration: 37102/59290
Iteration: 37103/59290
Iteration: 37104/59290
Iteration: 37105/59290
Iteration: 37106/59290
Iteration: 37107/59290
Iteration: 37108/59290
Iteration: 37109/59290
Iteration: 37110/59290
Iteration: 37111/59290
Iteration: 37112/59290
Iteration: 37113/59290
Iteration: 37114/59290
Iteration: 37115/59290
Iteration: 37116/59290
Iteration: 37117/59290
Iteration: 37118/59290
Iteration: 37119/59290
Iteration: 37120/59290

 63%|██████▎   | 37108/59290 [26:39<16:18, 22.67it/s]

Iteration: 37121/59290
Iteration: 37122/59290
Iteration: 37123/59290
Iteration: 37124/59290
Iteration: 37125/59290
Iteration: 37126/59290
Iteration: 37127/59290
Iteration: 37128/59290
Iteration: 37129/59290
Iteration: 37130/59290
Iteration: 37131/59290
Iteration: 37132/59290
Iteration: 37133/59290
Iteration: 37134/59290
Iteration: 37135/59290
Iteration: 37136/59290
Iteration: 37137/59290
Iteration: 37138/59290
Iteration: 37139/59290
Iteration: 37140/59290
Iteration: 37141/59290
Iteration: 37142/59290
Iteration: 37143/59290
Iteration: 37144/59290

 63%|██████▎   | 37132/59290 [26:39<13:24, 27.56it/s]

Iteration: 37145/59290
Iteration: 37146/59290
Iteration: 37147/59290
Iteration: 37148/59290
Iteration: 37149/59290
Iteration: 37150/59290
Iteration: 37151/59290
Iteration: 37152/59290
Iteration: 37153/59290
Iteration: 37154/59290
Iteration: 37155/59290
Iteration: 37156/59290
Iteration: 37157/59290
Iteration: 37158/59290
Iteration: 37159/59290
Iteration: 37160/59290
Iteration: 37161/59290
Iteration: 37162/59290
Iteration: 37163/59290
Iteration: 37164/59290
Iteration: 37165/59290
Iteration: 37166/59290
Iteration: 37167/59290
Iteration: 37168/59290

 63%|██████▎   | 37156/59290 [26:40<11:11, 32.95it/s]

Iteration: 37169/59290
Iteration: 37170/59290
Iteration: 37171/59290
Iteration: 37172/59290
Iteration: 37173/59290
Iteration: 37174/59290
Iteration: 37175/59290
Iteration: 37176/59290
Iteration: 37177/59290
Iteration: 37178/59290
Iteration: 37179/59290
Iteration: 37180/59290
Iteration: 37181/59290
Iteration: 37182/59290
Iteration: 37183/59290
Iteration: 37184/59290
Iteration: 37185/59290
Iteration: 37186/59290
Iteration: 37187/59290
Iteration: 37188/59290
Iteration: 37189/59290
Iteration: 37190/59290
Iteration: 37191/59290
Iteration: 37192/59290

 63%|██████▎   | 37180/59290 [26:40<09:33, 38.56it/s]

Iteration: 37193/59290
Iteration: 37194/59290
Iteration: 37195/59290
Iteration: 37196/59290
Iteration: 37197/59290
Iteration: 37198/59290
Iteration: 37199/59290
Iteration: 37200/59290
Iteration: 37201/59290
Iteration: 37202/59290
Iteration: 37203/59290
Iteration: 37204/59290
Iteration: 37205/59290
Iteration: 37206/59290
Iteration: 37207/59290
Iteration: 37208/59290
Iteration: 37209/59290
Iteration: 37210/59290
Iteration: 37211/59290
Iteration: 37212/59290
Iteration: 37213/59290
Iteration: 37214/59290
Iteration: 37215/59290
Iteration: 37216/59290

 63%|██████▎   | 37204/59290 [26:41<08:26, 43.63it/s]

Iteration: 37217/59290
Iteration: 37218/59290
Iteration: 37219/59290
Iteration: 37220/59290
Iteration: 37221/59290
Iteration: 37222/59290
Iteration: 37223/59290
Iteration: 37224/59290
Iteration: 37225/59290
Iteration: 37226/59290
Iteration: 37227/59290
Iteration: 37228/59290
Iteration: 37229/59290
Iteration: 37230/59290
Iteration: 37231/59290
Iteration: 37232/59290
Iteration: 37233/59290
Iteration: 37234/59290
Iteration: 37235/59290
Iteration: 37236/59290
Iteration: 37237/59290
Iteration: 37238/59290
Iteration: 37239/59290
Iteration: 37240/59290

 63%|██████▎   | 37228/59290 [26:42<11:32, 31.84it/s]

Iteration: 37241/59290
Iteration: 37242/59290
Iteration: 37243/59290
Iteration: 37244/59290
Iteration: 37245/59290
Iteration: 37246/59290
Iteration: 37247/59290
Iteration: 37248/59290
Iteration: 37249/59290
Iteration: 37250/59290
Iteration: 37251/59290
Iteration: 37252/59290
Iteration: 37253/59290
Iteration: 37254/59290
Iteration: 37255/59290
Iteration: 37256/59290
Iteration: 37257/59290
Iteration: 37258/59290
Iteration: 37259/59290
Iteration: 37260/59290
Iteration: 37261/59290
Iteration: 37262/59290
Iteration: 37263/59290
Iteration: 37264/59290

 63%|██████▎   | 37252/59290 [26:44<16:04, 22.86it/s]

Iteration: 37265/59290
Iteration: 37266/59290
Iteration: 37267/59290
Iteration: 37268/59290
Iteration: 37269/59290
Iteration: 37270/59290
Iteration: 37271/59290
Iteration: 37272/59290
Iteration: 37273/59290
Iteration: 37274/59290
Iteration: 37275/59290
Iteration: 37276/59290
Iteration: 37277/59290
Iteration: 37278/59290
Iteration: 37279/59290
Iteration: 37280/59290
Iteration: 37281/59290
Iteration: 37282/59290
Iteration: 37283/59290
Iteration: 37284/59290
Iteration: 37285/59290
Iteration: 37286/59290
Iteration: 37287/59290
Iteration: 37288/59290

 63%|██████▎   | 37276/59290 [26:44<13:19, 27.54it/s]

Iteration: 37289/59290
Iteration: 37290/59290
Iteration: 37291/59290
Iteration: 37292/59290
Iteration: 37293/59290
Iteration: 37294/59290
Iteration: 37295/59290
Iteration: 37296/59290
Iteration: 37297/59290
Iteration: 37298/59290
Iteration: 37299/59290
Iteration: 37300/59290
Iteration: 37301/59290
Iteration: 37302/59290
Iteration: 37303/59290
Iteration: 37304/59290
Iteration: 37305/59290
Iteration: 37306/59290
Iteration: 37307/59290
Iteration: 37308/59290
Iteration: 37309/59290
Iteration: 37310/59290
Iteration: 37311/59290
Iteration: 37312/59290

 63%|██████▎   | 37300/59290 [26:44<11:07, 32.96it/s]

Iteration: 37313/59290
Iteration: 37314/59290
Iteration: 37315/59290
Iteration: 37316/59290
Iteration: 37317/59290
Iteration: 37318/59290
Iteration: 37319/59290
Iteration: 37320/59290
Iteration: 37321/59290
Iteration: 37322/59290
Iteration: 37323/59290
Iteration: 37324/59290
Iteration: 37325/59290
Iteration: 37326/59290
Iteration: 37327/59290
Iteration: 37328/59290
Iteration: 37329/59290
Iteration: 37330/59290
Iteration: 37331/59290
Iteration: 37332/59290
Iteration: 37333/59290
Iteration: 37334/59290
Iteration: 37335/59290
Iteration: 37336/59290

 63%|██████▎   | 37324/59290 [26:45<09:31, 38.42it/s]

Iteration: 37337/59290
Iteration: 37338/59290
Iteration: 37339/59290
Iteration: 37340/59290
Iteration: 37341/59290
Iteration: 37342/59290
Iteration: 37343/59290
Iteration: 37344/59290
Iteration: 37345/59290
Iteration: 37346/59290
Iteration: 37347/59290
Iteration: 37348/59290
Iteration: 37349/59290
Iteration: 37350/59290
Iteration: 37351/59290
Iteration: 37352/59290
Iteration: 37353/59290
Iteration: 37354/59290
Iteration: 37355/59290
Iteration: 37356/59290
Iteration: 37357/59290
Iteration: 37358/59290
Iteration: 37359/59290
Iteration: 37360/59290

 63%|██████▎   | 37348/59290 [26:46<13:45, 26.57it/s]

Iteration: 37361/59290
Iteration: 37362/59290
Iteration: 37363/59290
Iteration: 37364/59290
Iteration: 37365/59290
Iteration: 37366/59290
Iteration: 37367/59290
Iteration: 37368/59290
Iteration: 37369/59290
Iteration: 37370/59290
Iteration: 37371/59290
Iteration: 37372/59290
Iteration: 37373/59290
Iteration: 37374/59290
Iteration: 37375/59290
Iteration: 37376/59290
Iteration: 37377/59290
Iteration: 37378/59290
Iteration: 37379/59290
Iteration: 37380/59290
Iteration: 37381/59290
Iteration: 37382/59290
Iteration: 37383/59290
Iteration: 37384/59290

 63%|██████▎   | 37372/59290 [27:19<2:38:01,  2.31it/s]

Iteration: 37385/59290
Iteration: 37386/59290
Iteration: 37387/59290
Iteration: 37388/59290
Iteration: 37389/59290
Iteration: 37390/59290
Iteration: 37391/59290
Iteration: 37392/59290
Iteration: 37393/59290
Iteration: 37394/59290
Iteration: 37395/59290
Iteration: 37396/59290
Iteration: 37397/59290
Iteration: 37398/59290
Iteration: 37399/59290
Iteration: 37400/59290
Iteration: 37401/59290
Iteration: 37402/59290
Iteration: 37403/59290
Iteration: 37404/59290
Iteration: 37405/59290
Iteration: 37406/59290
Iteration: 37407/59290
Iteration: 37408/59290

 63%|██████▎   | 37396/59290 [27:20<1:55:48,  3.15it/s]

Iteration: 37409/59290
Iteration: 37410/59290
Iteration: 37411/59290
Iteration: 37412/59290
Iteration: 37413/59290
Iteration: 37414/59290
Iteration: 37415/59290
Iteration: 37416/59290
Iteration: 37417/59290
Iteration: 37418/59290
Iteration: 37419/59290
Iteration: 37420/59290
Iteration: 37421/59290
Iteration: 37422/59290
Iteration: 37423/59290
Iteration: 37424/59290
Iteration: 37425/59290
Iteration: 37426/59290
Iteration: 37427/59290
Iteration: 37428/59290
Iteration: 37429/59290
Iteration: 37430/59290
Iteration: 37431/59290
Iteration: 37432/59290

 63%|██████▎   | 37420/59290 [27:22<1:29:09,  4.09it/s]

Iteration: 37433/59290
Iteration: 37434/59290
Iteration: 37435/59290
Iteration: 37436/59290
Iteration: 37437/59290
Iteration: 37438/59290
Iteration: 37439/59290
Iteration: 37440/59290
Iteration: 37441/59290
Iteration: 37442/59290
Iteration: 37443/59290
Iteration: 37444/59290
Iteration: 37445/59290
Iteration: 37446/59290
Iteration: 37447/59290
Iteration: 37448/59290
Iteration: 37449/59290
Iteration: 37450/59290
Iteration: 37451/59290
Iteration: 37452/59290
Iteration: 37453/59290
Iteration: 37454/59290
Iteration: 37455/59290
Iteration: 37456/59290

 63%|██████▎   | 37444/59290 [27:22<1:04:37,  5.63it/s]

Iteration: 37457/59290
Iteration: 37458/59290
Iteration: 37459/59290
Iteration: 37460/59290
Iteration: 37461/59290
Iteration: 37462/59290
Iteration: 37463/59290
Iteration: 37464/59290
Iteration: 37465/59290
Iteration: 37466/59290
Iteration: 37467/59290
Iteration: 37468/59290
Iteration: 37469/59290
Iteration: 37470/59290
Iteration: 37471/59290
Iteration: 37472/59290
Iteration: 37473/59290
Iteration: 37474/59290
Iteration: 37475/59290
Iteration: 37476/59290
Iteration: 37477/59290
Iteration: 37478/59290
Iteration: 37479/59290
Iteration: 37480/59290

 63%|██████▎   | 37468/59290 [27:23<46:57,  7.74it/s]

Iteration: 37481/59290
Iteration: 37482/59290
Iteration: 37483/59290
Iteration: 37484/59290
Iteration: 37485/59290
Iteration: 37486/59290
Iteration: 37487/59290
Iteration: 37488/59290
Iteration: 37489/59290
Iteration: 37490/59290
Iteration: 37491/59290
Iteration: 37492/59290
Iteration: 37493/59290
Iteration: 37494/59290
Iteration: 37495/59290
Iteration: 37496/59290
Iteration: 37497/59290
Iteration: 37498/59290
Iteration: 37499/59290
Iteration: 37500/59290
Iteration: 37501/59290
Iteration: 37502/59290
Iteration: 37503/59290
Iteration: 37504/59290

 63%|██████▎   | 37492/59290 [27:23<34:37, 10.49it/s]

Iteration: 37505/59290
Iteration: 37506/59290
Iteration: 37507/59290
Iteration: 37508/59290
Iteration: 37509/59290
Iteration: 37510/59290
Iteration: 37511/59290
Iteration: 37512/59290
Iteration: 37513/59290
Iteration: 37514/59290
Iteration: 37515/59290
Iteration: 37516/59290
Iteration: 37517/59290
Iteration: 37518/59290
Iteration: 37519/59290
Iteration: 37520/59290
Iteration: 37521/59290
Iteration: 37522/59290
Iteration: 37523/59290
Iteration: 37524/59290
Iteration: 37525/59290
Iteration: 37526/59290
Iteration: 37527/59290
Iteration: 37528/59290

 63%|██████▎   | 37516/59290 [27:23<25:57, 13.98it/s]

Iteration: 37529/59290
Iteration: 37530/59290
Iteration: 37531/59290
Iteration: 37532/59290
Iteration: 37533/59290
Iteration: 37534/59290
Iteration: 37535/59290
Iteration: 37536/59290
Iteration: 37537/59290
Iteration: 37538/59290
Iteration: 37539/59290
Iteration: 37540/59290
Iteration: 37541/59290
Iteration: 37542/59290
Iteration: 37543/59290
Iteration: 37544/59290
Iteration: 37545/59290
Iteration: 37546/59290
Iteration: 37547/59290
Iteration: 37548/59290
Iteration: 37549/59290
Iteration: 37550/59290
Iteration: 37551/59290
Iteration: 37552/59290

 63%|██████▎   | 37540/59290 [27:24<19:55, 18.20it/s]

Iteration: 37553/59290
Iteration: 37554/59290
Iteration: 37555/59290
Iteration: 37556/59290
Iteration: 37557/59290
Iteration: 37558/59290
Iteration: 37559/59290
Iteration: 37560/59290
Iteration: 37561/59290
Iteration: 37562/59290
Iteration: 37563/59290
Iteration: 37564/59290
Iteration: 37565/59290
Iteration: 37566/59290
Iteration: 37567/59290
Iteration: 37568/59290
Iteration: 37569/59290
Iteration: 37570/59290
Iteration: 37571/59290
Iteration: 37572/59290
Iteration: 37573/59290
Iteration: 37574/59290
Iteration: 37575/59290
Iteration: 37576/59290

 63%|██████▎   | 37564/59290 [27:24<16:11, 22.36it/s]

Iteration: 37577/59290
Iteration: 37578/59290
Iteration: 37579/59290
Iteration: 37580/59290
Iteration: 37581/59290
Iteration: 37582/59290
Iteration: 37583/59290
Iteration: 37584/59290
Iteration: 37585/59290
Iteration: 37586/59290
Iteration: 37587/59290
Iteration: 37588/59290
Iteration: 37589/59290
Iteration: 37590/59290
Iteration: 37591/59290
Iteration: 37592/59290
Iteration: 37593/59290
Iteration: 37594/59290
Iteration: 37595/59290
Iteration: 37596/59290
Iteration: 37597/59290
Iteration: 37598/59290
Iteration: 37599/59290
Iteration: 37600/59290

 63%|██████▎   | 37588/59290 [27:25<13:00, 27.80it/s]

Iteration: 37601/59290
Iteration: 37602/59290
Iteration: 37603/59290
Iteration: 37604/59290
Iteration: 37605/59290
Iteration: 37606/59290
Iteration: 37607/59290
Iteration: 37608/59290
Iteration: 37609/59290
Iteration: 37610/59290
Iteration: 37611/59290
Iteration: 37612/59290
Iteration: 37613/59290
Iteration: 37614/59290
Iteration: 37615/59290
Iteration: 37616/59290
Iteration: 37617/59290
Iteration: 37618/59290
Iteration: 37619/59290
Iteration: 37620/59290
Iteration: 37621/59290
Iteration: 37622/59290
Iteration: 37623/59290
Iteration: 37624/59290

 63%|██████▎   | 37612/59290 [27:25<10:49, 33.36it/s]

Iteration: 37625/59290
Iteration: 37626/59290
Iteration: 37627/59290
Iteration: 37628/59290
Iteration: 37629/59290
Iteration: 37630/59290
Iteration: 37631/59290
Iteration: 37632/59290
Iteration: 37633/59290
Iteration: 37634/59290
Iteration: 37635/59290
Iteration: 37636/59290
Iteration: 37637/59290
Iteration: 37638/59290
Iteration: 37639/59290
Iteration: 37640/59290
Iteration: 37641/59290
Iteration: 37642/59290
Iteration: 37643/59290
Iteration: 37644/59290
Iteration: 37645/59290
Iteration: 37646/59290
Iteration: 37647/59290
Iteration: 37648/59290

 63%|██████▎   | 37636/59290 [27:25<09:16, 38.90it/s]

Iteration: 37649/59290
Iteration: 37650/59290
Iteration: 37651/59290
Iteration: 37652/59290
Iteration: 37653/59290
Iteration: 37654/59290
Iteration: 37655/59290
Iteration: 37656/59290
Iteration: 37657/59290
Iteration: 37658/59290
Iteration: 37659/59290
Iteration: 37660/59290
Iteration: 37661/59290
Iteration: 37662/59290
Iteration: 37663/59290
Iteration: 37664/59290
Iteration: 37665/59290
Iteration: 37666/59290
Iteration: 37667/59290
Iteration: 37668/59290
Iteration: 37669/59290
Iteration: 37670/59290
Iteration: 37671/59290
Iteration: 37672/59290

 64%|██████▎   | 37660/59290 [27:26<08:12, 43.90it/s]

Iteration: 37673/59290
Iteration: 37674/59290
Iteration: 37675/59290
Iteration: 37676/59290
Iteration: 37677/59290
Iteration: 37678/59290
Iteration: 37679/59290
Iteration: 37680/59290
Iteration: 37681/59290
Iteration: 37682/59290
Iteration: 37683/59290
Iteration: 37684/59290
Iteration: 37685/59290
Iteration: 37686/59290
Iteration: 37687/59290
Iteration: 37688/59290
Iteration: 37689/59290
Iteration: 37690/59290
Iteration: 37691/59290
Iteration: 37692/59290
Iteration: 37693/59290
Iteration: 37694/59290
Iteration: 37695/59290
Iteration: 37696/59290

 64%|██████▎   | 37684/59290 [27:26<07:27, 48.30it/s]

Iteration: 37697/59290
Iteration: 37698/59290
Iteration: 37699/59290
Iteration: 37700/59290
Iteration: 37701/59290
Iteration: 37702/59290
Iteration: 37703/59290
Iteration: 37704/59290
Iteration: 37705/59290
Iteration: 37706/59290
Iteration: 37707/59290
Iteration: 37708/59290
Iteration: 37709/59290
Iteration: 37710/59290
Iteration: 37711/59290
Iteration: 37712/59290
Iteration: 37713/59290
Iteration: 37714/59290
Iteration: 37715/59290
Iteration: 37716/59290
Iteration: 37717/59290
Iteration: 37718/59290
Iteration: 37719/59290
Iteration: 37720/59290

 64%|██████▎   | 37708/59290 [27:28<10:58, 32.80it/s]

Iteration: 37721/59290
Iteration: 37722/59290
Iteration: 37723/59290
Iteration: 37724/59290
Iteration: 37725/59290
Iteration: 37726/59290
Iteration: 37727/59290
Iteration: 37728/59290
Iteration: 37729/59290
Iteration: 37730/59290
Iteration: 37731/59290
Iteration: 37732/59290
Iteration: 37733/59290
Iteration: 37734/59290
Iteration: 37735/59290
Iteration: 37736/59290
Iteration: 37737/59290
Iteration: 37738/59290
Iteration: 37739/59290
Iteration: 37740/59290
Iteration: 37741/59290
Iteration: 37742/59290
Iteration: 37744/59290

 64%|██████▎   | 37731/59290 [27:29<15:59, 22.47it/s]

Iteration: 37745/59290
Iteration: 37746/59290
Iteration: 37747/59290
Iteration: 37748/59290
Iteration: 37749/59290
Iteration: 37750/59290
Iteration: 37751/59290
Iteration: 37752/59290

 64%|██████▎   | 37739/59290 [27:30<17:02, 21.07it/s]

Iteration: 37753/59290
Iteration: 37754/59290
Iteration: 37755/59290
Iteration: 37756/59290
Iteration: 37757/59290
Iteration: 37758/59290
Iteration: 37759/59290
Iteration: 37760/59290
Iteration: 37761/59290
Iteration: 37762/59290
Iteration: 37763/59290
Iteration: 37764/59290
Iteration: 37765/59290
Iteration: 37766/59290
Iteration: 37767/59290
Iteration: 37768/59290
Iteration: 37769/59290
Iteration: 37770/59290
Iteration: 37771/59290
Iteration: 37772/59290
Iteration: 37773/59290
Iteration: 37774/59290
Iteration: 37775/59290
Iteration: 37776/59290

 64%|██████▎   | 37763/59290 [27:30<13:29, 26.61it/s]

Iteration: 37777/59290
Iteration: 37778/59290
Iteration: 37779/59290
Iteration: 37780/59290
Iteration: 37781/59290
Iteration: 37782/59290
Iteration: 37783/59290
Iteration: 37784/59290
Iteration: 37785/59290
Iteration: 37786/59290
Iteration: 37787/59290
Iteration: 37788/59290
Iteration: 37789/59290
Iteration: 37790/59290
Iteration: 37791/59290
Iteration: 37792/59290
Iteration: 37793/59290
Iteration: 37794/59290
Iteration: 37795/59290
Iteration: 37796/59290
Iteration: 37797/59290
Iteration: 37798/59290
Iteration: 37799/59290
Iteration: 37800/59290

 64%|██████▎   | 37787/59290 [27:31<10:51, 33.03it/s]

Iteration: 37801/59290
Iteration: 37802/59290
Iteration: 37803/59290
Iteration: 37804/59290
Iteration: 37805/59290
Iteration: 37806/59290
Iteration: 37807/59290
Iteration: 37808/59290
Iteration: 37809/59290
Iteration: 37810/59290
Iteration: 37811/59290
Iteration: 37812/59290
Iteration: 37813/59290
Iteration: 37814/59290
Iteration: 37815/59290
Iteration: 37816/59290
Iteration: 37817/59290
Iteration: 37818/59290
Iteration: 37819/59290
Iteration: 37820/59290
Iteration: 37821/59290
Iteration: 37822/59290
Iteration: 37823/59290
Iteration: 37824/59290

 64%|██████▍   | 37811/59290 [27:31<09:09, 39.10it/s]

Iteration: 37825/59290
Iteration: 37826/59290
Iteration: 37827/59290
Iteration: 37828/59290
Iteration: 37829/59290
Iteration: 37830/59290
Iteration: 37831/59290
Iteration: 37832/59290
Iteration: 37833/59290
Iteration: 37834/59290
Iteration: 37835/59290
Iteration: 37836/59290
Iteration: 37837/59290
Iteration: 37838/59290
Iteration: 37839/59290
Iteration: 37840/59290
Iteration: 37841/59290
Iteration: 37842/59290
Iteration: 37843/59290
Iteration: 37844/59290
Iteration: 37845/59290
Iteration: 37846/59290
Iteration: 37847/59290
Iteration: 37848/59290

 64%|██████▍   | 37835/59290 [27:31<08:04, 44.28it/s]

Iteration: 37849/59290
Iteration: 37850/59290
Iteration: 37851/59290
Iteration: 37852/59290
Iteration: 37853/59290
Iteration: 37854/59290
Iteration: 37855/59290
Iteration: 37856/59290
Iteration: 37857/59290
Iteration: 37858/59290
Iteration: 37859/59290
Iteration: 37860/59290
Iteration: 37861/59290
Iteration: 37862/59290
Iteration: 37863/59290
Iteration: 37864/59290
Iteration: 37865/59290
Iteration: 37866/59290
Iteration: 37867/59290
Iteration: 37868/59290
Iteration: 37869/59290
Iteration: 37870/59290
Iteration: 37871/59290
Iteration: 37872/59290

 64%|██████▍   | 37859/59290 [27:33<10:44, 33.23it/s]

Iteration: 37873/59290
Iteration: 37874/59290
Iteration: 37875/59290
Iteration: 37876/59290
Iteration: 37877/59290
Iteration: 37878/59290
Iteration: 37879/59290
Iteration: 37880/59290
Iteration: 37881/59290
Iteration: 37882/59290
Iteration: 37883/59290
Iteration: 37884/59290
Iteration: 37885/59290
Iteration: 37886/59290
Iteration: 37887/59290
Iteration: 37888/59290
Iteration: 37889/59290
Iteration: 37890/59290
Iteration: 37891/59290
Iteration: 37892/59290
Iteration: 37893/59290
Iteration: 37894/59290
Iteration: 37895/59290
Iteration: 37896/59290

 64%|██████▍   | 37883/59290 [27:34<15:38, 22.82it/s]

Iteration: 37897/59290
Iteration: 37898/59290
Iteration: 37899/59290
Iteration: 37900/59290
Iteration: 37901/59290
Iteration: 37902/59290
Iteration: 37903/59290
Iteration: 37904/59290
Iteration: 37905/59290
Iteration: 37906/59290
Iteration: 37907/59290
Iteration: 37908/59290
Iteration: 37909/59290
Iteration: 37910/59290
Iteration: 37911/59290
Iteration: 37912/59290
Iteration: 37913/59290
Iteration: 37914/59290
Iteration: 37915/59290
Iteration: 37916/59290
Iteration: 37917/59290
Iteration: 37918/59290
Iteration: 37919/59290
Iteration: 37920/59290

 64%|██████▍   | 37907/59290 [27:35<12:42, 28.05it/s]

Iteration: 37921/59290
Iteration: 37922/59290
Iteration: 37923/59290
Iteration: 37924/59290
Iteration: 37925/59290
Iteration: 37926/59290
Iteration: 37927/59290
Iteration: 37928/59290
Iteration: 37929/59290
Iteration: 37930/59290
Iteration: 37931/59290
Iteration: 37932/59290
Iteration: 37933/59290
Iteration: 37934/59290
Iteration: 37935/59290
Iteration: 37936/59290
Iteration: 37937/59290
Iteration: 37938/59290
Iteration: 37939/59290
Iteration: 37940/59290
Iteration: 37941/59290
Iteration: 37942/59290
Iteration: 37943/59290
Iteration: 37944/59290

 64%|██████▍   | 37931/59290 [27:35<10:37, 33.51it/s]

Iteration: 37945/59290
Iteration: 37946/59290
Iteration: 37947/59290
Iteration: 37948/59290
Iteration: 37949/59290
Iteration: 37950/59290
Iteration: 37951/59290
Iteration: 37952/59290
Iteration: 37953/59290
Iteration: 37954/59290
Iteration: 37955/59290
Iteration: 37956/59290
Iteration: 37957/59290
Iteration: 37958/59290
Iteration: 37959/59290
Iteration: 37960/59290
Iteration: 37961/59290
Iteration: 37962/59290
Iteration: 37963/59290
Iteration: 37964/59290
Iteration: 37965/59290
Iteration: 37966/59290
Iteration: 37967/59290
Iteration: 37968/59290

 64%|██████▍   | 37955/59290 [27:36<09:33, 37.23it/s]

Iteration: 37969/59290
Iteration: 37970/59290
Iteration: 37971/59290
Iteration: 37972/59290
Iteration: 37973/59290
Iteration: 37974/59290
Iteration: 37975/59290
Iteration: 37976/59290
Iteration: 37977/59290
Iteration: 37978/59290
Iteration: 37979/59290
Iteration: 37980/59290
Iteration: 37981/59290
Iteration: 37982/59290
Iteration: 37983/59290
Iteration: 37984/59290
Iteration: 37985/59290
Iteration: 37986/59290
Iteration: 37987/59290
Iteration: 37988/59290
Iteration: 37989/59290
Iteration: 37990/59290
Iteration: 37991/59290
Iteration: 37992/59290

 64%|██████▍   | 37979/59290 [27:36<08:23, 42.34it/s]

Iteration: 37993/59290
Iteration: 37994/59290
Iteration: 37995/59290
Iteration: 37996/59290
Iteration: 37997/59290
Iteration: 37998/59290
Iteration: 37999/59290
Iteration: 38000/59290
Iteration: 38001/59290
Iteration: 38002/59290
Iteration: 38003/59290
Iteration: 38004/59290
Iteration: 38005/59290
Iteration: 38006/59290
Iteration: 38007/59290
Iteration: 38008/59290
Iteration: 38009/59290
Iteration: 38010/59290
Iteration: 38011/59290
Iteration: 38012/59290
Iteration: 38013/59290
Iteration: 38014/59290
Iteration: 38015/59290
Iteration: 38016/59290

 64%|██████▍   | 38003/59290 [27:37<11:35, 30.60it/s]

Iteration: 38017/59290
Iteration: 38018/59290
Iteration: 38019/59290
Iteration: 38020/59290
Iteration: 38021/59290
Iteration: 38022/59290
Iteration: 38023/59290
Iteration: 38024/59290
Iteration: 38025/59290
Iteration: 38026/59290
Iteration: 38027/59290
Iteration: 38028/59290
Iteration: 38029/59290
Iteration: 38030/59290
Iteration: 38031/59290
Iteration: 38032/59290
Iteration: 38033/59290
Iteration: 38034/59290
Iteration: 38035/59290
Iteration: 38036/59290
Iteration: 38037/59290
Iteration: 38038/59290
Iteration: 38039/59290
Iteration: 38040/59290

 64%|██████▍   | 38027/59290 [27:39<17:25, 20.34it/s]

Iteration: 38041/59290
Iteration: 38042/59290
Iteration: 38043/59290
Iteration: 38044/59290
Iteration: 38045/59290
Iteration: 38046/59290
Iteration: 38047/59290
Iteration: 38048/59290
Iteration: 38049/59290
Iteration: 38050/59290
Iteration: 38051/59290
Iteration: 38052/59290
Iteration: 38053/59290
Iteration: 38054/59290
Iteration: 38055/59290
Iteration: 38056/59290
Iteration: 38057/59290
Iteration: 38058/59290
Iteration: 38059/59290
Iteration: 38060/59290
Iteration: 38061/59290
Iteration: 38062/59290
Iteration: 38063/59290
Iteration: 38064/59290

 64%|██████▍   | 38051/59290 [27:40<13:49, 25.60it/s]

Iteration: 38065/59290
Iteration: 38066/59290
Iteration: 38067/59290
Iteration: 38068/59290
Iteration: 38069/59290
Iteration: 38070/59290
Iteration: 38071/59290
Iteration: 38072/59290
Iteration: 38073/59290
Iteration: 38074/59290
Iteration: 38075/59290
Iteration: 38076/59290
Iteration: 38077/59290
Iteration: 38078/59290
Iteration: 38079/59290
Iteration: 38080/59290
Iteration: 38081/59290
Iteration: 38082/59290
Iteration: 38083/59290
Iteration: 38084/59290
Iteration: 38085/59290
Iteration: 38086/59290
Iteration: 38087/59290
Iteration: 38088/59290

 64%|██████▍   | 38075/59290 [27:40<11:21, 31.15it/s]

Iteration: 38089/59290
Iteration: 38090/59290
Iteration: 38091/59290
Iteration: 38092/59290
Iteration: 38093/59290
Iteration: 38094/59290
Iteration: 38095/59290
Iteration: 38096/59290
Iteration: 38097/59290
Iteration: 38098/59290
Iteration: 38099/59290
Iteration: 38100/59290
Iteration: 38101/59290
Iteration: 38102/59290
Iteration: 38103/59290
Iteration: 38104/59290
Iteration: 38105/59290
Iteration: 38106/59290
Iteration: 38107/59290
Iteration: 38108/59290
Iteration: 38109/59290
Iteration: 38110/59290
Iteration: 38111/59290
Iteration: 38112/59290

 64%|██████▍   | 38099/59290 [27:41<09:52, 35.74it/s]

Iteration: 38113/59290
Iteration: 38114/59290
Iteration: 38115/59290
Iteration: 38116/59290
Iteration: 38117/59290
Iteration: 38118/59290
Iteration: 38119/59290
Iteration: 38120/59290
Iteration: 38121/59290
Iteration: 38122/59290
Iteration: 38123/59290
Iteration: 38124/59290
Iteration: 38125/59290
Iteration: 38126/59290
Iteration: 38127/59290
Iteration: 38128/59290
Iteration: 38129/59290
Iteration: 38130/59290
Iteration: 38131/59290
Iteration: 38132/59290
Iteration: 38133/59290
Iteration: 38134/59290
Iteration: 38135/59290
Iteration: 38136/59290

 64%|██████▍   | 38123/59290 [27:42<11:49, 29.82it/s]

Iteration: 38137/59290
Iteration: 38138/59290
Iteration: 38139/59290
Iteration: 38140/59290
Iteration: 38141/59290
Iteration: 38142/59290
Iteration: 38143/59290
Iteration: 38144/59290
Iteration: 38145/59290
Iteration: 38146/59290
Iteration: 38147/59290
Iteration: 38148/59290
Iteration: 38149/59290
Iteration: 38150/59290
Iteration: 38151/59290
Iteration: 38152/59290
Iteration: 38153/59290
Iteration: 38154/59290
Iteration: 38155/59290
Iteration: 38156/59290
Iteration: 38157/59290
Iteration: 38158/59290
Iteration: 38159/59290
Iteration: 38160/59290

 64%|██████▍   | 38147/59290 [27:43<15:40, 22.47it/s]

Iteration: 38161/59290
Iteration: 38162/59290
Iteration: 38163/59290
Iteration: 38164/59290
Iteration: 38165/59290
Iteration: 38166/59290
Iteration: 38167/59290
Iteration: 38168/59290
Iteration: 38169/59290
Iteration: 38170/59290
Iteration: 38171/59290
Iteration: 38172/59290
Iteration: 38173/59290
Iteration: 38174/59290
Iteration: 38175/59290
Iteration: 38176/59290
Iteration: 38177/59290
Iteration: 38178/59290
Iteration: 38179/59290
Iteration: 38180/59290
Iteration: 38181/59290
Iteration: 38182/59290
Iteration: 38183/59290
Iteration: 38184/59290

 64%|██████▍   | 38171/59290 [27:45<17:03, 20.64it/s]

Iteration: 38185/59290
Iteration: 38186/59290
Iteration: 38187/59290
Iteration: 38188/59290
Iteration: 38189/59290
Iteration: 38190/59290
Iteration: 38191/59290
Iteration: 38192/59290
Iteration: 38193/59290
Iteration: 38194/59290
Iteration: 38195/59290
Iteration: 38196/59290
Iteration: 38197/59290
Iteration: 38198/59290
Iteration: 38199/59290
Iteration: 38200/59290
Iteration: 38201/59290
Iteration: 38202/59290
Iteration: 38203/59290
Iteration: 38204/59290
Iteration: 38205/59290
Iteration: 38206/59290
Iteration: 38207/59290
Iteration: 38208/59290

 64%|██████▍   | 38195/59290 [27:45<13:39, 25.76it/s]

Iteration: 38209/59290
Iteration: 38210/59290
Iteration: 38211/59290
Iteration: 38212/59290
Iteration: 38213/59290
Iteration: 38214/59290
Iteration: 38215/59290
Iteration: 38216/59290
Iteration: 38217/59290
Iteration: 38218/59290
Iteration: 38219/59290
Iteration: 38220/59290
Iteration: 38221/59290
Iteration: 38222/59290
Iteration: 38223/59290
Iteration: 38224/59290
Iteration: 38225/59290
Iteration: 38226/59290
Iteration: 38227/59290
Iteration: 38228/59290
Iteration: 38229/59290
Iteration: 38230/59290
Iteration: 38231/59290
Iteration: 38232/59290

 64%|██████▍   | 38219/59290 [27:46<11:12, 31.32it/s]

Iteration: 38233/59290
Iteration: 38234/59290
Iteration: 38235/59290
Iteration: 38236/59290
Iteration: 38237/59290
Iteration: 38238/59290
Iteration: 38239/59290
Iteration: 38240/59290
Iteration: 38241/59290
Iteration: 38242/59290
Iteration: 38243/59290
Iteration: 38244/59290
Iteration: 38245/59290
Iteration: 38246/59290
Iteration: 38247/59290
Iteration: 38248/59290
Iteration: 38249/59290
Iteration: 38250/59290
Iteration: 38251/59290
Iteration: 38252/59290
Iteration: 38253/59290
Iteration: 38254/59290
Iteration: 38255/59290
Iteration: 38256/59290

 65%|██████▍   | 38243/59290 [27:46<09:32, 36.75it/s]

Iteration: 38257/59290
Iteration: 38258/59290
Iteration: 38259/59290
Iteration: 38260/59290
Iteration: 38261/59290
Iteration: 38262/59290
Iteration: 38263/59290
Iteration: 38264/59290
Iteration: 38265/59290
Iteration: 38266/59290
Iteration: 38267/59290
Iteration: 38268/59290
Iteration: 38269/59290
Iteration: 38270/59290
Iteration: 38271/59290
Iteration: 38272/59290
Iteration: 38273/59290
Iteration: 38274/59290
Iteration: 38275/59290
Iteration: 38276/59290
Iteration: 38277/59290
Iteration: 38278/59290
Iteration: 38279/59290
Iteration: 38280/59290

 65%|██████▍   | 38267/59290 [27:46<08:19, 42.10it/s]

Iteration: 38281/59290
Iteration: 38282/59290
Iteration: 38283/59290
Iteration: 38284/59290
Iteration: 38285/59290
Iteration: 38286/59290
Iteration: 38287/59290
Iteration: 38288/59290
Iteration: 38289/59290
Iteration: 38290/59290
Iteration: 38291/59290
Iteration: 38292/59290
Iteration: 38293/59290
Iteration: 38294/59290
Iteration: 38295/59290
Iteration: 38296/59290
Iteration: 38297/59290
Iteration: 38298/59290
Iteration: 38299/59290
Iteration: 38300/59290
Iteration: 38301/59290
Iteration: 38302/59290
Iteration: 38303/59290
Iteration: 38304/59290

 65%|██████▍   | 38291/59290 [27:48<10:57, 31.93it/s]

Iteration: 38305/59290
Iteration: 38306/59290
Iteration: 38307/59290
Iteration: 38308/59290
Iteration: 38309/59290
Iteration: 38310/59290
Iteration: 38311/59290
Iteration: 38312/59290
Iteration: 38313/59290
Iteration: 38314/59290
Iteration: 38315/59290
Iteration: 38316/59290
Iteration: 38317/59290
Iteration: 38318/59290
Iteration: 38319/59290
Iteration: 38320/59290
Iteration: 38321/59290
Iteration: 38322/59290
Iteration: 38323/59290
Iteration: 38324/59290
Iteration: 38325/59290
Iteration: 38326/59290
Iteration: 38327/59290
Iteration: 38328/59290

 65%|██████▍   | 38315/59290 [27:49<14:47, 23.62it/s]

Iteration: 38329/59290
Iteration: 38330/59290
Iteration: 38331/59290
Iteration: 38332/59290
Iteration: 38333/59290
Iteration: 38334/59290
Iteration: 38335/59290
Iteration: 38336/59290
Iteration: 38337/59290
Iteration: 38338/59290
Iteration: 38339/59290
Iteration: 38340/59290
Iteration: 38341/59290
Iteration: 38342/59290
Iteration: 38343/59290
Iteration: 38344/59290
Iteration: 38345/59290
Iteration: 38346/59290
Iteration: 38347/59290
Iteration: 38348/59290
Iteration: 38349/59290
Iteration: 38350/59290
Iteration: 38351/59290
Iteration: 38352/59290

 65%|██████▍   | 38339/59290 [27:50<12:17, 28.39it/s]

Iteration: 38353/59290
Iteration: 38354/59290
Iteration: 38355/59290
Iteration: 38356/59290
Iteration: 38357/59290
Iteration: 38358/59290
Iteration: 38359/59290
Iteration: 38360/59290
Iteration: 38361/59290
Iteration: 38362/59290
Iteration: 38363/59290
Iteration: 38364/59290
Iteration: 38365/59290
Iteration: 38366/59290
Iteration: 38367/59290
Iteration: 38368/59290
Iteration: 38369/59290
Iteration: 38370/59290
Iteration: 38371/59290
Iteration: 38372/59290
Iteration: 38373/59290
Iteration: 38374/59290
Iteration: 38375/59290
Iteration: 38376/59290

 65%|██████▍   | 38363/59290 [27:50<10:13, 34.12it/s]

Iteration: 38377/59290
Iteration: 38378/59290
Iteration: 38379/59290
Iteration: 38380/59290
Iteration: 38381/59290
Iteration: 38382/59290
Iteration: 38383/59290
Iteration: 38384/59290
Iteration: 38385/59290
Iteration: 38386/59290
Iteration: 38387/59290
Iteration: 38388/59290
Iteration: 38389/59290
Iteration: 38390/59290
Iteration: 38391/59290
Iteration: 38392/59290
Iteration: 38393/59290
Iteration: 38394/59290
Iteration: 38395/59290
Iteration: 38396/59290
Iteration: 38397/59290
Iteration: 38398/59290
Iteration: 38399/59290
Iteration: 38400/59290

 65%|██████▍   | 38387/59290 [27:50<08:48, 39.55it/s]

Iteration: 38401/59290
Iteration: 38402/59290
Iteration: 38403/59290
Iteration: 38404/59290
Iteration: 38405/59290
Iteration: 38406/59290
Iteration: 38407/59290
Iteration: 38408/59290
Iteration: 38409/59290
Iteration: 38410/59290
Iteration: 38411/59290
Iteration: 38412/59290
Iteration: 38413/59290
Iteration: 38414/59290
Iteration: 38415/59290
Iteration: 38416/59290
Iteration: 38417/59290
Iteration: 38418/59290
Iteration: 38419/59290
Iteration: 38420/59290
Iteration: 38421/59290
Iteration: 38422/59290
Iteration: 38423/59290
Iteration: 38424/59290

 65%|██████▍   | 38411/59290 [27:51<07:48, 44.55it/s]

Iteration: 38425/59290
Iteration: 38426/59290
Iteration: 38427/59290
Iteration: 38428/59290
Iteration: 38429/59290
Iteration: 38430/59290
Iteration: 38431/59290
Iteration: 38432/59290
Iteration: 38433/59290
Iteration: 38434/59290
Iteration: 38435/59290
Iteration: 38436/59290
Iteration: 38437/59290
Iteration: 38438/59290
Iteration: 38439/59290
Iteration: 38440/59290
Iteration: 38441/59290
Iteration: 38442/59290
Iteration: 38443/59290
Iteration: 38444/59290
Iteration: 38445/59290
Iteration: 38446/59290
Iteration: 38447/59290
Iteration: 38448/59290

 65%|██████▍   | 38435/59290 [27:51<07:07, 48.76it/s]

Iteration: 38449/59290
Iteration: 38450/59290
Iteration: 38451/59290
Iteration: 38452/59290
Iteration: 38453/59290
Iteration: 38454/59290
Iteration: 38455/59290
Iteration: 38456/59290
Iteration: 38457/59290
Iteration: 38458/59290
Iteration: 38459/59290
Iteration: 38460/59290
Iteration: 38461/59290
Iteration: 38462/59290
Iteration: 38463/59290
Iteration: 38464/59290
Iteration: 38465/59290
Iteration: 38466/59290
Iteration: 38467/59290
Iteration: 38468/59290
Iteration: 38469/59290
Iteration: 38470/59290
Iteration: 38471/59290
Iteration: 38472/59290

 65%|██████▍   | 38459/59290 [27:52<06:36, 52.51it/s]

Iteration: 38473/59290
Iteration: 38474/59290
Iteration: 38475/59290
Iteration: 38476/59290
Iteration: 38477/59290
Iteration: 38478/59290
Iteration: 38479/59290
Iteration: 38480/59290
Iteration: 38481/59290
Iteration: 38482/59290
Iteration: 38483/59290
Iteration: 38484/59290
Iteration: 38485/59290
Iteration: 38486/59290
Iteration: 38487/59290
Iteration: 38488/59290
Iteration: 38489/59290
Iteration: 38490/59290
Iteration: 38491/59290
Iteration: 38492/59290
Iteration: 38493/59290
Iteration: 38494/59290
Iteration: 38495/59290
Iteration: 38496/59290

 65%|██████▍   | 38483/59290 [27:52<06:18, 55.00it/s]

Iteration: 38497/59290
Iteration: 38498/59290
Iteration: 38499/59290
Iteration: 38500/59290
Iteration: 38501/59290
Iteration: 38502/59290
Iteration: 38503/59290
Iteration: 38504/59290
Iteration: 38505/59290
Iteration: 38506/59290
Iteration: 38507/59290
Iteration: 38508/59290
Iteration: 38509/59290
Iteration: 38510/59290
Iteration: 38511/59290
Iteration: 38512/59290
Iteration: 38513/59290
Iteration: 38514/59290
Iteration: 38515/59290
Iteration: 38516/59290
Iteration: 38517/59290
Iteration: 38518/59290
Iteration: 38519/59290
Iteration: 38520/59290

 65%|██████▍   | 38507/59290 [27:52<06:34, 52.65it/s]

Iteration: 38521/59290
Iteration: 38522/59290
Iteration: 38523/59290
Iteration: 38524/59290
Iteration: 38525/59290
Iteration: 38526/59290
Iteration: 38527/59290
Iteration: 38528/59290
Iteration: 38529/59290
Iteration: 38530/59290
Iteration: 38531/59290
Iteration: 38532/59290
Iteration: 38533/59290
Iteration: 38534/59290
Iteration: 38535/59290
Iteration: 38536/59290
Iteration: 38537/59290
Iteration: 38538/59290
Iteration: 38539/59290
Iteration: 38540/59290
Iteration: 38541/59290
Iteration: 38542/59290
Iteration: 38543/59290
Iteration: 38544/59290

 65%|██████▍   | 38531/59290 [27:53<06:15, 55.26it/s]

Iteration: 38545/59290
Iteration: 38546/59290
Iteration: 38547/59290
Iteration: 38548/59290
Iteration: 38549/59290
Iteration: 38550/59290
Iteration: 38551/59290
Iteration: 38552/59290
Iteration: 38553/59290
Iteration: 38554/59290
Iteration: 38555/59290
Iteration: 38556/59290
Iteration: 38557/59290
Iteration: 38558/59290
Iteration: 38559/59290
Iteration: 38560/59290
Iteration: 38561/59290
Iteration: 38562/59290
Iteration: 38563/59290
Iteration: 38564/59290
Iteration: 38565/59290
Iteration: 38566/59290
Iteration: 38567/59290
Iteration: 38568/59290

 65%|██████▌   | 38555/59290 [27:54<09:36, 35.99it/s]

Iteration: 38569/59290
Iteration: 38570/59290
Iteration: 38571/59290
Iteration: 38572/59290
Iteration: 38573/59290
Iteration: 38574/59290
Iteration: 38575/59290
Iteration: 38576/59290
Iteration: 38577/59290
Iteration: 38578/59290
Iteration: 38579/59290
Iteration: 38580/59290
Iteration: 38581/59290
Iteration: 38582/59290
Iteration: 38583/59290
Iteration: 38584/59290
Iteration: 38585/59290
Iteration: 38586/59290
Iteration: 38587/59290
Iteration: 38588/59290
Iteration: 38589/59290
Iteration: 38590/59290
Iteration: 38591/59290
Iteration: 38592/59290

 65%|██████▌   | 38579/59290 [27:56<14:15, 24.20it/s]

Iteration: 38593/59290
Iteration: 38594/59290
Iteration: 38595/59290
Iteration: 38596/59290
Iteration: 38597/59290
Iteration: 38598/59290
Iteration: 38599/59290
Iteration: 38600/59290
Iteration: 38601/59290
Iteration: 38602/59290
Iteration: 38603/59290
Iteration: 38604/59290
Iteration: 38605/59290
Iteration: 38606/59290
Iteration: 38607/59290
Iteration: 38608/59290
Iteration: 38609/59290
Iteration: 38610/59290
Iteration: 38611/59290
Iteration: 38612/59290
Iteration: 38613/59290
Iteration: 38614/59290
Iteration: 38615/59290
Iteration: 38616/59290

 65%|██████▌   | 38603/59290 [27:56<12:00, 28.73it/s]

Iteration: 38617/59290
Iteration: 38618/59290
Iteration: 38619/59290
Iteration: 38620/59290
Iteration: 38621/59290
Iteration: 38622/59290
Iteration: 38623/59290
Iteration: 38624/59290
Iteration: 38625/59290
Iteration: 38626/59290
Iteration: 38627/59290
Iteration: 38628/59290
Iteration: 38629/59290
Iteration: 38630/59290
Iteration: 38631/59290
Iteration: 38632/59290
Iteration: 38633/59290
Iteration: 38634/59290
Iteration: 38635/59290
Iteration: 38636/59290
Iteration: 38637/59290
Iteration: 38638/59290
Iteration: 38639/59290
Iteration: 38640/59290

 65%|██████▌   | 38627/59290 [27:57<12:02, 28.58it/s]

Iteration: 38641/59290
Iteration: 38642/59290
Iteration: 38643/59290
Iteration: 38644/59290
Iteration: 38645/59290
Iteration: 38646/59290
Iteration: 38647/59290
Iteration: 38648/59290
Iteration: 38649/59290
Iteration: 38650/59290
Iteration: 38651/59290
Iteration: 38652/59290
Iteration: 38653/59290
Iteration: 38654/59290
Iteration: 38655/59290
Iteration: 38656/59290
Iteration: 38657/59290
Iteration: 38658/59290
Iteration: 38659/59290
Iteration: 38660/59290
Iteration: 38661/59290
Iteration: 38662/59290
Iteration: 38663/59290
Iteration: 38664/59290

 65%|██████▌   | 38651/59290 [27:58<13:34, 25.35it/s]

Iteration: 38665/59290
Iteration: 38666/59290
Iteration: 38667/59290
Iteration: 38668/59290
Iteration: 38669/59290
Iteration: 38670/59290
Iteration: 38671/59290
Iteration: 38672/59290
Iteration: 38673/59290
Iteration: 38674/59290
Iteration: 38675/59290
Iteration: 38676/59290
Iteration: 38677/59290
Iteration: 38678/59290
Iteration: 38679/59290
Iteration: 38680/59290
Iteration: 38681/59290
Iteration: 38682/59290
Iteration: 38683/59290
Iteration: 38684/59290
Iteration: 38685/59290
Iteration: 38686/59290
Iteration: 38687/59290
Iteration: 38688/59290

 65%|██████▌   | 38675/59290 [28:00<17:13, 19.96it/s]

Iteration: 38689/59290
Iteration: 38690/59290
Iteration: 38691/59290
Iteration: 38692/59290
Iteration: 38693/59290
Iteration: 38694/59290
Iteration: 38695/59290
Iteration: 38696/59290
Iteration: 38697/59290
Iteration: 38698/59290
Iteration: 38699/59290
Iteration: 38700/59290
Iteration: 38701/59290
Iteration: 38702/59290
Iteration: 38703/59290
Iteration: 38704/59290
Iteration: 38705/59290
Iteration: 38706/59290
Iteration: 38707/59290
Iteration: 38708/59290
Iteration: 38709/59290
Iteration: 38710/59290
Iteration: 38711/59290
Iteration: 38712/59290

 65%|██████▌   | 38699/59290 [28:01<15:21, 22.34it/s]

Iteration: 38713/59290
Iteration: 38714/59290
Iteration: 38715/59290
Iteration: 38716/59290
Iteration: 38717/59290
Iteration: 38718/59290
Iteration: 38719/59290
Iteration: 38720/59290
Iteration: 38721/59290
Iteration: 38722/59290
Iteration: 38723/59290
Iteration: 38724/59290
Iteration: 38725/59290
Iteration: 38726/59290
Iteration: 38727/59290
Iteration: 38728/59290
Iteration: 38729/59290
Iteration: 38730/59290
Iteration: 38731/59290
Iteration: 38732/59290
Iteration: 38733/59290
Iteration: 38734/59290
Iteration: 38735/59290
Iteration: 38736/59290

 65%|██████▌   | 38723/59290 [28:01<12:22, 27.69it/s]

Iteration: 38737/59290
Iteration: 38738/59290
Iteration: 38739/59290
Iteration: 38740/59290
Iteration: 38741/59290
Iteration: 38742/59290
Iteration: 38743/59290
Iteration: 38744/59290
Iteration: 38745/59290
Iteration: 38746/59290
Iteration: 38747/59290
Iteration: 38748/59290
Iteration: 38749/59290
Iteration: 38750/59290
Iteration: 38751/59290
Iteration: 38752/59290
Iteration: 38753/59290
Iteration: 38754/59290
Iteration: 38755/59290
Iteration: 38756/59290
Iteration: 38757/59290
Iteration: 38758/59290
Iteration: 38759/59290
Iteration: 38760/59290

 65%|██████▌   | 38747/59290 [28:02<10:17, 33.26it/s]

Iteration: 38761/59290
Iteration: 38762/59290
Iteration: 38763/59290
Iteration: 38764/59290
Iteration: 38765/59290
Iteration: 38766/59290
Iteration: 38767/59290
Iteration: 38768/59290
Iteration: 38769/59290
Iteration: 38770/59290
Iteration: 38771/59290
Iteration: 38772/59290
Iteration: 38773/59290
Iteration: 38774/59290
Iteration: 38775/59290
Iteration: 38776/59290
Iteration: 38777/59290
Iteration: 38778/59290
Iteration: 38779/59290
Iteration: 38780/59290
Iteration: 38781/59290
Iteration: 38782/59290
Iteration: 38783/59290
Iteration: 38784/59290

 65%|██████▌   | 38771/59290 [28:02<08:49, 38.77it/s]

Iteration: 38785/59290
Iteration: 38786/59290
Iteration: 38787/59290
Iteration: 38788/59290
Iteration: 38789/59290
Iteration: 38790/59290
Iteration: 38791/59290
Iteration: 38792/59290
Iteration: 38793/59290
Iteration: 38794/59290
Iteration: 38795/59290
Iteration: 38796/59290
Iteration: 38797/59290
Iteration: 38798/59290
Iteration: 38799/59290
Iteration: 38800/59290
Iteration: 38801/59290
Iteration: 38802/59290
Iteration: 38803/59290
Iteration: 38804/59290
Iteration: 38805/59290
Iteration: 38806/59290
Iteration: 38807/59290
Iteration: 38808/59290

 65%|██████▌   | 38795/59290 [28:03<12:02, 28.38it/s]

Iteration: 38809/59290
Iteration: 38810/59290
Iteration: 38811/59290
Iteration: 38812/59290
Iteration: 38813/59290
Iteration: 38814/59290
Iteration: 38815/59290
Iteration: 38816/59290
Iteration: 38817/59290
Iteration: 38818/59290
Iteration: 38819/59290
Iteration: 38820/59290
Iteration: 38821/59290
Iteration: 38822/59290
Iteration: 38823/59290
Iteration: 38824/59290
Iteration: 38825/59290
Iteration: 38826/59290
Iteration: 38827/59290
Iteration: 38828/59290
Iteration: 38829/59290
Iteration: 38830/59290
Iteration: 38831/59290
Iteration: 38832/59290

 65%|██████▌   | 38819/59290 [28:05<15:54, 21.46it/s]

Iteration: 38833/59290
Iteration: 38834/59290
Iteration: 38835/59290
Iteration: 38836/59290
Iteration: 38837/59290
Iteration: 38838/59290
Iteration: 38839/59290
Iteration: 38840/59290
Iteration: 38841/59290
Iteration: 38842/59290
Iteration: 38843/59290
Iteration: 38844/59290
Iteration: 38845/59290
Iteration: 38846/59290
Iteration: 38847/59290
Iteration: 38848/59290
Iteration: 38849/59290
Iteration: 38850/59290
Iteration: 38851/59290
Iteration: 38852/59290
Iteration: 38853/59290
Iteration: 38854/59290
Iteration: 38855/59290
Iteration: 38856/59290

 66%|██████▌   | 38843/59290 [28:06<12:49, 26.58it/s]

Iteration: 38857/59290
Iteration: 38858/59290
Iteration: 38859/59290
Iteration: 38860/59290
Iteration: 38861/59290
Iteration: 38862/59290
Iteration: 38863/59290
Iteration: 38864/59290
Iteration: 38865/59290
Iteration: 38866/59290
Iteration: 38867/59290
Iteration: 38868/59290
Iteration: 38869/59290
Iteration: 38870/59290
Iteration: 38871/59290
Iteration: 38872/59290
Iteration: 38873/59290
Iteration: 38874/59290
Iteration: 38875/59290
Iteration: 38876/59290
Iteration: 38877/59290
Iteration: 38878/59290
Iteration: 38879/59290
Iteration: 38880/59290

 66%|██████▌   | 38867/59290 [28:06<10:48, 31.51it/s]

Iteration: 38881/59290
Iteration: 38882/59290
Iteration: 38883/59290
Iteration: 38884/59290
Iteration: 38885/59290
Iteration: 38886/59290
Iteration: 38887/59290
Iteration: 38888/59290
Iteration: 38889/59290
Iteration: 38890/59290
Iteration: 38891/59290
Iteration: 38892/59290
Iteration: 38893/59290
Iteration: 38894/59290
Iteration: 38895/59290
Iteration: 38896/59290
Iteration: 38897/59290
Iteration: 38898/59290
Iteration: 38899/59290
Iteration: 38900/59290
Iteration: 38901/59290
Iteration: 38902/59290
Iteration: 38903/59290
Iteration: 38904/59290

 66%|██████▌   | 38891/59290 [28:08<14:46, 23.01it/s]

Iteration: 38905/59290
Iteration: 38906/59290
Iteration: 38907/59290
Iteration: 38908/59290
Iteration: 38909/59290
Iteration: 38910/59290
Iteration: 38911/59290
Iteration: 38912/59290
Iteration: 38913/59290
Iteration: 38914/59290
Iteration: 38915/59290
Iteration: 38916/59290
Iteration: 38917/59290
Iteration: 38918/59290
Iteration: 38919/59290
Iteration: 38920/59290
Iteration: 38921/59290
Iteration: 38922/59290
Iteration: 38923/59290
Iteration: 38924/59290
Iteration: 38925/59290
Iteration: 38926/59290
Iteration: 38927/59290
Iteration: 38928/59290

 66%|██████▌   | 38915/59290 [28:09<17:28, 19.43it/s]

Iteration: 38929/59290
Iteration: 38930/59290
Iteration: 38931/59290
Iteration: 38932/59290
Iteration: 38933/59290
Iteration: 38934/59290
Iteration: 38935/59290
Iteration: 38936/59290
Iteration: 38937/59290
Iteration: 38938/59290
Iteration: 38939/59290
Iteration: 38940/59290
Iteration: 38941/59290
Iteration: 38942/59290
Iteration: 38943/59290
Iteration: 38944/59290
Iteration: 38945/59290
Iteration: 38946/59290
Iteration: 38947/59290
Iteration: 38948/59290
Iteration: 38949/59290
Iteration: 38950/59290
Iteration: 38951/59290
Iteration: 38952/59290

 66%|██████▌   | 38939/59290 [28:10<15:02, 22.54it/s]

Iteration: 38953/59290
Iteration: 38954/59290
Iteration: 38955/59290
Iteration: 38956/59290
Iteration: 38957/59290
Iteration: 38958/59290
Iteration: 38959/59290
Iteration: 38960/59290
Iteration: 38961/59290
Iteration: 38962/59290
Iteration: 38963/59290
Iteration: 38964/59290
Iteration: 38965/59290
Iteration: 38966/59290
Iteration: 38967/59290
Iteration: 38968/59290
Iteration: 38969/59290
Iteration: 38970/59290
Iteration: 38971/59290
Iteration: 38972/59290
Iteration: 38973/59290
Iteration: 38974/59290
Iteration: 38975/59290
Iteration: 38976/59290

 66%|██████▌   | 38963/59290 [28:11<12:40, 26.74it/s]

Iteration: 38977/59290
Iteration: 38978/59290
Iteration: 38979/59290
Iteration: 38980/59290
Iteration: 38981/59290
Iteration: 38982/59290
Iteration: 38983/59290
Iteration: 38984/59290
Iteration: 38985/59290
Iteration: 38986/59290
Iteration: 38987/59290
Iteration: 38988/59290
Iteration: 38989/59290
Iteration: 38990/59290
Iteration: 38991/59290
Iteration: 38992/59290
Iteration: 38993/59290
Iteration: 38994/59290
Iteration: 38995/59290
Iteration: 38996/59290
Iteration: 38997/59290
Iteration: 38998/59290
Iteration: 38999/59290
Iteration: 39000/59290

 66%|██████▌   | 38987/59290 [28:11<10:30, 32.19it/s]

Iteration: 39001/59290
Iteration: 39002/59290
Iteration: 39003/59290
Iteration: 39004/59290
Iteration: 39005/59290
Iteration: 39006/59290
Iteration: 39007/59290
Iteration: 39008/59290
Iteration: 39009/59290
Iteration: 39010/59290
Iteration: 39011/59290
Iteration: 39012/59290
Iteration: 39013/59290
Iteration: 39014/59290
Iteration: 39015/59290
Iteration: 39016/59290
Iteration: 39017/59290
Iteration: 39018/59290
Iteration: 39019/59290
Iteration: 39020/59290
Iteration: 39021/59290
Iteration: 39022/59290
Iteration: 39023/59290
Iteration: 39024/59290

 66%|██████▌   | 39011/59290 [28:12<11:54, 28.38it/s]

Iteration: 39025/59290
Iteration: 39026/59290
Iteration: 39027/59290
Iteration: 39028/59290
Iteration: 39029/59290
Iteration: 39030/59290
Iteration: 39031/59290
Iteration: 39032/59290
Iteration: 39033/59290
Iteration: 39034/59290
Iteration: 39035/59290
Iteration: 39036/59290
Iteration: 39037/59290
Iteration: 39038/59290
Iteration: 39039/59290
Iteration: 39040/59290
Iteration: 39041/59290
Iteration: 39042/59290
Iteration: 39043/59290
Iteration: 39044/59290
Iteration: 39045/59290
Iteration: 39046/59290
Iteration: 39047/59290
Iteration: 39048/59290

 66%|██████▌   | 39035/59290 [28:14<15:29, 21.80it/s]

Iteration: 39049/59290
Iteration: 39050/59290
Iteration: 39051/59290
Iteration: 39052/59290
Iteration: 39053/59290
Iteration: 39054/59290
Iteration: 39055/59290
Iteration: 39056/59290
Iteration: 39057/59290
Iteration: 39058/59290
Iteration: 39059/59290
Iteration: 39060/59290
Iteration: 39061/59290
Iteration: 39062/59290
Iteration: 39063/59290
Iteration: 39064/59290
Iteration: 39065/59290
Iteration: 39066/59290
Iteration: 39067/59290
Iteration: 39068/59290
Iteration: 39069/59290
Iteration: 39070/59290
Iteration: 39071/59290
Iteration: 39072/59290

 66%|██████▌   | 39059/59290 [28:14<12:29, 26.97it/s]

Iteration: 39073/59290
Iteration: 39074/59290
Iteration: 39075/59290
Iteration: 39076/59290
Iteration: 39077/59290
Iteration: 39078/59290
Iteration: 39079/59290
Iteration: 39080/59290
Iteration: 39081/59290
Iteration: 39082/59290
Iteration: 39083/59290
Iteration: 39084/59290
Iteration: 39085/59290
Iteration: 39086/59290
Iteration: 39087/59290
Iteration: 39088/59290
Iteration: 39089/59290
Iteration: 39090/59290
Iteration: 39091/59290
Iteration: 39092/59290
Iteration: 39093/59290
Iteration: 39094/59290
Iteration: 39095/59290
Iteration: 39096/59290

 66%|██████▌   | 39083/59290 [28:14<10:22, 32.48it/s]

Iteration: 39097/59290
Iteration: 39098/59290
Iteration: 39099/59290
Iteration: 39100/59290
Iteration: 39101/59290
Iteration: 39102/59290
Iteration: 39103/59290
Iteration: 39104/59290
Iteration: 39105/59290
Iteration: 39106/59290
Iteration: 39107/59290
Iteration: 39108/59290
Iteration: 39109/59290
Iteration: 39110/59290
Iteration: 39111/59290
Iteration: 39112/59290
Iteration: 39113/59290
Iteration: 39114/59290
Iteration: 39115/59290
Iteration: 39116/59290
Iteration: 39117/59290
Iteration: 39118/59290
Iteration: 39119/59290
Iteration: 39120/59290

 66%|██████▌   | 39107/59290 [28:15<08:50, 38.08it/s]

Iteration: 39121/59290
Iteration: 39122/59290
Iteration: 39123/59290
Iteration: 39124/59290
Iteration: 39125/59290
Iteration: 39126/59290
Iteration: 39127/59290
Iteration: 39128/59290
Iteration: 39129/59290
Iteration: 39130/59290
Iteration: 39131/59290
Iteration: 39132/59290
Iteration: 39133/59290
Iteration: 39134/59290
Iteration: 39135/59290
Iteration: 39136/59290
Iteration: 39137/59290
Iteration: 39138/59290
Iteration: 39139/59290
Iteration: 39140/59290
Iteration: 39141/59290
Iteration: 39142/59290
Iteration: 39143/59290
Iteration: 39144/59290

 66%|██████▌   | 39131/59290 [28:15<07:46, 43.21it/s]

Iteration: 39145/59290
Iteration: 39146/59290
Iteration: 39147/59290
Iteration: 39148/59290
Iteration: 39149/59290
Iteration: 39150/59290
Iteration: 39151/59290
Iteration: 39152/59290
Iteration: 39153/59290
Iteration: 39154/59290
Iteration: 39155/59290
Iteration: 39156/59290
Iteration: 39157/59290
Iteration: 39158/59290
Iteration: 39159/59290
Iteration: 39160/59290
Iteration: 39161/59290
Iteration: 39162/59290
Iteration: 39163/59290
Iteration: 39164/59290
Iteration: 39165/59290
Iteration: 39166/59290
Iteration: 39167/59290
Iteration: 39168/59290

 66%|██████▌   | 39155/59290 [28:16<07:00, 47.84it/s]

Iteration: 39169/59290
Iteration: 39170/59290
Iteration: 39171/59290
Iteration: 39172/59290
Iteration: 39173/59290
Iteration: 39174/59290
Iteration: 39175/59290
Iteration: 39176/59290
Iteration: 39177/59290
Iteration: 39178/59290
Iteration: 39179/59290
Iteration: 39180/59290
Iteration: 39181/59290
Iteration: 39182/59290
Iteration: 39183/59290
Iteration: 39184/59290
Iteration: 39185/59290
Iteration: 39186/59290
Iteration: 39187/59290
Iteration: 39188/59290
Iteration: 39189/59290
Iteration: 39190/59290
Iteration: 39191/59290
Iteration: 39192/59290

 66%|██████▌   | 39179/59290 [28:16<06:30, 51.54it/s]

Iteration: 39193/59290
Iteration: 39194/59290
Iteration: 39195/59290
Iteration: 39196/59290
Iteration: 39197/59290
Iteration: 39198/59290
Iteration: 39199/59290
Iteration: 39200/59290
Iteration: 39201/59290
Iteration: 39202/59290
Iteration: 39203/59290
Iteration: 39204/59290
Iteration: 39205/59290
Iteration: 39206/59290
Iteration: 39207/59290
Iteration: 39208/59290
Iteration: 39209/59290
Iteration: 39210/59290
Iteration: 39211/59290
Iteration: 39212/59290
Iteration: 39213/59290
Iteration: 39214/59290
Iteration: 39215/59290
Iteration: 39216/59290

 66%|██████▌   | 39203/59290 [28:16<06:07, 54.61it/s]

Iteration: 39217/59290
Iteration: 39218/59290
Iteration: 39219/59290
Iteration: 39220/59290
Iteration: 39221/59290
Iteration: 39222/59290
Iteration: 39223/59290
Iteration: 39224/59290
Iteration: 39225/59290
Iteration: 39226/59290
Iteration: 39227/59290
Iteration: 39228/59290
Iteration: 39229/59290
Iteration: 39230/59290
Iteration: 39231/59290
Iteration: 39232/59290
Iteration: 39233/59290
Iteration: 39234/59290
Iteration: 39235/59290
Iteration: 39236/59290
Iteration: 39237/59290
Iteration: 39238/59290
Iteration: 39239/59290
Iteration: 39240/59290

 66%|██████▌   | 39227/59290 [28:17<09:02, 37.00it/s]

Iteration: 39241/59290
Iteration: 39242/59290
Iteration: 39243/59290
Iteration: 39244/59290
Iteration: 39245/59290
Iteration: 39246/59290
Iteration: 39247/59290
Iteration: 39248/59290
Iteration: 39249/59290
Iteration: 39250/59290
Iteration: 39251/59290
Iteration: 39252/59290
Iteration: 39253/59290
Iteration: 39254/59290
Iteration: 39255/59290
Iteration: 39256/59290
Iteration: 39257/59290
Iteration: 39258/59290
Iteration: 39259/59290
Iteration: 39260/59290
Iteration: 39261/59290
Iteration: 39262/59290
Iteration: 39263/59290
Iteration: 39264/59290

 66%|██████▌   | 39251/59290 [28:19<13:09, 25.39it/s]

Iteration: 39265/59290
Iteration: 39266/59290
Iteration: 39267/59290
Iteration: 39268/59290
Iteration: 39269/59290
Iteration: 39270/59290
Iteration: 39271/59290
Iteration: 39272/59290
Iteration: 39273/59290
Iteration: 39274/59290
Iteration: 39275/59290
Iteration: 39276/59290
Iteration: 39277/59290
Iteration: 39278/59290
Iteration: 39279/59290
Iteration: 39280/59290
Iteration: 39281/59290
Iteration: 39282/59290
Iteration: 39283/59290
Iteration: 39284/59290
Iteration: 39285/59290
Iteration: 39286/59290
Iteration: 39287/59290
Iteration: 39288/59290

 66%|██████▌   | 39275/59290 [28:20<11:09, 29.90it/s]

Iteration: 39289/59290
Iteration: 39290/59290
Iteration: 39291/59290
Iteration: 39292/59290
Iteration: 39293/59290
Iteration: 39294/59290
Iteration: 39295/59290
Iteration: 39296/59290
Iteration: 39297/59290
Iteration: 39298/59290
Iteration: 39299/59290
Iteration: 39300/59290
Iteration: 39301/59290
Iteration: 39302/59290
Iteration: 39303/59290
Iteration: 39304/59290
Iteration: 39305/59290
Iteration: 39306/59290
Iteration: 39307/59290
Iteration: 39308/59290
Iteration: 39309/59290
Iteration: 39310/59290
Iteration: 39311/59290
Iteration: 39312/59290

 66%|██████▋   | 39299/59290 [28:20<09:22, 35.57it/s]

Iteration: 39313/59290
Iteration: 39314/59290
Iteration: 39315/59290
Iteration: 39316/59290
Iteration: 39317/59290
Iteration: 39318/59290
Iteration: 39319/59290
Iteration: 39320/59290
Iteration: 39321/59290
Iteration: 39322/59290
Iteration: 39323/59290
Iteration: 39324/59290
Iteration: 39325/59290
Iteration: 39326/59290
Iteration: 39327/59290
Iteration: 39328/59290
Iteration: 39329/59290
Iteration: 39330/59290
Iteration: 39331/59290
Iteration: 39332/59290
Iteration: 39333/59290
Iteration: 39334/59290
Iteration: 39335/59290
Iteration: 39336/59290

 66%|██████▋   | 39323/59290 [28:20<08:08, 40.89it/s]

Iteration: 39337/59290
Iteration: 39338/59290
Iteration: 39339/59290
Iteration: 39340/59290
Iteration: 39341/59290
Iteration: 39342/59290
Iteration: 39343/59290
Iteration: 39344/59290
Iteration: 39345/59290
Iteration: 39346/59290
Iteration: 39347/59290
Iteration: 39348/59290
Iteration: 39349/59290
Iteration: 39350/59290
Iteration: 39351/59290
Iteration: 39352/59290
Iteration: 39353/59290
Iteration: 39354/59290
Iteration: 39355/59290
Iteration: 39356/59290
Iteration: 39357/59290
Iteration: 39358/59290
Iteration: 39359/59290
Iteration: 39360/59290

 66%|██████▋   | 39347/59290 [28:21<07:16, 45.73it/s]

Iteration: 39361/59290
Iteration: 39362/59290
Iteration: 39363/59290
Iteration: 39364/59290
Iteration: 39365/59290
Iteration: 39366/59290
Iteration: 39367/59290
Iteration: 39368/59290
Iteration: 39369/59290
Iteration: 39370/59290
Iteration: 39371/59290
Iteration: 39372/59290
Iteration: 39373/59290
Iteration: 39374/59290
Iteration: 39375/59290
Iteration: 39376/59290
Iteration: 39377/59290
Iteration: 39378/59290
Iteration: 39379/59290
Iteration: 39380/59290
Iteration: 39381/59290
Iteration: 39382/59290
Iteration: 39383/59290
Iteration: 39384/59290

 66%|██████▋   | 39371/59290 [28:21<07:50, 42.30it/s]

Iteration: 39385/59290
Iteration: 39386/59290
Iteration: 39387/59290
Iteration: 39388/59290
Iteration: 39389/59290
Iteration: 39390/59290
Iteration: 39391/59290
Iteration: 39392/59290
Iteration: 39393/59290
Iteration: 39394/59290
Iteration: 39395/59290
Iteration: 39396/59290
Iteration: 39397/59290
Iteration: 39398/59290
Iteration: 39399/59290
Iteration: 39400/59290
Iteration: 39401/59290
Iteration: 39402/59290
Iteration: 39403/59290
Iteration: 39404/59290
Iteration: 39405/59290
Iteration: 39406/59290
Iteration: 39407/59290
Iteration: 39408/59290

 66%|██████▋   | 39395/59290 [28:22<07:05, 46.76it/s]

Iteration: 39409/59290
Iteration: 39410/59290
Iteration: 39411/59290
Iteration: 39412/59290
Iteration: 39413/59290
Iteration: 39414/59290
Iteration: 39415/59290
Iteration: 39416/59290
Iteration: 39417/59290
Iteration: 39418/59290
Iteration: 39419/59290
Iteration: 39420/59290
Iteration: 39421/59290
Iteration: 39422/59290
Iteration: 39423/59290
Iteration: 39424/59290
Iteration: 39425/59290
Iteration: 39426/59290
Iteration: 39427/59290
Iteration: 39428/59290
Iteration: 39429/59290
Iteration: 39430/59290
Iteration: 39431/59290
Iteration: 39432/59290

 66%|██████▋   | 39419/59290 [28:22<06:35, 50.21it/s]

Iteration: 39433/59290
Iteration: 39434/59290
Iteration: 39435/59290
Iteration: 39436/59290
Iteration: 39437/59290
Iteration: 39438/59290
Iteration: 39439/59290
Iteration: 39440/59290
Iteration: 39441/59290
Iteration: 39442/59290
Iteration: 39443/59290
Iteration: 39444/59290
Iteration: 39445/59290
Iteration: 39446/59290
Iteration: 39447/59290
Iteration: 39448/59290
Iteration: 39449/59290
Iteration: 39450/59290
Iteration: 39451/59290
Iteration: 39452/59290
Iteration: 39453/59290
Iteration: 39454/59290
Iteration: 39455/59290
Iteration: 39456/59290

 67%|██████▋   | 39443/59290 [28:23<06:11, 53.44it/s]

Iteration: 39457/59290
Iteration: 39458/59290
Iteration: 39459/59290
Iteration: 39460/59290
Iteration: 39461/59290
Iteration: 39462/59290
Iteration: 39463/59290
Iteration: 39464/59290
Iteration: 39465/59290
Iteration: 39466/59290
Iteration: 39467/59290
Iteration: 39468/59290
Iteration: 39469/59290
Iteration: 39470/59290
Iteration: 39471/59290
Iteration: 39472/59290
Iteration: 39473/59290
Iteration: 39474/59290
Iteration: 39475/59290
Iteration: 39476/59290
Iteration: 39477/59290
Iteration: 39478/59290
Iteration: 39479/59290
Iteration: 39480/59290

 67%|██████▋   | 39467/59290 [28:23<06:01, 54.90it/s]

Iteration: 39481/59290
Iteration: 39482/59290
Iteration: 39483/59290
Iteration: 39484/59290
Iteration: 39485/59290
Iteration: 39486/59290
Iteration: 39487/59290
Iteration: 39488/59290
Iteration: 39489/59290
Iteration: 39490/59290
Iteration: 39491/59290
Iteration: 39492/59290
Iteration: 39493/59290
Iteration: 39494/59290
Iteration: 39495/59290
Iteration: 39496/59290
Iteration: 39497/59290
Iteration: 39498/59290
Iteration: 39499/59290
Iteration: 39500/59290
Iteration: 39501/59290
Iteration: 39502/59290
Iteration: 39503/59290
Iteration: 39504/59290

 67%|██████▋   | 39491/59290 [28:24<08:25, 39.19it/s]

Iteration: 39505/59290
Iteration: 39506/59290
Iteration: 39507/59290
Iteration: 39508/59290
Iteration: 39509/59290
Iteration: 39510/59290
Iteration: 39511/59290
Iteration: 39512/59290
Iteration: 39513/59290
Iteration: 39514/59290
Iteration: 39515/59290
Iteration: 39516/59290
Iteration: 39517/59290
Iteration: 39518/59290
Iteration: 39519/59290
Iteration: 39520/59290
Iteration: 39521/59290
Iteration: 39522/59290
Iteration: 39523/59290
Iteration: 39524/59290
Iteration: 39525/59290
Iteration: 39526/59290
Iteration: 39527/59290
Iteration: 39528/59290

 67%|██████▋   | 39515/59290 [28:26<15:48, 20.84it/s]

Iteration: 39529/59290
Iteration: 39530/59290
Iteration: 39531/59290
Iteration: 39532/59290
Iteration: 39533/59290
Iteration: 39534/59290
Iteration: 39535/59290
Iteration: 39536/59290
Iteration: 39537/59290
Iteration: 39538/59290
Iteration: 39539/59290
Iteration: 39540/59290
Iteration: 39541/59290
Iteration: 39542/59290
Iteration: 39543/59290
Iteration: 39544/59290
Iteration: 39545/59290
Iteration: 39546/59290
Iteration: 39547/59290
Iteration: 39548/59290
Iteration: 39549/59290
Iteration: 39550/59290
Iteration: 39551/59290
Iteration: 39552/59290

 67%|██████▋   | 39539/59290 [28:27<12:36, 26.12it/s]

Iteration: 39553/59290
Iteration: 39554/59290
Iteration: 39555/59290
Iteration: 39556/59290
Iteration: 39557/59290
Iteration: 39558/59290
Iteration: 39559/59290
Iteration: 39560/59290
Iteration: 39561/59290
Iteration: 39562/59290
Iteration: 39563/59290
Iteration: 39564/59290
Iteration: 39565/59290
Iteration: 39566/59290
Iteration: 39567/59290
Iteration: 39568/59290
Iteration: 39569/59290
Iteration: 39570/59290
Iteration: 39571/59290
Iteration: 39572/59290
Iteration: 39573/59290
Iteration: 39574/59290
Iteration: 39575/59290
Iteration: 39576/59290

 67%|██████▋   | 39563/59290 [28:28<14:23, 22.85it/s]

Iteration: 39577/59290
Iteration: 39578/59290
Iteration: 39579/59290
Iteration: 39580/59290
Iteration: 39581/59290
Iteration: 39582/59290
Iteration: 39583/59290
Iteration: 39584/59290
Iteration: 39585/59290
Iteration: 39586/59290
Iteration: 39587/59290
Iteration: 39588/59290
Iteration: 39589/59290
Iteration: 39590/59290
Iteration: 39591/59290
Iteration: 39592/59290
Iteration: 39593/59290
Iteration: 39594/59290
Iteration: 39595/59290
Iteration: 39596/59290
Iteration: 39597/59290
Iteration: 39598/59290
Iteration: 39599/59290
Iteration: 39600/59290

 67%|██████▋   | 39587/59290 [28:30<16:52, 19.46it/s]

Iteration: 39601/59290
Iteration: 39602/59290
Iteration: 39603/59290
Iteration: 39604/59290
Iteration: 39605/59290
Iteration: 39606/59290
Iteration: 39607/59290
Iteration: 39608/59290
Iteration: 39609/59290
Iteration: 39610/59290
Iteration: 39611/59290
Iteration: 39612/59290
Iteration: 39613/59290
Iteration: 39614/59290
Iteration: 39615/59290
Iteration: 39616/59290
Iteration: 39617/59290
Iteration: 39618/59290
Iteration: 39619/59290
Iteration: 39620/59290
Iteration: 39621/59290
Iteration: 39622/59290
Iteration: 39623/59290
Iteration: 39624/59290

 67%|██████▋   | 39611/59290 [28:30<13:28, 24.34it/s]

Iteration: 39625/59290
Iteration: 39626/59290
Iteration: 39627/59290
Iteration: 39628/59290
Iteration: 39629/59290
Iteration: 39630/59290
Iteration: 39631/59290
Iteration: 39632/59290
Iteration: 39633/59290
Iteration: 39634/59290
Iteration: 39635/59290
Iteration: 39636/59290
Iteration: 39637/59290
Iteration: 39638/59290
Iteration: 39639/59290
Iteration: 39640/59290
Iteration: 39641/59290
Iteration: 39642/59290
Iteration: 39643/59290
Iteration: 39644/59290
Iteration: 39645/59290
Iteration: 39646/59290
Iteration: 39647/59290
Iteration: 39648/59290

 67%|██████▋   | 39635/59290 [28:31<11:02, 29.66it/s]

Iteration: 39649/59290
Iteration: 39650/59290
Iteration: 39651/59290
Iteration: 39652/59290
Iteration: 39653/59290
Iteration: 39654/59290
Iteration: 39655/59290
Iteration: 39656/59290
Iteration: 39657/59290
Iteration: 39658/59290
Iteration: 39659/59290
Iteration: 39660/59290
Iteration: 39661/59290
Iteration: 39662/59290
Iteration: 39663/59290
Iteration: 39664/59290
Iteration: 39665/59290
Iteration: 39666/59290
Iteration: 39667/59290
Iteration: 39668/59290
Iteration: 39669/59290
Iteration: 39670/59290
Iteration: 39671/59290
Iteration: 39672/59290

 67%|██████▋   | 39659/59290 [28:31<09:20, 35.02it/s]

Iteration: 39673/59290
Iteration: 39674/59290
Iteration: 39675/59290
Iteration: 39676/59290
Iteration: 39677/59290
Iteration: 39678/59290
Iteration: 39679/59290
Iteration: 39680/59290
Iteration: 39681/59290
Iteration: 39682/59290
Iteration: 39683/59290
Iteration: 39684/59290
Iteration: 39685/59290
Iteration: 39686/59290
Iteration: 39687/59290
Iteration: 39688/59290
Iteration: 39689/59290
Iteration: 39690/59290
Iteration: 39691/59290
Iteration: 39692/59290
Iteration: 39693/59290
Iteration: 39694/59290
Iteration: 39695/59290
Iteration: 39696/59290

 67%|██████▋   | 39683/59290 [28:31<08:11, 39.88it/s]

Iteration: 39697/59290
Iteration: 39698/59290
Iteration: 39699/59290
Iteration: 39700/59290
Iteration: 39701/59290
Iteration: 39702/59290
Iteration: 39703/59290
Iteration: 39704/59290
Iteration: 39705/59290
Iteration: 39706/59290
Iteration: 39707/59290
Iteration: 39708/59290
Iteration: 39709/59290
Iteration: 39710/59290
Iteration: 39711/59290
Iteration: 39712/59290
Iteration: 39713/59290
Iteration: 39714/59290
Iteration: 39715/59290
Iteration: 39716/59290
Iteration: 39717/59290
Iteration: 39718/59290
Iteration: 39719/59290
Iteration: 39720/59290

 67%|██████▋   | 39707/59290 [28:32<07:17, 44.80it/s]

Iteration: 39721/59290
Iteration: 39722/59290
Iteration: 39723/59290
Iteration: 39724/59290
Iteration: 39725/59290
Iteration: 39726/59290
Iteration: 39727/59290
Iteration: 39728/59290
Iteration: 39729/59290
Iteration: 39730/59290
Iteration: 39731/59290
Iteration: 39732/59290
Iteration: 39733/59290
Iteration: 39734/59290
Iteration: 39735/59290
Iteration: 39736/59290
Iteration: 39737/59290
Iteration: 39738/59290
Iteration: 39739/59290
Iteration: 39740/59290
Iteration: 39741/59290
Iteration: 39742/59290
Iteration: 39743/59290
Iteration: 39744/59290

 67%|██████▋   | 39731/59290 [28:33<09:29, 34.33it/s]

Iteration: 39745/59290
Iteration: 39746/59290
Iteration: 39747/59290
Iteration: 39748/59290
Iteration: 39749/59290
Iteration: 39750/59290
Iteration: 39751/59290
Iteration: 39752/59290
Iteration: 39753/59290
Iteration: 39754/59290
Iteration: 39755/59290
Iteration: 39756/59290
Iteration: 39757/59290
Iteration: 39758/59290
Iteration: 39759/59290
Iteration: 39760/59290
Iteration: 39761/59290
Iteration: 39762/59290
Iteration: 39763/59290
Iteration: 39764/59290
Iteration: 39765/59290
Iteration: 39766/59290
Iteration: 39767/59290
Iteration: 39768/59290

 67%|██████▋   | 39755/59290 [28:35<13:41, 23.77it/s]

Iteration: 39769/59290
Iteration: 39770/59290
Iteration: 39771/59290
Iteration: 39772/59290
Iteration: 39773/59290
Iteration: 39774/59290
Iteration: 39775/59290
Iteration: 39776/59290
Iteration: 39777/59290
Iteration: 39778/59290
Iteration: 39779/59290
Iteration: 39780/59290
Iteration: 39781/59290
Iteration: 39782/59290
Iteration: 39783/59290
Iteration: 39784/59290
Iteration: 39785/59290
Iteration: 39786/59290
Iteration: 39787/59290
Iteration: 39788/59290
Iteration: 39789/59290
Iteration: 39790/59290
Iteration: 39791/59290
Iteration: 39792/59290

 67%|██████▋   | 39779/59290 [28:35<12:24, 26.19it/s]

Iteration: 39793/59290
Iteration: 39794/59290
Iteration: 39795/59290
Iteration: 39796/59290
Iteration: 39797/59290
Iteration: 39798/59290
Iteration: 39799/59290
Iteration: 39800/59290
Iteration: 39801/59290
Iteration: 39802/59290
Iteration: 39803/59290
Iteration: 39804/59290
Iteration: 39805/59290
Iteration: 39806/59290
Iteration: 39807/59290
Iteration: 39808/59290
Iteration: 39809/59290
Iteration: 39810/59290
Iteration: 39811/59290
Iteration: 39812/59290
Iteration: 39813/59290
Iteration: 39814/59290
Iteration: 39815/59290
Iteration: 39816/59290

 67%|██████▋   | 39803/59290 [28:36<10:13, 31.78it/s]

Iteration: 39817/59290
Iteration: 39818/59290
Iteration: 39819/59290
Iteration: 39820/59290
Iteration: 39821/59290
Iteration: 39822/59290
Iteration: 39823/59290
Iteration: 39824/59290
Iteration: 39825/59290
Iteration: 39826/59290
Iteration: 39827/59290
Iteration: 39828/59290
Iteration: 39829/59290
Iteration: 39830/59290
Iteration: 39831/59290
Iteration: 39832/59290
Iteration: 39833/59290
Iteration: 39834/59290
Iteration: 39835/59290
Iteration: 39836/59290
Iteration: 39837/59290
Iteration: 39838/59290
Iteration: 39839/59290
Iteration: 39840/59290

 67%|██████▋   | 39827/59290 [28:36<08:39, 37.47it/s]

Iteration: 39841/59290
Iteration: 39842/59290
Iteration: 39843/59290
Iteration: 39844/59290
Iteration: 39845/59290
Iteration: 39846/59290
Iteration: 39847/59290
Iteration: 39848/59290
Iteration: 39849/59290
Iteration: 39850/59290
Iteration: 39851/59290
Iteration: 39852/59290
Iteration: 39853/59290
Iteration: 39854/59290
Iteration: 39855/59290
Iteration: 39856/59290
Iteration: 39857/59290
Iteration: 39858/59290
Iteration: 39859/59290
Iteration: 39860/59290
Iteration: 39861/59290
Iteration: 39862/59290
Iteration: 39863/59290
Iteration: 39864/59290

 67%|██████▋   | 39851/59290 [28:36<07:39, 42.33it/s]

Iteration: 39865/59290
Iteration: 39866/59290
Iteration: 39867/59290
Iteration: 39868/59290
Iteration: 39869/59290
Iteration: 39870/59290
Iteration: 39871/59290
Iteration: 39872/59290
Iteration: 39873/59290
Iteration: 39874/59290
Iteration: 39875/59290
Iteration: 39876/59290
Iteration: 39877/59290
Iteration: 39878/59290
Iteration: 39879/59290
Iteration: 39880/59290
Iteration: 39881/59290
Iteration: 39882/59290
Iteration: 39883/59290
Iteration: 39884/59290
Iteration: 39885/59290
Iteration: 39886/59290
Iteration: 39887/59290
Iteration: 39888/59290

 67%|██████▋   | 39875/59290 [28:38<09:40, 33.42it/s]

Iteration: 39889/59290
Iteration: 39890/59290
Iteration: 39891/59290
Iteration: 39892/59290
Iteration: 39893/59290
Iteration: 39894/59290
Iteration: 39895/59290
Iteration: 39896/59290
Iteration: 39897/59290
Iteration: 39898/59290
Iteration: 39899/59290
Iteration: 39900/59290
Iteration: 39901/59290
Iteration: 39902/59290
Iteration: 39903/59290
Iteration: 39904/59290
Iteration: 39905/59290
Iteration: 39906/59290
Iteration: 39907/59290
Iteration: 39908/59290
Iteration: 39909/59290
Iteration: 39910/59290
Iteration: 39911/59290
Iteration: 39912/59290

 67%|██████▋   | 39899/59290 [28:39<13:45, 23.48it/s]

Iteration: 39913/59290
Iteration: 39914/59290
Iteration: 39915/59290
Iteration: 39916/59290
Iteration: 39917/59290
Iteration: 39918/59290
Iteration: 39919/59290
Iteration: 39920/59290
Iteration: 39921/59290
Iteration: 39922/59290
Iteration: 39923/59290
Iteration: 39924/59290
Iteration: 39925/59290
Iteration: 39926/59290
Iteration: 39927/59290
Iteration: 39928/59290
Iteration: 39929/59290
Iteration: 39930/59290
Iteration: 39931/59290
Iteration: 39932/59290
Iteration: 39933/59290
Iteration: 39934/59290
Iteration: 39935/59290
Iteration: 39936/59290

 67%|██████▋   | 39923/59290 [28:40<11:24, 28.29it/s]

Iteration: 39937/59290
Iteration: 39938/59290
Iteration: 39939/59290
Iteration: 39940/59290
Iteration: 39941/59290
Iteration: 39942/59290
Iteration: 39943/59290
Iteration: 39944/59290
Iteration: 39945/59290
Iteration: 39946/59290
Iteration: 39947/59290
Iteration: 39948/59290
Iteration: 39949/59290
Iteration: 39950/59290
Iteration: 39951/59290
Iteration: 39952/59290
Iteration: 39953/59290
Iteration: 39954/59290
Iteration: 39955/59290
Iteration: 39956/59290
Iteration: 39957/59290
Iteration: 39958/59290
Iteration: 39959/59290
Iteration: 39960/59290

 67%|██████▋   | 39947/59290 [28:40<09:32, 33.77it/s]

Iteration: 39961/59290
Iteration: 39962/59290
Iteration: 39963/59290
Iteration: 39964/59290
Iteration: 39965/59290
Iteration: 39966/59290
Iteration: 39967/59290
Iteration: 39968/59290
Iteration: 39969/59290
Iteration: 39970/59290
Iteration: 39971/59290
Iteration: 39972/59290
Iteration: 39973/59290
Iteration: 39974/59290
Iteration: 39975/59290
Iteration: 39976/59290
Iteration: 39977/59290
Iteration: 39978/59290
Iteration: 39979/59290
Iteration: 39980/59290
Iteration: 39981/59290
Iteration: 39982/59290
Iteration: 39983/59290
Iteration: 39984/59290

 67%|██████▋   | 39971/59290 [28:40<08:11, 39.34it/s]

Iteration: 39985/59290
Iteration: 39986/59290
Iteration: 39987/59290
Iteration: 39988/59290
Iteration: 39989/59290
Iteration: 39990/59290
Iteration: 39991/59290
Iteration: 39992/59290
Iteration: 39993/59290
Iteration: 39994/59290
Iteration: 39995/59290
Iteration: 39996/59290
Iteration: 39997/59290
Iteration: 39998/59290
Iteration: 39999/59290
Iteration: 40000/59290
Iteration: 40001/59290
Iteration: 40002/59290
Iteration: 40003/59290
Iteration: 40004/59290
Iteration: 40005/59290
Iteration: 40006/59290
Iteration: 40007/59290
Iteration: 40008/59290

 67%|██████▋   | 39995/59290 [28:41<07:14, 44.43it/s]

Iteration: 40009/59290
Iteration: 40010/59290
Iteration: 40011/59290
Iteration: 40012/59290
Iteration: 40013/59290
Iteration: 40014/59290
Iteration: 40015/59290
Iteration: 40016/59290
Iteration: 40017/59290
Iteration: 40018/59290
Iteration: 40019/59290
Iteration: 40020/59290
Iteration: 40021/59290
Iteration: 40022/59290
Iteration: 40023/59290
Iteration: 40024/59290
Iteration: 40025/59290
Iteration: 40026/59290
Iteration: 40027/59290
Iteration: 40028/59290
Iteration: 40029/59290
Iteration: 40030/59290
Iteration: 40031/59290
Iteration: 40032/59290

 67%|██████▋   | 40019/59290 [28:42<10:01, 32.02it/s]

Iteration: 40033/59290
Iteration: 40034/59290
Iteration: 40035/59290
Iteration: 40036/59290
Iteration: 40037/59290
Iteration: 40038/59290
Iteration: 40039/59290
Iteration: 40040/59290
Iteration: 40041/59290
Iteration: 40042/59290
Iteration: 40043/59290
Iteration: 40044/59290
Iteration: 40045/59290
Iteration: 40046/59290
Iteration: 40047/59290
Iteration: 40048/59290
Iteration: 40049/59290
Iteration: 40050/59290
Iteration: 40051/59290
Iteration: 40052/59290
Iteration: 40053/59290
Iteration: 40054/59290
Iteration: 40055/59290
Iteration: 40056/59290

 68%|██████▊   | 40043/59290 [28:44<15:28, 20.74it/s]

Iteration: 40057/59290
Iteration: 40058/59290
Iteration: 40059/59290
Iteration: 40060/59290
Iteration: 40061/59290
Iteration: 40062/59290
Iteration: 40063/59290
Iteration: 40064/59290
Iteration: 40065/59290
Iteration: 40066/59290
Iteration: 40067/59290
Iteration: 40068/59290
Iteration: 40069/59290
Iteration: 40070/59290
Iteration: 40071/59290
Iteration: 40072/59290
Iteration: 40073/59290
Iteration: 40074/59290
Iteration: 40075/59290
Iteration: 40076/59290
Iteration: 40077/59290
Iteration: 40078/59290
Iteration: 40079/59290
Iteration: 40080/59290

 68%|██████▊   | 40067/59290 [28:45<12:19, 25.99it/s]

Iteration: 40081/59290
Iteration: 40082/59290
Iteration: 40083/59290
Iteration: 40084/59290
Iteration: 40085/59290
Iteration: 40086/59290
Iteration: 40087/59290
Iteration: 40088/59290
Iteration: 40089/59290
Iteration: 40090/59290
Iteration: 40091/59290
Iteration: 40092/59290
Iteration: 40093/59290
Iteration: 40094/59290
Iteration: 40095/59290
Iteration: 40096/59290
Iteration: 40097/59290
Iteration: 40098/59290
Iteration: 40099/59290
Iteration: 40100/59290
Iteration: 40101/59290
Iteration: 40102/59290
Iteration: 40103/59290
Iteration: 40104/59290

 68%|██████▊   | 40091/59290 [28:45<10:11, 31.42it/s]

Iteration: 40105/59290
Iteration: 40106/59290
Iteration: 40107/59290
Iteration: 40108/59290
Iteration: 40109/59290
Iteration: 40110/59290
Iteration: 40111/59290
Iteration: 40112/59290
Iteration: 40113/59290
Iteration: 40114/59290
Iteration: 40115/59290
Iteration: 40116/59290
Iteration: 40117/59290
Iteration: 40118/59290
Iteration: 40119/59290
Iteration: 40120/59290
Iteration: 40121/59290
Iteration: 40122/59290
Iteration: 40123/59290
Iteration: 40124/59290
Iteration: 40125/59290
Iteration: 40126/59290
Iteration: 40127/59290
Iteration: 40128/59290

 68%|██████▊   | 40115/59290 [28:45<08:40, 36.86it/s]

Iteration: 40129/59290
Iteration: 40130/59290
Iteration: 40131/59290
Iteration: 40132/59290
Iteration: 40133/59290
Iteration: 40134/59290
Iteration: 40135/59290
Iteration: 40136/59290
Iteration: 40137/59290
Iteration: 40138/59290
Iteration: 40139/59290
Iteration: 40140/59290
Iteration: 40141/59290
Iteration: 40142/59290
Iteration: 40143/59290
Iteration: 40144/59290
Iteration: 40145/59290
Iteration: 40146/59290
Iteration: 40147/59290
Iteration: 40148/59290
Iteration: 40149/59290
Iteration: 40150/59290
Iteration: 40151/59290
Iteration: 40152/59290

 68%|██████▊   | 40139/59290 [28:46<07:34, 42.12it/s]

Iteration: 40153/59290
Iteration: 40154/59290
Iteration: 40155/59290
Iteration: 40156/59290
Iteration: 40157/59290
Iteration: 40158/59290
Iteration: 40159/59290
Iteration: 40160/59290
Iteration: 40161/59290
Iteration: 40162/59290
Iteration: 40163/59290
Iteration: 40164/59290
Iteration: 40165/59290
Iteration: 40166/59290
Iteration: 40167/59290
Iteration: 40168/59290
Iteration: 40169/59290
Iteration: 40170/59290
Iteration: 40171/59290
Iteration: 40172/59290
Iteration: 40173/59290
Iteration: 40174/59290
Iteration: 40175/59290
Iteration: 40176/59290

 68%|██████▊   | 40163/59290 [28:46<06:46, 47.03it/s]

Iteration: 40177/59290
Iteration: 40178/59290
Iteration: 40179/59290
Iteration: 40180/59290
Iteration: 40181/59290
Iteration: 40182/59290
Iteration: 40183/59290
Iteration: 40184/59290
Iteration: 40185/59290
Iteration: 40186/59290
Iteration: 40187/59290
Iteration: 40188/59290
Iteration: 40189/59290
Iteration: 40190/59290
Iteration: 40191/59290
Iteration: 40192/59290
Iteration: 40193/59290
Iteration: 40194/59290
Iteration: 40195/59290
Iteration: 40196/59290
Iteration: 40197/59290
Iteration: 40198/59290
Iteration: 40199/59290
Iteration: 40200/59290

 68%|██████▊   | 40187/59290 [28:46<06:16, 50.80it/s]

Iteration: 40201/59290
Iteration: 40202/59290
Iteration: 40203/59290
Iteration: 40204/59290
Iteration: 40205/59290
Iteration: 40206/59290
Iteration: 40207/59290
Iteration: 40208/59290
Iteration: 40209/59290
Iteration: 40210/59290
Iteration: 40211/59290
Iteration: 40212/59290
Iteration: 40213/59290
Iteration: 40214/59290
Iteration: 40215/59290
Iteration: 40216/59290
Iteration: 40217/59290
Iteration: 40218/59290
Iteration: 40219/59290
Iteration: 40220/59290
Iteration: 40221/59290
Iteration: 40222/59290
Iteration: 40223/59290
Iteration: 40224/59290

 68%|██████▊   | 40211/59290 [28:47<05:52, 54.09it/s]

Iteration: 40225/59290
Iteration: 40226/59290
Iteration: 40227/59290
Iteration: 40228/59290
Iteration: 40229/59290
Iteration: 40230/59290
Iteration: 40231/59290
Iteration: 40232/59290
Iteration: 40233/59290
Iteration: 40234/59290
Iteration: 40235/59290
Iteration: 40236/59290
Iteration: 40237/59290
Iteration: 40238/59290
Iteration: 40239/59290
Iteration: 40240/59290
Iteration: 40241/59290
Iteration: 40242/59290
Iteration: 40243/59290
Iteration: 40244/59290
Iteration: 40245/59290
Iteration: 40246/59290
Iteration: 40247/59290
Iteration: 40248/59290

 68%|██████▊   | 40235/59290 [28:48<09:06, 34.88it/s]

Iteration: 40249/59290
Iteration: 40250/59290
Iteration: 40251/59290
Iteration: 40252/59290
Iteration: 40253/59290
Iteration: 40254/59290
Iteration: 40255/59290
Iteration: 40256/59290
Iteration: 40257/59290
Iteration: 40258/59290
Iteration: 40259/59290
Iteration: 40260/59290
Iteration: 40261/59290
Iteration: 40262/59290
Iteration: 40263/59290
Iteration: 40264/59290
Iteration: 40265/59290
Iteration: 40266/59290
Iteration: 40267/59290
Iteration: 40268/59290
Iteration: 40269/59290
Iteration: 40270/59290
Iteration: 40271/59290
Iteration: 40272/59290

 68%|██████▊   | 40259/59290 [28:50<14:33, 21.78it/s]

Iteration: 40273/59290
Iteration: 40274/59290
Iteration: 40275/59290
Iteration: 40276/59290
Iteration: 40277/59290
Iteration: 40278/59290
Iteration: 40279/59290
Iteration: 40280/59290
Iteration: 40281/59290
Iteration: 40282/59290
Iteration: 40283/59290
Iteration: 40284/59290
Iteration: 40285/59290
Iteration: 40286/59290
Iteration: 40287/59290
Iteration: 40288/59290
Iteration: 40289/59290
Iteration: 40290/59290
Iteration: 40291/59290
Iteration: 40292/59290
Iteration: 40293/59290
Iteration: 40294/59290
Iteration: 40295/59290
Iteration: 40296/59290

 68%|██████▊   | 40283/59290 [28:51<11:40, 27.13it/s]

Iteration: 40297/59290
Iteration: 40298/59290
Iteration: 40299/59290
Iteration: 40300/59290
Iteration: 40301/59290
Iteration: 40302/59290
Iteration: 40303/59290
Iteration: 40304/59290
Iteration: 40305/59290
Iteration: 40306/59290
Iteration: 40307/59290
Iteration: 40308/59290
Iteration: 40309/59290
Iteration: 40310/59290
Iteration: 40311/59290
Iteration: 40312/59290
Iteration: 40313/59290
Iteration: 40314/59290
Iteration: 40315/59290
Iteration: 40316/59290
Iteration: 40317/59290
Iteration: 40318/59290
Iteration: 40319/59290
Iteration: 40320/59290

 68%|██████▊   | 40307/59290 [28:51<09:38, 32.79it/s]

Iteration: 40321/59290
Iteration: 40322/59290
Iteration: 40323/59290
Iteration: 40324/59290
Iteration: 40325/59290
Iteration: 40326/59290
Iteration: 40327/59290
Iteration: 40328/59290
Iteration: 40329/59290
Iteration: 40330/59290
Iteration: 40331/59290
Iteration: 40332/59290
Iteration: 40333/59290
Iteration: 40334/59290
Iteration: 40335/59290
Iteration: 40336/59290
Iteration: 40337/59290
Iteration: 40338/59290
Iteration: 40339/59290
Iteration: 40340/59290
Iteration: 40341/59290
Iteration: 40342/59290
Iteration: 40343/59290
Iteration: 40344/59290

 68%|██████▊   | 40331/59290 [28:51<08:14, 38.32it/s]

Iteration: 40345/59290
Iteration: 40346/59290
Iteration: 40347/59290
Iteration: 40348/59290
Iteration: 40349/59290
Iteration: 40350/59290
Iteration: 40351/59290
Iteration: 40352/59290
Iteration: 40353/59290
Iteration: 40354/59290
Iteration: 40355/59290
Iteration: 40356/59290
Iteration: 40357/59290
Iteration: 40358/59290
Iteration: 40359/59290
Iteration: 40360/59290
Iteration: 40361/59290
Iteration: 40362/59290
Iteration: 40363/59290
Iteration: 40364/59290
Iteration: 40365/59290
Iteration: 40366/59290
Iteration: 40367/59290
Iteration: 40368/59290

 68%|██████▊   | 40355/59290 [28:52<07:20, 42.96it/s]

Iteration: 40369/59290
Iteration: 40370/59290
Iteration: 40371/59290
Iteration: 40372/59290
Iteration: 40373/59290
Iteration: 40374/59290
Iteration: 40375/59290
Iteration: 40376/59290
Iteration: 40377/59290
Iteration: 40378/59290
Iteration: 40379/59290
Iteration: 40380/59290
Iteration: 40381/59290
Iteration: 40382/59290
Iteration: 40383/59290
Iteration: 40384/59290
Iteration: 40385/59290
Iteration: 40386/59290
Iteration: 40387/59290
Iteration: 40388/59290
Iteration: 40389/59290
Iteration: 40390/59290
Iteration: 40391/59290
Iteration: 40392/59290

 68%|██████▊   | 40379/59290 [28:52<06:37, 47.62it/s]

Iteration: 40393/59290
Iteration: 40394/59290
Iteration: 40395/59290
Iteration: 40396/59290
Iteration: 40397/59290
Iteration: 40398/59290
Iteration: 40399/59290
Iteration: 40400/59290
Iteration: 40401/59290
Iteration: 40402/59290
Iteration: 40403/59290
Iteration: 40404/59290
Iteration: 40405/59290
Iteration: 40406/59290
Iteration: 40407/59290
Iteration: 40408/59290
Iteration: 40409/59290
Iteration: 40410/59290
Iteration: 40411/59290
Iteration: 40412/59290
Iteration: 40413/59290
Iteration: 40414/59290
Iteration: 40415/59290
Iteration: 40416/59290

 68%|██████▊   | 40403/59290 [28:52<06:07, 51.40it/s]

Iteration: 40417/59290
Iteration: 40418/59290
Iteration: 40419/59290
Iteration: 40420/59290
Iteration: 40421/59290
Iteration: 40422/59290
Iteration: 40423/59290
Iteration: 40424/59290
Iteration: 40425/59290
Iteration: 40426/59290
Iteration: 40427/59290
Iteration: 40428/59290
Iteration: 40429/59290
Iteration: 40430/59290
Iteration: 40431/59290
Iteration: 40432/59290
Iteration: 40433/59290
Iteration: 40434/59290
Iteration: 40435/59290
Iteration: 40436/59290
Iteration: 40437/59290
Iteration: 40438/59290
Iteration: 40440/59290

 68%|██████▊   | 40426/59290 [28:53<05:59, 52.43it/s]

Iteration: 40441/59290
Iteration: 40442/59290
Iteration: 40443/59290
Iteration: 40444/59290
Iteration: 40445/59290
Iteration: 40446/59290
Iteration: 40447/59290
Iteration: 40448/59290

 68%|██████▊   | 40434/59290 [28:53<07:10, 43.76it/s]

Iteration: 40449/59290
Iteration: 40450/59290
Iteration: 40451/59290
Iteration: 40452/59290
Iteration: 40453/59290
Iteration: 40454/59290
Iteration: 40455/59290
Iteration: 40456/59290
Iteration: 40457/59290
Iteration: 40458/59290
Iteration: 40459/59290
Iteration: 40460/59290
Iteration: 40461/59290
Iteration: 40462/59290
Iteration: 40463/59290
Iteration: 40464/59290
Iteration: 40465/59290
Iteration: 40466/59290
Iteration: 40467/59290
Iteration: 40468/59290
Iteration: 40469/59290
Iteration: 40470/59290
Iteration: 40471/59290
Iteration: 40472/59290

 68%|██████▊   | 40458/59290 [28:54<06:23, 49.07it/s]

Iteration: 40473/59290
Iteration: 40474/59290
Iteration: 40475/59290
Iteration: 40476/59290
Iteration: 40477/59290
Iteration: 40478/59290
Iteration: 40479/59290
Iteration: 40480/59290
Iteration: 40481/59290
Iteration: 40482/59290
Iteration: 40483/59290
Iteration: 40484/59290
Iteration: 40485/59290
Iteration: 40486/59290
Iteration: 40487/59290
Iteration: 40488/59290
Iteration: 40489/59290
Iteration: 40490/59290
Iteration: 40491/59290
Iteration: 40492/59290
Iteration: 40493/59290
Iteration: 40494/59290
Iteration: 40495/59290
Iteration: 40496/59290

 68%|██████▊   | 40482/59290 [28:55<09:45, 32.13it/s]

Iteration: 40497/59290
Iteration: 40498/59290
Iteration: 40499/59290
Iteration: 40500/59290
Iteration: 40501/59290
Iteration: 40502/59290
Iteration: 40503/59290
Iteration: 40504/59290
Iteration: 40505/59290
Iteration: 40506/59290
Iteration: 40507/59290
Iteration: 40508/59290
Iteration: 40509/59290
Iteration: 40510/59290
Iteration: 40511/59290
Iteration: 40512/59290
Iteration: 40513/59290
Iteration: 40514/59290
Iteration: 40515/59290
Iteration: 40516/59290
Iteration: 40517/59290
Iteration: 40518/59290
Iteration: 40519/59290
Iteration: 40520/59290

 68%|██████▊   | 40506/59290 [28:57<14:03, 22.27it/s]

Iteration: 40521/59290
Iteration: 40522/59290
Iteration: 40523/59290
Iteration: 40524/59290
Iteration: 40525/59290
Iteration: 40526/59290
Iteration: 40527/59290
Iteration: 40528/59290
Iteration: 40529/59290
Iteration: 40530/59290
Iteration: 40531/59290
Iteration: 40532/59290
Iteration: 40533/59290
Iteration: 40534/59290
Iteration: 40535/59290
Iteration: 40536/59290
Iteration: 40537/59290
Iteration: 40538/59290
Iteration: 40539/59290
Iteration: 40540/59290
Iteration: 40541/59290
Iteration: 40542/59290
Iteration: 40543/59290
Iteration: 40544/59290

 68%|██████▊   | 40530/59290 [28:57<11:54, 26.26it/s]

Iteration: 40545/59290
Iteration: 40546/59290
Iteration: 40547/59290
Iteration: 40548/59290
Iteration: 40549/59290
Iteration: 40550/59290
Iteration: 40551/59290
Iteration: 40552/59290
Iteration: 40553/59290
Iteration: 40554/59290
Iteration: 40555/59290
Iteration: 40556/59290
Iteration: 40557/59290
Iteration: 40558/59290
Iteration: 40559/59290
Iteration: 40560/59290
Iteration: 40561/59290
Iteration: 40562/59290
Iteration: 40563/59290
Iteration: 40564/59290
Iteration: 40565/59290
Iteration: 40566/59290
Iteration: 40567/59290
Iteration: 40568/59290

 68%|██████▊   | 40554/59290 [28:58<09:45, 31.98it/s]

Iteration: 40569/59290
Iteration: 40570/59290
Iteration: 40571/59290
Iteration: 40572/59290
Iteration: 40573/59290
Iteration: 40574/59290
Iteration: 40575/59290
Iteration: 40576/59290
Iteration: 40577/59290
Iteration: 40578/59290
Iteration: 40579/59290
Iteration: 40580/59290
Iteration: 40581/59290
Iteration: 40582/59290
Iteration: 40583/59290
Iteration: 40584/59290
Iteration: 40585/59290
Iteration: 40586/59290
Iteration: 40587/59290
Iteration: 40588/59290
Iteration: 40589/59290
Iteration: 40590/59290
Iteration: 40591/59290
Iteration: 40592/59290

 68%|██████▊   | 40578/59290 [28:58<08:15, 37.76it/s]

Iteration: 40593/59290
Iteration: 40594/59290
Iteration: 40595/59290
Iteration: 40596/59290
Iteration: 40597/59290
Iteration: 40598/59290
Iteration: 40599/59290
Iteration: 40600/59290
Iteration: 40601/59290
Iteration: 40602/59290
Iteration: 40603/59290
Iteration: 40604/59290
Iteration: 40605/59290
Iteration: 40606/59290
Iteration: 40607/59290
Iteration: 40608/59290
Iteration: 40609/59290
Iteration: 40610/59290
Iteration: 40611/59290
Iteration: 40612/59290
Iteration: 40613/59290
Iteration: 40614/59290
Iteration: 40615/59290
Iteration: 40616/59290

 68%|██████▊   | 40602/59290 [29:01<18:39, 16.69it/s]

Iteration: 40617/59290
Iteration: 40618/59290
Iteration: 40619/59290
Iteration: 40620/59290
Iteration: 40621/59290
Iteration: 40622/59290
Iteration: 40623/59290
Iteration: 40624/59290
Iteration: 40625/59290
Iteration: 40626/59290
Iteration: 40627/59290
Iteration: 40628/59290
Iteration: 40629/59290
Iteration: 40630/59290
Iteration: 40631/59290
Iteration: 40632/59290
Iteration: 40633/59290
Iteration: 40634/59290
Iteration: 40635/59290
Iteration: 40636/59290
Iteration: 40637/59290
Iteration: 40638/59290
Iteration: 40639/59290
Iteration: 40640/59290

 69%|██████▊   | 40626/59290 [29:02<14:44, 21.09it/s]

Iteration: 40641/59290
Iteration: 40642/59290
Iteration: 40643/59290
Iteration: 40644/59290
Iteration: 40645/59290
Iteration: 40646/59290
Iteration: 40647/59290
Iteration: 40648/59290
Iteration: 40649/59290
Iteration: 40650/59290
Iteration: 40651/59290
Iteration: 40652/59290
Iteration: 40653/59290
Iteration: 40654/59290
Iteration: 40655/59290
Iteration: 40656/59290
Iteration: 40657/59290
Iteration: 40658/59290
Iteration: 40659/59290
Iteration: 40660/59290
Iteration: 40661/59290
Iteration: 40662/59290
Iteration: 40663/59290
Iteration: 40664/59290

 69%|██████▊   | 40650/59290 [29:02<11:46, 26.38it/s]

Iteration: 40665/59290
Iteration: 40666/59290
Iteration: 40667/59290
Iteration: 40668/59290
Iteration: 40669/59290
Iteration: 40670/59290
Iteration: 40671/59290
Iteration: 40672/59290
Iteration: 40673/59290
Iteration: 40674/59290
Iteration: 40675/59290
Iteration: 40676/59290
Iteration: 40677/59290
Iteration: 40678/59290
Iteration: 40679/59290
Iteration: 40680/59290
Iteration: 40681/59290
Iteration: 40682/59290
Iteration: 40683/59290
Iteration: 40684/59290
Iteration: 40685/59290
Iteration: 40686/59290
Iteration: 40687/59290
Iteration: 40688/59290

 69%|██████▊   | 40674/59290 [29:02<09:40, 32.05it/s]

Iteration: 40689/59290
Iteration: 40690/59290
Iteration: 40691/59290
Iteration: 40692/59290
Iteration: 40693/59290
Iteration: 40694/59290
Iteration: 40695/59290
Iteration: 40696/59290
Iteration: 40697/59290
Iteration: 40698/59290
Iteration: 40699/59290
Iteration: 40700/59290
Iteration: 40701/59290
Iteration: 40702/59290
Iteration: 40703/59290
Iteration: 40704/59290
Iteration: 40705/59290
Iteration: 40706/59290
Iteration: 40707/59290
Iteration: 40708/59290
Iteration: 40709/59290
Iteration: 40710/59290
Iteration: 40711/59290
Iteration: 40712/59290

 69%|██████▊   | 40698/59290 [29:03<08:14, 37.60it/s]

Iteration: 40713/59290
Iteration: 40714/59290
Iteration: 40715/59290
Iteration: 40716/59290
Iteration: 40717/59290
Iteration: 40718/59290
Iteration: 40719/59290
Iteration: 40720/59290
Iteration: 40721/59290
Iteration: 40722/59290
Iteration: 40723/59290
Iteration: 40724/59290
Iteration: 40725/59290
Iteration: 40726/59290
Iteration: 40727/59290
Iteration: 40728/59290
Iteration: 40729/59290
Iteration: 40730/59290
Iteration: 40731/59290
Iteration: 40732/59290
Iteration: 40733/59290
Iteration: 40734/59290
Iteration: 40735/59290
Iteration: 40736/59290

 69%|██████▊   | 40722/59290 [29:03<07:13, 42.84it/s]

Iteration: 40737/59290
Iteration: 40738/59290
Iteration: 40739/59290
Iteration: 40740/59290
Iteration: 40741/59290
Iteration: 40742/59290
Iteration: 40743/59290
Iteration: 40744/59290
Iteration: 40745/59290
Iteration: 40746/59290
Iteration: 40747/59290
Iteration: 40748/59290
Iteration: 40749/59290
Iteration: 40750/59290
Iteration: 40751/59290
Iteration: 40752/59290
Iteration: 40753/59290
Iteration: 40754/59290
Iteration: 40755/59290
Iteration: 40756/59290
Iteration: 40757/59290
Iteration: 40758/59290
Iteration: 40759/59290
Iteration: 40760/59290

 69%|██████▊   | 40746/59290 [29:05<10:42, 28.84it/s]

Iteration: 40761/59290
Iteration: 40762/59290
Iteration: 40763/59290
Iteration: 40764/59290
Iteration: 40765/59290
Iteration: 40766/59290
Iteration: 40767/59290
Iteration: 40768/59290
Iteration: 40769/59290
Iteration: 40770/59290
Iteration: 40771/59290
Iteration: 40772/59290
Iteration: 40773/59290
Iteration: 40774/59290
Iteration: 40775/59290
Iteration: 40776/59290
Iteration: 40777/59290
Iteration: 40778/59290
Iteration: 40779/59290
Iteration: 40780/59290
Iteration: 40781/59290
Iteration: 40782/59290
Iteration: 40783/59290
Iteration: 40784/59290

 69%|██████▉   | 40770/59290 [29:07<15:00, 20.57it/s]

Iteration: 40785/59290
Iteration: 40786/59290
Iteration: 40787/59290
Iteration: 40788/59290
Iteration: 40789/59290
Iteration: 40790/59290
Iteration: 40791/59290
Iteration: 40792/59290
Iteration: 40793/59290
Iteration: 40794/59290
Iteration: 40795/59290
Iteration: 40796/59290
Iteration: 40797/59290
Iteration: 40798/59290
Iteration: 40799/59290
Iteration: 40800/59290
Iteration: 40801/59290
Iteration: 40802/59290
Iteration: 40803/59290
Iteration: 40804/59290
Iteration: 40805/59290
Iteration: 40806/59290
Iteration: 40807/59290
Iteration: 40808/59290

 69%|██████▉   | 40794/59290 [29:07<12:43, 24.21it/s]

Iteration: 40809/59290
Iteration: 40810/59290
Iteration: 40811/59290
Iteration: 40812/59290
Iteration: 40813/59290
Iteration: 40814/59290
Iteration: 40815/59290
Iteration: 40816/59290
Iteration: 40817/59290
Iteration: 40818/59290
Iteration: 40819/59290
Iteration: 40820/59290
Iteration: 40821/59290
Iteration: 40822/59290
Iteration: 40823/59290
Iteration: 40824/59290
Iteration: 40825/59290
Iteration: 40826/59290
Iteration: 40827/59290
Iteration: 40828/59290
Iteration: 40829/59290
Iteration: 40830/59290
Iteration: 40831/59290
Iteration: 40832/59290

 69%|██████▉   | 40818/59290 [29:08<10:22, 29.66it/s]

Iteration: 40833/59290
Iteration: 40834/59290
Iteration: 40835/59290
Iteration: 40836/59290
Iteration: 40837/59290
Iteration: 40838/59290
Iteration: 40839/59290
Iteration: 40840/59290
Iteration: 40841/59290
Iteration: 40842/59290
Iteration: 40843/59290
Iteration: 40844/59290
Iteration: 40845/59290
Iteration: 40846/59290
Iteration: 40847/59290
Iteration: 40848/59290
Iteration: 40849/59290
Iteration: 40850/59290
Iteration: 40851/59290
Iteration: 40852/59290
Iteration: 40853/59290
Iteration: 40854/59290
Iteration: 40855/59290
Iteration: 40856/59290

 69%|██████▉   | 40842/59290 [29:08<08:42, 35.33it/s]

Iteration: 40857/59290
Iteration: 40858/59290
Iteration: 40859/59290
Iteration: 40860/59290
Iteration: 40861/59290
Iteration: 40862/59290
Iteration: 40863/59290
Iteration: 40864/59290
Iteration: 40865/59290
Iteration: 40866/59290
Iteration: 40867/59290
Iteration: 40868/59290
Iteration: 40869/59290
Iteration: 40870/59290
Iteration: 40871/59290
Iteration: 40872/59290
Iteration: 40873/59290
Iteration: 40874/59290
Iteration: 40875/59290
Iteration: 40876/59290
Iteration: 40877/59290
Iteration: 40878/59290
Iteration: 40879/59290
Iteration: 40880/59290

 69%|██████▉   | 40866/59290 [29:08<07:33, 40.64it/s]

Iteration: 40881/59290
Iteration: 40882/59290
Iteration: 40883/59290
Iteration: 40884/59290
Iteration: 40885/59290
Iteration: 40886/59290
Iteration: 40887/59290
Iteration: 40888/59290
Iteration: 40889/59290
Iteration: 40890/59290
Iteration: 40891/59290
Iteration: 40892/59290
Iteration: 40893/59290
Iteration: 40894/59290
Iteration: 40895/59290
Iteration: 40896/59290
Iteration: 40897/59290
Iteration: 40898/59290
Iteration: 40899/59290
Iteration: 40900/59290
Iteration: 40901/59290
Iteration: 40902/59290
Iteration: 40903/59290
Iteration: 40904/59290

 69%|██████▉   | 40890/59290 [29:09<09:29, 32.29it/s]

Iteration: 40905/59290
Iteration: 40906/59290
Iteration: 40907/59290
Iteration: 40908/59290
Iteration: 40909/59290
Iteration: 40910/59290
Iteration: 40911/59290
Iteration: 40912/59290
Iteration: 40913/59290
Iteration: 40914/59290
Iteration: 40915/59290
Iteration: 40916/59290
Iteration: 40917/59290
Iteration: 40918/59290
Iteration: 40919/59290
Iteration: 40920/59290
Iteration: 40921/59290
Iteration: 40922/59290
Iteration: 40923/59290
Iteration: 40924/59290
Iteration: 40925/59290
Iteration: 40926/59290
Iteration: 40927/59290
Iteration: 40928/59290

 69%|██████▉   | 40914/59290 [29:11<14:10, 21.61it/s]

Iteration: 40929/59290
Iteration: 40930/59290
Iteration: 40931/59290
Iteration: 40932/59290
Iteration: 40933/59290
Iteration: 40934/59290
Iteration: 40935/59290
Iteration: 40936/59290
Iteration: 40937/59290
Iteration: 40938/59290
Iteration: 40939/59290
Iteration: 40940/59290
Iteration: 40941/59290
Iteration: 40942/59290
Iteration: 40943/59290
Iteration: 40944/59290
Iteration: 40945/59290
Iteration: 40946/59290
Iteration: 40947/59290
Iteration: 40948/59290
Iteration: 40949/59290
Iteration: 40950/59290
Iteration: 40951/59290
Iteration: 40952/59290

 69%|██████▉   | 40938/59290 [29:12<11:35, 26.40it/s]

Iteration: 40953/59290
Iteration: 40954/59290
Iteration: 40955/59290
Iteration: 40956/59290
Iteration: 40957/59290
Iteration: 40958/59290
Iteration: 40959/59290
Iteration: 40960/59290
Iteration: 40961/59290
Iteration: 40962/59290
Iteration: 40963/59290
Iteration: 40964/59290
Iteration: 40965/59290
Iteration: 40966/59290
Iteration: 40967/59290
Iteration: 40968/59290
Iteration: 40969/59290
Iteration: 40970/59290
Iteration: 40971/59290
Iteration: 40972/59290
Iteration: 40973/59290
Iteration: 40974/59290
Iteration: 40975/59290
Iteration: 40976/59290

 69%|██████▉   | 40962/59290 [29:12<09:33, 31.96it/s]

Iteration: 40977/59290
Iteration: 40978/59290
Iteration: 40979/59290
Iteration: 40980/59290
Iteration: 40981/59290
Iteration: 40982/59290
Iteration: 40983/59290
Iteration: 40984/59290
Iteration: 40985/59290
Iteration: 40986/59290
Iteration: 40987/59290
Iteration: 40988/59290
Iteration: 40989/59290
Iteration: 40990/59290
Iteration: 40991/59290
Iteration: 40992/59290
Iteration: 40993/59290
Iteration: 40994/59290
Iteration: 40995/59290
Iteration: 40996/59290
Iteration: 40997/59290
Iteration: 40998/59290
Iteration: 40999/59290
Iteration: 41000/59290

 69%|██████▉   | 40986/59290 [29:13<08:13, 37.05it/s]

Iteration: 41001/59290
Iteration: 41002/59290
Iteration: 41003/59290
Iteration: 41004/59290
Iteration: 41005/59290
Iteration: 41006/59290
Iteration: 41007/59290
Iteration: 41008/59290
Iteration: 41009/59290
Iteration: 41010/59290
Iteration: 41011/59290
Iteration: 41012/59290
Iteration: 41013/59290
Iteration: 41014/59290
Iteration: 41015/59290
Iteration: 41016/59290
Iteration: 41017/59290
Iteration: 41018/59290
Iteration: 41019/59290
Iteration: 41020/59290
Iteration: 41021/59290
Iteration: 41022/59290
Iteration: 41023/59290
Iteration: 41024/59290

 69%|██████▉   | 41010/59290 [29:13<07:10, 42.41it/s]

Iteration: 41025/59290
Iteration: 41026/59290
Iteration: 41027/59290
Iteration: 41028/59290
Iteration: 41029/59290
Iteration: 41030/59290
Iteration: 41031/59290
Iteration: 41032/59290
Iteration: 41033/59290
Iteration: 41034/59290
Iteration: 41035/59290
Iteration: 41036/59290
Iteration: 41037/59290
Iteration: 41038/59290
Iteration: 41039/59290
Iteration: 41040/59290
Iteration: 41041/59290
Iteration: 41042/59290
Iteration: 41043/59290
Iteration: 41044/59290
Iteration: 41045/59290
Iteration: 41046/59290
Iteration: 41047/59290
Iteration: 41048/59290

 69%|██████▉   | 41034/59290 [29:13<06:26, 47.19it/s]

Iteration: 41049/59290
Iteration: 41050/59290
Iteration: 41051/59290
Iteration: 41052/59290
Iteration: 41053/59290
Iteration: 41054/59290
Iteration: 41055/59290
Iteration: 41056/59290
Iteration: 41057/59290
Iteration: 41058/59290
Iteration: 41059/59290
Iteration: 41060/59290
Iteration: 41061/59290
Iteration: 41062/59290
Iteration: 41063/59290
Iteration: 41064/59290
Iteration: 41065/59290
Iteration: 41066/59290
Iteration: 41067/59290
Iteration: 41068/59290
Iteration: 41069/59290
Iteration: 41070/59290
Iteration: 41071/59290
Iteration: 41072/59290

 69%|██████▉   | 41058/59290 [29:14<05:55, 51.27it/s]

Iteration: 41073/59290
Iteration: 41074/59290
Iteration: 41075/59290
Iteration: 41076/59290
Iteration: 41077/59290
Iteration: 41078/59290
Iteration: 41079/59290
Iteration: 41080/59290
Iteration: 41081/59290
Iteration: 41082/59290
Iteration: 41083/59290
Iteration: 41084/59290
Iteration: 41085/59290
Iteration: 41086/59290
Iteration: 41087/59290
Iteration: 41088/59290
Iteration: 41089/59290
Iteration: 41090/59290
Iteration: 41091/59290
Iteration: 41092/59290
Iteration: 41093/59290
Iteration: 41094/59290
Iteration: 41095/59290
Iteration: 41096/59290

 69%|██████▉   | 41082/59290 [29:14<05:34, 54.43it/s]

Iteration: 41097/59290
Iteration: 41098/59290
Iteration: 41099/59290
Iteration: 41100/59290
Iteration: 41101/59290
Iteration: 41102/59290
Iteration: 41103/59290
Iteration: 41104/59290
Iteration: 41105/59290
Iteration: 41106/59290
Iteration: 41107/59290
Iteration: 41108/59290
Iteration: 41109/59290
Iteration: 41110/59290
Iteration: 41111/59290
Iteration: 41112/59290
Iteration: 41113/59290
Iteration: 41114/59290
Iteration: 41115/59290
Iteration: 41116/59290
Iteration: 41117/59290
Iteration: 41118/59290
Iteration: 41119/59290
Iteration: 41120/59290

 69%|██████▉   | 41106/59290 [29:15<05:20, 56.71it/s]

Iteration: 41121/59290
Iteration: 41122/59290
Iteration: 41123/59290
Iteration: 41124/59290
Iteration: 41125/59290
Iteration: 41126/59290
Iteration: 41127/59290
Iteration: 41128/59290
Iteration: 41129/59290
Iteration: 41130/59290
Iteration: 41131/59290
Iteration: 41132/59290
Iteration: 41133/59290
Iteration: 41134/59290
Iteration: 41135/59290
Iteration: 41136/59290
Iteration: 41137/59290
Iteration: 41138/59290
Iteration: 41139/59290
Iteration: 41140/59290
Iteration: 41141/59290
Iteration: 41142/59290
Iteration: 41143/59290
Iteration: 41144/59290

 69%|██████▉   | 41130/59290 [29:16<08:41, 34.82it/s]

Iteration: 41145/59290
Iteration: 41146/59290
Iteration: 41147/59290
Iteration: 41148/59290
Iteration: 41149/59290
Iteration: 41150/59290
Iteration: 41151/59290
Iteration: 41152/59290
Iteration: 41153/59290
Iteration: 41154/59290
Iteration: 41155/59290
Iteration: 41156/59290
Iteration: 41157/59290
Iteration: 41158/59290
Iteration: 41159/59290
Iteration: 41160/59290
Iteration: 41161/59290
Iteration: 41162/59290
Iteration: 41163/59290
Iteration: 41164/59290
Iteration: 41165/59290
Iteration: 41166/59290
Iteration: 41167/59290
Iteration: 41168/59290

 69%|██████▉   | 41154/59290 [29:18<14:14, 21.22it/s]

Iteration: 41169/59290
Iteration: 41170/59290
Iteration: 41171/59290
Iteration: 41172/59290
Iteration: 41173/59290
Iteration: 41174/59290
Iteration: 41175/59290
Iteration: 41176/59290
Iteration: 41177/59290
Iteration: 41178/59290
Iteration: 41179/59290
Iteration: 41180/59290
Iteration: 41181/59290
Iteration: 41182/59290
Iteration: 41183/59290
Iteration: 41184/59290
Iteration: 41185/59290
Iteration: 41186/59290
Iteration: 41187/59290
Iteration: 41188/59290
Iteration: 41189/59290
Iteration: 41190/59290
Iteration: 41191/59290
Iteration: 41192/59290

 69%|██████▉   | 41178/59290 [29:18<11:25, 26.42it/s]

Iteration: 41193/59290
Iteration: 41194/59290
Iteration: 41195/59290
Iteration: 41196/59290
Iteration: 41197/59290
Iteration: 41198/59290
Iteration: 41199/59290
Iteration: 41200/59290
Iteration: 41201/59290
Iteration: 41202/59290
Iteration: 41203/59290
Iteration: 41204/59290
Iteration: 41205/59290
Iteration: 41206/59290
Iteration: 41207/59290
Iteration: 41208/59290
Iteration: 41209/59290
Iteration: 41210/59290
Iteration: 41211/59290
Iteration: 41212/59290
Iteration: 41213/59290
Iteration: 41214/59290
Iteration: 41215/59290
Iteration: 41216/59290

 69%|██████▉   | 41202/59290 [29:19<09:25, 31.99it/s]

Iteration: 41217/59290
Iteration: 41218/59290
Iteration: 41219/59290
Iteration: 41220/59290
Iteration: 41221/59290
Iteration: 41222/59290
Iteration: 41223/59290
Iteration: 41224/59290
Iteration: 41225/59290
Iteration: 41226/59290
Iteration: 41227/59290
Iteration: 41228/59290
Iteration: 41229/59290
Iteration: 41230/59290
Iteration: 41231/59290
Iteration: 41232/59290
Iteration: 41233/59290
Iteration: 41234/59290
Iteration: 41235/59290
Iteration: 41236/59290
Iteration: 41237/59290
Iteration: 41238/59290
Iteration: 41239/59290
Iteration: 41240/59290

 70%|██████▉   | 41226/59290 [29:19<08:03, 37.40it/s]

Iteration: 41241/59290
Iteration: 41242/59290
Iteration: 41243/59290
Iteration: 41244/59290
Iteration: 41245/59290
Iteration: 41246/59290
Iteration: 41247/59290
Iteration: 41248/59290
Iteration: 41249/59290
Iteration: 41250/59290
Iteration: 41251/59290
Iteration: 41252/59290
Iteration: 41253/59290
Iteration: 41254/59290
Iteration: 41255/59290
Iteration: 41256/59290
Iteration: 41257/59290
Iteration: 41258/59290
Iteration: 41259/59290
Iteration: 41260/59290
Iteration: 41261/59290
Iteration: 41262/59290
Iteration: 41263/59290
Iteration: 41264/59290

 70%|██████▉   | 41250/59290 [29:20<07:07, 42.21it/s]

Iteration: 41265/59290
Iteration: 41266/59290
Iteration: 41267/59290
Iteration: 41268/59290
Iteration: 41269/59290
Iteration: 41270/59290
Iteration: 41271/59290
Iteration: 41272/59290
Iteration: 41273/59290
Iteration: 41274/59290
Iteration: 41275/59290
Iteration: 41276/59290
Iteration: 41277/59290
Iteration: 41278/59290
Iteration: 41279/59290
Iteration: 41280/59290
Iteration: 41281/59290
Iteration: 41282/59290
Iteration: 41283/59290
Iteration: 41284/59290
Iteration: 41285/59290
Iteration: 41286/59290
Iteration: 41287/59290
Iteration: 41288/59290

 70%|██████▉   | 41274/59290 [29:52<2:07:01,  2.36it/s]

Iteration: 41289/59290
Iteration: 41290/59290
Iteration: 41291/59290
Iteration: 41292/59290
Iteration: 41293/59290
Iteration: 41294/59290
Iteration: 41295/59290
Iteration: 41296/59290
Iteration: 41297/59290
Iteration: 41298/59290
Iteration: 41299/59290
Iteration: 41300/59290
Iteration: 41301/59290
Iteration: 41302/59290
Iteration: 41303/59290
Iteration: 41304/59290
Iteration: 41305/59290
Iteration: 41306/59290
Iteration: 41307/59290
Iteration: 41308/59290
Iteration: 41309/59290
Iteration: 41310/59290
Iteration: 41311/59290
Iteration: 41312/59290

 70%|██████▉   | 41298/59290 [29:53<1:30:13,  3.32it/s]

Iteration: 41313/59290
Iteration: 41314/59290
Iteration: 41315/59290
Iteration: 41316/59290
Iteration: 41317/59290
Iteration: 41318/59290
Iteration: 41319/59290
Iteration: 41320/59290
Iteration: 41321/59290
Iteration: 41322/59290
Iteration: 41323/59290
Iteration: 41324/59290
Iteration: 41325/59290
Iteration: 41326/59290
Iteration: 41327/59290
Iteration: 41328/59290
Iteration: 41329/59290
Iteration: 41330/59290
Iteration: 41331/59290
Iteration: 41332/59290
Iteration: 41333/59290
Iteration: 41334/59290
Iteration: 41335/59290
Iteration: 41336/59290

 70%|██████▉   | 41322/59290 [29:53<1:04:30,  4.64it/s]

Iteration: 41337/59290
Iteration: 41338/59290
Iteration: 41339/59290
Iteration: 41340/59290
Iteration: 41341/59290
Iteration: 41342/59290
Iteration: 41343/59290
Iteration: 41344/59290
Iteration: 41345/59290
Iteration: 41346/59290
Iteration: 41347/59290
Iteration: 41348/59290
Iteration: 41349/59290
Iteration: 41350/59290
Iteration: 41351/59290
Iteration: 41352/59290
Iteration: 41353/59290
Iteration: 41354/59290
Iteration: 41355/59290
Iteration: 41356/59290
Iteration: 41357/59290
Iteration: 41358/59290
Iteration: 41359/59290
Iteration: 41360/59290

 70%|██████▉   | 41346/59290 [29:53<46:30,  6.43it/s]

Iteration: 41361/59290
Iteration: 41362/59290
Iteration: 41363/59290
Iteration: 41364/59290
Iteration: 41365/59290
Iteration: 41366/59290
Iteration: 41367/59290
Iteration: 41368/59290
Iteration: 41369/59290
Iteration: 41370/59290
Iteration: 41371/59290
Iteration: 41372/59290
Iteration: 41373/59290
Iteration: 41374/59290
Iteration: 41375/59290
Iteration: 41376/59290
Iteration: 41377/59290
Iteration: 41378/59290
Iteration: 41379/59290
Iteration: 41380/59290
Iteration: 41381/59290
Iteration: 41382/59290
Iteration: 41383/59290
Iteration: 41384/59290

 70%|██████▉   | 41370/59290 [29:54<33:58,  8.79it/s]

Iteration: 41385/59290
Iteration: 41386/59290
Iteration: 41387/59290
Iteration: 41388/59290
Iteration: 41389/59290
Iteration: 41390/59290
Iteration: 41391/59290
Iteration: 41392/59290
Iteration: 41393/59290
Iteration: 41394/59290
Iteration: 41395/59290
Iteration: 41396/59290
Iteration: 41397/59290
Iteration: 41398/59290
Iteration: 41399/59290
Iteration: 41400/59290
Iteration: 41401/59290
Iteration: 41402/59290
Iteration: 41403/59290
Iteration: 41404/59290
Iteration: 41405/59290
Iteration: 41406/59290
Iteration: 41407/59290
Iteration: 41408/59290

 70%|██████▉   | 41394/59290 [29:55<28:22, 10.51it/s]

Iteration: 41409/59290
Iteration: 41410/59290
Iteration: 41411/59290
Iteration: 41412/59290
Iteration: 41413/59290
Iteration: 41414/59290
Iteration: 41415/59290
Iteration: 41416/59290
Iteration: 41417/59290
Iteration: 41418/59290
Iteration: 41419/59290
Iteration: 41420/59290
Iteration: 41421/59290
Iteration: 41422/59290
Iteration: 41423/59290
Iteration: 41424/59290
Iteration: 41425/59290
Iteration: 41426/59290
Iteration: 41427/59290
Iteration: 41428/59290
Iteration: 41429/59290
Iteration: 41430/59290
Iteration: 41431/59290
Iteration: 41432/59290

 70%|██████▉   | 41418/59290 [29:57<28:22, 10.50it/s]

Iteration: 41433/59290
Iteration: 41434/59290
Iteration: 41435/59290
Iteration: 41436/59290
Iteration: 41437/59290
Iteration: 41438/59290
Iteration: 41439/59290
Iteration: 41440/59290
Iteration: 41441/59290
Iteration: 41442/59290
Iteration: 41443/59290
Iteration: 41444/59290
Iteration: 41445/59290
Iteration: 41446/59290
Iteration: 41447/59290
Iteration: 41448/59290
Iteration: 41449/59290
Iteration: 41450/59290
Iteration: 41451/59290
Iteration: 41452/59290
Iteration: 41453/59290
Iteration: 41454/59290
Iteration: 41455/59290
Iteration: 41456/59290

 70%|██████▉   | 41442/59290 [29:58<21:13, 14.02it/s]

Iteration: 41457/59290
Iteration: 41458/59290
Iteration: 41459/59290
Iteration: 41460/59290
Iteration: 41461/59290
Iteration: 41462/59290
Iteration: 41463/59290
Iteration: 41464/59290
Iteration: 41465/59290
Iteration: 41466/59290
Iteration: 41467/59290
Iteration: 41468/59290
Iteration: 41469/59290
Iteration: 41470/59290
Iteration: 41471/59290
Iteration: 41472/59290
Iteration: 41473/59290
Iteration: 41474/59290
Iteration: 41475/59290
Iteration: 41476/59290
Iteration: 41477/59290
Iteration: 41478/59290
Iteration: 41479/59290
Iteration: 41480/59290

 70%|██████▉   | 41466/59290 [29:58<16:14, 18.29it/s]

Iteration: 41481/59290
Iteration: 41482/59290
Iteration: 41483/59290
Iteration: 41484/59290
Iteration: 41485/59290
Iteration: 41486/59290
Iteration: 41487/59290
Iteration: 41488/59290
Iteration: 41489/59290
Iteration: 41490/59290
Iteration: 41491/59290
Iteration: 41492/59290
Iteration: 41493/59290
Iteration: 41494/59290
Iteration: 41495/59290
Iteration: 41496/59290
Iteration: 41497/59290
Iteration: 41498/59290
Iteration: 41499/59290
Iteration: 41500/59290
Iteration: 41501/59290
Iteration: 41502/59290
Iteration: 41503/59290
Iteration: 41504/59290

 70%|██████▉   | 41490/59290 [29:58<12:44, 23.28it/s]

Iteration: 41505/59290
Iteration: 41506/59290
Iteration: 41507/59290
Iteration: 41508/59290
Iteration: 41509/59290
Iteration: 41510/59290
Iteration: 41511/59290
Iteration: 41512/59290
Iteration: 41513/59290
Iteration: 41514/59290
Iteration: 41515/59290
Iteration: 41516/59290
Iteration: 41517/59290
Iteration: 41518/59290
Iteration: 41519/59290
Iteration: 41520/59290
Iteration: 41521/59290
Iteration: 41522/59290
Iteration: 41523/59290
Iteration: 41524/59290
Iteration: 41525/59290
Iteration: 41526/59290
Iteration: 41527/59290
Iteration: 41528/59290

 70%|███████   | 41514/59290 [30:00<13:30, 21.95it/s]

Iteration: 41529/59290
Iteration: 41530/59290
Iteration: 41531/59290
Iteration: 41532/59290
Iteration: 41533/59290
Iteration: 41534/59290
Iteration: 41535/59290
Iteration: 41536/59290
Iteration: 41537/59290
Iteration: 41538/59290
Iteration: 41539/59290
Iteration: 41540/59290
Iteration: 41541/59290
Iteration: 41542/59290
Iteration: 41543/59290
Iteration: 41544/59290
Iteration: 41545/59290
Iteration: 41546/59290
Iteration: 41547/59290
Iteration: 41548/59290
Iteration: 41549/59290
Iteration: 41550/59290
Iteration: 41551/59290
Iteration: 41552/59290

 70%|███████   | 41538/59290 [30:02<16:55, 17.49it/s]

Iteration: 41553/59290
Iteration: 41554/59290
Iteration: 41555/59290
Iteration: 41556/59290
Iteration: 41557/59290
Iteration: 41558/59290
Iteration: 41559/59290
Iteration: 41560/59290
Iteration: 41561/59290
Iteration: 41562/59290
Iteration: 41563/59290
Iteration: 41564/59290
Iteration: 41565/59290
Iteration: 41566/59290
Iteration: 41567/59290
Iteration: 41568/59290
Iteration: 41569/59290
Iteration: 41570/59290
Iteration: 41571/59290
Iteration: 41572/59290
Iteration: 41573/59290
Iteration: 41574/59290
Iteration: 41575/59290
Iteration: 41576/59290

 70%|███████   | 41562/59290 [30:02<13:52, 21.31it/s]

Iteration: 41577/59290
Iteration: 41578/59290
Iteration: 41579/59290
Iteration: 41580/59290
Iteration: 41581/59290
Iteration: 41582/59290
Iteration: 41583/59290
Iteration: 41584/59290
Iteration: 41585/59290
Iteration: 41586/59290
Iteration: 41587/59290
Iteration: 41588/59290
Iteration: 41589/59290
Iteration: 41590/59290
Iteration: 41591/59290
Iteration: 41592/59290
Iteration: 41593/59290
Iteration: 41594/59290
Iteration: 41595/59290
Iteration: 41596/59290
Iteration: 41597/59290
Iteration: 41598/59290
Iteration: 41599/59290
Iteration: 41600/59290

 70%|███████   | 41586/59290 [30:03<11:04, 26.65it/s]

Iteration: 41601/59290
Iteration: 41602/59290
Iteration: 41603/59290
Iteration: 41604/59290
Iteration: 41605/59290
Iteration: 41606/59290
Iteration: 41607/59290
Iteration: 41608/59290
Iteration: 41609/59290
Iteration: 41610/59290
Iteration: 41611/59290
Iteration: 41612/59290
Iteration: 41613/59290
Iteration: 41614/59290
Iteration: 41615/59290
Iteration: 41616/59290
Iteration: 41617/59290
Iteration: 41618/59290
Iteration: 41619/59290
Iteration: 41620/59290
Iteration: 41621/59290
Iteration: 41622/59290
Iteration: 41623/59290
Iteration: 41624/59290

 70%|███████   | 41610/59290 [30:03<09:07, 32.32it/s]

Iteration: 41625/59290
Iteration: 41626/59290
Iteration: 41627/59290
Iteration: 41628/59290
Iteration: 41629/59290
Iteration: 41630/59290
Iteration: 41631/59290
Iteration: 41632/59290
Iteration: 41633/59290
Iteration: 41634/59290
Iteration: 41635/59290
Iteration: 41636/59290
Iteration: 41637/59290
Iteration: 41638/59290
Iteration: 41639/59290
Iteration: 41640/59290
Iteration: 41641/59290
Iteration: 41642/59290
Iteration: 41643/59290
Iteration: 41644/59290
Iteration: 41645/59290
Iteration: 41646/59290
Iteration: 41647/59290
Iteration: 41648/59290

 70%|███████   | 41634/59290 [30:03<07:46, 37.84it/s]

Iteration: 41649/59290
Iteration: 41650/59290
Iteration: 41651/59290
Iteration: 41652/59290
Iteration: 41653/59290
Iteration: 41654/59290
Iteration: 41655/59290
Iteration: 41656/59290
Iteration: 41657/59290
Iteration: 41658/59290
Iteration: 41659/59290
Iteration: 41660/59290
Iteration: 41661/59290
Iteration: 41662/59290
Iteration: 41663/59290
Iteration: 41664/59290
Iteration: 41665/59290
Iteration: 41666/59290
Iteration: 41667/59290
Iteration: 41668/59290
Iteration: 41669/59290
Iteration: 41670/59290
Iteration: 41671/59290
Iteration: 41672/59290

 70%|███████   | 41658/59290 [30:04<06:48, 43.14it/s]

Iteration: 41673/59290
Iteration: 41674/59290
Iteration: 41675/59290
Iteration: 41676/59290
Iteration: 41677/59290
Iteration: 41678/59290
Iteration: 41679/59290
Iteration: 41680/59290
Iteration: 41681/59290
Iteration: 41682/59290
Iteration: 41683/59290
Iteration: 41684/59290
Iteration: 41685/59290
Iteration: 41686/59290
Iteration: 41687/59290
Iteration: 41688/59290
Iteration: 41689/59290
Iteration: 41690/59290
Iteration: 41691/59290
Iteration: 41692/59290
Iteration: 41693/59290
Iteration: 41694/59290
Iteration: 41695/59290
Iteration: 41696/59290

 70%|███████   | 41682/59290 [30:05<08:46, 33.44it/s]

Iteration: 41697/59290
Iteration: 41698/59290
Iteration: 41699/59290
Iteration: 41700/59290
Iteration: 41701/59290
Iteration: 41702/59290
Iteration: 41703/59290
Iteration: 41704/59290
Iteration: 41705/59290
Iteration: 41706/59290
Iteration: 41707/59290
Iteration: 41708/59290
Iteration: 41709/59290
Iteration: 41710/59290
Iteration: 41711/59290
Iteration: 41712/59290
Iteration: 41713/59290
Iteration: 41714/59290
Iteration: 41715/59290
Iteration: 41716/59290
Iteration: 41717/59290
Iteration: 41718/59290
Iteration: 41719/59290
Iteration: 41720/59290

 70%|███████   | 41706/59290 [30:07<13:08, 22.31it/s]

Iteration: 41721/59290
Iteration: 41722/59290
Iteration: 41723/59290
Iteration: 41724/59290
Iteration: 41725/59290
Iteration: 41726/59290
Iteration: 41727/59290
Iteration: 41728/59290
Iteration: 41729/59290
Iteration: 41730/59290
Iteration: 41731/59290
Iteration: 41732/59290
Iteration: 41733/59290
Iteration: 41734/59290
Iteration: 41735/59290
Iteration: 41736/59290
Iteration: 41737/59290
Iteration: 41738/59290
Iteration: 41739/59290
Iteration: 41740/59290
Iteration: 41741/59290
Iteration: 41742/59290
Iteration: 41743/59290
Iteration: 41744/59290

 70%|███████   | 41730/59290 [30:07<10:43, 27.30it/s]

Iteration: 41745/59290
Iteration: 41746/59290
Iteration: 41747/59290
Iteration: 41748/59290
Iteration: 41749/59290
Iteration: 41750/59290
Iteration: 41751/59290
Iteration: 41752/59290
Iteration: 41753/59290
Iteration: 41754/59290
Iteration: 41755/59290
Iteration: 41756/59290
Iteration: 41757/59290
Iteration: 41758/59290
Iteration: 41759/59290
Iteration: 41760/59290
Iteration: 41761/59290
Iteration: 41762/59290
Iteration: 41763/59290
Iteration: 41764/59290
Iteration: 41765/59290
Iteration: 41766/59290
Iteration: 41767/59290
Iteration: 41768/59290

 70%|███████   | 41754/59290 [30:07<08:54, 32.83it/s]

Iteration: 41769/59290
Iteration: 41770/59290
Iteration: 41771/59290
Iteration: 41772/59290
Iteration: 41773/59290
Iteration: 41774/59290
Iteration: 41775/59290
Iteration: 41776/59290
Iteration: 41777/59290
Iteration: 41778/59290
Iteration: 41779/59290
Iteration: 41780/59290
Iteration: 41781/59290
Iteration: 41782/59290
Iteration: 41783/59290
Iteration: 41784/59290
Iteration: 41785/59290
Iteration: 41786/59290
Iteration: 41787/59290
Iteration: 41788/59290
Iteration: 41789/59290
Iteration: 41790/59290
Iteration: 41791/59290
Iteration: 41792/59290

 70%|███████   | 41778/59290 [30:08<07:39, 38.08it/s]

Iteration: 41793/59290
Iteration: 41794/59290
Iteration: 41795/59290
Iteration: 41796/59290
Iteration: 41797/59290
Iteration: 41798/59290
Iteration: 41799/59290
Iteration: 41800/59290
Iteration: 41801/59290
Iteration: 41802/59290
Iteration: 41803/59290
Iteration: 41804/59290
Iteration: 41805/59290
Iteration: 41806/59290
Iteration: 41807/59290
Iteration: 41808/59290
Iteration: 41809/59290
Iteration: 41810/59290
Iteration: 41811/59290
Iteration: 41812/59290
Iteration: 41813/59290
Iteration: 41814/59290
Iteration: 41815/59290
Iteration: 41816/59290

 71%|███████   | 41802/59290 [30:08<06:48, 42.81it/s]

Iteration: 41817/59290
Iteration: 41818/59290
Iteration: 41819/59290
Iteration: 41820/59290
Iteration: 41821/59290
Iteration: 41822/59290
Iteration: 41823/59290
Iteration: 41824/59290
Iteration: 41825/59290
Iteration: 41826/59290
Iteration: 41827/59290
Iteration: 41828/59290
Iteration: 41829/59290
Iteration: 41830/59290
Iteration: 41831/59290
Iteration: 41832/59290
Iteration: 41833/59290
Iteration: 41834/59290
Iteration: 41835/59290
Iteration: 41836/59290
Iteration: 41837/59290
Iteration: 41838/59290
Iteration: 41839/59290
Iteration: 41840/59290

 71%|███████   | 41826/59290 [30:09<08:35, 33.87it/s]

Iteration: 41841/59290
Iteration: 41842/59290
Iteration: 41843/59290
Iteration: 41844/59290
Iteration: 41845/59290
Iteration: 41846/59290
Iteration: 41847/59290
Iteration: 41848/59290
Iteration: 41849/59290
Iteration: 41850/59290
Iteration: 41851/59290
Iteration: 41852/59290
Iteration: 41853/59290
Iteration: 41854/59290
Iteration: 41855/59290
Iteration: 41856/59290
Iteration: 41857/59290
Iteration: 41858/59290
Iteration: 41859/59290
Iteration: 41860/59290
Iteration: 41861/59290
Iteration: 41862/59290
Iteration: 41863/59290
Iteration: 41864/59290

 71%|███████   | 41850/59290 [30:11<13:04, 22.23it/s]

Iteration: 41865/59290
Iteration: 41866/59290
Iteration: 41867/59290
Iteration: 41868/59290
Iteration: 41869/59290
Iteration: 41870/59290
Iteration: 41871/59290
Iteration: 41872/59290
Iteration: 41873/59290
Iteration: 41874/59290
Iteration: 41875/59290
Iteration: 41876/59290
Iteration: 41877/59290
Iteration: 41878/59290
Iteration: 41879/59290
Iteration: 41880/59290
Iteration: 41881/59290
Iteration: 41882/59290
Iteration: 41883/59290
Iteration: 41884/59290
Iteration: 41885/59290
Iteration: 41886/59290
Iteration: 41887/59290
Iteration: 41888/59290

 71%|███████   | 41874/59290 [30:12<10:58, 26.44it/s]

Iteration: 41889/59290
Iteration: 41890/59290
Iteration: 41891/59290
Iteration: 41892/59290
Iteration: 41893/59290
Iteration: 41894/59290
Iteration: 41895/59290
Iteration: 41896/59290
Iteration: 41897/59290
Iteration: 41898/59290
Iteration: 41899/59290
Iteration: 41900/59290
Iteration: 41901/59290
Iteration: 41902/59290
Iteration: 41903/59290
Iteration: 41904/59290
Iteration: 41905/59290
Iteration: 41906/59290
Iteration: 41907/59290
Iteration: 41908/59290
Iteration: 41909/59290
Iteration: 41910/59290
Iteration: 41911/59290
Iteration: 41912/59290

 71%|███████   | 41898/59290 [30:12<09:02, 32.04it/s]

Iteration: 41913/59290
Iteration: 41914/59290
Iteration: 41915/59290
Iteration: 41916/59290
Iteration: 41917/59290
Iteration: 41918/59290
Iteration: 41919/59290
Iteration: 41920/59290
Iteration: 41921/59290
Iteration: 41922/59290
Iteration: 41923/59290
Iteration: 41924/59290
Iteration: 41925/59290
Iteration: 41926/59290
Iteration: 41927/59290
Iteration: 41928/59290
Iteration: 41929/59290
Iteration: 41930/59290
Iteration: 41931/59290
Iteration: 41932/59290
Iteration: 41933/59290
Iteration: 41934/59290
Iteration: 41935/59290
Iteration: 41936/59290

 71%|███████   | 41922/59290 [30:12<07:40, 37.69it/s]

Iteration: 41937/59290
Iteration: 41938/59290
Iteration: 41939/59290
Iteration: 41940/59290
Iteration: 41941/59290
Iteration: 41942/59290
Iteration: 41943/59290
Iteration: 41944/59290
Iteration: 41945/59290
Iteration: 41946/59290
Iteration: 41947/59290
Iteration: 41948/59290
Iteration: 41949/59290
Iteration: 41950/59290
Iteration: 41951/59290
Iteration: 41952/59290
Iteration: 41953/59290
Iteration: 41954/59290
Iteration: 41955/59290
Iteration: 41956/59290
Iteration: 41957/59290
Iteration: 41958/59290
Iteration: 41959/59290
Iteration: 41960/59290

 71%|███████   | 41946/59290 [30:13<06:43, 43.01it/s]

Iteration: 41961/59290
Iteration: 41962/59290
Iteration: 41963/59290
Iteration: 41964/59290
Iteration: 41965/59290
Iteration: 41966/59290
Iteration: 41967/59290
Iteration: 41968/59290
Iteration: 41969/59290
Iteration: 41970/59290
Iteration: 41971/59290
Iteration: 41972/59290
Iteration: 41973/59290
Iteration: 41974/59290
Iteration: 41975/59290
Iteration: 41976/59290
Iteration: 41977/59290
Iteration: 41978/59290
Iteration: 41979/59290
Iteration: 41980/59290
Iteration: 41981/59290
Iteration: 41982/59290
Iteration: 41983/59290
Iteration: 41984/59290

 71%|███████   | 41970/59290 [30:13<06:05, 47.33it/s]

Iteration: 41985/59290
Iteration: 41986/59290
Iteration: 41987/59290
Iteration: 41988/59290
Iteration: 41989/59290
Iteration: 41990/59290
Iteration: 41991/59290
Iteration: 41992/59290
Iteration: 41993/59290
Iteration: 41994/59290
Iteration: 41995/59290
Iteration: 41996/59290
Iteration: 41997/59290
Iteration: 41998/59290
Iteration: 41999/59290
Iteration: 42000/59290
Iteration: 42001/59290
Iteration: 42002/59290
Iteration: 42003/59290
Iteration: 42004/59290
Iteration: 42005/59290
Iteration: 42006/59290
Iteration: 42007/59290
Iteration: 42008/59290

 71%|███████   | 41994/59290 [30:14<05:37, 51.26it/s]

Iteration: 42009/59290
Iteration: 42010/59290
Iteration: 42011/59290
Iteration: 42012/59290
Iteration: 42013/59290
Iteration: 42014/59290
Iteration: 42015/59290
Iteration: 42016/59290
Iteration: 42017/59290
Iteration: 42018/59290
Iteration: 42019/59290
Iteration: 42020/59290
Iteration: 42021/59290
Iteration: 42022/59290
Iteration: 42023/59290
Iteration: 42024/59290
Iteration: 42025/59290
Iteration: 42026/59290
Iteration: 42027/59290
Iteration: 42028/59290
Iteration: 42029/59290
Iteration: 42030/59290
Iteration: 42031/59290
Iteration: 42032/59290

 71%|███████   | 42018/59290 [30:14<05:17, 54.42it/s]

Iteration: 42033/59290
Iteration: 42034/59290
Iteration: 42035/59290
Iteration: 42036/59290
Iteration: 42037/59290
Iteration: 42038/59290
Iteration: 42039/59290
Iteration: 42040/59290
Iteration: 42041/59290
Iteration: 42042/59290
Iteration: 42043/59290
Iteration: 42044/59290
Iteration: 42045/59290
Iteration: 42046/59290
Iteration: 42047/59290
Iteration: 42048/59290
Iteration: 42049/59290
Iteration: 42050/59290
Iteration: 42051/59290
Iteration: 42052/59290
Iteration: 42053/59290
Iteration: 42054/59290
Iteration: 42055/59290
Iteration: 42056/59290

 71%|███████   | 42042/59290 [30:15<08:40, 33.14it/s]

Iteration: 42057/59290
Iteration: 42058/59290
Iteration: 42059/59290
Iteration: 42060/59290
Iteration: 42061/59290
Iteration: 42062/59290
Iteration: 42063/59290
Iteration: 42064/59290
Iteration: 42065/59290
Iteration: 42066/59290
Iteration: 42067/59290
Iteration: 42068/59290
Iteration: 42069/59290
Iteration: 42070/59290
Iteration: 42071/59290
Iteration: 42072/59290
Iteration: 42073/59290
Iteration: 42074/59290
Iteration: 42075/59290
Iteration: 42076/59290
Iteration: 42077/59290
Iteration: 42078/59290
Iteration: 42079/59290
Iteration: 42080/59290

 71%|███████   | 42066/59290 [30:18<14:43, 19.49it/s]

Iteration: 42081/59290
Iteration: 42082/59290
Iteration: 42083/59290
Iteration: 42084/59290
Iteration: 42085/59290
Iteration: 42086/59290
Iteration: 42087/59290
Iteration: 42088/59290
Iteration: 42089/59290
Iteration: 42090/59290
Iteration: 42091/59290
Iteration: 42092/59290
Iteration: 42093/59290
Iteration: 42094/59290
Iteration: 42095/59290
Iteration: 42096/59290
Iteration: 42097/59290
Iteration: 42098/59290
Iteration: 42099/59290
Iteration: 42100/59290
Iteration: 42101/59290
Iteration: 42102/59290
Iteration: 42103/59290
Iteration: 42104/59290

 71%|███████   | 42090/59290 [30:18<11:38, 24.63it/s]

Iteration: 42105/59290
Iteration: 42106/59290
Iteration: 42107/59290
Iteration: 42108/59290
Iteration: 42109/59290
Iteration: 42110/59290
Iteration: 42111/59290
Iteration: 42112/59290
Iteration: 42113/59290
Iteration: 42114/59290
Iteration: 42115/59290
Iteration: 42116/59290
Iteration: 42117/59290
Iteration: 42118/59290
Iteration: 42119/59290
Iteration: 42120/59290
Iteration: 42121/59290
Iteration: 42122/59290
Iteration: 42123/59290
Iteration: 42124/59290
Iteration: 42125/59290
Iteration: 42126/59290
Iteration: 42127/59290
Iteration: 42128/59290

 71%|███████   | 42114/59290 [30:19<09:27, 30.24it/s]

Iteration: 42129/59290
Iteration: 42130/59290
Iteration: 42131/59290
Iteration: 42132/59290
Iteration: 42133/59290
Iteration: 42134/59290
Iteration: 42135/59290
Iteration: 42136/59290
Iteration: 42137/59290
Iteration: 42138/59290
Iteration: 42139/59290
Iteration: 42140/59290
Iteration: 42141/59290
Iteration: 42142/59290
Iteration: 42143/59290
Iteration: 42144/59290
Iteration: 42145/59290
Iteration: 42146/59290
Iteration: 42147/59290
Iteration: 42148/59290
Iteration: 42149/59290
Iteration: 42150/59290
Iteration: 42151/59290
Iteration: 42152/59290

 71%|███████   | 42138/59290 [30:19<08:01, 35.63it/s]

Iteration: 42153/59290
Iteration: 42154/59290
Iteration: 42155/59290
Iteration: 42156/59290
Iteration: 42157/59290
Iteration: 42158/59290
Iteration: 42159/59290
Iteration: 42160/59290
Iteration: 42161/59290
Iteration: 42162/59290
Iteration: 42163/59290
Iteration: 42164/59290
Iteration: 42165/59290
Iteration: 42166/59290
Iteration: 42167/59290
Iteration: 42168/59290
Iteration: 42169/59290
Iteration: 42170/59290
Iteration: 42171/59290
Iteration: 42172/59290
Iteration: 42173/59290
Iteration: 42174/59290
Iteration: 42175/59290
Iteration: 42176/59290

 71%|███████   | 42162/59290 [30:19<07:02, 40.50it/s]

Iteration: 42177/59290
Iteration: 42178/59290
Iteration: 42179/59290
Iteration: 42180/59290
Iteration: 42181/59290
Iteration: 42182/59290
Iteration: 42183/59290
Iteration: 42184/59290
Iteration: 42185/59290
Iteration: 42186/59290
Iteration: 42187/59290
Iteration: 42188/59290
Iteration: 42189/59290
Iteration: 42190/59290
Iteration: 42191/59290
Iteration: 42192/59290
Iteration: 42193/59290
Iteration: 42194/59290
Iteration: 42195/59290
Iteration: 42196/59290
Iteration: 42197/59290
Iteration: 42198/59290
Iteration: 42199/59290
Iteration: 42200/59290

 71%|███████   | 42186/59290 [30:20<06:17, 45.28it/s]

Iteration: 42201/59290
Iteration: 42202/59290
Iteration: 42203/59290
Iteration: 42204/59290
Iteration: 42205/59290
Iteration: 42206/59290
Iteration: 42207/59290
Iteration: 42208/59290
Iteration: 42209/59290
Iteration: 42210/59290
Iteration: 42211/59290
Iteration: 42212/59290
Iteration: 42213/59290
Iteration: 42214/59290
Iteration: 42215/59290
Iteration: 42216/59290
Iteration: 42217/59290
Iteration: 42218/59290
Iteration: 42219/59290
Iteration: 42220/59290
Iteration: 42221/59290
Iteration: 42222/59290
Iteration: 42223/59290
Iteration: 42224/59290

 71%|███████   | 42210/59290 [30:20<05:45, 49.46it/s]

Iteration: 42225/59290
Iteration: 42226/59290
Iteration: 42227/59290
Iteration: 42228/59290
Iteration: 42229/59290
Iteration: 42230/59290
Iteration: 42231/59290
Iteration: 42232/59290
Iteration: 42233/59290
Iteration: 42234/59290
Iteration: 42235/59290
Iteration: 42236/59290
Iteration: 42237/59290
Iteration: 42238/59290
Iteration: 42239/59290
Iteration: 42240/59290
Iteration: 42241/59290
Iteration: 42242/59290
Iteration: 42243/59290
Iteration: 42244/59290
Iteration: 42245/59290
Iteration: 42246/59290
Iteration: 42247/59290
Iteration: 42248/59290

 71%|███████   | 42234/59290 [30:21<05:25, 52.46it/s]

Iteration: 42249/59290
Iteration: 42250/59290
Iteration: 42251/59290
Iteration: 42252/59290
Iteration: 42253/59290
Iteration: 42254/59290
Iteration: 42255/59290
Iteration: 42256/59290
Iteration: 42257/59290
Iteration: 42258/59290
Iteration: 42259/59290
Iteration: 42260/59290
Iteration: 42261/59290
Iteration: 42262/59290
Iteration: 42263/59290
Iteration: 42264/59290
Iteration: 42265/59290
Iteration: 42266/59290
Iteration: 42267/59290
Iteration: 42268/59290
Iteration: 42269/59290
Iteration: 42270/59290
Iteration: 42271/59290
Iteration: 42272/59290

 71%|███████▏  | 42258/59290 [30:21<05:06, 55.59it/s]

Iteration: 42273/59290
Iteration: 42274/59290
Iteration: 42275/59290
Iteration: 42276/59290
Iteration: 42277/59290
Iteration: 42278/59290
Iteration: 42279/59290
Iteration: 42280/59290
Iteration: 42281/59290
Iteration: 42282/59290
Iteration: 42283/59290
Iteration: 42284/59290
Iteration: 42285/59290
Iteration: 42286/59290
Iteration: 42287/59290
Iteration: 42288/59290
Iteration: 42289/59290
Iteration: 42290/59290
Iteration: 42291/59290
Iteration: 42292/59290
Iteration: 42293/59290
Iteration: 42294/59290
Iteration: 42295/59290
Iteration: 42296/59290

 71%|███████▏  | 42282/59290 [30:22<07:56, 35.72it/s]

Iteration: 42297/59290
Iteration: 42298/59290
Iteration: 42299/59290
Iteration: 42300/59290
Iteration: 42301/59290
Iteration: 42302/59290
Iteration: 42303/59290
Iteration: 42304/59290
Iteration: 42305/59290
Iteration: 42306/59290
Iteration: 42307/59290
Iteration: 42308/59290
Iteration: 42309/59290
Iteration: 42310/59290
Iteration: 42311/59290
Iteration: 42312/59290
Iteration: 42313/59290
Iteration: 42314/59290
Iteration: 42315/59290
Iteration: 42316/59290
Iteration: 42317/59290
Iteration: 42318/59290
Iteration: 42319/59290
Iteration: 42320/59290

 71%|███████▏  | 42306/59290 [30:24<13:36, 20.79it/s]

Iteration: 42321/59290
Iteration: 42322/59290
Iteration: 42323/59290
Iteration: 42324/59290
Iteration: 42325/59290
Iteration: 42326/59290
Iteration: 42327/59290
Iteration: 42328/59290
Iteration: 42329/59290
Iteration: 42330/59290
Iteration: 42331/59290
Iteration: 42332/59290
Iteration: 42333/59290
Iteration: 42334/59290
Iteration: 42335/59290
Iteration: 42336/59290
Iteration: 42337/59290
Iteration: 42338/59290
Iteration: 42339/59290
Iteration: 42340/59290
Iteration: 42341/59290
Iteration: 42342/59290
Iteration: 42343/59290
Iteration: 42344/59290

 71%|███████▏  | 42330/59290 [30:25<10:50, 26.06it/s]

Iteration: 42345/59290
Iteration: 42346/59290
Iteration: 42347/59290
Iteration: 42348/59290
Iteration: 42349/59290
Iteration: 42350/59290
Iteration: 42351/59290
Iteration: 42352/59290
Iteration: 42353/59290
Iteration: 42354/59290
Iteration: 42355/59290
Iteration: 42356/59290
Iteration: 42357/59290
Iteration: 42358/59290
Iteration: 42359/59290
Iteration: 42360/59290
Iteration: 42361/59290
Iteration: 42362/59290
Iteration: 42363/59290
Iteration: 42364/59290
Iteration: 42365/59290
Iteration: 42366/59290
Iteration: 42367/59290
Iteration: 42368/59290

 71%|███████▏  | 42354/59290 [30:25<09:02, 31.22it/s]

Iteration: 42369/59290
Iteration: 42370/59290
Iteration: 42371/59290
Iteration: 42372/59290
Iteration: 42373/59290
Iteration: 42374/59290
Iteration: 42375/59290
Iteration: 42376/59290
Iteration: 42377/59290
Iteration: 42378/59290
Iteration: 42379/59290
Iteration: 42380/59290
Iteration: 42381/59290
Iteration: 42382/59290
Iteration: 42383/59290
Iteration: 42384/59290
Iteration: 42385/59290
Iteration: 42386/59290
Iteration: 42387/59290
Iteration: 42388/59290
Iteration: 42389/59290
Iteration: 42390/59290
Iteration: 42391/59290
Iteration: 42392/59290

 71%|███████▏  | 42378/59290 [30:26<07:38, 36.88it/s]

Iteration: 42393/59290
Iteration: 42394/59290
Iteration: 42395/59290
Iteration: 42396/59290
Iteration: 42397/59290
Iteration: 42398/59290
Iteration: 42399/59290
Iteration: 42400/59290
Iteration: 42401/59290
Iteration: 42402/59290
Iteration: 42403/59290
Iteration: 42404/59290
Iteration: 42405/59290
Iteration: 42406/59290
Iteration: 42407/59290
Iteration: 42408/59290
Iteration: 42409/59290
Iteration: 42410/59290
Iteration: 42411/59290
Iteration: 42412/59290
Iteration: 42413/59290
Iteration: 42414/59290
Iteration: 42415/59290
Iteration: 42416/59290

 72%|███████▏  | 42402/59290 [30:26<06:40, 42.17it/s]

Iteration: 42417/59290
Iteration: 42418/59290
Iteration: 42419/59290
Iteration: 42420/59290
Iteration: 42421/59290
Iteration: 42422/59290
Iteration: 42423/59290
Iteration: 42424/59290
Iteration: 42425/59290
Iteration: 42426/59290
Iteration: 42427/59290
Iteration: 42428/59290
Iteration: 42429/59290
Iteration: 42430/59290
Iteration: 42431/59290
Iteration: 42432/59290
Iteration: 42433/59290
Iteration: 42434/59290
Iteration: 42435/59290
Iteration: 42436/59290
Iteration: 42437/59290
Iteration: 42438/59290
Iteration: 42439/59290
Iteration: 42440/59290

 72%|███████▏  | 42426/59290 [30:27<08:24, 33.44it/s]

Iteration: 42441/59290
Iteration: 42442/59290
Iteration: 42443/59290
Iteration: 42444/59290
Iteration: 42445/59290
Iteration: 42446/59290
Iteration: 42447/59290
Iteration: 42448/59290
Iteration: 42449/59290
Iteration: 42450/59290
Iteration: 42451/59290
Iteration: 42452/59290
Iteration: 42453/59290
Iteration: 42454/59290
Iteration: 42455/59290
Iteration: 42456/59290
Iteration: 42457/59290
Iteration: 42458/59290
Iteration: 42459/59290
Iteration: 42460/59290
Iteration: 42461/59290
Iteration: 42462/59290
Iteration: 42463/59290
Iteration: 42464/59290

 72%|███████▏  | 42450/59290 [30:29<12:41, 22.11it/s]

Iteration: 42465/59290
Iteration: 42466/59290
Iteration: 42467/59290
Iteration: 42468/59290
Iteration: 42469/59290
Iteration: 42470/59290
Iteration: 42471/59290
Iteration: 42472/59290
Iteration: 42473/59290
Iteration: 42474/59290
Iteration: 42475/59290
Iteration: 42476/59290
Iteration: 42477/59290
Iteration: 42478/59290
Iteration: 42479/59290
Iteration: 42480/59290
Iteration: 42481/59290
Iteration: 42482/59290
Iteration: 42483/59290
Iteration: 42484/59290
Iteration: 42485/59290
Iteration: 42486/59290
Iteration: 42487/59290
Iteration: 42488/59290

 72%|███████▏  | 42474/59290 [30:29<10:21, 27.04it/s]

Iteration: 42489/59290
Iteration: 42490/59290
Iteration: 42491/59290
Iteration: 42492/59290
Iteration: 42493/59290
Iteration: 42494/59290
Iteration: 42495/59290
Iteration: 42496/59290
Iteration: 42497/59290
Iteration: 42498/59290
Iteration: 42499/59290
Iteration: 42500/59290
Iteration: 42501/59290
Iteration: 42502/59290
Iteration: 42503/59290
Iteration: 42504/59290
Iteration: 42505/59290
Iteration: 42506/59290
Iteration: 42507/59290
Iteration: 42508/59290
Iteration: 42509/59290
Iteration: 42510/59290
Iteration: 42511/59290
Iteration: 42512/59290

 72%|███████▏  | 42498/59290 [30:30<08:34, 32.66it/s]

Iteration: 42513/59290
Iteration: 42514/59290
Iteration: 42515/59290
Iteration: 42516/59290
Iteration: 42517/59290
Iteration: 42518/59290
Iteration: 42519/59290
Iteration: 42520/59290
Iteration: 42521/59290
Iteration: 42522/59290
Iteration: 42523/59290
Iteration: 42524/59290
Iteration: 42525/59290
Iteration: 42526/59290
Iteration: 42527/59290
Iteration: 42528/59290
Iteration: 42529/59290
Iteration: 42530/59290
Iteration: 42531/59290
Iteration: 42532/59290
Iteration: 42533/59290
Iteration: 42534/59290
Iteration: 42535/59290
Iteration: 42536/59290

 72%|███████▏  | 42522/59290 [30:30<07:17, 38.33it/s]

Iteration: 42537/59290
Iteration: 42538/59290
Iteration: 42539/59290
Iteration: 42540/59290
Iteration: 42541/59290
Iteration: 42542/59290
Iteration: 42543/59290
Iteration: 42544/59290
Iteration: 42545/59290
Iteration: 42546/59290
Iteration: 42547/59290
Iteration: 42548/59290
Iteration: 42549/59290
Iteration: 42550/59290
Iteration: 42551/59290
Iteration: 42552/59290
Iteration: 42553/59290
Iteration: 42554/59290
Iteration: 42555/59290
Iteration: 42556/59290
Iteration: 42557/59290
Iteration: 42558/59290
Iteration: 42559/59290
Iteration: 42560/59290

 72%|███████▏  | 42546/59290 [30:31<06:30, 42.85it/s]

Iteration: 42561/59290
Iteration: 42562/59290
Iteration: 42563/59290
Iteration: 42564/59290
Iteration: 42565/59290
Iteration: 42566/59290
Iteration: 42567/59290
Iteration: 42568/59290
Iteration: 42569/59290
Iteration: 42570/59290
Iteration: 42571/59290
Iteration: 42572/59290
Iteration: 42573/59290
Iteration: 42574/59290
Iteration: 42575/59290
Iteration: 42576/59290
Iteration: 42577/59290
Iteration: 42578/59290
Iteration: 42579/59290
Iteration: 42580/59290
Iteration: 42581/59290
Iteration: 42582/59290
Iteration: 42583/59290
Iteration: 42584/59290

 72%|███████▏  | 42570/59290 [30:32<08:07, 34.27it/s]

Iteration: 42585/59290
Iteration: 42586/59290
Iteration: 42587/59290
Iteration: 42588/59290
Iteration: 42589/59290
Iteration: 42590/59290
Iteration: 42591/59290
Iteration: 42592/59290
Iteration: 42593/59290
Iteration: 42594/59290
Iteration: 42595/59290
Iteration: 42596/59290
Iteration: 42597/59290
Iteration: 42598/59290
Iteration: 42599/59290
Iteration: 42600/59290
Iteration: 42601/59290
Iteration: 42602/59290
Iteration: 42603/59290
Iteration: 42604/59290
Iteration: 42605/59290
Iteration: 42606/59290
Iteration: 42607/59290
Iteration: 42608/59290

 72%|███████▏  | 42594/59290 [30:33<12:14, 22.74it/s]

Iteration: 42609/59290
Iteration: 42610/59290
Iteration: 42611/59290
Iteration: 42612/59290
Iteration: 42613/59290
Iteration: 42614/59290
Iteration: 42615/59290
Iteration: 42616/59290
Iteration: 42617/59290
Iteration: 42618/59290
Iteration: 42619/59290
Iteration: 42620/59290
Iteration: 42621/59290
Iteration: 42622/59290
Iteration: 42623/59290
Iteration: 42624/59290
Iteration: 42625/59290
Iteration: 42626/59290
Iteration: 42627/59290
Iteration: 42628/59290
Iteration: 42629/59290
Iteration: 42630/59290
Iteration: 42631/59290
Iteration: 42632/59290

 72%|███████▏  | 42618/59290 [31:06<2:03:02,  2.26it/s]

Iteration: 42633/59290
Iteration: 42634/59290
Iteration: 42635/59290
Iteration: 42636/59290
Iteration: 42637/59290
Iteration: 42638/59290
Iteration: 42639/59290
Iteration: 42640/59290
Iteration: 42641/59290
Iteration: 42642/59290
Iteration: 42643/59290
Iteration: 42644/59290
Iteration: 42645/59290
Iteration: 42646/59290
Iteration: 42647/59290
Iteration: 42648/59290
Iteration: 42649/59290
Iteration: 42650/59290
Iteration: 42651/59290
Iteration: 42652/59290
Iteration: 42653/59290
Iteration: 42654/59290
Iteration: 42655/59290
Iteration: 42656/59290

 72%|███████▏  | 42642/59290 [31:07<1:27:40,  3.16it/s]

Iteration: 42657/59290
Iteration: 42658/59290
Iteration: 42659/59290
Iteration: 42660/59290
Iteration: 42661/59290
Iteration: 42662/59290
Iteration: 42663/59290
Iteration: 42664/59290
Iteration: 42665/59290
Iteration: 42666/59290
Iteration: 42667/59290
Iteration: 42668/59290
Iteration: 42669/59290
Iteration: 42670/59290
Iteration: 42671/59290
Iteration: 42672/59290
Iteration: 42673/59290
Iteration: 42674/59290
Iteration: 42675/59290
Iteration: 42676/59290
Iteration: 42677/59290
Iteration: 42678/59290
Iteration: 42679/59290
Iteration: 42680/59290

 72%|███████▏  | 42666/59290 [31:07<1:02:35,  4.43it/s]

Iteration: 42681/59290
Iteration: 42682/59290
Iteration: 42683/59290
Iteration: 42684/59290
Iteration: 42685/59290
Iteration: 42686/59290
Iteration: 42687/59290
Iteration: 42688/59290
Iteration: 42689/59290
Iteration: 42690/59290
Iteration: 42691/59290
Iteration: 42692/59290
Iteration: 42693/59290
Iteration: 42694/59290
Iteration: 42695/59290
Iteration: 42696/59290
Iteration: 42697/59290
Iteration: 42698/59290
Iteration: 42699/59290
Iteration: 42700/59290
Iteration: 42701/59290
Iteration: 42702/59290
Iteration: 42703/59290
Iteration: 42704/59290

 72%|███████▏  | 42690/59290 [31:08<45:03,  6.14it/s]

Iteration: 42705/59290
Iteration: 42706/59290
Iteration: 42707/59290
Iteration: 42708/59290
Iteration: 42709/59290
Iteration: 42710/59290
Iteration: 42711/59290
Iteration: 42712/59290
Iteration: 42713/59290
Iteration: 42714/59290
Iteration: 42715/59290
Iteration: 42716/59290
Iteration: 42717/59290
Iteration: 42718/59290
Iteration: 42719/59290
Iteration: 42720/59290
Iteration: 42721/59290
Iteration: 42722/59290
Iteration: 42723/59290
Iteration: 42724/59290
Iteration: 42725/59290
Iteration: 42726/59290
Iteration: 42727/59290
Iteration: 42728/59290

 72%|███████▏  | 42714/59290 [31:08<32:47,  8.42it/s]

Iteration: 42729/59290
Iteration: 42730/59290
Iteration: 42731/59290
Iteration: 42732/59290
Iteration: 42733/59290
Iteration: 42734/59290
Iteration: 42735/59290
Iteration: 42736/59290
Iteration: 42737/59290
Iteration: 42738/59290
Iteration: 42739/59290
Iteration: 42740/59290
Iteration: 42741/59290
Iteration: 42742/59290
Iteration: 42743/59290
Iteration: 42744/59290
Iteration: 42745/59290
Iteration: 42746/59290
Iteration: 42747/59290
Iteration: 42748/59290
Iteration: 42749/59290
Iteration: 42750/59290
Iteration: 42751/59290
Iteration: 42752/59290

 72%|███████▏  | 42738/59290 [31:09<27:34, 10.00it/s]

Iteration: 42753/59290
Iteration: 42754/59290
Iteration: 42755/59290
Iteration: 42756/59290
Iteration: 42757/59290
Iteration: 42758/59290
Iteration: 42759/59290
Iteration: 42760/59290
Iteration: 42761/59290
Iteration: 42762/59290
Iteration: 42763/59290
Iteration: 42764/59290
Iteration: 42765/59290
Iteration: 42766/59290
Iteration: 42767/59290
Iteration: 42768/59290
Iteration: 42769/59290
Iteration: 42770/59290
Iteration: 42771/59290
Iteration: 42772/59290
Iteration: 42773/59290
Iteration: 42774/59290
Iteration: 42775/59290
Iteration: 42776/59290

 72%|███████▏  | 42762/59290 [31:11<26:12, 10.51it/s]

Iteration: 42777/59290
Iteration: 42778/59290
Iteration: 42779/59290
Iteration: 42780/59290
Iteration: 42781/59290
Iteration: 42782/59290
Iteration: 42783/59290
Iteration: 42784/59290
Iteration: 42785/59290
Iteration: 42786/59290
Iteration: 42787/59290
Iteration: 42788/59290
Iteration: 42789/59290
Iteration: 42790/59290
Iteration: 42791/59290
Iteration: 42792/59290
Iteration: 42793/59290
Iteration: 42794/59290
Iteration: 42795/59290
Iteration: 42796/59290
Iteration: 42797/59290
Iteration: 42798/59290
Iteration: 42799/59290
Iteration: 42800/59290

 72%|███████▏  | 42786/59290 [31:12<19:57, 13.78it/s]

Iteration: 42801/59290
Iteration: 42802/59290
Iteration: 42803/59290
Iteration: 42804/59290
Iteration: 42805/59290
Iteration: 42806/59290
Iteration: 42807/59290
Iteration: 42808/59290
Iteration: 42809/59290
Iteration: 42810/59290
Iteration: 42811/59290
Iteration: 42812/59290
Iteration: 42813/59290
Iteration: 42814/59290
Iteration: 42815/59290
Iteration: 42816/59290
Iteration: 42817/59290
Iteration: 42818/59290
Iteration: 42819/59290
Iteration: 42820/59290
Iteration: 42821/59290
Iteration: 42822/59290
Iteration: 42823/59290
Iteration: 42824/59290

 72%|███████▏  | 42810/59290 [31:12<15:13, 18.04it/s]

Iteration: 42825/59290
Iteration: 42826/59290
Iteration: 42827/59290
Iteration: 42828/59290
Iteration: 42829/59290
Iteration: 42830/59290
Iteration: 42831/59290
Iteration: 42832/59290
Iteration: 42833/59290
Iteration: 42834/59290
Iteration: 42835/59290
Iteration: 42836/59290
Iteration: 42837/59290
Iteration: 42838/59290
Iteration: 42839/59290
Iteration: 42840/59290
Iteration: 42841/59290
Iteration: 42842/59290
Iteration: 42843/59290
Iteration: 42844/59290
Iteration: 42845/59290
Iteration: 42846/59290
Iteration: 42847/59290
Iteration: 42848/59290

 72%|███████▏  | 42834/59290 [31:13<11:59, 22.87it/s]

Iteration: 42849/59290
Iteration: 42850/59290
Iteration: 42851/59290
Iteration: 42852/59290
Iteration: 42853/59290
Iteration: 42854/59290
Iteration: 42855/59290
Iteration: 42856/59290
Iteration: 42857/59290
Iteration: 42858/59290
Iteration: 42859/59290
Iteration: 42860/59290
Iteration: 42861/59290
Iteration: 42862/59290
Iteration: 42863/59290
Iteration: 42864/59290
Iteration: 42865/59290
Iteration: 42866/59290
Iteration: 42867/59290
Iteration: 42868/59290
Iteration: 42869/59290
Iteration: 42870/59290
Iteration: 42871/59290
Iteration: 42872/59290

 72%|███████▏  | 42858/59290 [31:13<09:42, 28.20it/s]

Iteration: 42873/59290
Iteration: 42874/59290
Iteration: 42875/59290
Iteration: 42876/59290
Iteration: 42877/59290
Iteration: 42878/59290
Iteration: 42879/59290
Iteration: 42880/59290
Iteration: 42881/59290
Iteration: 42882/59290
Iteration: 42883/59290
Iteration: 42884/59290
Iteration: 42885/59290
Iteration: 42886/59290
Iteration: 42887/59290
Iteration: 42888/59290
Iteration: 42889/59290
Iteration: 42890/59290
Iteration: 42891/59290
Iteration: 42892/59290
Iteration: 42893/59290
Iteration: 42894/59290
Iteration: 42895/59290
Iteration: 42896/59290

 72%|███████▏  | 42882/59290 [31:13<08:05, 33.80it/s]

Iteration: 42897/59290
Iteration: 42898/59290
Iteration: 42899/59290
Iteration: 42900/59290
Iteration: 42901/59290
Iteration: 42902/59290
Iteration: 42903/59290
Iteration: 42904/59290
Iteration: 42905/59290
Iteration: 42906/59290
Iteration: 42907/59290
Iteration: 42908/59290
Iteration: 42909/59290
Iteration: 42910/59290
Iteration: 42911/59290
Iteration: 42912/59290
Iteration: 42913/59290
Iteration: 42914/59290
Iteration: 42915/59290
Iteration: 42916/59290
Iteration: 42917/59290
Iteration: 42918/59290
Iteration: 42919/59290
Iteration: 42920/59290

 72%|███████▏  | 42906/59290 [31:14<06:57, 39.24it/s]

Iteration: 42921/59290
Iteration: 42922/59290
Iteration: 42923/59290
Iteration: 42924/59290
Iteration: 42925/59290
Iteration: 42926/59290
Iteration: 42927/59290
Iteration: 42928/59290
Iteration: 42929/59290
Iteration: 42930/59290
Iteration: 42931/59290
Iteration: 42932/59290
Iteration: 42933/59290
Iteration: 42934/59290
Iteration: 42935/59290
Iteration: 42936/59290
Iteration: 42937/59290
Iteration: 42938/59290
Iteration: 42939/59290
Iteration: 42940/59290
Iteration: 42941/59290
Iteration: 42942/59290
Iteration: 42943/59290
Iteration: 42944/59290

 72%|███████▏  | 42930/59290 [31:14<06:10, 44.11it/s]

Iteration: 42945/59290
Iteration: 42946/59290
Iteration: 42947/59290
Iteration: 42948/59290
Iteration: 42949/59290
Iteration: 42950/59290
Iteration: 42951/59290
Iteration: 42952/59290
Iteration: 42953/59290
Iteration: 42954/59290
Iteration: 42955/59290
Iteration: 42956/59290
Iteration: 42957/59290
Iteration: 42958/59290
Iteration: 42959/59290
Iteration: 42960/59290
Iteration: 42961/59290
Iteration: 42962/59290
Iteration: 42963/59290
Iteration: 42964/59290
Iteration: 42965/59290
Iteration: 42966/59290
Iteration: 42967/59290
Iteration: 42968/59290

 72%|███████▏  | 42954/59290 [31:15<05:38, 48.30it/s]

Iteration: 42969/59290
Iteration: 42970/59290
Iteration: 42971/59290
Iteration: 42972/59290
Iteration: 42973/59290
Iteration: 42974/59290
Iteration: 42975/59290
Iteration: 42976/59290
Iteration: 42977/59290
Iteration: 42978/59290
Iteration: 42979/59290
Iteration: 42980/59290
Iteration: 42981/59290
Iteration: 42982/59290
Iteration: 42983/59290
Iteration: 42984/59290
Iteration: 42985/59290
Iteration: 42986/59290
Iteration: 42987/59290
Iteration: 42988/59290
Iteration: 42989/59290
Iteration: 42990/59290
Iteration: 42991/59290
Iteration: 42992/59290

 72%|███████▏  | 42978/59290 [31:16<07:46, 34.95it/s]

Iteration: 42993/59290
Iteration: 42994/59290
Iteration: 42995/59290
Iteration: 42996/59290
Iteration: 42997/59290
Iteration: 42998/59290
Iteration: 42999/59290
Iteration: 43000/59290
Iteration: 43001/59290
Iteration: 43002/59290
Iteration: 43003/59290
Iteration: 43004/59290
Iteration: 43005/59290
Iteration: 43006/59290
Iteration: 43007/59290
Iteration: 43008/59290
Iteration: 43009/59290
Iteration: 43010/59290
Iteration: 43011/59290
Iteration: 43012/59290
Iteration: 43013/59290
Iteration: 43014/59290
Iteration: 43015/59290
Iteration: 43016/59290

 73%|███████▎  | 43002/59290 [31:18<13:17, 20.42it/s]

Iteration: 43017/59290
Iteration: 43018/59290
Iteration: 43019/59290
Iteration: 43020/59290
Iteration: 43021/59290
Iteration: 43022/59290
Iteration: 43023/59290
Iteration: 43024/59290
Iteration: 43025/59290
Iteration: 43026/59290
Iteration: 43027/59290
Iteration: 43028/59290
Iteration: 43029/59290
Iteration: 43030/59290
Iteration: 43031/59290
Iteration: 43032/59290
Iteration: 43033/59290
Iteration: 43034/59290
Iteration: 43035/59290
Iteration: 43036/59290
Iteration: 43037/59290
Iteration: 43038/59290
Iteration: 43039/59290
Iteration: 43040/59290

 73%|███████▎  | 43026/59290 [31:51<1:59:26,  2.27it/s]

Iteration: 43041/59290
Iteration: 43042/59290
Iteration: 43043/59290
Iteration: 43044/59290
Iteration: 43045/59290
Iteration: 43046/59290
Iteration: 43047/59290
Iteration: 43048/59290
Iteration: 43049/59290
Iteration: 43050/59290
Iteration: 43051/59290
Iteration: 43052/59290
Iteration: 43053/59290
Iteration: 43054/59290
Iteration: 43055/59290
Iteration: 43056/59290
Iteration: 43057/59290
Iteration: 43058/59290
Iteration: 43059/59290
Iteration: 43060/59290
Iteration: 43061/59290
Iteration: 43062/59290
Iteration: 43063/59290
Iteration: 43064/59290

 73%|███████▎  | 43050/59290 [31:51<1:24:47,  3.19it/s]

Iteration: 43065/59290
Iteration: 43066/59290
Iteration: 43067/59290
Iteration: 43068/59290
Iteration: 43069/59290
Iteration: 43070/59290
Iteration: 43071/59290
Iteration: 43072/59290
Iteration: 43073/59290
Iteration: 43074/59290
Iteration: 43075/59290
Iteration: 43076/59290
Iteration: 43077/59290
Iteration: 43078/59290
Iteration: 43079/59290
Iteration: 43080/59290
Iteration: 43081/59290
Iteration: 43082/59290
Iteration: 43083/59290
Iteration: 43084/59290
Iteration: 43085/59290
Iteration: 43086/59290
Iteration: 43087/59290
Iteration: 43088/59290

 73%|███████▎  | 43074/59290 [31:51<1:00:32,  4.46it/s]

Iteration: 43089/59290
Iteration: 43090/59290
Iteration: 43091/59290
Iteration: 43092/59290
Iteration: 43093/59290
Iteration: 43094/59290
Iteration: 43095/59290
Iteration: 43096/59290
Iteration: 43097/59290
Iteration: 43098/59290
Iteration: 43099/59290
Iteration: 43100/59290
Iteration: 43101/59290
Iteration: 43102/59290
Iteration: 43103/59290
Iteration: 43104/59290
Iteration: 43105/59290
Iteration: 43106/59290
Iteration: 43107/59290
Iteration: 43108/59290
Iteration: 43109/59290
Iteration: 43110/59290
Iteration: 43111/59290
Iteration: 43112/59290

 73%|███████▎  | 43098/59290 [31:52<43:35,  6.19it/s]

Iteration: 43113/59290
Iteration: 43114/59290
Iteration: 43115/59290
Iteration: 43116/59290
Iteration: 43117/59290
Iteration: 43118/59290
Iteration: 43119/59290
Iteration: 43120/59290
Iteration: 43121/59290
Iteration: 43122/59290
Iteration: 43123/59290
Iteration: 43124/59290
Iteration: 43125/59290
Iteration: 43126/59290
Iteration: 43127/59290
Iteration: 43128/59290
Iteration: 43129/59290
Iteration: 43130/59290
Iteration: 43131/59290
Iteration: 43132/59290
Iteration: 43133/59290
Iteration: 43134/59290
Iteration: 43136/59290

 73%|███████▎  | 43121/59290 [32:24<2:21:51,  1.90it/s]

Iteration: 43137/59290
Iteration: 43138/59290
Iteration: 43139/59290
Iteration: 43140/59290
Iteration: 43141/59290
Iteration: 43142/59290
Iteration: 43143/59290
Iteration: 43144/59290

 73%|███████▎  | 43129/59290 [32:57<4:22:09,  1.03it/s]

Iteration: 43145/59290
Iteration: 43146/59290
Iteration: 43147/59290
Iteration: 43148/59290
Iteration: 43149/59290
Iteration: 43150/59290
Iteration: 43151/59290
Iteration: 43152/59290
Iteration: 43153/59290
Iteration: 43154/59290
Iteration: 43155/59290
Iteration: 43156/59290
Iteration: 43157/59290
Iteration: 43158/59290
Iteration: 43159/59290
Iteration: 43160/59290
Iteration: 43161/59290
Iteration: 43162/59290
Iteration: 43163/59290
Iteration: 43164/59290
Iteration: 43165/59290
Iteration: 43166/59290
Iteration: 43167/59290
Iteration: 43168/59290

 73%|███████▎  | 43153/59290 [32:58<2:55:17,  1.53it/s]

Iteration: 43169/59290
Iteration: 43170/59290
Iteration: 43171/59290
Iteration: 43172/59290
Iteration: 43173/59290
Iteration: 43174/59290
Iteration: 43175/59290
Iteration: 43176/59290
Iteration: 43177/59290
Iteration: 43178/59290
Iteration: 43179/59290
Iteration: 43180/59290
Iteration: 43181/59290
Iteration: 43182/59290
Iteration: 43183/59290
Iteration: 43184/59290
Iteration: 43185/59290
Iteration: 43186/59290
Iteration: 43187/59290
Iteration: 43188/59290
Iteration: 43189/59290
Iteration: 43190/59290
Iteration: 43191/59290
Iteration: 43192/59290

 73%|███████▎  | 43177/59290 [33:00<2:03:38,  2.17it/s]

Iteration: 43193/59290
Iteration: 43194/59290
Iteration: 43195/59290
Iteration: 43196/59290
Iteration: 43197/59290
Iteration: 43198/59290
Iteration: 43199/59290
Iteration: 43200/59290
Iteration: 43201/59290
Iteration: 43202/59290
Iteration: 43203/59290
Iteration: 43204/59290
Iteration: 43205/59290
Iteration: 43206/59290
Iteration: 43207/59290
Iteration: 43208/59290
Iteration: 43209/59290
Iteration: 43210/59290
Iteration: 43211/59290
Iteration: 43212/59290
Iteration: 43213/59290
Iteration: 43214/59290
Iteration: 43215/59290
Iteration: 43216/59290

 73%|███████▎  | 43201/59290 [33:00<1:25:10,  3.15it/s]

Iteration: 43217/59290
Iteration: 43218/59290
Iteration: 43219/59290
Iteration: 43220/59290
Iteration: 43221/59290
Iteration: 43222/59290
Iteration: 43223/59290
Iteration: 43224/59290
Iteration: 43225/59290
Iteration: 43226/59290
Iteration: 43227/59290
Iteration: 43228/59290
Iteration: 43229/59290
Iteration: 43230/59290
Iteration: 43231/59290
Iteration: 43232/59290
Iteration: 43233/59290
Iteration: 43234/59290
Iteration: 43235/59290
Iteration: 43236/59290
Iteration: 43237/59290
Iteration: 43238/59290
Iteration: 43239/59290
Iteration: 43240/59290

 73%|███████▎  | 43225/59290 [33:01<59:32,  4.50it/s]

Iteration: 43241/59290
Iteration: 43242/59290
Iteration: 43243/59290
Iteration: 43244/59290
Iteration: 43245/59290
Iteration: 43246/59290
Iteration: 43247/59290
Iteration: 43248/59290
Iteration: 43249/59290
Iteration: 43250/59290
Iteration: 43251/59290
Iteration: 43252/59290
Iteration: 43253/59290
Iteration: 43254/59290
Iteration: 43255/59290
Iteration: 43256/59290
Iteration: 43257/59290
Iteration: 43258/59290
Iteration: 43259/59290
Iteration: 43260/59290
Iteration: 43261/59290
Iteration: 43262/59290
Iteration: 43263/59290
Iteration: 43264/59290

 73%|███████▎  | 43249/59290 [33:01<42:17,  6.32it/s]

Iteration: 43265/59290
Iteration: 43266/59290
Iteration: 43267/59290
Iteration: 43268/59290
Iteration: 43269/59290
Iteration: 43270/59290
Iteration: 43271/59290
Iteration: 43272/59290
Iteration: 43273/59290
Iteration: 43274/59290
Iteration: 43275/59290
Iteration: 43276/59290
Iteration: 43277/59290
Iteration: 43278/59290
Iteration: 43279/59290
Iteration: 43280/59290
Iteration: 43281/59290
Iteration: 43282/59290
Iteration: 43283/59290
Iteration: 43284/59290
Iteration: 43285/59290
Iteration: 43286/59290
Iteration: 43287/59290
Iteration: 43288/59290

 73%|███████▎  | 43273/59290 [33:02<30:33,  8.74it/s]

Iteration: 43289/59290
Iteration: 43290/59290
Iteration: 43291/59290
Iteration: 43292/59290
Iteration: 43293/59290
Iteration: 43294/59290
Iteration: 43295/59290
Iteration: 43296/59290
Iteration: 43297/59290
Iteration: 43298/59290
Iteration: 43299/59290
Iteration: 43300/59290
Iteration: 43301/59290
Iteration: 43302/59290
Iteration: 43303/59290
Iteration: 43304/59290
Iteration: 43305/59290
Iteration: 43306/59290
Iteration: 43307/59290
Iteration: 43308/59290
Iteration: 43309/59290
Iteration: 43310/59290
Iteration: 43311/59290
Iteration: 43312/59290

 73%|███████▎  | 43297/59290 [33:02<22:31, 11.84it/s]

Iteration: 43313/59290
Iteration: 43314/59290
Iteration: 43315/59290
Iteration: 43316/59290
Iteration: 43317/59290
Iteration: 43318/59290
Iteration: 43319/59290
Iteration: 43320/59290
Iteration: 43321/59290
Iteration: 43322/59290
Iteration: 43323/59290
Iteration: 43324/59290
Iteration: 43325/59290
Iteration: 43326/59290
Iteration: 43327/59290
Iteration: 43328/59290
Iteration: 43329/59290
Iteration: 43330/59290
Iteration: 43331/59290
Iteration: 43332/59290
Iteration: 43333/59290
Iteration: 43334/59290
Iteration: 43335/59290
Iteration: 43336/59290

 73%|███████▎  | 43321/59290 [33:03<19:40, 13.53it/s]

Iteration: 43337/59290
Iteration: 43338/59290
Iteration: 43339/59290
Iteration: 43340/59290
Iteration: 43341/59290
Iteration: 43342/59290
Iteration: 43343/59290
Iteration: 43344/59290
Iteration: 43345/59290
Iteration: 43346/59290
Iteration: 43347/59290
Iteration: 43348/59290
Iteration: 43349/59290
Iteration: 43350/59290
Iteration: 43351/59290
Iteration: 43352/59290
Iteration: 43353/59290
Iteration: 43354/59290
Iteration: 43355/59290
Iteration: 43356/59290
Iteration: 43357/59290
Iteration: 43358/59290
Iteration: 43359/59290
Iteration: 43360/59290

 73%|███████▎  | 43345/59290 [33:05<20:26, 13.00it/s]

Iteration: 43361/59290
Iteration: 43362/59290
Iteration: 43363/59290
Iteration: 43364/59290
Iteration: 43365/59290
Iteration: 43366/59290
Iteration: 43367/59290
Iteration: 43368/59290
Iteration: 43369/59290
Iteration: 43370/59290
Iteration: 43371/59290
Iteration: 43372/59290
Iteration: 43373/59290
Iteration: 43374/59290
Iteration: 43375/59290
Iteration: 43376/59290
Iteration: 43377/59290
Iteration: 43378/59290
Iteration: 43379/59290
Iteration: 43380/59290
Iteration: 43381/59290
Iteration: 43382/59290
Iteration: 43383/59290
Iteration: 43384/59290

 73%|███████▎  | 43369/59290 [33:06<16:03, 16.52it/s]

Iteration: 43385/59290
Iteration: 43386/59290
Iteration: 43387/59290
Iteration: 43388/59290
Iteration: 43389/59290
Iteration: 43390/59290
Iteration: 43391/59290
Iteration: 43392/59290
Iteration: 43393/59290
Iteration: 43394/59290
Iteration: 43395/59290
Iteration: 43396/59290
Iteration: 43397/59290
Iteration: 43398/59290
Iteration: 43399/59290
Iteration: 43400/59290
Iteration: 43401/59290
Iteration: 43402/59290
Iteration: 43403/59290
Iteration: 43404/59290
Iteration: 43405/59290
Iteration: 43406/59290
Iteration: 43407/59290
Iteration: 43408/59290

 73%|███████▎  | 43393/59290 [33:06<12:31, 21.16it/s]

Iteration: 43409/59290
Iteration: 43410/59290
Iteration: 43411/59290
Iteration: 43412/59290
Iteration: 43413/59290
Iteration: 43414/59290
Iteration: 43415/59290
Iteration: 43416/59290
Iteration: 43417/59290
Iteration: 43418/59290
Iteration: 43419/59290
Iteration: 43420/59290
Iteration: 43421/59290
Iteration: 43422/59290
Iteration: 43423/59290
Iteration: 43424/59290
Iteration: 43425/59290
Iteration: 43426/59290
Iteration: 43427/59290
Iteration: 43428/59290
Iteration: 43429/59290
Iteration: 43430/59290
Iteration: 43431/59290
Iteration: 43432/59290

 73%|███████▎  | 43417/59290 [33:06<10:00, 26.44it/s]

Iteration: 43433/59290
Iteration: 43434/59290
Iteration: 43435/59290
Iteration: 43436/59290
Iteration: 43437/59290
Iteration: 43438/59290
Iteration: 43439/59290
Iteration: 43440/59290
Iteration: 43441/59290
Iteration: 43442/59290
Iteration: 43443/59290
Iteration: 43444/59290
Iteration: 43445/59290
Iteration: 43446/59290
Iteration: 43447/59290
Iteration: 43448/59290
Iteration: 43449/59290
Iteration: 43450/59290
Iteration: 43451/59290
Iteration: 43452/59290
Iteration: 43453/59290
Iteration: 43454/59290
Iteration: 43455/59290
Iteration: 43456/59290

 73%|███████▎  | 43441/59290 [33:07<08:13, 32.09it/s]

Iteration: 43457/59290
Iteration: 43458/59290
Iteration: 43459/59290
Iteration: 43460/59290
Iteration: 43461/59290
Iteration: 43462/59290
Iteration: 43463/59290
Iteration: 43464/59290
Iteration: 43465/59290
Iteration: 43466/59290
Iteration: 43467/59290
Iteration: 43468/59290
Iteration: 43469/59290
Iteration: 43470/59290
Iteration: 43471/59290
Iteration: 43472/59290
Iteration: 43473/59290
Iteration: 43474/59290
Iteration: 43475/59290
Iteration: 43476/59290
Iteration: 43477/59290
Iteration: 43478/59290
Iteration: 43479/59290
Iteration: 43480/59290

 73%|███████▎  | 43465/59290 [33:07<07:00, 37.66it/s]

Iteration: 43481/59290
Iteration: 43482/59290
Iteration: 43483/59290
Iteration: 43484/59290
Iteration: 43485/59290
Iteration: 43486/59290
Iteration: 43487/59290
Iteration: 43488/59290
Iteration: 43489/59290
Iteration: 43490/59290
Iteration: 43491/59290
Iteration: 43492/59290
Iteration: 43493/59290
Iteration: 43494/59290
Iteration: 43495/59290
Iteration: 43496/59290
Iteration: 43497/59290
Iteration: 43498/59290
Iteration: 43499/59290
Iteration: 43500/59290
Iteration: 43501/59290
Iteration: 43502/59290
Iteration: 43503/59290
Iteration: 43504/59290

 73%|███████▎  | 43489/59290 [33:09<09:12, 28.61it/s]

Iteration: 43505/59290
Iteration: 43506/59290
Iteration: 43507/59290
Iteration: 43508/59290
Iteration: 43509/59290
Iteration: 43510/59290
Iteration: 43511/59290
Iteration: 43512/59290
Iteration: 43513/59290
Iteration: 43514/59290
Iteration: 43515/59290
Iteration: 43516/59290
Iteration: 43517/59290
Iteration: 43518/59290
Iteration: 43519/59290
Iteration: 43520/59290
Iteration: 43521/59290
Iteration: 43522/59290
Iteration: 43523/59290
Iteration: 43524/59290
Iteration: 43525/59290
Iteration: 43526/59290
Iteration: 43527/59290
Iteration: 43528/59290

 73%|███████▎  | 43513/59290 [33:10<12:31, 20.99it/s]

Iteration: 43529/59290
Iteration: 43530/59290
Iteration: 43531/59290
Iteration: 43532/59290
Iteration: 43533/59290
Iteration: 43534/59290
Iteration: 43535/59290
Iteration: 43536/59290
Iteration: 43537/59290
Iteration: 43538/59290
Iteration: 43539/59290
Iteration: 43540/59290
Iteration: 43541/59290
Iteration: 43542/59290
Iteration: 43543/59290
Iteration: 43544/59290
Iteration: 43545/59290
Iteration: 43546/59290
Iteration: 43547/59290
Iteration: 43548/59290
Iteration: 43549/59290
Iteration: 43550/59290
Iteration: 43551/59290
Iteration: 43552/59290

 73%|███████▎  | 43537/59290 [33:11<10:23, 25.28it/s]

Iteration: 43553/59290
Iteration: 43554/59290
Iteration: 43555/59290
Iteration: 43556/59290
Iteration: 43557/59290
Iteration: 43558/59290
Iteration: 43559/59290
Iteration: 43560/59290
Iteration: 43561/59290
Iteration: 43562/59290
Iteration: 43563/59290
Iteration: 43564/59290
Iteration: 43565/59290
Iteration: 43566/59290
Iteration: 43567/59290
Iteration: 43568/59290
Iteration: 43569/59290
Iteration: 43570/59290
Iteration: 43571/59290
Iteration: 43572/59290
Iteration: 43573/59290
Iteration: 43574/59290
Iteration: 43575/59290
Iteration: 43576/59290

 73%|███████▎  | 43561/59290 [33:11<08:29, 30.85it/s]

Iteration: 43577/59290
Iteration: 43578/59290
Iteration: 43579/59290
Iteration: 43580/59290
Iteration: 43581/59290
Iteration: 43582/59290
Iteration: 43583/59290
Iteration: 43584/59290
Iteration: 43585/59290
Iteration: 43586/59290
Iteration: 43587/59290
Iteration: 43588/59290
Iteration: 43589/59290
Iteration: 43590/59290
Iteration: 43591/59290
Iteration: 43592/59290
Iteration: 43593/59290
Iteration: 43594/59290
Iteration: 43595/59290
Iteration: 43596/59290
Iteration: 43597/59290
Iteration: 43598/59290
Iteration: 43599/59290
Iteration: 43600/59290

 74%|███████▎  | 43585/59290 [33:12<07:10, 36.44it/s]

Iteration: 43601/59290
Iteration: 43602/59290
Iteration: 43603/59290
Iteration: 43604/59290
Iteration: 43605/59290
Iteration: 43606/59290
Iteration: 43607/59290
Iteration: 43608/59290
Iteration: 43609/59290
Iteration: 43610/59290
Iteration: 43611/59290
Iteration: 43612/59290
Iteration: 43613/59290
Iteration: 43614/59290
Iteration: 43615/59290
Iteration: 43616/59290
Iteration: 43617/59290
Iteration: 43618/59290
Iteration: 43619/59290
Iteration: 43620/59290
Iteration: 43621/59290
Iteration: 43622/59290
Iteration: 43623/59290
Iteration: 43624/59290

 74%|███████▎  | 43609/59290 [33:13<09:37, 27.17it/s]

Iteration: 43625/59290
Iteration: 43626/59290
Iteration: 43627/59290
Iteration: 43628/59290
Iteration: 43629/59290
Iteration: 43630/59290
Iteration: 43631/59290
Iteration: 43632/59290
Iteration: 43633/59290
Iteration: 43634/59290
Iteration: 43635/59290
Iteration: 43636/59290
Iteration: 43637/59290
Iteration: 43638/59290
Iteration: 43639/59290
Iteration: 43640/59290
Iteration: 43641/59290
Iteration: 43642/59290
Iteration: 43643/59290
Iteration: 43644/59290
Iteration: 43645/59290
Iteration: 43646/59290
Iteration: 43647/59290
Iteration: 43648/59290

 74%|███████▎  | 43633/59290 [33:15<12:45, 20.45it/s]

Iteration: 43649/59290
Iteration: 43650/59290
Iteration: 43651/59290
Iteration: 43652/59290
Iteration: 43653/59290
Iteration: 43654/59290
Iteration: 43655/59290
Iteration: 43656/59290
Iteration: 43657/59290
Iteration: 43658/59290
Iteration: 43659/59290
Iteration: 43660/59290
Iteration: 43661/59290
Iteration: 43662/59290
Iteration: 43663/59290
Iteration: 43664/59290
Iteration: 43665/59290
Iteration: 43666/59290
Iteration: 43667/59290
Iteration: 43668/59290
Iteration: 43669/59290
Iteration: 43670/59290
Iteration: 43671/59290
Iteration: 43672/59290

 74%|███████▎  | 43657/59290 [33:15<10:24, 25.04it/s]

Iteration: 43673/59290
Iteration: 43674/59290
Iteration: 43675/59290
Iteration: 43676/59290
Iteration: 43677/59290
Iteration: 43678/59290
Iteration: 43679/59290
Iteration: 43680/59290
Iteration: 43681/59290
Iteration: 43682/59290
Iteration: 43683/59290
Iteration: 43684/59290
Iteration: 43685/59290
Iteration: 43686/59290
Iteration: 43687/59290
Iteration: 43688/59290
Iteration: 43689/59290
Iteration: 43690/59290
Iteration: 43691/59290
Iteration: 43692/59290
Iteration: 43693/59290
Iteration: 43694/59290
Iteration: 43695/59290
Iteration: 43696/59290

 74%|███████▎  | 43681/59290 [33:16<08:33, 30.39it/s]

Iteration: 43697/59290
Iteration: 43698/59290
Iteration: 43699/59290
Iteration: 43700/59290
Iteration: 43701/59290
Iteration: 43702/59290
Iteration: 43703/59290
Iteration: 43704/59290
Iteration: 43705/59290
Iteration: 43706/59290
Iteration: 43707/59290
Iteration: 43708/59290
Iteration: 43709/59290
Iteration: 43710/59290
Iteration: 43711/59290
Iteration: 43712/59290
Iteration: 43713/59290
Iteration: 43714/59290
Iteration: 43715/59290
Iteration: 43716/59290
Iteration: 43717/59290
Iteration: 43718/59290
Iteration: 43719/59290
Iteration: 43720/59290

 74%|███████▎  | 43705/59290 [33:16<07:13, 35.94it/s]

Iteration: 43721/59290
Iteration: 43722/59290
Iteration: 43723/59290
Iteration: 43724/59290
Iteration: 43725/59290
Iteration: 43726/59290
Iteration: 43727/59290
Iteration: 43728/59290
Iteration: 43729/59290
Iteration: 43730/59290
Iteration: 43731/59290
Iteration: 43732/59290
Iteration: 43733/59290
Iteration: 43734/59290
Iteration: 43735/59290
Iteration: 43736/59290
Iteration: 43737/59290
Iteration: 43738/59290
Iteration: 43739/59290
Iteration: 43740/59290
Iteration: 43741/59290
Iteration: 43742/59290
Iteration: 43743/59290
Iteration: 43744/59290

 74%|███████▍  | 43729/59290 [33:17<09:16, 27.98it/s]

Iteration: 43745/59290
Iteration: 43746/59290
Iteration: 43747/59290
Iteration: 43748/59290
Iteration: 43749/59290
Iteration: 43750/59290
Iteration: 43751/59290
Iteration: 43752/59290
Iteration: 43753/59290
Iteration: 43754/59290
Iteration: 43755/59290
Iteration: 43756/59290
Iteration: 43757/59290
Iteration: 43758/59290
Iteration: 43759/59290
Iteration: 43760/59290
Iteration: 43761/59290
Iteration: 43762/59290
Iteration: 43763/59290
Iteration: 43764/59290
Iteration: 43765/59290
Iteration: 43766/59290
Iteration: 43767/59290
Iteration: 43768/59290

 74%|███████▍  | 43753/59290 [33:19<12:32, 20.66it/s]

Iteration: 43769/59290
Iteration: 43770/59290
Iteration: 43771/59290
Iteration: 43772/59290
Iteration: 43773/59290
Iteration: 43774/59290
Iteration: 43775/59290
Iteration: 43776/59290
Iteration: 43777/59290
Iteration: 43778/59290
Iteration: 43779/59290
Iteration: 43780/59290
Iteration: 43781/59290
Iteration: 43782/59290
Iteration: 43783/59290
Iteration: 43784/59290
Iteration: 43785/59290
Iteration: 43786/59290
Iteration: 43787/59290
Iteration: 43788/59290
Iteration: 43789/59290
Iteration: 43790/59290
Iteration: 43791/59290
Iteration: 43792/59290

 74%|███████▍  | 43777/59290 [33:20<10:47, 23.95it/s]

Iteration: 43793/59290
Iteration: 43794/59290
Iteration: 43795/59290
Iteration: 43796/59290
Iteration: 43797/59290
Iteration: 43798/59290
Iteration: 43799/59290
Iteration: 43800/59290
Iteration: 43801/59290
Iteration: 43802/59290
Iteration: 43803/59290
Iteration: 43804/59290
Iteration: 43805/59290
Iteration: 43806/59290
Iteration: 43807/59290
Iteration: 43808/59290
Iteration: 43809/59290
Iteration: 43810/59290
Iteration: 43811/59290
Iteration: 43812/59290
Iteration: 43813/59290
Iteration: 43814/59290
Iteration: 43815/59290
Iteration: 43816/59290

 74%|███████▍  | 43801/59290 [33:20<08:46, 29.41it/s]

Iteration: 43817/59290
Iteration: 43818/59290
Iteration: 43819/59290
Iteration: 43820/59290
Iteration: 43821/59290
Iteration: 43822/59290
Iteration: 43823/59290
Iteration: 43824/59290
Iteration: 43825/59290
Iteration: 43826/59290
Iteration: 43827/59290
Iteration: 43828/59290
Iteration: 43829/59290
Iteration: 43830/59290
Iteration: 43831/59290
Iteration: 43832/59290
Iteration: 43833/59290
Iteration: 43834/59290
Iteration: 43835/59290
Iteration: 43836/59290
Iteration: 43837/59290
Iteration: 43838/59290
Iteration: 43839/59290
Iteration: 43840/59290

 74%|███████▍  | 43825/59290 [33:21<07:20, 35.15it/s]

Iteration: 43841/59290
Iteration: 43842/59290
Iteration: 43843/59290
Iteration: 43844/59290
Iteration: 43845/59290
Iteration: 43846/59290
Iteration: 43847/59290
Iteration: 43848/59290
Iteration: 43849/59290
Iteration: 43850/59290
Iteration: 43851/59290
Iteration: 43852/59290
Iteration: 43853/59290
Iteration: 43854/59290
Iteration: 43855/59290
Iteration: 43856/59290
Iteration: 43857/59290
Iteration: 43858/59290
Iteration: 43859/59290
Iteration: 43860/59290
Iteration: 43861/59290
Iteration: 43862/59290
Iteration: 43863/59290
Iteration: 43864/59290

 74%|███████▍  | 43849/59290 [33:21<06:19, 40.66it/s]

Iteration: 43865/59290
Iteration: 43866/59290
Iteration: 43867/59290
Iteration: 43868/59290
Iteration: 43869/59290
Iteration: 43870/59290
Iteration: 43871/59290
Iteration: 43872/59290
Iteration: 43873/59290
Iteration: 43874/59290
Iteration: 43875/59290
Iteration: 43876/59290
Iteration: 43877/59290
Iteration: 43878/59290
Iteration: 43879/59290
Iteration: 43880/59290
Iteration: 43881/59290
Iteration: 43882/59290
Iteration: 43883/59290
Iteration: 43884/59290
Iteration: 43885/59290
Iteration: 43886/59290
Iteration: 43887/59290
Iteration: 43888/59290

 74%|███████▍  | 43873/59290 [33:21<05:39, 45.40it/s]

Iteration: 43889/59290
Iteration: 43890/59290
Iteration: 43891/59290
Iteration: 43892/59290
Iteration: 43893/59290
Iteration: 43894/59290
Iteration: 43895/59290
Iteration: 43896/59290
Iteration: 43897/59290
Iteration: 43898/59290
Iteration: 43899/59290
Iteration: 43900/59290
Iteration: 43901/59290
Iteration: 43902/59290
Iteration: 43903/59290
Iteration: 43904/59290
Iteration: 43905/59290
Iteration: 43906/59290
Iteration: 43907/59290
Iteration: 43908/59290
Iteration: 43909/59290
Iteration: 43910/59290
Iteration: 43911/59290
Iteration: 43912/59290

 74%|███████▍  | 43897/59290 [33:22<05:10, 49.53it/s]

Iteration: 43913/59290
Iteration: 43914/59290
Iteration: 43915/59290
Iteration: 43916/59290
Iteration: 43917/59290
Iteration: 43918/59290
Iteration: 43919/59290
Iteration: 43920/59290
Iteration: 43921/59290
Iteration: 43922/59290
Iteration: 43923/59290
Iteration: 43924/59290
Iteration: 43925/59290
Iteration: 43926/59290
Iteration: 43927/59290
Iteration: 43928/59290
Iteration: 43929/59290
Iteration: 43930/59290
Iteration: 43931/59290
Iteration: 43932/59290
Iteration: 43933/59290
Iteration: 43934/59290
Iteration: 43935/59290
Iteration: 43936/59290

 74%|███████▍  | 43921/59290 [33:22<04:50, 52.89it/s]

Iteration: 43937/59290
Iteration: 43938/59290
Iteration: 43939/59290
Iteration: 43940/59290
Iteration: 43941/59290
Iteration: 43942/59290
Iteration: 43943/59290
Iteration: 43944/59290
Iteration: 43945/59290
Iteration: 43946/59290
Iteration: 43947/59290
Iteration: 43948/59290
Iteration: 43949/59290
Iteration: 43950/59290
Iteration: 43951/59290
Iteration: 43952/59290
Iteration: 43953/59290
Iteration: 43954/59290
Iteration: 43955/59290
Iteration: 43956/59290
Iteration: 43957/59290
Iteration: 43958/59290
Iteration: 43959/59290
Iteration: 43960/59290

 74%|███████▍  | 43945/59290 [33:23<04:38, 55.01it/s]

Iteration: 43961/59290
Iteration: 43962/59290
Iteration: 43963/59290
Iteration: 43964/59290
Iteration: 43965/59290
Iteration: 43966/59290
Iteration: 43967/59290
Iteration: 43968/59290
Iteration: 43969/59290
Iteration: 43970/59290
Iteration: 43971/59290
Iteration: 43972/59290
Iteration: 43973/59290
Iteration: 43974/59290
Iteration: 43975/59290
Iteration: 43976/59290
Iteration: 43977/59290
Iteration: 43978/59290
Iteration: 43979/59290
Iteration: 43980/59290
Iteration: 43981/59290
Iteration: 43982/59290
Iteration: 43983/59290
Iteration: 43984/59290

 74%|███████▍  | 43969/59290 [33:24<06:46, 37.68it/s]

Iteration: 43985/59290
Iteration: 43986/59290
Iteration: 43987/59290
Iteration: 43988/59290
Iteration: 43989/59290
Iteration: 43990/59290
Iteration: 43991/59290
Iteration: 43992/59290
Iteration: 43993/59290
Iteration: 43994/59290
Iteration: 43995/59290
Iteration: 43996/59290
Iteration: 43997/59290
Iteration: 43998/59290
Iteration: 43999/59290
Iteration: 44000/59290
Iteration: 44001/59290
Iteration: 44002/59290
Iteration: 44003/59290
Iteration: 44004/59290
Iteration: 44005/59290
Iteration: 44006/59290
Iteration: 44007/59290
Iteration: 44008/59290

 74%|███████▍  | 43993/59290 [33:26<11:58, 21.29it/s]

Iteration: 44009/59290
Iteration: 44010/59290
Iteration: 44011/59290
Iteration: 44012/59290
Iteration: 44013/59290
Iteration: 44014/59290
Iteration: 44015/59290
Iteration: 44016/59290
Iteration: 44017/59290
Iteration: 44018/59290
Iteration: 44019/59290
Iteration: 44020/59290
Iteration: 44021/59290
Iteration: 44022/59290
Iteration: 44023/59290
Iteration: 44024/59290
Iteration: 44025/59290
Iteration: 44026/59290
Iteration: 44027/59290
Iteration: 44028/59290
Iteration: 44029/59290
Iteration: 44030/59290
Iteration: 44031/59290
Iteration: 44032/59290

 74%|███████▍  | 44017/59290 [33:26<09:35, 26.54it/s]

Iteration: 44033/59290
Iteration: 44034/59290
Iteration: 44035/59290
Iteration: 44036/59290
Iteration: 44037/59290
Iteration: 44038/59290
Iteration: 44039/59290
Iteration: 44040/59290
Iteration: 44041/59290
Iteration: 44042/59290
Iteration: 44043/59290
Iteration: 44044/59290
Iteration: 44045/59290
Iteration: 44046/59290
Iteration: 44047/59290
Iteration: 44048/59290
Iteration: 44049/59290
Iteration: 44050/59290
Iteration: 44051/59290
Iteration: 44052/59290
Iteration: 44053/59290
Iteration: 44054/59290
Iteration: 44055/59290
Iteration: 44056/59290

 74%|███████▍  | 44041/59290 [33:27<07:53, 32.21it/s]

Iteration: 44057/59290
Iteration: 44058/59290
Iteration: 44059/59290
Iteration: 44060/59290
Iteration: 44061/59290
Iteration: 44062/59290
Iteration: 44063/59290
Iteration: 44064/59290
Iteration: 44065/59290
Iteration: 44066/59290
Iteration: 44067/59290
Iteration: 44068/59290
Iteration: 44069/59290
Iteration: 44070/59290
Iteration: 44071/59290
Iteration: 44072/59290
Iteration: 44073/59290
Iteration: 44074/59290
Iteration: 44075/59290
Iteration: 44076/59290
Iteration: 44077/59290
Iteration: 44078/59290
Iteration: 44079/59290
Iteration: 44080/59290

 74%|███████▍  | 44065/59290 [33:27<06:45, 37.54it/s]

Iteration: 44081/59290
Iteration: 44082/59290
Iteration: 44083/59290
Iteration: 44084/59290
Iteration: 44085/59290
Iteration: 44086/59290
Iteration: 44087/59290
Iteration: 44088/59290
Iteration: 44089/59290
Iteration: 44090/59290
Iteration: 44091/59290
Iteration: 44092/59290
Iteration: 44093/59290
Iteration: 44094/59290
Iteration: 44095/59290
Iteration: 44096/59290
Iteration: 44097/59290
Iteration: 44098/59290
Iteration: 44099/59290
Iteration: 44100/59290
Iteration: 44101/59290
Iteration: 44102/59290
Iteration: 44103/59290
Iteration: 44104/59290

 74%|███████▍  | 44089/59290 [33:28<05:56, 42.68it/s]

Iteration: 44105/59290
Iteration: 44106/59290
Iteration: 44107/59290
Iteration: 44108/59290
Iteration: 44109/59290
Iteration: 44110/59290
Iteration: 44111/59290
Iteration: 44112/59290
Iteration: 44113/59290
Iteration: 44114/59290
Iteration: 44115/59290
Iteration: 44116/59290
Iteration: 44117/59290
Iteration: 44118/59290
Iteration: 44119/59290
Iteration: 44120/59290
Iteration: 44121/59290
Iteration: 44122/59290
Iteration: 44123/59290
Iteration: 44124/59290
Iteration: 44125/59290
Iteration: 44126/59290
Iteration: 44127/59290
Iteration: 44128/59290

 74%|███████▍  | 44113/59290 [33:28<05:20, 47.32it/s]

Iteration: 44129/59290
Iteration: 44130/59290
Iteration: 44131/59290
Iteration: 44132/59290
Iteration: 44133/59290
Iteration: 44134/59290
Iteration: 44135/59290
Iteration: 44136/59290
Iteration: 44137/59290
Iteration: 44138/59290
Iteration: 44139/59290
Iteration: 44140/59290
Iteration: 44141/59290
Iteration: 44142/59290
Iteration: 44143/59290
Iteration: 44144/59290
Iteration: 44145/59290
Iteration: 44146/59290
Iteration: 44147/59290
Iteration: 44148/59290
Iteration: 44149/59290
Iteration: 44150/59290
Iteration: 44151/59290
Iteration: 44152/59290

 74%|███████▍  | 44137/59290 [33:28<04:54, 51.37it/s]

Iteration: 44153/59290
Iteration: 44154/59290
Iteration: 44155/59290
Iteration: 44156/59290
Iteration: 44157/59290
Iteration: 44158/59290
Iteration: 44159/59290
Iteration: 44160/59290
Iteration: 44161/59290
Iteration: 44162/59290
Iteration: 44163/59290
Iteration: 44164/59290
Iteration: 44165/59290
Iteration: 44166/59290
Iteration: 44167/59290
Iteration: 44168/59290
Iteration: 44169/59290
Iteration: 44170/59290
Iteration: 44171/59290
Iteration: 44172/59290
Iteration: 44173/59290
Iteration: 44174/59290
Iteration: 44175/59290
Iteration: 44176/59290

 74%|███████▍  | 44161/59290 [33:29<04:36, 54.64it/s]

Iteration: 44177/59290
Iteration: 44178/59290
Iteration: 44179/59290
Iteration: 44180/59290
Iteration: 44181/59290
Iteration: 44182/59290
Iteration: 44183/59290
Iteration: 44184/59290
Iteration: 44185/59290
Iteration: 44186/59290
Iteration: 44187/59290
Iteration: 44188/59290
Iteration: 44189/59290
Iteration: 44190/59290
Iteration: 44191/59290
Iteration: 44192/59290
Iteration: 44193/59290
Iteration: 44194/59290
Iteration: 44195/59290
Iteration: 44196/59290
Iteration: 44197/59290
Iteration: 44198/59290
Iteration: 44199/59290
Iteration: 44200/59290

 75%|███████▍  | 44185/59290 [33:29<04:25, 56.99it/s]

Iteration: 44201/59290
Iteration: 44202/59290
Iteration: 44203/59290
Iteration: 44204/59290
Iteration: 44205/59290
Iteration: 44206/59290
Iteration: 44207/59290
Iteration: 44208/59290
Iteration: 44209/59290
Iteration: 44210/59290
Iteration: 44211/59290
Iteration: 44212/59290
Iteration: 44213/59290
Iteration: 44214/59290
Iteration: 44215/59290
Iteration: 44216/59290
Iteration: 44217/59290
Iteration: 44218/59290
Iteration: 44219/59290
Iteration: 44220/59290
Iteration: 44221/59290
Iteration: 44222/59290
Iteration: 44223/59290
Iteration: 44224/59290

 75%|███████▍  | 44209/59290 [33:30<07:04, 35.54it/s]

Iteration: 44225/59290
Iteration: 44226/59290
Iteration: 44227/59290
Iteration: 44228/59290
Iteration: 44229/59290
Iteration: 44230/59290
Iteration: 44231/59290
Iteration: 44232/59290
Iteration: 44233/59290
Iteration: 44234/59290
Iteration: 44235/59290
Iteration: 44236/59290
Iteration: 44237/59290
Iteration: 44238/59290
Iteration: 44239/59290
Iteration: 44240/59290
Iteration: 44241/59290
Iteration: 44242/59290
Iteration: 44243/59290
Iteration: 44244/59290
Iteration: 44245/59290
Iteration: 44246/59290
Iteration: 44247/59290
Iteration: 44248/59290

 75%|███████▍  | 44233/59290 [33:33<12:02, 20.84it/s]

Iteration: 44249/59290
Iteration: 44250/59290
Iteration: 44251/59290
Iteration: 44252/59290
Iteration: 44253/59290
Iteration: 44254/59290
Iteration: 44255/59290
Iteration: 44256/59290
Iteration: 44257/59290
Iteration: 44258/59290
Iteration: 44259/59290
Iteration: 44260/59290
Iteration: 44261/59290
Iteration: 44262/59290
Iteration: 44263/59290
Iteration: 44264/59290
Iteration: 44265/59290
Iteration: 44266/59290
Iteration: 44267/59290
Iteration: 44268/59290
Iteration: 44269/59290
Iteration: 44270/59290
Iteration: 44271/59290
Iteration: 44272/59290

 75%|███████▍  | 44257/59290 [33:33<09:40, 25.88it/s]

Iteration: 44273/59290
Iteration: 44274/59290
Iteration: 44275/59290
Iteration: 44276/59290
Iteration: 44277/59290
Iteration: 44278/59290
Iteration: 44279/59290
Iteration: 44280/59290
Iteration: 44281/59290
Iteration: 44282/59290
Iteration: 44283/59290
Iteration: 44284/59290
Iteration: 44285/59290
Iteration: 44286/59290
Iteration: 44287/59290
Iteration: 44288/59290
Iteration: 44289/59290
Iteration: 44290/59290
Iteration: 44291/59290
Iteration: 44292/59290
Iteration: 44293/59290
Iteration: 44294/59290
Iteration: 44295/59290
Iteration: 44296/59290

 75%|███████▍  | 44281/59290 [33:33<07:56, 31.50it/s]

Iteration: 44297/59290
Iteration: 44298/59290
Iteration: 44299/59290
Iteration: 44300/59290
Iteration: 44301/59290
Iteration: 44302/59290
Iteration: 44303/59290
Iteration: 44304/59290
Iteration: 44305/59290
Iteration: 44306/59290
Iteration: 44307/59290
Iteration: 44308/59290
Iteration: 44309/59290
Iteration: 44310/59290
Iteration: 44311/59290
Iteration: 44312/59290
Iteration: 44313/59290
Iteration: 44314/59290
Iteration: 44315/59290
Iteration: 44316/59290
Iteration: 44317/59290
Iteration: 44318/59290
Iteration: 44319/59290
Iteration: 44320/59290

 75%|███████▍  | 44305/59290 [33:34<06:45, 36.92it/s]

Iteration: 44321/59290
Iteration: 44322/59290
Iteration: 44323/59290
Iteration: 44324/59290
Iteration: 44325/59290
Iteration: 44326/59290
Iteration: 44327/59290
Iteration: 44328/59290
Iteration: 44329/59290
Iteration: 44330/59290
Iteration: 44331/59290
Iteration: 44332/59290
Iteration: 44333/59290
Iteration: 44334/59290
Iteration: 44335/59290
Iteration: 44336/59290
Iteration: 44337/59290
Iteration: 44338/59290
Iteration: 44339/59290
Iteration: 44340/59290
Iteration: 44341/59290
Iteration: 44342/59290
Iteration: 44343/59290
Iteration: 44344/59290

 75%|███████▍  | 44329/59290 [33:34<05:57, 41.86it/s]

Iteration: 44345/59290
Iteration: 44346/59290
Iteration: 44347/59290
Iteration: 44348/59290
Iteration: 44349/59290
Iteration: 44350/59290
Iteration: 44351/59290
Iteration: 44352/59290
Iteration: 44353/59290
Iteration: 44354/59290
Iteration: 44355/59290
Iteration: 44356/59290
Iteration: 44357/59290
Iteration: 44358/59290
Iteration: 44359/59290
Iteration: 44360/59290
Iteration: 44361/59290
Iteration: 44362/59290
Iteration: 44363/59290
Iteration: 44364/59290
Iteration: 44365/59290
Iteration: 44366/59290
Iteration: 44367/59290
Iteration: 44368/59290

 75%|███████▍  | 44353/59290 [33:35<07:59, 31.13it/s]

Iteration: 44369/59290
Iteration: 44370/59290
Iteration: 44371/59290
Iteration: 44372/59290
Iteration: 44373/59290
Iteration: 44374/59290
Iteration: 44375/59290
Iteration: 44376/59290
Iteration: 44377/59290
Iteration: 44378/59290
Iteration: 44379/59290
Iteration: 44380/59290
Iteration: 44381/59290
Iteration: 44382/59290
Iteration: 44383/59290
Iteration: 44384/59290
Iteration: 44385/59290
Iteration: 44386/59290
Iteration: 44387/59290
Iteration: 44388/59290
Iteration: 44389/59290
Iteration: 44390/59290
Iteration: 44391/59290
Iteration: 44392/59290

 75%|███████▍  | 44377/59290 [33:37<11:27, 21.70it/s]

Iteration: 44393/59290
Iteration: 44394/59290
Iteration: 44395/59290
Iteration: 44396/59290
Iteration: 44397/59290
Iteration: 44398/59290
Iteration: 44399/59290
Iteration: 44400/59290
Iteration: 44401/59290
Iteration: 44402/59290
Iteration: 44403/59290
Iteration: 44404/59290
Iteration: 44405/59290
Iteration: 44406/59290
Iteration: 44407/59290
Iteration: 44408/59290
Iteration: 44409/59290
Iteration: 44410/59290
Iteration: 44411/59290
Iteration: 44412/59290
Iteration: 44413/59290
Iteration: 44414/59290
Iteration: 44415/59290
Iteration: 44416/59290

 75%|███████▍  | 44401/59290 [33:38<09:28, 26.18it/s]

Iteration: 44417/59290
Iteration: 44418/59290
Iteration: 44419/59290
Iteration: 44420/59290
Iteration: 44421/59290
Iteration: 44422/59290
Iteration: 44423/59290
Iteration: 44424/59290
Iteration: 44425/59290
Iteration: 44426/59290
Iteration: 44427/59290
Iteration: 44428/59290
Iteration: 44429/59290
Iteration: 44430/59290
Iteration: 44431/59290
Iteration: 44432/59290
Iteration: 44433/59290
Iteration: 44434/59290
Iteration: 44435/59290
Iteration: 44436/59290
Iteration: 44437/59290
Iteration: 44438/59290
Iteration: 44439/59290
Iteration: 44440/59290

 75%|███████▍  | 44425/59290 [33:38<07:48, 31.73it/s]

Iteration: 44441/59290
Iteration: 44442/59290
Iteration: 44443/59290
Iteration: 44444/59290
Iteration: 44445/59290
Iteration: 44446/59290
Iteration: 44447/59290
Iteration: 44448/59290
Iteration: 44449/59290
Iteration: 44450/59290
Iteration: 44451/59290
Iteration: 44452/59290
Iteration: 44453/59290
Iteration: 44454/59290
Iteration: 44455/59290
Iteration: 44456/59290
Iteration: 44457/59290
Iteration: 44458/59290
Iteration: 44459/59290
Iteration: 44460/59290
Iteration: 44461/59290
Iteration: 44462/59290
Iteration: 44463/59290
Iteration: 44464/59290

 75%|███████▍  | 44449/59290 [33:39<06:39, 37.10it/s]

Iteration: 44465/59290
Iteration: 44466/59290
Iteration: 44467/59290
Iteration: 44468/59290
Iteration: 44469/59290
Iteration: 44470/59290
Iteration: 44471/59290
Iteration: 44472/59290
Iteration: 44473/59290
Iteration: 44474/59290
Iteration: 44475/59290
Iteration: 44476/59290
Iteration: 44477/59290
Iteration: 44478/59290
Iteration: 44479/59290
Iteration: 44480/59290
Iteration: 44481/59290
Iteration: 44482/59290
Iteration: 44483/59290
Iteration: 44484/59290
Iteration: 44485/59290
Iteration: 44486/59290
Iteration: 44487/59290
Iteration: 44488/59290

 75%|███████▌  | 44473/59290 [33:39<05:51, 42.14it/s]

Iteration: 44489/59290
Iteration: 44490/59290
Iteration: 44491/59290
Iteration: 44492/59290
Iteration: 44493/59290
Iteration: 44494/59290
Iteration: 44495/59290
Iteration: 44496/59290
Iteration: 44497/59290
Iteration: 44498/59290
Iteration: 44499/59290
Iteration: 44500/59290
Iteration: 44501/59290
Iteration: 44502/59290
Iteration: 44503/59290
Iteration: 44504/59290
Iteration: 44505/59290
Iteration: 44506/59290
Iteration: 44507/59290
Iteration: 44508/59290
Iteration: 44509/59290
Iteration: 44510/59290
Iteration: 44511/59290
Iteration: 44512/59290

 75%|███████▌  | 44497/59290 [33:39<05:16, 46.74it/s]

Iteration: 44513/59290
Iteration: 44514/59290
Iteration: 44515/59290
Iteration: 44516/59290
Iteration: 44517/59290
Iteration: 44518/59290
Iteration: 44519/59290
Iteration: 44520/59290
Iteration: 44521/59290
Iteration: 44522/59290
Iteration: 44523/59290
Iteration: 44524/59290
Iteration: 44525/59290
Iteration: 44526/59290
Iteration: 44527/59290
Iteration: 44528/59290
Iteration: 44529/59290
Iteration: 44530/59290
Iteration: 44531/59290
Iteration: 44532/59290
Iteration: 44533/59290
Iteration: 44534/59290
Iteration: 44535/59290
Iteration: 44536/59290

 75%|███████▌  | 44521/59290 [33:40<04:53, 50.34it/s]

Iteration: 44537/59290
Iteration: 44538/59290
Iteration: 44539/59290
Iteration: 44540/59290
Iteration: 44541/59290
Iteration: 44542/59290
Iteration: 44543/59290
Iteration: 44544/59290
Iteration: 44545/59290
Iteration: 44546/59290
Iteration: 44547/59290
Iteration: 44548/59290
Iteration: 44549/59290
Iteration: 44550/59290
Iteration: 44551/59290
Iteration: 44552/59290
Iteration: 44553/59290
Iteration: 44554/59290
Iteration: 44555/59290
Iteration: 44556/59290
Iteration: 44557/59290
Iteration: 44558/59290
Iteration: 44559/59290
Iteration: 44560/59290

 75%|███████▌  | 44545/59290 [33:41<06:57, 35.33it/s]

Iteration: 44561/59290
Iteration: 44562/59290
Iteration: 44563/59290
Iteration: 44564/59290
Iteration: 44565/59290
Iteration: 44566/59290
Iteration: 44567/59290
Iteration: 44568/59290
Iteration: 44569/59290
Iteration: 44570/59290
Iteration: 44571/59290
Iteration: 44572/59290
Iteration: 44573/59290
Iteration: 44574/59290
Iteration: 44575/59290
Iteration: 44576/59290
Iteration: 44577/59290
Iteration: 44578/59290
Iteration: 44579/59290
Iteration: 44580/59290
Iteration: 44581/59290
Iteration: 44582/59290
Iteration: 44583/59290
Iteration: 44584/59290

 75%|███████▌  | 44569/59290 [33:43<12:09, 20.19it/s]

Iteration: 44585/59290
Iteration: 44586/59290
Iteration: 44587/59290
Iteration: 44588/59290
Iteration: 44589/59290
Iteration: 44590/59290
Iteration: 44591/59290
Iteration: 44592/59290
Iteration: 44593/59290
Iteration: 44594/59290
Iteration: 44595/59290
Iteration: 44596/59290
Iteration: 44597/59290
Iteration: 44598/59290
Iteration: 44599/59290
Iteration: 44600/59290
Iteration: 44601/59290
Iteration: 44602/59290
Iteration: 44603/59290
Iteration: 44604/59290
Iteration: 44605/59290
Iteration: 44606/59290
Iteration: 44607/59290
Iteration: 44608/59290

 75%|███████▌  | 44593/59290 [33:44<09:38, 25.39it/s]

Iteration: 44609/59290
Iteration: 44610/59290
Iteration: 44611/59290
Iteration: 44612/59290
Iteration: 44613/59290
Iteration: 44614/59290
Iteration: 44615/59290
Iteration: 44616/59290
Iteration: 44617/59290
Iteration: 44618/59290
Iteration: 44619/59290
Iteration: 44620/59290
Iteration: 44621/59290
Iteration: 44622/59290
Iteration: 44623/59290
Iteration: 44624/59290
Iteration: 44625/59290
Iteration: 44626/59290
Iteration: 44627/59290
Iteration: 44628/59290
Iteration: 44629/59290
Iteration: 44630/59290
Iteration: 44631/59290
Iteration: 44632/59290

 75%|███████▌  | 44617/59290 [33:44<07:54, 30.95it/s]

Iteration: 44633/59290
Iteration: 44634/59290
Iteration: 44635/59290
Iteration: 44636/59290
Iteration: 44637/59290
Iteration: 44638/59290
Iteration: 44639/59290
Iteration: 44640/59290
Iteration: 44641/59290
Iteration: 44642/59290
Iteration: 44643/59290
Iteration: 44644/59290
Iteration: 44645/59290
Iteration: 44646/59290
Iteration: 44647/59290
Iteration: 44648/59290
Iteration: 44649/59290
Iteration: 44650/59290
Iteration: 44651/59290
Iteration: 44652/59290
Iteration: 44653/59290
Iteration: 44654/59290
Iteration: 44655/59290
Iteration: 44656/59290

 75%|███████▌  | 44641/59290 [33:44<06:39, 36.65it/s]

Iteration: 44657/59290
Iteration: 44658/59290
Iteration: 44659/59290
Iteration: 44660/59290
Iteration: 44661/59290
Iteration: 44662/59290
Iteration: 44663/59290
Iteration: 44664/59290
Iteration: 44665/59290
Iteration: 44666/59290
Iteration: 44667/59290
Iteration: 44668/59290
Iteration: 44669/59290
Iteration: 44670/59290
Iteration: 44671/59290
Iteration: 44672/59290
Iteration: 44673/59290
Iteration: 44674/59290
Iteration: 44675/59290
Iteration: 44676/59290
Iteration: 44677/59290
Iteration: 44678/59290
Iteration: 44679/59290
Iteration: 44680/59290

 75%|███████▌  | 44665/59290 [33:46<08:49, 27.61it/s]

Iteration: 44681/59290
Iteration: 44682/59290
Iteration: 44683/59290
Iteration: 44684/59290
Iteration: 44685/59290
Iteration: 44686/59290
Iteration: 44687/59290
Iteration: 44688/59290
Iteration: 44689/59290
Iteration: 44690/59290
Iteration: 44691/59290
Iteration: 44692/59290
Iteration: 44693/59290
Iteration: 44694/59290
Iteration: 44695/59290
Iteration: 44696/59290
Iteration: 44697/59290
Iteration: 44698/59290
Iteration: 44699/59290
Iteration: 44700/59290
Iteration: 44701/59290
Iteration: 44702/59290
Iteration: 44703/59290
Iteration: 44704/59290

 75%|███████▌  | 44689/59290 [33:48<11:44, 20.72it/s]

Iteration: 44705/59290
Iteration: 44706/59290
Iteration: 44707/59290
Iteration: 44708/59290
Iteration: 44709/59290
Iteration: 44710/59290
Iteration: 44711/59290
Iteration: 44712/59290
Iteration: 44713/59290
Iteration: 44714/59290
Iteration: 44715/59290
Iteration: 44716/59290
Iteration: 44717/59290
Iteration: 44718/59290
Iteration: 44719/59290
Iteration: 44720/59290
Iteration: 44721/59290
Iteration: 44722/59290
Iteration: 44723/59290
Iteration: 44724/59290
Iteration: 44725/59290
Iteration: 44726/59290
Iteration: 44727/59290
Iteration: 44728/59290

 75%|███████▌  | 44713/59290 [33:48<09:32, 25.46it/s]

Iteration: 44729/59290
Iteration: 44730/59290
Iteration: 44731/59290
Iteration: 44732/59290
Iteration: 44733/59290
Iteration: 44734/59290
Iteration: 44735/59290
Iteration: 44736/59290
Iteration: 44737/59290
Iteration: 44738/59290
Iteration: 44739/59290
Iteration: 44740/59290
Iteration: 44741/59290
Iteration: 44742/59290
Iteration: 44743/59290
Iteration: 44744/59290
Iteration: 44745/59290
Iteration: 44746/59290
Iteration: 44747/59290
Iteration: 44748/59290
Iteration: 44749/59290
Iteration: 44750/59290
Iteration: 44751/59290
Iteration: 44752/59290

 75%|███████▌  | 44737/59290 [33:48<07:49, 30.96it/s]

Iteration: 44753/59290
Iteration: 44754/59290
Iteration: 44755/59290
Iteration: 44756/59290
Iteration: 44757/59290
Iteration: 44758/59290
Iteration: 44759/59290
Iteration: 44760/59290
Iteration: 44761/59290
Iteration: 44762/59290
Iteration: 44763/59290
Iteration: 44764/59290
Iteration: 44765/59290
Iteration: 44766/59290
Iteration: 44767/59290
Iteration: 44768/59290
Iteration: 44769/59290
Iteration: 44770/59290
Iteration: 44771/59290
Iteration: 44772/59290
Iteration: 44773/59290
Iteration: 44774/59290
Iteration: 44775/59290
Iteration: 44776/59290

 75%|███████▌  | 44761/59290 [33:49<06:37, 36.58it/s]

Iteration: 44777/59290
Iteration: 44778/59290
Iteration: 44779/59290
Iteration: 44780/59290
Iteration: 44781/59290
Iteration: 44782/59290
Iteration: 44783/59290
Iteration: 44784/59290
Iteration: 44785/59290
Iteration: 44786/59290
Iteration: 44787/59290
Iteration: 44788/59290
Iteration: 44789/59290
Iteration: 44790/59290
Iteration: 44791/59290
Iteration: 44792/59290
Iteration: 44793/59290
Iteration: 44794/59290
Iteration: 44795/59290
Iteration: 44796/59290
Iteration: 44797/59290
Iteration: 44798/59290
Iteration: 44799/59290
Iteration: 44800/59290

 76%|███████▌  | 44785/59290 [33:49<05:46, 41.85it/s]

Iteration: 44801/59290
Iteration: 44802/59290
Iteration: 44803/59290
Iteration: 44804/59290
Iteration: 44805/59290
Iteration: 44806/59290
Iteration: 44807/59290
Iteration: 44808/59290
Iteration: 44809/59290
Iteration: 44810/59290
Iteration: 44811/59290
Iteration: 44812/59290
Iteration: 44813/59290
Iteration: 44814/59290
Iteration: 44815/59290
Iteration: 44816/59290
Iteration: 44817/59290
Iteration: 44818/59290
Iteration: 44819/59290
Iteration: 44820/59290
Iteration: 44821/59290
Iteration: 44822/59290
Iteration: 44823/59290
Iteration: 44824/59290

 76%|███████▌  | 44809/59290 [33:49<05:11, 46.53it/s]

Iteration: 44825/59290
Iteration: 44826/59290
Iteration: 44827/59290
Iteration: 44828/59290
Iteration: 44829/59290
Iteration: 44830/59290
Iteration: 44831/59290
Iteration: 44832/59290
Iteration: 44833/59290
Iteration: 44834/59290
Iteration: 44835/59290
Iteration: 44836/59290
Iteration: 44837/59290
Iteration: 44838/59290
Iteration: 44839/59290
Iteration: 44840/59290
Iteration: 44841/59290
Iteration: 44842/59290
Iteration: 44843/59290
Iteration: 44844/59290
Iteration: 44845/59290
Iteration: 44846/59290
Iteration: 44847/59290
Iteration: 44848/59290

 76%|███████▌  | 44833/59290 [33:50<04:45, 50.66it/s]

Iteration: 44849/59290
Iteration: 44850/59290
Iteration: 44851/59290
Iteration: 44852/59290
Iteration: 44853/59290
Iteration: 44854/59290
Iteration: 44855/59290
Iteration: 44856/59290
Iteration: 44857/59290
Iteration: 44858/59290
Iteration: 44859/59290
Iteration: 44860/59290
Iteration: 44861/59290
Iteration: 44862/59290
Iteration: 44863/59290
Iteration: 44864/59290
Iteration: 44865/59290
Iteration: 44866/59290
Iteration: 44867/59290
Iteration: 44868/59290
Iteration: 44869/59290
Iteration: 44870/59290
Iteration: 44871/59290
Iteration: 44872/59290

 76%|███████▌  | 44857/59290 [33:50<04:30, 53.37it/s]

Iteration: 44873/59290
Iteration: 44874/59290
Iteration: 44875/59290
Iteration: 44876/59290
Iteration: 44877/59290
Iteration: 44878/59290
Iteration: 44879/59290
Iteration: 44880/59290
Iteration: 44881/59290
Iteration: 44882/59290
Iteration: 44883/59290
Iteration: 44884/59290
Iteration: 44885/59290
Iteration: 44886/59290
Iteration: 44887/59290
Iteration: 44888/59290
Iteration: 44889/59290
Iteration: 44890/59290
Iteration: 44891/59290
Iteration: 44892/59290
Iteration: 44893/59290
Iteration: 44894/59290
Iteration: 44895/59290
Iteration: 44896/59290

 76%|███████▌  | 44881/59290 [33:51<04:16, 56.09it/s]

Iteration: 44897/59290
Iteration: 44898/59290
Iteration: 44899/59290
Iteration: 44900/59290
Iteration: 44901/59290
Iteration: 44902/59290
Iteration: 44903/59290
Iteration: 44904/59290
Iteration: 44905/59290
Iteration: 44906/59290
Iteration: 44907/59290
Iteration: 44908/59290
Iteration: 44909/59290
Iteration: 44910/59290
Iteration: 44911/59290
Iteration: 44912/59290
Iteration: 44913/59290
Iteration: 44914/59290
Iteration: 44915/59290
Iteration: 44916/59290
Iteration: 44917/59290
Iteration: 44918/59290
Iteration: 44919/59290
Iteration: 44920/59290

 76%|███████▌  | 44905/59290 [33:52<06:44, 35.57it/s]

Iteration: 44921/59290
Iteration: 44922/59290
Iteration: 44923/59290
Iteration: 44924/59290
Iteration: 44925/59290
Iteration: 44926/59290
Iteration: 44927/59290
Iteration: 44928/59290
Iteration: 44929/59290
Iteration: 44930/59290
Iteration: 44931/59290
Iteration: 44932/59290
Iteration: 44933/59290
Iteration: 44934/59290
Iteration: 44935/59290
Iteration: 44936/59290
Iteration: 44937/59290
Iteration: 44938/59290
Iteration: 44939/59290
Iteration: 44940/59290
Iteration: 44941/59290
Iteration: 44942/59290
Iteration: 44943/59290
Iteration: 44944/59290

 76%|███████▌  | 44929/59290 [33:54<11:53, 20.14it/s]

Iteration: 44945/59290
Iteration: 44946/59290
Iteration: 44947/59290
Iteration: 44948/59290
Iteration: 44949/59290
Iteration: 44950/59290
Iteration: 44951/59290
Iteration: 44952/59290
Iteration: 44953/59290
Iteration: 44954/59290
Iteration: 44955/59290
Iteration: 44956/59290
Iteration: 44957/59290
Iteration: 44958/59290
Iteration: 44959/59290
Iteration: 44960/59290
Iteration: 44961/59290
Iteration: 44962/59290
Iteration: 44963/59290
Iteration: 44964/59290
Iteration: 44965/59290
Iteration: 44966/59290
Iteration: 44967/59290
Iteration: 44968/59290

 76%|███████▌  | 44953/59290 [33:55<09:26, 25.32it/s]

Iteration: 44969/59290
Iteration: 44970/59290
Iteration: 44971/59290
Iteration: 44972/59290
Iteration: 44973/59290
Iteration: 44974/59290
Iteration: 44975/59290
Iteration: 44976/59290
Iteration: 44977/59290
Iteration: 44978/59290
Iteration: 44979/59290
Iteration: 44980/59290
Iteration: 44981/59290
Iteration: 44982/59290
Iteration: 44983/59290
Iteration: 44984/59290
Iteration: 44985/59290
Iteration: 44986/59290
Iteration: 44987/59290
Iteration: 44988/59290
Iteration: 44989/59290
Iteration: 44990/59290
Iteration: 44991/59290
Iteration: 44992/59290

 76%|███████▌  | 44977/59290 [33:55<07:43, 30.86it/s]

Iteration: 44993/59290
Iteration: 44994/59290
Iteration: 44995/59290
Iteration: 44996/59290
Iteration: 44997/59290
Iteration: 44998/59290
Iteration: 44999/59290
Iteration: 45000/59290
Iteration: 45001/59290
Iteration: 45002/59290
Iteration: 45003/59290
Iteration: 45004/59290
Iteration: 45005/59290
Iteration: 45006/59290
Iteration: 45007/59290
Iteration: 45008/59290
Iteration: 45009/59290
Iteration: 45010/59290
Iteration: 45011/59290
Iteration: 45012/59290
Iteration: 45013/59290
Iteration: 45014/59290
Iteration: 45015/59290
Iteration: 45016/59290

 76%|███████▌  | 45001/59290 [33:55<06:31, 36.54it/s]

Iteration: 45017/59290
Iteration: 45018/59290
Iteration: 45019/59290
Iteration: 45020/59290
Iteration: 45021/59290
Iteration: 45022/59290
Iteration: 45023/59290
Iteration: 45024/59290
Iteration: 45025/59290
Iteration: 45026/59290
Iteration: 45027/59290
Iteration: 45028/59290
Iteration: 45029/59290
Iteration: 45030/59290
Iteration: 45031/59290
Iteration: 45032/59290
Iteration: 45033/59290
Iteration: 45034/59290
Iteration: 45035/59290
Iteration: 45036/59290
Iteration: 45037/59290
Iteration: 45038/59290
Iteration: 45039/59290
Iteration: 45040/59290

 76%|███████▌  | 45025/59290 [33:56<05:40, 41.93it/s]

Iteration: 45041/59290
Iteration: 45042/59290
Iteration: 45043/59290
Iteration: 45044/59290
Iteration: 45045/59290
Iteration: 45046/59290
Iteration: 45047/59290
Iteration: 45048/59290
Iteration: 45049/59290
Iteration: 45050/59290
Iteration: 45051/59290
Iteration: 45052/59290
Iteration: 45053/59290
Iteration: 45054/59290
Iteration: 45055/59290
Iteration: 45056/59290
Iteration: 45057/59290
Iteration: 45058/59290
Iteration: 45059/59290
Iteration: 45060/59290
Iteration: 45061/59290
Iteration: 45062/59290
Iteration: 45063/59290
Iteration: 45064/59290

 76%|███████▌  | 45049/59290 [33:56<05:08, 46.10it/s]

Iteration: 45065/59290
Iteration: 45066/59290
Iteration: 45067/59290
Iteration: 45068/59290
Iteration: 45069/59290
Iteration: 45070/59290
Iteration: 45071/59290
Iteration: 45072/59290
Iteration: 45073/59290
Iteration: 45074/59290
Iteration: 45075/59290
Iteration: 45076/59290
Iteration: 45077/59290
Iteration: 45078/59290
Iteration: 45079/59290
Iteration: 45080/59290
Iteration: 45081/59290
Iteration: 45082/59290
Iteration: 45083/59290
Iteration: 45084/59290
Iteration: 45085/59290
Iteration: 45086/59290
Iteration: 45087/59290
Iteration: 45088/59290

 76%|███████▌  | 45073/59290 [33:57<04:45, 49.74it/s]

Iteration: 45089/59290
Iteration: 45090/59290
Iteration: 45091/59290
Iteration: 45092/59290
Iteration: 45093/59290
Iteration: 45094/59290
Iteration: 45095/59290
Iteration: 45096/59290
Iteration: 45097/59290
Iteration: 45098/59290
Iteration: 45099/59290
Iteration: 45100/59290
Iteration: 45101/59290
Iteration: 45102/59290
Iteration: 45103/59290
Iteration: 45104/59290
Iteration: 45105/59290
Iteration: 45106/59290
Iteration: 45107/59290
Iteration: 45108/59290
Iteration: 45109/59290
Iteration: 45110/59290
Iteration: 45111/59290
Iteration: 45112/59290

 76%|███████▌  | 45097/59290 [33:57<04:26, 53.25it/s]

Iteration: 45113/59290
Iteration: 45114/59290
Iteration: 45115/59290
Iteration: 45116/59290
Iteration: 45117/59290
Iteration: 45118/59290
Iteration: 45119/59290
Iteration: 45120/59290
Iteration: 45121/59290
Iteration: 45122/59290
Iteration: 45123/59290
Iteration: 45124/59290
Iteration: 45125/59290
Iteration: 45126/59290
Iteration: 45127/59290
Iteration: 45128/59290
Iteration: 45129/59290
Iteration: 45130/59290
Iteration: 45131/59290
Iteration: 45132/59290
Iteration: 45133/59290
Iteration: 45134/59290
Iteration: 45135/59290
Iteration: 45136/59290

 76%|███████▌  | 45121/59290 [33:57<04:13, 55.79it/s]

Iteration: 45137/59290
Iteration: 45138/59290
Iteration: 45139/59290
Iteration: 45140/59290
Iteration: 45141/59290
Iteration: 45142/59290
Iteration: 45143/59290
Iteration: 45144/59290
Iteration: 45145/59290
Iteration: 45146/59290
Iteration: 45147/59290
Iteration: 45148/59290
Iteration: 45149/59290
Iteration: 45150/59290
Iteration: 45151/59290
Iteration: 45152/59290
Iteration: 45153/59290
Iteration: 45154/59290
Iteration: 45155/59290
Iteration: 45156/59290
Iteration: 45157/59290
Iteration: 45158/59290
Iteration: 45159/59290
Iteration: 45160/59290

 76%|███████▌  | 45145/59290 [33:59<07:09, 32.96it/s]

Iteration: 45161/59290
Iteration: 45162/59290
Iteration: 45163/59290
Iteration: 45164/59290
Iteration: 45165/59290
Iteration: 45166/59290
Iteration: 45167/59290
Iteration: 45168/59290
Iteration: 45169/59290
Iteration: 45170/59290
Iteration: 45171/59290
Iteration: 45172/59290
Iteration: 45173/59290
Iteration: 45174/59290
Iteration: 45175/59290
Iteration: 45176/59290
Iteration: 45177/59290
Iteration: 45178/59290
Iteration: 45179/59290
Iteration: 45180/59290
Iteration: 45181/59290
Iteration: 45182/59290
Iteration: 45183/59290
Iteration: 45184/59290

 76%|███████▌  | 45169/59290 [34:01<10:36, 22.19it/s]

Iteration: 45185/59290
Iteration: 45186/59290
Iteration: 45187/59290
Iteration: 45188/59290
Iteration: 45189/59290
Iteration: 45190/59290
Iteration: 45191/59290
Iteration: 45192/59290
Iteration: 45193/59290
Iteration: 45194/59290
Iteration: 45195/59290
Iteration: 45196/59290
Iteration: 45197/59290
Iteration: 45198/59290
Iteration: 45199/59290
Iteration: 45200/59290
Iteration: 45201/59290
Iteration: 45202/59290
Iteration: 45203/59290
Iteration: 45204/59290
Iteration: 45205/59290
Iteration: 45206/59290
Iteration: 45207/59290
Iteration: 45208/59290

 76%|███████▌  | 45193/59290 [34:01<09:07, 25.73it/s]

Iteration: 45209/59290
Iteration: 45210/59290
Iteration: 45211/59290
Iteration: 45212/59290
Iteration: 45213/59290
Iteration: 45214/59290
Iteration: 45215/59290
Iteration: 45216/59290
Iteration: 45217/59290
Iteration: 45218/59290
Iteration: 45219/59290
Iteration: 45220/59290
Iteration: 45221/59290
Iteration: 45222/59290
Iteration: 45223/59290
Iteration: 45224/59290
Iteration: 45225/59290
Iteration: 45226/59290
Iteration: 45227/59290
Iteration: 45228/59290
Iteration: 45229/59290
Iteration: 45230/59290
Iteration: 45231/59290
Iteration: 45232/59290

 76%|███████▋  | 45217/59290 [34:02<07:28, 31.38it/s]

Iteration: 45233/59290
Iteration: 45234/59290
Iteration: 45235/59290
Iteration: 45236/59290
Iteration: 45237/59290
Iteration: 45238/59290
Iteration: 45239/59290
Iteration: 45240/59290
Iteration: 45241/59290
Iteration: 45242/59290
Iteration: 45243/59290
Iteration: 45244/59290
Iteration: 45245/59290
Iteration: 45246/59290
Iteration: 45247/59290
Iteration: 45248/59290
Iteration: 45249/59290
Iteration: 45250/59290
Iteration: 45251/59290
Iteration: 45252/59290
Iteration: 45253/59290
Iteration: 45254/59290
Iteration: 45255/59290
Iteration: 45256/59290

 76%|███████▋  | 45241/59290 [34:02<06:21, 36.82it/s]

Iteration: 45257/59290
Iteration: 45258/59290
Iteration: 45259/59290
Iteration: 45260/59290
Iteration: 45261/59290
Iteration: 45262/59290
Iteration: 45263/59290
Iteration: 45264/59290
Iteration: 45265/59290
Iteration: 45266/59290
Iteration: 45267/59290
Iteration: 45268/59290
Iteration: 45269/59290
Iteration: 45270/59290
Iteration: 45271/59290
Iteration: 45272/59290
Iteration: 45273/59290
Iteration: 45274/59290
Iteration: 45275/59290
Iteration: 45276/59290
Iteration: 45277/59290
Iteration: 45278/59290
Iteration: 45279/59290
Iteration: 45280/59290

 76%|███████▋  | 45265/59290 [34:02<05:31, 42.25it/s]

Iteration: 45281/59290
Iteration: 45282/59290
Iteration: 45283/59290
Iteration: 45284/59290
Iteration: 45285/59290
Iteration: 45286/59290
Iteration: 45287/59290
Iteration: 45288/59290
Iteration: 45289/59290
Iteration: 45290/59290
Iteration: 45291/59290
Iteration: 45292/59290
Iteration: 45293/59290
Iteration: 45294/59290
Iteration: 45295/59290
Iteration: 45296/59290
Iteration: 45297/59290
Iteration: 45298/59290
Iteration: 45299/59290
Iteration: 45300/59290
Iteration: 45301/59290
Iteration: 45302/59290
Iteration: 45303/59290
Iteration: 45304/59290

 76%|███████▋  | 45289/59290 [34:04<08:17, 28.13it/s]

Iteration: 45305/59290
Iteration: 45306/59290
Iteration: 45307/59290
Iteration: 45308/59290
Iteration: 45309/59290
Iteration: 45310/59290
Iteration: 45311/59290
Iteration: 45312/59290
Iteration: 45313/59290
Iteration: 45314/59290
Iteration: 45315/59290
Iteration: 45316/59290
Iteration: 45317/59290
Iteration: 45318/59290
Iteration: 45319/59290
Iteration: 45320/59290
Iteration: 45321/59290
Iteration: 45322/59290
Iteration: 45323/59290
Iteration: 45324/59290
Iteration: 45325/59290
Iteration: 45326/59290
Iteration: 45327/59290
Iteration: 45328/59290

 76%|███████▋  | 45313/59290 [34:06<12:44, 18.29it/s]

Iteration: 45329/59290
Iteration: 45330/59290
Iteration: 45331/59290
Iteration: 45332/59290
Iteration: 45333/59290
Iteration: 45334/59290
Iteration: 45335/59290
Iteration: 45336/59290
Iteration: 45337/59290
Iteration: 45338/59290
Iteration: 45339/59290
Iteration: 45340/59290
Iteration: 45341/59290
Iteration: 45342/59290
Iteration: 45343/59290
Iteration: 45344/59290
Iteration: 45345/59290
Iteration: 45346/59290
Iteration: 45347/59290
Iteration: 45348/59290
Iteration: 45349/59290
Iteration: 45350/59290
Iteration: 45351/59290
Iteration: 45352/59290

 76%|███████▋  | 45337/59290 [34:07<10:00, 23.24it/s]

Iteration: 45353/59290
Iteration: 45354/59290
Iteration: 45355/59290
Iteration: 45356/59290
Iteration: 45357/59290
Iteration: 45358/59290
Iteration: 45359/59290
Iteration: 45360/59290
Iteration: 45361/59290
Iteration: 45362/59290
Iteration: 45363/59290
Iteration: 45364/59290
Iteration: 45365/59290
Iteration: 45366/59290
Iteration: 45367/59290
Iteration: 45368/59290
Iteration: 45369/59290
Iteration: 45370/59290
Iteration: 45371/59290
Iteration: 45372/59290
Iteration: 45373/59290
Iteration: 45374/59290
Iteration: 45375/59290
Iteration: 45376/59290

 77%|███████▋  | 45361/59290 [34:07<08:07, 28.56it/s]

Iteration: 45377/59290
Iteration: 45378/59290
Iteration: 45379/59290
Iteration: 45380/59290
Iteration: 45381/59290
Iteration: 45382/59290
Iteration: 45383/59290
Iteration: 45384/59290
Iteration: 45385/59290
Iteration: 45386/59290
Iteration: 45387/59290
Iteration: 45388/59290
Iteration: 45389/59290
Iteration: 45390/59290
Iteration: 45391/59290
Iteration: 45392/59290
Iteration: 45393/59290
Iteration: 45394/59290
Iteration: 45395/59290
Iteration: 45396/59290
Iteration: 45397/59290
Iteration: 45398/59290
Iteration: 45399/59290
Iteration: 45400/59290

 77%|███████▋  | 45385/59290 [34:07<06:45, 34.27it/s]

Iteration: 45401/59290
Iteration: 45402/59290
Iteration: 45403/59290
Iteration: 45404/59290
Iteration: 45405/59290
Iteration: 45406/59290
Iteration: 45407/59290
Iteration: 45408/59290
Iteration: 45409/59290
Iteration: 45410/59290
Iteration: 45411/59290
Iteration: 45412/59290
Iteration: 45413/59290
Iteration: 45414/59290
Iteration: 45415/59290
Iteration: 45416/59290
Iteration: 45417/59290
Iteration: 45418/59290
Iteration: 45419/59290
Iteration: 45420/59290
Iteration: 45421/59290
Iteration: 45422/59290
Iteration: 45423/59290
Iteration: 45424/59290

 77%|███████▋  | 45409/59290 [34:08<05:49, 39.77it/s]

Iteration: 45425/59290
Iteration: 45426/59290
Iteration: 45427/59290
Iteration: 45428/59290
Iteration: 45429/59290
Iteration: 45430/59290
Iteration: 45431/59290
Iteration: 45432/59290
Iteration: 45433/59290
Iteration: 45434/59290
Iteration: 45435/59290
Iteration: 45436/59290
Iteration: 45437/59290
Iteration: 45438/59290
Iteration: 45439/59290
Iteration: 45440/59290
Iteration: 45441/59290
Iteration: 45442/59290
Iteration: 45443/59290
Iteration: 45444/59290
Iteration: 45445/59290
Iteration: 45446/59290
Iteration: 45447/59290
Iteration: 45448/59290

 77%|███████▋  | 45433/59290 [34:09<07:53, 29.24it/s]

Iteration: 45449/59290
Iteration: 45450/59290
Iteration: 45451/59290
Iteration: 45452/59290
Iteration: 45453/59290
Iteration: 45454/59290
Iteration: 45455/59290
Iteration: 45456/59290
Iteration: 45457/59290
Iteration: 45458/59290
Iteration: 45459/59290
Iteration: 45460/59290
Iteration: 45461/59290
Iteration: 45462/59290
Iteration: 45463/59290
Iteration: 45464/59290
Iteration: 45465/59290
Iteration: 45466/59290
Iteration: 45467/59290
Iteration: 45468/59290
Iteration: 45469/59290
Iteration: 45470/59290
Iteration: 45471/59290
Iteration: 45472/59290

 77%|███████▋  | 45457/59290 [34:12<12:26, 18.52it/s]

Iteration: 45473/59290
Iteration: 45474/59290
Iteration: 45475/59290
Iteration: 45476/59290
Iteration: 45477/59290
Iteration: 45478/59290
Iteration: 45479/59290
Iteration: 45480/59290
Iteration: 45481/59290
Iteration: 45482/59290
Iteration: 45483/59290
Iteration: 45484/59290
Iteration: 45485/59290
Iteration: 45486/59290
Iteration: 45487/59290
Iteration: 45488/59290
Iteration: 45489/59290
Iteration: 45490/59290
Iteration: 45491/59290
Iteration: 45492/59290
Iteration: 45493/59290
Iteration: 45494/59290
Iteration: 45495/59290
Iteration: 45496/59290

 77%|███████▋  | 45481/59290 [34:12<09:46, 23.55it/s]

Iteration: 45497/59290
Iteration: 45498/59290
Iteration: 45499/59290
Iteration: 45500/59290
Iteration: 45501/59290
Iteration: 45502/59290
Iteration: 45503/59290
Iteration: 45504/59290
Iteration: 45505/59290
Iteration: 45506/59290
Iteration: 45507/59290
Iteration: 45508/59290
Iteration: 45509/59290
Iteration: 45510/59290
Iteration: 45511/59290
Iteration: 45512/59290
Iteration: 45513/59290
Iteration: 45514/59290
Iteration: 45515/59290
Iteration: 45516/59290
Iteration: 45517/59290
Iteration: 45518/59290
Iteration: 45519/59290
Iteration: 45520/59290

 77%|███████▋  | 45505/59290 [34:12<07:56, 28.92it/s]

Iteration: 45521/59290
Iteration: 45522/59290
Iteration: 45523/59290
Iteration: 45524/59290
Iteration: 45525/59290
Iteration: 45526/59290
Iteration: 45527/59290
Iteration: 45528/59290
Iteration: 45529/59290
Iteration: 45530/59290
Iteration: 45531/59290
Iteration: 45532/59290
Iteration: 45533/59290
Iteration: 45534/59290
Iteration: 45535/59290
Iteration: 45536/59290
Iteration: 45537/59290
Iteration: 45538/59290
Iteration: 45539/59290
Iteration: 45540/59290
Iteration: 45541/59290
Iteration: 45542/59290
Iteration: 45543/59290
Iteration: 45544/59290

 77%|███████▋  | 45529/59290 [34:13<06:40, 34.33it/s]

Iteration: 45545/59290
Iteration: 45546/59290
Iteration: 45547/59290
Iteration: 45548/59290
Iteration: 45549/59290
Iteration: 45550/59290
Iteration: 45551/59290
Iteration: 45552/59290
Iteration: 45553/59290
Iteration: 45554/59290
Iteration: 45555/59290
Iteration: 45556/59290
Iteration: 45557/59290
Iteration: 45558/59290
Iteration: 45559/59290
Iteration: 45560/59290
Iteration: 45561/59290
Iteration: 45562/59290
Iteration: 45563/59290
Iteration: 45564/59290
Iteration: 45565/59290
Iteration: 45566/59290
Iteration: 45567/59290
Iteration: 45568/59290

 77%|███████▋  | 45553/59290 [34:14<08:22, 27.33it/s]

Iteration: 45569/59290
Iteration: 45570/59290
Iteration: 45571/59290
Iteration: 45572/59290
Iteration: 45573/59290
Iteration: 45574/59290
Iteration: 45575/59290
Iteration: 45576/59290
Iteration: 45577/59290
Iteration: 45578/59290
Iteration: 45579/59290
Iteration: 45580/59290
Iteration: 45581/59290
Iteration: 45582/59290
Iteration: 45583/59290
Iteration: 45584/59290
Iteration: 45585/59290
Iteration: 45586/59290
Iteration: 45587/59290
Iteration: 45588/59290
Iteration: 45589/59290
Iteration: 45590/59290
Iteration: 45591/59290
Iteration: 45592/59290

 77%|███████▋  | 45577/59290 [34:16<12:37, 18.10it/s]

Iteration: 45593/59290
Iteration: 45594/59290
Iteration: 45595/59290
Iteration: 45596/59290
Iteration: 45597/59290
Iteration: 45598/59290
Iteration: 45599/59290
Iteration: 45600/59290
Iteration: 45601/59290
Iteration: 45602/59290
Iteration: 45603/59290
Iteration: 45604/59290
Iteration: 45605/59290
Iteration: 45606/59290
Iteration: 45607/59290
Iteration: 45608/59290
Iteration: 45609/59290
Iteration: 45610/59290
Iteration: 45611/59290
Iteration: 45612/59290
Iteration: 45613/59290
Iteration: 45614/59290
Iteration: 45615/59290
Iteration: 45616/59290

 77%|███████▋  | 45601/59290 [34:17<09:54, 23.01it/s]

Iteration: 45617/59290
Iteration: 45618/59290
Iteration: 45619/59290
Iteration: 45620/59290
Iteration: 45621/59290
Iteration: 45622/59290
Iteration: 45623/59290
Iteration: 45624/59290
Iteration: 45625/59290
Iteration: 45626/59290
Iteration: 45627/59290
Iteration: 45628/59290
Iteration: 45629/59290
Iteration: 45630/59290
Iteration: 45631/59290
Iteration: 45632/59290
Iteration: 45633/59290
Iteration: 45634/59290
Iteration: 45635/59290
Iteration: 45636/59290
Iteration: 45637/59290
Iteration: 45638/59290
Iteration: 45639/59290
Iteration: 45640/59290

 77%|███████▋  | 45625/59290 [34:17<08:03, 28.28it/s]

Iteration: 45641/59290
Iteration: 45642/59290
Iteration: 45643/59290
Iteration: 45644/59290
Iteration: 45645/59290
Iteration: 45646/59290
Iteration: 45647/59290
Iteration: 45648/59290
Iteration: 45649/59290
Iteration: 45650/59290
Iteration: 45651/59290
Iteration: 45652/59290
Iteration: 45653/59290
Iteration: 45654/59290
Iteration: 45655/59290
Iteration: 45656/59290
Iteration: 45657/59290
Iteration: 45658/59290
Iteration: 45659/59290
Iteration: 45660/59290
Iteration: 45661/59290
Iteration: 45662/59290
Iteration: 45663/59290
Iteration: 45664/59290

 77%|███████▋  | 45649/59290 [34:18<06:43, 33.81it/s]

Iteration: 45665/59290
Iteration: 45666/59290
Iteration: 45667/59290
Iteration: 45668/59290
Iteration: 45669/59290
Iteration: 45670/59290
Iteration: 45671/59290
Iteration: 45672/59290
Iteration: 45673/59290
Iteration: 45674/59290
Iteration: 45675/59290
Iteration: 45676/59290
Iteration: 45677/59290
Iteration: 45678/59290
Iteration: 45679/59290
Iteration: 45680/59290
Iteration: 45681/59290
Iteration: 45682/59290
Iteration: 45683/59290
Iteration: 45684/59290
Iteration: 45685/59290
Iteration: 45686/59290
Iteration: 45687/59290
Iteration: 45688/59290

 77%|███████▋  | 45673/59290 [34:18<05:45, 39.42it/s]

Iteration: 45689/59290
Iteration: 45690/59290
Iteration: 45691/59290
Iteration: 45692/59290
Iteration: 45693/59290
Iteration: 45694/59290
Iteration: 45695/59290
Iteration: 45696/59290
Iteration: 45697/59290
Iteration: 45698/59290
Iteration: 45699/59290
Iteration: 45700/59290
Iteration: 45701/59290
Iteration: 45702/59290
Iteration: 45703/59290
Iteration: 45704/59290
Iteration: 45705/59290
Iteration: 45706/59290
Iteration: 45707/59290
Iteration: 45708/59290
Iteration: 45709/59290
Iteration: 45710/59290
Iteration: 45711/59290
Iteration: 45712/59290

 77%|███████▋  | 45697/59290 [34:18<05:08, 44.00it/s]

Iteration: 45713/59290
Iteration: 45714/59290
Iteration: 45715/59290
Iteration: 45716/59290
Iteration: 45717/59290
Iteration: 45718/59290
Iteration: 45719/59290
Iteration: 45720/59290
Iteration: 45721/59290
Iteration: 45722/59290
Iteration: 45723/59290
Iteration: 45724/59290
Iteration: 45725/59290
Iteration: 45726/59290
Iteration: 45727/59290
Iteration: 45728/59290
Iteration: 45729/59290
Iteration: 45730/59290
Iteration: 45731/59290
Iteration: 45732/59290
Iteration: 45733/59290
Iteration: 45734/59290
Iteration: 45735/59290
Iteration: 45736/59290

 77%|███████▋  | 45721/59290 [34:19<04:42, 48.07it/s]

Iteration: 45737/59290
Iteration: 45738/59290
Iteration: 45739/59290
Iteration: 45740/59290
Iteration: 45741/59290
Iteration: 45742/59290
Iteration: 45743/59290
Iteration: 45744/59290
Iteration: 45745/59290
Iteration: 45746/59290
Iteration: 45747/59290
Iteration: 45748/59290
Iteration: 45749/59290
Iteration: 45750/59290
Iteration: 45751/59290
Iteration: 45752/59290
Iteration: 45753/59290
Iteration: 45754/59290
Iteration: 45755/59290
Iteration: 45756/59290
Iteration: 45757/59290
Iteration: 45758/59290
Iteration: 45759/59290
Iteration: 45760/59290

 77%|███████▋  | 45745/59290 [34:20<07:25, 30.43it/s]

Iteration: 45761/59290
Iteration: 45762/59290
Iteration: 45763/59290
Iteration: 45764/59290
Iteration: 45765/59290
Iteration: 45766/59290
Iteration: 45767/59290
Iteration: 45768/59290
Iteration: 45769/59290
Iteration: 45770/59290
Iteration: 45771/59290
Iteration: 45772/59290
Iteration: 45773/59290
Iteration: 45774/59290
Iteration: 45775/59290
Iteration: 45776/59290
Iteration: 45777/59290
Iteration: 45778/59290
Iteration: 45779/59290
Iteration: 45780/59290
Iteration: 45781/59290
Iteration: 45782/59290
Iteration: 45783/59290
Iteration: 45784/59290

 77%|███████▋  | 45769/59290 [34:22<10:44, 20.99it/s]

Iteration: 45785/59290
Iteration: 45786/59290
Iteration: 45787/59290
Iteration: 45788/59290
Iteration: 45789/59290
Iteration: 45790/59290
Iteration: 45791/59290
Iteration: 45792/59290
Iteration: 45793/59290
Iteration: 45794/59290
Iteration: 45795/59290
Iteration: 45796/59290
Iteration: 45797/59290
Iteration: 45798/59290
Iteration: 45799/59290
Iteration: 45800/59290
Iteration: 45801/59290
Iteration: 45802/59290
Iteration: 45803/59290
Iteration: 45804/59290
Iteration: 45805/59290
Iteration: 45806/59290
Iteration: 45807/59290
Iteration: 45808/59290

 77%|███████▋  | 45793/59290 [34:23<09:06, 24.71it/s]

Iteration: 45809/59290
Iteration: 45810/59290
Iteration: 45811/59290
Iteration: 45812/59290
Iteration: 45813/59290
Iteration: 45814/59290
Iteration: 45815/59290
Iteration: 45816/59290
Iteration: 45817/59290
Iteration: 45818/59290
Iteration: 45819/59290
Iteration: 45820/59290
Iteration: 45821/59290
Iteration: 45822/59290
Iteration: 45823/59290
Iteration: 45824/59290
Iteration: 45825/59290
Iteration: 45826/59290
Iteration: 45827/59290
Iteration: 45828/59290
Iteration: 45829/59290
Iteration: 45830/59290
Iteration: 45832/59290

 77%|███████▋  | 45816/59290 [34:23<07:37, 29.46it/s]

Iteration: 45833/59290
Iteration: 45834/59290
Iteration: 45835/59290
Iteration: 45836/59290
Iteration: 45837/59290
Iteration: 45838/59290
Iteration: 45839/59290
Iteration: 45840/59290

 77%|███████▋  | 45824/59290 [34:24<08:00, 28.00it/s]

Iteration: 45841/59290
Iteration: 45842/59290
Iteration: 45843/59290
Iteration: 45844/59290
Iteration: 45845/59290
Iteration: 45846/59290
Iteration: 45847/59290
Iteration: 45848/59290
Iteration: 45849/59290
Iteration: 45850/59290
Iteration: 45851/59290
Iteration: 45852/59290
Iteration: 45853/59290
Iteration: 45854/59290
Iteration: 45855/59290
Iteration: 45856/59290
Iteration: 45857/59290
Iteration: 45858/59290
Iteration: 45859/59290
Iteration: 45860/59290
Iteration: 45861/59290
Iteration: 45862/59290
Iteration: 45863/59290
Iteration: 45864/59290

 77%|███████▋  | 45848/59290 [34:57<1:53:36,  1.97it/s]

Iteration: 45865/59290
Iteration: 45866/59290
Iteration: 45867/59290
Iteration: 45868/59290
Iteration: 45869/59290
Iteration: 45870/59290
Iteration: 45871/59290
Iteration: 45872/59290
Iteration: 45873/59290
Iteration: 45874/59290
Iteration: 45875/59290
Iteration: 45876/59290
Iteration: 45877/59290
Iteration: 45878/59290
Iteration: 45879/59290
Iteration: 45880/59290
Iteration: 45881/59290
Iteration: 45882/59290
Iteration: 45883/59290
Iteration: 45884/59290
Iteration: 45885/59290
Iteration: 45886/59290
Iteration: 45887/59290
Iteration: 45888/59290

 77%|███████▋  | 45872/59290 [34:59<1:21:56,  2.73it/s]

Iteration: 45889/59290
Iteration: 45890/59290
Iteration: 45891/59290
Iteration: 45892/59290
Iteration: 45893/59290
Iteration: 45894/59290
Iteration: 45895/59290
Iteration: 45896/59290
Iteration: 45897/59290
Iteration: 45898/59290
Iteration: 45899/59290
Iteration: 45900/59290
Iteration: 45901/59290
Iteration: 45902/59290
Iteration: 45903/59290
Iteration: 45904/59290
Iteration: 45905/59290
Iteration: 45906/59290
Iteration: 45907/59290
Iteration: 45908/59290
Iteration: 45909/59290
Iteration: 45910/59290
Iteration: 45911/59290
Iteration: 45912/59290

 77%|███████▋  | 45896/59290 [34:59<57:14,  3.90it/s]

Iteration: 45913/59290
Iteration: 45914/59290
Iteration: 45915/59290
Iteration: 45916/59290
Iteration: 45917/59290
Iteration: 45918/59290
Iteration: 45919/59290
Iteration: 45920/59290
Iteration: 45921/59290
Iteration: 45922/59290
Iteration: 45923/59290
Iteration: 45924/59290
Iteration: 45925/59290
Iteration: 45926/59290
Iteration: 45927/59290
Iteration: 45928/59290
Iteration: 45929/59290
Iteration: 45930/59290
Iteration: 45931/59290
Iteration: 45932/59290
Iteration: 45933/59290
Iteration: 45934/59290
Iteration: 45935/59290
Iteration: 45936/59290

 77%|███████▋  | 45920/59290 [35:00<40:12,  5.54it/s]

Iteration: 45937/59290
Iteration: 45938/59290
Iteration: 45939/59290
Iteration: 45940/59290
Iteration: 45941/59290
Iteration: 45942/59290
Iteration: 45943/59290
Iteration: 45944/59290
Iteration: 45945/59290
Iteration: 45946/59290
Iteration: 45947/59290
Iteration: 45948/59290
Iteration: 45949/59290
Iteration: 45950/59290
Iteration: 45951/59290
Iteration: 45952/59290
Iteration: 45953/59290
Iteration: 45954/59290
Iteration: 45955/59290
Iteration: 45956/59290
Iteration: 45957/59290
Iteration: 45958/59290
Iteration: 45959/59290
Iteration: 45960/59290

 77%|███████▋  | 45944/59290 [35:34<2:05:24,  1.77it/s]

Iteration: 45961/59290
Iteration: 45962/59290
Iteration: 45963/59290
Iteration: 45964/59290
Iteration: 45965/59290
Iteration: 45966/59290
Iteration: 45967/59290
Iteration: 45968/59290
Iteration: 45969/59290
Iteration: 45970/59290
Iteration: 45971/59290
Iteration: 45972/59290
Iteration: 45973/59290
Iteration: 45974/59290
Iteration: 45975/59290
Iteration: 45976/59290
Iteration: 45977/59290
Iteration: 45978/59290
Iteration: 45979/59290
Iteration: 45980/59290
Iteration: 45981/59290
Iteration: 45982/59290
Iteration: 45983/59290
Iteration: 45984/59290

 78%|███████▊  | 45968/59290 [35:34<1:27:46,  2.53it/s]

Iteration: 45985/59290
Iteration: 45986/59290
Iteration: 45987/59290
Iteration: 45988/59290
Iteration: 45989/59290
Iteration: 45990/59290
Iteration: 45991/59290
Iteration: 45992/59290
Iteration: 45993/59290
Iteration: 45994/59290
Iteration: 45995/59290
Iteration: 45996/59290
Iteration: 45997/59290
Iteration: 45998/59290
Iteration: 45999/59290
Iteration: 46000/59290
Iteration: 46001/59290
Iteration: 46002/59290
Iteration: 46003/59290
Iteration: 46004/59290
Iteration: 46005/59290
Iteration: 46006/59290
Iteration: 46007/59290
Iteration: 46008/59290

 78%|███████▊  | 45992/59290 [35:34<1:01:58,  3.58it/s]

Iteration: 46009/59290
Iteration: 46010/59290
Iteration: 46011/59290
Iteration: 46012/59290
Iteration: 46013/59290
Iteration: 46014/59290
Iteration: 46015/59290
Iteration: 46016/59290
Iteration: 46017/59290
Iteration: 46018/59290
Iteration: 46019/59290
Iteration: 46020/59290
Iteration: 46021/59290
Iteration: 46022/59290
Iteration: 46023/59290
Iteration: 46024/59290
Iteration: 46025/59290
Iteration: 46026/59290
Iteration: 46027/59290
Iteration: 46028/59290
Iteration: 46029/59290
Iteration: 46030/59290
Iteration: 46031/59290
Iteration: 46032/59290

 78%|███████▊  | 46016/59290 [35:35<44:08,  5.01it/s]

Iteration: 46033/59290
Iteration: 46034/59290
Iteration: 46035/59290
Iteration: 46036/59290
Iteration: 46037/59290
Iteration: 46038/59290
Iteration: 46039/59290
Iteration: 46040/59290
Iteration: 46041/59290
Iteration: 46042/59290
Iteration: 46043/59290
Iteration: 46044/59290
Iteration: 46045/59290
Iteration: 46046/59290
Iteration: 46047/59290
Iteration: 46048/59290
Iteration: 46049/59290
Iteration: 46050/59290
Iteration: 46051/59290
Iteration: 46052/59290
Iteration: 46053/59290
Iteration: 46054/59290
Iteration: 46055/59290
Iteration: 46056/59290

 78%|███████▊  | 46040/59290 [35:35<31:48,  6.94it/s]

Iteration: 46057/59290
Iteration: 46058/59290
Iteration: 46059/59290
Iteration: 46060/59290
Iteration: 46061/59290
Iteration: 46062/59290
Iteration: 46063/59290
Iteration: 46064/59290
Iteration: 46065/59290
Iteration: 46066/59290
Iteration: 46067/59290
Iteration: 46068/59290
Iteration: 46069/59290
Iteration: 46070/59290
Iteration: 46071/59290
Iteration: 46072/59290
Iteration: 46073/59290
Iteration: 46074/59290
Iteration: 46075/59290
Iteration: 46076/59290
Iteration: 46077/59290
Iteration: 46078/59290
Iteration: 46079/59290
Iteration: 46080/59290

 78%|███████▊  | 46064/59290 [35:37<26:11,  8.42it/s]

Iteration: 46081/59290
Iteration: 46082/59290
Iteration: 46083/59290
Iteration: 46084/59290
Iteration: 46085/59290
Iteration: 46086/59290
Iteration: 46087/59290
Iteration: 46088/59290
Iteration: 46089/59290
Iteration: 46090/59290
Iteration: 46091/59290
Iteration: 46092/59290
Iteration: 46093/59290
Iteration: 46094/59290
Iteration: 46095/59290
Iteration: 46096/59290
Iteration: 46097/59290
Iteration: 46098/59290
Iteration: 46099/59290
Iteration: 46100/59290
Iteration: 46101/59290
Iteration: 46102/59290
Iteration: 46103/59290
Iteration: 46104/59290

 78%|███████▊  | 46088/59290 [35:39<23:58,  9.18it/s]

Iteration: 46105/59290
Iteration: 46106/59290
Iteration: 46107/59290
Iteration: 46108/59290
Iteration: 46109/59290
Iteration: 46110/59290
Iteration: 46111/59290
Iteration: 46112/59290
Iteration: 46113/59290
Iteration: 46114/59290
Iteration: 46115/59290
Iteration: 46116/59290
Iteration: 46117/59290
Iteration: 46118/59290
Iteration: 46119/59290
Iteration: 46120/59290
Iteration: 46121/59290
Iteration: 46122/59290
Iteration: 46123/59290
Iteration: 46124/59290
Iteration: 46125/59290
Iteration: 46126/59290
Iteration: 46127/59290
Iteration: 46128/59290

 78%|███████▊  | 46112/59290 [35:39<18:16, 12.02it/s]

Iteration: 46129/59290
Iteration: 46130/59290
Iteration: 46131/59290
Iteration: 46132/59290
Iteration: 46133/59290
Iteration: 46134/59290
Iteration: 46135/59290
Iteration: 46136/59290
Iteration: 46137/59290
Iteration: 46138/59290
Iteration: 46139/59290
Iteration: 46140/59290
Iteration: 46141/59290
Iteration: 46142/59290
Iteration: 46143/59290
Iteration: 46144/59290
Iteration: 46145/59290
Iteration: 46146/59290
Iteration: 46147/59290
Iteration: 46148/59290
Iteration: 46149/59290
Iteration: 46150/59290
Iteration: 46151/59290
Iteration: 46152/59290

 78%|███████▊  | 46136/59290 [35:40<13:48, 15.88it/s]

Iteration: 46153/59290
Iteration: 46154/59290
Iteration: 46155/59290
Iteration: 46156/59290
Iteration: 46157/59290
Iteration: 46158/59290
Iteration: 46159/59290
Iteration: 46160/59290
Iteration: 46161/59290
Iteration: 46162/59290
Iteration: 46163/59290
Iteration: 46164/59290
Iteration: 46165/59290
Iteration: 46166/59290
Iteration: 46167/59290
Iteration: 46168/59290
Iteration: 46169/59290
Iteration: 46170/59290
Iteration: 46171/59290
Iteration: 46172/59290
Iteration: 46173/59290
Iteration: 46174/59290
Iteration: 46175/59290
Iteration: 46176/59290

 78%|███████▊  | 46160/59290 [35:40<10:40, 20.49it/s]

Iteration: 46177/59290
Iteration: 46178/59290
Iteration: 46179/59290
Iteration: 46180/59290
Iteration: 46181/59290
Iteration: 46182/59290
Iteration: 46183/59290
Iteration: 46184/59290
Iteration: 46185/59290
Iteration: 46186/59290
Iteration: 46187/59290
Iteration: 46188/59290
Iteration: 46189/59290
Iteration: 46190/59290
Iteration: 46191/59290
Iteration: 46192/59290
Iteration: 46193/59290
Iteration: 46194/59290
Iteration: 46195/59290
Iteration: 46196/59290
Iteration: 46197/59290
Iteration: 46198/59290
Iteration: 46199/59290
Iteration: 46200/59290

 78%|███████▊  | 46184/59290 [35:40<08:31, 25.61it/s]

Iteration: 46201/59290
Iteration: 46202/59290
Iteration: 46203/59290
Iteration: 46204/59290
Iteration: 46205/59290
Iteration: 46206/59290
Iteration: 46207/59290
Iteration: 46208/59290
Iteration: 46209/59290
Iteration: 46210/59290
Iteration: 46211/59290
Iteration: 46212/59290
Iteration: 46213/59290
Iteration: 46214/59290
Iteration: 46215/59290
Iteration: 46216/59290
Iteration: 46217/59290
Iteration: 46218/59290
Iteration: 46219/59290
Iteration: 46220/59290
Iteration: 46221/59290
Iteration: 46222/59290
Iteration: 46223/59290
Iteration: 46224/59290

 78%|███████▊  | 46208/59290 [35:42<09:28, 22.99it/s]

Iteration: 46225/59290
Iteration: 46226/59290
Iteration: 46227/59290
Iteration: 46228/59290
Iteration: 46229/59290
Iteration: 46230/59290
Iteration: 46231/59290
Iteration: 46232/59290
Iteration: 46233/59290
Iteration: 46234/59290
Iteration: 46235/59290
Iteration: 46236/59290
Iteration: 46237/59290
Iteration: 46238/59290
Iteration: 46239/59290
Iteration: 46240/59290
Iteration: 46241/59290
Iteration: 46242/59290
Iteration: 46243/59290
Iteration: 46244/59290
Iteration: 46245/59290
Iteration: 46246/59290
Iteration: 46247/59290
Iteration: 46248/59290

 78%|███████▊  | 46232/59290 [35:44<12:13, 17.80it/s]

Iteration: 46249/59290
Iteration: 46250/59290
Iteration: 46251/59290
Iteration: 46252/59290
Iteration: 46253/59290
Iteration: 46254/59290
Iteration: 46255/59290
Iteration: 46256/59290
Iteration: 46257/59290
Iteration: 46258/59290
Iteration: 46259/59290
Iteration: 46260/59290
Iteration: 46261/59290
Iteration: 46262/59290
Iteration: 46263/59290
Iteration: 46264/59290
Iteration: 46265/59290
Iteration: 46266/59290
Iteration: 46267/59290
Iteration: 46268/59290
Iteration: 46269/59290
Iteration: 46270/59290
Iteration: 46271/59290
Iteration: 46272/59290

 78%|███████▊  | 46256/59290 [35:44<10:00, 21.69it/s]

Iteration: 46273/59290
Iteration: 46274/59290
Iteration: 46275/59290
Iteration: 46276/59290
Iteration: 46277/59290
Iteration: 46278/59290
Iteration: 46279/59290
Iteration: 46280/59290
Iteration: 46281/59290
Iteration: 46282/59290
Iteration: 46283/59290
Iteration: 46284/59290
Iteration: 46285/59290
Iteration: 46286/59290
Iteration: 46287/59290
Iteration: 46288/59290
Iteration: 46289/59290
Iteration: 46290/59290
Iteration: 46291/59290
Iteration: 46292/59290
Iteration: 46293/59290
Iteration: 46294/59290
Iteration: 46295/59290
Iteration: 46296/59290

 78%|███████▊  | 46280/59290 [35:45<08:02, 26.99it/s]

Iteration: 46297/59290
Iteration: 46298/59290
Iteration: 46299/59290
Iteration: 46300/59290
Iteration: 46301/59290
Iteration: 46302/59290
Iteration: 46303/59290
Iteration: 46304/59290
Iteration: 46305/59290
Iteration: 46306/59290
Iteration: 46307/59290
Iteration: 46308/59290
Iteration: 46309/59290
Iteration: 46310/59290
Iteration: 46311/59290
Iteration: 46312/59290
Iteration: 46313/59290
Iteration: 46314/59290
Iteration: 46315/59290
Iteration: 46316/59290
Iteration: 46317/59290
Iteration: 46318/59290
Iteration: 46319/59290
Iteration: 46320/59290

 78%|███████▊  | 46304/59290 [35:45<06:39, 32.50it/s]

Iteration: 46321/59290
Iteration: 46322/59290
Iteration: 46323/59290
Iteration: 46324/59290
Iteration: 46325/59290
Iteration: 46326/59290
Iteration: 46327/59290
Iteration: 46328/59290
Iteration: 46329/59290
Iteration: 46330/59290
Iteration: 46331/59290
Iteration: 46332/59290
Iteration: 46333/59290
Iteration: 46334/59290
Iteration: 46335/59290
Iteration: 46336/59290
Iteration: 46337/59290
Iteration: 46338/59290
Iteration: 46339/59290
Iteration: 46340/59290
Iteration: 46341/59290
Iteration: 46342/59290
Iteration: 46343/59290
Iteration: 46344/59290

 78%|███████▊  | 46328/59290 [35:45<05:39, 38.18it/s]

Iteration: 46345/59290
Iteration: 46346/59290
Iteration: 46347/59290
Iteration: 46348/59290
Iteration: 46349/59290
Iteration: 46350/59290
Iteration: 46351/59290
Iteration: 46352/59290
Iteration: 46353/59290
Iteration: 46354/59290
Iteration: 46355/59290
Iteration: 46356/59290
Iteration: 46357/59290
Iteration: 46358/59290
Iteration: 46359/59290
Iteration: 46360/59290
Iteration: 46361/59290
Iteration: 46362/59290
Iteration: 46363/59290
Iteration: 46364/59290
Iteration: 46365/59290
Iteration: 46366/59290
Iteration: 46367/59290
Iteration: 46368/59290

 78%|███████▊  | 46352/59290 [35:46<04:58, 43.31it/s]

Iteration: 46369/59290
Iteration: 46370/59290
Iteration: 46371/59290
Iteration: 46372/59290
Iteration: 46373/59290
Iteration: 46374/59290
Iteration: 46375/59290
Iteration: 46376/59290
Iteration: 46377/59290
Iteration: 46378/59290
Iteration: 46379/59290
Iteration: 46380/59290
Iteration: 46381/59290
Iteration: 46382/59290
Iteration: 46383/59290
Iteration: 46384/59290
Iteration: 46385/59290
Iteration: 46386/59290
Iteration: 46387/59290
Iteration: 46388/59290
Iteration: 46389/59290
Iteration: 46390/59290
Iteration: 46391/59290
Iteration: 46392/59290

 78%|███████▊  | 46376/59290 [35:46<04:32, 47.34it/s]

Iteration: 46393/59290
Iteration: 46394/59290
Iteration: 46395/59290
Iteration: 46396/59290
Iteration: 46397/59290
Iteration: 46398/59290
Iteration: 46399/59290
Iteration: 46400/59290
Iteration: 46401/59290
Iteration: 46402/59290
Iteration: 46403/59290
Iteration: 46404/59290
Iteration: 46405/59290
Iteration: 46406/59290
Iteration: 46407/59290
Iteration: 46408/59290
Iteration: 46409/59290
Iteration: 46410/59290
Iteration: 46411/59290
Iteration: 46412/59290
Iteration: 46413/59290
Iteration: 46414/59290
Iteration: 46415/59290
Iteration: 46416/59290

 78%|███████▊  | 46400/59290 [35:47<04:15, 50.45it/s]

Iteration: 46417/59290
Iteration: 46418/59290
Iteration: 46419/59290
Iteration: 46420/59290
Iteration: 46421/59290
Iteration: 46422/59290
Iteration: 46423/59290
Iteration: 46424/59290
Iteration: 46425/59290
Iteration: 46426/59290
Iteration: 46427/59290
Iteration: 46428/59290
Iteration: 46429/59290
Iteration: 46430/59290
Iteration: 46431/59290
Iteration: 46432/59290
Iteration: 46433/59290
Iteration: 46434/59290
Iteration: 46435/59290
Iteration: 46436/59290
Iteration: 46437/59290
Iteration: 46438/59290
Iteration: 46439/59290
Iteration: 46440/59290

 78%|███████▊  | 46424/59290 [35:47<04:05, 52.32it/s]

Iteration: 46441/59290
Iteration: 46442/59290
Iteration: 46443/59290
Iteration: 46444/59290
Iteration: 46445/59290
Iteration: 46446/59290
Iteration: 46447/59290
Iteration: 46448/59290
Iteration: 46449/59290
Iteration: 46450/59290
Iteration: 46451/59290
Iteration: 46452/59290
Iteration: 46453/59290
Iteration: 46454/59290
Iteration: 46455/59290
Iteration: 46456/59290
Iteration: 46457/59290
Iteration: 46458/59290
Iteration: 46459/59290
Iteration: 46460/59290
Iteration: 46461/59290
Iteration: 46462/59290
Iteration: 46463/59290
Iteration: 46464/59290

 78%|███████▊  | 46448/59290 [35:47<03:54, 54.75it/s]

Iteration: 46465/59290
Iteration: 46466/59290
Iteration: 46467/59290
Iteration: 46468/59290
Iteration: 46469/59290
Iteration: 46470/59290
Iteration: 46471/59290
Iteration: 46472/59290
Iteration: 46473/59290
Iteration: 46474/59290
Iteration: 46475/59290
Iteration: 46476/59290
Iteration: 46477/59290
Iteration: 46478/59290
Iteration: 46479/59290
Iteration: 46480/59290
Iteration: 46481/59290
Iteration: 46482/59290
Iteration: 46483/59290
Iteration: 46484/59290
Iteration: 46485/59290
Iteration: 46486/59290
Iteration: 46487/59290
Iteration: 46488/59290

 78%|███████▊  | 46472/59290 [35:49<05:47, 36.86it/s]

Iteration: 46489/59290
Iteration: 46490/59290
Iteration: 46491/59290
Iteration: 46492/59290
Iteration: 46493/59290
Iteration: 46494/59290
Iteration: 46495/59290
Iteration: 46496/59290
Iteration: 46497/59290
Iteration: 46498/59290
Iteration: 46499/59290
Iteration: 46500/59290
Iteration: 46501/59290
Iteration: 46502/59290
Iteration: 46503/59290
Iteration: 46504/59290
Iteration: 46505/59290
Iteration: 46506/59290
Iteration: 46507/59290
Iteration: 46508/59290
Iteration: 46509/59290
Iteration: 46510/59290
Iteration: 46511/59290
Iteration: 46512/59290

 78%|███████▊  | 46496/59290 [35:51<09:35, 22.25it/s]

Iteration: 46513/59290
Iteration: 46514/59290
Iteration: 46515/59290
Iteration: 46516/59290
Iteration: 46517/59290
Iteration: 46518/59290
Iteration: 46519/59290
Iteration: 46520/59290
Iteration: 46521/59290
Iteration: 46522/59290
Iteration: 46523/59290
Iteration: 46524/59290
Iteration: 46525/59290
Iteration: 46526/59290
Iteration: 46527/59290
Iteration: 46528/59290
Iteration: 46529/59290
Iteration: 46530/59290
Iteration: 46531/59290
Iteration: 46532/59290
Iteration: 46533/59290
Iteration: 46534/59290
Iteration: 46535/59290
Iteration: 46536/59290

 78%|███████▊  | 46520/59290 [35:51<08:14, 25.84it/s]

Iteration: 46537/59290
Iteration: 46538/59290
Iteration: 46539/59290
Iteration: 46540/59290
Iteration: 46541/59290
Iteration: 46542/59290
Iteration: 46543/59290
Iteration: 46544/59290
Iteration: 46545/59290
Iteration: 46546/59290
Iteration: 46547/59290
Iteration: 46548/59290
Iteration: 46549/59290
Iteration: 46550/59290
Iteration: 46551/59290
Iteration: 46552/59290
Iteration: 46553/59290
Iteration: 46554/59290
Iteration: 46555/59290
Iteration: 46556/59290
Iteration: 46557/59290
Iteration: 46558/59290
Iteration: 46559/59290
Iteration: 46560/59290

 79%|███████▊  | 46544/59290 [35:52<06:55, 30.67it/s]

Iteration: 46561/59290
Iteration: 46562/59290
Iteration: 46563/59290
Iteration: 46564/59290
Iteration: 46565/59290
Iteration: 46566/59290
Iteration: 46567/59290
Iteration: 46568/59290
Iteration: 46569/59290
Iteration: 46570/59290
Iteration: 46571/59290
Iteration: 46572/59290
Iteration: 46573/59290
Iteration: 46574/59290
Iteration: 46575/59290
Iteration: 46576/59290
Iteration: 46577/59290
Iteration: 46578/59290
Iteration: 46579/59290
Iteration: 46580/59290
Iteration: 46581/59290
Iteration: 46582/59290
Iteration: 46583/59290
Iteration: 46584/59290

 79%|███████▊  | 46568/59290 [35:52<05:55, 35.79it/s]

Iteration: 46585/59290
Iteration: 46586/59290
Iteration: 46587/59290
Iteration: 46588/59290
Iteration: 46589/59290
Iteration: 46590/59290
Iteration: 46591/59290
Iteration: 46592/59290
Iteration: 46593/59290
Iteration: 46594/59290
Iteration: 46595/59290
Iteration: 46596/59290
Iteration: 46597/59290
Iteration: 46598/59290
Iteration: 46599/59290
Iteration: 46600/59290
Iteration: 46601/59290
Iteration: 46602/59290
Iteration: 46603/59290
Iteration: 46604/59290
Iteration: 46605/59290
Iteration: 46606/59290
Iteration: 46607/59290
Iteration: 46608/59290

 79%|███████▊  | 46592/59290 [35:52<05:13, 40.56it/s]

Iteration: 46609/59290
Iteration: 46610/59290
Iteration: 46611/59290
Iteration: 46612/59290
Iteration: 46613/59290
Iteration: 46614/59290
Iteration: 46615/59290
Iteration: 46616/59290
Iteration: 46617/59290
Iteration: 46618/59290
Iteration: 46619/59290
Iteration: 46620/59290
Iteration: 46621/59290
Iteration: 46622/59290
Iteration: 46623/59290
Iteration: 46624/59290
Iteration: 46625/59290
Iteration: 46626/59290
Iteration: 46627/59290
Iteration: 46628/59290
Iteration: 46629/59290
Iteration: 46630/59290
Iteration: 46631/59290
Iteration: 46632/59290

 79%|███████▊  | 46616/59290 [35:53<04:41, 45.03it/s]

Iteration: 46633/59290
Iteration: 46634/59290
Iteration: 46635/59290
Iteration: 46636/59290
Iteration: 46637/59290
Iteration: 46638/59290
Iteration: 46639/59290
Iteration: 46640/59290
Iteration: 46641/59290
Iteration: 46642/59290
Iteration: 46643/59290
Iteration: 46644/59290
Iteration: 46645/59290
Iteration: 46646/59290
Iteration: 46647/59290
Iteration: 46648/59290
Iteration: 46649/59290
Iteration: 46650/59290
Iteration: 46651/59290
Iteration: 46652/59290
Iteration: 46653/59290
Iteration: 46654/59290
Iteration: 46655/59290
Iteration: 46656/59290

 79%|███████▊  | 46640/59290 [35:53<04:18, 48.99it/s]

Iteration: 46657/59290
Iteration: 46658/59290
Iteration: 46659/59290
Iteration: 46660/59290
Iteration: 46661/59290
Iteration: 46662/59290
Iteration: 46663/59290
Iteration: 46664/59290
Iteration: 46665/59290
Iteration: 46666/59290
Iteration: 46667/59290
Iteration: 46668/59290
Iteration: 46669/59290
Iteration: 46670/59290
Iteration: 46671/59290
Iteration: 46672/59290
Iteration: 46673/59290
Iteration: 46674/59290
Iteration: 46675/59290
Iteration: 46676/59290
Iteration: 46677/59290
Iteration: 46678/59290
Iteration: 46679/59290
Iteration: 46680/59290

 79%|███████▊  | 46664/59290 [35:54<04:04, 51.68it/s]

Iteration: 46681/59290
Iteration: 46682/59290
Iteration: 46683/59290
Iteration: 46684/59290
Iteration: 46685/59290
Iteration: 46686/59290
Iteration: 46687/59290
Iteration: 46688/59290
Iteration: 46689/59290
Iteration: 46690/59290
Iteration: 46691/59290
Iteration: 46692/59290
Iteration: 46693/59290
Iteration: 46694/59290
Iteration: 46695/59290
Iteration: 46696/59290
Iteration: 46697/59290
Iteration: 46698/59290
Iteration: 46699/59290
Iteration: 46700/59290
Iteration: 46701/59290
Iteration: 46702/59290
Iteration: 46703/59290
Iteration: 46704/59290

 79%|███████▊  | 46688/59290 [35:54<03:57, 53.00it/s]

Iteration: 46705/59290
Iteration: 46706/59290
Iteration: 46707/59290
Iteration: 46708/59290
Iteration: 46709/59290
Iteration: 46710/59290
Iteration: 46711/59290
Iteration: 46712/59290
Iteration: 46713/59290
Iteration: 46714/59290
Iteration: 46715/59290
Iteration: 46716/59290
Iteration: 46717/59290
Iteration: 46718/59290
Iteration: 46719/59290
Iteration: 46720/59290
Iteration: 46721/59290
Iteration: 46722/59290
Iteration: 46723/59290
Iteration: 46724/59290
Iteration: 46725/59290
Iteration: 46726/59290
Iteration: 46727/59290
Iteration: 46728/59290

 79%|███████▉  | 46712/59290 [36:28<1:32:22,  2.27it/s]

Iteration: 46729/59290
Iteration: 46730/59290
Iteration: 46731/59290
Iteration: 46732/59290
Iteration: 46733/59290
Iteration: 46734/59290
Iteration: 46735/59290
Iteration: 46736/59290
Iteration: 46737/59290
Iteration: 46738/59290
Iteration: 46739/59290
Iteration: 46740/59290
Iteration: 46741/59290
Iteration: 46742/59290
Iteration: 46743/59290
Iteration: 46744/59290
Iteration: 46745/59290
Iteration: 46746/59290
Iteration: 46747/59290
Iteration: 46748/59290
Iteration: 46749/59290
Iteration: 46750/59290
Iteration: 46751/59290
Iteration: 46752/59290

 79%|███████▉  | 46736/59290 [36:29<1:06:08,  3.16it/s]

Iteration: 46753/59290
Iteration: 46754/59290
Iteration: 46755/59290
Iteration: 46756/59290
Iteration: 46757/59290
Iteration: 46758/59290
Iteration: 46759/59290
Iteration: 46760/59290
Iteration: 46761/59290
Iteration: 46762/59290
Iteration: 46763/59290
Iteration: 46764/59290
Iteration: 46765/59290
Iteration: 46766/59290
Iteration: 46767/59290
Iteration: 46768/59290
Iteration: 46769/59290
Iteration: 46770/59290
Iteration: 46771/59290
Iteration: 46772/59290
Iteration: 46773/59290
Iteration: 46774/59290
Iteration: 46775/59290
Iteration: 46776/59290

 79%|███████▉  | 46760/59290 [36:29<47:14,  4.42it/s]

Iteration: 46777/59290
Iteration: 46778/59290
Iteration: 46779/59290
Iteration: 46780/59290
Iteration: 46781/59290
Iteration: 46782/59290
Iteration: 46783/59290
Iteration: 46784/59290
Iteration: 46785/59290
Iteration: 46786/59290
Iteration: 46787/59290
Iteration: 46788/59290
Iteration: 46789/59290
Iteration: 46790/59290
Iteration: 46791/59290
Iteration: 46792/59290
Iteration: 46793/59290
Iteration: 46794/59290
Iteration: 46795/59290
Iteration: 46796/59290
Iteration: 46797/59290
Iteration: 46798/59290
Iteration: 46799/59290
Iteration: 46800/59290

 79%|███████▉  | 46784/59290 [36:30<34:00,  6.13it/s]

Iteration: 46801/59290
Iteration: 46802/59290
Iteration: 46803/59290
Iteration: 46804/59290
Iteration: 46805/59290
Iteration: 46806/59290
Iteration: 46807/59290
Iteration: 46808/59290
Iteration: 46809/59290
Iteration: 46810/59290
Iteration: 46811/59290
Iteration: 46812/59290
Iteration: 46813/59290
Iteration: 46814/59290
Iteration: 46815/59290
Iteration: 46816/59290
Iteration: 46817/59290
Iteration: 46818/59290
Iteration: 46819/59290
Iteration: 46820/59290
Iteration: 46821/59290
Iteration: 46822/59290
Iteration: 46823/59290
Iteration: 46824/59290

 79%|███████▉  | 46808/59290 [36:30<24:44,  8.41it/s]

Iteration: 46825/59290
Iteration: 46826/59290
Iteration: 46827/59290
Iteration: 46828/59290
Iteration: 46829/59290
Iteration: 46830/59290
Iteration: 46831/59290
Iteration: 46832/59290
Iteration: 46833/59290
Iteration: 46834/59290
Iteration: 46835/59290
Iteration: 46836/59290
Iteration: 46837/59290
Iteration: 46838/59290
Iteration: 46839/59290
Iteration: 46840/59290
Iteration: 46841/59290
Iteration: 46842/59290
Iteration: 46843/59290
Iteration: 46844/59290
Iteration: 46845/59290
Iteration: 46846/59290
Iteration: 46847/59290
Iteration: 46848/59290

 79%|███████▉  | 46832/59290 [36:30<18:16, 11.36it/s]

Iteration: 46849/59290
Iteration: 46850/59290
Iteration: 46851/59290
Iteration: 46852/59290
Iteration: 46853/59290
Iteration: 46854/59290
Iteration: 46855/59290
Iteration: 46856/59290
Iteration: 46857/59290
Iteration: 46858/59290
Iteration: 46859/59290
Iteration: 46860/59290
Iteration: 46861/59290
Iteration: 46862/59290
Iteration: 46863/59290
Iteration: 46864/59290
Iteration: 46865/59290
Iteration: 46866/59290
Iteration: 46867/59290
Iteration: 46868/59290
Iteration: 46869/59290
Iteration: 46870/59290
Iteration: 46871/59290
Iteration: 46872/59290

 79%|███████▉  | 46856/59290 [36:32<16:17, 12.72it/s]

Iteration: 46873/59290
Iteration: 46874/59290
Iteration: 46875/59290
Iteration: 46876/59290
Iteration: 46877/59290
Iteration: 46878/59290
Iteration: 46879/59290
Iteration: 46880/59290
Iteration: 46881/59290
Iteration: 46882/59290
Iteration: 46883/59290
Iteration: 46884/59290
Iteration: 46885/59290
Iteration: 46886/59290
Iteration: 46887/59290
Iteration: 46888/59290
Iteration: 46889/59290
Iteration: 46890/59290
Iteration: 46891/59290
Iteration: 46892/59290
Iteration: 46893/59290
Iteration: 46894/59290
Iteration: 46895/59290
Iteration: 46896/59290

 79%|███████▉  | 46880/59290 [36:34<18:08, 11.41it/s]

Iteration: 46897/59290
Iteration: 46898/59290
Iteration: 46899/59290
Iteration: 46900/59290
Iteration: 46901/59290
Iteration: 46902/59290
Iteration: 46903/59290
Iteration: 46904/59290
Iteration: 46905/59290
Iteration: 46906/59290
Iteration: 46907/59290
Iteration: 46908/59290
Iteration: 46909/59290
Iteration: 46910/59290
Iteration: 46911/59290
Iteration: 46912/59290
Iteration: 46913/59290
Iteration: 46914/59290
Iteration: 46915/59290
Iteration: 46916/59290
Iteration: 46917/59290
Iteration: 46918/59290
Iteration: 46919/59290
Iteration: 46920/59290

 79%|███████▉  | 46904/59290 [36:35<13:38, 15.13it/s]

Iteration: 46921/59290
Iteration: 46922/59290
Iteration: 46923/59290
Iteration: 46924/59290
Iteration: 46925/59290
Iteration: 46926/59290
Iteration: 46927/59290
Iteration: 46928/59290
Iteration: 46929/59290
Iteration: 46930/59290
Iteration: 46931/59290
Iteration: 46932/59290
Iteration: 46933/59290
Iteration: 46934/59290
Iteration: 46935/59290
Iteration: 46936/59290
Iteration: 46937/59290
Iteration: 46938/59290
Iteration: 46939/59290
Iteration: 46940/59290
Iteration: 46941/59290
Iteration: 46942/59290
Iteration: 46943/59290
Iteration: 46944/59290

 79%|███████▉  | 46928/59290 [36:35<10:30, 19.61it/s]

Iteration: 46945/59290
Iteration: 46946/59290
Iteration: 46947/59290
Iteration: 46948/59290
Iteration: 46949/59290
Iteration: 46950/59290
Iteration: 46951/59290
Iteration: 46952/59290
Iteration: 46953/59290
Iteration: 46954/59290
Iteration: 46955/59290
Iteration: 46956/59290
Iteration: 46957/59290
Iteration: 46958/59290
Iteration: 46959/59290
Iteration: 46960/59290
Iteration: 46961/59290
Iteration: 46962/59290
Iteration: 46963/59290
Iteration: 46964/59290
Iteration: 46965/59290
Iteration: 46966/59290
Iteration: 46967/59290
Iteration: 46968/59290

 79%|███████▉  | 46952/59290 [36:36<08:20, 24.65it/s]

Iteration: 46969/59290
Iteration: 46970/59290
Iteration: 46971/59290
Iteration: 46972/59290
Iteration: 46973/59290
Iteration: 46974/59290
Iteration: 46975/59290
Iteration: 46976/59290
Iteration: 46977/59290
Iteration: 46978/59290
Iteration: 46979/59290
Iteration: 46980/59290
Iteration: 46981/59290
Iteration: 46982/59290
Iteration: 46983/59290
Iteration: 46984/59290
Iteration: 46985/59290
Iteration: 46986/59290
Iteration: 46987/59290
Iteration: 46988/59290
Iteration: 46989/59290
Iteration: 46990/59290
Iteration: 46991/59290
Iteration: 46992/59290

 79%|███████▉  | 46976/59290 [36:36<06:47, 30.23it/s]

Iteration: 46993/59290
Iteration: 46994/59290
Iteration: 46995/59290
Iteration: 46996/59290
Iteration: 46997/59290
Iteration: 46998/59290
Iteration: 46999/59290
Iteration: 47000/59290
Iteration: 47001/59290
Iteration: 47002/59290
Iteration: 47003/59290
Iteration: 47004/59290
Iteration: 47005/59290
Iteration: 47006/59290
Iteration: 47007/59290
Iteration: 47008/59290
Iteration: 47009/59290
Iteration: 47010/59290
Iteration: 47011/59290
Iteration: 47012/59290
Iteration: 47013/59290
Iteration: 47014/59290
Iteration: 47015/59290
Iteration: 47016/59290

 79%|███████▉  | 47000/59290 [36:37<08:08, 25.16it/s]

Iteration: 47017/59290
Iteration: 47018/59290
Iteration: 47019/59290
Iteration: 47020/59290
Iteration: 47021/59290
Iteration: 47022/59290
Iteration: 47023/59290
Iteration: 47024/59290
Iteration: 47025/59290
Iteration: 47026/59290
Iteration: 47027/59290
Iteration: 47028/59290
Iteration: 47029/59290
Iteration: 47030/59290
Iteration: 47031/59290
Iteration: 47032/59290
Iteration: 47033/59290
Iteration: 47034/59290
Iteration: 47035/59290
Iteration: 47036/59290
Iteration: 47037/59290
Iteration: 47038/59290
Iteration: 47039/59290
Iteration: 47040/59290

 79%|███████▉  | 47024/59290 [36:40<12:29, 16.36it/s]

Iteration: 47041/59290
Iteration: 47042/59290
Iteration: 47043/59290
Iteration: 47044/59290
Iteration: 47045/59290
Iteration: 47046/59290
Iteration: 47047/59290
Iteration: 47048/59290
Iteration: 47049/59290
Iteration: 47050/59290
Iteration: 47051/59290
Iteration: 47052/59290
Iteration: 47053/59290
Iteration: 47054/59290
Iteration: 47055/59290
Iteration: 47056/59290
Iteration: 47057/59290
Iteration: 47058/59290
Iteration: 47059/59290
Iteration: 47060/59290
Iteration: 47061/59290
Iteration: 47062/59290
Iteration: 47063/59290
Iteration: 47064/59290

 79%|███████▉  | 47048/59290 [36:40<09:41, 21.06it/s]

Iteration: 47065/59290
Iteration: 47066/59290
Iteration: 47067/59290
Iteration: 47068/59290
Iteration: 47069/59290
Iteration: 47070/59290
Iteration: 47071/59290
Iteration: 47072/59290
Iteration: 47073/59290
Iteration: 47074/59290
Iteration: 47075/59290
Iteration: 47076/59290
Iteration: 47077/59290
Iteration: 47078/59290
Iteration: 47079/59290
Iteration: 47080/59290
Iteration: 47081/59290
Iteration: 47082/59290
Iteration: 47083/59290
Iteration: 47084/59290
Iteration: 47085/59290
Iteration: 47086/59290
Iteration: 47087/59290
Iteration: 47088/59290

 79%|███████▉  | 47072/59290 [36:41<07:44, 26.33it/s]

Iteration: 47089/59290
Iteration: 47090/59290
Iteration: 47091/59290
Iteration: 47092/59290
Iteration: 47093/59290
Iteration: 47094/59290
Iteration: 47095/59290
Iteration: 47096/59290
Iteration: 47097/59290
Iteration: 47098/59290
Iteration: 47099/59290
Iteration: 47100/59290
Iteration: 47101/59290
Iteration: 47102/59290
Iteration: 47103/59290
Iteration: 47104/59290
Iteration: 47105/59290
Iteration: 47106/59290
Iteration: 47107/59290
Iteration: 47108/59290
Iteration: 47109/59290
Iteration: 47110/59290
Iteration: 47111/59290
Iteration: 47112/59290

 79%|███████▉  | 47096/59290 [36:41<06:21, 31.93it/s]

Iteration: 47113/59290
Iteration: 47114/59290
Iteration: 47115/59290
Iteration: 47116/59290
Iteration: 47117/59290
Iteration: 47118/59290
Iteration: 47119/59290
Iteration: 47120/59290
Iteration: 47121/59290
Iteration: 47122/59290
Iteration: 47123/59290
Iteration: 47124/59290
Iteration: 47125/59290
Iteration: 47126/59290
Iteration: 47127/59290
Iteration: 47128/59290
Iteration: 47129/59290
Iteration: 47130/59290
Iteration: 47131/59290
Iteration: 47132/59290
Iteration: 47133/59290
Iteration: 47134/59290
Iteration: 47135/59290
Iteration: 47136/59290

 79%|███████▉  | 47120/59290 [36:43<08:18, 24.42it/s]

Iteration: 47137/59290
Iteration: 47138/59290
Iteration: 47139/59290
Iteration: 47140/59290
Iteration: 47141/59290
Iteration: 47142/59290
Iteration: 47143/59290
Iteration: 47144/59290
Iteration: 47145/59290
Iteration: 47146/59290
Iteration: 47147/59290
Iteration: 47148/59290
Iteration: 47149/59290
Iteration: 47150/59290
Iteration: 47151/59290
Iteration: 47152/59290
Iteration: 47153/59290
Iteration: 47154/59290
Iteration: 47155/59290
Iteration: 47156/59290
Iteration: 47157/59290
Iteration: 47158/59290
Iteration: 47159/59290
Iteration: 47160/59290

 80%|███████▉  | 47144/59290 [36:45<11:33, 17.52it/s]

Iteration: 47161/59290
Iteration: 47162/59290
Iteration: 47163/59290
Iteration: 47164/59290
Iteration: 47165/59290
Iteration: 47166/59290
Iteration: 47167/59290
Iteration: 47168/59290
Iteration: 47169/59290
Iteration: 47170/59290
Iteration: 47171/59290
Iteration: 47172/59290
Iteration: 47173/59290
Iteration: 47174/59290
Iteration: 47175/59290
Iteration: 47176/59290
Iteration: 47177/59290
Iteration: 47178/59290
Iteration: 47179/59290
Iteration: 47180/59290
Iteration: 47181/59290
Iteration: 47182/59290
Iteration: 47183/59290
Iteration: 47184/59290

 80%|███████▉  | 47168/59290 [36:45<09:33, 21.12it/s]

Iteration: 47185/59290
Iteration: 47186/59290
Iteration: 47187/59290
Iteration: 47188/59290
Iteration: 47189/59290
Iteration: 47190/59290
Iteration: 47191/59290
Iteration: 47192/59290
Iteration: 47193/59290
Iteration: 47194/59290
Iteration: 47195/59290
Iteration: 47196/59290
Iteration: 47197/59290
Iteration: 47198/59290
Iteration: 47199/59290
Iteration: 47200/59290
Iteration: 47201/59290
Iteration: 47202/59290
Iteration: 47203/59290
Iteration: 47204/59290
Iteration: 47205/59290
Iteration: 47206/59290
Iteration: 47207/59290
Iteration: 47208/59290

 80%|███████▉  | 47192/59290 [36:46<07:37, 26.45it/s]

Iteration: 47209/59290
Iteration: 47210/59290
Iteration: 47211/59290
Iteration: 47212/59290
Iteration: 47213/59290
Iteration: 47214/59290
Iteration: 47215/59290
Iteration: 47216/59290
Iteration: 47217/59290
Iteration: 47218/59290
Iteration: 47219/59290
Iteration: 47220/59290
Iteration: 47221/59290
Iteration: 47222/59290
Iteration: 47223/59290
Iteration: 47224/59290
Iteration: 47225/59290
Iteration: 47226/59290
Iteration: 47227/59290
Iteration: 47228/59290
Iteration: 47229/59290
Iteration: 47230/59290
Iteration: 47231/59290
Iteration: 47232/59290

 80%|███████▉  | 47216/59290 [36:46<06:16, 32.06it/s]

Iteration: 47233/59290
Iteration: 47234/59290
Iteration: 47235/59290
Iteration: 47236/59290
Iteration: 47237/59290
Iteration: 47238/59290
Iteration: 47239/59290
Iteration: 47240/59290
Iteration: 47241/59290
Iteration: 47242/59290
Iteration: 47243/59290
Iteration: 47244/59290
Iteration: 47245/59290
Iteration: 47246/59290
Iteration: 47247/59290
Iteration: 47248/59290
Iteration: 47249/59290
Iteration: 47250/59290
Iteration: 47251/59290
Iteration: 47252/59290
Iteration: 47253/59290
Iteration: 47254/59290
Iteration: 47255/59290
Iteration: 47256/59290

 80%|███████▉  | 47240/59290 [36:47<05:20, 37.61it/s]

Iteration: 47257/59290
Iteration: 47258/59290
Iteration: 47259/59290
Iteration: 47260/59290
Iteration: 47261/59290
Iteration: 47262/59290
Iteration: 47263/59290
Iteration: 47264/59290
Iteration: 47265/59290
Iteration: 47266/59290
Iteration: 47267/59290
Iteration: 47268/59290
Iteration: 47269/59290
Iteration: 47270/59290
Iteration: 47271/59290
Iteration: 47272/59290
Iteration: 47273/59290
Iteration: 47274/59290
Iteration: 47275/59290
Iteration: 47276/59290
Iteration: 47277/59290
Iteration: 47278/59290
Iteration: 47279/59290
Iteration: 47280/59290

 80%|███████▉  | 47264/59290 [36:47<04:41, 42.76it/s]

Iteration: 47281/59290
Iteration: 47282/59290
Iteration: 47283/59290
Iteration: 47284/59290
Iteration: 47285/59290
Iteration: 47286/59290
Iteration: 47287/59290
Iteration: 47288/59290
Iteration: 47289/59290
Iteration: 47290/59290
Iteration: 47291/59290
Iteration: 47292/59290
Iteration: 47293/59290
Iteration: 47294/59290
Iteration: 47295/59290
Iteration: 47296/59290
Iteration: 47297/59290
Iteration: 47298/59290
Iteration: 47299/59290
Iteration: 47300/59290
Iteration: 47301/59290
Iteration: 47302/59290
Iteration: 47303/59290
Iteration: 47304/59290

 80%|███████▉  | 47288/59290 [36:47<04:13, 47.37it/s]

Iteration: 47305/59290
Iteration: 47306/59290
Iteration: 47307/59290
Iteration: 47308/59290
Iteration: 47309/59290
Iteration: 47310/59290
Iteration: 47311/59290
Iteration: 47312/59290
Iteration: 47313/59290
Iteration: 47314/59290
Iteration: 47315/59290
Iteration: 47316/59290
Iteration: 47317/59290
Iteration: 47318/59290
Iteration: 47319/59290
Iteration: 47320/59290
Iteration: 47321/59290
Iteration: 47322/59290
Iteration: 47323/59290
Iteration: 47324/59290
Iteration: 47325/59290
Iteration: 47326/59290
Iteration: 47327/59290
Iteration: 47328/59290

 80%|███████▉  | 47312/59290 [36:48<03:53, 51.38it/s]

Iteration: 47329/59290
Iteration: 47330/59290
Iteration: 47331/59290
Iteration: 47332/59290
Iteration: 47333/59290
Iteration: 47334/59290
Iteration: 47335/59290
Iteration: 47336/59290
Iteration: 47337/59290
Iteration: 47338/59290
Iteration: 47339/59290
Iteration: 47340/59290
Iteration: 47341/59290
Iteration: 47342/59290
Iteration: 47343/59290
Iteration: 47344/59290
Iteration: 47345/59290
Iteration: 47346/59290
Iteration: 47347/59290
Iteration: 47348/59290
Iteration: 47349/59290
Iteration: 47350/59290
Iteration: 47351/59290
Iteration: 47352/59290

 80%|███████▉  | 47336/59290 [36:49<06:39, 29.91it/s]

Iteration: 47353/59290
Iteration: 47354/59290
Iteration: 47355/59290
Iteration: 47356/59290
Iteration: 47357/59290
Iteration: 47358/59290
Iteration: 47359/59290
Iteration: 47360/59290
Iteration: 47361/59290
Iteration: 47362/59290
Iteration: 47363/59290
Iteration: 47364/59290
Iteration: 47365/59290
Iteration: 47366/59290
Iteration: 47367/59290
Iteration: 47368/59290
Iteration: 47369/59290
Iteration: 47370/59290
Iteration: 47371/59290
Iteration: 47372/59290
Iteration: 47373/59290
Iteration: 47374/59290
Iteration: 47375/59290
Iteration: 47376/59290

 80%|███████▉  | 47360/59290 [36:52<11:34, 17.19it/s]

Iteration: 47377/59290
Iteration: 47378/59290
Iteration: 47379/59290
Iteration: 47380/59290
Iteration: 47381/59290
Iteration: 47382/59290
Iteration: 47383/59290
Iteration: 47384/59290
Iteration: 47385/59290
Iteration: 47386/59290
Iteration: 47387/59290
Iteration: 47388/59290
Iteration: 47389/59290
Iteration: 47390/59290
Iteration: 47391/59290
Iteration: 47392/59290
Iteration: 47393/59290
Iteration: 47394/59290
Iteration: 47395/59290
Iteration: 47396/59290
Iteration: 47397/59290
Iteration: 47398/59290
Iteration: 47399/59290
Iteration: 47400/59290

 80%|███████▉  | 47384/59290 [36:52<09:00, 22.03it/s]

Iteration: 47401/59290
Iteration: 47402/59290
Iteration: 47403/59290
Iteration: 47404/59290
Iteration: 47405/59290
Iteration: 47406/59290
Iteration: 47407/59290
Iteration: 47408/59290
Iteration: 47409/59290
Iteration: 47410/59290
Iteration: 47411/59290
Iteration: 47412/59290
Iteration: 47413/59290
Iteration: 47414/59290
Iteration: 47415/59290
Iteration: 47416/59290
Iteration: 47417/59290
Iteration: 47418/59290
Iteration: 47419/59290
Iteration: 47420/59290
Iteration: 47421/59290
Iteration: 47422/59290
Iteration: 47423/59290
Iteration: 47424/59290

 80%|███████▉  | 47408/59290 [36:53<07:13, 27.44it/s]

Iteration: 47425/59290
Iteration: 47426/59290
Iteration: 47427/59290
Iteration: 47428/59290
Iteration: 47429/59290
Iteration: 47430/59290
Iteration: 47431/59290
Iteration: 47432/59290
Iteration: 47433/59290
Iteration: 47434/59290
Iteration: 47435/59290
Iteration: 47436/59290
Iteration: 47437/59290
Iteration: 47438/59290
Iteration: 47439/59290
Iteration: 47440/59290
Iteration: 47441/59290
Iteration: 47442/59290
Iteration: 47443/59290
Iteration: 47444/59290
Iteration: 47445/59290
Iteration: 47446/59290
Iteration: 47447/59290
Iteration: 47448/59290

 80%|████████  | 47432/59290 [36:53<05:58, 33.08it/s]

Iteration: 47449/59290
Iteration: 47450/59290
Iteration: 47451/59290
Iteration: 47452/59290
Iteration: 47453/59290
Iteration: 47454/59290
Iteration: 47455/59290
Iteration: 47456/59290
Iteration: 47457/59290
Iteration: 47458/59290
Iteration: 47459/59290
Iteration: 47460/59290
Iteration: 47461/59290
Iteration: 47462/59290
Iteration: 47463/59290
Iteration: 47464/59290
Iteration: 47465/59290
Iteration: 47466/59290
Iteration: 47467/59290
Iteration: 47468/59290
Iteration: 47469/59290
Iteration: 47470/59290
Iteration: 47471/59290
Iteration: 47472/59290

 80%|████████  | 47456/59290 [36:54<05:05, 38.68it/s]

Iteration: 47473/59290
Iteration: 47474/59290
Iteration: 47475/59290
Iteration: 47476/59290
Iteration: 47477/59290
Iteration: 47478/59290
Iteration: 47479/59290
Iteration: 47480/59290
Iteration: 47481/59290
Iteration: 47482/59290
Iteration: 47483/59290
Iteration: 47484/59290
Iteration: 47485/59290
Iteration: 47486/59290
Iteration: 47487/59290
Iteration: 47488/59290
Iteration: 47489/59290
Iteration: 47490/59290
Iteration: 47491/59290
Iteration: 47492/59290
Iteration: 47493/59290
Iteration: 47494/59290
Iteration: 47495/59290
Iteration: 47496/59290

 80%|████████  | 47480/59290 [36:54<04:30, 43.64it/s]

Iteration: 47497/59290
Iteration: 47498/59290
Iteration: 47499/59290
Iteration: 47500/59290
Iteration: 47501/59290
Iteration: 47502/59290
Iteration: 47503/59290
Iteration: 47504/59290
Iteration: 47505/59290
Iteration: 47506/59290
Iteration: 47507/59290
Iteration: 47508/59290
Iteration: 47509/59290
Iteration: 47510/59290
Iteration: 47511/59290
Iteration: 47512/59290
Iteration: 47513/59290
Iteration: 47514/59290
Iteration: 47515/59290
Iteration: 47516/59290
Iteration: 47517/59290
Iteration: 47518/59290
Iteration: 47519/59290
Iteration: 47520/59290

 80%|████████  | 47504/59290 [36:54<04:06, 47.82it/s]

Iteration: 47521/59290
Iteration: 47522/59290
Iteration: 47523/59290
Iteration: 47524/59290
Iteration: 47525/59290
Iteration: 47526/59290
Iteration: 47527/59290
Iteration: 47528/59290
Iteration: 47529/59290
Iteration: 47530/59290
Iteration: 47531/59290
Iteration: 47532/59290
Iteration: 47533/59290
Iteration: 47534/59290
Iteration: 47535/59290
Iteration: 47536/59290
Iteration: 47537/59290
Iteration: 47538/59290
Iteration: 47539/59290
Iteration: 47540/59290
Iteration: 47541/59290
Iteration: 47542/59290
Iteration: 47543/59290
Iteration: 47544/59290

 80%|████████  | 47528/59290 [36:55<03:48, 51.51it/s]

Iteration: 47545/59290
Iteration: 47546/59290
Iteration: 47547/59290
Iteration: 47548/59290
Iteration: 47549/59290
Iteration: 47550/59290
Iteration: 47551/59290
Iteration: 47552/59290
Iteration: 47553/59290
Iteration: 47554/59290
Iteration: 47555/59290
Iteration: 47556/59290
Iteration: 47557/59290
Iteration: 47558/59290
Iteration: 47559/59290
Iteration: 47560/59290
Iteration: 47561/59290
Iteration: 47562/59290
Iteration: 47563/59290
Iteration: 47564/59290
Iteration: 47565/59290
Iteration: 47566/59290
Iteration: 47567/59290
Iteration: 47568/59290

 80%|████████  | 47552/59290 [36:58<11:25, 17.13it/s]

Iteration: 47569/59290
Iteration: 47570/59290
Iteration: 47571/59290
Iteration: 47572/59290
Iteration: 47573/59290
Iteration: 47574/59290
Iteration: 47575/59290
Iteration: 47576/59290
Iteration: 47577/59290
Iteration: 47578/59290
Iteration: 47579/59290
Iteration: 47580/59290
Iteration: 47581/59290
Iteration: 47582/59290
Iteration: 47583/59290
Iteration: 47584/59290
Iteration: 47585/59290
Iteration: 47586/59290
Iteration: 47587/59290
Iteration: 47588/59290
Iteration: 47589/59290
Iteration: 47590/59290
Iteration: 47591/59290
Iteration: 47592/59290

 80%|████████  | 47576/59290 [36:59<09:40, 20.19it/s]

Iteration: 47593/59290
Iteration: 47594/59290
Iteration: 47595/59290
Iteration: 47596/59290
Iteration: 47597/59290
Iteration: 47598/59290
Iteration: 47599/59290
Iteration: 47600/59290
Iteration: 47601/59290
Iteration: 47602/59290
Iteration: 47603/59290
Iteration: 47604/59290
Iteration: 47605/59290
Iteration: 47606/59290
Iteration: 47607/59290
Iteration: 47608/59290
Iteration: 47609/59290
Iteration: 47610/59290
Iteration: 47611/59290
Iteration: 47612/59290
Iteration: 47613/59290
Iteration: 47614/59290
Iteration: 47615/59290
Iteration: 47616/59290

 80%|████████  | 47600/59290 [37:32<1:26:37,  2.25it/s]

Iteration: 47617/59290
Iteration: 47618/59290
Iteration: 47619/59290
Iteration: 47620/59290
Iteration: 47621/59290
Iteration: 47622/59290
Iteration: 47623/59290
Iteration: 47624/59290
Iteration: 47625/59290
Iteration: 47626/59290
Iteration: 47627/59290
Iteration: 47628/59290
Iteration: 47629/59290
Iteration: 47630/59290
Iteration: 47631/59290
Iteration: 47632/59290
Iteration: 47633/59290
Iteration: 47634/59290
Iteration: 47635/59290
Iteration: 47636/59290
Iteration: 47637/59290
Iteration: 47638/59290
Iteration: 47639/59290
Iteration: 47640/59290

 80%|████████  | 47624/59290 [37:32<1:01:28,  3.16it/s]

Iteration: 47641/59290
Iteration: 47642/59290
Iteration: 47643/59290
Iteration: 47644/59290
Iteration: 47645/59290
Iteration: 47646/59290
Iteration: 47647/59290
Iteration: 47648/59290
Iteration: 47649/59290
Iteration: 47650/59290
Iteration: 47651/59290
Iteration: 47652/59290
Iteration: 47653/59290
Iteration: 47654/59290
Iteration: 47655/59290
Iteration: 47656/59290
Iteration: 47657/59290
Iteration: 47658/59290
Iteration: 47659/59290
Iteration: 47660/59290
Iteration: 47661/59290
Iteration: 47662/59290
Iteration: 47663/59290
Iteration: 47664/59290

 80%|████████  | 47648/59290 [37:33<43:52,  4.42it/s]

Iteration: 47665/59290
Iteration: 47666/59290
Iteration: 47667/59290
Iteration: 47668/59290
Iteration: 47669/59290
Iteration: 47670/59290
Iteration: 47671/59290
Iteration: 47672/59290
Iteration: 47673/59290
Iteration: 47674/59290
Iteration: 47675/59290
Iteration: 47676/59290
Iteration: 47677/59290
Iteration: 47678/59290
Iteration: 47679/59290
Iteration: 47680/59290
Iteration: 47681/59290
Iteration: 47682/59290
Iteration: 47683/59290
Iteration: 47684/59290
Iteration: 47685/59290
Iteration: 47686/59290
Iteration: 47687/59290
Iteration: 47688/59290

 80%|████████  | 47672/59290 [37:33<31:36,  6.13it/s]

Iteration: 47689/59290
Iteration: 47690/59290
Iteration: 47691/59290
Iteration: 47692/59290
Iteration: 47693/59290
Iteration: 47694/59290
Iteration: 47695/59290
Iteration: 47696/59290
Iteration: 47697/59290
Iteration: 47698/59290
Iteration: 47699/59290
Iteration: 47700/59290
Iteration: 47701/59290
Iteration: 47702/59290
Iteration: 47703/59290
Iteration: 47704/59290
Iteration: 47705/59290
Iteration: 47706/59290
Iteration: 47707/59290
Iteration: 47708/59290
Iteration: 47709/59290
Iteration: 47710/59290
Iteration: 47711/59290
Iteration: 47712/59290

 80%|████████  | 47696/59290 [37:33<22:59,  8.40it/s]

Iteration: 47713/59290
Iteration: 47714/59290
Iteration: 47715/59290
Iteration: 47716/59290
Iteration: 47717/59290
Iteration: 47718/59290
Iteration: 47719/59290
Iteration: 47720/59290
Iteration: 47721/59290
Iteration: 47722/59290
Iteration: 47723/59290
Iteration: 47724/59290
Iteration: 47725/59290
Iteration: 47726/59290
Iteration: 47727/59290
Iteration: 47728/59290
Iteration: 47729/59290
Iteration: 47730/59290
Iteration: 47731/59290
Iteration: 47732/59290
Iteration: 47733/59290
Iteration: 47734/59290
Iteration: 47735/59290
Iteration: 47736/59290

 80%|████████  | 47720/59290 [37:34<16:58, 11.37it/s]

Iteration: 47737/59290
Iteration: 47738/59290
Iteration: 47739/59290
Iteration: 47740/59290
Iteration: 47741/59290
Iteration: 47742/59290
Iteration: 47743/59290
Iteration: 47744/59290
Iteration: 47745/59290
Iteration: 47746/59290
Iteration: 47747/59290
Iteration: 47748/59290
Iteration: 47749/59290
Iteration: 47750/59290
Iteration: 47751/59290
Iteration: 47752/59290
Iteration: 47753/59290
Iteration: 47754/59290
Iteration: 47755/59290
Iteration: 47756/59290
Iteration: 47757/59290
Iteration: 47758/59290
Iteration: 47759/59290
Iteration: 47760/59290

 81%|████████  | 47744/59290 [37:34<12:49, 15.01it/s]

Iteration: 47761/59290
Iteration: 47762/59290
Iteration: 47763/59290
Iteration: 47764/59290
Iteration: 47765/59290
Iteration: 47766/59290
Iteration: 47767/59290
Iteration: 47768/59290
Iteration: 47769/59290
Iteration: 47770/59290
Iteration: 47771/59290
Iteration: 47772/59290
Iteration: 47773/59290
Iteration: 47774/59290
Iteration: 47775/59290
Iteration: 47776/59290
Iteration: 47777/59290
Iteration: 47778/59290
Iteration: 47779/59290
Iteration: 47780/59290
Iteration: 47781/59290
Iteration: 47782/59290
Iteration: 47783/59290
Iteration: 47784/59290

 81%|████████  | 47768/59290 [37:34<09:52, 19.46it/s]

Iteration: 47785/59290
Iteration: 47786/59290
Iteration: 47787/59290
Iteration: 47788/59290
Iteration: 47789/59290
Iteration: 47790/59290
Iteration: 47791/59290
Iteration: 47792/59290
Iteration: 47793/59290
Iteration: 47794/59290
Iteration: 47795/59290
Iteration: 47796/59290
Iteration: 47797/59290
Iteration: 47798/59290
Iteration: 47799/59290
Iteration: 47800/59290
Iteration: 47801/59290
Iteration: 47802/59290
Iteration: 47803/59290
Iteration: 47804/59290
Iteration: 47805/59290
Iteration: 47806/59290
Iteration: 47807/59290
Iteration: 47808/59290

 81%|████████  | 47792/59290 [37:36<10:00, 19.14it/s]

Iteration: 47809/59290
Iteration: 47810/59290
Iteration: 47811/59290
Iteration: 47812/59290
Iteration: 47813/59290
Iteration: 47814/59290
Iteration: 47815/59290
Iteration: 47816/59290
Iteration: 47817/59290
Iteration: 47818/59290
Iteration: 47819/59290
Iteration: 47820/59290
Iteration: 47821/59290
Iteration: 47822/59290
Iteration: 47823/59290
Iteration: 47824/59290
Iteration: 47825/59290
Iteration: 47826/59290
Iteration: 47827/59290
Iteration: 47828/59290
Iteration: 47829/59290
Iteration: 47830/59290
Iteration: 47831/59290
Iteration: 47832/59290

 81%|████████  | 47816/59290 [37:38<12:32, 15.24it/s]

Iteration: 47833/59290
Iteration: 47834/59290
Iteration: 47835/59290
Iteration: 47836/59290
Iteration: 47837/59290
Iteration: 47838/59290
Iteration: 47839/59290
Iteration: 47840/59290
Iteration: 47841/59290
Iteration: 47842/59290
Iteration: 47843/59290
Iteration: 47844/59290
Iteration: 47845/59290
Iteration: 47846/59290
Iteration: 47847/59290
Iteration: 47848/59290
Iteration: 47849/59290
Iteration: 47850/59290
Iteration: 47851/59290
Iteration: 47852/59290
Iteration: 47853/59290
Iteration: 47854/59290
Iteration: 47855/59290
Iteration: 47856/59290

 81%|████████  | 47840/59290 [37:38<09:39, 19.75it/s]

Iteration: 47857/59290
Iteration: 47858/59290
Iteration: 47859/59290
Iteration: 47860/59290
Iteration: 47861/59290
Iteration: 47862/59290
Iteration: 47863/59290
Iteration: 47864/59290
Iteration: 47865/59290
Iteration: 47866/59290
Iteration: 47867/59290
Iteration: 47868/59290
Iteration: 47869/59290
Iteration: 47870/59290
Iteration: 47871/59290
Iteration: 47872/59290
Iteration: 47873/59290
Iteration: 47874/59290
Iteration: 47875/59290
Iteration: 47876/59290
Iteration: 47877/59290
Iteration: 47878/59290
Iteration: 47879/59290
Iteration: 47880/59290

 81%|████████  | 47864/59290 [37:39<08:10, 23.28it/s]

Iteration: 47881/59290
Iteration: 47882/59290
Iteration: 47883/59290
Iteration: 47884/59290
Iteration: 47885/59290
Iteration: 47886/59290
Iteration: 47887/59290
Iteration: 47888/59290
Iteration: 47889/59290
Iteration: 47890/59290
Iteration: 47891/59290
Iteration: 47892/59290
Iteration: 47893/59290
Iteration: 47894/59290
Iteration: 47895/59290
Iteration: 47896/59290
Iteration: 47897/59290
Iteration: 47898/59290
Iteration: 47899/59290
Iteration: 47900/59290
Iteration: 47901/59290
Iteration: 47902/59290
Iteration: 47903/59290
Iteration: 47904/59290

 81%|████████  | 47888/59290 [37:39<06:36, 28.75it/s]

Iteration: 47905/59290
Iteration: 47906/59290
Iteration: 47907/59290
Iteration: 47908/59290
Iteration: 47909/59290
Iteration: 47910/59290
Iteration: 47911/59290
Iteration: 47912/59290
Iteration: 47913/59290
Iteration: 47914/59290
Iteration: 47915/59290
Iteration: 47916/59290
Iteration: 47917/59290
Iteration: 47918/59290
Iteration: 47919/59290
Iteration: 47920/59290
Iteration: 47921/59290
Iteration: 47922/59290
Iteration: 47923/59290
Iteration: 47924/59290
Iteration: 47925/59290
Iteration: 47926/59290
Iteration: 47927/59290
Iteration: 47928/59290

 81%|████████  | 47912/59290 [37:40<05:30, 34.44it/s]

Iteration: 47929/59290
Iteration: 47930/59290
Iteration: 47931/59290
Iteration: 47932/59290
Iteration: 47933/59290
Iteration: 47934/59290
Iteration: 47935/59290
Iteration: 47936/59290
Iteration: 47937/59290
Iteration: 47938/59290
Iteration: 47939/59290
Iteration: 47940/59290
Iteration: 47941/59290
Iteration: 47942/59290
Iteration: 47943/59290
Iteration: 47944/59290
Iteration: 47945/59290
Iteration: 47946/59290
Iteration: 47947/59290
Iteration: 47948/59290
Iteration: 47949/59290
Iteration: 47950/59290
Iteration: 47951/59290
Iteration: 47952/59290

 81%|████████  | 47936/59290 [37:40<04:45, 39.78it/s]

Iteration: 47953/59290
Iteration: 47954/59290
Iteration: 47955/59290
Iteration: 47956/59290
Iteration: 47957/59290
Iteration: 47958/59290
Iteration: 47959/59290
Iteration: 47960/59290
Iteration: 47961/59290
Iteration: 47962/59290
Iteration: 47963/59290
Iteration: 47964/59290
Iteration: 47965/59290
Iteration: 47966/59290
Iteration: 47967/59290
Iteration: 47968/59290
Iteration: 47969/59290
Iteration: 47970/59290
Iteration: 47971/59290
Iteration: 47972/59290
Iteration: 47973/59290
Iteration: 47974/59290
Iteration: 47975/59290
Iteration: 47976/59290

 81%|████████  | 47960/59290 [37:42<06:30, 29.00it/s]

Iteration: 47977/59290
Iteration: 47978/59290
Iteration: 47979/59290
Iteration: 47980/59290
Iteration: 47981/59290
Iteration: 47982/59290
Iteration: 47983/59290
Iteration: 47984/59290
Iteration: 47985/59290
Iteration: 47986/59290
Iteration: 47987/59290
Iteration: 47988/59290
Iteration: 47989/59290
Iteration: 47990/59290
Iteration: 47991/59290
Iteration: 47992/59290
Iteration: 47993/59290
Iteration: 47994/59290
Iteration: 47995/59290
Iteration: 47996/59290
Iteration: 47997/59290
Iteration: 47998/59290
Iteration: 47999/59290
Iteration: 48000/59290

 81%|████████  | 47984/59290 [37:44<09:53, 19.04it/s]

Iteration: 48001/59290
Iteration: 48002/59290
Iteration: 48003/59290
Iteration: 48004/59290
Iteration: 48005/59290
Iteration: 48006/59290
Iteration: 48007/59290
Iteration: 48008/59290
Iteration: 48009/59290
Iteration: 48010/59290
Iteration: 48011/59290
Iteration: 48012/59290
Iteration: 48013/59290
Iteration: 48014/59290
Iteration: 48015/59290
Iteration: 48016/59290
Iteration: 48017/59290
Iteration: 48018/59290
Iteration: 48019/59290
Iteration: 48020/59290
Iteration: 48021/59290
Iteration: 48022/59290
Iteration: 48023/59290
Iteration: 48024/59290

 81%|████████  | 48008/59290 [37:45<08:45, 21.46it/s]

Iteration: 48025/59290
Iteration: 48026/59290
Iteration: 48027/59290
Iteration: 48028/59290
Iteration: 48029/59290
Iteration: 48030/59290
Iteration: 48031/59290
Iteration: 48032/59290
Iteration: 48033/59290
Iteration: 48034/59290
Iteration: 48035/59290
Iteration: 48036/59290
Iteration: 48037/59290
Iteration: 48038/59290
Iteration: 48039/59290
Iteration: 48040/59290
Iteration: 48041/59290
Iteration: 48042/59290
Iteration: 48043/59290
Iteration: 48044/59290
Iteration: 48045/59290
Iteration: 48046/59290
Iteration: 48047/59290
Iteration: 48048/59290

 81%|████████  | 48032/59290 [37:45<07:00, 26.75it/s]

Iteration: 48049/59290
Iteration: 48050/59290
Iteration: 48051/59290
Iteration: 48052/59290
Iteration: 48053/59290
Iteration: 48054/59290
Iteration: 48055/59290
Iteration: 48056/59290
Iteration: 48057/59290
Iteration: 48058/59290
Iteration: 48059/59290
Iteration: 48060/59290
Iteration: 48061/59290
Iteration: 48062/59290
Iteration: 48063/59290
Iteration: 48064/59290
Iteration: 48065/59290
Iteration: 48066/59290
Iteration: 48067/59290
Iteration: 48068/59290
Iteration: 48069/59290
Iteration: 48070/59290
Iteration: 48071/59290
Iteration: 48072/59290

 81%|████████  | 48056/59290 [37:45<05:47, 32.36it/s]

Iteration: 48073/59290
Iteration: 48074/59290
Iteration: 48075/59290
Iteration: 48076/59290
Iteration: 48077/59290
Iteration: 48078/59290
Iteration: 48079/59290
Iteration: 48080/59290
Iteration: 48081/59290
Iteration: 48082/59290
Iteration: 48083/59290
Iteration: 48084/59290
Iteration: 48085/59290
Iteration: 48086/59290
Iteration: 48087/59290
Iteration: 48088/59290
Iteration: 48089/59290
Iteration: 48090/59290
Iteration: 48091/59290
Iteration: 48092/59290
Iteration: 48093/59290
Iteration: 48094/59290
Iteration: 48095/59290
Iteration: 48096/59290

 81%|████████  | 48080/59290 [37:46<04:54, 38.01it/s]

Iteration: 48097/59290
Iteration: 48098/59290
Iteration: 48099/59290
Iteration: 48100/59290
Iteration: 48101/59290
Iteration: 48102/59290
Iteration: 48103/59290
Iteration: 48104/59290
Iteration: 48105/59290
Iteration: 48106/59290
Iteration: 48107/59290
Iteration: 48108/59290
Iteration: 48109/59290
Iteration: 48110/59290
Iteration: 48111/59290
Iteration: 48112/59290
Iteration: 48113/59290
Iteration: 48114/59290
Iteration: 48115/59290
Iteration: 48116/59290
Iteration: 48117/59290
Iteration: 48118/59290
Iteration: 48119/59290
Iteration: 48120/59290

 81%|████████  | 48104/59290 [37:46<04:18, 43.19it/s]

Iteration: 48121/59290
Iteration: 48122/59290
Iteration: 48123/59290
Iteration: 48124/59290
Iteration: 48125/59290
Iteration: 48126/59290
Iteration: 48127/59290
Iteration: 48128/59290
Iteration: 48129/59290
Iteration: 48130/59290
Iteration: 48131/59290
Iteration: 48132/59290
Iteration: 48133/59290
Iteration: 48134/59290
Iteration: 48135/59290
Iteration: 48136/59290
Iteration: 48137/59290
Iteration: 48138/59290
Iteration: 48139/59290
Iteration: 48140/59290
Iteration: 48141/59290
Iteration: 48142/59290
Iteration: 48143/59290
Iteration: 48144/59290

 81%|████████  | 48128/59290 [37:47<03:54, 47.54it/s]

Iteration: 48145/59290
Iteration: 48146/59290
Iteration: 48147/59290
Iteration: 48148/59290
Iteration: 48149/59290
Iteration: 48150/59290
Iteration: 48151/59290
Iteration: 48152/59290
Iteration: 48153/59290
Iteration: 48154/59290
Iteration: 48155/59290
Iteration: 48156/59290
Iteration: 48157/59290
Iteration: 48158/59290
Iteration: 48159/59290
Iteration: 48160/59290
Iteration: 48161/59290
Iteration: 48162/59290
Iteration: 48163/59290
Iteration: 48164/59290
Iteration: 48165/59290
Iteration: 48166/59290
Iteration: 48167/59290
Iteration: 48168/59290

 81%|████████  | 48152/59290 [37:47<03:35, 51.58it/s]

Iteration: 48169/59290
Iteration: 48170/59290
Iteration: 48171/59290
Iteration: 48172/59290
Iteration: 48173/59290
Iteration: 48174/59290
Iteration: 48175/59290
Iteration: 48176/59290
Iteration: 48177/59290
Iteration: 48178/59290
Iteration: 48179/59290
Iteration: 48180/59290
Iteration: 48181/59290
Iteration: 48182/59290
Iteration: 48183/59290
Iteration: 48184/59290
Iteration: 48185/59290
Iteration: 48186/59290
Iteration: 48187/59290
Iteration: 48188/59290
Iteration: 48189/59290
Iteration: 48190/59290
Iteration: 48191/59290
Iteration: 48192/59290

 81%|████████▏ | 48176/59290 [37:47<03:24, 54.27it/s]

Iteration: 48193/59290
Iteration: 48194/59290
Iteration: 48195/59290
Iteration: 48196/59290
Iteration: 48197/59290
Iteration: 48198/59290
Iteration: 48199/59290
Iteration: 48200/59290
Iteration: 48201/59290
Iteration: 48202/59290
Iteration: 48203/59290
Iteration: 48204/59290
Iteration: 48205/59290
Iteration: 48206/59290
Iteration: 48207/59290
Iteration: 48208/59290
Iteration: 48209/59290
Iteration: 48210/59290
Iteration: 48211/59290
Iteration: 48212/59290
Iteration: 48213/59290
Iteration: 48214/59290
Iteration: 48215/59290
Iteration: 48216/59290

 81%|████████▏ | 48200/59290 [37:49<05:35, 33.03it/s]

Iteration: 48217/59290
Iteration: 48218/59290
Iteration: 48219/59290
Iteration: 48220/59290
Iteration: 48221/59290
Iteration: 48222/59290
Iteration: 48223/59290
Iteration: 48224/59290
Iteration: 48225/59290
Iteration: 48226/59290
Iteration: 48227/59290
Iteration: 48228/59290
Iteration: 48229/59290
Iteration: 48230/59290
Iteration: 48231/59290
Iteration: 48232/59290
Iteration: 48233/59290
Iteration: 48234/59290
Iteration: 48235/59290
Iteration: 48236/59290
Iteration: 48237/59290
Iteration: 48238/59290
Iteration: 48239/59290
Iteration: 48240/59290

 81%|████████▏ | 48224/59290 [37:51<10:26, 17.67it/s]

Iteration: 48241/59290
Iteration: 48242/59290
Iteration: 48243/59290
Iteration: 48244/59290
Iteration: 48245/59290
Iteration: 48246/59290
Iteration: 48247/59290
Iteration: 48248/59290
Iteration: 48249/59290
Iteration: 48250/59290
Iteration: 48251/59290
Iteration: 48252/59290
Iteration: 48253/59290
Iteration: 48254/59290
Iteration: 48255/59290
Iteration: 48256/59290
Iteration: 48257/59290
Iteration: 48258/59290
Iteration: 48259/59290
Iteration: 48260/59290
Iteration: 48261/59290
Iteration: 48262/59290
Iteration: 48263/59290
Iteration: 48264/59290

 81%|████████▏ | 48248/59290 [37:52<08:09, 22.55it/s]

Iteration: 48265/59290
Iteration: 48266/59290
Iteration: 48267/59290
Iteration: 48268/59290
Iteration: 48269/59290
Iteration: 48270/59290
Iteration: 48271/59290
Iteration: 48272/59290
Iteration: 48273/59290
Iteration: 48274/59290
Iteration: 48275/59290
Iteration: 48276/59290
Iteration: 48277/59290
Iteration: 48278/59290
Iteration: 48279/59290
Iteration: 48280/59290
Iteration: 48281/59290
Iteration: 48282/59290
Iteration: 48283/59290
Iteration: 48284/59290
Iteration: 48285/59290
Iteration: 48286/59290
Iteration: 48287/59290
Iteration: 48288/59290

 81%|████████▏ | 48272/59290 [37:52<06:34, 27.92it/s]

Iteration: 48289/59290
Iteration: 48290/59290
Iteration: 48291/59290
Iteration: 48292/59290
Iteration: 48293/59290
Iteration: 48294/59290
Iteration: 48295/59290
Iteration: 48296/59290
Iteration: 48297/59290
Iteration: 48298/59290
Iteration: 48299/59290
Iteration: 48300/59290
Iteration: 48301/59290
Iteration: 48302/59290
Iteration: 48303/59290
Iteration: 48304/59290
Iteration: 48305/59290
Iteration: 48306/59290
Iteration: 48307/59290
Iteration: 48308/59290
Iteration: 48309/59290
Iteration: 48310/59290
Iteration: 48311/59290
Iteration: 48312/59290

 81%|████████▏ | 48296/59290 [37:53<05:28, 33.51it/s]

Iteration: 48313/59290
Iteration: 48314/59290
Iteration: 48315/59290
Iteration: 48316/59290
Iteration: 48317/59290
Iteration: 48318/59290
Iteration: 48319/59290
Iteration: 48320/59290
Iteration: 48321/59290
Iteration: 48322/59290
Iteration: 48323/59290
Iteration: 48324/59290
Iteration: 48325/59290
Iteration: 48326/59290
Iteration: 48327/59290
Iteration: 48328/59290
Iteration: 48329/59290
Iteration: 48330/59290
Iteration: 48331/59290
Iteration: 48332/59290
Iteration: 48333/59290
Iteration: 48334/59290
Iteration: 48335/59290
Iteration: 48336/59290

 81%|████████▏ | 48320/59290 [37:53<04:43, 38.68it/s]

Iteration: 48337/59290
Iteration: 48338/59290
Iteration: 48339/59290
Iteration: 48340/59290
Iteration: 48341/59290
Iteration: 48342/59290
Iteration: 48343/59290
Iteration: 48344/59290
Iteration: 48345/59290
Iteration: 48346/59290
Iteration: 48347/59290
Iteration: 48348/59290
Iteration: 48349/59290
Iteration: 48350/59290
Iteration: 48351/59290
Iteration: 48352/59290
Iteration: 48353/59290
Iteration: 48354/59290
Iteration: 48355/59290
Iteration: 48356/59290
Iteration: 48357/59290
Iteration: 48358/59290
Iteration: 48359/59290
Iteration: 48360/59290

 82%|████████▏ | 48344/59290 [37:53<04:10, 43.77it/s]

Iteration: 48361/59290
Iteration: 48362/59290
Iteration: 48363/59290
Iteration: 48364/59290
Iteration: 48365/59290
Iteration: 48366/59290
Iteration: 48367/59290
Iteration: 48368/59290
Iteration: 48369/59290
Iteration: 48370/59290
Iteration: 48371/59290
Iteration: 48372/59290
Iteration: 48373/59290
Iteration: 48374/59290
Iteration: 48375/59290
Iteration: 48376/59290
Iteration: 48377/59290
Iteration: 48378/59290
Iteration: 48379/59290
Iteration: 48380/59290
Iteration: 48381/59290
Iteration: 48382/59290
Iteration: 48383/59290
Iteration: 48384/59290

 82%|████████▏ | 48368/59290 [37:54<03:46, 48.21it/s]

Iteration: 48385/59290
Iteration: 48386/59290
Iteration: 48387/59290
Iteration: 48388/59290
Iteration: 48389/59290
Iteration: 48390/59290
Iteration: 48391/59290
Iteration: 48392/59290
Iteration: 48393/59290
Iteration: 48394/59290
Iteration: 48395/59290
Iteration: 48396/59290
Iteration: 48397/59290
Iteration: 48398/59290
Iteration: 48399/59290
Iteration: 48400/59290
Iteration: 48401/59290
Iteration: 48402/59290
Iteration: 48403/59290
Iteration: 48404/59290
Iteration: 48405/59290
Iteration: 48406/59290
Iteration: 48407/59290
Iteration: 48408/59290

 82%|████████▏ | 48392/59290 [37:54<03:29, 51.98it/s]

Iteration: 48409/59290
Iteration: 48410/59290
Iteration: 48411/59290
Iteration: 48412/59290
Iteration: 48413/59290
Iteration: 48414/59290
Iteration: 48415/59290
Iteration: 48416/59290
Iteration: 48417/59290
Iteration: 48418/59290
Iteration: 48419/59290
Iteration: 48420/59290
Iteration: 48421/59290
Iteration: 48422/59290
Iteration: 48423/59290
Iteration: 48424/59290
Iteration: 48425/59290
Iteration: 48426/59290
Iteration: 48427/59290
Iteration: 48428/59290
Iteration: 48429/59290
Iteration: 48430/59290
Iteration: 48431/59290
Iteration: 48432/59290

 82%|████████▏ | 48416/59290 [37:55<03:17, 54.97it/s]

Iteration: 48433/59290
Iteration: 48434/59290
Iteration: 48435/59290
Iteration: 48436/59290
Iteration: 48437/59290
Iteration: 48438/59290
Iteration: 48439/59290
Iteration: 48440/59290
Iteration: 48441/59290
Iteration: 48442/59290
Iteration: 48443/59290
Iteration: 48444/59290
Iteration: 48445/59290
Iteration: 48446/59290
Iteration: 48447/59290
Iteration: 48448/59290
Iteration: 48449/59290
Iteration: 48450/59290
Iteration: 48451/59290
Iteration: 48452/59290
Iteration: 48453/59290
Iteration: 48454/59290
Iteration: 48455/59290
Iteration: 48456/59290

 82%|████████▏ | 48440/59290 [37:55<03:09, 57.20it/s]

Iteration: 48457/59290
Iteration: 48458/59290
Iteration: 48459/59290
Iteration: 48460/59290
Iteration: 48461/59290
Iteration: 48462/59290
Iteration: 48463/59290
Iteration: 48464/59290
Iteration: 48465/59290
Iteration: 48466/59290
Iteration: 48467/59290
Iteration: 48468/59290
Iteration: 48469/59290
Iteration: 48470/59290
Iteration: 48471/59290
Iteration: 48472/59290
Iteration: 48473/59290
Iteration: 48474/59290
Iteration: 48475/59290
Iteration: 48476/59290
Iteration: 48477/59290
Iteration: 48478/59290
Iteration: 48479/59290
Iteration: 48480/59290

 82%|████████▏ | 48464/59290 [37:56<05:40, 31.76it/s]

Iteration: 48481/59290
Iteration: 48482/59290
Iteration: 48483/59290
Iteration: 48484/59290
Iteration: 48485/59290
Iteration: 48486/59290
Iteration: 48487/59290
Iteration: 48488/59290
Iteration: 48489/59290
Iteration: 48490/59290
Iteration: 48491/59290
Iteration: 48492/59290
Iteration: 48493/59290
Iteration: 48494/59290
Iteration: 48495/59290
Iteration: 48496/59290
Iteration: 48497/59290
Iteration: 48498/59290
Iteration: 48499/59290
Iteration: 48500/59290
Iteration: 48501/59290
Iteration: 48502/59290
Iteration: 48503/59290
Iteration: 48504/59290

 82%|████████▏ | 48488/59290 [37:59<09:03, 19.86it/s]

Iteration: 48505/59290
Iteration: 48506/59290
Iteration: 48507/59290
Iteration: 48508/59290
Iteration: 48509/59290
Iteration: 48510/59290
Iteration: 48511/59290
Iteration: 48512/59290
Iteration: 48513/59290
Iteration: 48514/59290
Iteration: 48515/59290
Iteration: 48516/59290
Iteration: 48517/59290
Iteration: 48518/59290
Iteration: 48519/59290
Iteration: 48520/59290
Iteration: 48521/59290
Iteration: 48522/59290
Iteration: 48523/59290
Iteration: 48524/59290
Iteration: 48525/59290
Iteration: 48526/59290
Iteration: 48528/59290

 82%|████████▏ | 48511/59290 [38:00<08:18, 21.64it/s]

Iteration: 48529/59290
Iteration: 48530/59290
Iteration: 48531/59290
Iteration: 48532/59290
Iteration: 48533/59290
Iteration: 48534/59290
Iteration: 48535/59290
Iteration: 48536/59290

 82%|████████▏ | 48519/59290 [38:00<08:20, 21.53it/s]

Iteration: 48537/59290
Iteration: 48538/59290
Iteration: 48539/59290
Iteration: 48540/59290
Iteration: 48541/59290
Iteration: 48542/59290
Iteration: 48543/59290
Iteration: 48544/59290
Iteration: 48545/59290
Iteration: 48546/59290
Iteration: 48547/59290
Iteration: 48548/59290
Iteration: 48549/59290
Iteration: 48550/59290
Iteration: 48551/59290
Iteration: 48552/59290
Iteration: 48553/59290
Iteration: 48554/59290
Iteration: 48555/59290
Iteration: 48556/59290
Iteration: 48557/59290
Iteration: 48558/59290
Iteration: 48559/59290
Iteration: 48560/59290

 82%|████████▏ | 48543/59290 [38:00<06:22, 28.10it/s]

Iteration: 48561/59290
Iteration: 48562/59290
Iteration: 48563/59290
Iteration: 48564/59290
Iteration: 48565/59290
Iteration: 48566/59290
Iteration: 48567/59290
Iteration: 48568/59290
Iteration: 48569/59290
Iteration: 48570/59290
Iteration: 48571/59290
Iteration: 48572/59290
Iteration: 48573/59290
Iteration: 48574/59290
Iteration: 48575/59290
Iteration: 48576/59290
Iteration: 48577/59290
Iteration: 48578/59290
Iteration: 48579/59290
Iteration: 48580/59290
Iteration: 48581/59290
Iteration: 48582/59290
Iteration: 48583/59290
Iteration: 48584/59290

 82%|████████▏ | 48567/59290 [38:01<05:10, 34.52it/s]

Iteration: 48585/59290
Iteration: 48586/59290
Iteration: 48587/59290
Iteration: 48588/59290
Iteration: 48589/59290
Iteration: 48590/59290
Iteration: 48591/59290
Iteration: 48592/59290
Iteration: 48593/59290
Iteration: 48594/59290
Iteration: 48595/59290
Iteration: 48596/59290
Iteration: 48597/59290
Iteration: 48598/59290
Iteration: 48599/59290
Iteration: 48600/59290
Iteration: 48601/59290
Iteration: 48602/59290
Iteration: 48603/59290
Iteration: 48604/59290
Iteration: 48605/59290
Iteration: 48606/59290
Iteration: 48607/59290
Iteration: 48608/59290

 82%|████████▏ | 48591/59290 [38:01<04:24, 40.47it/s]

Iteration: 48609/59290
Iteration: 48610/59290
Iteration: 48611/59290
Iteration: 48612/59290
Iteration: 48613/59290
Iteration: 48614/59290
Iteration: 48615/59290
Iteration: 48616/59290
Iteration: 48617/59290
Iteration: 48618/59290
Iteration: 48619/59290
Iteration: 48620/59290
Iteration: 48621/59290
Iteration: 48622/59290
Iteration: 48623/59290
Iteration: 48624/59290
Iteration: 48625/59290
Iteration: 48626/59290
Iteration: 48627/59290
Iteration: 48628/59290
Iteration: 48629/59290
Iteration: 48630/59290
Iteration: 48631/59290
Iteration: 48632/59290

 82%|████████▏ | 48615/59290 [38:01<03:52, 45.86it/s]

Iteration: 48633/59290
Iteration: 48634/59290
Iteration: 48635/59290
Iteration: 48636/59290
Iteration: 48637/59290
Iteration: 48638/59290
Iteration: 48639/59290
Iteration: 48640/59290
Iteration: 48641/59290
Iteration: 48642/59290
Iteration: 48643/59290
Iteration: 48644/59290
Iteration: 48645/59290
Iteration: 48646/59290
Iteration: 48647/59290
Iteration: 48648/59290
Iteration: 48649/59290
Iteration: 48650/59290
Iteration: 48651/59290
Iteration: 48652/59290
Iteration: 48653/59290
Iteration: 48654/59290
Iteration: 48655/59290
Iteration: 48656/59290

 82%|████████▏ | 48639/59290 [38:02<03:34, 49.72it/s]

Iteration: 48657/59290
Iteration: 48658/59290
Iteration: 48659/59290
Iteration: 48660/59290
Iteration: 48661/59290
Iteration: 48662/59290
Iteration: 48663/59290
Iteration: 48664/59290
Iteration: 48665/59290
Iteration: 48666/59290
Iteration: 48667/59290
Iteration: 48668/59290
Iteration: 48669/59290
Iteration: 48670/59290
Iteration: 48671/59290
Iteration: 48672/59290
Iteration: 48673/59290
Iteration: 48674/59290
Iteration: 48675/59290
Iteration: 48676/59290
Iteration: 48677/59290
Iteration: 48678/59290
Iteration: 48679/59290
Iteration: 48680/59290

 82%|████████▏ | 48663/59290 [38:03<05:48, 30.52it/s]

Iteration: 48681/59290
Iteration: 48682/59290
Iteration: 48683/59290
Iteration: 48684/59290
Iteration: 48685/59290
Iteration: 48686/59290
Iteration: 48687/59290
Iteration: 48688/59290
Iteration: 48689/59290
Iteration: 48690/59290
Iteration: 48691/59290
Iteration: 48692/59290
Iteration: 48693/59290
Iteration: 48694/59290
Iteration: 48695/59290
Iteration: 48696/59290
Iteration: 48697/59290
Iteration: 48698/59290
Iteration: 48699/59290
Iteration: 48700/59290
Iteration: 48701/59290
Iteration: 48702/59290
Iteration: 48703/59290
Iteration: 48704/59290

 82%|████████▏ | 48687/59290 [38:06<09:13, 19.16it/s]

Iteration: 48705/59290
Iteration: 48706/59290
Iteration: 48707/59290
Iteration: 48708/59290
Iteration: 48709/59290
Iteration: 48710/59290
Iteration: 48711/59290
Iteration: 48712/59290
Iteration: 48713/59290
Iteration: 48714/59290
Iteration: 48715/59290
Iteration: 48716/59290
Iteration: 48717/59290
Iteration: 48718/59290
Iteration: 48719/59290
Iteration: 48720/59290
Iteration: 48721/59290
Iteration: 48722/59290
Iteration: 48723/59290
Iteration: 48724/59290
Iteration: 48725/59290
Iteration: 48726/59290
Iteration: 48727/59290
Iteration: 48728/59290

 82%|████████▏ | 48711/59290 [38:06<07:46, 22.66it/s]

Iteration: 48729/59290
Iteration: 48730/59290
Iteration: 48731/59290
Iteration: 48732/59290
Iteration: 48733/59290
Iteration: 48734/59290
Iteration: 48735/59290
Iteration: 48736/59290
Iteration: 48737/59290
Iteration: 48738/59290
Iteration: 48739/59290
Iteration: 48740/59290
Iteration: 48741/59290
Iteration: 48742/59290
Iteration: 48743/59290
Iteration: 48744/59290
Iteration: 48745/59290
Iteration: 48746/59290
Iteration: 48747/59290
Iteration: 48748/59290
Iteration: 48749/59290
Iteration: 48750/59290
Iteration: 48751/59290
Iteration: 48752/59290

 82%|████████▏ | 48735/59290 [38:07<06:14, 28.16it/s]

Iteration: 48753/59290
Iteration: 48754/59290
Iteration: 48755/59290
Iteration: 48756/59290
Iteration: 48757/59290
Iteration: 48758/59290
Iteration: 48759/59290
Iteration: 48760/59290
Iteration: 48761/59290
Iteration: 48762/59290
Iteration: 48763/59290
Iteration: 48764/59290
Iteration: 48765/59290
Iteration: 48766/59290
Iteration: 48767/59290
Iteration: 48768/59290
Iteration: 48769/59290
Iteration: 48770/59290
Iteration: 48771/59290
Iteration: 48772/59290
Iteration: 48773/59290
Iteration: 48774/59290
Iteration: 48775/59290
Iteration: 48776/59290

 82%|████████▏ | 48759/59290 [38:07<05:11, 33.83it/s]

Iteration: 48777/59290
Iteration: 48778/59290
Iteration: 48779/59290
Iteration: 48780/59290
Iteration: 48781/59290
Iteration: 48782/59290
Iteration: 48783/59290
Iteration: 48784/59290
Iteration: 48785/59290
Iteration: 48786/59290
Iteration: 48787/59290
Iteration: 48788/59290
Iteration: 48789/59290
Iteration: 48790/59290
Iteration: 48791/59290
Iteration: 48792/59290
Iteration: 48793/59290
Iteration: 48794/59290
Iteration: 48795/59290
Iteration: 48796/59290
Iteration: 48797/59290
Iteration: 48798/59290
Iteration: 48799/59290
Iteration: 48800/59290

 82%|████████▏ | 48783/59290 [38:07<04:26, 39.39it/s]

Iteration: 48801/59290
Iteration: 48802/59290
Iteration: 48803/59290
Iteration: 48804/59290
Iteration: 48805/59290
Iteration: 48806/59290
Iteration: 48807/59290
Iteration: 48808/59290
Iteration: 48809/59290
Iteration: 48810/59290
Iteration: 48811/59290
Iteration: 48812/59290
Iteration: 48813/59290
Iteration: 48814/59290
Iteration: 48815/59290
Iteration: 48816/59290
Iteration: 48817/59290
Iteration: 48818/59290
Iteration: 48819/59290
Iteration: 48820/59290
Iteration: 48821/59290
Iteration: 48822/59290
Iteration: 48823/59290
Iteration: 48824/59290

 82%|████████▏ | 48807/59290 [38:09<06:08, 28.42it/s]

Iteration: 48825/59290
Iteration: 48826/59290
Iteration: 48827/59290
Iteration: 48828/59290
Iteration: 48829/59290
Iteration: 48830/59290
Iteration: 48831/59290
Iteration: 48832/59290
Iteration: 48833/59290
Iteration: 48834/59290
Iteration: 48835/59290
Iteration: 48836/59290
Iteration: 48837/59290
Iteration: 48838/59290
Iteration: 48839/59290
Iteration: 48840/59290
Iteration: 48841/59290
Iteration: 48842/59290
Iteration: 48843/59290
Iteration: 48844/59290
Iteration: 48845/59290
Iteration: 48846/59290
Iteration: 48847/59290
Iteration: 48848/59290

 82%|████████▏ | 48831/59290 [38:12<10:24, 16.75it/s]

Iteration: 48849/59290
Iteration: 48850/59290
Iteration: 48851/59290
Iteration: 48852/59290
Iteration: 48853/59290
Iteration: 48854/59290
Iteration: 48855/59290
Iteration: 48856/59290
Iteration: 48857/59290
Iteration: 48858/59290
Iteration: 48859/59290
Iteration: 48860/59290
Iteration: 48861/59290
Iteration: 48862/59290
Iteration: 48863/59290
Iteration: 48864/59290
Iteration: 48865/59290
Iteration: 48866/59290
Iteration: 48867/59290
Iteration: 48868/59290
Iteration: 48869/59290
Iteration: 48870/59290
Iteration: 48871/59290
Iteration: 48872/59290

 82%|████████▏ | 48855/59290 [38:12<08:06, 21.44it/s]

Iteration: 48873/59290
Iteration: 48874/59290
Iteration: 48875/59290
Iteration: 48876/59290
Iteration: 48877/59290
Iteration: 48878/59290
Iteration: 48879/59290
Iteration: 48880/59290
Iteration: 48881/59290
Iteration: 48882/59290
Iteration: 48883/59290
Iteration: 48884/59290
Iteration: 48885/59290
Iteration: 48886/59290
Iteration: 48887/59290
Iteration: 48888/59290
Iteration: 48889/59290
Iteration: 48890/59290
Iteration: 48891/59290
Iteration: 48892/59290
Iteration: 48893/59290
Iteration: 48894/59290
Iteration: 48895/59290
Iteration: 48896/59290

 82%|████████▏ | 48879/59290 [38:12<06:30, 26.66it/s]

Iteration: 48897/59290
Iteration: 48898/59290
Iteration: 48899/59290
Iteration: 48900/59290
Iteration: 48901/59290
Iteration: 48902/59290
Iteration: 48903/59290
Iteration: 48904/59290
Iteration: 48905/59290
Iteration: 48906/59290
Iteration: 48907/59290
Iteration: 48908/59290
Iteration: 48909/59290
Iteration: 48910/59290
Iteration: 48911/59290
Iteration: 48912/59290
Iteration: 48913/59290
Iteration: 48914/59290
Iteration: 48915/59290
Iteration: 48916/59290
Iteration: 48917/59290
Iteration: 48918/59290
Iteration: 48919/59290
Iteration: 48920/59290

 82%|████████▏ | 48903/59290 [38:14<08:00, 21.63it/s]

Iteration: 48921/59290
Iteration: 48922/59290
Iteration: 48923/59290
Iteration: 48924/59290
Iteration: 48925/59290
Iteration: 48926/59290
Iteration: 48927/59290
Iteration: 48928/59290
Iteration: 48929/59290
Iteration: 48930/59290
Iteration: 48931/59290
Iteration: 48932/59290
Iteration: 48933/59290
Iteration: 48934/59290
Iteration: 48935/59290
Iteration: 48936/59290
Iteration: 48937/59290
Iteration: 48938/59290
Iteration: 48939/59290
Iteration: 48940/59290
Iteration: 48941/59290
Iteration: 48942/59290
Iteration: 48943/59290
Iteration: 48944/59290

 83%|████████▎ | 48927/59290 [38:17<11:34, 14.92it/s]

Iteration: 48945/59290
Iteration: 48946/59290
Iteration: 48947/59290
Iteration: 48948/59290
Iteration: 48949/59290
Iteration: 48950/59290
Iteration: 48951/59290
Iteration: 48952/59290
Iteration: 48953/59290
Iteration: 48954/59290
Iteration: 48955/59290
Iteration: 48956/59290
Iteration: 48957/59290
Iteration: 48958/59290
Iteration: 48959/59290
Iteration: 48960/59290
Iteration: 48961/59290
Iteration: 48962/59290
Iteration: 48963/59290
Iteration: 48964/59290
Iteration: 48965/59290
Iteration: 48966/59290
Iteration: 48967/59290
Iteration: 48968/59290

 83%|████████▎ | 48951/59290 [38:17<08:53, 19.39it/s]

Iteration: 48969/59290
Iteration: 48970/59290
Iteration: 48971/59290
Iteration: 48972/59290
Iteration: 48973/59290
Iteration: 48974/59290
Iteration: 48975/59290
Iteration: 48976/59290
Iteration: 48977/59290
Iteration: 48978/59290
Iteration: 48979/59290
Iteration: 48980/59290
Iteration: 48981/59290
Iteration: 48982/59290
Iteration: 48983/59290
Iteration: 48984/59290
Iteration: 48985/59290
Iteration: 48986/59290
Iteration: 48987/59290
Iteration: 48988/59290
Iteration: 48989/59290
Iteration: 48990/59290
Iteration: 48991/59290
Iteration: 48992/59290

 83%|████████▎ | 48975/59290 [38:17<07:02, 24.42it/s]

Iteration: 48993/59290
Iteration: 48994/59290
Iteration: 48995/59290
Iteration: 48996/59290
Iteration: 48997/59290
Iteration: 48998/59290
Iteration: 48999/59290
Iteration: 49000/59290
Iteration: 49001/59290
Iteration: 49002/59290
Iteration: 49003/59290
Iteration: 49004/59290
Iteration: 49005/59290
Iteration: 49006/59290
Iteration: 49007/59290
Iteration: 49008/59290
Iteration: 49009/59290
Iteration: 49010/59290
Iteration: 49011/59290
Iteration: 49012/59290
Iteration: 49013/59290
Iteration: 49014/59290
Iteration: 49015/59290
Iteration: 49016/59290

 83%|████████▎ | 48999/59290 [38:18<05:44, 29.84it/s]

Iteration: 49017/59290
Iteration: 49018/59290
Iteration: 49019/59290
Iteration: 49020/59290
Iteration: 49021/59290
Iteration: 49022/59290
Iteration: 49023/59290
Iteration: 49024/59290
Iteration: 49025/59290
Iteration: 49026/59290
Iteration: 49027/59290
Iteration: 49028/59290
Iteration: 49029/59290
Iteration: 49030/59290
Iteration: 49031/59290
Iteration: 49032/59290
Iteration: 49033/59290
Iteration: 49034/59290
Iteration: 49035/59290
Iteration: 49036/59290
Iteration: 49037/59290
Iteration: 49038/59290
Iteration: 49039/59290
Iteration: 49040/59290

 83%|████████▎ | 49023/59290 [38:18<04:49, 35.46it/s]

Iteration: 49041/59290
Iteration: 49042/59290
Iteration: 49043/59290
Iteration: 49044/59290
Iteration: 49045/59290
Iteration: 49046/59290
Iteration: 49047/59290
Iteration: 49048/59290
Iteration: 49049/59290
Iteration: 49050/59290
Iteration: 49051/59290
Iteration: 49052/59290
Iteration: 49053/59290
Iteration: 49054/59290
Iteration: 49055/59290
Iteration: 49056/59290
Iteration: 49057/59290
Iteration: 49058/59290
Iteration: 49059/59290
Iteration: 49060/59290
Iteration: 49061/59290
Iteration: 49062/59290
Iteration: 49063/59290
Iteration: 49064/59290

 83%|████████▎ | 49047/59290 [38:19<04:10, 40.85it/s]

Iteration: 49065/59290
Iteration: 49066/59290
Iteration: 49067/59290
Iteration: 49068/59290
Iteration: 49069/59290
Iteration: 49070/59290
Iteration: 49071/59290
Iteration: 49072/59290
Iteration: 49073/59290
Iteration: 49074/59290
Iteration: 49075/59290
Iteration: 49076/59290
Iteration: 49077/59290
Iteration: 49078/59290
Iteration: 49079/59290
Iteration: 49080/59290
Iteration: 49081/59290
Iteration: 49082/59290
Iteration: 49083/59290
Iteration: 49084/59290
Iteration: 49085/59290
Iteration: 49086/59290
Iteration: 49087/59290
Iteration: 49088/59290

 83%|████████▎ | 49071/59290 [38:20<06:31, 26.09it/s]

Iteration: 49089/59290
Iteration: 49090/59290
Iteration: 49091/59290
Iteration: 49092/59290
Iteration: 49093/59290
Iteration: 49094/59290
Iteration: 49095/59290
Iteration: 49096/59290
Iteration: 49097/59290
Iteration: 49098/59290
Iteration: 49099/59290
Iteration: 49100/59290
Iteration: 49101/59290
Iteration: 49102/59290
Iteration: 49103/59290
Iteration: 49104/59290
Iteration: 49105/59290
Iteration: 49106/59290
Iteration: 49107/59290
Iteration: 49108/59290
Iteration: 49109/59290
Iteration: 49110/59290
Iteration: 49111/59290
Iteration: 49112/59290

 83%|████████▎ | 49095/59290 [38:23<10:40, 15.92it/s]

Iteration: 49113/59290
Iteration: 49114/59290
Iteration: 49115/59290
Iteration: 49116/59290
Iteration: 49117/59290
Iteration: 49118/59290
Iteration: 49119/59290
Iteration: 49120/59290
Iteration: 49121/59290
Iteration: 49122/59290
Iteration: 49123/59290
Iteration: 49124/59290
Iteration: 49125/59290
Iteration: 49126/59290
Iteration: 49127/59290
Iteration: 49128/59290
Iteration: 49129/59290
Iteration: 49130/59290
Iteration: 49131/59290
Iteration: 49132/59290
Iteration: 49133/59290
Iteration: 49134/59290
Iteration: 49135/59290
Iteration: 49136/59290

 83%|████████▎ | 49119/59290 [38:24<08:16, 20.48it/s]

Iteration: 49137/59290
Iteration: 49138/59290
Iteration: 49139/59290
Iteration: 49140/59290
Iteration: 49141/59290
Iteration: 49142/59290
Iteration: 49143/59290
Iteration: 49144/59290
Iteration: 49145/59290
Iteration: 49146/59290
Iteration: 49147/59290
Iteration: 49148/59290
Iteration: 49149/59290
Iteration: 49150/59290
Iteration: 49151/59290
Iteration: 49152/59290
Iteration: 49153/59290
Iteration: 49154/59290
Iteration: 49155/59290
Iteration: 49156/59290
Iteration: 49157/59290
Iteration: 49158/59290
Iteration: 49159/59290
Iteration: 49160/59290

 83%|████████▎ | 49143/59290 [38:24<06:34, 25.69it/s]

Iteration: 49161/59290
Iteration: 49162/59290
Iteration: 49163/59290
Iteration: 49164/59290
Iteration: 49165/59290
Iteration: 49166/59290
Iteration: 49167/59290
Iteration: 49168/59290
Iteration: 49169/59290
Iteration: 49170/59290
Iteration: 49171/59290
Iteration: 49172/59290
Iteration: 49173/59290
Iteration: 49174/59290
Iteration: 49175/59290
Iteration: 49176/59290
Iteration: 49177/59290
Iteration: 49178/59290
Iteration: 49179/59290
Iteration: 49180/59290
Iteration: 49181/59290
Iteration: 49182/59290
Iteration: 49183/59290
Iteration: 49184/59290

 83%|████████▎ | 49167/59290 [38:24<05:27, 30.95it/s]

Iteration: 49185/59290
Iteration: 49186/59290
Iteration: 49187/59290
Iteration: 49188/59290
Iteration: 49189/59290
Iteration: 49190/59290
Iteration: 49191/59290
Iteration: 49192/59290
Iteration: 49193/59290
Iteration: 49194/59290
Iteration: 49195/59290
Iteration: 49196/59290
Iteration: 49197/59290
Iteration: 49198/59290
Iteration: 49199/59290
Iteration: 49200/59290
Iteration: 49201/59290
Iteration: 49202/59290
Iteration: 49203/59290
Iteration: 49204/59290
Iteration: 49205/59290
Iteration: 49206/59290
Iteration: 49207/59290
Iteration: 49208/59290

 83%|████████▎ | 49191/59290 [38:25<04:35, 36.67it/s]

Iteration: 49209/59290
Iteration: 49210/59290
Iteration: 49211/59290
Iteration: 49212/59290
Iteration: 49213/59290
Iteration: 49214/59290
Iteration: 49215/59290
Iteration: 49216/59290
Iteration: 49217/59290
Iteration: 49218/59290
Iteration: 49219/59290
Iteration: 49220/59290
Iteration: 49221/59290
Iteration: 49222/59290
Iteration: 49223/59290
Iteration: 49224/59290
Iteration: 49225/59290
Iteration: 49226/59290
Iteration: 49227/59290
Iteration: 49228/59290
Iteration: 49229/59290
Iteration: 49230/59290
Iteration: 49231/59290
Iteration: 49232/59290

 83%|████████▎ | 49215/59290 [38:25<04:01, 41.76it/s]

Iteration: 49233/59290
Iteration: 49234/59290
Iteration: 49235/59290
Iteration: 49236/59290
Iteration: 49237/59290
Iteration: 49238/59290
Iteration: 49239/59290
Iteration: 49240/59290
Iteration: 49241/59290
Iteration: 49242/59290
Iteration: 49243/59290
Iteration: 49244/59290
Iteration: 49245/59290
Iteration: 49246/59290
Iteration: 49247/59290
Iteration: 49248/59290
Iteration: 49249/59290
Iteration: 49250/59290
Iteration: 49251/59290
Iteration: 49252/59290
Iteration: 49253/59290
Iteration: 49254/59290
Iteration: 49255/59290
Iteration: 49256/59290

 83%|████████▎ | 49239/59290 [38:26<03:36, 46.53it/s]

Iteration: 49257/59290
Iteration: 49258/59290
Iteration: 49259/59290
Iteration: 49260/59290
Iteration: 49261/59290
Iteration: 49262/59290
Iteration: 49263/59290
Iteration: 49264/59290
Iteration: 49265/59290
Iteration: 49266/59290
Iteration: 49267/59290
Iteration: 49268/59290
Iteration: 49269/59290
Iteration: 49270/59290
Iteration: 49271/59290
Iteration: 49272/59290
Iteration: 49273/59290
Iteration: 49274/59290
Iteration: 49275/59290
Iteration: 49276/59290
Iteration: 49277/59290
Iteration: 49278/59290
Iteration: 49279/59290
Iteration: 49280/59290

 83%|████████▎ | 49263/59290 [38:26<03:22, 49.46it/s]

Iteration: 49281/59290
Iteration: 49282/59290
Iteration: 49283/59290
Iteration: 49284/59290
Iteration: 49285/59290
Iteration: 49286/59290
Iteration: 49287/59290
Iteration: 49288/59290
Iteration: 49289/59290
Iteration: 49290/59290
Iteration: 49291/59290
Iteration: 49292/59290
Iteration: 49293/59290
Iteration: 49294/59290
Iteration: 49295/59290
Iteration: 49296/59290
Iteration: 49297/59290
Iteration: 49298/59290
Iteration: 49299/59290
Iteration: 49300/59290
Iteration: 49301/59290
Iteration: 49302/59290
Iteration: 49303/59290
Iteration: 49304/59290

 83%|████████▎ | 49287/59290 [38:26<03:11, 52.18it/s]

Iteration: 49305/59290
Iteration: 49306/59290
Iteration: 49307/59290
Iteration: 49308/59290
Iteration: 49309/59290
Iteration: 49310/59290
Iteration: 49311/59290
Iteration: 49312/59290
Iteration: 49313/59290
Iteration: 49314/59290
Iteration: 49315/59290
Iteration: 49316/59290
Iteration: 49317/59290
Iteration: 49318/59290
Iteration: 49319/59290
Iteration: 49320/59290
Iteration: 49321/59290
Iteration: 49322/59290
Iteration: 49323/59290
Iteration: 49324/59290
Iteration: 49325/59290
Iteration: 49326/59290
Iteration: 49327/59290
Iteration: 49328/59290

 83%|████████▎ | 49311/59290 [38:28<04:52, 34.16it/s]

Iteration: 49329/59290
Iteration: 49330/59290
Iteration: 49331/59290
Iteration: 49332/59290
Iteration: 49333/59290
Iteration: 49334/59290
Iteration: 49335/59290
Iteration: 49336/59290
Iteration: 49337/59290
Iteration: 49338/59290
Iteration: 49339/59290
Iteration: 49340/59290
Iteration: 49341/59290
Iteration: 49342/59290
Iteration: 49343/59290
Iteration: 49344/59290
Iteration: 49345/59290
Iteration: 49346/59290
Iteration: 49347/59290
Iteration: 49348/59290
Iteration: 49349/59290
Iteration: 49350/59290
Iteration: 49351/59290
Iteration: 49352/59290

 83%|████████▎ | 49335/59290 [38:30<09:15, 17.93it/s]

Iteration: 49353/59290
Iteration: 49354/59290
Iteration: 49355/59290
Iteration: 49356/59290
Iteration: 49357/59290
Iteration: 49358/59290
Iteration: 49359/59290
Iteration: 49360/59290
Iteration: 49361/59290
Iteration: 49362/59290
Iteration: 49363/59290
Iteration: 49364/59290
Iteration: 49365/59290
Iteration: 49366/59290
Iteration: 49367/59290
Iteration: 49368/59290
Iteration: 49369/59290
Iteration: 49370/59290
Iteration: 49371/59290
Iteration: 49372/59290
Iteration: 49373/59290
Iteration: 49374/59290
Iteration: 49375/59290
Iteration: 49376/59290

 83%|████████▎ | 49359/59290 [38:31<07:18, 22.66it/s]

Iteration: 49377/59290
Iteration: 49378/59290
Iteration: 49379/59290
Iteration: 49380/59290
Iteration: 49381/59290
Iteration: 49382/59290
Iteration: 49383/59290
Iteration: 49384/59290
Iteration: 49385/59290
Iteration: 49386/59290
Iteration: 49387/59290
Iteration: 49388/59290
Iteration: 49389/59290
Iteration: 49390/59290
Iteration: 49391/59290
Iteration: 49392/59290
Iteration: 49393/59290
Iteration: 49394/59290
Iteration: 49395/59290
Iteration: 49396/59290
Iteration: 49397/59290
Iteration: 49398/59290
Iteration: 49399/59290
Iteration: 49400/59290

 83%|████████▎ | 49383/59290 [38:31<05:53, 28.00it/s]

Iteration: 49401/59290
Iteration: 49402/59290
Iteration: 49403/59290
Iteration: 49404/59290
Iteration: 49405/59290
Iteration: 49406/59290
Iteration: 49407/59290
Iteration: 49408/59290
Iteration: 49409/59290
Iteration: 49410/59290
Iteration: 49411/59290
Iteration: 49412/59290
Iteration: 49413/59290
Iteration: 49414/59290
Iteration: 49415/59290
Iteration: 49416/59290
Iteration: 49417/59290
Iteration: 49418/59290
Iteration: 49419/59290
Iteration: 49420/59290
Iteration: 49421/59290
Iteration: 49422/59290
Iteration: 49423/59290
Iteration: 49424/59290

 83%|████████▎ | 49407/59290 [38:32<04:53, 33.65it/s]

Iteration: 49425/59290
Iteration: 49426/59290
Iteration: 49427/59290
Iteration: 49428/59290
Iteration: 49429/59290
Iteration: 49430/59290
Iteration: 49431/59290
Iteration: 49432/59290
Iteration: 49433/59290
Iteration: 49434/59290
Iteration: 49435/59290
Iteration: 49436/59290
Iteration: 49437/59290
Iteration: 49438/59290
Iteration: 49439/59290
Iteration: 49440/59290
Iteration: 49441/59290
Iteration: 49442/59290
Iteration: 49443/59290
Iteration: 49444/59290
Iteration: 49445/59290
Iteration: 49446/59290
Iteration: 49447/59290
Iteration: 49448/59290

 83%|████████▎ | 49431/59290 [38:32<04:11, 39.20it/s]

Iteration: 49449/59290
Iteration: 49450/59290
Iteration: 49451/59290
Iteration: 49452/59290
Iteration: 49453/59290
Iteration: 49454/59290
Iteration: 49455/59290
Iteration: 49456/59290
Iteration: 49457/59290
Iteration: 49458/59290
Iteration: 49459/59290
Iteration: 49460/59290
Iteration: 49461/59290
Iteration: 49462/59290
Iteration: 49463/59290
Iteration: 49464/59290
Iteration: 49465/59290
Iteration: 49466/59290
Iteration: 49467/59290
Iteration: 49468/59290
Iteration: 49469/59290
Iteration: 49470/59290
Iteration: 49471/59290
Iteration: 49472/59290

 83%|████████▎ | 49455/59290 [38:32<03:45, 43.63it/s]

Iteration: 49473/59290
Iteration: 49474/59290
Iteration: 49475/59290
Iteration: 49476/59290
Iteration: 49477/59290
Iteration: 49478/59290
Iteration: 49479/59290
Iteration: 49480/59290
Iteration: 49481/59290
Iteration: 49482/59290
Iteration: 49483/59290
Iteration: 49484/59290
Iteration: 49485/59290
Iteration: 49486/59290
Iteration: 49487/59290
Iteration: 49488/59290
Iteration: 49489/59290
Iteration: 49490/59290
Iteration: 49491/59290
Iteration: 49492/59290
Iteration: 49493/59290
Iteration: 49494/59290
Iteration: 49495/59290
Iteration: 49496/59290

 83%|████████▎ | 49479/59290 [38:33<03:28, 47.17it/s]

Iteration: 49497/59290
Iteration: 49498/59290
Iteration: 49499/59290
Iteration: 49500/59290
Iteration: 49501/59290
Iteration: 49502/59290
Iteration: 49503/59290
Iteration: 49504/59290
Iteration: 49505/59290
Iteration: 49506/59290
Iteration: 49507/59290
Iteration: 49508/59290
Iteration: 49509/59290
Iteration: 49510/59290
Iteration: 49511/59290
Iteration: 49512/59290
Iteration: 49513/59290
Iteration: 49514/59290
Iteration: 49515/59290
Iteration: 49516/59290
Iteration: 49517/59290
Iteration: 49518/59290
Iteration: 49519/59290
Iteration: 49520/59290

 83%|████████▎ | 49503/59290 [38:34<05:05, 32.04it/s]

Iteration: 49521/59290
Iteration: 49522/59290
Iteration: 49523/59290
Iteration: 49524/59290
Iteration: 49525/59290
Iteration: 49526/59290
Iteration: 49527/59290
Iteration: 49528/59290
Iteration: 49529/59290
Iteration: 49530/59290
Iteration: 49531/59290
Iteration: 49532/59290
Iteration: 49533/59290
Iteration: 49534/59290
Iteration: 49535/59290
Iteration: 49536/59290
Iteration: 49537/59290
Iteration: 49538/59290
Iteration: 49539/59290
Iteration: 49540/59290
Iteration: 49541/59290
Iteration: 49542/59290
Iteration: 49543/59290
Iteration: 49544/59290

 84%|████████▎ | 49527/59290 [38:36<08:25, 19.30it/s]

Iteration: 49545/59290
Iteration: 49546/59290
Iteration: 49547/59290
Iteration: 49548/59290
Iteration: 49549/59290
Iteration: 49550/59290
Iteration: 49551/59290
Iteration: 49552/59290
Iteration: 49553/59290
Iteration: 49554/59290
Iteration: 49555/59290
Iteration: 49556/59290
Iteration: 49557/59290
Iteration: 49558/59290
Iteration: 49559/59290
Iteration: 49560/59290
Iteration: 49561/59290
Iteration: 49562/59290
Iteration: 49563/59290
Iteration: 49564/59290
Iteration: 49565/59290
Iteration: 49566/59290
Iteration: 49567/59290
Iteration: 49568/59290

 84%|████████▎ | 49551/59290 [38:37<07:03, 23.02it/s]

Iteration: 49569/59290
Iteration: 49570/59290
Iteration: 49571/59290
Iteration: 49572/59290
Iteration: 49573/59290
Iteration: 49574/59290
Iteration: 49575/59290
Iteration: 49576/59290
Iteration: 49577/59290
Iteration: 49578/59290
Iteration: 49579/59290
Iteration: 49580/59290
Iteration: 49581/59290
Iteration: 49582/59290
Iteration: 49583/59290
Iteration: 49584/59290
Iteration: 49585/59290
Iteration: 49586/59290
Iteration: 49587/59290
Iteration: 49588/59290
Iteration: 49589/59290
Iteration: 49590/59290
Iteration: 49591/59290
Iteration: 49592/59290

 84%|████████▎ | 49575/59290 [38:37<05:41, 28.47it/s]

Iteration: 49593/59290
Iteration: 49594/59290
Iteration: 49595/59290
Iteration: 49596/59290
Iteration: 49597/59290
Iteration: 49598/59290
Iteration: 49599/59290
Iteration: 49600/59290
Iteration: 49601/59290
Iteration: 49602/59290
Iteration: 49603/59290
Iteration: 49604/59290
Iteration: 49605/59290
Iteration: 49606/59290
Iteration: 49607/59290
Iteration: 49608/59290
Iteration: 49609/59290
Iteration: 49610/59290
Iteration: 49611/59290
Iteration: 49612/59290
Iteration: 49613/59290
Iteration: 49614/59290
Iteration: 49615/59290
Iteration: 49616/59290

 84%|████████▎ | 49599/59290 [38:38<04:44, 34.12it/s]

Iteration: 49617/59290
Iteration: 49618/59290
Iteration: 49619/59290
Iteration: 49620/59290
Iteration: 49621/59290
Iteration: 49622/59290
Iteration: 49623/59290
Iteration: 49624/59290
Iteration: 49625/59290
Iteration: 49626/59290
Iteration: 49627/59290
Iteration: 49628/59290
Iteration: 49629/59290
Iteration: 49630/59290
Iteration: 49631/59290
Iteration: 49632/59290
Iteration: 49633/59290
Iteration: 49634/59290
Iteration: 49635/59290
Iteration: 49636/59290
Iteration: 49637/59290
Iteration: 49638/59290
Iteration: 49639/59290
Iteration: 49640/59290

 84%|████████▎ | 49623/59290 [38:38<04:04, 39.52it/s]

Iteration: 49641/59290
Iteration: 49642/59290
Iteration: 49643/59290
Iteration: 49644/59290
Iteration: 49645/59290
Iteration: 49646/59290
Iteration: 49647/59290
Iteration: 49648/59290
Iteration: 49649/59290
Iteration: 49650/59290
Iteration: 49651/59290
Iteration: 49652/59290
Iteration: 49653/59290
Iteration: 49654/59290
Iteration: 49655/59290
Iteration: 49656/59290
Iteration: 49657/59290
Iteration: 49658/59290
Iteration: 49659/59290
Iteration: 49660/59290
Iteration: 49661/59290
Iteration: 49662/59290
Iteration: 49663/59290
Iteration: 49664/59290

 84%|████████▎ | 49647/59290 [38:40<06:01, 26.66it/s]

Iteration: 49665/59290
Iteration: 49666/59290
Iteration: 49667/59290
Iteration: 49668/59290
Iteration: 49669/59290
Iteration: 49670/59290
Iteration: 49671/59290
Iteration: 49672/59290
Iteration: 49673/59290
Iteration: 49674/59290
Iteration: 49675/59290
Iteration: 49676/59290
Iteration: 49677/59290
Iteration: 49678/59290
Iteration: 49679/59290
Iteration: 49680/59290
Iteration: 49681/59290
Iteration: 49682/59290
Iteration: 49683/59290
Iteration: 49684/59290
Iteration: 49685/59290
Iteration: 49686/59290
Iteration: 49687/59290
Iteration: 49688/59290

 84%|████████▍ | 49671/59290 [38:42<08:52, 18.05it/s]

Iteration: 49689/59290
Iteration: 49690/59290
Iteration: 49691/59290
Iteration: 49692/59290
Iteration: 49693/59290
Iteration: 49694/59290
Iteration: 49695/59290
Iteration: 49696/59290
Iteration: 49697/59290
Iteration: 49698/59290
Iteration: 49699/59290
Iteration: 49700/59290
Iteration: 49701/59290
Iteration: 49702/59290
Iteration: 49703/59290
Iteration: 49704/59290
Iteration: 49705/59290
Iteration: 49706/59290
Iteration: 49707/59290
Iteration: 49708/59290
Iteration: 49709/59290
Iteration: 49710/59290
Iteration: 49711/59290
Iteration: 49712/59290

 84%|████████▍ | 49695/59290 [38:43<07:35, 21.05it/s]

Iteration: 49713/59290
Iteration: 49714/59290
Iteration: 49715/59290
Iteration: 49716/59290
Iteration: 49717/59290
Iteration: 49718/59290
Iteration: 49719/59290
Iteration: 49720/59290
Iteration: 49721/59290
Iteration: 49722/59290
Iteration: 49723/59290
Iteration: 49724/59290
Iteration: 49725/59290
Iteration: 49726/59290
Iteration: 49727/59290
Iteration: 49728/59290
Iteration: 49729/59290
Iteration: 49730/59290
Iteration: 49731/59290
Iteration: 49732/59290
Iteration: 49733/59290
Iteration: 49734/59290
Iteration: 49735/59290
Iteration: 49736/59290

 84%|████████▍ | 49719/59290 [38:43<06:03, 26.36it/s]

Iteration: 49737/59290
Iteration: 49738/59290
Iteration: 49739/59290
Iteration: 49740/59290
Iteration: 49741/59290
Iteration: 49742/59290
Iteration: 49743/59290
Iteration: 49744/59290
Iteration: 49745/59290
Iteration: 49746/59290
Iteration: 49747/59290
Iteration: 49748/59290
Iteration: 49749/59290
Iteration: 49750/59290
Iteration: 49751/59290
Iteration: 49752/59290
Iteration: 49753/59290
Iteration: 49754/59290
Iteration: 49755/59290
Iteration: 49756/59290
Iteration: 49757/59290
Iteration: 49758/59290
Iteration: 49759/59290
Iteration: 49760/59290

 84%|████████▍ | 49743/59290 [38:44<04:58, 31.94it/s]

Iteration: 49761/59290
Iteration: 49762/59290
Iteration: 49763/59290
Iteration: 49764/59290
Iteration: 49765/59290
Iteration: 49766/59290
Iteration: 49767/59290
Iteration: 49768/59290
Iteration: 49769/59290
Iteration: 49770/59290
Iteration: 49771/59290
Iteration: 49772/59290
Iteration: 49773/59290
Iteration: 49774/59290
Iteration: 49775/59290
Iteration: 49776/59290
Iteration: 49777/59290
Iteration: 49778/59290
Iteration: 49779/59290
Iteration: 49780/59290
Iteration: 49781/59290
Iteration: 49782/59290
Iteration: 49783/59290
Iteration: 49784/59290

 84%|████████▍ | 49767/59290 [38:44<04:13, 37.54it/s]

Iteration: 49785/59290
Iteration: 49786/59290
Iteration: 49787/59290
Iteration: 49788/59290
Iteration: 49789/59290
Iteration: 49790/59290
Iteration: 49791/59290
Iteration: 49792/59290
Iteration: 49793/59290
Iteration: 49794/59290
Iteration: 49795/59290
Iteration: 49796/59290
Iteration: 49797/59290
Iteration: 49798/59290
Iteration: 49799/59290
Iteration: 49800/59290
Iteration: 49801/59290
Iteration: 49802/59290
Iteration: 49803/59290
Iteration: 49804/59290
Iteration: 49805/59290
Iteration: 49806/59290
Iteration: 49807/59290
Iteration: 49808/59290

 84%|████████▍ | 49791/59290 [38:45<05:35, 28.30it/s]

Iteration: 49809/59290
Iteration: 49810/59290
Iteration: 49811/59290
Iteration: 49812/59290
Iteration: 49813/59290
Iteration: 49814/59290
Iteration: 49815/59290
Iteration: 49816/59290
Iteration: 49817/59290
Iteration: 49818/59290
Iteration: 49819/59290
Iteration: 49820/59290
Iteration: 49821/59290
Iteration: 49822/59290
Iteration: 49823/59290
Iteration: 49824/59290
Iteration: 49825/59290
Iteration: 49826/59290
Iteration: 49827/59290
Iteration: 49828/59290
Iteration: 49829/59290
Iteration: 49830/59290
Iteration: 49831/59290
Iteration: 49832/59290

 84%|████████▍ | 49815/59290 [38:48<08:24, 18.77it/s]

Iteration: 49833/59290
Iteration: 49834/59290
Iteration: 49835/59290
Iteration: 49836/59290
Iteration: 49837/59290
Iteration: 49838/59290
Iteration: 49839/59290
Iteration: 49840/59290
Iteration: 49841/59290
Iteration: 49842/59290
Iteration: 49843/59290
Iteration: 49844/59290
Iteration: 49845/59290
Iteration: 49846/59290
Iteration: 49847/59290
Iteration: 49848/59290
Iteration: 49849/59290
Iteration: 49850/59290
Iteration: 49851/59290
Iteration: 49852/59290
Iteration: 49853/59290
Iteration: 49854/59290
Iteration: 49855/59290
Iteration: 49856/59290

 84%|████████▍ | 49839/59290 [38:48<07:18, 21.53it/s]

Iteration: 49857/59290
Iteration: 49858/59290
Iteration: 49859/59290
Iteration: 49860/59290
Iteration: 49861/59290
Iteration: 49862/59290
Iteration: 49863/59290
Iteration: 49864/59290
Iteration: 49865/59290
Iteration: 49866/59290
Iteration: 49867/59290
Iteration: 49868/59290
Iteration: 49869/59290
Iteration: 49870/59290
Iteration: 49871/59290
Iteration: 49872/59290
Iteration: 49873/59290
Iteration: 49874/59290
Iteration: 49875/59290
Iteration: 49876/59290
Iteration: 49877/59290
Iteration: 49878/59290
Iteration: 49879/59290
Iteration: 49880/59290

 84%|████████▍ | 49863/59290 [38:49<05:52, 26.75it/s]

Iteration: 49881/59290
Iteration: 49882/59290
Iteration: 49883/59290
Iteration: 49884/59290
Iteration: 49885/59290
Iteration: 49886/59290
Iteration: 49887/59290
Iteration: 49888/59290
Iteration: 49889/59290
Iteration: 49890/59290
Iteration: 49891/59290
Iteration: 49892/59290
Iteration: 49893/59290
Iteration: 49894/59290
Iteration: 49895/59290
Iteration: 49896/59290
Iteration: 49897/59290
Iteration: 49898/59290
Iteration: 49899/59290
Iteration: 49900/59290
Iteration: 49901/59290
Iteration: 49902/59290
Iteration: 49903/59290
Iteration: 49904/59290

 84%|████████▍ | 49887/59290 [38:49<04:52, 32.12it/s]

Iteration: 49905/59290
Iteration: 49906/59290
Iteration: 49907/59290
Iteration: 49908/59290
Iteration: 49909/59290
Iteration: 49910/59290
Iteration: 49911/59290
Iteration: 49912/59290
Iteration: 49913/59290
Iteration: 49914/59290
Iteration: 49915/59290
Iteration: 49916/59290
Iteration: 49917/59290
Iteration: 49918/59290
Iteration: 49919/59290
Iteration: 49920/59290
Iteration: 49921/59290
Iteration: 49922/59290
Iteration: 49923/59290
Iteration: 49924/59290
Iteration: 49925/59290
Iteration: 49926/59290
Iteration: 49927/59290
Iteration: 49928/59290

 84%|████████▍ | 49911/59290 [38:49<04:11, 37.36it/s]

Iteration: 49929/59290
Iteration: 49930/59290
Iteration: 49931/59290
Iteration: 49932/59290
Iteration: 49933/59290
Iteration: 49934/59290
Iteration: 49935/59290
Iteration: 49936/59290
Iteration: 49937/59290
Iteration: 49938/59290
Iteration: 49939/59290
Iteration: 49940/59290
Iteration: 49941/59290
Iteration: 49942/59290
Iteration: 49943/59290
Iteration: 49944/59290
Iteration: 49945/59290
Iteration: 49946/59290
Iteration: 49947/59290
Iteration: 49948/59290
Iteration: 49949/59290
Iteration: 49950/59290
Iteration: 49951/59290
Iteration: 49952/59290

 84%|████████▍ | 49935/59290 [38:50<03:39, 42.67it/s]

Iteration: 49953/59290
Iteration: 49954/59290
Iteration: 49955/59290
Iteration: 49956/59290
Iteration: 49957/59290
Iteration: 49958/59290
Iteration: 49959/59290
Iteration: 49960/59290
Iteration: 49961/59290
Iteration: 49962/59290
Iteration: 49963/59290
Iteration: 49964/59290
Iteration: 49965/59290
Iteration: 49966/59290
Iteration: 49967/59290
Iteration: 49968/59290
Iteration: 49969/59290
Iteration: 49970/59290
Iteration: 49971/59290
Iteration: 49972/59290
Iteration: 49973/59290
Iteration: 49974/59290
Iteration: 49975/59290
Iteration: 49976/59290

 84%|████████▍ | 49959/59290 [38:50<03:18, 46.98it/s]

Iteration: 49977/59290
Iteration: 49978/59290
Iteration: 49979/59290
Iteration: 49980/59290
Iteration: 49981/59290
Iteration: 49982/59290
Iteration: 49983/59290
Iteration: 49984/59290
Iteration: 49985/59290
Iteration: 49986/59290
Iteration: 49987/59290
Iteration: 49988/59290
Iteration: 49989/59290
Iteration: 49990/59290
Iteration: 49991/59290
Iteration: 49992/59290
Iteration: 49993/59290
Iteration: 49994/59290
Iteration: 49995/59290
Iteration: 49996/59290
Iteration: 49997/59290
Iteration: 49998/59290
Iteration: 49999/59290
Iteration: 50000/59290

 84%|████████▍ | 49983/59290 [38:51<03:03, 50.60it/s]

Iteration: 50001/59290
Iteration: 50002/59290
Iteration: 50003/59290
Iteration: 50004/59290
Iteration: 50005/59290
Iteration: 50006/59290
Iteration: 50007/59290
Iteration: 50008/59290
Iteration: 50009/59290
Iteration: 50010/59290
Iteration: 50011/59290
Iteration: 50012/59290
Iteration: 50013/59290
Iteration: 50014/59290
Iteration: 50015/59290
Iteration: 50016/59290
Iteration: 50017/59290
Iteration: 50018/59290
Iteration: 50019/59290
Iteration: 50020/59290
Iteration: 50021/59290
Iteration: 50022/59290
Iteration: 50023/59290
Iteration: 50024/59290

 84%|████████▍ | 50007/59290 [38:52<05:07, 30.18it/s]

Iteration: 50025/59290
Iteration: 50026/59290
Iteration: 50027/59290
Iteration: 50028/59290
Iteration: 50029/59290
Iteration: 50030/59290
Iteration: 50031/59290
Iteration: 50032/59290
Iteration: 50033/59290
Iteration: 50034/59290
Iteration: 50035/59290
Iteration: 50036/59290
Iteration: 50037/59290
Iteration: 50038/59290
Iteration: 50039/59290
Iteration: 50040/59290
Iteration: 50041/59290
Iteration: 50042/59290
Iteration: 50043/59290
Iteration: 50044/59290
Iteration: 50045/59290
Iteration: 50046/59290
Iteration: 50047/59290
Iteration: 50048/59290

 84%|████████▍ | 50031/59290 [38:55<08:12, 18.79it/s]

Iteration: 50049/59290
Iteration: 50050/59290
Iteration: 50051/59290
Iteration: 50052/59290
Iteration: 50053/59290
Iteration: 50054/59290
Iteration: 50055/59290
Iteration: 50056/59290
Iteration: 50057/59290
Iteration: 50058/59290
Iteration: 50059/59290
Iteration: 50060/59290
Iteration: 50061/59290
Iteration: 50062/59290
Iteration: 50063/59290
Iteration: 50064/59290
Iteration: 50065/59290
Iteration: 50066/59290
Iteration: 50067/59290
Iteration: 50068/59290
Iteration: 50069/59290
Iteration: 50070/59290
Iteration: 50071/59290
Iteration: 50072/59290

 84%|████████▍ | 50055/59290 [38:55<07:09, 21.50it/s]

Iteration: 50073/59290
Iteration: 50074/59290
Iteration: 50075/59290
Iteration: 50076/59290
Iteration: 50077/59290
Iteration: 50078/59290
Iteration: 50079/59290
Iteration: 50080/59290
Iteration: 50081/59290
Iteration: 50082/59290
Iteration: 50083/59290
Iteration: 50084/59290
Iteration: 50085/59290
Iteration: 50086/59290
Iteration: 50087/59290
Iteration: 50088/59290
Iteration: 50089/59290
Iteration: 50090/59290
Iteration: 50091/59290
Iteration: 50092/59290
Iteration: 50093/59290
Iteration: 50094/59290
Iteration: 50095/59290
Iteration: 50096/59290

 84%|████████▍ | 50079/59290 [38:56<05:43, 26.83it/s]

Iteration: 50097/59290
Iteration: 50098/59290
Iteration: 50099/59290
Iteration: 50100/59290
Iteration: 50101/59290
Iteration: 50102/59290
Iteration: 50103/59290
Iteration: 50104/59290
Iteration: 50105/59290
Iteration: 50106/59290
Iteration: 50107/59290
Iteration: 50108/59290
Iteration: 50109/59290
Iteration: 50110/59290
Iteration: 50111/59290
Iteration: 50112/59290
Iteration: 50113/59290
Iteration: 50114/59290
Iteration: 50115/59290
Iteration: 50116/59290
Iteration: 50117/59290
Iteration: 50118/59290
Iteration: 50119/59290
Iteration: 50120/59290

 85%|████████▍ | 50103/59290 [38:56<04:44, 32.34it/s]

Iteration: 50121/59290
Iteration: 50122/59290
Iteration: 50123/59290
Iteration: 50124/59290
Iteration: 50125/59290
Iteration: 50126/59290
Iteration: 50127/59290
Iteration: 50128/59290
Iteration: 50129/59290
Iteration: 50130/59290
Iteration: 50131/59290
Iteration: 50132/59290
Iteration: 50133/59290
Iteration: 50134/59290
Iteration: 50135/59290
Iteration: 50136/59290
Iteration: 50137/59290
Iteration: 50138/59290
Iteration: 50139/59290
Iteration: 50140/59290
Iteration: 50141/59290
Iteration: 50142/59290
Iteration: 50143/59290
Iteration: 50144/59290

 85%|████████▍ | 50127/59290 [38:56<04:01, 37.99it/s]

Iteration: 50145/59290
Iteration: 50146/59290
Iteration: 50147/59290
Iteration: 50148/59290
Iteration: 50149/59290
Iteration: 50150/59290
Iteration: 50151/59290
Iteration: 50152/59290
Iteration: 50153/59290
Iteration: 50154/59290
Iteration: 50155/59290
Iteration: 50156/59290
Iteration: 50157/59290
Iteration: 50158/59290
Iteration: 50159/59290
Iteration: 50160/59290
Iteration: 50161/59290
Iteration: 50162/59290
Iteration: 50163/59290
Iteration: 50164/59290
Iteration: 50165/59290
Iteration: 50166/59290
Iteration: 50167/59290
Iteration: 50168/59290

 85%|████████▍ | 50151/59290 [38:57<03:31, 43.16it/s]

Iteration: 50169/59290
Iteration: 50170/59290
Iteration: 50171/59290
Iteration: 50172/59290
Iteration: 50173/59290
Iteration: 50174/59290
Iteration: 50175/59290
Iteration: 50176/59290
Iteration: 50177/59290
Iteration: 50178/59290
Iteration: 50179/59290
Iteration: 50180/59290
Iteration: 50181/59290
Iteration: 50182/59290
Iteration: 50183/59290
Iteration: 50184/59290
Iteration: 50185/59290
Iteration: 50186/59290
Iteration: 50187/59290
Iteration: 50188/59290
Iteration: 50189/59290
Iteration: 50190/59290
Iteration: 50191/59290
Iteration: 50192/59290

 85%|████████▍ | 50175/59290 [38:57<03:10, 47.81it/s]

Iteration: 50193/59290
Iteration: 50194/59290
Iteration: 50195/59290
Iteration: 50196/59290
Iteration: 50197/59290
Iteration: 50198/59290
Iteration: 50199/59290
Iteration: 50200/59290
Iteration: 50201/59290
Iteration: 50202/59290
Iteration: 50203/59290
Iteration: 50204/59290
Iteration: 50205/59290
Iteration: 50206/59290
Iteration: 50207/59290
Iteration: 50208/59290
Iteration: 50209/59290
Iteration: 50210/59290
Iteration: 50211/59290
Iteration: 50212/59290
Iteration: 50213/59290
Iteration: 50214/59290
Iteration: 50215/59290
Iteration: 50216/59290

 85%|████████▍ | 50199/59290 [38:58<02:55, 51.84it/s]

Iteration: 50217/59290
Iteration: 50218/59290
Iteration: 50219/59290
Iteration: 50220/59290
Iteration: 50221/59290
Iteration: 50222/59290
Iteration: 50223/59290
Iteration: 50224/59290
Iteration: 50225/59290
Iteration: 50226/59290
Iteration: 50227/59290
Iteration: 50228/59290
Iteration: 50229/59290
Iteration: 50230/59290
Iteration: 50231/59290
Iteration: 50232/59290
Iteration: 50233/59290
Iteration: 50234/59290
Iteration: 50235/59290
Iteration: 50236/59290
Iteration: 50237/59290
Iteration: 50238/59290
Iteration: 50239/59290
Iteration: 50240/59290

 85%|████████▍ | 50223/59290 [39:31<1:05:06,  2.32it/s]

Iteration: 50241/59290
Iteration: 50242/59290
Iteration: 50243/59290
Iteration: 50244/59290
Iteration: 50245/59290
Iteration: 50246/59290
Iteration: 50247/59290
Iteration: 50248/59290
Iteration: 50249/59290
Iteration: 50250/59290
Iteration: 50251/59290
Iteration: 50252/59290
Iteration: 50253/59290
Iteration: 50254/59290
Iteration: 50255/59290
Iteration: 50256/59290
Iteration: 50257/59290
Iteration: 50258/59290
Iteration: 50259/59290
Iteration: 50260/59290
Iteration: 50261/59290
Iteration: 50262/59290
Iteration: 50263/59290
Iteration: 50264/59290

 85%|████████▍ | 50247/59290 [39:32<46:42,  3.23it/s]

Iteration: 50265/59290
Iteration: 50266/59290
Iteration: 50267/59290
Iteration: 50268/59290
Iteration: 50269/59290
Iteration: 50270/59290
Iteration: 50271/59290
Iteration: 50272/59290
Iteration: 50273/59290
Iteration: 50274/59290
Iteration: 50275/59290
Iteration: 50276/59290
Iteration: 50277/59290
Iteration: 50278/59290
Iteration: 50279/59290
Iteration: 50280/59290
Iteration: 50281/59290
Iteration: 50282/59290
Iteration: 50283/59290
Iteration: 50284/59290
Iteration: 50285/59290
Iteration: 50286/59290
Iteration: 50287/59290
Iteration: 50288/59290

 85%|████████▍ | 50271/59290 [39:32<33:38,  4.47it/s]

Iteration: 50289/59290
Iteration: 50290/59290
Iteration: 50291/59290
Iteration: 50292/59290
Iteration: 50293/59290
Iteration: 50294/59290
Iteration: 50295/59290
Iteration: 50296/59290
Iteration: 50297/59290
Iteration: 50298/59290
Iteration: 50299/59290
Iteration: 50300/59290
Iteration: 50301/59290
Iteration: 50302/59290
Iteration: 50303/59290
Iteration: 50304/59290
Iteration: 50305/59290
Iteration: 50306/59290
Iteration: 50307/59290
Iteration: 50308/59290
Iteration: 50309/59290
Iteration: 50310/59290
Iteration: 50311/59290
Iteration: 50312/59290

 85%|████████▍ | 50295/59290 [39:33<24:38,  6.08it/s]

Iteration: 50313/59290
Iteration: 50314/59290
Iteration: 50315/59290
Iteration: 50316/59290
Iteration: 50317/59290
Iteration: 50318/59290
Iteration: 50319/59290
Iteration: 50320/59290
Iteration: 50321/59290
Iteration: 50322/59290
Iteration: 50323/59290
Iteration: 50324/59290
Iteration: 50325/59290
Iteration: 50326/59290
Iteration: 50327/59290
Iteration: 50328/59290
Iteration: 50329/59290
Iteration: 50330/59290
Iteration: 50331/59290
Iteration: 50332/59290
Iteration: 50333/59290
Iteration: 50334/59290
Iteration: 50335/59290
Iteration: 50336/59290

 85%|████████▍ | 50319/59290 [39:33<18:15,  8.19it/s]

Iteration: 50337/59290
Iteration: 50338/59290
Iteration: 50339/59290
Iteration: 50340/59290
Iteration: 50341/59290
Iteration: 50342/59290
Iteration: 50343/59290
Iteration: 50344/59290
Iteration: 50345/59290
Iteration: 50346/59290
Iteration: 50347/59290
Iteration: 50348/59290
Iteration: 50349/59290
Iteration: 50350/59290
Iteration: 50351/59290
Iteration: 50352/59290
Iteration: 50353/59290
Iteration: 50354/59290
Iteration: 50355/59290
Iteration: 50356/59290
Iteration: 50357/59290
Iteration: 50358/59290
Iteration: 50359/59290
Iteration: 50360/59290

 85%|████████▍ | 50343/59290 [39:34<13:45, 10.84it/s]

Iteration: 50361/59290
Iteration: 50362/59290
Iteration: 50363/59290
Iteration: 50364/59290
Iteration: 50365/59290
Iteration: 50366/59290
Iteration: 50367/59290
Iteration: 50368/59290
Iteration: 50369/59290
Iteration: 50370/59290
Iteration: 50371/59290
Iteration: 50372/59290
Iteration: 50373/59290
Iteration: 50374/59290
Iteration: 50375/59290
Iteration: 50376/59290
Iteration: 50377/59290
Iteration: 50378/59290
Iteration: 50379/59290
Iteration: 50380/59290
Iteration: 50381/59290
Iteration: 50382/59290
Iteration: 50383/59290
Iteration: 50384/59290

 85%|████████▍ | 50367/59290 [39:34<10:26, 14.23it/s]

Iteration: 50385/59290
Iteration: 50386/59290
Iteration: 50387/59290
Iteration: 50388/59290
Iteration: 50389/59290
Iteration: 50390/59290
Iteration: 50391/59290
Iteration: 50392/59290
Iteration: 50393/59290
Iteration: 50394/59290
Iteration: 50395/59290
Iteration: 50396/59290
Iteration: 50397/59290
Iteration: 50398/59290
Iteration: 50399/59290
Iteration: 50400/59290
Iteration: 50401/59290
Iteration: 50402/59290
Iteration: 50403/59290
Iteration: 50404/59290
Iteration: 50405/59290
Iteration: 50406/59290
Iteration: 50407/59290
Iteration: 50408/59290

 85%|████████▍ | 50391/59290 [39:35<08:08, 18.22it/s]

Iteration: 50409/59290
Iteration: 50410/59290
Iteration: 50411/59290
Iteration: 50412/59290
Iteration: 50413/59290
Iteration: 50414/59290
Iteration: 50415/59290
Iteration: 50416/59290
Iteration: 50417/59290
Iteration: 50418/59290
Iteration: 50419/59290
Iteration: 50420/59290
Iteration: 50421/59290
Iteration: 50422/59290
Iteration: 50423/59290
Iteration: 50424/59290
Iteration: 50425/59290
Iteration: 50426/59290
Iteration: 50427/59290
Iteration: 50428/59290
Iteration: 50429/59290
Iteration: 50430/59290
Iteration: 50431/59290
Iteration: 50432/59290

 85%|████████▌ | 50415/59290 [39:35<06:34, 22.51it/s]

Iteration: 50433/59290
Iteration: 50434/59290
Iteration: 50435/59290
Iteration: 50436/59290
Iteration: 50437/59290
Iteration: 50438/59290
Iteration: 50439/59290
Iteration: 50440/59290
Iteration: 50441/59290
Iteration: 50442/59290
Iteration: 50443/59290
Iteration: 50444/59290
Iteration: 50445/59290
Iteration: 50446/59290
Iteration: 50447/59290
Iteration: 50448/59290
Iteration: 50449/59290
Iteration: 50450/59290
Iteration: 50451/59290
Iteration: 50452/59290
Iteration: 50453/59290
Iteration: 50454/59290
Iteration: 50455/59290
Iteration: 50456/59290

 85%|████████▌ | 50439/59290 [39:36<05:38, 26.14it/s]

Iteration: 50457/59290
Iteration: 50458/59290
Iteration: 50459/59290
Iteration: 50460/59290
Iteration: 50461/59290
Iteration: 50462/59290
Iteration: 50463/59290
Iteration: 50464/59290
Iteration: 50465/59290
Iteration: 50466/59290
Iteration: 50467/59290
Iteration: 50468/59290
Iteration: 50469/59290
Iteration: 50470/59290
Iteration: 50471/59290
Iteration: 50472/59290
Iteration: 50473/59290
Iteration: 50474/59290
Iteration: 50475/59290
Iteration: 50476/59290
Iteration: 50477/59290
Iteration: 50478/59290
Iteration: 50479/59290
Iteration: 50480/59290

 85%|████████▌ | 50463/59290 [39:36<04:44, 31.04it/s]

Iteration: 50481/59290
Iteration: 50482/59290
Iteration: 50483/59290
Iteration: 50484/59290
Iteration: 50485/59290
Iteration: 50486/59290
Iteration: 50487/59290
Iteration: 50488/59290
Iteration: 50489/59290
Iteration: 50490/59290
Iteration: 50491/59290
Iteration: 50492/59290
Iteration: 50493/59290
Iteration: 50494/59290
Iteration: 50495/59290
Iteration: 50496/59290
Iteration: 50497/59290
Iteration: 50498/59290
Iteration: 50499/59290
Iteration: 50500/59290
Iteration: 50501/59290
Iteration: 50502/59290
Iteration: 50503/59290
Iteration: 50504/59290

 85%|████████▌ | 50487/59290 [39:37<04:04, 35.96it/s]

Iteration: 50505/59290
Iteration: 50506/59290
Iteration: 50507/59290
Iteration: 50508/59290
Iteration: 50509/59290
Iteration: 50510/59290
Iteration: 50511/59290
Iteration: 50512/59290
Iteration: 50513/59290
Iteration: 50514/59290
Iteration: 50515/59290
Iteration: 50516/59290
Iteration: 50517/59290
Iteration: 50518/59290
Iteration: 50519/59290
Iteration: 50520/59290
Iteration: 50521/59290
Iteration: 50522/59290
Iteration: 50523/59290
Iteration: 50524/59290
Iteration: 50525/59290
Iteration: 50526/59290
Iteration: 50527/59290
Iteration: 50528/59290

 85%|████████▌ | 50511/59290 [39:37<03:38, 40.14it/s]

Iteration: 50529/59290
Iteration: 50530/59290
Iteration: 50531/59290
Iteration: 50532/59290
Iteration: 50533/59290
Iteration: 50534/59290
Iteration: 50535/59290
Iteration: 50536/59290
Iteration: 50537/59290
Iteration: 50538/59290
Iteration: 50539/59290
Iteration: 50540/59290
Iteration: 50541/59290
Iteration: 50542/59290
Iteration: 50543/59290
Iteration: 50544/59290
Iteration: 50545/59290
Iteration: 50546/59290
Iteration: 50547/59290
Iteration: 50548/59290
Iteration: 50549/59290
Iteration: 50550/59290
Iteration: 50551/59290
Iteration: 50552/59290

 85%|████████▌ | 50535/59290 [39:38<03:17, 44.32it/s]

Iteration: 50553/59290
Iteration: 50554/59290
Iteration: 50555/59290
Iteration: 50556/59290
Iteration: 50557/59290
Iteration: 50558/59290
Iteration: 50559/59290
Iteration: 50560/59290
Iteration: 50561/59290
Iteration: 50562/59290
Iteration: 50563/59290
Iteration: 50564/59290
Iteration: 50565/59290
Iteration: 50566/59290
Iteration: 50567/59290
Iteration: 50568/59290
Iteration: 50569/59290
Iteration: 50570/59290
Iteration: 50571/59290
Iteration: 50572/59290
Iteration: 50573/59290
Iteration: 50574/59290
Iteration: 50575/59290
Iteration: 50576/59290

 85%|████████▌ | 50559/59290 [39:38<03:04, 47.28it/s]

Iteration: 50577/59290
Iteration: 50578/59290
Iteration: 50579/59290
Iteration: 50580/59290
Iteration: 50581/59290
Iteration: 50582/59290
Iteration: 50583/59290
Iteration: 50584/59290
Iteration: 50585/59290
Iteration: 50586/59290
Iteration: 50587/59290
Iteration: 50588/59290
Iteration: 50589/59290
Iteration: 50590/59290
Iteration: 50591/59290
Iteration: 50592/59290
Iteration: 50593/59290
Iteration: 50594/59290
Iteration: 50595/59290
Iteration: 50596/59290
Iteration: 50597/59290
Iteration: 50598/59290
Iteration: 50599/59290
Iteration: 50600/59290

 85%|████████▌ | 50583/59290 [39:38<02:56, 49.24it/s]

Iteration: 50601/59290
Iteration: 50602/59290
Iteration: 50603/59290
Iteration: 50604/59290
Iteration: 50605/59290
Iteration: 50606/59290
Iteration: 50607/59290
Iteration: 50608/59290
Iteration: 50609/59290
Iteration: 50610/59290
Iteration: 50611/59290
Iteration: 50612/59290
Iteration: 50613/59290
Iteration: 50614/59290
Iteration: 50615/59290
Iteration: 50616/59290
Iteration: 50617/59290
Iteration: 50618/59290
Iteration: 50619/59290
Iteration: 50620/59290
Iteration: 50621/59290
Iteration: 50622/59290
Iteration: 50623/59290
Iteration: 50624/59290

 85%|████████▌ | 50607/59290 [39:39<02:52, 50.24it/s]

Iteration: 50625/59290
Iteration: 50626/59290
Iteration: 50627/59290
Iteration: 50628/59290
Iteration: 50629/59290
Iteration: 50630/59290
Iteration: 50631/59290
Iteration: 50632/59290
Iteration: 50633/59290
Iteration: 50634/59290
Iteration: 50635/59290
Iteration: 50636/59290
Iteration: 50637/59290
Iteration: 50638/59290
Iteration: 50639/59290
Iteration: 50640/59290
Iteration: 50641/59290
Iteration: 50642/59290
Iteration: 50643/59290
Iteration: 50644/59290
Iteration: 50645/59290
Iteration: 50646/59290
Iteration: 50647/59290
Iteration: 50648/59290

 85%|████████▌ | 50631/59290 [39:39<02:48, 51.26it/s]

Iteration: 50649/59290
Iteration: 50650/59290
Iteration: 50651/59290
Iteration: 50652/59290
Iteration: 50653/59290
Iteration: 50654/59290
Iteration: 50655/59290
Iteration: 50656/59290
Iteration: 50657/59290
Iteration: 50658/59290
Iteration: 50659/59290
Iteration: 50660/59290
Iteration: 50661/59290
Iteration: 50662/59290
Iteration: 50663/59290
Iteration: 50664/59290
Iteration: 50665/59290
Iteration: 50666/59290
Iteration: 50667/59290
Iteration: 50668/59290
Iteration: 50669/59290
Iteration: 50670/59290
Iteration: 50671/59290
Iteration: 50672/59290

 85%|████████▌ | 50655/59290 [39:40<02:40, 53.68it/s]

Iteration: 50673/59290
Iteration: 50674/59290
Iteration: 50675/59290
Iteration: 50676/59290
Iteration: 50677/59290
Iteration: 50678/59290
Iteration: 50679/59290
Iteration: 50680/59290
Iteration: 50681/59290
Iteration: 50682/59290
Iteration: 50683/59290
Iteration: 50684/59290
Iteration: 50685/59290
Iteration: 50686/59290
Iteration: 50687/59290
Iteration: 50688/59290
Iteration: 50689/59290
Iteration: 50690/59290
Iteration: 50691/59290
Iteration: 50692/59290
Iteration: 50693/59290
Iteration: 50694/59290
Iteration: 50695/59290
Iteration: 50696/59290

 85%|████████▌ | 50679/59290 [39:40<02:34, 55.89it/s]

Iteration: 50697/59290
Iteration: 50698/59290
Iteration: 50699/59290
Iteration: 50700/59290
Iteration: 50701/59290
Iteration: 50702/59290
Iteration: 50703/59290
Iteration: 50704/59290
Iteration: 50705/59290
Iteration: 50706/59290
Iteration: 50707/59290
Iteration: 50708/59290
Iteration: 50709/59290
Iteration: 50710/59290
Iteration: 50711/59290
Iteration: 50712/59290
Iteration: 50713/59290
Iteration: 50714/59290
Iteration: 50715/59290
Iteration: 50716/59290
Iteration: 50717/59290
Iteration: 50718/59290
Iteration: 50719/59290
Iteration: 50720/59290

 86%|████████▌ | 50703/59290 [39:41<02:27, 58.07it/s]

Iteration: 50721/59290
Iteration: 50722/59290
Iteration: 50723/59290
Iteration: 50724/59290
Iteration: 50725/59290
Iteration: 50726/59290
Iteration: 50727/59290
Iteration: 50728/59290
Iteration: 50729/59290
Iteration: 50730/59290
Iteration: 50731/59290
Iteration: 50732/59290
Iteration: 50733/59290
Iteration: 50734/59290
Iteration: 50735/59290
Iteration: 50736/59290
Iteration: 50737/59290
Iteration: 50738/59290
Iteration: 50739/59290
Iteration: 50740/59290
Iteration: 50741/59290
Iteration: 50742/59290
Iteration: 50743/59290
Iteration: 50744/59290

 86%|████████▌ | 50727/59290 [39:41<02:22, 59.92it/s]

Iteration: 50745/59290
Iteration: 50746/59290
Iteration: 50747/59290
Iteration: 50748/59290
Iteration: 50749/59290
Iteration: 50750/59290
Iteration: 50751/59290
Iteration: 50752/59290
Iteration: 50753/59290
Iteration: 50754/59290
Iteration: 50755/59290
Iteration: 50756/59290
Iteration: 50757/59290
Iteration: 50758/59290
Iteration: 50759/59290
Iteration: 50760/59290
Iteration: 50761/59290
Iteration: 50762/59290
Iteration: 50763/59290
Iteration: 50764/59290
Iteration: 50765/59290
Iteration: 50766/59290
Iteration: 50767/59290
Iteration: 50768/59290

 86%|████████▌ | 50751/59290 [39:41<02:20, 60.77it/s]

Iteration: 50769/59290
Iteration: 50770/59290
Iteration: 50771/59290
Iteration: 50772/59290
Iteration: 50773/59290
Iteration: 50774/59290
Iteration: 50775/59290
Iteration: 50776/59290
Iteration: 50777/59290
Iteration: 50778/59290
Iteration: 50779/59290
Iteration: 50780/59290
Iteration: 50781/59290
Iteration: 50782/59290
Iteration: 50783/59290
Iteration: 50784/59290
Iteration: 50785/59290
Iteration: 50786/59290
Iteration: 50787/59290
Iteration: 50788/59290
Iteration: 50789/59290
Iteration: 50790/59290
Iteration: 50791/59290
Iteration: 50792/59290

 86%|████████▌ | 50775/59290 [39:42<02:24, 58.98it/s]

Iteration: 50793/59290
Iteration: 50794/59290
Iteration: 50795/59290
Iteration: 50796/59290
Iteration: 50797/59290
Iteration: 50798/59290
Iteration: 50799/59290
Iteration: 50800/59290
Iteration: 50801/59290
Iteration: 50802/59290
Iteration: 50803/59290
Iteration: 50804/59290
Iteration: 50805/59290
Iteration: 50806/59290
Iteration: 50807/59290
Iteration: 50808/59290
Iteration: 50809/59290
Iteration: 50810/59290
Iteration: 50811/59290
Iteration: 50812/59290
Iteration: 50813/59290
Iteration: 50814/59290
Iteration: 50815/59290
Iteration: 50816/59290

 86%|████████▌ | 50799/59290 [39:42<02:26, 57.95it/s]

Iteration: 50817/59290
Iteration: 50818/59290
Iteration: 50819/59290
Iteration: 50820/59290
Iteration: 50821/59290
Iteration: 50822/59290
Iteration: 50823/59290
Iteration: 50824/59290
Iteration: 50825/59290
Iteration: 50826/59290
Iteration: 50827/59290
Iteration: 50828/59290
Iteration: 50829/59290
Iteration: 50830/59290
Iteration: 50831/59290
Iteration: 50832/59290
Iteration: 50833/59290
Iteration: 50834/59290
Iteration: 50835/59290
Iteration: 50836/59290
Iteration: 50837/59290
Iteration: 50838/59290
Iteration: 50839/59290
Iteration: 50840/59290

 86%|████████▌ | 50823/59290 [39:43<02:29, 56.47it/s]

Iteration: 50841/59290
Iteration: 50842/59290
Iteration: 50843/59290
Iteration: 50844/59290
Iteration: 50845/59290
Iteration: 50846/59290
Iteration: 50847/59290
Iteration: 50848/59290
Iteration: 50849/59290
Iteration: 50850/59290
Iteration: 50851/59290
Iteration: 50852/59290
Iteration: 50853/59290
Iteration: 50854/59290
Iteration: 50855/59290
Iteration: 50856/59290
Iteration: 50857/59290
Iteration: 50858/59290
Iteration: 50859/59290
Iteration: 50860/59290
Iteration: 50861/59290
Iteration: 50862/59290
Iteration: 50863/59290
Iteration: 50864/59290

 86%|████████▌ | 50847/59290 [39:43<02:28, 57.03it/s]

Iteration: 50865/59290
Iteration: 50866/59290
Iteration: 50867/59290
Iteration: 50868/59290
Iteration: 50869/59290
Iteration: 50870/59290
Iteration: 50871/59290
Iteration: 50872/59290
Iteration: 50873/59290
Iteration: 50874/59290
Iteration: 50875/59290
Iteration: 50876/59290
Iteration: 50877/59290
Iteration: 50878/59290
Iteration: 50879/59290
Iteration: 50880/59290
Iteration: 50881/59290
Iteration: 50882/59290
Iteration: 50883/59290
Iteration: 50884/59290
Iteration: 50885/59290
Iteration: 50886/59290
Iteration: 50887/59290
Iteration: 50888/59290

 86%|████████▌ | 50871/59290 [39:43<02:29, 56.50it/s]

Iteration: 50889/59290
Iteration: 50890/59290
Iteration: 50891/59290
Iteration: 50892/59290
Iteration: 50893/59290
Iteration: 50894/59290
Iteration: 50895/59290
Iteration: 50896/59290
Iteration: 50897/59290
Iteration: 50898/59290
Iteration: 50899/59290
Iteration: 50900/59290
Iteration: 50901/59290
Iteration: 50902/59290
Iteration: 50903/59290
Iteration: 50904/59290
Iteration: 50905/59290
Iteration: 50906/59290
Iteration: 50907/59290
Iteration: 50908/59290
Iteration: 50909/59290
Iteration: 50910/59290
Iteration: 50911/59290
Iteration: 50912/59290

 86%|████████▌ | 50895/59290 [39:44<02:26, 57.35it/s]

Iteration: 50913/59290
Iteration: 50914/59290
Iteration: 50915/59290
Iteration: 50916/59290
Iteration: 50917/59290
Iteration: 50918/59290
Iteration: 50919/59290
Iteration: 50920/59290
Iteration: 50921/59290
Iteration: 50922/59290
Iteration: 50923/59290
Iteration: 50924/59290
Iteration: 50925/59290
Iteration: 50926/59290
Iteration: 50927/59290
Iteration: 50928/59290
Iteration: 50929/59290
Iteration: 50930/59290
Iteration: 50931/59290
Iteration: 50932/59290
Iteration: 50933/59290
Iteration: 50934/59290
Iteration: 50935/59290
Iteration: 50936/59290

 86%|████████▌ | 50919/59290 [39:44<02:31, 55.32it/s]

Iteration: 50937/59290
Iteration: 50938/59290
Iteration: 50939/59290
Iteration: 50940/59290
Iteration: 50941/59290
Iteration: 50942/59290
Iteration: 50943/59290
Iteration: 50944/59290
Iteration: 50945/59290
Iteration: 50946/59290
Iteration: 50947/59290
Iteration: 50948/59290
Iteration: 50949/59290
Iteration: 50950/59290
Iteration: 50951/59290
Iteration: 50952/59290
Iteration: 50953/59290
Iteration: 50954/59290
Iteration: 50955/59290
Iteration: 50956/59290
Iteration: 50957/59290
Iteration: 50958/59290
Iteration: 50959/59290
Iteration: 50960/59290

 86%|████████▌ | 50943/59290 [39:45<02:29, 55.93it/s]

Iteration: 50961/59290
Iteration: 50962/59290
Iteration: 50963/59290
Iteration: 50964/59290
Iteration: 50965/59290
Iteration: 50966/59290
Iteration: 50967/59290
Iteration: 50968/59290
Iteration: 50969/59290
Iteration: 50970/59290
Iteration: 50971/59290
Iteration: 50972/59290
Iteration: 50973/59290
Iteration: 50974/59290
Iteration: 50975/59290
Iteration: 50976/59290
Iteration: 50977/59290
Iteration: 50978/59290
Iteration: 50979/59290
Iteration: 50980/59290
Iteration: 50981/59290
Iteration: 50982/59290
Iteration: 50983/59290
Iteration: 50984/59290

 86%|████████▌ | 50967/59290 [39:45<02:26, 56.98it/s]

Iteration: 50985/59290
Iteration: 50986/59290
Iteration: 50987/59290
Iteration: 50988/59290
Iteration: 50989/59290
Iteration: 50990/59290
Iteration: 50991/59290
Iteration: 50992/59290
Iteration: 50993/59290
Iteration: 50994/59290
Iteration: 50995/59290
Iteration: 50996/59290
Iteration: 50997/59290
Iteration: 50998/59290
Iteration: 50999/59290
Iteration: 51000/59290
Iteration: 51001/59290
Iteration: 51002/59290
Iteration: 51003/59290
Iteration: 51004/59290
Iteration: 51005/59290
Iteration: 51006/59290
Iteration: 51007/59290
Iteration: 51008/59290

 86%|████████▌ | 50991/59290 [39:49<08:48, 15.71it/s]

Iteration: 51009/59290
Iteration: 51010/59290
Iteration: 51011/59290
Iteration: 51012/59290
Iteration: 51013/59290
Iteration: 51014/59290
Iteration: 51015/59290
Iteration: 51016/59290
Iteration: 51017/59290
Iteration: 51018/59290
Iteration: 51019/59290
Iteration: 51020/59290
Iteration: 51021/59290
Iteration: 51022/59290
Iteration: 51023/59290
Iteration: 51024/59290
Iteration: 51025/59290
Iteration: 51026/59290
Iteration: 51027/59290
Iteration: 51028/59290
Iteration: 51029/59290
Iteration: 51030/59290
Iteration: 51031/59290
Iteration: 51032/59290

 86%|████████▌ | 51015/59290 [39:51<08:23, 16.43it/s]

Iteration: 51033/59290
Iteration: 51034/59290
Iteration: 51035/59290
Iteration: 51036/59290
Iteration: 51037/59290
Iteration: 51038/59290
Iteration: 51039/59290
Iteration: 51040/59290
Iteration: 51041/59290
Iteration: 51042/59290
Iteration: 51043/59290
Iteration: 51044/59290
Iteration: 51045/59290
Iteration: 51046/59290
Iteration: 51047/59290
Iteration: 51048/59290
Iteration: 51049/59290
Iteration: 51050/59290
Iteration: 51051/59290
Iteration: 51052/59290
Iteration: 51053/59290
Iteration: 51054/59290
Iteration: 51055/59290
Iteration: 51056/59290

 86%|████████▌ | 51039/59290 [39:51<06:50, 20.12it/s]

Iteration: 51057/59290
Iteration: 51058/59290
Iteration: 51059/59290
Iteration: 51060/59290
Iteration: 51061/59290
Iteration: 51062/59290
Iteration: 51063/59290
Iteration: 51064/59290
Iteration: 51065/59290
Iteration: 51066/59290
Iteration: 51067/59290
Iteration: 51068/59290
Iteration: 51069/59290
Iteration: 51070/59290
Iteration: 51071/59290
Iteration: 51072/59290
Iteration: 51073/59290
Iteration: 51074/59290
Iteration: 51075/59290
Iteration: 51076/59290
Iteration: 51077/59290
Iteration: 51078/59290
Iteration: 51079/59290
Iteration: 51080/59290

 86%|████████▌ | 51063/59290 [39:52<05:35, 24.50it/s]

Iteration: 51081/59290
Iteration: 51082/59290
Iteration: 51083/59290
Iteration: 51084/59290
Iteration: 51085/59290
Iteration: 51086/59290
Iteration: 51087/59290
Iteration: 51088/59290
Iteration: 51089/59290
Iteration: 51090/59290
Iteration: 51091/59290
Iteration: 51092/59290
Iteration: 51093/59290
Iteration: 51094/59290
Iteration: 51095/59290
Iteration: 51096/59290
Iteration: 51097/59290
Iteration: 51098/59290
Iteration: 51099/59290
Iteration: 51100/59290
Iteration: 51101/59290
Iteration: 51102/59290
Iteration: 51103/59290
Iteration: 51104/59290

 86%|████████▌ | 51087/59290 [39:52<04:36, 29.66it/s]

Iteration: 51105/59290
Iteration: 51106/59290
Iteration: 51107/59290
Iteration: 51108/59290
Iteration: 51109/59290
Iteration: 51110/59290
Iteration: 51111/59290
Iteration: 51112/59290
Iteration: 51113/59290
Iteration: 51114/59290
Iteration: 51115/59290
Iteration: 51116/59290
Iteration: 51117/59290
Iteration: 51118/59290
Iteration: 51119/59290
Iteration: 51120/59290
Iteration: 51121/59290
Iteration: 51122/59290
Iteration: 51123/59290
Iteration: 51124/59290
Iteration: 51125/59290
Iteration: 51126/59290
Iteration: 51127/59290
Iteration: 51128/59290

 86%|████████▌ | 51111/59290 [39:52<03:53, 34.96it/s]

Iteration: 51129/59290
Iteration: 51130/59290
Iteration: 51131/59290
Iteration: 51132/59290
Iteration: 51133/59290
Iteration: 51134/59290
Iteration: 51135/59290
Iteration: 51136/59290
Iteration: 51137/59290
Iteration: 51138/59290
Iteration: 51139/59290
Iteration: 51140/59290
Iteration: 51141/59290
Iteration: 51142/59290
Iteration: 51143/59290
Iteration: 51144/59290
Iteration: 51145/59290
Iteration: 51146/59290
Iteration: 51147/59290
Iteration: 51148/59290
Iteration: 51149/59290
Iteration: 51150/59290
Iteration: 51151/59290
Iteration: 51152/59290

 86%|████████▌ | 51135/59290 [39:53<03:37, 37.53it/s]

Iteration: 51153/59290
Iteration: 51154/59290
Iteration: 51155/59290
Iteration: 51156/59290
Iteration: 51157/59290
Iteration: 51158/59290
Iteration: 51159/59290
Iteration: 51160/59290
Iteration: 51161/59290
Iteration: 51162/59290
Iteration: 51163/59290
Iteration: 51164/59290
Iteration: 51165/59290
Iteration: 51166/59290
Iteration: 51167/59290
Iteration: 51168/59290
Iteration: 51169/59290
Iteration: 51170/59290
Iteration: 51171/59290
Iteration: 51172/59290
Iteration: 51173/59290
Iteration: 51174/59290
Iteration: 51175/59290
Iteration: 51176/59290

 86%|████████▋ | 51159/59290 [39:53<03:16, 41.47it/s]

Iteration: 51177/59290
Iteration: 51178/59290
Iteration: 51179/59290
Iteration: 51180/59290
Iteration: 51181/59290
Iteration: 51182/59290
Iteration: 51183/59290
Iteration: 51184/59290
Iteration: 51185/59290
Iteration: 51186/59290
Iteration: 51187/59290
Iteration: 51188/59290
Iteration: 51189/59290
Iteration: 51190/59290
Iteration: 51191/59290
Iteration: 51192/59290
Iteration: 51193/59290
Iteration: 51194/59290
Iteration: 51195/59290
Iteration: 51196/59290
Iteration: 51197/59290
Iteration: 51198/59290
Iteration: 51199/59290
Iteration: 51200/59290

 86%|████████▋ | 51183/59290 [39:54<02:57, 45.56it/s]

Iteration: 51201/59290
Iteration: 51202/59290
Iteration: 51203/59290
Iteration: 51204/59290
Iteration: 51205/59290
Iteration: 51206/59290
Iteration: 51207/59290
Iteration: 51208/59290
Iteration: 51209/59290
Iteration: 51210/59290
Iteration: 51211/59290
Iteration: 51212/59290
Iteration: 51213/59290
Iteration: 51214/59290
Iteration: 51215/59290
Iteration: 51216/59290
Iteration: 51217/59290
Iteration: 51218/59290
Iteration: 51219/59290
Iteration: 51220/59290
Iteration: 51221/59290
Iteration: 51222/59290
Iteration: 51224/59290

 86%|████████▋ | 51206/59290 [39:54<02:54, 46.26it/s]

Iteration: 51225/59290
Iteration: 51226/59290
Iteration: 51227/59290
Iteration: 51228/59290
Iteration: 51229/59290
Iteration: 51230/59290
Iteration: 51231/59290
Iteration: 51232/59290

 86%|████████▋ | 51214/59290 [39:55<03:22, 39.93it/s]

Iteration: 51233/59290
Iteration: 51234/59290
Iteration: 51235/59290
Iteration: 51236/59290
Iteration: 51237/59290
Iteration: 51238/59290
Iteration: 51239/59290
Iteration: 51240/59290
Iteration: 51241/59290
Iteration: 51242/59290
Iteration: 51243/59290
Iteration: 51244/59290
Iteration: 51245/59290
Iteration: 51246/59290
Iteration: 51247/59290
Iteration: 51248/59290
Iteration: 51249/59290
Iteration: 51250/59290
Iteration: 51251/59290
Iteration: 51252/59290
Iteration: 51253/59290
Iteration: 51254/59290
Iteration: 51255/59290
Iteration: 51256/59290

 86%|████████▋ | 51238/59290 [39:55<03:00, 44.63it/s]

Iteration: 51257/59290
Iteration: 51258/59290
Iteration: 51259/59290
Iteration: 51260/59290
Iteration: 51261/59290
Iteration: 51262/59290
Iteration: 51263/59290
Iteration: 51264/59290
Iteration: 51265/59290
Iteration: 51266/59290
Iteration: 51267/59290
Iteration: 51268/59290
Iteration: 51269/59290
Iteration: 51270/59290
Iteration: 51271/59290
Iteration: 51272/59290
Iteration: 51273/59290
Iteration: 51274/59290
Iteration: 51275/59290
Iteration: 51276/59290
Iteration: 51277/59290
Iteration: 51278/59290
Iteration: 51279/59290
Iteration: 51280/59290

 86%|████████▋ | 51262/59290 [39:55<02:43, 49.05it/s]

Iteration: 51281/59290
Iteration: 51282/59290
Iteration: 51283/59290
Iteration: 51284/59290
Iteration: 51285/59290
Iteration: 51286/59290
Iteration: 51287/59290
Iteration: 51288/59290
Iteration: 51289/59290
Iteration: 51290/59290
Iteration: 51291/59290
Iteration: 51292/59290
Iteration: 51293/59290
Iteration: 51294/59290
Iteration: 51295/59290
Iteration: 51296/59290
Iteration: 51297/59290
Iteration: 51298/59290
Iteration: 51299/59290
Iteration: 51300/59290
Iteration: 51301/59290
Iteration: 51302/59290
Iteration: 51303/59290
Iteration: 51304/59290

 87%|████████▋ | 51286/59290 [39:56<02:31, 52.97it/s]

Iteration: 51305/59290
Iteration: 51306/59290
Iteration: 51307/59290
Iteration: 51308/59290
Iteration: 51309/59290
Iteration: 51310/59290
Iteration: 51311/59290
Iteration: 51312/59290
Iteration: 51313/59290
Iteration: 51314/59290
Iteration: 51315/59290
Iteration: 51316/59290
Iteration: 51317/59290
Iteration: 51318/59290
Iteration: 51319/59290
Iteration: 51320/59290
Iteration: 51321/59290
Iteration: 51322/59290
Iteration: 51323/59290
Iteration: 51324/59290
Iteration: 51325/59290
Iteration: 51326/59290
Iteration: 51327/59290
Iteration: 51328/59290

 87%|████████▋ | 51310/59290 [39:56<02:22, 55.99it/s]

Iteration: 51329/59290
Iteration: 51330/59290
Iteration: 51331/59290
Iteration: 51332/59290
Iteration: 51333/59290
Iteration: 51334/59290
Iteration: 51335/59290
Iteration: 51336/59290
Iteration: 51337/59290
Iteration: 51338/59290
Iteration: 51339/59290
Iteration: 51340/59290
Iteration: 51341/59290
Iteration: 51342/59290
Iteration: 51343/59290
Iteration: 51344/59290
Iteration: 51345/59290
Iteration: 51346/59290
Iteration: 51347/59290
Iteration: 51348/59290
Iteration: 51349/59290
Iteration: 51350/59290
Iteration: 51351/59290
Iteration: 51352/59290

 87%|████████▋ | 51334/59290 [40:00<08:37, 15.36it/s]

Iteration: 51353/59290
Iteration: 51354/59290
Iteration: 51355/59290
Iteration: 51356/59290
Iteration: 51357/59290
Iteration: 51358/59290
Iteration: 51359/59290
Iteration: 51360/59290
Iteration: 51361/59290
Iteration: 51362/59290
Iteration: 51363/59290
Iteration: 51364/59290
Iteration: 51365/59290
Iteration: 51366/59290
Iteration: 51367/59290
Iteration: 51368/59290
Iteration: 51369/59290
Iteration: 51370/59290
Iteration: 51371/59290
Iteration: 51372/59290
Iteration: 51373/59290
Iteration: 51374/59290
Iteration: 51375/59290
Iteration: 51376/59290

 87%|████████▋ | 51358/59290 [40:01<06:50, 19.33it/s]

Iteration: 51377/59290
Iteration: 51378/59290
Iteration: 51379/59290
Iteration: 51380/59290
Iteration: 51381/59290
Iteration: 51382/59290
Iteration: 51383/59290
Iteration: 51384/59290
Iteration: 51385/59290
Iteration: 51386/59290
Iteration: 51387/59290
Iteration: 51388/59290
Iteration: 51389/59290
Iteration: 51390/59290
Iteration: 51391/59290
Iteration: 51392/59290
Iteration: 51393/59290
Iteration: 51394/59290
Iteration: 51395/59290
Iteration: 51396/59290
Iteration: 51397/59290
Iteration: 51398/59290
Iteration: 51399/59290
Iteration: 51400/59290

 87%|████████▋ | 51382/59290 [40:01<05:29, 24.03it/s]

Iteration: 51401/59290
Iteration: 51402/59290
Iteration: 51403/59290
Iteration: 51404/59290
Iteration: 51405/59290
Iteration: 51406/59290
Iteration: 51407/59290
Iteration: 51408/59290
Iteration: 51409/59290
Iteration: 51410/59290
Iteration: 51411/59290
Iteration: 51412/59290
Iteration: 51413/59290
Iteration: 51414/59290
Iteration: 51415/59290
Iteration: 51416/59290
Iteration: 51417/59290
Iteration: 51418/59290
Iteration: 51419/59290
Iteration: 51420/59290
Iteration: 51421/59290
Iteration: 51422/59290
Iteration: 51423/59290
Iteration: 51424/59290

 87%|████████▋ | 51406/59290 [40:02<05:26, 24.17it/s]

Iteration: 51425/59290
Iteration: 51426/59290
Iteration: 51427/59290
Iteration: 51428/59290
Iteration: 51429/59290
Iteration: 51430/59290
Iteration: 51431/59290
Iteration: 51432/59290
Iteration: 51433/59290
Iteration: 51434/59290
Iteration: 51435/59290
Iteration: 51436/59290
Iteration: 51437/59290
Iteration: 51438/59290
Iteration: 51439/59290
Iteration: 51440/59290
Iteration: 51441/59290
Iteration: 51442/59290
Iteration: 51443/59290
Iteration: 51444/59290
Iteration: 51445/59290
Iteration: 51446/59290
Iteration: 51447/59290
Iteration: 51448/59290

 87%|████████▋ | 51430/59290 [40:03<04:25, 29.65it/s]

Iteration: 51449/59290
Iteration: 51450/59290
Iteration: 51451/59290
Iteration: 51452/59290
Iteration: 51453/59290
Iteration: 51454/59290
Iteration: 51455/59290
Iteration: 51456/59290
Iteration: 51457/59290
Iteration: 51458/59290
Iteration: 51459/59290
Iteration: 51460/59290
Iteration: 51461/59290
Iteration: 51462/59290
Iteration: 51463/59290
Iteration: 51464/59290
Iteration: 51465/59290
Iteration: 51466/59290
Iteration: 51467/59290
Iteration: 51468/59290
Iteration: 51469/59290
Iteration: 51470/59290
Iteration: 51471/59290
Iteration: 51472/59290

 87%|████████▋ | 51454/59290 [40:03<03:42, 35.24it/s]

Iteration: 51473/59290
Iteration: 51474/59290
Iteration: 51475/59290
Iteration: 51476/59290
Iteration: 51477/59290
Iteration: 51478/59290
Iteration: 51479/59290
Iteration: 51480/59290
Iteration: 51481/59290
Iteration: 51482/59290
Iteration: 51483/59290
Iteration: 51484/59290
Iteration: 51485/59290
Iteration: 51486/59290
Iteration: 51487/59290
Iteration: 51488/59290
Iteration: 51489/59290
Iteration: 51490/59290
Iteration: 51491/59290
Iteration: 51492/59290
Iteration: 51493/59290
Iteration: 51494/59290
Iteration: 51495/59290
Iteration: 51496/59290

 87%|████████▋ | 51478/59290 [40:03<03:11, 40.80it/s]

Iteration: 51497/59290
Iteration: 51498/59290
Iteration: 51499/59290
Iteration: 51500/59290
Iteration: 51501/59290
Iteration: 51502/59290
Iteration: 51503/59290
Iteration: 51504/59290
Iteration: 51505/59290
Iteration: 51506/59290
Iteration: 51507/59290
Iteration: 51508/59290
Iteration: 51509/59290
Iteration: 51510/59290
Iteration: 51511/59290
Iteration: 51512/59290
Iteration: 51513/59290
Iteration: 51514/59290
Iteration: 51515/59290
Iteration: 51516/59290
Iteration: 51517/59290
Iteration: 51518/59290
Iteration: 51519/59290
Iteration: 51520/59290

 87%|████████▋ | 51502/59290 [40:04<02:50, 45.72it/s]

Iteration: 51521/59290
Iteration: 51522/59290
Iteration: 51523/59290
Iteration: 51524/59290
Iteration: 51525/59290
Iteration: 51526/59290
Iteration: 51527/59290
Iteration: 51528/59290
Iteration: 51529/59290
Iteration: 51530/59290
Iteration: 51531/59290
Iteration: 51532/59290
Iteration: 51533/59290
Iteration: 51534/59290
Iteration: 51535/59290
Iteration: 51536/59290
Iteration: 51537/59290
Iteration: 51538/59290
Iteration: 51539/59290
Iteration: 51540/59290
Iteration: 51541/59290
Iteration: 51542/59290
Iteration: 51543/59290
Iteration: 51544/59290

 87%|████████▋ | 51526/59290 [40:04<02:35, 49.94it/s]

Iteration: 51545/59290
Iteration: 51546/59290
Iteration: 51547/59290
Iteration: 51548/59290
Iteration: 51549/59290
Iteration: 51550/59290
Iteration: 51551/59290
Iteration: 51552/59290
Iteration: 51553/59290
Iteration: 51554/59290
Iteration: 51555/59290
Iteration: 51556/59290
Iteration: 51557/59290
Iteration: 51558/59290
Iteration: 51559/59290
Iteration: 51560/59290
Iteration: 51561/59290
Iteration: 51562/59290
Iteration: 51563/59290
Iteration: 51564/59290
Iteration: 51565/59290
Iteration: 51566/59290
Iteration: 51567/59290
Iteration: 51568/59290

 87%|████████▋ | 51550/59290 [40:04<02:24, 53.53it/s]

Iteration: 51569/59290
Iteration: 51570/59290
Iteration: 51571/59290
Iteration: 51572/59290
Iteration: 51573/59290
Iteration: 51574/59290
Iteration: 51575/59290
Iteration: 51576/59290
Iteration: 51577/59290
Iteration: 51578/59290
Iteration: 51579/59290
Iteration: 51580/59290
Iteration: 51581/59290
Iteration: 51582/59290
Iteration: 51583/59290
Iteration: 51584/59290
Iteration: 51585/59290
Iteration: 51586/59290
Iteration: 51587/59290
Iteration: 51588/59290
Iteration: 51589/59290
Iteration: 51590/59290
Iteration: 51591/59290
Iteration: 51592/59290

 87%|████████▋ | 51574/59290 [40:05<02:18, 55.63it/s]

Iteration: 51593/59290
Iteration: 51594/59290
Iteration: 51595/59290
Iteration: 51596/59290
Iteration: 51597/59290
Iteration: 51598/59290
Iteration: 51599/59290
Iteration: 51600/59290
Iteration: 51601/59290
Iteration: 51602/59290
Iteration: 51603/59290
Iteration: 51604/59290
Iteration: 51605/59290
Iteration: 51606/59290
Iteration: 51607/59290
Iteration: 51608/59290
Iteration: 51609/59290
Iteration: 51610/59290
Iteration: 51611/59290
Iteration: 51612/59290
Iteration: 51613/59290
Iteration: 51614/59290
Iteration: 51615/59290
Iteration: 51616/59290

 87%|████████▋ | 51598/59290 [40:05<02:13, 57.75it/s]

Iteration: 51617/59290
Iteration: 51618/59290
Iteration: 51619/59290
Iteration: 51620/59290
Iteration: 51621/59290
Iteration: 51622/59290
Iteration: 51623/59290
Iteration: 51624/59290
Iteration: 51625/59290
Iteration: 51626/59290
Iteration: 51627/59290
Iteration: 51628/59290
Iteration: 51629/59290
Iteration: 51630/59290
Iteration: 51631/59290
Iteration: 51632/59290
Iteration: 51633/59290
Iteration: 51634/59290
Iteration: 51635/59290
Iteration: 51636/59290
Iteration: 51637/59290
Iteration: 51638/59290
Iteration: 51639/59290
Iteration: 51640/59290

 87%|████████▋ | 51622/59290 [40:06<02:08, 59.66it/s]

Iteration: 51641/59290
Iteration: 51642/59290
Iteration: 51643/59290
Iteration: 51644/59290
Iteration: 51645/59290
Iteration: 51646/59290
Iteration: 51647/59290
Iteration: 51648/59290
Iteration: 51649/59290
Iteration: 51650/59290
Iteration: 51651/59290
Iteration: 51652/59290
Iteration: 51653/59290
Iteration: 51654/59290
Iteration: 51655/59290
Iteration: 51656/59290
Iteration: 51657/59290
Iteration: 51658/59290
Iteration: 51659/59290
Iteration: 51660/59290
Iteration: 51661/59290
Iteration: 51662/59290
Iteration: 51663/59290
Iteration: 51664/59290

 87%|████████▋ | 51646/59290 [40:06<02:07, 59.98it/s]

Iteration: 51665/59290
Iteration: 51666/59290
Iteration: 51667/59290
Iteration: 51668/59290
Iteration: 51669/59290
Iteration: 51670/59290
Iteration: 51671/59290
Iteration: 51672/59290
Iteration: 51673/59290
Iteration: 51674/59290
Iteration: 51675/59290
Iteration: 51676/59290
Iteration: 51677/59290
Iteration: 51678/59290
Iteration: 51679/59290
Iteration: 51680/59290
Iteration: 51681/59290
Iteration: 51682/59290
Iteration: 51683/59290
Iteration: 51684/59290
Iteration: 51685/59290
Iteration: 51686/59290
Iteration: 51687/59290
Iteration: 51688/59290

 87%|████████▋ | 51670/59290 [40:06<02:04, 61.21it/s]

Iteration: 51689/59290
Iteration: 51690/59290
Iteration: 51691/59290
Iteration: 51692/59290
Iteration: 51693/59290
Iteration: 51694/59290
Iteration: 51695/59290
Iteration: 51696/59290
Iteration: 51697/59290
Iteration: 51698/59290
Iteration: 51699/59290
Iteration: 51700/59290
Iteration: 51701/59290
Iteration: 51702/59290
Iteration: 51703/59290
Iteration: 51704/59290
Iteration: 51705/59290
Iteration: 51706/59290
Iteration: 51707/59290
Iteration: 51708/59290
Iteration: 51709/59290
Iteration: 51710/59290
Iteration: 51711/59290
Iteration: 51712/59290

 87%|████████▋ | 51694/59290 [40:07<02:06, 60.09it/s]

Iteration: 51713/59290
Iteration: 51714/59290
Iteration: 51715/59290
Iteration: 51716/59290
Iteration: 51717/59290
Iteration: 51718/59290
Iteration: 51719/59290
Iteration: 51720/59290
Iteration: 51721/59290
Iteration: 51722/59290
Iteration: 51723/59290
Iteration: 51724/59290
Iteration: 51725/59290
Iteration: 51726/59290
Iteration: 51727/59290
Iteration: 51728/59290
Iteration: 51729/59290
Iteration: 51730/59290
Iteration: 51731/59290
Iteration: 51732/59290
Iteration: 51733/59290
Iteration: 51734/59290
Iteration: 51735/59290
Iteration: 51736/59290

 87%|████████▋ | 51718/59290 [40:07<02:03, 61.09it/s]

Iteration: 51737/59290
Iteration: 51738/59290
Iteration: 51739/59290
Iteration: 51740/59290
Iteration: 51741/59290
Iteration: 51742/59290
Iteration: 51743/59290
Iteration: 51744/59290
Iteration: 51745/59290
Iteration: 51746/59290
Iteration: 51747/59290
Iteration: 51748/59290
Iteration: 51749/59290
Iteration: 51750/59290
Iteration: 51751/59290
Iteration: 51752/59290
Iteration: 51753/59290
Iteration: 51754/59290
Iteration: 51755/59290
Iteration: 51756/59290
Iteration: 51757/59290
Iteration: 51758/59290
Iteration: 51759/59290
Iteration: 51760/59290

 87%|████████▋ | 51742/59290 [40:08<02:02, 61.84it/s]

Iteration: 51761/59290
Iteration: 51762/59290
Iteration: 51763/59290
Iteration: 51764/59290
Iteration: 51765/59290
Iteration: 51766/59290
Iteration: 51767/59290
Iteration: 51768/59290
Iteration: 51769/59290
Iteration: 51770/59290
Iteration: 51771/59290
Iteration: 51772/59290
Iteration: 51773/59290
Iteration: 51774/59290
Iteration: 51775/59290
Iteration: 51776/59290
Iteration: 51777/59290
Iteration: 51778/59290
Iteration: 51779/59290
Iteration: 51780/59290
Iteration: 51781/59290
Iteration: 51782/59290
Iteration: 51783/59290
Iteration: 51784/59290

 87%|████████▋ | 51766/59290 [40:08<02:02, 61.48it/s]

Iteration: 51785/59290
Iteration: 51786/59290
Iteration: 51787/59290
Iteration: 51788/59290
Iteration: 51789/59290
Iteration: 51790/59290
Iteration: 51791/59290
Iteration: 51792/59290
Iteration: 51793/59290
Iteration: 51794/59290
Iteration: 51795/59290
Iteration: 51796/59290
Iteration: 51797/59290
Iteration: 51798/59290
Iteration: 51799/59290
Iteration: 51800/59290
Iteration: 51801/59290
Iteration: 51802/59290
Iteration: 51803/59290
Iteration: 51804/59290
Iteration: 51805/59290
Iteration: 51806/59290
Iteration: 51807/59290
Iteration: 51808/59290

 87%|████████▋ | 51790/59290 [40:10<03:50, 32.57it/s]

Iteration: 51809/59290
Iteration: 51810/59290
Iteration: 51811/59290
Iteration: 51812/59290
Iteration: 51813/59290
Iteration: 51814/59290
Iteration: 51815/59290
Iteration: 51816/59290
Iteration: 51817/59290
Iteration: 51818/59290
Iteration: 51819/59290
Iteration: 51820/59290
Iteration: 51821/59290
Iteration: 51822/59290
Iteration: 51823/59290
Iteration: 51824/59290
Iteration: 51825/59290
Iteration: 51826/59290
Iteration: 51827/59290
Iteration: 51828/59290
Iteration: 51829/59290
Iteration: 51830/59290
Iteration: 51831/59290
Iteration: 51832/59290

 87%|████████▋ | 51814/59290 [40:12<06:51, 18.16it/s]

Iteration: 51833/59290
Iteration: 51834/59290
Iteration: 51835/59290
Iteration: 51836/59290
Iteration: 51837/59290
Iteration: 51838/59290
Iteration: 51839/59290
Iteration: 51840/59290
Iteration: 51841/59290
Iteration: 51842/59290
Iteration: 51843/59290
Iteration: 51844/59290
Iteration: 51845/59290
Iteration: 51846/59290
Iteration: 51847/59290
Iteration: 51848/59290
Iteration: 51849/59290
Iteration: 51850/59290
Iteration: 51851/59290
Iteration: 51852/59290
Iteration: 51853/59290
Iteration: 51854/59290
Iteration: 51855/59290
Iteration: 51856/59290

 87%|████████▋ | 51838/59290 [40:13<05:26, 22.81it/s]

Iteration: 51857/59290
Iteration: 51858/59290
Iteration: 51859/59290
Iteration: 51860/59290
Iteration: 51861/59290
Iteration: 51862/59290
Iteration: 51863/59290
Iteration: 51864/59290
Iteration: 51865/59290
Iteration: 51866/59290
Iteration: 51867/59290
Iteration: 51868/59290
Iteration: 51869/59290
Iteration: 51870/59290
Iteration: 51871/59290
Iteration: 51872/59290
Iteration: 51873/59290
Iteration: 51874/59290
Iteration: 51875/59290
Iteration: 51876/59290
Iteration: 51877/59290
Iteration: 51878/59290
Iteration: 51879/59290
Iteration: 51880/59290

 87%|████████▋ | 51862/59290 [40:13<05:07, 24.18it/s]

Iteration: 51881/59290
Iteration: 51882/59290
Iteration: 51883/59290
Iteration: 51884/59290
Iteration: 51885/59290
Iteration: 51886/59290
Iteration: 51887/59290
Iteration: 51888/59290
Iteration: 51889/59290
Iteration: 51890/59290
Iteration: 51891/59290
Iteration: 51892/59290
Iteration: 51893/59290
Iteration: 51894/59290
Iteration: 51895/59290
Iteration: 51896/59290
Iteration: 51897/59290
Iteration: 51898/59290
Iteration: 51899/59290
Iteration: 51900/59290
Iteration: 51901/59290
Iteration: 51902/59290
Iteration: 51903/59290
Iteration: 51904/59290

 88%|████████▊ | 51886/59290 [40:14<04:10, 29.59it/s]

Iteration: 51905/59290
Iteration: 51906/59290
Iteration: 51907/59290
Iteration: 51908/59290
Iteration: 51909/59290
Iteration: 51910/59290
Iteration: 51911/59290
Iteration: 51912/59290
Iteration: 51913/59290
Iteration: 51914/59290
Iteration: 51915/59290
Iteration: 51916/59290
Iteration: 51917/59290
Iteration: 51918/59290
Iteration: 51919/59290
Iteration: 51920/59290
Iteration: 51921/59290
Iteration: 51922/59290
Iteration: 51923/59290
Iteration: 51924/59290
Iteration: 51925/59290
Iteration: 51926/59290
Iteration: 51927/59290
Iteration: 51928/59290

 88%|████████▊ | 51910/59290 [40:14<03:30, 35.07it/s]

Iteration: 51929/59290
Iteration: 51930/59290
Iteration: 51931/59290
Iteration: 51932/59290
Iteration: 51933/59290
Iteration: 51934/59290
Iteration: 51935/59290
Iteration: 51936/59290
Iteration: 51937/59290
Iteration: 51938/59290
Iteration: 51939/59290
Iteration: 51940/59290
Iteration: 51941/59290
Iteration: 51942/59290
Iteration: 51943/59290
Iteration: 51944/59290
Iteration: 51945/59290
Iteration: 51946/59290
Iteration: 51947/59290
Iteration: 51948/59290
Iteration: 51949/59290
Iteration: 51950/59290
Iteration: 51951/59290
Iteration: 51952/59290

 88%|████████▊ | 51934/59290 [40:15<03:01, 40.61it/s]

Iteration: 51953/59290
Iteration: 51954/59290
Iteration: 51955/59290
Iteration: 51956/59290
Iteration: 51957/59290
Iteration: 51958/59290
Iteration: 51959/59290
Iteration: 51960/59290
Iteration: 51961/59290
Iteration: 51962/59290
Iteration: 51963/59290
Iteration: 51964/59290
Iteration: 51965/59290
Iteration: 51966/59290
Iteration: 51967/59290
Iteration: 51968/59290
Iteration: 51969/59290
Iteration: 51970/59290
Iteration: 51971/59290
Iteration: 51972/59290
Iteration: 51973/59290
Iteration: 51974/59290
Iteration: 51975/59290
Iteration: 51976/59290

 88%|████████▊ | 51958/59290 [40:15<02:43, 44.79it/s]

Iteration: 51977/59290
Iteration: 51978/59290
Iteration: 51979/59290
Iteration: 51980/59290
Iteration: 51981/59290
Iteration: 51982/59290
Iteration: 51983/59290
Iteration: 51984/59290
Iteration: 51985/59290
Iteration: 51986/59290
Iteration: 51987/59290
Iteration: 51988/59290
Iteration: 51989/59290
Iteration: 51990/59290
Iteration: 51991/59290
Iteration: 51992/59290
Iteration: 51993/59290
Iteration: 51994/59290
Iteration: 51995/59290
Iteration: 51996/59290
Iteration: 51997/59290
Iteration: 51998/59290
Iteration: 51999/59290
Iteration: 52000/59290

 88%|████████▊ | 51982/59290 [40:15<02:28, 49.31it/s]

Iteration: 52001/59290
Iteration: 52002/59290
Iteration: 52003/59290
Iteration: 52004/59290
Iteration: 52005/59290
Iteration: 52006/59290
Iteration: 52007/59290
Iteration: 52008/59290
Iteration: 52009/59290
Iteration: 52010/59290
Iteration: 52011/59290
Iteration: 52012/59290
Iteration: 52013/59290
Iteration: 52014/59290
Iteration: 52015/59290
Iteration: 52016/59290
Iteration: 52017/59290
Iteration: 52018/59290
Iteration: 52019/59290
Iteration: 52020/59290
Iteration: 52021/59290
Iteration: 52022/59290
Iteration: 52023/59290
Iteration: 52024/59290

 88%|████████▊ | 52006/59290 [40:16<02:18, 52.58it/s]

Iteration: 52025/59290
Iteration: 52026/59290
Iteration: 52027/59290
Iteration: 52028/59290
Iteration: 52029/59290
Iteration: 52030/59290
Iteration: 52031/59290
Iteration: 52032/59290
Iteration: 52033/59290
Iteration: 52034/59290
Iteration: 52035/59290
Iteration: 52036/59290
Iteration: 52037/59290
Iteration: 52038/59290
Iteration: 52039/59290
Iteration: 52040/59290
Iteration: 52041/59290
Iteration: 52042/59290
Iteration: 52043/59290
Iteration: 52044/59290
Iteration: 52045/59290
Iteration: 52046/59290
Iteration: 52047/59290
Iteration: 52048/59290

 88%|████████▊ | 52030/59290 [40:16<02:10, 55.51it/s]

Iteration: 52049/59290
Iteration: 52050/59290
Iteration: 52051/59290
Iteration: 52052/59290
Iteration: 52053/59290
Iteration: 52054/59290
Iteration: 52055/59290
Iteration: 52056/59290
Iteration: 52057/59290
Iteration: 52058/59290
Iteration: 52059/59290
Iteration: 52060/59290
Iteration: 52061/59290
Iteration: 52062/59290
Iteration: 52063/59290
Iteration: 52064/59290
Iteration: 52065/59290
Iteration: 52066/59290
Iteration: 52067/59290
Iteration: 52068/59290
Iteration: 52069/59290
Iteration: 52070/59290
Iteration: 52071/59290
Iteration: 52072/59290

 88%|████████▊ | 52054/59290 [40:17<02:05, 57.76it/s]

Iteration: 52073/59290
Iteration: 52074/59290
Iteration: 52075/59290
Iteration: 52076/59290
Iteration: 52077/59290
Iteration: 52078/59290
Iteration: 52079/59290
Iteration: 52080/59290
Iteration: 52081/59290
Iteration: 52082/59290
Iteration: 52083/59290
Iteration: 52084/59290
Iteration: 52085/59290
Iteration: 52086/59290
Iteration: 52087/59290
Iteration: 52088/59290
Iteration: 52089/59290
Iteration: 52090/59290
Iteration: 52091/59290
Iteration: 52092/59290
Iteration: 52093/59290
Iteration: 52094/59290
Iteration: 52095/59290
Iteration: 52096/59290

 88%|████████▊ | 52078/59290 [40:17<02:07, 56.68it/s]

Iteration: 52097/59290
Iteration: 52098/59290
Iteration: 52099/59290
Iteration: 52100/59290
Iteration: 52101/59290
Iteration: 52102/59290
Iteration: 52103/59290
Iteration: 52104/59290
Iteration: 52105/59290
Iteration: 52106/59290
Iteration: 52107/59290
Iteration: 52108/59290
Iteration: 52109/59290
Iteration: 52110/59290
Iteration: 52111/59290
Iteration: 52112/59290
Iteration: 52113/59290
Iteration: 52114/59290
Iteration: 52115/59290
Iteration: 52116/59290
Iteration: 52117/59290
Iteration: 52118/59290
Iteration: 52119/59290
Iteration: 52120/59290

 88%|████████▊ | 52102/59290 [40:18<03:41, 32.38it/s]

Iteration: 52121/59290
Iteration: 52122/59290
Iteration: 52123/59290
Iteration: 52124/59290
Iteration: 52125/59290
Iteration: 52126/59290
Iteration: 52127/59290
Iteration: 52128/59290
Iteration: 52129/59290
Iteration: 52130/59290
Iteration: 52131/59290
Iteration: 52132/59290
Iteration: 52133/59290
Iteration: 52134/59290
Iteration: 52135/59290
Iteration: 52136/59290
Iteration: 52137/59290
Iteration: 52138/59290
Iteration: 52139/59290
Iteration: 52140/59290
Iteration: 52141/59290
Iteration: 52142/59290
Iteration: 52143/59290
Iteration: 52144/59290

 88%|████████▊ | 52126/59290 [40:21<06:15, 19.08it/s]

Iteration: 52145/59290
Iteration: 52146/59290
Iteration: 52147/59290
Iteration: 52148/59290
Iteration: 52149/59290
Iteration: 52150/59290
Iteration: 52151/59290
Iteration: 52152/59290
Iteration: 52153/59290
Iteration: 52154/59290
Iteration: 52155/59290
Iteration: 52156/59290
Iteration: 52157/59290
Iteration: 52158/59290
Iteration: 52159/59290
Iteration: 52160/59290
Iteration: 52161/59290
Iteration: 52162/59290
Iteration: 52163/59290
Iteration: 52164/59290
Iteration: 52165/59290
Iteration: 52166/59290
Iteration: 52167/59290
Iteration: 52168/59290

 88%|████████▊ | 52150/59290 [40:22<05:31, 21.56it/s]

Iteration: 52169/59290
Iteration: 52170/59290
Iteration: 52171/59290
Iteration: 52172/59290
Iteration: 52173/59290
Iteration: 52174/59290
Iteration: 52175/59290
Iteration: 52176/59290
Iteration: 52177/59290
Iteration: 52178/59290
Iteration: 52179/59290
Iteration: 52180/59290
Iteration: 52181/59290
Iteration: 52182/59290
Iteration: 52183/59290
Iteration: 52184/59290
Iteration: 52185/59290
Iteration: 52186/59290
Iteration: 52187/59290
Iteration: 52188/59290
Iteration: 52189/59290
Iteration: 52190/59290
Iteration: 52191/59290
Iteration: 52192/59290

 88%|████████▊ | 52174/59290 [40:22<04:30, 26.28it/s]

Iteration: 52193/59290
Iteration: 52194/59290
Iteration: 52195/59290
Iteration: 52196/59290
Iteration: 52197/59290
Iteration: 52198/59290
Iteration: 52199/59290
Iteration: 52200/59290
Iteration: 52201/59290
Iteration: 52202/59290
Iteration: 52203/59290
Iteration: 52204/59290
Iteration: 52205/59290
Iteration: 52206/59290
Iteration: 52207/59290
Iteration: 52208/59290
Iteration: 52209/59290
Iteration: 52210/59290
Iteration: 52211/59290
Iteration: 52212/59290
Iteration: 52213/59290
Iteration: 52214/59290
Iteration: 52215/59290
Iteration: 52216/59290

 88%|████████▊ | 52198/59290 [40:23<03:42, 31.87it/s]

Iteration: 52217/59290
Iteration: 52218/59290
Iteration: 52219/59290
Iteration: 52220/59290
Iteration: 52221/59290
Iteration: 52222/59290
Iteration: 52223/59290
Iteration: 52224/59290
Iteration: 52225/59290
Iteration: 52226/59290
Iteration: 52227/59290
Iteration: 52228/59290
Iteration: 52229/59290
Iteration: 52230/59290
Iteration: 52231/59290
Iteration: 52232/59290
Iteration: 52233/59290
Iteration: 52234/59290
Iteration: 52235/59290
Iteration: 52236/59290
Iteration: 52237/59290
Iteration: 52238/59290
Iteration: 52239/59290
Iteration: 52240/59290

 88%|████████▊ | 52222/59290 [40:24<05:09, 22.81it/s]

Iteration: 52241/59290
Iteration: 52242/59290
Iteration: 52243/59290
Iteration: 52244/59290
Iteration: 52245/59290
Iteration: 52246/59290
Iteration: 52247/59290
Iteration: 52248/59290
Iteration: 52249/59290
Iteration: 52250/59290
Iteration: 52251/59290
Iteration: 52252/59290
Iteration: 52253/59290
Iteration: 52254/59290
Iteration: 52255/59290
Iteration: 52256/59290
Iteration: 52257/59290
Iteration: 52258/59290
Iteration: 52259/59290
Iteration: 52260/59290
Iteration: 52261/59290
Iteration: 52262/59290
Iteration: 52263/59290
Iteration: 52264/59290

 88%|████████▊ | 52246/59290 [40:27<08:07, 14.45it/s]

Iteration: 52265/59290
Iteration: 52266/59290
Iteration: 52267/59290
Iteration: 52268/59290
Iteration: 52269/59290
Iteration: 52270/59290
Iteration: 52271/59290
Iteration: 52272/59290
Iteration: 52273/59290
Iteration: 52274/59290
Iteration: 52275/59290
Iteration: 52276/59290
Iteration: 52277/59290
Iteration: 52278/59290
Iteration: 52279/59290
Iteration: 52280/59290
Iteration: 52281/59290
Iteration: 52282/59290
Iteration: 52283/59290
Iteration: 52284/59290
Iteration: 52285/59290
Iteration: 52286/59290
Iteration: 52287/59290
Iteration: 52288/59290

 88%|████████▊ | 52270/59290 [40:28<06:22, 18.34it/s]

Iteration: 52289/59290
Iteration: 52290/59290
Iteration: 52291/59290
Iteration: 52292/59290
Iteration: 52293/59290
Iteration: 52294/59290
Iteration: 52295/59290
Iteration: 52296/59290
Iteration: 52297/59290
Iteration: 52298/59290
Iteration: 52299/59290
Iteration: 52300/59290
Iteration: 52301/59290
Iteration: 52302/59290
Iteration: 52303/59290
Iteration: 52304/59290
Iteration: 52305/59290
Iteration: 52306/59290
Iteration: 52307/59290
Iteration: 52308/59290
Iteration: 52309/59290
Iteration: 52310/59290
Iteration: 52311/59290
Iteration: 52312/59290

 88%|████████▊ | 52294/59290 [40:28<05:04, 22.98it/s]

Iteration: 52313/59290
Iteration: 52314/59290
Iteration: 52315/59290
Iteration: 52316/59290
Iteration: 52317/59290
Iteration: 52318/59290
Iteration: 52319/59290
Iteration: 52320/59290
Iteration: 52321/59290
Iteration: 52322/59290
Iteration: 52323/59290
Iteration: 52324/59290
Iteration: 52325/59290
Iteration: 52326/59290
Iteration: 52327/59290
Iteration: 52328/59290
Iteration: 52329/59290
Iteration: 52330/59290
Iteration: 52331/59290
Iteration: 52332/59290
Iteration: 52333/59290
Iteration: 52334/59290
Iteration: 52335/59290
Iteration: 52336/59290

 88%|████████▊ | 52318/59290 [40:29<04:09, 27.99it/s]

Iteration: 52337/59290
Iteration: 52338/59290
Iteration: 52339/59290
Iteration: 52340/59290
Iteration: 52341/59290
Iteration: 52342/59290
Iteration: 52343/59290
Iteration: 52344/59290
Iteration: 52345/59290
Iteration: 52346/59290
Iteration: 52347/59290
Iteration: 52348/59290
Iteration: 52349/59290
Iteration: 52350/59290
Iteration: 52351/59290
Iteration: 52352/59290
Iteration: 52353/59290
Iteration: 52354/59290
Iteration: 52355/59290
Iteration: 52356/59290
Iteration: 52357/59290
Iteration: 52358/59290
Iteration: 52359/59290
Iteration: 52360/59290

 88%|████████▊ | 52342/59290 [40:29<03:29, 33.14it/s]

Iteration: 52361/59290
Iteration: 52362/59290
Iteration: 52363/59290
Iteration: 52364/59290
Iteration: 52365/59290
Iteration: 52366/59290
Iteration: 52367/59290
Iteration: 52368/59290
Iteration: 52369/59290
Iteration: 52370/59290
Iteration: 52371/59290
Iteration: 52372/59290
Iteration: 52373/59290
Iteration: 52374/59290
Iteration: 52375/59290
Iteration: 52376/59290
Iteration: 52377/59290
Iteration: 52378/59290
Iteration: 52379/59290
Iteration: 52380/59290
Iteration: 52381/59290
Iteration: 52382/59290
Iteration: 52383/59290
Iteration: 52384/59290

 88%|████████▊ | 52366/59290 [40:30<03:00, 38.45it/s]

Iteration: 52385/59290
Iteration: 52386/59290
Iteration: 52387/59290
Iteration: 52388/59290
Iteration: 52389/59290
Iteration: 52390/59290
Iteration: 52391/59290
Iteration: 52392/59290
Iteration: 52393/59290
Iteration: 52394/59290
Iteration: 52395/59290
Iteration: 52396/59290
Iteration: 52397/59290
Iteration: 52398/59290
Iteration: 52399/59290
Iteration: 52400/59290
Iteration: 52401/59290
Iteration: 52402/59290
Iteration: 52403/59290
Iteration: 52404/59290
Iteration: 52405/59290
Iteration: 52406/59290
Iteration: 52407/59290
Iteration: 52408/59290

 88%|████████▊ | 52390/59290 [40:30<02:38, 43.64it/s]

Iteration: 52409/59290
Iteration: 52410/59290
Iteration: 52411/59290
Iteration: 52412/59290
Iteration: 52413/59290
Iteration: 52414/59290
Iteration: 52415/59290
Iteration: 52416/59290
Iteration: 52417/59290
Iteration: 52418/59290
Iteration: 52419/59290
Iteration: 52420/59290
Iteration: 52421/59290
Iteration: 52422/59290
Iteration: 52423/59290
Iteration: 52424/59290
Iteration: 52425/59290
Iteration: 52426/59290
Iteration: 52427/59290
Iteration: 52428/59290
Iteration: 52429/59290
Iteration: 52430/59290
Iteration: 52431/59290
Iteration: 52432/59290

 88%|████████▊ | 52414/59290 [40:30<02:22, 48.29it/s]

Iteration: 52433/59290
Iteration: 52434/59290
Iteration: 52435/59290
Iteration: 52436/59290
Iteration: 52437/59290
Iteration: 52438/59290
Iteration: 52439/59290
Iteration: 52440/59290
Iteration: 52441/59290
Iteration: 52442/59290
Iteration: 52443/59290
Iteration: 52444/59290
Iteration: 52445/59290
Iteration: 52446/59290
Iteration: 52447/59290
Iteration: 52448/59290
Iteration: 52449/59290
Iteration: 52450/59290
Iteration: 52451/59290
Iteration: 52452/59290
Iteration: 52453/59290
Iteration: 52454/59290
Iteration: 52455/59290
Iteration: 52456/59290

 88%|████████▊ | 52438/59290 [40:31<02:11, 52.18it/s]

Iteration: 52457/59290
Iteration: 52458/59290
Iteration: 52459/59290
Iteration: 52460/59290
Iteration: 52461/59290
Iteration: 52462/59290
Iteration: 52463/59290
Iteration: 52464/59290
Iteration: 52465/59290
Iteration: 52466/59290
Iteration: 52467/59290
Iteration: 52468/59290
Iteration: 52469/59290
Iteration: 52470/59290
Iteration: 52471/59290
Iteration: 52472/59290
Iteration: 52473/59290
Iteration: 52474/59290
Iteration: 52475/59290
Iteration: 52476/59290
Iteration: 52477/59290
Iteration: 52478/59290
Iteration: 52479/59290
Iteration: 52480/59290

 88%|████████▊ | 52462/59290 [41:03<47:47,  2.38it/s]

Iteration: 52481/59290
Iteration: 52482/59290
Iteration: 52483/59290
Iteration: 52484/59290
Iteration: 52485/59290
Iteration: 52486/59290
Iteration: 52487/59290
Iteration: 52488/59290
Iteration: 52489/59290
Iteration: 52490/59290
Iteration: 52491/59290
Iteration: 52492/59290
Iteration: 52493/59290
Iteration: 52494/59290
Iteration: 52495/59290
Iteration: 52496/59290
Iteration: 52497/59290
Iteration: 52498/59290
Iteration: 52499/59290
Iteration: 52500/59290
Iteration: 52501/59290
Iteration: 52502/59290
Iteration: 52503/59290
Iteration: 52504/59290

 89%|████████▊ | 52486/59290 [41:04<33:52,  3.35it/s]

Iteration: 52505/59290
Iteration: 52506/59290
Iteration: 52507/59290
Iteration: 52508/59290
Iteration: 52509/59290
Iteration: 52510/59290
Iteration: 52511/59290
Iteration: 52512/59290
Iteration: 52513/59290
Iteration: 52514/59290
Iteration: 52515/59290
Iteration: 52516/59290
Iteration: 52517/59290
Iteration: 52518/59290
Iteration: 52519/59290
Iteration: 52520/59290
Iteration: 52521/59290
Iteration: 52522/59290
Iteration: 52523/59290
Iteration: 52524/59290
Iteration: 52525/59290
Iteration: 52526/59290
Iteration: 52527/59290
Iteration: 52528/59290

 89%|████████▊ | 52510/59290 [41:04<24:09,  4.68it/s]

Iteration: 52529/59290
Iteration: 52530/59290
Iteration: 52531/59290
Iteration: 52532/59290
Iteration: 52533/59290
Iteration: 52534/59290
Iteration: 52535/59290
Iteration: 52536/59290
Iteration: 52537/59290
Iteration: 52538/59290
Iteration: 52539/59290
Iteration: 52540/59290
Iteration: 52541/59290
Iteration: 52542/59290
Iteration: 52543/59290
Iteration: 52544/59290
Iteration: 52545/59290
Iteration: 52546/59290
Iteration: 52547/59290
Iteration: 52548/59290
Iteration: 52549/59290
Iteration: 52550/59290
Iteration: 52551/59290
Iteration: 52552/59290

 89%|████████▊ | 52534/59290 [41:04<17:22,  6.48it/s]

Iteration: 52553/59290
Iteration: 52554/59290
Iteration: 52555/59290
Iteration: 52556/59290
Iteration: 52557/59290
Iteration: 52558/59290
Iteration: 52559/59290
Iteration: 52560/59290
Iteration: 52561/59290
Iteration: 52562/59290
Iteration: 52563/59290
Iteration: 52564/59290
Iteration: 52565/59290
Iteration: 52566/59290
Iteration: 52567/59290
Iteration: 52568/59290
Iteration: 52569/59290
Iteration: 52570/59290
Iteration: 52571/59290
Iteration: 52572/59290
Iteration: 52573/59290
Iteration: 52574/59290
Iteration: 52575/59290
Iteration: 52576/59290

 89%|████████▊ | 52558/59290 [41:05<12:40,  8.85it/s]

Iteration: 52577/59290
Iteration: 52578/59290
Iteration: 52579/59290
Iteration: 52580/59290
Iteration: 52581/59290
Iteration: 52582/59290
Iteration: 52583/59290
Iteration: 52584/59290
Iteration: 52585/59290
Iteration: 52586/59290
Iteration: 52587/59290
Iteration: 52588/59290
Iteration: 52589/59290
Iteration: 52590/59290
Iteration: 52591/59290
Iteration: 52592/59290
Iteration: 52593/59290
Iteration: 52594/59290
Iteration: 52595/59290
Iteration: 52596/59290
Iteration: 52597/59290
Iteration: 52598/59290
Iteration: 52599/59290
Iteration: 52600/59290

 89%|████████▊ | 52582/59290 [41:05<09:26, 11.85it/s]

Iteration: 52601/59290
Iteration: 52602/59290
Iteration: 52603/59290
Iteration: 52604/59290
Iteration: 52605/59290
Iteration: 52606/59290
Iteration: 52607/59290
Iteration: 52608/59290
Iteration: 52609/59290
Iteration: 52610/59290
Iteration: 52611/59290
Iteration: 52612/59290
Iteration: 52613/59290
Iteration: 52614/59290
Iteration: 52615/59290
Iteration: 52616/59290
Iteration: 52617/59290
Iteration: 52618/59290
Iteration: 52619/59290
Iteration: 52620/59290
Iteration: 52621/59290
Iteration: 52622/59290
Iteration: 52623/59290
Iteration: 52624/59290

 89%|████████▊ | 52606/59290 [41:07<08:40, 12.83it/s]

Iteration: 52625/59290
Iteration: 52626/59290
Iteration: 52627/59290
Iteration: 52628/59290
Iteration: 52629/59290
Iteration: 52630/59290
Iteration: 52631/59290
Iteration: 52632/59290
Iteration: 52633/59290
Iteration: 52634/59290
Iteration: 52635/59290
Iteration: 52636/59290
Iteration: 52637/59290
Iteration: 52638/59290
Iteration: 52639/59290
Iteration: 52640/59290
Iteration: 52641/59290
Iteration: 52642/59290
Iteration: 52643/59290
Iteration: 52644/59290
Iteration: 52645/59290
Iteration: 52646/59290
Iteration: 52647/59290
Iteration: 52648/59290

 89%|████████▉ | 52630/59290 [41:09<09:31, 11.66it/s]

Iteration: 52649/59290
Iteration: 52650/59290
Iteration: 52651/59290
Iteration: 52652/59290
Iteration: 52653/59290
Iteration: 52654/59290
Iteration: 52655/59290
Iteration: 52656/59290
Iteration: 52657/59290
Iteration: 52658/59290
Iteration: 52659/59290
Iteration: 52660/59290
Iteration: 52661/59290
Iteration: 52662/59290
Iteration: 52663/59290
Iteration: 52664/59290
Iteration: 52665/59290
Iteration: 52666/59290
Iteration: 52667/59290
Iteration: 52668/59290
Iteration: 52669/59290
Iteration: 52670/59290
Iteration: 52671/59290
Iteration: 52672/59290

 89%|████████▉ | 52654/59290 [41:10<08:04, 13.69it/s]

Iteration: 52673/59290
Iteration: 52674/59290
Iteration: 52675/59290
Iteration: 52676/59290
Iteration: 52677/59290
Iteration: 52678/59290
Iteration: 52679/59290
Iteration: 52680/59290
Iteration: 52681/59290
Iteration: 52682/59290
Iteration: 52683/59290
Iteration: 52684/59290
Iteration: 52685/59290
Iteration: 52686/59290
Iteration: 52687/59290
Iteration: 52688/59290
Iteration: 52689/59290
Iteration: 52690/59290
Iteration: 52691/59290
Iteration: 52692/59290
Iteration: 52693/59290
Iteration: 52694/59290
Iteration: 52695/59290
Iteration: 52696/59290

 89%|████████▉ | 52678/59290 [41:11<06:11, 17.79it/s]

Iteration: 52697/59290
Iteration: 52698/59290
Iteration: 52699/59290
Iteration: 52700/59290
Iteration: 52701/59290
Iteration: 52702/59290
Iteration: 52703/59290
Iteration: 52704/59290
Iteration: 52705/59290
Iteration: 52706/59290
Iteration: 52707/59290
Iteration: 52708/59290
Iteration: 52709/59290
Iteration: 52710/59290
Iteration: 52711/59290
Iteration: 52712/59290
Iteration: 52713/59290
Iteration: 52714/59290
Iteration: 52715/59290
Iteration: 52716/59290
Iteration: 52717/59290
Iteration: 52718/59290
Iteration: 52719/59290
Iteration: 52720/59290

 89%|████████▉ | 52702/59290 [41:11<04:49, 22.73it/s]

Iteration: 52721/59290
Iteration: 52722/59290
Iteration: 52723/59290
Iteration: 52724/59290
Iteration: 52725/59290
Iteration: 52726/59290
Iteration: 52727/59290
Iteration: 52728/59290
Iteration: 52729/59290
Iteration: 52730/59290
Iteration: 52731/59290
Iteration: 52732/59290
Iteration: 52733/59290
Iteration: 52734/59290
Iteration: 52735/59290
Iteration: 52736/59290
Iteration: 52737/59290
Iteration: 52738/59290
Iteration: 52739/59290
Iteration: 52740/59290
Iteration: 52741/59290
Iteration: 52742/59290
Iteration: 52743/59290
Iteration: 52744/59290

 89%|████████▉ | 52726/59290 [41:11<03:53, 28.17it/s]

Iteration: 52745/59290
Iteration: 52746/59290
Iteration: 52747/59290
Iteration: 52748/59290
Iteration: 52749/59290
Iteration: 52750/59290
Iteration: 52751/59290
Iteration: 52752/59290
Iteration: 52753/59290
Iteration: 52754/59290
Iteration: 52755/59290
Iteration: 52756/59290
Iteration: 52757/59290
Iteration: 52758/59290
Iteration: 52759/59290
Iteration: 52760/59290
Iteration: 52761/59290
Iteration: 52762/59290
Iteration: 52763/59290
Iteration: 52764/59290
Iteration: 52765/59290
Iteration: 52766/59290
Iteration: 52767/59290
Iteration: 52768/59290

 89%|████████▉ | 52750/59290 [41:12<03:15, 33.52it/s]

Iteration: 52769/59290
Iteration: 52770/59290
Iteration: 52771/59290
Iteration: 52772/59290
Iteration: 52773/59290
Iteration: 52774/59290
Iteration: 52775/59290
Iteration: 52776/59290
Iteration: 52777/59290
Iteration: 52778/59290
Iteration: 52779/59290
Iteration: 52780/59290
Iteration: 52781/59290
Iteration: 52782/59290
Iteration: 52783/59290
Iteration: 52784/59290
Iteration: 52785/59290
Iteration: 52786/59290
Iteration: 52787/59290
Iteration: 52788/59290
Iteration: 52789/59290
Iteration: 52790/59290
Iteration: 52791/59290
Iteration: 52792/59290

 89%|████████▉ | 52774/59290 [41:12<02:46, 39.20it/s]

Iteration: 52793/59290
Iteration: 52794/59290
Iteration: 52795/59290
Iteration: 52796/59290
Iteration: 52797/59290
Iteration: 52798/59290
Iteration: 52799/59290
Iteration: 52800/59290
Iteration: 52801/59290
Iteration: 52802/59290
Iteration: 52803/59290
Iteration: 52804/59290
Iteration: 52805/59290
Iteration: 52806/59290
Iteration: 52807/59290
Iteration: 52808/59290
Iteration: 52809/59290
Iteration: 52810/59290
Iteration: 52811/59290
Iteration: 52812/59290
Iteration: 52813/59290
Iteration: 52814/59290
Iteration: 52815/59290
Iteration: 52816/59290

 89%|████████▉ | 52798/59290 [41:12<02:26, 44.23it/s]

Iteration: 52817/59290
Iteration: 52818/59290
Iteration: 52819/59290
Iteration: 52820/59290
Iteration: 52821/59290
Iteration: 52822/59290
Iteration: 52823/59290
Iteration: 52824/59290
Iteration: 52825/59290
Iteration: 52826/59290
Iteration: 52827/59290
Iteration: 52828/59290
Iteration: 52829/59290
Iteration: 52830/59290
Iteration: 52831/59290
Iteration: 52832/59290
Iteration: 52833/59290
Iteration: 52834/59290
Iteration: 52835/59290
Iteration: 52836/59290
Iteration: 52837/59290
Iteration: 52838/59290
Iteration: 52839/59290
Iteration: 52840/59290

 89%|████████▉ | 52822/59290 [41:13<02:12, 48.75it/s]

Iteration: 52841/59290
Iteration: 52842/59290
Iteration: 52843/59290
Iteration: 52844/59290
Iteration: 52845/59290
Iteration: 52846/59290
Iteration: 52847/59290
Iteration: 52848/59290
Iteration: 52849/59290
Iteration: 52850/59290
Iteration: 52851/59290
Iteration: 52852/59290
Iteration: 52853/59290
Iteration: 52854/59290
Iteration: 52855/59290
Iteration: 52856/59290
Iteration: 52857/59290
Iteration: 52858/59290
Iteration: 52859/59290
Iteration: 52860/59290
Iteration: 52861/59290
Iteration: 52862/59290
Iteration: 52863/59290
Iteration: 52864/59290

 89%|████████▉ | 52846/59290 [41:13<02:03, 52.37it/s]

Iteration: 52865/59290
Iteration: 52866/59290
Iteration: 52867/59290
Iteration: 52868/59290
Iteration: 52869/59290
Iteration: 52870/59290
Iteration: 52871/59290
Iteration: 52872/59290
Iteration: 52873/59290
Iteration: 52874/59290
Iteration: 52875/59290
Iteration: 52876/59290
Iteration: 52877/59290
Iteration: 52878/59290
Iteration: 52879/59290
Iteration: 52880/59290
Iteration: 52881/59290
Iteration: 52882/59290
Iteration: 52883/59290
Iteration: 52884/59290
Iteration: 52885/59290
Iteration: 52886/59290
Iteration: 52887/59290
Iteration: 52888/59290

 89%|████████▉ | 52870/59290 [41:14<01:56, 54.93it/s]

Iteration: 52889/59290
Iteration: 52890/59290
Iteration: 52891/59290
Iteration: 52892/59290
Iteration: 52893/59290
Iteration: 52894/59290
Iteration: 52895/59290
Iteration: 52896/59290
Iteration: 52897/59290
Iteration: 52898/59290
Iteration: 52899/59290
Iteration: 52900/59290
Iteration: 52901/59290
Iteration: 52902/59290
Iteration: 52903/59290
Iteration: 52904/59290
Iteration: 52905/59290
Iteration: 52906/59290
Iteration: 52907/59290
Iteration: 52908/59290
Iteration: 52909/59290
Iteration: 52910/59290
Iteration: 52911/59290
Iteration: 52912/59290

 89%|████████▉ | 52894/59290 [41:14<01:55, 55.32it/s]

Iteration: 52913/59290
Iteration: 52914/59290
Iteration: 52915/59290
Iteration: 52916/59290
Iteration: 52917/59290
Iteration: 52918/59290
Iteration: 52919/59290
Iteration: 52920/59290
Iteration: 52921/59290
Iteration: 52922/59290
Iteration: 52923/59290
Iteration: 52924/59290
Iteration: 52925/59290
Iteration: 52926/59290
Iteration: 52927/59290
Iteration: 52928/59290
Iteration: 52929/59290
Iteration: 52930/59290
Iteration: 52931/59290
Iteration: 52932/59290
Iteration: 52933/59290
Iteration: 52934/59290
Iteration: 52935/59290
Iteration: 52936/59290

 89%|████████▉ | 52918/59290 [41:16<03:24, 31.10it/s]

Iteration: 52937/59290
Iteration: 52938/59290
Iteration: 52939/59290
Iteration: 52940/59290
Iteration: 52941/59290
Iteration: 52942/59290
Iteration: 52943/59290
Iteration: 52944/59290
Iteration: 52945/59290
Iteration: 52946/59290
Iteration: 52947/59290
Iteration: 52948/59290
Iteration: 52949/59290
Iteration: 52950/59290
Iteration: 52951/59290
Iteration: 52952/59290
Iteration: 52953/59290
Iteration: 52954/59290
Iteration: 52955/59290
Iteration: 52956/59290
Iteration: 52957/59290
Iteration: 52958/59290
Iteration: 52959/59290
Iteration: 52960/59290

 89%|████████▉ | 52942/59290 [41:18<05:54, 17.89it/s]

Iteration: 52961/59290
Iteration: 52962/59290
Iteration: 52963/59290
Iteration: 52964/59290
Iteration: 52965/59290
Iteration: 52966/59290
Iteration: 52967/59290
Iteration: 52968/59290
Iteration: 52969/59290
Iteration: 52970/59290
Iteration: 52971/59290
Iteration: 52972/59290
Iteration: 52973/59290
Iteration: 52974/59290
Iteration: 52975/59290
Iteration: 52976/59290
Iteration: 52977/59290
Iteration: 52978/59290
Iteration: 52979/59290
Iteration: 52980/59290
Iteration: 52981/59290
Iteration: 52982/59290
Iteration: 52983/59290
Iteration: 52984/59290

 89%|████████▉ | 52966/59290 [41:19<05:03, 20.84it/s]

Iteration: 52985/59290
Iteration: 52986/59290
Iteration: 52987/59290
Iteration: 52988/59290
Iteration: 52989/59290
Iteration: 52990/59290
Iteration: 52991/59290
Iteration: 52992/59290
Iteration: 52993/59290
Iteration: 52994/59290
Iteration: 52995/59290
Iteration: 52996/59290
Iteration: 52997/59290
Iteration: 52998/59290
Iteration: 52999/59290
Iteration: 53000/59290
Iteration: 53001/59290
Iteration: 53002/59290
Iteration: 53003/59290
Iteration: 53004/59290
Iteration: 53005/59290
Iteration: 53006/59290
Iteration: 53007/59290
Iteration: 53008/59290

 89%|████████▉ | 52990/59290 [41:19<04:01, 26.08it/s]

Iteration: 53009/59290
Iteration: 53010/59290
Iteration: 53011/59290
Iteration: 53012/59290
Iteration: 53013/59290
Iteration: 53014/59290
Iteration: 53015/59290
Iteration: 53016/59290
Iteration: 53017/59290
Iteration: 53018/59290
Iteration: 53019/59290
Iteration: 53020/59290
Iteration: 53021/59290
Iteration: 53022/59290
Iteration: 53023/59290
Iteration: 53024/59290
Iteration: 53025/59290
Iteration: 53026/59290
Iteration: 53027/59290
Iteration: 53028/59290
Iteration: 53029/59290
Iteration: 53030/59290
Iteration: 53031/59290
Iteration: 53032/59290

 89%|████████▉ | 53014/59290 [41:20<03:18, 31.56it/s]

Iteration: 53033/59290
Iteration: 53034/59290
Iteration: 53035/59290
Iteration: 53036/59290
Iteration: 53037/59290
Iteration: 53038/59290
Iteration: 53039/59290
Iteration: 53040/59290
Iteration: 53041/59290
Iteration: 53042/59290
Iteration: 53043/59290
Iteration: 53044/59290
Iteration: 53045/59290
Iteration: 53046/59290
Iteration: 53047/59290
Iteration: 53048/59290
Iteration: 53049/59290
Iteration: 53050/59290
Iteration: 53051/59290
Iteration: 53052/59290
Iteration: 53053/59290
Iteration: 53054/59290
Iteration: 53055/59290
Iteration: 53056/59290

 89%|████████▉ | 53038/59290 [41:20<02:48, 37.17it/s]

Iteration: 53057/59290
Iteration: 53058/59290
Iteration: 53059/59290
Iteration: 53060/59290
Iteration: 53061/59290
Iteration: 53062/59290
Iteration: 53063/59290
Iteration: 53064/59290
Iteration: 53065/59290
Iteration: 53066/59290
Iteration: 53067/59290
Iteration: 53068/59290
Iteration: 53069/59290
Iteration: 53070/59290
Iteration: 53071/59290
Iteration: 53072/59290
Iteration: 53073/59290
Iteration: 53074/59290
Iteration: 53075/59290
Iteration: 53076/59290
Iteration: 53077/59290
Iteration: 53078/59290
Iteration: 53079/59290
Iteration: 53080/59290

 89%|████████▉ | 53062/59290 [41:22<04:09, 24.91it/s]

Iteration: 53081/59290
Iteration: 53082/59290
Iteration: 53083/59290
Iteration: 53084/59290
Iteration: 53085/59290
Iteration: 53086/59290
Iteration: 53087/59290
Iteration: 53088/59290
Iteration: 53089/59290
Iteration: 53090/59290
Iteration: 53091/59290
Iteration: 53092/59290
Iteration: 53093/59290
Iteration: 53094/59290
Iteration: 53095/59290
Iteration: 53096/59290
Iteration: 53097/59290
Iteration: 53098/59290
Iteration: 53099/59290
Iteration: 53100/59290
Iteration: 53101/59290
Iteration: 53102/59290
Iteration: 53103/59290
Iteration: 53104/59290

 90%|████████▉ | 53086/59290 [41:24<06:22, 16.20it/s]

Iteration: 53105/59290
Iteration: 53106/59290
Iteration: 53107/59290
Iteration: 53108/59290
Iteration: 53109/59290
Iteration: 53110/59290
Iteration: 53111/59290
Iteration: 53112/59290
Iteration: 53113/59290
Iteration: 53114/59290
Iteration: 53115/59290
Iteration: 53116/59290
Iteration: 53117/59290
Iteration: 53118/59290
Iteration: 53119/59290
Iteration: 53120/59290
Iteration: 53121/59290
Iteration: 53122/59290
Iteration: 53123/59290
Iteration: 53124/59290
Iteration: 53125/59290
Iteration: 53126/59290
Iteration: 53127/59290
Iteration: 53128/59290

 90%|████████▉ | 53110/59290 [41:25<05:24, 19.03it/s]

Iteration: 53129/59290
Iteration: 53130/59290
Iteration: 53131/59290
Iteration: 53132/59290
Iteration: 53133/59290
Iteration: 53134/59290
Iteration: 53135/59290
Iteration: 53136/59290
Iteration: 53137/59290
Iteration: 53138/59290
Iteration: 53139/59290
Iteration: 53140/59290
Iteration: 53141/59290
Iteration: 53142/59290
Iteration: 53143/59290
Iteration: 53144/59290
Iteration: 53145/59290
Iteration: 53146/59290
Iteration: 53147/59290
Iteration: 53148/59290
Iteration: 53149/59290
Iteration: 53150/59290
Iteration: 53151/59290
Iteration: 53152/59290

 90%|████████▉ | 53134/59290 [41:26<04:31, 22.66it/s]

Iteration: 53153/59290
Iteration: 53154/59290
Iteration: 53155/59290
Iteration: 53156/59290
Iteration: 53157/59290
Iteration: 53158/59290
Iteration: 53159/59290
Iteration: 53160/59290
Iteration: 53161/59290
Iteration: 53162/59290
Iteration: 53163/59290
Iteration: 53164/59290
Iteration: 53165/59290
Iteration: 53166/59290
Iteration: 53167/59290
Iteration: 53168/59290
Iteration: 53169/59290
Iteration: 53170/59290
Iteration: 53171/59290
Iteration: 53172/59290
Iteration: 53173/59290
Iteration: 53174/59290
Iteration: 53175/59290
Iteration: 53176/59290

 90%|████████▉ | 53158/59290 [41:26<03:43, 27.41it/s]

Iteration: 53177/59290
Iteration: 53178/59290
Iteration: 53179/59290
Iteration: 53180/59290
Iteration: 53181/59290
Iteration: 53182/59290
Iteration: 53183/59290
Iteration: 53184/59290
Iteration: 53185/59290
Iteration: 53186/59290
Iteration: 53187/59290
Iteration: 53188/59290
Iteration: 53189/59290
Iteration: 53190/59290
Iteration: 53191/59290
Iteration: 53192/59290
Iteration: 53193/59290
Iteration: 53194/59290
Iteration: 53195/59290
Iteration: 53196/59290
Iteration: 53197/59290
Iteration: 53198/59290
Iteration: 53199/59290
Iteration: 53200/59290

 90%|████████▉ | 53182/59290 [41:27<03:07, 32.63it/s]

Iteration: 53201/59290
Iteration: 53202/59290
Iteration: 53203/59290
Iteration: 53204/59290
Iteration: 53205/59290
Iteration: 53206/59290
Iteration: 53207/59290
Iteration: 53208/59290
Iteration: 53209/59290
Iteration: 53210/59290
Iteration: 53211/59290
Iteration: 53212/59290
Iteration: 53213/59290
Iteration: 53214/59290
Iteration: 53215/59290
Iteration: 53216/59290
Iteration: 53217/59290
Iteration: 53218/59290
Iteration: 53219/59290
Iteration: 53220/59290
Iteration: 53221/59290
Iteration: 53222/59290
Iteration: 53223/59290
Iteration: 53224/59290

 90%|████████▉ | 53206/59290 [41:27<02:40, 37.88it/s]

Iteration: 53225/59290
Iteration: 53226/59290
Iteration: 53227/59290
Iteration: 53228/59290
Iteration: 53229/59290
Iteration: 53230/59290
Iteration: 53231/59290
Iteration: 53232/59290
Iteration: 53233/59290
Iteration: 53234/59290
Iteration: 53235/59290
Iteration: 53236/59290
Iteration: 53237/59290
Iteration: 53238/59290
Iteration: 53239/59290
Iteration: 53240/59290
Iteration: 53241/59290
Iteration: 53242/59290
Iteration: 53243/59290
Iteration: 53244/59290
Iteration: 53245/59290
Iteration: 53246/59290
Iteration: 53247/59290
Iteration: 53248/59290

 90%|████████▉ | 53230/59290 [41:27<02:22, 42.61it/s]

Iteration: 53249/59290
Iteration: 53250/59290
Iteration: 53251/59290
Iteration: 53252/59290
Iteration: 53253/59290
Iteration: 53254/59290
Iteration: 53255/59290
Iteration: 53256/59290
Iteration: 53257/59290
Iteration: 53258/59290
Iteration: 53259/59290
Iteration: 53260/59290
Iteration: 53261/59290
Iteration: 53262/59290
Iteration: 53263/59290
Iteration: 53264/59290
Iteration: 53265/59290
Iteration: 53266/59290
Iteration: 53267/59290
Iteration: 53268/59290
Iteration: 53269/59290
Iteration: 53270/59290
Iteration: 53271/59290
Iteration: 53272/59290

 90%|████████▉ | 53254/59290 [41:28<02:09, 46.70it/s]

Iteration: 53273/59290
Iteration: 53274/59290
Iteration: 53275/59290
Iteration: 53276/59290
Iteration: 53277/59290
Iteration: 53278/59290
Iteration: 53279/59290
Iteration: 53280/59290
Iteration: 53281/59290
Iteration: 53282/59290
Iteration: 53283/59290
Iteration: 53284/59290
Iteration: 53285/59290
Iteration: 53286/59290
Iteration: 53287/59290
Iteration: 53288/59290
Iteration: 53289/59290
Iteration: 53290/59290
Iteration: 53291/59290
Iteration: 53292/59290
Iteration: 53293/59290
Iteration: 53294/59290
Iteration: 53295/59290
Iteration: 53296/59290

 90%|████████▉ | 53278/59290 [41:28<01:58, 50.54it/s]

Iteration: 53297/59290
Iteration: 53298/59290
Iteration: 53299/59290
Iteration: 53300/59290
Iteration: 53301/59290
Iteration: 53302/59290
Iteration: 53303/59290
Iteration: 53304/59290
Iteration: 53305/59290
Iteration: 53306/59290
Iteration: 53307/59290
Iteration: 53308/59290
Iteration: 53309/59290
Iteration: 53310/59290
Iteration: 53311/59290
Iteration: 53312/59290
Iteration: 53313/59290
Iteration: 53314/59290
Iteration: 53315/59290
Iteration: 53316/59290
Iteration: 53317/59290
Iteration: 53318/59290
Iteration: 53319/59290
Iteration: 53320/59290

 90%|████████▉ | 53302/59290 [41:29<01:51, 53.47it/s]

Iteration: 53321/59290
Iteration: 53322/59290
Iteration: 53323/59290
Iteration: 53324/59290
Iteration: 53325/59290
Iteration: 53326/59290
Iteration: 53327/59290
Iteration: 53328/59290
Iteration: 53329/59290
Iteration: 53330/59290
Iteration: 53331/59290
Iteration: 53332/59290
Iteration: 53333/59290
Iteration: 53334/59290
Iteration: 53335/59290
Iteration: 53336/59290
Iteration: 53337/59290
Iteration: 53338/59290
Iteration: 53339/59290
Iteration: 53340/59290
Iteration: 53341/59290
Iteration: 53342/59290
Iteration: 53343/59290
Iteration: 53344/59290

 90%|████████▉ | 53326/59290 [41:29<01:47, 55.50it/s]

Iteration: 53345/59290
Iteration: 53346/59290
Iteration: 53347/59290
Iteration: 53348/59290
Iteration: 53349/59290
Iteration: 53350/59290
Iteration: 53351/59290
Iteration: 53352/59290
Iteration: 53353/59290
Iteration: 53354/59290
Iteration: 53355/59290
Iteration: 53356/59290
Iteration: 53357/59290
Iteration: 53358/59290
Iteration: 53359/59290
Iteration: 53360/59290
Iteration: 53361/59290
Iteration: 53362/59290
Iteration: 53363/59290
Iteration: 53364/59290
Iteration: 53365/59290
Iteration: 53366/59290
Iteration: 53367/59290
Iteration: 53368/59290

 90%|████████▉ | 53350/59290 [41:29<01:42, 57.74it/s]

Iteration: 53369/59290
Iteration: 53370/59290
Iteration: 53371/59290
Iteration: 53372/59290
Iteration: 53373/59290
Iteration: 53374/59290
Iteration: 53375/59290
Iteration: 53376/59290
Iteration: 53377/59290
Iteration: 53378/59290
Iteration: 53379/59290
Iteration: 53380/59290
Iteration: 53381/59290
Iteration: 53382/59290
Iteration: 53383/59290
Iteration: 53384/59290
Iteration: 53385/59290
Iteration: 53386/59290
Iteration: 53387/59290
Iteration: 53388/59290
Iteration: 53389/59290
Iteration: 53390/59290
Iteration: 53391/59290
Iteration: 53392/59290

 90%|█████████ | 53374/59290 [41:30<01:39, 59.18it/s]

Iteration: 53393/59290
Iteration: 53394/59290
Iteration: 53395/59290
Iteration: 53396/59290
Iteration: 53397/59290
Iteration: 53398/59290
Iteration: 53399/59290
Iteration: 53400/59290
Iteration: 53401/59290
Iteration: 53402/59290
Iteration: 53403/59290
Iteration: 53404/59290
Iteration: 53405/59290
Iteration: 53406/59290
Iteration: 53407/59290
Iteration: 53408/59290
Iteration: 53409/59290
Iteration: 53410/59290
Iteration: 53411/59290
Iteration: 53412/59290
Iteration: 53413/59290
Iteration: 53414/59290
Iteration: 53415/59290
Iteration: 53416/59290

 90%|█████████ | 53398/59290 [41:30<01:38, 59.86it/s]

Iteration: 53417/59290
Iteration: 53418/59290
Iteration: 53419/59290
Iteration: 53420/59290
Iteration: 53421/59290
Iteration: 53422/59290
Iteration: 53423/59290
Iteration: 53424/59290
Iteration: 53425/59290
Iteration: 53426/59290
Iteration: 53427/59290
Iteration: 53428/59290
Iteration: 53429/59290
Iteration: 53430/59290
Iteration: 53431/59290
Iteration: 53432/59290
Iteration: 53433/59290
Iteration: 53434/59290
Iteration: 53435/59290
Iteration: 53436/59290
Iteration: 53437/59290
Iteration: 53438/59290
Iteration: 53439/59290
Iteration: 53440/59290

 90%|█████████ | 53422/59290 [41:31<01:36, 60.88it/s]

Iteration: 53441/59290
Iteration: 53442/59290
Iteration: 53443/59290
Iteration: 53444/59290
Iteration: 53445/59290
Iteration: 53446/59290
Iteration: 53447/59290
Iteration: 53448/59290
Iteration: 53449/59290
Iteration: 53450/59290
Iteration: 53451/59290
Iteration: 53452/59290
Iteration: 53453/59290
Iteration: 53454/59290
Iteration: 53455/59290
Iteration: 53456/59290
Iteration: 53457/59290
Iteration: 53458/59290
Iteration: 53459/59290
Iteration: 53460/59290
Iteration: 53461/59290
Iteration: 53462/59290
Iteration: 53463/59290
Iteration: 53464/59290

 90%|█████████ | 53446/59290 [41:31<01:34, 61.95it/s]

Iteration: 53465/59290
Iteration: 53466/59290
Iteration: 53467/59290
Iteration: 53468/59290
Iteration: 53469/59290
Iteration: 53470/59290
Iteration: 53471/59290
Iteration: 53472/59290
Iteration: 53473/59290
Iteration: 53474/59290
Iteration: 53475/59290
Iteration: 53476/59290
Iteration: 53477/59290
Iteration: 53478/59290
Iteration: 53479/59290
Iteration: 53480/59290
Iteration: 53481/59290
Iteration: 53482/59290
Iteration: 53483/59290
Iteration: 53484/59290
Iteration: 53485/59290
Iteration: 53486/59290
Iteration: 53487/59290
Iteration: 53488/59290

 90%|█████████ | 53470/59290 [41:31<01:35, 60.74it/s]

Iteration: 53489/59290
Iteration: 53490/59290
Iteration: 53491/59290
Iteration: 53492/59290
Iteration: 53493/59290
Iteration: 53494/59290
Iteration: 53495/59290
Iteration: 53496/59290
Iteration: 53497/59290
Iteration: 53498/59290
Iteration: 53499/59290
Iteration: 53500/59290
Iteration: 53501/59290
Iteration: 53502/59290
Iteration: 53503/59290
Iteration: 53504/59290
Iteration: 53505/59290
Iteration: 53506/59290
Iteration: 53507/59290
Iteration: 53508/59290
Iteration: 53509/59290
Iteration: 53510/59290
Iteration: 53511/59290
Iteration: 53512/59290

 90%|█████████ | 53494/59290 [41:33<02:49, 34.29it/s]

Iteration: 53513/59290
Iteration: 53514/59290
Iteration: 53515/59290
Iteration: 53516/59290
Iteration: 53517/59290
Iteration: 53518/59290
Iteration: 53519/59290
Iteration: 53520/59290
Iteration: 53521/59290
Iteration: 53522/59290
Iteration: 53523/59290
Iteration: 53524/59290
Iteration: 53525/59290
Iteration: 53526/59290
Iteration: 53527/59290
Iteration: 53528/59290
Iteration: 53529/59290
Iteration: 53530/59290
Iteration: 53531/59290
Iteration: 53532/59290
Iteration: 53533/59290
Iteration: 53534/59290
Iteration: 53535/59290
Iteration: 53536/59290

 90%|█████████ | 53518/59290 [41:36<05:48, 16.58it/s]

Iteration: 53537/59290
Iteration: 53538/59290
Iteration: 53539/59290
Iteration: 53540/59290
Iteration: 53541/59290
Iteration: 53542/59290
Iteration: 53543/59290
Iteration: 53544/59290
Iteration: 53545/59290
Iteration: 53546/59290
Iteration: 53547/59290
Iteration: 53548/59290
Iteration: 53549/59290
Iteration: 53550/59290
Iteration: 53551/59290
Iteration: 53552/59290
Iteration: 53553/59290
Iteration: 53554/59290
Iteration: 53555/59290
Iteration: 53556/59290
Iteration: 53557/59290
Iteration: 53558/59290
Iteration: 53559/59290
Iteration: 53560/59290

 90%|█████████ | 53542/59290 [41:36<04:37, 20.75it/s]

Iteration: 53561/59290
Iteration: 53562/59290
Iteration: 53563/59290
Iteration: 53564/59290
Iteration: 53565/59290
Iteration: 53566/59290
Iteration: 53567/59290
Iteration: 53568/59290
Iteration: 53569/59290
Iteration: 53570/59290
Iteration: 53571/59290
Iteration: 53572/59290
Iteration: 53573/59290
Iteration: 53574/59290
Iteration: 53575/59290
Iteration: 53576/59290
Iteration: 53577/59290
Iteration: 53578/59290
Iteration: 53579/59290
Iteration: 53580/59290
Iteration: 53581/59290
Iteration: 53582/59290
Iteration: 53583/59290
Iteration: 53584/59290

 90%|█████████ | 53566/59290 [41:37<03:43, 25.56it/s]

Iteration: 53585/59290
Iteration: 53586/59290
Iteration: 53587/59290
Iteration: 53588/59290
Iteration: 53589/59290
Iteration: 53590/59290
Iteration: 53591/59290
Iteration: 53592/59290
Iteration: 53593/59290
Iteration: 53594/59290
Iteration: 53595/59290
Iteration: 53596/59290
Iteration: 53597/59290
Iteration: 53598/59290
Iteration: 53599/59290
Iteration: 53600/59290
Iteration: 53601/59290
Iteration: 53602/59290
Iteration: 53603/59290
Iteration: 53604/59290
Iteration: 53605/59290
Iteration: 53606/59290
Iteration: 53607/59290
Iteration: 53608/59290

 90%|█████████ | 53590/59290 [41:37<03:03, 31.09it/s]

Iteration: 53609/59290
Iteration: 53610/59290
Iteration: 53611/59290
Iteration: 53612/59290
Iteration: 53613/59290
Iteration: 53614/59290
Iteration: 53615/59290
Iteration: 53616/59290
Iteration: 53617/59290
Iteration: 53618/59290
Iteration: 53619/59290
Iteration: 53620/59290
Iteration: 53621/59290
Iteration: 53622/59290
Iteration: 53623/59290
Iteration: 53624/59290
Iteration: 53625/59290
Iteration: 53626/59290
Iteration: 53627/59290
Iteration: 53628/59290
Iteration: 53629/59290
Iteration: 53630/59290
Iteration: 53631/59290
Iteration: 53632/59290

 90%|█████████ | 53614/59290 [41:38<02:34, 36.72it/s]

Iteration: 53633/59290
Iteration: 53634/59290
Iteration: 53635/59290
Iteration: 53636/59290
Iteration: 53637/59290
Iteration: 53638/59290
Iteration: 53639/59290
Iteration: 53640/59290
Iteration: 53641/59290
Iteration: 53642/59290
Iteration: 53643/59290
Iteration: 53644/59290
Iteration: 53645/59290
Iteration: 53646/59290
Iteration: 53647/59290
Iteration: 53648/59290
Iteration: 53649/59290
Iteration: 53650/59290
Iteration: 53651/59290
Iteration: 53652/59290
Iteration: 53653/59290
Iteration: 53654/59290
Iteration: 53655/59290
Iteration: 53656/59290

 90%|█████████ | 53638/59290 [41:38<02:14, 41.87it/s]

Iteration: 53657/59290
Iteration: 53658/59290
Iteration: 53659/59290
Iteration: 53660/59290
Iteration: 53661/59290
Iteration: 53662/59290
Iteration: 53663/59290
Iteration: 53664/59290
Iteration: 53665/59290
Iteration: 53666/59290
Iteration: 53667/59290
Iteration: 53668/59290
Iteration: 53669/59290
Iteration: 53670/59290
Iteration: 53671/59290
Iteration: 53672/59290
Iteration: 53673/59290
Iteration: 53674/59290
Iteration: 53675/59290
Iteration: 53676/59290
Iteration: 53677/59290
Iteration: 53678/59290
Iteration: 53679/59290
Iteration: 53680/59290

 91%|█████████ | 53662/59290 [41:38<02:00, 46.82it/s]

Iteration: 53681/59290
Iteration: 53682/59290
Iteration: 53683/59290
Iteration: 53684/59290
Iteration: 53685/59290
Iteration: 53686/59290
Iteration: 53687/59290
Iteration: 53688/59290
Iteration: 53689/59290
Iteration: 53690/59290
Iteration: 53691/59290
Iteration: 53692/59290
Iteration: 53693/59290
Iteration: 53694/59290
Iteration: 53695/59290
Iteration: 53696/59290
Iteration: 53697/59290
Iteration: 53698/59290
Iteration: 53699/59290
Iteration: 53700/59290
Iteration: 53701/59290
Iteration: 53702/59290
Iteration: 53703/59290
Iteration: 53704/59290

 91%|█████████ | 53686/59290 [41:39<01:50, 50.64it/s]

Iteration: 53705/59290
Iteration: 53706/59290
Iteration: 53707/59290
Iteration: 53708/59290
Iteration: 53709/59290
Iteration: 53710/59290
Iteration: 53711/59290
Iteration: 53712/59290
Iteration: 53713/59290
Iteration: 53714/59290
Iteration: 53715/59290
Iteration: 53716/59290
Iteration: 53717/59290
Iteration: 53718/59290
Iteration: 53719/59290
Iteration: 53720/59290
Iteration: 53721/59290
Iteration: 53722/59290
Iteration: 53723/59290
Iteration: 53724/59290
Iteration: 53725/59290
Iteration: 53726/59290
Iteration: 53727/59290
Iteration: 53728/59290

 91%|█████████ | 53710/59290 [41:39<01:45, 52.96it/s]

Iteration: 53729/59290
Iteration: 53730/59290
Iteration: 53731/59290
Iteration: 53732/59290
Iteration: 53733/59290
Iteration: 53734/59290
Iteration: 53735/59290
Iteration: 53736/59290
Iteration: 53737/59290
Iteration: 53738/59290
Iteration: 53739/59290
Iteration: 53740/59290
Iteration: 53741/59290
Iteration: 53742/59290
Iteration: 53743/59290
Iteration: 53744/59290
Iteration: 53745/59290
Iteration: 53746/59290
Iteration: 53747/59290
Iteration: 53748/59290
Iteration: 53749/59290
Iteration: 53750/59290
Iteration: 53751/59290
Iteration: 53752/59290

 91%|█████████ | 53734/59290 [41:40<01:39, 55.89it/s]

Iteration: 53753/59290
Iteration: 53754/59290
Iteration: 53755/59290
Iteration: 53756/59290
Iteration: 53757/59290
Iteration: 53758/59290
Iteration: 53759/59290
Iteration: 53760/59290
Iteration: 53761/59290
Iteration: 53762/59290
Iteration: 53763/59290
Iteration: 53764/59290
Iteration: 53765/59290
Iteration: 53766/59290
Iteration: 53767/59290
Iteration: 53768/59290
Iteration: 53769/59290
Iteration: 53770/59290
Iteration: 53771/59290
Iteration: 53772/59290
Iteration: 53773/59290
Iteration: 53774/59290
Iteration: 53775/59290
Iteration: 53776/59290

 91%|█████████ | 53758/59290 [41:40<01:39, 55.67it/s]

Iteration: 53777/59290
Iteration: 53778/59290
Iteration: 53779/59290
Iteration: 53780/59290
Iteration: 53781/59290
Iteration: 53782/59290
Iteration: 53783/59290
Iteration: 53784/59290
Iteration: 53785/59290
Iteration: 53786/59290
Iteration: 53787/59290
Iteration: 53788/59290
Iteration: 53789/59290
Iteration: 53790/59290
Iteration: 53791/59290
Iteration: 53792/59290
Iteration: 53793/59290
Iteration: 53794/59290
Iteration: 53795/59290
Iteration: 53796/59290
Iteration: 53797/59290
Iteration: 53798/59290
Iteration: 53799/59290
Iteration: 53800/59290

 91%|█████████ | 53782/59290 [41:42<02:54, 31.51it/s]

Iteration: 53801/59290
Iteration: 53802/59290
Iteration: 53803/59290
Iteration: 53804/59290
Iteration: 53805/59290
Iteration: 53806/59290
Iteration: 53807/59290
Iteration: 53808/59290
Iteration: 53809/59290
Iteration: 53810/59290
Iteration: 53811/59290
Iteration: 53812/59290
Iteration: 53813/59290
Iteration: 53814/59290
Iteration: 53815/59290
Iteration: 53816/59290
Iteration: 53817/59290
Iteration: 53818/59290
Iteration: 53819/59290
Iteration: 53820/59290
Iteration: 53821/59290
Iteration: 53822/59290
Iteration: 53823/59290
Iteration: 53824/59290

 91%|█████████ | 53806/59290 [41:44<05:05, 17.94it/s]

Iteration: 53825/59290
Iteration: 53826/59290
Iteration: 53827/59290
Iteration: 53828/59290
Iteration: 53829/59290
Iteration: 53830/59290
Iteration: 53831/59290
Iteration: 53832/59290
Iteration: 53833/59290
Iteration: 53834/59290
Iteration: 53835/59290
Iteration: 53836/59290
Iteration: 53837/59290
Iteration: 53838/59290
Iteration: 53839/59290
Iteration: 53840/59290
Iteration: 53841/59290
Iteration: 53842/59290
Iteration: 53843/59290
Iteration: 53844/59290
Iteration: 53845/59290
Iteration: 53846/59290
Iteration: 53847/59290
Iteration: 53848/59290

 91%|█████████ | 53830/59290 [41:45<04:30, 20.17it/s]

Iteration: 53849/59290
Iteration: 53850/59290
Iteration: 53851/59290
Iteration: 53852/59290
Iteration: 53853/59290
Iteration: 53854/59290
Iteration: 53855/59290
Iteration: 53856/59290
Iteration: 53857/59290
Iteration: 53858/59290
Iteration: 53859/59290
Iteration: 53860/59290
Iteration: 53861/59290
Iteration: 53862/59290
Iteration: 53863/59290
Iteration: 53864/59290
Iteration: 53865/59290
Iteration: 53866/59290
Iteration: 53867/59290
Iteration: 53868/59290
Iteration: 53869/59290
Iteration: 53870/59290
Iteration: 53871/59290
Iteration: 53872/59290

 91%|█████████ | 53854/59290 [41:45<03:38, 24.86it/s]

Iteration: 53873/59290
Iteration: 53874/59290
Iteration: 53875/59290
Iteration: 53876/59290
Iteration: 53877/59290
Iteration: 53878/59290
Iteration: 53879/59290
Iteration: 53880/59290
Iteration: 53881/59290
Iteration: 53882/59290
Iteration: 53883/59290
Iteration: 53884/59290
Iteration: 53885/59290
Iteration: 53886/59290
Iteration: 53887/59290
Iteration: 53888/59290
Iteration: 53889/59290
Iteration: 53890/59290
Iteration: 53891/59290
Iteration: 53892/59290
Iteration: 53893/59290
Iteration: 53894/59290
Iteration: 53895/59290
Iteration: 53896/59290

 91%|█████████ | 53878/59290 [41:46<02:58, 30.29it/s]

Iteration: 53897/59290
Iteration: 53898/59290
Iteration: 53899/59290
Iteration: 53900/59290
Iteration: 53901/59290
Iteration: 53902/59290
Iteration: 53903/59290
Iteration: 53904/59290
Iteration: 53905/59290
Iteration: 53906/59290
Iteration: 53907/59290
Iteration: 53908/59290
Iteration: 53909/59290
Iteration: 53910/59290
Iteration: 53911/59290
Iteration: 53912/59290
Iteration: 53913/59290
Iteration: 53914/59290
Iteration: 53915/59290
Iteration: 53916/59290
Iteration: 53917/59290
Iteration: 53918/59290
Iteration: 53920/59290

 91%|█████████ | 53901/59290 [41:50<06:57, 12.90it/s]

Iteration: 53921/59290
Iteration: 53922/59290
Iteration: 53923/59290
Iteration: 53924/59290
Iteration: 53925/59290
Iteration: 53926/59290
Iteration: 53927/59290
Iteration: 53928/59290

 91%|█████████ | 53909/59290 [41:51<07:14, 12.38it/s]

Iteration: 53929/59290
Iteration: 53930/59290
Iteration: 53931/59290
Iteration: 53932/59290
Iteration: 53933/59290
Iteration: 53934/59290
Iteration: 53935/59290
Iteration: 53936/59290
Iteration: 53937/59290
Iteration: 53938/59290
Iteration: 53939/59290
Iteration: 53940/59290
Iteration: 53941/59290
Iteration: 53942/59290
Iteration: 53943/59290
Iteration: 53944/59290
Iteration: 53945/59290
Iteration: 53946/59290
Iteration: 53947/59290
Iteration: 53948/59290
Iteration: 53949/59290
Iteration: 53950/59290
Iteration: 53951/59290
Iteration: 53952/59290

 91%|█████████ | 53933/59290 [41:51<05:11, 17.21it/s]

Iteration: 53953/59290
Iteration: 53954/59290
Iteration: 53955/59290
Iteration: 53956/59290
Iteration: 53957/59290
Iteration: 53958/59290
Iteration: 53959/59290
Iteration: 53960/59290
Iteration: 53961/59290
Iteration: 53962/59290
Iteration: 53963/59290
Iteration: 53964/59290
Iteration: 53965/59290
Iteration: 53966/59290
Iteration: 53967/59290
Iteration: 53968/59290
Iteration: 53969/59290
Iteration: 53970/59290
Iteration: 53971/59290
Iteration: 53972/59290
Iteration: 53973/59290
Iteration: 53974/59290
Iteration: 53975/59290
Iteration: 53976/59290

 91%|█████████ | 53957/59290 [41:52<03:54, 22.74it/s]

Iteration: 53977/59290
Iteration: 53978/59290
Iteration: 53979/59290
Iteration: 53980/59290
Iteration: 53981/59290
Iteration: 53982/59290
Iteration: 53983/59290
Iteration: 53984/59290
Iteration: 53985/59290
Iteration: 53986/59290
Iteration: 53987/59290
Iteration: 53988/59290
Iteration: 53989/59290
Iteration: 53990/59290
Iteration: 53991/59290
Iteration: 53992/59290
Iteration: 53993/59290
Iteration: 53994/59290
Iteration: 53995/59290
Iteration: 53996/59290
Iteration: 53997/59290
Iteration: 53998/59290
Iteration: 53999/59290
Iteration: 54000/59290

 91%|█████████ | 53981/59290 [41:52<03:04, 28.71it/s]

Iteration: 54001/59290
Iteration: 54002/59290
Iteration: 54003/59290
Iteration: 54004/59290
Iteration: 54005/59290
Iteration: 54006/59290
Iteration: 54007/59290
Iteration: 54008/59290
Iteration: 54009/59290
Iteration: 54010/59290
Iteration: 54011/59290
Iteration: 54012/59290
Iteration: 54013/59290
Iteration: 54014/59290
Iteration: 54015/59290
Iteration: 54016/59290
Iteration: 54017/59290
Iteration: 54018/59290
Iteration: 54019/59290
Iteration: 54020/59290
Iteration: 54021/59290
Iteration: 54022/59290
Iteration: 54023/59290
Iteration: 54024/59290

 91%|█████████ | 54005/59290 [41:53<02:32, 34.70it/s]

Iteration: 54025/59290
Iteration: 54026/59290
Iteration: 54027/59290
Iteration: 54028/59290
Iteration: 54029/59290
Iteration: 54030/59290
Iteration: 54031/59290
Iteration: 54032/59290
Iteration: 54033/59290
Iteration: 54034/59290
Iteration: 54035/59290
Iteration: 54036/59290
Iteration: 54037/59290
Iteration: 54038/59290
Iteration: 54039/59290
Iteration: 54040/59290
Iteration: 54041/59290
Iteration: 54042/59290
Iteration: 54043/59290
Iteration: 54044/59290
Iteration: 54045/59290
Iteration: 54046/59290
Iteration: 54047/59290
Iteration: 54048/59290

 91%|█████████ | 54029/59290 [41:53<02:10, 40.39it/s]

Iteration: 54049/59290
Iteration: 54050/59290
Iteration: 54051/59290
Iteration: 54052/59290
Iteration: 54053/59290
Iteration: 54054/59290
Iteration: 54055/59290
Iteration: 54056/59290
Iteration: 54057/59290
Iteration: 54058/59290
Iteration: 54059/59290
Iteration: 54060/59290
Iteration: 54061/59290
Iteration: 54062/59290
Iteration: 54063/59290
Iteration: 54064/59290
Iteration: 54065/59290
Iteration: 54066/59290
Iteration: 54067/59290
Iteration: 54068/59290
Iteration: 54069/59290
Iteration: 54070/59290
Iteration: 54071/59290
Iteration: 54072/59290

 91%|█████████ | 54053/59290 [41:53<01:55, 45.49it/s]

Iteration: 54073/59290
Iteration: 54074/59290
Iteration: 54075/59290
Iteration: 54076/59290
Iteration: 54077/59290
Iteration: 54078/59290
Iteration: 54079/59290
Iteration: 54080/59290
Iteration: 54081/59290
Iteration: 54082/59290
Iteration: 54083/59290
Iteration: 54084/59290
Iteration: 54085/59290
Iteration: 54086/59290
Iteration: 54087/59290
Iteration: 54088/59290
Iteration: 54089/59290
Iteration: 54090/59290
Iteration: 54091/59290
Iteration: 54092/59290
Iteration: 54093/59290
Iteration: 54094/59290
Iteration: 54095/59290
Iteration: 54096/59290

 91%|█████████ | 54077/59290 [41:54<01:45, 49.26it/s]

Iteration: 54097/59290
Iteration: 54098/59290
Iteration: 54099/59290
Iteration: 54100/59290
Iteration: 54101/59290
Iteration: 54102/59290
Iteration: 54103/59290
Iteration: 54104/59290
Iteration: 54105/59290
Iteration: 54106/59290
Iteration: 54107/59290
Iteration: 54108/59290
Iteration: 54109/59290
Iteration: 54110/59290
Iteration: 54111/59290
Iteration: 54112/59290
Iteration: 54113/59290
Iteration: 54114/59290
Iteration: 54115/59290
Iteration: 54116/59290
Iteration: 54117/59290
Iteration: 54118/59290
Iteration: 54119/59290
Iteration: 54120/59290

 91%|█████████ | 54101/59290 [41:54<01:38, 52.86it/s]

Iteration: 54121/59290
Iteration: 54122/59290
Iteration: 54123/59290
Iteration: 54124/59290
Iteration: 54125/59290
Iteration: 54126/59290
Iteration: 54127/59290
Iteration: 54128/59290
Iteration: 54129/59290
Iteration: 54130/59290
Iteration: 54131/59290
Iteration: 54132/59290
Iteration: 54133/59290
Iteration: 54134/59290
Iteration: 54135/59290
Iteration: 54136/59290
Iteration: 54137/59290
Iteration: 54138/59290
Iteration: 54139/59290
Iteration: 54140/59290
Iteration: 54141/59290
Iteration: 54142/59290
Iteration: 54143/59290
Iteration: 54144/59290

 91%|█████████▏| 54125/59290 [41:54<01:32, 55.55it/s]

Iteration: 54145/59290
Iteration: 54146/59290
Iteration: 54147/59290
Iteration: 54148/59290
Iteration: 54149/59290
Iteration: 54150/59290
Iteration: 54151/59290
Iteration: 54152/59290
Iteration: 54153/59290
Iteration: 54154/59290
Iteration: 54155/59290
Iteration: 54156/59290
Iteration: 54157/59290
Iteration: 54158/59290
Iteration: 54159/59290
Iteration: 54160/59290
Iteration: 54161/59290
Iteration: 54162/59290
Iteration: 54163/59290
Iteration: 54164/59290
Iteration: 54165/59290
Iteration: 54166/59290
Iteration: 54167/59290
Iteration: 54168/59290

 91%|█████████▏| 54149/59290 [41:55<01:29, 57.71it/s]

Iteration: 54169/59290
Iteration: 54170/59290
Iteration: 54171/59290
Iteration: 54172/59290
Iteration: 54173/59290
Iteration: 54174/59290
Iteration: 54175/59290
Iteration: 54176/59290
Iteration: 54177/59290
Iteration: 54178/59290
Iteration: 54179/59290
Iteration: 54180/59290
Iteration: 54181/59290
Iteration: 54182/59290
Iteration: 54183/59290
Iteration: 54184/59290
Iteration: 54185/59290
Iteration: 54186/59290
Iteration: 54187/59290
Iteration: 54188/59290
Iteration: 54189/59290
Iteration: 54190/59290
Iteration: 54191/59290
Iteration: 54192/59290

 91%|█████████▏| 54173/59290 [41:55<01:26, 59.31it/s]

Iteration: 54193/59290
Iteration: 54194/59290
Iteration: 54195/59290
Iteration: 54196/59290
Iteration: 54197/59290
Iteration: 54198/59290
Iteration: 54199/59290
Iteration: 54200/59290
Iteration: 54201/59290
Iteration: 54202/59290
Iteration: 54203/59290
Iteration: 54204/59290
Iteration: 54205/59290
Iteration: 54206/59290
Iteration: 54207/59290
Iteration: 54208/59290
Iteration: 54209/59290
Iteration: 54210/59290
Iteration: 54211/59290
Iteration: 54212/59290
Iteration: 54213/59290
Iteration: 54214/59290
Iteration: 54215/59290
Iteration: 54216/59290

 91%|█████████▏| 54197/59290 [41:56<01:25, 59.61it/s]

Iteration: 54217/59290
Iteration: 54218/59290
Iteration: 54219/59290
Iteration: 54220/59290
Iteration: 54221/59290
Iteration: 54222/59290
Iteration: 54223/59290
Iteration: 54224/59290
Iteration: 54225/59290
Iteration: 54226/59290
Iteration: 54227/59290
Iteration: 54228/59290
Iteration: 54229/59290
Iteration: 54230/59290
Iteration: 54231/59290
Iteration: 54232/59290
Iteration: 54233/59290
Iteration: 54234/59290
Iteration: 54235/59290
Iteration: 54236/59290
Iteration: 54237/59290
Iteration: 54238/59290
Iteration: 54239/59290
Iteration: 54240/59290

 91%|█████████▏| 54221/59290 [41:56<01:23, 60.42it/s]

Iteration: 54241/59290
Iteration: 54242/59290
Iteration: 54243/59290
Iteration: 54244/59290
Iteration: 54245/59290
Iteration: 54246/59290
Iteration: 54247/59290
Iteration: 54248/59290
Iteration: 54249/59290
Iteration: 54250/59290
Iteration: 54251/59290
Iteration: 54252/59290
Iteration: 54253/59290
Iteration: 54254/59290
Iteration: 54255/59290
Iteration: 54256/59290
Iteration: 54257/59290
Iteration: 54258/59290
Iteration: 54259/59290
Iteration: 54260/59290
Iteration: 54261/59290
Iteration: 54262/59290
Iteration: 54263/59290
Iteration: 54264/59290

 91%|█████████▏| 54245/59290 [41:56<01:23, 60.72it/s]

Iteration: 54265/59290
Iteration: 54266/59290
Iteration: 54267/59290
Iteration: 54268/59290
Iteration: 54269/59290
Iteration: 54270/59290
Iteration: 54271/59290
Iteration: 54272/59290
Iteration: 54273/59290
Iteration: 54274/59290
Iteration: 54275/59290
Iteration: 54276/59290
Iteration: 54277/59290
Iteration: 54278/59290
Iteration: 54279/59290
Iteration: 54280/59290
Iteration: 54281/59290
Iteration: 54282/59290
Iteration: 54283/59290
Iteration: 54284/59290
Iteration: 54285/59290
Iteration: 54286/59290
Iteration: 54287/59290
Iteration: 54288/59290

 92%|█████████▏| 54269/59290 [42:01<05:20, 15.69it/s]

Iteration: 54289/59290
Iteration: 54290/59290
Iteration: 54291/59290
Iteration: 54292/59290
Iteration: 54293/59290
Iteration: 54294/59290
Iteration: 54295/59290
Iteration: 54296/59290
Iteration: 54297/59290
Iteration: 54298/59290
Iteration: 54299/59290
Iteration: 54300/59290
Iteration: 54301/59290
Iteration: 54302/59290
Iteration: 54303/59290
Iteration: 54304/59290
Iteration: 54305/59290
Iteration: 54306/59290
Iteration: 54307/59290
Iteration: 54308/59290
Iteration: 54309/59290
Iteration: 54310/59290
Iteration: 54311/59290
Iteration: 54312/59290

 92%|█████████▏| 54293/59290 [42:01<04:31, 18.43it/s]

Iteration: 54313/59290
Iteration: 54314/59290
Iteration: 54315/59290
Iteration: 54316/59290
Iteration: 54317/59290
Iteration: 54318/59290
Iteration: 54319/59290
Iteration: 54320/59290
Iteration: 54321/59290
Iteration: 54322/59290
Iteration: 54323/59290
Iteration: 54324/59290
Iteration: 54325/59290
Iteration: 54326/59290
Iteration: 54327/59290
Iteration: 54328/59290
Iteration: 54329/59290
Iteration: 54330/59290
Iteration: 54331/59290
Iteration: 54332/59290
Iteration: 54333/59290
Iteration: 54334/59290
Iteration: 54335/59290
Iteration: 54336/59290

 92%|█████████▏| 54317/59290 [42:02<03:34, 23.24it/s]

Iteration: 54337/59290
Iteration: 54338/59290
Iteration: 54339/59290
Iteration: 54340/59290
Iteration: 54341/59290
Iteration: 54342/59290
Iteration: 54343/59290
Iteration: 54344/59290
Iteration: 54345/59290
Iteration: 54346/59290
Iteration: 54347/59290
Iteration: 54348/59290
Iteration: 54349/59290
Iteration: 54350/59290
Iteration: 54351/59290
Iteration: 54352/59290
Iteration: 54353/59290
Iteration: 54354/59290
Iteration: 54355/59290
Iteration: 54356/59290
Iteration: 54357/59290
Iteration: 54358/59290
Iteration: 54359/59290
Iteration: 54360/59290

 92%|█████████▏| 54341/59290 [42:02<02:52, 28.63it/s]

Iteration: 54361/59290
Iteration: 54362/59290
Iteration: 54363/59290
Iteration: 54364/59290
Iteration: 54365/59290
Iteration: 54366/59290
Iteration: 54367/59290
Iteration: 54368/59290
Iteration: 54369/59290
Iteration: 54370/59290
Iteration: 54371/59290
Iteration: 54372/59290
Iteration: 54373/59290
Iteration: 54374/59290
Iteration: 54375/59290
Iteration: 54376/59290
Iteration: 54377/59290
Iteration: 54378/59290
Iteration: 54379/59290
Iteration: 54380/59290
Iteration: 54381/59290
Iteration: 54382/59290
Iteration: 54383/59290
Iteration: 54384/59290

 92%|█████████▏| 54365/59290 [42:04<03:52, 21.18it/s]

Iteration: 54385/59290
Iteration: 54386/59290
Iteration: 54387/59290
Iteration: 54388/59290
Iteration: 54389/59290
Iteration: 54390/59290
Iteration: 54391/59290
Iteration: 54392/59290
Iteration: 54393/59290
Iteration: 54394/59290
Iteration: 54395/59290
Iteration: 54396/59290
Iteration: 54397/59290
Iteration: 54398/59290
Iteration: 54399/59290
Iteration: 54400/59290
Iteration: 54401/59290
Iteration: 54402/59290
Iteration: 54403/59290
Iteration: 54404/59290
Iteration: 54405/59290
Iteration: 54406/59290
Iteration: 54407/59290
Iteration: 54408/59290

 92%|█████████▏| 54389/59290 [42:06<05:17, 15.45it/s]

Iteration: 54409/59290
Iteration: 54410/59290
Iteration: 54411/59290
Iteration: 54412/59290
Iteration: 54413/59290
Iteration: 54414/59290
Iteration: 54415/59290
Iteration: 54416/59290
Iteration: 54417/59290
Iteration: 54418/59290
Iteration: 54419/59290
Iteration: 54420/59290
Iteration: 54421/59290
Iteration: 54422/59290
Iteration: 54423/59290
Iteration: 54424/59290
Iteration: 54425/59290
Iteration: 54426/59290
Iteration: 54427/59290
Iteration: 54428/59290
Iteration: 54429/59290
Iteration: 54430/59290
Iteration: 54431/59290
Iteration: 54432/59290

 92%|█████████▏| 54413/59290 [42:07<04:23, 18.47it/s]

Iteration: 54433/59290
Iteration: 54434/59290
Iteration: 54435/59290
Iteration: 54436/59290
Iteration: 54437/59290
Iteration: 54438/59290
Iteration: 54439/59290
Iteration: 54440/59290
Iteration: 54441/59290
Iteration: 54442/59290
Iteration: 54443/59290
Iteration: 54444/59290
Iteration: 54445/59290
Iteration: 54446/59290
Iteration: 54447/59290
Iteration: 54448/59290
Iteration: 54449/59290
Iteration: 54450/59290
Iteration: 54451/59290
Iteration: 54452/59290
Iteration: 54453/59290
Iteration: 54454/59290
Iteration: 54455/59290
Iteration: 54456/59290

 92%|█████████▏| 54437/59290 [42:08<03:28, 23.23it/s]

Iteration: 54457/59290
Iteration: 54458/59290
Iteration: 54459/59290
Iteration: 54460/59290
Iteration: 54461/59290
Iteration: 54462/59290
Iteration: 54463/59290
Iteration: 54464/59290
Iteration: 54465/59290
Iteration: 54466/59290
Iteration: 54467/59290
Iteration: 54468/59290
Iteration: 54469/59290
Iteration: 54470/59290
Iteration: 54471/59290
Iteration: 54472/59290
Iteration: 54473/59290
Iteration: 54474/59290
Iteration: 54475/59290
Iteration: 54476/59290
Iteration: 54477/59290
Iteration: 54478/59290
Iteration: 54479/59290
Iteration: 54480/59290

 92%|█████████▏| 54461/59290 [42:08<02:49, 28.43it/s]

Iteration: 54481/59290
Iteration: 54482/59290
Iteration: 54483/59290
Iteration: 54484/59290
Iteration: 54485/59290
Iteration: 54486/59290
Iteration: 54487/59290
Iteration: 54488/59290
Iteration: 54489/59290
Iteration: 54490/59290
Iteration: 54491/59290
Iteration: 54492/59290
Iteration: 54493/59290
Iteration: 54494/59290
Iteration: 54495/59290
Iteration: 54496/59290
Iteration: 54497/59290
Iteration: 54498/59290
Iteration: 54499/59290
Iteration: 54500/59290
Iteration: 54501/59290
Iteration: 54502/59290
Iteration: 54503/59290
Iteration: 54504/59290

 92%|█████████▏| 54485/59290 [42:08<02:21, 34.06it/s]

Iteration: 54505/59290
Iteration: 54506/59290
Iteration: 54507/59290
Iteration: 54508/59290
Iteration: 54509/59290
Iteration: 54510/59290
Iteration: 54511/59290
Iteration: 54512/59290
Iteration: 54513/59290
Iteration: 54514/59290
Iteration: 54515/59290
Iteration: 54516/59290
Iteration: 54517/59290
Iteration: 54518/59290
Iteration: 54519/59290
Iteration: 54520/59290
Iteration: 54521/59290
Iteration: 54522/59290
Iteration: 54523/59290
Iteration: 54524/59290
Iteration: 54525/59290
Iteration: 54526/59290
Iteration: 54527/59290
Iteration: 54528/59290

 92%|█████████▏| 54509/59290 [42:09<02:01, 39.41it/s]

Iteration: 54529/59290
Iteration: 54530/59290
Iteration: 54531/59290
Iteration: 54532/59290
Iteration: 54533/59290
Iteration: 54534/59290
Iteration: 54535/59290
Iteration: 54536/59290
Iteration: 54537/59290
Iteration: 54538/59290
Iteration: 54539/59290
Iteration: 54540/59290
Iteration: 54541/59290
Iteration: 54542/59290
Iteration: 54543/59290
Iteration: 54544/59290
Iteration: 54545/59290
Iteration: 54546/59290
Iteration: 54547/59290
Iteration: 54548/59290
Iteration: 54549/59290
Iteration: 54550/59290
Iteration: 54551/59290
Iteration: 54552/59290

 92%|█████████▏| 54533/59290 [42:09<01:48, 43.87it/s]

Iteration: 54553/59290
Iteration: 54554/59290
Iteration: 54555/59290
Iteration: 54556/59290
Iteration: 54557/59290
Iteration: 54558/59290
Iteration: 54559/59290
Iteration: 54560/59290
Iteration: 54561/59290
Iteration: 54562/59290
Iteration: 54563/59290
Iteration: 54564/59290
Iteration: 54565/59290
Iteration: 54566/59290
Iteration: 54567/59290
Iteration: 54568/59290
Iteration: 54569/59290
Iteration: 54570/59290
Iteration: 54571/59290
Iteration: 54572/59290
Iteration: 54573/59290
Iteration: 54574/59290
Iteration: 54575/59290
Iteration: 54576/59290

 92%|█████████▏| 54557/59290 [42:10<01:37, 48.36it/s]

Iteration: 54577/59290
Iteration: 54578/59290
Iteration: 54579/59290
Iteration: 54580/59290
Iteration: 54581/59290
Iteration: 54582/59290
Iteration: 54583/59290
Iteration: 54584/59290
Iteration: 54585/59290
Iteration: 54586/59290
Iteration: 54587/59290
Iteration: 54588/59290
Iteration: 54589/59290
Iteration: 54590/59290
Iteration: 54591/59290
Iteration: 54592/59290
Iteration: 54593/59290
Iteration: 54594/59290
Iteration: 54595/59290
Iteration: 54596/59290
Iteration: 54597/59290
Iteration: 54598/59290
Iteration: 54599/59290
Iteration: 54600/59290

 92%|█████████▏| 54581/59290 [42:10<01:30, 52.17it/s]

Iteration: 54601/59290
Iteration: 54602/59290
Iteration: 54603/59290
Iteration: 54604/59290
Iteration: 54605/59290
Iteration: 54606/59290
Iteration: 54607/59290
Iteration: 54608/59290
Iteration: 54609/59290
Iteration: 54610/59290
Iteration: 54611/59290
Iteration: 54612/59290
Iteration: 54613/59290
Iteration: 54614/59290
Iteration: 54615/59290
Iteration: 54616/59290
Iteration: 54617/59290
Iteration: 54618/59290
Iteration: 54619/59290
Iteration: 54620/59290
Iteration: 54621/59290
Iteration: 54622/59290
Iteration: 54623/59290
Iteration: 54624/59290

 92%|█████████▏| 54605/59290 [42:10<01:24, 55.17it/s]

Iteration: 54625/59290
Iteration: 54626/59290
Iteration: 54627/59290
Iteration: 54628/59290
Iteration: 54629/59290
Iteration: 54630/59290
Iteration: 54631/59290
Iteration: 54632/59290
Iteration: 54633/59290
Iteration: 54634/59290
Iteration: 54635/59290
Iteration: 54636/59290
Iteration: 54637/59290
Iteration: 54638/59290
Iteration: 54639/59290
Iteration: 54640/59290
Iteration: 54641/59290
Iteration: 54642/59290
Iteration: 54643/59290
Iteration: 54644/59290
Iteration: 54645/59290
Iteration: 54646/59290
Iteration: 54647/59290
Iteration: 54648/59290

 92%|█████████▏| 54629/59290 [42:12<02:43, 28.55it/s]

Iteration: 54649/59290
Iteration: 54650/59290
Iteration: 54651/59290
Iteration: 54652/59290
Iteration: 54653/59290
Iteration: 54654/59290
Iteration: 54655/59290
Iteration: 54656/59290
Iteration: 54657/59290
Iteration: 54658/59290
Iteration: 54659/59290
Iteration: 54660/59290
Iteration: 54661/59290
Iteration: 54662/59290
Iteration: 54663/59290
Iteration: 54664/59290
Iteration: 54665/59290
Iteration: 54666/59290
Iteration: 54667/59290
Iteration: 54668/59290
Iteration: 54669/59290
Iteration: 54670/59290
Iteration: 54671/59290
Iteration: 54672/59290

 92%|█████████▏| 54653/59290 [42:15<05:04, 15.24it/s]

Iteration: 54673/59290
Iteration: 54674/59290
Iteration: 54675/59290
Iteration: 54676/59290
Iteration: 54677/59290
Iteration: 54678/59290
Iteration: 54679/59290
Iteration: 54680/59290
Iteration: 54681/59290
Iteration: 54682/59290
Iteration: 54683/59290
Iteration: 54684/59290
Iteration: 54685/59290
Iteration: 54686/59290
Iteration: 54687/59290
Iteration: 54688/59290
Iteration: 54689/59290
Iteration: 54690/59290
Iteration: 54691/59290
Iteration: 54692/59290
Iteration: 54693/59290
Iteration: 54694/59290
Iteration: 54695/59290
Iteration: 54696/59290

 92%|█████████▏| 54677/59290 [42:16<03:57, 19.43it/s]

Iteration: 54697/59290
Iteration: 54698/59290
Iteration: 54699/59290
Iteration: 54700/59290
Iteration: 54701/59290
Iteration: 54702/59290
Iteration: 54703/59290
Iteration: 54704/59290
Iteration: 54705/59290
Iteration: 54706/59290
Iteration: 54707/59290
Iteration: 54708/59290
Iteration: 54709/59290
Iteration: 54710/59290
Iteration: 54711/59290
Iteration: 54712/59290
Iteration: 54713/59290
Iteration: 54714/59290
Iteration: 54715/59290
Iteration: 54716/59290
Iteration: 54717/59290
Iteration: 54718/59290
Iteration: 54719/59290
Iteration: 54720/59290

 92%|█████████▏| 54701/59290 [42:16<03:07, 24.50it/s]

Iteration: 54721/59290
Iteration: 54722/59290
Iteration: 54723/59290
Iteration: 54724/59290
Iteration: 54725/59290
Iteration: 54726/59290
Iteration: 54727/59290
Iteration: 54728/59290
Iteration: 54729/59290
Iteration: 54730/59290
Iteration: 54731/59290
Iteration: 54732/59290
Iteration: 54733/59290
Iteration: 54734/59290
Iteration: 54735/59290
Iteration: 54736/59290
Iteration: 54737/59290
Iteration: 54738/59290
Iteration: 54739/59290
Iteration: 54740/59290
Iteration: 54741/59290
Iteration: 54742/59290
Iteration: 54743/59290
Iteration: 54744/59290

 92%|█████████▏| 54725/59290 [42:17<02:31, 30.06it/s]

Iteration: 54745/59290
Iteration: 54746/59290
Iteration: 54747/59290
Iteration: 54748/59290
Iteration: 54749/59290
Iteration: 54750/59290
Iteration: 54751/59290
Iteration: 54752/59290
Iteration: 54753/59290
Iteration: 54754/59290
Iteration: 54755/59290
Iteration: 54756/59290
Iteration: 54757/59290
Iteration: 54758/59290
Iteration: 54759/59290
Iteration: 54760/59290
Iteration: 54761/59290
Iteration: 54762/59290
Iteration: 54763/59290
Iteration: 54764/59290
Iteration: 54765/59290
Iteration: 54766/59290
Iteration: 54767/59290
Iteration: 54768/59290

 92%|█████████▏| 54749/59290 [42:18<03:22, 22.45it/s]

Iteration: 54769/59290
Iteration: 54770/59290
Iteration: 54771/59290
Iteration: 54772/59290
Iteration: 54773/59290
Iteration: 54774/59290
Iteration: 54775/59290
Iteration: 54776/59290
Iteration: 54777/59290
Iteration: 54778/59290
Iteration: 54779/59290
Iteration: 54780/59290
Iteration: 54781/59290
Iteration: 54782/59290
Iteration: 54783/59290
Iteration: 54784/59290
Iteration: 54785/59290
Iteration: 54786/59290
Iteration: 54787/59290
Iteration: 54788/59290
Iteration: 54789/59290
Iteration: 54790/59290
Iteration: 54791/59290
Iteration: 54792/59290

 92%|█████████▏| 54773/59290 [42:21<04:43, 15.94it/s]

Iteration: 54793/59290
Iteration: 54794/59290
Iteration: 54795/59290
Iteration: 54796/59290
Iteration: 54797/59290
Iteration: 54798/59290
Iteration: 54799/59290
Iteration: 54800/59290
Iteration: 54801/59290
Iteration: 54802/59290
Iteration: 54803/59290
Iteration: 54804/59290
Iteration: 54805/59290
Iteration: 54806/59290
Iteration: 54807/59290
Iteration: 54808/59290
Iteration: 54809/59290
Iteration: 54810/59290
Iteration: 54811/59290
Iteration: 54812/59290
Iteration: 54813/59290
Iteration: 54814/59290
Iteration: 54815/59290
Iteration: 54816/59290

 92%|█████████▏| 54797/59290 [42:21<03:41, 20.30it/s]

Iteration: 54817/59290
Iteration: 54818/59290
Iteration: 54819/59290
Iteration: 54820/59290
Iteration: 54821/59290
Iteration: 54822/59290
Iteration: 54823/59290
Iteration: 54824/59290
Iteration: 54825/59290
Iteration: 54826/59290
Iteration: 54827/59290
Iteration: 54828/59290
Iteration: 54829/59290
Iteration: 54830/59290
Iteration: 54831/59290
Iteration: 54832/59290
Iteration: 54833/59290
Iteration: 54834/59290
Iteration: 54835/59290
Iteration: 54836/59290
Iteration: 54837/59290
Iteration: 54838/59290
Iteration: 54839/59290
Iteration: 54840/59290

 92%|█████████▏| 54821/59290 [42:22<03:14, 23.00it/s]

Iteration: 54841/59290
Iteration: 54842/59290
Iteration: 54843/59290
Iteration: 54844/59290
Iteration: 54845/59290
Iteration: 54846/59290
Iteration: 54847/59290
Iteration: 54848/59290
Iteration: 54849/59290
Iteration: 54850/59290
Iteration: 54851/59290
Iteration: 54852/59290
Iteration: 54853/59290
Iteration: 54854/59290
Iteration: 54855/59290
Iteration: 54856/59290
Iteration: 54857/59290
Iteration: 54858/59290
Iteration: 54859/59290
Iteration: 54860/59290
Iteration: 54861/59290
Iteration: 54862/59290
Iteration: 54863/59290
Iteration: 54864/59290

 93%|█████████▎| 54845/59290 [42:22<02:38, 27.98it/s]

Iteration: 54865/59290
Iteration: 54866/59290
Iteration: 54867/59290
Iteration: 54868/59290
Iteration: 54869/59290
Iteration: 54870/59290
Iteration: 54871/59290
Iteration: 54872/59290
Iteration: 54873/59290
Iteration: 54874/59290
Iteration: 54875/59290
Iteration: 54876/59290
Iteration: 54877/59290
Iteration: 54878/59290
Iteration: 54879/59290
Iteration: 54880/59290
Iteration: 54881/59290
Iteration: 54882/59290
Iteration: 54883/59290
Iteration: 54884/59290
Iteration: 54885/59290
Iteration: 54886/59290
Iteration: 54887/59290
Iteration: 54888/59290

 93%|█████████▎| 54869/59290 [42:23<02:11, 33.60it/s]

Iteration: 54889/59290
Iteration: 54890/59290
Iteration: 54891/59290
Iteration: 54892/59290
Iteration: 54893/59290
Iteration: 54894/59290
Iteration: 54895/59290
Iteration: 54896/59290
Iteration: 54897/59290
Iteration: 54898/59290
Iteration: 54899/59290
Iteration: 54900/59290
Iteration: 54901/59290
Iteration: 54902/59290
Iteration: 54903/59290
Iteration: 54904/59290
Iteration: 54905/59290
Iteration: 54906/59290
Iteration: 54907/59290
Iteration: 54908/59290
Iteration: 54909/59290
Iteration: 54910/59290
Iteration: 54911/59290
Iteration: 54912/59290

 93%|█████████▎| 54893/59290 [42:23<01:52, 39.18it/s]

Iteration: 54913/59290
Iteration: 54914/59290
Iteration: 54915/59290
Iteration: 54916/59290
Iteration: 54917/59290
Iteration: 54918/59290
Iteration: 54919/59290
Iteration: 54920/59290
Iteration: 54921/59290
Iteration: 54922/59290
Iteration: 54923/59290
Iteration: 54924/59290
Iteration: 54925/59290
Iteration: 54926/59290
Iteration: 54927/59290
Iteration: 54928/59290
Iteration: 54929/59290
Iteration: 54930/59290
Iteration: 54931/59290
Iteration: 54932/59290
Iteration: 54933/59290
Iteration: 54934/59290
Iteration: 54935/59290
Iteration: 54936/59290

 93%|█████████▎| 54917/59290 [42:23<01:39, 44.15it/s]

Iteration: 54937/59290
Iteration: 54938/59290
Iteration: 54939/59290
Iteration: 54940/59290
Iteration: 54941/59290
Iteration: 54942/59290
Iteration: 54943/59290
Iteration: 54944/59290
Iteration: 54945/59290
Iteration: 54946/59290
Iteration: 54947/59290
Iteration: 54948/59290
Iteration: 54949/59290
Iteration: 54950/59290
Iteration: 54951/59290
Iteration: 54952/59290
Iteration: 54953/59290
Iteration: 54954/59290
Iteration: 54955/59290
Iteration: 54956/59290
Iteration: 54957/59290
Iteration: 54958/59290
Iteration: 54959/59290
Iteration: 54960/59290

 93%|█████████▎| 54941/59290 [42:24<01:29, 48.75it/s]

Iteration: 54961/59290
Iteration: 54962/59290
Iteration: 54963/59290
Iteration: 54964/59290
Iteration: 54965/59290
Iteration: 54966/59290
Iteration: 54967/59290
Iteration: 54968/59290
Iteration: 54969/59290
Iteration: 54970/59290
Iteration: 54971/59290
Iteration: 54972/59290
Iteration: 54973/59290
Iteration: 54974/59290
Iteration: 54975/59290
Iteration: 54976/59290
Iteration: 54977/59290
Iteration: 54978/59290
Iteration: 54979/59290
Iteration: 54980/59290
Iteration: 54981/59290
Iteration: 54982/59290
Iteration: 54983/59290
Iteration: 54984/59290

 93%|█████████▎| 54965/59290 [42:24<01:22, 52.57it/s]

Iteration: 54985/59290
Iteration: 54986/59290
Iteration: 54987/59290
Iteration: 54988/59290
Iteration: 54989/59290
Iteration: 54990/59290
Iteration: 54991/59290
Iteration: 54992/59290
Iteration: 54993/59290
Iteration: 54994/59290
Iteration: 54995/59290
Iteration: 54996/59290
Iteration: 54997/59290
Iteration: 54998/59290
Iteration: 54999/59290
Iteration: 55000/59290
Iteration: 55001/59290
Iteration: 55002/59290
Iteration: 55003/59290
Iteration: 55004/59290
Iteration: 55005/59290
Iteration: 55006/59290
Iteration: 55007/59290
Iteration: 55008/59290

 93%|█████████▎| 54989/59290 [42:25<01:18, 55.14it/s]

Iteration: 55009/59290
Iteration: 55010/59290
Iteration: 55011/59290
Iteration: 55012/59290
Iteration: 55013/59290
Iteration: 55014/59290
Iteration: 55015/59290
Iteration: 55016/59290
Iteration: 55017/59290
Iteration: 55018/59290
Iteration: 55019/59290
Iteration: 55020/59290
Iteration: 55021/59290
Iteration: 55022/59290
Iteration: 55023/59290
Iteration: 55024/59290
Iteration: 55025/59290
Iteration: 55026/59290
Iteration: 55027/59290
Iteration: 55028/59290
Iteration: 55029/59290
Iteration: 55030/59290
Iteration: 55031/59290
Iteration: 55032/59290

 93%|█████████▎| 55013/59290 [42:25<01:14, 57.30it/s]

Iteration: 55033/59290
Iteration: 55034/59290
Iteration: 55035/59290
Iteration: 55036/59290
Iteration: 55037/59290
Iteration: 55038/59290
Iteration: 55039/59290
Iteration: 55040/59290
Iteration: 55041/59290
Iteration: 55042/59290
Iteration: 55043/59290
Iteration: 55044/59290
Iteration: 55045/59290
Iteration: 55046/59290
Iteration: 55047/59290
Iteration: 55048/59290
Iteration: 55049/59290
Iteration: 55050/59290
Iteration: 55051/59290
Iteration: 55052/59290
Iteration: 55053/59290
Iteration: 55054/59290
Iteration: 55055/59290
Iteration: 55056/59290

 93%|█████████▎| 55037/59290 [42:25<01:13, 57.99it/s]

Iteration: 55057/59290
Iteration: 55058/59290
Iteration: 55059/59290
Iteration: 55060/59290
Iteration: 55061/59290
Iteration: 55062/59290
Iteration: 55063/59290
Iteration: 55064/59290
Iteration: 55065/59290
Iteration: 55066/59290
Iteration: 55067/59290
Iteration: 55068/59290
Iteration: 55069/59290
Iteration: 55070/59290
Iteration: 55071/59290
Iteration: 55072/59290
Iteration: 55073/59290
Iteration: 55074/59290
Iteration: 55075/59290
Iteration: 55076/59290
Iteration: 55077/59290
Iteration: 55078/59290
Iteration: 55079/59290
Iteration: 55080/59290

 93%|█████████▎| 55061/59290 [42:26<01:11, 59.21it/s]

Iteration: 55081/59290
Iteration: 55082/59290
Iteration: 55083/59290
Iteration: 55084/59290
Iteration: 55085/59290
Iteration: 55086/59290
Iteration: 55087/59290
Iteration: 55088/59290
Iteration: 55089/59290
Iteration: 55090/59290
Iteration: 55091/59290
Iteration: 55092/59290
Iteration: 55093/59290
Iteration: 55094/59290
Iteration: 55095/59290
Iteration: 55096/59290
Iteration: 55097/59290
Iteration: 55098/59290
Iteration: 55099/59290
Iteration: 55100/59290
Iteration: 55101/59290
Iteration: 55102/59290
Iteration: 55103/59290
Iteration: 55104/59290

 93%|█████████▎| 55085/59290 [42:26<01:09, 60.31it/s]

Iteration: 55105/59290
Iteration: 55106/59290
Iteration: 55107/59290
Iteration: 55108/59290
Iteration: 55109/59290
Iteration: 55110/59290
Iteration: 55111/59290
Iteration: 55112/59290
Iteration: 55113/59290
Iteration: 55114/59290
Iteration: 55115/59290
Iteration: 55116/59290
Iteration: 55117/59290
Iteration: 55118/59290
Iteration: 55119/59290
Iteration: 55120/59290
Iteration: 55121/59290
Iteration: 55122/59290
Iteration: 55123/59290
Iteration: 55124/59290
Iteration: 55125/59290
Iteration: 55126/59290
Iteration: 55127/59290
Iteration: 55128/59290

 93%|█████████▎| 55109/59290 [42:27<01:09, 60.45it/s]

Iteration: 55129/59290
Iteration: 55130/59290
Iteration: 55131/59290
Iteration: 55132/59290
Iteration: 55133/59290
Iteration: 55134/59290
Iteration: 55135/59290
Iteration: 55136/59290
Iteration: 55137/59290
Iteration: 55138/59290
Iteration: 55139/59290
Iteration: 55140/59290
Iteration: 55141/59290
Iteration: 55142/59290
Iteration: 55143/59290
Iteration: 55144/59290
Iteration: 55145/59290
Iteration: 55146/59290
Iteration: 55147/59290
Iteration: 55148/59290
Iteration: 55149/59290
Iteration: 55150/59290
Iteration: 55151/59290
Iteration: 55152/59290

 93%|█████████▎| 55133/59290 [42:27<01:07, 61.41it/s]

Iteration: 55153/59290
Iteration: 55154/59290
Iteration: 55155/59290
Iteration: 55156/59290
Iteration: 55157/59290
Iteration: 55158/59290
Iteration: 55159/59290
Iteration: 55160/59290
Iteration: 55161/59290
Iteration: 55162/59290
Iteration: 55163/59290
Iteration: 55164/59290
Iteration: 55165/59290
Iteration: 55166/59290
Iteration: 55167/59290
Iteration: 55168/59290
Iteration: 55169/59290
Iteration: 55170/59290
Iteration: 55171/59290
Iteration: 55172/59290
Iteration: 55173/59290
Iteration: 55174/59290
Iteration: 55175/59290
Iteration: 55176/59290

 93%|█████████▎| 55157/59290 [42:27<01:07, 61.58it/s]

Iteration: 55177/59290
Iteration: 55178/59290
Iteration: 55179/59290
Iteration: 55180/59290
Iteration: 55181/59290
Iteration: 55182/59290
Iteration: 55183/59290
Iteration: 55184/59290
Iteration: 55185/59290
Iteration: 55186/59290
Iteration: 55187/59290
Iteration: 55188/59290
Iteration: 55189/59290
Iteration: 55190/59290
Iteration: 55191/59290
Iteration: 55192/59290
Iteration: 55193/59290
Iteration: 55194/59290
Iteration: 55195/59290
Iteration: 55196/59290
Iteration: 55197/59290
Iteration: 55198/59290
Iteration: 55199/59290
Iteration: 55200/59290

 93%|█████████▎| 55181/59290 [42:29<02:14, 30.46it/s]

Iteration: 55201/59290
Iteration: 55202/59290
Iteration: 55203/59290
Iteration: 55204/59290
Iteration: 55205/59290
Iteration: 55206/59290
Iteration: 55207/59290
Iteration: 55208/59290
Iteration: 55209/59290
Iteration: 55210/59290
Iteration: 55211/59290
Iteration: 55212/59290
Iteration: 55213/59290
Iteration: 55214/59290
Iteration: 55215/59290
Iteration: 55216/59290
Iteration: 55217/59290
Iteration: 55218/59290
Iteration: 55219/59290
Iteration: 55220/59290
Iteration: 55221/59290
Iteration: 55222/59290
Iteration: 55223/59290
Iteration: 55224/59290

 93%|█████████▎| 55205/59290 [42:32<03:42, 18.37it/s]

Iteration: 55225/59290
Iteration: 55226/59290
Iteration: 55227/59290
Iteration: 55228/59290
Iteration: 55229/59290
Iteration: 55230/59290
Iteration: 55231/59290
Iteration: 55232/59290
Iteration: 55233/59290
Iteration: 55234/59290
Iteration: 55235/59290
Iteration: 55236/59290
Iteration: 55237/59290
Iteration: 55238/59290
Iteration: 55239/59290
Iteration: 55240/59290
Iteration: 55241/59290
Iteration: 55242/59290
Iteration: 55243/59290
Iteration: 55244/59290
Iteration: 55245/59290
Iteration: 55246/59290
Iteration: 55247/59290
Iteration: 55248/59290

 93%|█████████▎| 55229/59290 [42:32<02:55, 23.08it/s]

Iteration: 55249/59290
Iteration: 55250/59290
Iteration: 55251/59290
Iteration: 55252/59290
Iteration: 55253/59290
Iteration: 55254/59290
Iteration: 55255/59290
Iteration: 55256/59290
Iteration: 55257/59290
Iteration: 55258/59290
Iteration: 55259/59290
Iteration: 55260/59290
Iteration: 55261/59290
Iteration: 55262/59290
Iteration: 55263/59290
Iteration: 55264/59290
Iteration: 55265/59290
Iteration: 55266/59290
Iteration: 55267/59290
Iteration: 55268/59290
Iteration: 55269/59290
Iteration: 55270/59290
Iteration: 55271/59290
Iteration: 55272/59290

 93%|█████████▎| 55253/59290 [42:32<02:23, 28.06it/s]

Iteration: 55273/59290
Iteration: 55274/59290
Iteration: 55275/59290
Iteration: 55276/59290
Iteration: 55277/59290
Iteration: 55278/59290
Iteration: 55279/59290
Iteration: 55280/59290
Iteration: 55281/59290
Iteration: 55282/59290
Iteration: 55283/59290
Iteration: 55284/59290
Iteration: 55285/59290
Iteration: 55286/59290
Iteration: 55287/59290
Iteration: 55288/59290
Iteration: 55289/59290
Iteration: 55290/59290
Iteration: 55291/59290
Iteration: 55292/59290
Iteration: 55293/59290
Iteration: 55294/59290
Iteration: 55295/59290
Iteration: 55296/59290

 93%|█████████▎| 55277/59290 [42:33<02:26, 27.30it/s]

Iteration: 55297/59290
Iteration: 55298/59290
Iteration: 55299/59290
Iteration: 55300/59290
Iteration: 55301/59290
Iteration: 55302/59290
Iteration: 55303/59290
Iteration: 55304/59290
Iteration: 55305/59290
Iteration: 55306/59290
Iteration: 55307/59290
Iteration: 55308/59290
Iteration: 55309/59290
Iteration: 55310/59290
Iteration: 55311/59290
Iteration: 55312/59290
Iteration: 55313/59290
Iteration: 55314/59290
Iteration: 55315/59290
Iteration: 55316/59290
Iteration: 55317/59290
Iteration: 55318/59290
Iteration: 55319/59290
Iteration: 55320/59290

 93%|█████████▎| 55301/59290 [42:34<02:00, 32.98it/s]

Iteration: 55321/59290
Iteration: 55322/59290
Iteration: 55323/59290
Iteration: 55324/59290
Iteration: 55325/59290
Iteration: 55326/59290
Iteration: 55327/59290
Iteration: 55328/59290
Iteration: 55329/59290
Iteration: 55330/59290
Iteration: 55331/59290
Iteration: 55332/59290
Iteration: 55333/59290
Iteration: 55334/59290
Iteration: 55335/59290
Iteration: 55336/59290
Iteration: 55337/59290
Iteration: 55338/59290
Iteration: 55339/59290
Iteration: 55340/59290
Iteration: 55341/59290
Iteration: 55342/59290
Iteration: 55343/59290
Iteration: 55344/59290

 93%|█████████▎| 55325/59290 [42:34<01:43, 38.48it/s]

Iteration: 55345/59290
Iteration: 55346/59290
Iteration: 55347/59290
Iteration: 55348/59290
Iteration: 55349/59290
Iteration: 55350/59290
Iteration: 55351/59290
Iteration: 55352/59290
Iteration: 55353/59290
Iteration: 55354/59290
Iteration: 55355/59290
Iteration: 55356/59290
Iteration: 55357/59290
Iteration: 55358/59290
Iteration: 55359/59290
Iteration: 55360/59290
Iteration: 55361/59290
Iteration: 55362/59290
Iteration: 55363/59290
Iteration: 55364/59290
Iteration: 55365/59290
Iteration: 55366/59290
Iteration: 55367/59290
Iteration: 55368/59290

 93%|█████████▎| 55349/59290 [42:35<01:33, 41.96it/s]

Iteration: 55369/59290
Iteration: 55370/59290
Iteration: 55371/59290
Iteration: 55372/59290
Iteration: 55373/59290
Iteration: 55374/59290
Iteration: 55375/59290
Iteration: 55376/59290
Iteration: 55377/59290
Iteration: 55378/59290
Iteration: 55379/59290
Iteration: 55380/59290
Iteration: 55381/59290
Iteration: 55382/59290
Iteration: 55383/59290
Iteration: 55384/59290
Iteration: 55385/59290
Iteration: 55386/59290
Iteration: 55387/59290
Iteration: 55388/59290
Iteration: 55389/59290
Iteration: 55390/59290
Iteration: 55391/59290
Iteration: 55392/59290

 93%|█████████▎| 55373/59290 [42:36<02:19, 28.18it/s]

Iteration: 55393/59290
Iteration: 55394/59290
Iteration: 55395/59290
Iteration: 55396/59290
Iteration: 55397/59290
Iteration: 55398/59290
Iteration: 55399/59290
Iteration: 55400/59290
Iteration: 55401/59290
Iteration: 55402/59290
Iteration: 55403/59290
Iteration: 55404/59290
Iteration: 55405/59290
Iteration: 55406/59290
Iteration: 55407/59290
Iteration: 55408/59290
Iteration: 55409/59290
Iteration: 55410/59290
Iteration: 55411/59290
Iteration: 55412/59290
Iteration: 55413/59290
Iteration: 55414/59290
Iteration: 55415/59290
Iteration: 55416/59290

 93%|█████████▎| 55397/59290 [42:39<04:14, 15.27it/s]

Iteration: 55417/59290
Iteration: 55418/59290
Iteration: 55419/59290
Iteration: 55420/59290
Iteration: 55421/59290
Iteration: 55422/59290
Iteration: 55423/59290
Iteration: 55424/59290
Iteration: 55425/59290
Iteration: 55426/59290
Iteration: 55427/59290
Iteration: 55428/59290
Iteration: 55429/59290
Iteration: 55430/59290
Iteration: 55431/59290
Iteration: 55432/59290
Iteration: 55433/59290
Iteration: 55434/59290
Iteration: 55435/59290
Iteration: 55436/59290
Iteration: 55437/59290
Iteration: 55438/59290
Iteration: 55439/59290
Iteration: 55440/59290

 93%|█████████▎| 55421/59290 [42:40<03:20, 19.31it/s]

Iteration: 55441/59290
Iteration: 55442/59290
Iteration: 55443/59290
Iteration: 55444/59290
Iteration: 55445/59290
Iteration: 55446/59290
Iteration: 55447/59290
Iteration: 55448/59290
Iteration: 55449/59290
Iteration: 55450/59290
Iteration: 55451/59290
Iteration: 55452/59290
Iteration: 55453/59290
Iteration: 55454/59290
Iteration: 55455/59290
Iteration: 55456/59290
Iteration: 55457/59290
Iteration: 55458/59290
Iteration: 55459/59290
Iteration: 55460/59290
Iteration: 55461/59290
Iteration: 55462/59290
Iteration: 55463/59290
Iteration: 55464/59290

 94%|█████████▎| 55445/59290 [42:40<02:39, 24.10it/s]

Iteration: 55465/59290
Iteration: 55466/59290
Iteration: 55467/59290
Iteration: 55468/59290
Iteration: 55469/59290
Iteration: 55470/59290
Iteration: 55471/59290
Iteration: 55472/59290
Iteration: 55473/59290
Iteration: 55474/59290
Iteration: 55475/59290
Iteration: 55476/59290
Iteration: 55477/59290
Iteration: 55478/59290
Iteration: 55479/59290
Iteration: 55480/59290
Iteration: 55481/59290
Iteration: 55482/59290
Iteration: 55483/59290
Iteration: 55484/59290
Iteration: 55485/59290
Iteration: 55486/59290
Iteration: 55487/59290
Iteration: 55488/59290

 94%|█████████▎| 55469/59290 [42:41<02:09, 29.60it/s]

Iteration: 55489/59290
Iteration: 55490/59290
Iteration: 55491/59290
Iteration: 55492/59290
Iteration: 55493/59290
Iteration: 55494/59290
Iteration: 55495/59290
Iteration: 55496/59290
Iteration: 55497/59290
Iteration: 55498/59290
Iteration: 55499/59290
Iteration: 55500/59290
Iteration: 55501/59290
Iteration: 55502/59290
Iteration: 55503/59290
Iteration: 55504/59290
Iteration: 55505/59290
Iteration: 55506/59290
Iteration: 55507/59290
Iteration: 55508/59290
Iteration: 55509/59290
Iteration: 55510/59290
Iteration: 55511/59290
Iteration: 55512/59290

 94%|█████████▎| 55493/59290 [42:41<01:47, 35.24it/s]

Iteration: 55513/59290
Iteration: 55514/59290
Iteration: 55515/59290
Iteration: 55516/59290
Iteration: 55517/59290
Iteration: 55518/59290
Iteration: 55519/59290
Iteration: 55520/59290
Iteration: 55521/59290
Iteration: 55522/59290
Iteration: 55523/59290
Iteration: 55524/59290
Iteration: 55525/59290
Iteration: 55526/59290
Iteration: 55527/59290
Iteration: 55528/59290
Iteration: 55529/59290
Iteration: 55530/59290
Iteration: 55531/59290
Iteration: 55532/59290
Iteration: 55533/59290
Iteration: 55534/59290
Iteration: 55535/59290
Iteration: 55536/59290

 94%|█████████▎| 55517/59290 [42:41<01:32, 40.67it/s]

Iteration: 55537/59290
Iteration: 55538/59290
Iteration: 55539/59290
Iteration: 55540/59290
Iteration: 55541/59290
Iteration: 55542/59290
Iteration: 55543/59290
Iteration: 55544/59290
Iteration: 55545/59290
Iteration: 55546/59290
Iteration: 55547/59290
Iteration: 55548/59290
Iteration: 55549/59290
Iteration: 55550/59290
Iteration: 55551/59290
Iteration: 55552/59290
Iteration: 55553/59290
Iteration: 55554/59290
Iteration: 55555/59290
Iteration: 55556/59290
Iteration: 55557/59290
Iteration: 55558/59290
Iteration: 55559/59290
Iteration: 55560/59290

 94%|█████████▎| 55541/59290 [42:42<01:22, 45.51it/s]

Iteration: 55561/59290
Iteration: 55562/59290
Iteration: 55563/59290
Iteration: 55564/59290
Iteration: 55565/59290
Iteration: 55566/59290
Iteration: 55567/59290
Iteration: 55568/59290
Iteration: 55569/59290
Iteration: 55570/59290
Iteration: 55571/59290
Iteration: 55572/59290
Iteration: 55573/59290
Iteration: 55574/59290
Iteration: 55575/59290
Iteration: 55576/59290
Iteration: 55577/59290
Iteration: 55578/59290
Iteration: 55579/59290
Iteration: 55580/59290
Iteration: 55581/59290
Iteration: 55582/59290
Iteration: 55583/59290
Iteration: 55584/59290

 94%|█████████▎| 55565/59290 [42:42<01:14, 49.69it/s]

Iteration: 55585/59290
Iteration: 55586/59290
Iteration: 55587/59290
Iteration: 55588/59290
Iteration: 55589/59290
Iteration: 55590/59290
Iteration: 55591/59290
Iteration: 55592/59290
Iteration: 55593/59290
Iteration: 55594/59290
Iteration: 55595/59290
Iteration: 55596/59290
Iteration: 55597/59290
Iteration: 55598/59290
Iteration: 55599/59290
Iteration: 55600/59290
Iteration: 55601/59290
Iteration: 55602/59290
Iteration: 55603/59290
Iteration: 55604/59290
Iteration: 55605/59290
Iteration: 55606/59290
Iteration: 55607/59290
Iteration: 55608/59290

 94%|█████████▍| 55589/59290 [42:42<01:09, 53.23it/s]

Iteration: 55609/59290
Iteration: 55610/59290
Iteration: 55611/59290
Iteration: 55612/59290
Iteration: 55613/59290
Iteration: 55614/59290
Iteration: 55615/59290
Iteration: 55616/59290
Iteration: 55617/59290
Iteration: 55618/59290
Iteration: 55619/59290
Iteration: 55620/59290
Iteration: 55621/59290
Iteration: 55622/59290
Iteration: 55623/59290
Iteration: 55624/59290
Iteration: 55625/59290
Iteration: 55626/59290
Iteration: 55627/59290
Iteration: 55628/59290
Iteration: 55629/59290
Iteration: 55630/59290
Iteration: 55631/59290
Iteration: 55632/59290

 94%|█████████▍| 55613/59290 [42:43<01:06, 55.58it/s]

Iteration: 55633/59290
Iteration: 55634/59290
Iteration: 55635/59290
Iteration: 55636/59290
Iteration: 55637/59290
Iteration: 55638/59290
Iteration: 55639/59290
Iteration: 55640/59290
Iteration: 55641/59290
Iteration: 55642/59290
Iteration: 55643/59290
Iteration: 55644/59290
Iteration: 55645/59290
Iteration: 55646/59290
Iteration: 55647/59290
Iteration: 55648/59290
Iteration: 55649/59290
Iteration: 55650/59290
Iteration: 55651/59290
Iteration: 55652/59290
Iteration: 55653/59290
Iteration: 55654/59290
Iteration: 55655/59290
Iteration: 55656/59290

 94%|█████████▍| 55637/59290 [42:44<01:56, 31.25it/s]

Iteration: 55657/59290
Iteration: 55658/59290
Iteration: 55659/59290
Iteration: 55660/59290
Iteration: 55661/59290
Iteration: 55662/59290
Iteration: 55663/59290
Iteration: 55664/59290
Iteration: 55665/59290
Iteration: 55666/59290
Iteration: 55667/59290
Iteration: 55668/59290
Iteration: 55669/59290
Iteration: 55670/59290
Iteration: 55671/59290
Iteration: 55672/59290
Iteration: 55673/59290
Iteration: 55674/59290
Iteration: 55675/59290
Iteration: 55676/59290
Iteration: 55677/59290
Iteration: 55678/59290
Iteration: 55679/59290
Iteration: 55680/59290

 94%|█████████▍| 55661/59290 [42:47<03:22, 17.90it/s]

Iteration: 55681/59290
Iteration: 55682/59290
Iteration: 55683/59290
Iteration: 55684/59290
Iteration: 55685/59290
Iteration: 55686/59290
Iteration: 55687/59290
Iteration: 55688/59290
Iteration: 55689/59290
Iteration: 55690/59290
Iteration: 55691/59290
Iteration: 55692/59290
Iteration: 55693/59290
Iteration: 55694/59290
Iteration: 55695/59290
Iteration: 55696/59290
Iteration: 55697/59290
Iteration: 55698/59290
Iteration: 55699/59290
Iteration: 55700/59290
Iteration: 55701/59290
Iteration: 55702/59290
Iteration: 55703/59290
Iteration: 55704/59290

 94%|█████████▍| 55685/59290 [42:47<02:40, 22.45it/s]

Iteration: 55705/59290
Iteration: 55706/59290
Iteration: 55707/59290
Iteration: 55708/59290
Iteration: 55709/59290
Iteration: 55710/59290
Iteration: 55711/59290
Iteration: 55712/59290
Iteration: 55713/59290
Iteration: 55714/59290
Iteration: 55715/59290
Iteration: 55716/59290
Iteration: 55717/59290
Iteration: 55718/59290
Iteration: 55719/59290
Iteration: 55720/59290
Iteration: 55721/59290
Iteration: 55722/59290
Iteration: 55723/59290
Iteration: 55724/59290
Iteration: 55725/59290
Iteration: 55726/59290
Iteration: 55727/59290
Iteration: 55728/59290

 94%|█████████▍| 55709/59290 [42:48<02:22, 25.04it/s]

Iteration: 55729/59290
Iteration: 55730/59290
Iteration: 55731/59290
Iteration: 55732/59290
Iteration: 55733/59290
Iteration: 55734/59290
Iteration: 55735/59290
Iteration: 55736/59290
Iteration: 55737/59290
Iteration: 55738/59290
Iteration: 55739/59290
Iteration: 55740/59290
Iteration: 55741/59290
Iteration: 55742/59290
Iteration: 55743/59290
Iteration: 55744/59290
Iteration: 55745/59290
Iteration: 55746/59290
Iteration: 55747/59290
Iteration: 55748/59290
Iteration: 55749/59290
Iteration: 55750/59290
Iteration: 55751/59290
Iteration: 55752/59290

 94%|█████████▍| 55733/59290 [42:49<01:56, 30.57it/s]

Iteration: 55753/59290
Iteration: 55754/59290
Iteration: 55755/59290
Iteration: 55756/59290
Iteration: 55757/59290
Iteration: 55758/59290
Iteration: 55759/59290
Iteration: 55760/59290
Iteration: 55761/59290
Iteration: 55762/59290
Iteration: 55763/59290
Iteration: 55764/59290
Iteration: 55765/59290
Iteration: 55766/59290
Iteration: 55767/59290
Iteration: 55768/59290
Iteration: 55769/59290
Iteration: 55770/59290
Iteration: 55771/59290
Iteration: 55772/59290
Iteration: 55773/59290
Iteration: 55774/59290
Iteration: 55775/59290
Iteration: 55776/59290

 94%|█████████▍| 55757/59290 [42:49<01:37, 36.09it/s]

Iteration: 55777/59290
Iteration: 55778/59290
Iteration: 55779/59290
Iteration: 55780/59290
Iteration: 55781/59290
Iteration: 55782/59290
Iteration: 55783/59290
Iteration: 55784/59290
Iteration: 55785/59290
Iteration: 55786/59290
Iteration: 55787/59290
Iteration: 55788/59290
Iteration: 55789/59290
Iteration: 55790/59290
Iteration: 55791/59290
Iteration: 55792/59290
Iteration: 55793/59290
Iteration: 55794/59290
Iteration: 55795/59290
Iteration: 55796/59290
Iteration: 55797/59290
Iteration: 55798/59290
Iteration: 55799/59290
Iteration: 55800/59290

 94%|█████████▍| 55781/59290 [42:49<01:24, 41.49it/s]

Iteration: 55801/59290
Iteration: 55802/59290
Iteration: 55803/59290
Iteration: 55804/59290
Iteration: 55805/59290
Iteration: 55806/59290
Iteration: 55807/59290
Iteration: 55808/59290
Iteration: 55809/59290
Iteration: 55810/59290
Iteration: 55811/59290
Iteration: 55812/59290
Iteration: 55813/59290
Iteration: 55814/59290
Iteration: 55815/59290
Iteration: 55816/59290
Iteration: 55817/59290
Iteration: 55818/59290
Iteration: 55819/59290
Iteration: 55820/59290
Iteration: 55821/59290
Iteration: 55822/59290
Iteration: 55823/59290
Iteration: 55824/59290

 94%|█████████▍| 55805/59290 [42:50<01:15, 46.36it/s]

Iteration: 55825/59290
Iteration: 55826/59290
Iteration: 55827/59290
Iteration: 55828/59290
Iteration: 55829/59290
Iteration: 55830/59290
Iteration: 55831/59290
Iteration: 55832/59290
Iteration: 55833/59290
Iteration: 55834/59290
Iteration: 55835/59290
Iteration: 55836/59290
Iteration: 55837/59290
Iteration: 55838/59290
Iteration: 55839/59290
Iteration: 55840/59290
Iteration: 55841/59290
Iteration: 55842/59290
Iteration: 55843/59290
Iteration: 55844/59290
Iteration: 55845/59290
Iteration: 55846/59290
Iteration: 55847/59290
Iteration: 55848/59290

 94%|█████████▍| 55829/59290 [42:50<01:09, 49.88it/s]

Iteration: 55849/59290
Iteration: 55850/59290
Iteration: 55851/59290
Iteration: 55852/59290
Iteration: 55853/59290
Iteration: 55854/59290
Iteration: 55855/59290
Iteration: 55856/59290
Iteration: 55857/59290
Iteration: 55858/59290
Iteration: 55859/59290
Iteration: 55860/59290
Iteration: 55861/59290
Iteration: 55862/59290
Iteration: 55863/59290
Iteration: 55864/59290
Iteration: 55865/59290
Iteration: 55866/59290
Iteration: 55867/59290
Iteration: 55868/59290
Iteration: 55869/59290
Iteration: 55870/59290
Iteration: 55871/59290
Iteration: 55872/59290

 94%|█████████▍| 55853/59290 [42:50<01:04, 53.16it/s]

Iteration: 55873/59290
Iteration: 55874/59290
Iteration: 55875/59290
Iteration: 55876/59290
Iteration: 55877/59290
Iteration: 55878/59290
Iteration: 55879/59290
Iteration: 55880/59290
Iteration: 55881/59290
Iteration: 55882/59290
Iteration: 55883/59290
Iteration: 55884/59290
Iteration: 55885/59290
Iteration: 55886/59290
Iteration: 55887/59290
Iteration: 55888/59290
Iteration: 55889/59290
Iteration: 55890/59290
Iteration: 55891/59290
Iteration: 55892/59290
Iteration: 55893/59290
Iteration: 55894/59290
Iteration: 55895/59290
Iteration: 55896/59290

 94%|█████████▍| 55877/59290 [42:51<01:00, 55.98it/s]

Iteration: 55897/59290
Iteration: 55898/59290
Iteration: 55899/59290
Iteration: 55900/59290
Iteration: 55901/59290
Iteration: 55902/59290
Iteration: 55903/59290
Iteration: 55904/59290
Iteration: 55905/59290
Iteration: 55906/59290
Iteration: 55907/59290
Iteration: 55908/59290
Iteration: 55909/59290
Iteration: 55910/59290
Iteration: 55911/59290
Iteration: 55912/59290
Iteration: 55913/59290
Iteration: 55914/59290
Iteration: 55915/59290
Iteration: 55916/59290
Iteration: 55917/59290
Iteration: 55918/59290
Iteration: 55919/59290
Iteration: 55920/59290

 94%|█████████▍| 55901/59290 [42:51<00:58, 58.01it/s]

Iteration: 55921/59290
Iteration: 55922/59290
Iteration: 55923/59290
Iteration: 55924/59290
Iteration: 55925/59290
Iteration: 55926/59290
Iteration: 55927/59290
Iteration: 55928/59290
Iteration: 55929/59290
Iteration: 55930/59290
Iteration: 55931/59290
Iteration: 55932/59290
Iteration: 55933/59290
Iteration: 55934/59290
Iteration: 55935/59290
Iteration: 55936/59290
Iteration: 55937/59290
Iteration: 55938/59290
Iteration: 55939/59290
Iteration: 55940/59290
Iteration: 55941/59290
Iteration: 55942/59290
Iteration: 55943/59290
Iteration: 55944/59290

 94%|█████████▍| 55925/59290 [42:52<00:56, 59.83it/s]

Iteration: 55945/59290
Iteration: 55946/59290
Iteration: 55947/59290
Iteration: 55948/59290
Iteration: 55949/59290
Iteration: 55950/59290
Iteration: 55951/59290
Iteration: 55952/59290
Iteration: 55953/59290
Iteration: 55954/59290
Iteration: 55955/59290
Iteration: 55956/59290
Iteration: 55957/59290
Iteration: 55958/59290
Iteration: 55959/59290
Iteration: 55960/59290
Iteration: 55961/59290
Iteration: 55962/59290
Iteration: 55963/59290
Iteration: 55964/59290
Iteration: 55965/59290
Iteration: 55966/59290
Iteration: 55967/59290
Iteration: 55968/59290

 94%|█████████▍| 55949/59290 [42:52<00:55, 60.58it/s]

Iteration: 55969/59290
Iteration: 55970/59290
Iteration: 55971/59290
Iteration: 55972/59290
Iteration: 55973/59290
Iteration: 55974/59290
Iteration: 55975/59290
Iteration: 55976/59290
Iteration: 55977/59290
Iteration: 55978/59290
Iteration: 55979/59290
Iteration: 55980/59290
Iteration: 55981/59290
Iteration: 55982/59290
Iteration: 55983/59290
Iteration: 55984/59290
Iteration: 55985/59290
Iteration: 55986/59290
Iteration: 55987/59290
Iteration: 55988/59290
Iteration: 55989/59290
Iteration: 55990/59290
Iteration: 55991/59290
Iteration: 55992/59290

 94%|█████████▍| 55973/59290 [42:52<00:53, 61.50it/s]

Iteration: 55993/59290
Iteration: 55994/59290
Iteration: 55995/59290
Iteration: 55996/59290
Iteration: 55997/59290
Iteration: 55998/59290
Iteration: 55999/59290
Iteration: 56000/59290
Iteration: 56001/59290
Iteration: 56002/59290
Iteration: 56003/59290
Iteration: 56004/59290
Iteration: 56005/59290
Iteration: 56006/59290
Iteration: 56007/59290
Iteration: 56008/59290
Iteration: 56009/59290
Iteration: 56010/59290
Iteration: 56011/59290
Iteration: 56012/59290
Iteration: 56013/59290
Iteration: 56014/59290
Iteration: 56015/59290
Iteration: 56016/59290

 94%|█████████▍| 55997/59290 [42:53<00:53, 62.02it/s]

Iteration: 56017/59290
Iteration: 56018/59290
Iteration: 56019/59290
Iteration: 56020/59290
Iteration: 56021/59290
Iteration: 56022/59290
Iteration: 56023/59290
Iteration: 56024/59290
Iteration: 56025/59290
Iteration: 56026/59290
Iteration: 56027/59290
Iteration: 56028/59290
Iteration: 56029/59290
Iteration: 56030/59290
Iteration: 56031/59290
Iteration: 56032/59290
Iteration: 56033/59290
Iteration: 56034/59290
Iteration: 56035/59290
Iteration: 56036/59290
Iteration: 56037/59290
Iteration: 56038/59290
Iteration: 56039/59290
Iteration: 56040/59290

 94%|█████████▍| 56021/59290 [42:53<00:52, 62.24it/s]

Iteration: 56041/59290
Iteration: 56042/59290
Iteration: 56043/59290
Iteration: 56044/59290
Iteration: 56045/59290
Iteration: 56046/59290
Iteration: 56047/59290
Iteration: 56048/59290
Iteration: 56049/59290
Iteration: 56050/59290
Iteration: 56051/59290
Iteration: 56052/59290
Iteration: 56053/59290
Iteration: 56054/59290
Iteration: 56055/59290
Iteration: 56056/59290
Iteration: 56057/59290
Iteration: 56058/59290
Iteration: 56059/59290
Iteration: 56060/59290
Iteration: 56061/59290
Iteration: 56062/59290
Iteration: 56063/59290
Iteration: 56064/59290

 95%|█████████▍| 56045/59290 [42:54<00:51, 62.81it/s]

Iteration: 56065/59290
Iteration: 56066/59290
Iteration: 56067/59290
Iteration: 56068/59290
Iteration: 56069/59290
Iteration: 56070/59290
Iteration: 56071/59290
Iteration: 56072/59290
Iteration: 56073/59290
Iteration: 56074/59290
Iteration: 56075/59290
Iteration: 56076/59290
Iteration: 56077/59290
Iteration: 56078/59290
Iteration: 56079/59290
Iteration: 56080/59290
Iteration: 56081/59290
Iteration: 56082/59290
Iteration: 56083/59290
Iteration: 56084/59290
Iteration: 56085/59290
Iteration: 56086/59290
Iteration: 56087/59290
Iteration: 56088/59290

 95%|█████████▍| 56069/59290 [42:55<01:49, 29.36it/s]

Iteration: 56089/59290
Iteration: 56090/59290
Iteration: 56091/59290
Iteration: 56092/59290
Iteration: 56093/59290
Iteration: 56094/59290
Iteration: 56095/59290
Iteration: 56096/59290
Iteration: 56097/59290
Iteration: 56098/59290
Iteration: 56099/59290
Iteration: 56100/59290
Iteration: 56101/59290
Iteration: 56102/59290
Iteration: 56103/59290
Iteration: 56104/59290
Iteration: 56105/59290
Iteration: 56106/59290
Iteration: 56107/59290
Iteration: 56108/59290
Iteration: 56109/59290
Iteration: 56110/59290
Iteration: 56111/59290
Iteration: 56112/59290

 95%|█████████▍| 56093/59290 [42:58<02:59, 17.80it/s]

Iteration: 56113/59290
Iteration: 56114/59290
Iteration: 56115/59290
Iteration: 56116/59290
Iteration: 56117/59290
Iteration: 56118/59290
Iteration: 56119/59290
Iteration: 56120/59290
Iteration: 56121/59290
Iteration: 56122/59290
Iteration: 56123/59290
Iteration: 56124/59290
Iteration: 56125/59290
Iteration: 56126/59290
Iteration: 56127/59290
Iteration: 56128/59290
Iteration: 56129/59290
Iteration: 56130/59290
Iteration: 56131/59290
Iteration: 56132/59290
Iteration: 56133/59290
Iteration: 56134/59290
Iteration: 56135/59290
Iteration: 56136/59290

 95%|█████████▍| 56117/59290 [42:59<02:38, 20.02it/s]

Iteration: 56137/59290
Iteration: 56138/59290
Iteration: 56139/59290
Iteration: 56140/59290
Iteration: 56141/59290
Iteration: 56142/59290
Iteration: 56143/59290
Iteration: 56144/59290
Iteration: 56145/59290
Iteration: 56146/59290
Iteration: 56147/59290
Iteration: 56148/59290
Iteration: 56149/59290
Iteration: 56150/59290
Iteration: 56151/59290
Iteration: 56152/59290
Iteration: 56153/59290
Iteration: 56154/59290
Iteration: 56155/59290
Iteration: 56156/59290
Iteration: 56157/59290
Iteration: 56158/59290
Iteration: 56159/59290
Iteration: 56160/59290

 95%|█████████▍| 56141/59290 [42:59<02:05, 25.17it/s]

Iteration: 56161/59290
Iteration: 56162/59290
Iteration: 56163/59290
Iteration: 56164/59290
Iteration: 56165/59290
Iteration: 56166/59290
Iteration: 56167/59290
Iteration: 56168/59290
Iteration: 56169/59290
Iteration: 56170/59290
Iteration: 56171/59290
Iteration: 56172/59290
Iteration: 56173/59290
Iteration: 56174/59290
Iteration: 56175/59290
Iteration: 56176/59290
Iteration: 56177/59290
Iteration: 56178/59290
Iteration: 56179/59290
Iteration: 56180/59290
Iteration: 56181/59290
Iteration: 56182/59290
Iteration: 56183/59290
Iteration: 56184/59290

 95%|█████████▍| 56165/59290 [43:00<01:41, 30.75it/s]

Iteration: 56185/59290
Iteration: 56186/59290
Iteration: 56187/59290
Iteration: 56188/59290
Iteration: 56189/59290
Iteration: 56190/59290
Iteration: 56191/59290
Iteration: 56192/59290
Iteration: 56193/59290
Iteration: 56194/59290
Iteration: 56195/59290
Iteration: 56196/59290
Iteration: 56197/59290
Iteration: 56198/59290
Iteration: 56199/59290
Iteration: 56200/59290
Iteration: 56201/59290
Iteration: 56202/59290
Iteration: 56203/59290
Iteration: 56204/59290
Iteration: 56205/59290
Iteration: 56206/59290
Iteration: 56207/59290
Iteration: 56208/59290

 95%|█████████▍| 56189/59290 [43:00<01:26, 35.91it/s]

Iteration: 56209/59290
Iteration: 56210/59290
Iteration: 56211/59290
Iteration: 56212/59290
Iteration: 56213/59290
Iteration: 56214/59290
Iteration: 56215/59290
Iteration: 56216/59290
Iteration: 56217/59290
Iteration: 56218/59290
Iteration: 56219/59290
Iteration: 56220/59290
Iteration: 56221/59290
Iteration: 56222/59290
Iteration: 56223/59290
Iteration: 56224/59290
Iteration: 56225/59290
Iteration: 56226/59290
Iteration: 56227/59290
Iteration: 56228/59290
Iteration: 56229/59290
Iteration: 56230/59290
Iteration: 56231/59290
Iteration: 56232/59290

 95%|█████████▍| 56213/59290 [43:01<01:59, 25.73it/s]

Iteration: 56233/59290
Iteration: 56234/59290
Iteration: 56235/59290
Iteration: 56236/59290
Iteration: 56237/59290
Iteration: 56238/59290
Iteration: 56239/59290
Iteration: 56240/59290
Iteration: 56241/59290
Iteration: 56242/59290
Iteration: 56243/59290
Iteration: 56244/59290
Iteration: 56245/59290
Iteration: 56246/59290
Iteration: 56247/59290
Iteration: 56248/59290
Iteration: 56249/59290
Iteration: 56250/59290
Iteration: 56251/59290
Iteration: 56252/59290
Iteration: 56253/59290
Iteration: 56254/59290
Iteration: 56255/59290
Iteration: 56256/59290

 95%|█████████▍| 56237/59290 [43:04<03:05, 16.46it/s]

Iteration: 56257/59290
Iteration: 56258/59290
Iteration: 56259/59290
Iteration: 56260/59290
Iteration: 56261/59290
Iteration: 56262/59290
Iteration: 56263/59290
Iteration: 56264/59290
Iteration: 56265/59290
Iteration: 56266/59290
Iteration: 56267/59290
Iteration: 56268/59290
Iteration: 56269/59290
Iteration: 56270/59290
Iteration: 56271/59290
Iteration: 56272/59290
Iteration: 56273/59290
Iteration: 56274/59290
Iteration: 56275/59290
Iteration: 56276/59290
Iteration: 56277/59290
Iteration: 56278/59290
Iteration: 56279/59290
Iteration: 56280/59290

 95%|█████████▍| 56261/59290 [43:05<02:35, 19.51it/s]

Iteration: 56281/59290
Iteration: 56282/59290
Iteration: 56283/59290
Iteration: 56284/59290
Iteration: 56285/59290
Iteration: 56286/59290
Iteration: 56287/59290
Iteration: 56288/59290
Iteration: 56289/59290
Iteration: 56290/59290
Iteration: 56291/59290
Iteration: 56292/59290
Iteration: 56293/59290
Iteration: 56294/59290
Iteration: 56295/59290
Iteration: 56296/59290
Iteration: 56297/59290
Iteration: 56298/59290
Iteration: 56299/59290
Iteration: 56300/59290
Iteration: 56301/59290
Iteration: 56302/59290
Iteration: 56303/59290
Iteration: 56304/59290

 95%|█████████▍| 56285/59290 [43:05<02:02, 24.55it/s]

Iteration: 56305/59290
Iteration: 56306/59290
Iteration: 56307/59290
Iteration: 56308/59290
Iteration: 56309/59290
Iteration: 56310/59290
Iteration: 56311/59290
Iteration: 56312/59290
Iteration: 56313/59290
Iteration: 56314/59290
Iteration: 56315/59290
Iteration: 56316/59290
Iteration: 56317/59290
Iteration: 56318/59290
Iteration: 56319/59290
Iteration: 56320/59290
Iteration: 56321/59290
Iteration: 56322/59290
Iteration: 56323/59290
Iteration: 56324/59290
Iteration: 56325/59290
Iteration: 56326/59290
Iteration: 56327/59290
Iteration: 56328/59290

 95%|█████████▍| 56309/59290 [43:06<01:39, 29.84it/s]

Iteration: 56329/59290
Iteration: 56330/59290
Iteration: 56331/59290
Iteration: 56332/59290
Iteration: 56333/59290
Iteration: 56334/59290
Iteration: 56335/59290
Iteration: 56336/59290
Iteration: 56337/59290
Iteration: 56338/59290
Iteration: 56339/59290
Iteration: 56340/59290
Iteration: 56341/59290
Iteration: 56342/59290
Iteration: 56343/59290
Iteration: 56344/59290
Iteration: 56345/59290
Iteration: 56346/59290
Iteration: 56347/59290
Iteration: 56348/59290
Iteration: 56349/59290
Iteration: 56350/59290
Iteration: 56351/59290
Iteration: 56352/59290

 95%|█████████▌| 56333/59290 [43:06<01:24, 35.19it/s]

Iteration: 56353/59290
Iteration: 56354/59290
Iteration: 56355/59290
Iteration: 56356/59290
Iteration: 56357/59290
Iteration: 56358/59290
Iteration: 56359/59290
Iteration: 56360/59290
Iteration: 56361/59290
Iteration: 56362/59290
Iteration: 56363/59290
Iteration: 56364/59290
Iteration: 56365/59290
Iteration: 56366/59290
Iteration: 56367/59290
Iteration: 56368/59290
Iteration: 56369/59290
Iteration: 56370/59290
Iteration: 56371/59290
Iteration: 56372/59290
Iteration: 56373/59290
Iteration: 56374/59290
Iteration: 56375/59290
Iteration: 56376/59290

 95%|█████████▌| 56357/59290 [43:08<02:04, 23.63it/s]

Iteration: 56377/59290
Iteration: 56378/59290
Iteration: 56379/59290
Iteration: 56380/59290
Iteration: 56381/59290
Iteration: 56382/59290
Iteration: 56383/59290
Iteration: 56384/59290
Iteration: 56385/59290
Iteration: 56386/59290
Iteration: 56387/59290
Iteration: 56388/59290
Iteration: 56389/59290
Iteration: 56390/59290
Iteration: 56391/59290
Iteration: 56392/59290
Iteration: 56393/59290
Iteration: 56394/59290
Iteration: 56395/59290
Iteration: 56396/59290
Iteration: 56397/59290
Iteration: 56398/59290
Iteration: 56399/59290
Iteration: 56400/59290

 95%|█████████▌| 56381/59290 [43:11<03:06, 15.56it/s]

Iteration: 56401/59290
Iteration: 56402/59290
Iteration: 56403/59290
Iteration: 56404/59290
Iteration: 56405/59290
Iteration: 56406/59290
Iteration: 56407/59290
Iteration: 56408/59290
Iteration: 56409/59290
Iteration: 56410/59290
Iteration: 56411/59290
Iteration: 56412/59290
Iteration: 56413/59290
Iteration: 56414/59290
Iteration: 56415/59290
Iteration: 56416/59290
Iteration: 56417/59290
Iteration: 56418/59290
Iteration: 56419/59290
Iteration: 56420/59290
Iteration: 56421/59290
Iteration: 56422/59290
Iteration: 56423/59290
Iteration: 56424/59290

 95%|█████████▌| 56405/59290 [43:11<02:24, 20.02it/s]

Iteration: 56425/59290
Iteration: 56426/59290
Iteration: 56427/59290
Iteration: 56428/59290
Iteration: 56429/59290
Iteration: 56430/59290
Iteration: 56431/59290
Iteration: 56432/59290
Iteration: 56433/59290
Iteration: 56434/59290
Iteration: 56435/59290
Iteration: 56436/59290
Iteration: 56437/59290
Iteration: 56438/59290
Iteration: 56439/59290
Iteration: 56440/59290
Iteration: 56441/59290
Iteration: 56442/59290
Iteration: 56443/59290
Iteration: 56444/59290
Iteration: 56445/59290
Iteration: 56446/59290
Iteration: 56447/59290
Iteration: 56448/59290

 95%|█████████▌| 56429/59290 [43:12<02:07, 22.42it/s]

Iteration: 56449/59290
Iteration: 56450/59290
Iteration: 56451/59290
Iteration: 56452/59290
Iteration: 56453/59290
Iteration: 56454/59290
Iteration: 56455/59290
Iteration: 56456/59290
Iteration: 56457/59290
Iteration: 56458/59290
Iteration: 56459/59290
Iteration: 56460/59290
Iteration: 56461/59290
Iteration: 56462/59290
Iteration: 56463/59290
Iteration: 56464/59290
Iteration: 56465/59290
Iteration: 56466/59290
Iteration: 56467/59290
Iteration: 56468/59290
Iteration: 56469/59290
Iteration: 56470/59290
Iteration: 56471/59290
Iteration: 56472/59290

 95%|█████████▌| 56453/59290 [43:12<01:42, 27.65it/s]

Iteration: 56473/59290
Iteration: 56474/59290
Iteration: 56475/59290
Iteration: 56476/59290
Iteration: 56477/59290
Iteration: 56478/59290
Iteration: 56479/59290
Iteration: 56480/59290
Iteration: 56481/59290
Iteration: 56482/59290
Iteration: 56483/59290
Iteration: 56484/59290
Iteration: 56485/59290
Iteration: 56486/59290
Iteration: 56487/59290
Iteration: 56488/59290
Iteration: 56489/59290
Iteration: 56490/59290
Iteration: 56491/59290
Iteration: 56492/59290
Iteration: 56493/59290
Iteration: 56494/59290
Iteration: 56495/59290
Iteration: 56496/59290

 95%|█████████▌| 56477/59290 [43:13<01:25, 33.04it/s]

Iteration: 56497/59290
Iteration: 56498/59290
Iteration: 56499/59290
Iteration: 56500/59290
Iteration: 56501/59290
Iteration: 56502/59290
Iteration: 56503/59290
Iteration: 56504/59290
Iteration: 56505/59290
Iteration: 56506/59290
Iteration: 56507/59290
Iteration: 56508/59290
Iteration: 56509/59290
Iteration: 56510/59290
Iteration: 56511/59290
Iteration: 56512/59290
Iteration: 56513/59290
Iteration: 56514/59290
Iteration: 56515/59290
Iteration: 56516/59290
Iteration: 56517/59290
Iteration: 56518/59290
Iteration: 56519/59290
Iteration: 56520/59290

 95%|█████████▌| 56501/59290 [43:13<01:12, 38.64it/s]

Iteration: 56521/59290
Iteration: 56522/59290
Iteration: 56523/59290
Iteration: 56524/59290
Iteration: 56525/59290
Iteration: 56526/59290
Iteration: 56527/59290
Iteration: 56528/59290
Iteration: 56529/59290
Iteration: 56530/59290
Iteration: 56531/59290
Iteration: 56532/59290
Iteration: 56533/59290
Iteration: 56534/59290
Iteration: 56535/59290
Iteration: 56536/59290
Iteration: 56537/59290
Iteration: 56538/59290
Iteration: 56539/59290
Iteration: 56540/59290
Iteration: 56541/59290
Iteration: 56542/59290
Iteration: 56543/59290
Iteration: 56544/59290

 95%|█████████▌| 56525/59290 [43:13<01:03, 43.81it/s]

Iteration: 56545/59290
Iteration: 56546/59290
Iteration: 56547/59290
Iteration: 56548/59290
Iteration: 56549/59290
Iteration: 56550/59290
Iteration: 56551/59290
Iteration: 56552/59290
Iteration: 56553/59290
Iteration: 56554/59290
Iteration: 56555/59290
Iteration: 56556/59290
Iteration: 56557/59290
Iteration: 56558/59290
Iteration: 56559/59290
Iteration: 56560/59290
Iteration: 56561/59290
Iteration: 56562/59290
Iteration: 56563/59290
Iteration: 56564/59290
Iteration: 56565/59290
Iteration: 56566/59290
Iteration: 56567/59290
Iteration: 56568/59290

 95%|█████████▌| 56549/59290 [43:14<00:56, 48.34it/s]

Iteration: 56569/59290
Iteration: 56570/59290
Iteration: 56571/59290
Iteration: 56572/59290
Iteration: 56573/59290
Iteration: 56574/59290
Iteration: 56575/59290
Iteration: 56576/59290
Iteration: 56577/59290
Iteration: 56578/59290
Iteration: 56579/59290
Iteration: 56580/59290
Iteration: 56581/59290
Iteration: 56582/59290
Iteration: 56583/59290
Iteration: 56584/59290
Iteration: 56585/59290
Iteration: 56586/59290
Iteration: 56587/59290
Iteration: 56588/59290
Iteration: 56589/59290
Iteration: 56590/59290
Iteration: 56591/59290
Iteration: 56592/59290

 95%|█████████▌| 56573/59290 [43:14<00:52, 51.99it/s]

Iteration: 56593/59290
Iteration: 56594/59290
Iteration: 56595/59290
Iteration: 56596/59290
Iteration: 56597/59290
Iteration: 56598/59290
Iteration: 56599/59290
Iteration: 56600/59290
Iteration: 56601/59290
Iteration: 56602/59290
Iteration: 56603/59290
Iteration: 56604/59290
Iteration: 56605/59290
Iteration: 56606/59290
Iteration: 56607/59290
Iteration: 56608/59290
Iteration: 56609/59290
Iteration: 56610/59290
Iteration: 56611/59290
Iteration: 56612/59290
Iteration: 56613/59290
Iteration: 56614/59290
Iteration: 56616/59290

 95%|█████████▌| 56596/59290 [43:15<00:51, 52.63it/s]

Iteration: 56617/59290
Iteration: 56618/59290
Iteration: 56619/59290
Iteration: 56620/59290
Iteration: 56621/59290
Iteration: 56622/59290
Iteration: 56623/59290
Iteration: 56624/59290

 95%|█████████▌| 56604/59290 [43:16<01:59, 22.51it/s]

Iteration: 56625/59290
Iteration: 56626/59290
Iteration: 56627/59290
Iteration: 56628/59290
Iteration: 56629/59290
Iteration: 56630/59290
Iteration: 56631/59290
Iteration: 56632/59290
Iteration: 56633/59290
Iteration: 56634/59290
Iteration: 56635/59290
Iteration: 56636/59290
Iteration: 56637/59290
Iteration: 56638/59290
Iteration: 56639/59290
Iteration: 56640/59290
Iteration: 56641/59290
Iteration: 56642/59290
Iteration: 56643/59290
Iteration: 56644/59290
Iteration: 56645/59290
Iteration: 56646/59290
Iteration: 56647/59290
Iteration: 56648/59290

 96%|█████████▌| 56628/59290 [43:19<02:56, 15.07it/s]

Iteration: 56649/59290
Iteration: 56650/59290
Iteration: 56651/59290
Iteration: 56652/59290
Iteration: 56653/59290
Iteration: 56654/59290
Iteration: 56655/59290
Iteration: 56656/59290
Iteration: 56657/59290
Iteration: 56658/59290
Iteration: 56659/59290
Iteration: 56660/59290
Iteration: 56661/59290
Iteration: 56662/59290
Iteration: 56663/59290
Iteration: 56664/59290
Iteration: 56665/59290
Iteration: 56666/59290
Iteration: 56667/59290
Iteration: 56668/59290
Iteration: 56669/59290
Iteration: 56670/59290
Iteration: 56671/59290
Iteration: 56672/59290

 96%|█████████▌| 56652/59290 [43:20<02:33, 17.23it/s]

Iteration: 56673/59290
Iteration: 56674/59290
Iteration: 56675/59290
Iteration: 56676/59290
Iteration: 56677/59290
Iteration: 56678/59290
Iteration: 56679/59290
Iteration: 56680/59290
Iteration: 56681/59290
Iteration: 56682/59290
Iteration: 56683/59290
Iteration: 56684/59290
Iteration: 56685/59290
Iteration: 56686/59290
Iteration: 56687/59290
Iteration: 56688/59290
Iteration: 56689/59290
Iteration: 56690/59290
Iteration: 56691/59290
Iteration: 56692/59290
Iteration: 56693/59290
Iteration: 56694/59290
Iteration: 56695/59290
Iteration: 56696/59290

 96%|█████████▌| 56676/59290 [43:20<01:56, 22.42it/s]

Iteration: 56697/59290
Iteration: 56698/59290
Iteration: 56699/59290
Iteration: 56700/59290
Iteration: 56701/59290
Iteration: 56702/59290
Iteration: 56703/59290
Iteration: 56704/59290
Iteration: 56705/59290
Iteration: 56706/59290
Iteration: 56707/59290
Iteration: 56708/59290
Iteration: 56709/59290
Iteration: 56710/59290
Iteration: 56711/59290
Iteration: 56712/59290
Iteration: 56713/59290
Iteration: 56714/59290
Iteration: 56715/59290
Iteration: 56716/59290
Iteration: 56717/59290
Iteration: 56718/59290
Iteration: 56719/59290
Iteration: 56720/59290

 96%|█████████▌| 56700/59290 [43:21<01:32, 28.02it/s]

Iteration: 56721/59290
Iteration: 56722/59290
Iteration: 56723/59290
Iteration: 56724/59290
Iteration: 56725/59290
Iteration: 56726/59290
Iteration: 56727/59290
Iteration: 56728/59290
Iteration: 56729/59290
Iteration: 56730/59290
Iteration: 56731/59290
Iteration: 56732/59290
Iteration: 56733/59290
Iteration: 56734/59290
Iteration: 56735/59290
Iteration: 56736/59290
Iteration: 56737/59290
Iteration: 56738/59290
Iteration: 56739/59290
Iteration: 56740/59290
Iteration: 56741/59290
Iteration: 56742/59290
Iteration: 56743/59290
Iteration: 56744/59290

 96%|█████████▌| 56724/59290 [43:21<01:15, 33.85it/s]

Iteration: 56745/59290
Iteration: 56746/59290
Iteration: 56747/59290
Iteration: 56748/59290
Iteration: 56749/59290
Iteration: 56750/59290
Iteration: 56751/59290
Iteration: 56752/59290
Iteration: 56753/59290
Iteration: 56754/59290
Iteration: 56755/59290
Iteration: 56756/59290
Iteration: 56757/59290
Iteration: 56758/59290
Iteration: 56759/59290
Iteration: 56760/59290
Iteration: 56761/59290
Iteration: 56762/59290
Iteration: 56763/59290
Iteration: 56764/59290
Iteration: 56765/59290
Iteration: 56766/59290
Iteration: 56767/59290
Iteration: 56768/59290

 96%|█████████▌| 56748/59290 [43:21<01:04, 39.51it/s]

Iteration: 56769/59290
Iteration: 56770/59290
Iteration: 56771/59290
Iteration: 56772/59290
Iteration: 56773/59290
Iteration: 56774/59290
Iteration: 56775/59290
Iteration: 56776/59290
Iteration: 56777/59290
Iteration: 56778/59290
Iteration: 56779/59290
Iteration: 56780/59290
Iteration: 56781/59290
Iteration: 56782/59290
Iteration: 56783/59290
Iteration: 56784/59290
Iteration: 56785/59290
Iteration: 56786/59290
Iteration: 56787/59290
Iteration: 56788/59290
Iteration: 56789/59290
Iteration: 56790/59290
Iteration: 56791/59290
Iteration: 56792/59290

 96%|█████████▌| 56772/59290 [43:22<00:56, 44.37it/s]

Iteration: 56793/59290
Iteration: 56794/59290
Iteration: 56795/59290
Iteration: 56796/59290
Iteration: 56797/59290
Iteration: 56798/59290
Iteration: 56799/59290
Iteration: 56800/59290
Iteration: 56801/59290
Iteration: 56802/59290
Iteration: 56803/59290
Iteration: 56804/59290
Iteration: 56805/59290
Iteration: 56806/59290
Iteration: 56807/59290
Iteration: 56808/59290
Iteration: 56809/59290
Iteration: 56810/59290
Iteration: 56811/59290
Iteration: 56812/59290
Iteration: 56813/59290
Iteration: 56814/59290
Iteration: 56815/59290
Iteration: 56816/59290

 96%|█████████▌| 56796/59290 [43:22<00:51, 48.66it/s]

Iteration: 56817/59290
Iteration: 56818/59290
Iteration: 56819/59290
Iteration: 56820/59290
Iteration: 56821/59290
Iteration: 56822/59290
Iteration: 56823/59290
Iteration: 56824/59290
Iteration: 56825/59290
Iteration: 56826/59290
Iteration: 56827/59290
Iteration: 56828/59290
Iteration: 56829/59290
Iteration: 56830/59290
Iteration: 56831/59290
Iteration: 56832/59290
Iteration: 56833/59290
Iteration: 56834/59290
Iteration: 56835/59290
Iteration: 56836/59290
Iteration: 56837/59290
Iteration: 56838/59290
Iteration: 56839/59290
Iteration: 56840/59290

 96%|█████████▌| 56820/59290 [43:23<00:47, 52.46it/s]

Iteration: 56841/59290
Iteration: 56842/59290
Iteration: 56843/59290
Iteration: 56844/59290
Iteration: 56845/59290
Iteration: 56846/59290
Iteration: 56847/59290
Iteration: 56848/59290
Iteration: 56849/59290
Iteration: 56850/59290
Iteration: 56851/59290
Iteration: 56852/59290
Iteration: 56853/59290
Iteration: 56854/59290
Iteration: 56855/59290
Iteration: 56856/59290
Iteration: 56857/59290
Iteration: 56858/59290
Iteration: 56859/59290
Iteration: 56860/59290
Iteration: 56861/59290
Iteration: 56862/59290
Iteration: 56863/59290
Iteration: 56864/59290

 96%|█████████▌| 56844/59290 [43:23<00:44, 54.88it/s]

Iteration: 56865/59290
Iteration: 56866/59290
Iteration: 56867/59290
Iteration: 56868/59290
Iteration: 56869/59290
Iteration: 56870/59290
Iteration: 56871/59290
Iteration: 56872/59290
Iteration: 56873/59290
Iteration: 56874/59290
Iteration: 56875/59290
Iteration: 56876/59290
Iteration: 56877/59290
Iteration: 56878/59290
Iteration: 56879/59290
Iteration: 56880/59290
Iteration: 56881/59290
Iteration: 56882/59290
Iteration: 56883/59290
Iteration: 56884/59290
Iteration: 56885/59290
Iteration: 56886/59290
Iteration: 56887/59290
Iteration: 56888/59290

 96%|█████████▌| 56868/59290 [43:23<00:42, 57.02it/s]

Iteration: 56889/59290
Iteration: 56890/59290
Iteration: 56891/59290
Iteration: 56892/59290
Iteration: 56893/59290
Iteration: 56894/59290
Iteration: 56895/59290
Iteration: 56896/59290
Iteration: 56897/59290
Iteration: 56898/59290
Iteration: 56899/59290
Iteration: 56900/59290
Iteration: 56901/59290
Iteration: 56902/59290
Iteration: 56903/59290
Iteration: 56904/59290
Iteration: 56905/59290
Iteration: 56906/59290
Iteration: 56907/59290
Iteration: 56908/59290
Iteration: 56909/59290
Iteration: 56910/59290
Iteration: 56911/59290
Iteration: 56912/59290

 96%|█████████▌| 56892/59290 [43:24<00:40, 58.63it/s]

Iteration: 56913/59290
Iteration: 56914/59290
Iteration: 56915/59290
Iteration: 56916/59290
Iteration: 56917/59290
Iteration: 56918/59290
Iteration: 56919/59290
Iteration: 56920/59290
Iteration: 56921/59290
Iteration: 56922/59290
Iteration: 56923/59290
Iteration: 56924/59290
Iteration: 56925/59290
Iteration: 56926/59290
Iteration: 56927/59290
Iteration: 56928/59290
Iteration: 56929/59290
Iteration: 56930/59290
Iteration: 56931/59290
Iteration: 56932/59290
Iteration: 56933/59290
Iteration: 56934/59290
Iteration: 56935/59290
Iteration: 56936/59290

 96%|█████████▌| 56916/59290 [43:24<00:39, 60.31it/s]

Iteration: 56937/59290
Iteration: 56938/59290
Iteration: 56939/59290
Iteration: 56940/59290
Iteration: 56941/59290
Iteration: 56942/59290
Iteration: 56943/59290
Iteration: 56944/59290
Iteration: 56945/59290
Iteration: 56946/59290
Iteration: 56947/59290
Iteration: 56948/59290
Iteration: 56949/59290
Iteration: 56950/59290
Iteration: 56951/59290
Iteration: 56952/59290
Iteration: 56953/59290
Iteration: 56954/59290
Iteration: 56955/59290
Iteration: 56956/59290
Iteration: 56957/59290
Iteration: 56958/59290
Iteration: 56959/59290
Iteration: 56960/59290

 96%|█████████▌| 56940/59290 [43:24<00:38, 61.27it/s]

Iteration: 56961/59290
Iteration: 56962/59290
Iteration: 56963/59290
Iteration: 56964/59290
Iteration: 56965/59290
Iteration: 56966/59290
Iteration: 56967/59290
Iteration: 56968/59290
Iteration: 56969/59290
Iteration: 56970/59290
Iteration: 56971/59290
Iteration: 56972/59290
Iteration: 56973/59290
Iteration: 56974/59290
Iteration: 56975/59290
Iteration: 56976/59290
Iteration: 56977/59290
Iteration: 56978/59290
Iteration: 56979/59290
Iteration: 56980/59290
Iteration: 56981/59290
Iteration: 56982/59290
Iteration: 56983/59290
Iteration: 56984/59290

 96%|█████████▌| 56964/59290 [43:25<00:37, 61.26it/s]

Iteration: 56985/59290
Iteration: 56986/59290
Iteration: 56987/59290
Iteration: 56988/59290
Iteration: 56989/59290
Iteration: 56990/59290
Iteration: 56991/59290
Iteration: 56992/59290
Iteration: 56993/59290
Iteration: 56994/59290
Iteration: 56995/59290
Iteration: 56996/59290
Iteration: 56997/59290
Iteration: 56998/59290
Iteration: 56999/59290
Iteration: 57000/59290
Iteration: 57001/59290
Iteration: 57002/59290
Iteration: 57003/59290
Iteration: 57004/59290
Iteration: 57005/59290
Iteration: 57006/59290
Iteration: 57007/59290
Iteration: 57008/59290

 96%|█████████▌| 56988/59290 [43:25<00:37, 62.13it/s]

Iteration: 57009/59290
Iteration: 57010/59290
Iteration: 57011/59290
Iteration: 57012/59290
Iteration: 57013/59290
Iteration: 57014/59290
Iteration: 57015/59290
Iteration: 57016/59290
Iteration: 57017/59290
Iteration: 57018/59290
Iteration: 57019/59290
Iteration: 57020/59290
Iteration: 57021/59290
Iteration: 57022/59290
Iteration: 57023/59290
Iteration: 57024/59290
Iteration: 57025/59290
Iteration: 57026/59290
Iteration: 57027/59290
Iteration: 57028/59290
Iteration: 57029/59290
Iteration: 57030/59290
Iteration: 57031/59290
Iteration: 57032/59290

 96%|█████████▌| 57012/59290 [43:26<00:36, 62.30it/s]

Iteration: 57033/59290
Iteration: 57034/59290
Iteration: 57035/59290
Iteration: 57036/59290
Iteration: 57037/59290
Iteration: 57038/59290
Iteration: 57039/59290
Iteration: 57040/59290
Iteration: 57041/59290
Iteration: 57042/59290
Iteration: 57043/59290
Iteration: 57044/59290
Iteration: 57045/59290
Iteration: 57046/59290
Iteration: 57047/59290
Iteration: 57048/59290
Iteration: 57049/59290
Iteration: 57050/59290
Iteration: 57051/59290
Iteration: 57052/59290
Iteration: 57053/59290
Iteration: 57054/59290
Iteration: 57055/59290
Iteration: 57056/59290

 96%|█████████▌| 57036/59290 [43:27<01:16, 29.60it/s]

Iteration: 57057/59290
Iteration: 57058/59290
Iteration: 57059/59290
Iteration: 57060/59290
Iteration: 57061/59290
Iteration: 57062/59290
Iteration: 57063/59290
Iteration: 57064/59290
Iteration: 57065/59290
Iteration: 57066/59290
Iteration: 57067/59290
Iteration: 57068/59290
Iteration: 57069/59290
Iteration: 57070/59290
Iteration: 57071/59290
Iteration: 57072/59290
Iteration: 57073/59290
Iteration: 57074/59290
Iteration: 57075/59290
Iteration: 57076/59290
Iteration: 57077/59290
Iteration: 57078/59290
Iteration: 57079/59290
Iteration: 57080/59290

 96%|█████████▌| 57060/59290 [43:30<02:03, 18.02it/s]

Iteration: 57081/59290
Iteration: 57082/59290
Iteration: 57083/59290
Iteration: 57084/59290
Iteration: 57085/59290
Iteration: 57086/59290
Iteration: 57087/59290
Iteration: 57088/59290
Iteration: 57089/59290
Iteration: 57090/59290
Iteration: 57091/59290
Iteration: 57092/59290
Iteration: 57093/59290
Iteration: 57094/59290
Iteration: 57095/59290
Iteration: 57096/59290
Iteration: 57097/59290
Iteration: 57098/59290
Iteration: 57099/59290
Iteration: 57100/59290
Iteration: 57101/59290
Iteration: 57102/59290
Iteration: 57103/59290
Iteration: 57104/59290

 96%|█████████▋| 57084/59290 [43:31<01:45, 20.90it/s]

Iteration: 57105/59290
Iteration: 57106/59290
Iteration: 57107/59290
Iteration: 57108/59290
Iteration: 57109/59290
Iteration: 57110/59290
Iteration: 57111/59290
Iteration: 57112/59290
Iteration: 57113/59290
Iteration: 57114/59290
Iteration: 57115/59290
Iteration: 57116/59290
Iteration: 57117/59290
Iteration: 57118/59290
Iteration: 57119/59290
Iteration: 57120/59290
Iteration: 57121/59290
Iteration: 57122/59290
Iteration: 57123/59290
Iteration: 57124/59290
Iteration: 57125/59290
Iteration: 57126/59290
Iteration: 57127/59290
Iteration: 57128/59290

 96%|█████████▋| 57108/59290 [43:31<01:25, 25.67it/s]

Iteration: 57129/59290
Iteration: 57130/59290
Iteration: 57131/59290
Iteration: 57132/59290
Iteration: 57133/59290
Iteration: 57134/59290
Iteration: 57135/59290
Iteration: 57136/59290
Iteration: 57137/59290
Iteration: 57138/59290
Iteration: 57139/59290
Iteration: 57140/59290
Iteration: 57141/59290
Iteration: 57142/59290
Iteration: 57143/59290
Iteration: 57144/59290
Iteration: 57145/59290
Iteration: 57146/59290
Iteration: 57147/59290
Iteration: 57148/59290
Iteration: 57149/59290
Iteration: 57150/59290
Iteration: 57151/59290
Iteration: 57152/59290

 96%|█████████▋| 57132/59290 [43:31<01:08, 31.36it/s]

Iteration: 57153/59290
Iteration: 57154/59290
Iteration: 57155/59290
Iteration: 57156/59290
Iteration: 57157/59290
Iteration: 57158/59290
Iteration: 57159/59290
Iteration: 57160/59290
Iteration: 57161/59290
Iteration: 57162/59290
Iteration: 57163/59290
Iteration: 57164/59290
Iteration: 57165/59290
Iteration: 57166/59290
Iteration: 57167/59290
Iteration: 57168/59290
Iteration: 57169/59290
Iteration: 57170/59290
Iteration: 57171/59290
Iteration: 57172/59290
Iteration: 57173/59290
Iteration: 57174/59290
Iteration: 57175/59290
Iteration: 57176/59290

 96%|█████████▋| 57156/59290 [43:32<00:58, 36.48it/s]

Iteration: 57177/59290
Iteration: 57178/59290
Iteration: 57179/59290
Iteration: 57180/59290
Iteration: 57181/59290
Iteration: 57182/59290
Iteration: 57183/59290
Iteration: 57184/59290
Iteration: 57185/59290
Iteration: 57186/59290
Iteration: 57187/59290
Iteration: 57188/59290
Iteration: 57189/59290
Iteration: 57190/59290
Iteration: 57191/59290
Iteration: 57192/59290
Iteration: 57193/59290
Iteration: 57194/59290
Iteration: 57195/59290
Iteration: 57196/59290
Iteration: 57197/59290
Iteration: 57198/59290
Iteration: 57199/59290
Iteration: 57200/59290

 96%|█████████▋| 57180/59290 [43:34<01:25, 24.78it/s]

Iteration: 57201/59290
Iteration: 57202/59290
Iteration: 57203/59290
Iteration: 57204/59290
Iteration: 57205/59290
Iteration: 57206/59290
Iteration: 57207/59290
Iteration: 57208/59290
Iteration: 57209/59290
Iteration: 57210/59290
Iteration: 57211/59290
Iteration: 57212/59290
Iteration: 57213/59290
Iteration: 57214/59290
Iteration: 57215/59290
Iteration: 57216/59290
Iteration: 57217/59290
Iteration: 57218/59290
Iteration: 57219/59290
Iteration: 57220/59290
Iteration: 57221/59290
Iteration: 57222/59290
Iteration: 57223/59290
Iteration: 57224/59290

 96%|█████████▋| 57204/59290 [43:37<02:24, 14.43it/s]

Iteration: 57225/59290
Iteration: 57226/59290
Iteration: 57227/59290
Iteration: 57228/59290
Iteration: 57229/59290
Iteration: 57230/59290
Iteration: 57231/59290
Iteration: 57232/59290
Iteration: 57233/59290
Iteration: 57234/59290
Iteration: 57235/59290
Iteration: 57236/59290
Iteration: 57237/59290
Iteration: 57238/59290
Iteration: 57239/59290
Iteration: 57240/59290
Iteration: 57241/59290
Iteration: 57242/59290
Iteration: 57243/59290
Iteration: 57244/59290
Iteration: 57245/59290
Iteration: 57246/59290
Iteration: 57247/59290
Iteration: 57248/59290

 97%|█████████▋| 57228/59290 [43:37<01:50, 18.68it/s]

Iteration: 57249/59290
Iteration: 57250/59290
Iteration: 57251/59290
Iteration: 57252/59290
Iteration: 57253/59290
Iteration: 57254/59290
Iteration: 57255/59290
Iteration: 57256/59290
Iteration: 57257/59290
Iteration: 57258/59290
Iteration: 57259/59290
Iteration: 57260/59290
Iteration: 57261/59290
Iteration: 57262/59290
Iteration: 57263/59290
Iteration: 57264/59290
Iteration: 57265/59290
Iteration: 57266/59290
Iteration: 57267/59290
Iteration: 57268/59290
Iteration: 57269/59290
Iteration: 57270/59290
Iteration: 57271/59290
Iteration: 57272/59290

 97%|█████████▋| 57252/59290 [43:38<01:26, 23.52it/s]

Iteration: 57273/59290
Iteration: 57274/59290
Iteration: 57275/59290
Iteration: 57276/59290
Iteration: 57277/59290
Iteration: 57278/59290
Iteration: 57279/59290
Iteration: 57280/59290
Iteration: 57281/59290
Iteration: 57282/59290
Iteration: 57283/59290
Iteration: 57284/59290
Iteration: 57285/59290
Iteration: 57286/59290
Iteration: 57287/59290
Iteration: 57288/59290
Iteration: 57289/59290
Iteration: 57290/59290
Iteration: 57291/59290
Iteration: 57292/59290
Iteration: 57293/59290
Iteration: 57294/59290
Iteration: 57295/59290
Iteration: 57296/59290

 97%|█████████▋| 57276/59290 [43:38<01:09, 28.81it/s]

Iteration: 57297/59290
Iteration: 57298/59290
Iteration: 57299/59290
Iteration: 57300/59290
Iteration: 57301/59290
Iteration: 57302/59290
Iteration: 57303/59290
Iteration: 57304/59290
Iteration: 57305/59290
Iteration: 57306/59290
Iteration: 57307/59290
Iteration: 57308/59290
Iteration: 57309/59290
Iteration: 57310/59290
Iteration: 57311/59290
Iteration: 57312/59290
Iteration: 57313/59290
Iteration: 57314/59290
Iteration: 57315/59290
Iteration: 57316/59290
Iteration: 57317/59290
Iteration: 57318/59290
Iteration: 57319/59290
Iteration: 57320/59290

 97%|█████████▋| 57300/59290 [43:40<01:28, 22.61it/s]

Iteration: 57321/59290
Iteration: 57322/59290
Iteration: 57323/59290
Iteration: 57324/59290
Iteration: 57325/59290
Iteration: 57326/59290
Iteration: 57327/59290
Iteration: 57328/59290
Iteration: 57329/59290
Iteration: 57330/59290
Iteration: 57331/59290
Iteration: 57332/59290
Iteration: 57333/59290
Iteration: 57334/59290
Iteration: 57335/59290
Iteration: 57336/59290
Iteration: 57337/59290
Iteration: 57338/59290
Iteration: 57339/59290
Iteration: 57340/59290
Iteration: 57341/59290
Iteration: 57342/59290
Iteration: 57343/59290
Iteration: 57344/59290

 97%|█████████▋| 57324/59290 [43:42<02:05, 15.64it/s]

Iteration: 57345/59290
Iteration: 57346/59290
Iteration: 57347/59290
Iteration: 57348/59290
Iteration: 57349/59290
Iteration: 57350/59290
Iteration: 57351/59290
Iteration: 57352/59290
Iteration: 57353/59290
Iteration: 57354/59290
Iteration: 57355/59290
Iteration: 57356/59290
Iteration: 57357/59290
Iteration: 57358/59290
Iteration: 57359/59290
Iteration: 57360/59290
Iteration: 57361/59290
Iteration: 57362/59290
Iteration: 57363/59290
Iteration: 57364/59290
Iteration: 57365/59290
Iteration: 57366/59290
Iteration: 57367/59290
Iteration: 57368/59290

 97%|█████████▋| 57348/59290 [43:43<01:52, 17.29it/s]

Iteration: 57369/59290
Iteration: 57370/59290
Iteration: 57371/59290
Iteration: 57372/59290
Iteration: 57373/59290
Iteration: 57374/59290
Iteration: 57375/59290
Iteration: 57376/59290
Iteration: 57377/59290
Iteration: 57378/59290
Iteration: 57379/59290
Iteration: 57380/59290
Iteration: 57381/59290
Iteration: 57382/59290
Iteration: 57383/59290
Iteration: 57384/59290
Iteration: 57385/59290
Iteration: 57386/59290
Iteration: 57387/59290
Iteration: 57388/59290
Iteration: 57389/59290
Iteration: 57390/59290
Iteration: 57391/59290
Iteration: 57392/59290

 97%|█████████▋| 57372/59290 [43:44<01:26, 22.13it/s]

Iteration: 57393/59290
Iteration: 57394/59290
Iteration: 57395/59290
Iteration: 57396/59290
Iteration: 57397/59290
Iteration: 57398/59290
Iteration: 57399/59290
Iteration: 57400/59290
Iteration: 57401/59290
Iteration: 57402/59290
Iteration: 57403/59290
Iteration: 57404/59290
Iteration: 57405/59290
Iteration: 57406/59290
Iteration: 57407/59290
Iteration: 57408/59290
Iteration: 57409/59290
Iteration: 57410/59290
Iteration: 57411/59290
Iteration: 57412/59290
Iteration: 57413/59290
Iteration: 57414/59290
Iteration: 57415/59290
Iteration: 57416/59290

 97%|█████████▋| 57396/59290 [43:44<01:08, 27.54it/s]

Iteration: 57417/59290
Iteration: 57418/59290
Iteration: 57419/59290
Iteration: 57420/59290
Iteration: 57421/59290
Iteration: 57422/59290
Iteration: 57423/59290
Iteration: 57424/59290
Iteration: 57425/59290
Iteration: 57426/59290
Iteration: 57427/59290
Iteration: 57428/59290
Iteration: 57429/59290
Iteration: 57430/59290
Iteration: 57431/59290
Iteration: 57432/59290
Iteration: 57433/59290
Iteration: 57434/59290
Iteration: 57435/59290
Iteration: 57436/59290
Iteration: 57437/59290
Iteration: 57438/59290
Iteration: 57439/59290
Iteration: 57440/59290

 97%|█████████▋| 57420/59290 [43:44<00:56, 33.15it/s]

Iteration: 57441/59290
Iteration: 57442/59290
Iteration: 57443/59290
Iteration: 57444/59290
Iteration: 57445/59290
Iteration: 57446/59290
Iteration: 57447/59290
Iteration: 57448/59290
Iteration: 57449/59290
Iteration: 57450/59290
Iteration: 57451/59290
Iteration: 57452/59290
Iteration: 57453/59290
Iteration: 57454/59290
Iteration: 57455/59290
Iteration: 57456/59290
Iteration: 57457/59290
Iteration: 57458/59290
Iteration: 57459/59290
Iteration: 57460/59290
Iteration: 57461/59290
Iteration: 57462/59290
Iteration: 57463/59290
Iteration: 57464/59290

 97%|█████████▋| 57444/59290 [43:45<00:47, 38.55it/s]

Iteration: 57465/59290
Iteration: 57466/59290
Iteration: 57467/59290
Iteration: 57468/59290
Iteration: 57469/59290
Iteration: 57470/59290
Iteration: 57471/59290
Iteration: 57472/59290
Iteration: 57473/59290
Iteration: 57474/59290
Iteration: 57475/59290
Iteration: 57476/59290
Iteration: 57477/59290
Iteration: 57478/59290
Iteration: 57479/59290
Iteration: 57480/59290
Iteration: 57481/59290
Iteration: 57482/59290
Iteration: 57483/59290
Iteration: 57484/59290
Iteration: 57485/59290
Iteration: 57486/59290
Iteration: 57487/59290
Iteration: 57488/59290

 97%|█████████▋| 57468/59290 [43:45<00:41, 43.69it/s]

Iteration: 57489/59290
Iteration: 57490/59290
Iteration: 57491/59290
Iteration: 57492/59290
Iteration: 57493/59290
Iteration: 57494/59290
Iteration: 57495/59290
Iteration: 57496/59290
Iteration: 57497/59290
Iteration: 57498/59290
Iteration: 57499/59290
Iteration: 57500/59290
Iteration: 57501/59290
Iteration: 57502/59290
Iteration: 57503/59290
Iteration: 57504/59290
Iteration: 57505/59290
Iteration: 57506/59290
Iteration: 57507/59290
Iteration: 57508/59290
Iteration: 57509/59290
Iteration: 57510/59290
Iteration: 57511/59290
Iteration: 57512/59290

 97%|█████████▋| 57492/59290 [43:46<00:37, 48.19it/s]

Iteration: 57513/59290
Iteration: 57514/59290
Iteration: 57515/59290
Iteration: 57516/59290
Iteration: 57517/59290
Iteration: 57518/59290
Iteration: 57519/59290
Iteration: 57520/59290
Iteration: 57521/59290
Iteration: 57522/59290
Iteration: 57523/59290
Iteration: 57524/59290
Iteration: 57525/59290
Iteration: 57526/59290
Iteration: 57527/59290
Iteration: 57528/59290
Iteration: 57529/59290
Iteration: 57530/59290
Iteration: 57531/59290
Iteration: 57532/59290
Iteration: 57533/59290
Iteration: 57534/59290
Iteration: 57535/59290
Iteration: 57536/59290

 97%|█████████▋| 57516/59290 [43:46<00:34, 51.63it/s]

Iteration: 57537/59290
Iteration: 57538/59290
Iteration: 57539/59290
Iteration: 57540/59290
Iteration: 57541/59290
Iteration: 57542/59290
Iteration: 57543/59290
Iteration: 57544/59290
Iteration: 57545/59290
Iteration: 57546/59290
Iteration: 57547/59290
Iteration: 57548/59290
Iteration: 57549/59290
Iteration: 57550/59290
Iteration: 57551/59290
Iteration: 57552/59290
Iteration: 57553/59290
Iteration: 57554/59290
Iteration: 57555/59290
Iteration: 57556/59290
Iteration: 57557/59290
Iteration: 57558/59290
Iteration: 57559/59290
Iteration: 57560/59290

 97%|█████████▋| 57540/59290 [43:48<01:01, 28.34it/s]

Iteration: 57561/59290
Iteration: 57562/59290
Iteration: 57563/59290
Iteration: 57564/59290
Iteration: 57565/59290
Iteration: 57566/59290
Iteration: 57567/59290
Iteration: 57568/59290
Iteration: 57569/59290
Iteration: 57570/59290
Iteration: 57571/59290
Iteration: 57572/59290
Iteration: 57573/59290
Iteration: 57574/59290
Iteration: 57575/59290
Iteration: 57576/59290
Iteration: 57577/59290
Iteration: 57578/59290
Iteration: 57579/59290
Iteration: 57580/59290
Iteration: 57581/59290
Iteration: 57582/59290
Iteration: 57583/59290
Iteration: 57584/59290

 97%|█████████▋| 57564/59290 [43:50<01:40, 17.11it/s]

Iteration: 57585/59290
Iteration: 57586/59290
Iteration: 57587/59290
Iteration: 57588/59290
Iteration: 57589/59290
Iteration: 57590/59290
Iteration: 57591/59290
Iteration: 57592/59290
Iteration: 57593/59290
Iteration: 57594/59290
Iteration: 57595/59290
Iteration: 57596/59290
Iteration: 57597/59290
Iteration: 57598/59290
Iteration: 57599/59290
Iteration: 57600/59290
Iteration: 57601/59290
Iteration: 57602/59290
Iteration: 57603/59290
Iteration: 57604/59290
Iteration: 57605/59290
Iteration: 57606/59290
Iteration: 57607/59290
Iteration: 57608/59290

 97%|█████████▋| 57588/59290 [43:51<01:24, 20.10it/s]

Iteration: 57609/59290
Iteration: 57610/59290
Iteration: 57611/59290
Iteration: 57612/59290
Iteration: 57613/59290
Iteration: 57614/59290
Iteration: 57615/59290
Iteration: 57616/59290
Iteration: 57617/59290
Iteration: 57618/59290
Iteration: 57619/59290
Iteration: 57620/59290
Iteration: 57621/59290
Iteration: 57622/59290
Iteration: 57623/59290
Iteration: 57624/59290
Iteration: 57625/59290
Iteration: 57626/59290
Iteration: 57627/59290
Iteration: 57628/59290
Iteration: 57629/59290
Iteration: 57630/59290
Iteration: 57631/59290
Iteration: 57632/59290

 97%|█████████▋| 57612/59290 [43:52<01:06, 25.24it/s]

Iteration: 57633/59290
Iteration: 57634/59290
Iteration: 57635/59290
Iteration: 57636/59290
Iteration: 57637/59290
Iteration: 57638/59290
Iteration: 57639/59290
Iteration: 57640/59290
Iteration: 57641/59290
Iteration: 57642/59290
Iteration: 57643/59290
Iteration: 57644/59290
Iteration: 57645/59290
Iteration: 57646/59290
Iteration: 57647/59290
Iteration: 57648/59290
Iteration: 57649/59290
Iteration: 57650/59290
Iteration: 57651/59290
Iteration: 57652/59290
Iteration: 57653/59290
Iteration: 57654/59290
Iteration: 57655/59290
Iteration: 57656/59290

 97%|█████████▋| 57636/59290 [43:52<00:53, 30.81it/s]

Iteration: 57657/59290
Iteration: 57658/59290
Iteration: 57659/59290
Iteration: 57660/59290
Iteration: 57661/59290
Iteration: 57662/59290
Iteration: 57663/59290
Iteration: 57664/59290
Iteration: 57665/59290
Iteration: 57666/59290
Iteration: 57667/59290
Iteration: 57668/59290
Iteration: 57669/59290
Iteration: 57670/59290
Iteration: 57671/59290
Iteration: 57672/59290
Iteration: 57673/59290
Iteration: 57674/59290
Iteration: 57675/59290
Iteration: 57676/59290
Iteration: 57677/59290
Iteration: 57678/59290
Iteration: 57679/59290
Iteration: 57680/59290

 97%|█████████▋| 57660/59290 [43:52<00:44, 36.46it/s]

Iteration: 57681/59290
Iteration: 57682/59290
Iteration: 57683/59290
Iteration: 57684/59290
Iteration: 57685/59290
Iteration: 57686/59290
Iteration: 57687/59290
Iteration: 57688/59290
Iteration: 57689/59290
Iteration: 57690/59290
Iteration: 57691/59290
Iteration: 57692/59290
Iteration: 57693/59290
Iteration: 57694/59290
Iteration: 57695/59290
Iteration: 57696/59290
Iteration: 57697/59290
Iteration: 57698/59290
Iteration: 57699/59290
Iteration: 57700/59290
Iteration: 57701/59290
Iteration: 57702/59290
Iteration: 57703/59290
Iteration: 57704/59290

 97%|█████████▋| 57684/59290 [43:53<00:38, 41.85it/s]

Iteration: 57705/59290
Iteration: 57706/59290
Iteration: 57707/59290
Iteration: 57708/59290
Iteration: 57709/59290
Iteration: 57710/59290
Iteration: 57711/59290
Iteration: 57712/59290
Iteration: 57713/59290
Iteration: 57714/59290
Iteration: 57715/59290
Iteration: 57716/59290
Iteration: 57717/59290
Iteration: 57718/59290
Iteration: 57719/59290
Iteration: 57720/59290
Iteration: 57721/59290
Iteration: 57722/59290
Iteration: 57723/59290
Iteration: 57724/59290
Iteration: 57725/59290
Iteration: 57726/59290
Iteration: 57727/59290
Iteration: 57728/59290

 97%|█████████▋| 57708/59290 [43:53<00:34, 46.02it/s]

Iteration: 57729/59290
Iteration: 57730/59290
Iteration: 57731/59290
Iteration: 57732/59290
Iteration: 57733/59290
Iteration: 57734/59290
Iteration: 57735/59290
Iteration: 57736/59290
Iteration: 57737/59290
Iteration: 57738/59290
Iteration: 57739/59290
Iteration: 57740/59290
Iteration: 57741/59290
Iteration: 57742/59290
Iteration: 57743/59290
Iteration: 57744/59290
Iteration: 57745/59290
Iteration: 57746/59290
Iteration: 57747/59290
Iteration: 57748/59290
Iteration: 57749/59290
Iteration: 57750/59290
Iteration: 57751/59290
Iteration: 57752/59290

 97%|█████████▋| 57732/59290 [43:53<00:31, 49.80it/s]

Iteration: 57753/59290
Iteration: 57754/59290
Iteration: 57755/59290
Iteration: 57756/59290
Iteration: 57757/59290
Iteration: 57758/59290
Iteration: 57759/59290
Iteration: 57760/59290
Iteration: 57761/59290
Iteration: 57762/59290
Iteration: 57763/59290
Iteration: 57764/59290
Iteration: 57765/59290
Iteration: 57766/59290
Iteration: 57767/59290
Iteration: 57768/59290
Iteration: 57769/59290
Iteration: 57770/59290
Iteration: 57771/59290
Iteration: 57772/59290
Iteration: 57773/59290
Iteration: 57774/59290
Iteration: 57775/59290
Iteration: 57776/59290

 97%|█████████▋| 57756/59290 [43:54<00:28, 53.30it/s]

Iteration: 57777/59290
Iteration: 57778/59290
Iteration: 57779/59290
Iteration: 57780/59290
Iteration: 57781/59290
Iteration: 57782/59290
Iteration: 57783/59290
Iteration: 57784/59290
Iteration: 57785/59290
Iteration: 57786/59290
Iteration: 57787/59290
Iteration: 57788/59290
Iteration: 57789/59290
Iteration: 57790/59290
Iteration: 57791/59290
Iteration: 57792/59290
Iteration: 57793/59290
Iteration: 57794/59290
Iteration: 57795/59290
Iteration: 57796/59290
Iteration: 57797/59290
Iteration: 57798/59290
Iteration: 57799/59290
Iteration: 57800/59290

 97%|█████████▋| 57780/59290 [43:54<00:27, 55.79it/s]

Iteration: 57801/59290
Iteration: 57802/59290
Iteration: 57803/59290
Iteration: 57804/59290
Iteration: 57805/59290
Iteration: 57806/59290
Iteration: 57807/59290
Iteration: 57808/59290
Iteration: 57809/59290
Iteration: 57810/59290
Iteration: 57811/59290
Iteration: 57812/59290
Iteration: 57813/59290
Iteration: 57814/59290
Iteration: 57815/59290
Iteration: 57816/59290
Iteration: 57817/59290
Iteration: 57818/59290
Iteration: 57819/59290
Iteration: 57820/59290
Iteration: 57821/59290
Iteration: 57822/59290
Iteration: 57823/59290
Iteration: 57824/59290

 97%|█████████▋| 57804/59290 [43:55<00:25, 58.11it/s]

Iteration: 57825/59290
Iteration: 57826/59290
Iteration: 57827/59290
Iteration: 57828/59290
Iteration: 57829/59290
Iteration: 57830/59290
Iteration: 57831/59290
Iteration: 57832/59290
Iteration: 57833/59290
Iteration: 57834/59290
Iteration: 57835/59290
Iteration: 57836/59290
Iteration: 57837/59290
Iteration: 57838/59290
Iteration: 57839/59290
Iteration: 57840/59290
Iteration: 57841/59290
Iteration: 57842/59290
Iteration: 57843/59290
Iteration: 57844/59290
Iteration: 57845/59290
Iteration: 57846/59290
Iteration: 57847/59290
Iteration: 57848/59290

 98%|█████████▊| 57828/59290 [43:55<00:24, 59.50it/s]

Iteration: 57849/59290
Iteration: 57850/59290
Iteration: 57851/59290
Iteration: 57852/59290
Iteration: 57853/59290
Iteration: 57854/59290
Iteration: 57855/59290
Iteration: 57856/59290
Iteration: 57857/59290
Iteration: 57858/59290
Iteration: 57859/59290
Iteration: 57860/59290
Iteration: 57861/59290
Iteration: 57862/59290
Iteration: 57863/59290
Iteration: 57864/59290
Iteration: 57865/59290
Iteration: 57866/59290
Iteration: 57867/59290
Iteration: 57868/59290
Iteration: 57869/59290
Iteration: 57870/59290
Iteration: 57871/59290
Iteration: 57872/59290

 98%|█████████▊| 57852/59290 [43:55<00:23, 60.59it/s]

Iteration: 57873/59290
Iteration: 57874/59290
Iteration: 57875/59290
Iteration: 57876/59290
Iteration: 57877/59290
Iteration: 57878/59290
Iteration: 57879/59290
Iteration: 57880/59290
Iteration: 57881/59290
Iteration: 57882/59290
Iteration: 57883/59290
Iteration: 57884/59290
Iteration: 57885/59290
Iteration: 57886/59290
Iteration: 57887/59290
Iteration: 57888/59290
Iteration: 57889/59290
Iteration: 57890/59290
Iteration: 57891/59290
Iteration: 57892/59290
Iteration: 57893/59290
Iteration: 57894/59290
Iteration: 57895/59290
Iteration: 57896/59290

 98%|█████████▊| 57876/59290 [43:56<00:22, 61.56it/s]

Iteration: 57897/59290
Iteration: 57898/59290
Iteration: 57899/59290
Iteration: 57900/59290
Iteration: 57901/59290
Iteration: 57902/59290
Iteration: 57903/59290
Iteration: 57904/59290
Iteration: 57905/59290
Iteration: 57906/59290
Iteration: 57907/59290
Iteration: 57908/59290
Iteration: 57909/59290
Iteration: 57910/59290
Iteration: 57911/59290
Iteration: 57912/59290
Iteration: 57913/59290
Iteration: 57914/59290
Iteration: 57915/59290
Iteration: 57916/59290
Iteration: 57917/59290
Iteration: 57918/59290
Iteration: 57919/59290
Iteration: 57920/59290

 98%|█████████▊| 57900/59290 [43:56<00:22, 62.50it/s]

Iteration: 57921/59290
Iteration: 57922/59290
Iteration: 57923/59290
Iteration: 57924/59290
Iteration: 57925/59290
Iteration: 57926/59290
Iteration: 57927/59290
Iteration: 57928/59290
Iteration: 57929/59290
Iteration: 57930/59290
Iteration: 57931/59290
Iteration: 57932/59290
Iteration: 57933/59290
Iteration: 57934/59290
Iteration: 57935/59290
Iteration: 57936/59290
Iteration: 57937/59290
Iteration: 57938/59290
Iteration: 57939/59290
Iteration: 57940/59290
Iteration: 57941/59290
Iteration: 57942/59290
Iteration: 57943/59290
Iteration: 57944/59290

 98%|█████████▊| 57924/59290 [43:58<00:44, 30.52it/s]

Iteration: 57945/59290
Iteration: 57946/59290
Iteration: 57947/59290
Iteration: 57948/59290
Iteration: 57949/59290
Iteration: 57950/59290
Iteration: 57951/59290
Iteration: 57952/59290
Iteration: 57953/59290
Iteration: 57954/59290
Iteration: 57955/59290
Iteration: 57956/59290
Iteration: 57957/59290
Iteration: 57958/59290
Iteration: 57959/59290
Iteration: 57960/59290
Iteration: 57961/59290
Iteration: 57962/59290
Iteration: 57963/59290
Iteration: 57964/59290
Iteration: 57965/59290
Iteration: 57966/59290
Iteration: 57967/59290
Iteration: 57968/59290

 98%|█████████▊| 57948/59290 [44:01<01:24, 15.91it/s]

Iteration: 57969/59290
Iteration: 57970/59290
Iteration: 57971/59290
Iteration: 57972/59290
Iteration: 57973/59290
Iteration: 57974/59290
Iteration: 57975/59290
Iteration: 57976/59290
Iteration: 57977/59290
Iteration: 57978/59290
Iteration: 57979/59290
Iteration: 57980/59290
Iteration: 57981/59290
Iteration: 57982/59290
Iteration: 57983/59290
Iteration: 57984/59290
Iteration: 57985/59290
Iteration: 57986/59290
Iteration: 57987/59290
Iteration: 57988/59290
Iteration: 57989/59290
Iteration: 57990/59290
Iteration: 57991/59290
Iteration: 57992/59290

 98%|█████████▊| 57972/59290 [44:01<01:04, 20.36it/s]

Iteration: 57993/59290
Iteration: 57994/59290
Iteration: 57995/59290
Iteration: 57996/59290
Iteration: 57997/59290
Iteration: 57998/59290
Iteration: 57999/59290
Iteration: 58000/59290
Iteration: 58001/59290
Iteration: 58002/59290
Iteration: 58003/59290
Iteration: 58004/59290
Iteration: 58005/59290
Iteration: 58006/59290
Iteration: 58007/59290
Iteration: 58008/59290
Iteration: 58009/59290
Iteration: 58010/59290
Iteration: 58011/59290
Iteration: 58012/59290
Iteration: 58013/59290
Iteration: 58014/59290
Iteration: 58015/59290
Iteration: 58016/59290

 98%|█████████▊| 57996/59290 [44:02<00:50, 25.62it/s]

Iteration: 58017/59290
Iteration: 58018/59290
Iteration: 58019/59290
Iteration: 58020/59290
Iteration: 58021/59290
Iteration: 58022/59290
Iteration: 58023/59290
Iteration: 58024/59290
Iteration: 58025/59290
Iteration: 58026/59290
Iteration: 58027/59290
Iteration: 58028/59290
Iteration: 58029/59290
Iteration: 58030/59290
Iteration: 58031/59290
Iteration: 58032/59290
Iteration: 58033/59290
Iteration: 58034/59290
Iteration: 58035/59290
Iteration: 58036/59290
Iteration: 58037/59290
Iteration: 58038/59290
Iteration: 58039/59290
Iteration: 58040/59290

 98%|█████████▊| 58020/59290 [44:02<00:40, 31.20it/s]

Iteration: 58041/59290
Iteration: 58042/59290
Iteration: 58043/59290
Iteration: 58044/59290
Iteration: 58045/59290
Iteration: 58046/59290
Iteration: 58047/59290
Iteration: 58048/59290
Iteration: 58049/59290
Iteration: 58050/59290
Iteration: 58051/59290
Iteration: 58052/59290
Iteration: 58053/59290
Iteration: 58054/59290
Iteration: 58055/59290
Iteration: 58056/59290
Iteration: 58057/59290
Iteration: 58058/59290
Iteration: 58059/59290
Iteration: 58060/59290
Iteration: 58061/59290
Iteration: 58062/59290
Iteration: 58063/59290
Iteration: 58064/59290

 98%|█████████▊| 58044/59290 [44:03<00:33, 36.73it/s]

Iteration: 58065/59290
Iteration: 58066/59290
Iteration: 58067/59290
Iteration: 58068/59290
Iteration: 58069/59290
Iteration: 58070/59290
Iteration: 58071/59290
Iteration: 58072/59290
Iteration: 58073/59290
Iteration: 58074/59290
Iteration: 58075/59290
Iteration: 58076/59290
Iteration: 58077/59290
Iteration: 58078/59290
Iteration: 58079/59290
Iteration: 58080/59290
Iteration: 58081/59290
Iteration: 58082/59290
Iteration: 58083/59290
Iteration: 58084/59290
Iteration: 58085/59290
Iteration: 58086/59290
Iteration: 58087/59290
Iteration: 58088/59290

 98%|█████████▊| 58068/59290 [44:04<00:50, 24.16it/s]

Iteration: 58089/59290
Iteration: 58090/59290
Iteration: 58091/59290
Iteration: 58092/59290
Iteration: 58093/59290
Iteration: 58094/59290
Iteration: 58095/59290
Iteration: 58096/59290
Iteration: 58097/59290
Iteration: 58098/59290
Iteration: 58099/59290
Iteration: 58100/59290
Iteration: 58101/59290
Iteration: 58102/59290
Iteration: 58103/59290
Iteration: 58104/59290
Iteration: 58105/59290
Iteration: 58106/59290
Iteration: 58107/59290
Iteration: 58108/59290
Iteration: 58109/59290
Iteration: 58110/59290
Iteration: 58111/59290
Iteration: 58112/59290

 98%|█████████▊| 58092/59290 [44:07<01:15, 15.86it/s]

Iteration: 58113/59290
Iteration: 58114/59290
Iteration: 58115/59290
Iteration: 58116/59290
Iteration: 58117/59290
Iteration: 58118/59290
Iteration: 58119/59290
Iteration: 58120/59290
Iteration: 58121/59290
Iteration: 58122/59290
Iteration: 58123/59290
Iteration: 58124/59290
Iteration: 58125/59290
Iteration: 58126/59290
Iteration: 58127/59290
Iteration: 58128/59290
Iteration: 58129/59290
Iteration: 58130/59290
Iteration: 58131/59290
Iteration: 58132/59290
Iteration: 58133/59290
Iteration: 58134/59290
Iteration: 58135/59290
Iteration: 58136/59290

 98%|█████████▊| 58116/59290 [44:08<01:03, 18.35it/s]

Iteration: 58137/59290
Iteration: 58138/59290
Iteration: 58139/59290
Iteration: 58140/59290
Iteration: 58141/59290
Iteration: 58142/59290
Iteration: 58143/59290
Iteration: 58144/59290
Iteration: 58145/59290
Iteration: 58146/59290
Iteration: 58147/59290
Iteration: 58148/59290
Iteration: 58149/59290
Iteration: 58150/59290
Iteration: 58151/59290
Iteration: 58152/59290
Iteration: 58153/59290
Iteration: 58154/59290
Iteration: 58155/59290
Iteration: 58156/59290
Iteration: 58157/59290
Iteration: 58158/59290
Iteration: 58159/59290
Iteration: 58160/59290

 98%|█████████▊| 58140/59290 [44:08<00:49, 23.14it/s]

Iteration: 58161/59290
Iteration: 58162/59290
Iteration: 58163/59290
Iteration: 58164/59290
Iteration: 58165/59290
Iteration: 58166/59290
Iteration: 58167/59290
Iteration: 58168/59290
Iteration: 58169/59290
Iteration: 58170/59290
Iteration: 58171/59290
Iteration: 58172/59290
Iteration: 58173/59290
Iteration: 58174/59290
Iteration: 58175/59290
Iteration: 58176/59290
Iteration: 58177/59290
Iteration: 58178/59290
Iteration: 58179/59290
Iteration: 58180/59290
Iteration: 58181/59290
Iteration: 58182/59290
Iteration: 58183/59290
Iteration: 58184/59290

 98%|█████████▊| 58164/59290 [44:09<00:39, 28.56it/s]

Iteration: 58185/59290
Iteration: 58186/59290
Iteration: 58187/59290
Iteration: 58188/59290
Iteration: 58189/59290
Iteration: 58190/59290
Iteration: 58191/59290
Iteration: 58192/59290
Iteration: 58193/59290
Iteration: 58194/59290
Iteration: 58195/59290
Iteration: 58196/59290
Iteration: 58197/59290
Iteration: 58198/59290
Iteration: 58199/59290
Iteration: 58200/59290
Iteration: 58201/59290
Iteration: 58202/59290
Iteration: 58203/59290
Iteration: 58204/59290
Iteration: 58205/59290
Iteration: 58206/59290
Iteration: 58207/59290
Iteration: 58208/59290

 98%|█████████▊| 58188/59290 [44:09<00:32, 34.16it/s]

Iteration: 58209/59290
Iteration: 58210/59290
Iteration: 58211/59290
Iteration: 58212/59290
Iteration: 58213/59290
Iteration: 58214/59290
Iteration: 58215/59290
Iteration: 58216/59290
Iteration: 58217/59290
Iteration: 58218/59290
Iteration: 58219/59290
Iteration: 58220/59290
Iteration: 58221/59290
Iteration: 58222/59290
Iteration: 58223/59290
Iteration: 58224/59290
Iteration: 58225/59290
Iteration: 58226/59290
Iteration: 58227/59290
Iteration: 58228/59290
Iteration: 58229/59290
Iteration: 58230/59290
Iteration: 58231/59290
Iteration: 58232/59290

 98%|█████████▊| 58212/59290 [44:11<00:43, 24.88it/s]

Iteration: 58233/59290
Iteration: 58234/59290
Iteration: 58235/59290
Iteration: 58236/59290
Iteration: 58237/59290
Iteration: 58238/59290
Iteration: 58239/59290
Iteration: 58240/59290
Iteration: 58241/59290
Iteration: 58242/59290
Iteration: 58243/59290
Iteration: 58244/59290
Iteration: 58245/59290
Iteration: 58246/59290
Iteration: 58247/59290
Iteration: 58248/59290
Iteration: 58249/59290
Iteration: 58250/59290
Iteration: 58251/59290
Iteration: 58252/59290
Iteration: 58253/59290
Iteration: 58254/59290
Iteration: 58255/59290
Iteration: 58256/59290

 98%|█████████▊| 58236/59290 [44:13<01:03, 16.70it/s]

Iteration: 58257/59290
Iteration: 58258/59290
Iteration: 58259/59290
Iteration: 58260/59290
Iteration: 58261/59290
Iteration: 58262/59290
Iteration: 58263/59290
Iteration: 58264/59290
Iteration: 58265/59290
Iteration: 58266/59290
Iteration: 58267/59290
Iteration: 58268/59290
Iteration: 58269/59290
Iteration: 58270/59290
Iteration: 58271/59290
Iteration: 58272/59290
Iteration: 58273/59290
Iteration: 58274/59290
Iteration: 58275/59290
Iteration: 58276/59290
Iteration: 58277/59290
Iteration: 58278/59290
Iteration: 58279/59290
Iteration: 58280/59290

 98%|█████████▊| 58260/59290 [44:14<00:53, 19.26it/s]

Iteration: 58281/59290
Iteration: 58282/59290
Iteration: 58283/59290
Iteration: 58284/59290
Iteration: 58285/59290
Iteration: 58286/59290
Iteration: 58287/59290
Iteration: 58288/59290
Iteration: 58289/59290
Iteration: 58290/59290
Iteration: 58291/59290
Iteration: 58292/59290
Iteration: 58293/59290
Iteration: 58294/59290
Iteration: 58295/59290
Iteration: 58296/59290
Iteration: 58297/59290
Iteration: 58298/59290
Iteration: 58299/59290
Iteration: 58300/59290
Iteration: 58301/59290
Iteration: 58302/59290
Iteration: 58303/59290
Iteration: 58304/59290

 98%|█████████▊| 58284/59290 [44:14<00:41, 24.32it/s]

Iteration: 58305/59290
Iteration: 58306/59290
Iteration: 58307/59290
Iteration: 58308/59290
Iteration: 58309/59290
Iteration: 58310/59290
Iteration: 58311/59290
Iteration: 58312/59290
Iteration: 58313/59290
Iteration: 58314/59290
Iteration: 58315/59290
Iteration: 58316/59290
Iteration: 58317/59290
Iteration: 58318/59290
Iteration: 58319/59290
Iteration: 58320/59290
Iteration: 58321/59290
Iteration: 58322/59290
Iteration: 58323/59290
Iteration: 58324/59290
Iteration: 58325/59290
Iteration: 58326/59290
Iteration: 58327/59290
Iteration: 58328/59290

 98%|█████████▊| 58308/59290 [44:15<00:32, 29.83it/s]

Iteration: 58329/59290
Iteration: 58330/59290
Iteration: 58331/59290
Iteration: 58332/59290
Iteration: 58333/59290
Iteration: 58334/59290
Iteration: 58335/59290
Iteration: 58336/59290
Iteration: 58337/59290
Iteration: 58338/59290
Iteration: 58339/59290
Iteration: 58340/59290
Iteration: 58341/59290
Iteration: 58342/59290
Iteration: 58343/59290
Iteration: 58344/59290
Iteration: 58345/59290
Iteration: 58346/59290
Iteration: 58347/59290
Iteration: 58348/59290
Iteration: 58349/59290
Iteration: 58350/59290
Iteration: 58351/59290
Iteration: 58352/59290

 98%|█████████▊| 58332/59290 [44:15<00:27, 35.29it/s]

Iteration: 58353/59290
Iteration: 58354/59290
Iteration: 58355/59290
Iteration: 58356/59290
Iteration: 58357/59290
Iteration: 58358/59290
Iteration: 58359/59290
Iteration: 58360/59290
Iteration: 58361/59290
Iteration: 58362/59290
Iteration: 58363/59290
Iteration: 58364/59290
Iteration: 58365/59290
Iteration: 58366/59290
Iteration: 58367/59290
Iteration: 58368/59290
Iteration: 58369/59290
Iteration: 58370/59290
Iteration: 58371/59290
Iteration: 58372/59290
Iteration: 58373/59290
Iteration: 58374/59290
Iteration: 58375/59290
Iteration: 58376/59290

 98%|█████████▊| 58356/59290 [44:16<00:23, 40.46it/s]

Iteration: 58377/59290
Iteration: 58378/59290
Iteration: 58379/59290
Iteration: 58380/59290
Iteration: 58381/59290
Iteration: 58382/59290
Iteration: 58383/59290
Iteration: 58384/59290
Iteration: 58385/59290
Iteration: 58386/59290
Iteration: 58387/59290
Iteration: 58388/59290
Iteration: 58389/59290
Iteration: 58390/59290
Iteration: 58391/59290
Iteration: 58392/59290
Iteration: 58393/59290
Iteration: 58394/59290
Iteration: 58395/59290
Iteration: 58396/59290
Iteration: 58397/59290
Iteration: 58398/59290
Iteration: 58399/59290
Iteration: 58400/59290

 98%|█████████▊| 58380/59290 [44:16<00:20, 45.14it/s]

Iteration: 58401/59290
Iteration: 58402/59290
Iteration: 58403/59290
Iteration: 58404/59290
Iteration: 58405/59290
Iteration: 58406/59290
Iteration: 58407/59290
Iteration: 58408/59290
Iteration: 58409/59290
Iteration: 58410/59290
Iteration: 58411/59290
Iteration: 58412/59290
Iteration: 58413/59290
Iteration: 58414/59290
Iteration: 58415/59290
Iteration: 58416/59290
Iteration: 58417/59290
Iteration: 58418/59290
Iteration: 58419/59290
Iteration: 58420/59290
Iteration: 58421/59290
Iteration: 58422/59290
Iteration: 58423/59290
Iteration: 58424/59290

 99%|█████████▊| 58404/59290 [44:16<00:17, 49.54it/s]

Iteration: 58425/59290
Iteration: 58426/59290
Iteration: 58427/59290
Iteration: 58428/59290
Iteration: 58429/59290
Iteration: 58430/59290
Iteration: 58431/59290
Iteration: 58432/59290
Iteration: 58433/59290
Iteration: 58434/59290
Iteration: 58435/59290
Iteration: 58436/59290
Iteration: 58437/59290
Iteration: 58438/59290
Iteration: 58439/59290
Iteration: 58440/59290
Iteration: 58441/59290
Iteration: 58442/59290
Iteration: 58443/59290
Iteration: 58444/59290
Iteration: 58445/59290
Iteration: 58446/59290
Iteration: 58447/59290
Iteration: 58448/59290

 99%|█████████▊| 58428/59290 [44:17<00:16, 52.46it/s]

Iteration: 58449/59290
Iteration: 58450/59290
Iteration: 58451/59290
Iteration: 58452/59290
Iteration: 58453/59290
Iteration: 58454/59290
Iteration: 58455/59290
Iteration: 58456/59290
Iteration: 58457/59290
Iteration: 58458/59290
Iteration: 58459/59290
Iteration: 58460/59290
Iteration: 58461/59290
Iteration: 58462/59290
Iteration: 58463/59290
Iteration: 58464/59290
Iteration: 58465/59290
Iteration: 58466/59290
Iteration: 58467/59290
Iteration: 58468/59290
Iteration: 58469/59290
Iteration: 58470/59290
Iteration: 58471/59290
Iteration: 58472/59290

 99%|█████████▊| 58452/59290 [44:17<00:15, 53.53it/s]

Iteration: 58473/59290
Iteration: 58474/59290
Iteration: 58475/59290
Iteration: 58476/59290
Iteration: 58477/59290
Iteration: 58478/59290
Iteration: 58479/59290
Iteration: 58480/59290
Iteration: 58481/59290
Iteration: 58482/59290
Iteration: 58483/59290
Iteration: 58484/59290
Iteration: 58485/59290
Iteration: 58486/59290
Iteration: 58487/59290
Iteration: 58488/59290
Iteration: 58489/59290
Iteration: 58490/59290
Iteration: 58491/59290
Iteration: 58492/59290
Iteration: 58493/59290
Iteration: 58494/59290
Iteration: 58495/59290
Iteration: 58496/59290

 99%|█████████▊| 58476/59290 [44:19<00:26, 31.10it/s]

Iteration: 58497/59290
Iteration: 58498/59290
Iteration: 58499/59290
Iteration: 58500/59290
Iteration: 58501/59290
Iteration: 58502/59290
Iteration: 58503/59290
Iteration: 58504/59290
Iteration: 58505/59290
Iteration: 58506/59290
Iteration: 58507/59290
Iteration: 58508/59290
Iteration: 58509/59290
Iteration: 58510/59290
Iteration: 58511/59290
Iteration: 58512/59290
Iteration: 58513/59290
Iteration: 58514/59290
Iteration: 58515/59290
Iteration: 58516/59290
Iteration: 58517/59290
Iteration: 58518/59290
Iteration: 58519/59290
Iteration: 58520/59290

 99%|█████████▊| 58500/59290 [44:21<00:43, 17.98it/s]

Iteration: 58521/59290
Iteration: 58522/59290
Iteration: 58523/59290
Iteration: 58524/59290
Iteration: 58525/59290
Iteration: 58526/59290
Iteration: 58527/59290
Iteration: 58528/59290
Iteration: 58529/59290
Iteration: 58530/59290
Iteration: 58531/59290
Iteration: 58532/59290
Iteration: 58533/59290
Iteration: 58534/59290
Iteration: 58535/59290
Iteration: 58536/59290
Iteration: 58537/59290
Iteration: 58538/59290
Iteration: 58539/59290
Iteration: 58540/59290
Iteration: 58541/59290
Iteration: 58542/59290
Iteration: 58543/59290
Iteration: 58544/59290

 99%|█████████▊| 58524/59290 [44:22<00:39, 19.20it/s]

Iteration: 58545/59290
Iteration: 58546/59290
Iteration: 58547/59290
Iteration: 58548/59290
Iteration: 58549/59290
Iteration: 58550/59290
Iteration: 58551/59290
Iteration: 58552/59290
Iteration: 58553/59290
Iteration: 58554/59290
Iteration: 58555/59290
Iteration: 58556/59290
Iteration: 58557/59290
Iteration: 58558/59290
Iteration: 58559/59290
Iteration: 58560/59290
Iteration: 58561/59290
Iteration: 58562/59290
Iteration: 58563/59290
Iteration: 58564/59290
Iteration: 58565/59290
Iteration: 58566/59290
Iteration: 58567/59290
Iteration: 58568/59290

 99%|█████████▊| 58548/59290 [44:23<00:31, 23.90it/s]

Iteration: 58569/59290
Iteration: 58570/59290
Iteration: 58571/59290
Iteration: 58572/59290
Iteration: 58573/59290
Iteration: 58574/59290
Iteration: 58575/59290
Iteration: 58576/59290
Iteration: 58577/59290
Iteration: 58578/59290
Iteration: 58579/59290
Iteration: 58580/59290
Iteration: 58581/59290
Iteration: 58582/59290
Iteration: 58583/59290
Iteration: 58584/59290
Iteration: 58585/59290
Iteration: 58586/59290
Iteration: 58587/59290
Iteration: 58588/59290
Iteration: 58589/59290
Iteration: 58590/59290
Iteration: 58591/59290
Iteration: 58592/59290

 99%|█████████▉| 58572/59290 [44:23<00:24, 28.92it/s]

Iteration: 58593/59290
Iteration: 58594/59290
Iteration: 58595/59290
Iteration: 58596/59290
Iteration: 58597/59290
Iteration: 58598/59290
Iteration: 58599/59290
Iteration: 58600/59290
Iteration: 58601/59290
Iteration: 58602/59290
Iteration: 58603/59290
Iteration: 58604/59290
Iteration: 58605/59290
Iteration: 58606/59290
Iteration: 58607/59290
Iteration: 58608/59290
Iteration: 58609/59290
Iteration: 58610/59290
Iteration: 58611/59290
Iteration: 58612/59290
Iteration: 58613/59290
Iteration: 58614/59290
Iteration: 58615/59290
Iteration: 58616/59290

 99%|█████████▉| 58596/59290 [44:24<00:20, 34.57it/s]

Iteration: 58617/59290
Iteration: 58618/59290
Iteration: 58619/59290
Iteration: 58620/59290
Iteration: 58621/59290
Iteration: 58622/59290
Iteration: 58623/59290
Iteration: 58624/59290
Iteration: 58625/59290
Iteration: 58626/59290
Iteration: 58627/59290
Iteration: 58628/59290
Iteration: 58629/59290
Iteration: 58630/59290
Iteration: 58631/59290
Iteration: 58632/59290
Iteration: 58633/59290
Iteration: 58634/59290
Iteration: 58635/59290
Iteration: 58636/59290
Iteration: 58637/59290
Iteration: 58638/59290
Iteration: 58639/59290
Iteration: 58640/59290

 99%|█████████▉| 58620/59290 [44:24<00:16, 39.53it/s]

Iteration: 58641/59290
Iteration: 58642/59290
Iteration: 58643/59290
Iteration: 58644/59290
Iteration: 58645/59290
Iteration: 58646/59290
Iteration: 58647/59290
Iteration: 58648/59290
Iteration: 58649/59290
Iteration: 58650/59290
Iteration: 58651/59290
Iteration: 58652/59290
Iteration: 58653/59290
Iteration: 58654/59290
Iteration: 58655/59290
Iteration: 58656/59290
Iteration: 58657/59290
Iteration: 58658/59290
Iteration: 58659/59290
Iteration: 58660/59290
Iteration: 58661/59290
Iteration: 58662/59290
Iteration: 58663/59290
Iteration: 58664/59290

 99%|█████████▉| 58644/59290 [44:24<00:14, 44.26it/s]

Iteration: 58665/59290
Iteration: 58666/59290
Iteration: 58667/59290
Iteration: 58668/59290
Iteration: 58669/59290
Iteration: 58670/59290
Iteration: 58671/59290
Iteration: 58672/59290
Iteration: 58673/59290
Iteration: 58674/59290
Iteration: 58675/59290
Iteration: 58676/59290
Iteration: 58677/59290
Iteration: 58678/59290
Iteration: 58679/59290
Iteration: 58680/59290
Iteration: 58681/59290
Iteration: 58682/59290
Iteration: 58683/59290
Iteration: 58684/59290
Iteration: 58685/59290
Iteration: 58686/59290
Iteration: 58687/59290
Iteration: 58688/59290

 99%|█████████▉| 58668/59290 [44:25<00:12, 48.35it/s]

Iteration: 58689/59290
Iteration: 58690/59290
Iteration: 58691/59290
Iteration: 58692/59290
Iteration: 58693/59290
Iteration: 58694/59290
Iteration: 58695/59290
Iteration: 58696/59290
Iteration: 58697/59290
Iteration: 58698/59290
Iteration: 58699/59290
Iteration: 58700/59290
Iteration: 58701/59290
Iteration: 58702/59290
Iteration: 58703/59290
Iteration: 58704/59290
Iteration: 58705/59290
Iteration: 58706/59290
Iteration: 58707/59290
Iteration: 58708/59290
Iteration: 58709/59290
Iteration: 58710/59290
Iteration: 58711/59290
Iteration: 58712/59290

 99%|█████████▉| 58692/59290 [44:25<00:11, 51.76it/s]

Iteration: 58713/59290
Iteration: 58714/59290
Iteration: 58715/59290
Iteration: 58716/59290
Iteration: 58717/59290
Iteration: 58718/59290
Iteration: 58719/59290
Iteration: 58720/59290
Iteration: 58721/59290
Iteration: 58722/59290
Iteration: 58723/59290
Iteration: 58724/59290
Iteration: 58725/59290
Iteration: 58726/59290
Iteration: 58727/59290
Iteration: 58728/59290
Iteration: 58729/59290
Iteration: 58730/59290
Iteration: 58731/59290
Iteration: 58732/59290
Iteration: 58733/59290
Iteration: 58734/59290
Iteration: 58735/59290
Iteration: 58736/59290

 99%|█████████▉| 58716/59290 [44:26<00:10, 53.50it/s]

Iteration: 58737/59290
Iteration: 58738/59290
Iteration: 58739/59290
Iteration: 58740/59290
Iteration: 58741/59290
Iteration: 58742/59290
Iteration: 58743/59290
Iteration: 58744/59290
Iteration: 58745/59290
Iteration: 58746/59290
Iteration: 58747/59290
Iteration: 58748/59290
Iteration: 58749/59290
Iteration: 58750/59290
Iteration: 58751/59290
Iteration: 58752/59290
Iteration: 58753/59290
Iteration: 58754/59290
Iteration: 58755/59290
Iteration: 58756/59290
Iteration: 58757/59290
Iteration: 58758/59290
Iteration: 58759/59290
Iteration: 58760/59290

 99%|█████████▉| 58740/59290 [44:26<00:09, 55.90it/s]

Iteration: 58761/59290
Iteration: 58762/59290
Iteration: 58763/59290
Iteration: 58764/59290
Iteration: 58765/59290
Iteration: 58766/59290
Iteration: 58767/59290
Iteration: 58768/59290
Iteration: 58769/59290
Iteration: 58770/59290
Iteration: 58771/59290
Iteration: 58772/59290
Iteration: 58773/59290
Iteration: 58774/59290
Iteration: 58775/59290
Iteration: 58776/59290
Iteration: 58777/59290
Iteration: 58778/59290
Iteration: 58779/59290
Iteration: 58780/59290
Iteration: 58781/59290
Iteration: 58782/59290
Iteration: 58783/59290
Iteration: 58784/59290

 99%|█████████▉| 58764/59290 [44:26<00:09, 57.05it/s]

Iteration: 58785/59290
Iteration: 58786/59290
Iteration: 58787/59290
Iteration: 58788/59290
Iteration: 58789/59290
Iteration: 58790/59290
Iteration: 58791/59290
Iteration: 58792/59290
Iteration: 58793/59290
Iteration: 58794/59290
Iteration: 58795/59290
Iteration: 58796/59290
Iteration: 58797/59290
Iteration: 58798/59290
Iteration: 58799/59290
Iteration: 58800/59290
Iteration: 58801/59290
Iteration: 58802/59290
Iteration: 58803/59290
Iteration: 58804/59290
Iteration: 58805/59290
Iteration: 58806/59290
Iteration: 58807/59290
Iteration: 58808/59290

 99%|█████████▉| 58788/59290 [44:27<00:08, 58.85it/s]

Iteration: 58809/59290
Iteration: 58810/59290
Iteration: 58811/59290
Iteration: 58812/59290
Iteration: 58813/59290
Iteration: 58814/59290
Iteration: 58815/59290
Iteration: 58816/59290
Iteration: 58817/59290
Iteration: 58818/59290
Iteration: 58819/59290
Iteration: 58820/59290
Iteration: 58821/59290
Iteration: 58822/59290
Iteration: 58823/59290
Iteration: 58824/59290
Iteration: 58825/59290
Iteration: 58826/59290
Iteration: 58827/59290
Iteration: 58828/59290
Iteration: 58829/59290
Iteration: 58830/59290
Iteration: 58831/59290
Iteration: 58832/59290

 99%|█████████▉| 58812/59290 [44:27<00:07, 60.24it/s]

Iteration: 58833/59290
Iteration: 58834/59290
Iteration: 58835/59290
Iteration: 58836/59290
Iteration: 58837/59290
Iteration: 58838/59290
Iteration: 58839/59290
Iteration: 58840/59290
Iteration: 58841/59290
Iteration: 58842/59290
Iteration: 58843/59290
Iteration: 58844/59290
Iteration: 58845/59290
Iteration: 58846/59290
Iteration: 58847/59290
Iteration: 58848/59290
Iteration: 58849/59290
Iteration: 58850/59290
Iteration: 58851/59290
Iteration: 58852/59290
Iteration: 58853/59290
Iteration: 58854/59290
Iteration: 58855/59290
Iteration: 58856/59290

 99%|█████████▉| 58836/59290 [45:00<03:09,  2.39it/s]

Iteration: 58857/59290
Iteration: 58858/59290
Iteration: 58859/59290
Iteration: 58860/59290
Iteration: 58861/59290
Iteration: 58862/59290
Iteration: 58863/59290
Iteration: 58864/59290
Iteration: 58865/59290
Iteration: 58866/59290
Iteration: 58867/59290
Iteration: 58868/59290
Iteration: 58869/59290
Iteration: 58870/59290
Iteration: 58871/59290
Iteration: 58872/59290
Iteration: 58873/59290
Iteration: 58874/59290
Iteration: 58875/59290
Iteration: 58876/59290
Iteration: 58877/59290
Iteration: 58878/59290
Iteration: 58879/59290
Iteration: 58880/59290

 99%|█████████▉| 58860/59290 [45:00<02:07,  3.36it/s]

Iteration: 58881/59290
Iteration: 58882/59290
Iteration: 58883/59290
Iteration: 58884/59290
Iteration: 58885/59290
Iteration: 58886/59290
Iteration: 58887/59290
Iteration: 58888/59290
Iteration: 58889/59290
Iteration: 58890/59290
Iteration: 58891/59290
Iteration: 58892/59290
Iteration: 58893/59290
Iteration: 58894/59290
Iteration: 58895/59290
Iteration: 58896/59290
Iteration: 58897/59290
Iteration: 58898/59290
Iteration: 58899/59290
Iteration: 58900/59290
Iteration: 58901/59290
Iteration: 58902/59290
Iteration: 58903/59290
Iteration: 58904/59290

 99%|█████████▉| 58884/59290 [45:00<01:26,  4.70it/s]

Iteration: 58905/59290
Iteration: 58906/59290
Iteration: 58907/59290
Iteration: 58908/59290
Iteration: 58909/59290
Iteration: 58910/59290
Iteration: 58911/59290
Iteration: 58912/59290
Iteration: 58913/59290
Iteration: 58914/59290
Iteration: 58915/59290
Iteration: 58916/59290
Iteration: 58917/59290
Iteration: 58918/59290
Iteration: 58919/59290
Iteration: 58920/59290
Iteration: 58921/59290
Iteration: 58922/59290
Iteration: 58923/59290
Iteration: 58924/59290
Iteration: 58925/59290
Iteration: 58926/59290
Iteration: 58927/59290
Iteration: 58928/59290

 99%|█████████▉| 58908/59290 [45:01<00:59,  6.47it/s]

Iteration: 58929/59290
Iteration: 58930/59290
Iteration: 58931/59290
Iteration: 58932/59290
Iteration: 58933/59290
Iteration: 58934/59290
Iteration: 58935/59290
Iteration: 58936/59290
Iteration: 58937/59290
Iteration: 58938/59290
Iteration: 58939/59290
Iteration: 58940/59290
Iteration: 58941/59290
Iteration: 58942/59290
Iteration: 58943/59290
Iteration: 58944/59290
Iteration: 58945/59290
Iteration: 58946/59290
Iteration: 58947/59290
Iteration: 58948/59290
Iteration: 58949/59290
Iteration: 58950/59290
Iteration: 58951/59290
Iteration: 58952/59290

 99%|█████████▉| 58932/59290 [45:02<00:45,  7.83it/s]

Iteration: 58953/59290
Iteration: 58954/59290
Iteration: 58955/59290
Iteration: 58956/59290
Iteration: 58957/59290
Iteration: 58958/59290
Iteration: 58959/59290
Iteration: 58960/59290
Iteration: 58961/59290
Iteration: 58962/59290
Iteration: 58963/59290
Iteration: 58964/59290
Iteration: 58965/59290
Iteration: 58966/59290
Iteration: 58967/59290
Iteration: 58968/59290
Iteration: 58969/59290
Iteration: 58970/59290
Iteration: 58971/59290
Iteration: 58972/59290
Iteration: 58973/59290
Iteration: 58974/59290
Iteration: 58975/59290
Iteration: 58976/59290

 99%|█████████▉| 58956/59290 [45:05<00:41,  8.05it/s]

Iteration: 58977/59290
Iteration: 58978/59290
Iteration: 58979/59290
Iteration: 58980/59290
Iteration: 58981/59290
Iteration: 58982/59290
Iteration: 58983/59290
Iteration: 58984/59290
Iteration: 58985/59290
Iteration: 58986/59290
Iteration: 58987/59290
Iteration: 58988/59290
Iteration: 58989/59290
Iteration: 58990/59290
Iteration: 58991/59290
Iteration: 58992/59290
Iteration: 58993/59290
Iteration: 58994/59290
Iteration: 58995/59290
Iteration: 58996/59290
Iteration: 58997/59290
Iteration: 58998/59290
Iteration: 58999/59290
Iteration: 59000/59290

 99%|█████████▉| 58980/59290 [45:06<00:29, 10.45it/s]

Iteration: 59001/59290
Iteration: 59002/59290
Iteration: 59003/59290
Iteration: 59004/59290
Iteration: 59005/59290
Iteration: 59006/59290
Iteration: 59007/59290
Iteration: 59008/59290
Iteration: 59009/59290
Iteration: 59010/59290
Iteration: 59011/59290
Iteration: 59012/59290
Iteration: 59013/59290
Iteration: 59014/59290
Iteration: 59015/59290
Iteration: 59016/59290
Iteration: 59017/59290
Iteration: 59018/59290
Iteration: 59019/59290
Iteration: 59020/59290
Iteration: 59021/59290
Iteration: 59022/59290
Iteration: 59023/59290
Iteration: 59024/59290

100%|█████████▉| 59004/59290 [45:06<00:20, 13.90it/s]

Iteration: 59025/59290
Iteration: 59026/59290
Iteration: 59027/59290
Iteration: 59028/59290
Iteration: 59029/59290
Iteration: 59030/59290
Iteration: 59031/59290
Iteration: 59032/59290
Iteration: 59033/59290
Iteration: 59034/59290
Iteration: 59035/59290
Iteration: 59036/59290
Iteration: 59037/59290
Iteration: 59038/59290
Iteration: 59039/59290
Iteration: 59040/59290
Iteration: 59041/59290
Iteration: 59042/59290
Iteration: 59043/59290
Iteration: 59044/59290
Iteration: 59045/59290
Iteration: 59046/59290
Iteration: 59047/59290
Iteration: 59048/59290

100%|█████████▉| 59028/59290 [45:07<00:14, 18.08it/s]

Iteration: 59049/59290
Iteration: 59050/59290
Iteration: 59051/59290
Iteration: 59052/59290
Iteration: 59053/59290
Iteration: 59054/59290
Iteration: 59055/59290
Iteration: 59056/59290
Iteration: 59057/59290
Iteration: 59058/59290
Iteration: 59059/59290
Iteration: 59060/59290
Iteration: 59061/59290
Iteration: 59062/59290
Iteration: 59063/59290
Iteration: 59064/59290
Iteration: 59065/59290
Iteration: 59066/59290
Iteration: 59067/59290
Iteration: 59068/59290
Iteration: 59069/59290
Iteration: 59070/59290
Iteration: 59071/59290
Iteration: 59072/59290

100%|█████████▉| 59052/59290 [45:08<00:14, 16.25it/s]

Iteration: 59073/59290
Iteration: 59074/59290
Iteration: 59075/59290
Iteration: 59076/59290
Iteration: 59077/59290
Iteration: 59078/59290
Iteration: 59079/59290
Iteration: 59080/59290
Iteration: 59081/59290
Iteration: 59082/59290
Iteration: 59083/59290
Iteration: 59084/59290
Iteration: 59085/59290
Iteration: 59086/59290
Iteration: 59087/59290
Iteration: 59088/59290
Iteration: 59089/59290
Iteration: 59090/59290
Iteration: 59091/59290
Iteration: 59092/59290
Iteration: 59093/59290
Iteration: 59094/59290
Iteration: 59095/59290
Iteration: 59096/59290

100%|█████████▉| 59076/59290 [45:11<00:16, 12.83it/s]

Iteration: 59097/59290
Iteration: 59098/59290
Iteration: 59099/59290
Iteration: 59100/59290
Iteration: 59101/59290
Iteration: 59102/59290
Iteration: 59103/59290
Iteration: 59104/59290
Iteration: 59105/59290
Iteration: 59106/59290
Iteration: 59107/59290
Iteration: 59108/59290
Iteration: 59109/59290
Iteration: 59110/59290
Iteration: 59111/59290
Iteration: 59112/59290
Iteration: 59113/59290
Iteration: 59114/59290
Iteration: 59115/59290
Iteration: 59116/59290
Iteration: 59117/59290
Iteration: 59118/59290
Iteration: 59119/59290
Iteration: 59120/59290

100%|█████████▉| 59100/59290 [45:12<00:12, 15.45it/s]

Iteration: 59121/59290
Iteration: 59122/59290
Iteration: 59123/59290
Iteration: 59124/59290
Iteration: 59125/59290
Iteration: 59126/59290
Iteration: 59127/59290
Iteration: 59128/59290
Iteration: 59129/59290
Iteration: 59130/59290
Iteration: 59131/59290
Iteration: 59132/59290
Iteration: 59133/59290
Iteration: 59134/59290
Iteration: 59135/59290
Iteration: 59136/59290
Iteration: 59137/59290
Iteration: 59138/59290
Iteration: 59139/59290
Iteration: 59140/59290
Iteration: 59141/59290
Iteration: 59142/59290
Iteration: 59143/59290
Iteration: 59144/59290

100%|█████████▉| 59124/59290 [45:12<00:08, 19.93it/s]

Iteration: 59145/59290
Iteration: 59146/59290
Iteration: 59147/59290
Iteration: 59148/59290
Iteration: 59149/59290
Iteration: 59150/59290
Iteration: 59151/59290
Iteration: 59152/59290
Iteration: 59153/59290
Iteration: 59154/59290
Iteration: 59155/59290
Iteration: 59156/59290
Iteration: 59157/59290
Iteration: 59158/59290
Iteration: 59159/59290
Iteration: 59160/59290
Iteration: 59161/59290
Iteration: 59162/59290
Iteration: 59163/59290
Iteration: 59164/59290
Iteration: 59165/59290
Iteration: 59166/59290
Iteration: 59167/59290
Iteration: 59168/59290

100%|█████████▉| 59148/59290 [45:13<00:05, 24.95it/s]

Iteration: 59169/59290
Iteration: 59170/59290
Iteration: 59171/59290
Iteration: 59172/59290
Iteration: 59173/59290
Iteration: 59174/59290
Iteration: 59175/59290
Iteration: 59176/59290
Iteration: 59177/59290
Iteration: 59178/59290
Iteration: 59179/59290
Iteration: 59180/59290
Iteration: 59181/59290
Iteration: 59182/59290
Iteration: 59183/59290
Iteration: 59184/59290
Iteration: 59185/59290
Iteration: 59186/59290
Iteration: 59187/59290
Iteration: 59188/59290
Iteration: 59189/59290
Iteration: 59190/59290
Iteration: 59191/59290
Iteration: 59192/59290

100%|█████████▉| 59172/59290 [45:13<00:03, 30.45it/s]

Iteration: 59193/59290
Iteration: 59194/59290
Iteration: 59195/59290
Iteration: 59196/59290
Iteration: 59197/59290
Iteration: 59198/59290
Iteration: 59199/59290
Iteration: 59200/59290
Iteration: 59201/59290
Iteration: 59202/59290
Iteration: 59203/59290
Iteration: 59204/59290
Iteration: 59205/59290
Iteration: 59206/59290
Iteration: 59207/59290
Iteration: 59208/59290
Iteration: 59209/59290
Iteration: 59210/59290
Iteration: 59211/59290
Iteration: 59212/59290
Iteration: 59213/59290
Iteration: 59214/59290
Iteration: 59215/59290
Iteration: 59216/59290

100%|█████████▉| 59196/59290 [45:14<00:02, 35.96it/s]

Iteration: 59217/59290
Iteration: 59218/59290
Iteration: 59219/59290
Iteration: 59220/59290
Iteration: 59221/59290
Iteration: 59222/59290
Iteration: 59223/59290
Iteration: 59224/59290
Iteration: 59225/59290
Iteration: 59226/59290
Iteration: 59227/59290
Iteration: 59228/59290
Iteration: 59229/59290
Iteration: 59230/59290
Iteration: 59231/59290
Iteration: 59232/59290
Iteration: 59233/59290
Iteration: 59234/59290
Iteration: 59235/59290
Iteration: 59236/59290
Iteration: 59237/59290
Iteration: 59238/59290
Iteration: 59239/59290
Iteration: 59240/59290

100%|█████████▉| 59220/59290 [45:14<00:01, 41.12it/s]

Iteration: 59241/59290
Iteration: 59242/59290
Iteration: 59243/59290
Iteration: 59244/59290
Iteration: 59245/59290
Iteration: 59246/59290
Iteration: 59247/59290
Iteration: 59248/59290
Iteration: 59249/59290
Iteration: 59250/59290
Iteration: 59251/59290
Iteration: 59252/59290
Iteration: 59253/59290
Iteration: 59254/59290
Iteration: 59255/59290
Iteration: 59256/59290
Iteration: 59257/59290
Iteration: 59258/59290
Iteration: 59259/59290
Iteration: 59260/59290
Iteration: 59261/59290
Iteration: 59262/59290
Iteration: 59263/59290
Iteration: 59264/59290

100%|█████████▉| 59244/59290 [45:14<00:01, 45.52it/s]

Iteration: 59265/59290
Iteration: 59266/59290
Iteration: 59267/59290
Iteration: 59268/59290
Iteration: 59269/59290
Iteration: 59270/59290
Iteration: 59271/59290
Iteration: 59272/59290
Iteration: 59273/59290
Iteration: 59274/59290
Iteration: 59275/59290
Iteration: 59276/59290
Iteration: 59277/59290
Iteration: 59278/59290
Iteration: 59279/59290
Iteration: 59280/59290
Iteration: 59281/59290
Iteration: 59282/59290
Iteration: 59283/59290
Iteration: 59284/59290
Iteration: 59285/59290
Iteration: 59286/59290
Iteration: 59287/59290
Iteration: 59288/59290

100%|██████████| 59290/59290 [45:15<00:00, 21.84it/s]

Iteration: 59289/59290
Iteration: 59290/59290
Iteration: 59291/59290
Iteration: 59292/59290
Iteration: 59293/59290
Iteration: 59294/59290
Iteration: 59295/59290
Iteration: 59296/59290
Iteration: 59297/59290
Iteration: 59298/59290
Iteration: 59299/59290
Iteration: 59300/59290
Iteration: 59301/59290
Iteration: 59302/59290
Iteration: 59303/59290
Iteration: 59304/59290
Iteration: 59305/59290
Iteration: 59306/59290
Iteration: 59307/59290
Iteration: 59308/59290
Iteration: 59309/59290
Iteration: 59310/59290

In [15]:
df['humidity'] = humidity_values
df['pressure'] = pressure_values
df['temperature'] = temperature_values
df['wind_speed'] = wind_values
df = df.drop(columns=["date", "hour"])

/tmp/ipykernel_35822/886961149.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['humidity'] = humidity_values
/tmp/ipykernel_35822/886961149.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pressure'] = pressure_values
/tmp/ipykernel_35822/886961149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['temperature'] = temperature_values
/tmp/ipykernel_35822/886961149.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wind_speed'] = wind_values

In [16]:
df = df.drop(columns=["lat", "lon"])

In [17]:
df

,timestamp,sensorId,humidity,pressure,temperature,wind_speed
0,2025-11-09 16:00:00,16836a55-7140-43e2-9a63-56fac5cba714,88,944.7,12.5,7.1
1,2025-11-09 17:00:00,16836a55-7140-43e2-9a63-56fac5cba714,90,944.7,12.1,7.1
2,2025-11-09 18:00:00,16836a55-7140-43e2-9a63-56fac5cba714,91,944.5,12.0,6.2
3,2025-11-09 19:00:00,16836a55-7140-43e2-9a63-56fac5cba714,91,944.9,12.0,5.8
4,2025-11-09 20:00:00,16836a55-7140-43e2-9a63-56fac5cba714,93,944.8,11.8,5.8
...,...,...,...,...,...,...
59306,2026-03-01 18:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,51,950.9,7.6,7.4
59307,2026-03-01 19:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,56,950.7,6.5,6.2
59308,2026-03-01 20:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,56,951.1,5.8,6.8
59309,2026-03-01 21:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,58,951.2,5.2,6.9
59310,2026-03-01 22:00:00,fec52a19-9148-4350-a1b4-ae0da05ee199,58,950.8,4.7,7.0

In [18]:
df.isnull().sum()

timestamp      0
sensorId       0
humidity       0
pressure       0
temperature    0
wind_speed     0
dtype: int64

In [19]:
df.to_csv('../data/raw/bitola_forecast_weather.csv',index=False)