## Data Preprocessing of Skopje Dataset

In [3]:
import pandas as pd
import numpy as np
import os

In [4]:
base_dir = os.getcwd()

csv_path = os.path.join(base_dir, "..", "data", "training", "skopje_features.csv")
df = pd.read_csv(csv_path,low_memory=False)

In [5]:
df.head(30)

,sensorId,timestamp,city,co,humidity,no2,o3,pm10,pm25,pressure,temperature,wind_speed
0,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T11:01:27+01:00,bitola,NaN,49.0,NaN,NaN,7.0,3.0,944.0,15.0,NaN
1,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T11:16:58+01:00,bitola,NaN,46.0,NaN,NaN,3.0,3.0,944.0,15.0,NaN
2,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T11:32:30+01:00,bitola,NaN,45.0,NaN,NaN,2.0,2.0,944.0,16.0,NaN
3,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T11:48:01+01:00,bitola,NaN,43.0,NaN,NaN,3.0,1.0,944.0,16.0,NaN
4,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T12:03:33+01:00,bitola,NaN,42.0,NaN,NaN,1.0,0.0,944.0,16.0,NaN
5,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T12:19:05+01:00,bitola,NaN,41.0,NaN,NaN,1.0,0.0,944.0,16.0,NaN
6,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T12:34:37+01:00,bitola,NaN,41.0,NaN,NaN,1.0,0.0,944.0,16.0,NaN
7,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T12:50:08+01:00,bitola,NaN,43.0,NaN,NaN,4.0,2.0,944.0,16.0,NaN
8,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T13:05:40+01:00,bitola,NaN,45.0,NaN,NaN,2.0,1.0,944.0,15.0,NaN
9,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T13:25:38+01:00,bitola,NaN,46.0,NaN,NaN,NaN,NaN,944.0,13.0,NaN
10,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T13:41:09+01:00,bitola,NaN,48.0,NaN,NaN,7.0,1.0,944.0,13.0,NaN
11,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T13:56:41+01:00,bitola,NaN,49.0,NaN,NaN,1.0,1.0,944.0,12.0,NaN
12,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T14:12:13+01:00,bitola,NaN,50.0,NaN,NaN,4.0,2.0,944.0,12.0,NaN
13,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T14:27:44+01:00,bitola,NaN,51.0,NaN,NaN,3.0,1.0,944.0,12.0,NaN
14,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T14:43:16+01:00,bitola,NaN,52.0,NaN,NaN,4.0,1.0,944.0,11.0,NaN
15,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T14:58:48+01:00,bitola,NaN,53.0,NaN,NaN,1.0,1.0,944.0,11.0,NaN
16,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T15:14:20+01:00,bitola,NaN,58.0,NaN,NaN,4.0,2.0,944.0,11.0,NaN
17,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T15:29:51+01:00,bitola,NaN,60.0,NaN,NaN,1.0,1.0,944.0,10.0,NaN
18,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T15:45:23+01:00,bitola,NaN,62.0,NaN,NaN,3.0,2.0,944.0,9.0,NaN
19,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T16:00:55+01:00,bitola,NaN,63.0,NaN,NaN,1.0,1.0,944.0,9.0,NaN
20,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T16:16:27+01:00,bitola,NaN,64.0,NaN,NaN,4.0,3.0,944.0,8.0,NaN
21,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T16:31:58+01:00,bitola,NaN,66.0,NaN,NaN,2.0,2.0,944.0,8.0,NaN
22,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T16:47:30+01:00,bitola,NaN,67.0,NaN,NaN,9.0,3.0,944.0,8.0,NaN
23,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T17:03:02+01:00,bitola,NaN,67.0,NaN,NaN,3.0,2.0,944.0,8.0,NaN
24,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T17:18:34+01:00,bitola,NaN,67.0,NaN,NaN,2.0,2.0,944.0,7.0,NaN
25,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T17:34:05+01:00,bitola,NaN,68.0,NaN,NaN,0.0,0.0,944.0,7.0,NaN
26,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T17:49:37+01:00,bitola,NaN,69.0,NaN,NaN,1.0,1.0,944.0,7.0,NaN
27,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T18:05:09+01:00,bitola,NaN,71.0,NaN,NaN,1.0,1.0,944.0,7.0,NaN
28,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T18:20:41+01:00,bitola,NaN,70.0,NaN,NaN,1.0,1.0,944.0,6.0,NaN
29,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12T18:36:12+01:00,bitola,NaN,69.0,NaN,NaN,0.0,0.0,944.0,6.0,NaN

In [6]:
len(df)

6032606

In [7]:
df.tail(10)

,sensorId,timestamp,city,co,humidity,no2,o3,pm10,pm25,pressure,temperature,wind_speed
6032596,sensor_dev_8550_72,2025-11-30 14:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.818376
6032597,sensor_dev_8550_72,2025-11-30 15:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.167487
6032598,sensor_dev_8550_72,2025-11-30 16:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.900000
6032599,sensor_dev_8550_72,2025-11-30 17:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.763675
6032600,sensor_dev_8550_72,2025-11-30 18:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.402492
6032601,sensor_dev_8550_72,2025-11-30 19:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.804984
6032602,sensor_dev_8550_72,2025-11-30 20:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.052316
6032603,sensor_dev_8550_72,2025-11-30 21:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.049571
6032604,sensor_dev_8550_72,2025-11-30 22:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.763675
6032605,sensor_dev_8550_72,2025-11-30 23:00:00+00:00,bitola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.742159

In [8]:
df.describe()

,co,humidity,no2,o3,pm10,pm25,pressure,temperature,wind_speed
count,26733.000000,3.093419e+06,44739.000000,40890.000000,4.482685e+06,4.473701e+06,2.486358e+06,3.186934e+06,1.298256e+06
mean,1.128717,5.486827e+01,23.999620,29.206554,2.452176e+01,1.372310e+01,9.824769e+02,1.706728e+01,4.937822e+00
std,2.372218,1.865493e+01,20.777529,27.638312,4.332482e+01,2.298722e+01,1.299249e+01,9.462147e+00,3.241113e+00
min,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,7.400000e+02,-9.300000e+01,0.000000e+00
25%,0.000000,4.100000e+01,7.000000,7.000000,6.000000e+00,3.000000e+00,9.790000e+02,1.000000e+01,2.741678e+00
50%,0.000000,5.400000e+01,21.000000,19.000000,1.200000e+01,7.000000e+00,9.850000e+02,1.600000e+01,4.456591e+00
75%,1.000000,6.800000e+01,35.000000,44.000000,2.700000e+01,1.500000e+01,9.900000e+02,2.400000e+01,6.439876e+00
max,17.000000,9.900000e+01,172.000000,185.000000,1.994000e+03,9.980000e+02,1.604000e+03,6.200000e+01,4.566469e+01

In [9]:
percent_missing = (df.isnull().sum() * 100) / len(df)
print(percent_missing)

sensorId        0.000000
timestamp       0.000000
city            0.000000
co             99.556858
humidity       48.721680
no2            99.258380
o3             99.322183
pm10           25.692396
pm25           25.841320
pressure       58.784678
temperature    47.171521
wind_speed     78.479350
dtype: float64

### Drop the insignificant columns that has missing value percentage above 90%

In [10]:
df= df.drop(columns=['no2','o3','co','city'],axis=1)

In [11]:
df.columns

Index(['sensorId', 'timestamp', 'humidity', 'pm10', 'pm25', 'pressure',
       'temperature', 'wind_speed'],
      dtype='object')

In [12]:
df['sensorId'].value_counts()

sensorId
sensor_dev_20701_157                    86042
sensor_dev_61184_835                    85473
sensor_dev_78164_619                    85003
sensor_dev_62788_603                    84969
sensor_dev_80195_553                    84924
                                        ...
10968604-7c7a-4c7b-82a1-937793ac214f       20
d42147ab-9f8c-4816-964b-62e6a82d6492       13
3c286a07-a04d-43d1-907f-e578355f242a        9
28dc8a2f-834a-4aa9-aef0-37a7935aeaa7        9
e1b76485-5f40-4e91-af09-86ce9099919b        3
Name: count, Length: 141, dtype: int64

In [13]:
print(df['timestamp'].min())
print(df['timestamp'].max())

2023-12-01 00:00:00+00:00
2025-12-01T00:59:50+01:00

In [14]:
df['sensorId'].nunique()

141

### Convert the original timestamp into hourly timestamp

In [15]:
df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True,format="ISO8601")


df["timestamp"] = df["timestamp"].dt.floor("h")

In [16]:
df.head(30)

,sensorId,timestamp,humidity,pm10,pm25,pressure,temperature,wind_speed
0,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 10:00:00+00:00,49.0,7.0,3.0,944.0,15.0,NaN
1,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 10:00:00+00:00,46.0,3.0,3.0,944.0,15.0,NaN
2,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 10:00:00+00:00,45.0,2.0,2.0,944.0,16.0,NaN
3,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 10:00:00+00:00,43.0,3.0,1.0,944.0,16.0,NaN
4,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 11:00:00+00:00,42.0,1.0,0.0,944.0,16.0,NaN
5,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 11:00:00+00:00,41.0,1.0,0.0,944.0,16.0,NaN
6,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 11:00:00+00:00,41.0,1.0,0.0,944.0,16.0,NaN
7,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 11:00:00+00:00,43.0,4.0,2.0,944.0,16.0,NaN
8,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 12:00:00+00:00,45.0,2.0,1.0,944.0,15.0,NaN
9,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 12:00:00+00:00,46.0,NaN,NaN,944.0,13.0,NaN
10,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 12:00:00+00:00,48.0,7.0,1.0,944.0,13.0,NaN
11,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 12:00:00+00:00,49.0,1.0,1.0,944.0,12.0,NaN
12,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 13:00:00+00:00,50.0,4.0,2.0,944.0,12.0,NaN
13,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 13:00:00+00:00,51.0,3.0,1.0,944.0,12.0,NaN
14,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 13:00:00+00:00,52.0,4.0,1.0,944.0,11.0,NaN
15,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 13:00:00+00:00,53.0,1.0,1.0,944.0,11.0,NaN
16,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 14:00:00+00:00,58.0,4.0,2.0,944.0,11.0,NaN
17,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 14:00:00+00:00,60.0,1.0,1.0,944.0,10.0,NaN
18,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 14:00:00+00:00,62.0,3.0,2.0,944.0,9.0,NaN
19,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 15:00:00+00:00,63.0,1.0,1.0,944.0,9.0,NaN
20,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 15:00:00+00:00,64.0,4.0,3.0,944.0,8.0,NaN
21,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 15:00:00+00:00,66.0,2.0,2.0,944.0,8.0,NaN
22,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 15:00:00+00:00,67.0,9.0,3.0,944.0,8.0,NaN
23,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 16:00:00+00:00,67.0,3.0,2.0,944.0,8.0,NaN
24,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 16:00:00+00:00,67.0,2.0,2.0,944.0,7.0,NaN
25,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 16:00:00+00:00,68.0,0.0,0.0,944.0,7.0,NaN
26,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 16:00:00+00:00,69.0,1.0,1.0,944.0,7.0,NaN
27,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 17:00:00+00:00,71.0,1.0,1.0,944.0,7.0,NaN
28,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 17:00:00+00:00,70.0,1.0,1.0,944.0,6.0,NaN
29,007f2b03-94e6-47b3-9e3e-44273354acd5,2023-12-12 17:00:00+00:00,69.0,0.0,0.0,944.0,6.0,NaN

### Hourly aggregation grouped by sensorId and timestamp

In [17]:
df_hourly = (
    df.groupby(["sensorId", "timestamp"])
      .agg({
          "humidity":"mean",
          "pm10":"mean",
          "pm25":"mean",
          "pressure":"mean",
          "temperature":"mean",
          "wind_speed":"mean"
      })
      .reset_index()
)

In [18]:
df_hourly = df_hourly.sort_values(by=["timestamp", "sensorId"]).reset_index(drop=True)

In [19]:
df_hourly.head(20)

,sensorId,timestamp,humidity,pm10,pm25,pressure,temperature,wind_speed
0,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,2023-12-01 00:00:00+00:00,81.000000,195.000000,102.500000,984.000000,5.50,6.409617
1,07b58ccf-7faa-4f0a-a10a-e7b485d52ffe,2023-12-01 00:00:00+00:00,95.500000,23.500000,16.250000,971.000000,4.00,6.409617
2,0a058579-12c9-47be-971b-607198002d3b,2023-12-01 00:00:00+00:00,65.000000,66.000000,39.000000,984.000000,7.00,6.409617
3,1000,2023-12-01 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,6.409617
4,1001,2023-12-01 00:00:00+00:00,NaN,NaN,98.000000,NaN,NaN,6.409617
5,1002,2023-12-01 00:00:00+00:00,NaN,NaN,58.000000,NaN,NaN,4.213692
6,1003,2023-12-01 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,11.246759
7,1004,2023-12-01 00:00:00+00:00,NaN,NaN,61.000000,NaN,NaN,6.409617
8,1286fb13-a4de-44cd-a390-4117fcddf1a9,2023-12-01 00:00:00+00:00,62.000000,51.000000,31.250000,983.000000,8.75,11.246759
9,1a2af884-336b-427d-9b37-fe332557539f,2023-12-01 00:00:00+00:00,83.000000,61.000000,32.500000,982.000000,6.00,11.246759
10,200cdb67-8dc5-4dcf-ac62-748db636e04e,2023-12-01 00:00:00+00:00,NaN,122.250000,98.500000,NaN,NaN,6.409617
11,24eaebc2-ca62-49ff-8b22-880bc131b69f,2023-12-01 00:00:00+00:00,69.000000,94.500000,50.500000,981.000000,9.00,6.409617
12,2c275060-799f-46c9-a2eb-fc613c4b4ff6,2023-12-01 00:00:00+00:00,74.250000,65.000000,41.000000,986.000000,6.00,6.409617
13,35bdd494-5395-4ac5-b7b9-05b82c9b6acd,2023-12-01 00:00:00+00:00,57.500000,99.500000,59.000000,985.250000,9.00,6.409617
14,3791738b-bec6-452e-9aae-5b11a899bfe2,2023-12-01 00:00:00+00:00,74.333333,34.000000,19.333333,983.333333,6.00,11.246759
15,3d5e32fb-3c41-427f-b6ef-ed19e84026dd,2023-12-01 00:00:00+00:00,68.500000,37.250000,26.250000,986.000000,6.00,6.409617
16,3d7bd712-24a9-482c-b387-a8168b12d3f4,2023-12-01 00:00:00+00:00,72.000000,111.333333,94.000000,NaN,9.00,6.409617
17,3e2465de-c2c2-4473-9c62-7113265debd9,2023-12-01 00:00:00+00:00,59.750000,50.000000,35.750000,969.000000,9.00,6.409617
18,3f9a8bfd-d15a-4b2a-8516-81260c25416e,2023-12-01 00:00:00+00:00,94.000000,25.500000,11.000000,945.000000,4.00,3.617955
19,52546b6e-77bf-40f8-b0e5-6e54d7947e9f,2023-12-01 00:00:00+00:00,87.250000,69.750000,49.250000,984.000000,4.00,6.409617

In [20]:
df_hourly['sensorId'].value_counts()

sensorId
01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4    17544
sensor_dev_77790_464                    17544
sensor_dev_61184_835                    17544
sensor_dev_60237_141                    17544
sensor_dev_39548_976                    17544
                                        ...
10968604-7c7a-4c7b-82a1-937793ac214f       12
d42147ab-9f8c-4816-964b-62e6a82d6492        6
3c286a07-a04d-43d1-907f-e578355f242a        4
28dc8a2f-834a-4aa9-aef0-37a7935aeaa7        4
e1b76485-5f40-4e91-af09-86ce9099919b        1
Name: count, Length: 141, dtype: int64

In [21]:
percent_missing = (df_hourly.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

sensorId        0.000000
timestamp       0.000000
humidity       49.868582
pm10           25.890928
pm25           26.399149
pressure       59.789864
temperature    48.542267
wind_speed     21.610804
dtype: float64

In [22]:
len(df_hourly)

1656167

In [23]:
sensor_stats = df_hourly.groupby('sensorId')[['humidity', 'pressure', 'pm10','pm25','temperature']].apply(lambda x: x.isnull().mean())

In [24]:
print(sensor_stats[sensor_stats['humidity'] > 0.9])

                                      humidity  pressure      pm10      pm25  \
sensorId
0f241923-b5b5-4c4a-bf08-279b9e3a8540       1.0       1.0  0.000000  0.000000
1000                                       1.0       1.0  0.266758  0.368217
1001                                       1.0       1.0  0.690834  0.684850
1002                                       1.0       1.0  0.684166  0.681259
1003                                       1.0       1.0  0.278272  0.369357
1004                                       1.0       1.0  0.683197  0.678238
1005                                       1.0       1.0  0.099317  1.000000
1f5c7035-6c1f-45ee-97f4-0a292b49710a       1.0       1.0  0.000000  0.000000
200cdb67-8dc5-4dcf-ac62-748db636e04e       1.0       1.0  0.004104  0.004104
3c286a07-a04d-43d1-907f-e578355f242a       1.0       1.0  0.000000  0.000000
5346db83-fbf0-48c4-8714-1d896ca2f5e8       1.0       1.0  0.000000  0.000000
541ffef0-4f3a-4b7f-9673-e6486d543455       1.0       1.0  0.000000  0.000367
59c15198-7ba8-45af-aac4-5b3d1560fd81       1.0       1.0  0.029469  0.029469
6380c7cc-df23-4512-ad10-f2b363000579       1.0       1.0  0.007410  0.007410
8a759ac2-fd2e-4513-b1e9-9e8de8694153       1.0       1.0  0.000000  0.000000
996a42d1-c6a3-4ec1-b879-bae2a55b7777       1.0       1.0  0.000000  0.000000
b4fea216-2ee8-4c1f-b536-bdb9bd46e577       1.0       1.0  0.000000  0.000000
d42147ab-9f8c-4816-964b-62e6a82d6492       1.0       1.0  0.000000  1.000000
e1b76485-5f40-4e91-af09-86ce9099919b       1.0       1.0  0.000000  0.000000
fefbf9e0-ff44-4b85-b968-2af046c4f4dc       1.0       1.0  0.000000  0.000000
sensor_dev_60237_141                       1.0       1.0  0.813098  0.813098
sensor_dev_61184_835                       1.0       1.0  0.013110  0.013110
sensor_dev_77790_464                       1.0       1.0  0.198586  0.198586
sensor_dev_77844_828                       1.0       1.0  0.000000  0.000000
sensor_dev_77849_684                       1.0       1.0  0.989854  0.989854
sensor_dev_78019_564                       1.0       1.0  0.685591  0.685591
sensor_dev_78110_618                       1.0       1.0  0.977314  0.977314
sensor_dev_78164_619                       1.0       1.0  0.016758  0.016758
sensor_dev_78188_661                       1.0       1.0  0.903158  0.903158
sensor_dev_78370_972                       1.0       1.0  0.000000  0.000000
sensor_dev_78432_137                       1.0       1.0  0.239284  0.239284
sensor_dev_78456_119                       1.0       1.0  0.993103  0.993103
sensor_dev_78464_424                       1.0       1.0  0.819311  0.819311
sensor_dev_78662_610                       1.0       1.0  0.595816  0.595816
sensor_dev_79190_458                       1.0       1.0  0.132695  0.132695
sensor_dev_79765_769                       1.0       1.0  0.638509  0.638509
sensor_dev_80193_378                       1.0       1.0  0.109097  0.109097
sensor_dev_80195_553                       1.0       1.0  0.018867  0.018867
sensor_dev_81720_819                       1.0       1.0  0.000000  0.000000
sensor_dev_81853_15                        1.0       1.0  0.000000  0.000000
sensor_dev_81855_345                       1.0       1.0  0.000000  0.000000
sensor_dev_81880_63                        1.0       1.0  0.000000  0.000000
sensor_dev_81888_631                       1.0       1.0  0.000000  0.000000
sensor_dev_81942_280                       1.0       1.0  0.000000  0.000000
sensor_dev_81984_843                       1.0       1.0  0.000000  0.000000
sensor_dev_82681_781                       1.0       1.0  0.000000  0.000000
sensor_dev_82683_723                       1.0       1.0  0.000000  0.000000
sensor_dev_82685_644                       1.0       1.0  0.000000  0.000000
sensor_dev_82703_642                       1.0       1.0  0.000000  0.000000
sensor_dev_82707_917                       1.0       1.0  0.000000  0.000000
sensor_dev_82724_611                       1.0       1.0  0.000000  0.000000
sensor_dev_83224_195                       1.0       1.0  0.000000  0.000000
sensor_dev_83413_356                       1.0       1.0  0.000000  0.000000
sensor_dev_84687_383                       1.0       1.0  0.000000  0.000000
sensor_dev_84891_599                       1.0       1.0  0.000000  0.000000
sensor_dev_8550_72                         1.0       1.0  0.824726  0.824726

                                      temperature
sensorId
0f241923-b5b5-4c4a-bf08-279b9e3a8540          1.0
1000                                          1.0
1001                                          1.0
1002                                          1.0
1003                                          1.0
1004                                          1.0
1005                                          1.0
1f5c7035-6c1f-45ee-97f4-0a292b49710a          1.0
200cdb67-8dc5-4dcf-ac62-748db636e04e          1.0
3c286a07-a04d-43d1-907f-e578355f242a          1.0
5346db83-fbf0-48c4-8714-1d896ca2f5e8          1.0
541ffef0-4f3a-4b7f-9673-e6486d543455          1.0
59c15198-7ba8-45af-aac4-5b3d1560fd81          1.0
6380c7cc-df23-4512-ad10-f2b363000579          1.0
8a759ac2-fd2e-4513-b1e9-9e8de8694153          1.0
996a42d1-c6a3-4ec1-b879-bae2a55b7777          1.0
b4fea216-2ee8-4c1f-b536-bdb9bd46e577          1.0
d42147ab-9f8c-4816-964b-62e6a82d6492          1.0
e1b76485-5f40-4e91-af09-86ce9099919b          1.0
fefbf9e0-ff44-4b85-b968-2af046c4f4dc          1.0
sensor_dev_60237_141                          1.0
sensor_dev_61184_835                          1.0
sensor_dev_77790_464                          1.0
sensor_dev_77844_828                          1.0
sensor_dev_77849_684                          1.0
sensor_dev_78019_564                          1.0
sensor_dev_78110_618                          1.0
sensor_dev_78164_619                          1.0
sensor_dev_78188_661                          1.0
sensor_dev_78370_972                          1.0
sensor_dev_78432_137                          1.0
sensor_dev_78456_119                          1.0
sensor_dev_78464_424                          1.0
sensor_dev_78662_610                          1.0
sensor_dev_79190_458                          1.0
sensor_dev_79765_769                          1.0
sensor_dev_80193_378                          1.0
sensor_dev_80195_553                          1.0
sensor_dev_81720_819                          1.0
sensor_dev_81853_15                           1.0
sensor_dev_81855_345                          1.0
sensor_dev_81880_63                           1.0
sensor_dev_81888_631                          1.0
sensor_dev_81942_280                          1.0
sensor_dev_81984_843                          1.0
sensor_dev_82681_781                          1.0
sensor_dev_82683_723                          1.0
sensor_dev_82685_644                          1.0
sensor_dev_82703_642                          1.0
sensor_dev_82707_917                          1.0
sensor_dev_82724_611                          1.0
sensor_dev_83224_195                          1.0
sensor_dev_83413_356                          1.0
sensor_dev_84687_383                          1.0
sensor_dev_84891_599                          1.0
sensor_dev_8550_72                            1.0

### Remove the sensors that have 100% missing values for pm10 and pm25

In [25]:
sensor_stats = df_hourly.groupby('sensorId')[['pm10', 'pm25']].count()
valid_sensors = sensor_stats[sensor_stats.sum(axis=1) > 0].index

df_hourly = df_hourly[df_hourly['sensorId'].isin(valid_sensors)]

In [26]:
len(df_hourly)

1654557

In [27]:
df_hourly['sensorId'].value_counts()

sensorId
01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4    17544
sensor_dev_77790_464                    17544
sensor_dev_61184_835                    17544
sensor_dev_60237_141                    17544
sensor_dev_39548_976                    17544
                                        ...
10968604-7c7a-4c7b-82a1-937793ac214f       12
d42147ab-9f8c-4816-964b-62e6a82d6492        6
3c286a07-a04d-43d1-907f-e578355f242a        4
28dc8a2f-834a-4aa9-aef0-37a7935aeaa7        4
e1b76485-5f40-4e91-af09-86ce9099919b        1
Name: count, Length: 140, dtype: int64

### Remove the sparse sensor

In [28]:
sensor_counts = df_hourly["sensorId"].value_counts()


valid_sensors = sensor_counts[sensor_counts >= 10000].index


df_hourly = df_hourly[df_hourly["sensorId"].isin(valid_sensors)]

In [29]:
percent_missing = (df_hourly.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

sensorId        0.000000
timestamp       0.000000
humidity       48.486739
pm10           29.008050
pm25           29.231003
pressure       58.932761
temperature    47.090655
wind_speed     11.374765
dtype: float64

In [30]:
df_hourly['sensorId'].value_counts()

sensorId
01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4    17544
sensor_dev_77790_464                    17544
sensor_dev_61184_835                    17544
sensor_dev_60237_141                    17544
sensor_dev_39548_976                    17544
                                        ...
sensor_dev_84941_208                    13150
0f10deea-03bc-4a47-ae87-85442140467c    12947
10661e7e-e9c5-4e67-a5fa-06cdf6f3e76d    12132
sensor_dev_82685_644                    11660
sensor_dev_82724_611                    10645
Name: count, Length: 86, dtype: int64

In [31]:
start = df_hourly['timestamp'].min()
end = df_hourly['timestamp'].max()
print(f"Start: {start}")
print(f"End: {end}")

Start: 2023-12-01 00:00:00+00:00
End: 2025-11-30 23:00:00+00:00

### Add the full timeframe for each sensor

In [32]:
processed_dfs = []
for sensor_id, group in df_hourly.groupby('sensorId'):
    group = group.sort_values('timestamp').set_index('timestamp')
    group = group.resample('h').asfreq().reindex(pd.date_range(start, end, freq='h'))
    group['sensorId'] = sensor_id
    processed_dfs.append(group.reset_index())

df_hourly_full = pd.concat(processed_dfs)

In [33]:
df_hourly_full = df_hourly_full.rename(columns={'index': 'timestamp'})

In [34]:
df_hourly_full.columns

Index(['timestamp', 'sensorId', 'humidity', 'pm10', 'pm25', 'pressure',
       'temperature', 'wind_speed'],
      dtype='object')

In [35]:
df_hourly_full['sensorId'].value_counts()

sensorId
007f2b03-94e6-47b3-9e3e-44273354acd5    17544
fef6bc74-bf86-4874-9531-51b033580379    17544
sensor_dev_77790_464                    17544
sensor_dev_62788_603                    17544
sensor_dev_61184_835                    17544
                                        ...
60aa65c6-b7c4-4aae-8769-5dbcba356b5d    17544
5e8e87e4-dd6d-4fe9-bd41-964b8f74607b    17544
5de2a490-05f1-4f33-927e-a7e6f5664b72    17544
59c15198-7ba8-45af-aac4-5b3d1560fd81    17544
sensor_dev_8550_72                      17544
Name: count, Length: 86, dtype: int64

In [36]:
percent_missing = (df_hourly_full.isnull().sum() * 100) / len(df_hourly)
print(percent_missing)

timestamp       0.000000
sensorId        0.000000
humidity       51.483634
pm10           32.004945
pm25           32.227898
pressure       61.929656
temperature    50.087550
wind_speed     14.371660
dtype: float64

### Linear Interpolation process for filling small gaps

In [37]:
df_hourly_full = df_hourly_full.sort_values(['sensorId', 'timestamp'])

cols_to_fix = ['temperature', 'humidity', 'pressure', 'wind_speed']

for col in cols_to_fix:

    df_hourly_full[col] = df_hourly_full.groupby('sensorId')[col].transform(
        lambda x: x.interpolate(method='linear', limit=3)
    )

In [38]:
percent_missing = (df_hourly_full.isnull().sum() * 100) / len(df_hourly_full)
print(percent_missing)

timestamp       0.000000
sensorId        0.000000
humidity       48.904217
pm10           31.073699
pm25           31.290165
pressure       59.422422
temperature    47.828317
wind_speed     13.953488
dtype: float64

In [39]:
len(df_hourly_full)

1508784

In [40]:
sensor_stats = df_hourly_full.groupby('sensorId')[['humidity', 'pressure', 'pm10','pm25','temperature']].apply(lambda x: x.isnull().mean())
print(sensor_stats[sensor_stats['humidity'] > 0.5])

                                      humidity  pressure      pm10      pm25  \
sensorId
1000                                  1.000000  1.000000  0.266758  0.368217
1001                                  1.000000  1.000000  0.690834  0.684850
1002                                  1.000000  1.000000  0.684166  0.681259
1003                                  1.000000  1.000000  0.278272  0.369357
1004                                  1.000000  1.000000  0.683197  0.678238
200cdb67-8dc5-4dcf-ac62-748db636e04e  1.000000  1.000000  0.004104  0.004104
3f9a8bfd-d15a-4b2a-8516-81260c25416e  0.646774  0.624658  0.825068  0.825068
59c15198-7ba8-45af-aac4-5b3d1560fd81  1.000000  1.000000  0.029469  0.029469
6380c7cc-df23-4512-ad10-f2b363000579  1.000000  1.000000  0.007410  0.007410
7903d37a-a533-49ed-9348-93cd396fe034  0.818456  0.815948  0.832136  0.832136
8defa36a-62ca-448a-9ffb-5a2848c2dfa0  0.526619  0.525878  0.026334  0.026334
a6f0822c-acc2-4245-b3a9-2151aa9e3299  0.512996  0.503363  0.702519  0.702519
b80e5cd2-76cb-40bf-b784-2a0a312e6264  0.538475  1.000000  0.547424  0.547424
bb32cbe7-0391-463c-9716-d37930d1f567  0.822731  0.822731  0.888224  0.888224
e6658b42-ee46-4f48-ba49-7ab6eaa993c5  0.845645  0.845645  0.846101  0.846101
sensor_dev_10699_244                  0.693513  1.000000  0.689637  0.689637
sensor_dev_34617_228                  0.546512  1.000000  0.376539  0.376539
sensor_dev_60237_141                  1.000000  1.000000  0.813098  0.813098
sensor_dev_61184_835                  1.000000  1.000000  0.013110  0.013110
sensor_dev_77790_464                  1.000000  1.000000  0.198586  0.198586
sensor_dev_77849_684                  1.000000  1.000000  0.989854  0.989854
sensor_dev_78019_564                  1.000000  1.000000  0.685591  0.685591
sensor_dev_78110_618                  1.000000  1.000000  0.977314  0.977314
sensor_dev_78164_619                  1.000000  1.000000  0.016758  0.016758
sensor_dev_78188_661                  1.000000  1.000000  0.903158  0.903158
sensor_dev_78432_137                  1.000000  1.000000  0.239284  0.239284
sensor_dev_78456_119                  1.000000  1.000000  0.993103  0.993103
sensor_dev_78464_424                  1.000000  1.000000  0.819311  0.819311
sensor_dev_78662_610                  1.000000  1.000000  0.595816  0.595816
sensor_dev_79190_458                  1.000000  1.000000  0.132695  0.132695
sensor_dev_79765_769                  1.000000  1.000000  0.638509  0.638509
sensor_dev_80193_378                  1.000000  1.000000  0.109097  0.109097
sensor_dev_80195_553                  1.000000  1.000000  0.018867  0.018867
sensor_dev_81855_345                  1.000000  1.000000  0.066404  0.066404
sensor_dev_82681_781                  1.000000  1.000000  0.213862  0.213862
sensor_dev_82685_644                  1.000000  1.000000  0.335385  0.335385
sensor_dev_82703_642                  1.000000  1.000000  0.064979  0.064979
sensor_dev_82724_611                  1.000000  1.000000  0.393240  0.393240
sensor_dev_8550_72                    1.000000  1.000000  0.824726  0.824726

                                      temperature
sensorId
1000                                     1.000000
1001                                     1.000000
1002                                     1.000000
1003                                     1.000000
1004                                     1.000000
200cdb67-8dc5-4dcf-ac62-748db636e04e     1.000000
3f9a8bfd-d15a-4b2a-8516-81260c25416e     0.624658
59c15198-7ba8-45af-aac4-5b3d1560fd81     1.000000
6380c7cc-df23-4512-ad10-f2b363000579     1.000000
7903d37a-a533-49ed-9348-93cd396fe034     0.815948
8defa36a-62ca-448a-9ffb-5a2848c2dfa0     0.525878
a6f0822c-acc2-4245-b3a9-2151aa9e3299     0.503363
b80e5cd2-76cb-40bf-b784-2a0a312e6264     0.538475
bb32cbe7-0391-463c-9716-d37930d1f567     0.822731
e6658b42-ee46-4f48-ba49-7ab6eaa993c5     0.845645
sensor_dev_10699_244                     0.687472
sensor_dev_34617_228                     0.369585
sensor_dev_60237_141                     1.000000
sensor_dev_61184_835                     1.000000
sensor_dev_77790_464                     1.000000
sensor_dev_77849_684                     1.000000
sensor_dev_78019_564                     1.000000
sensor_dev_78110_618                     1.000000
sensor_dev_78164_619                     1.000000
sensor_dev_78188_661                     1.000000
sensor_dev_78432_137                     1.000000
sensor_dev_78456_119                     1.000000
sensor_dev_78464_424                     1.000000
sensor_dev_78662_610                     1.000000
sensor_dev_79190_458                     1.000000
sensor_dev_79765_769                     1.000000
sensor_dev_80193_378                     1.000000
sensor_dev_80195_553                     1.000000
sensor_dev_81855_345                     1.000000
sensor_dev_82681_781                     1.000000
sensor_dev_82685_644                     1.000000
sensor_dev_82703_642                     1.000000
sensor_dev_82724_611                     1.000000
sensor_dev_8550_72                       1.000000

### Remove again the sensors that have high percentage of missing values for pm10 and pm25

In [41]:
sensors_to_keep = sensor_stats[(sensor_stats['pm10'] <= 0.8) & (sensor_stats['pm25'] <= 0.8)].index

df_hourly_full = df_hourly_full[df_hourly_full['sensorId'].isin(sensors_to_keep)]

In [42]:
df_hourly_full['sensorId'].value_counts()

sensorId
007f2b03-94e6-47b3-9e3e-44273354acd5    17544
sensor_dev_62788_603                    17544
sensor_dev_39548_976                    17544
sensor_dev_34617_228                    17544
sensor_dev_20701_157                    17544
                                        ...
5de2a490-05f1-4f33-927e-a7e6f5664b72    17544
59c15198-7ba8-45af-aac4-5b3d1560fd81    17544
52546b6e-77bf-40f8-b0e5-6e54d7947e9f    17544
3e2465de-c2c2-4473-9c62-7113265debd9    17544
sensor_dev_84941_208                    17544
Name: count, Length: 75, dtype: int64

In [43]:
percent_missing = (df_hourly_full.isnull().sum() * 100) / len(df_hourly_full)
print(percent_missing)

timestamp       0.000000
sensorId        0.000000
humidity       42.565359
pm10           22.681715
pm25           22.929929
pressure       54.659067
temperature    41.364493
wind_speed     16.000000
dtype: float64

### Fill missing weather with the average of all other sensors in Skopje for that specific hour

In [44]:
weather_cols = ['humidity', 'pressure', 'temperature', 'wind_speed']

df_hourly_full[weather_cols] = df_hourly_full[weather_cols].fillna(
    df_hourly_full.groupby('timestamp')[weather_cols].transform('mean')
)

In [45]:
percent_missing = (df_hourly_full.isnull().sum() * 100) / len(df_hourly_full)
print(percent_missing)

timestamp       0.000000
sensorId        0.000000
humidity        0.039900
pm10           22.681715
pm25           22.929929
pressure        0.039900
temperature     0.039900
wind_speed      0.000000
dtype: float64

In [46]:
df_hourly_full.head(20)

,timestamp,sensorId,humidity,pm10,pm25,pressure,temperature,wind_speed
0,2023-12-01 00:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,75.916667,NaN,NaN,981.158046,6.359756,7.391761
1,2023-12-01 01:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.331140,NaN,NaN,981.250000,6.315041,7.238935
2,2023-12-01 02:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.574786,NaN,NaN,981.250000,6.236111,7.570863
3,2023-12-01 03:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.818376,NaN,NaN,981.133333,6.378968,7.031864
4,2023-12-01 04:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.098291,NaN,NaN,981.044444,6.593254,6.751236
5,2023-12-01 05:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.581197,NaN,NaN,981.000000,6.569444,7.115020
6,2023-12-01 06:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.589744,NaN,NaN,981.241667,6.738095,6.709050
7,2023-12-01 07:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,78.341667,NaN,NaN,981.620968,7.269380,8.655718
8,2023-12-01 08:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,78.126984,NaN,NaN,982.054688,8.214015,9.931705
9,2023-12-01 09:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,70.751938,NaN,NaN,981.532828,11.372222,7.709606
10,2023-12-01 10:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,70.176357,NaN,NaN,980.901515,12.309259,10.910098
11,2023-12-01 11:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,68.090909,NaN,NaN,980.404040,13.640741,11.035393
12,2023-12-01 12:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,67.806818,NaN,NaN,979.472222,14.096296,10.823806
13,2023-12-01 13:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,69.845520,NaN,NaN,979.075758,13.503704,10.558935
14,2023-12-01 14:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,72.961874,NaN,NaN,979.257576,12.809259,7.403177
15,2023-12-01 15:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,75.653986,NaN,NaN,979.169192,12.085185,8.315140
16,2023-12-01 16:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.146825,NaN,NaN,979.130208,11.462121,7.601759
17,2023-12-01 17:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,78.102324,NaN,NaN,979.281994,10.900162,8.415877
18,2023-12-01 18:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,78.761905,NaN,NaN,979.493867,10.528836,6.861490
19,2023-12-01 19:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,79.317872,NaN,NaN,979.318404,10.058567,7.908835

In [47]:
df_hourly_full.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed
count,1.315275e+06,1.017354e+06,1.014088e+06,1.315275e+06,1.315275e+06,1.315800e+06
mean,5.566136e+01,2.492260e+01,1.387223e+01,9.828889e+02,1.720202e+01,4.959989e+00
std,1.782989e+01,4.210747e+01,2.289562e+01,9.442534e+00,9.319345e+00,3.199850e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,9.220000e+02,-5.800000e+01,0.000000e+00
25%,4.185390e+01,6.000000e+00,3.250000e+00,9.787500e+02,9.703252e+00,2.811690e+00
50%,5.575000e+01,1.200000e+01,6.750000e+00,9.830000e+02,1.641870e+01,4.510787e+00
75%,6.950000e+01,2.766667e+01,1.533333e+01,9.880000e+02,2.432623e+01,6.432324e+00
max,9.900000e+01,1.873750e+03,9.980000e+02,1.195000e+03,5.950000e+01,4.566469e+01

In [48]:
len(df_hourly_full)

1315800

In [49]:
df_hourly_full['sensorId'].value_counts()

sensorId
007f2b03-94e6-47b3-9e3e-44273354acd5    17544
sensor_dev_62788_603                    17544
sensor_dev_39548_976                    17544
sensor_dev_34617_228                    17544
sensor_dev_20701_157                    17544
                                        ...
5de2a490-05f1-4f33-927e-a7e6f5664b72    17544
59c15198-7ba8-45af-aac4-5b3d1560fd81    17544
52546b6e-77bf-40f8-b0e5-6e54d7947e9f    17544
3e2465de-c2c2-4473-9c62-7113265debd9    17544
sensor_dev_84941_208                    17544
Name: count, Length: 75, dtype: int64

### Load the neighborhood matrix of distances

In [50]:
base_dir = os.getcwd()

csv_path = os.path.join(base_dir, "..", "data", "neighbors_data", "skopje_neighbors.csv")
neighbourhood_matrix = pd.read_csv(csv_path)
neighbourhood_matrix

,sensor_id,neighbor_id,distance_km
0,sensor_dev_60237_141,sensor_dev_10699_244,6.937128
1,sensor_dev_10699_244,sensor_dev_60237_141,6.937128
2,sensor_dev_60237_141,fefbf9e0-ff44-4b85-b968-2af046c4f4dc,3.446379
3,fefbf9e0-ff44-4b85-b968-2af046c4f4dc,sensor_dev_60237_141,3.446379
4,sensor_dev_60237_141,sensor_dev_81984_843,7.062097
...,...,...,...
34405,680b0098-7c4d-44cf-acb1-dc4031e93d34,sensor_dev_51158_685,12.425126
34406,sensor_dev_51158_685,8c5db228-0f2c-4bb5-9141-ac8b5e7f6c8a,2.571231
34407,8c5db228-0f2c-4bb5-9141-ac8b5e7f6c8a,sensor_dev_51158_685,2.571231
34408,680b0098-7c4d-44cf-acb1-dc4031e93d34,8c5db228-0f2c-4bb5-9141-ac8b5e7f6c8a,13.408616
34409,8c5db228-0f2c-4bb5-9141-ac8b5e7f6c8a,680b0098-7c4d-44cf-acb1-dc4031e93d34,13.408616

In [51]:
valid_sensors = df_hourly_full['sensorId'].unique()

In [52]:
neighbors_df_clean = neighbourhood_matrix[
    (neighbourhood_matrix['sensor_id'].isin(valid_sensors)) &
    (neighbourhood_matrix['neighbor_id'].isin(valid_sensors))
].copy()

### Function for appending neighborhood features in each sensor

In [53]:
def append_neighbors(df_hourly, neighbors_df, weather_cols, k_search=20, k_keep=5):
    # 1. Standardize the neighbor list
    # Ensure we only take the top K based on distance
    neighbors_topk = (
        neighbors_df.sort_values(["sensor_id", "distance_km"])
        .groupby("sensor_id")
        .head(k_search)
        .copy()
    )

    # Track original distance rank
    neighbors_topk['dist_rank'] = neighbors_topk.groupby("sensor_id").cumcount() + 1

    # 2. Merge with main data
    # We use 'neighbor_id' from the matrix to match 'sensorId' in the hourly data
    neighbor_values = neighbors_topk.merge(
        df_hourly[['sensorId', 'timestamp'] + weather_cols],
        left_on='neighbor_id',
        right_on='sensorId',
        how='inner'
    )

    # 3. Filter for availability
    # The 'sensor_id' here is the ORIGINAL sensor we are finding neighbors for
    available_topk = (
        neighbor_values.sort_values(['sensor_id', 'timestamp', 'dist_rank'])
        .groupby(['sensor_id', 'timestamp'])
        .head(k_keep)
        .copy()
    )

    # Create the 1, 2, 3 rank for the wide-format columns
    available_topk['final_rank'] = available_topk.groupby(['sensor_id', 'timestamp']).cumcount() + 1

    # 4. Pivot to wide format
    pivot_df = available_topk.pivot(
        index=['sensor_id', 'timestamp'],
        columns='final_rank',
        values=weather_cols
    )

    # Clean up column names: neighbor1_temp, neighbor2_temp, etc.
    if isinstance(pivot_df.columns, pd.MultiIndex):
        pivot_df.columns = [f"neighbor{rank}_{col}" for col, rank in pivot_df.columns]
    else:
        # Handle case with only one weather column
        pivot_df.columns = [f"neighbor{i}_{weather_cols[0]}" for i in pivot_df.columns]

    pivot_df = pivot_df.reset_index()

    # 5. Final Join back to original data
    df_result = df_hourly.merge(
        pivot_df,
        left_on=['sensorId', 'timestamp'],
        right_on=['sensor_id', 'timestamp'],
        how='left'
    ).drop(columns=['sensor_id'])

    return df_result

In [54]:
weather_cols

['humidity', 'pressure', 'temperature', 'wind_speed']

In [55]:
df_final = append_neighbors(df_hourly_full,neighbors_df_clean, weather_cols)

In [56]:
df_final

,timestamp,sensorId,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,...,neighbor1_temperature,neighbor2_temperature,neighbor3_temperature,neighbor4_temperature,neighbor5_temperature,neighbor1_wind_speed,neighbor2_wind_speed,neighbor3_wind_speed,neighbor4_wind_speed,neighbor5_wind_speed
0,2023-12-01 00:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,75.916667,NaN,NaN,981.158046,6.359756,7.391761,74.00,75.916667,...,5.00,6.359756,4.000000,6.359756,4.000000,11.246759,11.246759,11.246759,7.391761,11.246759
1,2023-12-01 01:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.331140,NaN,NaN,981.250000,6.315041,7.238935,73.75,76.331140,...,5.00,6.315041,3.750000,6.315041,3.750000,12.313894,12.313894,12.313894,7.238935,12.313894
2,2023-12-01 02:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.574786,NaN,NaN,981.250000,6.236111,7.570863,74.50,76.574786,...,5.00,6.236111,3.750000,6.236111,3.750000,10.972620,10.972620,10.972620,7.570863,10.972620
3,2023-12-01 03:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.818376,NaN,NaN,981.133333,6.378968,7.031864,75.75,76.818376,...,5.75,6.378968,4.000000,6.378968,4.000000,10.233123,10.233123,10.233123,7.031864,10.233123
4,2023-12-01 04:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.098291,NaN,NaN,981.044444,6.593254,6.751236,73.75,77.098291,...,6.00,6.593254,4.000000,6.593254,5.000000,10.739832,10.739832,10.739832,6.751236,10.739832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1315795,2025-11-30 19:00:00+00:00,sensor_dev_84941_208,83.000000,NaN,NaN,981.371212,7.000000,0.663094,80.75,74.500000,...,7.00,7.000000,8.484127,8.484127,8.484127,0.663094,0.663094,0.663094,0.254558,0.254558
1315796,2025-11-30 20:00:00+00:00,sensor_dev_84941_208,85.500000,NaN,NaN,981.377604,6.750000,1.077217,82.25,78.500000,...,7.00,7.000000,8.317073,8.317073,8.317073,1.077217,1.077217,1.077217,0.360000,0.360000
1315797,2025-11-30 21:00:00+00:00,sensor_dev_84941_208,88.000000,NaN,NaN,981.609375,6.000000,0.762645,83.00,81.000000,...,6.00,6.000000,8.040650,8.040650,8.040650,0.762645,0.762645,0.762645,0.254558,0.254558
1315798,2025-11-30 22:00:00+00:00,sensor_dev_84941_208,89.500000,NaN,NaN,981.594086,6.000000,0.961617,84.25,81.000000,...,6.00,6.000000,8.077083,8.077083,8.077083,0.961617,0.961617,0.961617,0.648999,0.648999
1315799,2025-11-30 23:00:00+00:00,sensor_dev_84941_208,89.000000,NaN,NaN,981.567204,6.000000,0.839303,83.00,82.000000,...,6.00,6.000000,8.062500,8.062500,8.062500,0.839303,0.839303,0.839303,0.569210,0.569210

In [57]:
percent_missing = (df_final.isnull().sum() * 100) / len(df_final)
print(percent_missing)

timestamp                 0.000000
sensorId                  0.000000
humidity                  0.039900
pm10                     22.681715
pm25                     22.929929
pressure                  0.039900
temperature               0.039900
wind_speed                0.000000
neighbor1_humidity        0.039900
neighbor2_humidity        0.039900
neighbor3_humidity        0.039900
neighbor4_humidity        0.039900
neighbor5_humidity        0.039900
neighbor1_pressure        0.039900
neighbor2_pressure        0.039900
neighbor3_pressure        0.039900
neighbor4_pressure        0.039900
neighbor5_pressure        0.039900
neighbor1_temperature     0.039900
neighbor2_temperature     0.039900
neighbor3_temperature     0.039900
neighbor4_temperature     0.039900
neighbor5_temperature     0.039900
neighbor1_wind_speed      0.000000
neighbor2_wind_speed      0.000000
neighbor3_wind_speed      0.000000
neighbor4_wind_speed      0.000000
neighbor5_wind_speed      0.000000
dtype: float64

In [58]:
len(df_final)

1315800

In [59]:
df_final['sensorId'].value_counts()

sensorId
007f2b03-94e6-47b3-9e3e-44273354acd5    17544
sensor_dev_62788_603                    17544
sensor_dev_39548_976                    17544
sensor_dev_34617_228                    17544
sensor_dev_20701_157                    17544
                                        ...
5de2a490-05f1-4f33-927e-a7e6f5664b72    17544
59c15198-7ba8-45af-aac4-5b3d1560fd81    17544
52546b6e-77bf-40f8-b0e5-6e54d7947e9f    17544
3e2465de-c2c2-4473-9c62-7113265debd9    17544
sensor_dev_84941_208                    17544
Name: count, Length: 75, dtype: int64

In [60]:
df_final.describe()

,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,neighbor3_humidity,neighbor4_humidity,...,neighbor1_temperature,neighbor2_temperature,neighbor3_temperature,neighbor4_temperature,neighbor5_temperature,neighbor1_wind_speed,neighbor2_wind_speed,neighbor3_wind_speed,neighbor4_wind_speed,neighbor5_wind_speed
count,1.315275e+06,1.017354e+06,1.014088e+06,1.315275e+06,1.315275e+06,1.315800e+06,1.315275e+06,1.315275e+06,1.315275e+06,1.315275e+06,...,1.315275e+06,1.315275e+06,1.315275e+06,1.315275e+06,1.315275e+06,1.315800e+06,1.315800e+06,1.315800e+06,1.315800e+06,1.315800e+06
mean,5.566136e+01,2.492260e+01,1.387223e+01,9.828889e+02,1.720202e+01,4.959989e+00,5.530974e+01,5.483988e+01,5.550372e+01,5.499049e+01,...,1.730046e+01,1.737855e+01,1.724795e+01,1.742116e+01,1.762854e+01,4.835616e+00,4.860076e+00,4.854149e+00,4.848925e+00,4.847676e+00
std,1.782989e+01,4.210747e+01,2.289562e+01,9.442534e+00,9.319345e+00,3.199850e+00,1.748186e+01,1.797581e+01,1.810821e+01,1.741685e+01,...,9.297880e+00,9.299696e+00,9.369366e+00,9.257707e+00,9.154232e+00,2.940298e+00,2.905205e+00,2.851479e+00,2.876215e+00,2.877265e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,9.220000e+02,-5.800000e+01,0.000000e+00,0.000000e+00,4.500000e+00,0.000000e+00,0.000000e+00,...,-5.800000e+01,-5.800000e+01,-1.300000e+01,-5.800000e+01,-7.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,4.185390e+01,6.000000e+00,3.250000e+00,9.787500e+02,9.703252e+00,2.811690e+00,4.175000e+01,4.100000e+01,4.141880e+01,4.150000e+01,...,9.786458e+00,1.000000e+01,9.650362e+00,1.000000e+01,1.016497e+01,2.747581e+00,2.811690e+00,2.863049e+00,2.833955e+00,2.817445e+00
50%,5.575000e+01,1.200000e+01,6.750000e+00,9.830000e+02,1.641870e+01,4.510787e+00,5.536111e+01,5.450000e+01,5.537326e+01,5.525000e+01,...,1.650000e+01,1.668617e+01,1.650000e+01,1.667963e+01,1.698374e+01,4.452954e+00,4.503598e+00,4.510787e+00,4.503598e+00,4.503598e+00
75%,6.950000e+01,2.766667e+01,1.533333e+01,9.880000e+02,2.432623e+01,6.432324e+00,6.900000e+01,6.850000e+01,6.964757e+01,6.867029e+01,...,2.450000e+01,2.450000e+01,2.450000e+01,2.453125e+01,2.475000e+01,6.369014e+00,6.375926e+00,6.342817e+00,6.341009e+00,6.359372e+00
max,9.900000e+01,1.873750e+03,9.980000e+02,1.195000e+03,5.950000e+01,4.566469e+01,9.900000e+01,9.900000e+01,9.900000e+01,9.900000e+01,...,5.950000e+01,5.733333e+01,5.950000e+01,5.950000e+01,5.733333e+01,3.462369e+01,3.462369e+01,2.926869e+01,2.926869e+01,2.926869e+01

### Function for extracting time features

In [61]:
def extract_time_features(df, timestamp_col='timestamp'):
    
    month = df[timestamp_col].dt.month

    df['season'] = np.select(
        [
            month.isin([12, 1, 2]),
            month.isin([3, 4, 5]),
            month.isin([6, 7, 8]),
            month.isin([9, 10, 11])
        ],
        [
            'winter',
            'spring',
            'summer',
            'autumn'
        ]
    )

    df['hour_sin'] = np.sin(2 * np.pi * df[timestamp_col].dt.hour / 24)
    df['hour_cos'] = np.cos(2 * np.pi * df[timestamp_col].dt.hour / 24)


    df['month_sin'] = np.sin(2 * np.pi * (df[timestamp_col].dt.month - 1) / 12)
    df['month_cos'] = np.cos(2 * np.pi * (df[timestamp_col].dt.month - 1) / 12)
    
    df['day_sin'] = np.sin(2 * np.pi * df[timestamp_col].dt.dayofweek / 7)
    df['day_cos'] = np.cos(2 * np.pi * df[timestamp_col].dt.dayofweek / 7)


    df['is_weekend'] = df[timestamp_col].dt.dayofweek.isin([5, 6]).astype(int)

    df['is_heating_season'] = df[timestamp_col].dt.month.isin([11, 12, 1, 2, 3]).astype(int)

    return df

In [62]:
df_final = extract_time_features(df_final)

In [63]:
df_final.head(20)

,timestamp,sensorId,humidity,pm10,pm25,pressure,temperature,wind_speed,neighbor1_humidity,neighbor2_humidity,...,neighbor5_wind_speed,season,hour_sin,hour_cos,month_sin,month_cos,day_sin,day_cos,is_weekend,is_heating_season
0,2023-12-01 00:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,75.916667,NaN,NaN,981.158046,6.359756,7.391761,74.000000,75.916667,...,11.246759,winter,0.000000e+00,1.000000e+00,-0.5,0.866025,-0.433884,-0.900969,0,1
1,2023-12-01 01:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.331140,NaN,NaN,981.250000,6.315041,7.238935,73.750000,76.331140,...,12.313894,winter,2.588190e-01,9.659258e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
2,2023-12-01 02:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.574786,NaN,NaN,981.250000,6.236111,7.570863,74.500000,76.574786,...,10.972620,winter,5.000000e-01,8.660254e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
3,2023-12-01 03:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,76.818376,NaN,NaN,981.133333,6.378968,7.031864,75.750000,76.818376,...,10.233123,winter,7.071068e-01,7.071068e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
4,2023-12-01 04:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.098291,NaN,NaN,981.044444,6.593254,6.751236,73.750000,77.098291,...,10.739832,winter,8.660254e-01,5.000000e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
5,2023-12-01 05:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.581197,NaN,NaN,981.000000,6.569444,7.115020,75.500000,77.581197,...,11.019764,winter,9.659258e-01,2.588190e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
6,2023-12-01 06:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.589744,NaN,NaN,981.241667,6.738095,6.709050,75.000000,77.589744,...,10.296251,winter,1.000000e+00,6.123234e-17,-0.5,0.866025,-0.433884,-0.900969,0,1
7,2023-12-01 07:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,78.341667,NaN,NaN,981.620968,7.269380,8.655718,76.000000,78.341667,...,11.246759,winter,9.659258e-01,-2.588190e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
8,2023-12-01 08:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,78.126984,NaN,NaN,982.054688,8.214015,9.931705,76.250000,78.126984,...,11.269782,winter,8.660254e-01,-5.000000e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
9,2023-12-01 09:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,70.751938,NaN,NaN,981.532828,11.372222,7.709606,71.000000,70.751938,...,9.585739,winter,7.071068e-01,-7.071068e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
10,2023-12-01 10:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,70.176357,NaN,NaN,980.901515,12.309259,10.910098,68.000000,70.176357,...,12.984975,winter,5.000000e-01,-8.660254e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
11,2023-12-01 11:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,68.090909,NaN,NaN,980.404040,13.640741,11.035393,65.750000,68.090909,...,12.819235,winter,2.588190e-01,-9.659258e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
12,2023-12-01 12:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,67.806818,NaN,NaN,979.472222,14.096296,10.823806,65.500000,67.806818,...,12.101570,winter,1.224647e-16,-1.000000e+00,-0.5,0.866025,-0.433884,-0.900969,0,1
13,2023-12-01 13:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,69.845520,NaN,NaN,979.075758,13.503704,10.558935,66.750000,69.845520,...,12.889810,winter,-2.588190e-01,-9.659258e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
14,2023-12-01 14:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,72.961874,NaN,NaN,979.257576,12.809259,7.403177,69.250000,72.961874,...,12.229406,winter,-5.000000e-01,-8.660254e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
15,2023-12-01 15:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,75.653986,NaN,NaN,979.169192,12.085185,8.315140,71.666667,75.653986,...,9.220499,winter,-7.071068e-01,-7.071068e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
16,2023-12-01 16:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,77.146825,NaN,NaN,979.130208,11.462121,7.601759,76.250000,77.146825,...,7.244860,winter,-8.660254e-01,-5.000000e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
17,2023-12-01 17:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,78.102324,NaN,NaN,979.281994,10.900162,8.415877,76.500000,78.102324,...,11.720751,winter,-9.659258e-01,-2.588190e-01,-0.5,0.866025,-0.433884,-0.900969,0,1
18,2023-12-01 18:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,78.761905,NaN,NaN,979.493867,10.528836,6.861490,75.500000,78.761905,...,9.565437,winter,-1.000000e+00,-1.836970e-16,-0.5,0.866025,-0.433884,-0.900969,0,1
19,2023-12-01 19:00:00+00:00,007f2b03-94e6-47b3-9e3e-44273354acd5,79.317872,NaN,NaN,979.318404,10.058567,7.908835,77.250000,79.317872,...,10.002560,winter,-9.659258e-01,2.588190e-01,-0.5,0.866025,-0.433884,-0.900969,0,1

In [64]:
df_final.isnull().sum()

timestamp                     0
sensorId                      0
humidity                    525
pm10                     298446
pm25                     301712
pressure                    525
temperature                 525
wind_speed                    0
neighbor1_humidity          525
neighbor2_humidity          525
neighbor3_humidity          525
neighbor4_humidity          525
neighbor5_humidity          525
neighbor1_pressure          525
neighbor2_pressure          525
neighbor3_pressure          525
neighbor4_pressure          525
neighbor5_pressure          525
neighbor1_temperature       525
neighbor2_temperature       525
neighbor3_temperature       525
neighbor4_temperature       525
neighbor5_temperature       525
neighbor1_wind_speed          0
neighbor2_wind_speed          0
neighbor3_wind_speed          0
neighbor4_wind_speed          0
neighbor5_wind_speed          0
season                        0
hour_sin                      0
hour_cos                      0
month_sin                     0
month_cos                     0
day_sin                       0
day_cos                       0
is_weekend                    0
is_heating_season             0
dtype: int64

In [65]:
df_final.to_csv("../data/training/skopje_final_data.csv", index=False)